### ISSUE TITLE
Slow Pererformance in rocksdb::DB::Put method

### ISSUE THREAD

**Issue by evgenisqream** [facebook/rocksdb#10014]
Dear RocksDB engineers. My company uses  rocksdb database for storing kind of meta data. It was found that sometimes the method rocksdb::DB::Put may take several seconds.   It happens randomly when during approaching to Put method with the same key. I tried to change paranoid_checks to false, but the issue still happens. Please assist. Thanks.

**Comment by jay-zhuang** [comment]
You can check the log see if the write is stalled: https://github.com/facebook/rocksdb/wiki/Write-Stalls
There're different reasons for the write stall, based on that, you can increase the compaction throughput if compaction is unable to catchup, etc.

**Comment by yinciki** [comment]
> You can check the log see if the write is stalled: https://github.com/facebook/rocksdb/wiki/Write-Stalls There're different reasons for the write stall, based on that, you can increase the compaction throughput if compaction is unable to catchup, etc.

I met similar problems when I constantly write kvs to rocksdb, when the db became larger, the Put procedure slowed down evidently. I checked the LOG and found no stalled related message which mentioned in the wiki. So it might not be of any kind of write stalls ? Any suggestions ?
