### ISSUE TITLE
PHP, non-EOL versions support

### ISSUE THREAD

**Issue by cayolblake** [facebook/rocksdb#10023]
Hello,

It listed here https://github.com/facebook/rocksdb/blob/main/LANGUAGE-BINDINGS.md that PHP support is through https://github.com/Photonios/rocksdb-php which is 7 years old with no updates or compatibility with any usable non-EOL PHP version.

Any better option? Should the LANGUAGE-BINDINGS.md doc be updated with up to date info?

**Comment by ajkr** [comment]
I do not know of a better option. Feel free to update LANGUAGE-BINDINGS.md with your findings and send a PR, even if it's just to delete/recommend against the option it currently mentions.
