### ISSUE TITLE
install-headers bug

### ISSUE THREAD

**Issue by bjne** [facebook/rocksdb#1005]
https://github.com/facebook/rocksdb/blob/master/Makefile#L1065

`*.h => "*.h"`

```
    for header in `find "include/rocksdb" -type f -name *.h`; do \
        install -C -m 644 $$header $(INSTALL_PATH)/$$header; \
    done
```

**Comment by adamretter** [comment]
@bjne I am not a bash expert, however I think you are saying the problem is that the expansion of `*.h` would be done by `bash` and not `find`. I remember in the past being told that one should use `\*.h`, how does that compare to your suggestion of `"*.h"`?

**Comment by bjne** [comment]
That is correct, shell could be expanding unescaped *

I think either is fine, needs testing tho.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
