### ISSUE TITLE
Reading User defined Timestamp

### ISSUE THREAD

**Issue by ronag** [facebook/rocksdb#10064]
The UDT feature is great. However, I'm missing the possibility to retrieve the UDT, i.e. when I do a get I would like to know what timestamp the retrieved value has.

**Comment by riversand963** [comment]
For point lookup, the following allows returning the timestamps
```
DB::Get(ReadOptions, const Slice& key, std::string* value, std::string* timestamp);
DB::MultiGet(ReadOptions, ..., std::vector<std::string>* timestamps);
```
For range scan, you can access the timestamps via `Iterator::timestamp()`.
