### ISSUE TITLE
What is the problem with using "use_mmap_reads" in WinRandomAccessFile

### ISSUE THREAD

**Issue by shpala** [facebook/rocksdb#1007]
There is an assertion check in the constructor 
WinRandomAccessFile():
 assert(!options.use_mmap_reads);

**Comment by yuslepukhin** [comment]
That's because this file does not memory mapping. The assertion is to prevent this file from being instantiated on accident. NewRandomAccessFile() should instantiate a different class that does memory mapping.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
