### ISSUE TITLE
open error: Invalid argument: Compression type Snappy is not linked with the binary.

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10071]
**I can compile and run"db_bench" locally in my cloud service provider,** but when I compile the "db_bench" remotely in clion by toolchain, appears problem "open error: Invalid argument: Compression type Snappy is not linked with the binary."!
How to solve it? I guess bashrc or bash_profile settings.
![image](https://user-images.githubusercontent.com/43542395/170830739-adb70c15-f7fc-4d2a-ab7f-42576694dd11.png)
![image](https://user-images.githubusercontent.com/43542395/170830771-2fe16b6b-0448-40ae-a062-5000ac7b6663.png)
![image](https://user-images.githubusercontent.com/43542395/170830781-df4c2a5e-9955-495e-b940-9e2f2fc3329a.png)

**Comment by jay-zhuang** [comment]
try add CMake options: `-DWITH_SNAPPY=1`
cmake doesn't link with compression by default, for more option, check
https://github.com/facebook/rocksdb/blob/4eb7b35f6d47f9a19a7f080d2ebbfdfb31430417/CMakeLists.txt#L67-L73

**Comment by HBSDLJZ** [comment]
thank you~~ you helped me solving this problem!
