### ISSUE TITLE
Some questions about manifest live files

### ISSUE THREAD

**Issue by LucienXian** [facebook/rocksdb#10074]
I'm trying to build rocksdb on S3, put related table files etc on S3. We are implementing a fork splitting feature that splits one rocksdb instance into two. This is a lazy split, that is, in the initial stage, the two new db instances will share the table files left by the original db instance. As the compaction progresses, the original old files are gradually deleted, and their respective table files are placed in the new directory. .
Our approach here is to first prohibit the deletion of table files after splitting, and then use additional threads to regularly scan the table files of the old db and compare the Current manifests of the two new dbs` (ManifestReader.GetLiveFiles gets the file lists NewA and NewB, and find all files in the old directory that are not in NewA and NewB)`, so as to select the real eliminated files.
I have a question, is there any hidden danger in this approach? For example, whether the selected to_deleted file may be referenced by a request or snapshot.

**Comment by ajkr** [comment]
It is an interesting design. I imagine RocksDB API does not support it well. For example, the LOCK file should prevent you from opening the same DB twice.

`GetLiveFiles()` should be enough to serve new queries including queries on snapshots. Ongoing requests (including iterators that were created earlier) may use files not returned by `GetLiveFiles()`. I don't think we expose files that are needed for ongoing queries only. If this property is 1 there should be no such files, at least: https://github.com/facebook/rocksdb/blob/84210c94895ff111dfca941ee37215232ed1ad79/include/rocksdb/db.h#L969-L973

I will close this as there's no specific issue/request in RocksDB to address, but please let us know if any arise.
