### ISSUE TITLE
make ldb error

### ISSUE THREAD

**Issue by YiteGu** [facebook/rocksdb#10072]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
run: make ldb

### Actual behavior
make failed:
rocksdb]$ make ldb
$DEBUG_LEVEL is 1
Makefile:166: Warning: Compiling in debug mode. Don't use the resulting binary in production
  CC       tools/ldb.o
  CC       tools/io_tracer_parser_tool.o
  CC       tools/ldb_cmd.o
  CC       tools/ldb_tool.o
  CC       tools/sst_dump_tool.o
  CC       utilities/blob_db/blob_dump_tool.o
  AR       librocksdb_tools_debug.a
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ar: 正在创建 librocksdb_tools_debug.a
  AR       librocksdb_debug.a
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ar: 正在创建 librocksdb_debug.a
  CCLD     ldb
./librocksdb_tools_debug.a(ldb_cmd.o)：在函数‘rocksdb::DBImpl* rocksdb::static_cast_with_check<rocksdb::DBImpl, rocksdb::DB>(rocksdb::DB*)’中：
/home/work/gyt/rocksdb/./util/cast_util.h:21：对‘typeinfo for rocksdb::DBImpl’ Undefined reference
/home/work/gyt/rocksdb/./util/cast_util.h:21：对‘typeinfo for rocksdb::DB’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o)：在函数‘rocksdb::ListFileRangeDeletesCommand::DoCommand()’中：
/home/work/gyt/rocksdb/tools/ldb_cmd.cc:3964：对‘rocksdb::SyncPoint::GetInstance()’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o)：在函数‘void rocksdb::SyncPoint::Process<51ul>(char const (&) [51ul], void*)’中：
/home/work/gyt/rocksdb/./test_util/sync_point.h:130：对‘rocksdb::SyncPoint::Process(rocksdb::Slice const&, void*)’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o)：在函数‘rocksdb::TtlIterator* rocksdb::static_cast_with_check<rocksdb::TtlIterator, rocksdb::Iterator>(rocksdb::Iterator*)’中：
/home/work/gyt/rocksdb/./util/cast_util.h:21：对‘typeinfo for rocksdb::Iterator’Undefined reference
/home/work/gyt/rocksdb/./util/cast_util.h:21：对‘typeinfo for rocksdb::Iterator’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o):(.rodata+0x990)：对‘typeinfo for rocksdb::log::Reader::Reporter’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o):(.rodata+0x9e0)：对‘typeinfo for rocksdb::WriteBatch::Handler’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o):(.rodata._ZTIN7rocksdb10ComparatorE[_ZTIN7rocksdb10ComparatorE]+0x10)：对‘typeinfo for rocksdb::Customizable’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o):(.rodata._ZTIN7rocksdb12StderrLoggerE[_ZTIN7rocksdb12StderrLoggerE]+0x10)：对‘typeinfo for rocksdb::Logger’Undefined reference
./librocksdb_tools_debug.a(ldb_cmd.o):(.rodata._ZTIN7rocksdb11TtlIteratorE[_ZTIN7rocksdb11TtlIteratorE]+0x10)：对‘typeinfo for rocksdb::Iterator’Undefined reference
collect2: error: ld returned 1 exit status
make: *** [ldb] 错误 1

### Steps to reproduce the behavior
rocksdb branch: 7.2.2
1. cd rocksdb
2. make ldb

**Comment by jay-zhuang** [comment]
Please be specific about the build environment, looks like it's your local build configuration issue.

**Comment by YiteGu** [comment]
my build environment is centos7

**Comment by YiteGu** [comment]
@jay-zhuang 
I found the root cause of problem
First, I build librocksdb.a with command `make static_lib`
and then, I want to build ldb with command `make ldb` in the same code repository. Because `make static_lib` with debug_level 0, but `make ldb` with debug_level 1, use rtti and no_rtti will cause to compile error in linker phase.

**Comment by MuChenMuXuan** [comment]
Referring to [link](https://github.com/facebook/rocksdb/blob/main/INSTALL.md), as stated in the documentation:

> Running make all will compile our static library, along with all our tools and unit tests. Our tools have a dependency on gflags 2.2.0 or a newer version. You will need to have gflags installed to execute make all. This will compile RocksDB in debug mode. Do not use binaries compiled by make all for production purposes.

When compiling rocksdb to use tools like ldb, it is necessary to compile it in debug mode. The specific steps are as follows:
1. cd /root/bin/rocksdb-8.9.1
2. make all
3. make install

At this point, executable files will be generated in the directory /root/bin/rocksdb-8.9.1:
```
/root/bin/rocksdb-8.9.1/ldb
/root/bin/rocksdb-8.9.1/sst_dump
```

It is essential to emphasize that if you compile using the command `make static_lib`, you will not be able to install the ldb tool because it does not build in debug mode.

Furthermore, it's important to note that debug versions should not be used in production environments as they can significantly impact performance.
