### ISSUE TITLE
FIFO compaction may fail to clean up files based on TTL.

### ISSUE THREAD

**Issue by liming30** [facebook/rocksdb#10133]
Hi, We are using RocksDB's FIFO Compaction policy for file cleanup, but we noticed a strange phenomenon that some files are kept for a long time and cannot be cleaned up according to TTL, but only according to max_size, which makes us keep too many files on disk.

### Expected behavior
The files are expected to be cleaned up according to the file's creation time and TTL.

### Actual behavior
FIFO Compaction always tells us nothing to do even though some of the files are out of time.

> FIFO compaction: nothing to do. Total size 16492556603, max size 107374182400

### Steps to reproduce the behavior
I found that `total_size -= f->compensated_file_size` is used in FIFO Compaction to calculate the remaining `total_size`, `total_size` is the sum of all the `file_size`, however `f->compensated_file_size`may be larger than the `file_size` of the file, which makes the final `total_size` calculation result underflow, so that `PickTTLCompaction` does not take effect.

The calculation logic of `compensated_file_size`:
>      if (file_meta->compensated_file_size == 0) {  
>         file_meta->compensated_file_size = file_meta->fd.GetFileSize();
>         if (file_meta->num_deletions * 2 >= file_meta->num_entries) {
>           file_meta->compensated_file_size +=
>               (file_meta->num_deletions * 2 - file_meta->num_entries) *
>               average_value_size * kDeletionWeightOnCompaction;
>         }
>     }

The calculation logic of `PickTTLCompaction`:

```
  if (current_time > mutable_cf_options.ttl) {
    for (auto ritr = level_files.rbegin(); ritr != level_files.rend(); ++ritr) {
      FileMetaData* f = *ritr;
      assert(f);
      if (f->fd.table_reader && f->fd.table_reader->GetTableProperties()) {
        uint64_t creation_time =
            f->fd.table_reader->GetTableProperties()->creation_time;
        if (creation_time == 0 ||
            creation_time >= (current_time - mutable_cf_options.ttl)) {
          break;
        }
      }
      total_size -= f->compensated_file_size; // may underflow
      inputs[0].files.push_back(f);
    }
  }

  // Return a nullptr and proceed to size-based FIFO compaction if:
  // 1. there are no files older than ttl OR
  // 2. there are a few files older than ttl, but deleting them will not bring
  //    the total size to be less than max_table_files_size threshold.
  if (inputs[0].files.empty() ||
      total_size >
          mutable_cf_options.compaction_options_fifo.max_table_files_size) { // Underflow will cause this condition to take effect.
    return nullptr;
  }
```

**Comment by liming30** [comment]
In the following Compaction process, we actually delete the file directly, so should we use `total_size -= f->fd.GetFileSize()` instead of `total_size -= f->compensated_file_size` here?

**Comment by liming30** [comment]
Hi, @ajkr , could you please take the time to help look at this issue?

**Comment by lhsoft** [comment]
@ajkr I think we need to avoid the underflow and I have sent the PR out

**Comment by ajkr** [comment]
> @ajkr I think we need to avoid the underflow and I have sent the PR out

Thank you!
