### ISSUE TITLE
OptimizeForPointLookup and iterators

### ISSUE THREAD

**Issue by ronag** [facebook/rocksdb#10135]
The comments for `OptimizeForPointLookup` currently says:

>   // Use this if you don't need to keep the data sorted, i.e. you'll never use
>   // an iterator, only Put() and Get() API calls

Which seems a bit absolute. I don't quite understand why you could not use iterators with these settings. Could we either extend the comments clarifying why or modify it to more clearly explain that iterators might be slower but stil work?

I don't see why any of the below options would "disable" iterators?

```cpp
ColumnFamilyOptions* ColumnFamilyOptions::OptimizeForPointLookup(
    uint64_t block_cache_size_mb) {
  BlockBasedTableOptions block_based_options;
  block_based_options.data_block_index_type =
      BlockBasedTableOptions::kDataBlockBinaryAndHash;
  block_based_options.data_block_hash_table_util_ratio = 0.75;
  block_based_options.filter_policy.reset(NewBloomFilterPolicy(10));
  block_based_options.block_cache =
      NewLRUCache(static_cast<size_t>(block_cache_size_mb * 1024 * 1024));
  table_factory.reset(new BlockBasedTableFactory(block_based_options));
  memtable_prefix_bloom_size_ratio = 0.02;
  memtable_whole_key_filtering = true;
  return this;
}
```

**Comment by ajkr** [comment]
It's called `OptimizeForPointLookup()` so it should reserve the right to make changes that prefer point lookups at the cost of harming iterators.

**Comment by ajkr** [comment]
I'd accept a PR though to weaken the language. "you'll never use an iterator" is a bit too strong. Perhaps it could say the "settings may be harmful to iterator operations."
