### ISSUE TITLE
`cache_index_and_filter_blocks` seem to not works, it leads `Get` operation slowdown

### ISSUE THREAD

**Issue by Wine93** [facebook/rocksdb#10149]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Hi, guys~ i use `cache_index_and_filter_blocks=true` in RocksDB `v6.28`, but it seems not works when i `Put` some keys, and the perf context shows that every time the `Get` operation read filter block from SST file, it leads `Get` operation slowdown.
one more thing that confuses me is the `LOG` shows the `FilterBlock` only occupied about `0.8%` of the block cache, and the `DataBlock` occupied about `94%`, but in my understanding, the default value of `high_pri_pool_ratio` is `0.5` for LRU cache, so the `DataBlock` will not take more than `50%`.
Can you answer this question for me or give me some advice, thank you very much.

* perf context for `Get` operation:
```
 block_cache_hit_count = 0
 block_read_count = 1
 block_read_byte = 10385482
 block_read_time = 5601882
 block_cache_index_hit_count = 0
 index_block_read_count = 0
 block_cache_filter_hit_count = 0
 filter_block_read_count = 1
 compression_dict_block_read_count = 0
 secondary_cache_hit_count = 0
 block_checksum_time = 11428512
 block_decompress_time = 0
 ...
 read_index_block_nanos = 0
 read_filter_block_nanos = 17074254
 ...
 bloom_memtable_hit_count = 1
 bloom_memtable_miss_count = 0
 bloom_sst_hit_count = 0
 bloom_sst_miss_count = 2
 ...
 bytes_read = 10385482
 bytes_written = 0
 open_nanos = 0
 allocate_nanos = 0
 write_nanos = 0
 read_nanos = 5593012
```

*   table_factory options:
```
  cache_index_and_filter_blocks: 1
  cache_index_and_filter_blocks_with_high_priority: 1
  pin_l0_filter_and_index_blocks_in_cache: 1
  pin_top_level_index_and_filter: 1
  index_type: 0
  data_block_index_type: 0
  index_shortening: 1
  data_block_hash_table_util_ratio: 0.750000
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x7f9bc5231c30
  block_cache_name: LRUCache
  block_cache_options:
    capacity : 536870912
    num_shard_bits : 6
    strict_capacity_limit : 0
    memory_allocator : None
    high_pri_pool_ratio: 0.500
```

* other important options:
```
memtable_prefix_bloom_ratio: 0.100000
memtable_whole_key_filtering: 0
prefix_extractor: rocksdb.FixedPrefix.10
enable_blob_files: true
enable_blob_garbage_collection: false
```
* LOG:
```
** Compaction Stats [ordered_column_familiy] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0   24.89 MB   0.5      0.0     0.0      0.0       0.1      0.1       0.0   1.0      0.4     40.1     31.19             30.84        11    2.836   1029K      0       0.0       1.1
  L6      1/0   71.99 MB   0.0      0.1     0.1      0.0       0.1      0.1       0.0   1.1     16.5     13.3      8.17              8.07         2    4.083     12M      0       0.0       0.0
 Sum      3/0   96.88 MB   0.0      0.1     0.1      0.0       0.2      0.2       0.0   1.1      3.8     34.6     39.36             38.91        13    3.027     13M      0       0.0       1.1
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0

...

Block cache LRUCache@0x7f9bc5231c30#6 capacity: 512.00 MB collections: 261 last_copies: 1 last_secs: 0.005924 secs_since: 0
Block cache entry stats(count,size,portion): DataBlock(30870,484.61 MB,94.6503%) FilterBlock(8,4.00 MB,0.781298%) IndexBlock(13,1.79 MB,0.350383%) Misc(1,0.00 KB,0%)

...

** File Read Latency Histogram By Level [ordered_column_familiy] **
** Level 0 read latency histogram (micros):
Count: 81353 Average: 7.1940  StdDev: 7.67
Min: 2  Median: 6.6506  Max: 457
Percentiles: P50: 6.65 P75: 8.43 P99: 14.02 P99.9: 33.92 P99.99: 338.28
------------------------------------------------------
(       1,       2 ]       16   0.020%   0.020%
(       2,       3 ]      733   0.901%   0.921%
(       3,       4 ]     3316   4.076%   4.997% #
(       4,       6 ]    29165  35.850%  40.847% #######
(       6,      10 ]    45780  56.273%  97.120% ###########
(      10,      15 ]     1901   2.337%  99.457%
(      15,      22 ]      305   0.375%  99.832%
(      22,      34 ]       56   0.069%  99.900%
(      34,      51 ]        4   0.005%  99.905%
(     170,     250 ]       58   0.071%  99.977%
(     250,     380 ]       16   0.020%  99.996%
(     380,     580 ]        3   0.004% 100.000%

** Level 6 read latency histogram (micros):
Count: 4419514 Average: 5550.1381  StdDev: 691.01
Min: 1  Median: 5772.1268  Max: 18358
Percentiles: P50: 5772.13 P75: 6791.31 P99: 9770.82 P99.9: 9882.55 P99.99: 9893.73
------------------------------------------------------
[       0,       1 ]        1   0.000%   0.000%
(       1,       2 ]        1   0.000%   0.000%
(       2,       3 ]       52   0.001%   0.001%
(       3,       4 ]    10920   0.247%   0.248%
(       4,       6 ]   267292   6.048%   6.296% #
(       6,      10 ]   201494   4.559%  10.855% #
(      10,      15 ]     4527   0.102%  10.958%
(      15,      22 ]      679   0.015%  10.973%
(      22,      34 ]      257   0.006%  10.979%
(      34,      51 ]       39   0.001%  10.980%
(      51,      76 ]      151   0.003%  10.983%
(      76,     110 ]       63   0.001%  10.985%
(     110,     170 ]       52   0.001%  10.986%
(     170,     250 ]       61   0.001%  10.987%
(     250,     380 ]        6   0.000%  10.988%
(     380,     580 ]        1   0.000%  10.988%
(     870,    1300 ]        1   0.000%  10.988%
(    1300,    1900 ]        2   0.000%  10.988%
(    2900,    4400 ]     5795   0.131%  11.119%
(    4400,    6600 ]  2755138  62.340%  73.459% ############
(    6600,    9900 ]  1174773  26.581% 100.041% #####
(    9900,   14000 ]      289   0.007% 100.047%
(   14000,   22000 ]        2   0.000% 100.047%

** Blob file read latency histogram (micros):
Count: 722894565 Average: 3.3089  StdDev: 4.79
Min: 1  Median: 2.7134  Max: 33406
Percentiles: P50: 2.71 P75: 3.23 P99: 4.77 P99.9: 12.17 P99.99: 27.55
------------------------------------------------------
[       0,       1 ]        3   0.000%   0.000%
(       1,       2 ] 41723483   5.772%   5.772% #
(       2,       3 ] 448179974  61.998%  67.770% ############
(       3,       4 ] 222925659  30.838%  98.608% ######
(       4,       6 ]  7370727   1.020%  99.627%
(       6,      10 ]  1632412   0.226%  99.853%
(      10,      15 ]   782499   0.108%  99.961%
(      15,      22 ]   164015   0.023%  99.984%
(      22,      34 ]    94099   0.013%  99.997%
(      34,      51 ]    10724   0.001%  99.998%
(      51,      76 ]     2737   0.000%  99.999%
(      76,     110 ]      485   0.000%  99.999%
(     110,     170 ]     1018   0.000%  99.999%
(     170,     250 ]     4589   0.001% 100.000%
(     250,     380 ]     1782   0.000% 100.000%
(     380,     580 ]      326   0.000% 100.000%
(     580,     870 ]      265   0.000% 100.000%
(     870,    1300 ]      445   0.000% 100.000%
(    1300,    1900 ]     1112   0.000% 100.000%
(    1900,    2900 ]      165   0.000% 100.000%
(    2900,    4400 ]       73   0.000% 100.000%
(    4400,    6600 ]       16   0.000% 100.000%
(    9900,   14000 ]        1   0.000% 100.000%
(   22000,   33000 ]       10   0.000% 100.000%
(   33000,   50000 ]        1   0.000% 100.000%
```

* all SST files:
```
 73716 -rw-r--r-- 1 root root  75483026 Jun 11 01:49 000119.sst
 13128 -rw-r--r-- 1 root root  13440679 Jun 11 09:07 000133.sst
 12368 -rw-r--r-- 1 root root  12662561 Jun 11 15:42 000149.sst
 75812 -rw-r--r-- 1 root root  77630018 Jun 11 19:21 000157.sst
 21836 -rw-r--r-- 1 root root  22359624 Jun 11 19:21 000158.sst
  2652 -rw-r--r-- 1 root root   2715189 Jun 11 20:46 000159.sst
  2644 -rw-r--r-- 1 root root   2704293 Jun 11 22:06 000161.sst
```

### Expected behavior

read filter block from block cache.

### Actual behavior

read filter block from `SST` file.

### Steps to reproduce the behavior

`none`

**Comment by akankshamahajan15** [comment]
Did you set the filter_policy as well in table_factory options?

**Comment by Wine93** [comment]
> 

my filter_policy reset as below shown:

```
BlockBasedTableOptions tableOptions;
tableOptions.filter_policy.reset(NewBloomFilterPolicy(10, false));
```

**Comment by akankshamahajan15** [comment]
Which RocksDB version are you using?

**Comment by Wine93** [comment]
> Which RocksDB version are you using?

RocksDB [v6.28](https://github.com/facebook/rocksdb/tree/6.28.fb)

**Comment by mdcallag** [comment]
"one more thing that confuses me is the LOG shows the FilterBlock only occupied about 0.8% of the block cache, and the DataBlock occupied about 94%, but in my understanding, the default value of high_pri_pool_ratio is 0.5 for LRU cache, so the DataBlock will not take more than 50%."

I am curious what the implementation does:
1) data blocks can't use more than 50% in any case
2) data blocks can't use more than 50% when there is memory pressure and index+filter blocks need at least 50%

---

For the question about Get always doing reads from storage for filter blocks, one place where that can happen is the first read from an SST, compaction produces new SSTs, so if your Get operations are always the first read from an SST then this can happen. It is unlikely, but possible. I am just trying to get more context on the problem.

---

From the perf_context stats this is interesting:  bytes_read = 10385482

I assume you either have large values or set the block_size option to a large value (the former is more likely). Lets assume you have 10M values. The LOG output you shared has a 512M block cache and 64 shards (num_shard_bits=64) so each shard of the block cache gets 512M/64 bytes (=8M/shard). In this case reading a 10M value means that a 10M block will be added to one shard of the block cache.But that 10M block is larger than the 8M/shard limit, so everything else in that shard will be evicted. So this ends as:
1) read index & filter blocks, put them in a shard of the block cache. If that shard already caches a 10M data block it will be evicted
2) read the 10M data block, put it in a shard of the block cache. Everything else in that shard will be evicted.
3) goto 1

I have seen this before with universal compaction and the option to partition large sorted runs for universal into many SSTs (by storing them in L1, L2, ...) was motivated by this problem.

**Comment by ajkr** [comment]
I agree with Mark's analysis except believe the filter block is the one that's larger than a cache shard because the PerfContext stats show `filter_block_read_count == block_read_count`.

Various options can help, like reducing `num_shard_bits`, reducing `target_file_size_base`, or reducing filter bits/key. Let us know if you need further help.

**Comment by Wine93** [comment]
> "one more thing that confuses me is the LOG shows the FilterBlock only occupied about 0.8% of the block cache, and the DataBlock occupied about 94%, but in my understanding, the default value of high_pri_pool_ratio is 0.5 for LRU cache, so the DataBlock will not take more than 50%."
> 
> I am curious what the implementation does:
> 
> 1. data blocks can't use more than 50% in any case
> 2. data blocks can't use more than 50% when there is memory pressure and index+filter blocks need at least 50%
> 
> For the question about Get always doing reads from storage for filter blocks, one place where that can happen is the first read from an SST, compaction produces new SSTs, so if your Get operations are always the first read from an SST then this can happen. It is unlikely, but possible. I am just trying to get more context on the problem.
> 
> From the perf_context stats this is interesting: bytes_read = 10385482
> 
> I assume you either have large values or set the block_size option to a large value (the former is more likely). Lets assume you have 10M values. The LOG output you shared has a 512M block cache and 64 shards (num_shard_bits=64) so each shard of the block cache gets 512M/64 bytes (=8M/shard). In this case reading a 10M value means that a 10M block will be added to one shard of the block cache.But that 10M block is larger than the 8M/shard limit, so everything else in that shard will be evicted. So this ends as:
> 
> 1. read index & filter blocks, put them in a shard of the block cache. If that shard already caches a 10M data block it will be evicted
> 2. read the 10M data block, put it in a shard of the block cache. Everything else in that shard will be evicted.
> 3. goto 1
> 
> I have seen this before with universal compaction and the option to partition large sorted runs for universal into many SSTs (by storing them in L1, L2, ...) was motivated by this problem.

Thank you @mdcallag. The truth is as you say, the filter block is the one that's larger than a cache shared, because the filter block is `10MB+` and the cached shared is only `8MB` (512MB/64), so it can't add the filter block into cache. Then i reducing the `num_shard_bits `, it works well and all filter blocks will be cached.
Thank you @ajkr.
