### ISSUE TITLE
ERROR: unknown command line flag 'gtest_color' ERROR: unknown command line flag 'gtest_filter'

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10162]
how solving this problems? thankyou~

**Comment by HBSDLJZ** [comment]
When I compile and run DB_ The above problems will occur during bench.

**Comment by hx235** [comment]
Could you provide your exact command of running db_bench and version of your RocksDB? Did you provide `gtest_color` and `gtest_filter ` to db_bench? These don't seem to be parameters related to `db_bench` but the gtest framework.

**Comment by hx235** [comment]
I'm closing this issue as it sounds very likely to me that the issue was about unrelated parameters being passed into db_bench.
