### ISSUE TITLE
Initializes the space occupied

### ISSUE THREAD

**Issue by q96456** [facebook/rocksdb#1017]
hi.I find an empty rocksdb's database need 145 MB of space.I use "du -h" to find the phenomenon.Why and can I fix it.

**Comment by igorcanadi** [comment]
Probably because we preallocate space for the write-ahead-log. Try setting `allow_fallocate ` to false: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/options.h#L1057

**Comment by dhruba** [comment]
Is it a newly created database or a database that had  data earlier but you deleted all the data from it?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
