### ISSUE TITLE
ColumnFamilyOptions SanitizeOptions is buggy on 32-bit platforms

### ISSUE THREAD

**Issue by edouarda** [facebook/rocksdb#1018]
```cpp
  ClipToRange(&result.write_buffer_size,
              ((size_t)64) << 10, ((size_t)64) << 30);
```

This results in trying to clamp between 65,536 and 0, resulting in clamping to 65,536, resulting in very small buffers, resulting in ShouldFlushNow() being true quite easily, resulting in assertion failing and database performance being "not what it should be".

The fix is either to do something like this

```cpp
static const size_t clamp_max = std::conditional<sizeof(size_t) == 4,
      std::integral_constant<size_t, 0xffffffff>,
      std::integral_constant<size_t, 64ull << 30>>::type::value;

ClipToRange(&result.write_buffer_size, ((size_t)64) << 10, clamp_max);
```

Or you can use a define.

**Comment by dhruba** [comment]
Hi edouarda, if you can submit a pull request, we can merge it in very quickly. And thanks for finding this.

**Comment by dhruba** [comment]
https://reviews.facebook.net/D55455

**Comment by edouarda** [comment]
Awesome, do you need me to do the PR?
