### ISSUE TITLE
Trivial Move

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10246]
![trivial_move](https://user-images.githubusercontent.com/43542395/175337259-31e2e2e2-39f5-461b-9443-02daa8abfa24.png)
![image](https://user-images.githubusercontent.com/43542395/175337581-b888ffc2-deca-4d23-ab7d-c34d1a19091c.png)
I printed the log “**Enter db_impl_compaction_flush.cc move.**” in this part of the code, but the logic did not print the log during the stress test. Is its “**Trivial Move**” logic not here?

**Comment by jay-zhuang** [comment]
stress test may not generate file that is qualified for trivial move. There're several unittests purposely generate files for that, for example:
https://github.com/facebook/rocksdb/blob/30141461f98bc2606c984a19e4a9472b2174be85/db/db_compaction_test.cc#L1143
which should print the message in your code.

**Comment by HBSDLJZ** [comment]
**[1]** If I use "db_bench" to write a large amount of data, such as writing 1000000 pieces of data, will “**Trivial Move**” not be triggered?

**[2]** I think if there is no overlapping SSTable in the next layer, or even no SSTable, “**Trivial Move**” will always be triggered, right?

**[3]** If you say so, will all merge operations be concentrated in the following methods?
compaction_job.cc Compaction::ProcessKeyValueCompaction()

Thankyou!~

**Comment by jay-zhuang** [comment]
> **[1]** If I use "db_bench" to write a large amount of data, such as writing 1000000 pieces of data, will “**Trivial Move**” not be triggered?

random data are likely overlapped, `db_bench fillseq` will generate sequential data which will not overlap.

> **[2]** I think if there is no overlapping SSTable in the next layer, or even no SSTable, “**Trivial Move**” will always be triggered, right?

yes, which is set here: https://github.com/facebook/rocksdb/blob/49628c9a83d337ea7b01f7ad3bdffa340e013913/db/compaction/compaction_picker_universal.cc#L471

> **[3]** If you say so, will all merge operations be concentrated in the following methods? compaction_job.cc Compaction::ProcessKeyValueCompaction()

not sure what's your question.

**Comment by HBSDLJZ** [comment]
Thank you very much indeed！
