### ISSUE TITLE
the total memory size of `memtables` exceed write buffer manager's limit

### ISSUE THREAD

**Issue by Wine93** [facebook/rocksdb#10267]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Hi, guys~ I create many DB instances in one process, and in order to limit the total memory size of memtable, i create a write buffer manager object which `_buffer_size` is `2GB` and pass it to all DB instance:

```
auto manager = std::make_shared<rocksdb::WriteBufferManager>(2147483648, nullptr); 
```

but now the jeprof shows that the memtable cost about `4GB`. 
Can you answer this question for me or give me some advice, thank you very much.

* jeprof:
![image](https://user-images.githubusercontent.com/9267583/176146162-5c4ffa86-ea2e-462b-9c89-70df1a1a14f9.png)

![memory](https://user-images.githubusercontent.com/9267583/176146666-4115600c-9610-4229-8e34-b66970ffd7a4.png)

* important configures:

```
...
Options.max_background_jobs: 16
Options.max_background_compactions: -1
Options.max_subcompactions: 1
...

# There are two column familys with the same configuration
...
Options.write_buffer_size: 67108864
Options.max_write_buffer_number: 3
...
```

### Expected behavior
the total memory size of memtable within the limit (`2GB`)

### Actual behavior
the total memory size of memtable exceed the limit (`2GB`)

### Steps to reproduce the behavior
`none`

**Comment by ajkr** [comment]
Can you share your LOG file? I wonder if flush is falling behind. In that case the WriteBufferManager memory limit is loose, unless you construct your `WriteBufferManager` with `allow_stall == true` (not commonly recommended).

**Comment by Wine93** [comment]
> 

Thank for your reply, all DB instances's logs in here:
[instance1_LOG.txt](https://github.com/facebook/rocksdb/files/9006797/instance1_LOG.txt)
[instance2_LOG.txt](https://github.com/facebook/rocksdb/files/9006799/instance2_LOG.txt)
[instance3_LOG.txt](https://github.com/facebook/rocksdb/files/9006801/instance3_LOG.txt)
[instance4_LOG.txt](https://github.com/facebook/rocksdb/files/9006803/instance4_LOG.txt)
[instance5_LOG.txt](https://github.com/facebook/rocksdb/files/9006805/instance5_LOG.txt)
[instance6_LOG.txt](https://github.com/facebook/rocksdb/files/9006806/instance6_LOG.txt)
[instance7_LOG.txt](https://github.com/facebook/rocksdb/files/9006808/instance7_LOG.txt)
[instance8_LOG.txt](https://github.com/facebook/rocksdb/files/9006809/instance8_LOG.txt)
[instance9_LOG.txt](https://github.com/facebook/rocksdb/files/9006810/instance9_LOG.txt)
[instance10_LOG.txt](https://github.com/facebook/rocksdb/files/9006811/instance10_LOG.txt)
[instance11_LOG.txt](https://github.com/facebook/rocksdb/files/9006814/instance11_LOG.txt)
[instance12_LOG.txt](https://github.com/facebook/rocksdb/files/9006816/instance12_LOG.txt)

**Comment by ajkr** [comment]
Thanks. The logs show `max_write_buffer_size_to_maintain: 201326592` (192MB). I suspect `WriteBufferManager` doesn't have the capability to trim the history. What if you set it a bit smaller, like 32MB?

**Comment by Wine93** [comment]
> max_write_buffer_size_to_maintain

Thanks, i will try it.

**Comment by Wine93** [comment]
Thanks @ajkr, your suggestion helped me a lot. When i reducing the `max_write_buffer_size_to_maintain` to `32MB`, the memory usage of the process becomes stable, thanks again :)

**Comment by ajkr** [comment]
No problem, glad it worked!
