### ISSUE TITLE
`rocksdb::port::win::GetWindowsErrSz` may assign `nullptr` to `std::string`

### ISSUE THREAD

**Issue by jxy-s** [facebook/rocksdb#10274]
`rocksdb::port::win::GetWindowsErrSz` may assign `nullptr` to `std::string`.
https://github.com/facebook/rocksdb/blob/main/port/win/io_win.cc#L39-L50

### Expected behavior

rocksdb should not crash when an error code can't be resolved to a string. It should not assign `nullptr` to `std::string`.

### Actual behavior

rocksdb will try to assign `nullptr` to a `std::string` if the error code can't be resolved to a string:
https://github.com/facebook/rocksdb/blob/main/port/win/io_win.cc#L39-L50

### Steps to reproduce the behavior

Generate an error in `rocksdb::port::win` that can't be resolved to a string.

**Comment by akankshamahajan15** [comment]
@jxy-s Can you create a PR for the fix?

**Comment by jxy-s** [comment]
Yes happy to.

**Comment by jxy-s** [comment]
Here is a stack trace and information from the dump where this issue occurred in our environment. I have trimmed part of the stack trace and removed internal names:

```
exe!std::_Narrow_char_traits<char,int>::length+0x3e
exe!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign+0x2d
exe!std::basic_string<char,std::char_traits<char>,std::allocator<char> >::basic_string<char,std::char_traits<char>,+0xc2
exe!rocksdb::port::GetWindowsErrSz+0x42
exe!rocksdb::port::IOErrorFromWindowsError+0x6a
exe!rocksdb::port::WinFileSystem::CreateDirIfMissing+0x26a
exe!rocksdb::CompositeEnv::CreateDirIfMissing+0x6b
exe!rocksdb::CreateLoggerFromOptions+0x221
exe!rocksdb::SanitizeOptions+0xe0
exe!rocksdb::DBImpl::DBImpl+0xf8
exe!rocksdb::DBImpl::Open+0x2c2
exe!rocksdb::DB::Open+0x29e

03 000000f3`029fb220 00007ff6`4a60271a     exe!rocksdb::port::GetWindowsErrSz+0x42 [CUT\port\win\io_win.cc @ 48] 
<unavailable>     unsigned long err = <value unavailable>
000000f3`029fb270 char * lpMsgBuf = 0x00000000`00000000 "" 
```
