### ISSUE TITLE
No way to call javajni transaction.prepare() to implement 2pc

### ISSUE THREAD

**Issue by jessin20161124** [facebook/rocksdb#10283]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
No way to call javajni transaction.prepare() to implement 2pc

**Comment by riversand963** [comment]
I can see a `prepare()` function in `Transaction` java class: https://github.com/facebook/rocksdb/blob/main/java/src/main/java/org/rocksdb/Transaction.java#L181. Can you try it?

**Comment by jessin20161124** [comment]
> I can see a `prepare()` function in `Transaction` java class: https://github.com/facebook/rocksdb/blob/main/java/src/main/java/org/rocksdb/Transaction.java#L181. Can you try it?

it is not a public method. I can not use it.

**Comment by riversand963** [comment]
hmm, not sure if it's intentional, but `commit()` is public, and I think it can be made public.
Maybe @adamretter knows more.
Feel free to contribute a PR.

**Comment by adamretter** [comment]
@riversand963 @jessin20161124 I can try and take a look at that on Monday. If it is just a matter of exposing an API that in C++ is already public, we should be able to that in Java without much difficulty (cc @alanpaxton)
