### ISSUE TITLE
Error of `Max allowed space was reached` will not recover even if disk space has enough space when using blobdb

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#10294]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
After disk space has enough space, `write` should be successful.

### Actual behavior
After disk space has enough space, error of `Max allowed space was reached` keep going.

### Steps to reproduce the behavior
1. Use integraded blobdb of rocksdb 7.2.0. 
2. Set `SstFileManager` as follows
```
  std::shared_ptr<rocksdb::SstFileManager> sst_file_mgr; 
  sst_file_mgr.reset(rocksdb::NewSstFileManager(env, nullptr, "", 0, 
                                true, nullptr, 0.1, 1024ULL * 1024 * 1024));
  uint64_t max_disk_space = 1024ULL * 1024 * 1024 *  1024 * 2.8;
  sst_file_mgr->SetMaxAllowedSpaceUsage(max_disk_space);
  sst_file_mgr->SetCompactionBufferSize(max_disk_space / 25);
  sst_file_mgr->SetDeleteRateBytesPerSecond(0);
  sst_file_mgr->SetMaxTrashDBRatio(0.1);
```
3. Value size is 100k, and write qps is 10000, read qps is 50000

**Comment by ltamasi** [comment]
This is actually a known issue with the out-of-space auto-recovery logic and is not specific to BlobDB. See also https://github.com/facebook/rocksdb/issues/9692, https://github.com/facebook/rocksdb/issues/9762, and https://github.com/facebook/rocksdb/issues/9876.

**Comment by ltamasi** [comment]
Closing since it's a duplicate

**Comment by riversand963** [comment]
@GOGOYAO are you using pipelined write?

**Comment by GOGOYAO** [comment]
> pipelined

no
