### ISSUE TITLE
Possible bug during checkpoint creation

### ISSUE THREAD

**Issue by RoeyMaor** [facebook/rocksdb#10301]
During checkpoint creation the latest sequence number is taken, before all column families are flushed.
This sequence number is then returned as the sequence number representing the checkpoint.
![image](https://user-images.githubusercontent.com/16507852/177016582-d1454444-7e93-403d-8239-309fd9e65c1c.png)

relevant code in checkpoint_impl.cc:
![image](https://user-images.githubusercontent.com/16507852/177014163-a35c6148-5b35-446b-a9fe-22c353d0f726.png)

Between the moment it is taken until the column families are flushed inside the GetLiveFilesStorageInfo function, new elements could be written to the memtables. Therefore in the flushed files, and in the checkpoint DB, there will be elements with sequence numbers larger than the sequence number returned in the API, raising a question to what is the meaning of the sequence number returned.

Roy.

**Comment by akankshamahajan15** [comment]
In checkpoint.h, it's mentioned that sequence_number might not point to latest sequence one. I am not sure but it might be to ensure consistency incase data is lost. cc @pdillinger Do you have more context on this?
 
 https://github.com/facebook/rocksdb/blob/3ffb3baa0b5ce782ea36c8c53adb211127a92dcc/include/rocksdb/utilities/checkpoint.h#L40-L42

**Comment by pdillinger** [comment]
This code is very old and that's why we only provide a very weak guarantee as Akanksha points out. I've thought about trying to provide a better guarantee, but it's complicated. You can always open the checkpoint as a read-only DB and GetLatestSequenceNumber() on it. Slow but authoritative.

**Comment by RoeyMaor** [comment]
@pdillinger @akankshamahajan15 Thank you both very much for your responses.
