### ISSUE TITLE
Possible Inconsistency between column families in atomic flush

### ISSUE THREAD

**Issue by RoeyMaor** [facebook/rocksdb#10302]
Discussion - When flushing using AtomicFlushMemTables there might be an inconsistency where there are sequence numbers that are "vanished" and not flushed in specific column families.

To clarify what I mean let's look at the following exapmle:

Assume latest sequence number is 999, and there are 2 CFs. AtomicFlushMemTables flushes each CF seperately. Therefore the following situation could be possible:
1) CF1 receives 1000,1001,1002 and is flushed.
2) 1003, 1004 are written to CF1's other memtable, and 1005, 1006 to CF2.
3) CF2 is flushed
4) MANIFEST is atomically updated with all flush results together (as this is an atomic flush).

**The result is that no table file will contain sequence numbers 1003, 1004, even though 1005, 1006 exist in the table files.**
If the DB is still live this won't affect Get requests to it as 1003 and 1004 are still available via the memtables of CF1. **But, this is a problem for checkpoints, for example, as the files and only the files will be copied to the checkpoint folder (after being flushed). Therefore the checkpoint DB's latest sequence in the MANIFEST will be 1006 but 1003 and 1004 are not in the checkpoint DB**. Also, in case immutable_db_options_.atomic_flush is false, then a regular flush will be made anyways and this error is true regardless.

One explanation as to why this might not be an issue is if all writes are blocked during the duration of the flush of all CFs. Though it appears this is not the case.

It appears something like that was already thought of, as there is a mechanism called atomic_flush_seqno (memtable.h):
![atomic_flush_seq_no](https://user-images.githubusercontent.com/16507852/177016446-0aa464f9-da52-4ecd-ba03-2e6d379cef7c.PNG)
![atomicflushseq2](https://user-images.githubusercontent.com/16507852/177016545-e03cfd4d-6d41-4de4-9321-b21b0a1c0b0a.PNG)

that is used within AtomicFlushMemTables to set the maximum sequence number to be flushed, but **it appears this variable is not used anywhere** (other than checking if it has default value or not)

I would appreciate your thoughts, whether I am missing something here.

Thanks
Roy.

**Comment by RoeyMaor** [comment]
> @RoeyMaor Which RocksDB version is this?

7.0.2 :)

**Comment by riversand963** [comment]
I don't think this can happen due to the single-threaded write thread impl and how we seal memtables for flush.
> 1. CF1 receives 1000,1001,1002 and is flushed.

When cf1 receives 1000, 1001, 1002, a flush may be triggered, and it will not happen yet. Furthermore, we will seal the memtables of cf2 without any writes going to the existing memtables.
> 2. 1003, 1004 are written to CF1's other memtable, and 1005, 1006 to CF2.

This can happen only after the memtables of ALL cfs are sealed.
> 3. CF2 is flushed

Assuming there is no newer triggere flush, then cf2 will flush only memtables before 1005.
> 4. MANIFEST is atomically updated with all flush results together (as this is an atomic flush).

MANIFEST now contains info about cf1 and cf2 being flushed with older memtables seq < 1003, assuming no other flush triggerd.

**Comment by riversand963** [comment]
> It appears something like that was already thought of, as there is a mechanism called atomic_flush_seqno (

This was introduced so that we may be able to return something to applications to reason about what has been atomically flushed so far, but we have not received requests for adding this interface. Given the low overhead of such a seq, we just leave it there in case it needs to be exposed in the future.

**Comment by RoeyMaor** [comment]
@riversand963 
Thanks, so you are saying that before you flush any CF you stop all writes to all memtables, then seal memtables, then resume all writes, correct?

**Comment by riversand963** [comment]
To be more exact, when we trigger a flush, we are the leader of current write group, thus no other writes can proceed. We seal all existing memtables for all column families and put this flush request to the flush queue. Then all writes can proceed.
A background thread will deque the flush request, and pick the right memtables to flush and commit to the MANIFEST.

**Comment by RoeyMaor** [comment]
@riversand963 
Cool thanks for the clarification. So this relies on the writer queue to stop all writes. How does it work with pipelined writes?

Also a somewhat related question, if two flushes for the same CF enter the job queue of the thread pool, is it guaranteed the first one popped will finish first?

Thanks again for the valuable info

**Comment by riversand963** [comment]
It's not compatible with pipelined, and we have a check for that: https://github.com/facebook/rocksdb/blob/main/db/db_impl/db_impl_open.cc#L279

Also a somewhat related question, if two flushes for the same CF enter the job queue of the thread pool, is it guaranteed the first one popped will finish first?

Flushing the data can finish out-of-order, but committing to MANIFEST will be in order.

**Comment by akankshamahajan15** [comment]
Closing this since it's more of a question than a bug. Please feel free to continue the discussion.
