### ISSUE TITLE
when I compile with hdfs ,its error

### ISSUE THREAD

**Issue by hfx123456** [facebook/rocksdb#10335]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Steps to reproduce the behavior
  CC       plugin/hdfs/env_hdfs_impl.o
plugin/hdfs/env_hdfs_impl.cc: In member function ‘virtual rocksdb::IOStatus rocksdb::HdfsFileSystem::NewDirectory(const string&, const rocksdb::IOOptions&, std::unique_ptr<rocksdb::FSDirectory>*, rocksdb::IODebugContext*)’:
plugin/hdfs/env_hdfs_impl.cc:508:38: error: invalid new-expression of abstract class type ‘rocksdb::{anonymous}::HdfsDirectory’
  508 |     result->reset(new HdfsDirectory(0));
      |                                      ^
plugin/hdfs/env_hdfs_impl.cc:404:7: note:   because the following virtual functions are pure within ‘rocksdb::{anonymous}::HdfsDirectory’:
  404 | class HdfsDirectory : public FSDirectory {
      |       ^~~~~~~~~~~~~
In file included from plugin/hdfs/env_hdfs.h:9,
                 from plugin/hdfs/env_hdfs_impl.cc:7:
./include/rocksdb/file_system.h:1271:20: note: 	‘virtual rocksdb::IOStatus rocksdb::FSDirectory::Close(const rocksdb::IOOptions&, rocksdb::IODebugContext*)’
 1271 |   virtual IOStatus Close(const IOOptions& options, IODebugContext* dbg) = 0;
      |                    ^~~~~
plugin/hdfs/env_hdfs_impl.cc: In member function ‘virtual rocksdb::IOStatus rocksdb::HdfsFileSystem::FileExists(const string&, const rocksdb::IOOptions&, rocksdb::IODebugContext*)’:
plugin/hdfs/env_hdfs_impl.cc:527:51: error: ‘ToString’ is not a member of ‘rocksdb’
  527 |                                ROCKSDB_NAMESPACE::ToString(value) + " on path " + fname + ".\n");
      |                                                   ^~~~~~~~
make: *** [Makefile:2426: plugin/hdfs/env_hdfs_impl.o] Error 1

**Comment by guoxiangCN** [comment]
This error because of that an "ToString" method was defined in "class Configuration" too, which has the same name with string_utils.h:: ToString.
