### ISSUE TITLE
Add wiki about cuckoo-hash based memtable.

### ISSUE THREAD

**Issue by hrjaco** [facebook/rocksdb#1033]
I just noticed there is a cuckoo hash based memtable https://github.com/facebook/rocksdb/commit/9d9d2965cb4df6163624a31d2b5dd7364813f27f, which seems to be very good for point lookup. But I do not see wiki mentioning it. Curious is it of production quality? If so, could someone please add it to wikis:
https://github.com/facebook/rocksdb/wiki/Hash-based-memtable-implementations
https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide#custom-memtable-and-table-format

Thanks!

**Comment by hrjaco** [comment]
Also it would be great if there are related benchmark results to share.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
