### ISSUE TITLE
Understanding of disableWAL write option

### ISSUE THREAD

**Issue by kwins** [facebook/rocksdb#10333]
>   Some Put set disableWAL=true, others Put set disableWAL = false, all of Put not sorted when execute Put API 
![image](https://user-images.githubusercontent.com/20967436/178185436-91ac49fa-c774-4beb-9ff9-291feb8f689c.png)

version: 6.20.3
### Expected behavior
get five wal log

### Actual behavior
only get one wal log

**Comment by riversand963** [comment]
Until RocksDB switches to the new WAL, all writes with disableWAL=false will go to the same WAL.
WAL switching happens in several cases. Usually, you don't get a new WAL on every write.

**Comment by kwins** [comment]
But when i modify transaction_log_impl.cc:154 NextImpl(false)  to NextImpl(false) , i can get five wal log

![image](https://user-images.githubusercontent.com/20967436/178984906-73ec0091-f591-4420-82c9-1cc45a858e53.png)

Then i found some explain in rocksdb::TransactionLogIterator in below
![image](https://user-images.githubusercontent.com/20967436/178985262-a8646ca5-e9c3-41f6-80cf-42574fbce887.png)


Questing:
Why the iterator will stop at the beginning of any gap in sequences?
