### ISSUE TITLE
seekToLast() Broken For rocksdbjni Library?

### ISSUE THREAD

**Issue by jamespedwards42** [facebook/rocksdb#1034]
both #seekToFirst() and #seek(byte[] key) work just fine, however when I use #seekToLast() instead the iterator is always invalid.  

Also, this might be expected/desired behavior, but if I continue to iterate forward on a valid iterator with #next() until #isValid() returns false I am then unable to use #prev() to go back to a valid state.  The iterator will remain invalid once it has completed its forward traversal.

**Comment by adamretter** [comment]
@jamespedwards42 Let me see if I can reproduce this...

**Comment by jamespedwards42** [comment]
@adamretter Adding the tailing read option is what breaks it.  My goal was to reuse the same iterator and call seekToLast each time to see the latest sorted entry.

`db.newIterator(new ReadOptions().setTailing(true));`

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
