### ISSUE TITLE
TransactionLogIterator::GetBatch cannot be called repeatedly

### ISSUE THREAD

**Issue by 1522140840** [facebook/rocksdb#10361]
TransactionLogIterator::GetBatch can only be called once, because the smart pointer move operation is used inside the function. If it is called multiple times, the iter->GetBatch().writeBatchPtr() obtained the second time will be nullptr; I think it should be The user knows that this method cannot be called repeatedly

**Comment by riversand963** [comment]
For now, the application needs to take the ownership after calling `GetBatch()`, and do whatever with the batch afterwards.
