### ISSUE TITLE
Fixed Socialbar / Distorting UI 

### ISSUE THREAD

**Issue by Raeskaa** [facebook/rocksdb#10381]
### Fixed Socialbar

The social bar must be fixed at the top and must be static throughout the website and must not move similar to the navbar but when I scroll down, it just moves and the website looks terrible 

https://user-images.githubusercontent.com/84667136/179442278-e0c63946-a858-4801-9469-2c7353a1e6f4.mp4

### Expected Response

https://user-images.githubusercontent.com/84667136/179442255-c4645e04-1971-46e7-b9a5-d75d51801cbd.mp4

**Comment by cbi42** [comment]
Hi @Raeskaa , thanks for reporting. Would you like to contribute a fix?

**Comment by Raeskaa** [comment]
Yeah sure! @cbi42 
I'd like to take this up
