### ISSUE TITLE
level0_file_num_compaction_trigger = 2

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10397]
I have set this parameter to 2. Why is the printed one larger than 2, 11? Thank you for your help.
<img width="282" alt="image" src="https://user-images.githubusercontent.com/43542395/180122542-445efcb7-6e2c-4498-8d75-119d7856c9df.png">

**Comment by jay-zhuang** [comment]
the parameter level0_file_num_compaction_trigger means it will trigger compaction when there's 2 SST. it can still have more than 2 SSTs on L0.

**Comment by HBSDLJZ** [comment]
How to prevent too many files in this level？Thankyou~
I hope to send blocking when a certain number is reached.
