### ISSUE TITLE
 What scenario will set the parameter “sync” of rocksdb to “true”？

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10405]
If the parameter sync of rocksdb is set to true, data downtime will not be lost.

What is the application scenario of this approach in practical work? Can you help me list a few?

Thank you.

**Comment by jay-zhuang** [comment]
I assume you're talking about the sync in WriteOptions:
https://github.com/facebook/rocksdb/blob/b283f041f58deb87a7a0fa21005c963d0f0dee88/include/rocksdb/options.h#L1690-L1706
which has high write performance impact, but has strong data consistency. for example, if an application store it's data schema in RocksDB, schema change is infrequent and requires extra consistency, then the feature could be enabled only for schema write.

**Comment by HBSDLJZ** [comment]
If this parameter is enabled, can the system convert random writes to sequential writes? Does it not have this feature?
