### ISSUE TITLE
Can't compile on armv6l

### ISSUE THREAD

**Issue by motorto** [facebook/rocksdb#10420]
Trying to cross compile to armv6l  the version 7.4.3 but I am getting
errors. I have attatched the CMakeError.log and CMakeOutput.log.

I don't know what info to provide so if I am missing something please tell me.

Tried the following patch with no avail: 

<details> 
  <summary>Patch</summary>

From here: https://github.com/facebook/rocksdb/issues/8609#issuecomment-1009572506
```diff
diff --git a/utilities/transactions/lock/range/range_tree/lib/portability/toku_time.h b/utilities/transactions/lock/range/range_tree/lib/portability/toku_time.h
index 225e3fa72..cd5f935f1 100644
--- a/utilities/transactions/lock/range/range_tree/lib/portability/toku_time.h
+++ b/utilities/transactions/lock/range/range_tree/lib/portability/toku_time.h
@@ -131,6 +131,10 @@ static inline tokutime_t toku_time_now(void) {
   uint64_t result;
   __asm __volatile__("mrs %[rt], cntvct_el0" : [ rt ] "=r"(result));
   return result;
+#elif defined(__arm__)
+  uint32_t lo, hi;
+  __asm __volatile__("mrrc p15, 1, %[lo], %[hi], c14" : [ lo ] "=r" (lo), [hi] "=r" (hi));
+  return (uint64_t)hi << 32 | lo;
 #elif defined(__powerpc__)
   return __ppc_get_timebase();
 #elif defined(__s390x__)
```
</details>

- [CMakeError.log](https://github.com/facebook/rocksdb/files/9188709/CMakeError.log)
- [CMakeOutput.log](https://github.com/facebook/rocksdb/files/9188710/CMakeOutput.log)

**Comment by adamretter** [comment]
@motorto It would help to include what you tried
