### ISSUE TITLE
ycsb “ You have to open all column families. Column families not opened: usertable”

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10447]
![image](https://user-images.githubusercontent.com/43542395/182031502-69c3aef5-82d1-49e4-aff6-db2b07fbd024.png)

**./bin/ycsb run rocksdb -s -P workloads/workloada -p rocksdb.dir=/tmp/ycsb-rocksdb-data -p rocksdb.optionsfile=workloads/ycsb-rocksdb-options.ini**

When I perform the ycsb experiment, I add the ycsb-rocksdb-options.ini configuration file, and the above error is reported

**Comment by ajkr** [comment]
"Column families not opened: usertable" suggests the application (ycsb) did not provide proper arguments to open their database.

**Comment by dkdl012** [comment]
@ajkr I'm in exact same issue. 
Does this mean that it's impossible to benchmark a rocksdb in ycsb, applying ycsb-rocksdb-options.ini?

If you know of any other possible ways to benchmark a rocksdb with ycsb, I'm glad to know.
