### ISSUE TITLE
Whether there is an identifier in sstable helps us quickly determine which sstable kV belongs to.

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10445]
We can use level_ num to determine which level KV belongs to. Is sstable uniquely identified?
Whether there is an identifier in sstable helps us quickly determine which sstable kV belongs to.

**Comment by ajkr** [comment]
Seems it is there since 7.3. See line starting with "Start tracking SST unique id in MANIFEST" in https://github.com/facebook/rocksdb/releases/tag/v7.3.1.
