### ISSUE TITLE
librocksdbjni-win64.dll is missing in rocksdbjni-7.4.4.jar

### ISSUE THREAD

**Issue by stefan-zobel** [facebook/rocksdb#10448]
The rocksdbjni-7.4.4.jar deployed to Maven Central doesn't have a Win64 librocksdbjni-win64.dll inside.

**Comment by dlucek** [comment]
> The rocksdbjni-7.4.4.jar deployed to Maven Central doesn't have a Win64 librocksdbjni-win64.dll inside.

I have the same issue under Windows 10.  JDK 15.0.1+9

**Comment by sambsnyd** [comment]
I note that 7.4.4 is also missing the x86 dll, so it wouldn't work on 32-bit windows either.
