### ISSUE TITLE
The log of remote compaction

### ISSUE THREAD

**Issue by Qiaolin-Yu** [facebook/rocksdb#10462]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

@jay-zhuang 
I'm trying to test remote compaction, but I have a problem with the log on the remote side.

According to my current understanding, RocksDB will determine the location of log based on `db_name`, and the remote end will gets the same `db_name` as the primary db. So will the log of the remote side be written to the log file of the primary db?

**Comment by jay-zhuang** [comment]
The remote side log should be in the `output_directory`, the same directory as the compaction output files.
Here is the code for creating the log (internally, the remote side uses the secondary instance to open and compact the files):
https://github.com/facebook/rocksdb/blob/d6b9c4ae26dfbb59eecbe27d85ada22b36dee44c/db/db_impl/db_impl_secondary.cc#L688-L694
the `tmp_opts.info_log` should always be nullptr as we haven't provide an override yet, which we will in the future.
