### ISSUE TITLE
Java packages for v7.4.5

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#10470]
We had to patch 7.4 again for a serious bug. This issue tracks creating new Java packages

**Comment by asad-awadia** [comment]
@pdillinger what was the bug and how do you build rocksdb java on your laptop? `make -j16 rocksdbjavastaticreleasedocker` ?

**Comment by asad-awadia** [comment]
`rocksdbjavastaticrelease` should this one create the jars ?

**Comment by adamretter** [comment]
7.4.5 will be released shortly. Apologies for the delay, there was a miscommunication

**Comment by adamretter** [comment]
7.4.5 is now available from Maven Central

**Comment by adamretter** [comment]
> how do you build rocksdb java on your laptop?

@asad-awadia We use `make rocksdbjavastaticreleasedocker` to build platform specific release jars.

**Comment by asad-awadia** [comment]
@adamretter in version 7 it also builds a jar without osx/linux suffix that works on both platforms -- which one is that for v6.22.1 ? I only see platform specific jars

**Comment by adamretter** [comment]
@asad-awadia For macOS RocksDB 7.4.5 the jar is - [rocksdbjni-7.4.5-osx.jar](https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/7.4.5/) it contains two native libraries, one for Intel mac and one for Arm Mac, respectively `librocksdbjni-osx-x86_64.jnilib` and `librocksdbjni-osx-arm64.jnilib`

The 6.22.1 jar for macOS is [rocksdbjni-6.22.1-osx.jar](https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/6.22.1/) and it only contains a native library for Intel Mac (`librocksdbjni-osx.jnilib`).
