### ISSUE TITLE
Clarify license of utilities/transactions/lock/range/range_tree/lib/util/dbt.cc

### ISSUE THREAD

**Issue by vasanth-kandasamy** [facebook/rocksdb#10478]
All the files in range_tree/lib are 'Apache V2' licensed except range_tree/lib/util/dbt.cc.
Kindly clarify.

**Comment by i-kvasanth** [comment]
@spetrunia / @riversand963 - Please clarify.

**Comment by siying** [comment]
Thanks. We need to modify it. @SergeyMakarenko what's the procedure we should follow to change license to the file?

**Comment by i-kvasanth** [comment]
@SergeyMakarenko  Could you please tell is there any update on the above issue?
