### ISSUE TITLE
iterator.seek() so slow

### ISSUE THREAD

**Issue by meilihao** [facebook/rocksdb#10510]
I use rocksdb to store cdp(Continuous Data Protection) data. key is `'p'+nanosecond timestamp(uint64)`, value is `sector + bio data`.

my env:
![2022-08-09_19-16-48](https://user-images.githubusercontent.com/4382586/183634928-e6122ca3-e2f3-4e5b-b59a-6e4a18bedbfe.png)

my code:
![2022-08-09_19-15-11](https://user-images.githubusercontent.com/4382586/183634960-d0865fca-f40b-4f38-8cf8-83ef0d8f60f1.png)
![2022-08-09_19-15-46](https://user-images.githubusercontent.com/4382586/183634946-ebaeecf8-bcbb-48b3-9618-9d0a5e859d85.png)
![2022-08-09_19-08-47](https://user-images.githubusercontent.com/4382586/183635002-303f0a15-12d4-4320-b8ab-f11ae6f56b19.png)

### Expected behavior
iterator.seek() returns soon.
### Actual behavior
![2022-08-09_19-09-18](https://user-images.githubusercontent.com/4382586/183634983-026b35f6-6fd0-42d1-9204-75d987738931.png)

![2022-08-09_19-24-15](https://user-images.githubusercontent.com/4382586/183635963-311b9f7d-7b39-4479-bc71-2e073184161d.png)

**seek() need 1~2h or more on my other db(206g)**.

**Comment by meilihao** [comment]
I found `seekToFirst()` is slow too.

**Comment by cbi42** [comment]
Do you have a lot of Deletes in your app? From the perf_context, it seems that a lot of data block (`block_read_bytes`) is read due to skipping deleted entries (`internal_delete_skipped_count`). Doing a full manual compaction might help remove all the tombstones. A similar issue before: #10300

**Comment by meilihao** [comment]
@cbi42, thank your answer. I tried `db.CompactRange(Range{nil, nil})`, and `iterator.seek() returns soon`. But CompactRange(42g) need 11 minutes, it's too long.

There is a lot of writing rocksdb in my application. Do you have any optimization suggestions?

**Comment by cbi42** [comment]
Hi @meilihao, I'm not an expert on compaction, so my suggestion on that is limited and others are welcomed to add more. I think tuning options that allow more compactions in the background should be helpful. You can checkout some wikis here: https://github.com/facebook/rocksdb/wiki/Compaction, https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning, https://github.com/facebook/rocksdb/wiki/Prefix-Seek.
