### ISSUE TITLE
How to recover from a compactions corruption?

### ISSUE THREAD

**Issue by LucienXian** [facebook/rocksdb#10531]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
When put a key-value, db will return such a message:
```
{Corruption: block checksum mismatch: stored = 613959899, computed = 819860087, type=1 in xxx.sst}
```
In the log, we found that this was because the crc check failed during the compaction flush, and then a background error was recorded.

We built db on the remote file system. The remote_fs here has three replications, and there may be corruption in the file data of one replication. At this point I need to randomly retry to another replica. But because of this failure, the subsequent compaction will no longer be done, and it cannot be reinserted. Is there a mechanism that allows us to retry the compaction. Or it is detected from the outside that the db is in a read-only mode due to compactions corruption, and then the db is automatically reopened..

### Actual behavior
Subsequent insertion fails, no more compaction

**Comment by ltamasi** [comment]
Yes, by default an error during a background compaction will put the DB in read-only mode. You can use the `Resume` API to recover from this and put the DB back in read-write mode. See more details on the wiki here: https://github.com/facebook/rocksdb/wiki/Background-Error-Handling

**Comment by LucienXian** [comment]
> Yes, by default an error during a background compaction will put the DB in read-only mode. You can use the `Resume` API to recover from this and put the DB back in read-write mode. See more details on the wiki here: https://github.com/facebook/rocksdb/wiki/Background-Error-Handling

@ltamasi Thx!!  But I still have a question, how do we know that a bg error is set in error_handler_ at this time, which causes the writing to fail? (I want to call resume manually to restore db with this flag)

**Comment by ltamasi** [comment]
One thing you might do is to create your own `EventListener` and override the `OnBackgroundError` virtual. This way, your application would get notified whenever a background error occurs.

**Comment by LucienXian** [comment]
> One thing you might do is to create your own `EventListener` and override the `OnBackgroundError` virtual. This way, your application would get notified whenever a background error occurs.

Thx! I got it.
