### ISSUE TITLE
How to cross compile rocksdb? Is there any docs?

### ISSUE THREAD

**Issue by wahaha666** [facebook/rocksdb#10530]

**Comment by asad-awadia** [comment]
`make jclean clean rocksdbjavastaticreleasedocker` if you have docker

`rocksdbjavastaticrelease` this should use vagrant but doesn't build the jars for some reason - I posted a question but nobody is replying

**Comment by wahaha666** [comment]
> `make jclean clean rocksdbjavastaticreleasedocker` if you have docker
> 
> `rocksdbjavastaticrelease` this should use vagrant but doesn't build the jars for some reason - I posted a question but nobody is replying

@asad-awadia Thans for  replaying! I want to compile ARM64's library of rocksdb on linux x86, but  I couldn't find any documentation！

**Comment by wahaha666** [comment]
> `make jclean clean rocksdbjavastaticreleasedocker` if you have docker
> 
> `rocksdbjavastaticrelease` this should use vagrant but doesn't build the jars for some reason - I posted a question but nobody is replying

@asad-awadia Thans for  replaying! I want to compile ARM64's library of rocksdb on linux x86, but  I couldn't find any documentation！

**Comment by asad-awadia** [comment]
@adamretter is rocksdb supported on arm? How should I build the JAVA JARS if I want to run it in a linux container on arm [aws graviton] ?

**Comment by adamretter** [comment]
@asad-awadia Yes RocksDB is supported on Arm. We provide binaries for Arm in the packages available for RocksJava from Maven Central. Otherwise, you can simply compile RocksDB as normal on your Arm platform to get Arm compatible binaries.
