### ISSUE TITLE
MultiGet and Get cannot find some keys but they do exist in iteration

### ISSUE THREAD

**Issue by yinciki** [facebook/rocksdb#10551]
MultiGet and Get methods cannot return the existing values but in iteration the values can be found anyway

rocksdb version: 6.29

### Expected behavior
get correct values with MultiGet and Get methods
### Actual behavior
MultiGet and Get methods cannot return the existing values but in iteration the values can be found.

### Steps to reproduce the behavior
20 keys to query in total, 19 of them exist in db, but MultiGet and Get method would miss 7 and 2 keys respectively, and during iteration, all the 19 keys can be found and Get method returns correctly.

here is my test code and  output: 

`#include <cstdio>
#include <string>
#include <iostream>
#include <fstream>
#include <sstream>
#include <ctime>
#include <set>
#include "rocksdb/db.h"
#include "rocksdb/slice.h"
#include "rocksdb/options.h"
#include <time.h>

#define random_double(RAND_MAX) (rand() / float(RAND_MAX))

using rocksdb::DB;
using rocksdb::Options;
using rocksdb::PinnableSlice;
using rocksdb::ReadOptions;
using rocksdb::Status;
using rocksdb::WriteBatch;
using rocksdb::WriteOptions;
using namespace std;

int main(int argc, char *argv[]) {
  const char* kDBPath = argv[1];
  const char* file_name = argv[2];
  clock_t start, finish; 
  ifstream file(file_name, ios::in);
  uint64_t key;
  uint64_t cnt = 0;
  string strLine = "";
  vector<uint64_t> key_vector_1;
  set<uint64_t> key_set; 
  while (getline(file, strLine)) {
    istringstream iss(strLine);
    iss >> key;
    key_vector_1.push_back(key);
    key_set.insert(key);
  }
  cout << "keys loaded \n";
  DB* db;
  Options options;
  // Optimize RocksDB. This is the easiest way to get RocksDB to perform well
  options.IncreaseParallelism();
  options.OptimizeLevelStyleCompaction();
  // create the DB if it's not already present
  options.create_if_missing = true;
  // options.PrepareForBulkLoad();
  options.unordered_write=true;
  // open DB
  Status s = DB::Open(options, kDBPath, &db);
  assert(s.ok());
  cout << "db opened\n";
  // atomically apply a set of updates

  vector<PinnableSlice> values(key_vector_1.size()); 
  vector<Status> statuses(key_vector_1.size());  
  vector<rocksdb::Slice> querySlices; 
  uint32_t get_miss_num = 0;
  for (int i = 0; i < key_vector_1.size(); i++) {
    rocksdb::Slice db_key(to_string(key_vector_1[i]));
    querySlices.emplace_back(db_key);  
    PinnableSlice value;
    Status st = db->Get(ReadOptions(), db->DefaultColumnFamily(), db_key, &value);
    if(value == nullptr) {
      cout << "query key = " << to_string(key_vector_1[i]) 
                << " miss" << endl;  
      get_miss_num++;
    } else {
      cout << "query key = " << to_string(key_vector_1[i]) << endl;
    }
  }
  cout << "querySlices num = " << querySlices.size() 
       << " get_miss_num = " << get_miss_num << endl;
  start = clock();
  db->MultiGet(ReadOptions(), db->DefaultColumnFamily(), querySlices.size(), querySlices.data(), values.data(), statuses.data());  
  finish = clock();
  double read_duration;
  uint32_t multi_get_miss_num = 0;
  read_duration = (double)(finish - start) / CLOCKS_PER_SEC;
  // cout << "read_duration : " << read_duration << "s\n";
  for(int i = 0; i < values.size(); i++)  {
    string val_str = *values[i].GetSelf();
    // cout << "value size : " << values[i].size() << endl; 
    if(values[i] == nullptr) {
      uint64_t value;
      multi_get_miss_num++;
    }
  } 
  cout << "multi_get_miss_num = " << multi_get_miss_num << endl;
  uint32_t iter_get_fail_num = 0;
  uint32_t iter_found_num = 0;

  //ofstream out("/dockerdata/db_keys_out");
  rocksdb::Iterator* it = db->NewIterator(rocksdb::ReadOptions());
  set<uint64_t>::iterator iter;
  for (it->SeekToFirst(); it->Valid(); it->Next()) {
    // cout << it->key().ToString() << ": " << it->value().ToString() << endl;
    istringstream iss(it->key().ToString());
    uint64_t key_long;
    iss >> key_long;
    //string value;
    PinnableSlice value;
    Status st = db->Get(ReadOptions(), db->DefaultColumnFamily(), it->key(), &value);
    if(!st.ok()) {
    //if(value == nullptr) {
      cout << "Result of Get() int iter with key=" << it->key().ToString() << " is " << st.code() << endl;
      iter_get_fail_num++; 
    }
    iter = key_set.find(key_long);
    if (iter != key_set.end()){
      //out << it->key().ToString() << endl;
      cout << "iter found " << it->key().ToString() << endl;
      iter_found_num++;
      key_set.erase(key_long); 
    }
    //cout << it->key().ToString() << endl;
  }
  assert(it->status().ok()); // Check for any errors found during the scan
  for (iter = key_set.begin(); iter != key_set.end(); iter++) {
    cout << "iter not found key : " << *iter << endl;
  }
  cout << "iter_get_fail_num = " << iter_get_fail_num 
       << " iter_found_num = " << iter_found_num << endl;
  //out.close();
  delete it;

  delete db;

  return 0;
}`

output:

query key = 351080526806802400 miss
query key = 842181544122013376
query key = 687690058756956288
query key = 1066969494187141024
query key = 401001089282613376
query key = 700043425808839168
query key = 693672914172515328
query key = 228618606942117408 miss
query key = 558903836480973280
query key = 791223753301281952
query key = 1043452785184688512
query key = 623332548612178816
query key = 5479434867911552
query key = 757799316453318048
query key = 1058953432170170240
query key = 981176876522516192
query key = 74866089513475616
query key = 1100552468417015680
query key = 556897041592479968
query key = 631227321167967296
querySlices num = 20 get_miss_num = 2
multi_get_miss_num = 7
iter found 1043452785184688512
iter found 1058953432170170240
iter found 1066969494187141024
iter found 1100552468417015680
iter found 351080526806802400
iter found 401001089282613376
iter found 5479434867911552
iter found 556897041592479968
iter found 558903836480973280
iter found 623332548612178816
iter found 631227321167967296
iter found 687690058756956288
iter found 693672914172515328
iter found 700043425808839168
iter found 74866089513475616
iter found 757799316453318048
iter found 791223753301281952
iter found 842181544122013376
iter found 981176876522516192
iter not found key : 228618606942117408
iter_get_fail_num = 0 iter_found_num = 19

**Comment by cbi42** [comment]
Hi @yinciki, I think it might have something to do with your usage of slices.
```
rocksdb::Slice db_key(to_string(key_vector_1[i]));
querySlices.emplace_back(db_key);
PinnableSlice value;
Status st = db->Get(ReadOptions(), db->DefaultColumnFamily(), db_key, &value);
```

When `Get()` is called, `db_key` points to a string that is no longer allocated.

**Comment by yinciki** [comment]
> Hi @yinciki, I think it might have something to do with your usage of slices.
> 
> ```
> rocksdb::Slice db_key(to_string(key_vector_1[i]));
> querySlices.emplace_back(db_key);
> PinnableSlice value;
> Status st = db->Get(ReadOptions(), db->DefaultColumnFamily(), db_key, &value);
> ```
> 
> When `Get()` is called, `db_key` points to a string that is no longer allocated.

Thank you for your reply.  How about the MultiGet?

**Comment by cbi42** [comment]
> > Hi @yinciki, I think it might have something to do with your usage of slices.
> > ```
> > rocksdb::Slice db_key(to_string(key_vector_1[i]));
> > querySlices.emplace_back(db_key);
> > PinnableSlice value;
> > Status st = db->Get(ReadOptions(), db->DefaultColumnFamily(), db_key, &value);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When `Get()` is called, `db_key` points to a string that is no longer allocated.
> 
> Thank you for your reply. How about the MultiGet?

It seems to be the same issue with Slice pointing to string that might be freed?
```
rocksdb::Slice db_key(to_string(key_vector_1[i]));
querySlices.emplace_back(db_key);
...
db->MultiGet(ReadOptions(), db->DefaultColumnFamily(), querySlices.size(), querySlices.data(), values.data(), statuses.data());

```

**Comment by cbi42** [comment]
https://github.com/facebook/rocksdb/wiki/Basic-Operations#slice has some information regarding `Slice`.

**Comment by yinciki** [comment]
> https://github.com/facebook/rocksdb/wiki/Basic-Operations#slice has some information regarding `Slice`.

Indeed, I just verified the problem. Many thanks!
