### ISSUE TITLE
rocksdbjni on Windows doesn't release memory cache

### ISSUE THREAD

**Issue by Toshh** [facebook/rocksdb#1058]
Hi,

I'm using rocksdbjni.dll(V4.3.1) on Windows.
Its performance is better than leveldb.

But I have one issue. And this issue occurs in LevelDB jni also.
Windows keeps  .sst files as Active state in RAM even if finish to read/write data.
I checked by using RAMMap.exe
So finally memory usage leach maximum in my system.

Now my workaround is using Dynamic Chache Service that can restrict memory chache amount.

Do you have any plan to fix it?

And when will package include locksdbjni.dll?
I struggled to create it manually...

**Comment by adamretter** [comment]
@Toshh Regards RocksJava support on Windows, please see - https://github.com/facebook/rocksdb/issues/703#issuecomment-206027819

**Comment by adamretter** [comment]
@Toshh The release of RocksJava 4.9.0 now available on Maven Central has a Windows .dll included within it.
