### ISSUE TITLE
The ldb backup feature doesn’t works anymore.

### ISSUE THREAD

**Issue by ytrezq** [facebook/rocksdb#10581]
I tried several combinations but looks like the argument parsing is dead :

    sh-5.1# ./ldb --db=/mnt/openethereum/xdai/db/3c648cbdc4c9333d/archive/db backup --backup_dir /mnt/openethereum/xdai/db/3c648cbdc4c9333d/snapshot/
    Failed: --backup_dir: missing backup directory

**Comment by ytrezq** [comment]
@ajkr : hey why `question`? This is a minimal case which means there’s nothing which can be done to get it working. The code must be changed !

**Comment by riversand963** [comment]
Can you try `--backup_dir=<your path>`?
Also, please provide more information about version. With existing information, other people need to guess.

**Comment by riversand963** [comment]
The argument parsing logic of ldb is not as robust as gflags etc, but it has the advantage of fewer dependencies, which can be useful when having to debug on machines where it's impractical to install third-party libs.

**Comment by riversand963** [comment]
Closing because I tried on my machine
```
(main)$ ./ldb --db=/dev/shm/rocksdb/dbbench/ backup --backup_dir=/tmp
open db OK
open backup engine OK
create new backup OK
```
btw, I am on 7670fdd6907df2de42e558be0e09736f341debc5

**Comment by ytrezq** [comment]
@riversand963 : shouldn’t it be reflected when using `--help` that an `=` is required ?

**Comment by mrambacher** [comment]
I think it is --backup_dir=<directory>.  Your command is missing the "="

/ Mark
