### ISSUE TITLE
Please conduct Java/other platform testing for 7.6.fb

### ISSUE THREAD

**Issue by gitbw95** [facebook/rocksdb#10599]
Hi @adamretter ,

https://github.com/facebook/rocksdb/commits/7.6.fb is ready for Java/other platform testing. 

Thanks!
Bo

**Comment by adamretter** [comment]
I can confirm that I have now completed testing the 7.6.fb branch on
all platforms and it looks good.

**Comment by gitbw95** [comment]
Thanks a lot @adamretter !
