### ISSUE TITLE
Backup to S3?

### ISSUE THREAD

**Issue by shuzhang1989** [facebook/rocksdb#1060]
For the current version of RocksDb, do we have a way to backup and restore to / from S3?

**Comment by siying** [comment]
You can write your own Env which operates on S3 files. You are also welcome to contribute back:)

**Comment by shuzhang1989** [comment]
haha @siying , i see. Thanks for the info :)

**Comment by igorcanadi** [comment]
rocks-strata is a tool that can backup RocksDB and it already has an S3 implementation: https://github.com/facebookgo/rocks-strata.

**Comment by shuzhang1989** [comment]
@igorcanadi wow, i will definitely take a look! Thanks !
