### ISSUE TITLE
env_test crash

### ISSUE THREAD

**Issue by walterzhaoJR** [facebook/rocksdb#10608]
### Expected behavior
env_test execution succeed

### Actual behavior
when i run env_test in docker，env_test crash
![image](https://user-images.githubusercontent.com/22393698/187404757-168541f3-d318-4a00-9e38-f769a64f0d84.png)

### Steps to reproduce the behavior

df -T
![image](https://user-images.githubusercontent.com/22393698/187404876-b23fb29d-1c12-4652-a8bd-d729d8b18c68.png)

**Comment by hx235** [comment]
Hi which version of RocksDB are you running?

**Comment by walterzhaoJR** [comment]
> Hi which version of RocksDB are you running?

5.8.13
