### ISSUE TITLE
write/get performance degradation

### ISSUE THREAD

**Issue by yinciki** [facebook/rocksdb#10617]
I tried to write huge number of kvs into my rocksdb and read from it, but it took much longer time to write and read as the number of kvs in the rocksdb increased significantly. 

For example :
```
read:
read key size: 129093 time:0.530049s num of total keys in db:2887843
read key size: 244723 time:1.54977s num of total keys in db:8818742
read key size: 344095 time:2.55462s num of total keys in db:17799862
read key size: 425377 time:4.65428s num of total keys in db:29813991
read key size: 501021 time:4.07396s num of total keys in db:44869844
read key size: 566703 time:6.32499s num of total keys in db:62959572
read key size: 629516 time:6.45402s num of total keys in db:39147167
read key size: 697774 time:23.9644s num of total keys in db:63301526

write:
write key size: 2925541 time: 12.6122s num of totals keys in db:2925541
write key size: 2993724 time: 42.5936s num of totals keys in db:8844806
write key size: 3041703 time: 67.349s num of totals keys in db:17805774
write key size: 3052455 time: 178.853s num of totals keys in db:29819197
write key size: 3042681 time: 132.074s num of totals keys in db:44875301
write key size: 3050712 time: 266.279s num of totals keys in db:62982117
write key size: 3022345 time: 184.746s num of totals keys in db:39168682
write key size: 3033348 time: 388.838s num of totals keys in db:63331191
```

the db configuration (rocksdb version 6.29.5):
```
  options.IncreaseParallelism();
  options.OptimizeLevelStyleCompaction();
  options.create_if_missing = true;
  options.PrepareForBulkLoad();
  options.unordered_write=true;

  options.allow_mmap_reads = true;
  table_options.filter_policy.reset(rocksdb::NewBloomFilterPolicy(10, true));
  table_options.no_block_cache = true;
  table_options.block_restart_interval = 4;
  table_options.block_size = 16 * 1024;
  options.table_factory.reset(rocksdb::NewBlockBasedTableFactory(table_options));
  options.max_open_files = -1; 
  options.env->SetBackgroundThreads(4);
  options.compaction_style = rocksdb::kCompactionStyleLevel;
  options.write_buffer_size = 134217728; // 128MB
  options.max_write_buffer_number = 4;
  options.min_write_buffer_number_to_merge = 3;
  options.target_file_size_base = 134217728; // 128MB
  options.max_background_compactions = 4;
  options.level0_file_num_compaction_trigger = 8;
  options.level0_slowdown_writes_trigger = 17; 
  options.level0_stop_writes_trigger = 24; 
  options.num_levels = 4;
  options.max_bytes_for_level_base = 671088640; // 512MB
  options.max_bytes_for_level_multiplier = 8;
  options.level_compaction_dynamic_level_bytes = true;
```

The read time and write time increased exaggeratively, is this normal? Any suggestions?
Btw, the memtables_usage also increased quickly and finally caused OOM, how to limit the memory usage?

**Comment by mrambacher** [comment]
Can you give an idea on how you were producing these numbers?  What tool were you using?  What was the key and value sizes?  How many read/write threads were there?  How were the keys generated for read/write?  Were the reads and writes happening in parallel or did you write N keys and then read them and then write another chunk?

On the OOM, can you track the memory utilization over time? 

Most likely, you hit either some write limiter or compaction was involved slowing the writes down or consuming your I/O bandwidth, but that is hard to tell without more information.

**Comment by yinciki** [comment]
> Can you give an idea on how you were producing these numbers? What tool were you using? What was the key and value sizes? How many read/write threads were there? How were the keys generated for read/write? Were the reads and writes happening in parallel or did you write N keys and then read them and then write another chunk?
> 
> On the OOM, can you track the memory utilization over time?
> 
> Most likely, you hit either some write limiter or compaction was involved slowing the writes down or consuming your I/O bandwidth, but that is hard to tell without more information.

Thanks for your reply. The detailed info is listed as follows

Can you give an idea on how you were producing these numbers? 
"write key size/read key size" means the put/get kv num, "time" means the time consumed by the db->Write/db->MultiGet and 
"num of total keys in db" is from the function db->GetAggregatedIntProperty("rocksdb.estimate-num-keys", &num_keys);

What tool were you using?
If you mean the timekeeping, I just used a timer. 

What was the key and value sizes?
The key size was 8 bytes, there were two kinds of value size: 736 bytes.

How many read/write threads were there?
I did not specify this except this option: options.env->SetBackgroundThreads(4); 
There were 8 rocksdb processes running in parallel, but they were separate and write to different paths. 

How were the keys generated for read/write?
The keys were simply hashed unit64_t from some dataset which represented feature_ids. 

Were the reads and writes happening in parallel or did you write N keys and then read them and then write another chunk?
They were not in parallel. Write happened before read. 

On the OOM, can you track the memory utilization over time?
Yes, I tracked the index_filter_block_usage and the memtables_usage, their usage grew as follows:
index_filter_block_usage = 0 memtables_usage = 2422212608
index_filter_block_usage = 0 memtables_usage = 2298480640
index_filter_block_usage = 0 memtables_usage = 2422212608
index_filter_block_usage = 0 memtables_usage = 2298480640
index_filter_block_usage = 0 memtables_usage = 14622574840
index_filter_block_usage = 0 memtables_usage = 13986138952
index_filter_block_usage = 0 memtables_usage = 14622574840
index_filter_block_usage = 0 memtables_usage = 13986138952
index_filter_block_usage = 0 memtables_usage = 36636738216
index_filter_block_usage = 0 memtables_usage = 35246919360
index_filter_block_usage = 0 memtables_usage = 51325307032
index_filter_block_usage = 0 memtables_usage = 35246919360
index_filter_block_usage = 208 memtables_usage = 17138976768
index_filter_block_usage = 208 memtables_usage = 16595814400
index_filter_block_usage = 208 memtables_usage = 36734235368
index_filter_block_usage = 208 memtables_usage = 35573812312

As a matter of fact, the memory was not totally occupied by rocksdb, but the db's memory usage kept growing and finally caused OOM.

**Comment by mrambacher** [comment]
> Can you give an idea on how you were producing these numbers? "write key size/read key size" means the put/get kv num, "time" means the time consumed by the db->Write/db->MultiGet and "num of total keys in db" is from the function db->GetAggregatedIntProperty("rocksdb.estimate-num-keys", &num_keys);

Was your test using Get or MultiGet? If MultiGet, how many keys were you getting in a batch?

> What tool were you using? If you mean the timekeeping, I just used a timer.

Were the metrics gathered via db_bench or some other utility?  Can you share that utility?

> What was the key and value sizes? The key size was 8 bytes, there were two kinds of value size: 736 bytes.
> 
> How many read/write threads were there? I did not specify this except this option: options.env->SetBackgroundThreads(4); There were 8 rocksdb processes running in parallel, but they were separate and write to different paths.

The 8 processes that were running in parallel, what were they doing?  Could they have been competing for resources?  Were all of them experiencing the same performance?

> How were the keys generated for read/write? The keys were simply hashed unit64_t from some dataset which represented feature_ids.
> 
> Were the reads and writes happening in parallel or did you write N keys and then read them and then write another chunk? They were not in parallel. Write happened before read.

Can you please give more details on how you were doing the tests?  For example, you wrote N keys in K iterations, presumably resulting in N*K unique keys in the database or is it N keys?  When you perform a read, were you reading against the entire keyspace all of the time (N*K) or just a subset?  Do you know how often the reads successfully returned a value versus "key not found"?

**Comment by yinciki** [comment]
>Was your test using Get or MultiGet? If MultiGet, how many keys were you getting in a batch?

MultiGet, the number of keys were listed as the read key size, i.e. 129093, 244723...

>Were the metrics gathered via db_bench or some other utility? Can you share that utility?

I uploaded the code and LOG, please check it. Please note that functions InitializeRocksDB, DumpOnlineFormatValues, QueryAsyncOnlineFormat were been used to initialize the db, write and read respectively.

>The 8 processes that were running in parallel, what were they doing? Could they have been competing for resources? Were all of them experiencing the same performance?

There were 8 gpus(processes) doing the training process together. They were separated and might only compete for the memory. But I tried with single process, the rocksdb performance was similar.

>For example, you wrote N keys in K iterations, presumably resulting in NK unique keys in the database or is it N keys? 

The upper bound is N*K, but there might be some duplicates and thus the db size was always growing up.

>When you perform a read, were you reading against the entire keyspace all of the time (NK) or just a subset?

It was reading from the whole key space.

>Do you know how often the reads successfully returned a value versus "key not found"?

Yes.  I added the miss size :
read:
read key size: 129093 time:0.530049s num of total keys in db:2887843 miss: 2149
read key size: 244723 time:1.54977s num of total keys in db:8818742 miss: 4220
read key size: 344095 time:2.55462s num of total keys in db:17799862 miss: 7075
read key size: 425377 time:4.65428s num of total keys in db:29813991 miss: 11656
read key size: 501021 time:4.07396s num of total keys in db:44869844 miss: 19219
read key size: 566703 time:6.32499s num of total keys in db:62959572 miss: 29975
read key size: 629516 time:6.45402s num of total keys in db:39147167 miss: 45591
read key size: 697774 time:23.9644s num of total keys in db:63301526 miss: 65836


[test.zip](https://github.com/facebook/rocksdb/files/9489010/test.zip)

**Comment by mdcallag** [comment]
This is an interesting problem. Most of us don't have much experience with mmap for reads.

For the usage of MultiGet to read up to ~64M keys in one call, I don't know enough about the implementation to understand the memory consumption implications. I assume that data blocks containing the found keys will be pinned Hopefully an expert has an answer for that including why this shows up as memtable usage per:
```
db->GetProperty("rocksdb.cur-size-all-mem-tables", &memtables_usage);
```

But from looking at the [MultiGet implementation](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/db.h#L668) when it is used to fetch N keys:
* it allocates a vector, user_keys, of size N for those keys
* it allocators a vector, cf, of size N for the matching column family pointers
* it returns up to N values via "values". I assume those can pin things in memory (memtable, data blocks) 

In your case N can be large

**Comment by ajkr** [comment]
It looks like you are performing writes with 10+GB of data.

```
Interval writes: 2 writes, 33M keys, 2 commit groups, 1.0 writes per commit group, ingest: 24004.10 MB, 40.01 MB/s
Interval WAL: 2 writes, 0 syncs, 2.00 writes per sync, written: 23.44 GB, 40.01 MB/s
```

We don't split memtables in the middle of a write operation, so even though you configured write_buffer_size=128MB, it will produce 10+GB memtables. Then with `min_write_buffer_number_to_merge == 3` it can buffer 40+GB memtable data before one flush:

```
2022/09/02-22:45:58.212860 140458156095232 EVENT_LOG_v1 {"time_micros": 1662129958212848, "job": 2, "event": "flush_started", "num_memtables": 3, "num_entries": 62960536, "num_deletes": 0, "total_data_size": 48227770576, "memory_usage": 49451374760, "flush_reason": "Write Buffer Full"}
```

I suspect MultiGet() does not pin memtables (yet) so should do an allocation/copy for values found in memtable. This was recently fixed for GetMergeOperands() in #10458 and could be fixed for MultiGet() similarly. But for this use case I think the first step should be to break up the writes into smaller write operations and see what happens.

**Comment by yinciki** [comment]
@ajkr Thank you for your suggestion, I did split the original write batches into much smaller batches and the write operations time consumption seems more stable, but the MultiGet still took longer and longer time to finish. Is it the same case that smaller  
MultiGet operations might help?
[LOG.zip](https://github.com/facebook/rocksdb/files/9553292/LOG.zip)

**Comment by yinciki** [comment]
@ajkr I tried to split the MultiGet into small chunks, but it did not work. It turned out the MultiGet process still got slower and slower, any suggestions?

**Comment by ajkr** [comment]
In the provided LOG file, the number of L0 files is always growing, which is due to disable_auto_compactions=1. This at least costs extra CPU on the read side since every L0 file at least needs to have its filter checked for each key.
