### ISSUE TITLE
Minor version bump backwards compatibility

### ISSUE THREAD

**Issue by asad-awadia** [facebook/rocksdb#10623]
Upgraded from Rocksdb 6.4.6 to 6.22.1 but now I can't go back?

Once the DB folder has been upgraded you can't go back down? Even with minor version bumps?

Seeing errors like

```
org.rocksdb.RocksDBException: Unknown Footer version. Maybe this file was created with newer version of RocksDB?
```

**Comment by adamretter** [comment]
Sorry to hear about that. I'm afraid RocksDB does not follow Semver versioning... So there is not a major/minor release guarantee of backwards files compatibility.

**Comment by ajkr** [comment]
6.19 changed default format_version to 5, which is readable by 6.6 or later. You could try full compaction using 6.22 with format_version <= 4 and then downgrade. But keep in mind these are very old versions missing lots of bug fixes.

**Comment by asad-awadia** [comment]
@ajkr 

1. "You could try full compaction using 6.22 with format_version <= 4 " How do I do this? at 6..22 the format version is already 5

2. Is there a script or tool that can be run or written to bring the DB back to the old format [6.4 from 6.22]
