### ISSUE TITLE
the ldb tool ignores the `—column_family=` parameter with the `compact` command

### ISSUE THREAD

**Issue by ytrezq** [facebook/rocksdb#10630]
Took a while to understand why `ldb compact` always does nothing but after debugging in turns out the column family is never passed to `CompactRange`.
Please fix this !

**Comment by anand1976** [comment]
@ytrezq Can you share the exact commands used to create the DB and then compact it?

**Comment by ajkr** [comment]
I tried `./ldb compact --db=./tmp-db/ --column_family=column_family_name_000009`, and verified it compacted "column_family_name_000009" and nothing else
