### ISSUE TITLE
gorocksdb run error

### ISSUE THREAD

**Issue by Rongze92** [facebook/rocksdb#10643]
# github.com/lni/dragonboat/v3/internal/logdb/kv/rocksdb/gorocksdb
In file included from ../../../../pkg/mod/github.com/lni/dragonboat/v3@v3.2.6/internal/logdb/kv/rocksdb/gorocksdb/db.go:7:
In file included from ./extended.h:22:
/usr/local/include/rocksdb/version.h:7:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 error generated.

**Comment by ajkr** [comment]
I think `#include <string>` is correct code. Perhaps the build machine is not set up correctly. Can you google "fatal error: 'string' file not found"  and tried some of the suggestions?
