### ISSUE TITLE
WalManager::GetUpdatesSince return error if WalManager::PurgeObsoleteWALFiles is running in the same time

### ISSUE THREAD

**Issue by lnsphix** [facebook/rocksdb#10648]
WalManager::GetUpdatesSince return error:
```
IO error: No such file or directorywhile stat a file for size:
```

I guess the reason is that PurgeObsoleteWALFiles is running in the same time, and is deleting some files in archives, than `s = env_->GetFileSize(LogFileName(path, number), &size_bytes);` will return error in the function WalManager::GetSortedWalsOfType.

**Comment by lnsphix** [comment]
@igorcanadi
I see wal_manager.cc is mainly written by you, can you help to check if my guess is true or not? Thank you.

**Comment by ajkr** [comment]
Thanks, it turns out this is a known problem. Will use #5763 for tracking this issue.
