### ISSUE TITLE
GetApproximateSizes returns size 0 for existing keys

### ISSUE THREAD

**Issue by tanruixiang** [facebook/rocksdb#10733]
### Expected behavior
Returns the correct size.
### Actual behavior
GetApproximateSizes returns size 0 for existing keys.
### Steps to reproduce the behavior
Add the test case in `db_test.cc`.
```
TEST_F(DBTest, bugtest) {
  Options options = CurrentOptions();
  options.write_buffer_size = 10000;  
  options.compression = kNoCompression;
  options.create_if_missing = true;
  DestroyAndReopen(options);
  SizeApproximationOptions size_approx_options;
  size_approx_options.include_memtables = true;
  size_approx_options.include_files = true;
  auto default_cf = db_->DefaultColumnFamily();
  for(int i = 0; i < 30; i++){
    Put(Key(i), "");
  }
  uint64_t size;
  for(int i = 0; i < 25; i++){
   std::string start = Key(i);
   std::string end = Key(i+1);
   Range r(start, end);
   size = 0;
     ASSERT_OK(
      db_->GetApproximateSizes(size_approx_options, default_cf, &r, 1, &size));
    ASSERT_GT(size, 0);
  }
}
```

**Comment by cbi42** [comment]
Hi @tanruixiang, I think this is expected. In this case, keys are in a memtable and a rough estimate of the size of the given key range is returned (https://github.com/facebook/rocksdb/wiki/Approximate-Size#skiplist-memtable-size-estimation).

**Comment by tanruixiang** [comment]
> Hi @tanruixiang, I think this is expected. In this case, keys are in a memtable and a rough estimate of the size of the given key range is returned (https://github.com/facebook/rocksdb/wiki/Approximate-Size#skiplist-memtable-size-estimation).



> Hi @tanruixiang, I think this is expected. In this case, keys are in a memtable and a rough estimate of the size of the given key range is returned (https://github.com/facebook/rocksdb/wiki/Approximate-Size#skiplist-memtable-size-estimation).

Hi @cbi42 , If you set `write_buffer_size` very low and let the key enter SST, this problem will still occur. Only some keys will show size 0. May I ask is this as expected?
```
key000000 key000001 19
key000001 key000002 57
key000002 key000003 19
key000003 key000004 1121
key000004 key000005 19
key000005 key000006 19
key000006 key000007 19
key000007 key000008 19
key000008 key000009 1140
key000009 key000010 19
key000010 key000011 19
key000011 key000012 266
key000012 key000013 19
key000013 key000014 2109
key000014 key000015 19
key000015 key000016 19
key000016 key000017 19
key000017 key000018 19
key000018 key000019 19
key000019 key000020 0
key000020 key000021 19
key000021 key000022 57
key000022 key000023 76
key000023 key000024 19
key000024 key000025 19
```

**Comment by cbi42** [comment]
I think your output is still estimation from memtable. You can try do a `Flush()` after all keys are inserted, and you should see all estimation being 0. This is expected since the granularity of `ApproximateSize()` for SST files is at data block level, and in this case all keys are in the same data block. You can see more implementation detail in https://github.com/facebook/rocksdb/blob/07249fea8f999de65bb8cf9844366c1461362f44/memtable/inlineskiplist.h#L615 for memtable and https://github.com/facebook/rocksdb/blob/07249fea8f999de65bb8cf9844366c1461362f44/table/block_based/block_based_table_reader.cc#L2714 for table files.

**Comment by tanruixiang** [comment]
> I think your output is still estimation from memtable. You can try do a `Flush()` after all keys are inserted, and you should see all estimation being 0. This is expected since the granularity of `ApproximateSize()` for SST files is at data block level, and in this case all keys are in the same data block. You can see more implementation detail in
> 
> https://github.com/facebook/rocksdb/blob/07249fea8f999de65bb8cf9844366c1461362f44/memtable/inlineskiplist.h#L615
> 
> for memtable and
> https://github.com/facebook/rocksdb/blob/07249fea8f999de65bb8cf9844366c1461362f44/table/block_based/block_based_table_reader.cc#L2714
> 
> for table files.


Thanks a lot for your answer. You're right. I found out that key(19) counts more entries than key(20), resulting in a count of 0. I didn't delve into it, I'm guessing it's a problem with using `kBranching_`  to estimate the number of entries.
