### ISSUE TITLE
Very poor performance to *open* a database

### ISSUE THREAD

**Issue by seanofw** [facebook/rocksdb#10731]
I'm seeing unusually poor performance in a small project I've been working on.  I'm using RocksDB 7.5.3, and my program is written in C#.  I'm using the [curiosity-ai](https://github.com/curiosity-ai/rocksdb-sharp) bindings for RocksDB for C# (.NET 6), also v7.5.3.

I have a database with about 31,000 key/value pairs in it.  The database is used in write-once-read-many fashion:  It's created and populated initially, and then it's read many times.  When it needs to be "updated," the database is simply deleted entirely and then rebuilt.  The keys are short strings, on average about 8 bytes long each.  The values vary in size:  Most are 12 bytes long, but there are some larger values that have up to a few kilobytes of data.

Creating the database consists of starting with an empty directory, opening the database exactly once, `Put()`ing all 31,000 entries into it, and then closing it.  It is never written to again.  Whether this is efficient or not, I don't really care about write times, because writing is an offline process, and it can take as long as it wants; and its performance seems pretty good overall.

But for read times, I'm seeing really bizarre performance results being output from my program, like this:

```
Keyword DB: open: 1121.3 msec, read: 2.2 msec
```

A single `get()` operation takes 2.2 msec, which is very reasonable.  But that's only after it takes nearly a full second (!) for the call to `OpenReadOnly()`, which is bad.

I've instrumented the program so that the only thing it's measuring is the call to `OpenReadOnly()`.  Just to be sure there isn't something weird going on with the C# runtime, I made it perform `OpenReadOnly()` a few times in a row (closing each afterward), and measured just the time of the last few:  and they all take about 1.1 to 1.2 seconds.

If I create the database with only a dozen or so of the key/value pairs, the cost for `OpenReadOnly()` drops to just 8 msec, so the issue seems to be caused by the way RocksDB handles the data itself.

The write options for the database are not very fancy:
```
DbOptions options = new DbOptions()
options.SetCreateIfMissing(true);
options.SetCompression(Compression.Snappy);
RocksDb keywordDb = RocksDb.Open(options, "search/keywords");
```

The read options are even less fancy:
```
DbOptions dbOptions = new DbOptions();
dbOptions.SetKeepLogFileNum(1);
RocksDb keywordDb = RocksDb.OpenReadOnly(dbOptions, "search/keywords", false);
```

So is this behavior normal?  Is the time to open a database supposed to be proportional to the number of keys in it, or is there something wrong here?  Is there some operation I should be doing after building the database to "optimize" it?

I've attached the most recent `LOG` file.  Any help would be appreciated; I'm really not sure what else to look at now.

[LOG.txt](https://github.com/facebook/rocksdb/files/9638859/LOG.txt)

**Comment by cbi42** [comment]
Maybe the DB is reloading data from WAL during restart. Can you try do a `Flush()` or `CompactRange()` after all keys are written?

**Comment by seanofw** [comment]
I added both a `CompactRange()` and then a `Flush()`, just before closing the database, and that cut the time to open the database to only about 50 msec.  So I think you're right.  But this should probably be included in the documentation somewhere that in write-once-read-many (WORM) scenarios, compaction is a critical step, or you'll end up waiting for every read.
