### ISSUE TITLE
Disable compiler warnings on MS Windows builds

### ISSUE THREAD

**Issue by pin113** [facebook/rocksdb#10745]
### Expected behavior
A compiler warning is typically required if it has a high likelihood of flagging memory corruption, information disclosure, or double-free vulnerabilities. To resolve this issue, enable the indicated warning(s) by removing /Wxxxx switches (where xxxx is a warning id indicated here) from your command line, and resolve any warnings subsequently raised during compilation. 

### Actual behavior
The current build disables compiler warnings which are reported by [BinSkim](https://github.com/microsoft/binskim). BinSkim is a binary static analysis tool and [Microsoft is suggesting](https://learn.microsoft.com/en-us/windows-hardware/drivers/bringup/security-overview) to run BinSkim for best practices to improve the security of their products. BinSkim is part of the [MVI program](https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/virus-initiative-criteria?view=o365-worldwide) and it is our goal to meet the requirements of the [MVI program](https://learn.microsoft.com/en-us/microsoft-365/security/intelligence/virus-initiative-criteria?view=o365-worldwide).

**Comment by pin113** [comment]
Are there any plans to resolve this issue?

**Comment by adamretter** [comment]
Is there an accompanying Pull Request?

**Comment by pin113** [comment]
Is someone looking into this issue?

**Comment by rhubner** [comment]
Hello @pin113, 

Thank you for reporting this issue. I think your suggestions make sense, but I don't know how much RocksDB code is ready. I tried to remove some compiler flags and compile rocksdb and this are the results : 

- [4127](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4127?view=msvc-170) - ❌ Doesn't build
- [4800](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4800?view=msvc-170) - ✅ Build OK
- [4996](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-170) - ❌ Doesn't build
- 4351 - ✅ Build OK - Unable to find in MSVC documentation.
- [4100](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4100?view=msvc-170) - ❌ Doesn't build
- [4204](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4204?view=msvc-170) - ✅ Build OK 
- [4324](https://learn.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-4-c4324?view=msvc-170) - ❌ Doesn't build

I created PR #12205 for removing those who are working.

**Comment by ajkr** [comment]
> removing /Wxxxx switches (where xxxx is a warning id indicated here) 

Where is "here"? Should there be a list of warnings we can't disable with accompanying reasons?
