### ISSUE TITLE
Leaks on unloading

### ISSUE THREAD

**Issue by edouarda** [facebook/rocksdb#1077]
Currently RocksDB "leaks" memory on exit.

This is not a serious problem in itself as since the executable is exiting, it doesn't matter if not all resources are freed.

However it has the disadvantage of triggering a lot of false alerts (noise) in tools that track memory leaks.

It would therefore be really nice if RocksDB could capture the main thread exit and properly deallocate all structures. That problem is especially true on the Windows port where the main thread exit is ignored.

It may also require adding "UnsafeCleanXXX" function in the environement as you may want to manually destroy some object when you know your application is exiting.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
