### ISSUE TITLE
rockstable run error : IO error No such file or directory

### ISSUE THREAD

**Issue by followheart** [facebook/rocksdb#1079]
when my rocksdb instance run a few time , i find some error in rocksdb LOG,

2016/04/14-15:46:14.280843 7f68a4bff700 Move log file ./db_data/rt_mc_1_11/089425.log to ./db_data/rt_mc_1_11/archive/089425.log -- OK
2016/04/14-15:46:14.280885 7f68a4bff700 Move log file ./db_data/rt_mc_1_11/089426.log to ./db_data/rt_mc_1_11/archive/089412.log -- OK
2016/04/14-15:46:14.280931 7f68a4bff700 Move log file ./db_data/rt_mc_1_11//089425.log to ./db_data/rt_mc_1_11/archive/089427.log -- IO error: ./db_data/rt_m
c_1_11//089427.log: No such file or directory
2016/04/14-15:46:14.280953 7f68a4bff700 Move log file ./db_data/rt_mc_1_11//089426.log to ./db_data/rt_mc_1_11/archive/089426.log -- IO error: ./db_data/rt_m
c_1_11//089426.log: No such file or directory

this situation only happen in PurgeObsoleteFiles()---->wal_manager_.ArchiveWALFile(fname, number),
i am confused that why this happen twice? is this error very bad ?

**Comment by followheart** [comment]
@siying , do you have any idea about this?

**Comment by siying** [comment]
This should be harmless, right?

**Comment by followheart** [comment]
thanks for answering so quckily，
yes，ithis is harmless in the production environment ，but i want to know why this is happen? this should be only delete one time correctly, is it? 
in my case，my rocksdb suddleny uses cpu as much as 80% in some time....when i read runtime log,i find this error info, then i want to know detail, although maybe this is not the main causes..

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
