### ISSUE TITLE
RocksDB JNI SIGSEGV on retrieving RockDB properties

### ISSUE THREAD

**Issue by OStevan** [facebook/rocksdb#10808]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
RocksDB causes memory corruption which in turn triggers a JVM crash when trying to obtain rocksdb properties such as "rocksdb.live-sst-files-size".

### Actual behavior
Every 30 seconds we try to obtain a set of rocksdb properties for purposes of tracking perf and RockDB status. However, at random points in time we get null pointer dereference that causes JVM crashes.

```java
    private final OptimisticTransactionDB db;

    public long liveSstFilesSize() {
        return getProperty("rocksdb.live-sst-files-size");
    }

    public long baseLevel() {
        return getProperty("rocksdb.base-level");
    }

    public long numRunningCompactions() {
        return getProperty("rocksdb.num-running-compactions");
    }

    public long compactionPending() {
        return getProperty("rocksdb.compaction-pending");
    }

    public long numRunningFlushes() {
        return getProperty("rocksdb.num-running-flushes");
    }

    public long numImmutableMemTable() {
        return getProperty("rocksdb.num-immutable-mem-table");
    }

    public long backgroundErrors() {
        return getProperty("rocksdb.background-errors");
    }

    public long curSizeAllMemTables() {
        return getProperty("rocksdb.cur-size-all-mem-tables");
    }

    public long numEntriesImmMemTables() {
        return getProperty("rocksdb.num-entries-imm-mem-tables");
    }

    public long numDeletesImmMemTables() {
        return getProperty("rocksdb.num-deletes-imm-mem-tables");
    }

    public long estimateNumKeys() {
        return getProperty("rocksdb.estimate-num-keys");
    }

    public long numLiveVersions() {
        return getProperty("rocksdb.num-live-versions");
    }

    public long numSnapshots() {
        return getProperty("rocksdb.num-snapshots");
    }

    private long getProperty(String property) {
        try {
            return db.getLongProperty(property);
        } catch (RocksDBException e) {
            return -1;
        }
    }
```

### Steps to reproduce the behavior

The version we are currently on is `org.rocksdb:rocksdbjni:7.4.4`.
We could not reproduce it reliably in a simple manner but it's happening, the best we have are the JVM crash logs
[rocks_crash.txt](https://github.com/facebook/rocksdb/files/9766183/rocks_crash.txt)

**Comment by alanpaxton** [comment]
Hi Stevan, are you able to provide a full repro program for this issue ? It would really help to track down what is going wrong. What is happening when "RocksDB causes memory corruption" ?
Has the database already been closed or stopped when you retrieve the properties ?

**Comment by OStevan** [comment]
Hi @alanpaxton , thanks for the answer.

Last week after opening the issue I managed to find a race condition. We were in fact retrieving properties after closing the DB. We fixed the race condition and we haven't experienced any JVM crashes since then. Since that seems to be the issue I'm happy to close this issue.

Is there a reason why a RocksDBException isn't thrown? Is it expected that this brings down the JVM?

**Comment by alanpaxton** [comment]
Hi @OStevan , thanks for getting back to me.

It definitely sounds like the race condition is the cause of the problem.

The reason a RocksDBException isn't thrown is that many of the JNI methods just don't check for a closed database, so the result is a call into C++ with pointers to deallocated RocksDB state, which ends in the kind of crash you saw.
The reason checks aren't made is because the Java API is meant to prefer performance over safety; it just gets out of your way and lets you get to RocksDB. Which makes it your responsibility to ensure you don't access a closed DB, or suffer an undecipherable crash. This is kind of natural for C++ programmers, but very strange for Java programmers.

We often talk about making a "safer" interface (and it would be very interesting to try it with the new Project Panama native interfaces), but in the end it needs fb/Meta to support that sort of work.

**Comment by OStevan** [comment]
Thanks for the comprehensive answer, hopefully "safer" interfaces become a reality in future.

In any case I'm closing this issues as it was a bug in our code.
