### ISSUE TITLE
Streaming replication in RocksDB Java

### ISSUE THREAD

**Issue by rahulxxarora** [facebook/rocksdb#10836]
I was referring to the Wiki page to find some answers for implementing a streaming replication feature. I came across this page -- https://github.com/facebook/rocksdb/wiki/Replication-Helpers#function-for-streaming-updates-and-catching-up

From what I could understand, it says that the master node can use the getUpdatesSince() method to get the transactional logs and then the same logs can be applied to the slaves by using the putLogData() on a (possibly) remote node.

I'm having difficulty in implementing this because the getUpdatesSince() returns an iterator in the transactional logs and the putLogData() takes a byte array. How do I combine these two? What am I missing here? I couldn't find a working example of this in Java anywhere. 

Also, are there any caveats of using the same that I should be careful about?

**Comment by siying** [comment]
I think the expected way of updating in the secondary side is to directly do DB::Write(), rather than putting logs.

**Comment by rahulxxarora** [comment]
One question though, how does the slave know what all write options are to be used with this log statement?

Currently, I've implemented the functionality of applying the logs like this:

```
public void applyTransactionLogs(List<byte[]> transactionLogs) throws RocksDBException {
    WriteBatch writeBatch = new WriteBatch();
    for (byte[] transactionLog: transactionLogs) {
        writeBatch.putLogData(transactionLog);
    }
    this.rocksDB.write(new WriteOptions(), writeBatch);
}
```

**Comment by rahulxxarora** [comment]
The behaviour I'm seeing with the above code is that the logs are copied in the secondary instance but the data is not visible in the queries. What am I doing wrong here?

**Comment by siying** [comment]
> )
I think the expect way is to construct a WriteBatch using new WriteBatch(serialized) in the destination side. putLogData() is not for it at all.

Another way is to use WriteBatch.iterate() to extract all contents, serialize over the wire using the format you would like and insert them into target DB.

**Comment by rahulxxarora** [comment]
This helps, thanks.
