### ISSUE TITLE
RocksDB secondary instance not following up with primary

### ISSUE THREAD

**Issue by rahulxxarora** [facebook/rocksdb#10834]
I'm using RocksDB as a secondary instance in one of my service nodes. The other node runs as primary on a different VM. I was trying to see how can I manually replicate data from primary to secondary without the use of a distributed file system so, I generated a snapshot in the primary instance and copied it to the secondary instance and started my service (on secondary node). This was working fine till now, the secondary node was able to load up the data of the primary node on startup.

But then, I did the same thing again to see if the new updates are added in the secondary or not after copying the new snapshot to secondary node and calling tryCatchUpWithPrimary(). Unfortunately, the secondary node didn't pick up the new data.

Is that expected?

**Comment by ajkr** [comment]
Yes, it sounds expected since the secondary is operating on a copy of the DB, not the same DB as the primary. They need to access the same DB, for example, on a distributed file system.
