### ISSUE TITLE
Does the SSTable on the last level have a Bloom filter?

### ISSUE THREAD

**Issue by HBSDLJZ** [facebook/rocksdb#10935]
Does the SSTable on the last level have a Bloom filter?

**Comment by ajkr** [comment]
Yes if you set a `filter_policy` and `optimize_filters_for_hits == false`. Otherwise no.

**Comment by patelprateek** [comment]
@ajkr : do we need to set filter policy for lowest levels ?

Does filter help in query read performance if all data is compacted and in lowest level ?  I assume no 

iiuc , for mid levels after we do a binary search on filematadata (sst file index)  and find a target file whose range might contain key, filter can help in deciding whether to read this file or move to next level . In case binary search gives a file whose range doesnt contain search key , we dont need filter and can proceed to next level

For the lowest level do we also use a filter ? can filter in lowest level help in improving query performance assuming we are searching mostly for keys that are present in our DB

**Comment by ajkr** [comment]
> can filter in lowest level help in improving query performance assuming we are searching mostly for keys that are present in our DB

Under that assumption, no. That's why the option for disabling bottom level file filter is called `optimize_filters_for_hits` - if a query is a hit (i.e., `Get()` finds the lookup key), then a bottom level file filter could not have helped.

**Comment by patelprateek** [comment]
@ajkr : `optimize_filters_for_hits` , is my understanding correct that the hits we are talking about is cache hit rate i.e not having filters at lowest level would allow more cache space to be used for blocks . the hits are not talking about optimizing the bloom filters size i.e bits/hash used  for decreasing false positive hit rate  ?
In case keys dont exist (DB can be queries with keys that might not exist in DB) , then the bloom filter would help with faster lookup response ?
