### ISSUE TITLE
Dependency on AWS SDK

### ISSUE THREAD

**Issue by shuzhang1989** [facebook/rocksdb#1094]
Hi,

I am thinking to write an S3 environment for rocksdb, turned out we can leverage the AWS cpp sdk (https://github.com/aws/aws-sdk-cpp), but I wonder what's the best practice here to wind a 3rd party lib into rocks db?

**Comment by dhruba** [comment]
This is a great initiative. Is the change all localized to a new rocksdb::Env?

We have similar integration of rocksdb + HDFS, see https://github.com/facebook/rocksdb/blob/master/util/env_hdfs.cc. If you can create a similar file for S3, that would be awesome!

**Comment by shuzhang1989** [comment]
@dhruba yes, my assumption is that we can create another environment implementation separately.
The HDFS integration has the assumption that the user has HDFS library installed by themselves. Should we also push the responsibility of installing AWS sdk to users, or Rocksdb itself will integrate necessary aws libraries? Looks there is a third-party folder there.

**Comment by dhruba** [comment]
My vote would be to make the user install the S3 libraries outside of rocksdb, but have a env_s3.cc inside of the rocksdb code. Basically, follow the same structure that we have done for HDFS

**Comment by shuzhang1989** [comment]
@dhruba SGTM, thanks!

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
