### ISSUE TITLE
Hi,I have some questions about a db api of OpenForReadOnly

### ISSUE THREAD

**Issue by yangwu200799** [facebook/rocksdb#1097]
I describe my requirement as follows:
I have two client of database, they are in two different processes,one has write and read request of database called A,another has only read request of database called B. Now A writes into database without a stop. I want that B can read the real time updates of database written by A.
I see that rocksdb has an api  OpenForReadOnly. But it seems that B can only read the snapshot when B uses OpenForReadOnly. I don't know how can B reads the updates written by A after OpenForReadOnly. 

Thanks

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
