### ISSUE TITLE
How to partial merge deletion of last item in list

### ISSUE THREAD

**Issue by adamretter** [facebook/rocksdb#1098]
I have a Merge Operator which maintains a list of values. I merge values to the database like:

```
db->Merge("key1", "ADD_X")
db->Merge("key1", "DEL_X")
```

In my `MergeOperator::PartialMerge` I receive the parameters:

* `left_operand` = `ADD_X`
* `right_operand` = `DEL_X`

An add for "X" followed by a delete for "X" effectively cancels out the operations on "X". I am assuming that I should return `true` as I was able to process the operands, however I am wondering what I should set `new_value` to, should it be `nullptr` or an empty string? or something else?

**Comment by dhruba** [comment]
1. return false from PartialMerge if you want to handle this as a FullMerge.
2. return true but set new_value="EMPTY", so that when a FullMerge occurs later, then you can handle it appropriately.
3. You can also setup CompactionFilter to drop keys where value="EMPTY"

**Comment by adamretter** [comment]
@dhruba Thank you very much, I already had (3) so I have implemented (2) and it seems to be working well. I also had to extend my PartialMerge to handle merging where left and right are both `EMPTY` :-)
