### ISSUE TITLE
Facing issue with WAL file deletion for few WAL options.

### ISSUE THREAD

**Issue by saranya20222** [facebook/rocksdb#11000]
Hi Team,
Observing the below two behaviour with respect to rocksdb WAL confguration.

Issue1:
Configuration:
max_total_wal_size=67108864
WAL_size_limit_MB=256
WAL_ttl_seconds=30

When we set wal_size_limit_mb to 256 MB and also wal_ttl_seconds to 30 sec, WAL files are not getting checked and cleared after every 30 secs even though archive directory reaches configured 256 MB limit.
**Observation:** With these configurations (wal_size_limit_mb to 256 MB and wal_ttl_seconds to 30 sec), we can see WAL files in archive directory are getting cleared only after 10th min. Could you please suggest is there any configuration to reduce default 10mins?

Issue2:
when we set only the wal_ttl_seconds to 30sec, we can see logs are getting cleared during load. But once we stop the load (When there is no write to WAL files), the WAL files are not getting cleared after 30sec. Is this the expected behaviour?

**Comment by 1522140840** [comment]
I have also encountered similar problems, and I feel that it is related to using multiple CFs; Have you solved this problem?

**Comment by git-hulk** [comment]
@saranya20222 I guess not.

It will check WAL files every 10 minutes if you both set wal_ttl_seconds and wal_size_limit_mb, refer: https://github.com/facebook/rocksdb/blob/dfaf4dc111ff090800f2765fdcd88d48a6abbab8/include/rocksdb/options.h#L827

And the option comment has also mentioned this: https://github.com/facebook/rocksdb/blob/dfaf4dc111ff090800f2765fdcd88d48a6abbab8/include/rocksdb/options.h#L827

**Comment by 1522140840** [comment]
my rocksdb Configuration:

 Options.WAL_ttl_seconds: 300
 Options.min_write_buffer_number_to_merge: 1
 Options.write_buffer_size: 67108864

but i find total 83 wal log files in db path; It's been four hours and the log hasn't been deleted yet

```
-rw-r--r-- 1 work work   57M Nov 10 11:09 292063.log
-rw-r--r-- 1 work work   57M Nov 10 11:11 292072.log
-rw-r--r-- 1 work work   58M Nov 10 11:14 292074.log
-rw-r--r-- 1 work work   58M Nov 10 11:16 292076.log
-rw-r--r-- 1 work work   58M Nov 10 11:19 292078.log
-rw-r--r-- 1 work work   58M Nov 10 11:21 292086.log
-rw-r--r-- 1 work work   57M Nov 10 11:24 292088.log
-rw-r--r-- 1 work work   57M Nov 10 11:26 292090.log
-rw-r--r-- 1 work work   57M Nov 10 11:29 292092.log
-rw-r--r-- 1 work work   57M Nov 10 11:31 292100.log
-rw-r--r-- 1 work work   58M Nov 10 11:33 292102.log
-rw-r--r-- 1 work work   57M Nov 10 11:36 292104.log
-rw-r--r-- 1 work work   57M Nov 10 11:39 292106.log
-rw-r--r-- 1 work work   58M Nov 10 11:41 292115.log
-rw-r--r-- 1 work work   58M Nov 10 11:44 292117.log
-rw-r--r-- 1 work work   58M Nov 10 11:46 292119.log
-rw-r--r-- 1 work work   58M Nov 10 11:49 292121.log
-rw-r--r-- 1 work work   58M Nov 10 11:52 292142.log
-rw-r--r-- 1 work work   58M Nov 10 11:55 292146.log
-rw-r--r-- 1 work work   58M Nov 10 11:58 292148.log
-rw-r--r-- 1 work work   58M Nov 10 12:01 292150.log
-rw-r--r-- 1 work work   58M Nov 10 12:04 292158.log
-rw-r--r-- 1 work work   58M Nov 10 12:08 292160.log
-rw-r--r-- 1 work work   58M Nov 10 12:12 292162.log
-rw-r--r-- 1 work work   58M Nov 10 12:16 292164.log
-rw-r--r-- 1 work work   58M Nov 10 12:20 292171.log
-rw-r--r-- 1 work work   58M Nov 10 12:24 292173.log
-rw-r--r-- 1 work work   58M Nov 10 12:28 292175.log
-rw-r--r-- 1 work work   58M Nov 10 12:32 292177.log
-rw-r--r-- 1 work work   58M Nov 10 12:37 292184.log
-rw-r--r-- 1 work work   58M Nov 10 12:41 292186.log
-rw-r--r-- 1 work work   58M Nov 10 12:45 292188.log
-rw-r--r-- 1 work work   58M Nov 10 12:50 292190.log
-rw-r--r-- 1 work work   58M Nov 10 12:54 292199.log
-rw-r--r-- 1 work work   58M Nov 10 12:58 292201.log
-rw-r--r-- 1 work work   58M Nov 10 13:02 292203.log
-rw-r--r-- 1 work work   58M Nov 10 13:06 292205.log
-rw-r--r-- 1 work work   58M Nov 10 13:10 292212.log
-rw-r--r-- 1 work work   58M Nov 10 13:14 292214.log
-rw-r--r-- 1 work work   58M Nov 10 13:18 292216.log
-rw-r--r-- 1 work work   58M Nov 10 13:21 292218.log
-rw-r--r-- 1 work work   58M Nov 10 13:25 292228.log
-rw-r--r-- 1 work work   58M Nov 10 13:28 292230.log
-rw-r--r-- 1 work work   58M Nov 10 13:32 292232.log
-rw-r--r-- 1 work work   58M Nov 10 13:35 292234.log
-rw-r--r-- 1 work work   58M Nov 10 13:38 292241.log
-rw-r--r-- 1 work work   58M Nov 10 13:41 292243.log
-rw-r--r-- 1 work work   58M Nov 10 13:43 292245.log
-rw-r--r-- 1 work work   57M Nov 10 13:46 292247.log
-rw-r--r-- 1 work work   58M Nov 10 13:49 292255.log
-rw-r--r-- 1 work work   58M Nov 10 13:52 292257.log
-rw-r--r-- 1 work work   58M Nov 10 13:55 292259.log
-rw-r--r-- 1 work work   58M Nov 10 13:58 292261.log
-rw-r--r-- 1 work work   58M Nov 10 14:00 292269.log
-rw-r--r-- 1 work work   58M Nov 10 14:03 292271.log
-rw-r--r-- 1 work work   58M Nov 10 14:05 292273.log
-rw-r--r-- 1 work work   58M Nov 10 14:08 292275.log
-rw-r--r-- 1 work work   57M Nov 10 14:11 292283.log
-rw-r--r-- 1 work work   58M Nov 10 14:13 292285.log
-rw-r--r-- 1 work work   57M Nov 10 14:16 292287.log
-rw-r--r-- 1 work work   58M Nov 10 14:18 292289.log
-rw-r--r-- 1 work work   57M Nov 10 14:21 292297.log
-rw-r--r-- 1 work work   58M Nov 10 14:23 292299.log
-rw-r--r-- 1 work work   58M Nov 10 14:26 292301.log
-rw-r--r-- 1 work work   57M Nov 10 14:28 292303.log
-rw-r--r-- 1 work work   57M Nov 10 14:31 292314.log
-rw-r--r-- 1 work work   58M Nov 10 14:33 292316.log
-rw-r--r-- 1 work work   58M Nov 10 14:36 292318.log
-rw-r--r-- 1 work work   58M Nov 10 14:38 292320.log
-rw-r--r-- 1 work work   57M Nov 10 14:41 292327.log
-rw-r--r-- 1 work work   58M Nov 10 14:43 292329.log
-rw-r--r-- 1 work work   58M Nov 10 14:46 292331.log
-rw-r--r-- 1 work work   57M Nov 10 14:48 292333.log
-rw-r--r-- 1 work work   58M Nov 10 14:51 292340.log
-rw-r--r-- 1 work work   58M Nov 10 14:53 292342.log
-rw-r--r-- 1 work work   58M Nov 10 14:56 292344.log
-rw-r--r-- 1 work work   58M Nov 10 14:59 292346.log
-rw-r--r-- 1 work work   58M Nov 10 15:01 292353.log
-rw-r--r-- 1 work work   58M Nov 10 15:04 292355.log
-rw-r--r-- 1 work work   58M Nov 10 15:06 292357.log
-rw-r--r-- 1 work work   58M Nov 10 15:09 292359.log
-rw-r--r-- 1 work work   46M Nov 10 15:11 292377.log
```

By printing the log, I found that VersionEdit.min_log_number_to_keep_ I don't think it's normal for keep to remain unchanged for a long time; I am looking at the source code here; I use muti cf.

![image](https://github.com/facebook/rocksdb/assets/27505826/2ee66515-6a4b-47b0-a85a-47fdd94c5544)



![image](https://github.com/facebook/rocksdb/assets/27505826/d18f3ac5-4a61-49c8-b3ea-5d0bf7fefb23)

**Comment by git-hulk** [comment]
@1522140840 Did you set the `max_total_wal_size`?

**Comment by 1522140840** [comment]
> @1522140840 Did you set the `max_total_wal_size`?

no ,i just set WAL_ttl_seconds; In another scenario, I only used the default CF and only set WAL_ Ttl_ Seconds, it work ok

**Comment by git-hulk** [comment]
`max_total_wal_size` will affect when logs can be deleted if you're using multi-column families. It will be set to `[sum of all write_buffer_size * max_write_buffer_number] * 4` by default.

**Comment by 1522140840** [comment]
If I have 6 cfs, is that my sum?  sum=256MB*40*6* 4

Multi CF just WAL_ttl_seconds not work？

write_buffer_size:256MB
max_write_buffer_number:40
![image](https://github.com/facebook/rocksdb/assets/27505826/965c808c-1b2d-4ce9-96e5-87dbac97bdbf)

**Comment by 1522140840** [comment]
Actually, my question is why expired logs were not moved to the archive directory

**Comment by 1522140840** [comment]
My question; One of my CF data writes is relatively small, which leads to a large number of WAL files being unable to be archived or deleted；

**Comment by ajkr** [comment]
> And the option comment has also mentioned this:
> 
> https://github.com/facebook/rocksdb/blob/dfaf4dc111ff090800f2765fdcd88d48a6abbab8/include/rocksdb/options.h#L827

Hm, this isn't very intuitive. I suspect that behavior was chosen for configs where `db_options_.WAL_ttl_seconds / 2 > 600`, which is normally the case when archived WAL TTL is enabled. Using `kDefaultIntervalToDeleteObsoleteWAL` (600) instead of `db_options_.WAL_ttl_seconds / 2` in that case guarantees we will check for size-based expiration regularly.

But this issue is asking about a case where `db_options_.WAL_ttl_seconds / 2 == 15`. We don't need to use `kDefaultIntervalToDeleteObsoleteWAL` in that case to guarantee regularity of size-based expiration.

I think maybe we can use `std::min(db_options_.WAL_ttl_seconds / 2, kDefaultIntervalToDeleteObsoleteWAL)` in this case, where both size-based and time-based expiration of archived WALs are enabled

**Comment by ajkr** [comment]
> Actually, my question is why expired logs were not moved to the archive directory

The knob you're setting (`WAL_ttl_seconds`) is the expiration time for already-archived logs. You also need a mechanism to make logs obsolete such that they will be archived in the first place. The suggestion above to set `max_total_wal_size` was good advice as it can serve this purpose.
