### ISSUE TITLE
Wrong argument order for Java WriteBatchWithIndex#iteratorWithBase

### ISSUE THREAD

**Issue by nicktelford** [facebook/rocksdb#11008]
### Expected behavior
`WriteBatchWithIndex#iteratorWithBase` is a JNI native method, defined as:

```
private native long iteratorWithBase(final long handle, final long baseIteratorHandle,
    final long cfHandle, final long readOptionsHandle);
```
The argument order here is:

1. `handle`
2. `baseIteratorHandle`
3. `cfHandle`
4. `readOptionsHandle`

Whereas the argument order in the JNI bridge is:

```
jlong Java_org_rocksdb_WriteBatchWithIndex_iteratorWithBase(
    JNIEnv*, jobject, jlong jwbwi_handle, jlong jcf_handle,
    jlong jbase_iterator_handle, jlong jread_opts_handle)
```

1. `handle`
2. **`columnFamilyHandle`**
3. **`baseIteratorHandle`**
4. `readOptionsHandle`

### Actual behavior

The argument order in the Java `native` method should reflect the argument order in the JNI bridge:

```
private native long iteratorWithBase(final long handle, final long cfHandle,
    final long baseIteratorHandle, final long readOptionsHandle);
```

**Comment by adamretter** [comment]
So the good news is, that this isn't actually a problem in practice as the call to the Java native method looks like:
```
iteratorWithBase(nativeHandle_, columnFamilyHandle.nativeHandle_,
            baseIterator.nativeHandle_, readOptions == null ? 0 : readOptions.nativeHandle_));
```

As the first two arguments are longs, there is no implementation issue.

I agree that the first two arguments in the native signature in Java should be swaped.

@nicktelford Would you like to send a PR?
