### ISSUE TITLE
Missing versions in GH releases

### ISSUE THREAD

**Issue by kwek20** [facebook/rocksdb#11018]
History doc mentions 7.8.0 and 7.9.0 but they're not released on github: https://github.com/facebook/rocksdb/releases.

### Expected behavior

Seeing all versions mentioned in https://github.com/facebook/rocksdb/blob/main/HISTORY.md

### Actual behavior

missing latest couple releases

**Comment by adamretter** [comment]
Not all versions are publicly released.
