### ISSUE TITLE
About secondary instance snapshot read

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#11021]
Why `DBImplSecondary::Get` support snapshot but `DBImplSecondary::NewIterator` does not support snapshot?

**Comment by rockeet** [comment]
I see, very thanks!

**Comment by rockeet** [comment]
BTW: Is there any plan to implement snapshot read on secondary instance?

**Comment by riversand963** [comment]
I think this is something that can be done in the future, and should not be too difficult once we have a scalable way of coordinating file deletions among primary and the secondaries.
Thanks @rockeet for the issue. I will close this one for now, feel free to reopen if necessary.
