### ISSUE TITLE
Question about `Transaction` without `DeleteRange`

### ISSUE THREAD

**Issue by AdjoiningCat** [facebook/rocksdb#11038]
Hi,

I find that `DeleteRange` can be used only in `db`, but not in `Transaction`.

What's the exactly reason for this?

**Comment by ajkr** [comment]
Some reasons for write-prepared were covered in #4812. The pieces to make it work for write-committed might be able to be pulled together from around the repo (e.g., range locking) and unreviewed PRs (e.g., #8260), but we wouldn't be able to support it well given the lack of internal users / low team bandwidth at the moment.
