### ISSUE TITLE
[BUG] timestamped reading a blob value says something corrupted

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#11056]
https://github.com/facebook/rocksdb/blob/bec4264813bd1c949be67cdba69d72143b0b25d9/db/blob/blob_file_reader.cc#L546

I'm trying the latest per-cf blob-format with timestamped reads/writes.
I found it didnt work because reader's userkey is different from writer's userkey in the last 8bytes timestamp part.

It seems the above comparation should trim the timestamp part,
Or just because timestamped read/writes have not been fully tested/supported in blobdb mode?

**Comment by ltamasi** [comment]
Right, this is a known issue (see #9818) - the combination of timestamps and blobs is not supported currently.
