### ISSUE TITLE
how to specify different level SST files into different storage 

### ISSUE THREAD

**Issue by gaowayne** [facebook/rocksdb#11076]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
For example, I would like to put low level SST files into fast SSD, and put high level SST into slower but high density SSD

### Actual behavior
I cannot find we can configure the SST files for different level separately

**Comment by cbi42** [comment]
You can use tiered storage feature to assign last level data to a different storage media: https://github.com/facebook/rocksdb/wiki/Tiered-Storage-%28Experimental%29
