### ISSUE TITLE
Performance for xxh3 on ARM is almost 1.5X better with latest code from xxHash repo

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#11073]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Perf from db_bench --benchmarks=xxh3 should be close on c6i.2xl (x86) and c7g.2xl (ARM)

### Actual behavior

Perf on x86 is much better

### Steps to reproduce the behavior

See my [blog post](http://smalldatum.blogspot.com/2023/01/rocksdb-microbenchmarks-hash-checksum.html).
Merging latest code from the the xxHash dev branch will help.

**Comment by pdillinger** [comment]
By the way, if you have time to test new XXH3 vs. CRC32c on ARM, I would consider changing the default back to CRC32c on ARM if it's faster.

**Comment by mdcallag** [comment]
Thanks for a quick fix. This doubles xxh3 perf on ARM

For each group of 3:
* first line is c7g (Arm) with RocksDB at e9d6a0d7 (commit prior to your fix)
* second line is c7g (Arm) with RocksDB at fd911f96 (your fix)
* third line is older result from c6i (x86)

So your change doubles perf for xxh3 on Arm, but x86 is still ~3x faster. 
I still consider this closed since it uses the latest from xxHash upstream.

```
xxh3         :       0.405 micros/op 2471705 ops/sec 0.518 seconds 1280000 operations; 9655.1 MB/s (4096 per op)
xxh3         :       0.245 micros/op 4086454 ops/sec 0.313 seconds 1280000 operations; 15962.7 MB/s (4096 per op)
xxh3         :       0.085 micros/op 11703285 ops/sec ...

xxh3         :       0.812 micros/op 1231868 ops/sec 0.520 seconds 640000 operations; 9624.0 MB/s (8192 per op)
xxh3         :       0.462 micros/op 2163024 ops/sec 0.296 seconds 640000 operations; 16898.6 MB/s (8192 per op)
xxh3         :       0.152 micros/op 6596850 ops/sec ...
```
