### ISSUE TITLE
Unreachable code warning/error in merging_iterator.cc on MSVC

### ISSUE THREAD

**Issue by clemahieu** [facebook/rocksdb#11072]
When compiling on Windows 11 Visual Studio 2022 I get unreachable code warnings/errors in merging_iterator.cc

1>merging_iterator.cc
1>Z:\nano-node.src\rocksdb\table\merging_iterator.cc(855): warning C4702: unreachable code
1>Z:\nano-node.src\rocksdb\table\merging_iterator.cc(1062): warning C4702: unreachable code

Both of these lines are range for loops:
` for (auto& i : active_) {`

**Comment by pdillinger** [comment]
Already fixed https://github.com/facebook/rocksdb/pull/10897
