### ISSUE TITLE
license issue in dbt.cc

### ISSUE THREAD

**Issue by vchhasatia** [facebook/rocksdb#11086]
Hello rocksdb team,

I am confused by license information in dbt.cc file. 
Other files have option to select from AGPL/GPL/Apache licenses. However, following file is under AGPL/GPL license
https://github.com/facebook/rocksdb/blob/0a2d3b663a962cf86af5ad82c80baf1cd71f7766/utilities/transactions/lock/range/range_tree/lib/util/dbt.cc

Will it be possible to add Apache 2.0 as an option in dbt.cc file?

**Comment by ajkr** [comment]
Duplicate of #10478

comment from the original PR author: https://github.com/facebook/rocksdb/pull/7753#issuecomment-740167538

upstream dbt.cc: https://github.com/percona/PerconaFT/blob/master/util/dbt.cc
