### ISSUE TITLE
Fix error: "tmp_cfid’ may be used uninitialized [-Werror=maybe-uninitialized]

### ISSUE THREAD

**Issue by codeoos** [facebook/rocksdb#11100]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

In file trace_reply/trace_reply.cc,it will be reported an error "error: ‘tmp_cfid’ may be used uninitialized [-Werror=maybe-uninitialized]" by g++-12.

*I'm a newbie,how can i push my commit to rocksdb? When i push my commit in a new branch ,git tell me that i don't have permission.*

### Expected behavior

compile successful

### Actual behavior

report error: ‘tmp_cfid’ may be used uninitialized [-Werror=maybe-uninitialized]

**Comment by cbi42** [comment]
Fixed in #11101.
