### ISSUE TITLE
[Question] Iterator Gabage collection in java

### ISSUE THREAD

**Issue by asad-awadia** [facebook/rocksdb#11142]
What happens if an iterator is not closed and is eventually garbage collected in the jvm? is native memory leaked?

Can iterators be garbage collected at all? or are they exempt?

Is GC good enough alternative to not closing them?

Asking because keeping an iterator open keeps underlying state open

**Comment by asad-awadia** [comment]
also what does `seek`ing to `null` mean? is that valid?

**Comment by adamretter** [comment]
> What happens if an iterator is not closed and is eventually garbage collected in the jvm? is native memory leaked?

So the `RocksIterator` class inherits from the `RocksObject` class. The `RocksObject` class is used wherever a light-weight Java object *owns* an underlying C++ object. When any `RocksObject` is closed, the underlying C++ object will be deleted/free'd from memory. The `RocksObject` can be closed by one of two routes:

1. Explicitly (or implicitly via try-with-resources) calling `RocksObject#close()`
2. In older versions of RocksDB, by the Java Garbage Collector invoking `RocksObject#finalize()`. This functionality was removed in https://github.com/facebook/rocksdb/pull/9523, and the user is now expected to always call `RocksObject#close()` themselves.

> Can iterators be garbage collected at all? or are they exempt?

After https://github.com/facebook/rocksdb/pull/9523 if an object is Garbage Collected before you call `RocksObject#close()` then you will leak memory in the form of the owned C++ object never being free'd.
