### ISSUE TITLE
RocksDB continuous benchmarks are backing up, and need regular cleansing

### ISSUE THREAD

**Issue by alanpaxton** [facebook/rocksdb#11169]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

The hourly continuous benchmarks (benchmark-linux, on main)should each complete in < 1 hr.

### Actual behavior

They are each taking 1h6m to run, and a queue of them is building up; the next benchmark will not run until the previous one has completed.

### Steps to reproduce the behavior

No steps required. This is happening as part of the automated CI runs.

We can see at [RocksDB CircleCI](https://app.circleci.com/pipelines/github/facebook/rocksdb) that there are a number of running `benchmark-linux` workflows outstanding; there should only ever be one.

The PR https://github.com/facebook/rocksdb/pull/11074 reduces the runtime back to under 1 hour.

Until the PR is merged, it is necessary for someone with CI permissions to regularly kill the outstanding workflows

**Comment by anand1976** [comment]
PR #11074 has been landed. Closing this issue.
