### ISSUE TITLE
CI Benchmarking uploads are failing (401). Can someone check the CI config for me ?

### ISSUE THREAD

**Issue by alanpaxton** [facebook/rocksdb#11190]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

In the "benchmark-linux" workflow in config.yml, the post-benchmark step "Send benchmark report to visualisation" should successfully upload contents of a generated report.tsv to an OpenSearch index.

### Actual behavior

The  step "Send benchmark report to visualisation" is failing internally with a 401 in ./benchmark_log_tool.py, suggesting that the ES_USER and/or ES_PASS environment variables are incorrectly configured in CircleCI. I have confirmed that the previously used values are still correct. I wonder if the CI was restarted in some way in early January ?

### Steps to reproduce the behavior

The "benchmark-linux" workflow is run hourly on CI. See https://app.circleci.com/pipelines/github/facebook/rocksdb/24181/workflows/caaf1cf7-0342-415d-8ac8-5e1ed630bcc9

If someone known to me from the meta team could contact me as alan at evolvedbinary dot com I can share what should be the correct values for these.

**Comment by ajkr** [comment]
Sent. I didn't think of any way they'd have changed but let us know if your info differs.

**Comment by alanpaxton** [comment]
Thanks Andrew. Emailed you back. I had wondered if they might have been reset. I can manually upload via the same script the benchmark uses with the credentials I have, so they should be enough to get things working again.

**Comment by ajkr** [comment]
Updated as discussed. Looks like it worked: https://app.circleci.com/pipelines/github/facebook/rocksdb/24308/workflows/1c00c9a1-adad-44e7-992f-11fc7153c798/jobs/567974. Let us know if anything still looks wrong

**Comment by alanpaxton** [comment]
Yes thanks Andrew, definitely working again, 201s in the "Send benchmark report to visualisation" and I'm seeing things on the OpenSearch graphs again now.
