### ISSUE TITLE
Nvcc complier 

### ISSUE THREAD

**Issue by raaka1** [facebook/rocksdb#1122]
I am using rocksdb on embedded system 
Linux tegra-ubuntu 3.10.67-g458d45c #1 SMP PREEMPT Mon Feb 8 17:44:18 PST 2016 aarch64 aarch64 aarch64 GNU/Linux

I have received following error, is this compiler related ?

```
 nvcc --std=c++11 TeraCore.cpp 
In file included from /usr/include/rocksdb/immutable_options.h:10:0,
                 from /usr/include/rocksdb/db.h:18,
                 from TeraCore.cpp:3:
/usr/include/rocksdb/options.h:69:32: error: enumerator value -1 is too large for underlying type ‘char’
   kDisableCompressionOption = -1,
```

**Comment by dhruba** [comment]
I think we can change the rocksdb code (in include/rocksdb/options.h)

kDisableCompressionOption = -1

to
kDisableCompressionOption = 0xff

Please verity  if this fixes your problem, and if it does, then submit a pull request for your rocksdb change.

**Comment by 4tXJ7f** [comment]
It seems like `0xff` does not work for compilers that define `char` to use the same representation as `signed char` [0]. Maybe also make the type `unsigned char` or `uint8_t`?

[0] http://coliru.stacked-crooked.com/a/d1ef43b27dac1fd3

**Comment by dhruba** [comment]
@4tXJ7f andres: your suggestion makes sense

**Comment by raaka1** [comment]
when i run `make install `

```
*** Error in `g++': double free or corruption (top): 0x0009e030 ***
Aborted
```

leveldb works fine tough

**Comment by vmorris** [comment]
#1160

**Comment by gnuowned** [comment]
Seen this same issue when try to compile ceph from GIT. Any proposed solution besides @vmorris one?

**Comment by raaka1** [comment]
I am using Jetson TK1 from Nvidia :)

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
