### ISSUE TITLE
[consult] how rocksdb implement hash partition and range partition?

### ISSUE THREAD

**Issue by littleDrew** [facebook/rocksdb#11235]
### Questition
- **how rocksdb implement hash partition and range partition**? Could someOne help to explain this for detail?
- how rocksdb do data partition in distribute cluster environment, what's the implement code directory in this repo? 
- if can sort out the implementation details of data partitioning from front to back, this will be nice for new user~

**Comment by ajkr** [comment]
The RocksDB user is responsible for partitioning the data, not RocksDB itself. You can find some RocksDB users listed in https://github.com/facebook/rocksdb/blob/main/USERS.md
