### ISSUE TITLE
RocksDB JNI 3.13.1 Snappy not linked error

### ISSUE THREAD

**Issue by nickpan47** [facebook/rocksdb#1127]
Hi, several reports from our users shows that they have encountered the following issue when using rocksdbjni-3.13.1 in CentOS and Redhat 6.6.

org.apache.samza.SamzaException: Error opening RocksDB store
xxx/Partition_6, received the following exception from RocksDB
org.rocksdb.RocksDBException: Invalid argument: Compression type Snappy is
not linked with the binary.
        at
org.apache.samza.storage.kv.RocksDbKeyValueStore$.openDB(RocksDbKeyValueStore.scala:81)
        at
org.apache.samza.storage.kv.RocksDbKeyValueStore.db$lzycompute(RocksDbKeyValueStore.scala:103)

Runtime environment: RedHat Enterprise Linux 6.6, Java 8 (Oracle 1.8.0_40)

Just a note: we have found earlier that the native lib loader in rocksdbjni-3.13.1 was not load by invoking constructor of FlushOption class (issue-989). Could it be related?

Is there any fix for this in the newer version of rocksdbjni versions?

Thanks!

**Comment by adamretter** [comment]
I believe that the latest released versions of rocksdbjni feature statically linked binaries which should help avoid such linking issues.

**Comment by nickpan47** [comment]
@adamretter thanks for the recommendation. I have opened a JIRA in Samza to upgrade the rocksdbjni version (SAMZA-955).
