### ISSUE TITLE
upgrading to rocks 7.9.2 demonstrated freezes

### ISSUE THREAD

**Issue by rolfyone** [facebook/rocksdb#11293]
Some teku (ethereum CL client) users use rocksdb, and our latest couple of releases went from Rocksdb 7.7.3 to 7.9.2.

We've had issues with occasional freezes. It may be something that we're doing that's unexpected, but I'm not really sure how to progress the issue, so our next release we'll go back to 7.7.3.

I was hoping to understand if it's a regression, or if it's something that we've done that's not really correct.  I have a couple of rocksdb logs, I was wondering if there were any red flags that might indicate a problem?

rocksdb db/LOG: https://pastebin.com/raw/SNyKM2m7
rocksdb archive/LOG: https://pastebin.com/raw/jC4Dv2aR

We have 2 database instances, both probably not super complicated I would have thought, but it's very possible that we're doing something that's odd...

The archive database can get quite large, probably in the order of 60GB, and the other one is more like less than a couple of GB... The archive one is mostly a write / read database, where as the other one is heavy on read/write/delete.

What we notice on our monitoring appears to be a deadlock, but it appears to eventually clear, presumably everything is waiting on data while this 'freeze' occurs...

Any observations would be welcome at this point...

**Comment by ajkr** [comment]
Few things that interested me in the LOG files -

- Lines like below without any intervening compactions suggest table readers are being evicted. You can set max_open_files=-1 to avoid this
```
2023/03/07-18:19:44.366240 140308967835200 [WARN] [ble/block_based/block_based_table_reader.cc:729] Another ~1000 SST files opened without unique ID to verify
2023/03/07-18:22:14.258714 140297589749312 [WARN] [ble/block_based/block_based_table_reader.cc:729] Another ~1000 SST files opened without unique ID to verify
2023/03/07-18:24:14.186287 140308998256192 [WARN] [ble/block_based/block_based_table_reader.cc:729] Another ~1000 SST files opened without unique ID to verify
```
- The block cache is tiny according to the stats, probably the default (8MB). Would be good to increase it according to how much free memory you have
```
Block cache entry stats(count,size,portion): DataBlock(32,2.92 MB,36.4779%) IndexBlock(5,52.91 KB,0.645828%) Misc(1,0.00 KB,0%)
```
- Block size is unusually large. I guess the KVs are large but the configured block size must be even bigger since the below line shows 4 entries (78899707 bytes) fit in 1 data block. Are you setting block_size to a non-default value?
```
2023/03/07-17:58:51.769194 140308981470784 EVENT_LOG_v1 {"time_micros": 1678211931769139, "cf_name": "default", "job": 252, "event": "table_file_creation", "file_number": 360079, "file_size": 78900706, "file_checksum": "", "file_checksum_func_name": "Unknown", "smallest_seqno": 42556353, "largest_seqno": 42556389, "table_properties": {"data_size": 78899707, "index_size": 21, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 1, "index_value_is_delta_encoded": 1, "filter_size": 0, "raw_key_size": 36, "raw_average_key_size": 9, "raw_value_size": 78899643, "raw_average_value_size": 19724910, "num_data_blocks": 1, "num_entries": 4, "num_filter_entries": 0, "num_deletions": 0, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "", "column_family_name": "default", "column_family_id": 0, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "NoCompression", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; max_dict_buffer_bytes=0; use_zstd_dict_trainer=1; ", "creation_time": 1678211927, "oldest_key_time": 1678211927, "file_creation_time": 1678211930, "slow_compression_estimated_data_size": 0, "fast_compression_estimated_data_size": 0, "db_id": "5f9c18e8-6b40-4711-bd61-f5c2f9c79ca1", "db_session_id": "VYB700VVTPV2AKYMM4PG", "orig_file_number": 360079, "seqno_to_time_mapping": "N/A"}}
```

**Comment by rolfyone** [comment]
We're storing some pretty big 'values' in a couple of tables, I think the states are about 50MB or so, and blocks are pretty big too in terms of the 'block size'...

All of this is awesome information, I'll look into them. I'm not sure why we don't see freezes on 7.7.3, but still the information on configuration is very helpful, thankyou.

**Comment by rolfyone** [comment]
It looks like we have max open files set to 128 by default.
Cache size was 8MB ish, confirmed.
We also have a large write buffer set, about 128MB, 
6 background threads...

We can likely bump a lot of this, I'll setup a test environment and have a play! Is any of this a likely candidate for freezes? I guess if queries are getting dropped, then the calling fn would have to wait for the query to time out?

**Comment by ajkr** [comment]
Slow reads waiting on I/O might appear as freezes. Write stalls could too though I don't recall seeing those in your LOG files. 

I couldn't identify any relevant change between 7.7.3 and 7.9.2. If you have more before vs. after data (e.g., disk bandwidth before vs. after, LOG files before vs. after, etc.), that might help.
