### ISSUE TITLE
Why does the tag of version 8 not exist?

### ISSUE THREAD

**Issue by silence-coding** [facebook/rocksdb#11297]
Why is there no tag for version 8? I see it already in HISTORY.md.  @ajkr 

https://github.com/facebook/rocksdb/blob/main/HISTORY.md#800-02192023

**Comment by adamretter** [comment]
@silence-coding That is in preparation for the upcoming release. 8.x.x has not yet been released, see - https://github.com/facebook/rocksdb/releases

**Comment by silence-coding** [comment]
Is the release time determined? @adamretter

**Comment by adamretter** [comment]
@silence-coding See Andrew's suggestion here - https://github.com/facebook/rocksdb/issues/11239#issuecomment-1458458366

**Comment by ajkr** [comment]
Yeah, still planning for March 17.
