### ISSUE TITLE
[Feature request] Add IngestExternalFile() to WriteBatch

### ISSUE THREAD

**Issue by socketpair** [facebook/rocksdb#11308]
In my scenario, I need to call DeleteRange() + IngestExternalFile() Atomically. Noway currently, without crutches.

**Comment by ajkr** [comment]
Can you call DeleteRange() on SstFileWriter when you build the file? The range tombstone and point keys would then be ingested with the same seqno. We made point keys override range tombstones in such cases specifically so IngestExternalFile() can atomically overwrite a range of keys

**Comment by socketpair** [comment]
Actually, in my case, I need to delete all the data from current DB before ingesting new SST file. No, I can't just remove DB or so, because there are other readers (in different processes) and they should not be interrupted. It's expected they will call `TryCatchUpWithPrimary()` in order to see new data.

If there is a better way - please tell me. Possible remove column family ?

**Comment by socketpair** [comment]
Regarding building of SST file. In documentation, it's said all the keys MUST be ordered. What about this operation (it consists of two keys) I guess all the operations must be ordered by the first keys if we speak about range operations. Right ? Or, possibly, only order of calling the function important in this case ?

I know, the SST file is a sorted list of k-v pairs. For tombstones for single deletion—everything is clear. For range – is not.

**Comment by ajkr** [comment]
I don't think there is any requirement for range deletions. We can handle out-of-order and overlapping range tombstones (but not "negative" range tombstones, e.g., `DeleteRange("b", "a")`). Range tombstones are stored separately from the point keys so don't have to be ordered relative to `SstFileWriter::Put()`s.

**Comment by socketpair** [comment]
Okay, that's good news! please document this important thing at least.

**Comment by ajkr** [comment]
Sure, I made a few improvements to the docs/tests: #11309, #11322, #11390
