### ISSUE TITLE
Rocksdb for external sorting

### ISSUE THREAD

**Issue by sureshmbabu1** [facebook/rocksdb#11306]
Hi,

I am planning to use rocksdb for external sorting.  I have around 50 to 100 million keys on average to be sorted.  What is the best compaction strategy for the external sortinf use case? Any suggestions on  options to be tuned  for this use case>

**Comment by siying** [comment]
You can try this:
(1) use vector memtable
(2) use very large number of L0 files, like infinite. (options.level0_file_num_compaction_trigger)
(3) use relatively large options.max_write_buffer_number (say 8), and options.max_background_flushes accordingly.
(4) Trigger CompactRange() after inserting all the files in the DB with options.max_subcompactions set for parallelism, say 8.

Let us know how it works.
