### ISSUE TITLE
RocksDB is not storing checkpoints to specified directory 

### ISSUE THREAD

**Issue by DASANIDrinker** [facebook/rocksdb#11305]
package spendreport;

import org.apache.flink.runtime.state.StateBackend;
import org.apache.flink.streaming.api.datastream.DataStream;
import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.walkthrough.common.sink.AlertSink;
import org.apache.flink.walkthrough.common.entity.Alert;
import org.apache.flink.walkthrough.common.entity.Transaction;
import org.apache.flink.walkthrough.common.source.TransactionSource;
//import org.apache.flink.contrib.streaming.state;
import org.apache.flink.contrib.streaming.state.RocksDBStateBackend;

import javax.security.auth.login.Configuration;

/**
 * Skeleton code for the datastream walkthrough
 */
public class FraudDetectionJob {
	public static void main(String[] args) throws Exception {
		StreamExecutionEnvironment env = StreamExecutionEnvironment.getExecutionEnvironment();
		// env.setStateBackend(new RocksDBStateBackend(filebackend, true));

		// Enabling Checkpoint
		long checkpointInterval = 5000;
		env.enableCheckpointing(checkpointInterval);

		// Enable Web UI
//    Configuration conf = new Configuration();
//    env = StreamExecutionEnvironment.createLocalEnvironmentWithWebUI(conf);
		RocksDBStateBackend rocksDBStateBackend = new RocksDBStateBackend("file:///C:/Users/xxx/frauddetection/rocksDBdata");

		// Create a Flink execution environment and set the state backend
		env.setStateBackend((StateBackend) rocksDBStateBackend);
		DataStream<Transaction> transactions = env
				.addSource(new TransactionSource())
				.name("transactions");

		DataStream<Alert> alerts = transactions
				.keyBy(Transaction::getAccountId)
				.process(new FraudDetector())
				.name("fraud-detector");

		alerts
				.addSink(new AlertSink())
				.name("send-alerts");

		env.execute("Fraud Detection");
	}
} 

I'm following along this article to use rocksDB as my backend: https://medium.com/swlh/run-a-stateful-streaming-service-with-apache-flink-and-rocksdb-749fbc24d78f  Everything is fine besides the fact that checkpoints are not saving at all in the specified directory. I'm using Windows.

**Comment by siying** [comment]
Can you go to your info log files (by default it's LOG and LOG.* files under the DB directory) and see whether you can see any error message there?
