### ISSUE TITLE
DelteRange() does not support passing nullptr as either end.

### ISSUE THREAD

**Issue by socketpair** [facebook/rocksdb#11310]
For example, `CompactRange()` allows passing `nullptr` for both ends of the range; It will be nice to have the same for `DeleteRange()`.

An additional interesting case (yes, my real case) – is to erase all the data in DB. I would love to pass `nullptr` for both ends in `DeleteRange()`

**Comment by cbi42** [comment]
Duplicate of #9911. Added a comment in #9911.
