### ISSUE TITLE
Exception thrown when it is not supposed to

### ISSUE THREAD

**Issue by ChromMob** [facebook/rocksdb#11315]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
No error thrown.
### Actual behavior
```
org.rocksdb.RocksDBException: lock hold by current process, acquire time 1679336321 acquiring thread 281471341752608: /home/ubuntu/MC/economy/CXFs62r1zRWqKE2oRqW+6yiT8aMiYOnF4WUSlz8bOc=/LOCK: No locks available
        at org.rocksdb.RocksDB.open(Native Method)
        at org.rocksdb.RocksDB.open(RocksDB.java:252) 
```
### Steps to reproduce the behavior
Access rocksdb in java from multiple threads.
The code still work I just do not understand why it throws an exception.

**Comment by siying** [comment]
The error message means that you've already opened this DB in the same process.

**Comment by ChromMob** [comment]
Could it be s bug of jni? Should I create a unit method for example instead of constructor.

**Comment by siying** [comment]
> Could it be s bug of jni? Should I create a init method for example instead of constructor.

The Java API is widely used by many users. I will be surprised if JNI has such an obvious bug. Opening DB in constructor doesn't appear to be an intuitive way of opening RocksDB, but it doesn't appear to cause the problem you mentioned. If you share the whole repro steps, some experienced Java programmers in the community can spot an issue.

**Comment by ChromMob** [comment]
Thank you so much but due to the nature of code I can't share the full code but I will verify my code thoroughly once more and post the  related code here for someone here to help me.

**Comment by ChromMob** [comment]
Ok so for some reason putIfAbsent() was not working properly so I just replaced it with containtsKey check and it works thank you everyone.
