### ISSUE TITLE
Quickly merge and Split db

### ISSUE THREAD

**Issue by mayuehappy** [facebook/rocksdb#11317]
I'm a contributor to flink where we use rocksdb extensively as a state backend (more then
 30000 streaming jobs),
But we now rely on Rocksdb to provide some features to optimize the rescaling speed of Flink jobs, details in [https://groups.google.com/g/rocksdb/c/V4lWIKreL5E/m/NaX2fRdbAAAJ](https://groups.google.com/g/rocksdb/c/V4lWIKreL5E/m/NaX2fRdbAAAJ),
can anyone take a look?

**Comment by mayuehappy** [comment]
I found out that there has been a PR（https://github.com/facebook/rocksdb/pull/5602） before to work on this issue. But my scenario looks simpler, we can guarantee that there is no intersection Key between two Dbs. 
so we hope

- Quickly Merge Db by ingesting SST files generated by live DB 

- Clip Db with KeyRange by directly traversing the sst files and than Delete redundant files and rewrite files with intersecting keys.

Can this approach work?

**Comment by cbi42** [comment]
Hi @mayuehappy - I think ingesting SST files generated by live DB can work, it's just not supported by RocksDB yet (maybe something like #5602 will work, I have not read that in detail). 

> Clip Db with KeyRange by directly traversing the sst files and than Delete redundant files and rewrite files with intersecting keys.

I wonder how this would work. DeleteFile() API is planned to be removed according to https://github.com/facebook/rocksdb/blob/c14eb134edbb5326298b75f8cd4400fded92f18b/include/rocksdb/db.h#L1609-L1615 and is recommended not to use it. Would DeleteRange() work for clipping a DB?

**Comment by mayuehappy** [comment]
hi @cbi42 
I drafted two PRs to implement this feature, please take a look and let me know if something is wrong or if there is a better suggestion. Thanks !
https://github.com/facebook/rocksdb/pull/11378
https://github.com/facebook/rocksdb/pull/11379

**Comment by patelprateek** [comment]
@mayuehappy : thanks for feature. I am curios is this method of merging two DBS with non overlapping keys faster than the ingestExternalFile api ? do you have any performance benchmarks for the two approaches ?

**Comment by cbi42** [comment]
> @mayuehappy : thanks for feature. I am curios is this method of merging two DBS with non overlapping keys faster than the ingestExternalFile api ? do you have any performance benchmarks for the two approaches ?

It should be much faster if applicable. This feature ingests files from another DB directly without the need to use SSTFileWriter to create sst files.

**Comment by patelprateek** [comment]
@cbi42 : could you also provide some insight here
I have two dbs , both are fully compacted and all SST files are at lowest levels.
Since i shard on keys . i know there is no intersection of keys , but they can still be overlapping ranges, so how do we do the merge in fast efficient way ? I thought all SST files at lower levels have not just disjoin keys but also non overlapping ranges since they are sorted

**Comment by cbi42** [comment]
> but they can still be overlapping ranges,

This API requires CFs to have disjoint key ranges. So if your two DBs have overlapping key ranges, it won't work. You may need to use SST file ingestion.

> I thought all SST files at lower levels have not just disjoin keys but also non overlapping ranges since they are sorted

Yes, SST files at level >= 1 have disjoint and sorted key ranges. But that won't suffice for this API.
