### ISSUE TITLE
GetLatestSequenceNumber : IO error "No such file or directory"

### ISSUE THREAD

**Issue by sadanand48** [facebook/rocksdb#11338]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
No Error/Crash expected

### Actual behavior
Rocks DB crashes.

on rocksdb 7.7.3 getLatestSequenceNumber() is crashing the rocksdb as it is unable to find the log file (maybe some sort of race condition here ) 

`status : IOError(Undefined); message : while stat a file for size: /var/lib/hadoop-ozone/om/data/om.db/000121.log: No such file or directory`

```
Stack: [0x00007fb6b8883000,0x00007fb6b8984000],  sp=0x00007fb6b89817f8,  free space=1017k
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.rocksdb.RocksDB.getLatestSequenceNumber(J)J+0
j  org.rocksdb.RocksDB.getLatestSequenceNumber()J+5
j  org.apache.hadoop.hdds.utils.db.RocksDatabase.getLatestSequenceNumber()J+18
j  org.apache.hadoop.hdds.utils.db.RDBStore.getUpdatesSince(JJ)Lorg/apache/hadoop/hdds/utils/db/DBUpdatesWrapper;+395
j  org.apache.hadoop.ozone.om.OzoneManager.getDBUpdates(Lorg/apache/hadoop/ozone/protocol/proto/OzoneManagerProtocolProtos$DBUpdatesRequest;)Lorg/apache/hadoop/ozone/om/helpers/DBUpdates;+30
j  org.apache.hadoop.ozone.protocolPB.OzoneManagerRequestHandler.getOMDBUpdates(Lorg/apache/hadoop/ozone/protocol/proto/OzoneManagerProtocolProtos$DBUpdatesRequest;)Lorg/apache/hadoop/ozone/p
rotocol/proto/OzoneManagerProtocolProtos$DBUpdatesResponse;+9 
```

I already see a similar bug fixed for another API in https://github.com/facebook/rocksdb/pull/8573

### Steps to reproduce the behavior
Seeing this only when the load is high and don't have exact reproduction steps.

**Comment by ajkr** [comment]
I can't find any logic under `getLatestSequenceNumber()` that accesses any file. It looks your call to `getLatestSequenceNumber()` is part of a higher-level operation, `getUpdatesSince()`. We have seen similar reports with our implementation of `GetUpdatesSince()`, such as #10648 and #5763. Is it possible the stack trace is incorrect and the error arises from a different function like `GetUpdatesSince()`?

**Comment by sadanand48** [comment]
Thanks @ajkr for taking a look, Yes, In the Java process that crashed due to the rocksdb crash, the stacktrace points to the `getUpdatesSince()` call however the rocksdb crashlog I have pasted in description points to `getLatestSequenceNumber`
```
Caused by: org.rocksdb.RocksDBException: while stat a file for size: /data/ozonedata/om/db/om.db/004684.log: No such file or directory
	at org.rocksdb.RocksDB.getUpdatesSince(Native Method)
	at org.rocksdb.RocksDB.getUpdatesSince(RocksDB.java:3966)
	at org.apache.hadoop.hdds.utils.db.RocksDatabase.getUpdatesSince(RocksDatabase.java:598)
```

**Comment by ajkr** [comment]
Thanks for the additional info. I think it looks like the known GetUpdatesSince() issue, then. Let's use #5763 for this issue. If you want to try solving it please feel free :).
