### ISSUE TITLE
IOError

### ISSUE THREAD

**Issue by sccData** [facebook/rocksdb#11345]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Could you help me?

Failed to rename: 000003.dbtmp to CURRENT: access denied

**Comment by akankshamahajan15** [comment]
Seems like a permission issue, not a rocksdb bug.
