### ISSUE TITLE
[Question] BlobDB limitations and comparison to tikv/titan

### ISSUE THREAD

**Issue by cscetbon** [facebook/rocksdb#11343]
I'd like to know what limitations still stand in BlobDB. I read [your article](https://rocksdb.org/blog/2021/05/26/integrated-blob-db.html) which was written almost 2 years ago but the limitations probably don't stand anymore (not sure).
Also how does it compare to [Titan](https://www.pingcap.com/blog/titan-storage-engine-design-and-implementation/) in term of engine design and expected performance ?

**Comment by ltamasi** [comment]
Hi @cscetbon - The limitations mentioned in the blog post are mostly gone now. See the current feature status on the wiki at https://github.com/facebook/rocksdb/wiki/BlobDB .

I am not aware of a head-to-head performance comparison between Titan and BlobDB but the broad outlines of how the two systems implement key-value separation are similar. From a practical standpoint, Titan is a layer on top of RocksDB which focuses on TiKV users and compatibility with RocksDB features relevant for TiKV. On the other hand, BlobDB is part of the RocksDB distribution; it is integrated into the core RocksDB engine and our goal is to provide compatibility with all other RocksDB features.

**Comment by ltamasi** [comment]
The "old" BlobDB doesn't support column families, the new one does. Again, see the wiki for more details.
