### ISSUE TITLE
RocksDB 8.1 public release

### ISSUE THREAD

**Issue by ltamasi** [facebook/rocksdb#11363]
Hi @adamretter ! Could you please start the Java testing for the 8.1 branch? The latest version is actually the patch release 8.1.1. Thanks!

**Comment by adamretter** [comment]
@ltamasi I have now tested the 8.1.fb branch and can confirm that it is passing on all platforms. Thank you

**Comment by ltamasi** [comment]
Thanks @adamretter !

**Comment by jbonofre** [comment]
Do you want me to test 8.1.1 on my project ?

**Comment by theolivenbaum** [comment]
Any updates on the release to Maven?

**Comment by adamretter** [comment]
This has now been published to Maven Central. Apologies for the delay.

**Comment by theolivenbaum** [comment]
Awesome, thanks @adamretter! I still don't see it here https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/ but I assume it probably will appear there soon

**Comment by adamretter** [comment]
@theolivenbaum Yes, it can take some time to be synchronized at Sonatype.
