### ISSUE TITLE
why it's not safe to close the DB when a manual compaction is in progress?

### ISSUE THREAD

**Issue by qq1033731787** [facebook/rocksdb#11373]
in FAQ it said it's not safe to close the DB when a manual compaction is in progress;why ? what will happen if i do so
```
Q: Can I close the DB when a manual compaction is in progress?

A: No, it's not safe to do that. However, you call CancelAllBackgroundWork(db, true) in another thread to abort the running compactions, so that you can close the DB sooner. Since 6.5, you can also speed it up using DB::DisableManualCompaction().
```

**Comment by akankshamahajan15** [comment]
IIRC, it'll give you a segmentation error. You can test the behavior with a unit test.

**Comment by akankshamahajan15** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
