### ISSUE TITLE
Question: The write performance of Rocksdb 7 is slower than that of Rocksdb 6

### ISSUE THREAD

**Issue by konghaiya** [facebook/rocksdb#11376]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Our project uses Rocksdb for write optimization. After upgrading to version 7.10.2, we found that the write performance has decreased by about 10 times compared to Rocksdb 6. Is there any special configuration on version 7, or is it due to some reason?

### Expected behavior

Rocksdb 7 should have better write performance than Rocksdb 6

**Comment by aierui** [comment]
@konghaiya  Is there a detailed configuration given for both versions?
