### ISSUE TITLE
db_bench fillrandom is not truly random, long run fillrandom does not take more storage with sst files

### ISSUE THREAD

**Issue by gaowayne** [facebook/rocksdb#11380]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
fillrandom can create realy random workload, there is no locality. we need 100% unique when fill random 
### Actual behavior
fillrandom will not create really random promise unique keys, and filluniquerandom will crash and panic
### Steps to reproduce the behavior
just run db_bench fillrandom to see finally SST files does not grow it maintain a size because key ranges are locality.
if run filluniquerandom, it panic

**Comment by gaowayne** [comment]
> This needs more details.
> 
> The OP also posted in the group with a claim that I couldn't reproduce. [See here](https://groups.google.com/g/rocksdb/c/JNZjlhSBFJE).
> 
> Other points:
> 
> * fillrandom is random, meaning it should and will generate duplicate keys
> * filluniquerandom with --num=30B means that db_bench will do one huge allocation to buffer 30B 8-byte keys. I assume the crash and panic referred to by the OP occurs when that ~240G allocation fails during the [call to resize](https://github.com/facebook/rocksdb/blob/bd80433c73691031ba7baa65c16c63a83aef201a/tools/db_bench_tool.cc#L4883). But I can only guess because this bug report has so few details.
> 
> My suggestion for anyone seeking a large database is:
> 
> 1. --benchmarks=fillseq to load all of the keys
> 2. --benchmarks=overwrite to overwrite X% of the keys and "fragment" the LSM tree, X=10 should be OK

thank you so much man. 
for filluniquerandom, with --num=30B, you are right, it is huge allocation panic. but when I reduce --num, allocation panic gone, but it still report server exit error, I did not debug it yet. I am originally think use random key insert place all sst files on my 30T QLC drive. but I found db_bench uniform insert is very locality, all sst files size can only reach 1.6T like this.

here is my db_bench parameters.
```
./db_bench --num=3000000000000 --db=/mnt/nvme8n1p1/test1  --histogram=1 --key_size=4096 --value_size=8192 --compression_type=none --benchmarks="fillrandom,stats" --statistics --stats_per_interval=1 --stats_interval_seconds=240  --threads=1 --target_file_size_multiplier=10 --write_buffer_size=134217728  --use_existing_db=0 --disable_wal=false --cache_size=536870912 --bloom_bits=10 --bloom_locality=1


 ./db_bench --num=3000000000000 --db=/mnt/nvme8n1p1/test1  --histogram=1 --key_size=4096 --value_size=8192 --compression_type=none --benchmarks="fillseq,stats" --statistics --stats_per_interval=1 --stats_interval_seconds=240  --threads=1 --target_file_size_multiplier=10 --write_buffer_size=134217728  --use_existing_db=0 --disable_wal=false --cache_size=536870912 --bloom_bits=10 --bloom_locality=1

```

for large database, suggestion above, I tried fillseq to load all keys, since too many of them, it failed too. 
you can try above my commands to fillrandom, all sst files will stay in less than 2T that means no new keys are created, rocksdb just delete many sst files then create new one. 

you can also try my fillseq command above, what I see is that db_bench will be killed by OOM, then when I tried to load it, it failed.

**Comment by ajkr** [comment]
`./db_bench --num=3000000000000 ... --benchmarks="fillseq,stats" ...`: that is 3T keys, each of which is 12KB, so would need to write tens of PB. I see you have a working command in #11431, so will close this issue in favor of that one.

**Comment by gaowayne** [comment]
> `./db_bench --num=3000000000000 ... --benchmarks="fillseq,stats" ...`: that is 3T keys, each of which is 12KB, so would need to write tens of PB. I see you have a working command in #11431, so will close this issue in favor of that one.

thank you so much. man
