### ISSUE TITLE
Question about ttl.

### ISSUE THREAD

**Issue by wei2xia** [facebook/rocksdb#11397]
![image](https://user-images.githubusercontent.com/58818313/233818125-fae3dbc0-c1ba-47d9-8c64-ce7174ef2cf5.png)

what is the difference？how to set ttl for ColumnFamilyHandle right？

**Comment by ltamasi** [comment]
`TtlDB` provides per-KV TTL functionality. Basically, it works by encoding the current timestamp into the value. A key-value then becomes eligible for removal at (original timestamp + TTL), and eventually gets cleaned up during compaction (using a compaction filter). See more details on the wiki here: https://github.com/facebook/rocksdb/wiki/Time-to-Live .

On the other hand, the `ttl` option in `ColumnFamilyOptions` works on the file level; setting it results in files with updates older than the TTL getting scheduled for compaction, see https://github.com/facebook/rocksdb/wiki/Leveled-Compaction#ttl .
