### ISSUE TITLE
RocksDB 8.1 does not compile on RaspberryPi 3 B

### ISSUE THREAD

**Issue by luismeruje** [facebook/rocksdb#11402]
I have tried compiling from branch 8.1.fb, however the compilation process fails.

### Expected behavior
Following the instructions in the example folder, rocksdb would compile and run on Raspberry Pi 3B.

### Actual behavior
Error during compilation.

### Steps to reproduce the behavior
```
make static_lib
```
Which produces the following error:

```
[...]
  CC       db/log_reader.o
  CC       db/log_writer.o
  CC       db/malloc_stats.o
  CC       db/memtable.o
db/memtable.cc: In member function ‘void rocksdb::MemTable::UpdateOldestKeyTime()’:
db/memtable.cc:256:1: error: insn does not satisfy its constraints:
  256 | }
      | ^
(insn 294 293 295 14 (set (reg:CC_DNE 100 cc)
        (compare:CC_DNE (ior:SI (ne:SI (reg:SI 0 r0 [166])
                    (const_int -1 [0xffffffffffffffff]))
                (ne:SI (reg:SI 1 r1 [+4 ])
                    (const_int -1 [0xffffffffffffffff])))
            (const_int 0 [0]))) "/usr/include/c++/11/bits/atomic_base.h":571:36 337 {*cmp_ior}
     (expr_list:REG_DEAD (reg:SI 1 r1 [+4 ])
        (expr_list:REG_DEAD (reg:SI 0 r0 [166])
            (nil))))
during RTL pass: cprop_hardreg
db/memtable.cc:256:1: internal compiler error: in extract_constrain_insn, at recog.c:2671
0x567ea3 internal_error(char const*, ...)
	???:0
0x567f55 fancy_abort(char const*, int, char const*)
	???:0
0x318b75 _fatal_insn(char const*, rtx_def const*, char const*, int, char const*)
	???:0
0x318ba9 _fatal_insn_not_found(rtx_def const*, char const*, int, char const*)
	???:0
0x78b1e5 extract_constrain_insn(rtx_insn*)
	???:0
Please submit a full bug report,
[...]
```

Other info:
 OS - Ubuntu Server 22.04
 Gcc version - 11.3.0
Compilation is being done on the raspberry pi (no cross-compilation).
 
 Can someone point me to either a working version, or a solution to fix the compilation error?

**Comment by ltamasi** [comment]
This is an internal error in `gcc`, that is, the bug is not in RocksDB but the compiler itself. Can you try building with a more recent `gcc` version?

**Comment by luismeruje** [comment]
I have tried with both older and newer versions of gcc, as well as different versions of rocksdb. The error persists. 
The problem seems to come from line 245 of db/memtable.cc : 
```
 if (oldest_key_time == std::numeric_limits<uint64_t>::max()) {
```

I've tried the following alternatives, but the same error shows up during compilation

```
 if (oldest_key_time == 0xffffffffffffffff) {

//And
if (oldest_key_time > 0xfffffffffffffffe){
```

Commenting out the if statement solves this particular problem (another error shows up, but is solved by a patch suggested in a different issue), and I am then able to compile and run rocksdb. Since this seems to be a compiler issue, should I post this on a gcc board/forum instead?

**Comment by ltamasi** [comment]
> Commenting out the if statement solves this particular problem (another error shows up, but is solved by a patch suggested in a different issue), and I am then able to compile and run rocksdb. Since this seems to be a compiler issue, should I post this on a gcc board/forum instead?

Yeah, that would make sense since this is an internal compiler error. You might also consider trying to build RocksDB with `clang`
