### ISSUE TITLE
Error while blob log header: Magic number mismatch

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#11401]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

I use rocksdb 7.2 on NVME SSD in production environment. 
After running several days, we found error like follows.
```
2023/04/24-04:17:39.974031 139770275780352 [db/compaction/compaction_job.cc:2449] [base_data_cf] [JOB 15997] Compacting 1@1 + 7@2 files to L2, score 1.02
2023/04/24-04:17:39.974040 139770275780352 [db/compaction/compaction_job.cc:2453] [base_data_cf] Compaction start summary: Base version 28102 Base level 1, inputs: [84858(207KB)], [84545(166KB) 84547(166KB) 84548(168KB) 84549(167KB) 84550(168KB) 84551(169KB) 84552(169KB)]
2023/04/24-04:17:39.974051 139770275780352 EVENT_LOG_v1 {"time_micros": 1682281059974044, "job": 15997, "event": "compaction_started", "compaction_reason": "LevelMaxLevelSize", "files_L1": [84858], "files_L2": [84545, 84547, 84548, 84549, 84550, 84551, 84552], "score": 1.02435, "input_data_size": 1417021}
2023/04/24-04:17:39.978087 139770275780352 [WARN] [db/db_impl/db_impl_compaction_flush.cc:3426] Compaction error: Corruption: Error while decoding blob log header: Magic number mismatch
2023/04/24-04:17:39.992750 139770275780352 [WARN] [db/error_handler.cc:395] Background IO error Corruption: Error while decoding blob log header: Magic number mismatch
2023/04/24-04:17:39.992769 139770275780352 [db/error_handler.cc:286] ErrorHandler: Set regular background error
2023/04/24-04:17:39.992789 139770275780352 (Original Log Time 2023/04/24-04:17:39.978017) [db/compaction/compaction_job.cc:970] [base_data_cf] compacted to: base level 1 level multiplier 1.00 max bytes base 393216 files[4 2 18] max score 0.80, MB/sec: 359.5 rd, 0.0 wr, level 2, files in(1, 7) out(0 +0 blob) MB in(0.2, 1.1 +0.0 blob) out(0.0 +0.0 blob), read-write-amplify(6.7) write-amplify(0.0) Corruption: Error while decoding blob log header: Magic number mismatch, records in: 54782, records dropped: 54782 output_compression: LZ4
2023/04/24-04:17:39.992855 139770275780352 (Original Log Time 2023/04/24-04:17:39.978022) [db/compaction/compaction_job.cc:981] [base_data_cf] Blob file summary: head=84322, tail=84872
2023/04/24-04:17:39.992860 139770275780352 (Original Log Time 2023/04/24-04:17:39.978036) EVENT_LOG_v1 {"time_micros": 1682281059978026, "job": 15997, "event": "compaction_finished", "compaction_time_micros": 3942, "compaction_time_cpu_micros": 567, "output_level": 2, "num_output_files": 0, "total_output_size": 0, "num_input_records": 54782, "num_output_records": 0, "num_subcompactions": 1, "output_compression": "LZ4", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "file_write_nanos": 0, "file_range_sync_nanos": 0, "file_fsync_nanos": 0, "file_prepare_write_nanos": 0, "lsm_state": [4, 2, 18], "blob_file_head": 84322, "blob_file_tail": 84872}
2023/04/24-04:17:39.992864 139770275780352 [ERROR] [db/db_impl/db_impl_compaction_flush.cc:2925] Waiting after background compaction error: Corruption: Error while decoding blob log header: Magic number mismatch, Accumulated background error counts: 1
```
I have no idea what happens. The disk works normally, on which I can create file and write data into file. I haven't found exception in my disk.

In the other hand, I wonder how I can recover from this error.

### Expected behavior
No error

### Actual behavior
I get the error `Error while blob log header: Magic number mismatch` when compacting.

### Steps to reproduce the behavior
Have no idea to reproduce it.

**Comment by ltamasi** [comment]
This sounds like an on-disk corruption. You could try and find the affected files by using a tool like `hexdump` to check the magic number of your blob files; the very first four bytes of any blob file should be `37 8f 24 00`. You could also use RocksDB's `blob_dump` tool with the `--show_summary` switch, which would fail with the magic number related error above.

**Comment by GOGOYAO** [comment]
> This sounds like an on-disk corruption. You could try and find the affected files by using a tool like `hexdump` to check the magic number of your blob files; the very first four bytes of any blob file should be `37 8f 24 00`. You could also use RocksDB's `blob_dump` tool with the `--show_summary` switch, which would fail with the magic number related error above.

It happened again on another machine. I restarted the program and it recovered. I can not found the error file from the log and I just find one sst file and one blob flle is deleted even if the error happened. Any more idea about the new error log?
```
2023/04/27-02:49:06.975458 139793139656448 [db/compaction/compaction_job.cc:2449] [base_data_cf] [JOB 21261] Compacting 1@1 + 7@2 files to L2, score 1.32
2023/04/27-02:49:06.977012 139793139656448 [db/compaction/compaction_job.cc:2453] [base_data_cf] Compaction start summary: Base version 36853 Base level 1, inputs: [99801(205KB)], [99688(143KB) 99611(167KB) 99613(168KB) 99614(169KB) 99615(170KB) 99616(170KB) 99617(169KB)]
2023/04/27-02:49:06.977043 139793139656448 EVENT_LOG_v1 {"time_micros": 1682534946977030, "job": 21261, "event": "compaction_started", "compaction_reason": "LevelMaxLevelSize", "files_L1": [99801], "files_L2": [99688, 99611, 99613, 99614, 99615, 99616, 99617], "score": 1.31746, "input_data_size": 1396931}
2023/04/27-02:49:06.989721 139793139656448 [WARN] [db/db_impl/db_impl_compaction_flush.cc:3426] Compaction error: Corruption: Error while decoding blob log header: Magic number mismatch
2023/04/27-02:49:06.990135 139793139656448 [WARN] [db/error_handler.cc:395] Background IO error Corruption: Error while decoding blob log header: Magic number mismatch
2023/04/27-02:49:06.990143 139793139656448 [db/error_handler.cc:286] ErrorHandler: Set regular background error
2023/04/27-02:49:06.990158 139793139656448 (Original Log Time 2023/04/27-02:49:06.989622) [db/compaction/compaction_job.cc:970] [base_data_cf] compacted to: base level 1 level multiplier 1.00 max bytes base 393216 files[4 3 17] max score 0.80, MB/sec: 115.8 rd, 0.0 wr, level 2, files in(1, 7) out(0 +0 blob) MB in(0.2, 1.1 +0.1 blob) out(0.0 +0.0 blob), read-write-amplify(5.5) write-amplify(0.0) Corruption: Error while decoding blob log header: Magic number mismatch, records in: 54628, records dropped: 54619 output_compression: LZ4
2023/04/27-02:49:06.990160 139793139656448 (Original Log Time 2023/04/27-02:49:06.989630) [db/compaction/compaction_job.cc:981] [base_data_cf] Blob file summary: head=99350, tail=99816
2023/04/27-02:49:06.990164 139793139656448 (Original Log Time 2023/04/27-02:49:06.989665) EVENT_LOG_v1 {"time_micros": 1682534946989638, "job": 21261, "event": "compaction_finished", "compaction_time_micros": 12556, "compaction_time_cpu_micros": 1441, "output_level": 2, "num_output_files": 0, "total_output_size": 0, "num_input_records": 54628, "num_output_records": 9, "num_subcompactions": 1, "output_compression": "LZ4", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "file_write_nanos": 41429, "file_range_sync_nanos": 0, "file_fsync_nanos": 0, "file_prepare_write_nanos": 507, "lsm_state": [4, 3, 17], "blob_file_head": 99350, "blob_file_tail": 99816}
2023/04/27-02:49:06.990167 139793139656448 [ERROR] [db/db_impl/db_impl_compaction_flush.cc:2925] Waiting after background compaction error: Corruption: Error while decoding blob log header: Magic number mismatch, Accumulated background error counts: 1
2023/04/27-02:49:07.992963 139793139656448 [DEBUG] [db/db_impl/db_impl_files.cc:345] [JOB 21261] Delete /media/ssd2/web_server/picasso/data/storage/data/39157487/delta_db/099818.blob type=10 #99818 -- OK
2023/04/27-02:49:07.992983 139793139656448 EVENT_LOG_v1 {"time_micros": 1682534947992980, "job": 21261, "event": "blob_file_deletion", "file_number": 99818}
2023/04/27-02:49:07.993015 139793139656448 [DEBUG] [db/db_impl/db_impl_files.cc:345] [JOB 21261] Delete /media/ssd2/web_server/picasso/data/storage/data/39157487/delta_db/099817.sst type=2 #99817 -- OK
2023/04/27-02:49:07.993020 139793139656448 EVENT_LOG_v1 {"time_micros": 1682534947993019, "job": 21261, "event": "table_file_deletion", "file_number": 99817}
```

**Comment by ltamasi** [comment]
The file number of the problematic blob file is not logged in the event log. What I was suggesting above is to check all blob files from the command line using one of the tools I mentioned to find the corrupt file (and then copy it from any backups/replicas etc. that you might have).

The two deleted files are the partial outputs of the failed compaction (failed compactions do not get committed and their output files get deleted).

**Comment by GOGOYAO** [comment]
OK. I will try your method when it happens again. 
But in the other hand I wonder why it will recover when I restart my progress.

**Comment by GOGOYAO** [comment]
Another error happened in the same cluster.
```
 3852 =====Column families:=====
 3853 2023/04/26-09:11:16.060267 140604430558976 [db/db_impl/db_impl_compaction_flush.cc:1735] default
 3854 2023/04/26-09:11:16.060270 140604430558976 [db/db_impl/db_impl_compaction_flush.cc:1735] key_meta_cf
 3855 2023/04/26-09:11:16.060273 140604430558976 [db/db_impl/db_impl_compaction_flush.cc:1735] base_data_cf
 3856 2023/04/26-09:11:16.060275 140604430558976 [db/db_impl/db_impl_compaction_flush.cc:1735] delta_data_cf
 3857 2023/04/26-09:11:16.060277 140604430558976 [db/db_impl/db_impl_compaction_flush.cc:1738] =====End of column families list=====
 3858 2023/04/26-09:11:16.060307 140604430558976 [db/db_impl/db_impl_compaction_flush.cc:1749] Manual atomic flush finished, status: Corruption: Key size mismatch when reading blob
```

In my application, I use write buffer manager(allow_stall==true) to control the flush. When write request qps uprushes, write buffer manager usage exceeds 90% and I trigger manual atomic flush to try to avoid decreasing write fail(status is Incomplement). 
So maybe the error is caused by manual atomic flush or write fail(status is Incomplement). Because Another mirror cluster which has the same write request  qps, have never encountered the error.

Some options is like follows:
```
Options.min_write_buffer_number_to_merge = 1
Column Families Num = 4
atomic flush = true
```

**Comment by GOGOYAO** [comment]
I restart my progress and found another error.
```
2023/04/27-14:16:20.780642 140274849408768 [db/compaction/compaction_job.cc:2449] [base_data_cf] [JOB 7] Compacting 1@2 files to L2, score 0.60
2023/04/27-14:16:20.780678 140274849408768 [db/compaction/compaction_job.cc:2453] [base_data_cf] Compaction start summary: Base version 18 Base level 2, inputs: [84545(166KB)]
2023/04/27-14:16:20.780688 140274849408768 EVENT_LOG_v1 {"time_micros": 1682576180780681, "job": 7, "event": "compaction_started", "compaction_reason": "PeriodicCompaction", "files_L2": [84545], "score": 0.6, "input_data_size": 170617}
2023/04/27-14:16:20.789773 140274849408768 [WARN] [db/db_impl/db_impl_compaction_flush.cc:3426] Compaction error: Corruption: Malformed blob file
2023/04/27-14:16:20.790129 140274849408768 [WARN] [db/error_handler.cc:395] Background IO error Corruption: Malformed blob file
2023/04/27-14:16:20.790134 140274849408768 [db/error_handler.cc:286] ErrorHandler: Set regular background error
2023/04/27-14:16:20.790166 140274849408768 (Original Log Time 2023/04/27-14:16:20.789729) [db/compaction/compaction_job.cc:970] [base_data_cf] compacted to: base level 1 level multiplier 10.00 max bytes base 1638400 files[3 6 18] max score 0.60, MB/sec: 18.9 rd, 0.0 wr, level 2, files in(0, 1) out(0 +0 blob) MB in(0.0, 0.2 +0.0 blob) out(0.0 +0.0 blob), read-write-amplify(0.0) write-amplify(0.0) Corruption: Malformed blob file, records in: 6647, records dropped: 6647 output_compression: LZ4
2023/04/27-14:16:20.790169 140274849408768 (Original Log Time 2023/04/27-14:16:20.789734) [db/compaction/compaction_job.cc:981] [base_data_cf] Blob file summary: head=84322, tail=85629
2023/04/27-14:16:20.790173 140274849408768 (Original Log Time 2023/04/27-14:16:20.789746) EVENT_LOG_v1 {"time_micros": 1682576180789737, "job": 7, "event": "compaction_finished", "compaction_time_micros": 9016, "compaction_time_cpu_micros": 741, "output_level": 2, "num_output_files": 0, "total_output_size": 0, "num_input_records": 6647, "num_output_records": 0, "num_subcompactions": 1, "output_compression": "LZ4", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "file_write_nanos": 0, "file_range_sync_nanos": 0, "file_fsync_nanos": 0, "file_prepare_write_nanos": 0, "lsm_state": [3, 6, 18], "blob_file_head": 84322, "blob_file_tail": 85629}
2023/04/27-14:16:20.790177 140274849408768 [ERROR] [db/db_impl/db_impl_compaction_flush.cc:2925] Waiting after background compaction error: Corruption: Malformed blob file, Accumulated background error counts: 1
2023/04/27-14:16:20.790188 140273526970112 [db/db_impl/db_impl_compaction_flush.cc:1749] Manual atomic flush finished, status: Corruption: Malformed blob file
=====Column families:=====
2023/04/27-14:16:20.790200 140273526970112 [db/db_impl/db_impl_compaction_flush.cc:1753] default
2023/04/27-14:16:20.790202 140273526970112 [db/db_impl/db_impl_compaction_flush.cc:1753] key_meta_cf
2023/04/27-14:16:20.790204 140273526970112 [db/db_impl/db_impl_compaction_flush.cc:1753] base_data_cf
2023/04/27-14:16:20.790207 140273526970112 [db/db_impl/db_impl_compaction_flush.cc:1753] delta_data_cf
2023/04/27-14:16:20.790208 140273526970112 [db/db_impl/db_impl_compaction_flush.cc:1756] =====End of column families list=====
2023/04/27-14:16:21.792115 140274849408768 [DEBUG] [db/db_impl/db_impl_files.cc:345] [JOB 7] Delete /media/ssd2/web_server/picasso/data/storage/data/39247908/delta_db/085548.log type=0 #85548 -- OK
2023/04/27-14:16:23.332593 140273223481088 [ERROR] [db/db_impl/db_impl_compaction_flush.cc:2832] Waiting after background flush error: Corruption: Malformed blob fileAccumulated background error counts: 2
```

**Comment by GOGOYAO** [comment]
I find the error file. 
```
ls: cannot access 084335.blob: No such file or directory
total 0
-????????? ? ? ? ?            ? 084335.blob
```

**Comment by ltamasi** [comment]
> @ltamasi Another error happened in the same cluster.
>
... 
>  3858 2023/04/26-09:11:16.060307 140604430558976 [db/db_impl/db_impl_compaction_flush.cc:1749] Manual atomic flush finished, status: Corruption: Key size mismatch when reading blob

Just for the record, this doesn't seem to be the original error; there are no blob reads done during flush (garbage collection is only performed during compaction). Seems like there was a prior compaction failure in the background.

**Comment by ltamasi** [comment]
> I find the error file.
> 
> ```
> ls: cannot access 084335.blob: No such file or directory
> total 0
> -????????? ? ? ? ?            ? 084335.blob
> ```

So you can't access the file even using `ls`, right? That does point toward a filesystem (or lower) level corruption.

**Comment by GOGOYAO** [comment]
> > I find the error file.
> > ```
> > ls: cannot access 084335.blob: No such file or directory
> > total 0
> > -????????? ? ? ? ?            ? 084335.blob
> > ```
> 
> So you can't access the file even using `ls`, right? That does point toward a filesystem (or lower) level corruption.

Yes, I can not access the file. But I am not sure when the error file is produced. 
I stop the process and run `rm -rf {rocksdb_dir}` to clear the whole SSD, and then the error file occured. So maybe the error file is produced by `rm`

**Comment by GOGOYAO** [comment]
In another machine where the same error occured, I find the error file whose first four bytes are wrong. The details is as follows,
```
$ hexdump 139328.blob| head -5
0000000 ffdf f207 0016 0628 b101 ae34 36da c69d
0000010 31fb 3832 3739 6132 7075 765f 5f32 3132
0000020 3036 3838 3132 3539 0001 0001 08e7 81e4
0000030 a2c0 1906 060f 3131 3332 1830 e500 93b2
0000040 a1e6 1a06 060e 3937 3732 3438 002f 00f5
```
This file can be accessed by `ls`.
```
$ file 139328.blob
139328.blob: data
$ ll 139328.blob
-rw-r--r-- 1 user user_group 135564 May  5 18:02 139328.blob
```

**Comment by GOGOYAO** [comment]
> 139328

I search `139328.blob` in rocksdb LOG, nothing is found.
```
grep "Generated blob file" LOG | grep 139328
```
In my opinion, every blob file print a log when generated. So any hints here?

**Comment by GOGOYAO** [comment]
And w

> > 139328
> 
> I search `139328.blob` in rocksdb LOG, nothing is found.
> 
> ```
> grep "Generated blob file" LOG | grep 139328
> ```
> 
> In my opinion, every blob file print a log when generated. So any hints here?

After this error happens, the write requests to the db instance get error like `Corruption: Corruption: Error while decoding blob log header: Magic number mismatch`. Why does the write request need `decoding blob log header`?

And I find many logs like this.
```
IO error: No such file or directory: while unlink() file: /media/ssd1/web_server/picasso/data/storage/data/39100705/delta_db/158358.blob: No such file or directory
```
Could this `IO error` relate to the `Magic number mismatch`?

**Comment by GOGOYAO** [comment]
I open the error file`139328.blob` directly. I find some readable bytes at the end of the error file as follows.
```
779 ^Kter.policybloomfilter^O^D^Asize^@
780 ^N^Axed.key.length^@  ^M^Aormat.version^@^H^U^Aindex.key.is.user.key^A^N^D^Asize{^N^V^Avalue.is.delta.encoded^A^H^N^Amerge.operands^@^S^C^Gtornullptr^H^O^Anum.data.blocks^C^L^G^Bentries<    99>O^L^N^Afilter_entries^@^L^O^Arange-deletions^@^H^O^Aoldest.key.time^@  ^S^Criginal.file.numberôÄ^H^H^U^Gprefix.extractor.namenullptr
781 ^Q^Boperty.collectors[]^H^L^Craw.key.sizeüÏ^X^L
782 ^Cvalue.size<96>Û^C^@^@^@^@^A^@^@^@^@ì³ç^C^@^R^Erocksdb.properties°<9b>^Hû^F^@^@^@^@^A^@^@^@^@<9f>þ^Um^A°¢^H"Ô<9a>^HW^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^E^@^    @^@÷Ïô<85>·Aâ<88>
```

**Comment by ltamasi** [comment]
Regarding why writes are failing: this is expected behavior after background errors, see https://github.com/facebook/rocksdb/wiki/Background-Error-Handling . (In a nutshell, you're correct that RocksDB doesn't have to read anything from blob files when you do a write. This is the background error code getting propagated to writes after the DB goes into read-only mode following a failed compaction.)

As for 139328.blob: based on the fragment above, this is really an SST file (specifically, part of a properties block). So there's clearly some sort of corruption happening. I suggest checking your kernel logs for any signs of filesystem/hardware issues. It might also be an in-memory corruption, which you could try to find by running your application using ASAN.

**Comment by GOGOYAO** [comment]
> Regarding why writes are failing: this is expected behavior after background errors, see https://github.com/facebook/rocksdb/wiki/Background-Error-Handling . (In a nutshell, you're correct that RocksDB doesn't have to read anything from blob files when you do a write. This is the background error code getting propagated to writes after the DB goes into read-only mode following a failed compaction.)
> 
> As for 139328.blob: based on the fragment above, this is really an SST file (specifically, part of a properties block). So there's clearly some sort of corruption happening. I suggest checking your kernel logs for any signs of filesystem/hardware issues. It might also be an in-memory corruption, which you could try to find by running your application using ASAN.

I check the kernel logs by `dmesg -T` and nothing happened in the day when the blob file was created. 
And I think `in-memory corruption` should have caused core dump but the application keep running without exit.

As you said, the blob file is actually a sst file. When a sst file is created, a log like `Generated table xxx` should be printed out. But in the log file, there are nothing about `139328 ` around the time `139328.blob` created.

In my application, I open hundreds of rocksdb instances with `WriteBufferManager` to control the memory usage. And this error happened after I use `manual flush` when `WriteBufferManager` use too much memory(eg. 60%). But I failed to reproduce this error using `manual flush` offline.

**Comment by GOGOYAO** [comment]
I find another error blob file, which does not seem like a sst file.

```
$ hexdump -x 099524.blob | head
0000000    0000    0000    0000    2000    0102    0000    0000    39b5
0000010    08c2    7f80    c888    e757    0c0a    8a08    d9d8    b1bc
0000020    1da7    a510    10f2    0110    a552    02ea    fb08    1201
0000030    011f    34b1    daae    9d36    fbc6    3535    3934    3535
0000040    7561    5f70    3276    345f    3332    3836    3931    3935
0000050    0fda    e9fc    0a02    e9f8    0a02    e9f4    0a02    6204
0000060    7361    1265    e9ea    0802    bfa7    ca83    1a01    4d01
0000070    4f20    0c5a    b3e7    e7bb    9fbb    b7e5    e5a5    b785
0000080    0c5a    bde5    e9b1    b39f    92e6    e6ad    be94    065a
0000090    98e9    e885    bbaf    065a    b7e5    e5a5    b785    0c5a
```

**Comment by ltamasi** [comment]
> And I think in-memory corruption should have caused core dump but the application keep running without exit.

In-memory corruptions do not necessarily cause a crash. If you're convinced it's not a hardware/filesystem issue, I think your best bet to catch any memory management issues is to try to reproduce this under ASAN.

**Comment by ltamasi** [comment]
> In-memory corruptions do not necessarily cause a crash. If you're convinced it's not a hardware/filesystem issue, I think your best bet to catch any memory management issues is to try to reproduce this under ASAN.

Have you been able to reproduce this using ASAN as suggested above?
