### ISSUE TITLE
Looking for rocksdbjni for rocksdb 8.1.1

### ISSUE THREAD

**Issue by jbonofre** [facebook/rocksdb#11410]
I see rocksdb 8.1.1 has been released but rocksdbjni available version is 8.0.0 on Maven Central:

https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/

Any change you can release and push rocksdbjni 8.1.1 on Maven Central ?

Thanks !

**Comment by cbi42** [comment]
Tracked in #11363.
