### ISSUE TITLE
cgo compaction segmentfault probabilistically

### ISSUE THREAD

**Issue by meilihao** [facebook/rocksdb#11416]
env:
- oracle linux 7.9
- [grocksdb v1.7.16/v1.7.15](https://github.com/linxGnu/grocksdb)

### Expected behavior
`db.CompactRange(Range{nil, nil})` is ok

### Actual behavior
`db.CompactRange(Range{nil, nil})`  crashes probabilistically

rocksdb 7.10.2/7.9.2 have the same problem.

**Comment by akankshamahajan15** [comment]
@meilihao Can you share the logs and the trace what seg are you getting. We can't debug from this information.

**Comment by meilihao** [comment]
![2023-05-19_18-04-41](https://github.com/facebook/rocksdb/assets/4382586/991f68cd-ad6a-4757-8f12-dcdafca35db2)
![2023-05-19_18-07-31](https://github.com/facebook/rocksdb/assets/4382586/39b586f3-53b8-4198-a32b-9bdfff330f8a)

**Comment by meilihao** [comment]
The rocksdb db has disappeared, it may be a problem with my code logic, I will check it carefully.
