### ISSUE TITLE
rocksdbjni 8.1.1 is broken on Windows, jar is missing librocksdbjni-win64.dll

### ISSUE THREAD

**Issue by sambsnyd** [facebook/rocksdb#11420]
### Expected behavior
Able to load rocksdbjni 8.1.1 on Windows

### Actual behavior
Unable to load rocksdbjni 8.1.1 on Windows

### Steps to reproduce the behavior
View contents of rocksdbjni-8.1.1.jar in your preferred zip file viewer and observe that librocksdbjni-win64.dll is not contained therein.

**Comment by adamretter** [comment]
@sambsnyd Sorry about that. It looks like there was a small hiccup in the release process. I have now released version 8.1.1.1 to Maven Central to address that.

**Comment by jkschneider** [comment]
Thanks for the quick turnaround @adamretter!
