### ISSUE TITLE
Any TTL timestamp per record available via get() API?

### ISSUE THREAD

**Issue by nickpan47** [facebook/rocksdb#1143]
Is there any APIs available s.t. we can tell what's the current expiration time associated w/ a record in RocksDB database w/ TTL?

The use case is: since the TTL RocksDB expires records w/ background compaction threads, there may be time that get() or iterator.next() will get records that should be expired. For application that can not run correct logic w/ stale records, the application will need to tell whether the record it gets from RocksDB has actually expired at the moment of access. Is there anyway to expose this internally kept expiration timestamp via the get or iterator APIs?

Thanks!

**Comment by nickpan47** [comment]
Any one has an answer?

**Comment by adamretter** [comment]
I just had a quick look at `utilities/db_ttl_impl.h`, it looks like `TtlIterator` has a `timestamp()` method.

Is that what you were looking for?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
