### ISSUE TITLE
Unable to compile benchmark tools 8.1.1 on Mac OS X

### ISSUE THREAD

**Issue by sptrakesh** [facebook/rocksdb#11437]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Build and install 8.1.1 on Mac OS X (Ventura 13.3.1)
### Actual behavior
Compilation fails with error

```
/tmp/rocksdb/tools/db_bench_tool.cc:6964:14: error: variable 'num_seek_to_first' set but not used [-Werror,-Wunused-but-set-variable]
    uint64_t num_seek_to_first = 0;
             ^
/tmp/rocksdb/tools/db_bench_tool.cc:6965:14: error: variable 'num_next' set but not used [-Werror,-Wunused-but-set-variable]
    uint64_t num_next = 0;
```
### Steps to reproduce the behavior
Check out 8.1.1 on Mac OS X and try to compile

```
cmake -DWITH_TESTS=OFF \
    -DWITH_ALL_TESTS=OFF \
    -DCMAKE_CXX_STANDARD=20 \
    -DCMAKE_BUILD_TYPE=Release \
    -DROCKSDB_BUILD_SHARED=OFF \
    -DCMAKE_PREFIX_PATH=$PREFIX \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_INSTALL_LIBDIR=lib \
    .. \
make -j12
```

**Comment by asad-awadia** [comment]
how do you remove these flags `-Werror,-Wunused-variable` ? they are always breaking my compiles

**Comment by ajkr** [comment]
Pass `-DFAIL_ON_WARNINGS=OFF` to your `cmake` command
