### ISSUE TITLE
can rocksdb call fsync when wal file create but not sync when write data

### ISSUE THREAD

**Issue by scut-lz** [facebook/rocksdb#11454]

**Comment by cbi42** [comment]
> call fsync when wal file create

We currently do not call `fsync` when creating a new WAL file and have not planned to implement it. What is your use case?

> not sync when write data

This is the default write behavior.

**Comment by scut-lz** [comment]
> > call fsync when wal file create
> 
> We currently do not call `fsync` when creating a new WAL file and have not planned to implement it. What is your use case?
> 
> > not sync when write data
> 
> This is the default write behavior.
thank you for your reply,
the use case is we need to close jounal of the fs, so we need to consider whether manifest, wal can flush metadata timely by manual control
