### ISSUE TITLE
How to induce gc worker

### ISSUE THREAD

**Issue by Lsgoose** [facebook/rocksdb#11478]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
I want to induce the gc to work. But now I only find --writes in db_bench. How can I test that the data can write over 0.8 to induce the gc worker?

**Comment by cbi42** [comment]
Hi - could you explain what you mean by "induce the gc to work"? I'm not sure what gc means.

**Comment by mdcallag** [comment]
If you are asking whether there are ways to force compaction and/or flush there are. The API has ways to request compaction -- full or for a range.

There are also less proper ways to do it, see the implementation for : db_bench --benchmarks=flush,compact0,compact1
