### ISSUE TITLE
Question: whats Corruption mean?

### ISSUE THREAD

**Issue by leodie** [facebook/rocksdb#1148]
I use

`     Status s = m_db->Get(rocksdb::ReadOptions(), keyword, &value);`
value is right, but status is kCorruption

what's that mean?

**Comment by siying** [comment]
Can you print out s.ToString()? It will provide more information.

**Comment by leodie** [comment]
Thanks, I fix it, use 
`m_db->Flush(rocksdb::FlushOptions());`
