### ISSUE TITLE
RocksDB 8.3 public release

### ISSUE THREAD

**Issue by jowlyzhang** [facebook/rocksdb#11496]
Hi @adamretter ! Could you please start the Java testing for the 8.3 branch? The release branch is https://github.com/facebook/rocksdb/tree/8.3.fb

**Comment by adamretter** [comment]
Okay. In progress...

**Comment by adamretter** [comment]
@jowlyzhang that's done now and all looks good.

**Comment by jowlyzhang** [comment]
Thanks! @adamretter
