### ISSUE TITLE
Getting started with RocksDB on Mac OS

### ISSUE THREAD

**Issue by vinhqdang** [facebook/rocksdb#1150]
Hello all

I have a question on stackoverflow [here](http://stackoverflow.com/questions/37616259/getting-started-with-rocksdb-on-macos). Could you please help me to answer?

**Update**: I also followed the guides at http://pyrocksdb.readthedocs.io/en/v0.2.1/installation.html#building-pyrocksdb to add

```
$ export CPLUS_INCLUDE_PATH=${CPLUS_INCLUDE_PATH}:`pwd`/include
$ export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:`pwd`
$ export LIBRARY_PATH=${LIBRARY_PATH}:`pwd`
```

but it does not help: when I move the example file to any other directory and tried to compile, it will raise an error

**Comment by ajkr** [comment]
the comments on the stackoverflow answer suggests this has been resolved.
