### ISSUE TITLE
HyperClockCache not supported in Java API

### ISSUE THREAD

**Issue by KKcorps** [facebook/rocksdb#11510]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

I have upgraded rocksdb to 8.1.1 primarily to use ClockCache instead of LRUCache since it's now production ready.

### Actual behavior

However, upon investigation I found out that even when I use `ClockCache` in java, rocksDB still creates an `LRUCache`

The reason for this seems to be some API incompatibility between HyperClockCache and existing LRUCache

Can you please implement this since I have seen the benchmarks and it will give atlease 1.5-2X performance boost for us.

<img width="694" alt="Screenshot 2023-06-05 at 6 24 08 PM" src="https://github.com/facebook/rocksdb/assets/5559703/12d35bdb-4750-4013-997c-6b98f14b8d44">

### Steps to reproduce the behavior

Just use `new ClockCache()` in java program

**Comment by KKcorps** [comment]
If there is blocker in supporting this, please put the `DEPRECATED or WARNING` header in [ClockCache](https://github.com/facebook/rocksdb/blob/main/java/src/main/java/org/rocksdb/ClockCache.java) java class as well

**Comment by cavallium** [comment]
Any news on this? In java there is still only LRUCache

**Comment by cmccrorie** [comment]
Hello @KKcorps 

My colleague @rhubner  is going to work on implementing this. We are aiming to have this done by middle of next week. 

Thank you.

**Comment by KKcorps** [comment]
That's amazing to hear. Please also publish some performance numbers if possible
