### ISSUE TITLE
v8.1.1 compile failed with gcc 13.1.1 and Arch Linux

### ISSUE THREAD

**Issue by sangshuduo** [facebook/rocksdb#11523]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

compile successfully

### Actual behavior

In file included from /root/work/taosdata/TDengine.3/contrib/geos/src/algorithm/ConvexHull.cpp:30:  
/root/work/taosdata/TDengine.3/contrib/geos/include/geos/util.h:38:12: error: 'make\_unique' has not been declared in 'std'  
  38 | using std::make\_unique;  
     |            ^~~~~~~~~~~  
/root/work/taosdata/TDengine.3/contrib/geos/src/algorithm/ConvexHull.cpp: In member function 'std::unique\_ptr\<geos::geom::CoordinateSequence> geos::algorithm::ConvexHull::toCoordinateSequence(geos::geom::Coordinate::ConstVect&)':  
/root/work/taosdata/TDengine.3/contrib/geos/src/algorithm/ConvexHull.cpp:118:23: error: 'make\_unique' is not a member of 'geos::detail'  
 118 |     auto cs = detail::make\_unique\<CoordinateSequence>(cv.size());  
     |                       ^~~~~~~~~~~  
/root/work/taosdata/TDengine.3/contrib/geos/src/algorithm/ConvexHull.cpp:118:53: error: expected primary-expression before '>' token  
 118 |     auto cs = detail::make\_unique\<CoordinateSequence>(cv.size());  
     |                                                     ^  
At global scope:  
cc1plus: note: unrecognized command-line option '-Wno-errno=unused-private-field' may have been intended to silence earlier diagnostics  
cc1plus: note: unrecognized command-line option '-Wno-reserved-user-defined-literal' may have been intended to silence earlier diagnostics  
make\[2\]: \*\*\* \[contrib/geos/CMakeFiles/geos.dir/build.make:146: contrib/geos/CMakeFiles/geos.dir/src/algorithm/ConvexHull.cpp.o\] Error 1  
make\[1\]: \*\*\* \[CMakeFiles/Makefile2:2603: contrib/geos/CMakeFiles/geos.dir/all\] Error 2  
make: \*\*\* \[Makefile:136: all\] Error 2

### Steps to reproduce the behavior

clone rocksdb in an arch linux environment

$ gcc --version  
gcc (GCC) 13.1.1 20230429  
Copyright (C) 2023 Free Software Foundation, Inc.  
This is free software; see the source for copying conditions.  There is NO  
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by jowlyzhang** [comment]
These error messages doesn't seem to come from RocksDB code. Do you have the command to reproduce this?

**Comment by sangshuduo** [comment]
> These error messages doesn't seem to come from RocksDB code. Do you have the command to reproduce this?

sorry my mistake.
