### ISSUE TITLE
Crash tests blackbox run verification failed

### ISSUE THREAD

**Issue by dnanuti** [facebook/rocksdb#11531]
I am new to RocksDB. Following up on this blog-post (https://rocksdb.org/blog/2022/10/05/lost-buffered-write-recovery.html), I want to reproduce the scenarios described here using RocksDB 8.0.x.

I tried running blackbox tests against a release build in several ways, but did not get a successful build.
A part of the extra parameters are inspired from the CI definition:
https://github.com/facebook/rocksdb/blob/main/.circleci/config.yml#L521
The rest were set through trial and error with the errors in the output (e.g. `reopen=0` when WAL is disabled).

### Expected behavior
I would expect the test run to pass.

### Actual behavior
Blackbox run failing with: `Verification failed :(`
And stderr like:
```
stderr:
WARNING: prefix_size is non-zero but memtablerep != prefix_hash
error : inconsistent values for key 000000000000240D00000000000000B778787878787878: Get returns 0x25599103212023222D2C2F2E29282B2A35343736313033323D3C3F3E39383B3A05040706010003020D0C0F0E09080B0A15141716111013121D1C1F1E19181B1A, expected state does not have the key.
error : inconsistent values for key 000000000000263D000000000000012B00000000000000E1: Get returns 0x71B28B587574777679787B7A7D7C7F7E616063626564676669686B6A6D6C6F6E515053525554575659585B5A5D5C5F5E414043424544474649484B4A4D4C4F4E313033323534373639383B3A3D3C3F3E212023222524272629282B2A2D2C2F2E, expected state does not have the key.
error : inconsistent values for key 00000000000032C7000000000000010C78787878: Get returns 0xC3CFE816C7C6C5C4CBCAC9C8CFCECDCCD3D2D1D0D7D6D5D4DBDAD9D8DFDEDDDCE3E2E1E0E7E6E5E4EBEAE9E8EFEEEDECF3F2F1F0F7F6F5F4FBFAF9F8FFFEFDFC83828180878685848B8A89888F8E8D8C93929190979695949B9A99989F9E9D9C, expected state does not have the key.
Iterator has key 00000000000018C300000000000000C57878787878, but expected state does not.
Column family: default, op_logs: S 00000000000018C300000000000000BE787878787878 N SFP 00000000000018C300000000000000C778787878787878 P SFP 00000000000018C300000000000000C3787878 N
```

### Steps to reproduce the behavior
```
python -u ./db_crashtest.py --simple blackbox --duration=960 --max_key=2500000 --read_fault_one_in=0 --use_direct_io_for_flush_and_compaction=0 --async_io=0 --use_direct_reads=0 --reopen=0 --disable_wal=1 > crashtest-bbox.out
```

### Open questions
- Do you recommend running the tests against a debug build or release build?
- How to reproduce the existing tests consistently? 
- Are there any priorities for db_stress_tool on your radar?

**Comment by ajkr** [comment]
I ran the provided command five times on the main branch and didn't see any failure. My build command was simply `make -j56 db_stress`. My /tmp directory (where the DB and expected state are stored by default) is a btrfs file system.

Does it fail every time for you? Does it fail on the main branch or only 8.0.x?

**Comment by dnanuti** [comment]
I am trying to reproduce the scenarios from this blog post: https://rocksdb.org/blog/2022/10/05/lost-buffered-write-recovery.html. I noticed it's mentioning these are running as part of your CI. Would you please provide the configuration used for reproducing these?

I ran the tests against a binary built from RocksDB 8.0.0 (02/19/2023): https://github.com/facebook/rocksdb/tree/v8.0.0
The binary was built like this: `DEBUG_LEVEL=0 LIB_MODE=static make db_stress`

I did not achieve test runs with consistent results. 

`/tmp` is a `tmpfs` filesystem:
```
df -T /tmp
Filesystem     Type  Mounted on
tmpfs          tmpfs /tmp
```
But I did not encounter the error mentioned here: https://github.com/facebook/rocksdb/issues/7535

**Comment by fuatbasik** [comment]
@ajkr what do you see as the output after a successful run.  At my end (using Pyhton 3.11), I can see stdout if the subprocess dies itself (unhappy path) but cannot see it if subprocess times out (happy path) (see the codeblock below).
Since the outcome of the db_stress is written to the stdout, I am not able to confirm if the test outcome was actually successful.  This is probably because child.kill() clears stdout.

```
 try:
        outs, errs = child.communicate(timeout=timeout)
        hit_timeout = False
        print("WARNING: db_stress ended before kill: exitcode=%d\n" % child.returncode)
    except subprocess.TimeoutExpired:
        hit_timeout = True
        child.kill()
        print("KILLED %d\n" % child.pid)
        outs, errs = child.communicate()
```

**Comment by fuatbasik** [comment]
Hi @ajkr 
I just wanted to follow up on this. When running crash tests via tools/db_crashtest.py, are you able to see the stdout of the db_stress_tool?

**Comment by fuatbasik** [comment]
This PR should improve the validation coverage: https://github.com/facebook/rocksdb/pull/11592

**Comment by ajkr** [comment]
> I did not achieve test runs with consistent results, I experienced different failures.

Is this still an issue? I tried running the provided command (`python -u ./db_crashtest.py --simple blackbox --duration=960 --max_key=2500000 --read_fault_one_in=0 --use_direct_io_for_flush_and_compaction=0 --async_io=0 --use_direct_reads=0 --reopen=0 --disable_wal=1 > crashtest-bbox.out`) on tmpfs and v8.0.0 tag. Still, I did not encounter any failure. Perhaps try running it in single-threaded mode - considering the errors are all about expected state missing values, I wonder if the expected state is empty. If you run in single threaded mode and see missing values starting at key 0 that'd more or less confirm it.

**Comment by dnanuti** [comment]
> Is this still an issue? I tried running the provided command (python -u ./db_crashtest.py --simple blackbox --duration=960 --max_key=2500000 --read_fault_one_in=0 --use_direct_io_for_flush_and_compaction=0 --async_io=0 --use_direct_reads=0 --reopen=0 --disable_wal=1 > crashtest-bbox.out) on tmpfs and v8.0.0 tag. Still, I did not encounter any failure. Perhaps try running it in single-threaded mode - considering the errors are all about expected state missing values, I wonder if the expected state is empty. If you run in single threaded mode and see missing values starting at key 0 that'd more or less confirm it.

We have concluded that the issues we encountered were due to the usage of the same expected values directory across different blackbox test runs and fixed this by passing an individual value per blackbox run for `expected_values_dir` flag.
