### ISSUE TITLE
I compiled version 6.29.5 on arm64 but failed

### ISSUE THREAD

**Issue by hotwinters** [facebook/rocksdb#11548]
![lADPKIJfT61IFkPNC_TND_A_4080_3060 jpg_720x720q90g](https://github.com/facebook/rocksdb/assets/34262412/d2c2f4c0-5929-46cd-9fb0-2fd462a6af9e)

**Comment by hotwinters** [comment]
what should i do, i don't know how to compile

**Comment by mdcallag** [comment]
I don't know, but others will be able to find this issue via search if you copy/paste the error text rather than a screenshot.
