### ISSUE TITLE
Improve docs for subcompactions

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#11553]
The wiki page for subcompactions is hard to find (directly, or [via Google](https://www.google.com/search?q=rocksdb+subcompactions)) because the title is _sub-compactions_.

https://github.com/facebook/rocksdb/wiki/Sub-Compaction

The content on this page is useful but too brief.

**Comment by cbi42** [comment]
Added some more detail about how subcompaction key ranges are computed and renamed the wiki to [_Subcompaction_](https://github.com/facebook/rocksdb/wiki/Subcompaction). Let me know if you think anything else should be added.

**Comment by mdcallag** [comment]
Excellent. Thank you.
