### ISSUE TITLE
level_compaction_dynamic_level_bytes=true kill performance when max_subcompactions is configured

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#11559]
Recently we upgraded to rocksdb main branch, we observed significant performance degrades, we found it is because level_compaction_dynamic_level_bytes=true by default(#11525).

`max_subcompactions` makes `L0 + L1` -> `L1` compaction concurrently by multi sub compactions, when `level_compaction_dynamic_level_bytes=true`, data may be compacted from L0 to non-L1, which disables the concurrency, cause slowdown, even stop on high write workload.

**Comment by akankshamahajan15** [comment]
cc @cbi42  Do you have any context about it?

**Comment by cbi42** [comment]
> when level_compaction_dynamic_level_bytes=true, data may be compacted from L0 to non-L1, which disables the concurrency

I don't think this is true tho: subcompaction should only require input level to be L0 and output to be not L0: https://github.com/facebook/rocksdb/blob/ca50ccc71a1ce89008b4737e74f321b8df8a3b5b/db/compaction/compaction.cc#L790C78-L790C78. Is the performance impact caused by something else?

**Comment by rockeet** [comment]
> > when level_compaction_dynamic_level_bytes=true, data may be compacted from L0 to non-L1, which disables the concurrency
> 
> I don't think this is true though: subcompaction should only require input level to be L0 and output to be not L0: https://github.com/facebook/rocksdb/blob/ca50ccc71a1ce89008b4737e74f321b8df8a3b5b/db/compaction/compaction.cc#L790C78-L790C78. Is the performance impact caused by something else?

Confirmed, it is something else, very thanks @cbi42 !

**Comment by ajkr** [comment]
We are concerned about any surprises users find from changing the default level_compaction_dynamic_level_bytes from false to true, even if tangentially related. Was the root cause of your performance change totally unrelated to the default change?

**Comment by rockeet** [comment]
> We are concerned about any surprises users find from changing the default level_compaction_dynamic_level_bytes from false to true, even if tangentially related. Was the root cause of your performance change totally unrelated to the default change?

Yes, it is totally unrelated to the default change.
