### ISSUE TITLE
Is the behavior of ingest sst the same between setting dynamic level base and default

### ISSUE THREAD

**Issue by SpadeA-Tang** [facebook/rocksdb#11561]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

8.sst, 9.sst, and 11.sst are overlapped with each other, and 10.sst is not.
![a2320e7e-07a8-46c5-9f3a-9889b6f73c3a](https://github.com/facebook/rocksdb/assets/71589810/be6820c0-71d9-48dd-bef8-4ff47966a3b3)
This is the output of not setting dynamic level base.
![ca4d515d-4cb1-4225-9947-c1ee9befe8b0](https://github.com/facebook/rocksdb/assets/71589810/806cab9d-16bd-48e0-9bf3-fd578217bc42)
This is the output of setting dynamic level base.

Is this what we exepect?

**Comment by cbi42** [comment]
Hi - the code about this is old (https://github.com/facebook/rocksdb/blob/ca50ccc71a1ce89008b4737e74f321b8df8a3b5b/db/external_sst_file_ingestion_job.cc#L882-L885) but I think this is intended. I think the assumption was that when `level_compaction_dynamic_level_bytes` is true, the LSM consists of L0, then Lbase...Lmax. So if we cannot ingest into Lbase (L6 in this case), we should ingest into L0.

**Comment by SpadeA-Tang** [comment]
> Hi - the code about this is old (
> 
> https://github.com/facebook/rocksdb/blob/ca50ccc71a1ce89008b4737e74f321b8df8a3b5b/db/external_sst_file_ingestion_job.cc#L882-L885
> 
> ) but I think this is intended. I think the assumption was that when `level_compaction_dynamic_level_bytes` is true, the LSM consists of L0, then Lbase...Lmax. So if we cannot ingest into Lbase (L6 in this case), we should ingest into L0.

Thanks for the replay, if there's some potential problems if the code is modified as this.
![image](https://github.com/facebook/rocksdb/assets/71589810/9424f30f-7858-4edf-80b8-a27ecc235e9c)

**Comment by SpadeA-Tang** [comment]
> is there concern with ingesting files into L0?

Ingesting files into L0 may quickly cause write stall, which is not good for workloads when write and ingest are performed simultaneously.
And I see when level_compaction_dynamic_level_bytes is false, the ingest level is not either the bottom level or L0, so I have this doubt. Anyway, if it's intentional, that's fine.

**Comment by ajkr** [comment]
Does your bulk loaded data intend to overwrite/delete existing KVs, or does it just happen to land in L0 because its key-range overlaps some file that exists in the DB?

**Comment by SpadeA-Tang** [comment]
> Does your bulk loaded data intend to overwrite/delete existing KVs

Some ssts are overlapped with the previous ssts ingested, and lands in L0 as a result.

**Comment by ajkr** [comment]
I see.

> Anyway, if it's intentional, that's fine.

Yes, L0 seems like a reasonable place to put such overlapping files to me.

There might be ways to optimize compaction out of L0, but it doesn't sound like you need that. Let us know if my assumption is incorrect.
