### ISSUE TITLE
Compaction error: Corruption: Error while decoding blob record: Header CRC mismatch

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#11579]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

I have some trouble currently in `decoding blob record`. The last error, which has not been solved,  is [here](https://github.com/facebook/rocksdb/issues/11401) and now another error come out.

### Expected behavior
No error happened in compaction job.
### Actual behavior
 [db/db_impl/db_impl_compaction_flush.cc:3426] Compaction error: Corruption: Error while decoding blob record: Header CRC mismatch
### Steps to reproduce the behavior
Have no idea to reproduce it. It happened with a low frequency.
More infos:
rocksdb 7.2
centos 7
gcc 10.3
linux kernal  4.18.0

**Comment by ltamasi** [comment]
Probably the same issue as before; merging this into the earlier one.
