### ISSUE TITLE
Checking for key's existence returns different results with different methods

### ISSUE THREAD

**Issue by Mis1eader-dev** [facebook/rocksdb#11586]
### Expected behavior
All of the 4 methods of checking for a key should behave the same.

### Actual behavior
Only the `.GetXX` methods do this reliably. The other two are unpredictable.

### Steps to reproduce the behavior
```cpp
string sessionId = "\n"; // Key
bool exists;

// 1
string temp;
db->KeyMayExist(ReadOptions(), sessionsTable, sessionId, &temp, &exists);
return exists; // If key is an unprintable character, it returns true even
               // if the key doesn't exist, otherwise it does return false
               // if a printable character is in the key and it doesn't exist in the db

// 2
PinnableWideColumns pin;
return db->GetEntity(ReadOptions(), sessionsTable, sessionId, &pin).ok(); // Works as expected

// 3
string temp;
return db->Get(ReadOptions(), sessionsTable, sessionId, &temp).ok(); // Works as expected

// 4
const auto it = db->NewIterator(ReadOptions(), sessionsTable);
it->Seek(sessionId);
exists = it->Valid();
delete it;
return exists; // If key is an unprintable character, it returns true even
               // if the key doesn't exist, otherwise it does return false
               // if a printable character is in the key and it doesn't exist in the db
```

Update: `KeyMayExist` returns false even if the key exists, it might be reading from the cache.

**Comment by ajkr** [comment]
`Seek()`'s API allows it to land on a key at or after the seek key, so it might be positioned at some later key.

`KeyMayExist()`'s API allows it to return true for a key that doesn't exist, but does not allow it to return false for a key that does exist.

As far as I can tell the described behavior is aligned with the API. Let me know if you disagree.

**Comment by Mis1eader-dev** [comment]
I have been doing key existence checks with `db->Get(...)` and `db->GetEntity(...)` so far, but I believe they add unnecessary overhead for a simple check, copying the values and processing them, only to be discarded.

`KeyMayExist()` may have potential, but it isn't clear what it does exactly, and no mention of it in the wiki.
The comment written on the function definition is not clear either. It could be due to the usage of 'may'.
