### ISSUE TITLE
any ways to disable io_uring? running ubuntu 22.04 with kernel 5.15

### ISSUE THREAD

**Issue by kolinfluence** [facebook/rocksdb#11582]
any ways to disable io_uring? running ubuntu 22.04 with kernel 5.15, it doesnt seem to work with v8.1.1

my golang client only supports up to v8.1.1 for now and my kernel is 5.15

is there a way to disable io_uring during compile?

**Comment by lhsoft** [comment]
cmake -DWITH_LIBURING=off ..

**Comment by ajkr** [comment]
Or if using our Makefile, set the environment variable `ROCKSDB_USE_IO_URING=0`
