### ISSUE TITLE
Does prefix seek api avaliable for java in 4.5.1 version

### ISSUE THREAD

**Issue by jainshasha** [facebook/rocksdb#1159]
Hi,

I am not able to find the api in java for prefix seek functionality in 4.5.1 version of RocksDB.
Could anyone help me in confirming about this, would really appreciate that.

Regards,
Shashank Jain

**Comment by adamretter** [comment]
In the Java API - at the moment there is only support for the following prefix extractors:

1. FixedPrefixTransform
2. CappedPrefixTransform

These are currently available on Options and ColumnFamilyOptions via . `#useFixedLengthPrefixExtractor(int)` and `#useCappedPrefixExtractor(int) respectively.

**Comment by jainshasha** [comment]
Ohk, Thanks for the prompt reply.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
