### ISSUE TITLE
Respect ReadOptions.iterate_lower_bound_ during iterating in WBWI

### ISSUE THREAD

**Issue by luqun** [facebook/rocksdb#11607]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

in https://github.com/facebook/rocksdb/blob/main/utilities/write_batch_with_index/write_batch_with_index_internal.cc#L306, it only checks iterate_upper_bound_.  We should also check iterate_lower_bound_ if passed since ReadOptions support both iterate_lower_bound_ and iterate_upper_bound_ and customer doesn't expect only one bound is checked in WBWI.

### Expected behavior

iterate_lower_bound_ is checked if specified before data return to customer. 

For optimization, maybe in normal cf, only check iterate_upper_bound_ while in rev cf, only check iterate_lower_bound_?

### Actual behavior

Only iterate_upper_bound_ is checked..

### Steps to reproduce the behavior

NA, From code: https://github.com/facebook/rocksdb/blob/main/utilities/write_batch_with_index/write_batch_with_index_internal.cc#L306

**Comment by ywave620** [comment]
@jowlyzhang After diving into this a bit, I think I'm able to undertake this bug. Could you assign it to me

**Comment by jowlyzhang** [comment]
> @jowlyzhang After diving into this a bit, I think I'm able to undertake this bug. Could you assign it to me

Of course, thank you for working on this.
