### ISSUE TITLE
deleted record is returned during iterating in WBWI with upper bounds

### ISSUE THREAD

**Issue by luqun** [facebook/rocksdb#11606]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

When iterate_upper_bound is specified and data are stored in Write Batch with index. In BaseDeltaIterator::UpdateCurrent(),  It compares current retrieved key with iterate_upper_bound_ and find out the retrieved key is out of range, then it just return --- but at this time, the deltaiterator is still valid. see code https://github.com/facebook/rocksdb/blob/main/utilities/write_batch_with_index/write_batch_with_index_internal.cc#L307

### Expected behavior
These deleted KV pair shouldn't return during iterating in WBWI with upper bounds

### Actual behavior
The Deleted KV pair returned during iterating in WBWI with upper bounds

### Steps to reproduce the behavior
adding following test into utilities/transactions/transaction_test.cc, compile and run

  TEST_P(TransactionTest, UpperBoundTest) {
    // This test does writes without snapshot validation, and then tries to create
    // iterator later, which is unsupported in write unprepared.
    if (txn_db_options.write_policy == WRITE_UNPREPARED) {
      return;
    }

    WriteOptions write_options;
    ReadOptions read_options, snapshot_read_options;
    Status s;

    Transaction* txn = db->BeginTransaction(write_options);
    ASSERT_TRUE(txn);

    // Write some keys in a txn
    s = txn->Put("2", "2");
    ASSERT_OK(s);

    s = txn->Put("1", "1");
    ASSERT_OK(s);

    s = txn->Delete("2");
    ASSERT_OK(s);

    read_options.iterate_upper_bound = new Slice("2", 1);
    Iterator* iter = txn->GetIterator(read_options);
    ASSERT_OK(iter->status());
    iter->SeekToFirst();
    while(iter->Valid())
    {
      ASSERT_EQ("1", iter->key().ToString());
      iter->Next();
    }
    delete iter;
    delete txn;
  }

**Comment by cz2h** [comment]
It looks like the delta_iterator_ never sets its status to false as what base_iterator_ is doing. I'd like to work on this issue.
