### ISSUE TITLE
Broken link in rocksdb github wiki

### ISSUE THREAD

**Issue by cz2h** [facebook/rocksdb#11618]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

These two links seems to be pointing to incorrect URLs.

- This link I am assuming [this](https://github.com/facebook/rocksdb/wiki/RocksDB-Overview#:~:text=logfile%20(aka.%20Write%20Ahead%20Log(WAL))) points to the WAL wiki page, but I got redirected to the welcome page of wiki after clicking it.
- This [command](https://github.com/facebook/rocksdb/wiki/Building-on-Windows#:~:text=wget%20http%3A//zlib.net/zlib1211.zip) uses an expired link, referencing from [zlib](https://zlib.net/fossils/zlib-1.2.11.tar.gz)

### Expected behavior
The link and windows script works properly

**Comment by ltamasi** [comment]
Thanks for reporting! I fixed the link to the WAL page and updated the Windows build instructions to use the current zlib version (1.2.13).
