### ISSUE TITLE
which python lib is for rocksdb

### ISSUE THREAD

**Issue by code1704** [facebook/rocksdb#11612]
https://python-rocksdb.readthedocs.io/en/latest/ does not work with latest rocksdb

```
rocksdb/_rocksdb.cpp:772:10: fatal error: rocksdb/utilities/backupable_db.h: No such file or directory
     #include "rocksdb/utilities/backupable_db.h"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    compilation terminated.
```

Any suggestion?

**Comment by ltamasi** [comment]
`backupable_db.h` was removed in the 7.0 major release in early 2022 (see https://github.com/facebook/rocksdb/issues/9389). Seems like those Python bindings haven't been updated; in fact, that project hasn't been maintained for several years. (Note that it's a third-party project; RocksDB doesn't have official Python bindings.)
