### ISSUE TITLE
Compaction Iterator skip type deletion key wrongly when allow_ingest_behind == true

### ISSUE THREAD

**Issue by DWAE86** [facebook/rocksdb#11615]
Hello. Reading code in `compaction_iterator.cc`, I think it skips/drops type deletion key when it shouldn't, if we set `allow_ingest_behind == true`.
```cpp
    ...
    } else if (compaction_ != nullptr &&
               (ikey_.type == kTypeDeletion ||
                (ikey_.type == kTypeDeletionWithTimestamp &&
                 cmp_with_history_ts_low_ < 0)) &&
               DefinitelyInSnapshot(ikey_.sequence, earliest_snapshot_) &&
               compaction_->KeyNotExistsBeyondOutputLevel(ikey_.user_key,
                                                          &level_ptrs_)) {
      ...
      ++iter_stats_.num_record_drop_obsolete;
      if (!bottommost_level_) {
        ++iter_stats_.num_optimized_del_drop_obsolete;
      }
      AdvanceInputIter();
      ...
```
This code doesn't check `allow_ingest_behind`, and `KeyNotExistsBeyondOutputLevel()` will return true even if `allow_ingest_behind == true`, so this type deletion key will be skipped. if we ingest behind a type value key that has the same user key, it wouldn't be deleted and we will get unexpected result.

I'm not sure whether this is the expected behavior when `allow_ingest_behind == true`.

**Comment by cbi42** [comment]
Hi - I think this is the expected behavior. When nothing is ingested, keys with op_type kTypeDeletion or kTypeDeletionTimestamp can be dropped if they don't cover anything  (`KeyNotExistsBeyondOutputLevel()` returns true). allow_ingest_behind=true does not prevent this.

**Comment by DWAE86** [comment]
I'm having doubts because I think this dropping-deletionType-key action is an optimization. With or without it, the behavior should be same, but now they are not.

For example, in MergeHelper, if allow_ingest_behind=true, we don't transfer kTypeMerge to kTypeValue, so keys ingested behind after compaction can still be queried. I think for the same reason we shouldn't drop deletion key if allow_ingest_behind=true.

**Comment by DWAE86** [comment]
I think I got it wrong. Sorry for the trouble.
