### ISSUE TITLE
HyperClockCache: How to ensure the correctness of overwriting in standalone situations

### ISSUE THREAD

**Issue by wanghanrong9841** [facebook/rocksdb#11625]
When inserting two entries with the same key into HyperClockCache, the first one will be inserted into table, the second one will be set 'standalone'. Now if Lookup with the key, the first entry with old value will be returned, however the second entry with new value will never be found by Lookup. I am curious about how it ensures the correctness of the overwriting？

**Comment by jowlyzhang** [comment]
HyperClockCache is designed to be used as `BlockBasedTableOptions::block_cache`.Blocks rarely mutate, so supporting overwriting is not a priority for HyperClockCache. Per documentation from `clock_cache.h`:

```
// * Insert usually does not (but might) overwrite a previous entry associated
// with a cache key. This is OK for RocksDB uses of Cache.
```

```
// However, overwrite capability is not really needed by RocksDB. Also, we
// know from our "redundant" stats that overwrites are very rare for the block
// cache, so we should not spend much to make them effective.
```
