### ISSUE TITLE
Bulk loading vector memtable throughput performance

### ISSUE THREAD

**Issue by patelprateek** [facebook/rocksdb#11629]
Using rocks 6.8.1 

I am doing bulk load few hundred gb to terabyte scale.  
Few relevant params :
auto compaction : off
max_background_jobs=16
max_background_flushes=10
min_write_buffer_number_to_merge=4 , 
memtable size 64Mb

The only thing i changes was : 
memtable_factory: changed SkipListFactory  to VectorMemtableFactory
allow_concurrent_memtable_write: changed True to False 

I profile my indexing pipeline by logging time it takes to do initial load + flush and then final compaction
I observe with vector memtable (recommended option for large bulk loads) , i see a large 1.6x-2x increase in the initial load + flush time , is this expected ? On documentation i read the flush operation for vector memtable might be slower  , curios why ?

I am using same number of writer threads in both setup and i observe when i use Vector memtable , my inital write throughput to be almost 1.7x lower i.e 77Mb/s as opposed to 132Mb/s in case of skip list.

QQ : for vector memtable , if i have multiple writer thread , and allow_concurrent_memtable_write=False , how do multiple writer threads write to memtable , do they use some synchronization ?

### Expected behavior
Vector memtable should scale and be more performant and give better index load runtime 

### Actual behavior
Skiplist being more performant and if i increase writer threads i believe i can achieve even higher write throughput during inital load phase.

**Comment by ajkr** [comment]
I believe this was discussed in https://github.com/facebook/rocksdb/issues/11627#issuecomment-1647169454. LMK if anything else is needed
