### ISSUE TITLE
Compactfiles not respecting files to compact

### ISSUE THREAD

**Issue by patelprateek** [facebook/rocksdb#11627]
using version 6.8.1

Use case : Doing a bulk load of couple hundred GB data . Turned off auto compaction. 
Bottleneck is single threaded final compaction for thousands of files at L0 .  using CompactRange method for this final compaction.

To workaround this i tired following the suggestion from this [link](https://rockset.com/blog/optimizing-bulk-load-in-rocksdb/#:~:text=Rockset%20parallelizes%20writes%20on%20multiple,of%20the%20data%20while%20sorting.) 
```
There is a feature in RocksDB that enables multi-threaded compaction with option [max_subcompactions](https://github.com/facebook/rocksdb/blob/d61d4507c0980b544e87fd0aa5ed2990a45dad5e/include/rocksdb/options.h#L563-L567). However, increasing the number of subcompactions for our final compaction doesn’t do anything. With all files in level 0, the compaction algorithm cannot find good boundaries for each subcompaction and decides to use a single thread instead. We fixed this by first executing a priming compaction — we first compact a small number of files with [CompactFiles()](https://github.com/facebook/rocksdb/wiki/Manual-Compaction#compactfiles). Now that RocksDB has some files in non-0 level, which are partitioned by range,  it can determine good subcompaction boundaries and the multi-threaded compaction works like a charm with all cores busy
```

I get files using getLiveFiles api , sample few random files ~10-20 , then apply compactFile on top of this

### Expected behavior
I would expect the compact file to take few seconds to merge the small number of files , butlooking at logs it doesnt seem like that. The timers  show it is taking hours to compact all the files and then the next call to compactRange again takes a smaller amount of time.Also i observe only single thread with ~<5% cpu usage , so it seems even after the compact call there is no parallel compaction going on.
Any ideas or how can i make the final compaction multi threaded ?

### Actual behavior
I would expect compactFiles call to return within seconds and then parallelization in the next compactRange api call to be doen in parallel based onoptions like max_subcompaction and max_background_compaction

**Comment by ajkr** [comment]
The expected behavior needs to account for the LSM invariant that newer versions of any given key reside in a higher level. If you pick a random sample of L0 files to compact, we must include all older overlapping L0 files to preserve that invariant.

Have you tried picking the oldest few L0 files to invoke `CompactFiles()` on? I am not sure if it will still pick the newer ones, but if so I'd at least call that an implementation limitation. If that is a problem you could workaround it by calling the `CompactFiles()` as soon as a few L0 files are generated while bulk loading is still happening.

**Comment by patelprateek** [comment]
@ajkr Thanks for the clarifying this . Let me try to pick some old set of files .
BTW is there some metadata of live files that i could use to pick older files instead of random sampling ?

**Comment by patelprateek** [comment]
@ajkr : can you please give me some pointers on how to find the oldest file for a given level ? I am using rocksdb-jni through java . 
when doing `livefilesMetadata` or `liveFiles` api , does rocks db returns the list based on file creation timestamp ? 

Also regarding the second approach of triggering compaction after first few files , is there a way to trigger such a compaction only once and disable compaction for the rest of the ingestion. from what i can tell the options doesnt doesnt give this ability  ?

**Comment by ajkr** [comment]
For the second approach I was thinking you would call one of the GetLiveFiles() APIs fairly early on in the ingestion when there are only a few L0 files. Then you can pass all of the files it returns to CompactFiles(). You can run this CompactFiles() in a separate thread in parallel with your ingestion. You can keep auto-compaction disabled the whole time. Then run a CompactRange() with subcompaction enabled at the end.

By the way, I haven't checked whether this restriction still applies in more recent versions. It might be fixed.

**Comment by patelprateek** [comment]
I tried the second approach : every million entries i check for livefiles and if i have some minimal number of liveFiles ~10-20 i run compactFiles . But i am running into few issues that i dont understand
```
compact being called on files with filenames [/000013.sst, /000012.sst, /000011.sst, /000010.sst, /000009.sst, /000008.sst, /000006.sst, /CURRENT, /MANIFEST-000007, /OPTIONS-000005]
```

It seems like there are some `Live files`  that i should not be compacting. 
Also when i call the compactFiles (with flush=False) on the above set of files , it throws an exception saying

```
org.rocksdb.RocksDBException: Specified compaction input file /000000.sst does not exist in column family default.
	at org.rocksdb.RocksDB.compactFiles(Native Method)
	at org.rocksdb.RocksDB.compactFiles(RocksDB.java:3474)
	at org.rocksdb.RocksDB.compactFiles(RocksDB.java:3439)
```

I am not really sure why it is looking for `000000.sst` when it is not even in the list of filenames i provide. Is it looking for some old sst file that it expects to have. 
Also why does the sst files numbering star from 6 and not 0 ?  what parameters in roksdb option impact this sst file numbering ?

**Comment by ajkr** [comment]
It might not return a proper error message, but CompactFiles() should only be called with SST files. "/CURRENT, /MANIFEST-000007, /OPTIONS-000005" aren't SST files

**Comment by patelprateek** [comment]
Yes i suspected that , so i switched to fetching only sst files using 
```
GetColumnFamilyMetaData().levels().get(0).files()
```

I still do not see parallelism during final compaction.
my current option config is 
max_background_compactions=16
num_levels=2
max_background_compactions=16
max_background_flushes=10
max_subcompactions=16

Still very low <3% cpu utilization and only ~100 MB/s disk write rate during the compaction stage . Using a pd-ssd disk , so i am hoping i can increase the throughput much higher if i can parallelize this final compaction.

Any other methods i should try to parallelize final compaction 
- should i switch to universal compaction ? I dont care about space amplifcation , will this be faster or more efficient io ?
- any other flags i might be missing 
- will enable thread_tracking allow me to look into logs to confirm only single thread , what else can i look into log to understand why not parallelizing ?

**Comment by ajkr** [comment]
The config looks good. How many L1 files does the CompactFiles() produce? More L1 files is better as we use their boundaries for splitting into subcompactions in the RocksDB version you are using (https://github.com/facebook/rocksdb/blob/f48aa1c3084700bc72b73ee36f027e428f0dda86/db/compaction/compaction_job.cc#L480). Version 7.6+ doesn't have that restriction

**Comment by patelprateek** [comment]
I am using 2 levels . 
Since auto compaction is off all files are in L0 during ingestion phase (i also verified this by checking files present at each level prior to any compaction invoked)

One thing you were correct about is if the files are oldest , compaction runs faster than random sample .

The weird thing i am observing now is post compactFile call , it only generates 1 L1 file , the number of L0 files are correctly reduced by the exact number i asked it to compact.

Does compact file do not adhere to target_file_size limitation ? 
All my memtable are 64 Mb , i use `min_write_buffer_number_to_merge=4` , so i would expect L0 files to 256Mb 
I also set `target_file_size_base=268435456` , so L1 (last level in my case ) files should also be 256 Mb . 
I dont understand how or why it generates 1  L1 file after merging 4 256Mb L0 file  (my inital bulk load data has no duplicates  or updates , its all inserts of unique KV). Also i tried ``min_write_buffer_number_to_merge=2` to see if i reduce L0 file size , if it impacts compcted file , but still observe only 1 L1 file.

**Comment by patelprateek** [comment]
Also regarding your comment about version 7.6 `restriction` , can you please elaborate what restriction is this ? Are you talking `The expected behavior needs to account for the LSM invariant that newer versions of any given key reside in a higher level. If you pick a random sample of L0 files to compact, we must include all older overlapping L0 files to preserve that invariant.`

**Comment by patelprateek** [comment]
One interesting observation is , when i  was accidentally providing the most recent 20-30 files for compaction , the CompactFiles would compact all the files (as you had explained before) , generated 1 giant file in L1 with 0 files left in L0

The size of this giant file is 50% smaller than the combined size of few hundred SST files  that were being produced when 
i wasnt trying to parallelize the final compaction (and also the case where i tried compaction on the first 20-30 oldest files , in this case it produces 1 SST file in L1  from the `compactFiles` api (with few hundred files left for compaction at L0) , and then the final `compactRange` call would move everything to L1 respecting the target_file_size param).

I do not have any sort of compression at any level configured , so another thing i am curious about is why 1 SST file size is almost 50% smaller in one giant single file compaction  ((in all the cases i am ingesting the exact same data , with same configuration , only difference is calling compactFiles and files i provide to compactFiles)

**Comment by patelprateek** [comment]
I think i figured it out , the compactionOptions that i was passing to compactFiles uses the default params of `target_output_file_size = -1` and `compressionType=snappy` . After fixing that i do observe much better parallelization.

**Comment by ajkr** [comment]
> Also regarding your comment about version 7.6 `restriction` , can you please elaborate what restriction is this ?

I meant to refer to the original restriction from the Rockset blog post: "With all files in level 0, the compaction algorithm cannot find good boundaries for each subcompaction and decides to use a single thread instead."

Since version 7.6, we changed the way we pick subcompaction boundaries (#10393). We no longer rely on file boundaries for subcompaction boundaries so it shouldn't matter that all the files are in L0.

**Comment by patelprateek** [comment]
@ajkr : Thanks for all the help , it seems the jobs are running  fine. 
The one major I am observing now are  : 
 using vector Memtable is much slower than skiplist . In the bulk load documentation it was recommended to use vector memtable so i am curios what could be the limiting factor. From what i can tell the slowness is in the initial ingestion to L0 (writing to memtable + flush) operation.  The throughput is almost 50% slower and also the cpu utilization is almost 30%-40% lower when i switch to vector memtable keeping every other parameter same (also concurrent_writes writes changed to False) .  
I am using writeBatch instead of puts (puts has lower degradation when switching from skiplist to vector memtable relative to the degradation when using writeBatch. WriteBatch has much better throughput in the inital ingestion phased almost 2x better).

Is this expected ?  
Also can you please advise on writebatch size ? when i increase the number of elements in my single writebatch , i see lower cpu usage , lower throughput , longer ingestion time as well , but a batch size of 16-32 seems more ideal than 100 and above.

**Comment by ajkr** [comment]
If you are comparing skiplist with concurrent_writes true against vector with concurrent_writes false, I think it is expected. I see a roughly similar result:

skiplist with concurrent writes:
```
TEST_TMPDIR=./dbbench ./db_bench -benchmarks=fillrandom -write_buffer_size=1048576 -batch_size=16 -num=1000000 -disable_auto_compactions=true -threads=10 -allow_concurrent_memtable_write=true
...
fillrandom   :       7.020 micros/op 1416556 ops/sec 7.059 seconds 10000000 operations;  156.7 MB/s
```

vector without concurrent writes:
```
TEST_TMPDIR=./dbbench ./db_bench -benchmarks=fillrandom -write_buffer_size=1048576 -batch_size=16 -num=1000000 -disable_auto_compactions=true -threads=10 -memtablerep=vector -allow_concurrent_memtable_write=false
...
fillrandom   :       9.333 micros/op 1067026 ops/sec 9.372 seconds 10000000 operations;  118.0 MB/s
```

I don't have advice on specific write batch sizes, but you can probably experiment quicker with different sizes by coming up with db_bench commands like the above, and varying the `-batch_size` parameter
