### ISSUE TITLE
Sequence number of Write/WriteBatch

### ISSUE THREAD

**Issue by findmenowhere** [facebook/rocksdb#11622]
Hi, I'm asking for exposing the seq number of write/writeBatch operations to users. Previous discussion: https://github.com/facebook/rocksdb/issues/2146

This information is highly valuable in the replication scenario. With the provision of the sequence number, users can easily confirm whether RocksDB replication has successfully received the specific key-value pair.

Thanks in advance!

**Comment by jowlyzhang** [comment]
Hello, we didn't have plans to expose sequence number. There is a user-defined timestamp feature https://github.com/facebook/rocksdb/wiki/User-defined-Timestamp-%28Experimental%29 that can help with user-defined multi versioning.

**Comment by findmenowhere** [comment]
Thanks! Got it.
