### ISSUE TITLE
  How to use the latest version of Rocksdb in C++11

### ISSUE THREAD

**Issue by darkhacker8** [facebook/rocksdb#11637]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Our project is version c++11, and we hope to use the latest version of RockSDB that relies on c++17

 is there any other way to use the latest version of rocksdb in our project without changing C++11

### Actual behavior
In the C++11 project, rocksdb 'string' appeared when compiling rocksdb_ View 'in namespace' std 'does not name a type problem

**Comment by adamretter** [comment]
@darkhacker8 RocksDB requires C++ 17 at the source code level. You might be able to build the RocksDB static/dynamic library binary and link to it from your project in C++ 11.

**Comment by darkhacker8** [comment]
Thank you for your answer, but I ran into another problem: compile RocksDB statically/Dynamic compilation into. so and. a files, and start the project to import the compiled files. Both methods will generate strings_ View cannot find the error. What I understand is that regardless of whether dynamic or static compilation is a binary file, why does introducing a string when running a project still result in missing strings_ View error

**Comment by darkhacker8** [comment]
> @darkhacker8 RocksDB requires C++ 17 at the source code level. You might be able to build the RocksDB static/dynamic library binary and link to it from your project in C++ 11.

Thank you for your answer, but I ran into another problem: compile RocksDB statically/Dynamic compilation into. so and. a files, and start the project to import the compiled files. Both methods will generate strings_ View cannot find the error. What I understand is that regardless of whether dynamic or static compilation is a binary file, why does introducing a string when running a project still result in missing strings_ View error

**Comment by adamretter** [comment]
I cant' answer your question. You have not provided enough information about what a 'project' is?
