### ISSUE TITLE
Add an option for block cache to cache writes

### ISSUE THREAD

**Issue by jjhuo** [facebook/rocksdb#1164]
We have a workload(Ceph bluestore on SSDs), whole db size is about 0.5GB to 4GB per 400GB drive, uncompressed and constantly being updated(at a rate about 5K per second, but we want more). And we don't want rocksdb to share page cache with others, and want to configure rocksdb to use fixed amount of memory, so tried to use block cache to replace page cache. db read is good, slightly better than page cache; but db updates suffers, tps with block cache dropped by half compared to page cache, because block cache doesn't cache sst file writes then compaction will have read blocks from drive again. Can rocksdb have an option to enable block cache to cache all or partial writes?

**Comment by siying** [comment]
We do plan to explore the possibility of warm block cache after generating new SST files. For now, it's not supported.

**Comment by jjhuo** [comment]
Thanks, Siying. Do you have an estimate when this feature will be developed?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
