### ISSUE TITLE
Aync_io doesn't work for db_bench

### ISSUE THREAD

**Issue by DarthVaderSCY** [facebook/rocksdb#11678]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Like in https://rocksdb.org/blog/2022/10/07/asynchronous-io-in-rocksdb.html, scan with async_io should have better performance than without.
### Actual behavior
I test db_bench with --benchmarks="seekrandom", but in db/arena_wrapped_db_iter.cc, env->GetFileSystem()->use_async_io() always returns false, which will result in the option "read_options_.async_io" turning to false. My Linux version is 5.19.0, and the file system of tested dbs is XFS. I read in your document that async_io only supports PosixFileSystem. Does XFS belong to PosixFileSystem, or there's some other requirement?

**Comment by akankshamahajan15** [comment]
Can you share what db_bench command are you using?
