### ISSUE TITLE
db_bench problem

### ISSUE THREAD

**Issue by Lsgoose** [facebook/rocksdb#11687]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Actual behavior
When I run db_bench with --benchmarks = fillseq, it fails. Here is the error:
2023/08/09-16:17:27.826754 ae6b [WARN] [db/db_impl/db_impl_open.cc:2173] DB::Open() failed: IO error: No such file or directory: While renaming a file to /tmp/rocksdbtest-0/dbbench/IDENTITY: /tmp/rocksdbtest-0/dbbench/000000.dbtmp: No such file or directory
2023/08/09-16:17:27.826937 ae6b [db/db_impl/db_impl.cc:489] Shutdown: canceling all background work
2023/08/09-16:17:27.827489 ae6b [db/db_impl/db_impl.cc:692] Shutdown complete
open error: IO error: No such file or directory: While renaming a file to /tmp/rocksdbtest-0/dbbench/IDENTITY: /tmp/rocksdbtest-0/dbbench/000000.dbtmp: No such file or directory
How can I solve it ?

**Comment by akankshamahajan15** [comment]
Can you share the complete `db_bench` command? One way to mitigate is specify `--db=`
