### ISSUE TITLE
Conflicting documentation about db_bench behavior when -seed=0

### ISSUE THREAD

**Issue by fandahao17** [facebook/rocksdb#11706]
### Expected behavior

In db_bench's [source code](https://github.com/facebook/rocksdb/blob/6a3da5635e1013f03930453481f49724f2319252/tools/db_bench_tool.cc#L288), it says "When (-seed is) 0 it is derived from the current time."

``` C
DEFINE_int64(seed, 0,
             "Seed base for random number generators. "
             "When 0 it is derived from the current time.");
```

The RocksDB Wiki is supposed to be consistent with the code.

### Actual behavior

The [Wiki for db_bench ](https://github.com/facebook/rocksdb/wiki/Benchmarking-tools)says "When 0 it is deterministic". The word "deterministic" is a bit misleading. At first we thought this means the seed is fixed to 0 or some "deterministic" number.

**Comment by mdcallag** [comment]
I agree the wiki should match the code. There were a few obscure problems related to --seed in the past. The wiki needs to be updated to match the code. If you want to much information about the obscure problems [start here](http://smalldatum.blogspot.com/2022/02/rocksdb-externals-avoiding-problems.html).

**Comment by ajkr** [comment]
I deleted the output of `./db_bench -help` from the wiki. Users can run `./db_bench -help` to learn the current meaning of all the options.
