### ISSUE TITLE
`keyMayExist` in the Java API incomplete

### ISSUE THREAD

**Issue by adamretter** [facebook/rocksdb#1171]
`RocksDB#keyMayExist` in the Java API does not allow control over whether the value should be returned or not, i.e. there is no control over the initial value of `value_found`.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by adamretter** [comment]
Fixed by https://github.com/facebook/rocksdb/pull/6186
