### ISSUE TITLE
Print default values statistic based matrix of rocksdb

### ISSUE THREAD

**Issue by Shalaka1197** [facebook/rocksdb#11752]
Print default values of below statistic based matrix of rocks dB using java.

- - bytes-written-rate
- • bytes-read-rate
- • memtable-bytes-flushed-rate
- • memtable-hit-ratio
- • block-cache-data-hit-ratio
- • block-cache-index-hit-ratio
- • block-cache-filter-hit-ratio
- • write-stall-duration-[avg | total]
- • bytes-read-compaction-rate
- • number-open-files
- • number-file-errors-total

**Comment by anand1976** [comment]
@Shalaka1197 Please clarify what exactly the issue is.

**Comment by donggyu04** [comment]
@anand1976 

How to use rocksdb statistic by using jni? could you show me any example?

**Comment by Shalaka1197** [comment]
@anand1976 I need to print these matrix in console .I am using Kafka streams and Java. Please can you give any sample code

**Comment by Shalaka1197** [comment]
@anand1976 You can use Metrics Reporter interface of Kafka to print those metrics.
