### ISSUE TITLE
Options misconfigured when read only mode

### ISSUE THREAD

**Issue by patelprateek** [facebook/rocksdb#11750]
In my use case i am configuring options on my indexing path (write-only) .
When SST files are generated i also observe an Options files is also persisted which shows the options that i had configured during  indexing.

When i copy over these file to read only instance and open the DB in read-only mode , i see few options parameters different than what is used in indexing.
my code structure is like 
```
  rocksdb::Options options;
  options.paranoid_checks = false;
  options.max_background_jobs = 0;
  options.max_file_opening_threads = 1;
  rocksdb::BlockBasedTableOptions to;
  to.block_cache = cache;
  to.cache_index_and_filter_blocks = true;
  to.pin_l0_filter_and_index_blocks_in_cache = false;
  to.pin_top_level_index_and_filter = true;
  options.table_factory.reset(rocksdb::NewBlockBasedTableFactory(to));

  rocksdb::DB* db;
  rocksdb::Status status;
  if (read_only) {
    status =
        rocksdb::DB::OpenForReadOnly(options, path, cf_descs, &cf_handles, &db);
  } else {
    status = rocksdb::DB::Open(options, path, cf_descs, &cf_handles, &db);
  }
```

I was under the assumption the options file persisted during indexing takes precendence and will be used when i call `OpenForReadOnly` and overwrite any thing configured prior ? 
If i have to tune some options on the read only side and for the remaining use the indexing side options, should i be modifying options post opening the db ? 
Any guidance on correct usage or setting options will be helpful

**Comment by anand1976** [comment]
@patelprateek For questions about usage etc., we encourage posting to public dev groups rather than opening an issue in Github.

> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

To begin with, please see this wiki about the options file - https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File
