### ISSUE TITLE
C# support 

### ISSUE THREAD

**Issue by mike7ang1rdz** [facebook/rocksdb#11808]
Is there any chances of getting c# net core 6+ support?

**Comment by ajkr** [comment]
There are a couple C# language binding projects we have heard about; see https://github.com/facebook/rocksdb/blob/main/LANGUAGE-BINDINGS.md

**Comment by theolivenbaum** [comment]
@mike7ang1rdz We maintain an up to date binding at https://github.com/curiosity-ai/rocksdb-sharp/
You just need to add this package: https://www.nuget.org/packages/rocksdb/
