### ISSUE TITLE
Rocks Counters in Java API

### ISSUE THREAD

**Issue by darionyaphet** [facebook/rocksdb#1184]
Hi : 

Have Java API could support Counters ? I don't found how to use it .

**Comment by adamretter** [comment]
@darionyaphet Do you mean a key/value pair where the value is an atomic increment?

If so then yes, first you should probably read - https://github.com/facebook/rocksdb/wiki/Merge-Operator

Then you can use the `ColumnFamilyOptions#setMergeOperatorName(String)`, the name to use for the add merge operator is `uint64add`.

Does that help you?

**Comment by darionyaphet** [comment]
@adamretter Yes it's Thanks a lot ~~
