### ISSUE TITLE
RocksJava: make RocksDBException a RuntimeException

### ISSUE THREAD

**Issue by phraktle** [facebook/rocksdb#1185]
Checked exceptions on every database operation are unwieldy (especially in Java 8 lambdas) and are usually handled in a higher layer so you tend to propagate them instead of handling locally.

Hence the request is to make RocksDBException an un-checked exception to make the API usage more convenient.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
