### ISSUE TITLE
rocksdb::BlockPrefixIndex::GetBlocks error

### ISSUE THREAD

**Issue by helloleef** [facebook/rocksdb#1186]
(gdb) bt
#0  0x00007f58ee798425 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f58ee79bb8b in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000001237fbd in __gnu_cxx::__verbose_terminate_handler() () at ../../../../gcc-4.9.3/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00000000011dff96 in __cxxabiv1::__terminate(void (*)()) () at ../../../../gcc-4.9.3/libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00000000011dffe1 in std::terminate() () at ../../../../gcc-4.9.3/libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00000000011ded2f in __cxa_pure_virtual () at ../../../../gcc-4.9.3/libstdc++-v3/libsupc++/pure.cc:50
#6  0x00000000010a79bc in rocksdb::BlockPrefixIndex::GetBlocks(rocksdb::Slice const&, unsigned int**) () at table/block_prefix_index.cc:215
#7  0x00000000010a62b3 in rocksdb::BlockIter::PrefixSeek(rocksdb::Slice const&, unsigned int*) () at table/block.cc:294
#8  0x00000000010a6377 in rocksdb::BlockIter::Seek(rocksdb::Slice const&) () at table/block.cc:93
#9  0x00000000010a185f in rocksdb::BlockBasedTable::Get(rocksdb::ReadOptions const&, rocksdb::Slice const&, rocksdb::GetContext*, bool) ()

```
at table/block_based_table_reader.cc:1235
```
#10 0x000000000115f107 in rocksdb::TableCache::Get(rocksdb::ReadOptions const&, rocksdb::InternalKeyComparator const&, rocksdb::FileDescriptor const&, rocksdb::Slice const&, rocksdb::GetContext_, rocksdb::HistogramImpl_, bool) () at db/table_cache.cc:271
#11 0x0000000001169c54 in rocksdb::Version::Get(rocksdb::ReadOptions const&, rocksdb::LookupKey const&, std::string_, rocksdb::Status_, rocksdb::MergeContext_, bool_, bool_, unsigned long_) () at db/version_set.cc:903
#12 0x000000000111094b in rocksdb::DBImpl::GetImpl(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle_, rocksdb::Slice const&, std::string_, bool*) ()

```
at db/db_impl.cc:3289
```
#13 0x0000000001110af9 in rocksdb::DBImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle_, rocksdb::Slice const&, std::string_) () at db/db_impl.cc:3197
#14 0x00000000010d2fc5 in rocksdb::DBWithTTLImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle_, rocksdb::Slice const&, std::string_) ()

```
at utilities/ttl/db_ttl_impl.cc:195
```

any body met this ?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
