### ISSUE TITLE
Logger class/object in C-API

### ISSUE THREAD

**Issue by ehamilto** [facebook/rocksdb#1188]
Hi,

I see that when it comes to logging features, the C-API provides these two functions,

`
extern ROCKSDB_LIBRARY_API void rocksdb_options_set_env(rocksdb_options_t*,
                                                        rocksdb_env_t*);
extern ROCKSDB_LIBRARY_API void rocksdb_options_set_info_log(rocksdb_options_t*,
rocksdb_logger_t*);
`

However, I don't see that it provides for the creation of objects of type rocksdb_logger_t. 

Thank you in advance,

Ethan.

**Comment by dhruba** [comment]
I think you have to implement GetOptions in the C code here:
https://github.com/facebook/rocksdb/blob/master/db/c.cc#L1899

Inside the Options object returned via the above call, you will find a pointer to the logger by accessing opt->rep.info_log. Similar to here:
https://github.com/facebook/rocksdb/blob/master/db/c.cc#L1471

**Comment by ehamilto** [comment]
Thanks, this is useful info.
