### ISSUE TITLE
db_bench threads problem

### ISSUE THREAD

**Issue by wanglinke521** [facebook/rocksdb#11891]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

###
When I use this db_bench command with a larger threads setting for concurrent writes, it doesn't improve the speed. In fact, it is slower than a single-threaded write. Additionally, the number of SST files persisted to disk is also similar. What is the reason for this? Thanks.
```
db_bench --benchmarks=fillseq,levelstats --compression_type=none histogram=true --statistics=true --num=960000000 --key_size=1024 --value_size=2048 --stats_interval_seconds=240 --db=./test --threads=64
```

**Comment by jowlyzhang** [comment]
Is this something you can repeatedly reproduce? Would you mind sharing the two `db_bench` commands you run to get this contrasting results, and the running results themselves?

**Comment by mdcallag** [comment]
The fillseq workload with 1 thread benefits from trivial move, while with more than one thread it. With trivial move there is less write-amp and will be fewer write stalls. For more on trivial move [see here](https://www.google.com/search?q=site%3Asmalldatum.blogspot.com+trivial+move)

With one thread the clients write 19.37GB of data into the LSM tree, it is written once to the WAL and then again during memtable flush, but there is no compaction beyond that -- see the Write(GB) and Moved(GB) columns and the Write(GB) column is 0 except for L0 because that is where the memtable flush writes are counted.

With more than one thread the Write(GB) column is non-zero for levels beyond L0.

With
```
nk=10000000; for nt in 1 2 4 8; do echo Run for nt $nt at $( date ); ./db_bench --benchmarks=fillseq,levelstats,stats --compression_type=none histogram=true --statistics=true --num=$nk --key_size=16 --value_size=2048 --compression_type=none --db=./test --threads=$nt >& o.nt${nt}.nk${nk} ; done
```

For 1 thread
```
Cumulative writes: 10M writes, 10M keys, 10M commit groups, 1.0 writes per commit group, ingest: 19.37 GB, 250.85 MB/s
...
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      0/0    0.00 KB   0.0      0.0     0.0      0.0      19.4     19.4       0.0   1.0      0.0    332.0     59.83             30.19       313    0.191       0      0       0.0       0.0
  L1      1/0   63.45 MB   0.2      0.0     0.0      0.0       0.0      0.0      19.4   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
  L2     40/0    2.48 GB   1.0      0.0     0.0      0.0       0.0      0.0      19.3   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
  L3    272/0   16.86 GB   0.7      0.0     0.0      0.0       0.0      0.0      16.9   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum    313/0   19.40 GB   0.0      0.0     0.0      0.0      19.4     19.4      55.6   1.0      0.0    332.0     59.83             30.19       313    0.191       0      0       0.0       0.0
 ```

For 2 threads
```
Cumulative writes: 20M writes, 20M keys, 19M commit groups, 1.0 writes per commit group, ingest: 38.74 GB, 226.97 MB/s
..
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      2/0   63.90 MB   0.5      0.0     0.0      0.0      19.9     19.9       0.0   1.0      0.0    296.3     68.77             34.84       635    0.108       0      0       0.0       0.0
  L1      2/0   157.38 MB   0.6     21.9    17.5      4.5      21.6     17.1       2.4   1.2    307.4    302.0     73.08             65.44       139    0.526     11M   197K       0.0       0.0
  L2     40/0    2.30 GB   0.9     11.0     8.9      2.0      10.9      8.8      10.4   1.2    328.0    325.9     34.20             31.45        71    0.482   5630K    36K       0.0       0.0
  L3    304/0   16.92 GB   0.7      0.0     0.0      0.0       0.0      0.0      16.9   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum    348/0   19.44 GB   0.0     32.9    26.4      6.5      52.3     45.8      29.7   2.6    191.3    304.4    176.05            131.74       845    0.208     16M   234K       0.0       0.0
 ```
 
 For 4 threads
 ```
 Cumulative writes: 40M writes, 40M keys, 20M commit groups, 2.0 writes per commit group, ingest: 77.26 GB, 309.11 MB/s
 ...
 Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      3/0   50.03 MB   0.8      0.0     0.0      0.0      20.6     20.6       0.0   1.0      0.0    248.6     84.94             42.53      1269    0.067       0      0       0.0       0.0
  L1      2/1   257.24 MB   0.5     31.1    19.3     11.9      30.1     18.2       1.3   1.6    316.7    305.7    100.67             88.95       296    0.340     16M   554K       0.0       0.0
  L2     49/1    2.41 GB   1.0     10.5     9.4      1.1      10.4      9.3       9.8   1.1    323.6    321.1     33.15             30.50        75    0.442   5383K    42K       0.0       0.0
  L3    316/0   16.75 GB   0.7      0.0     0.0      0.0       0.0      0.0      16.7   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum    370/2   19.46 GB   0.0     41.6    28.7     12.9      61.1     48.2      27.9   3.0    194.8    285.8    218.76            161.98      1640    0.133     21M   596K       0.0       0.0
 ```

**Comment by wanglinke521** [comment]
> Is this something you can repeatedly reproduce? Would you mind sharing the two `db_bench` commands you run to get this contrasting results, and the running results themselves?

Thank you very much for your response. Here are the experimental results for the two different thread counts:
- For 1 thread
```
db_bench --benchmarks=fillseq,levelstats --compression_type=none histogram=true --statistics=true --num=1000000 --key_size=1024 --value_size=2048 --stats_interval=10000 --threads=1 --db=./test
```
```
fillseq      :      74.287 micros/op 13461 ops/sec 74.287 seconds 1000000 operations;   39.4 MB/s

Level Files Size(MB)
--------------------
  0        1       63
  1        1       63
  2       40     2539
  3        4      254
  4        0        0
  5        0        0
  6        0        0

```
- For 10 threads
```
db_bench --benchmarks=fillseq,levelstats --compression_type=none histogram=true --statistics=true --num=1000000 --key_size=1024 --value_size=2048 --stats_interval=10000 --threads=10 --db=./test
```
```
fillseq      :     211.399 micros/op 47176 ops/sec 211.970 seconds 10000000 operations;  138.2 MB/s

Level Files Size(MB)
--------------------
  0       11      265
  1       10      581
  2       36     2312
  3        0        0
  4        0        0
  5        0        0
  6        0        0
```
From the experimental results, it can be observed that the number of files written and the occupied space are not significantly different between the two scenarios. However, the scenario with 10 threads take longer to complete.

**Comment by wanglinke521** [comment]
> The fillseq workload with 1 thread benefits from trivial move, while with more than one thread it. With trivial move there is less write-amp and will be fewer write stalls. For more on trivial move [see here](https://www.google.com/search?q=site%3Asmalldatum.blogspot.com+trivial+move)
> 
> With one thread the clients write 19.37GB of data into the LSM tree, it is written once to the WAL and then again during memtable flush, but there is no compaction beyond that -- see the Write(GB) and Moved(GB) columns and the Write(GB) column is 0 except for L0 because that is where the memtable flush writes are counted.
> 
> With more than one thread the Write(GB) column is non-zero for levels beyond L0.
> 
> With
> 
> ```
> nk=10000000; for nt in 1 2 4 8; do echo Run for nt $nt at $( date ); ./db_bench --benchmarks=fillseq,levelstats,stats --compression_type=none histogram=true --statistics=true --num=$nk --key_size=16 --value_size=2048 --compression_type=none --db=./test --threads=$nt >& o.nt${nt}.nk${nk} ; done
> ```
> 
> For 1 thread
> 
> ```
> Cumulative writes: 10M writes, 10M keys, 10M commit groups, 1.0 writes per commit group, ingest: 19.37 GB, 250.85 MB/s
> ...
> ** Compaction Stats [default] **
> Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>   L0      0/0    0.00 KB   0.0      0.0     0.0      0.0      19.4     19.4       0.0   1.0      0.0    332.0     59.83             30.19       313    0.191       0      0       0.0       0.0
>   L1      1/0   63.45 MB   0.2      0.0     0.0      0.0       0.0      0.0      19.4   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
>   L2     40/0    2.48 GB   1.0      0.0     0.0      0.0       0.0      0.0      19.3   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
>   L3    272/0   16.86 GB   0.7      0.0     0.0      0.0       0.0      0.0      16.9   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
>  Sum    313/0   19.40 GB   0.0      0.0     0.0      0.0      19.4     19.4      55.6   1.0      0.0    332.0     59.83             30.19       313    0.191       0      0       0.0       0.0
> ```
> 
> For 2 threads
> 
> ```
> Cumulative writes: 20M writes, 20M keys, 19M commit groups, 1.0 writes per commit group, ingest: 38.74 GB, 226.97 MB/s
> ..
> Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>   L0      2/0   63.90 MB   0.5      0.0     0.0      0.0      19.9     19.9       0.0   1.0      0.0    296.3     68.77             34.84       635    0.108       0      0       0.0       0.0
>   L1      2/0   157.38 MB   0.6     21.9    17.5      4.5      21.6     17.1       2.4   1.2    307.4    302.0     73.08             65.44       139    0.526     11M   197K       0.0       0.0
>   L2     40/0    2.30 GB   0.9     11.0     8.9      2.0      10.9      8.8      10.4   1.2    328.0    325.9     34.20             31.45        71    0.482   5630K    36K       0.0       0.0
>   L3    304/0   16.92 GB   0.7      0.0     0.0      0.0       0.0      0.0      16.9   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
>  Sum    348/0   19.44 GB   0.0     32.9    26.4      6.5      52.3     45.8      29.7   2.6    191.3    304.4    176.05            131.74       845    0.208     16M   234K       0.0       0.0
> ```
> 
> For 4 threads
> 
> ```
> Cumulative writes: 40M writes, 40M keys, 20M commit groups, 2.0 writes per commit group, ingest: 77.26 GB, 309.11 MB/s
> ...
> Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
> ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>  L0      3/0   50.03 MB   0.8      0.0     0.0      0.0      20.6     20.6       0.0   1.0      0.0    248.6     84.94             42.53      1269    0.067       0      0       0.0       0.0
>  L1      2/1   257.24 MB   0.5     31.1    19.3     11.9      30.1     18.2       1.3   1.6    316.7    305.7    100.67             88.95       296    0.340     16M   554K       0.0       0.0
>  L2     49/1    2.41 GB   1.0     10.5     9.4      1.1      10.4      9.3       9.8   1.1    323.6    321.1     33.15             30.50        75    0.442   5383K    42K       0.0       0.0
>  L3    316/0   16.75 GB   0.7      0.0     0.0      0.0       0.0      0.0      16.7   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
> Sum    370/2   19.46 GB   0.0     41.6    28.7     12.9      61.1     48.2      27.9   3.0    194.8    285.8    218.76            161.98      1640    0.133     21M   596K       0.0       0.0
> ```

Thank you very much for your response！I will carefully consider your answer.

**Comment by jowlyzhang** [comment]
The number of key/value pairs to write, a.k.a `--num= 1000000` applies to each thread. So that the total operations for when thread is 1 is 1000000, but the total number of operations for when thread is 10 will be 10 * 1000000. I copied them together to make the comparison easier.

fillseq      :        74.287 micros/op 13461 ops/sec 74.287 seconds 1000000 operations;   39.4 MB/s
fillseq      :     211.399 micros/op 47176 ops/sec 211.970 seconds 10000000 operations;  138.2 MB/s

I think these numbers match the expectation. When multiple threads are writing concurrently, each operation takes longer, thus a bigger micros/op, if this is what you mean by "speed", it is indeed "slower", but I think that is still aligned with expectation. Having more threads writing improve the throughput, thus a higher ops/sec and higher MB/s. Throughput may be a better evaluation for speed though.

**Comment by jowlyzhang** [comment]
As for the number of files and the total file size, that is related to the logical size of the DB, not directly related to the speed. It's not surprising that these two benchmark commands can result in DBs with similar physical and logical size. For example, if all 10 threads write a key "a", only the last version been written is needed, the 9 versions been written before will be compacted away by the compaction process, making the DB having a similar physical size as where only one thread writes the key "a". The size of the DB depends on the pattern of the keys being written and how fast the compaction process cleans up obsolete entries.
