### ISSUE TITLE
Low priority write may cause crash when it is rate limited

### ISSUE THREAD

**Issue by caipengbo** [facebook/rocksdb#11902]
When low priority write is rate limited, `my_batch->GetDataSize()` may be **greater than** `GetSingleBurstBytes()`:

https://github.com/facebook/rocksdb/blob/fce04587b80db3d51d422ed8b1c52bd6291c9efc/db/db_impl/db_impl_write.cc#L1951-L1958

which might cause an assert failure?

https://github.com/facebook/rocksdb/blob/fce04587b80db3d51d422ed8b1c52bd6291c9efc/util/rate_limiter.cc#L110-L112

**Comment by jowlyzhang** [comment]
cc @hx235 to take a look at this.

**Comment by hx235** [comment]
Sorry for the late response. The following modified UT did repro the crash on upstream/main
```
@@ -3874,7 +3874,8 @@ TEST_F(DBTest2, LowPriWrite) {
   }
   ASSERT_EQ(0, rate_limit_count.load());
   wo.low_pri = true;
-  ASSERT_OK(Put("", "", wo));
+  std::string big_value = std::string(2 * 1024 * 1024, 'a');
+  ASSERT_OK(Put("", big_value, wo));
   ASSERT_EQ(1, rate_limit_count.load());
   wo.low_pri = false;
   ASSERT_OK(Put("", "", wo));
   
Note: Google Test filter = DBTest2.LowPriWrite
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DBTest2
[ RUN      ] DBTest2.LowPriWrite
db_test2: util/rate_limiter.cc:112: virtual void rocksdb::GenericRateLimiter::Request(int64_t, rocksdb::Env::IOPriority, rocksdb::Statistics*): Assertion `bytes <= refill_bytes_per_period_.load(std::memory_order_relaxed)' failed.
```

@caipengbo Would you be interested in coming up with a fix? `RequestToken()` would be helpful. See https://github.com/facebook/rocksdb/blob/63ed8688408b59dab86876928efa97f36dc0c3d1/file/writable_file_writer.cc#L562-L625 for an example. Thanks!

**Comment by caipengbo** [comment]
> Would you be interested in coming up with a fix? 
Ok, I'll try to fix it :)
