### ISSUE TITLE
Idea: Treat WAL file as blob file

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#11914]
If WAL file can be treated as blob file, memtab can save value handle(reference to WAL) instead of value content, this saves memory and ssd/disk bandwidth during memtab flush and later compactions.

More enhancements: this idea can be used as a prerequisite of #11835

**Comment by ltamasi** [comment]
This is very similar to what the "old" BlobDB (`rocksdb::blob_db::BlobDB`) is doing. See https://rocksdb.org/blog/2021/05/26/integrated-blob-db.html for the trade-offs of the two approaches.
