### ISSUE TITLE
Is there any document for building/integrating rocksdb for/into android/ios app ?

### ISSUE THREAD

**Issue by thenewvu** [facebook/rocksdb#1193]
I saw that rocksdb supports Android and iOS but I didn't find any document for building/integrating it for/into those platforms. So if I'm correct (that it indeed supports those platforms), could you guys give some time to write some document for it ? Such as:
- Common use cases for using Rocksdb on those platforms (when should use, when should not use, ...).
- How to build it for Android/iOS.
- Specific build options for those platforms.
- Good practices when wrapping/using it on those platforms.

Thank you.

**Comment by HannanShaik** [comment]
+1

**Comment by sagar0** [comment]
You should use RocksDBLite for mobile use cases. Check out [ROCKSDB_LITE.md](https://github.com/facebook/rocksdb/blob/master/ROCKSDB_LITE.md), and some build related information in [INSTALL.md](https://github.com/facebook/rocksdb/blob/master/INSTALL.md).

**Comment by benoitc** [comment]
i can see some instructions to build onios but none on android . Is this possible to build rocksdb lite for android ? Any example on how to do it if possible?

**Comment by benoitc** [comment]
bump

**Comment by MoNTE48** [comment]
+1

**Comment by kildo162** [comment]
+1

**Comment by sagar0** [comment]
May be someone in RocksDB community who has experience with iOS and/or Android can help by writing such instructions?

**Comment by sagar0** [comment]
Posted in the developers FB group: https://www.facebook.com/groups/rocksdb.dev/permalink/1703698279728679/ , to get community help.

**Comment by promethe42** [comment]
For Android, here is an extract of the `CMakeLists.txt` for my project which depends on RocksDB:

```
set(ROCKSDB_VERSION     "5.8")

if (ANDROID)
  set(ROCKSDB_LITE      ON)
  set(ROCKSDB_PORTABLE  ON)
  set(ANDROID_STL         "c++_shared")
  set(ARG_ANDROID_STL     "-DANDROID_STL=${ANDROID_STL}")
else()
  set(ROCKSDB_LITE      OFF)
  set(ROCKSDB_PORTABLE  OFF)
endif()
ExternalProject_Add(
  rocksdb
  URL               "https://github.com/facebook/rocksdb/archive/v${ROCKSDB_VERSION}.zip"
  PREFIX            "third_party/rocksdb"
  INSTALL_COMMAND   ""
  CMAKE_ARGS        "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
                    "-DWITH_TESTS=OFF"
                    "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
                    "${ARG_ANDROID_STL}"
                    "-DROCKSDB_LITE=${ROCKSDB_LITE}"
                    "-DPORTABLE=${ROCKSDB_PORTABLE}"
                    "-DWITH_TESTS=OFF"
                    "-DWITH_TOOLS=OFF"
)
```

Then I use a Docker container with the NDK and CMake. Here is the Dockerfile:

```
FROM lakoo/android-ndk:26-26.0.2-r16

# Intall make
RUN apt-get update && apt-get install make

# Install CMake
RUN cd / && \
    wget -q https://cmake.org/files/v3.9/cmake-3.9.6-Linux-x86_64.sh -O cmake.sh && \
    chmod +x ./cmake.sh && \
    ./cmake.sh --skip-license && \
    rm -rf cmake.sh

WORKDIR /data
```

Then build it in an image named `rocksdb-android`:

```bash
docker build . -t rocksdb-android
```

Finally, assuming you are in the directory where your project's `CMakeLists.txt` is, use Docker to build your project in a single command line:

```bash
docker run -it --rm \
    -v "$PWD":/data \
    -v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro \
    -u $(id -u $USER):$(id -g $USER) \
    rocksdb-android \
    bash -c "mkdir -p build && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/android-ndk-linux/build/cmake/android.toolchain.cmake && make -j$(nproc)"
```

**Comment by adamretter** [comment]
It seems that ROCKSDB_LITE support has been removed in commit 4720ba4391eb016b05a30d09a8275624c3a4a87e
(sdong <siying.d@fb.com> / Fri Jan 27 13:14:19 2023 -0800)
