### ISSUE TITLE
How to turn on compression for each level in rocksdb？

### ISSUE THREAD

**Issue by wanglinke521** [facebook/rocksdb#11931]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

When using rocksdb, how to use `compression_per_level` to enable compression at each level.

**Comment by ltamasi** [comment]
`compression_per_level` is just an `std::vector` of `CompressionType`s, so you can simply set its elements to whatever compression algo you'd like to use for each level. Note that `level_compaction_dynamic_level_bytes` (which is now the default) complicates things a bit: https://github.com/facebook/rocksdb/blob/main/include/rocksdb/advanced_options.h#L542-L571

Also, note that this is a legacy setting. For typical use cases, we recommend setting a space efficient compression method like `zstd` for the bottommost level (option `bottommost_compression`) and a fast compression algo like `lz4` for the rest of the levels; there's usually no need to set compression on a per-level granularity. See more info on the wiki: https://github.com/facebook/rocksdb/wiki/Compression
