### ISSUE TITLE
Please conduct Java/other platform testing for 8.7.fb

### ISSUE THREAD

**Issue by cbi42** [facebook/rocksdb#11966]
https://github.com/facebook/rocksdb/commits/8.7.fb is ready for Java/other platform testing, thanks!

**Comment by cbi42** [comment]
@adamretter I'm having trouble adding you as assignee so pinging here instead..

**Comment by adamretter** [comment]
> I'm having trouble adding you as assignee

@cbi42 Sorry about that, Danny Chen is trying to get my access restored...

I will start testing...

**Comment by adamretter** [comment]
@cbi42 Looks like he fixed it :-)

**Comment by adamretter** [comment]
@cbi42 The code won't build for RocksJava I am afraid as the links to the old libraries are no longer valid, it needs this PR merged in - https://github.com/facebook/rocksdb/pull/9304

**Comment by cbi42** [comment]
@adamretter Hi - is the test completed?

**Comment by cbi42** [comment]
kindly ping @adamretter

**Comment by adamretter** [comment]
@cbi42 Sorry for the delay, I had previously meant to reply to let you know that all tests pass now.

**Comment by cbi42** [comment]
Thanks, the 8.7 release is tagged now.
