### ISSUE TITLE
rocksdb doesn't sync to disk

### ISSUE THREAD

**Issue by sxb075** [facebook/rocksdb#1198]
We're using the ruby API set to store a large set of k,v pairs to databases.  Inadvertently, I get into a situation where the k,v pairs can't be retrieved using the get API.  However, running an iterator on the database can see the values.  Iterating over the values, and invoking a put doesn't address this either.  Is there a flush API in ruby that can help address this?  Or is there some parameter that can be set, that can address this issue?  The default settings for SST, logs, bufs, etc. are being used.

**Comment by igorcanadi** [comment]
This is extremely weird and the first bug report of this kind I've ever seen (especially if you're using the default settings). Are your bloom filters also turned off? Can you send us your LOG files (you can find them in the same directory as other RocksDB files)?

BTW The title doesn't seem related to the issue.

**Comment by sxb075** [comment]
here's the LOG file that has been attached.  every entry can be viewed using the iterator, but a get on any of these entries returns a null.

[LOG.txt](https://github.com/facebook/rocksdb/files/351997/LOG.txt)

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
