### ISSUE TITLE
Memory leak after manual compactions

### ISSUE THREAD

**Issue by areyohrahul** [facebook/rocksdb#11980]
RocksDB 8.5.4 (RocksDBJni)

Hi, I'm using RocksDB for a read-heavy workload. After several tests, I found out that the reads work best if the DB is in the best state (compacted). So, I'm running manual compaction by running db.compactRange(CF) every 60 mins.

I also keep monitoring my system's memory usage by "sar -r 1" command. And, it clearly shows an increase in memory after every compaction which is never reclaimed.

Is this a known issue? or am I doing something wrong here?

Please let me know if more details are required.

**Comment by areyohrahul** [comment]
So, although running compactions manually does increase the memory by a small % I also tried turning the manual ones off completely and found out that the memory was still increasing at an almost constant rate. 

In my app, I'm only doing read-modify-write type of operations. Earlier, I was not closing the WriteBatch object which was leading to a memory leak every time I was writing something. Not sure what is it this time.

During the reads, I only use the ColumnFamilyHandle object (which inherited RocksObject that can caused the problem during writes earlier) which is only defined once and is reused multiple times. One important thing to note here is that I'm using multi-get operations. So, with all the keys, I also have to pass on their respective ColumnFamilyHandles to the method call. In my case, it's the same handle so before the call, I just make 'n' copies of the ColumnFamilyHandle object.

I'm guessing that it should not be the problem. 

I;m not using iterators. My filter and index blocks are cached in the block cache. My memtable size is 100 MB * 6. 

Any suggestions please?

**Comment by popduke** [comment]
Observed similar "RES leak" in 7.10.2 after run several hours under moderate get/iterate/write workload, and manual compaction triggered periodically, but the JVM heap is quite stable.

**Comment by areyohrahul** [comment]
Hey @popduke, were you able to solve it?

**Comment by popduke** [comment]
@areyohrahul, not yet, I'm still investigating. In my use case, in addition to manual compaction, I also create a checkpoint at a regular interval (e.g., once every 5 minutes). This checkpoint is opened in read-only mode, and it's closed shortly after reading some KV (metadata in my app). I'm confident that there is no native handle leak during this process on the Java side. However, I'm still observing a gradual increase in RSS. Here's my heap profile from jemalloc/jeprof. It appears that the memory is being occupied by the DBImplReadOnly related code path, which corresponds to the checkpoint activity in my program. I'm uncertain if this is the actual source of the leak. 
BTW. I configured jemalloc with the settings *"background_thread:true, dirty_decay_ms:0, muzzy_decay_ms:0"* to ensure that unused memory is returned to the OS as soon as the test workload stops..
[heapprofile.pdf](https://github.com/facebook/rocksdb/files/13212596/heapprofile.pdf)

**Comment by areyohrahul** [comment]
Let me know if you find anything though
