### ISSUE TITLE
RocksDB 5.18.4 Not Forward Compatible with RocksDB 6.29.4.1

### ISSUE THREAD

**Issue by Hussain-Badshah** [facebook/rocksdb#11989]
Scenario: We upgraded Kafka-streams version from 2.8.0 to 3.2.3 in our streaming applications and post deployment with this upgrade, application came up and started working as expected but when it was rolled back to a version containing kafka-streams 2.8.0 operations on RocksDB DB failed with following error: 

**Error while executing put key <some_key> and <some_value> from org.rocksdb.RocksDBException: Unknown Footer version. Maybe this file was created with newer version of RocksDB? at org.rocksdb.RocksDB.put(Native Method) at org.rocksdb.RocksDB.put(RocksDB.java:542)** 

Clearly it says that there's some issue regarding the forward compatibility. Kafka-streams API v2.8.0 has 5.18.4 version of RocksDB and kafka-streams v3.2.3 contains 6.29.4.1 version of RocksDB. Is the former one not compatible with the latter one? The answer to this question would be really really helpful. 

And if yes, then does anything need to be done in the kafka-streams application to make it compatible?

### Expected behavior
Application should have worked even after rolling back to older kafka-streams OR RocksDB version.

### Actual behavior
Application broke while persisting data into the state store by an older RocksDB version, once the state store was accessed by a newer version of RocksDB previously. 

### Steps to reproduce the behavior
1. Deploy an application with 3.2.3 kafka-streams which contains 6.29.4.1 RocksDB, with a use-case to put data into the state store. 
2. Roll the application back to a version containing kafka streams 2.8.0 which contains 5.18.4 RocksDB and execute the same use-case to put data into the state store and verify the behavior.

**Comment by OneCricketeer** [comment]
Did you follow the upgrade guide? https://kafka.apache.org/36/documentation/streams/upgrade-guide 

> Since 3.0.0 release, Kafka Streams uses a newer RocksDB version whose on-disk format changed. This means that old versioned RocksDB would not be able to recognize the bytes written by that newer versioned RocksDB

**Comment by Hussain-Badshah** [comment]
Okay, thanks @OneCricketeer :)
