### ISSUE TITLE
add rust to third party language bindings

### ISSUE THREAD

**Issue by spacejam** [facebook/rocksdb#1204]
https://github.com/facebook/rocksdb/wiki/Third-party-language-bindings
rust: https://github.com/spacejam/rust-rocksdb

**Comment by igorcanadi** [comment]
Done. Thanks @spacejam for building this!

**Comment by siying** [comment]
@spacejam do you mind sending a pull request to add it to LANGUAGE-BINDINGS.md file too?

**Comment by veeve** [comment]
this is great! thanks @spacejam!

**Comment by igorcanadi** [comment]
https://github.com/facebook/rocksdb/commit/c6a8665b37594bde380fd16695cb2b9ce6376f2d
