### ISSUE TITLE
fatal error: 'lz4.h' file not found

### ISSUE THREAD

**Issue by heyingquan0030** [facebook/rocksdb#12049]
I am getting the following error while compiling MariaDB source code:

```
server/storage/rocksdb/rocksdb/util/compression.h:43:10: fatal error: 'lz4.h' file not found
#include <lz4.h>
         ^~~~~~~
1 error generated.
make[2]: *** [storage/rocksdb/CMakeFiles/rocksdblib.dir/rocksdb/db/arena_wrapped_db_iter.cc.o] Error 1
make[1]: *** [storage/rocksdb/CMakeFiles/rocksdblib.dir/all] Error 2
make: *** [all] Error 2
```
But I've installed the lz4 library locally.

My local environment is as follows:
```
operating system: macOS
rocksdb branch: main
mariaDB branch: 11.1
lz4: 1.9.4
```

I'm a beginner in both CMake and C++. Can you give me some advice? Appreciate it.

**Comment by mdcallag** [comment]
I have plenty of experience compiling MyRocks from source using the FB fork of upstream MySQL. I have no experience doing that for MariaDB. I don't have to do anything special, but my builds are on Ubuntu and I installed compression libraries via "apt".

The [MariaDB page](https://mariadb.com/kb/en/building-myrocks-in-mariadb/) on compiling MyRocks from source didn't do anything special with flags, but it also assumes you did the normal system install via apt on Ubuntu or the RedHat/CentOS equivalent.

**Comment by heyingquan0030** [comment]
@mdcallag Thanks for the suggestion, I upgraded the platform and it works!
