### ISSUE TITLE
Potential license issue while using RocksDB through Apache-2.0 license

### ISSUE THREAD

**Issue by lombarde** [facebook/rocksdb#12079]
I would like to use RocksDB through Apache-2.0 license, but while going through the code I noticed that the files coming from PerconaFT bring some files without clear license.

Most files added through this [PR](https://github.com/facebook/rocksdb/pull/7753) are stating the three licenses PerconaFT is licensed with, but there are a few exceptions, e.g.:

- `utilities/transactions/lock/range/range_tree/lib/util/dbt.cc` has GPLv2 and AGPLv3 licenses (also PerconaFT current code for the same file has GPLv2 and AGPLv2 licenses only)
- `utilities/transactions/lock/range/range_tree/lib/db.h` has no license stated (probably not coming from PerconaFT directly)

PerconaFT 'locktree' and 'omt' are available under the Apache-2.0 license, and RocksDB uses only 'locktree', so from the high level Apache-2.0 should be fine, only those files I mentioned pose a potential issue, `dbc.cc` in particular.

Can someone help to clarify?

**Comment by ajkr** [comment]
#12083 will fix the missing licenses. We can continue tracking "dbt.cc"'s license inconsistency using #10478.
