### ISSUE TITLE
db_bench for multi columns already built database

### ISSUE THREAD

**Issue by fyulingi** [facebook/rocksdb#12099]
I want to test the random read performance for one rocksdb instance already build. I run the command `./db_bench --db=[my_own_db_path] --options_file=[my_own_db_option_file_path] --use_existing_db=1 --threads=1 --benchmarks=readrandom  > read_log_ours.txt 2>&1 &`. However, the instance has many columns, while the command raised an error: `open error: Invalid argument: Column families not opened: ....`.

**Comment by ajkr** [comment]
Benchmarking databases built externally from `db_bench` is not fully supported. `use_existing_keys=1` should make it work on a single CF database. But we still need to add a feature like `use_existing_cfs` if we want to support your use case.
