### ISSUE TITLE
in centos7 make static_lib fail  gcc (GCC) 8.3.1 

### ISSUE THREAD

**Issue by ygf85611** [facebook/rocksdb#12107]
### Expected behavior
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
mkdir build && cd build
cmake -DROCKSDB_BUILD_SHARED=0 ..
make static_lib

### Actual behavior
make static_lib
$DEBUG_LEVEL is 0, $LIB_MODE is static
: No such file or directory
Makefile:243: make_config.mk: No such file or directory
grep: /opt/ezone/rocksdb_version/rocksdb/make_config.mk: No such file or directory
make: *** No rule to make target `make_config.mk'.  Stop.

**Comment by rhubner** [comment]
Hello @ygf85611 

If you are using cmake to build RocksDB  there isn't any target named `static_lib`. By default cmake builds a static library under target `rocksdb`. So in your case with cmake parameter `-DROCKSDB_BUILD_SHARED=0` , `make rocksdb` should be enough to get a static build, or just simple `make `will do the job. You can also add parameter  `-j <number of cpu cores>` to build RocksDB faster.

Radek

**Comment by raffertyyu** [comment]
Rocksdb support both `make` and `cmake` build system. use
```
cd rocksdb
make static_lib -j$(nproc)
```
or
```
cd rocksdb
mkdir build && cd build
cmake -DROCKSDB_BUILD_SHARED=off ..
make -j$(nproc)
```
