### ISSUE TITLE
Is there a plan to launch the wide column functionality of the java api

### ISSUE THREAD

**Issue by test-wangxiaoyu** [facebook/rocksdb#12113]
The latest version of rocksdb's java api does not yet have a wide column api. Does the community have plans to add this feature to the java api? If so, which version will be released

**Comment by ltamasi** [comment]
#11982 is actually the initial patch for supporting wide columns in `WriteBatchWithIndex`. Wide columns themselves have been around since RocksDB 7.9 (https://github.com/facebook/rocksdb/blob/main/HISTORY.md#new-features-10) and the existing APIs are stable; we will be adding more features though.

**Comment by adamretter** [comment]
@test-wangxiaoyu Okay cool. Let's leave this open as a Feature Request for the Java API. I have had @cmccrorie add it to our backlog here

**Comment by adamretter** [comment]
@test-wangxiaoyu (CC @cmccrorie) our plan is to work on this in February 2024.

**Comment by test-wangxiaoyu** [comment]
> 你好 RocksDB 社区，
> 
> 我们正在研究这个问题，在 API 设计过程中我们提出了一个重要问题：
> 
> _**行通常有多宽？**_
> 
> 我知道宽列数据库（Cassandra、ScyllaDB、HBase，...）在一行中可以有相当多的名称-值对（1M）。检查 C++ API，我可以看到它的`WideColumns`定义是这样的`std::vector<WideColumn>`，所以我假设在 RocksDB 中，所有内容都应该适合内存，并且可能不会太大。
> 
> 玛耶@pdillinger 或者@ajkr有一些想法。
> 
> 抄送：@adamretter

In fact, we can consider this, let the user to decide the number of fields contained in the wide column, the user can choose to set an appropriate number of fields in the wide column according to the specific business scenario needs

**Comment by test-wangxiaoyu** [comment]
> RocksDB社区你好，
> 
> 我们正在研究这个问题，在API设计过程中我们提出了一个重要问题：
> 
> _**行通常多宽？**_
> 
> 我知道宽列数据库（Cassandra、ScyllaDB、HBase，...）在一行中可以有相当多的名称值对（1M）。检查C++ API，我看到它的`WideColumns`定义可以是这样的`std::vector<WideColumn>`，所以我假设在 RocksDB 中，所有内容都应该适合内存，并且可能不太麻烦。
> 
> 玛耶@pdillinger 或者@ajkr有一些想法。
> 
> 抄送：@adamretter

<img width="1124" alt="image" src="https://github.com/facebook/rocksdb/assets/90183930/2d20f3fd-554f-42df-b2fa-94dcc4eb6e35">
Here I take the data storage tool I am writing as an example, my storage tool is with the concept of column family and field, rocksdb provides column family function, and the number of fields contained in each column family, I want users to set their own according to their data situation
