### ISSUE TITLE
RocksDB java RocksDB#loadLibrary(List<String> paths) can't be called correctly

### ISSUE THREAD

**Issue by cavallium** [facebook/rocksdb#12132]
### Expected behavior
There are two methods to load RocksDB library:
- ```RocksDB#loadLibrary()```
- ```RocksDB#loadLibrary(final List<String> paths)```

Calling the second one, I expect to load RocksDB from an alternative path, not the default one.

### Actual behavior
Calling ```RocksDB#loadLibrary(final List<String> paths)``` triggers the ```static {}``` block in RocksDB.java, that calls ```RocksDB#loadLibrary()``` automatically, preventing the use of ```RocksDB#loadLibrary(final List<String> paths)```

### Steps to reproduce the behavior
1. Put a breakpoint in both RocksDB#loadLibrary methods
2. Call ```RocksDB.loadLibrary(List.of("your-custom-rocksdb-path"));```
3. The ```RocksDB#loadLibrary()``` method will be called before ```RocksDB#loadLibrary(final List<String> paths)```

**Comment by cavallium** [comment]
> This should be already fixed in 8.8; see #11277 and the fix in #11919 .

Thanks for the clarification.

By the way I'm using 8.8.1 (the last published release on maven central), the static code is still present.

**Comment by ltamasi** [comment]
So we still have a `static` block in the latest code on mainline (other than tests/samples which should be fine)? Could you please point me to it?

**Comment by adamretter** [comment]
Let me take a look...

**Comment by cavallium** [comment]
> So we still have a `static` block in the latest code on mainline (other than tests/samples, which should be fine)? Could you please point me to it?

I'm not talking about the mainline code on GitHub, I'm talking about the released version on maven central (8.8.1):

https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/8.8.1/rocksdbjni-8.8.1-sources.jar

RocksDB.java, line 36

**Comment by rhubner** [comment]
Hello @cavallium,
you are right. I don't know why, but by some accident this code wasn't removed. Let me fix it.

Radek

**Comment by adamretter** [comment]
Apologies for that creeping back in, Radek has now prepared a fix for that here - https://github.com/facebook/rocksdb/pull/12133

**Comment by cavallium** [comment]
The static initializer block is still present in the current release, v8.9.1: is the fix scheduled for the next release or it's a regression?

**Comment by adamretter** [comment]
@cavallium I expect it to be scheduled for the next release.
