### ISSUE TITLE
About 32 bit architecture support ?

### ISSUE THREAD

**Issue by Athi2019rit** [facebook/rocksdb#12146]
Hi Guys, Recently I've tried to build rocksdb under 32 bit architecture using cmake version 3.28.0. I'm getting error when tried to build the visual studio code solution for rocksdb. 

RocksDB Version used : v4.11.2
Cmake version : 3.28.0
Build Type: Debug
Architecture: Win32

I'm using rocksdb version 4.11.2 for c++ 11 support. 

Cmake command used : cmake -G "Visual Studio 12 2013" -A Win32 -DCMAKE_BUILD_TYPE=Debug ..

Warnings:
Warning	C4244 'argument' : conversion from 'const uint64_t' to 'size_t', possible loss of data rocksdblib e:\rocksdb_test\rocksdb\utilities\spatialdb\spatial_db.cc

Error:
Error C2220 warning treated as error - no 'object' file generated	rocksdblib	e:\rocksdb_test\rocksdb\utilities\document\json_document.cc

Is rocksdb supports 32 bit architecture ? is there any way to build rocksdb under 32 bit architecture which has c++11 support in windows.

**Comment by jsteemann** [comment]
Note that when compiling RocksDB, any compile warnings are turned into compile errors by default.
There is a RocksDB CMake option `FAIL_ON_WARNINGS` to turn off this behavior. 
So you could try cmaking with the option `-DFAIL_ON_WARNINGS=Off` and check if compilation then gets any further. 

> Is rocksdb supports 32 bit architecture ? is there any way to build rocksdb under 32 bit architecture which has c++11 support in windows.

Please note this line in the CMakeLists.txt file: https://github.com/facebook/rocksdb/blob/main/CMakeLists.txt#L2

I also think that the minimum C++ language version for compiling RocksDB has moved to C++17 (see https://github.com/facebook/rocksdb/blob/main/CMakeLists.txt#L85). Which obviously is supported by newer versions of MSVC, but I can't tell what compiler & environment you are targeting.

**Comment by adamretter** [comment]
There is a best effort approach to supporting RocksDB 32bit on Linux, and OpenBSD. As far as I know we do not officially support RocksDB on Windows 32bit Windows. That could possibly change if someone wanted to contribute and maintain that code, but you might want to check with one of the official Meta RocksDB team members

**Comment by Athi2019rit** [comment]
> 
> I also think that the minimum C++ language version for compiling RocksDB has moved to C++17 (see https://github.com/facebook/rocksdb/blob/main/CMakeLists.txt#L85). Which obviously is supported by newer versions of MSVC, but I can't tell what compiler & environment you are targeting.


I'm targetting to build rocksdb tag 4.11.2 which gives c++11 support. Cmake compiled with no problem after warnings are set to off , but when build the msvc build for rocksdb.sln it doesn't compiles in vs community edition 2013 but compiles under platform vs 2019 edition

**Comment by Athi2019rit** [comment]
> There is a best effort approach to supporting RocksDB 32bit on Linux, and OpenBSD. As far as I know we do not officially support RocksDB on Windows 32bit Windows. That could possibly change if someone wanted to contribute and maintain that code, but you might want to check with one of the official Meta RocksDB team members

Thanks

**Comment by adamretter** [comment]
> build the msvc build for rocksdb.sln it doesn't compiles in vs community edition 2013 but compiles under platform vs 2019 edition

It used to be possible with older versions to build them with Visual Studio 2015.

> Is there support available for linux 32 bit or it will be supported in future ?

It should just work. There is code and binaries - https://github.com/facebook/rocksdb/blob/main/Makefile#L2329

**Comment by Athi2019rit** [comment]
> > build the msvc build for rocksdb.sln it doesn't compiles in vs community edition 2013 but compiles under platform vs 2019 edition
> 
> It used to be possible with older versions to build them with Visual Studio 2015.
> 
> > Is there support available for linux 32 bit or it will be supported in future ?
> 
> It should just work. There is code and binaries - https://github.com/facebook/rocksdb/blob/main/Makefile#L2329

Thanks 

>
