### ISSUE TITLE
execute_process(COMMAND mkdir ${DIR}) fails to create a directory with cmake on Windows

### ISSUE THREAD

**Issue by clumsy** [facebook/rocksdb#1215]
This is the case for `rockdb/java` JNI cmake project
I suggest using `file(MAKE_DIRECTORY ${DIR})`

**Comment by adamretter** [comment]
Fixed by: https://github.com/facebook/rocksdb/pull/1219

**Comment by adamretter** [comment]
Closed by https://github.com/facebook/rocksdb/pull/1219
