### ISSUE TITLE
periodic compaction seconds not working as expected

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12165]
My understanding is that with periodic compaction seconds, we can schedule files to be compacted. And when compaction runs, tombstones are removed to keep db size small among other things.

My db size is small (around 5gb) so leaving all the defaults in place for rocksdb will mean I will accumulate a lot of tombstones so before trying to use periodic compactions seconds (because it wasn't exposed via c api so I couldn't use it), I used less optimal settings to force compaction:

  opts.set_max_bytes_for_level_base(25 * 1024 * 1024);
   opts.set_target_file_size_base(32 * 1024 * 1024);

which was fine but it's not ideal. After periodic compaction seconds was exposed via c api, I removed the two settings above and set periodic compaction seconds to run every 3 hours (i delete data on a cron every 4 hours).

As we can see, periodic compaction seconds doesn't seem to force compaction? or at least doesn't delete tombstones like I expected:

<img width="1513" alt="Screenshot 2023-12-19 at 11 34 18 AM" src="https://github.com/facebook/rocksdb/assets/43054535/88a08370-a4f7-45d4-92fa-0fcfedd5d6f5">

Here is the LOG file as well in case it helps:
[LOG.txt](https://github.com/facebook/rocksdb/files/13720550/LOG.txt)

Any idea why periodic compaction seconds is not working? Or at least is not doing the same thing as setting the "bad" options

**Comment by cbi42** [comment]
`periodic_compaction_seconds` compacts file to the same level. If a file with tombstones is not in the bottommost level, it may not be helpful. You may want to set `ttl` too which compacts old files down. 

You may want to consider using delete triggered compaction if the goal is to remove files with many tombstones: https://github.com/facebook/rocksdb/blob/7b24dec25d6df81ef3f3a33f12968c5476692acd/include/rocksdb/utilities/table_properties_collectors.h#L18

> i delete data on a cron every 4 hours

Another thing to consider to is do manual compaction after you issue deletions.

**Comment by zaidoon1** [comment]
oh so I did misunderstand what this feature does, what does `compacts file to the same level` achieve? 

also I did read in the docs about setting `ttl ` to compact old files down but I'm not sure what exact feature that is. Can you link me to the code for the compaction ttl? (specifically, I rely on the C api since i'm using rust rocksdb so hopefully that's exposed)

> delete triggered compaction i

regarding this, I initially considered it but after asking around in the community, it seems this feature is best suited for when deletion is concentrated in a specific range where as my deletes are all over the place. Is this accurate?

> Another thing to consider to is do manual compaction after you issue deletions.

This definitely sounds like a great idea and I'll likely go with this approach and combine it with the ttl based compaction

**Comment by cbi42** [comment]
> what does compacts file to the same level achieve

It lets files go through compaction filter periodically. The option has a different meaning for [universal compaction](https://github.com/facebook/rocksdb/blob/7b24dec25d6df81ef3f3a33f12968c5476692acd/include/rocksdb/advanced_options.h#L879-L892).

> Can you link me to the code for the compaction ttl? 

I don't see it in C API. Feel free to submit a PR to add it.

> delete triggered compaction

You can specify a file to be compacted if it has more than a D tombstones in a window of X entries, or that the ratio of tombstones exceed some value. 

> I'm guessing I need to set CompactRangeOptions::bottommost_level_compaction to BottommostLevelCompaction::KforceOptimized

Yeah, setting it to kForceOptimized should be enough.

**Comment by ajkr** [comment]
I wonder if we could get away with the following behavior change: in leveled compaction, also trigger compaction to the next level for upper-level files whose data age exceeds `periodic_compaction_seconds`. (Is `ttl < periodic_compaction_seconds` in leveled compaction a common/useful setting today?)

**Comment by git-hulk** [comment]
> I wonder if we could get away with the following behavior change: in leveled compaction, also trigger compaction to the next level for upper-level files whose data age exceeds periodic_compaction_seconds.

As a user, I believe it would be better if we could trigger compaction to the next level. I can submit a PR to resolve this if it sounds good to maintainers.

**Comment by zaidoon1** [comment]
I also agree that it would be great to trigger compaction to the next level.

**Comment by zaidoon1** [comment]
I've created a pr to expose options ttl as well https://github.com/facebook/rocksdb/pull/12170

**Comment by git-hulk** [comment]
> Is periodic_compaction_seconds < ttl in leveled compaction a common/useful setting today?

I see, seems `periodic_compaction_seconds` will perform the same way with TTL in level compaction if allowed to trigger next-level compaction.

**Comment by zaidoon1** [comment]
right, based on my understanding, I completely misunderstood how periodic_compaction_seconds, what I was looking for is the TTL option

**Comment by cbi42** [comment]
> Is periodic_compaction_seconds < ttl in leveled compaction a common/useful setting today?

Probably not, this can also prevent `ttl` compaction from happening. 

> trigger compaction to the next level for upper-level files whose data age exceeds periodic_compaction_seconds

I'm fine with this change. It should not affect users who configure ttl <= periodic_compaction_seconds. The change may not make sense when `level_compaction_dynamic_level_bytes=false`, but neither does `ttl`.

**Comment by ajkr** [comment]
> As a user, I believe it would be better if we could trigger compaction to the next level. I can submit a PR to resolve this if it sounds good to maintainers.

It sounds good to me

**Comment by zaidoon1** [comment]
so while I wait for the change to expose ttl via c api to land. I'm doing manual compaction and in the LOG, I can see it triggering:

[LOG.txt](https://github.com/facebook/rocksdb/files/13747450/LOG.txt)

<img width="1712" alt="Screenshot 2023-12-21 at 8 56 22 PM" src="https://github.com/facebook/rocksdb/assets/43054535/785affce-e4b6-4241-bb7e-99b997a886e0">


However, I'm noticing the number of tombstones doesn't reach/approach 0. Is this expected? Note that while running manual compaction, I didn't enable bottommost_level_compaction since after chatting with some folks, I was told " unless you use snapshots there can not be delete on the bottommost level.". Is this statement accurate? Maybe I should be enabling bottmost level compaction to actually get the results I'm expecting?


Also, after removing the "bad settings" I'm noticing the following in the logs:

"More existing levels in DB than needed: all non-zero levels <= level 5 are unnecessary.  max_bytes_for_level_multiplier may not be guaranteed."

Should I set CompactRangeOptions::target_level ?,  the docs say:  If target_level is -1, the compacted files will be moved to the minimum level whose computed max_bytes is still large enough to hold the files. I'm assuming this will address this problem?

**Comment by git-hulk** [comment]
> I'm fine with this change. It should not affect users who configure ttl <= periodic_compaction_seconds. The change may not make sense when level_compaction_dynamic_level_bytes=false, but neither does ttl.

Sure, thank you!

**Comment by kishorenc** [comment]
I just stumbled on this exact same gotcha. Perhaps the documentation / comments around `periodic_compaction_seconds` could have been clearer in this regard. Like others on this thread, I fully expected compaction to trigger to the next level and that would be a welcome change.

**Comment by cbi42** [comment]
`periodic_compaction_seconds` was working as expected and improvement is made in #12175.
