### ISSUE TITLE
[Question] `WriteBatch` potentially spanning multiple memtables

### ISSUE THREAD

**Issue by mohitreddy1996** [facebook/rocksdb#12162]
Question: How does Memtable flush work when a `WriteBatch` could potentially span across multiple memtables? Are these affected memtables flushed together? Or only the memtable which is sealed (for different reasons like reached buffer size etc) are flushed while others are still in memory?

We are exploring if we could disable WAL. We have recovery implemented at the application layer. But if a `WriteBatch` spanning across multiple Memtables are not flushed together, there could be a failure scenario in which we have flushed partial data, losing the rest.

P.S: Apologies for posting a question as an issue, I had posted the same question on [FB but haven't received any replies](https://www.facebook.com/groups/rocksdb.dev/permalink/7026174880814299/?mibextid=oMANbw). Would really appreciate it if this could be answered.

**Comment by cbi42** [comment]
> Or only the memtable which is sealed (for different reasons like reached buffer size etc) are flushed while others are still in memory?

This is the default behavior. For your use case, you may want to look at [atomic flush](https://github.com/facebook/rocksdb/wiki/Atomic-flush).
