### ISSUE TITLE
manual compaction not working as expected

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12178]
I'm doing a manual compaction periodically (compact cf range, start and end are both NULL to compact the entire cf) and in the LOG, I can see it triggering:

[LOG.txt](https://github.com/facebook/rocksdb/files/13747450/LOG.txt)

However, I'm noticing the number of tombstones doesn't reach/approach 0. Is this expected? Note that while running manual compaction, I didn't enable bottommost_level_compaction since after chatting with some folks, I was told " unless you use snapshots there can not be delete on the bottommost level.". Is this statement accurate? Maybe I should be enabling bottmost level compaction to actually get the results I'm expecting?

<img width="1719" alt="Screenshot 2023-12-23 at 8 39 18 AM" src="https://github.com/facebook/rocksdb/assets/43054535/0fdb50f9-7952-447f-8370-005dcf4f84a3">

Notice for example, for url cf, level 5 and 0 are not 0 even though I ran compaction. 

Also I had bad settings,  that i removed and reverted to the default, after removing the "bad settings" I'm noticing the following in the logs:

"More existing levels in DB than needed: all non-zero levels <= level 5 are unnecessary. max_bytes_for_level_multiplier may not be guaranteed."

I assumed compaction would also take care of this to remove unnecessary levels, but that doesn't appear to be happening, 

Should I set CompactRangeOptions::target_level ?, the docs say: If target_level is -1, the compacted files will be moved to the minimum level whose computed max_bytes is still large enough to hold the files. But I don't know if that will solve this problem. Also given that it's not by default set to -1, what is the implications of setting it to -1 and doing this periodically?

**Comment by ajkr** [comment]
I think the usage is correct. How did you determine there are remaining tombstones? From the log ("url" CF):

```
2023/12/22-01:25:07.803634 4055307 EVENT_LOG_v1 {"time_micros": 1703208307803615, "cf_name": "url", "job": 11, "event": "table_file_creation", "file_number": 641, "file_size": 40692394, "file_checksum": "", "file_checksum_func_name": "Unknown", "smallest_seqno": 0, "largest_seqno": 0, "table_properties": {"data_size": 40471063, "index_size": 1660575, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 1, "index_value_is_delta_encoded": 1, "filter_size": 565, "raw_key_size": 117296256, "raw_average_key_size": 175, "raw_value_size": 0, "raw_average_value_size": 0, "num_data_blocks": 17143, "num_entries": 669158, "num_filter_entries": 519, "num_deletions": 0, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "ribbonfilter", "column_family_name": "url", "column_family_id": 1, "comparator": "leveldb.BytewiseComparator", "user_defined_timestamps_persisted": 1, "merge_operator": "nullptr", "prefix_extractor_name": "zone_id_host_extractor", "property_collectors": "[]", "compression": "ZSTD", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=1; max_dict_buffer_bytes=0; use_zstd_dict_trainer=1; ", "creation_time": 1701452426, "oldest_key_time": 0, "file_creation_time": 1703208306, "slow_compression_estimated_data_size": 0, "fast_compression_estimated_data_size": 0, "db_id": "399d2952-76b6-4f3e-ac01-0bbfe47f0bd8", "db_session_id": "SVATYB3P8UE2Y7B8OPMC", "orig_file_number": 641, "seqno_to_time_mapping": "N/A"}}
2023/12/22-01:25:07.805046 4055307 (Original Log Time 2023/12/22-01:25:07.804610) [db/compaction/compaction_job.cc:1729] [url] [JOB 11] Compacted 1@0 + 1@6 files to L6 => 40692394 bytes
2023/12/22-01:25:07.805049 4055307 (Original Log Time 2023/12/22-01:25:07.805001) [db/compaction/compaction_job.cc:908] [url] compacted to: base level 6 level multiplier 10.00 max bytes base 268435456 files[0 0 0 0 0 0 1] max score 0.00, MB/sec: 29.2 rd, 29.0 wr, level 6, files in(1, 1) out(1 +0 blob) MB in(0.5, 38.6 +0.0 blob) out(38.8 +0.0 blob), read-write-amplify(147.6) write-amplify(73.5) OK, records in: 687702, records dropped: 18544 output_compression: ZSTD
```

Some analysis:
- `"num_deletions": 0`: an L6 file is created with zero tombstones
- `files[0 0 0 0 0 0 1]`: when this compaction finished, the CF contains only that L6 file

There could be tombstones in the memtable, but those would have had to be added after the manual compaction started because manual compaction flushes the memtable as its first step.

**Comment by zaidoon1** [comment]
so I'm basing all my findings on the metric. It shows level 0 has some tombstones, and level 5 has some tombstones, and level 6 has 0 tombstones.

A few things:

1. Based on my understanding, level 0 should never have tombstones unless I'm using snapshots (which I am not) but I'm seeing tombstones. Should I enable bottommost compaction in this case? What is the consequence of doing that (it's not enabled by default)
2. The metric which shows the tombstones per level is populated by getting the live files and summing rocksdb_livefiles_deletions per level (https://github.com/rust-rocksdb/rust-rocksdb/blob/66f04df013b6e6bd42b5a8c353406e09a7c7da2a/src/db.rs#L2097-L2106). Is this maybe pulling stale/invalid data?

**Comment by zaidoon1** [comment]
Ok, my apologies, the issue is that the metric I have setup is reporting old values and I'm not resetting the metric after some files are deleted, etc.. which makes things very confusing.
