### ISSUE TITLE
How can I evaluate the range query performance using db_bench?

### ISSUE THREAD

**Issue by lim-yoona** [facebook/rocksdb#12195]
I read the official documents, but don't find performance test about range query.

**Comment by ajkr** [comment]
In `db_bench` the benchmark is called "seekrandom". There are different options for specifying what kind of scan is done after each `Seek()`. The most basic one is `-seek_nexts` to call `Next()` the specified number of times

**Comment by lim-yoona** [comment]
> In `db_bench` the benchmark is called "seekrandom". There are different options for specifying what kind of scan is done after each `Seek()`. The most basic one is `-seek_nexts` to call `Next()` the specified number of times

Thank you, I got it!!!
