### ISSUE TITLE
How Are the Tiered Storage and Adaptive Compaction Projects Going?

### ISSUE THREAD

**Issue by Hexancer** [facebook/rocksdb#12209]
Hey RocksDB Community,

Hope you're all doing well! Just wondering, how are things shaping up with the Tiered Storage and Adaptive Compaction projects? I've seen some initial steps at https://github.com/facebook/rocksdb/blob/6.24.fb/include/rocksdb/advanced_options.h#L778-L783 , and I'm curious to know about the current development status.

Would love to get some insights:

What's the latest update on the Tiered Storage and Adaptive Compaction projects?
Any exciting roadmap or milestones in the works?
How can us eager contributors jump in and be part of the action?
Appreciate any info you can share. Thanks a bunch for your hard work on RocksDB!

Best

**Comment by ajkr** [comment]
You can read more about tiered storage here: https://rocksdb.org/blog/2022/11/09/time-aware-tiered-storage.html.

For adaptive compaction it depends what you mean. If you mean making leveled and universal work well automatically in more scenarios, then yes, that is gradually happening. If you mean a hybrid or unified strategy, then no, that is not something we are actively working on.

For getting involved, our usual suggestion applies, which is to search for issues with the "up-for-grabs" label. There might not be any in your area of interest, but we will keep it in mind and possibly think of some.
