### ISSUE TITLE
Feature Request: rate limit compaction but not flushes

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12220]
My db size is small (around 5gb). In order to not accumulate a lot of tombstones and use up more disk space unnecessarily, I'm currently running compaction every 30 min which completes very quickly. The issue is that I see a huge cpu spike every time compactions runs (which is expected since compaction is heavy), however, what I would like to do is slow down compaction a bit so that the impact on cpu is minimal. There is a rate limiter https://github.com/facebook/rocksdb/wiki/Rate-Limiter but as far as I understand, this will impact flushes as well which I don't want to rate limit. 

Example below of cpu usage (you can tell when compaction is running)

<img width="1315" alt="Screenshot 2024-01-09 at 9 45 35 PM" src="https://github.com/facebook/rocksdb/assets/43054535/4cb0e01e-9a69-4ea1-a017-7c3bf6b6f827">

**Comment by ajkr** [comment]
From that wiki - "RocksDB specified rocksdb::Env::IO_LOW for internal compaction related IO and rocksdb::Env::IO_HIGH for internal flush related IO."

To achieve your goal, you could implement a `RateLimiter` that wraps a rate limiter created by `NewGenericRateLimiter()`. For requests with priority below `Env::IO_HIGH`, forward them to the wrapped rate limiter. For other requests, do not forward them and instead simply return.

**Comment by zaidoon1** [comment]
so for more context, I'm using rust-rocksdb which relies on the c api to use rocksdb. Correct me if i'm wrong, but it looks like the best (only?) way to do this would be to update the rate limiter in rocksdb to allow more customization/decide what to rate limit and update the c api accordingly?

**Comment by ajkr** [comment]
Oh I see. A simpler thing to expose in the C API would be the `mode` argument: https://github.com/facebook/rocksdb/blob/4835c11cce4d7c0b59170cfdb5ab3c4afdeda19e/include/rocksdb/rate_limiter.h#L165

Then rate limit `RateLimiter::Mode::kReadsOnly`, which would have the side effect of not rate limiting flush because it does not perform read I/O

**Comment by ajkr** [comment]
Fixed by #12259
