### ISSUE TITLE
Strange exported function names in official Maven build for Windows

### ISSUE THREAD

**Issue by theolivenbaum** [facebook/rocksdb#12226]
I'm [trying](https://github.com/curiosity-ai/rocksdb-sharp/issues/49) to switch our [C# RockDB binding](https://github.com/curiosity-ai/rocksdb-sharp/) to use the [official JNI builds](https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni), and that's fine for macOS and Linux, but weirdly, the function names exported for the Windows .dll files have some weird prefixes on them. When we try to use this library instead of the [custom built .dll](https://github.com/curiosity-ai/rocksdb-sharp/blob/master/build-native/build-rocksdb.sh), it fails because it can't find any of the functions exported.

### Expected behavior
Exported function names don't have added JAVA-related prefixes:

<img width="409" alt="image" src="https://github.com/facebook/rocksdb/assets/8791811/c4fa53b8-ad1d-4578-8c75-754e0f5a011e">

### Actual behavior
Method names have strange prefixes, like `Java_org_rocksdb_AbstractEventListener_...`
![image](https://github.com/facebook/rocksdb/assets/8791811/10d04e5d-a390-4c1c-95ff-d860dfd9aac1)

### Steps to reproduce the behavior
Download the [latest Windows build from Maven](https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/8.9.1/rocksdbjni-8.9.1-win64.jar), open it as a zip and use [DLL Export](https://www.nirsoft.net/utils/dll_export_viewer.html) or other tools to view exported function names.

**Comment by adamretter** [comment]
@theolivenbaum You are looking at the named of the JNI interface functions. These exist on all platforms. You should also be able to find the non-JNI (i.e. pure C++) API functions too

**Comment by rubo** [comment]
Looks like the non-JNI functions are not exported for Windows.

**Comment by adamretter** [comment]
@rubo if that is the case, then we may need to tweak the CMake build that is used for Windows. @rhubner any ideas on this one?

**Comment by rhubner** [comment]
@adamretter Nothing in my sleeve at the moment, but at least I can replicate what @rubo mentioned.

**Comment by rubo** [comment]
Any chance this will be addressed in the next release?

**Comment by adamretter** [comment]
@rubo It depends on timing. We have a draft PR that @rhubner has prepared but it is still far from ideal (as it currently means  having to list all files to export symbols from). We need to find a better approach in that PR - if you have ideas?

**Comment by theolivenbaum** [comment]
@adamretter any ideas why this it different than on the Linux/macOS builds?

**Comment by rhubner** [comment]
@theolivenbaum 

It's a limitation of linker on windows. By default it only exports from the library you are compiling, in our case rocksdbjni. To export symbols from librocksdb you need to provide _def_ file where all symbols are explicitly mentioned. Unfortunately there is no simple solution to generate these symbols automatically. 

I have two ideas how to fix this, neither is best: 

1. First compile rocksdb.dll and then export all symbols and with some PowerShell magic prepare _def_ file.
2. Change build that rocksdb and rocksjni will be compiled together. At the moment we first compile rocksdb to .lib and then we compile rocksdbjni.dll and link together. 

Radek

**Comment by theolivenbaum** [comment]
Wouldn't it be possible to compile just the rocksdb library without the Java methods instead and provide it as part of the package?

**Comment by rhubner** [comment]
@theolivenbaum 
Yes, but then it will double the size of the distribution package(.jar) and code will be there twice. Once as `librocksdb.dll` and second as `librocksdbjni.dll`

**Comment by theolivenbaum** [comment]
Not sure if relevant in this case, but just found this: https://cmake.org/cmake/help/latest/prop_tgt/WINDOWS_EXPORT_ALL_SYMBOLS.html

````
This can be used to export symbols from a .dll that are not in any of its object files 
but are added by the linker from dependencies (e.g. msvcrt.lib).
````

**Comment by theolivenbaum** [comment]
Another question about the JNI builds: are they built with or without the jemalloc / tcmalloc flags?

**Comment by rhubner** [comment]
@theolivenbaum

> Another question about the JNI builds: are they built with or without the jemalloc / tcmalloc flags?

Without jemalloc/tcmalloc and we are not planning to support in our builds jemalloc/tcmalloc

**Comment by theolivenbaum** [comment]
Perfect, just wanted to confirm that! I've added on our end a separate build for Linux (on top of using the JNI r)eleases) so we can have a librocksd-jemalloc.so, because we very often hit [this](https://blog.cloudflare.com/the-effect-of-switching-to-tcmalloc-on-rocksdb-memory-use/) in production.

**Comment by rhubner** [comment]
Hello @theolivenbaum

I just updated #12246 Now we should be able to compile and release .dll on windows with rocksdb functions. The solution is not perfect, but it works. Unfortunately WINDOWS_EXPORT_ALL_SYMBOLS didn't work.

It will be great if you can check the PR and test if the output .dll works for you.

Radek

**Comment by rubo** [comment]
I think we can consider this issue resolved. Thank you for the fix.

**Comment by ajkr** [comment]
> I'm [trying](https://github.com/curiosity-ai/rocksdb-sharp/issues/49) to switch our [C# RockDB binding](https://github.com/curiosity-ai/rocksdb-sharp/) to use the [official JNI builds](https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni), and that's fine for macOS and Linux, but weirdly, the function names exported for the Windows .dll files have some weird prefixes on them. When we try to use this library instead of the [custom built .dll](https://github.com/curiosity-ai/rocksdb-sharp/blob/master/build-native/build-rocksdb.sh), it fails because it can't find any of the functions exported.

Have you considered alternative solutions like updating the build script so it doesn't assume the build host's compression libraries will be present on the target machine? There should be a way to do this using our build system. Using Java artifacts for a non-Java project sounds like a less common solution, though I could be wrong.

**Comment by adamretter** [comment]
> Using Java artifacts for a non-Java project sounds like a less common solution, though I could be wrong.

If you extract the .dll or .so files from the Jar file, then you really just have a binary build of RocksDB as a library. It does also include the JNI C++ API, but that is fairly light-weight, and you can use it if you wish, or just ignore it.
