### ISSUE TITLE
Iterator is still valid after calling the `Reset`

### ISSUE THREAD

**Issue by git-hulk** [facebook/rocksdb#12225]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

iter->Valid() should return false after calling the Reset() function.

### Actual behavior

The return value is true after resetting the iterator.

### Steps to reproduce the behavior

1. Use iter->Seek() to make the iterator become valid
2. Then iter->Reset() and call iter->Valid() will return true

I'm not quite sure if it's an expected behavior. If not, then I can submit a PR to solve it, but this may introduce compatibility issue for users.

**Comment by ajkr** [comment]
Probably we should prohibit users from calling `Cleanable::Reset()` on an `Iterator`. I can't think of a reason to call it - is there one? The following patch would prevent it, though I don't really want to add four `friend class`es to `Iterator`, so would be glad to see any improvement on that -

```
diff --git a/include/rocksdb/iterator.h b/include/rocksdb/iterator.h
index e90b887b1..11c48e8be 100644
--- a/include/rocksdb/iterator.h
+++ b/include/rocksdb/iterator.h
@@ -27,7 +27,7 @@

 namespace ROCKSDB_NAMESPACE {

-class Iterator : public Cleanable {
+class Iterator : protected Cleanable {
  public:
   Iterator() {}
   // No copying allowed
@@ -152,6 +152,11 @@ class Iterator : public Cleanable {
     assert(false);
     return Slice();
   }
+
+  friend class WriteUnpreparedTxn;
+  friend class WriteUnpreparedTxnDB;
+  friend class WritePreparedTxn;
+  friend class WritePreparedTxnDB;
 };

 // Return an empty iterator (yields nothing).
```

**Comment by git-hulk** [comment]
@ajkr Thanks for your reply.

> Probably we should prohibit users from calling Cleanable::Reset() on an Iterator. 

In our scenario, we want to make the iterator invalid if it mismatches the prefix. But it seems there is no way to do that for now, so I tried `Reset()` and found it just cleans up some resources. It makes sense to me if the Reset is only used for cleaning up the iterator.

**Comment by ajkr** [comment]
> the iterator invalid if it mismatches the prefix

RocksDB can do it for you if you have a `prefix_extractor` configured, and you set `ReadOptions::prefix_same_as_start`. There's some read-amp optimizations too when RocksDB has awareness that scanning never needs to visit another prefix.

If implementing it in application code, you would probably implement an `Iterator` subclass that wraps a RocksDB iterator, and you can make the wrapper's `Valid() == false` as needed

**Comment by git-hulk** [comment]
@ajkr Thanks for your answer. It works well for me.
