### ISSUE TITLE
Update RocksJava Wiki to include Logging Page

### ISSUE THREAD

**Issue by neilramaswamy** [facebook/rocksdb#12255]
Please let me know if there is a better venue for submitting a Wiki page update. With my changes in #12213, I think it's a good idea to add documentation to RocksJava on how to use (native) Loggers, especially for JDK 17 users who might be experiencing the same regression that my changes should mitigate.

## Logging

By default, a RocksDB database will not perform any internal logging. However, as a RocksJava user, you still might be interested in compaction statistics, write stalls, flush times, etc.

RocksJava supports two forms of logging: JVM-based logging, and native logging. In JVM-based logging, a user-supplied Java class is invoked over the JNI for every log message. In native logging, a native logger (i.e. one that only exists in the C++ realm) is invoked for every log message. While a JVM-based logger would allow you to utilized your existing JVM logging infrastructure (like Log4J), it does have non-trivial overhead compared to using a native logger.

## Configuring a JVM Logger

Once you have an `Options` or `DBOptions` object, you can call `options.setLogger` and pass it an instance of `org.rocksdb.Logger`, which can be constructed either by:

1. Passing in `options` directly. This is deprecated as of RocksDB 8.11.0, but supported in all versions.
2. Passing in an `InfoLogLevel`. This is supported as of RocksDB 8.11.0, but is the recommended constructor.

For example:

```java
org.rocksdb.Logger jvmLogger = new org.rocksdb.Logger(org.rocksdb.InfoLogLevel.INFO_LEVEL) {
    @Override
    protected void log(InfoLogLevel level, String message) {
        switch (level) {
            case FATAL_LEVEL:
            case ERROR_LEVEL:
                log4jLogger.error(message);
                break;
            case WARN_LEVEL:
            case INFO_LEVEL:
                log4jLogger.info(message);
                break;
            case DEBUG_LEVEL:
                log4jLogger.debug(message);
                break;
            default:
                log4jLogger.trace(message);
        }
    }
};

options.setLogger(jvmLogger);
```

> [!IMPORTANT]  
> If you don't create your `Options` in a try-catch (so that auto-closing of the object happens), do not forget to call `options.close()` when you are done using the Options object. You can safely close your `Options` after you are done using it, even if the underlying database is still open.

## Configuring a Native Logger

You can configure a Native Logger with the same `options.setLogger` method, on either `Options` or `DBOptions`. Currently, only the standard error logger is supported, but implementing [other native loggers](https://github.com/facebook/rocksdb/wiki/Logger) would be welcome contributions. You can use the `stderr` native logger from RocksJava as follows:

``` java
StdErrLogger stdErrLogger = new StdErrLogger(InfoLogLevel.DEBUG_LEVEL);
options.setLogger(stdErrLogger);
```

If you are opening multiple RocksDB databases from the same RocksJava process, it will be hard to differentiate which logs belong to which RocksDB database. If you were writing your own JVM logger, you could embed the database name in your JVM logger. To achieve this same functionality with native loggers, you can create a `StderrLogger` with a log prefix, which will be appended to each log after the log's timestamp and thread ID.

``` java
StdErrLogger stdErrLoggerForFooDB = new StdErrLogger(InfoLogLevel.DEBUG_LEVEL, "[Foo DB] ");
fooOptions.setLogger(stdErrLoggerForFooDB);
RocksDB.open(fooOptions, ...)

StdErrLogger stdErrLoggerForBarDB = new StdErrLogger(InfoLogLevel.DEBUG_LEVEL, "[Bar DB] ");
barOptions.setLogger(stdErrLoggerForBarDB);
RocksDB.open(barOptions, ...)
```

**Comment by adamretter** [comment]
Seems like a good idea. What is your opinion on adding it to an existing page, or whether to add a new page in its own right?

**Comment by neilramaswamy** [comment]
I think adding a "Logging" page under the RocksJava wiki would be best. The existing RocksJava Basics page is getting a bit long in my opinion, and this isn't really a basic feature -- the RocksDB logs certainly won't be useful for anyone with a "basic" use-case.

**Comment by adamretter** [comment]
@neilramaswamy Thanks, I have added a page based on your example here - https://github.com/facebook/rocksdb/wiki/Logging-in-RocksJava

* I also adapted it to demonstrate a slf4j bridge.
* I tried to make the memory management responsibilities when using Logger clearer.

What do you think?

**Comment by neilramaswamy** [comment]
Just confused about one part:

> but implementing your own [native logger](https://github.com/facebook/rocksdb/wiki/Logger) is also possible.

How do we practically expect Java users to do that? For our native logger changes, we have support over on the C++ side. If you're just suggesting that users can submit a PR to add another native logger, maybe that can be made more explicit. Currently, it sounds possible from RocksJava, but I don't think it is.

Otherwise, this is great!

**Comment by adamretter** [comment]
> How do we practically expect Java users to do that?

We would expect them to write C++, hence the "native" aspect. I have updated the wording to try and make that clearer.

Thanks for your work on this @neilramaswamy.
