### ISSUE TITLE
Question about compression type in rocksdbjava benchmark

### ISSUE THREAD

**Issue by krobz** [facebook/rocksdb#12258]
Hi, 
I want to test benchmark by jdb_bench and ran commands below:
```
make -j16 rocksdbjava
make -j16 jdb_bench 
```
it works fine, but got some errors when I tried to run the benchmark .sh (  ./jdb_bench.sh --benchmarks=fillseq )

### Expected behavior

there should be no error.

### Actual behavior
`Unable to load snappy library:java.lang.UnsatisfiedLinkError: no snappy in java.library.path` 
I got this error also when using `lz4, lz4hc, xpress, zstd`.

I found one line in install.md that "If you wish to build the RocksJava static target, then cmake is required for building Snappy". But how could I build Snappy in RocksJava by cmake. 
I tried `cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DWITH_GFLAGS=1 -DWITH_SNAPPY=1 -DWITH_LZ4=1 -DWITH_ZLIB=1 -DWITH_JNI=1` but it does not work.

Thank you for your help!

**Comment by adamretter** [comment]
> I found one line in install.md that "If you wish to build the RocksJava static target, then cmake is required for building Snappy". But how could I build Snappy in RocksJava by cmake.

This just means that you need to have a recent copy of CMake installed.

Have you installed the compression libraries to your system before running `make`? Details of that are listed in `INSTALL.md`
