### ISSUE TITLE
Missing documentation - How To Backup RocksDB page

### ISSUE THREAD

**Issue by c0dzilla** [facebook/rocksdb#12292]
Check the page: https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F

### Expected behavior

Contains info about RocksDB backup.

### Actual behavior

Empty page with "Hello hello hello hello"

![image](https://github.com/facebook/rocksdb/assets/23701803/fb0dca48-2018-40e7-a418-38595d686974)

### Steps to reproduce the behavior

Open https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F

**Comment by c0dzilla** [comment]
Turns out the valid page is available at: https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB .
So the page mentioned in this issue description could be stale. If so, it can be deleted.

**Comment by adamretter** [comment]
@c0dzilla I have now deleted the redundant page at: https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F
