### ISSUE TITLE
Error: use of undeclared identifier 'abort' (Clang)

### ISSUE THREAD

**Issue by AlexNk** [facebook/rocksdb#1233]
When compiling by Clang 3.8.0 the following error was observed:
```
util/thread_posix.cc:22:5: error: use of undeclared identifier 'abort'
    abort();
```
To fix it, add include of stdlib.h to thread_posix.cc

**Comment by IslamAbdelRahman** [comment]
Thanks @AlexNk for reporting, do you want to create a pull request to fix it ?

**Comment by AlexNk** [comment]
Just double-checked.
This issue relates only to 4.6 (latest release) and 4.7.
In later versions this file is not exists and project can be successfully compiled with clang.

**Comment by tamird** [comment]
@IslamAbdelRahman this still seems to be an issue on 5.1.4. See https://github.com/facebook/rocksdb/blob/v5.1.4/util/threadpool_imp.cc#L32.
