### ISSUE TITLE
when to use checkpoint vs opening rocksdb in read only mode

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12340]
Reading https://github.com/facebook/rocksdb/wiki/Checkpoints , it is not clear to me when I should use a checkpoint vs opening rocksdb in read only mode. 

For example, I have a rocksdb instance that is open in read/write mode all the time and is being written to/read from all the time. I have a separate cronjob (different process) that opens rocksdb in read only mode, iterates over the entire db and deletes orphaned keys based on some specific requirements (sends delete requests to the process that has rocksdb open in read/write mode). This is done every 3 hours, then the cronjob closes the db, and reopens it in read only mode again to get a fresher view the next run and does the same thing. Per https://github.com/facebook/rocksdb/wiki/Iterator#resource-pinned-by-iterators-and-iterator-refreshing ` the best use of iterator is to keep it short-lived, so that these resource is freed timely. ` but in my case, i'm keeping the iterator around for a few hours as it takes me that long to iterate over the entire db (adding some delays to not overload disk as well). 

Questions:

1. in my specific use case, is taking a checkpoint and processing that from a different process better? If so why?
2. I assume the comment about keeping the iterators short lived still applies even when opening rocksdb in read only mode as it will pin the resources in the process that has the db open in read/write mode?

**Comment by ltamasi** [comment]
> For example, I have a rocksdb instance that is open in read/write mode all the time and is being written to/read from all the time. I have a separate cronjob (different process) that opens rocksdb in read only mode
...
> 
> Questions:
> 
> 1. in my specific use case, is taking a checkpoint and processing that from a different process better? If so why?

Generally speaking, using a read-only instance this way is not safe/supported: the read/write instance can delete files (e.g. SST files that get compacted away) from underneath the read-only instance. Checkpoints ensure that all the files necessary for a consistent snapshot of the database are preserved (by copying or hard-linking them).

> 2. I assume the comment about keeping the iterators short lived still applies even when opening rocksdb in read only mode as it will pin the resources in the process that has the db open in read/write mode?

Having a read-only instance open has no effect on the read/write instance, which is why files might be deleted (see above).

**Comment by zaidoon1** [comment]
got it, so aside from the possible consistency issue, is there any performance benefits of using checkpoint over read only instance for my use case?

**Comment by ltamasi** [comment]
In general, checkpoints do not offer a performance benefit. They don't have much of a performance overhead either though (other than copying certain types of files where hard linking is not appropriate), so I would suggest using them in use cases like this for the sake of correctness.

**Comment by zaidoon1** [comment]
got it, thank you!
