### ISSUE TITLE
unexplained sudden increase in memory usage

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12364]
I suddenly started seeing the memory usage increase for no apparent reason and it has not come down yet:

<img width="841" alt="Screenshot 2024-02-20 at 4 16 14 PM" src="https://github.com/facebook/rocksdb/assets/43054535/5666bd9e-3110-436e-9419-ff90d699f342">

<img width="1702" alt="Screenshot 2024-02-20 at 4 15 50 PM" src="https://github.com/facebook/rocksdb/assets/43054535/ad5df7bd-cf40-4a78-a9e3-1d5aad3beef1">

I have various metrics tracking memory usage, other things happening in rocksdb but none explain why the memory usage went up to the level it hit without coming back down:

<img width="1706" alt="Screenshot 2024-02-20 at 4 17 12 PM" src="https://github.com/facebook/rocksdb/assets/43054535/2f8e5466-b5b0-4455-8672-76bcb715182f">

<img width="1705" alt="Screenshot 2024-02-20 at 4 31 26 PM" src="https://github.com/facebook/rocksdb/assets/43054535/32898bc0-eb8a-4379-95b1-0d630b0e05a6">

I've also attached the LOG file (although I got the LOG a day after this issue started so not sure how useful):

[LOG.txt](https://github.com/facebook/rocksdb/files/14351423/LOG.txt)

Any idea or suggestions to what can cause this?

**Comment by zaidoon1** [comment]
is there a formula for calculating max memory usage? My initial understanding is that if set_cache_index_and_filter_blocks is set to true, then total memory usage by rocksdb can be calculated as follows:

block cache size per cf + max_write_buffer_number per cf x write_buffer_size per cf

for example, say we have 3 cfs and each is configured with the following
values:
block cache size = 1.5 GB
write_buffer_size = 256 MB
max_write_buffer_number = 4

then total memory usage will be 3 x 1.5 GB + 3 x 4 x 256 MB = 7.5 GB


But it seems this formula is still missing something?

**Comment by ajkr** [comment]
What allocator are you using? We use jemalloc. If you are using jemalloc, can you set `dump_malloc_stats`?

**Comment by zaidoon1** [comment]
I'm using jemalloc, I'll look into `dump_malloc_stats`

**Comment by zaidoon1** [comment]
I may have misunderstood your question, in my LOG file i see:

```
  block_cache_options:
    capacity : 33554432
    num_shard_bits : 6
    strict_capacity_limit : 0
    memory_allocator : None
    high_pri_pool_ratio: 0.500
    low_pri_pool_ratio: 0.000
    ```
    looks like I can set an allocator for block cache? My application that has rocksdb bundled in it is using jemalloc, but I don't pass a memory allocator when constructing the block cache. Is that an issue?

**Comment by ajkr** [comment]
> looks like I can set an allocator for block cache? My application that has rocksdb bundled in it is using jemalloc, but I don't pass a memory allocator when constructing the block cache. Is that an issue?

Probably not an issue. `memory_allocator` is useful only if you want to customize allocations for block cache blocks. For example, adding instrumentation or requesting them from a special jemalloc arena.

**Comment by zaidoon1** [comment]
so i tried setting dump_malloc_stats but nothing shows up. Note that i'm doing this from rust so i'm using the c api to do this.

rust code:

```
            db_opts.enable_statistics();
            db_opts.set_log_level(LogLevel::Info);
            db_opts.set_dump_malloc_stats(true);
```
 
which translates to calling the following c functions:
```
rocksdb_options_enable_statistics
rocksdb_options_set_info_log_level
rocksdb_options_set_dump_malloc_stats
```

And per https://github.com/facebook/rocksdb/blob/d1386de632333e936b5bed63510c5d89d6cd18b4/db/db_impl/db_impl.cc#L1166-L1173

I expect to see a `Malloc STATS` section but don't see that.

Is there something else I need to call/set to get this to show up?

**Comment by zaidoon1** [comment]
correction, it turns out the rust crate by default doesn't not build rocksdb with jemalloc and it gates it behind a feature flag so I actually wasn't using jemalloc for rocksdb part at least which explains why the stats were not printing. I'll enable jemalloc with rocksdb and see how that changes perf/memory utilization and will report back if that on its own resolves the issue.

**Comment by zaidoon1** [comment]
so even after enabling the feature flag, I still don't see the stats. Just to make sure, the rust library tries to get rocksdb to use jemalloc by setting:
```
config.define("WITH_JEMALLOC", "ON");
```

is `WITH_JEMALLOC ON` the correct flag?

**Comment by mdcallag** [comment]
In past tests I usually see RSS with glibc malloc being 2X or more larger than RSS with jemalloc.
One example - https://smalldatum.blogspot.com/2018/04/myrocks-malloc-and-fragmentation-strong.html

RocksDB can be a stress test for allocator fragmentation and jemalloc does better at avoiding it.

**Comment by zaidoon1** [comment]
update, the rust bindings are the problem as they were not actually getting rocksdb to use jemalloc. After fixing them locally, I can actually see the malloc stats.

**Comment by zaidoon1** [comment]
a feature request that might be helpful is to include in the LOG the allocator being used by rocksdb to make sure that users don't think they are using something that they are not actually using.

**Comment by ajkr** [comment]
> a feature request that might be helpful is to include in the LOG the allocator being used by rocksdb to make sure that users don't think they are using something that they are not actually using.

Agreed. We could log the value of `HasJemalloc()` here to start with: https://github.com/facebook/rocksdb/blob/2940acac0088384b9fd146ce2a2ba5e2a298d5d5/db/db_impl/db_impl.cc#L138-L151

Feel free to submit a PR if you are interested

**Comment by leeqx** [comment]
> I suddenly started seeing the memory usage increase for no apparent reason and it has not come down yet:
> 
> <img alt="Screenshot 2024-02-20 at 4 16 14 PM" width="841" src="https://private-user-images.githubusercontent.com/43054535/306420218-5666bd9e-3110-436e-9419-ff90d699f342.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjM1NzUsIm5iZiI6MTcwOTYyMzI3NSwicGF0aCI6Ii80MzA1NDUzNS8zMDY0MjAyMTgtNTY2NmJkOWUtMzExMC00MzZlLTk0MTktZmY5MGQ2OTlmMzQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3MjExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMjY5MTA2ZGQ1MDdjMzVlZTE3YzkyZTE5NTgzYmQzYTBjMjRlYWIyMGQzYzU0ZmY4ZTNkYmRiZjdhMjMyMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XOrJAU0dCp_QxUAo2zft2pyXIuA36Gi6-uRBpJJmxo8"> <img alt="Screenshot 2024-02-20 at 4 15 50 PM" width="1702" src="https://private-user-images.githubusercontent.com/43054535/306422002-ad5df7bd-cf40-4a78-a9e3-1d5aad3beef1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjM1NzUsIm5iZiI6MTcwOTYyMzI3NSwicGF0aCI6Ii80MzA1NDUzNS8zMDY0MjIwMDItYWQ1ZGY3YmQtY2Y0MC00YTc4LWE5ZTMtMWQ1YWFkM2JlZWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3MjExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNzkxZWM5MDczY2NiZDQ1YjRmZGQzYjVmNjUyMjllOTJlMTc0MjQyYTg3ZTNlNWNjYWNmYjA5N2JhZmU3NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4JNFrVaIu1fNiIGog0uJ4LqKye7QuhloBXWGiYSl2Hs">
> I have various metrics tracking memory usage, other things happening in rocksdb but none explain why the memory usage went up to the level it hit without coming back down:
> 
> <img alt="Screenshot 2024-02-20 at 4 17 12 PM" width="1706" src="https://private-user-images.githubusercontent.com/43054535/306421410-2f8e5466-b5b0-4455-8672-76bcb715182f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjM1NzUsIm5iZiI6MTcwOTYyMzI3NSwicGF0aCI6Ii80MzA1NDUzNS8zMDY0MjE0MTAtMmY4ZTU0NjYtYjViMC00NDU1LTg2NzItNzZiY2I3MTUxODJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3MjExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZTdkNmVkNjk3MjBkN2RmN2RlODQwZDY5OGFhY2Q2OTg3ODg0MWZiYjg3ZTFkODQxYTk2ZWU1N2M0ZjNmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2lmXZpg9G_w58vM_IElzXg-E8ntDNWIRolk2noqDcuM"> <img alt="Screenshot 2024-02-20 at 4 31 26 PM" width="1705" src="https://private-user-images.githubusercontent.com/43054535/306423667-32898bc0-eb8a-4379-95b1-0d630b0e05a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjM1NzUsIm5iZiI6MTcwOTYyMzI3NSwicGF0aCI6Ii80MzA1NDUzNS8zMDY0MjM2NjctMzI4OThiYzAtZWI4YS00Mzc5LTk1YjEtMGQ2MzBiMGUwNWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3MjExNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYzNhMDFkNjcwZTIyYzljYWM3NDJiYzU3NjEyYmE5NzY3Mzc4YjhkMjhkYmEzZDE3ZWU1NWYyYjE4ZDQzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ggYMSxAqzSTMlKQvGe4dbHXtrTtKgts_5Z7h1bFQg9g">
> I've also attached the LOG file (although I got the LOG a day after this issue started so not sure how useful):
> 
> [LOG.txt](https://github.com/facebook/rocksdb/files/14351423/LOG.txt)
> 
> Any idea or suggestions to what can cause this?

please shared me the monitor code of Rocksdb? I need to monitor rocksdb's memory usage, thanks.

**Comment by zaidoon1** [comment]
@leeqx the rss memory i got from container_memory_rss{app_name=~"service_name.service"}. and other rocksdb memory usage metrics i got using https://github.com/zaidoon1/rust-rocksdb/blob/3e4a0f632a8c0c2839c7d183725c53895110d907/src/perf.rs#L267 

Also update, after actually enabling jemalloc, I can confirm the memory issue is definitely fixed
<img width="1316" alt="Screenshot 2024-03-05 at 3 35 48 AM" src="https://github.com/facebook/rocksdb/assets/43054535/66a71b30-bc0d-4035-ad7b-84b884c96c5a">

thanks for the help everyone!
