### ISSUE TITLE
Master branch unable to find zstd

### ISSUE THREAD

**Issue by Mis1eader-dev** [facebook/rocksdb#12361]
Today I checked out into the master branch in one of my projects, and it no longer is able to perform `find_package` on `zstd` and fails.

### Expected behavior
Should be able to link against `zstd` with `find_package`.

### Actual behavior
Unable to link against `zstd` with rocksdb's own CMakeLists.txt `find_package`.

### Steps to reproduce the behavior
Enable `zstd` in CMakeLists.txt
```cmake
set(WITH_ZSTD ON)
```
Run CMake, it fails in `find_package`.

**Comment by raffertyyu** [comment]
fixed in #12309 and waiting to be merged
