### ISSUE TITLE
Is it possible to make the db.get operation after db.close without exception?

### ISSUE THREAD

**Issue by losper** [facebook/rocksdb#12382]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
call db.get after db.close without exception.
### Actual behavior
An exception has occurred when db.get after db.close
### Steps to reproduce the behavior
``` C
db->Close();
db->Get(ReadOptions(), "key2", &value); // An exception has occurred 
```

**Comment by adamretter** [comment]
Could you not track whether you have closed the database in a variable?

```
bool closed = false;

...

db->Close();
closed = true;

...

if (!closed) {
    db->Get(ReadOptions(), "key2", &value);
}
```

**Comment by hx235** [comment]
Why do you want to call Get() after a DB close?

**Comment by hx235** [comment]
If you'd like to call Get() conditionally, something like the above https://github.com/facebook/rocksdb/issues/12382#issuecomment-1963993445 seems fine to me.
