### ISSUE TITLE
Feature request: check if prefix exists without seeking

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12396]
Currently, my service is performing thousands of prefix matches per second to check if a given prefix matches any key in a cf/db. The current approach I'm using is to do a seek to the prefix and if found then return true otherwise return false.

My setup is as follows:

say my key format is: `<uid>:<some dynamic value>`
my prefix extractor is setup to extract the `<uid>`
my prefix exists check are in the form of:` <uid>:<some prefix>` so while i always have the uid and I am benefiting from the prefix extractor/prefix bloom. I still have to seek to <some prefix> to check if there exists a key that starts with this prefix

the feature request:
instead of seeking to the first key that matches the prefix being searched, we stop searching once we find any key that matches the prefix being searched for.

**Comment by ajkr** [comment]
It's a good question. The core of the issue sounds familiar. Users want ways to prevent lookups from searching older LSM components when they already got what they need. 

I will need to think about it more. Coming up with a good API for this may be challenging. Here are a couple use cases we heard about recently that felt like the same core issue.

I dealt with such a case yesterday in #12438. Actually, that user would have preferred an iterator interface, but currently the iterator does not support returning unmerged operands it finds (`GetMergeOperands()`'s feature), so there were too many missing pieces.

There was also a question last week: for a SQL query like `SELECT * FROM t LIMIT 10`, why does RocksDB need to look at all the LSM components? The typical implementation is create an iterator, seek to the start of the table, and call Next() until the tenth entry. But, if there were an iterator where the first-order of the sort was the LSM component (new to old), and second-order of the sort was the key, we could probably get all 10 entries just from the first LSM component (memtable).

**Comment by ajkr** [comment]
> Coming up with a good API for this may be challenging.

I remembered @pdillinger's proposal in #11644. Assuming it supports the limit options ("There would likely be limit options on number of keys and value size"), for your use case you could call the hypothetical `MultiGetRange()` function with your prefix as the range, and the number of keys limit set to one.

The `SELECT * FROM t LIMIT 10` case is similar; we just make the range cover the whole table, and set the number of keys limit to 10.

> And in terms of complexity, is it a simple thing I can do with some directions/pointers from you or does it require more deep level of how rocksdb works?

I think it's difficult. The whole iterator hierarchy today uses key order; it doesn't consider LSM component order at all. Once you introduce LSM component order, there are all sorts of challenges. For example, how to tell if keys were overwritten or deleted in an earlier component that you already processed a while ago. Or how to deal with merge operands - one key's merge operands may be spread over multiple LSM components but all are needed to obtain the value.

**Comment by zaidoon1** [comment]
got it, this makes sense, and thanks for the insight. The `Select * from t limit n` is a great generalization of the problem I'm trying to solve where we want to fetch any records but don't care about order.  It looks like it's best if I can close this ticket in favour of https://github.com/facebook/rocksdb/issues/11644 ?

**Comment by ajkr** [comment]
Sure, if you agree the `MultiGetRange()` API would solve this use case, we can close this issue. How we can actually implement it will hopefully be figured out eventually in #11644...

**Comment by xingbowang** [comment]
As we discussed you could explore the new UDI(User Defined Index) interface and then implement a Trie index yourself to plug it in. If you want to contribute the Trie index implementation, we are happy to review it as well. Another piece of the puzzle is UDI is not working as primary index right now, so maybe need some change to allow UDI to serve as primary index. Meantime, I am wondering how big is your trie. Do you need some kind of lazy load from disk or loading it into memory completely is good enough?

**Comment by zaidoon1** [comment]
> As we discussed you could explore the new UDI(User Defined Index) interface and then implement a Trie index yourself to plug it in. If you want to contribute the Trie index implementation, we are happy to review it as well. Another piece of the puzzle is UDI is not working as primary index right now, so maybe need some change to allow UDI to serve as primary index. Meantime, I am wondering how big is your trie. Do you need some kind of lazy load from disk or loading it into memory completely is good enough?


>  If you want to contribute the Trie index implementation, 

I'll give this a shot and see how far i get!

> Another piece of the puzzle is UDI is not working as primary index right now, so maybe need some change to allow UDI to serve as primary index. 

right, I'll definitely be wanting this to be a primary index so i'll look into this as well.

>  Do you need some kind of lazy load from disk or loading it into memory completely is good enough?

I'm pretty sure, even after switching to a trie based index, we will need some kind of lazy loading since we won't have enough memory to completely load everything. But I don't have enough data to back this up. I'll probably start with what is easier to implement and then see if that's enough or if we need to optimize further.

**Comment by zaidoon1** [comment]
also note, per the code comments, for UDT:

```
// This is currently supported only for a restricted set of use cases. The
// CF must be ingest only, and only files containing Puts generated by
// SstFileWriter are supported.
```

this will need to be re-wroked since we do regular db operations: get, put, delete.

**Comment by xingbowang** [comment]
I guess you mean UDI, not UDT. UDT refer to user defined timestamp.
Yes, this is a limitation. Feel free to come up with the solution. We will help you review it. We do want to generalize it to normal operation.
