### ISSUE TITLE
ZSTD_TrainDictionary runs even when the compression is set to kNoCompression for a given level

### ISSUE THREAD

**Issue by kwadhwa18** [facebook/rocksdb#12409]
ZSTD_TrainDictionary [[link](https://github.com/facebook/rocksdb/blob/a53ed916917fe79a6c3f07313ec7a3fa85ae6dc4/table/block_based/block_based_table_builder.cc#L1894)] runs for `SSTFileWriter::Finish` even when `bottommost_compression` option is set to `kNoCompression`. This reduces throughput for `SstFileWriter::Finish`

We construct rocksdb options using ZSTD compression for levels including 2 and above. For levels 0 and 1, we set it to `kNoCompression`. We also set `zstd_max_train_bytes` to a non-zero positive value (which is applicable for levels with ZSTD compression enabled).  These options are used for the database and also passed to `SstFileWriter` for creating sst files to be later added to that database. Since the BlockBasedTableBuilder::Finish [[link](https://github.com/facebook/rocksdb/blob/a53ed916917fe79a6c3f07313ec7a3fa85ae6dc4/table/block_based/block_based_table_builder.cc#L1892)] only checks for `zstd_max_train_bytes` to be non-zero positive value, it runs `ZSTD_TrainDictionary` even when it shouldn't since `SSTFileWriter` is operating at bottommost level
 
### Expected behavior

If the bottommost_compression or compression_per_level for a level is set to `kNoCompression`, then don't run `ZSTD_TrainDictionary`

### Actual behavior

`ZSTD_TrainDictionary` is also run for level which has `kNoCompression` set

**Comment by ajkr** [comment]
Another case is `max_dict_bytes > 0` will build a dictionary even when compression type is `kNoCompression`. These sound like good sanitizations to add. Would you be interested in adding some of them?

**Comment by kwadhwa18** [comment]
are you referring to https://github.com/facebook/rocksdb/blob/210c8df820380a52c5c99a7cedee731fa380c356/table/block_based/block_based_table_builder.cc#L1874-L1887?

I can help with the sanitizations - is the level information available inside `BlockBasedTableBuilder`?

**Comment by ajkr** [comment]
> are you referring to
> 
> https://github.com/facebook/rocksdb/blob/210c8df820380a52c5c99a7cedee731fa380c356/table/block_based/block_based_table_builder.cc#L1874-L1887
> 
> ?

Yes.

> I can help with the sanitizations - is the level information available inside `BlockBasedTableBuilder`?

Yes, `BlockBasedTableBuilder::Rep` has `compression_type` and `compression_opts`, which are the settings specific to the level for which the table is being built

**Comment by kwadhwa18** [comment]
I have attempted a fix https://github.com/facebook/rocksdb/pull/12420. PTAL!
