### ISSUE TITLE
PrefixKey Question

### ISSUE THREAD

**Issue by yemt** [facebook/rocksdb#1240]
Can i according the prefixKey to find out all the total key number immediately?

**Comment by IslamAbdelRahman** [comment]
Hi @yemt, I am not sure I understand the question correctly, Do you have a prefix and want to figure out the total number of keys that have this prefix ? Can you explain more what do you mean by "immediately" ?

**Comment by yemt** [comment]
@IslamAbdelRahman ，yes，is what I mean，“immediately” I'd like to confirm whether there is this interface。

**Comment by IslamAbdelRahman** [comment]
@yemt, I hope I answered your questions. I will close this issue

**Comment by yemt** [comment]
yes,ths
