### ISSUE TITLE
Windows GitHub Action build of RocksDB failing silently without marking job as failed

### ISSUE THREAD

**Issue by rhubner** [facebook/rocksdb#12421]
### Expected behavior
Mark _build-windows-vs2019_ job as failed
### Actual behavior
_build-windows-vs2019_ is marked as a success.
### Steps to reproduce the behavior
Follow steps to build on windows or check GitHub action [log file ](https://github.com/facebook/rocksdb/actions/runs/8238002885/job/22527942755#step:3:6192): 
```
306>D:\a\rocksdb\rocksdb\db\external_sst_file_basic_test.cc(1961): error C2220: the following warning is treated as an error [D:\a\rocksdb\rocksdb\build\external_sst_file_basic_test.vcxproj]
306>D:\a\rocksdb\rocksdb\db\external_sst_file_basic_test.cc(1961): warning C4706: assignment within conditional expression [D:\a\rocksdb\rocksdb\build\external_sst_file_basic_test.vcxproj]
```

### Proposed solution
Refactor windows build steps. Split one big _Custom step_  [link](https://github.com/facebook/rocksdb/blob/179afd5bef7a043e10c9af322cf620ce11a7322f/.github/actions/windows-build-steps/action.yml#L17) to multiple steps. Reuse GitHub action marketplace for common task, for example `actions/setup-java@v4`. Put compilation and tests to separate steps, so that GitHub action can use exit code to mark build as failed.

cc: @pdillinger

**Comment by robandpdx** [comment]
Try using this pwsh feature...

https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.4#psnativecommanduseerroractionpreference
