### ISSUE TITLE
RocksDB#multiGet copies keys

### ISSUE THREAD

**Issue by adamretter** [facebook/rocksdb#1251]
The `multiGet` function in RocksJava in the `RocksDB` and and `Transaction` class make copies of the provided `key` lists, this should be avoided by either:
1. Using Slices instead so that the `byte[]` are encapsulated and the `List`/`Map` contains just a reference to the slice.
2. Just returning a `List` of values as opposed to a `Map`. Probably the simplest option and closest to the C++ API!

**Comment by buremba** [comment]
And update on this? Maybe we can add a new low-level `multiGet` method that doesn't copy the underlying array and create an HashMap? It should be super-useful considering `multiGet` will often be used for fetching too many keys and the current implementation copies array and create a big `HashMap` even though we expect the result to contain only a few values.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by buremba** [comment]
We should have this. :)

**Comment by adamretter** [comment]
This is done, we now have `multiGetAsList` functions.
