### ISSUE TITLE
Feature request: rate limit compaction triggered by periodic compaction seconds/ ttl only

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12536]
my db size is small but I do have a significant amount of deletes so I set a db ttl/periodic compaction seconds to make sure the tombstones are deleted every few hours.  However, this caused lots of cpu usage spikes as reported in https://github.com/facebook/rocksdb/issues/12220 . I then rate limited compactions which solved this issue, HOWEVER, I thought write stalls can only be caused if flush is slow which is the main reason why I wanted to rate limit compaction but not flushes. It turns out, my understanding was incorrect, we do in fact stall if compaction is slow:

<img width="1443" alt="Screenshot 2024-04-15 at 12 34 02 AM" src="https://github.com/facebook/rocksdb/assets/43054535/6c909e9d-1852-49ad-a698-0b3f4ba44a92">

Given this information, what I would like to do instead is rate limit compaction triggered by db ttl/periodic compaction seconds since this compaction is mainly a clean up operation that doesn't need to happen immediately while at the same time, making sure that compaction triggered to make sure rocksdb "work fast" is not rate limited to avoid stalls.

 Note that I'm using rocksdb in rust so i'm relying on the c apis to control rocksdb behaviour. 
 
 The alternative right now is to play around with the rate limiting so that I don't impact rocksdb write operations while at the same time making sure cpu doesn't spike significantly when periodic compaction seconds/db ttl is running which is trickier to balance.

**Comment by zaidoon1** [comment]
@ajkr what do you think about this? Is there a quick fix that I can implement or will this be more involved?

**Comment by ajkr** [comment]
What are your settings for compaction style, TTL/periodic seconds, and how is data deleted? I am thinking there might be other ways to help with the compaction spikes particularly if you're using leveled compaction style and RocksDB's deletion APIs (vs. other mechanisms like a compaction filter to delete data).

**Comment by zaidoon1** [comment]
when deleting I use ` rocksdb_writebatch_delete_cf `, I don't do have any compaction filters, etc.. And here is my options file (I don't use the default cf so can ignore any options related to that):

[OPTIONS.txt](https://github.com/facebook/rocksdb/files/15039205/OPTIONS.txt)

**Comment by ajkr** [comment]
Thanks for the info. I was wondering if you'd be interested in trying `compaction_pri = kRoundRobin`? Round-robin compaction style simply picks files within a level by cycling through them in order. Whereas the default compaction style (`kMinOverlappingRatio`) picks files according to some heuristic that can form hotspots (key ranges from which files are repeatedly picked) and coldspots (key ranges from which files are rarely or never picked).

I suspect `kRoundRobin` should work better with aggressive TTL settings. That's because round-robin picks the oldest data in the level to compact, saving work for TTL compaction later. In the best case (write rate is high enough that a full cycle of round-robin compaction completes in each level before any file's data age reaches the TTL), there would be no files compacted for TTL reason at all.

**Comment by zaidoon1** [comment]
got it, that's definitely good to know. I'll try out `kRoundRobin` and report back.

**Comment by zaidoon1** [comment]
Here is the results after switching to `kRoundRobin`: 
<img width="466" alt="Screenshot 2024-07-04 at 11 40 55 AM" src="https://github.com/facebook/rocksdb/assets/43054535/3cd754c2-51d4-48e4-b0a1-8728980c90e1">

I don't see much of a difference. Here is some interesting stats at the time of one spike:



<img width="1713" alt="Screenshot 2024-07-04 at 11 56 56 AM" src="https://github.com/facebook/rocksdb/assets/43054535/6f256f2c-993f-4b14-a4a7-8e7bbfcb0bfb">


I don't have a reason to think it's something else given that when I rate limited compaction, the problem was solved, I am using ribbon filters instead of bloom which is supposed to use up more cpu but I don't think that's related given that the rate limiting wouldn't have affected it? 

I'm thinking of a potential workaround, right now, I have 4 cfs that have the same ttl to trigger compaction, what if I change the ttl slightly to make sure they are not triggering at the same time? In theory this should reduce the number of compactions running at a given time (at least related to ttl, not write rate) and that should reduce cpu usage. Thoughts?

**Comment by zaidoon1** [comment]
> I'm thinking of a potential workaround, right now, I have 4 cfs that have the same ttl to trigger compaction, what if I change the ttl slightly to make sure they are not triggering at the same time? In theory this should reduce the number of compactions running at a given time (at least related to ttl, not write rate) and that should reduce cpu usage. Thoughts?

I tried this as well, and unfortunately that didn't help either.

**Comment by zaidoon1** [comment]
I'm starting to think this is NOT related to compaction. Let's take a look here:

<img width="1704" alt="Screenshot 2024-07-06 at 3 38 04 PM" src="https://github.com/facebook/rocksdb/assets/43054535/9cf0bd87-5c83-4725-b84a-c09e7c81d42c">

we can see the cpu spikes correlate with the block cache MISSes. @ajkr any idea what I should look at next?

**Comment by zaidoon1** [comment]
is it possible to get block cache stats (block cache miss) per cf so I can narrow down which cf is causing the issue

**Comment by zaidoon1** [comment]
At this point, my guess is the compression settings i'm using is to blame:

```
 opts.set_compression_type(DBCompressionType::Lz4);
 opts.set_bottommost_compression_type(DBCompressionType::Zstd);
 opts.set_bottommost_zstd_max_train_bytes(0, true);
```

I assume  Zstd for bottommost is definitely not great with cpu usage. Per https://rocksdb.org/blog/2021/05/31/dictionary-compression.html I'm thinking of trying:

```
(zstd only) EXTRA_CXXFLAGS=-DZSTD_STATIC_LINKING_ONLY: Hold digested dictionaries in block cache to save repetitive deserialization overhead. This saves a lot of CPU for read-heavy workloads. This compiler flag is necessary because one of the digested dictionary APIs we use is marked as experimental. We still use it in production, however.
```

And if that doesn't help then disable bottommost_compression/use something other than zstd

**Comment by zaidoon1** [comment]
also if `DZSTD_STATIC_LINKING_ONLY` is set correct, should I expect https://github.com/facebook/rocksdb/blob/v9.3.1/monitoring/statistics.cc#L42-L49 to be populated?

**Comment by zaidoon1** [comment]
after doing some testing, I can confirm the cpu spikes is related to compaction + using zstd compression in the bottommost level. Removing:

```
 opts.set_bottommost_compression_type(DBCompressionType::Zstd);
 opts.set_bottommost_zstd_max_train_bytes(0, true);
 ```
 
 results in a more stable cpu usage. However, it does increase disk space usage by about 25% which is not ideal. I'm thinking of setting bottommost compression type to lz4 at this point to gain some compression benefits while keeping cpu usage reasonable. @ajkr What do you think? Is there a way for me to keep zstd while reducing the cpu usage impact?

**Comment by ajkr** [comment]
> Is there a gotcha with enabling this option?

Sort of. A different option (`max_dict_bytes`) needs to also be enabled, otherwise there is no dictionary to build a digested dictionary from. Depending on your data patterns, you could find major space savings by enabling dictionary especially considering the small data block size (4K)

> @ajkr What do you think? Is there a way for me to keep zstd while reducing the cpu usage impact?

There are ways to shift it around like rate limiting or deprioritizing compaction CPU (`LowerThreadPoolCPUPriority()`).

Another consideration is maybe the CPU impact is more about compression than decompression. Although block cache misses points to decompression, the two are interleaved during compaction so it could be either. If compression is a major source of CPU you can try `CompressionOptions::level < 3` (3 is the ZSTD default) for the bottommost compression settings.

**Comment by zaidoon1** [comment]
something was still not adding up looking at my graphs, so I disabled zstd all together in bottommost compression and let it run for half a day or so and here is all the stats i have collected:

so starting with the cpu spikes, we can see 3 cpu spikes that I'm interested in knowing the cause of:

<img width="1712" alt="Screenshot 2024-07-10 at 11 20 41 PM" src="https://github.com/facebook/rocksdb/assets/43054535/8a3e0a1f-0023-4fe5-a743-00479ac93c4b">

also memory usage went up, i assume it's related to disabling zstd as well

Here is all other rocksdb stats I have that don't show anything interesting happening at the time of each cpu spike:


<img width="1676" alt="Screenshot 2024-07-10 at 11 23 13 PM" src="https://github.com/facebook/rocksdb/assets/43054535/3058a744-7104-48c1-aaf8-519b94a99351">



<img width="1709" alt="Screenshot 2024-07-10 at 11 23 28 PM" src="https://github.com/facebook/rocksdb/assets/43054535/d3423a4f-abd3-4124-997e-2cf51eb18a35">


<img width="1701" alt="Screenshot 2024-07-10 at 11 23 47 PM" src="https://github.com/facebook/rocksdb/assets/43054535/f702e4f0-209a-4edf-b1f5-0b87cad5f5e1">


<img width="1696" alt="Screenshot 2024-07-10 at 11 24 02 PM" src="https://github.com/facebook/rocksdb/assets/43054535/6672200d-56ff-4ba0-b723-9a25add9f281">


<img width="1702" alt="Screenshot 2024-07-10 at 11 24 18 PM" src="https://github.com/facebook/rocksdb/assets/43054535/e522aa42-ced7-4dec-a16e-e90447e9d02a">



<img width="1701" alt="Screenshot 2024-07-10 at 11 24 28 PM" src="https://github.com/facebook/rocksdb/assets/43054535/8e14e5b7-a211-4959-bc11-5d4086fb6941">


<img width="1702" alt="Screenshot 2024-07-10 at 11 24 40 PM" src="https://github.com/facebook/rocksdb/assets/43054535/26c0092f-939c-4601-ba2b-55f71fcec416">


<img width="1702" alt="Screenshot 2024-07-10 at 11 24 56 PM" src="https://github.com/facebook/rocksdb/assets/43054535/86a65e79-cafc-4f52-bf6f-ea7dfc9db0e1">

<img width="1705" alt="Screenshot 2024-07-10 at 11 25 20 PM" src="https://github.com/facebook/rocksdb/assets/43054535/6c6bad47-7d80-46a9-baa4-5669006be4d8">

<img width="1706" alt="Screenshot 2024-07-10 at 11 25 28 PM" src="https://github.com/facebook/rocksdb/assets/43054535/35af9228-83d2-484c-82e6-7bee37cf9509">


At this point, i'm confused on what really is the cause, I don't see compaction related writes/reads that match every single cpu spike. 

Do you know what other metrics I should look at or have any theories?

**Comment by ajkr** [comment]
Maybe memtable flush? From the "Memory Usage of All Mem Tables" chart we can infer flush is happening to reduce the memory, even though "Number of Running Flushes" is always zero. Maybe the query for running flush count did not capture points when it was nonzero.

"Number of SST Files" also changes outside the time compaction is said to be running, so there could be hidden compactions happening too.

**Comment by zaidoon1** [comment]
> Maybe the query for running flush count did not capture points when it was nonzero.

This makes sense. I collect rocksdb metrics every 1 minute. This is not great to capture operations that run infrequently/very quickly.  I'll update things from my end to run every 5 seconds or so to get a better picture.


Also now that you mentioned memtable flush, I'm pretty much running default rocksdb settings right now but I do have the following configured:

```
opts.set_write_buffer_size(256 * 1024 * 1024);
opts.set_max_write_buffer_number(4);
```

This maybe causing us to build large amount of data in memory so when flushing, we flush a big amount of data all at once?


Also while we are on this topic, something that didn't make sense to me is the metric:

<img width="819" alt="Screenshot 2024-07-12 at 11 01 39 PM" src="https://github.com/user-attachments/assets/a9f676c4-b8e0-4013-9f68-72747d8df676">

shouldn't we be building up more data in memory before flushing the memtables given my configuration above?


Here is the option file as well for reference:

[OPTIONS-000007.txt](https://github.com/user-attachments/files/16200705/OPTIONS-000007.txt)

**Comment by zaidoon1** [comment]
oh I did think of something just now, every few hours, I do create a checkpoint to allow some background service to crawl and clean up the db (delete orphaned indexes). 

@ajkr would the metrics:
```
/// Bytes read/written while creating backups
BackupReadBytes("rocksdb.backup.read.bytes"),
BackupWriteBytes("rocksdb.backup.write.bytes"),
```

track checkpoints?

**Comment by zaidoon1** [comment]
> Maybe memtable flush? From the "Memory Usage of All Mem Tables" chart we can infer flush is happening to reduce the memory, even though "Number of Running Flushes" is always zero. Maybe the query for running flush count did not capture points when it was nonzero.


I can confirm it was the memtable flush that is actually causing the cpu spikes. This is because I set max total wal size to 15MB as I was having issues with rocksdb taking a long time to start up after a restart due to wal replay. I've solved this by flushing cfs before shutdown so that when rocksdb starts up again, it doesn't have to replay a big WAL.

**Comment by zaidoon1** [comment]
I'm going to close this issue as it's not related to compaction but I most likely will create a separate issue about how to make memtable flush less "noticeable" cpu usage wise.
