### ISSUE TITLE
can restore rocksdb when using?

### ISSUE THREAD

**Issue by xieqing287227** [facebook/rocksdb#1256]
app is using rocksdb /tmp/rocksdb and created a backup to /tmp/rocksdb/backup
can we run another application to restore the db from /tmp/rocksdb/backup?

**Comment by xieqing287227** [comment]
or can the first app spawn a thread to restore from /tmp/rocksdb/backup when main thread using db?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
