### ISSUE TITLE
delay_write_rate?

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1260]
I can not find API to set `delay_write_rate` in RocksJava? Is it not supported?

**Comment by adamretter** [comment]
@xh931076284 I assume you mean`DBOptions::delayed_write_rate`? If so then, no that does not yet seem to be in the Java API, but if you need it, it would be very simple to add it.

**Comment by xh931076284** [comment]
Yes.We had test the performance of rocksdb and rocksdbjava,and found the significant difference between the two,so,I want to try to find the reason.But so far,We have not found where is the time to spend in calling rocksdbjava? Can you help me?

**Comment by xh931076284** [comment]
@adamretter I have added a setDelayedWriteRate function to java api, and it works well . Thank you.

**Comment by adamretter** [comment]
@xh931076284 Will you send a PR for that?

**Comment by xh931076284** [comment]
What is PR?

**Comment by adamretter** [comment]
@xh931076284 A Pull Request. i.e. if you have made those changes locally to RocksJava, would you consider contributing them back to the project?

**Comment by xh931076284** [comment]
@adamretter Yes, it's my honor.

**Comment by adamretter** [comment]
@xh931076284 Probably start by reading this - https://help.github.com/articles/using-pull-requests/

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
