### ISSUE TITLE
c bindings: missing abi to set IgnoreSnapshots to true for compaction filter

### ISSUE THREAD

**Issue by BusyJay** [facebook/rocksdb#1262]
Currently c bindings only has ABI to create compaction filter with IgnoreSnapshots being false by default. And there is no way to change this value.

IgnoreSnapshots will be useful when snapshot is used very frequently and the consistent view can be ensured by the application even calling the filter on keys written before the snapshot.

**Comment by siddontang** [comment]
@siying 

can we add a `ignore_snapshots` function pointer field like name or filter?

**Comment by siying** [comment]
@siddontang definitely. You are more than welcome to do that.

**Comment by siddontang** [comment]
Hi @siying 
Maybe we should add an argument for rocksdb_compactionfilter_create function, but I worry about the compatibility issue, or should we use another new function?
