### ISSUE TITLE
`make db_bench` failed: No rule to make target 'monitoring/statistics.h', needed by 'tools/simulated_hybrid_file_system.o'.  Stop.

### ISSUE THREAD

**Issue by eval-exec** [facebook/rocksdb#12663]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Expect `make db_bench` succcess
### Actual behavior
```bash
❯ make db_bench
$DEBUG_LEVEL is 1, $LIB_MODE is shared
Makefile:185: Warning: Compiling in debug mode. Don't use the resulting binary in production
make: *** No rule to make target 'monitoring/statistics.h', needed by 'tools/simulated_hybrid_file_system.o'.  Stop.

```

### Steps to reproduce the behavior
On latest main branch commit:`2eb404de1`
execute `make db_bench`

**Comment by hx235** [comment]
Can you do make clean first and see if it succeeds?
