### ISSUE TITLE
[Question] If checkpoint using hardlink, does it mean the after checkpoint created, write will be visible to created one?

### ISSUE THREAD

**Issue by gftea** [facebook/rocksdb#12693]
As I understand, in the same file system, checkpoint use hardlink for checkpointing, which means sharing same file content.
So if creating a checkpoint, then later writes to db, whether new writes will visible when reading the previous created checkpoint?

**Comment by cbi42** [comment]
New writes won't be available. SST files are immutable after creation and new writes will be persisted into a new SST file.

**Comment by ajkr** [comment]
We also hardlink inactive WALs, though those don't receive new writes either as they are inactive. Mutable files (active WAL, MANIFEST) are not hardlinked.
