### ISSUE TITLE
Rocksdb fails to compile on x86 musl

### ISSUE THREAD

**Issue by Kladki** [facebook/rocksdb#12725]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Rocksdb compiles.

### Actual behavior
Fails to compile, with [the following error](https://gitlab.alpinelinux.org/Kladky/aports/-/jobs/1408180#L247). With [this patch](https://gitlab.alpinelinux.org/alpine/aports/-/commit/b3e3bf7a4410bd853069ec41de6bd2782b42d480) we managed to get the error down [to this](https://gitlab.alpinelinux.org/Kladky/aports/-/jobs/1408169#L451), but we are not sure how to proceed from there.

### Steps to reproduce the behavior
1. Try to compile Rocksdb on an x86 musl system
2. See error

**Comment by ajkr** [comment]
There was a related patch, but I couldn't accept it yet because there were a bunch of test failures: #12515

**Comment by rhubner** [comment]
Hello @Kladki,
Thank you for reporting this issue. To solve your problem, you need to compile RocksDB on modern CPUs for x32 target  with flag `PORTABLE=1`

Detail answer: 
RocksDB contains a lot of low-level optimisation with vector instructions. Most of this instruction doesn't work in 32bit mode. Unfortunatelly for example `__BMI2__` flag is setup even when you are compiling RocksDB for x86(32bit) target.

For example `_bzhi_u64` [(declaration)](https://github.com/gcc-mirror/gcc/blob/3dedfad5a1edb14169a138492e486ee691387a53/gcc/config/i386/bmi2intrin.h#L62).  As you can see few lines up, there is macro which enable `_bzhi_u64` only on 64bit systems. 

Radek

**Comment by rhubner** [comment]
Hello @Kladki,

Thank for quick response. I'm little confused with your build system. I can see that you use cmake to generate build configuration for ninja build. But it doesn't look like the ninja build is the one used for final compilation. It looks to me you are using our make file.  Also if I check the build log you provided, I can still [see](https://gitlab.alpinelinux.org/Kladky/aports/-/jobs/1408180#L224) the `-m=native` in `Cflags` flags.

In you PR, I don't understand why did you deleted `cmake --build build` [link](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/62513/diffs?commit_id=7545f9c053ea2816960b4e38030639c47bf094fd#cda118dd7d6b5cfef62690fdc80b1563d5a3628f_40_41)

I don't think you need the patch for `util/math.h` either. You just need to tell build system to compile with `PORTABLE=1` on x86 architectures. 

Radek
