### ISSUE TITLE
what's the catch for avoid_unnecessary_blocking_io

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12724]
I just discovered `avoid_unnecessary_blocking_io` and after reading the wiki https://github.com/facebook/rocksdb/wiki/IO#avoid-blocking-io as well as the code comments: https://github.com/facebook/rocksdb/blob/v9.2.1/include/rocksdb/options.h#L1316-L1322 It sounds like a win. However, it's not default on, why not? Is there a "catch"/caveats here?

**Comment by ajkr** [comment]
The main catch I can think of would be a problem when the high-pri thread pool is contended. Sending purges there could delay purge itself resulting in increased space/memory usage, or delay the other work that  happens in the high-pri pool (memtable flushes). I doubt this would be a problem most of the time.

Using `SstFileManager` can move the actual deletion work to a dedicated thread. That could let you avoid adding I/O heavy work to the high-pri pool.

**Comment by zaidoon1** [comment]
makes sense, thank you!
