### ISSUE TITLE
memtable_prefix_bloom_ratio vs SST bloom filters

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#12745]
For a workload that is read heavy and most lookups (over 99%) are for keys that don't exist. Is there any benefit in enabling memtable_prefix_bloom_ratio if SST bloom filters are already enabled? Is it expected that I see an improvement?

**Comment by ajkr** [comment]
SST bloom filter typically has more obvious improvements by saving I/Os. Memtable filter may help with CPU efficiency only. You could try it, or if the memtable lookup CPU is low enough already, it might not be worthwhile to optimize.

**Comment by zaidoon1** [comment]
got it, thank you! I'll keep this ticket open for now and will report back on the results I see for posterity

**Comment by zaidoon1** [comment]
so enabled memtable prefix bloom ratio and as you suspected, there is not much of a difference. Thanks for the help!
