### ISSUE TITLE
Bug in Instagram page restoration

### ISSUE THREAD

**Issue by hoseirn** [facebook/rocksdb#12804]
One of my friend's Instagram accounts has been deactivated for over 3 months. I am an IT expert and have successfully restored several friends' accounts that were either disabled or hacked. However, all the recovery forms for disabled pages that I had saved are now inactive! Please guide me on how to restore my friend's Instagram account. When I log into their account, a page with no links is displayed, and it shows the following dialogue:

---

**You submitted an appeal**
It usually takes us just over a day to review your information. Check back here.
Your account is not visible to people on Instagram, and you can't use it.

**What happens next?**
We'll take another look at your account.
If we find your account does follow our Community Guidelines, you'll be able to use Instagram again.
If we find your account doesn't follow our Community Guidelines, it will be permanently disabled and you won't be able to appeal again.

---

Please advise on how to proceed with restoring my friend's Instagram account.
The forms I previously used but are now inactive are:

1. https://help.instagram.com/contact/1652567838289083 
2. https://help.instagram.com/contact/396169787183059 
3. https://help.instagram.com/contact/1784471218363829 
4. https://help.instagram.com/contact/606967319425038

**Comment by hx235** [comment]
Not relevant
