### ISSUE TITLE
The uninitialized variable bug in StderrLogger

### ISSUE THREAD

**Issue by wqshr12345** [facebook/rocksdb#12837]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
 
The constructor is called without initializing log_prefix_len, leading to subsequent out-of-memory (OOM) issues.
 
<img width="641" alt="image" src="https://github.com/facebook/rocksdb/assets/43242755/c2937b40-c24d-4420-8537-cf0454bb3503">
<img width="521" alt="image" src="https://github.com/facebook/rocksdb/assets/43242755/4c2d32dd-cc67-4a2e-b218-98d344502f7a">

**Comment by zaidoon1** [comment]
@wqshr12345 can you create a pr with a fix?

**Comment by wqshr12345** [comment]
@zaidoon1 Hello, I have created a simple PR—https://github.com/facebook/rocksdb/pull/12839.
