### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [facebook/rocksdb#12845]
File:
\java\rocksjni\portal.h line 2708
 
Code:
if (map == nullptr) {
      return nullptr;
    }

    if (map == nullptr) { // <-- identical
      return nullptr;
    }

**Comment by rhubner** [comment]
Hello @maddin200,

Thank you for reporting this issue. Can you please explain more what is the problem? I don't see the reason why `map` can't be `nullptr`.

Radek

**Comment by maddin200** [comment]
I think it is the same code twice, so the second statement will be never reached.

**Comment by rhubner** [comment]
Hello @maddin200, 

If the answer was enough, can you please close the issue? 

Radek
