### ISSUE TITLE
Compactions during Backup/Checkpoint not honoring DisableFileDeletions() ... missing file errors result.

### ISSUE THREAD

**Issue by matthewvon** [facebook/rocksdb#12849]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Backup and Checkpoint calls to DisableFileDeletions() is honored.  A compaction executing during Backup or Checkpoint should not impact the file set.

### Actual behavior
SstFileManager calls DeleteScheduler.DeleteFile() which has no code checking DBImpl::IsFileDeletionEnabled().  And DeleteScheduler.DeleteFile() might also rename the file.

Backup and Checkpoint can start background compactions due to flushing buffers.  The compaction's files can be created, compacted to another level, and deleted all within the Backup / Compaction.

### Steps to reproduce the behavior
Have data pending in write buffer.  Have enough level 0 files that next flush will cause a compaction.  Start backup with log flush.

**Comment by matthewvon** [comment]
My proposed solution is to add 2 API calls to SstFileManager and DeleteScheduler that parallel 
- DBImpl::DisableFileDeletions()
- DBImpl::EnableFileDeletions()

The DBImpl routines will call the parallel routines in SstFileManager.  SstFileManager (actually SstFileManagerImpl) will do nothing but call same routine on DeleteScheduler.  DeleteScheduler will only track a simple bool state.  Also, DeleteScheduler will NOT rename file to "*.trash".  The rename can also break Backup / Checkpoint if file name was captured already.

DeleteScheduler::EnableFileDeletions() will also kick the background thread (starting one if necessary).

**Comment by matthewvon** [comment]
Also considering changing `std::queue<FileAndDir> queue_;` to an std::map<std::string, std::string> just so that the same file name does not add repeatedly if deletes disable for a long time (like 112Gig backing up over Internet to AWS S3 bucket).

**Comment by matthewvon** [comment]
Work in progress is here (no tests to prove it works or not):
https://github.com/stardog-union/rocksdb/pull/53

**Comment by jowlyzhang** [comment]
Hello, just want to understand the issue better. From the original description: "Backup and Checkpoint can start background compactions due to flushing buffers. The compaction's files can be created, compacted to another level, and deleted all within the Backup / Compaction.", 

This says it's compaction that delete the file even though file deletions are disabled. 

All compaction job's file deletion go through this path to discover obsolete files after it finishes https://github.com/facebook/rocksdb/blob/6870cc1187c12458b3c5b4d2ba2f4ac22d5b0049/db/db_impl/db_impl_files.cc#L116-L123, which should honor the file deletion disabled setting.

So if a compaction job finishes after the file deletions are already disabled, it's not likely it can get past this and continue to delete files. I'm not sure flushing and compaction initiated by the backup itself can achieve that because they should all start and finish after file deletions are disabled. 

Is this issue surfaced when you try to backup and get some error, what error did you get?

**Comment by matthewvon** [comment]
I am closing this issue.  My first analysis was proven incorrect.  The customer that is impacted has an older version of our code which shipped with rocksdb 6.20.3.  The customer is a financial entity which is extremely slow to release any log files.  Finally got something useful yesterday and discovered the truth.  

Scenario:  eight manual compactions due to nightly automation when the same automation initiates a backup (substitute "manual compactions" for the term "optimize/optimization" below):

Research notes:

- matthewRange.png shows “File Deletions Enabled” for the first time at 30:22.941369.  Then there are eight more “File Deletions Enabled” messages within two seconds.  The subsequent eight messages do NOT have a paired “File Deletions Disabled”.  And if there had been an equivalent number of “File Deletions Disabled”, all but the last “File Deletions Enabled” would have been a different error message. (see db/db_impl/db_impl_files.cc)
- the only explanation for the “File Deletions …” sequence is that EnableFileDeletions() was called with its “force” parameter set to true.  In that scenario, the first call sets the counter of pending enable calls to zero AND triggers a clean up of dead files.
- The first EnableFileDeletions() is called on thread 2ae453b4d700.  And that thread immediate purges the 340270.sst file that backup expects to find.
- The only place that calls EnableFileDeletions() with “force” set to true is ResumeImpl() which is only called by RecoverFromBGError().
- We know that database optimization was running at the same time.

My theory of the moment is that optimization encountered a “recoverable error”.  Most like the error was out of disk space.

There are comments in more recent rocksdb release notes that they removed the “force” option from EnableFileDeletions().  Maybe they have seen similar badness?

My recommendation is that we NOT implement my previously proposed changes to rocksdb.  But that we do patch our version to not call EnableFileDeletions() from ResumeImpl() with “force” set to true.
