### ISSUE TITLE
We want to add a single sst file to a DB, but failed due to the too tight restriction.

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1288]
There  is a restriction on the SST files ingested into a DB, is that the key ranges in the sst files can not overlap  with each other or existing/deleted keys in the DB, why? we want to write s single sst file and than 
add it to an existing DB, but failed due to the restriction. Could you tell us  what about  the restriction you consider? And what can I do to add sst filea to DB if the keys ranges overlap with the the files in the DB?

**Comment by IslamAbdelRahman** [comment]
@xh931076284, I will be working in the following weeks on removing this restriction, will update this issue when we have the updated AddFile().

**Comment by xh931076284** [comment]
@IslamAbdelRahman Could you tell us about the role  the restriction play in DB, or the reason to do this?

**Comment by IslamAbdelRahman** [comment]
@xh931076284, there are multiple reasons but
1st reason is that if you have (K1 => V1) in the memtable and then ingest a file with (K1 => V2) in level-0.
on the read path, RocksDB will first check the memtable and find the key and return immediately reporting that the value for K1 is V1, even thought we just ingested a file with (K1 => V2).

another reason is that the file generated by SstFileWriter will have sequence number 0 (that mean that we are ingesting data in the past) which will cause conflicts with L0 files as well similar to the conflicts that could happen in the first scenario.

**Comment by xh931076284** [comment]
@IslamAbdelRahman Ok, thank you!

**Comment by VladRodionov** [comment]
> 1st reason is that if you have (K1 => V1) in the memtable and then ingest a file with (K1 => V2) in level-0.
on the read path, RocksDB will first check the memtable and find the key and return immediately reporting that the value for K1 is V1, even thought we just ingested a file with (K1 => V2).

another reason is that the file generated by SstFileWriter will have sequence number 0 (that mean that we are ingesting data in the past) which will cause conflicts with L0 files as well similar to the conflicts that could happen in the first scenario.

All these are not the issues with FIFO compaction style. Correct? When can we expect the new AddFile w/o restrictions? Lets say, for FIFO compaction?

**Comment by IslamAbdelRahman** [comment]
This commit should remove all the restrictions
https://github.com/facebook/rocksdb/commit/869ae5d7868d7d48dd55b7be02a23581101ed69a

Please give it a try and tell us if you have any feedback

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
