### ISSUE TITLE
segmentation fault in RocksDB version 4.9

### ISSUE THREAD

**Issue by TaecMike** [facebook/rocksdb#1292]
I am running into segmentation fault with the following parameters:

===== Benchmark =====
Start filluniquerandom at Mon Aug 22 11:37:00 PDT 2016
Loading 1048576 unique keys randomly into database...
./db_bench --db=/rocksdb/db/ --num_levels=6 --key_size=20 --value_size=800 --block_size=4096 --cache_size=17179869184 --cache_numshardbits=6 --compression_type=snappy --compression_ratio=0.5 --hard_rate_limit=2 --rate_limit_delay_max_milliseconds=1000000 --write_buffer_size=134217728 --max_write_buffer_number=2 --target_file_size_base=134217728 --max_bytes_for_level_base=1073741824 --sync=0 --disable_data_sync=1 --verify_checksum=1 --delete_obsolete_files_period_micros=62914560 --max_grandparent_overlap_factor=10 --statistics=1 --stats_per_interval=1 --stats_interval=1048576 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --num_multi_db=8 --rate_limiter_bytes_per_sec=157286400 --open_files=20480 --level0_file_num_compaction_trigger=8 --level0_slowdown_writes_trigger=16 --level0_stop_writes_trigger=24 --max_background_compactions=16 --max_background_flushes=16 --benchmarks=filluniquerandom --use_existing_db=0 --num=1048576 --threads=1 2>&1 | tee /rocksdb/output/benchmark_filluniquerandom.log
RocksDB:    version 4.9
Date:       Mon Aug 22 11:37:12 2016
CPU:        8 \* Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
CPUCache:   8192 KB
2016/08/22-11:38:55  ... thread 0: (1048576,1048576) ops and (323053.1,323053.1) ops/second in (3.245832,3.245832) seconds

I have attached the output log for reference as well.

[segmentationfault.txt](https://github.com/facebook/rocksdb/files/431016/segmentationfault.txt)

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
