### ISSUE TITLE
How to get the middle-key of a sst file?

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1293]
If We want to split a big sst file into two smaller sst files according to the middle-key, What can we do?
Can we travel a specified Block directly？

**Comment by IslamAbdelRahman** [comment]
Hi @xh931076284, Can you please clarify more what are you trying to achieve ?

It's not possible to split an SST file into 2 SST files without re-generating the smaller SST files by reading the original SST file.

**Comment by xh931076284** [comment]
@IslamAbdelRahman Yes.Frist, we want to lookup and read the middle-key of a single sst file; second, we want to read the original SST file , and write the key range from smallest key to middle-key  to a re-generating SST file; and write the key range from middle-key to largest key to another re-generating SST file.

**Comment by siying** [comment]
Feel free to add a function in block_based_table_reader to return you the key.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
