### ISSUE TITLE
What's going on with the latest release? (SupplyChainAttackPoC for Meta BB)

### ISSUE THREAD

**Issue by theolivenbaum** [facebook/rocksdb#12962]
The latest release ([9.5.2](https://github.com/facebook/rocksdb/releases/tag/v9.5.2)) is marked as "SupplyChainAttackPoC for Meta BB" - could anyone from Meta please elaborate on what's going on?

All I could find is this post on oss-security: https://www.openwall.com/lists/oss-security/2024/08/22/2, but some official note would be great to explain if this is just a mistake or an actual security issue.

**Comment by hx235** [comment]
Hi - we are investigating why the titled got changed

**Comment by theolivenbaum** [comment]
@hx235 anything we should be worried about? Do I need to retract the latest release of our rocksdb wrapper?

**Comment by anand1976** [comment]
We've determined that the release title change was part of an effort sponsored by Meta to identify security vulnerabilities. This was not due to a malicious user.

**Comment by ericpruitt** [comment]
Are any details going to be made available to the public?

**Comment by andreasstieger** [comment]
Not only the title got changed - the content did.

**Comment by adamretter** [comment]
@andreasstieger can you describe where the content was changed please?

**Comment by andreasstieger** [comment]
From the archive pages I see the short commit for this tag changed from d1826fb to a7e70f9.

https://web.archive.org/web/20240821151922/https://github.com/facebook/rocksdb/releases/tag/v9.5.2

https://web.archive.org/web/20240822053615/https://github.com/facebook/rocksdb/releases/tag/v9.5.2

**Comment by jaykorean** [comment]
The commit change in the release tag was something that the release manager did internally, not from an external user.

Regarding the title change done due to a security vulnerability, we completed an internal verification and confirmed that there have been no bad or unintended changes injected into 9.5.2. We mitigated the issue by disabling the self-hosted run and down-scoping the `GITHUB_TOKEN` accesses used for the workflows.

We will put together all of the details and communicate this out to the public via our communication channels.

**Comment by andreasstieger** [comment]
How many ways are there to not say that this project force-pushed a publicly visible tag?

**Comment by hx235** [comment]
> How many ways are there to not say that this project force-pushed a publicly visible tag?

Force-pushing to a publicly visible tag is not a good way to correct the mistake originally made in the tag (e.g, pointing to the wrong commit). We will avoid doing that in the future. Thanks!

**Comment by equinox** [comment]
> We will put together all of the details and communicate this out to the public via our communication channels.

Hi there, could you please link said public communications here? I seemed to have missed it. Thanks!

**Comment by hx235** [comment]
> > We will put together all of the details and communicate this out to the public via our communication channels.
> 
> Hi there, could you please link said public communications here? I seemed to have missed it. Thanks!

Hi - the public communication is still pending and not yet set out

**Comment by jaykorean** [comment]
FYI - https://rocksdb.org/blog/2025/02/07/mitigated-bug-update.html
