### ISSUE TITLE
mac running RocksDB error thread "thread 13 "Java. Lang. UnsatisfiedLinkError: cannot load library: / var/folders / 9/4 zgd37yd6ws4qcyhzvdmn7b40000gn/T/z librocksdbjni72531095764446538 96.jnilib

### ISSUE THREAD

**Issue by jh248** [facebook/rocksdb#12982]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Run RocksDB as normal
### Actual behavior
Report an error：Exception in thread "Thread-13" java.lang.UnsatisfiedLinkError: Can't load library: /var/folders/9z/4zgd37yd6ws4qcyhzvdmn7b40000gn/T/librocksdbjni7253109576444653896.jnilib
### Steps to reproduce the behavior
        
        <dependency>
            <groupId>com.ververica</groupId>
            <artifactId>frocksdbjni</artifactId>
            <version>5.17.2-ververica-2.1</version>
            <scope>provided</scope>
        </dependency>
        use by maven，but it can‘t running,and I couldn't find a solution

**Comment by rhubner** [comment]
Hello @jh248 ,

thank you for reaching our community. Unfortunately I can't help you much with this problem as it's not a official RocksDBJava build. I suggest you to contact community of  [frocksdb](https://github.com/ververica/frocksdb) as it's their fork of RocksDB and I don't know what king of modification they are doing.

My bet is that you initialize RocksDB on controller node, and then you want to use it on computation node. As I mention on #12961, in _MapReduce_ style distributed computing systems, you need to pay attention which code is used where and sometimes you need to reinitialize certain structures on computation node. Also pay proper attention to class-path.

Radek
