### ISSUE TITLE
rocksdb high cpu usage due to LRU cache contention?

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#13081]
We can see a strong correlation between increasing the number of block cache HITs and the amount of cpu used by rocksdb: 
 
<img width="1712" alt="Screenshot 2024-10-18 at 12 59 33 AM" src="https://github.com/user-attachments/assets/cc62fb50-9037-4d45-bdfc-b0e4acb2cb5b">

<img width="1716" alt="Screenshot 2024-10-18 at 2 02 55 AM" src="https://github.com/user-attachments/assets/8ba02f2b-0469-475f-806b-da96ad77345d">

<img width="1721" alt="Screenshot 2024-10-18 at 1 05 22 AM" src="https://github.com/user-attachments/assets/df057c11-36b3-405f-81fa-457dfbac134c">

<img width="1713" alt="Screenshot 2024-10-18 at 1 42 35 AM" src="https://github.com/user-attachments/assets/c9c2855c-4d13-4157-8163-05501ba61583">

Is this expected behaviour? And is there a fix for this? Is switching to hyper clock cache the only way to truly fix this?

**Comment by mdcallag** [comment]
The big win comes from using hyper clock.

Smaller improvements might be possible from using more shards in the LRU block cache assuming that your problem is a hot shard rather than a hot block.

**Comment by zaidoon1** [comment]
got it, that's good to know! I've started rolling out the change to hyper clock cache. I'll keep this issue open for now and will post a before/after

**Comment by zaidoon1** [comment]
After rolling out the change to hyper clock cache. After adding 2x the load compared to LRU cache, I see half the cpu usage compared to LRU cache:

<img width="555" alt="Screenshot 2024-10-30 at 2 03 33 AM" src="https://github.com/user-attachments/assets/04bb8770-512e-4b3c-bb71-01000493d1ca">
