### ISSUE TITLE
compaction not running or running very slowly when entire db is deleted?

### ISSUE THREAD

**Issue by zaidoon1** [facebook/rocksdb#13120]
so for my service, there are times when something happens that causes pretty much the entire db to be deleted using individual delete requests. I'm aware that sending individual delete requests to delete the entire db (instead of a range delete for example) will fill the db with tombstones and pretty much degrade the performance of rocksdb severely as we can see below. What I don't understand is why does it take days for compaction to run/finish compacting all of the tombstones away. As we can see there is not much activity and compaction is not running, I've seen this issue happen in the past and it took a few days for rocksdb to recover/go back to normal after an event like this (deleting pretty much the entire db)

<img width="1708" alt="Screenshot 2024-11-06 at 1 41 02 PM" src="https://github.com/user-attachments/assets/a2dbb974-05af-4934-848d-ff9282aca9c1">
<img width="1704" alt="Screenshot 2024-11-06 at 1 39 40 PM" src="https://github.com/user-attachments/assets/4ad9304f-3657-486a-8ef1-8aae3ef1a624">
<img width="1725" alt="Screenshot 2024-11-06 at 1 39 15 PM" src="https://github.com/user-attachments/assets/96e13649-4857-4087-ba74-81913ccd42c8">
<img width="1704" alt="Screenshot 2024-11-06 at 1 38 30 PM" src="https://github.com/user-attachments/assets/ef012fb3-7338-4fec-8e42-a565fae24049">

rocksdb config:

[OPTIONS-000007.txt](https://github.com/user-attachments/files/17651744/OPTIONS-000007.txt)

I'm running latest rocksdb version, pretty much default settings, however, I do have db ttl set to a few hours which is more confusing since the docs say:
```
Leveled: Non-bottom-level files with all keys older than TTL will go through the compaction process. This usually happens in a cascading way so that those entries will be compacted to bottommost level/file. The feature is used to remove stale entries that have been deleted or updated from the file system.
```

My understanding is that after the entire db is deleted, once the ttl is up, compaction would run and compact the entire db to get rocksdb back to a normal state.

**Comment by cbi42** [comment]
>  there is not much activity and compaction is not running

After the entire DB is deleted, is there any more writes to the DB? RocksDB doesn't have a timer-based trigger to check if there's eligible compactions. Usually it tries to schedule a compaction after a flush/compaction. I suspect that there's nothing to trigger compaction to be scheduled. Can you do a manual compaction after you issue all the deletions?

**Comment by zaidoon1** [comment]
> After the entire DB is deleted, is there any more writes to the DB? 

there is writes, but my workload is extremely read heavy. The other problem is that the service started using 10 cpus and that is the max number of cpus allocated for the service using cgroups so it started being throttled and made things worse. 

A few questions:

1. would CompactOnDeletionCollector help here? 
2. we can see the number of sst files go down, this means compaction did happen right? Note that this metric is powered by me getting the number of "live files"
3. I feel like running manual compaction wouldn't work here if the moment the db size went down after all the deletes, rocksdb started using all cpus, started getting throttled and pretty much deadlocked?

**Comment by cbi42** [comment]
> a simple db restart fixed the issue and everything went back to normal

Do you hold snapshot for a very long time? Restart will clear the snapshots. Tombstone can be in the last level files if there's a snapshot preventing them to be dropped. 

> would CompactOnDeletionCollector help here?

If the problem is that files with many tombstones are not being compacted down to the last level, then yes. It won't help if there's snapshot keeping tombstones ailve.

> I feel like running manual compaction wouldn't work here if the moment the db size went down after all the deletes, rocksdb started using all cpus, started getting throttled and pretty much deadlocked?

The hope is to compact away the tombstones with manual compaction so that iterators won't use this much CPU.

**Comment by zaidoon1** [comment]
> Do you hold snapshot for a very long time? 

my delete workflow is as follows:

1. create a checkpoint
2. have some separate service/process open the checkpoint (read only mode)
3. iterate over all the kvs, check if they are stale, if they are stale, send a delete request to the service that has rocksdb open in read/write mode and move to the next kv.

Is checkpoint and snapshot the same thing here?

**Comment by zaidoon1** [comment]
>  Manual compaction should help.

got it, thank you!
