### ISSUE TITLE
There is a problem of function UnSchedule() in env_hdfs.h. No-return value would lead to compilation failed.

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1312]

**Comment by IslamAbdelRahman** [comment]
Thanks @xh931076284 for reporting this issue, are you interested in sending a pull request to fix it ?

**Comment by xh931076284** [comment]
@IslamAbdelRahman Okey.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
