### ISSUE TITLE
Can I open multiple CF in different DB with one same rocksdb_option_t ?

### ISSUE THREAD

**Issue by 979357361** [facebook/rocksdb#13133]
Hi guys, 
Good day! I have encountered some problem with using RocksDB in C APIs

I wants to open a series of DBs, each DB has one default CF and multiple data CFs, all data CF stores same type of data and is differnt from the default CF, so the rocksdb_option_t for default CF and other CF are not the same, tuning a customed rocksdb_option_t for each CF is tanglesome, especially when many other options are assigned to rocksdb_option_t in different ways, like point directly copy, shared point trans or copy and trans, this makes it complicated to release these structures in the right places. 
Since all data CFs use the same option tuning, is it OK to open all CFs with one same rocksdb_option_t? 
For <rocksdb_create_column_families>, it sames OK,
How about <rocksdb_open_column_families> ?

I also run into another question which makes me puzzled. I have set a CompactFilterFactory for data CF rocksdb_option_t, when I call many manul compacts by API <rocksdb_compact_range_cf_opt> with two NULL key range and default compact_opt, it is supported to compact the entire CF data and filter out all staled data, however, only part of staled data are filter out, could this be due to multiple threads initiating compact concurrently? the thread safe of compact filter can be ensured.

thanks for your time! any help is wlecome

**Comment by cbi42** [comment]
Using the same option should be fine. Options like block cache will be be shared across CFs. 

Manual compaction with default options and compaction filter should compact all keys. Can you check if all keys went through compaction filter?

**Comment by 979357361** [comment]
> Using the same option should be fine. Options like block cache will be be shared across CFs.
Yes, using the same option to open multi CF is OK

> Manual compaction with default options and compaction filter should compact all keys. Can you check if all keys went through compaction filter?
All valid key (except deletion marker) in compaction associated SST will pass through the filter
