### ISSUE TITLE
Tags for releases 4.10, 4.10.1, 4.11, 4.11.1

### ISSUE THREAD

**Issue by bdarnell** [facebook/rocksdb#1318]
`HISTORY.md` refers to releases 4.10 and 4.11, and branches for those releases exist (`4.*.fb`, and those branches contain patch releases 4.10.1 and 4.11.1), but the latest release tag is `rocksdb-4.9`. Please create tags for these releases (in accordance with your [release methodology](https://github.com/facebook/rocksdb/wiki/RocksDB-Release-Methodology) unless those releases are incomplete or withdrawn for some reason.

**Comment by yiwu-arbug** [comment]
We are going for 4.11.2 and skip 4.10.x, 4.11.0 and 4.11.1 due to multiple issues.
