### ISSUE TITLE
Memory leak in iterator when using thread sleep

### ISSUE THREAD

**Issue by keivanmoazami** [facebook/rocksdb#13204]
### Issue Description:

I am using RocksDB version 9.7.2 and have configured the database with the following options, while writing data with Blob storage enabled. During iteration over records with an iterator, if I use a thread sleep inside the loop, the memory used by the Blob is not properly released.
Specifically, when I manually delete the memory `delete[] it->value().data()`, sometimes leading to crash.

### Steps to Reproduce:
1. Configure RocksDB with the bellow options (including Blob storage).
2. Write data to the database using Blob.
3. Use an iterator to read the data.
4. Introduce thread sleep within the iteration loop.
5. Observe that the memory used by the Blob is not released after the iteration.

### Expected Behavior:
The Blob memory should be released properly after the iteration loop, even if thread sleep is used within the loop.

### Actual Behavior:
Memory used by the Blob is not released, resulting in a memory leak.

### Environment:
RocksDB version: 9.7.2
Operating System: Windows 10
Compiler: MSVC

```
rocksdb::ReadOptions read_options;
read_options.total_order_seek = true;
read_options.auto_prefix_mode = true;
read_options.adaptive_readahead = true;
read_options.readahead_size = 2 * 1024 * 1024; // 2 MB
read_options.async_io = true;
read_options.iterate_lower_bound = &lower_bound_key;
read_options.iterate_upper_bound = &upper_bound_key;

std::unique_ptr<rocksdb::Iterator> it(mDb->NewIterator(read_options));
for (it->Seek(key); it->Valid(); it->Next())
{
        if (it->key().compare(upper_bound_key) >= 0)
	       break;	  
	std::this_thread::sleep_for(std::chrono::milliseconds(30));
}
```

Db options
```
mDbOptions.create_if_missing = true;
mDbOptions.create_missing_column_families = true;
mDbOptions.skip_stats_update_on_db_open = true;
mDbOptions.skip_checking_sst_file_sizes_on_db_open = true;

mDbOptions.allow_concurrent_memtable_write = true;
mDbOptions.enable_write_thread_adaptive_yield = true;
mDbOptions.paranoid_checks = false;
mDbOptions.avoid_unnecessary_blocking_io = true;

auto cpuCores = getCpuCores();
mDbOptions.max_background_jobs = cpuCores;
mDbOptions.env->SetBackgroundThreads(static_cast<int>(round(cpuCores * 0.75)), rocksdb::Env::Priority::HIGH);
mDbOptions.env->SetBackgroundThreads(static_cast<int>(round(cpuCores * 0.25)), rocksdb::Env::Priority::LOW);

mDbOptions.prefix_extractor.reset(rocksdb::NewFixedPrefixTransform(sizeof(int)));

//cache
rocksdb::BlockBasedTableOptions table_options;
size_t block_cache_size = 256 * 1024 * 1024; 
std::shared_ptr<rocksdb::Cache> block_cache = rocksdb::NewLRUCache(block_cache_size);
table_options.block_cache = block_cache;
table_options.no_block_cache = false; 
table_options.block_size = 256 * 1024;
table_options.cache_index_and_filter_blocks = true;
table_options.filter_policy.reset(rocksdb::NewBloomFilterPolicy(10, false));
mDbOptions.table_factory.reset(rocksdb::NewBlockBasedTableFactory(table_options));

size_t blob_cache_size = 256 * 1024 * 1024; 
mDbOptions.blob_cache = rocksdb::NewLRUCache(blob_cache_size);

mDbOptions.compaction_readahead_size = 2 * 1024 * 1024; 
mDbOptions.disable_auto_compactions = false;
mDbOptions.level0_file_num_compaction_trigger = 20; 
mDbOptions.level0_slowdown_writes_trigger = 80;
mDbOptions.level0_stop_writes_trigger = 120;

mDbOptions.max_write_buffer_number = 4;
mDbOptions.min_write_buffer_number_to_merge = 1;
mDbOptions.write_buffer_size = 10 * 1024 * 1024; 
mDbOptions.compression = rocksdb::kNoCompression;

mDbOptions.target_file_size_base = 64 * 1024 * 1024; 
mDbOptions.max_bytes_for_level_base = 256 * 1024 * 1024; 
mDbOptions.level_compaction_dynamic_level_bytes = true;

mDbOptions.enable_blob_files = true;
mDbOptions.blob_file_size = 10 * 1024 * 1024; 
mDbOptions.blob_compression_type = rocksdb::kNoCompression;
mDbOptions.min_blob_size = 1024; // 1 KB
mDbOptions.enable_blob_garbage_collection = false;

mWriteOptions.disableWAL = true;
mWriteOptions.sync = false;
mWriteOptions.memtable_insert_hint_per_batch = true;
```

Any insights or suggestions for proper memory management in this scenario would be greatly appreciated.

**Comment by jowlyzhang** [comment]
It's not clear what this "memory leak" means, what is the symptom of memory leaking in your example?

This `delete[] it->value().data()` is a detrimental operation, it's expected that it could lead to crash. See documentation for `Iterator::value()`: https://github.com/facebook/rocksdb/blob/b339d089ed4a7ac7a8ed4ab7d57cccdc0602f0ed/include/rocksdb/iterator.h#L40
Specifically: The underlying storage for the returned slice is valid only until the next modification of the iterator. it->value() is a slice backed by memory managed by RocksDB, user are not supposed to manipulate that memory.

**Comment by keivanmoazami** [comment]
The following images show heap profiling results. When `this_thread::sleep_for` is not used, no memory leak is observed. However, when use `this_thread::sleep_for` for 30 seconds, 8.7 MB memory leak detected. you can see detail of heap profiling in images.

no mem leak:
![no_mem_leak](https://github.com/user-attachments/assets/c7d9e491-fd0c-452d-8f8c-e139cf9e94a3)

mem leak:
![mem_leak_0](https://github.com/user-attachments/assets/3d828819-8478-43eb-a27d-fe2413ecb3f2)
![mem_leak_1](https://github.com/user-attachments/assets/7006b16a-bf7d-4583-8f3b-d4ed3ecd3eb8)
![mem_leak_2](https://github.com/user-attachments/assets/08d4c877-e16f-4ee0-8c81-faea0f3cfaf2)

**Comment by keivanmoazami** [comment]
Excuse me. You are correct; this is not a memory leak. when use thread sleep it cause cache value in blob cache.
