### ISSUE TITLE
A problem about the first get() call?

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1332]
When use java api get() function to make random access to DB, the time spent firstly is much longer than follow?

**Comment by adamretter** [comment]
Is this specific to the Java API, or does the same go for the C++ API?

**Comment by xh931076284** [comment]
@adamretter Just for java api.

**Comment by siying** [comment]
How much longer? Milliseconds? Or longer than a second?

**Comment by xh931076284** [comment]
First get() spend 1.7 seconds with 2.7 billion entries in db and 40 milliseconds with no data db.

**Comment by siying** [comment]
What's your value of max_open_files, cache_index_and_filter_blocks setting, and compaction style?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
