### ISSUE TITLE
Can I change the ColumnFamily (e.g. CreateColumnFamily or DropColumnFamily or DestroyColumnFamilyHandle) without reopening the DB?

### ISSUE THREAD

**Issue by susejiangnan** [facebook/rocksdb#1347]

**Comment by siying** [comment]
No, you can't.

**Comment by siying** [comment]
I don't understand the question. CreateColumnFamily() and DropColumnFamily() take effective immediately. You don't need to reopen the DB.

**Comment by sagar0** [comment]
I hope your issue is resolved.
Closing this issue as it is more than an year old. Please feel free to reopen if you think this issue is still relevant and/or has been closed in error.
