### ISSUE TITLE
A problem of manual compact。

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1355]
Fristly write all data(8.7G) into level-0 with options max_bytes_for_level_base=1*SizeUnit.GB, than call CompactRange() to compact , after compaction, I find that all data are compacted into level-1 and the size is 8.4G far greater than the option  max_bytes_for_level_base. Why is this?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
