### ISSUE TITLE
Tried to delete a non-existing file /hdfsdata/2/dinnne/VTVTGrapth//001226.sst, type=2 --IO error: no such file or diectory.

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1365]
Write large data into DB with auto compaction , level0_slowdown_writes_trigger=1<<30, level0_stop_writes_trigger<<30, the error occurred in the LOG. 
I can not check out the reason, Could you tell the possible reason?

**Comment by siying** [comment]
It may be a false alert. Did you see any read/write failure?

**Comment by xh931076284** [comment]
No, have no much more info.  level0_slowdown_writes_trigger=1<<30, level0_stop_writes_trigger<<30 , will the two options cause data lost?

**Comment by siying** [comment]
No these options are fine.




On Thu, Sep 29, 2016 at 8:07 PM -0700, "xh931076284" <notifications@github.com<mailto:notifications@github.com>> wrote:


No, have no much more info. level0_slowdown_writes_trigger=1<<30, level0_stop_writes_trigger<<30 , will the two options cause data lost?

-

**Comment by xh931076284** [comment]
@siying , You means these options have no problem?
Is it possbile that the write rate is too high so that the the number of SST file in the level-0 is too much to compact to level-1, and so some SST file are deleted?
Note: it works with  multithreading using JAVA API.

**Comment by xh931076284** [comment]
"Generated table #1498 : 5336001 keys, 141496205 bytes" is the log info means the data in memtable will be flushed into a SST file named 001498.sst?
"Delete /hdfsdata/2/dinner/VTVTGraph22compact/001498.sst type=2 #1498 -- ok" : is this log info means that the sst file is deleted in the ending of a compaction related to the 001498.sst? 

"  Tried to delete a non-existing file /hdfsdata/2/dinner/VTVTGraph22compact/001498.sst type=2 #1498 -- IO error: no such file of directory":  is the log info means that it tried to delete a SST file has been already deleted resulating in a IO error?

Detail info is recorded in follower three pictures;
![img_20160930_133434](https://cloud.githubusercontent.com/assets/19407588/18981772/ca7ed234-8713-11e6-9aef-c32b235e94be.jpg)
![img_20160930_133509](https://cloud.githubusercontent.com/assets/19407588/18981773/ca81ab12-8713-11e6-9ca6-8502c4f0e26c.jpg)
![img_20160930_133555](https://cloud.githubusercontent.com/assets/19407588/18981774/cab409ae-8713-11e6-99d5-86def2ed1dfd.jpg)

**Comment by xh931076284** [comment]
@siying I find out the reason.   I set options.delete_obsolete_files_period_micros = 300000000,and db->EnableFileDeletions(true).

**Comment by siying** [comment]
These teo settings are common. We have never seen any problem.





On Thu, Sep 29, 2016 at 10:14 PM -0700, "xh931076284" <notifications@github.com<mailto:notifications@github.com>> wrote:


@siying<https://github.com/siying> , You means these options have no problem?
Is it possbile that the write rate is too high so that the the number of SST file in the level-0 is too much to compact to level-1, and so some SST file are deleted?
Note: it works with multithreading using JAVA API.

-

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
