### ISSUE TITLE
Considering SPDK support for bypassing the CPU for disk access

### ISSUE THREAD

**Issue by codri** [facebook/rocksdb#1374]
Hi,

I wonder if it would be possible to add SPDK(https://software.intel.com/en-us/articles/introduction-to-the-storage-performance-development-kit-spdk) support when running RocksDB instances inside VMs. As far as I understand this can improve Disk Access performance access a lot, when running from inside VMs.

Based on this comment[https://news.ycombinator.com/item?id=12023092](not entirely scientific) seems like there could be some big benefits for using SPDK.

Does RocksDB depend on the filesystem? How hard would it be to support this?

Overall it looks like this could be a low hanging performance fruit. I'm completely new to RocksDB and don't know the internal structure, I may be talking crazy.

The referenced comment:

> Submitting and completing a 4k I/O using SPDK is about 7 times more CPU efficient than the equivalent operation with libaio, which is opening a raw block device with O_DIRECT.
> Said another way, on a recent Xeon CPU you can expect to drive somewhere around 3 million 4k I/O per second with SPDK per core. With libaio, you can do about 450,000 per core off the top of my head.
> SPDK has no locks or cross core communication required, so it scales linearly with additional CPU cores. Blk-mq in the kernel also helped the kernel scaling problem significantly, but I'm not sure if it is perfectly linear yet.
> Most applications need something like a filesystem to function - there is no denying that. Using SPDK requires applications to implement at least the minimal set of features in the filesystem that their application needs. Many databases and storage services already bypass the filesystem or use the filesystem as a block allocator only, so it is not a big leap from there to SPDK.

**Comment by Liuchang0812** [comment]
it seems useful. Rocksdb uses file system abstraction which is Env class, It could be supported by impl a new Env.

**Comment by siying** [comment]
RocksDB currently requires a file system abstraction. If someone can implement a file-like wrapper to SPDK, RocksDB can support it.

If someone sends a pull request, we will be happy to review and merge it.

**Comment by codri** [comment]
I'm afraid I cannot be working currently on this, don't have that much free time.

Though, I've investigated this domain a little bit more. It looks that for this to work in a public cloud of some kind, the hypervisor disk drivers should allow this. And I think all of them now don't. This could probably still be handy for bypassing the OS inside the VM. Though again, not sure how much benefit could bring.

Not sure, if the benefits are worth the effort because of this. Also, not sure how many rocksdb deployments are running on bear metal servers, for this to be handy.

So please, do whatever you consider best with this issue. I'll keep it in mind if I'm going to have some free time for hacking.

**Comment by davecohn** [comment]
Work on a RocksDB integration is targeted for the 17.03 release of the SPDK (http://www.spdk.io/roadmap/).

**Comment by Liuchang0812** [comment]
Ceph BlueStore has implemented a BlueFSEnv based on SPDK/NVMe

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
