### ISSUE TITLE
Will different compression strategy affect query performance?

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1376]
Level0 -1: use kNoCompression , level2-6: use kSnappyCompression , these options should improve the flush speed and decrease disk space amplification. Will it decrease the query speed?

**Comment by IslamAbdelRahman** [comment]
If a read needs to access a data block, it will first need to read the block / decompress the block / put the block in the block cache

This means that the read will consume more CPU because of decompression cost, but if the read found the block in the block cache, it will be there uncompressed

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
