### ISSUE TITLE
Wiki: default value of target_file_size_base

### ISSUE THREAD

**Issue by ghost** [facebook/rocksdb#1400]
The [wiki page](https://github.com/facebook/rocksdb/wiki/Basic-Operations) mistakenly states that default target_file_size_base is 2MB.

It seems this should be 64MB instead (according to include/rocksdb/options.h).

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
