### ISSUE TITLE
Wiki: difference between SingleDelete and Delete is not clear

### ISSUE THREAD

**Issue by ghost** [facebook/rocksdb#1406]
This sentence from [SingleDelete](https://github.com/facebook/rocksdb/wiki/Single-Delete) documentation is not clear:

> In contrast to the conventional Delete() operation, the deletion entry is removed along with the value when the two are lined up in a compaction. 

For me, as a newcomer to RocksDB, it doesn't describe the difference from `Delete`, because it matches my initial expectation of what a `Delete` would do.

Only after reading the highlighted sentence ([from here](https://github.com/facebook/rocksdb/wiki/Delete-A-Range-Of-Keys)) I could understand the difference:

> if you never overwrite existing keys, you can try to use DB::SingleDelete() instead of Delete() to kill tombstones sooner. _Tombstones will be dropped after it meets the original keys, rather than compacted to the last level._

Please, make the difference clear in `SingleDelete` documentation by specifying the behaviour of `Delete` too, so that new users can get correct understanding.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
