### ISSUE TITLE
receive SIGSEGV inside VersionSet::LogAndApply call

### ISSUE THREAD

**Issue by yijiem** [facebook/rocksdb#1412]
Hi team. We are using rocksdb 4.1.0 and we hit a segfault inside VersionSet::LogAndApply when we CreateColumnFamily, here is the function call stack and logs:

**call stack:**
#0  0x00007ff4fc0e4444 in rocksdb::VersionSet::LogAndApply(rocksdb::ColumnFamilyData*, rocksdb::MutableCFOptions const&, rocksdb::VersionEdit*, rocksdb::InstrumentedMutex*, rock

sdb::Directory*, bool, rocksdb::ColumnFamilyOptions const*) () from /usr/lib/librocksdb.so.4.1
#1  0x00007ff4fc07a81e in rocksdb::DBImpl::CreateColumnFamily(rocksdb::ColumnFamilyOptions const&, std::string const&, rocksdb::ColumnFamilyHandle**) ()
   from /usr/lib/librocksdb.so.4.1

**logs:**

Oct 20 04:31:29 localhost lrse[2836]: [kvs.INFO] (2836) Created column family [ConsistentSnapshot] (ID 2)
Oct 20 04:31:29 localhost lrse[2836]: [kvs.ERR] (2836) MANIFEST write: IO error: /rfs/lrse/meta/info/meta/MANIFEST-000004: Device or resource busy
Oct 20 04:31:29 localhost lrse[2836]: [kvs.INFO] (2836) ManifestContains: checking /rfs/lrse/meta/info/meta/MANIFEST-000004
Oct 20 04:31:29 localhost lrse[2836]: [kvs.INFO] (2836) ManifestContains: IO error: /rfs/lrse/meta/info/meta/MANIFEST-000004: Software caused connection abort
Oct 20 04:31:29 localhost lrse[2836]: [kvs.INFO] (2836) ManifestContains: is unable to reopen the manifest file  /rfs/lrse/meta/info/meta/MANIFEST-000004
Oct 20 04:31:29 localhost pm[1695]: [pm.ERR]: Output from lrse: /opt/rbt/bin/lrse (pid 2836) received signal 11 (SIGSEGV) dumping core

We would like to exit gracefully in this case. Thanks!

**Comment by anip30** [comment]
We also hit the same issue? Should we upgrade the rocksdb?

**Comment by yiwu-arbug** [comment]
@anip30 Looks like it is a real IO error and rocksdb should return error status. Is it a crash for you or are you getting an error returned? If it is crash inside rocksdb, are you able to get a stack trace?

**Comment by anip30** [comment]
Hey. I think application got an exception but rocksdb crashed inside. We can't get rocksdb stack trace.

I just have 

#0  0x00007fba5be45444 in rocksdb::VersionSet::LogAndApply(rocksdb::ColumnFamilyData*, rocksdb::MutableCFOptions const&, rocksdb::VersionEdit*, rocksdb::InstrumentedMutex*, rocksdb::Directory*, bool, rocksdb::ColumnFamilyOptions const*) () from /usr/lib/librocksdb.so.4.1
No symbol table info available.
#1  0x00007fba5bddb81e in rocksdb::DBImpl::CreateColumnFamily(rocksdb::ColumnFamilyOptions const&, std::string const&, rocksdb::ColumnFamilyHandle**) () from /usr/lib/librocksdb.so.4.1

everything else is optimized out.

**Comment by miasantreble** [comment]
@yijiem @anip30 
I think this commit might have fixed the problem https://github.com/facebook/rocksdb/commit/34704d5c7bfb1dbcfeb4986bc8eb42f1f78481a0#diff-6822534358e613a82db5431a19a6036f
Can you please try that and let us know?
If not, can you please share the LOG file or more detailed stacktrace? Thanks!
