### ISSUE TITLE
What can I do to compiler a jar with window?

### ISSUE THREAD

**Issue by xh931076284** [facebook/rocksdb#1418]

**Comment by adamretter** [comment]
@xh931076284 If you mean with Microsoft Windows binaries, then please see the CMakeLists.txt file for instructions. The current release on Maven Central has Windows binaries available if that is easier.

**Comment by xh931076284** [comment]
@adamretter Yes, I do as the CMakeLists.txt described, and get the dll, I try to compile a jar used maven but failed.  Can you tell me to compile  a jar in windows.

**Comment by adamretter** [comment]
@xh931076284 Did you add `-DJNI=1` to your cmake build?

**Comment by xh931076284** [comment]
@adamretter Yes, I did.
