### ISSUE TITLE
binary distributions

### ISSUE THREAD

**Issue by phraktle** [facebook/rocksdb#144]
Hi,

It would be great to have a binary distribution available, that would include multi-platform builds (linux, macosx) and bindings (java, etc).

Earlier, I have made an attempt on an automated build VM environment setup using Vagrant / Ansible: https://github.com/phraktle/rocksdb-build – this might serve as useful starting point, but I don't have time to maintain this.

Thanks,
  Viktor

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by Gadreel** [comment]
The package in Maven Central is perfect for this:

http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rocksdbjni%22

But a bit out of date.  Up vote :)

**Comment by vjon** [comment]
@igorcanadi, it looks like this was fixed quite a while ago as per your Review link, and can be closed.

**Comment by adamretter** [comment]
The RocksJava builds are published to Maven Central - http://search.maven.org/#search%7Cga%7C1%7Crocksdbjni
We just published the 4.13.2 build on Maven Central last night

**Comment by partylana** [comment]
wheres the binary?
