### ISSUE TITLE
freebsd build error with cmake 

### ISSUE THREAD

**Issue by ananclub** [facebook/rocksdb#1440]
FreeBSD 11.0 with cmake clang 3.8.0

```
/home/anan/projects/rocksdb/util/env_test.cc:1067:22: error: use of undeclared identifier 'O_DIRECT'
```

**Comment by adamretter** [comment]
Did you mean `cmake`? Have you tried `gmake`? Can you tell me the full command line you are running?

**Comment by ananclub** [comment]
%cmake ../../rocksdb/
%make

gmake has the same error.

maybe should use O_SYNC on Freebsd?

**Comment by yuslepukhin** [comment]
This is a compile time error

**Comment by carpecarp** [comment]
I have the same problem on freebsd 10.3.

You can fix by moving #include <fcntl.h> out of the #ifdef OS_LINUX block. 

env_test.cc needs fcntl.h in freebsd as well as linux in order to get a definition of O_DIRECT.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
