### ISSUE TITLE
When TransactionDB/OptimisticTransactionDB add to the Java API?

### ISSUE THREAD

**Issue by zhouquan03** [facebook/rocksdb#1443]
Hi, I see adamretter has implement the API, see: https://github.com/adamretter/rocksdb/blob/java-transactions/java/src/main/java/org/rocksdb/OptimisticTransactionDB.java

When you merge into the repository and release new version?

**Comment by yiwu-arbug** [comment]
This is the PR: #1298

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
