### ISSUE TITLE
non intuitive behavior of DBWithTTL:get for staled data

### ISSUE THREAD

**Issue by ummae** [facebook/rocksdb#1445]
I think It would be better to check expiration before return it.

We could check the timestamp of data on `SanityCheckTimestamp`. and.. honestly I don't know why it doesn't now
https://github.com/facebook/rocksdb/blob/master/utilities/ttl/db_ttl_impl.cc#L192

**Comment by yiwu-arbug** [comment]
@igorcanadi Hi! Do you mind take a look? Thanks!

**Comment by igorcanadi** [comment]
I agree. @ummae would you mind sending a quick PR?

**Comment by ummae** [comment]
@igorcanadi okay, I will.

**Comment by ummae** [comment]
@igorcanadi I found [DateTieredDB](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/utilities/date_tiered_db.h) that seems work like what I expected to `DBWithTTL`. It need timestamp to put for keys, though. I am not sure still we need this logic on `DBWithTTL`. What do you think?

**Comment by igorcanadi** [comment]
DateTieredDB is a different concept from DBWithTTL internally. It uses column families to drop old data instead of compaction. If that suits your need, that's fine. If not, I think a patch that fixes DBWithTTL behavior will be accepted.

**Comment by ummae** [comment]
@igorcanadi okay, there are two problems on the PR, please let me know what do you think about it

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
