### ISSUE TITLE
Build error in AWS EC2

### ISSUE THREAD

**Issue by yuchi518** [facebook/rocksdb#145]
Hi,

I set up an amazon ec2 with image 'Amazon Linux AMI 2014.03.1' for x64.
I download RocksDB 3.0 branch code.

And follow the install.md, section Linux - CentOS to install dependent lib.
I can do 'make'  or 'make shared_lib' and output an .so and .a file correctly.
But I try to build jni, 'make rocksdbjava', there are some errors occur.

g++ -g -Wall -Werror -I. -I./include -std=c++11  -DROCKSDB_PLATFORM_POSIX  -DOS_LINUX -fno-builtin-memcmp -DROCKSDB_ATOMIC_PRESENT -DROCKSDB_FALLOCATE_PRESENT -DSNAPPY -DGFLAGS=google -DZLIB -DBZIP2   -DHAVE_JEMALLOC -fPIC -DNDEBUG -O2 -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -Woverloaded-virtual -c table/block_hash_index.cc -o table/block_hash_index.o 
g++: internal compiler error: deleted (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See http://bugzilla.redhat.com/bugzilla for instructions.
make[1]: **\* [db/db_impl_debug.o] Error 4
make[1]: **\* Waiting for unfinished jobs....

I had try gcc47-c++ and gcc48-c++, same issue.

I don't think this is rocksdb issue, but I have no ideal what happen.

Do you have any comment?

Thanks.

**Comment by hixel** [comment]
"make clean" before helped me
