### ISSUE TITLE
Way to add je_ prefix to malloc calls?

### ISSUE THREAD

**Issue by alexreg** [facebook/rocksdb#1462]
The C++ new operator implicitly uses `malloc` of course, but here I want to link to a version of jemalloc that has the `je_` prefixes (complex long-winded reason). Is this possible?

**Comment by nevets963** [comment]
@alexreg You can either use LD_PRELOAD technique or link against jemalloc and this will 'replace' default malloc implementation. More info here: https://github.com/jemalloc/jemalloc/wiki/Getting-Started

Issue #1442 shows that RocksDb can be linked with jemalloc or tcmalloc already at build time, but they're proposing some changes.

**Comment by alexreg** [comment]
Yeah, the problem is the jemalloc prefix though (`je_`). If jemalloc is compiled with that, the build complains about missing symbols.

**Comment by nevets963** [comment]
Note:

**Comment by nevets963** [comment]
Note from https://github.com/jemalloc/jemalloc/wiki/Getting-Started:

Link jemalloc into the application at build time, **but use it as a generic malloc implementation**:
cc app.c -o app -L${JEMALLOC_PATH}/lib -Wl,-rpath,${JEMALLOC_PATH}/lib -ljemalloc

Compile jemalloc with an API prefix (see the --with-jemalloc-prefix configure option), link with jemalloc at build time as above, but use jemalloc distinctly from the system allocator.

**Comment by siying** [comment]
Sorry I don't know how we can help. Can I close the issue?

**Comment by grooverdan** [comment]
I can't see an easy way either.

I did ask the jemalloc folks for exposing the prefix which would make it easier. https://github.com/jemalloc/jemalloc/issues/723 

Then, or alternately through some other mechanism, the operator ::new family of operators could be overwritten like in 16e03882054fa8c947ca84f30b87e1cd3e929597

**Comment by alexreg** [comment]
@grooverdan Yeah... sadly no reply on that issue. I bumped it, just in case. Any thoughts, given the above, @siying?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
