### ISSUE TITLE
Iterator with lower bound

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#1471]
When there are a lot of tombstone keys, we will benefit a lot from iterator's upper bound when run forward scan operation. Is there any plan to support lower bound for iterator, it is useful when doing reverse scan.

**Comment by siying** [comment]
We don't have such a plan. But you are welcome to implement something. Maybe reuse the same option.

**Comment by zhangjinpeng1987** [comment]
OK

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
