### ISSUE TITLE
test failure: util/env_test.c incorrect assumption about page size

### ISSUE THREAD

**Issue by grooverdan** [facebook/rocksdb#1498]
The page size util/env_test.c:NewAligned is a fixed 4K size rather than using sysconf(_SC_PAGESIZE) to determine this like the rockdb does.

This results in an assertion during make check on non-4K page size Linux kernels.

**Comment by siying** [comment]
Is passing this test in your platform important for you?

**Comment by grooverdan** [comment]
yes. I'll get a patch written and submitted.

**Comment by grooverdan** [comment]
note to self: and util/io_posix.cc:NewAligned
