### ISSUE TITLE
Storing RocksDB in RAMdisk

### ISSUE THREAD

**Issue by vinhqdang** [facebook/rocksdb#1517]
Hello everyone,

Can RocksDB work on Ramdisk. Today I tried to store rocksdb in RAMdisk (8GB / Macbook Pro 2014 with 16GB RAM), and the program always crashes (segmentation fault).

I did not changed anything. Before, one line of code is:

``path += "/testdb/";``

and now it is:

``path += "/Volumes/ram_disk/testdb/";``

I tested my RAMdisk in command line, indeed I can read/write on that.

Can rocksdb work with ramdisk, or something is wrong with my programming?

Thank you very much,

**Comment by vinhqdang** [comment]
Here is the result of ``df -h .``

```
df -h .
Filesystem   Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk2  8.0Gi   27Mi  8.0Gi     1%       6 4294967273    0%   /Volumes/ram_disk
```

**Comment by vinhqdang** [comment]
Ramdisk is created by the command line:

```
diskutil erasevolume HFS+ 'ram_disk' `hdiutil attach -nomount ram://16777216`
```

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
