### ISSUE TITLE
universal compaction never use second dbpath

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#1524]
When using universal compaction and multiple dbpathes(two in my case, and on two different SSD), just first dbpath is used, when the first SSD is full(target_size was configured as half of available space), insertion always failed, and the second SSD is never used.

**Comment by rockeet** [comment]
This issue also reproduced on level based compaction.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
