### ISSUE TITLE
File is too large for PlainTableReader

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#1538]
I encountered an error: "File is too large for PlainTableReader!" when using universal compaction and table factory is PlainTableFactory, and target_file_size_mulitplier is 2, and level_num is 7.
Why PlainTableBuilder can build a table which can not be read?

**Comment by siying** [comment]
How many compaction threads do you use?

**Comment by rockeet** [comment]
@siying  base_background_compactions = 2;
         and max_background_compactions = 4;

**Comment by siying** [comment]
The maximum plain table size is 2GB. Please tune the options to make sure single SST file doesn't exceed the size.

**Comment by siying** [comment]
We usually use target_file_size_mulitplier =1, and hardly use other value.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
