### ISSUE TITLE
Rocks JNI does not dispose family handle

### ISSUE THREAD

**Issue by koldat** [facebook/rocksdb#1541]
Dropping family is just marking family as dropped internally. But files are deleted after handle is disposed. JNI leaks the pointer when user calls dropFamily.

**Comment by koldat** [comment]
@adamretter any feedback? The issue is that if one drops family, its files are not deleted, because RocksDB still tracks that reference.

**Comment by adamretter** [comment]
@koldat Is that expected behaviour, in the C++ API for DropColumnFamily I don't see any mention if it explicitly dropping files.

**Comment by koldat** [comment]
It does drop the files. Correct way is to explicitly close family handle after delete. That dereference shared pointers inside and native part does what it requires. Sorry I did not update issues with this finding. You can close the defect. Thanks Tomas
