### ISSUE TITLE
List of Patents

### ISSUE THREAD

**Issue by tmobi** [facebook/rocksdb#1543]
First of all, it's pretty cool that Facebook released RocksDB under a BSD license. It also comes with a patent grant, which, although [slightly](https://news.ycombinator.com/item?id=9356508) [controversial](https://news.ycombinator.com/item?id=9111849), seems to generally be received quite well - many thanks for that, too!

Having thought about it, I became a little curious which patents are actually related to RocksDB. After all, its underlying data structures are quite well-understood. I did a quick search on google patents, and also looked at some wikipedia pages (for example for LSM trees and bloom filters), but couldn't really find anything. Is there a list of patents that are related to RocksDB?

**Comment by SethTisue** [comment]
relevant: #2589 (license is now Apache)

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by siying** [comment]
Since you are asking a legal related question, you are unlikely to get an answer anyway:)
