### ISSUE TITLE
is it possible to build x86 windows version?

### ISSUE THREAD

**Issue by bsploit** [facebook/rocksdb#1563]
I want to use rocksdb in java application on x86 windows pc. is it possible or it will require too much changes?

**Comment by adamretter** [comment]
There are released artifacts for Windows on Maven. At the moment we only support 64bit windows, and you can build from that, see CMakeLists.txt.

If you want 32bit support, you would need to work on that, we have in general 32bit support including a Linux 32 bit build, but at the moment it is not supported for Windows.

**Comment by domenkozar** [comment]
There are `WIN32` conditionals now in CMakeLists, did anyone succeed to build it?

**Comment by sinowood** [comment]
I have successfully built and run Windows x86 version using VS 2015.
Just follow the steps in CMakeLists.txt, but for step 3 use the following cmake command instead.
`cmake -G "Visual Studio 14" -DFAIL_ON_WARNINGS=0 ..`

**Comment by Alexcei88** [comment]
Does it work successfully?

**Comment by sinowood** [comment]
Yes, x86 build works fine for me.

**Comment by xuy98** [comment]
Are you able to run all unit tests?
