### ISSUE TITLE
Memory use for rocksdb are growing and we got OOM.

### ISSUE THREAD

**Issue by xarnold** [facebook/rocksdb#1566]
Our java application open 12 db for writable mode and open serveral db for read only mode.
Each DB has following configuration.

max_backfground_compactions=1
block_cache=null
max_open_files=5000
block_size=4k
write_buffer_size=512mb
max_write_buffer_number=3
max_bytes_for_level_base=2048mb
target_file_size_base=512mb

Max Heap size for java application is 16gb.
After startup application, Memory usage for application is growing up to 42gb and we got OOM.
1. Anybody explain why such big memory used in application in spite of parameter ?
2. How can we limit memory usage for rocksdb ?

Thanks in advance.
Regards, Arnold.

**Comment by adamretter** [comment]
I don't believe this is explicitly linked to the Java API of RocksDB as it is really just a thin wrapper around RocksDB itself.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
