### ISSUE TITLE
rocksdb crashed at rocksdb::InternalStats::DumpCFStats

### ISSUE THREAD

**Issue by zyin** [facebook/rocksdb#1597]
Program terminated with signal 7, Bus error.
#0  rocksdb::InternalStats::DumpCFStats(std::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
    at /usr/include/c++/4.8.2/ext/atomicity.h:84
84      /usr/include/c++/4.8.2/ext/atomicity.h: No such file or directory.
        in /usr/include/c++/4.8.2/ext/atomicity.h
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.192.el6.x86_64
(gdb) bt
#0  rocksdb::InternalStats::DumpCFStats(std::basic_string<char, std::char_traits<char>, std::allocator<char> >*) ()
    at /usr/include/c++/4.8.2/ext/atomicity.h:84
#1  0x00000000004fd742 in rocksdb::DBImpl::MaybeDumpStats() () at ./include/rocksdb/slice.h:40
#2  0x000000000051f80d in rocksdb::DBImpl::BackgroundCallCompaction(void*) () at ./include/rocksdb/options.h:136
#3  0x00000000005c6d4f in rocksdb::ThreadPool::BGThread(unsigned long) () at util/threadpool.cc:224
#4  0x00000000005c6e33 in rocksdb::BGThreadWrapper(void*) () at util/threadpool.cc:253
#5  0x00000030a0207aa1 in ?? ()
#6  0x00007f575e765700 in ?? ()
#7  0x0000000000000000 in ?? ()

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
