### ISSUE TITLE
Error when building Git repository

### ISSUE THREAD

**Issue by v-vendetta** [facebook/rocksdb#1602]
Hi,

I am running Centos 6 and I encountered an error at 5% when building the Git repository. I have also installed successfully at the prerequisites. Any help is greatly appreciated!

>code as follows ```
git clone https://github.com/facebook/mysql-5.6.git
cd mysql-5.6
git submodule init
git submodule update
cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SSL=system \
-DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 \
-DENABLE_DTRACE=0 -DCMAKE_CXX_FLAGS="-march=native"
make -j8
```

[  0%] [  1%] [  1%] Built target regex
[  2%] Built target zlib
Built target vio
[  5%] Built target strings
Building CXX object sql/CMakeFiles/gen_lex_hash.dir/gen_lex_hash.cc.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [sql/CMakeFiles/gen_lex_hash.dir/gen_lex_hash.cc.o] Error 1
make[1]: *** [sql/CMakeFiles/gen_lex_hash.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target mysqlservices
Scanning dependencies of target semisync_slave_client
Scanning dependencies of target comp_sql
Scanning dependencies of target my_safe_process
[  5%] Built target INFO_SRC
[  5%] [  5%] [  5%] Built target INFO_BIN
[  5%] [  5%] [  5%] Building C object libservices/CMakeFiles/mysqlservices.dir/my_snprintf_service.c.o
Building C object libservices/CMakeFiles/mysqlservices.dir/thd_alloc_service.c.o
Building C object scripts/CMakeFiles/comp_sql.dir/comp_sql.c.o
[  5%] [  5%] [  5%] Built target abi_check
Building CXX object mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/safe_process.cc.o
Building C object libservices/CMakeFiles/mysqlservices.dir/thd_wait_service.c.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/safe_process.cc.o] Error 1
make[1]: *** [mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/all] Error 2
Building C object libservices/CMakeFiles/mysqlservices.dir/my_plugin_log_service.c.o
Building CXX object plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave_client.cc.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave_client.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  5%] [  5%] [  5%] [  5%] Building C object libservices/CMakeFiles/mysqlservices.dir/my_thread_scheduler_service.c.o
Building CXX object plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave.cc.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave.cc.o] Error 1
Building C object libservices/CMakeFiles/mysqlservices.dir/mysql_string_service.c.o
Building CXX object plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync.cc.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync.cc.o] Error 1
make[1]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/all] Error 2
Linking C static library libmysqlservices.a
Linking C executable comp_sql
[  5%] Built target mysqlservices
[  5%] Built target comp_sql
make: *** [all] Error 2

**Comment by Liuchang0812** [comment]
your gcc's version is too low, please execute following commands in your bash:

```bash
gcc --version
g++ --version
```

**Comment by v-vendetta** [comment]
Thanks for the quick response. Output as follows:

> [root@myrocksdb mysql-5.6]# gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@myrocksdb mysql-5.6]# g++ --version
g++ (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17)
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by adamretter** [comment]
@v-vendetta You need at least gcc 4.8.

**Comment by v-vendetta** [comment]
gcc is now version 4.8.2. but i am having error at 12% now....

`[ 12%] Building C object mysys/CMakeFiles/mysys.dir/my_alarm.c.o
[ 12%] Building C object mysys/CMakeFiles/mysys.dir/posix_timers.c.o
[ 12%] Building C object mysys/CMakeFiles/mysys.dir/my_largepage.c.o
[ 12%] Building C object mysys/CMakeFiles/mysys.dir/my_lockmem.c.o
Linking C static library libmysys.a
[ 12%] Built target mysys
make: *** [all] Error 2`

**Comment by Liuchang0812** [comment]
you are building MySQL, not rocksdb ?

**Comment by v-vendetta** [comment]
@Liuchang0812  rocksdb. I followed the instructions from this webpage.
http://myrocks.io/docs/getting-started/ 
There after I upgraded gcc to 4.8.2 from this webpage.
https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b

`sudo yum install cmake gcc-c++ bzip2-devel libaio-devel bison \
zlib-devel snappy-devel
sudo yum install gflags-devel readline-devel ncurses-devel \
openssl-devel lz4-devel gdb git
`

`git clone https://github.com/facebook/mysql-5.6.git
cd mysql-5.6
git submodule init
git submodule update
cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo -DWITH_SSL=system \
-DWITH_ZLIB=bundled -DMYSQL_MAINTAINER_MODE=0 -DENABLED_LOCAL_INFILE=1 \
-DENABLE_DTRACE=0 -DCMAKE_CXX_FLAGS="-march=native"
make -j8`

**Comment by Liuchang0812** [comment]
attach  more error log, please

**Comment by v-vendetta** [comment]
Sorry, I’m a newbie in this. How can I collect the error log? Its not in my /var/log/messages

 

Regards,

Timothy Lee

Systems Engineer | NetXcel Systems Pte Ltd

+65 6838 0259| timothylee@netxcel.com.sg | www.netxcel.com.sg

**Comment by davidmgkang** [comment]
@adamretter 

Hello, I have a same problem.
log is below.


```sh
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_alarm.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/posix_timers.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_largepage.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_lockmem.c.o
Linking C static library libmysys.a
[ 10%] Built target mysys
Scanning dependencies of target dbug
[ 10%] Building C object dbug/CMakeFiles/dbug.dir/dbug.c.o
Linking C static library libdbug.a
[ 10%] Built target dbug
Scanning dependencies of target mysys_ssl
[ 10%] Building CXX object mysys_ssl/CMakeFiles/mysys_ssl.dir/crypt_genhash_impl.cc.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [mysys_ssl/CMakeFiles/mysys_ssl.dir/crypt_genhash_impl.cc.o] Error 1
make[1]: *** [mysys_ssl/CMakeFiles/mysys_ssl.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by adamretter** [comment]
I am afraid I can't help with building MyRocks. I don't know of this is even the right place for such questions. @fosco @siying comments please...

**Comment by davidmgkang** [comment]
yeah also like this... 


```
[ 86%] Building CXX object sql/CMakeFiles/sql.dir/sql_audit.cc.o
[ 86%] Building CXX object sql/CMakeFiles/sql.dir/sql_base.cc.o
[ 86%] Building CXX object sql/CMakeFiles/sql.dir/sql_bootstrap.cc.o
[ 86%] Building CXX object sql/CMakeFiles/sql.dir/sql_cache.cc.o
[ 86%] Building CXX object sql/CMakeFiles/sql.dir/sql_class.cc.o
[ 86%] Building CXX object sql/CMakeFiles/sql.dir/shardedlocks.cc.o
[ 87%] Building CXX object sql/CMakeFiles/sql.dir/sql_connect.cc.o
make[2]: *** [sql/CMakeFiles/sql.dir/sql_yacc.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Linking CXX executable mysql_client_test
[ 87%] Built target mysql_client_test
Linking CXX executable ldb
Linking CXX executable mysql_ldb
Linking CXX executable sst_dump
[ 87%] Built target ldb
make[1]: *** [libmysqld/CMakeFiles/sql_embedded.dir/all] Error 2
[ 87%] Built target mysql_ldb
[ 87%] Built target sst_dump
make[1]: *** [sql/CMakeFiles/sql.dir/all] Error 2
make: *** [all] Error 2
```
