### ISSUE TITLE
Set prefix_extractor for rocksdb_readoptions_t

### ISSUE THREAD

**Issue by alexreg** [facebook/rocksdb#1605]
The C API doesn't seem to have a way to set the *prefix_extractor* for a `rocksdb_readoptions_t` object. Could we get this added please?

**Comment by yiwu-arbug** [comment]
ReadOptions don't have prefix_extractor. Options have it. And there is `rocksdb_options_set_prefix_extractor`.

**Comment by alexreg** [comment]
Sorry, I just meant the “prefix” field on ReadOptions. How does one perform a prefix seek using the C API then?

**Comment by yiwu-arbug** [comment]
Seems `ReadOptions.prefix` have been removed long ago and now all you need to set is `Options.prefix_extractor`.
https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes

**Comment by alexreg** [comment]
Thanks for the info.
