### ISSUE TITLE
Error when building Git repository

### ISSUE THREAD

**Issue by v-vendetta** [facebook/rocksdb#1608]
Error at 12% when building. gcc version is 4.8.2. Please help.

`[root@myrocksdb ~]# gcc --version
gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@myrocksdb ~]# g++ --version
g++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[root@myrocksdb ~]# gfortran --version
GNU Fortran (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.

GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING

[root@myrocksdb ~]# source /opt/rh/devtoolset-2/enable
[root@myrocksdb ~]# cd mysql-5.6
[root@myrocksdb mysql-5.6]# make -j8
[  1%] [  1%] [  1%] Built target zlib
[  2%] Built target regex
Built target vio
Building CXX object sql/CMakeFiles/gen_lex_hash.dir/gen_lex_hash.cc.o
[  5%] Built target strings
[  5%] Built target INFO_BIN
[  5%] [  5%] Built target mysqlservices
Built target comp_sql
[  5%] [  5%] [  5%] Building CXX object plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave_client.cc.o
Scanning dependencies of target GenFixPrivs
Built target INFO_SRC
Building CXX object plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave.cc.o
cc1plus: error: unrecognized command line option "-std=c++11"
[  5%] cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [sql/CMakeFiles/gen_lex_hash.dir/gen_lex_hash.cc.o] Error 1
make[1]: *** [sql/CMakeFiles/gen_lex_hash.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target mysys
make[2]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave_client.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  5%] cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync_slave.cc.o] Error 1
Building CXX object mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/safe_process.cc.o
[  5%] Building CXX object plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync.cc.o
Generating mysql_fix_privilege_tables_sql.c
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/safe_process.cc.o] Error 1
make[1]: *** [mysql-test/lib/My/SafeProcess/CMakeFiles/my_safe_process.dir/all] Error 2
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/semisync.cc.o] Error 1
make[1]: *** [plugin/semisync/CMakeFiles/semisync_slave_client.dir/all] Error 2
[  5%] Built target GenFixPrivs
[  5%] Built target abi_check
[  6%] [  6%] [  6%] [  6%] Building C object mysys/CMakeFiles/mysys.dir/charset.c.o
Building C object mysys/CMakeFiles/mysys.dir/array.c.o
[  6%] Building C object mysys/CMakeFiles/mysys.dir/charset-def.c.o
Building C object mysys/CMakeFiles/mysys.dir/checksum.c.o
[  6%] Building C object mysys/CMakeFiles/mysys.dir/errors.c.o
Building C object mysys/CMakeFiles/mysys.dir/hash.c.o
[  6%] [  6%] Building C object mysys/CMakeFiles/mysys.dir/list.c.o
Building C object mysys/CMakeFiles/mysys.dir/mf_cache.c.o
[  6%] Building C object mysys/CMakeFiles/mysys.dir/mf_dirname.c.o
[  6%] Building C object mysys/CMakeFiles/mysys.dir/mf_fn_ext.c.o
[  6%] [  6%] Building C object mysys/CMakeFiles/mysys.dir/mf_format.c.o
Building C object mysys/CMakeFiles/mysys.dir/mf_getdate.c.o
[  6%] [  6%] Building C object mysys/CMakeFiles/mysys.dir/mf_iocache.c.o
Building C object mysys/CMakeFiles/mysys.dir/mf_iocache2.c.o
[  6%] [  6%] Building C object mysys/CMakeFiles/mysys.dir/mf_keycache.c.o
Building C object mysys/CMakeFiles/mysys.dir/mf_keycaches.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_loadpath.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_pack.c.o
[  7%] [  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_path.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_qsort.c.o
Building C object mysys/CMakeFiles/mysys.dir/mf_qsort2.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_radix.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_same.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_sort.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_soundex.c.o
[  7%] [  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_arr_appstr.c.o
Building C object mysys/CMakeFiles/mysys.dir/mf_tempdir.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_tempfile.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_unixpath.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mf_wcomp.c.o
[  7%] Building C object mysys/CMakeFiles/mysys.dir/mulalloc.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_access.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_alloc.c.o
[  8%] [  8%] [  8%] Building C object mysys/CMakeFiles/mysys.dir/my_bit.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_bitmap.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_chsize.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_compress.c.o
[  8%] [  8%] Building C object mysys/CMakeFiles/mysys.dir/my_copy.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_create.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_delete.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_div.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_error.c.o
[  8%] [  8%] [  8%] Building C object mysys/CMakeFiles/mysys.dir/my_file.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_fopen.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_fstream.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_gethwaddr.c.o
[  8%] Building C object mysys/CMakeFiles/mysys.dir/my_getsystime.c.o
[  9%] Building C object mysys/CMakeFiles/mysys.dir/my_getwd.c.o
[  9%] [  9%] Building C object mysys/CMakeFiles/mysys.dir/my_compare.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_init.c.o
[  9%] [  9%] Building C object mysys/CMakeFiles/mysys.dir/my_lib.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_lock.c.o
[  9%] [  9%] Building C object mysys/CMakeFiles/mysys.dir/my_malloc.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_mess.c.o
[  9%] Building C object mysys/CMakeFiles/mysys.dir/my_mkdir.c.o
[  9%] Building C object mysys/CMakeFiles/mysys.dir/my_mmap.c.o
[  9%] [  9%] [  9%] Building C object mysys/CMakeFiles/mysys.dir/my_once.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_open.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_pread.c.o
[  9%] Building C object mysys/CMakeFiles/mysys.dir/my_pthread.c.o
[  9%] Building C object mysys/CMakeFiles/mysys.dir/my_quick.c.o
[  9%] [ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_read.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_redel.c.o
[ 10%] [ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_rename.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_seek.c.o
[ 10%] [ 10%] [ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_sleep.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_static.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_symlink.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_symlink2.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_sync.c.o
[ 10%] [ 10%] [ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_thr_init.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/my_write.c.o
Building C object mysys/CMakeFiles/mysys.dir/ptr_cmp.c.o
Building C object mysys/CMakeFiles/mysys.dir/queues.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/stacktrace.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/string.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/thr_alarm.c.o
[ 10%] Building C object mysys/CMakeFiles/mysys.dir/thr_lock.c.o
[ 11%] Building C object mysys/CMakeFiles/mysys.dir/thr_mutex.c.o
[ 11%] [ 11%] Building C object mysys/CMakeFiles/mysys.dir/thr_rwlock.c.o
Building C object mysys/CMakeFiles/mysys.dir/tree.c.o
[ 11%] [ 11%] Building C object mysys/CMakeFiles/mysys.dir/base64.c.o
Building C object mysys/CMakeFiles/mysys.dir/typelib.c.o
[ 11%] Building C object mysys/CMakeFiles/mysys.dir/my_memmem.c.o
[ 11%] Building C object mysys/CMakeFiles/mysys.dir/my_getpagesize.c.o
[ 11%] [ 11%] Building C object mysys/CMakeFiles/mysys.dir/lf_alloc-pin.c.o
Building C object mysys/CMakeFiles/mysys.dir/lf_dynarray.c.o
[ 11%] Building C object mysys/CMakeFiles/mysys.dir/lf_hash.c.o
[ 11%] [ 11%] Building C object mysys/CMakeFiles/mysys.dir/my_atomic.c.o
Building C object mysys/CMakeFiles/mysys.dir/my_getncpus.c.o
[ 11%] Building C object mysys/CMakeFiles/mysys.dir/my_rdtsc.c.o
[ 11%] Building C object mysys/CMakeFiles/mysys.dir/waiting_threads.c.o
[ 11%] Building C object mysys/CMakeFiles/mysys.dir/psi_noop.c.o
[ 12%] Building C object mysys/CMakeFiles/mysys.dir/my_alarm.c.o
[ 12%] Building C object mysys/CMakeFiles/mysys.dir/posix_timers.c.o
[ 12%] Building C object mysys/CMakeFiles/mysys.dir/my_largepage.c.o
[ 12%] Building C object mysys/CMakeFiles/mysys.dir/my_lockmem.c.o
Linking C static library libmysys.a
[ 12%] Built target mysys
make: *** [all] Error 2
`

**Comment by Vadius** [comment]
@v-vendetta, your issue looks like related to [MySQL](https://github.com/mysql/mysql-server), not to RocksDB.
And even for MySQL, you should show all version checks after `source /opt/rh/devtoolset-2/enable` because nobody knows which versions actually used after it.

**Comment by v-vendetta** [comment]
Thank you for your email. I am on National Service&nbsp;from 03/01/2017&nbsp;- 20/01/2017.

I may&nbsp;have limited access to my email, but will respond whenever I can.

For urgent matters, please call&nbsp;6838 0259&nbsp;or whatsapp me.

&nbsp;

Wishing all a Happy New Year &amp; Gong Xi Fa Cai!!!

&nbsp;

Regards,

Tim

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
