### ISSUE TITLE
wiki: unknown flag for Bulk Load of keys in Random Order

### ISSUE THREAD

**Issue by siddontang** [facebook/rocksdb#1610]
I follow the wiki guide using db_bench for https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks#test-1-bulk-load-of-keys-in-random-order , but meet following error:

```
ERROR: unknown command line flag 'max_grandparent_overlap_factor'
ERROR: unknown command line flag 'source_compaction_factor'
```

I think RocksDB doesn't have these flags now.

**Comment by siddontang** [comment]
Btw, for https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks#test-5-multi-threaded-read-and-single-threaded-write 

```
ERROR: unknown command line flag 'writes_per_second'
```

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
