### ISSUE TITLE
Prefix API Wiki incorrect. 

### ISSUE THREAD

**Issue by ipapapa** [facebook/rocksdb#1613]
The [Prefix seek API documentation](https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes) refers to the `read_options.total_order_seek = true` as `read_options.total_order_mode = true;` (difference in word `seek` vs `mode`). Does this need to be corrected?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
