### ISSUE TITLE
Examples run are failed with malloc_zone_unregister() on macOS Sierra

### ISSUE THREAD

**Issue by mgalushka** [facebook/rocksdb#1616]
Tried to build examples as per instructions, everything is built fine, but when starting all example binaries failed with same error:

`simple_example(31091,0x7fffd4fb03c0) malloc: *** malloc_zone_unregister() failed for 0x7fffd4fa6000
`

**Comment by mritun** [comment]
Possibly related to the following Jemalloc issue: https://github.com/jemalloc/jemalloc/issues/420

**Comment by mgalushka** [comment]
Upgrading to jemalloc 4.4 helped, thanks @mritun
