### ISSUE TITLE
Remove dependency of db/db_filesnapshot.cc on testharness.h

### ISSUE THREAD

**Issue by paramr** [facebook/rocksdb#1618]
While building prod code,  this causes dependency on gtest which is awkward.

**Comment by vjon** [comment]
This should be fixed by commit 4a17b47bb5a2cc09f95acb53ec565bccd171ee4e

Please test on your end and close this Issue if the fix works for you. Thanks!

**Comment by paramr** [comment]
Thanks for fixing.  Closing for now.  Will verify this fully when I get this changes from next release version of rocksdb.
