### ISSUE TITLE
Transactional database not exposed in c.cc

### ISSUE THREAD

**Issue by KasperJanssens** [facebook/rocksdb#1637]
Hello,

More of a question maybe, is there a reason why the transactional database and such are not exposed in the c-api? I would need foreign function bindings for that and I can of course start adding them myself, but I was wondering why they were not there yet in the first place? Looking at the wrong file?

Kasper

**Comment by yiwu-arbug** [comment]
Our C API usually don't keep up with latest changes. If you find something missing, feel free to add it and send a pull request.

**Comment by KasperJanssens** [comment]
Okay, will try to add the transactionality and provide a pull request.
