### ISSUE TITLE
compilation error: db/db_test.cc:131:18: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_FlushMemTable’

### ISSUE THREAD

**Issue by marcin-github** [facebook/rocksdb#1638]
rocksdb in version 4.11.2,

g++  -g -W -Wextra -Wall -Wsign-compare -Wshadow -Wno-unused-parameter -I. -I./include -std=c++11  -DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX  -DOS_LINUX -fno-builtin-memcmp -DROCKSDB_FALLOCATE_PRESENT -DSNAPPY -DGFLAGS=gflags -DZLIB -DBZIP2 -DROCKSDB_MALLOC_USABLE_SIZE -DROCKSDB_PTHREAD_ADAPTIVE_MUTEX -DROCKSDB_BACKTRACE -march=native   -isystem ./third-party/gtest-1.7.0/fused-src -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -DNDEBUG -Woverloaded-virtual -Wnon-virtual-dtor -Wno-missing-field-initializers -c db/db_test.cc -o db/db_test.o 
In file included from db/db_test.cc:27:0:
./db/db_test_util.h: In member function ‘virtual rocksdb::Status rocksdb::SpecialEnv::NewWritableFile(const string&, std::unique_ptr<rocksdb::WritableFile>*, const rocksdb::EnvOptions&)::SSTableFile::Close()’:
./db/db_test_util.h:236:16: warning: unused variable ‘preallocation_size’ [-Wunused-variable]
         size_t preallocation_size = preallocation_block_size();
                ^
In file included from ./util/testharness.h:12:0,
                 from ./table/mock_table.h:25,
                 from ./db/db_test_util.h:47,
                 from db/db_test.cc:27:
db/db_test.cc: In member function ‘virtual void rocksdb::DBTest_MockEnvTest_Test::TestBody()’:
db/db_test.cc:131:18: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_FlushMemTable’
   ASSERT_OK(dbi->TEST_FlushMemTable());
                  ^
db/db_test.cc:131:3: note: in expansion of macro ‘ASSERT_OK’
   ASSERT_OK(dbi->TEST_FlushMemTable());
   ^
db/db_test.cc: In member function ‘virtual void rocksdb::DBTest_MemEnvTest_Test::TestBody()’:
db/db_test.cc:179:18: error: ‘class rocksdb::DBImpl’ has no member named ‘TEST_FlushMemTable’
   ASSERT_OK(dbi->TEST_FlushMemTable());
 [...]

gcc version 5.4.0 (Gentoo 5.4.0 p1.0, pie-0.6.5)

**Comment by yiwu-arbug** [comment]
To compile the tests you need to remove `-DNDEBUG`.

**Comment by marcin-github** [comment]
Thank you for information.
