### ISSUE TITLE
Open Files limit ?

### ISSUE THREAD

**Issue by yuchi518** [facebook/rocksdb#164]
Hi,

I got an error message

org.rocksdb.RocksDBException: IO error: /Volumes/Backup/pbf/planet-140514/nodes/021806.log: Too many open files
    at org.rocksdb.RocksDB.put(Native Method)
    at org.rocksdb.RocksDB.put(RocksDB.java:139)

Does the max open files have any limits ?

I open rocksdb with following options:

options = new Options();
options.setCreateIfMissing(true);
options.setMaxOpenFiles(-1);
options.setAllowMmapReads(false);
options.setAllowMmapWrites(false);
options.setMaxWriteBufferNumber(4);

When error occurs, the db folder contains about 9620 sst files and folder size is about 19GB.
The version of RocksDB is 3.0.

Does any one have any suggestion?

Thanks.

**Comment by linas** [comment]
FWIW complete rocks newbie., here, using all default settings, wrote a "small" dataset, no more than a few million records, uses half-a-GB when on disk. After about five minutes, I hit `Too many open files` with about 980 sst files, which are all open when I count them with `lsof -p pid |grep sst | wc`. 

(Actually, what I really get is silent data corruption; during debugging, I tried closing and reopening rocks, the reopen fails either with too many open files, or with a complaint that some sst file cannot be found. The open files seem to stay open forever, even after I close the rocks DB! At this point, the only choice is to just exit the app. When I exit the app and restart, it seems like rocks has the pre-data-corruption data in it. So it seems that rocks is ignoring the `getrlimit(RLIMIT_NOFILE)` setting (which is 1024 for me), blowing right past it, and then silently corrupting data when it is no longer getting valid file handles from the OS. This is rocks version 5.17 on ubuntu focal 20.04 stable))
