### ISSUE TITLE
How to change value with rocksdb_compactionfilter_create without leaking memory.

### ISSUE THREAD

**Issue by tmccombs** [facebook/rocksdb#1646]
The `rocksdb_compactionfilter_create`  uses an output `**char` parameter to allow the filter function to change the value of the an entry during compaction. However, I don't know how you would do so with allocated memory (without leaking memory), since there isn't any mechanism to free the memory after it has been copied into the output `std::string` in `rocksdb_compactionfilter_t::Filter`.  Currently, it is possible to use a static string, or a subsequence of the input value, but those options seem of limited value.

Unfortunately, simply calling `free` on the memory won't work because the memory may not have been allocated by `malloc` (it could be  a static string, or allocated by an alternative strategy).

I can think of a couple possible solutions:

- Allow the user to specify a function to free memory allocated for the new value after it is copied
- Pass the filter function the `std::string` in a wrapping struct and provide functions to write to it

Thoughts?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
