### ISSUE TITLE
Provide DBWithTTL::Open via the C API

### ISSUE THREAD

**Issue by davidstrauss** [facebook/rocksdb#1649]
Currently, it's only possible to open a `DBWithTTL` via the C++ API (and maybe the Java one), but not via the functions defined in `c.h`.

**Comment by yiwu-arbug** [comment]
Feel free to send a PR and we'll be glad to merge it :)

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
