### ISSUE TITLE
memtable.cc#L738 compile error: this statement may fall through [-Werror=implicit-fallthrough=

### ISSUE THREAD

**Issue by grooverdan** [facebook/rocksdb#1650]
https://github.com/facebook/rocksdb/blob/master/db/memtable.cc#L738

This is a new warning in gcc-7

<pre>
15:01:44 ${CXX} --version
15:01:44 + x86_64-unknown-linux-gnu-g++ --version
15:01:44 x86_64-unknown-linux-gnu-g++ (crosstool-NG crosstool-ng-1.22.0-201-g11cb2dd) 7.0.0 20161209 (experimental)

15:02:13 db/memtable.cc: In member function 'void rocksdb::MemTable::Update(rocksdb::SequenceNumber, const rocksdb::Slice&, const rocksdb::Slice&)':
15:02:13 db/memtable.cc:736:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
15:02:13            }
15:02:13            ^
15:02:13 db/memtable.cc:738:9: note: here
15:02:13          default:
15:02:13          ^~~~~~~
15:02:13 cc1plus: all warnings being treated as errors
15:02:13 Makefile:1521: recipe for target 'db/memtable.o' failed
</pre>

There is no comment about the fall-though being deliberate in the code. I'm hoping someone can clarify with a comment or a break statement.

**Comment by testn** [comment]
feel like a mistake in the original where break is missing on the previous line

**Comment by yiwu-arbug** [comment]
The logic here is to fallback to Add() if in-place update failed. Do you want to send a fix of the compile error or do you want us to fix it? Thanks!

**Comment by testn** [comment]
There is already " Add(seq, kTypeValue, key, value);" at the bottom of the function call. I don't think it should fall through as it makes the code looks confusing.
