### ISSUE TITLE
Extend DBWithTTL to allow an explicit TTL at write time

### ISSUE THREAD

**Issue by davidstrauss** [facebook/rocksdb#1651]
Right now, DBWithTTL always appends the current time (in seconds since the Unix epoch) to each written entry. Compaction then discards (by filtering) values with a timestamp older than the TTL the DB was opened with.

We could support a dynamic TTL by:

 * Defining the appended timestamp for each entry as an expiration time.
 * Defining the TTL specified while opening the database as grace period for retention after expiration.
 * Adding a new write method that allows specifying a TTL. This TTL gets added to the current time before writing the expiration to the entry.

This would preserve existing behavior while allowing dynamic TTLs for each write. While it may seem strange to allow a dynamic TTL *and* an overall grace period, it would support the needs of cache APIs like Drupal's which allow requesting expired items when fresh data isn't critical. If compaction happens aggressively, this would still allow a guaranteed minimum retention time.

Of course, I would also want to add corresponding C header support, at least after #1649. :smile:

**Comment by anirbanr-fb** [comment]
Can we not support both the modes by adding a new syntax to the append.

1. Use ts:EPOCH  to show that the data has an explicit timestamp.
2. Use ttl:EPOCH to represent the explicit expiration time.
3. Just a number for the backward compatibility.

Compaction filter honors the TTL on DB open for ts:
TTL becomes don't care for those data values which have explicit time of expiration.

**Comment by davidstrauss** [comment]
> Use ttl:EPOCH to represent the explicit expiration time.

I would prefer `exp:EPOCH` (as in "expiration") because it's not actually a TTL value.

> Just a number for the backward compatibility.

I'm not sure this is safely possible. The current code assumes the last `sizeof(int32_t)` of the value holds the timestamp. There is no delimiter or other means of safely looking for a `ts:`-style prefix without potentially matching actual (non-timestamp/expiration) values people are using.

**Comment by davidstrauss** [comment]
What we could do is put a new, magic value in the final `sizeof(int32_t)` of new things written that indicates that further preceding bytes use the new format. The current timestamp values are already "sanity checked" in a way where we know certain values will never be written (and therefore could use those as magic values).

**Comment by anirbanr-fb** [comment]
1. agree on the exp: thing.
2. we will have int32_t numbers only when we are opening an old ttl DB with the new
software. We can do the magic number or we can hand wave and say that if your
data has "exp:" or "ts:" at the absolutely wrong place, then all bets are off.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
