### ISSUE TITLE
How do I build `shared_lib` with snappy ?

### ISSUE THREAD

**Issue by unoexperto** [facebook/rocksdb#1663]
Sadly I already spent 3 hrs on this so I have to ask here. Sorry about that.

How do I build `shared_lib` with snappy ? I tried setting env variable `WITH_SNAPPY`. I tried to edit `thirdparty.inc`. Nothing helps. What should I do ?

Thanks.

SO question: http://stackoverflow.com/q/41125827/226895

**Comment by yiwu-arbug** [comment]
Have you specify the SNAPPY macro? e.g. `make OPT=-DSNAPPY shared_lib`.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
