### ISSUE TITLE
correct Netflix usage description to remove reference of spinning disks

### ISSUE THREAD

**Issue by vuzilla** [facebook/rocksdb#1678]
I want to correct the "Netflix" line in the USERS.md file to this below.  I'm not sure how long it'll take to go through the Company License route.  Since it's a simple 1 line change, can someone replace the line for me?

[Netflix](http://techblog.netflix.com/2016/05/application-data-caching-using-ssds.html) uses RocksDB on AWS EC2 instances with local SSD drives to cache application data.

Thanks

Vu

**Comment by vjon** [comment]
@vuzilla, this was fixed by 296691847d0e3c15a315680d0913284ce18767f8

Please review the change and update/close this Issue as necessary. Thanks!
