### ISSUE TITLE
Broken messages in java RocksDBException

### ISSUE THREAD

**Issue by xpromache** [facebook/rocksdb#1688]
Hello,

It looks like with in the version 4.13.4 (from maven) of RocksDB java, the exception messages seem to be broken. At least opening a database which is already open, results in an RocksDBException with the message being one letter "+" or "L" or similar. In the previous version (4.11.2) the message was something like "No locks available for /tmp/rdb-test".

For example, the code below:

<pre>
package inutil;

import org.rocksdb.RocksDB;
import org.rocksdb.RocksDBException;

public class RdbTest {
    public static void main(String[] args) throws Exception {
        RocksDB.loadLibrary();

        RocksDB.open("/tmp/rdb-test");

        try {
            RocksDB.open("/tmp/rdb-test");
        } catch (RocksDBException e) {
            e.printStackTrace();
        }
    }
}
</pre>
Will produce this output
<pre>
org.rocksdb.RocksDBException: +
	at org.rocksdb.RocksDB.open(Native Method)
	at org.rocksdb.RocksDB.open(RocksDB.java:231)
	at org.rocksdb.RocksDB.open(RocksDB.java:160)
	at inutil.RdbTest.main(RdbTest.java:15)
</pre>

**Comment by adamretter** [comment]
Interesting. What platform are you on please?

**Comment by xpromache** [comment]
Ubuntu 14, oracle jdk 8

**Comment by adamretter** [comment]
@xpromache I can reproduce what you see. I am investigating...

**Comment by adamretter** [comment]
@xpromache I can't see that this ever actually worked correctly. I have opened a PR which fixes this here - https://github.com/facebook/rocksdb/pull/1714
