### ISSUE TITLE
Building under Microsoft Visual Studio C++?

### ISSUE THREAD

**Issue by vinniefalco** [facebook/rocksdb#169]
There are some obstacles in compiling RocksDB with the latest Visual Studio. For example, use of `__thread` and `__attribute__`. I would like to have a Windows port. I'm okay with having a "port_cxx11.h" (i.e. ported to C++11, using `std::mutex`, `std::condition_variable`, et. al.). This would be useful for other platforms that support C++11 as well. But I'm stumped on some of the non standard language constructs. Thoughts?

**Comment by mohamedmansour** [comment]
@vinniefalco my coworkers over at Bing just merged a performant windows port @yuslepukhin Windows Port from Microsoft #646 yay!
