### ISSUE TITLE
Column families and prefixes

### ISSUE THREAD

**Issue by alexeibs** [facebook/rocksdb#1713]
All keys in my data have a prefix. So my keys look like:

PREFIX_key1
DIFFERENT_PREFIX_key2
ANOTHER_PREFIX_key3

There are 14 different prefixes. Every read and merge operation (there is no write, only merge) should operate with all prefixes. So every time I need access to 14x keys.
Should I create a column family for each prefix? Does it change anything?

**Comment by yiwu-arbug** [comment]
You want to have separate CFs if you have multiple sets of data and you want to have different optimizations (compaction style, write buffer size, etc) for them. If each of your prefixes gets similar workload then it doesn't seems to me they need to be in different CFs.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
