### ISSUE TITLE
rocksdb UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by raiusa** [facebook/rocksdb#1715]
I got following error when tried to use kafka stream .
I am using `0.10.1.0` version of kafka-client and kafka-stream. I read on internet that this issue has been fixed 
with this version as it uses `rocksdbjni-4.9.0 ja`r. 
Any help.

```
Exception in thread "StreamThread-1" java.lang.UnsatisfiedLinkError: Local\Temp\librocksdbjni6935746072594020003.dll: Can't find dependent libraries
```

**Comment by adamretter** [comment]
@raiusa can you try with RocksDB 4.11.2?

**Comment by raiusa** [comment]
Thanks for the reply. I don't use RockDD in my project. Kafka-stream has a dependency on RocksDB and 0.10.1.0 kafka-stream uses 4.9. But, I can add  RocksDB 4.11.2 as a dependency in pom and see how does it work.

**Comment by raiusa** [comment]
Got the same error after modifying pom (add RocksDB 4.11.2 dependency)..

<dependency>
	<groupId>org.apache.kafka</groupId>
	<artifactId>kafka-streams</artifactId>
	<version>0.10.1.0</version>
	<exclusions>
        <exclusion>  
          <groupId>org.rocksdb</groupId>
          <artifactId>rocksdbjni</artifactId>
        </exclusion>
      </exclusions> 
</dependency>
<dependency>
	<groupId>org.rocksdb</groupId>
	<artifactId>rocksdbjni</artifactId>
	<version>4.11.2</version>
</dependency>

**Comment by adamretter** [comment]
@raiusa I just noticed that you are using the Windows build, can you take a look at the dependencies required by `librocksdbjni6935746072594020003.dll` and ensure that you have those libraries installed please?

You can use the Dependency Walker tool to examine the dependencies.

**Comment by raiusa** [comment]
I am using eclipse as IDE and maven as build tool on window machine. I have checked maven 
dependency tree and find RocksDB4.11.2 . Even I have deleted all other version fro my local repository.
Thanks

**Comment by adamretter** [comment]
@raiusa I still need you to check the dependencies of the .dll and make sure you have those installed.

**Comment by raiusa** [comment]
I don't find  librocksdbjni7901374894607061476.dll  file  under tmp folder (C:\Users\xxxx\AppData\Local\Temp\) on my local. Am I missing something?

java.lang.UnsatisfiedLinkError: C:\Users\xxxx\AppData\Local\Temp\librocksdbjni1901318640949808252.dll: Can't find dependent libraries

**Comment by adamretter** [comment]
Each time you run the application, a temporary copy of the .dll will be extracted to your temp folder and will have a different name than the last version. You can also just extract a .dll from the Rocks jar and run the dependency walker tool against that.

**Comment by raiusa** [comment]
thanks for providing information about .dll. It's new to me. Finally I extracted a .dll from jar and ran the  dependency walker and attached the screen shot. I couldn't interpret much form walker.

![image](https://cloud.githubusercontent.com/assets/22483034/21462574/4b054ba8-c923-11e6-9d11-4f445cff65e7.png)

**Comment by raiusa** [comment]
Here is with error 

![image](https://cloud.githubusercontent.com/assets/22483034/21462738/241c1aec-c925-11e6-94ea-a5d9b52f3151.png)

**Comment by adamretter** [comment]
@raiusa So the Dependency Walker tool seems to show that the RocksDB DLL has a dependency on some other Windows DLL which is not present on your system. Can you install it?

**Comment by peteryao2017** [comment]
@adamretter  Did this issue get resolved? I am running into the same issue running Kafka 0.10.1.0 version of kafka-client and kafka-stream on windows 7.
My company has very strict rules about what you can install on your machine.
Is there any work around on this?

**Comment by adamretter** [comment]
@peteryao2017 If you have exactly the same problem. It is likely you need to download and install the `Microsoft Visual C++ 2015 Redistributable` from Microsoft.

**Comment by peteryao2017** [comment]
Thank you very much!
Peter
