### ISSUE TITLE
Compile rocksdb failed on OS X

### ISSUE THREAD

**Issue by Leviathan1995** [facebook/rocksdb#1717]
I git clone the newest version of rocksdb on os x, when I try to compile this library:
`$ make install`

but I got these information:

`db/db_impl.cc:602:3: error: use of undeclared`
`identifier 'malloc_stats_print'; did`
      `you mean 'je_malloc_stats_print'?`
  `malloc_stats_print(GetJemallocStatu...`
  `^~~~~~~~~~~~~~~~~~`
`1 error generated.`

so I change `malloc_stats_print` to `je_malloc_stats_print`, then it become work well.

**Comment by yiwu-arbug** [comment]
#1453 is fixing it.
