### ISSUE TITLE
Simplify RocksDB configuration

### ISSUE THREAD

**Issue by igorcanadi** [facebook/rocksdb#172]
RocksDB has a very big number of different configuration options that we added to make it flexible and suitable for various workloads and environments (in-memory, SSD, point lookups, etc). Configuring all these options to get the most out of RocksDB is not easy and requires very high familiarity with RocksDB internals.

On the other hand, RocksDB's default options are inherited from LevelDB and not suitable for any high-performance server workload.

We should invest some time in making RocksDB's options easier to configure and understand. For starting proposals, see: https://github.com/facebook/rocksdb/wiki/Proposals-on-Improving-Rocksdb's-Options

We're welcoming all contributions and thoughts in this effort.

**Comment by ekg** [comment]
How does one go about setting these options?

```c++
options.filter_policy = rocksdb::NewBloomFilterPolicy(10);
options.block_cache = rocksdb::NewLRUCache(1073741825);
```

The API has changed and they are now attached to BlockBasedTableOptions.

But you can't just do:

```c++
rocksdb::BlockBasedTableOptions topt;
topt.filter_policy = rocksdb::NewBloomFilterPolicy(10);
topt.block_cache = rocksdb::NewLRUCache(block_cache_size, 7);
options.table_factory.reset(NewBlockBasedTableFactory(topt));
```

It seems this configuration has become much more complex, and there is no obvious place where it has been documented.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
