### ISSUE TITLE
FindValueForCurrentKey requires iter value being pinned

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#1720]
This too restricted, our custom SST's iterator never pin keys and values, so our SST can not support full feature of DBIter.

We noticed that this restriction is introduced in commit 68a8e6b8fa67df745221e23ea5af12393f35ce77.

Could you provide an option to remove this restriction? @IslamAbdelRahman @siying

**Comment by rockeet** [comment]
We are trying to implement pin data in our iterator, but we can not find any method which can tell an iterator that the pinned keys and values are unneeded(unpin the pinned data). So if an InternalIterator was set as pin enabled(by PinnedIteratorsManager), it is dangerous of out of memory if the iterator is used for iterate over the whole database.

**Comment by rockeet** [comment]
Can anyone take a look at this issue ?

**Comment by IslamAbdelRahman** [comment]
Hi @rockeet , are you talking about the assert ?

**Comment by rockeet** [comment]
@IslamAbdelRahman Yes, that assert is critical, so we implemented pin data in our SST's iterator, but this introduced another issue: there is no change to release the pinned data in an iterator's lifetime, the pinned data can only be released in the destructor of SST's iterator.

So, to implement the full feature of an SST, we need one of the two:
1. A chance to release the pinned data of an SST's iterator
    - By adding a virtual method to InternalIterator, and call the method when the pinned data is not needed.
2. Move the logic of pinning data to the callers of InternalIterator
    - By adding a virtual method to InternalIterator for reporting if it support pin data, if yes, use the optimization of 68a8e6b8fa67df745221e23ea5af12393f35ce77, if not, use the slow path.

**Comment by IslamAbdelRahman** [comment]
@rockeet, I will look into this soon ( hopefully end of this week )

**Comment by rockeet** [comment]
Hi @IslamAbdelRahman, How about the status?

**Comment by rockeet** [comment]
Hi @IslamAbdelRahman, How about the status?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
