### ISSUE TITLE
Open projects updates

### ISSUE THREAD

**Issue by shuzhang1989** [facebook/rocksdb#1725]
want to see if i can contribute to any at https://github.com/facebook/rocksdb/wiki/Open-Projects

Is the list still updated? I randomly checked one "Improve performance of statistics by making use of thread local storage", looks it has been done in 1613fa9490a941f2833a4b3c4bded28e8335168a and 7c95868378c3fc745d49bdd6bb8ead3ea82a9335.

are some projects already finished, and i wonder if there is anything new to be added?

**Comment by siying** [comment]
Thank you for your interests! I removed the entry. I checked all other entries. They are not done.

**Comment by shuzhang1989** [comment]
thank you!
