### ISSUE TITLE
IngestExternalFile()

### ISSUE THREAD

**Issue by shuzhang1989** [facebook/rocksdb#1745]
Looks this is an alternative of AddFile().
Let's say i already have some keys and I only have 1 level, and the new SSTs also has the same keys, if I call IngestExternalFile(), will the new SST's value overwrite the existing ones?

**Comment by IslamAbdelRahman** [comment]
Hi @shuzhang1989, That's correct

**Comment by msb-at-yahoo** [comment]
Do the SSTs have to be created with SstFileWriter? I have a use case where I want to copy a column family from one DB to another.  Currently, we use a "portable" exchange format that involves reading all of the records on one side and re-inserting on the other. In the common case where source and destination are both using RocksDB, it seems like a better option would be to just copy the SSTs and ingest them.

**Comment by IslamAbdelRahman** [comment]
@msb-at-yahoo, Yes the file must be created using SstFileWriter. we will investigate in the future the possibility of dropping this restriction

**Comment by shuzhang1989** [comment]
@IslamAbdelRahman thanks. will this api be avaialble for 4.11? i notice addfile() has been marked deprecated already

**Comment by IslamAbdelRahman** [comment]
@shuzhang1989, this API is available starting from RocksDB 4.13

**Comment by shuzhang1989** [comment]
awesome! we will try this out

**Comment by shuzhang1989** [comment]
@IslamAbdelRahman one more question - if the db is in read only mode, is it okay to use this API to add external immutable files?

**Comment by IslamAbdelRahman** [comment]
@shuzhang1989, IngestExternalFile should not be used in read only mode. I did not handle this scenario when implementing it.
I will update the code so that it returns an error if used in read only mode

**Comment by fredia** [comment]
hi @IslamAbdelRahman , you mentioned that `we will investigate in the future the possibility of dropping this restriction`. 

Does this restriction still exist now? I want use `IngestExternalFile()` to merge two rocksDB instances, but when I ingest some .sst files which generated by another rocksDB instance, I got `org.rocksdb.RocksDBException: External file version not found`.

**Comment by ajkr** [comment]
The restriction still exists and the error you saw is the expected one (only SstFileWriter writes an external version property).

Do you have a way to resolve key conflicts when merging two DBs?

**Comment by fredia** [comment]
Thanks for your reply.  I found that PR(https://github.com/facebook/rocksdb/pull/5602) is trying to resolve this restriction.

`Do you have a way to resolve key conflicts when merging two DBs?`
\>Sorry, I am new to Rocksdb and I don't know how to resolve key conflicts.  
But, In our case,  we ensure that keys in external .sst files don't overlap with keys in live DB instance. 

An immature idea, how about adding an option to let users choose which keys to keep?
