### ISSUE TITLE
update zlib to 1.2.10

### ISSUE THREAD

**Issue by min-mwei** [facebook/rocksdb#1769]
Looks zlib 1.2.8 is pulled from its site. So the build is now failing.  

Simply replace 1.2.8 with 1.2.10 in the Makefile should fix it.

**Comment by yiwu-arbug** [comment]
#1741 addresses it.

**Comment by min-mwei** [comment]
Great. 

Also, I think all the downloads in the Makefile should be removed because the "make" should just work locally. So I like the idea of having all related tar balls (snappy, zlib etc.) checked into the rocksdb repo. 

My two cents.

**Comment by adamretter** [comment]
@yiwu-arbug I don't think you should put these in the rocks repo. Better to download with checksums IMHO.

**Comment by yiwu-arbug** [comment]
@adamretter sounds good.
