### ISSUE TITLE
how to understand the following questions about universal compaction

### ISSUE THREAD

**Issue by Shawn001** [facebook/rocksdb#1772]
1. options.level0_file_num_compaction_trigger 
   is this meaning of files in Level 0  or  the total sorted runs?

2. when execute full compaction, as follows
   Level 0: File0_0, File0_1, File0_2
Level 1: (empty)
Level 2: (empty)
Level 3: (empty)
Level 4: File4_0, File4_1, File4_2, File4_3
Level 5: File5_0, File5_1, File5_2, File5_3, File5_4, File5_5, File5_6, File5_7

when Level 0 compact to level4, how to orginze these sst files  in Level 4, all sst files in Level4 are in one sorted run.

thanks.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
