### ISSUE TITLE
DeleteRange related bug?

### ISSUE THREAD

**Issue by petermattis** [facebook/rocksdb#1778]
This is a heads up that there is some funkiness going on with `DeleteRange` for CockroachDB. Are there any known issues with it or caveats to its usage?

This past weekend I experimented with using `DeleteRange` to replace the equivalent functionality that we currently implement using `Iterators` and `Delete` in CockroachDB. I very quickly ran into internal consistency check failures (the consistency checks verify that keys and values on different replicas are identical). Unfortunately, I haven't had a chance to narrow down a test case, but can reproduce the consistency failures in a fresh cluster in a few minutes (see https://github.com/cockroachdb/cockroach/issues/12919).

A few sanity checks did not reveal any obvious brokenness. For example, after executing the `DeleteRange` the data is definitely deleted, at least when an attempt is made to read it immediately. I'm not even sure what the consistency check failure is indicating at this point. Was deleted data resurrected? Or is something else going on?

**Comment by ajkr** [comment]
Thanks, I'm taking a look. There aren't any known correctness issues, although it is a new feature. Also just a reminder (as mentioned in the .h file), using this API frequently or on small ranges can severely degrade performance.

**Comment by petermattis** [comment]
Yeah, we're aware of the performance implications and will definitely be testing various scenarios to see the impact. We're experimenting with this API because the iterator+delete approach seems to be causing perf problems of its own which we haven't fully understood yet. What would you classify as a "small range"? Our use case is for deleting a 32-64MB range of data containing O(100k) keys. 

I probably won't have time this week to narrow down the problem on our end, but my plan is to spend some time next week doing so.

**Comment by ajkr** [comment]
I saw benefits to range scan perf with deleted ranges of 50k keys on RocksDB 5.1, which has some critical optimizations. For 5.0, I'm not sure what the threshold is for you to see benefit to range scan perf. In both 5.0 and 5.1, we can expect some negative impact to random read perf.

**Comment by ajkr** [comment]
I tested your roachdemo repro with the above fix, looks like it's working properly now. Thanks a lot for reporting! I'll try to make a new 5.0 release tomorrow.

**Comment by petermattis** [comment]
That was quick. I'll test your fix locally today.

**Comment by petermattis** [comment]
Looks good in my testing too. Thanks!

**Comment by ajkr** [comment]
No problem, there's a new release (v5.0.2) with the fix: https://github.com/facebook/rocksdb/releases/tag/v5.0.2
