### ISSUE TITLE
Performance Benchmarks Flags

### ISSUE THREAD

**Issue by jetOak** [facebook/rocksdb#1785]
I've been attempting to run the performance benchmarks found here: https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks

However when I enter the given commands I get errors.  In order to make the commands run I have to remove the following flags:

--max_grandparent_overlap_factor=$overlap 
--source_compaction_factor=10000000
--writes_per_second=$wps

Are these flags no longer supported?  Has the syntax changed?

Additionally how would you go about comparing the results produced by the benchmarks?  I would like to compare the performance of one drive to another and some pointers would be helpful.

**Comment by adamretter** [comment]
@mdcallag I think maybe you are the most knowledgable on benchmarking? I also found something similar with the RocksJava benchmark tool flags - https://github.com/facebook/rocksdb/wiki/RocksJava-Performance-on-Flash-Storage

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
