### ISSUE TITLE
build_detect_platform does not set USE_SSE

### ISSUE THREAD

**Issue by tamird** [facebook/rocksdb#1790]
Looks like USE_SSE=1 was set in `fbcode_config.sh` in https://github.com/facebook/rocksdb/commit/06eed650a0e4aad03b71f229e596879471daae06, but perhaps the correct place to put it is in `build_detect_platform`.

Currently, `USE_SSE` is not documented anywhere either, so users are also unlikely to know that they should be setting it.

**Comment by adamretter** [comment]
@tamird Would you be able to submit a PR please?
