### ISSUE TITLE
perf_context timers enabled for DBImpl::mutex_

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#1809]
This is a request to clean up InstrumentedMutex:
1)  DBImpl::mutex_ enabled the perf_context timer by default
2) When both the perf_context timer and the stats timer are requested, can we only start the timer once in InstrumentedMutex::Lock?
3) Can the check for the stats timer be simpler? ShouldReportToStats checks 3 conditions today and in the common case all 3 must be evaluated. I want mutex entry & exit to be as fast as possible to reduce contention.

-- More detail for problem #1 

DBImpl::mutex_ is a source of mutex contention and I think the perf_context timer is enabled by default for it which means that InstrumentedMutex::Lock will be slower. It is enabled because DB_MUTEX_WAIT_MICROS is used in ctor for mutex_
https://github.com/facebook/rocksdb/blob/master/db/db_impl.cc#L318

And then it is used by the macro:
https://github.com/facebook/rocksdb/blob/master/util/instrumented_mutex.cc#L20

To reproduce do "mark release" after applying this diff
```
diff --git a/util/perf_context_imp.h b/util/perf_context_imp.h
index ee1a7c3..c0b00d6 100644
--- a/util/perf_context_imp.h
+++ b/util/perf_context_imp.h
@@ -36,6 +36,7 @@ namespace rocksdb {
#define PERF_CONDITIONAL_TIMER_FOR_MUTEX_GUARD(metric, condition) \
PerfStepTimer perf_step_timer_##metric(&(perf_context.metric), true); \
if ((condition)) { \
+fprintf(stderr, "perf timer\n"); \
perf_step_timer_##metric.Start(); \
}
```

Run: ./db_bench --db=/s/bld/rdb --benchmarks=overwrite
See lots of printing from that fprintf I added.

db_bench uses this for the perf level:
DEFINE_int32(perf_level, rocksdb::PerfLevel::kDisable, "Level of perf collection");

**Comment by siying** [comment]
https://github.com/facebook/rocksdb/pull/3241

**Comment by ajkr** [comment]
`To reproduce do "mark release" after applying this diff` :)

**Comment by siying** [comment]
Hmm, I realized that although PerfStepTImer.Start() is called, but its not enabled so the actual timing is not called: https://github.com/facebook/rocksdb/blob/master/monitoring/perf_step_timer.h#L16-L17

So there is no bug here. @ajkr can you verify what I mentioned is correct?

**Comment by ajkr** [comment]
I think Mark's point 2. is something we can address, where we measure the time of the same operation twice (once to put it in PerfContext, once to put in Statistics).

**Comment by siying** [comment]
I'm working on an improvement for 2, but I realized that we use the same perf counter for mutex.lock() and conditional_variable.wait(), which doesn't make sense to me. We should split it to two counters. @ajkr do you agree?

**Comment by siying** [comment]
https://github.com/facebook/rocksdb/pull/3427
