### ISSUE TITLE
GFlags undefined reference

### ISSUE THREAD

**Issue by wrinkledcheese** [facebook/rocksdb#1820]
It appears as though I have an issue compiling rocksdb.

I had an issue at first regarding std::stoull and various other string to * functions not being define din std:: namespace.

I read somewhere in a closed ticket from 2014 where someone had the same issue but all they said was it had to do with version of Linux and GCC, without giving details.  I'm running FreeBSD 10.2, and GCC 4.9.4.

I also read somewhere that it may have to do with GFlags breaking backwards compatibility, but I could find no specific version information as to which version of GFlags I should be running, so I cloned the latest github and installed that.  I received this error with both the 2.1.2 and version 2.2.0 per the github ChangeLog.txt file for gflags.  I tried 2.2.0 about an hour ago and ran gmake clean before gmake all.  I'm trying to run the benchmarks and then modify the benchmark data to see the difference between test data and my data.

The only thing I can think of to try is to compile GFlags as a shared or static - the opposite of the default - and give that a go.

Here are the error messages I get.  

tools/db_bench_tool.o: In function `rocksdb::db_bench_tool(int, char**)':
/rocksdb/tools/db_bench_tool.cc:4876: undefined reference to `gflags::SetUsageMessage(std::string const&)'
/rocksdb/tools/db_bench_tool.cc:4879: undefined reference to `gflags::ParseCommandLineFlags(int*, char***, bool)'
tools/db_bench_tool.o: In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.919]':
/rocksdb/tools/db_bench_tool.cc:80: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:183: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:185: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:190: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:194: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
tools/db_bench_tool.o:/rocksdb/tools/db_bench_tool.cc:196: more undefined references to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
tools/db_bench_tool.o: In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.919]':
/rocksdb/tools/db_bench_tool.cc:322: undefined reference to `gflags::RegisterFlagValidator(unsigned long const*, bool (*)(char const*, unsigned long))'
/rocksdb/tools/db_bench_tool.cc:324: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:330: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:334: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:337: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:341: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
tools/db_bench_tool.o:/rocksdb/tools/db_bench_tool.cc:344: more undefined references to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
tools/db_bench_tool.o: In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.919]':
/rocksdb/tools/db_bench_tool.cc:664: undefined reference to `gflags::RegisterFlagValidator(int const*, bool (*)(char const*, int))'
/rocksdb/tools/db_bench_tool.cc:666: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:680: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:683: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:686: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:690: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
tools/db_bench_tool.o:/rocksdb/tools/db_bench_tool.cc:693: more undefined references to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)' follow
tools/db_bench_tool.o: In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.919]':
/rocksdb/tools/db_bench_tool.cc:917: undefined reference to `gflags::RegisterFlagValidator(double const*, bool (*)(char const*, double))'
/rocksdb/tools/db_bench_tool.cc:920: undefined reference to `gflags::RegisterFlagValidator(double const*, bool (*)(char const*, double))'
/rocksdb/tools/db_bench_tool.cc:923: undefined reference to `gflags::RegisterFlagValidator(int const*, bool (*)(char const*, int))'
/rocksdb/tools/db_bench_tool.cc:926: undefined reference to `gflags::RegisterFlagValidator(int const*, bool (*)(char const*, int))'
/rocksdb/tools/db_bench_tool.cc:930: undefined reference to `gflags::RegisterFlagValidator(int const*, bool (*)(char const*, int))'
/rocksdb/tools/db_bench_tool.cc:933: undefined reference to `gflags::RegisterFlagValidator(int const*, bool (*)(char const*, int))'
/rocksdb/tools/db_bench_tool.cc:935: undefined reference to `gflags::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)'
/rocksdb/tools/db_bench_tool.cc:939: undefined reference to `gflags::RegisterFlagValidator(int const*, bool (*)(char const*, int))'
/rocksdb/tools/db_bench_tool.cc:942: undefined reference to `gflags::RegisterFlagValidator(int const*, bool (*)(char const*, int))'
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:894: db_bench] Error 1

**Comment by wrinkledcheese** [comment]
It's probably worth mentioning gmake static_lib and gmake shared_lib work fine.

**Comment by wrinkledcheese** [comment]
I also noticed that the gflags namespace changes between gmake all and gmake db_bench

tools/db_bench_tool.o: In function `rocksdb::db_bench_tool(int, char**)':
/home/wayne/rocksdb/tools/db_bench_tool.cc:4876: undefined reference to `google::SetUsageMessage(std::string const&)'
tools/db_bench_tool.o: In function `__static_initialization_and_destruction_0(int, int) [clone .constprop.919]':
/home/wayne/rocksdb/tools/db_bench_tool.cc:80: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
/home/wayne/rocksdb/tools/db_bench_tool.cc:447: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
/home/wayne/rocksdb/tools/db_bench_tool.cc:462: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
/home/wayne/rocksdb/tools/db_bench_tool.cc:477: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
/home/wayne/rocksdb/tools/db_bench_tool.cc:495: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)'
tools/db_bench_tool.o:/home/wayne/rocksdb/tools/db_bench_tool.cc:582: more undefined references to `google::FlagRegisterer::FlagRegisterer<std::string>(char const*, char const*, char const*, std::string*, std::string*)' follow
collect2: error: ld returned 1 exit status
gmake: *** [Makefile:894: db_bench] Error 1

**Comment by wrinkledcheese** [comment]
Found this little gem tucked away in build_tools/build_detect_plathform

# Using gflags in rocksdb:
# Our project depends on gflags, which requires users to take some extra steps
# before they can compile the whole repository:
#   1. Install gflags. You may download it from here:
#      https://gflags.github.io/gflags/ (Mac users can `brew install gflags`)
#   2. Once installed, add the include path for gflags to your CPATH env var and
#      the lib path to LIBRARY_PATH. If installed with default settings, the lib
#      will be /usr/local/lib and the include path will be /usr/local/include

Going to give it a go and let you you know/close.  I will also shoot a link to this comment in #1806

**Comment by wrinkledcheese** [comment]
This didn't solve anything.

**Comment by yiwu-arbug** [comment]
Try this?
CFLAGS="-I <gflag_header_path>/include/ -DGFLAGS=google" LDFLAGS="<gflag_path>/libgflags.a" make db_bench

**Comment by wrinkledcheese** [comment]
I will give that a try.  For now I've just written a few patches to the FreeBSD ports that I haven't pushed upstream.

**Comment by kyleyuanmh** [comment]
Is there someone has found the solution? I confront the same problem :

" Please install gflags to run rocksdb tools "

**Comment by rba4062** [comment]
@wrinkledcheese - were you able to solve this issue. If yes, which OS version and how. I have tried several things mentioned in the readme etc, but unable to find the issue here.

I am trying to compile it on Ubuntu 18.04 and was using the following command

```
CPATH=/usr/include/gflags/ LIBRARY_PATH=${LIBRARY_PATH}:/usr/lib/x86_64-linux-gnu/ make -j 4 db_bench
```

Gflags is correctly installed in my machine

```
ls /usr/lib/x86_64-linux-gnu/libgflags.so -la 
lrwxrwxrwx 1 root root 16 Aug  6  2017 /usr/lib/x86_64-linux-gnu/libgflags.so -> libgflags.so.2.2
```

**Comment by Wayne-II** [comment]
The -j flag can be problematic.  Try without -j 4.  Aside from that, I suspect the second last post prior to closing the ticket was the solution that worked for me.  We did not move forward with rocksdb.

**Comment by focus-zhaos** [comment]
> Try this?
> CFLAGS="-I <gflag_header_path>/include/ -DGFLAGS=google" LDFLAGS="<gflag_path>/libgflags.a" make db_bench
thanks！solve it
