### ISSUE TITLE
Save file after paranoid_file_checks failure

### ISSUE THREAD

**Issue by bdarnell** [facebook/rocksdb#1825]
When `paranoid_file_checks` are enabled, any corruption in the generated SST file results in the file being discarded without being aded to the database. This is good in that it keeps the database from becoming corrupted, but it also makes it difficult to figure out what's going on. It would be nice if corrupted sstables could be saved somewhere for later examination.

Motivating example: cockroachdb/cockroach#13005

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
