### ISSUE TITLE
WriteBatchWithIndex missing from the C-API

### ISSUE THREAD

**Issue by warrenfalk** [facebook/rocksdb#1833]
I would like to include WriteBatchWithIndex support in the rocksdb bindings for .Net (rocksdb-sharp), but that particular API appears to be missing from c.cc

**Comment by yiwu-arbug** [comment]
You are welcome to send a PR to add support to it :)

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
