### ISSUE TITLE
Plain Table file can't be ingested

### ISSUE THREAD

**Issue by vmx** [facebook/rocksdb#1838]
If you want to ingest a Plain Table file via `IngestExternalFile()` it fails. `IngestExternalFile()` expects support for `SeekToLast()`, which the `PlainTableIterator` doesn't have.

The error message is:

    loadplain: table/plain_table_reader.cc:639: virtual void rocksdb::PlainTableIterator::SeekToLast(): Assertion `false' failed

Here's a minimal example reproducing the issue:

```C++
#include "rocksdb/db.h"
#include "rocksdb/table.h"
#include "rocksdb/slice_transform.h"

int main(int argc, char *argv[])
{
    rocksdb::DB* db;
    rocksdb::Options options;
    options.create_if_missing = true;

    options.table_factory.reset(rocksdb::NewPlainTableFactory());
    options.prefix_extractor.reset(rocksdb::NewFixedPrefixTransform(2));

    rocksdb::SstFileWriter sst_file_writer(rocksdb::EnvOptions(), options, options.comparator);
    std::string file_path = "/tmp/plaintable.sst";

    rocksdb::Status s = sst_file_writer.Open(file_path);
    s = sst_file_writer.Add(rocksdb::Slice("Hello"), rocksdb::Slice("world!"));
    s = sst_file_writer.Finish();

    s = rocksdb::DB::Open(options, "/tmp/plaintabledb", &db);

    rocksdb::IngestExternalFileOptions ifo;
    s = db->IngestExternalFile({file_path}, ifo);

    delete db;
    return 0;
}
```

**Comment by yiwu-arbug** [comment]
Seems to me we can either
  1. Implement `PlainTableIterator::SeekToLast()` by naively scan from the first value to the last value.
  2. Simply ingest the file at level 0.
You are welcome to send a PR to fix it :)  cc @IslamAbdelRahman

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
