### ISSUE TITLE
Request: Optimization for subcompact: Add Get Random Keys

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#1842]
subcompact boundaries are MinKey and MaxKey of input SSTs, this may be not sufficient for some use cases. if the number of input SST files is small, the subcompact sizes may be skewed.

If we add an method like TableReader::GetRandomKeys(), we can get more accurate boundaries, thus the subcompact size can be more evenly distributed.

Further more, this GetRandomKeys() can be used for other scenarios(sampling, statistics...).

@siying @IslamAbdelRahman

**Comment by rockeet** [comment]
Hi @siying @IslamAbdelRahman, Do you a look at this issue?

**Comment by siying** [comment]
A potential solution is to find boundary using block boundary keys, rather than file boundaries. Some algorithm can be designed to do some efficient binary search to find them. You are welcome to contribute.

**Comment by Vegetable26** [comment]
Hello @siying, I have been considering contributing to RocksDB and was wondering if it'd be ok if I tried picking up this task?

Thanks!

**Comment by siying** [comment]
@Vegetable26 you'll be more than welcome to pick up this task.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
