### ISSUE TITLE
customize The Merge Operatoion delimiter on Java

### ISSUE THREAD

**Issue by xcl3721** [facebook/rocksdb#1843]
Thanks the Great Work First

Please Make The Merge Operator delimiter customizable

Now:
```
    options.setMergeOperator(new StringAppendOperator());
```
    the default delim_char is ','

I Want:
```
    options.setMergeOperator(new StringAppendOperator("\n"));
```
on Java

**Comment by IslamAbdelRahman** [comment]
@xcl3721, currently this is available in the c++ implementation
feel free to modify the Java code to accept the delimiter and use it when creating the c++ object

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
