### ISSUE TITLE
statistics for each column family

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#1848]
Currently the statistics is for the db instance, not for column families, in our case(https://github.com/pingcap/tikv) we use four column families to store different types of data, the statistics don't indicate clearly which column family's cache miss is high and so on.
Is there any plan to support statistics for each column family? thanks.

**Comment by siying** [comment]
So far we don't have such a plan.

**Comment by mavigdor** [comment]
Hi,
How did you get the statistics to work? I am getting zeros 
see posted issue: https://github.com/facebook/rocksdb/issues/1937

I am using RocksJava but stats.getTickerCount(), but it returns zero.
Can you assist?
Thanks!
