### ISSUE TITLE
How to use Regex in RocksDB ?

### ISSUE THREAD

**Issue by GuacheSuede** [facebook/rocksdb#1860]
Is there regex support in rocksdb, and if so, how does one use it ? Thanks

**Comment by IslamAbdelRahman** [comment]
Can you please explain more? Do you mean find keys which match a specific regex ?

**Comment by GuacheSuede** [comment]
@IslamAbdelRahman Yes, thats what i mean

**Comment by yiwu-arbug** [comment]
We don't support regex in rocksdb.
