### ISSUE TITLE
Unexpected version incompatibility

### ISSUE THREAD

**Issue by msb-at-yahoo** [facebook/rocksdb#1867]
Due other reasons, we recently attempted to downgrade from rocksdb-5.0.2 to rocksdb-4.8.  On some instances, we were then unable to restart rocksdb and got errors like:

Mon Feb 13 22:18:56 2017:   what():  Error listing column families: Corruption: VersionEdit: new-file2 entry

Since kNewFile2 isn't very new, I assume there was some other change, possibly unintentional?  Any ideas where to look?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
