### ISSUE TITLE
Is it possible to add a function maybe called GetWithSequenceNumber, which can return the sequence number along with the value? 

### ISSUE THREAD

**Issue by flabby** [facebook/rocksdb#1871]
We want to wrap RocksDB to support multi structures, like Redis's Hash, ZSet, Set.  
We want to use the sequence number as a type of data version.
Is it possible to add a function maybe called **GetWithSequenceNumber**, which can return the sequence number along with the value?

**Comment by qiwei9743** [comment]
I guess no, since the old sequence number maybe be discarded while compaction(because it is not referenced by any snapshot).

**Comment by ajkr** [comment]
Right, Get() will only return the latest version of your key and older ones will be dropped by compaction. There wouldn't be a way to access older versions.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
