### ISSUE TITLE
Corruption - Bad table magic number

### ISSUE THREAD

**Issue by zafffod** [facebook/rocksdb#1885]
Occasionally RocksDB gets in corrupted state, while running, with the following error in the log:

**2017/01/09-23:09:36.471906 3cb4 [events_data] [JOB 51] Level-0 flush table #101: 1113284 bytes Corruption: Bad table magic number**

Below is the log of rocksdb :
2017/01/09-22:57:18.693240 3cb4 (Original Log Time 2017/01/09-22:57:18.693240) Calling FlushMemTableToOutputFile with column family [events_data], flush slots available 1, compaction slots allowed 1, compaction slots scheduled 1
2017/01/09-22:57:18.693240 3cb4 [events_data] [JOB 49] Flushing memtable with next log file: 96
2017/01/09-22:57:18.693240 3cb4 EVENT_LOG_v1 {"time_micros": 1483995438693240, "job": 49, "event": "flush_started", "num_memtables": 1, "num_entries": 44817, "num_deletes": 0, "memory_usage": 4065432}
2017/01/09-22:57:18.693240 3cb4 [events_data] [JOB 49] Level-0 flush table #97: started
2017/01/09-22:57:18.724494 3cb4 [events_data] [JOB 49] Level-0 flush table #97: 1213459 bytes OK
2017/01/09-22:57:18.724494 3cb4 EVENT_LOG_v1 {"time_micros": 1483995438724494, "cf_name": "events_data", "job": 49, "event": "table_file_creation", "file_number": 97, "file_size": 1213459, "table_properties": {"data_size": 1210521, "index_size": 2698, "filter_size": 0, "raw_key_size": 349284, "raw_average_key_size": 19, "raw_value_size": 981782, "raw_average_value_size": 56, "num_data_blocks": 75, "num_entries": 17518, "filter_policy_name": "", "kDeletedKeys": "0"}}
2017/01/09-22:57:18.724494 3cb4 (Original Log Time 2017/01/09-22:57:18.724494) [events_data] Level-0 commit table #97 started
2017/01/09-22:57:18.724494 3cb4 (Original Log Time 2017/01/09-22:57:18.724494) [events_data] Level-0 commit table #97: memtable #1 done
2017/01/09-22:57:18.724494 3cb4 (Original Log Time 2017/01/09-22:57:18.724494) EVENT_LOG_v1 {"time_micros": 1483995438724494, "job": 49, "event": "flush_finished", "lsm_state": [1, 1, 0, 0, 0, 0, 0]}
2017/01/09-22:57:18.724494 3cb4 (Original Log Time 2017/01/09-22:57:18.724494) [events_data] Level summary: base level 1 max bytes base 10485760 files[1 1 0 0 0 0 0] max score 0.25
2017/01/09-23:04:11.282360 3cb4 (Original Log Time 2017/01/09-23:04:11.282360) Calling FlushMemTableToOutputFile with column family [events_data], flush slots available 1, compaction slots allowed 1, compaction slots scheduled 1
2017/01/09-23:04:11.282360 3cb4 [events_data] [JOB 50] Flushing memtable with next log file: 98
2017/01/09-23:04:11.282360 3cb4 EVENT_LOG_v1 {"time_micros": 1483995851282360, "job": 50, "event": "flush_started", "num_memtables": 1, "num_entries": 44802, "num_deletes": 0, "memory_usage": 4065432}
2017/01/09-23:04:11.282360 3cb4 [events_data] [JOB 50] Level-0 flush table #99: started
2017/01/09-23:04:11.329240 3cb4 [events_data] [JOB 50] Level-0 flush table #99: 1212707 bytes OK
2017/01/09-23:04:11.329240 3cb4 EVENT_LOG_v1 {"time_micros": 1483995851329240, "cf_name": "events_data", "job": 50, "event": "table_file_creation", "file_number": 99, "file_size": 1212707, "table_properties": {"data_size": 1209798, "index_size": 2665, "filter_size": 0, "raw_key_size": 349184, "raw_average_key_size": 19, "raw_value_size": 981142, "raw_average_value_size": 56, "num_data_blocks": 74, "num_entries": 17513, "filter_policy_name": "", "kDeletedKeys": "0"}}
2017/01/09-23:04:11.329240 3cb4 (Original Log Time 2017/01/09-23:04:11.329240) [events_data] Level-0 commit table #99 started
2017/01/09-23:04:11.329240 3cb4 (Original Log Time 2017/01/09-23:04:11.329240) [events_data] Level-0 commit table #99: memtable #1 done
2017/01/09-23:04:11.329240 3cb4 (Original Log Time 2017/01/09-23:04:11.329240) EVENT_LOG_v1 {"time_micros": 1483995851329240, "job": 50, "event": "flush_finished", "lsm_state": [2, 1, 0, 0, 0, 0, 0]}
2017/01/09-23:04:11.329240 3cb4 (Original Log Time 2017/01/09-23:04:11.329240) [events_data] Level summary: base level 1 max bytes base 10485760 files[2 1 0 0 0 0 0] max score 0.50
2017/01/09-23:09:36.440653 3cb4 (Original Log Time 2017/01/09-23:09:36.440653) Calling FlushMemTableToOutputFile with column family [events_data], flush slots available 1, compaction slots allowed 1, compaction slots scheduled 1
2017/01/09-23:09:36.440653 3cb4 [events_data] [JOB 51] Flushing memtable with next log file: 100
2017/01/09-23:09:36.440653 3cb4 EVENT_LOG_v1 {"time_micros": 1483996176440653, "job": 51, "event": "flush_started", "num_memtables": 1, "num_entries": 44820, "num_deletes": 0, "memory_usage": 4065384}
2017/01/09-23:09:36.440653 3cb4 [events_data] [JOB 51] Level-0 flush table #101: started
**2017/01/09-23:09:36.471906 3cb4 [events_data] [JOB 51] Level-0 flush table #101: 1113284 bytes Corruption: Bad table magic number**
2017/01/09-23:09:36.471906 3cb4 [ERROR] Waiting after background flush error: Corruption: Bad table magic numberAccumulated background error counts: 1
2017/01/09-23:09:36.471906 3cb4 (Original Log Time 2017/01/09-23:09:36.471906) EVENT_LOG_v1 {"time_micros": 1483996176471906, "job": 51, "event": "flush_finished", "lsm_state": [2, 1, 0, 0, 0, 0, 0]}

**Comment by yiwu-arbug** [comment]
No clue of what's happening. Apparently RocksDB is trying to read the file immediately after flush but sees corruption. The magic number is a constant at the end of each sst file: https://github.com/facebook/rocksdb/wiki/Rocksdb-BlockBasedTable-Format

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by Paras-3** [comment]
same issue I'm also facing in rocksdb with node js 
 Error: Corruption: Bad table magic number: expected 9863518390377041911, found 17165469985819521537 in D:\Users/Project_324/Sequence.db//000008.sst
