### ISSUE TITLE
RockDB data portability (aka empty db issue)

### ISSUE THREAD

**Issue by davidecaroselli** [facebook/rocksdb#1887]
Hi team!

I'm experiencing some issues with RocksDB:
1. I create a very small database on one machine, let's call it VM1.
2. Stop any process that read/write on that db.
3. SCP the entire db folder from one machine to another, VM2.
4. And now it comes the problem: if I dump the db content with my binary, I get content only in VM1, and an "empty DB" on VM2.

More precisely my code does something like:
```c++
it = db->NewIterator();
it->SeekToFirst();

while (it->Valid()) {
   ...
}
```

Now the problem is that the line `it->Valid()` it's immediately `false` on VM2.

**Do you know any good reason why I should not be able to do such operation?**

Thank you!

**Comment by davidecaroselli** [comment]
ops, almost forgot! This is the DB that is causing the issue: [db.tar.gz](https://github.com/facebook/rocksdb/files/788170/db.tar.gz) and the version of rocksdb is 4.13.5

thanks!

**Comment by davidecaroselli** [comment]
Just found the solution!
The problem was related to snappy library: rocksdb on VM1 was built with snappy, while rocksdb on VM2 not. When I tried to read the sst file with sst_dump on VM2 I get this error:
```
/.../000007.sst: Corruption: Snappy not supported or corrupted Snappy compressed block contents
```
May I suggest to throw this error at `DB->Open()` instead of silently fail?

Thanks!

**Comment by yiwu-arbug** [comment]
`DB->Open()` don't actually read the sst file, but `it->Status()` should reveal the error. Does it work for you?

**Comment by davidecaroselli** [comment]
yes, the issue arises if I use it->Status(). I was expecting database to be "readable" after db->Open(), my mistake!

Thanks!
