### ISSUE TITLE
too many WAL logs

### ISSUE THREAD

**Issue by siddontang** [facebook/rocksdb#1888]
Hi

We meet a very strange case in production. we use 4 CFs with 5 max_write_buffer_number each, so I think the max WAL log number may be 20 normally, but surprisedly, we see too many logs, maybe 100+. 

Another strange thing is that when our program crashes, we use `du` to see the total log size, about 40GB, but when we  move all logs to another disk and use `du`again, we see the total log size is about 5GB, very strange and we don't know why.

[log.zip](https://github.com/facebook/rocksdb/files/788806/log.zip)

**Comment by yiwu-arbug** [comment]
It looks likely that 008127.log contain data from CF "write" and the CF don't get flush since, so we have to keep 008127.log, which prevents logs being purged. Also at this point total CF size at this point is ~1G < max_total_wal_size.

**Comment by siddontang** [comment]
🤔 is it a bug or a normal case? 

Btw, do you know why the `du` size decrease from 40GB to 5GB?

**Comment by siying** [comment]
@siddontang Maybe something to do with fallocate. Did you set super large write_buffer_size? https://github.com/facebook/rocksdb/blob/v5.1.2/db/db_impl.cc#L3811-L3829

**Comment by siying** [comment]
Or did you set options.avoid_flush_during_recovery to true?

**Comment by siddontang** [comment]
Hi @siying 

We only 128MB for the write_buffer_size, the max_write_buffer_number is 5. We use the default value for the avoid_flush_during_recovery.

**Comment by siying** [comment]
@siddontang if you still keep the 40GB case, you can run "filefrag -v <file_name>" against those files and see whether it is a fallocate problem.

**Comment by siddontang** [comment]
Thanks @siyin 

But now the user has no environment at that time, so I have to try it later. 

Btw, the avoid_flush_during_recovery is false, which can cause the too many logs problem?

**Comment by siddontang** [comment]
> It looks likely that 008127.log contain data from CF "write" and the CF don't get flush since, so we have to keep 008127.log

/cc @yiwu-arbug restart the program can't flush the log? I am confused here.

**Comment by yiwu-arbug** [comment]
avoid_flush_during_recovery being false is fine. Setting it to true will keep the WAL files on restart.

What I'm referring to is before the restart at 2017/02/20-10:29:13 there are ~1G WAL files accumulating (the 1G size is by summing what the log tell me). After the restart the WAL files should be gone. I'm just reading from the attached log file.

**Comment by zhangjinpeng1987** [comment]
@yiwu-arbug Since the WAL will be gone after restart, why there are so many small WAL logs that less than 1MB?

**Comment by zhangjinpeng1987** [comment]
The little WAL logs are created when flush memtable to sst(when we fire manual compaction for one column family), because we use 4 column families, so the WAL logs can not delete. Thanks all of you.
