### ISSUE TITLE
env_test fails in PowerPC64 Little Endian (ppc64le)

### ISSUE THREAD

**Issue by ayappanec** [facebook/rocksdb#1889]
[ RUN      ] DefaultEnvWithDirectIO/EnvPosixTestWithParam.PositionedAppend/0
env_test: util/io_posix.cc:639: virtual rocksdb::Status rocksdb::PosixWritableFile::PositionedAppend(const rocksdb::Slice&, uint64_t): Assertion `use_direct_io() && IsSectorAligned(offset) && IsSectorAligned(data.size()) && IsPageAligned(data.data())' failed.

After debugging the issue, it seems like there is a hard-coded Pagesize assumption in the below part of the code. 

std::unique_ptr<char, Deleter> NewAligned(const size_t size, const char ch) {
  char* ptr = nullptr;
........
#else
  if (posix_memalign(reinterpret_cast<void**>(&ptr), **4 * 1024**, size) != 0) {
    return std::unique_ptr<char, Deleter>(nullptr, Deleter(free));
  }
........

The alignment value is 4096. So the address of the allocated memory will be a multiple of 4096. 
Looking at the IsPageAligned function..,

static bool IsPageAligned(const void* ptr) {
  return uintptr_t(ptr) % (kPageSize) == 0;
}

Here kPageSize refers to the system pagesize which is 65536 ( 64 * 1024) in PowerPC64 LE (ppc64le) and not 4096. So the function returns false. The alignment value in posix_memalign should be more generic like "sysconf(_SC_PAGESIZE)"

**Comment by lightmark** [comment]
Thanks. @ayappanec we will fix this soon.

**Comment by yiwu-arbug** [comment]
@ayappanec Can you confirm if #1499 works for you?

**Comment by grooverdan** [comment]
Thanks @yiwu-arbug for the commit! , since f0879e4c396ab8ffd6246afea9f6400c5098bc12 this can be closed too.

**Comment by ayappanec** [comment]
Yes, the commit works. Thanks
