### ISSUE TITLE
JNI: Crash for multiple database creation with multiple column families whithout option

### ISSUE THREAD

**Issue by vincenthouy** [facebook/rocksdb#1897]
I ran a concurrent test on rocksdbjni (version 4.9 and reproduced with  5.1.2)
My test is creating 10 databases in parallel
Each database contains 15 column families
The first 20 are well created, after that I've got a systematic crash.
If I have only one column family (other than the default), I don't have any issue

Test has been run on windows 10 and linux ubuntu with same result.
I attach the error  report and the source code of my test. 
[hs_err.zip](https://github.com/facebook/rocksdb/files/793953/hs_err.zip)
[src.zip](https://github.com/facebook/rocksdb/files/793962/src.zip)

It seems the bug is different between 4.9 and 5.1.2 version:
For 4,9 I don't have any issue if the creation is made one after the other.
For 5.1.2, it seems the crash appear after the creation of arround 300 column families for all database managed by the process

**Comment by adamretter** [comment]
Could you try with this branch please -
https://github.com/adamretter/rocksdb/tree/java8

**Comment by vincenthouy** [comment]
I've just try with your branch on my linux. I've got the same issue while creating a column family.
Here the JVM crash report:
[hs_err_pid15628.txt](https://github.com/facebook/rocksdb/files/795916/hs_err_pid15628.txt)

**Comment by vincenthouy** [comment]
I successfully found the problem in my process:  I wasn't providing any ColumnFamilyOptions while creating the multiple databases. By adding a ColumnFamilyOptions  for each Column Family creation, I didn't have any errors.  The provided column family could be initialized with a simple new ColumnFamilyOptions().

Error is not a parallelism errors since I could reproduce the crash a single creation thread. Parallelism of creation seems only to generate the problem more quickly.

The error is more related of the fact of creating a number of database (100) with lot of keys (around 100 000) without providing options for column families creation. 
After an average of  82 creation/data initialization, a crash happen.

Hope it can help you.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
