### ISSUE TITLE
5.1.3 error: use of undeclared identifier 'SYNC_FILE_RANGE_WRITE'

### ISSUE THREAD

**Issue by ilovezfs** [facebook/rocksdb#1918]
I'm seeing the following build failure on macOS while attempting to build 5.1.3:
```
  CC       util/iostats_context.o
  CC       util/io_posix.o
  CC       util/log_buffer.o
  CC       util/logging.o
  CC       util/lru_cache.o
util/io_posix.cc:775:35: error: use of undeclared identifier 'SYNC_FILE_RANGE_WRITE'
      static_cast<off_t>(nbytes), SYNC_FILE_RANGE_WRITE) == 0) {
                                  ^
  CC       util/memenv.o
1 error generated.
make: *** [util/io_posix.o] Error 1
make: *** Waiting for unfinished jobs....
```

Full build logs are here:
https://bot.brew.sh/job/Homebrew%20Core/16959/version=sierra/consoleText
https://bot.brew.sh/job/Homebrew%20Core/16959/version=el_capitan/consoleText
https://bot.brew.sh/job/Homebrew%20Core/16959/version=yosemite/consoleText

**Comment by lightmark** [comment]
We missed one patch, I will re-release it.

**Comment by lightmark** [comment]
https://github.com/facebook/rocksdb/releases/tag/v5.1.4

**Comment by ilovezfs** [comment]
@lightmark thanks! https://github.com/Homebrew/homebrew-core/pull/10326.
