### ISSUE TITLE
Division by 0 During Compaction (v5.2, Windows)

### ISSUE THREAD

**Issue by jamescourtney** [facebook/rocksdb#1925]
Hello,

I'm in the process of upgrading from v4.9 to v5.2 on Windows, and have observed a DivideByZero issue at this call stack:
```
rocksdb::Roundup Line 23
rocksdb::`anonymous namespace'::ReadaheadRandomAccessFile::ReadaheadRandomAccessFile Line 472
rocksdb::NewReadaheadRandomAccessFile Line 594
rocksdb::TableCache::GetTableReader Line 101
rocksdb::TableCache::NewIterator Line 198
rocksdb::VersionSet::MakeInputIterator Line 3387
rocksdb::CompactionJob::ProcessKeyValueCompaction Line 667
rocksdb::CompactionJob::Run() Line 537
rocksdb::DBImpl::BackgroundCompaction Line 3650
rocksdb::DBImpl::BackgroundCallCompaction Line 3348
rocksdb::DBImpl::BGWorkCompaction Line 3148
```
Specifically, the "alignment" parameter passed into Roundup seems to be 0.

**Comment by lightmark** [comment]
It seems windows get the alignment_size from `page_size_ = sinfo.dwPageSize;`. @yuslepukhin , I failed to figure out what happened here since 4k is hardcoded on posix part, could you have a see? I will add some sanitizations also.

**Comment by yuslepukhin** [comment]
@lightmark This is fixed in my latest commit

**Comment by yuslepukhin** [comment]
See c9df05d1e4dd28d23200422813f2238842899f58
