### ISSUE TITLE
Rocksdb compilation fails with IBM Java

### ISSUE THREAD

**Issue by ayappanec** [facebook/rocksdb#1926]
While doing `make rocksdbjava` with IBM Java, it fails with the following error. 

```
In file included from java/rocksjni/backupenginejni.cc:14:0:
./java/./rocksjni/portal.h: In static member function 'static _jbyteArray* rocksdb::JniUtil::v_op(std::function<rocksdb::Status(rocksdb::Slice, std::basic_string<char>*)>, JNIEnv*, jbyteArray, jint)':
./java/./rocksjni/portal.h:929:78: error: invalid conversion from 'const jbyte* {aka const signed char*}' to 'jbyte* {aka signed char*}' [-fpermissive]
                                 reinterpret_cast<const jbyte*>(value.c_str()));
                                                                              ^
In file included from java/rocksjni/backupenginejni.cc:9:0:
/opt/ibm/java-x86_64-80/include/jni.h:627:7: error:   initializing argument 4 of 'void JNIEnv_::SetByteArrayRegion(jbyteArray, jsize, jsize, jbyte*)' [-fpermissive]
  void SetByteArrayRegion(jbyteArray array, jsize start, jsize len, jbyte *buf) { functions->SetByteArrayRegion(this, array, start, len, buf); }
       ^
In file included from java/rocksjni/backupablejni.cc:17:0:
./java/./rocksjni/portal.h: In static member function 'static _jbyteArray* rocksdb::JniUtil::v_op(std::function<rocksdb::Status(rocksdb::Slice, std::basic_string<char>*)>, JNIEnv*, jbyteArray, jint)':
./java/./rocksjni/portal.h:929:78: error: invalid conversion from 'const jbyte* {aka const signed char*}' to 'jbyte* {aka signed char*}' [-fpermissive]
                                 reinterpret_cast<const jbyte*>(value.c_str()));
                                                                              ^
In file included from java/rocksjni/backupablejni.cc:12:0:
/opt/ibm/java-x86_64-80/include/jni.h:627:7: error:   initializing argument 4 of 'void JNIEnv_::SetByteArrayRegion(jbyteArray, jsize, jsize, jbyte*)' [-fpermissive]
  void SetByteArrayRegion(jbyteArray array, jsize start, jsize len, jbyte *buf) { functions->SetByteArrayRegion(this, array, start, len, buf); }
       ^
In file included from java/rocksjni/checkpoint.cc:15:0:
./java/./rocksjni/portal.h: In static member function 'static _jbyteArray* rocksdb::JniUtil::v_op(std::function<rocksdb::Status(rocksdb::Slice, std::basic_string<char>*)>, JNIEnv*, jbyteArray, jint)':
./java/./rocksjni/portal.h:929:78: error: invalid conversion from 'const jbyte* {aka const signed char*}' to 'jbyte* {aka signed char*}' [-fpermissive]
                                 reinterpret_cast<const jbyte*>(value.c_str()));
                                                                              ^
....................
....................,
```
Checking out the jni header file in IBM Java, it has
```
void SetByteArrayRegion(jbyteArray array, jsize start, jsize len, **jbyte *buf**) { functions->SetByteArrayRegion(this, array, start, len, buf); }
```

whereas in Openjdk, 
```
void (JNICALL *SetByteArrayRegion)
      (JNIEnv *env, jbyteArray array, jsize start, jsize len, **const jbyte *buf**);
```
The const qualifier is missing in Set* JNI calls for IBM Java. I made a small patch which fixes this issue. 
https://github.com/ibmsoe/rocksdb/commit/6663b405f324b871a9ed9ab656017582f1da60cb

If this okay, i can go for a pull request.

Thanks
Ayappan P

**Comment by adamretter** [comment]
@ayappanec That looks okay to me. @IslamAbdelRahman Any comments on this?

**Comment by siying** [comment]
@ayappanec if the extra const is the problem, will removing the const in cast work? Do we need to move from reintepret_cast<> to C style cast? We are following Google C++ Style and C style casting is not recommended: https://google.github.io/styleguide/cppguide.html#Casting

**Comment by zdenekkorcak** [comment]
We used extra "const_cast<jbyte*>" to solve this problem:
    const_cast<jbyte*>(reinterpret_cast<const jbyte*>(value_slice.data()))
It is a little bit longer than C style casting, but it follows Google C++ Style

**Comment by ayappanec** [comment]
@siying Removing just the const qualifier fails to compile. 
 In file included from java/rocksjni/write_batch_with_index.cc:13:0:
./java/./rocksjni/portal.h: In static member function âstatic _jbyteArray* rocksdb::JniUtil::v_op(std::function<rocksdb::Status(rocksdb::Slice, std::basic_string<char>*)>, JNIEnv*, jbyteArray, jint          )â:
./java/./rocksjni/portal.h:929:71: error: reinterpret_cast from type âconst char*â to type âjbyte* {aka signed char*}â casts away qualifiers
                                 reinterpret_cast<jbyte*>(value.c_str()));

As mentioned by @zdenekkorcak , we need to add an extra "const_cast" to fix this.

**Comment by ayappanec** [comment]
New changes at https://github.com/ibmsoe/rocksdb/commit/7ff6d27c749b93ab5041ba95166c46c7b53227f9

**Comment by ayappanec** [comment]
Any update on this ?

**Comment by adamretter** [comment]
@ayappanec Switching to the C++ style I think likely addresses @siying's concerns. Can you open a PR?

I have a concern though, that we have no way of preventing this from creeping in again in future because there is no IBM Java CI

**Comment by ayappanec** [comment]
We have a Jenkins CI machine for Open Source projects in PowerPC64 LE. I will include rocksdb project with IBM java & Openjdk in PowerPC64 LE.

**Comment by adamretter** [comment]
@ayappanec Okay but is the output of that public and can we somehow get notifications if we break the build like we do with Travis on GitHub?

**Comment by ayappanec** [comment]
The output of that will be public. I will try to set notifications for facebook/rocksdb if there is any build break.
