### ISSUE TITLE
Dynamic stats_dump_period_sec options

### ISSUE THREAD

**Issue by yiwu-arbug** [facebook/rocksdb#1930]
We would like to support dynamic stats_dump_period_sec via DB::SetDBOptions(). Sample commit to support new dynamic option: https://github.com/facebook/rocksdb/commit/91300d01f6649785975b747675d0a2d50142d4c7

Since stats_dump_period_sec may be access without holding db mutex, we need to make it atomic. For that we probably also need to have custom copy assignment operator for MutableDBOptions.

**Comment by mhlakhani** [comment]
I've passed this on to https://github.com/raza15 who will be taking a look at this. Thanks for filing @yiwu-arbug!

**Comment by yiwu-arbug** [comment]
@mhlakhani awesome! Let me know if you have any question!

**Comment by raza15** [comment]
Just wanted to confirm. The value of stats_dump_period_sec should be set 3600 by default (In the MutableDBOptions() constructor), right? This is indicated in the DBOptionsInterface.java file.

**Comment by raza15** [comment]
But the default value is indicated as 600 in the options.h file. Which one to use?

**Comment by yiwu-arbug** [comment]
@raza15 seems the comment in java code is not updated. Let's update it to indicate the default value is 600.

**Comment by raza15** [comment]
@yiwu-arbug  Alright I'll add to this change to my current PR

**Comment by mhlakhani** [comment]
@yiwu-arbug can we close this out now that the PR has landed?

**Comment by yiwu-arbug** [comment]
Yes!
