### ISSUE TITLE
Use RocksDB

### ISSUE THREAD

**Issue by mikewang2016** [facebook/rocksdb#1936]
I need something like this in a row:

key, unique_id, value

unique_id should never change once the record is generated.

key and unique_id is one-to-one map.

I need query "value" by key, or by unique_id.

Can I implement this function using RocksDB?

It seems there is really a seq ID associated with every key-value pair, but it cannot be used to query value, right?

**Comment by siying** [comment]
You need to maintain two mapping, key->(something) and unique_id=>(something).
One way is:
key=>unique_id
unique_id=>value

**Comment by mikewang2016** [comment]
Thanks for the suggestion.

But that means, when I search "value" by "key", I need do two rounds of search: (1) search unique_id by key; (2) search value by unique_id;

That will downgrade performance.

BTW:
the size of "key" and "value" is not big. So, I guess I can duplicate "value":
Insert "key->value" and "unique_id->value" to DB using column family (for atomic write)

This is not perfect, but seems work.

besides, the "unique_id" is only need to be a unique number (so its size can be smaller than "key") which can be used to find "value" very quickly. Is there certain internal ID in RocksDB can achieve similar purpose?

**Comment by yiwu-arbug** [comment]
We don't have secondary index of any kind. Even if we return sequence id for each write, we won't be able to use it to find a key quickly.

**Comment by yiwu-arbug** [comment]
Wait, if you can always get the unique_id when you have the key, how about you store your key in the form "unique_id+key" and
* when you want to query key, query "unique_id+key" instead
* when you want to query unique_id, have a iterator seek to "unique_id+(empty)", and look at the first key you encounter.
Depends on the encoding of "unique_id+key", you may need a custom key comparator.

**Comment by mikewang2016** [comment]
Thank you, but for most of the time, I can only get one of them, either key or unique_id, not both.

It will be great if RocksDB can export a function which queries data (key-value pair) by its sequence ID. Of course, I am not sure if other people has similar requirement.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
