### ISSUE TITLE
seekForPrev Behavior

### ISSUE THREAD

**Issue by jm4games** [facebook/rocksdb#1938]
So I have been trying to using seekForPrev on an interator and I want to verify the behavoir. The wiki (https://github.com/facebook/rocksdb/wiki/SeekForPrev) states that I should be able to use seekToPrev("c4") and if key "c4" exist, get it. But I am only able to retrieve for example "c3". So essentially the behavoir I am seeing is that seekToPrev will give you the first key '<' then the prefix provided and not '<='. Was this intended? Its is a bug in the code or is the wiki article incorrect? Or maybe I am just doing something wrong... 

For reference I am using rocks 5.0.2.

**Comment by jm4games** [comment]
So as a simple test I confirmed that I can use 'Seek' to get the key I expect. Meaning if I were to seek 'c4', then I will get 'c4'. But if I use SeekForPrev, I get 'c3'.

**Comment by jm4games** [comment]
So from looking at the code this is how the comparison is done: 

`    
    iter_->Seek(k, nullptr);
    valid_ = iter_->Valid();
    if (!Valid()) {
      SeekToLast();
    }

    while (Valid() && comparator_.comparator.Compare(k, key()) < 0) {
      Prev();
    }
`
Where 'k' is the key prefix. Does the comparator take into account just the prefix of 'key()'?  If not then 'k' will never be equal in the case where the prefix is only part of the key. (ie. if the prefix is 123, but the full key is 12345)

**Comment by yiwu-arbug** [comment]
I think this is intended behavior but @lightmark can confirm. The comparator take into account the full key, not just the prefix.

**Comment by jm4games** [comment]
Comments in code state that the behavior of 'SeekForPrev' should be '<=' in sync with what the wiki article provides. So would that imply this is a bug?

**Comment by yiwu-arbug** [comment]
Are you seeking using the prefix or the fully key? Say you have {b1,c1,c2} in the DB then my understanding is SeekForPrev(c1) = c1 and SeekForPrev(c) = b1.

**Comment by yiwu-arbug** [comment]
@jm4games are you able to share the simple test you have?

**Comment by jm4games** [comment]
@yiwu-arbug  Ok your last example cleared it up for me. I made the stupid assumption that it was only matching on the prefix which is not the case. It will want to match the full key. So like your example I was only supply part of the key (eg 'c') and not the full key which will end up giving ups c1. What I really need to be doing is supplying a full key that is the max of the range I want. The prefix extractor I am guessing is only used for the bloom filter. 

Thanks for the help, sry the for trouble.

**Comment by lightmark** [comment]
It takes the full key.
if you have "c3" and "c4" and seekforprev("c4"), it should return "c4". I am not able to understand your use case though.
