### ISSUE TITLE
How can i use rocksdb java to store data in-memery?

### ISSUE THREAD

**Issue by weihuazheng** [facebook/rocksdb#1954]
i want to use rocksdb java to store data in-memery as possible

**Comment by adamretter** [comment]
Take a read of the following two wiki pages:
* [How to persist in memory RocksDB database?](https://github.com/facebook/rocksdb/wiki/How-to-persist-in-memory-RocksDB-database%3F)
* [PlainTable-Format](https://github.com/facebook/rocksdb/wiki/PlainTable-Format)

It is not yet possible to set the table factory from the Java API, but I think it would be pretty trivial to add that.

**Comment by weihuazheng** [comment]
@adamretter  thanks a lot.
