### ISSUE TITLE
Tomcat crashes while trying to close RocksDb

### ISSUE THREAD

**Issue by koushikpaul1** [facebook/rocksdb#1955]
I am facing the below issue while trying to close rocksdb in java. The tomcat immediately crashes while trying to close rocksdb. I am using rocksdbjni-4.9.0.jar.

```
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f9c5c827ab2, pid=16470, tid=140309579605760
#
# JRE version: Java(TM) SE Runtime Environment (8.0_45-b14) (build 1.8.0_45-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.45-b02 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni-linux64.so+0x175ab2]  Java_org_rocksdb_DBOptions_setCreateIfMissing+0x2
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /usr/local/apache-tomcat-8.5.9/webapps/hs_err_pid16470.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by adamretter** [comment]
Can you provide a link to the `hs_err_pid16470.log` file please?

**Comment by koushikpaul1** [comment]
I have attached the file. please check. 

[hs_err_pid371.txt](https://github.com/facebook/rocksdb/files/827114/hs_err_pid371.txt)

**Comment by adamretter** [comment]
Could you follow the example here https://github.com/facebook/rocksdb/wiki/JNI-Debugging#linux to get me the relevant C++ line number of your top stack frame?

**Comment by koushikpaul1** [comment]
I am getting something like this ??:?  with the command 

addr2line -e /usr/local/lib/librocksdbjni-linux64.so 0x175ab2

where 0x175ab2 is the problematic frame as given in the tomcat log provided above.

**Comment by adamretter** [comment]
Okay that may be because you are using the production binaries. Could you try building debug binaries (DEBUG_LEVEL=2) from HEAD and reproducing?

**Comment by chitralverma** [comment]
Hey, I'm running into the same issue, any resolutions for this one ?

**Comment by adamretter** [comment]
@chitralverma Please see above, I need further details to be able to understand the issue. Perhaps you could provide these?

**Comment by pokai0426** [comment]
I'm running into the same issue
[hs_err_pid14376.log](https://github.com/facebook/rocksdb/files/2545847/hs_err_pid14376.log)

**Comment by pokai0426** [comment]
@adamretter how can i do

**Comment by sagar0** [comment]
@pokai0426 Looking at the log, your crash seems be in `RocksDB.put` whereas the earlier crash's stack trace shows `RocksDB.get`. So this might be a different issue. However, could you get use the line numbers by following the instructions here: https://github.com/facebook/rocksdb/wiki/JNI-Debugging . See if you can reproduce the issue with debug binaries if you can.
