### ISSUE TITLE
SetupDelay can make delay_write_rate way too low

### ISSUE THREAD

**Issue by revans2** [facebook/rocksdb#1966]
We have a situation where we have a rocksdb instance (4.5.1) that is getting a high write rate with large batches, and has been up for over almost a month.  Over that month we have only hit about 200 delays, but most delays drops the delay_write_rate until at this point it is close to 26 KB/sec.  Once this happens a write of 15 MB can cause a delay of 10 mins.  Compaction completely finished 8 mins before the write woke up.

Looking at the code SetupDelay will take the current compaction bytes and the previous compaction bytes to try and determine if we are falling behind in compaction or catching up, aka should we decrease the rate or increase the rate.  But sadly this code is only ever executed when a delay happens.

So in our situation everything is going fine for hours, no delays, and the writes are then not throttled.  We hit a snag and need a delay.  Well it is highly likely that because of the snag we have more compaction to do now, then we did a few mins ago when we didn't need the delay.  As such the rate drops, we recover and the process repeats.

We should either have previous compaction bytes updated only when a delay happens, or we should have the rate rise back up based off of the amount of time we have no delays.

**Comment by siying** [comment]
CC @IslamAbdelRahman

**Comment by IslamAbdelRahman** [comment]
Hi @revans2, we are working on breaking the stalls if we have finished all bg work
https://github.com/facebook/rocksdb/pull/1884

**Comment by revans2** [comment]
@IslamAbdelRahman That sounds like a perfect solution.  I'm not sure how you track issues.  Do you want me to just close this pointing to your fix?
