### ISSUE TITLE
consider adding a PopSavePoint for WriteBatch

### ISSUE THREAD

**Issue by siddontang** [facebook/rocksdb#1969]
Hi

I see that WriteBatch uses a stack to support save point, but it only supports SetSavePoint and RollbackToSavePoint. Sometimes, we may need set the save point and then pop it with no error. 

Consider the following case with pseudo code. 

```
WriteBatch wb = WriteBatch::new();

for int i = 0; i < 1000; i++ {
    wb.SetSavePoint();
    // do something, like wb.Put, wb.Delete
    if error {
          wb.RollbackToSavePoint()
    } else {
          wb.PopSavePoint()
    }
}
```

For the above code, we only need one save point all the time, if no Pop, the save point stack size is 1000, seem no need here.

**Comment by yiwu-arbug** [comment]
Seems to me it make sense. As always, you are welcome to send a pull request!

**Comment by siddontang** [comment]
Hi @yiwu-arbug 

I tried before, but found that WriteBatchWithIndex also needed to be changed, but I'm not familiar with it, maybe we can return an error simply for the transaction WriteBatch.

**Comment by yiwu-arbug** [comment]
For WriteBatchWithIndex, I didn't check carefully, but probably just relay the call to WriteBatch and call RebuildIndex will work, like what it is done in WriteBatchWithIndex::RollbackToSavePoint: https://github.com/facebook/rocksdb/blob/master/utilities/write_batch_with_index/write_batch_with_index.cc#L796
