### ISSUE TITLE
test failure - DBTest2::ReadAmpBitmapLiveInCacheAfterDBClose

### ISSUE THREAD

**Issue by grooverdan** [facebook/rocksdb#1977]
at release 5.3 (fe1835617aa490f5d391f588a8735659f62c1270)

<pre>
Thread 1 "db_test2" hit Breakpoint 2, rocksdb::DBTest2_ReadAmpBitmapLiveInCacheAfterDBClose_Test::TestBody (this=0x9dc530) at /home/dan/repos/rocksdb/db/db_test2.cc:2074
2074      ASSERT_EQ(total_useful_bytes_iter1 + total_useful_bytes_iter2,
(gdb) p total_useful_bytes_iter1
$13 = 640000
(gdb) p total_useful_bytes_iter2
$14 = 640000
(gdb) list
2069          options.statistics->getTickerCount(READ_AMP_ESTIMATE_USEFUL_BYTES);
2070      size_t total_loaded_bytes_iter2 =
2071          options.statistics->getTickerCount(READ_AMP_TOTAL_READ_BYTES);
2072
2073      // We reached read_amp of 100% because we read all the keys in the DB
2074      ASSERT_EQ(total_useful_bytes_iter1 + total_useful_bytes_iter2,
2075                total_loaded_bytes_iter1 + total_loaded_bytes_iter2);
2076    }
2077
2078    #ifndef ROCKSDB_LITE
(gdb) p total_loaded_bytes_iter1
$15 = 1202304
(gdb) p total_loaded_bytes_iter2
$16 = 1202432
(gdb) n
/home/dan/repos/rocksdb/db/db_test2.cc:2075: Failure
Value of: total_loaded_bytes_iter1 + total_loaded_bytes_iter2
  Actual: 2404736
Expected: total_useful_bytes_iter1 + total_useful_bytes_iter2
Which is: 1280000
testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=0x9dc530, method=&virtual testing::Test::TestBody(), location=0x5dcd43 "the test body")
    at /home/dan/repos/rocksdb/third-party/gtest-1.7.0/fused-src/gtest/gtest-all.cc:3882
</pre>

**Comment by yiwu-arbug** [comment]
It works on my side. Any easy way to reproduce?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
