### ISSUE TITLE
RocksDB failed to build (Release|x64) on windows due to warning C4244: '=': conversion from 'uint64_t' to 'double', possible loss of data

### ISSUE THREAD

**Issue by KarenHuang2016** [facebook/rocksdb#1979]
Hi,
We (the MSVC++ team) do a nightly build of the latest RocksDB sources as a compiler "Real World Code" test. We noticed warning C4244 is reported after commit 5b11124 "add max to histogram stats". This warning is reported form file histogram.cc like below:
d:\rocksdb\src\util\histogram.cc(238): warning C4244: '=': conversion from 'uint64_t' to 'double', possible loss of data 

//histogram.cc
void HistogramStat::Data(HistogramData * const data) const {
  assert(data);
  data->median = Median();
  data->percentile95 = Percentile(95);
  data->percentile99 = Percentile(99);
  **data->max = max();**
  data->average = Average();
  data->standard_deviation = StandardDeviation();
}

The "data->max" is doulbe and the return value of "max()" is uint64_t. So the warning C4244 is reported.

Could you please take a look at this? Thanks!

**Comment by ajkr** [comment]
it's fixed here: https://github.com/facebook/rocksdb/commit/900c62be61f71c8040c83e8348a2f1fe408c2087
