### ISSUE TITLE
A tool show how many page cache rocksdb used

### ISSUE THREAD

**Issue by baotiao** [facebook/rocksdb#1981]
I have wrote a tool to show how many page cache used by rocksdb
do you need it

```
└─[$] ./rocksdb ./db/
total rocksdb cache size 12721 MB
```

**Comment by IslamAbdelRahman** [comment]
Yes! that would be great.
Is there a way to know the page cache hit rate? that would be very useful in statistics

**Comment by baotiao** [comment]
This is the code, It is widely used in our production pika(https://github.com/Qihoo360/pika). Since out DBA always want to know how much page cache does rocksdb used.
I don't know where should I put the code. And we can have more information, such which sst file was in the paga cache, and so on.

I know we can write a script through ftrace to know the page cache hit rate, but we havn't the script, if you need it, I can write it for you

**Comment by mikhail-antonov** [comment]
This is indeed a useful feature, impl may depend on the OS/kernel version.

http://www.brendangregg.com/blog/2014-12-31/linux-page-cache-hit-ratio.html - some notes covering older kernels, in new ones we should have much better tolling with BCC/BPF.

**Comment by baotiao** [comment]
@mikhail-antonov  but BCC/BPF is add in version 4.10,  many distribution still use old kernel veison, such as 3.10.

**Comment by mikhail-antonov** [comment]
I think they were added in 3.15 first, but most good features start to be available in 4.x (the newer the better, obviously). I think my point is that would be good to provide an option for folks running new-ish kernel to be able to leverage it.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
