### ISSUE TITLE
Error: recipe for target 'ldb_cmd_test' failed

### ISSUE THREAD

**Issue by raza15** [facebook/rocksdb#2002]
Hi. I am trying to run rocksdb in debug mode on Ubuntu 16.04. I did all the required installations as indicated in INSTALL.md. I cloned a fresh repository and I run "make clean" and then "make check" from the root directory of the project. The "make check" runs several tests but then it fails with the following error:

  CC       db/compaction_job_stats_test.o
  CCLD     compaction_job_stats_test
  CC       utilities/option_change_migration/option_change_migration_test.o
  CCLD     option_change_migration_test
  CC       utilities/transactions/transaction_test.o
  CCLD     transaction_test
  CC       tools/ldb_cmd_test.o
  CCLD     ldb_cmd_test
collect2: error: ld returned 1 exit status
Makefile:1309: recipe for target 'ldb_cmd_test' failed
make: *** [ldb_cmd_test] Error 1

Anybody knows how to fix this?

commit: 36ad75778bfaad69ee59d29eb4f2e86ff28f7af5

**Comment by siying** [comment]
Our CI builds work fine. Is it just ldb_cmd_test? If you comment out this test (https://github.com/facebook/rocksdb/blob/5.3.fb/Makefile#L420) what will you see?

**Comment by raza15** [comment]
@siying this issue has been resolved and updated in the following merged PR: https://github.com/facebook/rocksdb/pull/2016
