### ISSUE TITLE
 Assertion `prev_smallest_seqno > largest_seqno' failed

### ISSUE THREAD

**Issue by ZhenNan2016** [facebook/rocksdb#2003]
the disk space was full. and then I'm trying to  restart the c++ application after the disk space  was released, but the rocksdb  throw  the following exception  :

db/compaction_picker.cc:1403: virtual rocksdb::Compaction* rocksdb::UniversalCompactionPicker::PickCompaction(const string&, const rocksdb::MutableCFOptions&, rocksdb::VersionStorageInfo*, rocksdb::LogBuffer*): Assertion `prev_smallest_seqno > largest_seqno' failed.
by the way, the rocksdb version is 4.11.2， it is  included into the c + + application。

**Comment by hedengcheng** [comment]
Hi, @siying 
Would you please have a look on this problem? We met it so many times.
Does this bug imply that RocksDB was not crash safe on "Dish Full" problem?

**Comment by siying** [comment]
It means some L0 files don't followed the universal compaction rule: some files have overlapping sequence number ranges. On top of my head, I can't think of a reason why this can happen even with out of space condition. Can you dig the manifest file for the compaction/flush history and see when did the sequence number condition has been broken and in which way (compaction, flush, etc)?

**Comment by ZhenNan2016** [comment]
hi，@siying
I can‘t get the manifest file for the compaction/flush history now，because  the server goes down and  it has disappeared. 
Would you please check my options if has a error using, that leading to this exception? as follows :
        Options options;
        options.create_if_missing = true;
        options.keep_log_file_num = 100;
        options.recycle_log_file_num = 100;
        options.OptimizeUniversalStyleCompaction();
        options.level0_file_num_compaction_trigger = 1;
        options.max_background_flushes = 16;
        options.max_open_files = 100;
        options.base_background_compactions = 2;
        options.max_background_compactions = 2;
        options.target_file_size_base = (size_t)2 * 1024 * 1024;
        options.max_bytes_for_level_base = (size_t)16 * 1024 * 1024;
        options.num_levels = 6;

        options.write_buffer_size = (size_t)4 * 1024 * 1024;
        options.max_write_buffer_number = 6;

        //initialize BlockBasedTableOptions
        auto cache1 = rocksdb::NewLRUCache(4 * 1024 * 1024LL);//之前1G
        rocksdb::BlockBasedTableOptions bbt_opts;
        bbt_opts.block_cache = cache1;
        bbt_opts.cache_index_and_filter_blocks = true;
        bbt_opts.block_size = 64 * 1024;
        bbt_opts.format_version = 2;
        options.table_factory.reset(rocksdb::NewBlockBasedTableFactory(bbt_opts));

**Comment by ZhenNan2016** [comment]
hi, @siying 

the disk space was full.  not released,  the rocksdb  throw the following exception:
./util/posix_logger.h:151: virtual void rocksdb::PosixLogger::Logv(const char*, __va_list_tag*): Assertion `sz == write_size' failed.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
