### ISSUE TITLE
Public API is broken

### ISSUE THREAD

**Issue by vmx** [facebook/rocksdb#2008]
Commit 11526252cc0b5e1db82bf30dad7e202616f90dd4 introduced the inclusion of `port/likely.h` in `rocksdb/db.h` ([direct link to line](https://github.com/facebook/rocksdb/commit/11526252cc0b5e1db82bf30dad7e202616f90dd4#diff-2d5da900224eb97125a84105b6cafa19R19)). This breaks the public API as now another header search path (besides the normal RocksDB include directory) is needed.

An easy way to reproduce the problem is to compile the examples, which currently fails with:

```
In file included from simple_example.cc:9:0:
../include/rocksdb/db.h:19:25: fatal error: port/likely.h: No such file or directory
 #include "port/likely.h"
```

I've added a new job to Travis in #2007 that also builds the examples. I don't know if a new job is the right way to do it, but at least it shows the problem (see [Travis Job #6682.8](https://travis-ci.org/facebook/rocksdb/jobs/213065597#L617)).

**Comment by lightmark** [comment]
@maysamyabandeh

**Comment by lightmark** [comment]
https://github.com/facebook/rocksdb/pull/2009
