### ISSUE TITLE
Building RocksJava?

### ISSUE THREAD

**Issue by mikhail-antonov** [facebook/rocksdb#2014]
Hey guys,

I have a question on RocksJava build. I'm currently using it (mostly in the context of using SstFileWriter API to prepare data for bulkload) and need to make a few fixes. 

I wanted to make sure that the jars produced from my build (including .so libs) are followed the same process as what's being published to Maven Central (though I only intent to test linux64 versions ever).

Are steps at https://github.com/facebook/rocksdb/wiki/RocksJava-Basics the latest guide we have? Does that reflect RocksJava release process?

**Comment by mikhail-antonov** [comment]
@adamretter I suppose you're the one mostly involved in it?..

**Comment by adamretter** [comment]
The target that we use for producing the Maven artifacts is:

```
PORTABLE=1 make rocksdbjavastaticrelease
```

**Comment by mikhail-antonov** [comment]
Thanks! Let me poke around.
