### ISSUE TITLE
gcc: internal compiler error

### ISSUE THREAD

**Issue by vinniefalco** [facebook/rocksdb#2020]
rocksdb suddenly no longer compiles under gcc, I get "internal compiler error." See:
https://travis-ci.org/vinniefalco/NuDB/jobs/213555724#L713

Building with clang works fine, see:
https://travis-ci.org/vinniefalco/NuDB/builds/213555723

```
$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
```

**Comment by siying** [comment]
RocksDB now requires GCC 4.8 to build, and it has been a while. But either way you shouldn't get "internal compiler error". We don't see it in any of our CI systems, you can see our Travis builds: https://travis-ci.org/facebook/rocksdb

**Comment by vinniefalco** [comment]
I didn't write my .travis.yml (I'm largely a Windows developer) but I will try to figure out how to get Travis to use a more recent gcc. Thanks!
