### ISSUE TITLE
RocksJni DBOptions not support setEnv？

### ISSUE THREAD

**Issue by clark010** [facebook/rocksdb#2022]
I am using RocksDB's HDFS api and i write a newHDFSEnv class, but i found when using multi columnFamily, it can't set env through DBOptions（the feature only support in Options）, if there is other way to support set HDFSEnv in options？

**Comment by adamretter** [comment]
You can find a patch here - https://github.com/adamretter/rocksdb/commit/175fdf72dcaecd7cee02411b3be6997a0b762899

I will submit a PR once I have added the other missing options.

**Comment by clark010** [comment]
@adamfaulkner  thanks for the patch, it help me a lot.
