### ISSUE TITLE
RangeDelAggregator holds pointers which outlives the table readers that created them

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#2048]
We implemented a custom SST and we are trying implement the full features of SST, including **range delete**, now we are trapped by  **range delete**...

In file `db/db_range_del_test.cc`:`508`, it says:

>   // The RangeDelAggregator holds pointers into range deletion blocks created by
>   // table readers. This test ensures the aggregator can still access those
>   // blocks even if it outlives the table readers that created them.
> 
**This violate the general rule**, and makes our custom SST can not work for range delete, since our SST only use `mmap` and doesn't need block cache, when the SST is closed, the memory block referenced by `RangeDelAggregator` becomes invalid, thus produce a segfault.

@IslamAbdelRahman @siying

**Comment by ajkr** [comment]
What is the general rule it violates?

**Comment by ajkr** [comment]
Sorry but we create a collapsed form of the range deletions for faster searching in RangeDelAggregator, and it's not trivial to remove range deletions from this representation as files are closed. Feel free to contribute ideas/code.

For now, can you copy the range deletion data into a Block object, then call NewIterator() on it, and register a cleanup function (RegisterCleanup()) that deletes the Block?

**Comment by rockeet** [comment]
Thank you, we have worked around this issue by your advise!

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
