### ISSUE TITLE
ASSERT ! IngestExternalFile with allow_mmap_reads

### ISSUE THREAD

**Issue by mm304321141** [facebook/rocksdb#2069]
on Windows .

[io_win.cc : 724](https://github.com/facebook/rocksdb/blob/master/port/win/io_win.cc#L724)
```
  assert(!options.use_mmap_reads);
```

try modify
[external_sst_file_ingestion_job.cc : 459](https://github.com/facebook/rocksdb/blob/master/db/external_sst_file_ingestion_job.cc#L459)
```
  std::unique_ptr<RandomRWFile> rwfile;
  EnvOptions env_options = env_options_;
  env_options.use_mmap_reads = false;
  Status status = env_->NewRandomRWFile(file_to_ingest->internal_file_path,
                                        &rwfile, env_options);
```

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
