### ISSUE TITLE
ASSERT ! IngestExternalFile under UniversalCompaction

### ISSUE THREAD

**Issue by mm304321141** [facebook/rocksdb#2070]
assert here ...
[compaction_picker.cc : 1554](https://github.com/facebook/rocksdb/blob/master/db/compaction_picker.cc#L1554)
```
        assert(prev_smallest_seqno > largest_seqno);
```

here is test code ...
```
#include <utility>
#include <iterator>
#include <memory>
#include <cstdlib>
#include <vector>
#include <thread>
#include <random>
#include <iostream>

#include <rocksdb/db.h>
#include <rocksdb/memtablerep.h>
#include <rocksdb/table.h>
#include <rocksdb/slice.h>
#include <rocksdb/sst_file_writer.h>
#include <util/coding.h>
#include <db/memtable.h>

std::string get_key(size_t i)
{
  char buffer[32];
  snprintf(buffer, sizeof buffer, "%010zd", i);
  return buffer;
}
std::string get_value(size_t i)
{
  char const *str = "0123456789QWERTYUIOPASDFGHJKLZXCVBNM";
  return str + (i % (strlen(str) - 1));
}

int main()
{
  rocksdb::DB *db;
  rocksdb::Options options;

  options.allow_mmap_reads = true;
  options.compaction_style = rocksdb::kCompactionStyleUniversal;

  options.create_if_missing = true;

  char const *dp_dir = "C:/osc/rocksdb_test/testdb";
  char const *sst_add = "C:/osc/rocksdb_test/add.sst";

  rocksdb::Status s = rocksdb::DB::Open(options, dp_dir, &db);

  rocksdb::ReadOptions ro;
  rocksdb::WriteOptions wo;
  rocksdb::FlushOptions fo;

  std::string value;

  rocksdb::SstFileWriter w(rocksdb::EnvOptions(db->GetDBOptions()), db->GetOptions(), db->GetOptions().comparator);
  w.Open(sst_add);
  w.Add(get_key(0), get_value(0));
  w.Finish();

  s = db->Put(wo, get_key(0), get_value(0));
  db->Flush(fo);
  s = db->Put(wo, get_key(1), get_value(1));
  db->Flush(fo);
  db->CompactRange(rocksdb::CompactRangeOptions(), nullptr, nullptr);
  s = db->SingleDelete(wo, get_key(1));
  db->Flush(fo);
  db->IngestExternalFile({ sst_add }, rocksdb::IngestExternalFileOptions());
  s = db->Delete(wo, get_key(0));
  db->Flush(fo);
  db->CompactRange(rocksdb::CompactRangeOptions(), nullptr, nullptr);

  auto it = db->NewIterator(ro);
  rocksdb::Slice value_slice;
  for (it->SeekToLast(); it->Valid(); it->Prev())
  {
    value_slice = it->value();
  }
  delete it;
  delete db;

  return 0;
}
```

**Comment by yiwu-arbug** [comment]
@IslamAbdelRahman do we support ingesting file with universal compaction?

**Comment by IslamAbdelRahman** [comment]
Thanks @mm304321141  for the report, IngestExternalFile does not support universal compaction right now. We are planning to support it very soon
CC: @mikhail-antonov

**Comment by rockeet** [comment]
It seems that universal compaction requires seqnum not overlap with each sorted run, this condition can not be satisfied with keys non-overloap with each sorted run.

Our use case of `IngestExternalFile` is by MyRocks, we use universal compation in MyRocks. 

@IslamAbdelRahman @siying @mikhail-antonov @ajkr Can any one propose a quick fix for this simple case?

**Comment by mikhail-antonov** [comment]
The quickest and easiest solution we discussed was to run it as:

if (compaction == universal)
   - unconditionally insert file to L0
   - unconditionally force memtable flush before ingest.

That seems to cover existing problems. I have some WIP on it.

**Comment by mikhail-antonov** [comment]
in theory that would cause more read ampl, but in practice would depend on the ingest rate and volume

**Comment by IslamAbdelRahman** [comment]
Thanks @mikhail-antonov, unfortunately ingesting in L0 could be very bad for MyRocks case since they will insert a big amount of files.

@lightmark is going to work on a general solution to support IngestExternalFile with universal compaction. It will be very similar to the leveled compaction approach but it will require us to assign a global sequence number in a different way to the ingested file

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
