### ISSUE TITLE
wiki: dead links on the page "Article about rocks"

### ISSUE THREAD

**Issue by HassanCehef** [facebook/rocksdb#2085]
Hi 😃 

On the wiki, page https://github.com/facebook/rocksdb/wiki/Articles-about-Rocks, all the links pointing to the **rocksdb.org** blog are dead. They point to the old link structure `/blog/id/slug`, whereas the current structure seems to be `/blob/YYYY/MM/DD/slug`.

I can't submit a pull request against the wiki (I don't know if it's possible), so here's the list:
* Migrating: http://rocksdb.org/blog/2015/01/16/migrating-from-leveldb-to-rocksdb-2.html
* Integrating: http://rocksdb.org/blog/2015/04/22/integrating-rocksdb-with-mongodb-2.html
* WriteBatchWithIndex: http://rocksdb.org/blog/2015/02/27/write-batch-with-index.html
* How to persist: http://rocksdb.org/blog/2014/03/27/how-to-persist-in-memory-rocksdb-database.html
* Reading RocksDB: http://rocksdb.org/blog/2015/02/24/reading-rocksdb-options-from-a-file.html
* How to backup: http://rocksdb.org/blog/2014/03/27/how-to-backup-rocksdb.html

I hope this helps :)
(On an unrelated note, the blog is not served over HTTPS :( )

**Comment by yiwu-arbug** [comment]
Thank you for reporting! Will update the wiki.

**Comment by yiwu-arbug** [comment]
Done.
