### ISSUE TITLE
Not able to build rocksdb fat jar on AIX 6.1

### ISSUE THREAD

**Issue by manishbansal8843** [facebook/rocksdb#2091]
Getting below error while executing `make rocksdbjava` command:

```
Makefile:104:` Warning: Compiling in debug mode. Don't use the resulting binary in production
Unknown platform!
grep: can't open -o
In file included from ./db/dbformat.h:15,
                 from ./utilities/column_aware_encoding_util.h:10,
                 from utilities/column_aware_encoding_util.cc:8:
./include/rocksdb/db.h:17:25: error: unordered_map: No such file or directory
In file included from ./include/rocksdb/options.h:26,
                 from ./include/rocksdb/db.h:22,
                 from ./db/dbformat.h:15,
                 from ./utilities/column_aware_encoding_util.h:10,
                 from utilities/column_aware_encoding_util.cc:8:
./include/rocksdb/write_buffer_manager.h:15:18: error: atomic: No such file or directory
In file included from ./include/rocksdb/cache.h:29,
                 from ./include/rocksdb/table.h:23,
                 from ./db/dbformat.h:19,
                 from ./utilities/column_aware_encoding_util.h:10,
                 from utilities/column_aware_encoding_util.cc:8:
./include/rocksdb/statistics.h:11:19: error: cstdint: No such file or directory
In file included from ./util/statistics.h:15,
                 from ./table/persistent_cache_options.h:10,
                 from ./table/format.h:19,
                 from ./table/filter_block.h:31,
                 from ./table/block_based_table_reader.h:24,
                 from ./utilities/column_aware_encoding_util.h:15,
                 from utilities/column_aware_encoding_util.cc:8:
./util/histogram.h:17:17: error: mutex: No such file or directory
./util/histogram.h:149:24: error: no newline at end of file
In file included from ./util/statistics.h:16,
                 from ./table/persistent_cache_options.h:10,
                 from ./table/format.h:19,
                 from ./table/filter_block.h:31,
                 from ./table/block_based_table_reader.h:24,
                 from ./utilities/column_aware_encoding_util.h:15,
                 from utilities/column_aware_encoding_util.cc:8:
./util/mutexlock.h:14:18: error: thread: No such file or directory
In file included from ./util/thread_local.h:18,
                 from ./util/statistics.h:17,
                 from ./table/persistent_cache_options.h:10,
                 from ./table/format.h:19,
                 from ./table/filter_block.h:31,
                 from ./table/block_based_table_reader.h:24,
                 from ./utilities/column_aware_encoding_util.h:15,
                 from utilities/column_aware_encoding_util.cc:8:
./util/autovector.h:9:28: error: initializer_list: No such file or directory
make: *** [utilities/column_aware_encoding_util.d] Error
```

Platform - AIX `6.1
GCC: 4.1.0
make: GNU Make 3.80

**Comment by adamretter** [comment]
@manishbansal8843 are you on `ppcle`?

I think @ayappanec has managed to build this on LinuxPPC, but I am not sure if anyone has tried on AIX. Also I think it might be the case that if you are on a big-endian architecture, then you might be in for a lot of work to port RocksDB to such a platform.

**Comment by ayappanec** [comment]
@adamretter is right. AIX being a big-endian architecture, it involves significant work to port RocksDB. I am actually part of the official IBM AIX Opensource team and we have a good amount of opensource packages ported to AIX. http://www-03.ibm.com/systems/power/software/aix/linux/toolbox/alpha.html

**Comment by ayappanec** [comment]
@manishbansal8843 First you need to get all the tools required to build RocksDB in AIX and then try porting it to AIX platform.

**Comment by manishbansal8843** [comment]
@adamretter Yes it is POWER7 processor type which is BE.

@ayappanec I am not sure what all tools are required here. I thought only gcc and gmake is enough. Can you please help me walk-through the same.

**Comment by ayappanec** [comment]
@manishbansal8843 You need to figure out from the error. For example, you got a error "error: unordered_map: No such file or directory" . Find out which package provides this in linux. Then check it in AIX Toolbox link which i shared in the previous thread. If it is not there, then you may have to port that also.  It's going to take significant effort.

**Comment by manishbansal8843** [comment]
@ayappanec I tried some googling and got to know that above error is coming because rocksdb source code is using c++11 standards. Therefore i need a gcc and g++ compiler version >=4.8. Further after installing gcc and g++ 4.8.5, and setting environment variable EXTRA_CXXFLAGS=-std=c++11, i was able to proceed. However, after this, i am getting new errors as below.

```
gmake rocksdbjava
Makefile:104: Warning: Compiling in debug mode. Don't use the resulting binary in production
Unknown platform!
grep: 0652-033 Cannot open -o.
GEN      util/build_version.cc
CC       jl/db/auto_roll_logger.o
In file included from ./db/auto_roll_logger.h:16:0,
 from db/auto_roll_logger.cc:6:
./util/sync_point.h:108:56: error: 'std::thread' has not been declared
bool DisabledByMarker(const std::string& point, std::thread::id thread_id);
```
Now above error is coming due to lack of threading support in g++ 4.8.5 version. Some people have suggested to use -pthread option for which i did set environment variable as below.

`export JAVA_LDFLAGS=-pthread`

However, this still does not work. Now, i am not sure this will work for AIX or not. Kindly suggest what can be done here.

**Comment by ayappanec** [comment]
Again make sure you got all the tools for compilation. Check for libstdc++ and it's devel package in your AIX machine.

**Comment by adamretter** [comment]
@manishbansal8843 @ayappanec I just found this other isuse https://github.com/facebook/rocksdb/issues/966 where @koldat claims to have RocksDB running on AIX. Maybe worth asking him if he could send a PR or patches?

**Comment by ayappanec** [comment]
@adamretter Great!. So somebody has successfully done it. @manishbansal8843 May be you can check with @koldat about the changes.

**Comment by Downchuck** [comment]
https://github.com/facebook/rocksdb/pull/2194
