### ISSUE TITLE
RocksDB cache data gets removed when tomcat shuts down.

### ISSUE THREAD

**Issue by koushikpaul1** [facebook/rocksdb#2129]
RocksDB cache data is getting removed when tomcat is shutting down. The data persisting with .sst files can be fetched but those in cache only cannot be retrieved. The issue only arises when tomcat is closed.

I am using TTlDB and using jar rocksdbjni-4.9.0

**Comment by yiwu-arbug** [comment]
Do you have WAL enable and how do issue WAL sync?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
