### ISSUE TITLE
c.cc: static fun  CopyString, return c stye string without '\0'

### ISSUE THREAD

**Issue by loadwiki** [facebook/rocksdb#2130]
As describe in the title, does somebody have this problem?
I'm developing a c api for rocksdb branch(nemo-rocksdb).
After a simple test I find some string argument of my c func wrong.
Finally I find a func named CopyString ,which I copy from rocksdb/db/c.cc:
static char* CopyString(const std::string& str) {
  char* result = reinterpret_cast<char*>(malloc(sizeof(char) * str.size()));
  memcpy(result, str.data(), sizeof(char) * str.size());
  return result;
}

**Comment by loadwiki** [comment]
The issue still exist in latest version.
In a go project c-rocksdb(go wrapper for rocksdb),the issue also exist.
My question is , is there a problem  for rocksdb go wrapper?

**Comment by yiwu-arbug** [comment]
I check a few C api and seems this is intended behavior. Since for example `rocksdb_get` also return the length of the value, we don't need to have '\0' at the end, and this allow us to return a value which may contain '\0' in the middle.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
