### ISSUE TITLE
Incorrect log message in BackgroundFlush

### ISSUE THREAD

**Issue by tcwalther** [facebook/rocksdb#2131]
The following log message in `BackgroundFlush` seems to have the wrong parameters passed:

```c++
ROCKS_LOG_BUFFER(
  log_buffer,
  "Calling FlushMemTableToOutputFile with column "
  "family [%s], flush slots available %d, compaction slots allowed %d, "
  "compaction slots scheduled %d",
  cfd->GetName().c_str(), immutable_db_options_.max_background_flushes,
  bg_flush_scheduled_, BGCompactionsAllowed() - bg_compaction_scheduled_);
```

In: https://github.com/facebook/rocksdb/blob/ff9728701614dcd5ea3ab019fe2fadebb6a8dd3f/db/db_impl_compaction_flush.cc#L1105-L1109

In particular, the _compaction slots allowed_ part prints `bg_flush_scheduled`, and the _compaction slots scheduled_ part prints `BGCompactionsAllowed() - bg_compaction_scheduled_`.

**Comment by yiwu-arbug** [comment]
Thank you for bring this up! Do you interest in sending a pull request to fix it?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
