### ISSUE TITLE
Sequence Number of WriteBatch

### ISSUE THREAD

**Issue by graetzer** [facebook/rocksdb#2146]
Is there a reason that the `WriteBatchInternal::Sequence(const WriteBatch*)` method, 
is only available in a private header?

It would be really helpful to be able to know the sequence number of a WriteBatch in the WAL,
or at least the sequence number of a committed transaction. Then we could use this number, when we want to tail the WAL. Currently I can't really see another way, other than to use the `GetLatestSequenceNumber` method

**Comment by yiwu-arbug** [comment]
We have no plan so far to expose sequence number of a write. I'm interested to know your use case though. Why do you want to tail the WAL?

**Comment by graetzer** [comment]
We are using RocksDB as a second storage engine for our database. We need a reliable count of inserted / deleted documents in our database without adding that much overhead.
We implemented this by periodically storing our counters in rocksdb. In the event of a crashed process, we restore the correct counter values by scanning the WAL for the PUTs and Deletes we miss. We needed the commit sequence number to figure out from which point to start scanning, without counting operations twice.

Anyways, thanks for getting back to me  :)
