### ISSUE TITLE
Test failure in SpatialDBTest.FeatureSetSerializeTest

### ISSUE THREAD

**Issue by mbakke** [facebook/rocksdb#2148]
I'm seeing a test failure in `spatial-db-test`.

```
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from SpatialDBTest
[ RUN      ] SpatialDBTest.FeatureSetSerializeTest
utilities/spatialdb/spatial_db_test.cc:99: Failure
Value of: !deserialized.Deserialize(serialized)
  Actual: false
Expected: true
terminate called after throwing an instance of 'testing::internal::GoogleTestFailureException'
  what():  utilities/spatialdb/spatial_db_test.cc:99: Failure
Value of: !deserialized.Deserialize(serialized)
  Actual: false
Expected: true
```

The contents of `serialized` here is "\030\000\000\000\000\000\000\000\000\n@\001a\004\001".

1. Is this the expected contents of the `serialized` string?
2. If so, why is it getting deserialized successfully?

The environment is zlib-1.2.11,  snappy-1.1.3, lz4-1.7.5, jemalloc-4.5.0, gcc-5.4.0 and glibc-2.25 on GNU Guix. Thanks in advance!

**Comment by siying** [comment]
Are you using SpatialDB? We are not actively maintaining it.

**Comment by mbakke** [comment]
I'm not. I only build RocksDB since Ceph requires it. At least I know it's safe to disable this test, thanks!

**Comment by siying** [comment]
@mbakke yes it's safe to ignore. I just realized that it is failing on GCC-5 and passes on 4.8 and 4.9. We'll fix or disable the test.

**Comment by siying** [comment]
@mbakke I hope this is fixed with https://github.com/facebook/rocksdb/commit/ca96654d8550bca727ecdd2d79e211b82fc76ec4
