### ISSUE TITLE
Lua specified merge operation

### ISSUE THREAD

**Issue by Downchuck** [facebook/rocksdb#2162]
Can the RocksDB Lua CompactionFilter work also be extended to support Lua-based merge operations?

**Comment by lightmark** [comment]
It can be extend but just not in our roadmap. Would you like to contribute?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by johnjamespj** [comment]
@lightmark Can try to extend Lua support to merge operations?
