### ISSUE TITLE
how to split or merge RocksDB instance   over HDFS

### ISSUE THREAD

**Issue by jerousrb** [facebook/rocksdb#2201]
Hi, Can I ask a few question? 
     first,if we through the rocksDb env_hdfs with the deployment of a three node (D E F)distributed HDFS. we open a DB( named A) with two columnfamilys(named CF1 CF2) on node D; then we close DB A on node D. can we open this DB (with CF1) on node E, another this DB (with CF2) on node F , the both support write and read?   There are some problem with this use? 

 another question, Do you known how to split one RocksDB into two or more Db, which contain a portion data of the parent DB? thanks. 

@siying

**Comment by siying** [comment]
All column families of a DB has to be opened all together. There isn't a way you can close a column family in one service and open it in another one.

**Comment by jerousrb** [comment]
in the repair::AddTables， this function add all file into level 0,  How to distinguish between old and new data in different sstable(level 0 or level N)?   @siying

**Comment by jerousrb** [comment]
if we split manifest into two part, and update the reference sstale info in storage info,  can we split one db into two? @siying    @lightmark

**Comment by lightmark** [comment]
Any key in SSTable file is associated with a sequence number which denotes whether it is newer or older. So even we put all files on Level 0, the consistency of db is preserved.

I don't think there is a way to split manifest...

**Comment by jerousrb** [comment]
we can scan the manifest and update the FileMetaData (smallest largest ) of all the sst table to build version. then write snapshot about the version . @lightmark

**Comment by clark010** [comment]
Hi, @jerousrb 
    Have you already solved this problem? Or do you have any new idea about it?
Now i run into this problem too, that is, I want to split one db and merge part of it into another one, 
my idea is:
1. Read all first db's sst files and skip all unnecessary keys then write left parts to a new sst file
    a. before reading, we need sort all sst files according to their levels and sequence num(min/max), just like the process of read path
    b.need modify the index part(smallest or largest key)
    c. sequence num can be replaced by 0?(not sure)
2. ingest all the sst files into the new rocksdb
    a. first inserted record should not be overwrote by later one(ingest_behind=true)
But now i'm not sure if it's ok in step 1.a to sort sst file and 1.c to process sequence num
Any suggestion about that @siying @lightmark

**Comment by jerousrb** [comment]
hi，@clark010 
 now we decide to experiment this idea:
1. accoding to the verison info  and the manifest , we  scan all the sst file storage info, select the file (key range in right side) update the fd info(smallest or largest key)  then write to a new manifest; other info(CF info ) will keep with the left DB;
2. in the right db, add a new refer_table_reader to this file(the old file contain left and right side key range), we reader the old file, filter out range key.

**Comment by jerousrb** [comment]
hi，@siying @lightmark
In the RocksDB ,  the  memory  ,Arena allocate from system, can be shared in the Multiple DB instances ？
this memory   is shared among multiple CF ,yes ?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
