### ISSUE TITLE
Removing deprecated files in the java repo

### ISSUE THREAD

**Issue by Banu27** [facebook/rocksdb#2210]
I found the presence of java files `BackupableDB.java` and `RestoreBackupableDB.java` confusing while trying to upgrade to recent versions of rocksdb from an older version that used these classes. Is there any reason they are still existing in the repo?

Thanks!

**Comment by adamretter** [comment]
@Banu27 Good spot. Seems like these were previously left in by mistake. I have opened a PR to remove them and clean up the references here - https://github.com/facebook/rocksdb/pull/2212
