### ISSUE TITLE
rocksdbjni 5.2.1 in maven central repo not contain librocksdbjni-win64.dll

### ISSUE THREAD

**Issue by lcy362** [facebook/rocksdb#2215]

**Comment by adamretter** [comment]
@lcy362 Apologies it seems to have been missed form the multi-platform jar, however it is present in the Win64 jar, so you could just use that as a workaround until the next release - https://search.maven.org/remotecontent?filepath=org/rocksdb/rocksdbjni/5.2.1/rocksdbjni-5.2.1-win64.jar
