### ISSUE TITLE
Add Support for Bulk Loading older data with FIFO Compaction approach

### ISSUE THREAD

**Issue by vuzilla** [facebook/rocksdb#2227]
Our use case is this.
- We create a new cluster.  It starts receiving newer record updates almost immediately, but is not yet being read from.
- We want to back-fill the older data from another cluster.  However, we want the records currently being written to take precedence.

So for FIFO, we want to add SST files to the end of L0, so it's the last SST to be checked in L0.  In this case, there wouldn't be a need to merge any SST's--just add to the end of L0.

Thanks

Vu

**Comment by siying** [comment]
What @mikhail-antonov and @lightmark are doing about bulkloading old data should be easily applicable to FIFO compaction.

**Comment by vuzilla** [comment]
Is this the change you're referencing?
https://github.com/facebook/rocksdb/pull/2202

I can try the latest release out to verify that it works with FIFO Compaction.

Thanks

Vu

**Comment by mikhail-antonov** [comment]
#2144 for ingest of older data with universal compaction, see reviews and comments there, in progress
#2202 is for normal ingest (overwriting existing data) with universal compactions

**Comment by mikhail-antonov** [comment]
@vuzilla  i'm not sure current approach is easily portable to FIFO compactions (which I haven't looked at yet), but we can certainly look into it.

Conceptually the usecase you described is exactly what i want for universal in #2144

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
