### ISSUE TITLE
Crash on win64 

### ISSUE THREAD

**Issue by acipolletti** [facebook/rocksdb#2229]
Hi i successfully compiled a static 64 bits release of rocksdb library, using both vs2015 and vs2017.
After i create a very simple 64bits console application , using following code

#include <cassert>
#include "rocksdb/db.h"
#pragma comment(lib, "Rpcrt4.lib")

int main()
{
	rocksdb::DB* db;
	rocksdb::Options options;
    return 0;
}

but when start , the executable crash with the exception in the attached file.
![exception](https://cloud.githubusercontent.com/assets/422082/25520707/2b01e3ba-2bfd-11e7-87a8-d8e580eb8e6d.png)

**Comment by yuslepukhin** [comment]
@acipolletti Run CMake with -DWITH_AVX2=0 as your hardware does not support AVX2 instructions.

**Comment by acipolletti** [comment]
Fixed. Thanks a lot.
