### ISSUE TITLE
rocksdb v5.3.3 jars not available in maven

### ISSUE THREAD

**Issue by bharatviswa504** [facebook/rocksdb#2241]
RocksDB v 5.3.3 is released, but jars are not available in maven repo.
> Could not find org.rocksdb:rocksdbjni:5.3.3.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/5.3.3/rocksdbjni-5.3.3.pom
      https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/5.3.3/rocksdbjni-5.3.3.jar

**Comment by yiwu-arbug** [comment]
We found issue with java build with 5.3.3. We are likely to have a minor version release to fix that. Stay tune. cc @sagar0

**Comment by bharatviswa504** [comment]
@yiwu-arbug Thanks for info.. So, rocksdb 5.3.4 version jars when it will be available in maven?

**Comment by sagar0** [comment]
@bharatviswa504 yeah, they will be available in maven soon. @adamretter is working on building the jars to add to maven repo.

**Comment by bharatviswa504** [comment]
@sagar0 Thanks for info..

**Comment by bharatviswa504** [comment]
@adamretter 
@sagar0 I am still not able to use 5.3.4 rocksdb jar, as they are not available in maven.
Could you please let me know, when they will be available.

**Comment by sagar0** [comment]
5.3.4 jars will be available soon, may be in a few days. We were running into a jar build issue due to Centos 5 EOL, but it is now fixed in https://github.com/facebook/rocksdb/pull/2270.

**Comment by adamretter** [comment]
@bharatviswa504 I just released 5.3.4 to Maven Central. It will appear there during the next 2 hours (as they have a sync period from staging).
