### ISSUE TITLE
Iterators that do not load value in memory

### ISSUE THREAD

**Issue by HassanCehef** [facebook/rocksdb#2243]
Hi,

In the usage I do of rocks, I store meta-data as part of the key. It works perfectly fine with prefix iterators. Sometimes, I have to perform a sort of garbage collection, which executes Deletes depending on the metadata of the key (in a coarse way). The idea is that I iterate over all the keys I store, to know if I can get rid of some keys. Thus, in the garbage collection phase, I never have to call value(). And yet the value is loaded in memory. This is useless IO for this usage.

I would like to have an iterator that does not load the value in memory. After looking in the code, I did not find any option to do that.

1. Is there an option that I would have missed?
1. Could you give me a few pointers on where the IO is performed, so I can disable it? I am currently digging into the Seek/Next/value methods of different Iterators.
1. I will probably have to do it anyway; would you like a PR afterwards? Is this a use-case you would like to have/feel is useful?
1. Is what I'm doing completely dumb, and I should rely on another Column Family to store metadata for instance?

Thanks 😸

**Comment by IslamAbdelRahman** [comment]
Hi @HassanCehef 
This is not possible, RocksDB stores multiple keys and values together in a single block, we need to read the whole block from the device and decompress it to extract the key and value. So it's not possible to *only read keys*

**Comment by HassanCehef** [comment]
Hi @IslamAbdelRahman 
Thanks for your answer. I will find a workaround then.
