### ISSUE TITLE
how filter some data from get and iterator?

### ISSUE THREAD

**Issue by jerousrb** [facebook/rocksdb#2244]
If i want to filter out some of the key data within the rocksdb，how to achieve?
for example，one rocksdb already contains  data in range[10-1000]，but now  i just want to read some range[600-1000] of the data. in particular, i hope the iterator also does not contain the out range[10-599] data for next \ pre seektofirst.  thinks!

  @siying  @lightmark

**Comment by lightmark** [comment]
We have iterate_upper_bound but not iterate_lower_bound. It is symmetric, do you want to contribute?

**Comment by jerousrb** [comment]
thanks for you answer. @lightmark 
     this function  iterate_upper_bound   implementation is in the wrapper iterator （NewDBIterator）, why not to process iterate_upper_bound  in the  the bottom of the iterator （such as block iterator）, avoid reading more data into memory？

**Comment by lightmark** [comment]
We read block in a whole, so it makes little sense in block iterator. But I already has a PR to process it in two_level_iterator which may be what you want.
https://github.com/facebook/rocksdb/pull/2239
