### ISSUE TITLE
Rocksbdjni: java.lang.RuntimeException: librocksdbjni-win64.dll was not found inside JAR.

### ISSUE THREAD

**Issue by ccleve** [facebook/rocksdb#2251]
Version 5.2.1 fails with the exception in the title.  I can confirm that the .dll is not in the .jar.

Please double check that it's included in 5.3.4 when that comes out. Thanks. @adamretter

**Comment by adamretter** [comment]
@ccleve I just released 5.3.4 to Maven Central (it will appear in the next 2 hours).
