### ISSUE TITLE
Ingesting sst files with addFile error

### ISSUE THREAD

**Issue by h-1** [facebook/rocksdb#2261]
Hi,

I am trying to implement [Creating and Ingesting SST files](https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files) in Java. I was able to create the SST files, but I am not able to ingest it into the db.

I tried `addFileWithFileInfo` but got this error: `java.lang.UnsatisfiedLinkError: org.rocksdb.RocksDB.addFile(JJ[JIZ)V` which seems like `addFile` is the old implemnetation, the new one is IngestExternalFile. Though I am not able to see `IngestExternalFile` in Java.

Any suggestions?

Thanks for the help!

**Comment by IslamAbdelRahman** [comment]
Which RocksDB version are you using ?
CC: @mikhail-antonov

**Comment by h-1** [comment]
I am using [5.2.1](https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni/5.2.1).

**Comment by mikhail-antonov** [comment]
I used SstFileWriter successfully from Java with subsequent ingest in C++, but not sure I did ingest from Java.

Looking at the code, https://github.com/facebook/rocksdb/blob/master/java/rocksjni/rocksjni.cc#L2174 - AddFile in JNI layer called IngestExternalFile internally (in C++).

Unsatisfied link error indicates that JNI signature doesn't match.. (JJ[Ljava/lang/String;IZ)V is the signature to be used, not sure where your signature comes from.

**Comment by mikhail-antonov** [comment]
Also this should be something we should be able to reproduce easily.

**Comment by h-1** [comment]
@mikhail-antonov 

I actually tried the same thing you did. Created SST file with Java, loaded with C++. I had no problems as well. The problem only happens with Java loading. Below is a sample code that generates the error.

`   public static void main(String[] args) throws Exception {

    Options options = new Options();
    options.setCreateIfMissing(true);
    String filePath = "/Documents/sst";

    SstFileWriter sstFileWriter = new SstFileWriter(new EnvOptions(), options, new BytewiseComparator(new ComparatorOptions()));

    sstFileWriter.open(filePath);
    sstFileWriter.add(new Slice("key1"), new Slice("1"));
    sstFileWriter.add(new Slice("key2"), new Slice("2"));
    sstFileWriter.finish();

    RocksDB db = RocksDB.open("/Documents/");
    ExternalSstFileInfo externalSstFileInfo = new ExternalSstFileInfo();
    externalSstFileInfo.setFilePath(filePath);
    externalSstFileInfo.setNumEntries(2);
    externalSstFileInfo.setSmallestKey("key1");
    externalSstFileInfo.setLargestKey("key2");
    db.addFileWithFileInfo(externalSstFileInfo);
    db.close();
}
`

**Comment by mikhail-antonov** [comment]
Hmm...So this is Java method being called:

```
private native void addFile(long handle, long cfHandle, long[] fiHandleList, int fiHandleListLen,
      boolean moveFile) throws RocksDBException;
```

There's also a similar method in Java with signature:
```
private native void addFile(long handle, long cfHandle, String[] filePathList,
      int filePathListLen, boolean moveFile) throws RocksDBException;
```

But in JNI header, only the latter one has signature:
```
/*
 * Class:     org_rocksdb_RocksDB
 * Method:    addFile
 * Signature: (JJ[Ljava/lang/String;IZ)V
 */
void Java_org_rocksdb_RocksDB_addFile__JJ_3Ljava_lang_String_2IZ(
    JNIEnv* env, jobject jdb, jlong jdb_handle, jlong jcf_handle,
    jobjectArray jfile_path_list, jint jfile_path_list_len,
    jboolean jmove_file) {

```

So that does look like a bug. Let me have a look. Thanks for the report!

**Comment by mikhail-antonov** [comment]
From what I can see, we only support passing in list of file_paths of the files being ingested in the new api - https://github.com/facebook/rocksdb/blob/master/include/rocksdb/db.h#L955

@adamretter @IslamAbdelRahman do we really need to many variances of AddFile methods in Java api? E.g. where would we need an api that accepts ExternalSstFileInfo object with populated fields (other than file_path)?

**Comment by adamretter** [comment]
So I started looking at this yesterday. @h-1 is getting this error because it seems that whoever added support for addFile missed off half the implementation that they intended :-(

addFile in the C++ code is now deprecated in favour of IngestExeternalFile. I will likely send a PR tomorrow now that addresses that.
