### ISSUE TITLE
The performance issuse about prefix seek

### ISSUE THREAD

**Issue by lanxia** [facebook/rocksdb#2263]
Recently, I have done many tests to compare the performance of **Seek** between the prefix mod and the non prefix mod. But all test shows that the performance of prefix seek is a bit slower than normal seek. This 
result does not meet expectation. I doubt that my test is wrong in somewhere, anyone have experience with such test?

**Comment by yiwu-arbug** [comment]
cc @lightmark any idea?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
