### ISSUE TITLE
Merge operator giving stale data

### ISSUE THREAD

**Issue by gauravyadav7** [facebook/rocksdb#2273]
I am using a rocksdb instance in production, with 128 column families and inserting/updating small key/value pairs in the order of 75000 keys/second. I am running a test which verifies these key/value pairs as well. After few hours, for few keys I get stale/old data. And when I try to re-lookup keys (without any further inserts/updates), I get the latest/right data back.
I have my custom merge operator and I added few logs in the custom merge operator, only to find that when I am getting stale data, merge operator is not being called at all and blindly giving an older/stale value. But, when I re-lookup the same key after few minutes, merge operator is called correctly and I get latest data.
Has anyone seen this issue before ?

It is a very random scenario and behavior is not predictable at all. For same test, sometimes it even passes without any issue.
I am not sure if I will be able to reproduce this behavior in a stand alone test, so I was just wondering if anyone has seen this issue before ?
Also, I do not see any errors in rocksdb logs.
 
Please see rocksdb options below that I am using. Let me know if you need any other information.
RocksDB version: 4.0.0
Rocksdb options set:
    options_.keep_log_file_num = 2;
    options_.log_file_time_to_roll = 300;
    // 1M individual log files.
    options_.max_log_file_size = 1048576;
    options_.info_log_level = rocksdb::InfoLogLevel::ERROR_LEVEL;
    options_.arena_block_size = 4096;
    options_.compression = rocksdb::CompressionType::kSnappyCompression;
    options_.max_write_buffer_number = 4;
    options_.disableDataSync = true; 
    options_.verify_checksums_in_compaction = false;
    options_.create_if_missing = true;
    options_.allow_mmap_reads = false;
    options_.allow_mmap_writes = false;
    options_.num_levels = 6;
    options_.max_mem_compaction_level = 3;
    options_.delete_obsolete_files_period_micros = 10 * 1000l * 1000l;
    options_.max_background_flushes = 4;
    options_.max_background_compactions = 3;
    options_.level0_file_num_compaction_trigger = 2;
    options_.level0_stop_writes_trigger = 512;
    options_.level0_slowdown_writes_trigger = 256;
    options_.target_file_size_base = 2 * 1024 * 1024;
    options_.target_file_size_multiplier = 1; 
    options_.max_bytes_for_level_base = 8 * options_.target_file_size_base;
    options_.max_bytes_for_level_multiplier = 8;
    options_.db_write_buffer_size = 16 * 1024 * 1024;
    options_.compaction_style = rocksdb::kCompactionStyleLevel;
    options_.allow_os_buffer = true;
    options_.OptimizeLevelStyleCompaction(16 * 1024 * 1024);
    options_.write_buffer_size = 16 * 1024 * 1024;
    options_.max_manifest_file_size = 10 * 1024 * 1024;
    options_.manifest_preallocation_size = 10 * 1024 * 1024;
    options_.is_fd_close_on_exec = true;
    options_.stats_dump_period_sec = 300;
    options_.max_open_files = 64 * 1024;
    options_.min_write_buffer_number_to_merge = 1;
    options_.use_fsync = false;
    rocksdb::BlockBasedTableOptions table_options;
    table_options.filter_policy.reset(rocksdb::NewBloomFilterPolicy(10));
    table_options.cache_index_and_filter_blocks = false;
    table_options.block_size = 4 * 1024;
    table_options.block_size_deviation = 2;
    options_.table_factory.reset(rocksdb::NewBlockBasedTableFactory(table_options));
    options_.db_log_dir = logdir;
    writeOptions_.disableWAL = true;
    writeOptions_.sync = false;
    readOptions_.verify_checksums = false;
    readOptions_.fill_cache = true;
    options_.max_write_buffer_number = 16;
    options_.allow_mmap_reads = true;
    options_.db_write_buffer_size = 
    options_.max_write_buffer_number * options_.write_buffer_size;
    options_.merge_operator = std::make_shared<CustomKeyMergeOperator>();
    options_.comparator = new CustomKeyComparatorOperator();

For each of 128 column families:
    cfOptions_ = options_;
    cfOptions_.memtable_prefix_bloom_bits = 131072;
    cfOptions_.arena_block_size = 4096;
    cfOptions_.memtable_prefix_bloom_probes = 6;
    cfOptions_.filter_deletes = false;
    cfOptions_.OptimizeForPointLookup(64);

**Comment by yiwu-arbug** [comment]
Is it possible the write and the read happen on different thread, and that you try to read the key before the write had returned? When you write, are you using transaction, write batch, or a simple Merge? When you read, are you using Get, MultiGet or iterators?

Also, can you try a more recent release (e.g. v5.3.4) to see if it can be reproduce? A standalone test will definitely help with the investigation.

**Comment by gauravyadav7** [comment]
My test runs with 64 threads, with all of them doing read and writes. My test always makes sure to read a key only after it has been successfully written. And I use these steps:

INSERT ->
1. rocksdb::WriteBatch batch 
2. batch.Merge(columnFamilyHandle, key, value) // Multiple such entries before calling Write()
3. rocksDBInstance->Write(writeOptions_, batch)

LOOKUP ->
rocksDBInstance->Get(readOptions_, columnFamilyHandle, key, value);

I am planning to use newer release and test out again. Will let you know how it goes

**Comment by gauravyadav7** [comment]
I was not able to reproduce this issue with latest (>5.0) version of RocksDB
