### ISSUE TITLE
Linking RocksJava on Windows 10

### ISSUE THREAD

**Issue by adamretter** [facebook/rocksdb#2297]
I have been trying to build better RocksJava artifacts for our Windows users by including the 3rd-party compression libraries (Snappy, LZ4 and ZLib), as such I have followed a process which I have described here: https://github.com/facebook/rocksdb/wiki/Building-on-Windows

However, both the resultant `build\java\Release\rocksdbjni.lib` and `build\java\Release\rocksdbjni.dll` when examined with `dumpbin /exports` seem to show that they only contain the symbols for RocksJava and LZ4. I would also expect them to contain the symbols for Snappy and ZLib.

When I check dependencies, the `rockdbjni.lib` shows none, but weirdly is only ~306KB in size:

```
C:\Users\aretter\code\rocksdb\build>dumpbin /dependents java\Release\rocksdbjni.lib
Microsoft (R) COFF/PE Dumper Version 14.00.24213.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file java\Release\rocksdbjni.lib

File Type: LIBRARY

  Summary

          CC .debug$S
          14 .idata$2
          14 .idata$3
           8 .idata$4
           8 .idata$5
          10 .idata$6
```

whilst `rocksdbjni.dll` shows dependencies on Snappy (`snappy64.dll`) and ZLib (`zlibwapi.dll`) yet is ~4.10MB in size:
```
C:\Users\aretter\code\rocksdb\build>dumpbin /dependents java\Release\rocksdbjni.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24213.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file java\Release\rocksdbjni.dll

File Type: DLL

  Image has the following dependencies:

    snappy64.dll
    zlibwapi.dll
    Cabinet.dll
    RPCRT4.dll
    MSVCP140.dll
    VCRUNTIME140.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-convert-l1-1-0.dll
    api-ms-win-crt-time-l1-1-0.dll
    api-ms-win-crt-environment-l1-1-0.dll
    api-ms-win-crt-filesystem-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    KERNEL32.dll

  Summary

       14000 .data
        1000 .gfids
       1F000 .pdata
       ED000 .rdata
        3000 .reloc
        1000 .rsrc
      304000 .text
        1000 .tls
```

I am a bit confused by what is going on here. Java requires a .dll for JNI on Windows, and it looks like the .dll has LZ4 statically linked in, but for some reason has dynamically linked in Snappy and ZLib when they should have been statically linked in. 

Could someone shed some light on the linking of `librockjni.dll` on Windows?
@yuslepukhin Sorry to ask, but I suspect you are the most knowledgable in this area.

**Comment by yuslepukhin** [comment]
@adamretter you are linking to DLLs so your symbols may be only in the import table but not in the executable. You may want to link to static version of the libraries which is somewhat better perfwise.

**Comment by adamretter** [comment]
@yuslepukhin Okay, excuse my ignorance but in the `thirdparty.inc` file that you added I have set the paths to be the `.lib` libraries. I was under the impression that `.lib` was a statically linked library?

**Comment by yuslepukhin** [comment]
@adamretter I understand the frustration that may come with it. The tidbit that is helpful to know is that you can not really tell if .lib is a static library. A size may give you a hint.
On Windows when you link to a library you always link to a .lib. However, that library may be a static library OR it may be a IMPORT library that accompanies a corresponding DLL. 
When a DLL is build a corresponding IMPORT .lib file is always built. You never specify the actual DLL file to the linker.
I can not change this fact but I can tell you about it.

**Comment by PaulWoods4422** [comment]
Looking at your how to build on windows page I can see you are pulling in the import library for ZLib

> The resultant static library can be found in %CODE_HOME%\zlib-1.2.11\contrib\vstudio\vc14\x64\ZlibDllDebug\zlibwapi.lib or %CODE_HOME%\zlib-1.2.11\contrib\vstudio\vc14\x64\ZlibDllRelease\zlibwapi.lib.

( Notice ZLibDllRelease ) you want the static library at vc14\x64\ZlibStatRelease\zlibstat.lib
For Snappy there is no static lib target in the project, and it's not just a case of changing the configuration type unfortunately.  If I get time I will have a go at building Snappy as a static lib and get back to you.

**Comment by adamretter** [comment]
@PaulWoods4422 Ah ha! Thank you Paul that is very useful. I have updated the Wiki page with your info about ZLib. I also opened an issue enquiring about a static library build for the Snappy port here - https://bitbucket.org/robertvazan/snappy-visual-cpp/issues/3/static-library

**Comment by PaulWoods4422** [comment]
I found a project here that might be useful - I needed to convert the project file to VS2015, and then create a 64 bit config ( the same as you did for gFlags ) https://github.com/kmanley/snappy-msvc 
I haven't tried the resulting library though.

**Comment by adamretter** [comment]
@PaulWoods4422 so using https://github.com/kmanley/snappy-msvc I followed this procedure:

1. Download snappy from http://code.google.com/p/snappy and extract to <snappy_dir>
2. Open Developer Command Prompt for VS2015
3. cd snappy_dir
4. git clone https://github.com/kmanley/snappy-msvc
5. cd snappy-msvc
6. devenv snappy.sln /upgrade
7. Open the solution in Visual Studio and create an x64 target from the 32 bit target. Close Visual Studio.
8. msbuild snappy.sln

Unfortunately the build fails for me with a whole bunch of errors:
```
"C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\snappy.sln" (default target) (1) ->
"C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\snappy.vcxproj" (default target) (2) ->
(ClCompile target) ->
  ..\snappy.cc(98): error C2061: syntax error: identifier 'ssize_t' [C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\sna
ppy.vcxproj]
  ..\snappy.cc(102): error C2065: 'len': undeclared identifier [C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\snappy.v
cxproj]
  ..\snappy.cc(140): error C2061: syntax error: identifier 'ssize_t' [C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\sn
appy.vcxproj]
  ..\snappy.cc(143): error C2065: 'len': undeclared identifier [C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\snappy.v
cxproj]
  ..\snappy.cc(146): error C2065: 'len': undeclared identifier [C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\snappy.v
cxproj]
  ..\snappy.cc(150): error C2065: 'len': undeclared identifier [C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\snappy.v
cxproj]
  ..\snappy.cc(1108): error C2660: 'snappy::IncrementalCopy': function does not take 3 arguments [C:\Users\aretter\code
\snappy-1.1.3\snappy-msvc\snappy.vcxproj]
  ..\snappy.cc(1209): error C2660: 'snappy::`anonymous-namespace'::IncrementalCopyFastPath': function does not take 3 a
rguments [C:\Users\aretter\code\snappy-1.1.3\snappy-msvc\snappy.vcxproj]
  ..\snappy.cc(1214): error C2660: 'snappy::IncrementalCopy': function does not take 3 arguments [C:\Users\aretter\code
\snappy-1.1.3\snappy-msvc\snappy.vcxproj]

    42 Warning(s)
    9 Error(s)
```

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
