### ISSUE TITLE
RocksJava builds are failing on Travis

### ISSUE THREAD

**Issue by sagar0** [facebook/rocksdb#2299]
All RocksJava builds on Travis are failing, across linux/mac with both gcc/clang. 
Example: https://travis-ci.org/facebook/rocksdb/builds/232466228
```
clang: error: no such file or directory: 'util/build_version.cc'
clang: error: no input files
make: *** [jl/util/build_version.o] Error 1
```

**Comment by adamretter** [comment]
@sagar0 Yeah, I looked into Travis and saw the build failures for the file `util/build_version.cc` in RocksJava. Unfortunately the `Makefile` and the Travis config have become complicated to a state where I can't figure out why this fails for RocksJava and not for Rocks itself.

It seems that `util/build_version.cc` is not generated by the `Makefile` for when make is called with the targets `clean jclean rocksdbjava` in Travis but I can't see why?!?

**Comment by yiwu-arbug** [comment]
It looks to me `make clean` is executed after build_version.cc being generated. I'm trying to split the command into `make clean jclean && make rocksdbjava jtest`. Testing it out with a test branch: https://travis-ci.org/facebook/rocksdb/builds/232621078

**Comment by yiwu-arbug** [comment]
Looks like it fix the issue. Will send a fix.
