### ISSUE TITLE
Linking issue

### ISSUE THREAD

**Issue by marijnfs** [facebook/rocksdb#2304]
I can't for the life of me figure out how to properly link rocksdb in windows (linux is no problem). I build rocksdb myself, had to deselect MT so that it was compilable, and add the Rpcrt4.lib to my project. Now I'm left with two linking errors, which seem to pertain to the compression? Any suggestion here?

```
main.obj : error LNK2001: unresolved external symbol "public: struct rocksdb::ColumnFamilyOptions * __cdecl rocksdb::ColumnFamilyOptions::OptimizeLevelStyleCompaction(unsigned __int64)" (?OptimizeLevelStyleCompaction@ColumnFamilyOptions@rocksdb@@QEAAPEAU12@_K@Z)
main.obj : error LNK2001: unresolved external symbol "public: struct rocksdb::DBOptions * __cdecl rocksdb::DBOptions::IncreaseParallelism(int)" (?IncreaseParallelism@DBOptions@rocksdb@@QEAAPEAU12@H@Z)
```

**Comment by adamretter** [comment]
This is how we do it - https://github.com/facebook/rocksdb/wiki/Building-on-Windows

**Comment by marijnfs** [comment]
Thanks, i'm getting further with it but get stuck with the snappy instructions. When using the command line build commands I get
`fatal error C1083: Cannot open include file: 'Windows.h':`
and if I load the .sln in visual studio to add wherever the windows.h should be, I can't build it.

**Comment by adamretter** [comment]
@marijnfs Which version of Windows and which version of Visual Studio. I am using Windows 10 and Visual Studio 2015 Community

**Comment by marijnfs** [comment]
I'm using the exact same. If I want to build within visual studio it asks me to install Windows XP support? Really strange.

**Comment by marijnfs** [comment]
I tried the steps again and still get the same error (gflags builds btw). 
The second error I get (in the same build) is:
`LINK : fatal error LNK1104: cannot open file 'snappy64.lib' [C:\Users\marijn\Software\snappy-visual-cpp\runtests\runtests.vcxproj]`
Something about the paths doesn't seem to work out?

**Comment by adamretter** [comment]
We don't build within Visual Studio, we do it all from the command line as indicated in that Wiki article so I am not sure I can comment on that. I will get a fresh copy of `snappy-visual-cpp` and see if I have any problems, it is not impossible that I perhaps forgot to document some required step

**Comment by marijnfs** [comment]
Yeah I wonder if there is some command to add include directories perhaps? Maybe something you already happen to have in your environment variables.

**Comment by marijnfs** [comment]
Another point that might cause the problems, I keep messages saying I should Install Windows XP support for C++? Is this necessary?

**Comment by marijnfs** [comment]
Ok I have made progress by installing the Windows XP support after some trail and error. Now the error I'm left with is:

`error : This project references NuGet package(s) that are mis sing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. Th e missing file is ..\packages\Snappy.1.1.1.7\build\native\Snappy.props. `

However NuGet seems to be there, not sure how to progress now? Anyway, apparently Windows XP support is a requirement for building snappy!

**Comment by adamretter** [comment]
@marijnfs Ah okay. Yes I get the NuGet error too and have devised a workaround - I have updated the Wiki page for you with the details.

**Comment by marijnfs** [comment]
I'm still not able to get everything compiled, especially because I need MT linking due to another lib (windows is such a pain). Do you perhaps have any precompiled libraries ready? (amd64)

**Comment by adamretter** [comment]
@marijnfs Where exactly do you get stuck? If you want a static library, then you should exclude Snappy, as we don't have a way to build that as a static library yet. If you just want binaries, you can find them on Maven Central.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by gencer** [comment]
@adamretter , I have the same issue. The fact is, I installed RocksDB using `vcpkg`. VS finds the include files, I manually added `rocksdb-sharedd.lib` and `zlibd.lib` files, however I got following issues on new created project. (_Multi Threaded Debug DLL_)

```
1>------ Build started: Project: ConsoleApplication1, Configuration: Debug Win32 ------
1>ConsoleApplication1.cpp
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: struct rocksdb::ColumnFamilyOptions * __thiscall rocksdb::ColumnFamilyOptions::OptimizeLevelStyleCompaction(unsigned __int64)" (?OptimizeLevelStyleCompaction@ColumnFamilyOptions@rocksdb@@QAEPAU12@_K@Z) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: __thiscall rocksdb::ColumnFamilyOptions::ColumnFamilyOptions(void)" (??0ColumnFamilyOptions@rocksdb@@QAE@XZ) referenced in function "public: __thiscall rocksdb::Options::Options(void)" (??0Options@rocksdb@@QAE@XZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: struct rocksdb::DBOptions * __thiscall rocksdb::DBOptions::IncreaseParallelism(int)" (?IncreaseParallelism@DBOptions@rocksdb@@QAEPAU12@H@Z) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: __thiscall rocksdb::DBOptions::DBOptions(void)" (??0DBOptions@rocksdb@@QAE@XZ) referenced in function "public: __thiscall rocksdb::Options::Options(void)" (??0Options@rocksdb@@QAE@XZ)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: static class rocksdb::Status __cdecl rocksdb::DB::Open(struct rocksdb::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class rocksdb::DB * *)" (?Open@DB@rocksdb@@SA?AVStatus@2@ABUOptions@2@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAPAV12@@Z) referenced in function _main
1>C:\Users\gence\source\repos\ConsoleApplication1\Debug\ConsoleApplication1.exe : fatal error LNK1120: 5 unresolved externals
1>Done building project "ConsoleApplication1.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```

I am suspecting that there are _more dependencies_ than `zlib` and `vcpkg` did not installed them.

**Comment by gencer** [comment]
Ah, It seems the problem is here: https://github.com/Microsoft/vcpkg/issues/2411
