### ISSUE TITLE
Java Merge API crashes if value is longer than certain length (like 32 bytes)

### ISSUE THREAD

**Issue by scv119** [facebook/rocksdb#2313]
Note this is a heisenbug.

Testing this on Mac 10.12.4 and java version "1.8.0_91"

Test case: https://github.com/scv119/rocksdb/commit/a568701e8e122ce853693047748aad4eec4d8360

Error Log: 
```
make jtest 
....
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010347a60c, pid=26409, tid=6915
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x47a60c]
#
# Core dump written. Default location: /cores/core or core.26409
#
# An error report file with more information is saved as:


# /Users/chenshen/src/rocksdb/java/hs_err_pid26409.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
make[1]: *** [run_test] Abort trap: 6 (core dumped)
make: *** [jtest] Error 2
```

JVM Crash Log:
https://gist.github.com/scv119/11d1a10a850c7596f889b267b97f5f0b
https://gist.github.com/scv119/d741212f9d0c1d2f7fba0bef5340dd8f
https://gist.github.com/scv119/354e75094e9c18a5b8dbe46c2ff0f143

**Comment by siying** [comment]
Can you try to include this diff/ https://github.com/facebook/rocksdb/commit/3a04a254ac4b782fbe6b8521e0c77f3311f0d98c

**Comment by scv119** [comment]
@siying seems that commit fix the issue, I no longer reproduce this in my unittest.

**Comment by scv119** [comment]
I think this issue is resolved, I no longer encounter this bug once rebased onto the rev @siying provided.
