### ISSUE TITLE
RocksDb jni : 5.3.4 initialization error

### ISSUE THREAD

**Issue by hari-rangarajan** [facebook/rocksdb#2319]
/devtools/jdk1.8.0_102/bin/java: symbol lookup error: /tmp/librocksdbjni4846178717713967486.so: undefined symbol: ZSTD_versionNumber

**Comment by jamespedwards42** [comment]
@hari-rangarajan Should be fixed in the next release thanks to @adamretter: https://github.com/facebook/rocksdb/issues/2280

**Comment by adamretter** [comment]
We have now release 5.3.6 which I believe addresses this.
