### ISSUE TITLE
How to improve performance to get all keys in the case of very big data

### ISSUE THREAD

**Issue by yizishou** [facebook/rocksdb#2323]
I have hundreds of 8Bytes-Key-500M-Value pairs in my db, and I want to get a list of these keys.

But it takes me almost 10 minutes to finish the iteration.

I kept all options by default, is there any options can help?

**Comment by yizishou** [comment]
consider add a Key Iterator?

**Comment by lightmark** [comment]
We are gonna have blob storage soon. I think it is already in master branch, though not stable, if you want to try it.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
