### ISSUE TITLE
Update github releases

### ISSUE THREAD

**Issue by JelteF** [facebook/rocksdb#2327]
[HISTORY.md](https://github.com/facebook/rocksdb/blob/master/HISTORY.md) says that both rocksdb 5.4 and 5.5 have been released. However this is not reflected by the [github releases page](https://github.com/facebook/rocksdb/releases).

**Comment by yiwu-arbug** [comment]
Both versions are going through release pipeline. Please refer to the github release page for the latest official release.

**Comment by JelteF** [comment]
Ok, good to know the idea behind this. I'll close the issue then. It is a bit confusing though to have the history file say something is released while it is not actually released.
