### ISSUE TITLE
(C API) rocksdb_sstfilewriter_create_with_comparator ignores comparator

### ISSUE THREAD

**Issue by warrenfalk** [facebook/rocksdb#2328]
Is it just me or does the implementation of ```rocksdb_sstfilewriter_create_with_comparator``` look identical to the implementation of ```rocksdb_sstfilewriter_create```?

I'm happy to submit a pull request for this, but I don't know what the intent of having a separate ```rocksdb_sstfilewriter_create_with_comparator``` function is.  It seems to me that ```rocksdb_sstfilewriter_create``` already supports a comparator by virtue of using an Options.  So  ```rocksdb_sstfilewriter_create_with_comparator``` is superfluous and should just be removed.  Is there a reason for it that I'm missing?

**Comment by sagar0** [comment]
Yes, 'rocksdb_sstfilewriter_create_with_comparator' should be deprecated/removed, as passing in the comparator via Options is the suggested approach. Feel free to submit a pull request. 
Its deprecated in C++ API: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/sst_file_writer.h#L66-L78

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
