### ISSUE TITLE
Require a newer CMake minimum version in CMakeLists.txt

### ISSUE THREAD

**Issue by ObiWahn** [facebook/rocksdb#2332]
It is quite hard to embed RocksDB using the source distribution in combination with CMake. I would like to contribute in that area. But to make proper use of CMake's target system and other newer features I would need CMake 3.0

- 3.2 would be fantastic
- official support for version 2.6.x already ended | x < 4

Embedding RocksDB should be as easy as:

``` cmake
cmake_minimum_required(VERSION 3.2)
project(myapp)
add_subdirectory(3rdParty/rocksdb)
add_executable(myapp main.c)
target_link_libraries(myapp rocksdb)
```

**Comment by adamretter** [comment]
@ObiWahn Just to not that Travis only provides up to CMake 3.2.2

**Comment by ObiWahn** [comment]
@adamretter Is Travis the only relevant place? You build on legacy systems like CentOS 6 with plain make right?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
