### ISSUE TITLE
Forcing rocksdb to commit all merges

### ISSUE THREAD

**Issue by VaronisDNMacClient** [facebook/rocksdb#2342]
I'm using `rocksdb C++ 4.6.0`

From what I saw, `rocksdb` is executing merge operations asynchronously and sometimes only on-demand.

This is problematic for me, because I sometimes have the following scenario:

Start up instance **A** of rocksdb using `rocksdb::Open()`
`merge` values into **A** using some `rocksdb::MergeOperator`
Shutdown **A**
Start up instance of **A** as **readonly** using using `rocksdb::OpenForReadOnly()` and `get()` from it
The problem: because **A** is now **readonly**, the asynchronous merges are not committed. They may have been executed in the previous **writeable** instance, but that is not deterministic.

Changing the second instancing of **A** to be **writeable** is solving the issue, but incorrect as to its usage and semantics.

How can I force rocksdb to commit all merges before shutting down the instance? I've tried to use **flush** but it doesn't seem to have any effect, and **compact** seems to expect parameters I can't give.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
