### ISSUE TITLE
IngestExternalFile and DeleteRange

### ISSUE THREAD

**Issue by danhhz** [facebook/rocksdb#2344]
[CockroachDB](https://github.com/cockroachdb/cockroach) currently uses DeleteRange and intends to start using IngestExternalFile. Unfortunately, it looks like these two features don't play well together: ["file ingestion with range tombstones is currently unsupported"](https://github.com/facebook/rocksdb/blob/v5.3.4/db/external_sst_file_ingestion_job.cc#L413). Is fixing this on the roadmap? If so, do you have an ETA?

cc @IslamAbdelRahman or @ajkr maybe

Thanks!

**Comment by ajkr** [comment]
Right, we didn't implement support yet as previously there was no need. It doesn't look very difficult (but maybe I'm missing something), so I can try doing it later this week.

**Comment by danhhz** [comment]
That would be great, thanks!

**Comment by ajkr** [comment]
In the meantime if you need to ingest a file into a DB containing range deletions, you can issue a full compaction first. That'll get rid of all the range deletions as long as there aren't snapshots older than them.

**Comment by danhhz** [comment]
Ah, good to know. I doubt we could ship it that way, but it'll help during development of our IngestExternalFile support.

**Comment by IslamAbdelRahman** [comment]
@ajkr, Can you please refresh my memory regarding what was the issue that avoided us from supporting this ?

**Comment by ajkr** [comment]
I think lack of use case and maybe we didn't think of a way to detect whether a level's range deletions cover any keys in the ingested file. We should be able to Seek() each range's begin key in the to-be-ingested file, and verify it reaches a key beyond the range's end.

**Comment by ajkr** [comment]
#2370

**Comment by danhhz** [comment]
Awesome!

**Comment by ajkr** [comment]
It's supported now. Let us know your experience using it! :)

**Comment by danhhz** [comment]
Thanks! I'll try it out this week.

One quick semantics question if you don't mind: if I have a span of keys that's only had DeleteRange called on it (yeah, doesn't make a ton of sense I know) and the range tombstone still exists (hasn't been compacted) and I call IngestExternalFile with data for that keyspan... what level is the file put into? L0? LMax?

**Comment by ajkr** [comment]
Generally, the file gets placed in a "newer" position than the overlapping range tombstone, which roughly means:

- range tombstone in level n for some n > 0 => we ingest to level n-1
- range tombstone in L0 => we ingest as a newer L0 file
- range tombstone in memtable => we flush first, then ingest the file as the newest in L0

**Comment by danhhz** [comment]
I ran a quick test yesterday and this worked beautifully. More extensive testing will have to wait until we upgrade the version of RocksDB we're using, which might take a week or two. Thanks again for the fix!!!
