### ISSUE TITLE
SIGSEV running Rocksdbjni

### ISSUE THREAD

**Issue by JeremyCoxBMI** [facebook/rocksdb#2351]
I get a core dump using Rocksdbjni running a program I have successfully run before.  It seems after a Java rebuild of my jar, the problem simply started.  EDIT: I double-checked all my logs; the problem has always existed.

The problem seems to be in the rockdb library (per the error message).
I updated to rocksdbjni 5.3.4 from 3.6  and recompiled rocksDB C++ library.  Neither helped.

The put command is the offender causing the crash.  The constructor seems to work fine.

       try {
                byte[] k = longToBytes(key);
                byte[] v = arrayListLongToBytes(positions);
                if (k!= null && v != null)
                    db.put(k,v);
            } catch (RocksDBException e) {
                e.printStackTrace();
                exit(1);
            }

[hs_err_pid30334 (copy).log.txt](https://github.com/facebook/rocksdb/files/1022647/hs_err_pid30334.copy.log.txt)

**Comment by adamretter** [comment]
Your `hs_err` does not match the code that you posted. The hs_err shows that the problem is occurring when you call `get`.

**Comment by JeremyCoxBMI** [comment]
Oops!   I drilled down too far down the code.
A get is called first in the append operation!

     public void append(long key, long pos) {
        ArrayList<Long> temp = get(key);   **// GET call**
        if (temp == null)
            temp = new ArrayList<Long>();
        temp.add(pos);
        put(key, temp);
    }

    public void append(long key, PositionList p){
        ArrayList<Long> q = p.toArrayListLong();
        ArrayList<Long> temp = get(key);
        if (temp == null)
            temp = new ArrayList<Long>();
        for (Long x : q)
            temp.add(x);
        put(key, temp);
    }

    public void put(long key, ArrayList<Long> positions) {
        if (positions != null) {
            try {
                byte[] k = longToBytes(key);
                byte[] v = arrayListLongToBytes(positions);
                if (k!= null && v != null)
                    db.put(k,v);
//                db.put(longToBytes(key), arrayListLongToBytes(positions));
            } catch (RocksDBException e) {
                e.printStackTrace();
                exit(1);
            }
        }
    }

**Comment by adamretter** [comment]
@JeremyCoxBMI Would you be able to resolve the C++ line numbers in the stack trace for us please? See - https://github.com/facebook/rocksdb/wiki/JNI-Debugging#interpreting-hs_err_pid-files

**Comment by JeremyCoxBMI** [comment]
I hope I did this correctly.

$ addr2line -e /data/1/b/tmp/librocksdbjni406370862549213581..so 0xb61ae
/rocksdb/./java/rocksjni/rocksjni.cc:465

**Comment by adamretter** [comment]
@JeremyCoxBMI, that line number doesn't seem to match inside the function `rocksdb_get_helper` in either version 3.6.1 or 5.3.4. Which version are you using?

**Comment by JeremyCoxBMI** [comment]
IntelliJ says I have rocksdbjni 3.6.2 in my distro.

Apologies -- my update to 5.3.4 was not automaticaIly processed properly by the builder.

Let me know if there is value in trying the updated version. I can manually install the library.

**Comment by adamretter** [comment]
@JeremyCoxBMI Unfortunately I can't match that in 3.6.2 either. Could you try 5.3.6?

**Comment by JeremyCoxBMI** [comment]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb55fa6c9e3, pid=5366, tid=0x00007fb5dcf12700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni3200687002803783170.so+**0x1f69e3**]  rocksdb_get_helper(JNIEnv_*, rocksdb::DB*, rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, _jbyteArray*, int, int)+**0x273**
#
# Core dump written. Default location: /data/1/nvme/chr1only/core or core.5366
#
# An error report file with more information is saved as:
# /data/1/nvme/chr1only/hs_err_pid5366.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)

This is 5.3.6

**It seems I am not getting valid output:**
$ addr2line -e /data/1/b/tmp/librocksdbjni3200687002803783170.so 0x1f69e3
??:?

_Just in case that was wrong, although I think it is correct:_
$ addr2line -e /data/1/b/tmp/librocksdbjni3200687002803783170.so 0x273
??:0

**Comment by adamretter** [comment]
@JeremyCoxBMI Sorry, to get the line numbers you will need to build a version from the tag `v5.3.6`, so that it includes the debug symbols. The versions we release to Maven Central are for production use.

**Comment by JeremyCoxBMI** [comment]
I downloaded v5.3.6 (not RocksDB 5.3.6) from
https://github.com/facebook/rocksdb/releases

I compiled it in C, but I believe I still need to compile the jar to include it in my project, and then import that jar into my project.

How should I compile the jar?

I thought I was supposed to compile via maven in the java/ subdirectory, but didn't work for me.  No build targets.

**Comment by JeremyCoxBMI** [comment]
I am trying

make jclean clean
make -j 4 rocksdbjavastatic

But is this the right compile option to include debugging?

**Comment by adamretter** [comment]
@JeremyCoxBMI Very close :-)

try:

```bash
cd rocksdb
git checkout v5.3.6
make jclean clean
DEBUG_LEVEL=2 make rocksdbjavastatic
```

**Comment by JeremyCoxBMI** [comment]
I'm at a loss -- I repeated this with a fresh clone just to be sure.  I added the Jar to my project, then made and ran.  I am still not getting line numbers.  :( 

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f182ba3fa26, pid=10551, tid=0x00007f1878cba700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni8389933268722817432.so+0x1f9a26]  rocksdb_get_helper(JNIEnv_*, rocksdb::DB*, rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, _jbyteArray*, int, int)+0x246
#
# Core dump written. Default location: /data/1/nvme/chr1only/core or core.10551
#
# An error report file with more information is saved as:
# /data/1/nvme/chr1only/hs_err_pid10551.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
jwc@kluedebian:/data/1/nvme/chr1only$  addr2line -e /data/1/b/tmp/librocksdbjni8389933268722817432.so 0x1f9a26
??:?

**Comment by adamretter** [comment]
If you change:
```
DEBUG_LEVEL=2 make rocksdbjavastatic
```
to
```
export DEBUG_LEVEL=1
make rocksdbjava
```

do you get them?

**Comment by JeremyCoxBMI** [comment]
hurray!

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc52db09676, pid=13799, tid=0x00007fc5828f8700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_131-b11) (build 1.8.0_131-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.131-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni5229584561419586884.so+0x1f2676]  rocksdb_get_helper(JNIEnv_*, rocksdb::DB*, rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, _jbyteArray*, int, int)+0x246
#
# Core dump written. Default location: /data/1/nvme/chr1only/core or core.13799
#
# An error report file with more information is saved as:
# /data/1/nvme/chr1only/hs_err_pid13799.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Aborted (core dumped)
jwc@kluedebian:/data/1/nvme/chr1only$  addr2line -e /data/1/b/tmp/librocksdbjni5229584561419586884.so 0x1f2676
/home/jwc/Downloads/tmp/rocksdb/java/rocksjni/rocksjni.cc:559

```

**Comment by adamretter** [comment]
Okay so that makes sense, the line is here - https://github.com/facebook/rocksdb/blob/v5.3.6/java/rocksjni/rocksjni.cc#L559

So in my limited experience a SIGSEGV is often caused by working with memory that has already been freed. The only thing that I can see that might be happening from the stack trace at that line is that for some reason you have lost your db pointer. Is it possible you are doing a get after closing the database?

**Comment by JeremyCoxBMI** [comment]
This doesn't make sense -- although I will step through with the debugger.

Quick question -- if the constructor failed in anyway, I would get a RocksDBException thrown?
My interface layer constructs using this code, and I assumed the database was opened correctly since I did not exit.  Always best to check these assumptions. :D

```
    public RocksDbKlue(String path, boolean readonly, int maxFiles){
        databasePath = path;
        options = new Options().setCreateIfMissing(true).setMaxOpenFiles(maxFiles);

        try {
            if (readonly)  db = RocksDB.openReadOnly(options, databasePath);
            else           db = RocksDB.open(options, databasePath);
        } catch( RocksDBException e) {
            System.out.println("RocksDbKlue Constructor failed.");
            e.printStackTrace();
            exit(0); 
        }
    }
```

**Comment by adamretter** [comment]
Indeed if `RocksDB#open(...)` fails, you should get an exception.

Please check you are not calling `close` or `finalize` by accident on RocksDB, also worth checking that you haven't used it accidentally in a `try-with-resources` where you didn't mean to.

To check my assumption about what is wrong you could compile and run with ASAN which could help shed some light on this: https://github.com/facebook/rocksdb/wiki/JNI-Debugging#asan

**Comment by JeremyCoxBMI** [comment]
My program does this
1) open RocksDB
2) open text file
3) import text into memory 
4) dump memory to RocksDB
5) close RocksDB

The crash is on the first get() call in my append operation on step 4.
The attached debug pictures show the only variable to change state is
```
db.owningHandle_
```

![rocks_b4_get_screenshot from 2017-05-25 10-13-18](https://cloud.githubusercontent.com/assets/17282194/26453759/d2316620-4132-11e7-8c94-2976bdb5500b.png)
![rocks_open_screenshot from 2017-05-25 10-10-23](https://cloud.githubusercontent.com/assets/17282194/26453761/d48c9408-4132-11e7-95b2-189f56898025.png)

**Comment by JeremyCoxBMI** [comment]
ASAN SIGSEV error

[ASAN_compile_error.txt](https://github.com/facebook/rocksdb/files/1029309/ASAN_compile_error.txt)

**Comment by JeremyCoxBMI** [comment]
FOUND THE BUG!

MISPLACED Brackets on the function body.

#Embarrassing.

Thanks for all the help.
