### ISSUE TITLE
Merged values can silently exceed the size limitation of byte[] in Java.

### ISSUE THREAD

**Issue by StefanRRichter** [facebook/rocksdb#2383]
RocksDB's JNI bridge currently only offers `byte[]` as type for keys and values. Not only does this limits the maximum size of keys and values to 2^31, but it can also cause a problem with the merge operator.

When we merge multiple values under one key, they are internally concatenated to one value in RocksDB. This way, it is possible to accumulate a total value size per key that is larger than 2^31 bytes. Whenever we try to access such values that grew beyond this limit through merging, we will encounter an `ArrayIndexOutOfBoundsException` at best and a segfault at worst (I have seen this when the state grew a lot larger).

This behaviour is particularly problematic, because RocksDB accepts to store all the values, but on the next access the code fails unexpectedly.

What are your thoughts on this problem and is there any workaround that I missed?

Right now, I think the only proper long term solution to this is building RocksDB's JNI bridge around `(Direct)ByteBuffer` as input and output types, instead of simple `byte[]`. This would also enable larger keys and values, and potentially avoid copies when interacting through JNI.

**Comment by sagar0** [comment]
@StephanEwen also mentioned this in-person recently, and this is a valid concern.
@adamretter what do you think? Are there any good workarounds?

**Comment by adamretter** [comment]
Java uses `int` internally for the array index, however arrays are zero based addressing, so if I am not mistaken then the maximum theoretical size of a Java byte array is `2^31-1`. However, it seems in practice that it can actually be a little less than this depending on various VM and memory limits.

So that would allow you to have about 2GB of storage.

@StefanRRichter Do you really have a single values which are ~2GB? It would seem to be that is quite unlikely.

**Comment by StefanRRichter** [comment]
@adamretter This problem came up for some users of Apache Flink. We use RocksDB as a backend for stateful stream processing. We use merging state to collect events, e.g. events that happen as part of user sessions, over time windows. It seems that there are users with that have many events and/or potentially large time windows (days, weeks). They are hitting this boundary. While there might be workarounds in they way they write they jobs, it would be better to enable them to use more then 2GB of state per key/window or at least fail fast in case we cannot go past 2GB.

**Comment by adamretter** [comment]
@sagar0 @siying Can you guys comment on whether 2GB for a single value in RocksDB is a sensible idea?

**Comment by StefanRRichter** [comment]
The alternative for our use case would be to introduce artificial subkeys, having one key/value pair per event. Would that make more sense from a performance point of view or just introduce more overhead due to redundant prefix keys? I assumed avoiding this that this is the exact case for using merge operator in the first place?

**Comment by StephanEwen** [comment]
Is there anything forbidding this in principle? Form the Apache Flink use case perspective, degraded performance for such large values would be okay (much better than crashes) - users can look at their metrics and see why (super large values).

If there was a Java interface that did not use `byte[]` but rather something that mimics the C++ interface (a pointer (`long`) and a length (`long`) to return the result through), would that help circumvent the problem?

**Comment by siying** [comment]
@adamretter RocksDB does support 2GB single value. I do have a (disabled) use case that verifies we can handle it. It's hard to imagine why people use RocksDB in this way though. Whether we need to support it depends on whether there is a need. I'm OK with either way.

**Comment by StefanRRichter** [comment]
@siying If it is hard to imagine why people would do this, what is the best practise you would suggest instead? In case you want to collect (i.e. append) event's values for time windows under a composite key of (window_id | extract_key(event)) and iterate those event values as soon as the window is evaluated? For me this sounded like a good case for applying the merge operator and it seems that there are cases where users have very large states per key/window pair.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by adamretter** [comment]
@StefanRRichter As I understand it I think you need to set the option `max_successive_merges`, this will ensure that the merges are merged down to a concrete value when a maximum number of merge operations are present, see https://github.com/facebook/rocksdb/blob/04c11b867df9190da204e38357a14d20296fb244/include/rocksdb/advanced_options.h#L530

@siying anything further to add on this?

**Comment by StefanRRichter** [comment]
@adamretter Thanks a lot for your input on this topic. From a user perspective I find it a bit unfortunate that you have to know and tune this parameter to stop errors that can lead to data loss. Even if you know about it, a "safe" choice for the parameter can depend on the size of the merged values, which is hard to know upfront if you are using RocksDB as a backend inside another system without prior knowledge about the potential values that users could merge when using it. I think the fix from @azagrebin is already a good improvement to catch the error and report a proper cause. In the long term, I wonder if we could also expose support for larger values through JNI?

**Comment by adamretter** [comment]
We could potentially expose larger values through RocksJava, but the best
mechanism to do so is unclear to me. Both byte[] and ByteBuffer are limited
to 32bits of storage size. Also I really wonder if it is desirable to be
copying around 2GB+ arrays in memory, especially as each represents a
single key or value.

**Comment by StefanRRichter** [comment]
Yes, the size limitations of `ByteBuffer` and `byte[]` are problematic, and copying data can be as well. I think a solution could be based on the same principle as a direct byte buffer, but would require a custom implementation that supports `long` typed offsets and indexes. I am not familar with the internal memory management of RocksDB, but would it be possible to pin the slice with the value data and return the memory address via JNI so that we can use this in Java to initialize the memory address inside our custom "ReadOnlyBigDirectyByteBuffer", which then operates on the internal data without creating a copy. I guess on downside, the buffer would require to be `AutoCloseable` to unpin the internal data after usage.

**Comment by adamretter** [comment]
Something like that would indeed be possible. We would want to read in
chunks though to avoid too many JNI boundary calls (which have quite the
performance detriment).

**Comment by StefanRRichter** [comment]
I think that would be really nice to have! I think that a more direct data transfer out of (also potentially into) of RockDB with zero data copy could also be beneficial for performance. Do you think there is a realistic chance to see something like that in the near future? Would an outside contribution help and have a chance to make it in?

**Comment by StephanEwen** [comment]
@adamretter If we would follow a similar approach to DirectByteBuffer, then there is no JNI boundary per access to the buffer - that is efficiently handled by Unsafe / VarHandle. The JNI boundary would be crossed once per read/write row call, similar to the current API.

**Comment by unoexperto** [comment]
@StefanRRichter @StephanEwen Hi guys! I just stumbled up on this problem with 6.7.3 and I was wondering if there is plan to address this edge case ? I have't investigated it deeper mostly because I couldn't figure out quickly how to compile your JNI wrapper but maybe we can have an API that returns linked list of `ByteBuffer`s instead of copying `byte[]` (in iterator `value()` and `get()`) ? In majority of use-cases I don't even need raw byte array because it's parsed to some Java object.

**Comment by StephanEwen** [comment]
That would be a question for @adamretter 

I personally would be super happy to see an API that returns a native ByteBuffer, avoids a copy and object allocation on the way. If there are any plans for that, we'd be happy to contribute.

**Comment by adamretter** [comment]
@unoexperto @StephanEwen Hey guys, let's revisit this...

We now in 6.7.3 and newer have ByteBuffer versions of most functions, to which you can pass a Direct ByteBuffer. So that should eliminate some inefficiency with copies etc.

Regards large merge queues I think we suggested that `max_successive_merges` should be used.

Was there another use-case for having single (i.e. merged) values that are 2GB in size? If so, wouldn't this be a better use-case for BlobDB?

**Comment by unoexperto** [comment]
@adamretter Thank you for prompt response!

> We now in 6.7.3 and newer have ByteBuffer versions of most functions, to which you can pass a Direct ByteBuffer. So that should eliminate some inefficiency with copies etc.

Could you please point to Java classes that allow getting `ByteBuffer` from iterator or use `ByteBuffer` in `put()`, `get()`, `merge()` calls ? I'm on 6.7.3 and all these methods still operate with `byte[]`.

> Regards large merge queues I think we suggested that max_successive_merges should be used.

I understood `max_successive_merges` only as optimization that defines how many merge operations should be in WAL until those merged and actual value is updated. So it's not limiting number of total merges per KV pair. Am I correct ?

> Was there another use-case for having single (i.e. merged) values that are 2GB in size? If so, wouldn't this be a better use-case for BlobDB?

My use-case was similar to what you guys did at Facebook with [LogDevice](https://engineering.fb.com/core-data/logdevice-a-distributed-data-store-for-logs/). I store logs in 10 mins chunks where key is `<CustomerID><EpochOfSegment><LogLevel>`. I relied on native String appender to merge individual log entries in value. Average size of log entry is ~1100 bytes. It was nice until I stumbled upon customer who generated more than 2GB in 10 mins timeframe :) So right now I'm planning to write each log entry as individual KV pair **and** either use partitioned index or manually partition customers into different column families. Thoughts ?

**Comment by adamretter** [comment]
> Could you please point to Java classes that allow getting ByteBuffer from iterator or use ByteBuffer in put(), get(), merge() calls ? I'm on 6.7.3 and all these methods still operate with byte[].

Apologies, it seems that it did not make it into 6.7.3. It is in `master` and I see that it will be in the upcoming `6.8.x` series: https://github.com/facebook/rocksdb/blob/6.8.fb/java/src/main/java/org/rocksdb/RocksIterator.java#L92


>I understood max_successive_merges only as optimization that defines how many merge operations should be in WAL until those merged and actual value is updated. So it's not limiting number of total merges per KV pair. Am I correct ?

I am not clear on the implementation itself, but the documentation seems to imply "total merges per KV pair", i.e. it says "This will ensure that there are never more than max_successive_merges merge operations in the memtable."

Personally - I can't really comment on if RocksDB is the right choice, or how best to structure your data. If you need >2GB values and RocksDB supports that in the C++ layer, we could expose a suitable mechanism in the Java layer. Whether storing single >2GB values into RocksDB is sensible or not is a different discussion.

**Comment by StephanEwen** [comment]
Thanks, @adamretter, great to see the ByteBuffer API coming up.

From our use cases (Apache Flink) the case where row size exceeds 2GB are certainly not frequent.

They are mostly "accidents", some extreme unexpected data skew makes a key extremely hot (many values that get concatenated (merged)). It would be nice if that only caused slowdown (you can identify the issue in the metrics) and not lead to an unrecoverable error.

**Comment by ajkr** [comment]
I don't think we support >2GB merged values in C++ API either. It is indeed a difficult question how to deal with this case since at `Merge()` time we don't know if we're accepting an operand that'll cause overflow later when the value is merged. Can the merge operator return an error, or compress the base value during full merge?

**Comment by Zakelly** [comment]
Hi guys, after going through the discussion above, I found the original problem that the merged values can exceed the size limitation of Java object (byte[] or ByteBuffer) has not been solved?

I'm glad to see the ByteBuffer API, since it is beneficial for performance. But without pagination parameters (e.g. startOffset of the value) it is still not possible to read a value from RocksDB larger than 2^31. Do I miss something?
