### ISSUE TITLE
5.4.5 build breaks on db_bench when using LITE

### ISSUE THREAD

**Issue by lxcode** [facebook/rocksdb#2386]
Because of some uses of blob_db that aren't wrapped in ifdefs for ROCKSB_LITE, the db_bench tool breaks:

 CC       tools/ldb_cmd.o
  CC       tools/ldb_tool.o
  CC       tools/sst_dump_tool.o
  AR       librocksdb-lite.a
ar: warning: creating librocksdb-lite.a
  CC       tools/db_bench.o
  CC       tools/db_bench_tool.o
tools/db_bench_tool.cc:3419:13: error: use of undeclared identifier 
'FLAGS_use_blob_db'
        if (FLAGS_use_blob_db) {
            ^
tools/db_bench_tool.cc:3422:11: error: use of undeclared identifier 'blob_db'
          blob_db::BlobDB* blobdb =
          ^
tools/db_bench_tool.cc:3423:27: error: use of undeclared identifier 'blob_db'
              static_cast<blob_db::BlobDB*>(db_with_cfh->db);
                          ^
tools/db_bench_tool.cc:3447:19: error: use of undeclared identifier 
'FLAGS_use_blob_db'
              if (FLAGS_use_blob_db) {
                  ^
tools/db_bench_tool.cc:3461:17: error: use of undeclared identifier 
'FLAGS_use_blob_db'
            if (FLAGS_use_blob_db) {
                ^
tools/db_bench_tool.cc:3474:12: error: use of undeclared identifier 
'FLAGS_use_blob_db'
      if (!FLAGS_use_blob_db) {
           ^
6 errors generated.

https://www.mail-archive.com/freebsd-pkg-fallout@freebsd.org/msg482649.html

**Comment by yiwu-arbug** [comment]
Thanks for raising the issue. We just tag v5.4.6 with a hot fix to this: https://github.com/facebook/rocksdb/releases/tag/v5.4.6

**Comment by lxcode** [comment]
Thanks! Could you do the rocksdb-5.4.6 tag as well? The FreeBSD port depends on the rocksdb-x.x.x-style tag instead of the vx.x.x one.

**Comment by yiwu-arbug** [comment]
@lxcode done.
