### ISSUE TITLE
Java tests frequently keep failing on Travis

### ISSUE THREAD

**Issue by sagar0** [facebook/rocksdb#2387]
Java tests frequently keep failing on Travis for unknown (random) reasons. A rerun of the same test almost always succeeds. We should strive to make these tests more stable. 
(I believe we might be depending on some randomization somewhere, which could be resulting in these failures. I haven't spent enough time, but definitely worth investigating).

Example: https://travis-ci.org/facebook/rocksdb/builds/237084411

**Comment by adamretter** [comment]
@sagar0 Could it maybe be related to this - https://github.com/facebook/rocksdb/issues/2384
