### ISSUE TITLE
Error in tempdir()

### ISSUE THREAD

**Issue by Exaeta** [facebook/rocksdb#2389]
```Error in tempdir() using tmp/rocksdb.XXXX: Parent directory (/tmp) does not exist at -e line 2.```

I have done ```export TMP=~/tmp``` but this did not fix this problem. How do I get the program to put the temporary files somewhere else? I don't have the ability to create /tmp and it does not exist on the system I am using.

**Comment by ajkr** [comment]
The environment variable to set is called `TEST_TMPDIR`.
