### ISSUE TITLE
Remove blocks for deleted sstables from the block cache

### ISSUE THREAD

**Issue by petermattis** [facebook/rocksdb#2391]
[Mentioned this in person to @siying and decided to file an issue]

A frequently asked question about CockroachDB is [why memory usage is high on an idle cluster](https://www.cockroachlabs.com/docs/operational-faqs.html#why-is-memory-usage-increasing-despite-lack-of-traffic). The answer has to do with the small amount of background traffic that is present on an idle cluster that results in `Merge` operations. These operations create sstable churn which is almost unnoticeable except for the effect it has on the block cache: when an sstable is deleted, its blocks are not removed from the block cache. The end result is a relatively small amount of disk usage on an idle cluster can be combined with a significant amount of memory usage in the block cache.

It would be nice if RocksDB either automatically removed blocks for deleted sstables from the block cache, or provided a routine to remove such blocks. There is no significant urgency to this other than the desire to "fix" one of our FAQs.

**Comment by maysamyabandeh** [comment]
Would not be much simpler if one simply clears the block cache when the node is idle? This could be improved by a ::clear(float b) API that clears only the b% least recently used from the block cache.

**Comment by petermattis** [comment]
@maysamyabandeh I've had the same thought, though then the problem is shifted to determining when a node is idle. If this isn't addressed in some fashion at the RocksDB level, we'll eventually do something ourselves. It isn't high priority.

**Comment by maysamyabandeh** [comment]
@petermattis We discussed it internally. Although the feature makes sense, due to other high priority tasks it is not likely that we would have cycles for this one. If your team want to work on a patch we would be happy to review it. Alternatively, as you suggested, you would need to detect the idle state and manually evict the stale cache items by lowering its capacity.

**Comment by petermattis** [comment]
@maysamyabandeh Thanks for the update. We'll likely tackle this on our end.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
