### ISSUE TITLE
new binding for Erlang applications

### ISSUE THREAD

**Issue by benoitc** [facebook/rocksdb#2394]
not sure what is the best way to submit it so opening a ticket for it. 

I created an Erlang binding for rocksdb: 
https://gitlab.com/barrel-db/erlang-rocksdb

It support latest rocksdb and different OS platforms. The binding is used in the barrel database written in Erlang. 

If the ticket is not the right way to add a binding just let me know how to process and I will do it :)

**Comment by maysamyabandeh** [comment]
Thanks @benoitc. Feel free to go ahead with a PR updating https://github.com/facebook/rocksdb/blob/master/LANGUAGE-BINDINGS.md

**Comment by adamretter** [comment]
@benoitc I also added your Erlang binding to Wikipedia page - https://en.wikipedia.org/wiki/RocksDB#Third-party_Language_Bindings
