### ISSUE TITLE
Is it bad to have a large numbers of column families

### ISSUE THREAD

**Issue by JelteF** [facebook/rocksdb#2426]
I couldn't find anything in the wiki about this. Is it bad to to have a large number of column families in a single database? If so, at what kind of numbers will you start running into issues? A thousand, 10 thousand, 100 thousand, one million?

**Comment by clark010** [comment]
> The main idea behind Column Families is that they share the write-ahead log and don't share memtables and table files.
@JelteF I think if the table don't share memtables and table files, it will take the db to use a large memory and on it may generate a large num of files on disk.

**Comment by tbarbugli** [comment]
Each column family will use at least `write_buffer_size` memory (64MB by default) to store memtables. This should already limit your options to < 1,000

**Comment by Ironman-Jason** [comment]
@tbarbugli , if I create million column family in the database, is there something like LRU swap for column family write_buffer?
