### ISSUE TITLE
How can I avoid the crc32 check while block cache is not enough

### ISSUE THREAD

**Issue by absolute8511** [facebook/rocksdb#2431]
I noticed a CPU cost issue while I am using the LRU block cache and with the config `cache_index_and_filter_blocks = true`  . Most of the CPU usage is in `rocksdb::crc32c::ExtendImpl<&(rocksdb::crc32c::Fast_CRC32(unsigned long*, unsigned char const**))>`.   

After browsing the codes, I found while the filter block was evicted by LRU, we need reload next time. Every time we load these blocks we need verify the crc32 checksum which cost the CPUs a lot. 
```
FilterBlockReader* BlockBasedTable::ReadFilter(Rep* rep) {
  // TODO: We might want to unify with ReadBlockFromFile() if we start
  // requiring checksum verification in Table::Open.
  if (rep->filter_type == Rep::FilterType::kNoFilter) {
    return nullptr;
  }
  BlockContents block;
  if (!ReadBlockContents(rep->file.get(), rep->footer, ReadOptions(),
                         rep->filter_handle, &block, rep->ioptions,
                         false /* decompress */, Slice() /*compression dict*/,
                         rep->persistent_cache_options)
           .ok()) {
    // Error reading the block
    return nullptr;
  }

  assert(rep->filter_policy);
....

```
Since the default `ReadOptions()` will not skip the crc32 verify while reading, the crc32 check 
 can not be skipped while loading the filter blocks to cache.  I think maybe we should add an options here to skip the crc32 verify?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
