### ISSUE TITLE
How can I make a self-defined sstable format

### ISSUE THREAD

**Issue by kayaklee** [facebook/rocksdb#2432]
I want to verify some ideas to optimize compaction, but I have to implement self-defined sst format file, include the read/write interface of sst. So I want know about that which interfaces should I overwrite to implement the new sst format, and how to ingest the self-defined sst files.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by siying** [comment]
@kayaklee the one you need to override is TableFactory: https://github.com/facebook/rocksdb/blob/5.10.fb/include/rocksdb/table.h#L400-L494 . Where you can implement your implementation of TableReader and TableBuilder and returned them by the factory functions. Be aware that, these are internal classes and aren't exposed in released headers.

By the way, we now hope github issues are only bug reports and feature development tracking. Non-bug related discussion should go to RocksDB's Google mailing list or Facebook group.
