### ISSUE TITLE
Tags v5.4.6 v5.4.5 crash in windows 7

### ISSUE THREAD

**Issue by kobegan** [facebook/rocksdb#2458]
v5.4.6 v5.4.5 crash in windows 7. other releases work fine.
building params:
cmake -G "Visual Studio 14 2015 Win64" ..
MSBuild  rocksdb.sln /p:Configuration=Debug /p:Platform=x64 /m
After building done, I run db_test.exe in  Debug. However, its crash details as below.

Unhandled exception at 0x000000013F457BE7 in db_test.exe: 0xC000001D: Illegal Instruction.

Call Stack:
db_test.exe!std::_Uhash_compare<std::basic_string<char,std::char_traits<char>,std::allocator<char> ,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > ,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > ::_Uhash_compare<std::basic_string<char,std::char_traits<char>,std::allocator<char> ,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > ,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >(std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > _Hasharg, std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > _Keyeqarg) Line 107 C++

 	db_test.exe!std::unordered_map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,rocksdb::OptionTypeInfo,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,rocksdb::OptionTypeInfo> > >::unordered_map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,rocksdb::OptionTypeInfo,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,rocksdb::OptionTypeInfo> > >(std::initializer_list<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,rocksdb::OptionTypeInfo> > _Ilist) Line 358	C++

 	db_test.exe!rocksdb::`dynamic initializer for 'db_options_type_info''() Line 138	C++

**Comment by PraveenSinghRao** [comment]
Most likely due to advanced instructions not supported by your processor. Please try -DPORTABLE=1 with cmake.

**Comment by kobegan** [comment]
@PraveenSinghRao I tried to rebuild the project with the config you mentioned, however, the crash issue still exists.

**Comment by kobegan** [comment]
This issue duplicates #2229. Close this one.
