### ISSUE TITLE
Skip some SSTables we don't care about when iterate a range

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#2459]
I saw cockroachdb create a patch for RocksDB that can skip some SSTables when iterate a range, this can speedup going through a range in some special situations. Is there any plan to support such cool feature in master?
https://github.com/cockroachdb/cockroach/blob/master/pkg/storage/engine/db.cc#L2049

**Comment by siddontang** [comment]
see https://github.com/facebook/rocksdb/pull/2265
