### ISSUE TITLE
Naming inconsistencies in C-API

### ISSUE THREAD

**Issue by vmx** [facebook/rocksdb#2464]
I found a naming [inconsistency in the C-API](https://github.com/facebook/rocksdb/blob/0d278456c9e94459aa62d50ba18b10bcc166a75f/include/rocksdb/c.h#L869-L872). I think setting MemTable factories should have a "memtable" prefix as `rocksdb_options_set_memtable_vector_rep()` has.

    rocksdb_options_set_hash_skip_list_rep() -> rocksdb_options_set_memtable_hash_skip_list_rep()
    rocksdb_options_set_hash_link_list_rep() -> rocksdb_options_set_memtable_hash_link_list_rep()

Are there any plans to remove such C-API inconsistencies? If there is one, let me know an I'll create an pull request for it.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
