### ISSUE TITLE
rocksdbjni 5.4.6 not published on maven central

### ISSUE THREAD

**Issue by isavin** [facebook/rocksdb#2466]
On github the latest release is 5.4.6:
https://github.com/facebook/rocksdb/releases

But this version is not published in Maven Central, latest there is 5.4.5:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rocksdbjni%22

**Comment by sagar0** [comment]
There is no change in rockdbjni related code between 5.4.5 and 5.4.6. The only change between the two versions is a fix for rocksdb_lite [build issue](https://github.com/facebook/rocksdb/commit/8c1f5c254fdfcf36ffdc34c261e0cbba8d8861f2), which wouldn't affect rockdbjni, and hence we decided not to publish a new jar to maven.
