### ISSUE TITLE
Can I use RocksDB purely in memory and use the pointer to record address for read?

### ISSUE THREAD

**Issue by smartseal** [facebook/rocksdb#2467]
Hi all, 
I am new to RocksDB and I have interest to use it in my projects. I have the following two questions first:
1) Can RocksDB used purely in memory without file support?
2) I want to access the record as fast a possible for reading. Can I got the underlying memory address of the value field of key/value and keep it by a pointer? I want to read the field of the value directly and not want to get it out each time when I need it.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
