### ISSUE TITLE
Opimize Opportunity in Universal Compaction: Sorted Runs on Level0

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#2468]
In some situations(especially in data loading phase), time adjacent memtable(or SST)s also have no overlapping key ranges, these memtable(or SST)s can be treated as a sorted run. This will greately reduce comapction overhead and read amplification.

**Comment by rockeet** [comment]
This proposal may resolve [https://github.com/facebook/rocksdb/issues/2530#issuecomment-312788666](this issue) in data loading.

**Comment by siying** [comment]
@rockeet did you try the CompactionOptionsUniversal.allow_trivial_move=true?

**Comment by rockeet** [comment]
@siying Yes, we have set allow_trivial_move=true

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
