### ISSUE TITLE
Do I have to close and re-open the store after restoring is completed with PrepareForBulkLoad?

### ISSUE THREAD

**Issue by guozhangwang** [facebook/rocksdb#2476]
I am using `Options:: PrepareForBulkLoad` to restore a rocksDB instance before ready for queries, the steps are:

1. Open the store with the above config turned on, use batch write apis to put records into the store;
2. Close the store, and then re-open it with the above config turned off.

I'm wondering if I can save step 2) above? If yes how?

**Comment by guozhangwang** [comment]
@siying could you share some thoughts?

**Comment by siying** [comment]
It's not needed from correctness point of the view. But to serve good read/write performance after bulk loading, I suggest you reopen the DB with the configuration for normal load.

**Comment by guozhangwang** [comment]
Got it, thanks!
