### ISSUE TITLE
Can't build example programs

### ISSUE THREAD

**Issue by chshaiiith** [facebook/rocksdb#2479]
I must be doing something different and I can't find a proper tutorial for it . I am unable to compile my code using rocksdb libraries. I am using Ubuntu 16.04.

g++ -std=c++11 -I/rocksdb/include -L/usr/local/lib -lrocksdb ../examples/options_file_example.cc

its giving the following error:
/tmp/cc3aegBw.o: In function `main':
options_file_example.cc:(.text+0x1f9): undefined reference to `rocksdb::DBOptions::DBOptions()'
options_file_example.cc:(.text+0x21e): undefined reference to `rocksdb::ColumnFamilyOptions::ColumnFamilyOptions()'
options_file_example.cc:(.text+0x231): undefined reference to `rocksdb::kDefaultColumnFamilyName[abi:cxx11]'
options_file_example.cc:(.text+0x2a9): undefined reference to `rocksdb::ColumnFamilyOptions::ColumnFamilyOptions()'
options_file_example.cc:(.text+0x340): undefined reference to `rocksdb::NewLRUCache(unsigned long, int, bool, double)'
options_file_example.cc:(.text+0x3bf): undefined reference to `rocksdb::NewBlockBasedTableFactory(rocksdb::BlockBasedTableOptions const&)'
options_file_example.cc:(.text+0x423): undefined reference to `rocksdb::NewBlockBasedTableFactory(rocksdb::BlockBasedTableOptions const&)'
options_file_example.cc:(.text+0x497): undefined reference to `rocksdb::DestroyDB(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::Options const&)'
options_file_example.cc:(.text+0x528): undefined reference to `rocksdb::DB::Open(rocksdb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::DB**)'
options_file_example.cc:(.text+0x5d5): undefined reference to `rocksdb::ColumnFamilyOptions::ColumnFamilyOptions()'
options_file_example.cc:(.text+0x6e2): undefined reference to `rocksdb::DBOptions::DBOptions()'
options_file_example.cc:(.text+0x6f6): undefined reference to `rocksdb::Env::Default()'
options_file_example.cc:(.text+0x72a): undefined reference to `rocksdb::LoadLatestOptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::Env*, rocksdb::DBOptions*, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> >*, bool)'
options_file_example.cc:(.text+0x915): undefined reference to `rocksdb::DB::Open(rocksdb::DBOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**)'
collect2: error: ld returned 1 exit status

Any help or leads would be great ! Thanks in advance.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
