### ISSUE TITLE
overhead from statistics and perf context

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#2489]
The overhead for db_bench --statistics and the perf context code using in-memory fillseq:
* --statistics=1 costs about 30% of throughput
* compiling in but not using perf context costs about 10% of throughput

For context MySQL with their perf_schema code enabled at run time costs about 10% of throughput on some micro-benchmarks. 

I built from HEAD at:
commit af1746751f2ff48381c53390bb7e4759b4d6bd11
Author: Siying Dong 
Date:   Wed Jun 21 10:28:54 2017 -0700
    WriteBufferManager will not trigger flush if much data is already being flushed

An internal bug is open for this.

I run fillseq via this command line and repeated the test for two builds -- one regular build (with fast crc really used) and one with fast crc used and with perf context disabled (by adding #define NPERF_CONTEXT 1 to monitoring/perf_context_imp.h).
```
./db_bench --benchmarks=fillseq --num=$1 --db=./ldb --statistics=$3 --stats_per_interval=0 --stats_interval_seconds=10 --cache_size=10737418240 --disable_wal=1 --compression_type=none --threads=1 --level_compaction_dynamic_level_bytes=1 --max_background_compactions=8 --max_background_flushes=3 --max_write_buffer_number=4 --write_buffer_size=33554432 --bytes_per_sync=4194304 --max_bytes_for_level_base=134217728 --memtablerep=$2
```

So I have two binaries that I will call rx.original and rx.noperfctx. The perf context code is enabled at compile time for rx.original and disabled at compile time for rx.noperfctx. The default value for --perf_level with db_bench is kDisable, so the perf context code is disabled at run time even when it is enabled at compile time.

Then for each I ran the command line above with --statistics=0 and 1 for both vector and skip_list memtable. It turns out there isn't much difference in throughput for this test with skip_list vs vector but I will share the data because I have it.

The first set of results is throughput in MB/sec in the first two columns for the rx.original binary that has the perf context enabled at compile time & disabled at run time. More than 30% of throughput is lost with --statistics=1.
```
stats enabled (--statistics = 0 or 1)
no      yes     ratio (y/n)     memtable
213.2   142.8   0.669           skiplist
210.8   145.3   0.689           vector
```

A similar test, but using the rx.noperfctx binary with perf context support disabled at compile time. Again more than 30% of throughput is lost with --statistics=1. The first two columns are MB/sec.
```
stats enabled (--statistics = 0 or 1)
no      yes     ratio (y/n)     memtable
234.2   149.9   0.640           skiplist
239.8   152.6   0.636           vector
```

In the next table I use the data from above for tests with --statistics=0 to compare the impact of the perf context code with --perf_level=kDisable vs disabling that feature at compile time. About 10% of throughput is lost when the perf context code is compiled in but doing nothing.
```
disabled at
run-time        compile-time    run/compile     memtable
213.2           234.2           0.910           skiplist
210.8           239.8           0.879           vector
```

**Comment by PraveenSinghRao** [comment]
Was there a regression in benchmarks when statistics were enhanced? We see a regression (esp. in load part of load random benchmark) on Windows. Not sure if it is a Windows only issue.

**Comment by ajkr** [comment]
It didn't regress on Linux with glibc 2.22+ but may have regressed on windows as I'm not familiar with `GetCurrentProcessorNumber()`'s performance. Maybe we should bring back thread-local for all platforms where we don't have the glibc's optimized `sched_getcpu()`.

**Comment by PraveenSinghRao** [comment]
Actually on Windows it was at the time it moved to thread local. I will lookup the commit #.

I think it hasn't regressed further when it moved to per-core. I can verify.

**Comment by ajkr** [comment]
Oh, that's interesting. We use thread-local in several places (e.g., superversion, concurrent arena allocator, perf_context/io_context, and formerly stats). I wonder how all that is affecting windows perf.

Thanks for helping verify the core-local changes :).

**Comment by mdcallag** [comment]
Test scripts:
* for fillseq - https://gist.github.com/mdcallag/ca1da5f7a34a64c0e14359a113ef21e1
* for readwhilewriting - https://gist.github.com/mdcallag/56253a09d8278d582e60e575e1320c91
* for readrandom - https://gist.github.com/mdcallag/a859908a58d7243051aced4197250f13

I have 2 db_bench binaries and the scripts above assume that:
* db_bench.sse - regular build with fast crc support enabled
* db_bench.sse - like db_bench.sse except perf context support disabled at compile time

Results for readwhilewriting show:
* impact from --statistics is mostly less than 10% reduction in QPS
* impact from perf context compiled in but disabled at run time is a QPS loss between 15% and 20%

Numbers below are MB/sec based on QPS * sizeof(KV pair)
Tests were run for 1 and 20 threads using server with 24 real CPU cores & 48 with HT enabled

```
perf_context disabled at compile-time
--statisics enabled/disabled
yes     no      dop     ratio
  9.8    12.7    1      .771
208.2   226.3   20      .920

perf_context enabled at run-time
--statisics enabled/disabled
yes     no      dop     ratio
  9.1     9.7    1      .938
179.3   188.6   20      .950

with --statisics enabled
perf_context enabled/disabled at compile-time
yes     no      dop     ratio
  9.1     9.8    1      .928
179.3   208.2   20      .861
```

**Comment by mdcallag** [comment]
And results for readonly that show:
* impact from --statistics is mostly less than 10% reduction in QPS
* impact from perf context compiled in but disabled at run time is a QPS loss between 15% and 20%

```
perf_context disabled at compile-time
--statisics enabled/disabled
yes     no      dop     ratio
 14.5    16.6    1      .873
224.3   242.6   20      .924

perf_context enabled at run-time
--statisics enabled/disabled
yes     no      dop     ratio
 11.5    12.4    1      .927
193.5   206.9   20      .935

with --statisics enabled
perf_context enabled/disabled at compile-time
yes     no      dop     ratio
 11.5    14.5    1      .793
193.5   224.3   20      .862
```

**Comment by PraveenSinghRao** [comment]
I verified that core_local has similar perf as thread local on Windows (both of which have lower perf than when statistics just modified member variables as in 4.8) for load part of RandomLoad benchmark.

I am curious how perf didn't change for linux. The benchmark issues the writes in a single thread. So multi-threaded optimization would not really benefit it. But statistics functions execute more instructions and calls including getcurrentprocessor to access core-local array (whereas in 4.8 they just accessed a member variable).

Making CoreLocalArray members __forceinline helped some on Windows (they were not getting inlined by default nor with inline keyword). It is possible these are inlined in Linux build.

**Comment by siying** [comment]
@lightmark fixed a recent performance regression: https://github.com/facebook/rocksdb/commit/0025a36409b2e3263a2909798a2c8c16942b9bae . Hopefully the perf_context regression problem has been solved.

**Comment by ajkr** [comment]
Thanks a lot for verifying, Praveen!

In my comment, I didn't mean to refer to the same benchmark that Mark used. My benchmark was more like multi-threaded read, in which case thread-local perf was similar to core-local perf, and both were faster than the global atomics in 4.8.

There is a blog post with more details: http://rocksdb.org/blog/2017/05/14/core-local-stats.html

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
