### ISSUE TITLE
Next released version eta

### ISSUE THREAD

**Issue by danhhz** [facebook/rocksdb#2496]
Hey! Do you have an estimate for when you'll cut the next release? There's a few commits that went in right after v5.4.6 9c9909bf7d978a4faab2def9f4570a7583899508 5a9b4d74354c1499839728831fecafd9b75b0af5 that we'd like. And we strongly prefer to use releases to picking some random commit at HEAD.

Thanks!

**Comment by yiwu-arbug** [comment]
cc @lightmark time for 5.5 release?

**Comment by danhhz** [comment]
Thanks @yiwu-arbug. Ping @lightmark any thoughts on timing for when this might happen?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
