### ISSUE TITLE
Get() with PinnableSlice for transaction.h?

### ISSUE THREAD

**Issue by jsteemann** [facebook/rocksdb#2509]
Since RocksDB 5.4.x there is a method `DB::Get()` that can store the lookup result in a `PinnableSlice`:

```
Status DB::Get(const ReadOptions& options, 
               ColumnFamilyHandle* column_family, 
               const Slice& key, 
               PinnableSlice* value)
```

That method will work on the raw database, but not in the context of transactions. 
Are there any plans to make an equivalent method (`Get` with `PinnableSlice` parameter) available in `utilities/transaction.h` as well? Thanks!

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
