### ISSUE TITLE
Target given more than once in the same rule (make)

### ISSUE THREAD

**Issue by wouterbeek** [facebook/rocksdb#2514]
When running `make shared_lib` I get the following warning message twice:

```
Makefile:1721: target 'utilities/merge_operators/cassandra/test_utils.d' given more than once in the same rule
```

I have installed all dependencies listed in `INSTALL.md` and my OS is Fedora 25.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
