### ISSUE TITLE
sst files are not removed with failing alter table

### ISSUE THREAD

**Issue by jocel1** [facebook/rocksdb#2524]
Hi!

I'm trying to migrate an existing innodb file with about 160M rows on MariaDB 10.2.6
I first created the table without secondary index, INSERT / SELECT the datas (it takes about 1h), and then try to ALTER TABLE to add the secondary indexes + a UNIQUE KEY.
For some reason not related to RocksDB, I have duplicates on the UNIQUE KEY, and it fails at the end of the ALTER TABLE process:
ERROR 1062 (23000): Duplicate entry '.\xF4S\xC8T\xDA\x133\x91P,\x84C[\xB5\xAE-8' for key 'md5_unique'

However, I noticed than all the sst files created during this process have not been deleted. 
I ran once again the command, and a bunch of new sst were created, so the size of the DB keeps growing.
Is this the expected behaviour?

RocksDB options used in the my.cnf:
rocksdb_enable_write_thread_adaptive_yield=ON
rocksdb_allow_concurrent_memtable_write=ON
rocksdb_blind_delete_primary_key=ON
rocksdb_enable_2pc=0
rocksdb_max_total_wal_size=4G
rocksdb_block_size=16384
rocksdb_block_cache_size=16G
rocksdb_write_disable_wal=1
rocksdb_max_background_flushes=40
rocksdb_max_background_compactions=40
rocksdb_bulk_load=1
rocksdb_commit_in_the_middle=1
rocksdb_flush_log_at_trx_commit=2

collation-server=utf8_bin

Thanks,
  Jocelyn Fournier

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
