### ISSUE TITLE
L0 -> L0 compaction generate a large sst file

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#2530]
In heavy write situation L0->L0 compaction may generate large sst file, maybe we need improve the L0->L0 compaction mechanism.
```
2017/07/01-12:57:29.569138 7fa068200700 [db/compaction_job.cc:1432] [default] [JOB 26043623] Compacting 28@0 files to L0, score 13.61

2017/07/01-12:57:29.569156 7fa068200700 [db/compaction_job.cc:1436] [default] Compaction start summary: Base version 28230 Base level 0, inputs: [147799(105MB) 147739(105MB) 147689(
105MB) 147645(105MB) 147603(105MB) 147545(105MB) 147495(105MB) 147457(105MB) 147410(105MB) 147371(105MB) 147328(105MB) 147281(105MB) 147209(105MB) 147157(105MB) 147111(105MB) 147054
(105MB) 147007(105MB) 146964(106MB) 146900(105MB) 146843(105MB) 146787(105MB) 146748(105MB) 146695(105MB) 146651(105MB) 146607(105MB) 146557(105MB) 146520(105MB) 146464(105MB)]
2017/07/01-12:57:29.569171 7fa068200700 EVENT_LOG_v1 {"time_micros": 1498885049569162, "job": 26043623, "event": "compaction_started", "files_L0": [147799, 147739, 147689, 147645, 1
47603, 147545, 147495, 147457, 147410, 147371, 147328, 147281, 147209, 147157, 147111, 147054, 147007, 146964, 146900, 146843, 146787, 146748, 146695, 146651, 146607, 146557, 146520
, 146464], "score": 13.6113, "input_data_size": 3104270093}

2017/07/01-13:02:50.186376 7fa068200700 [db/compaction_job.cc:1135] [default] [JOB 26043623] Generated table #147827: 15531332 keys, **3099345523** bytes
2017/07/01-13:02:50.186412 7fa068200700 EVENT_LOG_v1 {"time_micros": 1498885370186395, "cf_name": "default", "job": 26043623, "event": "table_file_creation", "file_number": 147827, "file_size": 3099345523, "table_properties": {"data_size": 3079402587, "index_size": 527744, "filter_size": 19414213, "raw_key_size": 683378458, "raw_average_key_size": 43, "raw_value_size": 2635487806, "raw_average_value_size": 169, "num_data_blocks": 11752, "num_entries": 15531332, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "63500", "kMergeOperands": "0"}}
```
@ajkr Please take a look when you are free.

**Comment by rockeet** [comment]
We also encountered this issue, in one of our case, with universal compaction, L0->L0 compaction input reached 2TB. The compressed "input_data_size" is 572GB, the decompressed is more than 2TB.

> 2017/07/01-11:51:09.435575 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435547) [default] Universal: sorted runs files(528): files[527 0 0 0 0 0 18] max score 52.12 (415 files need compaction)
> 2017/07/01-11:51:09.435579 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435549) [default] Universal: First candidate file 7883[0]  to reduce size amp.
> 2017/07/01-11:51:09.435581 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435550) [default] Universal: Possible candidate file 7880[0]  is already being compacted. No size amp reduction possible.
> 2017/07/01-11:51:09.435584 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435552) [default] Universal: Possible candidate file 7883[0].
> 2017/07/01-11:51:09.435586 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435555) [default] Universal: Picking file 7883[0] with size 447646079936 (compensated size 447646079936)
> 2017/07/01-11:51:09.435589 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435557) [default] Universal: Picking file 7889[1] with size 95953998469 (compensated size 95953998469)
> 2017/07/01-11:51:09.435591 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435557) [default] Universal: Picking file 7890[2] with size 29167285335 (compensated size 29167285335)
> 2017/07/01-11:51:09.435593 7ffc5fc51700 (Original Log Time 2017/07/01-11:51:09.435565) [default] Universal: compacting for size ratio
> 2017/07/01-11:51:09.435596 7ffc5fc51700 [default] [JOB 4291] Compacting 3@0 files to L0, score 52.12
> 2017/07/01-11:51:09.435601 7ffc5fc51700 [default] Compaction start summary: Base version 4112 Base level 0, inputs: [7883(416GB) 7889(89GB) 7890(27GB)], [], [], [], [], [], []
> 2017/07/01-11:51:09.435616 7ffc5fc51700 EVENT_LOG_v1 {"time_micros": 1498881069435605, "job": 4291, "event": "compaction_started", "files_L0": [7883, 7889, 7890], "files_L1": [], "files_L2": [], "files_L3": [], "files_L4": [], "files_L5": [], "files_L6": [], "score": 52.125, "input_data_size": 572767363740}
>

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
