### ISSUE TITLE
suggest to update “PlainTable Format” wiki

### ISSUE THREAD

**Issue by xieyilun** [facebook/rocksdb#2538]
1. remove "TotalOrderPlainTableFactory"

2. recommend use "CappedPrefixTransform" instead of "FixedPrefixTransform", because assertion not work in release

**Comment by siying** [comment]
Which assert doesn't work with FixedPrefixTransform?

**Comment by xieyilun** [comment]
util/slice.cc

virtual Slice Transform(const Slice& src) const override {
  assert(InDomain(src));
  return Slice(src.data(), prefix_len_);
}

make release，this assert doesn't work

**Comment by siying** [comment]
Oh you are using keys shorter than that?

**Comment by xieyilun** [comment]
Yes
So I suggest to recommend CappedPrefixTransform in your wiki

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
