### ISSUE TITLE
DISABLE_JEMALLOC doesn't prevent linking

### ISSUE THREAD

**Issue by KenMacD** [facebook/rocksdb#2555]
On Linux when building `rocksdb` with:

    DISABLE_JEMALLOC=1 make shared_lib

The resulting shared library will still link against `jemalloc` if it was installed on the system.

It seems to be being added at:

https://github.com/facebook/rocksdb/blob/master/build_tools/build_detect_platform#L317-L322

**Comment by maysamyabandeh** [comment]
Seems make sense to move the jemalloc update of PLATFORM_LDFLAGS and JAVA_LDFLAGS to  
this line in the Makefile: https://github.com/facebook/rocksdb/blob/master/Makefile#L220
```
ifndef DISABLE_JEMALLOC
   ifdef JEMALLOC
```
@siying what do you think?

**Comment by siying** [comment]
@maysamyabandeh I don't have an opinion on this.
