### ISSUE TITLE
Column families related functions for `rocksdb_transactiondb_t` (C-API)

### ISSUE THREAD

**Issue by DarkEld3r** [facebook/rocksdb#2564]
Column families related functions are missing for the `rocksdb_transactiondb_t` in the C-API. I suppose implementation should be pretty straightforward, so I can try to submit a pull request. Am I missing something?

**Comment by adamretter** [comment]
@DarkEld3r Probably not. The C and Java API's sometimes lag behind the C++ API. If you see something missing that you want, please sign the CLA and send a PR :-)

**Comment by DarkEld3r** [comment]
@adamretter Sorry for bothering, but I have made the pull request (#2669) that fixes this issue. Could you please provide some information? Is there a hope for merging? :smile:

**Comment by adamretter** [comment]
@DarkEld3r I am not really involved in the C API. Perhaps @siying can get the right person to take a look?
