### ISSUE TITLE
rocksdb 5.5.1 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [facebook/rocksdb#2565]
RE: https://github.com/Homebrew/homebrew-core/pull/15141

The sha256 checksum for rocksdb 5.5.1 was originally (https://github.com/Homebrew/homebrew-core/commit/1b2b13222787fe4a4e81299b1fef16fa06fd9f9f)
a1d29149d23bfc8635e464505daf222fcdefa3eaa67455fe38725ba7c9478602
but for the [current download](https://github.com/facebook/rocksdb/archive/v5.5.1.tar.gz), it's
b8d8848bc2fd08905c034e5fb4d471fe137237825a19dfbe251d23b25df1ed3b

Just wanted to make sure you weren't hacked, and ask what the reason(s) for the changes were.

**Comment by adamretter** [comment]
@siying Would this have changed when I noticed the issue with the tags (which I think you addressed)?

**Comment by ilovezfs** [comment]
@lightmark @ajkr @yiwu-arbug any ideas? This issue is now blocking the snappy 1.1.6 upgrade in Homebrew.

**Comment by yiwu-arbug** [comment]
@ilovezfs The one only the current download page is the correct one. We tagged the wrong revision at the beginning but corrected it later. Are you able to fix it on homebrew side? Sorry for inconvenience.

**Comment by ilovezfs** [comment]
@yiwu-arbug In the future, it would be best to tag a new version (even if it's 5.5.1.1 or 5.5.2) rather than retagging.

I could update the checksum this time, but it will mean it will be more difficult for you to determine which users are on the not-really-5.5.1 version we've been distributing so far, and which ones are on the ok-it's-really-5.5.1-this-time version.

**Comment by yiwu-arbug** [comment]
@ilovezfs totally agree. Will create a 5.5.2 tag to fix the confusion.

**Comment by ilovezfs** [comment]
@yiwu-arbug that would be awesome. Thanks!

**Comment by yiwu-arbug** [comment]
Done. Just created 5.5.2 tag.

**Comment by ilovezfs** [comment]
@yiwu-arbug thanks: https://github.com/Homebrew/homebrew-core/pull/15597.
