### ISSUE TITLE
A question about blobdb

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#2582]
When use blobdb with multiple column families, currently all values are store in the blob file, sometimes we wanna store some column families's value in the blob file, and the others we wanna store them in the lsm engine, because some column families's values are short, at the same time we want guarantee the write through multiple column families is atomic. 
@anirbanr-fb Is there any plan to support such feature? Thanks in advance.

**Comment by yiwu-arbug** [comment]
Thank you for your interest in blob db! The blob db is not yet ready as I'm still trying to fix some crash issue. Also option to store value in LSM is not implemented yet. Though to achieve atomic writes you can simply use write batch on top of blob db.
