### ISSUE TITLE
Runtime unhandled exception with RocksDB on Windows

### ISSUE THREAD

**Issue by sangodbole** [facebook/rocksdb#2585]
Hi Team, 
I am seeing the following exception at Runtime with my c++ application trying to use RocksDB. 
Unhandled exception at 0x000000013F5A43E0 in TestRocks.exe: 0xC000001D: Illegal Instruction.

Happening in file lru_cache.cc line 443. 
 int num_shards = 1 << num_shard_bits;

Other important build information:

Build on VS2017 with Release x64 Windows7
all libraries built for x64
Rocks DB built exactly according to this page with zlib as compression
https://github.com/facebook/rocksdb/wiki/Building-on-Windows

My Source coude that calls rocksDB:
#include <cassert>
#include "rocksdb/db.h"
int main()
{
	rocksdb::DB* db;
	rocksdb::Options options;
	options.create_if_missing = true;
	rocksdb::Status status = rocksdb::DB::Open(options, "/tmp/testdb", &db);
	assert(status.ok());
}

would definitely appreciate if anyone has any pointers. I can provide any more system information if necessary.  All code compiles and builds without any errors or warning.

**Comment by maysamyabandeh** [comment]
Illegal Instruction usually means a wrong option is applied to the compiler. Perhaps you can share the options used by the compiler in the rocksdb user group (https://www.facebook.com/groups/rocksdb.dev) so that the other windows users might be able to help you.

**Comment by sangodbole** [comment]
I use the following options 
cmake -G "Visual Studio 15 Win64" -DGFLAGS=1 -DZLIB=1 ..
msbuild rocksdb.sln /p:Configuration=Release

I will share them in the user group as well. Thanks

**Comment by sangodbole** [comment]
Someone from the facebook community helped me. works with the option -DPORTABLE=1 
Apparently my processor does not support the newest instructions.
