### ISSUE TITLE
Static lib file size is bigger than expected

### ISSUE THREAD

**Issue by JohnsonJackblue** [facebook/rocksdb#2593]
Hello,

I recently build RocksDB with Windows and my rocksdb.lib have a size of 170 mb, I would like to know if it's normal.

Also I found this stackoverflow topic : https://stackoverflow.com/questions/40192894/rocksdb-static-library-size-thats-built-from-source-is-really-large

Strip solve his problem, but Visual studio set debug symbols on a pdb file well normally this problem can not happen.

Cordially,

**Comment by JohnsonJackblue** [comment]
I also tried to use
`msbuild rocksdb.sln /p:Configuration=MinSizeRel /p:Plateform=x64`
but I earn only 4mb. I don't know if I did something wrong or it's the normal size of this lib because linux package is around 12mb.

Thanks in advance !

**Comment by sagar0** [comment]
Wondering if @yuslepukhin can help?

**Comment by sagar0** [comment]
This seems to have been answered in the RocksDB google group.

**Comment by JohnsonJackblue** [comment]
Thanks @sagar0, I've taken a look to the RocksDB google group but see nothing related, if you can post the link to the topic I will really appreciate :)

Also, I tried to use shared lib instead to reduce library size, but I get symbols error even if the rocksdb-shared.lib is correctly linked on my visual studio project (and rocksdb-shared.dll is on my Release folder).
Also include are correctly set up.

Here the log:

```
1>TestApp.obj : error LNK2001: unresolved external symbol "public: __cdecl rocksdb::DBOptions::DBOptions(void)" (??0DBOptions@rocksdb@@QEAA@XZ)
1>TestApp.obj : error LNK2001: unresolved external symbol "public: __cdecl rocksdb::ColumnFamilyOptions::ColumnFamilyOptions(void)" (??0ColumnFamilyOptions@rocksdb@@QEAA@XZ)
1>TestApp.obj : error LNK2001: unresolved external symbol "public: static class rocksdb::Status __cdecl rocksdb::DB::Open(struct rocksdb::Options const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class rocksdb::DB * *)" (?Open@DB@rocksdb@@SA?AVStatus@2@AEBUOptions@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAPEAV12@@Z)
1>TestApp.obj : error LNK2001: unresolved external symbol "public: __cdecl rocksdb::ReadOptions::ReadOptions(void)" (??0ReadOptions@rocksdb@@QEAA@XZ)
1>C:\Users\Jackblue\documents\visual studio 2015\Projects\TestApp\x64\Release\TestApp.exe : fatal error LNK1120: 4 unresolved externals
```

**Comment by sagar0** [comment]
Sorry, my mistake: not 'google' group but our 'facebook' group :) . 
I was referring to your post in "RocksDB Developers Public" facebook group: https://www.facebook.com/groups/rocksdb.dev/permalink/1341600742605103/ . @PraveenSinghRao seems to have replied there.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
