### ISSUE TITLE
LITE build broken on db_bench again

### ISSUE THREAD

**Issue by lxcode** [facebook/rocksdb#2596]
There appears to have been a regression between 5.4.6 and 5.5.2 causing the same issue as described in:

https://github.com/facebook/rocksdb/issues/2386

Build log is here:

http://beefy9.nyi.freebsd.org/data/110amd64-default/445841/logs/rocksdb-lite-5.5.2.log

**Comment by yiwu-arbug** [comment]
Just tag 5.5.3 with fixes for lite build.
