### ISSUE TITLE
Breaking code changes: "do not read next datablock if upperbound is reached"

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#2604]
Breaking code changes: a30a6960346518dadb7e79184116b5bc68c1fe2c

This commit breaked existing SST implementations, and imposed irrelevant unneeded module coupling.

"do not read next datablock", this feature should be implemented in SSTable(especially for BlockBasedTable) itself, and should not escape out of SSTable implementation boundary.

There are also [many comments](https://github.com/facebook/rocksdb/pull/2239) which intended to reject this pull request, but the pull request was accepted finally? What's wrong in the process?

@siying @IslamAbdelRahman @lightmark @al13n321

**Comment by siying** [comment]
Can you explain what scenario this commit broke?

**Comment by rockeet** [comment]
[TableReader::NewIterator](https://github.com/facebook/rocksdb/pull/2239/files#diff-e46a3603a4d8aece5d21dcfcda8f3f5aL43) was added a parameter `const InternalKeyComparator*`,  this change was spread to all rocksdb builtin SSTable implementations.

The alternative solution should be using existing `TableReaderOptions::internal_comparator`, this will not break any existing code.

**Comment by rockeet** [comment]
@siying @lightmark Is there any update?

**Comment by siying** [comment]
The function you mentioned is not public RocksDB API. If you fork your own branch and have some updates there, it is expected that you'll need to sometimes do some hard change when the upstream updates.

**Comment by rockeet** [comment]
Yes, I can always merge upstream changes, the real issue is: such inappropriate code changes will lead rocksdb code into a disordered state, which will finally harm `rocksdb itself`.

Now that has such a good solution(using `TableReaderOptions::internal_comparator`), it should be fixed.

@siying @lightmark

**Comment by ajkr** [comment]
`TableReaderOptions` is part of the `TableFactory::NewTableReader` API. It is not part of any `TableReader` APIs. Thus in the current code we cannot guarantee an arbitrary `TableReader` has access to an `InternalKeyComparator`.

If you want to fix this, feel free to submit a PR. I do not agree this was a breaking code change as it conforms to the existing design (refactoring as you desire is a separate concern) and only affected internal APIs.

**Comment by ajkr** [comment]
it should be `rep_->internal_comparator` in block-based table reader as we don't have access to the `TableReaderOptions` there. @lightmark can you fix it when you're back from vacation?

**Comment by rockeet** [comment]
@lightmark As this pull request has  other code changes, can you fix it? As @ajkr commented, it is `rep_->internal_comparator` for block-based table, for other tables, `internal_compare` can be always accessed in `TableFactory::NewTableReader` through param `TableReaderOptions`.

**Comment by rockeet** [comment]
Is there any update?

**Comment by lightmark** [comment]
I just come back from PTO. I can fix it but I don't quite sure how does it lead rocksdb code into **disorder** state as nothing in public api changed.

**Comment by rockeet** [comment]
@lightmark Thanks for your fix! Now there is no **disorder** state, it's great!

**Comment by mm304321141** [comment]
@lightmark https://github.com/Terark/terark-zip-rocksdb
We implemented a custom table ...

**Comment by lightmark** [comment]
@mm304321141 That is not recommended.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
