### ISSUE TITLE
License update not included in latest releases

### ISSUE THREAD

**Issue by StefanRRichter** [facebook/rocksdb#2605]
Hi,

I noticed that RocksDB changed the license in the current master so that it can be safely used in Apache projects. Unfortunately, I think the new license text was not included in the latest releases or and is also not merged into any of the current 5.x branches. This makes the current releases still not useable for Apache projects. Is there any plan to propagate the license changes into the next releases?

Best,
Stefan

**Comment by siying** [comment]
We are going release something with the change.

**Comment by siying** [comment]
We just released 5.5.4.

**Comment by StefanRRichter** [comment]
Thanks, that was quick! :-)

**Comment by siying** [comment]
We'll probably need to release 5.5.5 soon with this change https://github.com/facebook/rocksdb/pull/2610/
