### ISSUE TITLE
blobdb return wrong value

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#2611]
I use blobdb, and create a column family,  after I put a key/value to this cf I read it, but the returned value is not equal with the one I have putted.
```
put msg cf, key: [135, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2], value: [10, 4, 8, 5, 24, 5, 16, 5]
get msg cf key: [135, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2], value: [2, 158, 1, 8, 0]
```

**Comment by yiwu-arbug** [comment]
Are you testing with the latest master? Are you hitting #2553?

**Comment by zhangjinpeng1987** [comment]
@yiwu-arbug Thanks, exactly hitting the bug.

**Comment by zhangjinpeng1987** [comment]
BTW, When there are multiple column families with blobdb, if we can specified which column family should use blob engine and which should use lsm engine, this is helpfull for our use case. And if each column family has individual blobfile is also helpfull, because each column family's data has its own characteristic, this will make gc more efficiently.

**Comment by yiwu-arbug** [comment]
@zhangjinpeng1987 Thanks for the suggestion. May consider it later on.
