### ISSUE TITLE
Return type for SliceTransform::Transform is too limiting

### ISSUE THREAD

**Issue by GilGribb** [facebook/rocksdb#2614]
SliceTransform::Transform returns a slice, when it should return a string.

For example, suppose the key is a 64 bit unsigned int and we are using little endian machines. Thus a memcmp()-type total order (i.e. lexicographic on bytes) is not really what you want. No problem, we can easily define a rocksdb::Comparator that does the right thing to order the DB the way you expect: 0,1,2,3...

But what if we want to use prefix seek mode with our little endian 64 bit unsigned  int? Maybe we want our "prefix" to be the high order 32 bits. There is no good way to do it because SliceTransform::Transform returns a slice, which pretty much means it must be a substring of the original key. In our example, the prefix is not a substring of the original key string. The prefix is the same length as the original key (64 bits), it just has all of the the lower bits set to zero.

Rocks is designed to work with binary data for high performance applications. This is great. Because of the return value from SliceTransform::Transform is a slice, it isn't practical to use prefix seek mode with binary keys. Since binary data is best for performance, this is a drag.

I can probably work around it by using slices from a huge array of all possible prefixes (I don't have that many). But that would be 32GB of RAM for the 64 bit unsigned int example.

**Comment by HassanCehef** [comment]
Hi,

For your example, it seems like you could solve the issue by writing your integers in a big-endian way. 
using https://linux.die.net/man/3/htobe32 it should work on both little and big-endianned processors. Then your keys will be sorted. You can also prefix seek on only the high order 32 bits: just change your query to also apply htobeXX functions first.

**Comment by GilGribb** [comment]
>For your example, it seems like you could solve the issue by writing your integers in a big-endian way.

Yeah is another workaround for the example I gave. But then I can't use the slices coming back from rocks directly; I have to make a byte swapped version.

That doesn't work in general. Suppose I wanted to "prefix" on the high 22 bits instead of the high 32 bits (this is perfectly reasonable). Now again, no slice of the given key is the prefix and byte swapping can't help. 

My actual use case is more like spatial hashing using Morton codes. 

So what we are left if with is encoding and decoding (as in an endian swap). This is undesirable because it means prefix seek mode just doesn't work with arbitrary key spaces (yet the rest of rocks was designed to support arbitrary key spaces).

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
