### ISSUE TITLE
RocksDB Java requires Visual C++ Runtime for Visual Studio 2015 to be installed

### ISSUE THREAD

**Issue by nihathrael** [facebook/rocksdb#2622]
Hi everyone,
it seems rocksdb java requires the Visual C++ Runtime for Visual Studio 2015 to be installed on a windows machine in order to run. Otherwise an exception similar to this will be thrown:

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\...\librocksdbjni8946565711160985166.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.load0(Unknown Source)
        at java.lang.System.load(Unknown Source)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35
```

As far as I understood the included binaries should be statically linked. 

Is it possible to include the visual studio runtime statically, so that no additional software needs to be installed on an "empty" windows server when using rocksdb or is this technically not possible?

Best,
Thomas

**Comment by adamretter** [comment]
I think we would be able to do this using the `/MT` argument to the linker. However this is probably a question better answered by @yuslepukhin.

**Comment by mkosieradzki** [comment]
I think the most simplistic way instead of doing static linking is deploy vc runtime dlls together with your application (as private assemblies)

https://msdn.microsoft.com/en-us/library/ms235291.aspx

This is MUCH easier and much more elastic approach.

**Comment by adamretter** [comment]
@mkosieradzki So the article you linked seems to suggest copying the .dll's for the C++ runtime into the application package, and names the files as `mfc100u.dll` and `msvcr100.dll`.
However Visual Studio 2015, does not seem to have those files, the closest named files that I can find is `mfc140u.dll` and `msvcp140.dll`. However I am not at all sure they are the correct files.

Is it really a problem for the end-user to install "Microsoft Visual C++ 2015 Redistributable" from https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by mkosieradzki** [comment]
It depends on the VS version.
VS2015 (internally named 14) uses msvcr140.dll

IMO. It is usually not a problem, I am just providing this specific solution for people that are very pushy on static linking which I find useful in limited number of scenarios.

People tend to do the following (false) distinction:
1. static linking - hooray! we don't have to install anything
2. dynamic linking - booo! we need to install vcredist...

And there are many projects statically linked for WRONG reasons (I am not saying static linking is bad, I am saying static linking for wrong reason is bad).

So if they need really need to avoid vcredist installation they can just xcopy some dlls...

**Comment by adamretter** [comment]
@mkosieradzki Strange. I cannot find a `msvcr140.dll` on my system, only a `msvcp140.dll`?!?

**Comment by mkosieradzki** [comment]
My bad. There is new layout in VS 2015 (I used the mechanism described above for older runtime versions) so I didn't noticed that they have changed the package layout in VS2015.

https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/

There are many good news in the linked article :), especially when targeting the newest versions of windows.

BTW. application local method is still supported:

>App-local deployment of the Universal CRT is supported.  To obtain the binaries for app-local deployment, install the Windows Software Development Kit (SDK) for Windows 10.  The binaries will be installed to C:\Program Files (x86)\Windows Kits\10\Redist\ucrt.  You will need to copy all of the DLLs with your app (note that the set of DLLs are necessary is different on different versions of Windows, so you must include all of the DLLs in order for your program to run on all supported versions of Windows).
```

**Comment by mkosieradzki** [comment]
Also yet another point against static linking:
> If you currently statically link the Visual C++ libraries, then things will continue to work just as they currently work for you.  We strongly recommend against static linking of the Visual C++ libraries, for both performance and serviceability reasons, but we recognize that there are some use cases that require static libraries and we will continue to support the static libraries for those reasons.

**Comment by adamretter** [comment]
@yuslepukhin Do you have any thoughts on best practice here please?

**Comment by adamretter** [comment]
I think we can close this for now. If someone wishes to send a PR to add an option for static linking to our Windows CMake build we can then reconsider it.
