### ISSUE TITLE
Expose OptimisticTransactionDB in the C API

### ISSUE THREAD

**Issue by mkosieradzki** [facebook/rocksdb#2632]
WriteWithCallback is required to implement optimistic transactions and I would like to add such a feature in C# API.

It is currently not exposed in the C API.

If required I can try to create a PR.

**Comment by sagar0** [comment]
Please do. We'd love to have such a contribution.

**Comment by mkosieradzki** [comment]
OK. BTW I can see I will also need to expose:
at least

GetLatestSequenceNumber 

and

GetLatestSequenceForKey, GetEarliestMemTableSequenceNumber, GetAndRefSuperVersion (which can be called only on the write thread), ReturnAndCleanupSuperVersion 
OR
something more high-level like TransactionUtil::CheckKeysForConflicts

And if I wanted to add snapshots support it's getting way too complex.

I have noticed that for JNI they are using C++ API. Maybe I should try to do the same for C#.

Maybe it would be a better idea just to expose OptimisticTransactionDB in C API in a similar manner that TransactionDB is already exposed?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
