### ISSUE TITLE
rdb tool cannot not compile 

### ISSUE THREAD

**Issue by zydcom** [facebook/rocksdb#2635]
`node-gyp build` cannot work well 

```
make: Entering directory `/home/linqing.zyd/rocksdb/tools/rdb/build'
  CXX(target) Release/obj.target/rdb/rdb.o
../rdb.cc:7:25: fatal error: db/_wrapper.h: No such file or directory
 #include "db/_wrapper.h"
                         ^
compilation terminated.
make: *** [Release/obj.target/rdb/rdb.o] Error 1
make: Leaving directory `/home/linqing.zyd/rocksdb/tools/rdb/build'
```

**Comment by yiwu-arbug** [comment]
It should probably be "db/db_wrapper.h". Can you try if it works? If so, do you mind sending a pull request to fix it? Thanks!

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by adnavare** [comment]
Hi I am facing this same error when compiling rdb. I don't see db/dh_wrapper.h in my current rdb directory. So i have replaced it with just db_wrapper.h. But now after changing that i am seeing the error

 ../db_wrapper.h:49:38: error: ‘Arguments’ does not name a type
     static Handle<Value> Close(const Arguments& args);

Can someone please help me in compiling this tool.

**Comment by macnod** [comment]
I couldn't immediately get this to compile, so I'm using the ldb program included in the tools folder.  I built that one by going to the rocksdb home folder and running `make ldb`.
