### ISSUE TITLE
make tools error when using g++ 7.1.1

### ISSUE THREAD

**Issue by choleraehyq** [facebook/rocksdb#2672]
```
[cholerae@x240s rocksdb]$ make tools
Makefile:117: Warning: Compiling in debug mode. Don't use the resulting binary in production
  GEN      util/build_version.cc
  CC       cache/lru_cache.o
cache/lru_cache.cc: In constructor ‘rocksdb::LRUCache::LRUCache(size_t, int, bool, double)’:
cache/lru_cache.cc:464:42: error: ‘new’ of type ‘rocksdb::LRUCacheShard’ with extended alignment 64 [-Werror=aligned-new=]
   shards_ = new LRUCacheShard[num_shards_];
                                          ^
cache/lru_cache.cc:464:42: note: uses ‘void* operator new [](std::size_t)’, which does not have an alignment parameter
cache/lru_cache.cc:464:42: note: use ‘-faligned-new’ to enable C++17 over-aligned new support
cc1plus: all warnings being treated as errors
make: *** [Makefile:1721: cache/lru_cache.o] Error 1
```

```
[cholerae@x240s rocksdb]$ g++ --version
g++ (GCC) 7.1.1 20170622 (Red Hat 7.1.1-3)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by maysamyabandeh** [comment]
Seems like you are passing -Waligned-new to your compiler:
https://gcc.gnu.org/gcc-7/changes.html

> -Waligned-new has been added to the C++ front end. It warns about new of type with extended alignment without -faligned-new.

**Comment by choleraehyq** [comment]
I just use the official Makefile without any change. Maybe we should modify the Makefile to fit gcc 7?

**Comment by siying** [comment]
CC @IslamAbdelRahman

**Comment by maysamyabandeh** [comment]
Would you like to submit a pull request?

**Comment by choleraehyq** [comment]
Ok, I'll have a try.

**Comment by grooverdan** [comment]
FYI things I've tried but not managed to get correct yet (out of time for now).

https://github.com/grooverdan/rocksdb/commit/22b6b716621b2fc1e04a95d31dcc7907022f4b8c

(still complains of same error).

https://github.com/grooverdan/rocksdb/commit/928ade378fae26843f68a392fd866feef84f32d4

CXXFLAGS=-std=c++1z  need for gcc/clang of version clang-4.0 (__cplusplus == 201406)/gcc-7.1 (#if __cplusplus >= 201703) which is the base need to support operator new[](sz,align). (note gcc-6.3 has __cplusplus at 201500).
(needs proper escaping to work with old compilers) 

For testing suggest playing with https://wandbox.org/ with a samples like:
<pre>
// This file is a "Hello, world!" in C++ language by GCC for wandbox.
#include <iostream>
#include <cstdlib>

class A
{
public:
#if __cplusplus >= 201703
   void* operator new[](size_t s, std::align_val_t a) { return aligned_alloc( (size_t)a, s); }
#endif
};

int main()
{
    A  *ptr = new(std::align_val_t(64)) A[7];
    std::cout << "Hello, Wandbox! " <<  __cplusplus << std::endl;
}
</pre>

**Comment by grooverdan** [comment]
Oh, and I haven't even looked how OSX clang versions map into this.
