### ISSUE TITLE
rocksdb::RepairDB leaks WAL files under options.wal_dir

### ISSUE THREAD

**Issue by Liuchang0812** [facebook/rocksdb#2673]

**Comment by maysamyabandeh** [comment]
@Liuchang0812 Thanks for reporting. Unfortunately without more details the report is not actionable.

**Comment by siying** [comment]
CC @ajkr

**Comment by Liuchang0812** [comment]
thank you, i will give more informations soon.

**Comment by siying** [comment]
@Liuchang0812 a pull request will be more preferred:)

**Comment by Liuchang0812** [comment]
@siying yeah, I will create a PR this weekend.
