### ISSUE TITLE
Too many SST files of very small size

### ISSUE THREAD

**Issue by AmanSin** [facebook/rocksdb#2686]
Hello Team

I am using RocksDBJava after running the service for sometime I can see the "Too many open files" exception. Digging though the previous issue mentioned on the portal I found out that it is because of system limitation of opening a maximum number of files.
When I check the directory, which the rocksDB is using, I noticed there is over 100K sst files of 1KB size, and this can be the reason of the given error.
I wanted to know is there any way by which we can configure the rocksBD to generate SST files of large size, so that the total number of files created is minimum and we can avoid this error.

**Comment by AmanSin** [comment]
Also in my current project there ane many read threads and one write thread, and I open and close the connection (using RocksDB.open() and RocksDB.close() ) before reading or writing to the rockdDB.

**Comment by maysamyabandeh** [comment]
Github issues is not the best place to ask for configuration help. I recommend user group (https://www.facebook.com/groups/rocksdb.dev) where other users can help you with that.
