### ISSUE TITLE
RockJava assertion error with ColumnFamilyHandle

### ISSUE THREAD

**Issue by scottfines** [facebook/rocksdb#2687]
Looks like a very simple looping problem can result in an assertion failure:

```java
File tmpDir = Files.createTempDir();

try (RocksDB rocksDB = RocksDB.open(tmpDir.getAbsolutePath())) {
	ColumnFamilyDescriptor cdf = new ColumnFamilyDescriptor("column-0".getBytes(Charsets.UTF_8),new ColumnFamilyOptions());
	ColumnFamilyHandle handle = rocksDB.createColumnFamily(cdf);

	int numKeys = 500_000;

	for (int i = 0; i < numKeys; ++i) {
		byte[] key = new byte[50];
		byte[] val = new byte[] { 42 };
		rocksDB.put(handle,key, val);
	}
}

tmpDir.delete();
```

will produce 

```
Assertion failed: (refs_.load(std::memory_order_relaxed) == 0), function ~ColumnFamilyData, file db/column_family.cc, line 425.
```

This does not appear to occur in rocks 5.3.6, but starts occurring in 5.4.5 and carries through to 5.6.1 (I didn't try 5.5.x)

Environment:
java version: Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
rocksdb version: 5.6.1 AND 5.4.5
Os: Mac OS X Siera

**Comment by maysamyabandeh** [comment]
We had a similar issue but was reported fix in 5.5.1: https://github.com/facebook/rocksdb/issues/1964
@adamretter do you think it is the same problem?

**Comment by adamretter** [comment]
@maysamyabandeh It does look familiar yes.

@scottfines Can you please try and refactor your code to follow the correct alloc/free order as described here: https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#opening-a-database-with-column-families

**Comment by maysamyabandeh** [comment]
@adamretter since this is a bit unintuitive is it possible to automatically point the users to the wiki doc. For example we can augment the assert message to include that. Or perhaps we can do more?

**Comment by adamretter** [comment]
@maysamyabandeh Yes I have some ideas about how to make this more Java like. I will send a PR soon.

**Comment by flozano** [comment]
I'm getting this same error and I think I'm following the same alloc/free order as described above:
```
	@Override
	public void close() {
		closeColumnFamilyHandles();
		closeDatabase();
		closeDatabaseOptions();
		closeColumnFamilyOptions();
		deletePath();
	}
```
each `close****` method just does try{}catch() with error logging). There are no occurences of such errors in the log.

I've tried reordering above a little, and I still get the same assertion error. I'm using RocksDB 5.8.0, JDK 1.8.0_144, MacOS 10.12.

**Comment by publicocean0** [comment]
In my code i m using a RockdbGarbageCollector class ... you could use a similar class for handling the logic for freeing objects

**Comment by maysamyabandeh** [comment]
@adamretter Is the PR you had in mind already landed?

**Comment by adamretter** [comment]
Conclusion is to implement proposed changes in https://github.com/facebook/rocksdb/issues/974
