### ISSUE TITLE
IO error: While open a file for random read

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#2696]
We encounter `IO error: While open a file for random read: /data1/kv1/deploy/data/db/093618.sst: No such file or directory` error, why this would happen?
```
2017/08/04 13:01:55.218 region.rs:207: [ERROR] failed to delete data in [zt\200\000\000\000\000\000\000\377\035_i\200\000\000\000\000\377\000\000\001\003\200\000\000\000\377Y\2037\225\003\200\000\000\377\000\000\213\025E\000\000\000\374, zt\200\000\000\000\000\000\000\377\035_i\200\000\000\000\000\377\000\000\001\003\200\000\000\000\377Y\203y\325\003\200\000\000\377\000\000\326\320\314\000\000\000\374): Other(StringError(“IO error: While open a file for random read: /data1/kv1/deploy/data/db/093618.sst: No such file or directory”))
```

**Comment by zhangjinpeng1987** [comment]
BTW, we don't use `delete_files_in_range`.

**Comment by maysamyabandeh** [comment]
It could be a bug or simply a disk error. At this point there is not much data to suggest that it is a bug or help in debugging it.

**Comment by yiwu-arbug** [comment]
Closing the issue for now. @zhangjinpeng1987 reopen if you can provide more input.

**Comment by panda-sheep** [comment]
@zhangjinpeng1987 Did you encounter this problem later? Me too. Failed to start an empty rocksdb.
