### ISSUE TITLE
Delete DB does not delete the entire DB

### ISSUE THREAD

**Issue by sangodbole** [facebook/rocksdb#2701]
I have the following program running RocksDB on windows with C++. I see that delete is deleting only one of the *.sst files and rest of the db is still on disk. Could someone tell if this is an expected behavior(if yes, is there another way to remove all the db files). Is Batch insert the problem here? I appreciate all the help in advance. 

#include "rocksdb/db.h"
using namespace std;
int main()
{
	rocksdb::DB* db;
	rocksdb::Options options;
	options.create_if_missing = true;
	rocksdb::WriteOptions write_options;
	write_options.disableWAL = true;

	rocksdb::Status status = rocksdb::DB::Open(options, "C:\\Code\\testdb", &db);
	std::string m_Const = "aaa";
	vector<string> valueBatchVector;
	rocksdb::WriteBatch batch;

	// create a batch of 10000
	for (uint32_t key = 0; key < 10000; key++)
	{
		valueBatchVector.push_back(m_Const + to_string(key));
	}
	//put it in rocksDB
	for (int i = 0; i < 1000; i++)
	{
		int intKey;
		batch.Clear();
		for (int j = 0; j < 10000; j++)
		{
			intKey = j + i * 10000;
			rocksdb::Slice keyS((char*)&intKey, sizeof(int));
			batch.Put(keyS, valueBatchVector[j]);
		}
		if (status.ok())
			status = db->Write(write_options, &batch);
	}
	//delete the db
	delete db;
}

**Comment by siying** [comment]
`delete db;` only closes the DB. If you want to clean up the data call DestroyDB() after it.

**Comment by sangodbole** [comment]
Thanks! That works.
