### ISSUE TITLE
build err on freebsd11.1 clang 4.0

### ISSUE THREAD

**Issue by ananclub** [facebook/rocksdb#2707]
CC       utilities/column_aware_encoding_util.o
utilities/column_aware_encoding_util.cc:61:23: error: cannot use dynamic_cast with -fno-rtti
  table_reader_.reset(dynamic_cast<BlockBasedTable*>(table_reader.release()));

FreeBSD clang version 4.0.0 (tags/RELEASE_400/final 297347) (based on LLVM 4.0.0)
Target: x86_64-unknown-freebsd11.1
Thread model: posix
InstalledDir: /usr/bin

**Comment by yiwu-arbug** [comment]
Will fix soon.

**Comment by yiwu-arbug** [comment]
A workaround is add USE_RTTI=1 when building, e.g. `USE_RTTI=1 make all`.

**Comment by yiwu-arbug** [comment]
What's the command you use to build? `make all` are not compatible with `DEBUG_LEVEL=0`.

**Comment by ananclub** [comment]
sorry for reply late.

I use below command to build.

gmake DEBUG_LEVEL=0 CXX=c++ EXTRA_CXXFLAGS="-I/usr/local/include" EXTRA_CFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib -llz4 -lpthread -lsnappy -lz -lbz2 -lgflags" -j8 

now i use cmake to genarate Makefile,that works.
