### ISSUE TITLE
Proposal: Delete input SST files earlier in compaction

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#2710]
Currently, compaction input SST files are deleted after compaction completed. Ideally, input SST files can be deleted earlier:
1. We know a compaction may generates multiple output SST files, and there are many input SST files, so when an output SST file is finished, we can check which input SST's content is covered by the output SST files, such input SST files can be deleted as soon.
2. New request for such data can using newly generated SST files, thus there may be overlap between new(output) SSTs and old(input) SSTs, some data may have duplicated data both in old SST and new SST, these duplication are all the same(user key, seqnum, optype, value data are all the same), we can use any duplication.

Challenges: The SST file management will be much more complicated, especailly for a failing compaction
* Some output SST files have been generated, and the corresponding input SST files have been deleted, but the compaction failed later.

Benefits: Space amplification can be greatly reduced,  especially for universal compaction(which also reduce write amplification).

**Comment by yiwu-arbug** [comment]
cc @ajkr @siying

**Comment by rockeet** [comment]
@ajkr @siying @IslamAbdelRahman Is there any update?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
