### ISSUE TITLE
Problem compiling rocksdb (or problem excuting make comand)

### ISSUE THREAD

**Issue by cld378632668** [facebook/rocksdb#2715]
When excuting make comand in rocksdb directory, it reports:
```
[root@myheart-2 rocksdb]# make  or make all
Makefile:117: Warning: Compiling in debug mode. Don't use the resulting binary in production （搜索不到）
  GEN      util/build_version.cc
Makefile:117: Warning: Compiling in debug mode. Don't use the resulting binary in production
  GEN      util/build_version.cc
  CC       cache/clock_cache.o
  CC       cache/lru_cache.o
/tmp/ccZRJ2y7.s: Assembler messages:
/tmp/ccZRJ2y7.s:7334: Error: no such instruction: `shlx %ebx,%r14d,%ebx'
make: *** [cache/lru_cache.o] Error 1
```
I'm new to c/c++ on linux,  what should I do next?
Thanks!

**Comment by yiwu-arbug** [comment]
Can you try `make clean` once and then `make all`? If the error persist maybe there's something wrong with your gcc..

**Comment by cld378632668** [comment]
How to judge if there is wrong with gcc? 
The gcc can serve other programs well.

**Comment by yiwu-arbug** [comment]
I never see the issue before and we are not using assembly in our code explicitly. Can you Google search the error message and see if there are solutions?

**Comment by adamretter** [comment]
NB: This was cross-posted from Stackoverflow - https://stackoverflow.com/questions/45647631/make-compilation-error-of-open-source-project-on-linux-like-tmp-ccnvqmsf-s7

**Comment by ajkr** [comment]
a user mentioned to us today that running `PORTABLE=1 make ...` fixed a similar issue on CentOS.

**Comment by richardyc** [comment]
Also experienced a similar issue with `gcc (Ubuntu 6.5.0-2ubuntu1~14.04.1) 6.5.0 20181026`. Solved the issue using `PORTABLE=1 make ...`.
Detailed error message:
```
  CC       jl/db/convenience.o
  CC       jl/db/db_filesnapshot.o
  CC       jl/db/db_impl/db_impl.o
/tmp/ccHgKozh.s: Assembler messages:
/tmp/ccHgKozh.s:97950: Error: no such instruction: `kmovd %eax,%k1'
/tmp/ccHgKozh.s:97952: Error: no such instruction: `kshiftrd $31,%k1,%k0'
/tmp/ccHgKozh.s:97953: Error: no such instruction: `kmovd %k0,%edi'
make: *** [jl/db/db_impl/db_impl.o] Error 1
```
