### ISSUE TITLE
5.7.1 undefined symbols build failure on macOS

### ISSUE THREAD

**Issue by ilovezfs** [facebook/rocksdb#2729]
```
macOS: 10.12.6-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
```
```
  CC       tools/blob_dump.o
  CCLD     sst_dump
  CCLD     db_sanity_test
Undefined symbols for architecture x86_64:
  "typeinfo for rocksdb::Comparator", referenced from:
      typeinfo for rocksdb::SanityTestSpecialComparator::NewComparator in db_sanity_test.o
      typeinfo for rocksdb::test::(anonymous namespace)::Uint64ComparatorImpl in testutil.o
  "typeinfo for rocksdb::MergeOperator", referenced from:
      typeinfo for rocksdb::test::ChanglingMergeOperator in testutil.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [db_sanity_test] Error 1
```
Full log: https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6429/version=sierra/consoleText

**Comment by adamretter** [comment]
I can' reproduce the problem you are seeing on my Mac:

macOS Sierra (10.12.5)
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.6.0

**Comment by ilovezfs** [comment]
@adamretter it occurs on all 3 CI nodes (10.12, 10.11, and 10.10):

https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6429/
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6429/version=sierra/console
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6429/version=el_capitan/console
https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/6429/version=yosemite/console

and is a regression from 5.6.1.

**Comment by ilovezfs** [comment]
@adamretter also note it occurs during `make tools`.

**Comment by adamretter** [comment]
@ilovezfs Okay I just tried `make clean && make tools` on tag `v5.7.1` and all works fine here.

**Comment by yiwu-arbug** [comment]
Not reproducing on my side either. MacOS 10.12.6 + Apple Clang 8.1.0

**Comment by ilovezfs** [comment]
The install method is
```
  def install
    ENV.cxx11
    ENV["PORTABLE"] = "1" if build.bottle?

    # build regular rocksdb
    system "make", "clean"
    system "make", "static_lib"
    system "make", "shared_lib"
    system "make", "tools"
    system "make", "install", "INSTALL_PATH=#{prefix}"

    bin.install "sst_dump" => "rocksdb_sst_dump"
    bin.install "db_sanity_test" => "rocksdb_sanity_test"
    bin.install "db_stress" => "rocksdb_stress"
    bin.install "write_stress" => "rocksdb_write_stress"
    bin.install "ldb" => "rocksdb_ldb"
    bin.install "db_repl_stress" => "rocksdb_repl_stress"
    bin.install "rocksdb_dump"
    bin.install "rocksdb_undump"

    # build rocksdb_lite
    ENV.append_to_cflags "-DROCKSDB_LITE=1"
    ENV["LIBNAME"] = "librocksdb_lite"
    system "make", "clean"
    system "make", "static_lib"
    system "make", "shared_lib"
    system "make", "install", "INSTALL_PATH=#{prefix}"
  end
```
If I skip straight to `make tools` then that step works. But if `make static_lib` has been run, then the `make tools` step fails.

I hope that helps.

**Comment by adamretter** [comment]
@ilovezfs Okay I can reproduce with `make clean && make static_lib && make tools`:

```
aretter$ make static_lib

...

 CC       tools/ldb_tool.o
  CC       tools/sst_dump_tool.o
  CC       utilities/blob_db/blob_dump_tool.o
  AR       librocksdb.a
ar: creating archive librocksdb.a
/opt/local/bin/ranlib: file: librocksdb.a(db_impl_debug.o) has no symbols
/opt/local/bin/ranlib: file: librocksdb.a(rocks_lua_compaction_filter.o) has no symbols


aretter$ make tools
Makefile:117: Warning: Compiling in debug mode. Don't use the resulting binary in production
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
  GEN      util/build_version.cc
  CC       tools/sst_dump.o
  CCLD     sst_dump
  CC       tools/db_sanity_test.o
  CC       util/testutil.o
  CCLD     db_sanity_test
Undefined symbols for architecture x86_64:
  "typeinfo for rocksdb::Comparator", referenced from:
      typeinfo for rocksdb::SanityTestSpecialComparator::NewComparator in db_sanity_test.o
      typeinfo for rocksdb::test::(anonymous namespace)::Uint64ComparatorImpl in testutil.o
  "typeinfo for rocksdb::MergeOperator", referenced from:
      typeinfo for rocksdb::test::ChanglingMergeOperator in testutil.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [db_sanity_test] Error 1
```

@yiwu-arbug Should that work?

@ilovezfs I guess for a quick fix you could work around my injecting another `make clean` into your build script?

**Comment by ilovezfs** [comment]
@adamretter yup, and then I hit: https://github.com/facebook/rocksdb/issues/2731

**Comment by ilovezfs** [comment]
>@yiwu-arbug Should that work?

@adamretter @yiwu-arbug presumably it should, since it used to work before this latest release.

**Comment by yiwu-arbug** [comment]
The workaround is doing `DEBUG_LEVEL=0 make tools`. I'm still checking why `make tools` will build some of the test only code.

**Comment by yiwu-arbug** [comment]
Seems the inclusion of testutil.h is intentional. Please either `make clean` before `make tools`, or adding `DEBUG_LEVEL=0` for all your make commands. Let me know if it works for you.

**Comment by ilovezfs** [comment]
@yiwu-arbug hmm … this no longer seems to be a problem in 5.7.2.
