### ISSUE TITLE
PrepareForBulkload set num.levels to 2 causing exception

### ISSUE THREAD

**Issue by guozhangwang** [facebook/rocksdb#2734]
When we set the `options.prepareForBulkload` to true, it auto-set the `num.levels` to 2 for optimized bulk load. However, for cases when there is already existing sst files for this rocksDB (we have scenarios where we have a "stale" rocksdb file and we have a log of updates after that stale checkpoint, and we are trying to bulk load these changes before reusing the store) we can encounter the following issue:

```
org.rocksdb.RocksDBException: db has more levels than options.num_levels
at org.rocksdb.RocksDB.open(Native Method)
at org.rocksdb.RocksDB.open(RocksDB.java:231)
at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:199)
```

My question is: is bulk loading option designed for loading into an empty store only? If not, is there a way to go around this issue?

**Comment by guozhangwang** [comment]
cc @siying  @adamretter

**Comment by guozhangwang** [comment]
@yiwu-arbug Thanks for your suggestion. As for `Issue a full CompactRange() with target level`, I saw there is this API:

```
compactRange(final boolean reduce_level, final int target_level, final int target_path_id)
```

Just clarify I should call with parameter `compactRange(false, 1, 2)`, right?

Also you mentioned `Reopen db once your old options.num_levels`.. do you mean the following:

After the database object is opened with the old num_levels, say the default value, 7, call `compactRange(false, 1, 2)`, then close the database object, and then re-open with `options.prepareForBulkload` to start loading?

**Comment by guozhangwang** [comment]
@yiwu-arbug could you confirm my understanding? Thanks!

**Comment by yiwu-arbug** [comment]
This steps:
1. compactRange(true, 1, path_id); // path_id = 0 if you don't have multiple db_paths
2. Reopen with old num_levels (e.g. 7)
3. Reopen again with options.prepareForBulkload. 

Step 2 is to workaround max levels check during recovery.

**Comment by guozhangwang** [comment]
Thanks @yiwu-arbug !
