### ISSUE TITLE
Add SeekForPrev() to RocksJava

### ISSUE THREAD

**Issue by zawlazaw** [facebook/rocksdb#2742]
Currently, the iterator in RocksJava does only support `Seek()`, but not `SeekForPrev()`.
According to the [Rocks Wiki](https://github.com/facebook/rocksdb/wiki/SeekForPrev), the latter one was added to RocksDb in 4.13.
Although possible, it is clumsy and inefficient to manually simulate the behavior of `SeekForPrev(`) in user code.

Adding `seekToPrev` to the `RocksIteratorInterface` (and its implementations, as already existing for seek) is likely to be a small modification to the codebase (for someone who knows how...), but a large step for the Java API.

**Comment by yiwu-arbug** [comment]
You are welcome to send us a pull request. Our Java binding and C binding are largely rely on community contribution.

**Comment by adamretter** [comment]
@zawlazaw is this something you could contribute?

**Comment by zawlazaw** [comment]
Yes, I will give it a try. The coding part is no problem. Further, the compilation chain works now (generating the jars via 'make rocksdbjavastatic' and adding them to a test project). To me the more challenging problems are 1. available time, 2. being unfamiliar with the typical github-workflow (clone, branch, pull-requests) and 3. the CLA.
However, since the coding part of this issue is rather trivial, this is probably a nice contribution to start with - so I'll be back in a couple of days with the PR & CLA.

**Comment by zawlazaw** [comment]
Since the above PR was my first github-contribution ever, I just wanted to mention that it was fun and less hard than expected. Getting the CLA was trivial, and for the git-workflow I followed the [GitHub Standard Fork & Pull Request Workflow](https://gist.github.com/Chaser324/ce0505fbed06b947d962). 
While reading the code, I detected some other minor possible improvements (e.g., IMO `java/make run_test` should be executed by `make rocksdbjavastatic`). However, I am unsure about the "typical" way of collaboration: should I simply create additional PRs, or should I first discuss such ideas here as an issue, or on some mailing list, or directly by email to someone?

**Comment by adamretter** [comment]
I see that you have already sent a PR :-)

I am not sure I like the idea of make `rocksdbjavastatic` also executing `run_test`. I rather prefer to have small targets that can be combined when needed.

**Comment by zawlazaw** [comment]
(sorry for continuing OT): I agree, always running all tests is probably too much. My intention was to *force* test execution before *publishing* (similar to jenkins), so a better alternative might be to let `rocksdbjavastaticpublishcentral` additionally depend on `run_test`. However, this is really no longer related to `seekForPrev` :)
So back to meta-level: where to discuss such (and more advanced) ideas? In a separate issue? Or (if easy to provide) by sending a PR? Or on some mailing list?

**Comment by killme2008** [comment]
hello ,is it released?  @zawlazaw

**Comment by zawlazaw** [comment]
@killme2008, currently it is inside branch 5.9.fb, so let's hope for next version :)
