### ISSUE TITLE
delete_range and memtable prefix bloom filter bug

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#2743]
When enable memtable prefix bloom filter, at the same time use delete_range may see keys have deleted by delete_range.
For example, when I put keys (`a111`, `b111`, `c111`, let we use FixedLength(1) as prefix extractor) and then flush them into sst file. After that, I delete_range(a111, c111), when I db.Get(`b111`), it will return the value in sst file.
Because here did't consider delete_range when prefix_bloom is not null.
https://github.com/facebook/rocksdb/blob/master/db/memtable.cc#L653

**Comment by zhangjinpeng1987** [comment]
@ajkr

**Comment by siddontang** [comment]
Another serious problem when enable memtable prefix bloom filter.

After we ingest a SST, may k1 -> v1, k2 -> v2, ... kn-> vn, and delete k2. 
Sadly, seeking k2 can get k2.

**Comment by zhangjinpeng1987** [comment]
'''
Another serious problem when enable memtable prefix bloom filter.

After we ingest a SST, may k1 -> v1, k2 -> v2, ... kn-> vn, and delete k2.
Sadly, seeking k2 can get k2.
'''
@ajkr this [pr](https://github.com/facebook/rocksdb/pull/2745) don't fix the problem mentioned above.

**Comment by zhangjinpeng1987** [comment]
`test_prefix_bloom_delete_after_ingest` in this [file](https://github.com/pingcap/rust-rocksdb/pull/118/files#diff-fcd9700172ff6f22606f4ecd7ab25a88L617) reproduce the exact situation described above.

**Comment by siddontang** [comment]
The second problem is our fault, we don't use total seek mode :sob: 

Please ignore it.

**Comment by ajkr** [comment]
Agreed. I updated the wiki (https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes) slightly:

Before: "... we might return Valid()=false, or any key in the DB that is larger than the previous key"

After: "... we might return Valid()=false, or any key that is larger than the previous key"

In optimized prefix seek mode (default), we use a special memtable iterator that only sees keys in the seeked key's prefix. So the deletion outside that prefix isn't found.
