### ISSUE TITLE
Problem with comparator

### ISSUE THREAD

**Issue by jackbergus** [facebook/rocksdb#2762]
There are some problems while trying to extend the comparator

https://stackoverflow.com/questions/45603644/implementing-a-comparator-for-rocksdb

The problem seems to be with the header of the class: the destructor is defined in .h, but it is not exported in the .cpp, therefore any class trying to extend it, make the linking phase to fail.

I've just managed to solve the problem within my repository. I can create a pull request if needed.

**Comment by ajkr** [comment]
I tried this and got the same error as you. It was fixable by adding `-fno-rtti` to my comparator's build flags. Does that work for you? Alternatively, rebuilding rocksdb library with `USE_RTTI=1` worked for me.

cc @siying we may need to update some docs.

**Comment by ajkr** [comment]
I am curious, though, what is the code change you have that fixes it?

**Comment by jackbergus** [comment]
With the current version, it works. Beforehand, the descructor was declared only in the .h file, and missing on the cpp one, hence there were some problems in the linking phase, because not all the methods were compiled correctly.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
