### ISSUE TITLE
A performance related question

### ISSUE THREAD

**Issue by nastarangithub** [facebook/rocksdb#2770]
Hi,
I'm using RocksDB inside a Java application and the platform is Ubuntu.
There is only one instance of the DB in whole application.
The block of code I'm using to initialize the instance is as follows:

```java
RocksDB.loadLibrary();
BlockBasedTableConfig blockBasedTableConfig = new BlockBasedTableConfig()
                    .setFilter(new BloomFilter(10, false));
Options options = new Options()
                    .setCreateIfMissing(true)
                    .setLevelCompactionDynamicLevelBytes(true)
                    .setMaxBackgroundCompactions(4)
                    .setMaxBackgroundFlushes(4)
                    .setBytesPerSync(1048576)
                    .setTableFormatConfig(blockBasedTableConfig)
                    .setMergeOperator(new StringAppendOperator())
                    .setBottommostCompressionType(CompressionType.ZSTD_COMPRESSION);

RocksDB rocksDB = RocksDB.open(options,  "path-to-the-db");
```

The problem is that when the RocksDB size is more the 6.5G, the read operation is too slow.
I use `get` method to read a value by a key.
The keys are strings such as "cardno:6037997126565777".
Please notify me if there is a problem in the tuning or reading process.
Thank you

**Comment by houyujiangjun** [comment]
you should cut your database into small pieces. and set MmapRead true.

**Comment by ajkr** [comment]
Try increasing your block cache size. Our default is only 8MB which is pretty small for a 6.5GB database.

I don't understand why mmap reads or cutting into smaller databases would help.

**Comment by sagar0** [comment]
Closing this as its been too long. Please let us know if you are running into this issue and we can reopen it.
