### ISSUE TITLE
How to get Sequence Number for prepared writebatch when using 2PC?

### ISSUE THREAD

**Issue by mkosieradzki** [facebook/rocksdb#2775]
I am probably missing something or there is no such information stored.

I am implementing a distributed database based on a synchronously replicated RocksDB.

To synchronously replicate RocksDB I would like to use 2PC. My concept is fairly simple:
Prepare()
Replicate()
when got quorum acknowledgement
Commit()

Implementation-wise I am considering two alternative approaches:
### Custom LSN
Prepare()
reserve LSN
Replicate explicitly write batch transaction->GetWriteBatch()
when got quorum acknowledgement for this LSN
Commit()

### Use RocksDB sequence number
Prepare()
Get LSN for prepared write batch (HOW??)
Utilize GetUpdatesSince() for replication
when got quorum acknowledgement for this LSN
Commit()

I would definitely prefer the second approach - however I think it is currently impossible to get access to: WritePreparedTxn::prepare_seq_ IMO prepare_seq should be exposed on the Transaction class through some virtual getter.

Am I missing something?

UPDATE:
Also WriteCommittedTxn::PrepareInternal when doing WAL-only write does not even read the "seq_used". If I am not wrong we could access that seq after Prepare in both WriteCommittedTxn and WritePreparedTxn variants.

**Comment by maysamyabandeh** [comment]
The seq number has been exposed very recently only for the internal use cases. Exposing it via public API means more work to keep this seq number consistent. For example currently the seq number will be the same before and after recovery. However for soon-to-be-released WritePrepare transactions it takes a bit more work to keep the seq the same across WAL recovery.

However I am in favor of exposing this seq as the maintenance work to keep the seq consistent does not seem to be much.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
