### ISSUE TITLE
All travis-ci builds on osx are hanging

### ISSUE THREAD

**Issue by zawlazaw** [facebook/rocksdb#2778]
According to here: https://travis-ci.org/facebook/rocksdb/pull_requests, all travis-ci builds since ~16 hours ago are hanging. They all finish their linux build jobs, but cannot start any osx build job.
Since my build [#8923](https://travis-ci.org/facebook/rocksdb/builds/267341384) is the first in the chain of hanging builds, I wonder whether I made a mistake.
I found the following bug report on travis-ci: https://github.com/travis-ci/travis-ci/issues/5310
According to this, there is a bug in travis-ci when the PR used push with --force (as I did in order to re-base to master after local commits). The suggested workaround is to restart the build. However, I cannot find a way to restart my build.

Do you have another explanation for the current behavior?
Do you know how to restart the build?
How do you avoid to use a forced push when needed?

**Comment by zawlazaw** [comment]
Ok, finally my build (and later ones) finished with ~19 hours latency.
Looking at the list of open jobs today shows that it is typical to wait ca. 20 hours to get osx resources for testing, while the linux jobs start immediately.

**Comment by zawlazaw** [comment]
The problem does no longer exist, so I'll close this issue as "wasn't a real issue".

**Comment by sagar0** [comment]
Late, but ... 

We do occasionally see our travis builds having a considerable lag. 

> Do you know how to restart the build?

@zawlazaw You should see an option to restart a travis build once you create an account and log in to travis. 

> How do you avoid to use a forced push when needed?

push with --force option is the only way to rebase.
