### ISSUE TITLE
Put/Get std::string_view

### ISSUE THREAD

**Issue by thedrow** [facebook/rocksdb#2793]
C++17 has introduced std::string_view which are very similar to the Slices API RocksDB provides.
Boost also has an implementation of string_view.
Put & Get do not allow to set anything else other than a Slice.
It'd be very useful to have an API for Put/Get that works for more string-like types such as string_view.

**Comment by siying** [comment]
Is it for performance improvement or the convenience of code using RocksDB? I don't see how performance can be improved with it.

**Comment by thedrow** [comment]
This is mainly for convenience of code using RocksDB API. I expect C++17 codebases to use that type so RocksDB should accept it one way or another.
It may be easier to simply add a constructor overload for string_view in Slice so that they'll point to the same data.
Another approach is to solely use string_views but that will break the API.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
