### ISSUE TITLE
Does the rocksdb support the HDFS as the storage backend?

### ISSUE THREAD

**Issue by alexBaiJW** [facebook/rocksdb#2806]

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by maobaolong** [comment]
if this feature can be achieved, we can using rockdb on many fs as storage backend, such s3, oss, alluxio, cepth, because hdfs fs api has become a fs api stander, just like posix.
