### ISSUE TITLE
Corrupted MANIFEST

### ISSUE THREAD

**Issue by andresteves** [facebook/rocksdb#2808]
Hi,

I am unable to start the database instance. The error I came accross in the logs is 
`Detected unclean shutdown - /datadrive/mongodb/mongod.lock is not empty.
2017-08-29T15:56:24.504+0000 I -        [initandlisten] Invariant failure: s resulted in status BadValue: Corruption: no meta-nextfile entry in descriptor at src/mongo/db/storage/rocks/src/rocks_engine.cpp 201
`
Is there anyway to repair the MANIFEST file? I tried `make ` rocksdb to use repair class but I can't find it anywhere.

I can help by providing any information you need to solve this. Unfortunately no backup exists at the moment.

Thanks in advance

**Comment by ajkr** [comment]
Yes, our repair class is the way to go. I just updated the wiki (https://github.com/facebook/rocksdb/wiki/RocksDB-Repairer) with build/usage instructions. Let me know if you have more questions!

**Comment by andresteves** [comment]
Thank you very much @ajkr. I will come back in a couple of hours to report! Again thank you for the fast response

**Comment by andresteves** [comment]
Hi @ajkr I am trying to 'make -j64 ldb' but keeps on happening:

`virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
Makefile:1725: recipe for target 'cache/lru_cache.o' failed
make: *** [cache/lru_cache.o] Error 1
make: *** Waiting for unfinished jobs....
Makefile:1725: recipe for target 'db/builder.o' failed
make: *** [db/builder.o] Error 1`

I have 3.75GB of memory in my VM in Azure of which 3.4 is free...

Is it possible to build it locally and copy the ldb CLI into the azure vm?

Thanks,
Andre

**Comment by ajkr** [comment]
Can you try without the `-j64`? I should remove it from the wiki as that's just the parallelism setting that works best on my server, not for everyone.

**Comment by andresteves** [comment]
Thanks @ajkr . That worked and I was able to recover the MANIFEST but lost all my sst files... Is that normal? I am now unable to login to mongodb with my normal credentials.

**Comment by ajkr** [comment]
can you show us the warnings/errors in the repairer's output?

```
$ grep -E 'WARN|ERROR' ./repair-log.txt
```

**Comment by andresteves** [comment]
Well on my stupidity I ran the repair again to the same log file...
But I knew the error and so I search on repair.cc code and the text show was: 

```
column family unknown (probably due to legacy format); "
            "adding to default column family id 0
```
and
```
: inconsistent column family name '%s'; expected '%s' for column "
            "family id %" PRIu32 "."
```

Any of this helps?

Thanks

**Comment by ajkr** [comment]
Do you know what version of rocksdb generated the SST files? Version 4.8 onwards should store column family names in SST files. Earlier versions probably need the manifest to recover files in non-default column families.

BTW, if you want to rerun, you can just move the files out of the `lost/` directory and back into your db directory.

**Comment by andresteves** [comment]
Hi @ajkr 

The RocksDB version is 4.13.5.
I moved the files out of the `lost/` and started the mongodb service and that was when the files went missing.

Any idea why that happened? An update of mongodb (3.2 to 3.4) would cause that?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by suesunss** [comment]
@ajkr  @gfosco 

Is this repair tool working for multiple column families ?

When I use it for a corrupted DB, still encounter this issue:

```txt
You have to open all column families. Column families not opened: xxx
```
