### ISSUE TITLE
Attemipting to switch to VS 2017 CI build reveals compiler internal error

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#2816]
MSVC 2017 latest at this point in time compiler reports the following and aborts the build. This reproduces only when we build optimized debug build for CI. 

Removing -DOPTDBG=1 allows the build to proceed. However, the latter may significantly slower the tests which do not run against  a RAM drive on AppVeyor (point to explore).

The bug does not reproduce with VS 2015.

`c:\dev\external_sst_error\external_sst_file_test.cc(50) : fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\utc\src\p2\main.c', line 256)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information

Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX86\x64\cl.exe.  You will be prompted to send an error report to Microsoft later.`

I have reported a bug internally **488121**. 

Suggested workarounds include disabling a specific optimization on the affected class. However, there is not a guaranteed that this will not affect the generated code elsewhere.

I am postponing the compiler switch until I see a resolution.

**Comment by yuslepukhin** [comment]
Latest 2017 compilers works.

**Comment by yuslepukhin** [comment]
This now works

**Comment by yuslepukhin** [comment]
Apparently does not

**Comment by gfosco** [comment]
Worked around this VS bug in 3445 and we're officially upgraded to 2017 on Appveyor.
