### ISSUE TITLE
BlobDBTest.ReadWhileGC test fails because it attempts to destroy database more than once

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#2818]
WARNING: blob_db_test_je::BlobDBTest.ReadWhileGC State: Completed
WARNING: Note: Google Test filter = BlobDBTest.ReadWhileGC
WARNING: [==========] Running 1 test from 1 test case.
WARNING: [----------] Global test environment set-up.
WARNING: [----------] 1 test from BlobDBTest
WARNING: [ RUN      ] BlobDBTest.ReadWhileGC
WARNING: c:\dev\rocksdb\rocksdb\utilities\blob_db\blob_db_test.cc(62): error: DestroyBlobDB(dbname_, options, bdb_options)
WARNING: IO error: Failed to delete: f:\db\testrocksdb-6812/blob_db_test/blob_dir/000001.blob: Permission denied
WARNING: c:\dev\rocksdb\rocksdb\utilities\blob_db\blob_db_test.cc(62): error: DestroyBlobDB(dbname_, options, bdb_options)
WARNING: IO error: Failed to delete: f:\db\testrocksdb-6812/blob_db_test/blob_dir/000001.blob: Permission denied
WARNING: c:\dev\rocksdb\rocksdb\utilities\blob_db\blob_db_test.cc(62): error: DestroyBlobDB(dbname_, options, bdb_options)
WARNING: IO error: Failed to delete: f:\db\testrocksdb-6812/blob_db_test/blob_dir/000001.blob: Permission denied
WARNING: unknown file: error: SEH exception with code 0xc0000005 thrown in the test fixture's destructor.

**Comment by siying** [comment]
@yiwu-arbug  is it a bug?

**Comment by yiwu-arbug** [comment]
Maybe a true IO error. @yuslepukhin is it resolved?
