### ISSUE TITLE
BlobDb::Open leaks memory

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#2820]
After new the code returns 3 times w/o deleting the allocated DB. The ptr to the db is passed to the listeners before db is fully initialized and then become dangling ptrs if leaks are fixed.

https://github.com/facebook/rocksdb/blob/4a90cbf42970185ebd2d1c5aac253424ca443ccf/utilities/blob_db/blob_db.cc#L138

**Comment by yiwu-arbug** [comment]
Thanks for reporting. Will fix.

By the way, are you trying to use blob db?
