### ISSUE TITLE
Centos7 signal SIGSEGV with gcc7.1.0

### ISSUE THREAD

**Issue by qimj** [facebook/rocksdb#2822]
hi, all
I  compiled RocksDB5.7.3 with gcc 7.1.0 and run simple code like this:

```c++
#include <string>
#include <rocksdb/db.h>

using namespace std;
int main(){
    return 0;
}
```
and i got signal SIGSEGV here.

<img width="1383" alt="sig" src="https://user-images.githubusercontent.com/6648308/29963894-efea499c-8f3a-11e7-9a82-70d7c5fcf22b.png">

it seemed rocksdb::ColumnFamilyOptions::~ColumnFamilyOptions try to free some invalid address.

**Comment by siying** [comment]
The line number include/rocksdb/options.h:185 doesn't match the file in RocksDB 5.7.3. Can you check which release/commit you are using so that I can find the exact line it crashes?
