### ISSUE TITLE
ERROR INSTALL. make: *** [db/version_set.o] Error 1

### ISSUE THREAD

**Issue by Rafoula** [facebook/rocksdb#2828]
Hello, 
I have linux 12.04 and I want to install rocksdb. 
I Have gcc and g++ version : 4.7. 
And after I follow these: 

cd rocksdb
sudo make install

and I have this error : 
"db/version_set.cc: In member function ‘uint64_t rocksdb::VersionStorageInfo::EstimateLiveDataSize() const’:
db/version_set.cc:2040:18: error: ‘class std::map<rocksdb::InternalKey*, rocksdb::FileMetaData*, rocksdb::VersionStorageInfo::EstimateLiveDataSize() const::<lambda(rocksdb::InternalKey*, rocksdb::InternalKey*)> >’ has no member named ‘emplace_hint’
make: *** [db/version_set.o] Error 1
"
Can you help me?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
