### ISSUE TITLE
Can keys be expired with TTL on RocksJava?

### ISSUE THREAD

**Issue by andre-paris** [facebook/rocksdb#2832]
Found that I can open a db with TTL support using:
```java
TtlDB.open(DBOptions options, String db_path, List<ColumnFamilyDescriptor> columnFamilyDescriptors, List<ColumnFamilyHandle> columnFamilyHandles, List<Integer> ttlValues, boolean readOnly)
```
But not found a java implementation of `TtlCompactionFilter`.
I'm missing something?

Thanks

**Comment by adamretter** [comment]
Compaction Filters are not yet supported in the Java API. I started implementing support for it here: https://github.com/facebook/rocksdb/pull/1241 I will try and bring that up to date.

**Comment by sagar0** [comment]
@andre-paris Since creating a compaction filter is not yet supported, you can selectively expose `TtlCompactionFilter` in Java, similar to the way `RemoveEmptyValueCompactionFilter` and `CassandraCompactionFilter` are exposed. Please feel free to send a pull request.
