### ISSUE TITLE
overlapped files of delete range

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#2833]
Hi, we have updated to v5.7.3, but we still encounter data loss, and it may still cause by delete range.
Here is the MANIFEST file [manifest.txt](https://github.com/facebook/rocksdb/files/1275935/manifest.txt). Look for file 27630 in line 42.
@ajkr

**Comment by ajkr** [comment]
Do you have the LOG for generating file 27630? Also do you use any manual compactions on default column family?

**Comment by huachaohuang** [comment]
Sorry, the above case has been messed up, but we have just produced another case, here are the LOG and MANIFEST: [rocksdb.tar.gz](https://github.com/facebook/rocksdb/files/1276367/rocksdb.tar.gz)

**Comment by zhangjinpeng1987** [comment]
I find compaction `JOB 1012` didn't pick 72629 and 72636, but the first output of `JOB 1012` 80784 overlap with 72629 and 72636 by delete range mark.

**Comment by zhangjinpeng1987** [comment]
BTW, we didn't use any manual compaction on default column family.

**Comment by zhangjinpeng1987** [comment]
Sst files 72629, 72636, 72647, 72653 are associated with the same delete range mark, and 72647 is nobody's input but deleted wrongly:
```
2017/09/04-14:12:31.500479 7ff0027ff700 EVENT_LOG_v1 {"time_micros": 1504505551500477, "job": 4, "event": "table_file_deletion", "file_number": 72647}
```
So the contact between 72653 and 72636 has been broken. When `JOB 1012` pick 72653 and executing `ExpandInputsToCleanCut`, 72629 and 72636 will never be picked.

**Comment by zhangjinpeng1987** [comment]
sst 72647 is dropped by DeleteFilesInRange, so there is conflict between delete range and DeleteFilesInRange.

**Comment by ajkr** [comment]
We need to fix `DeleteFilesInRange` to preserve contact between files. Even without range deletions this behavior can cause old versions of a key to reappear (if a user key is split between files and only the file containing newest version is deleted), which is confusing.

**Comment by zhangjinpeng1987** [comment]
Another corner case between DeleteFilesInRange and DeleteRange,
L2   sst1[a, c), sst2[c, e) sst3[e, g)
L3   sst4[a, d), ss5[d, g)
Suppose sst2 contains a DeleteRange[c, d) mark, after call DeleteFilesInRange(b, f), sst2 will be dropped, so the content [c, d) in L3 will reappear.
@ajkr

**Comment by ajkr** [comment]
Oh, good point. We might need a more fundamental change to `DeleteFilesInRange`. We could:

- start from bottommost level and iterate upwards
- at each level:
  - pick the widest clean-cut set of files that fall entirely in the range.
  - reset the range to the min and max of the clean-cut set of files found above.

Then the files being deleted at level `i` are always in a narrower range than the files being deleted at level `j`, for `i < j`. So we shouldn't have the problem of previously covered data reappearing.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
