### ISSUE TITLE
Regarding Block Cache Setup for ReadOptions and WriteOptions

### ISSUE THREAD

**Issue by MahiZoho** [facebook/rocksdb#2834]
Hi,

I would like to setup block cache(2 GB) for ReadOptions(preferably) and WriteOptions. How could i do that?
I couldn't find any reference w.r.t

Please help me in setting it.

Thanks & Best Regards,
- Mahi

**Comment by ajkr** [comment]
https://github.com/facebook/rocksdb/wiki/Block-Cache
