### ISSUE TITLE
What is the best way to load huge data set Maintaining Atomicity

### ISSUE THREAD

**Issue by Hemanth-Eduru** [facebook/rocksdb#2835]
1.What is the best way to load huge data set ( in to already existing DB)  Maintaining Atomicity.
I tried to use the batch but ran into memory issues( Insufficient RAM).
One possible way is to create and Ingest SST files and another possible way is to create a backup of Db before loading and restore it to previous version if that loading fails (or partially loads).
Is there  any Better way to do so?

**Comment by ajkr** [comment]
`IngestExternalFile` with a list of files will allow you to load atomically into a live DB. I think it is the best way.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
