### ISSUE TITLE
Is there a way to delete files in a non-closed range?

### ISSUE THREAD

**Issue by BusyJay** [facebook/rocksdb#2837]
API `DeleteFilesInRange` will treat range as a closed range `[begin, end]`. But sometimes only files in range `[begin, end)` is meant to be deleted.

**Comment by siddontang** [comment]
@siying @ajkr 

Now for DeleteRange it uses `[being, end)`, maybe it is better to unify all ranges in operations to left closed and right open.

**Comment by ajkr** [comment]
Sounds good but we can't change the default behavior now for compatibility reasons. We could add a flag for excluding right endpoint and default it to false. Want to try implementing it?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
