### ISSUE TITLE
Why "<=" here

### ISSUE THREAD

**Issue by cooljiansir** [facebook/rocksdb#2846]
https://github.com/facebook/rocksdb/blob/79810e2d491895b5e4b9dab8fd6ad03ad1f2bb19/db/db_impl_write.cc#L865

`oldest_alive_log` should not be greater than any cf's `OldestLogToKeep()` definitely, why not use `==` instead of `<=` here, did i miss something?

**Comment by siying** [comment]
Is the question about whether the code has a bug, or whether the code can be made clearer to read?

**Comment by cooljiansir** [comment]
Not a bug. Just a little confusing, I think that `oldest_alive_log <= OldestLogToKeep()`, isn't it?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
