### ISSUE TITLE
Multi-threaded manual compaction?

### ISSUE THREAD

**Issue by gbitzes** [facebook/rocksdb#2847]
Hi,

After a bulk load, I'm calling CompactRange(nullptr, nullptr) to prepare the db for fast reads. However, by observing CPU usage on the target machine, and rocksdb's LOG file, I'm realizing that only one thread is used for compaction.

Is there some option for turning on multi-threaded manual compaction? I tried setting max_background_jobs to a high value, without any success.

Thanks

**Comment by siying** [comment]
Unfortunately, currently it's not supported in leveled compaction.It is supported in universal compaction, following max_subcompaction.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by iFA88** [comment]
Greetings, i have just the same question. I use 50+ column family which ones have 5-260 GB size, when i start manual compaction for all CF it will do just in single thread, therefore the `max_background_jobs` is 12, `max_subcompaction` is 1.
My `compact_range(column_family=cf)` call are blocked until the compaction is not done and in the LOG i got for every call: `Manual compaction waiting for all other scheduled background compactions to finish` 
RocksDB version: 6.8.1
