### ISSUE TITLE
How could i get the last flush timestamp?

### ISSUE THREAD

**Issue by corndolly** [facebook/rocksdb#2851]
Hi, experts:
      I disable WAL for my rocksdb,   so i want to know the timestamp last flush operation happened?  How could i get this information?  
Thanks!

**Comment by yiwu-arbug** [comment]
Manually, you can look at the LOG file and search for flush event.

Programmatically, you can call `DB:: GetPropertiesOfAllTables` and check `table_properties.creation_time`.

**Comment by corndolly** [comment]
Thanks for your comment.
