### ISSUE TITLE
Install rocksdb in Linux 12.04

### ISSUE THREAD

**Issue by Rafoula** [facebook/rocksdb#2870]
Hello, I have Linux 12.04 and I want to install rocksdb. 
Could you help me Someone? 
I must install first gflags and these libraries? Or I could install without these libraries.
Libraries:
zlib - a library for data compression.
bzip2 - a library for data compression.
lz4 - a library for extremely fast data compression.
snappy - a library for fast data compression.
zstandard - Fast real-time compression algorithm.
All our tools depend on:
gflags - a library that handles command line flags processing. You can compile rocksdb library even if you don't have gflags installed

**Comment by yiwu-arbug** [comment]
yes you can install without those libraries, as long as you don't need the compression support.

**Comment by siying** [comment]
As what @yiwu-arbug said, we don't require any of them for RocksDB to be built and use. However, we suggest you at least install one of the compression libraries. Usually the recommendation is the lightweight compression Snappy or LZ4. Otherwise, you cannot compress data in the database.

**Comment by Rafoula** [comment]
thank you @yiwu-arbug and @siying. 
I have downloaded Snappy. 
After,Firstly I downloaded rocksdb with this command:
                                      **$ git clone -b 4.9.fb https://github.com/facebook/rocksdb.git.**

Secondly I follow these commands: 
                                    **cd rocksdb 
                                    sudo make install**

But I have error like this:
  CC       db/version_set.o
db/version_set.cc: In member function ‘uint64_t rocksdb::VersionStorageInfo::EstimateLiveDataSize() const’:
db/version_set.cc:2040:18: error: ‘class std::map<rocksdb::InternalKey*, rocksdb::FileMetaData*, rocksdb::VersionStorageInfo::EstimateLiveDataSize() const::<lambda(rocksdb::InternalKey*, rocksdb::InternalKey*)> >’ has no member named ‘emplace_hint’
make: *** [db/version_set.o] Error 1

Could you help me , please because I don't know why I had this error.
Thank you.

**Comment by adamretter** [comment]
@Rafoula Have you read - https://github.com/facebook/rocksdb/blob/master/INSTALL.md

Do you have a suitable compiler, e.g. at least GCC 4.8?

**Comment by Rafoula** [comment]
@adamretter thank you! I had ggc 4.7 and this is the problem.
