### ISSUE TITLE
WriteBatch corruption when using manual_wal_flush

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#2871]
```
2017/09/11-10:31:22.437701 7f75c336ae40 [db/db_impl_open.cc:506] Recovering log #757 mode 2
2017/09/11-10:31:22.463380 7f75c336ae40 [WARN] [db/db_impl_open.cc:448] /data1/kv2/data/db/000757.log: dropping 422773 bytes; Corruption: unknown WriteBatch tag
2017/09/11-10:31:22.463405 7f75c336ae40 [db/db_impl_open.cc:726] Point in time recovered to log #757 seq #24603006
```

Here is the LOG file [LOG.old.1505097155505139.txt](https://github.com/facebook/rocksdb/files/1294603/LOG.old.1505097155505139.txt).

**Comment by zhangjinpeng1987** [comment]
@ajkr Any clue?

**Comment by yiwu-arbug** [comment]
It is hard to debug without the corrupted WAL (.log file). If you can provide the WAL file we can take a look. If you cannot you can debug by looking into the corrupted WAL file. The error says recovery encounter a invalid value type: https://github.com/facebook/rocksdb/blob/eb6425303eb2474009a1a3a4857d7e49ccd19820/db/write_batch.cc#L356

cc @maysamyabandeh

**Comment by maysamyabandeh** [comment]
The log says:
```
2017/09/11-10:31:19.313098 7f75c336ae40             Options.manual_wal_flush: 0
```
Are you sure the issue related to manual_wal_flush? Even if it was set, how can we be sure that is due to that specifically?

**Comment by javaforfun** [comment]
> Are you sure the issue related to manual_wal_flush?
That's because https://github.com/facebook/rocksdb/pull/2864

**Comment by huachaohuang** [comment]
Hi, the corrupted WAL was deleted after recovery, so we cannot provide it. We will try to reproduce the problem with absolute consistency mode.
We are not sure that this problem is due to `manual_wal_flush`, but since we only encounter this problem with `manual_wal_flush`, we think it may be a clue.

**Comment by javaforfun** [comment]
@yiwu-arbug @maysamyabandeh reproduced with wal_recovery_mode =  kAbsoluteConsistency
```
2017/09/19-16:52:04.499234 7f26464d7e40 [db/db_impl_open.cc:506] Recovering log #343 mode 1
2017/09/19-16:52:04.499371 7f26464d7e40 [WARN] [db/db_impl_open.cc:448] /data1/kv4/data/db/000343.log: dropping 319 bytes; Corruption: bad record length
2017/09/19-16:52:04.499399 7f26464d7e40 [WARN] [db/db_impl_open.cc:448] /data1/kv4/data/db/000343.log: dropping 32768 bytes; Corruption: checksum mismatch
2017/09/19-16:52:04.499430 7f26464d7e40 [WARN] [db/db_impl_open.cc:448] /data1/kv4/data/db/000343.log: dropping 32768 bytes; Corruption: bad record length
2017/09/19-16:52:04.499462 7f26464d7e40 [WARN] [db/db_impl_open.cc:448] /data1/kv4/data/db/000343.log: dropping 32768 bytes; Corruption: checksum mismatch
```
wal and log files: [data.tar.gz](https://github.com/facebook/rocksdb/files/1314146/data.tar.gz)

**Comment by maysamyabandeh** [comment]
@javaforfun can you tell more about how you reproduced it? Is it with killing the process?
If you are setting manual_wal_flush to true it means that WAL is buffered in application memory space and not flushed until i) you do that explicitly or ii) buffer is full. When is that you manually call FlushWA? This is in contrast to the previous behavior where the application memory buffer is flushed to the OS buffer right after writing each record. So depending on the way that you reproduced it, it is possible that a record is flushed only partially and hence has to be discarded during recovery.
