### ISSUE TITLE
Improve readahead in RocksDB

### ISSUE THREAD

**Issue by sagar0** [facebook/rocksdb#2874]
Readahead in RocksDB can be configured by setting `DBOptions.advise_random_on_open = false` and by providing a reasonable value to `ReadOptions.readahead_size` as mentioned here: https://github.com/facebook/rocksdb/wiki/Iterator#read-ahead . But RocksDB's read-ahead implementation incurs considerable overhead and is suitable only for a select few use-cases. RocksDB should optimize its read-ahead implementation, especially by making prefetch more lightweight in BlockBasedTableReader.

This could improve MyRocks performance too in comparison to other storage engines. See https://github.com/facebook/mysql-5.6/issues/705 .

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by sagar0** [comment]
First version of readahead is implemented in #3282 .

**Comment by sagar0** [comment]
Another improvement just landed, this time for Direct IO user range scans - #3884.

**Comment by sagar0** [comment]
Explicit user readahead (ReadOptions.readahead_size > 0) performance improvements : #5246.

**Comment by siying** [comment]
Although there are outstanding works needed to improve readahead, the issues mentioned here seem to be stale. Close it and track it in somewhere else.
