### ISSUE TITLE
block checksum mismatch

### ISSUE THREAD

**Issue by huangwei04** [facebook/rocksdb#2882]
The rocksdb got a error: "block checksum mismatch", when i test ceph performance.
 Can someone help me?
  
system:
  centos7
  
  file system: 
  bluefs
  
  rocksdb version: 
  commit e15382c09c87a65eaeca9bda233bab503f1e5772
  Author: Siying Dong <siying.d@fb.com>
  Date:   Thu Apr 27 08:12:28 2017

  log:
  000555.sst is lelve 1 
./sst_dump --file=000550.sst --verify_checksum --command=verify 
from [] to []
Process 000550.sst
Sst file format: block-based
000550.sst is corrupted: Corruption: block checksum mismatch: expected 561930444, got 781856447  in 000550.sst offset 164524 size 4165
  
 
2017-09-05 11:26:30.181778 7fd5bf317700  4 rocksdb: [/clove/vm/renhw/ceph/rpmbuild/BUILD/ceph-12.1.0.5/src/rocksdb/db/compaction_job.cc:1403] [default] [JOB 3] Compacting 4@0 + 1@1 files to L1, score 1.00
2017-09-05 11:26:30.181807 7fd5bf317700  4 rocksdb: [/clove/vm/renhw/ceph/rpmbuild/BUILD/ceph-12.1.0.5/src/rocksdb/db/compaction_job.cc:1407] [default] Compaction start summary: Base version 2 Base level 0, inputs: [563(1488KB) 561(8590KB) 555(507KB) 552(3874KB)], [550(55MB)]
2017-09-05 11:26:30.181827 7fd5bf317700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1504581990181813, "job": 3, "event": "compaction_started", "files_L0": [563, 561, 555, 552], "files_L1": [550], "score": 1, "input_data_size": 72834941}
2017-09-05 11:26:32.079310 7fd5bf317700  3 rocksdb: [/clove/vm/renhw/ceph/rpmbuild/BUILD/ceph-12.1.0.5/src/rocksdb/db/db_impl_compaction_flush.cc:1591] Compaction error: Corruption: block checksum mismatch
2017-09-05 11:26:32.079329 7fd5bf317700  4 rocksdb: (Original Log Time 2017/09/05-11:26:32.079244) [/clove/vm/renhw/ceph/rpmbuild/BUILD/ceph-12.1.0.5/src/rocksdb/db/compaction_job.cc:621] [default] compacted to: base level 1 max bytes base 268435456 files[4 1 0 0 0 0 0] max score 0.00, MB/sec: 38.4 rd, 32.3 wr, level 1, files in(4, 1) out(1) MB in(14.1, 55.3) out(58.4), read-write-amplify(9.1) write-amplify(4.1) Corruption: block checksum mismatch, records in: 434215, records dropped: 73730

2017-09-05 11:26:32.079336 7fd5bf317700  4 rocksdb: (Original Log Time 2017/09/05-11:26:32.079300) EVENT_LOG_v1 {"time_micros": 1504581992079285, "job": 3, "event": "compaction_finished", "compaction_time_micros": 1897387, "output_level": 1, "num_output_files": 1, "total_output_size": 61278587, "num_input_records": 419816, "num_output_records": 346086, "num_subcompactions": 1, "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 4, "lsm_state": [4, 1, 0, 0, 0, 0, 0]}
2017-09-05 11:26:32.079339 7fd5bf317700  2 rocksdb: [/clove/vm/renhw/ceph/rpmbuild/BUILD/ceph-12.1.0.5/src/rocksdb/db/db_impl_compaction_flush.cc:1275] Waiting after background compaction error: Corruption: block checksum mismatch, Accumulated background error counts: 1

**Comment by siying** [comment]
Is it a single occurrence, or it happens frequently? If it is a single occurrence, maybe it's real media or RAM hardware corruption.

**Comment by huangwei04** [comment]
I encountered this error three times on different machines.

**Comment by huangwei04** [comment]
I encountered this error three times on different machines. Every time it happens in Compacting:4@0 + 1@1 files to L1.  Is it a coincidence?

**Comment by siying** [comment]
@huangwei04 if you set options.paranoid_file_checks=true, will you catch something different error message?

**Comment by huangwei04** [comment]
@siying Ok, i' try. The error did not appear in  last  week.
 Is there some way to recover the rocksdb?

**Comment by huangwei04** [comment]
@siying Ok, i'll try. The error did not appear in last week.
Is there some way to recover the rocksdb?

**Comment by huangwei04** [comment]
@siying Ok, i'll try it. The error did not appear in last week.
Is there some way to recover the rocksdb?

**Comment by siying** [comment]
@huangwei04 you should be able to open the DB, scan the DB with read_options.verify_checksum=false, and copy all the data to another DB.

**Comment by huangwei04** [comment]
It happend again. I print out one of the sst files and found that the wrong data block  was continuous sometime.

LOG:

Footer Details:
--------------------------------------
  checksum: 1
  metaindex handle: 83CDB52153
  index handle: DBCDB521B49321
  footer version: 2
  table_magic_number: 9863518390377041911

Metaindex Details:
--------------------------------------
  Filter block handle: EC878020C7BEB501
  Properties block handle: B8C6B521C606

Table Properties:
--------------------------------------
  # data blocks: 16935
  # entries: 1130192
  raw key size: 24907107
  raw average key size: 22.037943
  raw value size: 45958829
  raw average value size: 40.664621
  data block size: 67109868
  index block size: 543161
  filter block size: 2973511
  (estimated) table size: 70626540
  filter policy name: rocksdb.BuiltinBloomFilter
  column family ID: 0
  column family name: default
  comparator name: leveldb.BytewiseComparator
  merge operator name: .T:int64_array.b:bitwise_xor
  property collectors names: []
  SST file compression algo: NoCompression
  creation time: 0



Data Block # 269 @ A09E3FA71E
--------------------------------------
Error reading the block - Skipped

Data Block # 270 @ CCBC3F941E
--------------------------------------
Error reading the block - Skipped

Data Block # 271 @ E5DA3F911E
--------------------------------------
Error reading the block - Skipped

Data Block # 272 @ FBF83F9D1E
--------------------------------------
Error reading the block - Skipped

Data Block # 273 @ 9D97408E1E
--------------------------------------
  HEX    4F007F8000000000000003BEC73CCE217262645F646174612E333833613736343363393836392E303030303030303030303031
32666539213DFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFF6F: 01017A010000F6E32A8080C00102000000010000005F2601000011082001000
004034800000000000000270000007262645F646174612E333833613736343363393836392E30303030303030303030303132666539FEFF
FFFFFFFFFFFF7DE33C730000000000030000000000000006031C0000000300000000000000FFFFFFFF0000000000000000FFFFFFFFFFFFF
FFF000000004756000000000000690A000000000000000000000000000002021500000008661703000000000089DC2A0000000000010000
000000300000000000E570BA59F796A41002021500000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000475600000000000000000000000000000024000000E570BA59247D3511FFFFFFFFFFFFFFFF000040000000000000
004000000000000000000007000000736E61707365742300000003021D00000000000000000000000100000000000000000000000000000
0000000000000000000008080800280808002000200130000000201008310831083080163844600832008FFF0
  ASCII  O : ^A ^A z ^A
  ------
@                                                                                                              
                                                                                             166031,3       4%
Error reading the block - Skipped

Data Block # 259 @ A5F03C961E
--------------------------------------
Error reading the block - Skipped

Data Block # 260 @ C08E3DA11E
--------------------------------------
Error reading the block - Skipped

Data Block # 261 @ E6AC3D9C1E
--------------------------------------
Error reading the block - Skipped

Data Block # 262 @ 87CB3D9D1E
--------------------------------------
Error reading the block - Skipped

Data Block # 263 @ A9E93D8D1E
--------------------------------------
Error reading the block - Skipped

Data Block # 264 @ BB873E8F1E
--------------------------------------
Error reading the block - Skipped

Data Block # 265 @ CFA53EA11E
--------------------------------------
Error reading the block - Skipped

Data Block Summary:
--------------------------------------
  # data blocks: 16935
  min data block size: 45
  max data block size: 4085
  avg data block size: 3957.791143

**Comment by huangwei04** [comment]
It happend again. I printed out one of the sst files and found that the wrong data block was continuous sometime.

LOG:

Footer Details:

checksum: 1
metaindex handle: 83CDB52153
index handle: DBCDB521B49321
footer version: 2
table_magic_number: 9863518390377041911

Metaindex Details:

Filter block handle: EC878020C7BEB501
Properties block handle: B8C6B521C606

Table Properties:

data blocks: 16935

entries: 1130192

raw key size: 24907107
raw average key size: 22.037943
raw value size: 45958829
raw average value size: 40.664621
data block size: 67109868
index block size: 543161
filter block size: 2973511
(estimated) table size: 70626540
filter policy name: rocksdb.BuiltinBloomFilter
column family ID: 0
column family name: default
comparator name: leveldb.BytewiseComparator
merge operator name: .T:int64_array.b:bitwise_xor
property collectors names: []
SST file compression algo: NoCompression
creation time: 0

Data Block # 269 @ A09E3FA71E

Error reading the block - Skipped

Data Block # 270 @ CCBC3F941E

Error reading the block - Skipped

Data Block # 271 @ E5DA3F911E

Error reading the block - Skipped

Data Block # 272 @ FBF83F9D1E

Error reading the block - Skipped

Data Block # 273 @ 9D97408E1E

HEX 4F007F8000000000000003BEC73CCE217262645F646174612E333833613736343363393836392E303030303030303030303031
32666539213DFFFFFFFFFFFFFFFEFFFFFFFFFFFFFFFF6F: 01017A010000F6E32A8080C00102000000010000005F2601000011082001000
004034800000000000000270000007262645F646174612E333833613736343363393836392E30303030303030303030303132666539FEFF
FFFFFFFFFFFF7DE33C730000000000030000000000000006031C0000000300000000000000FFFFFFFF0000000000000000FFFFFFFFFFFFF
FFF000000004756000000000000690A000000000000000000000000000002021500000008661703000000000089DC2A0000000000010000
000000300000000000E570BA59F796A41002021500000000000000000000000000000000000000000000000000000000000000000000000
0000000000000000000475600000000000000000000000000000024000000E570BA59247D3511FFFFFFFFFFFFFFFF000040000000000000
004000000000000000000007000000736E61707365742300000003021D00000000000000000000000100000000000000000000000000000
0000000000000000000008080800280808002000200130000000201008310831083080163844600832008FFF0
ASCII O : ^A ^A z ^A

@
166031,3 4%
Error reading the block - Skipped

Data Block # 259 @ A5F03C961E

Error reading the block - Skipped

Data Block # 260 @ C08E3DA11E

Error reading the block - Skipped

Data Block # 261 @ E6AC3D9C1E

Error reading the block - Skipped

Data Block # 262 @ 87CB3D9D1E

Error reading the block - Skipped

Data Block # 263 @ A9E93D8D1E

Error reading the block - Skipped

Data Block # 264 @ BB873E8F1E

Error reading the block - Skipped

Data Block # 265 @ CFA53EA11E

Error reading the block - Skipped

Data Block Summary:

data blocks: 16935

min data block size: 45
max data block size: 4085
avg data block size: 3957.791143

**Comment by siying** [comment]
Did you set you set options.paranoid_file_checks=true in your run?

Also, can you check whether in the corrupted pages, the data is repeated from some pages in the same file?

**Comment by huangwei04** [comment]
yes, I have set it.
003826.sst is damaged when i dump the sst files. I think that it was ok when be created, otherwise there wouldn't be this log.

rocksdb log:
2017-09-19 12:15:01.658384 7f18276a8700  4 rocksdb: [/home/zstor/ceph/rpmbuild/BUILD/ceph-12.2.0/src/rocksdb/db/compaction_job.cc:1116] [default] [JOB 605] Generated table #3826: 68110 keys, 68399955 bytes

2017-09-19 12:15:01.658411 7f18276a8700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1505794501658397, "cf_name": "default", "job": 605, "event": "table_file_creation", "file_number": 3826, "file_size": 68399955, "table_properties": {"data_size": 67110376, "index_size": 956637, "filter_size": 331956, "raw_key_size": 5699758, "raw_average_key_size": 83, "raw_value_size": 64599465, "raw_average_value_size": 948, "num_data_blocks": 11998, "num_entries": 68110, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}


sst_dump log:
/home/hw/db/160/osd12/db.slow]# ls
003826_dump.txt  003834.sst  004260.sst  004275.sst  004292.sst  004307.sst  004312.sst  004317.sst
003826.sst       003841.sst  004265.sst  004280.sst  004297.sst  004310.sst  004315.sst  004318.sst
003831.sst       004117.sst  004270.sst  004287.sst  004302.sst  004311.sst  004316.sst  004319.sst
[root@gitbuilder-ceph-rpm-centos7-amd64-basic /home/hw/db/160/osd12/db.slow]# /home/hw/db/sst_dump --file=. --verify_checksum --command=verify
from [] to []
Process ./003826.sst
Sst file format: block-based
./003826.sst is corrupted: Corruption: block checksum mismatch: expected 40499449, got 40480783  in ./003826.sst offset 651341 size 4016
Process ./003831.sst
Sst file format: block-based
The file is ok

**Comment by huangwei04** [comment]
yes, I have set it, but the Level 1 sst can be checked?

003826.sst is damaged when i dump the sst files. 

rocksdb log:
2017-09-19 12:15:01.658384 7f18276a8700  4 rocksdb: [/home/zstor/ceph/rpmbuild/BUILD/ceph-12.2.0/src/rocksdb/db/compaction_job.cc:1116] [default] [JOB 605] Generated table #3826: 68110 keys, 68399955 bytes

2017-09-19 12:15:01.658411 7f18276a8700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1505794501658397, "cf_name": "default", "job": 605, "event": "table_file_creation", "file_number": 3826, "file_size": 68399955, "table_properties": {"data_size": 67110376, "index_size": 956637, "filter_size": 331956, "raw_key_size": 5699758, "raw_average_key_size": 83, "raw_value_size": 64599465, "raw_average_value_size": 948, "num_data_blocks": 11998, "num_entries": 68110, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}


sst_dump log:
/home/hw/db/160/osd12/db.slow]# ls
003826_dump.txt  003834.sst  004260.sst  004275.sst  004292.sst  004307.sst  004312.sst  004317.sst
003826.sst       003841.sst  004265.sst  004280.sst  004297.sst  004310.sst  004315.sst  004318.sst
003831.sst       004117.sst  004270.sst  004287.sst  004302.sst  004311.sst  004316.sst  004319.sst
[root@gitbuilder-ceph-rpm-centos7-amd64-basic /home/hw/db/160/osd12/db.slow]# /home/hw/db/sst_dump --file=. --verify_checksum --command=verify
from [] to []
Process ./003826.sst
Sst file format: block-based
./003826.sst is corrupted: Corruption: block checksum mismatch: expected 40499449, got 40480783  in ./003826.sst offset 651341 size 4016
Process ./003831.sst
Sst file format: block-based
The file is ok

**Comment by huangwei04** [comment]
@siying  Yes, i have set it.
003826.sst is damaged when i dump the sst files. I think that it was ok when be created, otherwise there wouldn't be this log.

rocksdb log:
2017-09-19 12:15:01.658384 7f18276a8700  4 rocksdb: [/home/zstor/ceph/rpmbuild/BUILD/ceph-12.2.0/src/rocksdb/db/compaction_job.cc:1116] [default] [JOB 605] Generated table #3826: 68110 keys, 68399955 bytes

2017-09-19 12:15:01.658411 7f18276a8700  4 rocksdb: EVENT_LOG_v1 {"time_micros": 1505794501658397, "cf_name": "default", "job": 605, "event": "table_file_creation", "file_number": 3826, "file_size": 68399955, "table_properties": {"data_size": 67110376, "index_size": 956637, "filter_size": 331956, "raw_key_size": 5699758, "raw_average_key_size": 83, "raw_value_size": 64599465, "raw_average_value_size": 948, "num_data_blocks": 11998, "num_entries": 68110, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}


sst_dump log:
/home/hw/db/160/osd12/db.slow]# ls
003826_dump.txt  003834.sst  004260.sst  004275.sst  004292.sst  004307.sst  004312.sst  004317.sst
003826.sst       003841.sst  004265.sst  004280.sst  004297.sst  004310.sst  004315.sst  004318.sst
003831.sst       004117.sst  004270.sst  004287.sst  004302.sst  004311.sst  004316.sst  004319.sst
[root@gitbuilder-ceph-rpm-centos7-amd64-basic /home/hw/db/160/osd12/db.slow]# /home/hw/db/sst_dump --file=. --verify_checksum --command=verify
from [] to []
Process ./003826.sst
Sst file format: block-based
./003826.sst is corrupted: Corruption: block checksum mismatch: expected 40499449, got 40480783  in ./003826.sst offset 651341 size 4016
Process ./003831.sst
Sst file format: block-based
The file is ok

**Comment by huangwei04** [comment]
# This is a RocksDB option file.
#
# For detailed file format spec, please refer to the example file
# in examples/rocksdb_option_file_example.ini
#

[Version]
  rocksdb_version=5.4.0
  options_file_version=1.1

[DBOptions]
  avoid_flush_during_shutdown=false
  avoid_flush_during_recovery=false
  dump_malloc_stats=false
  info_log_level=DEBUG_LEVEL
  wal_recovery_mode=kTolerateCorruptedTailRecords
  stats_dump_period_sec=600
  bytes_per_sync=0
  WAL_ttl_seconds=0
  max_subcompactions=1
  WAL_size_limit_MB=0
  wal_dir=db.wal
  write_thread_max_yield_usec=100
  max_log_file_size=0
  manifest_preallocation_size=4194304
  log_file_time_to_roll=0
  max_total_wal_size=0
  keep_log_file_num=1000
  wal_bytes_per_sync=0
  db_write_buffer_size=0
  table_cache_numshardbits=6
  max_open_files=-1
  max_file_opening_threads=16
  enable_write_thread_adaptive_yield=true
  max_background_flushes=1
  base_background_compactions=1
  use_fsync=false
  use_adaptive_mutex=false
  random_access_max_buffer_size=1048576
  delete_obsolete_files_period_micros=21600000000
  writable_file_max_buffer_size=0
  compaction_readahead_size=2097152
  skip_log_error_on_recovery=false
  paranoid_checks=true
  is_fd_close_on_exec=true
  db_log_dir=
  enable_thread_tracking=false
  allow_concurrent_memtable_write=true
  error_if_exists=false
  create_missing_column_families=false
  write_thread_slow_yield_usec=3
  max_manifest_file_size=18446744073709551615
  create_if_missing=false
  fail_if_options_file_error=false
  allow_2pc=false
  access_hint_on_compaction_start=NORMAL
  use_direct_io_for_flush_and_compaction=false
  max_background_compactions=1
  use_direct_reads=false
  skip_stats_update_on_db_open=false
  allow_mmap_writes=false
  delayed_write_rate=16777216
  recycle_log_file_num=4
  new_table_reader_for_compaction_inputs=true
  allow_fallocate=true
  allow_mmap_reads=false
  advise_random_on_open=true
  

[CFOptions "default"]
  compaction_pri=kByCompensatedSize
  compaction_filter_factory=nullptr
  memtable_factory=SkipListFactory
  bottommost_compression=kDisableCompressionOption
  compression=kNoCompression
  max_sequential_skip_in_iterations=8
  max_bytes_for_level_multiplier_additional=1:1:1:1:1:1:1
  compression_per_level=
  max_bytes_for_level_multiplier=10.000000
  max_bytes_for_level_base=268435456
  table_factory=BlockBasedTable
  max_successive_merges=0
  arena_block_size=33554432
  merge_operator=.T:int64_array.b:bitwise_xor
  target_file_size_multiplier=1
  num_levels=7
  min_write_buffer_number_to_merge=1
  prefix_extractor=nullptr
  bloom_locality=0
  max_write_buffer_number=4
  level0_stop_writes_trigger=36
  level0_slowdown_writes_trigger=20
  level0_file_num_compaction_trigger=4
  write_buffer_size=268435456
  memtable_huge_page_size=0
  max_compaction_bytes=1677721600
  hard_pending_compaction_bytes_limit=274877906944
  target_file_size_base=67108864
  soft_pending_compaction_bytes_limit=68719476736
  comparator=leveldb.BytewiseComparator
  memtable_insert_with_hint_prefix_extractor=nullptr
  force_consistency_checks=false
  max_write_buffer_number_to_maintain=0
  paranoid_file_checks=true
  optimize_filters_for_hits=false
  level_compaction_dynamic_level_bytes=false
  purge_redundant_kvs_while_flush=true
  inplace_update_support=false
  compaction_style=kCompactionStyleLevel
  compaction_filter=nullptr
  disable_auto_compactions=false
  inplace_update_num_locks=10000
  memtable_prefix_bloom_size_ratio=0.000000
  report_bg_io_stats=false
  
[TableOptions/BlockBasedTable "default"]
  read_amp_bytes_per_bit=8589934592
  format_version=2
  whole_key_filtering=true
  filter_policy=rocksdb.BuiltinBloomFilter
  verify_compression=false
  block_size_deviation=10
  block_size=4096
  partition_filters=false
  checksum=kCRC32c
  hash_index_allow_collision=true
  index_block_restart_interval=1
  block_restart_interval=16
  no_block_cache=false
  pin_l0_filter_and_index_blocks_in_cache=true
  cache_index_and_filter_blocks_with_high_priority=true
  metadata_block_size=4096
  cache_index_and_filter_blocks=true
  index_type=kBinarySearch
  flush_block_policy_factory=FlushBlockBySizePolicyFactory

**Comment by siying** [comment]
Just to verify, if you read using direct I/O, will it be corrupted too?

By the way, I don't think we ever released 5.4.0. There was a bug we fixed and backported to 5.4.6, with which we may ignore fsync() error code in flush: https://github.com/facebook/rocksdb/commit/2955407c3ab7e42ff71aa5fb7b5adf3d77ff53ab . However, you are seeing this in compaction output, so this is not the bug.

With options.paranoid_file_checks=true, we read all the data from the file after generating an SST file, no matter which level it is. And I reopening a file and modifying content in RocksDB is really rare. So more likely, either there is a hardware error happening somewhere, or somehow OS failed to flush dirty page to the drive, and somehow either error code is not returned to fsync(), or RocksDB ignores it somewhere.

**Comment by huangwei04** [comment]
@siying 
how does rocksdb calculate the remaining size  of path dynamically in function GetPathId ?
funtion: LevelCompactionBuilder::GetPathId 
uint64_t current_path_size = ioptions.db_paths[0].target_size;

**Comment by huangwei04** [comment]
@siying hi! There are two dir:db and db.slow to place sst files. db is on  ssd, db.slow is on hdd.  All the wrong sst files were on db.slow. I want to know that hwo rocksdb choose the dir when a sst be created.

**Comment by siying** [comment]
@huangwei04 which level belongs to which DB Path is never recalculated.

**Comment by huangwei04** [comment]
@siying  Thank you very much.  It would be something wrong whith the hdd disk.

**Comment by kapitan-k** [comment]
@huangwei04 FYI got "block checksum mismatch" two times. The first time it happened sporadically and it turned out to be a hdd failure. The second time I got it always at the same db size, at the same compaction and memtest revealed some errors so I had to change one memstick.

**Comment by geekgaoxiang** [comment]
we had the same problem ,and it happened in the same db

**Comment by ytrezq** [comment]
@siying Hello, can you help please, I m also having a checksum mismatch issue on that block based sst file https://doc-00-48-docs.googleusercontent.com/docs/securesc/0d5bieic93mql3dfqv1u17h46tjkfbrt/tfqk8n8tmk2odtt33p0gp06m9j3prvfe/1613165925000/03058620958359194349/03058620958359194349/1gstMO4z6OWGm5pYjL5j-BhdkXf3_Wbyq?e=download&authuser=0.

The data it contains is public and available through many apis for free but not as a database (which means the file needs to be rebuild by hand or the invalid cell erased from the manifest).
