### ISSUE TITLE
Iterator does NOT seems to be using the Block Cache

### ISSUE THREAD

**Issue by Hemanth-Eduru** [facebook/rocksdb#2883]
I found that Iterator Next ( **rocksdb_iter_next()** )  does not seems to utilise the block cache.
This is the way I tested

1.  Create a DB and load with Sequential Data.
2.   Close the DB and  reopen the DB. (After configuring  Block Cache to 1 GB)
3.   Create an iterator and seek it to first .(using **rocksdb_create_iterator()**)
4.   Iterate through whole range of keys using the iterator.(using **rocksdb_create_iterator() and rocksdb_iter_next()** )

At the end I printed statistics (using **rocksdb_options_statistics_get_string()**) 
I found **rocksdb.block.cache.hit COUNT** as Zero.  Below is statistics Output (truncated )
```
rocksdb.block.cache.miss COUNT : 555558
rocksdb.block.cache.hit COUNT : 0
rocksdb.block.cache.add COUNT : 555558
rocksdb.block.cache.add.failures COUNT : 0
rocksdb.block.cache.index.miss COUNT : 0
rocksdb.block.cache.index.hit COUNT : 0
rocksdb.block.cache.index.add COUNT : 0
rocksdb.block.cache.index.bytes.insert COUNT : 0
rocksdb.block.cache.index.bytes.evict COUNT : 0
rocksdb.block.cache.filter.miss COUNT : 0
rocksdb.block.cache.filter.hit COUNT : 0
rocksdb.block.cache.filter.add COUNT : 0
rocksdb.block.cache.filter.bytes.insert COUNT : 0
rocksdb.block.cache.filter.bytes.evict COUNT : 0
rocksdb.block.cache.data.miss COUNT : 555558
rocksdb.block.cache.data.hit COUNT : 0
rocksdb.block.cache.data.add COUNT : 555558
rocksdb.block.cache.data.bytes.insert COUNT : 2262232960
rocksdb.block.cache.bytes.read COUNT : 0
rocksdb.block.cache.bytes.write COUNT : 2262232960
rocksdb.bloom.filter.useful COUNT : 0
rocksdb.persistent.cache.hit COUNT : 0
rocksdb.persistent.cache.miss COUNT : 0
rocksdb.sim.block.cache.hit COUNT : 0
rocksdb.sim.block.cache.miss COUNT : 0
rocksdb.memtable.hit COUNT : 0
rocksdb.memtable.miss COUNT : 0
rocksdb.l0.hit COUNT : 0
rocksdb.l1.hit COUNT : 0
rocksdb.l2andup.hit COUNT : 0
```

I repeated the Same test using Get () and **provided keys in sequential order** there I have seen Non Zero 
**rocksdb.block.cache.hit COUNT** Below is statistics Output (truncated)

```
rocksdb.block.cache.miss COUNT : 555558
rocksdb.block.cache.hit COUNT : 39444446
rocksdb.block.cache.add COUNT : 555558
rocksdb.block.cache.add.failures COUNT : 0
rocksdb.block.cache.index.miss COUNT : 0
rocksdb.block.cache.index.hit COUNT : 0
rocksdb.block.cache.index.add COUNT : 0
rocksdb.block.cache.index.bytes.insert COUNT : 0
rocksdb.block.cache.index.bytes.evict COUNT : 0
rocksdb.block.cache.filter.miss COUNT : 0
rocksdb.block.cache.filter.hit COUNT : 0
rocksdb.block.cache.filter.add COUNT : 0
rocksdb.block.cache.filter.bytes.insert COUNT : 0
rocksdb.block.cache.filter.bytes.evict COUNT : 0
rocksdb.block.cache.data.miss COUNT : 555558
rocksdb.block.cache.data.hit COUNT : 39444446
rocksdb.block.cache.data.add COUNT : 555558
rocksdb.block.cache.data.bytes.insert COUNT : 2262230384
rocksdb.block.cache.bytes.read COUNT : 160618069344
rocksdb.block.cache.bytes.write COUNT : 2262230384
rocksdb.bloom.filter.useful COUNT : 0
rocksdb.persistent.cache.hit COUNT : 0
rocksdb.persistent.cache.miss COUNT : 0
rocksdb.sim.block.cache.hit COUNT : 0
rocksdb.sim.block.cache.miss COUNT : 0
rocksdb.memtable.hit COUNT : 0
rocksdb.memtable.miss COUNT : 40000000
rocksdb.l0.hit COUNT : 12138119
rocksdb.l1.hit COUNT : 13930874
rocksdb.l2andup.hit COUNT : 13931007
```

Is this expected behaviour ? I guess if iterator Next uses Block cache   Iterator may be further speed up , Am I right ?

**Comment by ajkr** [comment]
Seems expected, can you iterate over the whole DB twice and check the stats? First time block is used should be a cache miss; subsequent times will be cache hit.

**Comment by Hemanth-Eduru** [comment]
I Will repeat the test by iterating twice and will get back.
And isn't it logical that ( even for the first time ) if iterator next element in the cache (beacuse of sequential loading of keys) it may be fetched directly from cache?

**Comment by Hemanth-Eduru** [comment]
I repeated the test by iterating the whole range twice now I can see the Cache HIT being Non Zero.

**Comment by ajkr** [comment]
The iterator references the data block while it's in use. It only needs to get the block from block cache for the first key accessed in the block. Then subsequent accesses to keys in the same data block aren't expected to count as a hit or miss.

**Comment by Hemanth-Eduru** [comment]
> Then subsequent accesses to keys in the same data block aren't expected to count as a hit or miss.

It seems I miss interpreted the cache Hit and miss .
Closing the issue as it got resolved.
