### ISSUE TITLE
Can you set a prefix extractor after creating a database?

### ISSUE THREAD

**Issue by JelteF** [facebook/rocksdb#2891]
The wiki FAQ states the following:
>Q: Can I change the prefix extractor?
>
> A: No. Once you've specified a prefix extractor, you cannot change it. However, you can disable it by specifying a null value.

This makes it unclear to me if I can enable a prefix extractor on an already existing database after creating it. Does creating it count as changing it?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.

**Comment by JelteF** [comment]
I'm still wondering what the answer to this is.

**Comment by yiwu-arbug** [comment]
You can create prefix extractor to an existing DB if you never set a prefix extractor before. cc @siying correct me if I'm wrong.
