### ISSUE TITLE
question

### ISSUE THREAD

**Issue by publicocean0** [facebook/rocksdb#2896]
hi i m exalutating to use rocksdb, it seams very good code. I saw there is also transaction.
It is possible also to use two-phase transaction?

**Comment by siying** [comment]
2-phase commit is used in MyRocks for syncing up with MySQL binlogs, so it is a production-ready feature. If it can satisfy your specific requirement, you are welcome to use it.

**Comment by publicocean0** [comment]
thanks for the support
