### ISSUE TITLE
ForwardIterator::RenewIterators questions

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#2902]
Should this code make use of svnew instead of sv_ https://github.com/facebook/rocksdb/blob/master/db/forward_iterator.cc#L629 ?

**Comment by adsharma** [comment]
I don't work on rocksdb these days. Could you please reassign to someone on
the team?

**Comment by siying** [comment]
@al13n321 is the only person familiar with ForwardIterator now. I'm not sure he has time to kindly answer the question.

**Comment by maysamyabandeh** [comment]
@ajkr  can you please chime in? 
```
625   if (!read_options_.ignore_range_deletions) {
626     std::unique_ptr<InternalIterator> range_del_iter(
627         svnew->mem->NewRangeTombstoneIterator(read_options_));
628     range_del_agg.AddTombstones(std::move(range_del_iter));
629     sv_->imm->AddRangeTombstoneIterators(read_options_, &arena_,
630                                          &range_del_agg);
631   }
```

**Comment by ajkr** [comment]
Yes that looks more correct, thanks.
