### ISSUE TITLE
Makefile:1296 recipe for target 'cleanable_test' failed

### ISSUE THREAD

**Issue by MShah890** [facebook/rocksdb#2906]
I am using UBUNTU 16.04 and I am trying to install rocksdb. I have successfully installed all dependencies.

I have moved to `rocksdb-master` directory and have run the `make` command and I get the following.

![image](https://user-images.githubusercontent.com/9371688/30601891-e0ea9c2c-9d17-11e7-9e89-9d2e5a0b92c7.png)

I am new to docker and rocksdb so please help out.

**Comment by maysamyabandeh** [comment]
Feel free to ask help in the user group: https://www.facebook.com/groups/rocksdb.dev
Issue page is to be used to report bugs.
