### ISSUE TITLE
How to use NewCompactOnDeletionCollectorFactory?

### ISSUE THREAD

**Issue by mperham** [facebook/rocksdb#2909]
Sorry if I'm missing something obvious but the wiki isn't very clear here:

https://github.com/facebook/rocksdb/wiki/Implement-Queue-Service-Using-RocksDB#reclaiming-space-of-deleted-items-faster

I don't know what that paragraph means -- could it be a little more explicit: how do I configure my DB to use this thing?

**Comment by maysamyabandeh** [comment]
The code shows it is of type TablePropertiesCollectorFactory, which can be set in ImmutableCFOptions::table_properties_collector_factories.

**Comment by mperham** [comment]
@maysamyabandeh Thank you for your advice, I appreciate your time here.  I don't know C++ and am using the tecbot/gorocksdb bindings.  None of that appears to be in the Go binding.  Any chance you can show the actual C++ code necessary and I can adapt to the Go bindings?

**Comment by maysamyabandeh** [comment]
Here is an example of how to assign this config: https://github.com/facebook/rocksdb/blob/master/db/table_properties_collector_test.cc#L385
About golang, you will have better luck asking in user group: https://www.facebook.com/groups/rocksdb.dev
