### ISSUE TITLE
Is the wiki about MANIFEST up to date?

### ISSUE THREAD

**Issue by Wbrta** [facebook/rocksdb#2911]
Recently I read code about `version_set.h/version_set.cc` but I doubt that `FileMetaData` do not contain the code about path or path size which appeared in wiki about MANIFEST. And the wiki about MANIFEST was updated in 04/06/2016.
So I want to know whether the wiki about MANIFEST is up to date.
By the way, I think the explanation about MANIFEST is not clear, especially the **Version Edit Layout**
Thanks.

**Comment by ajkr** [comment]
Is this the wiki you're talking about (https://github.com/facebook/rocksdb/wiki/MANIFEST)? I didn't find any mention of `FileMetaData`.

**Comment by Wbrta** [comment]
@ajkr Yes. `FileMetaData` is a struct in `version_edit.h` and class `VersionEdit` use it by `std::vector<std::pair<int, FileMetaData>> new_files_;` And `new_file` refers to `New File edit record` in wiki about MANIFEST.

**Comment by ajkr** [comment]
File number should be enough to reconstruct the path.

**Comment by ajkr** [comment]
You can use `ldb manifest_dump --verbose ...` to see the `VersionEdit`s in your manifest and correlate them to files in your directory. E.g., my manifest has

```
VersionEdit {
  LogNumber: 18
  PrevLogNumber: 0
  NextFileNumber: 20
  LastSeq: 4
  AddFile: 0 19 938 'bar' seq:3, type:1 .. 'foo' seq:4, type:1
  ColumnFamily: 1
}
```

which corresponds to file 000019.sst.
