### ISSUE TITLE
question about partition columnfamilies

### ISSUE THREAD

**Issue by publicocean0** [facebook/rocksdb#2912]
hi , i have a question about how colulumn families save data in the storage. 
Is there a way for saving in different folders the different column families?
In the case the answer is negative , about your experience, has a  sense to create different instance of dbrocks in a single machine? this could create problems(for example, too much memory used  in a single normal machine)?

**Comment by ajkr** [comment]
One common approach is run multiple rocksdb instances in the same process. Resource limits can be shared by opening the DBs with the same objects in `rate_limiter`, `env`, `write_buffer_manager`, etc.

**Comment by ajkr** [comment]
Also, from our FAQ (https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ):

Q: What's the difference between storing data in multiple column family and in multiple rocksdb database?

A: The main differences will be backup, atomic writes and performance of writes. The advantage of using multiple databases: database is the unit of backup or checkpoint. It's easier to copy a database to another host than a column family. Advantages of using multiple column families: (1) write batches are atomic across multiple column families on one database. You can't achieve this using multiple RocksDB databases. (2) If you issue sync writes to WAL, too many databases may hurt the performance.

**Comment by publicocean0** [comment]
thanks, all clear and it is  what i expected.

**Comment by publicocean0** [comment]
Sorry, I m trying to use rocksdb with java. I have a problem with transactions. It seams there is a conflict in a makefile .

**Comment by siying** [comment]
CC @sagar0

**Comment by sagar0** [comment]
@publicocean0  What conflict in makefile are you referring to? Could you please elaborate?

**Comment by publicocean0** [comment]
I d like to use rocksdb in my new java project with transactions. I tried to apply patch as described  in https://github.com/adamretter/rocksdb/tree/java-transactions/java but it seams there some conflicts like those ones
`java/rocksjni/backupenginejni.cc:12:46: fatal error: include/org_rocksdb_BackupEngine.h: File o directory non esistente
 #include "include/org_rocksdb_BackupEngine.h"
                                              ^
compilation terminated.
java/rocksjni/backupablejni.cc:16:53: fatal error: include/org_rocksdb_BackupableDBOptions.h: File o directory non esistente
 #include "include/org_rocksdb_BackupableDBOptions.h"
                                                     ^
compilation terminated.
java/rocksjni/checkpoint.cc:14:44: fatal error: include/org_rocksdb_Checkpoint.h: File o directory non esistente
 #include "include/org_rocksdb_Checkpoint.h"
                                            ^
` 
Do you think this integration will be aligned in future? it is in your plan ?

**Comment by sagar0** [comment]
It seems like you are referring to PR #1298 . We can accept it if @adamretter resurrects that PR.

**Comment by publicocean0** [comment]
ah , uhmmm it seams blocked for almost a year. The probability he resurrects that PR seams very low.

**Comment by publicocean0** [comment]
but hearders in format org_rocksdb_.... how are created? 
```
#include "include/org_rocksdb_HashSkipListMemTableConfig.h"
#include "include/org_rocksdb_HashLinkedListMemTableConfig.h"
#include "include/org_rocksdb_VectorMemTableConfig.h"
#include "include/org_rocksdb_SkipListMemTableConfig.h"
```
it seams you created on the fly this files and you put it in the folder "include".

**Comment by publicocean0** [comment]
I cloned https://github.com/adamretter/rocksdb/tree/java-transactions/java and i fixed problems , now it can compile. I could create a fork and submit it to you. Anyway the version it is 5.0.0 not 5.8.0.
Eventually you can help to upgrade it to the current version?

**Comment by sagar0** [comment]
@adamretter -- what's the plan and what do you think of @publicocean0's proposal?
I'll let @adamretter chime in here, so that he can get credit for the initial implementation of Transactions in RocksJava (in PR #1298). 

@publicocean0 -- Re: 5.0 vs 5.8, if at all we decide to proceed forward, you need to create a new pull request or rebase on the latest master so that the code can be merged.

**Comment by publicocean0** [comment]
ok , i will tell you about it . Before i studied a bit how it works better.

**Comment by publicocean0** [comment]
i gave a look in this days about JNI transactions . I tried to merge the current release with adamretter source. I made also some fixes. Now there compilation is blocking in the last compilation phase. All is compiling except the portal.h. it might be refactored with last changes in rockdsb.

**Comment by adamretter** [comment]
I can rebased it when I am back in the office tomorrow

**Comment by publicocean0** [comment]
cool ! Eventually i could a patch about my merge , so you can concentrate just on portal.h.

**Comment by publicocean0** [comment]
hi no news about the commit for JNI transactions?

**Comment by publicocean0** [comment]
i need a little help about 
`txn_db->GetColumnFamilyHandleUnlocked` : this class has no more this method. How can i retrieve the columnfamily handle by id? 
 `db->GetColumnFamilyHandleUnlocked`: DB class has no more this api but i found it in DBImpl. I supposed casting directly to DBImpl instead DB it might work.
