### ISSUE TITLE
L0->L0 compaction test

### ISSUE THREAD

**Issue by hshs1103** [facebook/rocksdb#2914]
Hi, dear all

I want to see how often L0->L0 compaction occurs. So, I fixed compaction_picker.cc code. 
Fixed code is same as below.

--------------------------------------------------------------------------------------

bool LevelCompactionBuilder::PickIntraL0Compaction() {
  start_level_inputs_.clear();
  const std::vector<FileMetaData*>& level_files =
      vstorage_->LevelFiles(0 /* level */);
  if (level_files.size() <
          static_cast<size_t>(
              mutable_cf_options_.level0_file_num_compaction_trigger + 2) ||
      level_files[0]->being_compacted) {
    // If L0 isn't accumulating much files beyond the regular trigger, don't
    // resort to L0->L0 compaction yet.
    return false;
  }

    //add here

   level_zero_cnt++;
   std::lock_guard<std::mutex> guard(L0_print_mutex);
   out_file.open("/home/hshs1103/num_of_L0_compaction.txt", std::ios::app);
   out_file << "L0->L0 count:  " << level_zero_cnt << "\n";
   out_file.close();

  return FindIntraL0Compaction(level_files, kMinFilesForIntraL0Compaction,
                               port::kMaxUint64, &start_level_inputs_);
}
}  

-----------------------------------------------------------------------------------

i was experimenting with db_bench to check the frequency of L0->L0 compaction. 
but it didn't work. 
So, I have some questions.

1.Where do I modify the code to know how many times L0-> L0 compaction occur?
2. Is it possible to test L0 compaction in db_bench? If so, what should I do?
3. Is there another benchmark to check for L0-> L0 Compaction instead of db_bench? If you have, please let me know how to do it !

**Comment by maysamyabandeh** [comment]
You can print such stats by running "stats" benchmark at the end. "Comp(cnt)" is the number of compactions for each level.
```
$ ./db_bench --benchmarks="readwhilewriting,stats" --duration 1 | grep "Compaction Stats" -C4
RocksDB:    version 5.8
Date:       Thu Sep 21 16:29:09 2017
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
 Sum      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
```

**Comment by hshs1103** [comment]
Thanks @maysamyabandeh.

But I want to know how many times L0->L0 Compaction was occured.

![image](https://user-images.githubusercontent.com/20452176/30728118-b7de3d18-9f90-11e7-873f-2d43cac5c648.png)

In this picture, L0 Comp(cnt) means that number of L0->L1 compactions. isn't it right?

**Comment by ajkr** [comment]
@hshs1103 - the "L0" line represents files that were output to L0. Unfortunately it combines stats for files generated by flush and files generated by L0->L0 compaction.

One way to check if L0->L0 happened is by looking at the W-Amp column. If it's 1.0, that means data was written exactly once to L0 (when flushed), and never rewritten. If it's above 1.0, then at least some of the data was rewritten, which can only be caused by L0->L0.

For example, here's my output for a workload that's heavy in L0->L0 compactions:

```
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0     17/14  104.13 MB   0.8      1.2     0.0      1.2       1.9      0.6       0.0   2.9     57.1     87.4        22      1738    0.013     18M   7998
```
