### ISSUE TITLE
[Question]Rocksdb linkbench

### ISSUE THREAD

**Issue by hshs1103** [facebook/rocksdb#2925]
Hi, dear all

I want to test with linkbench in rocksdb.

Is it possible experiment with linkbench in rocksdb version 5.7.1?

I found the following site after looking for a test method.

https://github.com/facebookarchive/linkbench/wiki/Running-linkbench-with-rocksdb

But I do not know how to starting the rocksdb server. 

If you know how to use rocksdb with linkbench, please let me know.

**Comment by maysamyabandeh** [comment]
Linkbench sends SQL queries to MySQL. When MySQL uses MyRocks as the storage engine (which is based on RocksDB) the RocksDB is tested under linkbench.
MyRocks: https://github.com/facebook/mysql-5.6

I recommend using User Group (https://www.facebook.com/groups/rocksdb.dev) for such questions, where the others users can chime in. Issues are better reserved for bug reports.
