### ISSUE TITLE
IO error: While fsync: a directory: Invalid argument - when using CIFS mount

### ISSUE THREAD

**Issue by mkosieradzki** [facebook/rocksdb#2929]
When trying to use RocksDB on CIFS mount I get `IO error: While fsync: a directory: Invalid argument` when calling `rocksdb_transactiondb_open`.

I have attached log.

[mylog.txt](https://github.com/facebook/rocksdb/files/1332785/mylog.txt)

**Comment by maysamyabandeh** [comment]
Dir fsync is necessary for correctness in posix fs. You can extend your code with a new env to add support for new filesystems.

**Comment by mkosieradzki** [comment]
I did A LOT of research here and found the root cause.

I am not disabling fsync I am only silencing it when FS does not implement it see:
https://github.com/torvalds/linux/blob/6ed0529fef09f50ef41d396cb55c5519e4936b16/fs/sync.c#L187-L188

It returns EINVAL if fsync is not implemented by this specific FS.

If other error is returned I am not altering the flow.

Root cause is that that CIFS is not implementing this operation:
https://github.com/torvalds/linux/blob/69c902f597c4bec92013a526268620fb6255c24a/fs/cifs/cifsfs.c#L1168-L1176

however for example NFS is:
https://github.com/torvalds/linux/blob/c971aa3693e1b68086e62645c54a087616217b6f/fs/nfs/dir.c#L63

with a dummy operation.

@maysamyabandeh Can you give this PR another chance, please?

**Comment by mkosieradzki** [comment]
I was apparently wrong. In the first place I did tests only with Sync WAL. After disabling sync wal application started to segfault so it's definitely a bad idea and apparently CIFS requires proper directory sync implementation in the first place :-(
