### ISSUE TITLE
Disable shlx instructon

### ISSUE THREAD

**Issue by topilski** [facebook/rocksdb#2930]
Hi, how to disable SHLX instruction? according issue https://github.com/fastogt/fastonosql/issues/45#issuecomment-332107389

**Comment by maysamyabandeh** [comment]
I recommend posting a self-contained question to the User Group (https://www.facebook.com/groups/rocksdb.dev), where other Windows users can chime in.

**Comment by topilski** [comment]
Reopen please, SHLX it is CPU instruction, and it independent on platform on which executed code on Linux/MacOSX you also will receive SIGILL signal.

**Comment by topilski** [comment]
You have similar issue: https://github.com/facebook/rocksdb/issues/2715 why you not close it?

**Comment by maysamyabandeh** [comment]
> By default the binary we produce is optimized for the platform you're compiling on (-march=native or the equivalent). SSE4.2 will thus be enabled automatically if your CPU supports it. To print a warning if your CPU does not support SSE4.2, build with USE_SSE=1 make static_lib or, if using CMake, cmake -DFORCE_SSE42=ON. If you want to build a portable binary, add PORTABLE=1 before your make commands, like this: PORTABLE=1 make static_lib.
https://github.com/facebook/rocksdb/blob/1039133f2da932912227ed0a8c5810a364291430/INSTALL.md
