### ISSUE TITLE
on the choice of table_cache_numshardbits?

### ISSUE THREAD

**Issue by UncP** [facebook/rocksdb#2931]
```
int GetDefaultCacheShardBits(size_t capacity) {
  int num_shard_bits = 0;
  size_t min_shard_size = 512L * 1024L;  // Every shard is at least 512KB.
  size_t num_shards = capacity / min_shard_size;
  while (num_shards >>= 1) {
    if (++num_shard_bits >= 6) {
      // No more than 6.
      return num_shard_bits;
    }
  }
  return num_shard_bits;
}
```

If the block cache reaches 32MB, the `num_shard_bits` will always be 6, in this case i think there will be a performance issue.

Consider this situation, say we have 2 block caches, one with capacity 1GB, the other with capacity 16GB, and the `num_shard_bits` is 6. Now the size of each shard will be 16MB and 256MB.

when we want to find a slice in a shard, it seems that finding a slice in 16MB will always be faster then in 256MB.

Am i right?

**Comment by maysamyabandeh** [comment]
The best way to figure that is to run the bench. Feel free to share the results if you found a performance issue afterwards. In this particular case, the default function is used only if the users does not provide the number of shard bits.

**Comment by UncP** [comment]
thanks for your reply!
