### ISSUE TITLE
Backup / Restore semantics?

### ISSUE THREAD

**Issue by mperham** [facebook/rocksdb#2938]
Can we restore a hot db?

I wrote a test which did this to a live, blank database:

```
open empty db
put element
backup
put second element
restore from latest
verify second element is gone
```

which failed on the assertion.  Do we need to close and reopen the database?  What about any CF handles?

**Comment by ajkr** [comment]
Can you try close before the restore and open after? Restore isn't supported on a live DB.

**Comment by mperham** [comment]
Cool, it works when I close the DB and reopen.  Note the wiki page says "use these APIs" but doesn't say anything higher-level about needing to reopen the database.  I added a note that restored databases must be reopened.
