### ISSUE TITLE
Superversion leaks in DBImpl::NewInternalIterator on error return.

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#2955]
### Expected behavior
Superversion is registered for cleanup at all times or released immediately

### Actual behavior
Superversion is only registered for cleanup for happy path. Otherwise the pointer is left dangling as NewErrorInternalIterator() does not care about it.

### Steps to reproduce the behavior
See https://github.com/facebook/rocksdb/blob/master/db/db_impl.cc#L911

**Comment by yiwu-arbug** [comment]
@yuslepukhin thanks for reporting! will fix.
