### ISSUE TITLE
Static library Windows build size

### ISSUE THREAD

**Issue by qraz** [facebook/rocksdb#2968]
I was building using vcpkg on Windows 7 with VS 2015 with update 3.

 When I built using static library option, the size of the binary is around 1 GB. I think it could be due to the debug information being added to the library, although it happens with release builds (750 MB) as well.

I've read this post replies to this https://www.facebook.com/groups/rocksdb.dev/permalink/1341600742605103/ saying that the size is normal. 
Has anyone else noticed this and have any solution or work around? Thanks.

**Comment by siying** [comment]
We use github issues for bug reports, which are expected to be closed after resolved. We recommend people to move open-ended questions to either RocksDB facebook group, or the Google group. It's very hard to keep an open discussion going here.
