### ISSUE TITLE
'make check' creates a lot of test binaries in the root directory

### ISSUE THREAD

**Issue by reddragon** [facebook/rocksdb#297]
A small nit. If I do 'make check', it ends up creating a lot of test binaries in the root directory. They can possibly be moved into a 'bin' or 'bintests' kind of directory, so as not to clutter the root directory.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
