### ISSUE TITLE
how to use ldb with column families?

### ISSUE THREAD

**Issue by zoglee** [facebook/rocksdb#300]
Hi, I find there is no option for specifying the column family (eg: by name), then how can I access data in non-default column-family by ldb?

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
