### ISSUE TITLE
‘perf_context’ is not a member of 'rocksdb'

### ISSUE THREAD

**Issue by yanchenmochen** [facebook/rocksdb#3010]
when I compile the ceph12.2.0 using make, It will counter the fault 
"/home/sqh/ceph/src/kv/RocksDBStore.cc": in the member function ‘ virtual int RocksDBStore::submit_transacti’
error: 'perf_context' is not a member of 'rocksdb' in /home/sqh/ceph/src/kv/RocksDBStore.cc:508
ang it will counter the same error in line 535,537,539,541,561,589,593,595.
How can I resolve this problem?

**Comment by yiwu-arbug** [comment]
Not familiar with Ceph, but you probably need to take this commit: https://github.com/ceph/ceph/commit/9d73a7121fdb1ae87cb1aa6f7d9d7a13f329ae68
