### ISSUE TITLE
corrupt when value to long

### ISSUE THREAD

**Issue by chenqinb** [facebook/rocksdb#3012]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
should not corrupt
### Actual behavior
corrupt
### Steps to reproduce the behavior
I have one Key-Value,like which only have a lots of merge operations.
eg:
key = 8618000000000
value = id1,id2,id3,......
the value is growning when the id append.Then the process corrupt.
How could I spilt the value to two or more Key-Value instace, in FullMerge2 or PartialMergeMulti?
like this:
key = 8618000000000-1
value = id1,id2,id3......id10000000
Key = 8618000000000-2
value = id10000001,id10000002....

**Comment by yiwu-arbug** [comment]
We don't have API to split KVs. You can do it in application layer. However, can you provide more info of the corruption? Would be great you can provide reproduce steps so we can investigate further.

**Comment by chenqinb** [comment]
Thanks for answer!  
Append the IDs to the same key,about 800K per minitune.And after some times ,the count of IDs are very huge, then run out of memory, coredump in C++ new.
800K per mininute is mysterious, becasue it is the test env.But in the release env, the IDs is grown with time go.
In application layer, I don't know the size of the value, only in FullMerge2 I get the size.
Thanks answer again!

**Comment by miasantreble** [comment]
I think this is expected, but with this PR: https://github.com/facebook/rocksdb/pull/3484 we are going to fail explicitly once key or value reaches 4GB
