### ISSUE TITLE
RecordTick in DbIter __dtor potentially wrong

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#3013]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

https://github.com/facebook/rocksdb/blob/5.11.fb/db/db_iter.cc#L153 potentially make the stats wrong.

The argument of -1 for uint64_t results in a max value for the type. 

### Expected behavior

The number of ticks decreased

### Actual behavior

Depending on the impl we have a potential overflow.

### Steps to reproduce the behavior

Code review

**Comment by yiwu-arbug** [comment]
We need a proper way to subtract from tickers :/  cc @ajkr

**Comment by ajkr** [comment]
Could you elaborate in what case or on what platform it's expected to be wrong? The case I think it'd be wrong is if the ticker is 0 and we add `(uint64_t)-1`. But that won't happen because this decrement only happens in the destructor when the ticker must be positive. What am I missing?

**Comment by siying** [comment]
@ajkr statistics is not the place to keep current status, so I don't really like the stats NO_ITERATION. But since it's already there, let me think of a way to fix it.

**Comment by siying** [comment]
Wow this is really hard to fix... I can try to add Statistics::reduceTick(), but any existing implementation will see a build break.
