### ISSUE TITLE
No way to not use libtbb if it is detected, even if it is only available as a dynamic library

### ISSUE THREAD

**Issue by adamnovak** [facebook/rocksdb#3036]
### Expected behavior

RocksDB should be able to build a library that does not use `libtbb` whether or not `libtbb` is available on the build system. This is useful for building static binaries (note that `libtbb-dev` in Ubuntu does not ship a static `libtbb.a`), and for building dynamic binaries intended to be used on systems where `libtbb` will not be available.

### Actual behavior

RocksDB detects that libtbb works here:

https://github.com/facebook/rocksdb/blob/279296f4d834d4cbdc35be28fca5b1eef71693a3/build_tools/build_detect_platform#L306-L315

There is no way to override this check and request that `libtbb` not be used in the build.

This is causing trouble for our downstream project in https://github.com/vgteam/vg/issues/1173 where a user is trying to build a static binary of our tool, which uses RocksDB, on a system where `libtbb`'s headers and dynamic library are installed, but where no `libtbb.a` is available. The only thing I can really tell them is to uninstall `libtbb` from the system, which is hardly an appropriate answer.

### Steps to reproduce the behavior

* Build RocksDB when `libtbb` is installed but `libtbb.a` does not exist.

* See that `PLATFORM_LDFLAGS` in `make_config.mk` contains `-ltbb`.

* Try to link a `-static` RocksDB-using binary, using those flags.

* Observe an error due to a missing `-ltbb`.

**Comment by yiwu-arbug** [comment]
@adamnovak Thanks for reporting! Do you have a fix to the TBB lib detection in mind?

**Comment by adamnovak** [comment]
The simplest thing would be to add an environment variable to override it.
There's already a `DISABLE_JEMALLOC` flag available.

**Comment by yiwu-arbug** [comment]
@adamnovak do you want to send us a pull request for it? Thanks!
