### ISSUE TITLE
Ingest files of different column families atomically

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#3044]
The `IngestExternalFile` interface can only ingest files of the same column family atomically. Is it possible that RocksDB can ingest files of different column families atomically? If it is possible  theoretically, we may give it a try :)

**Comment by maysamyabandeh** [comment]
This qualifies as a feature request. Issues are to be used only for bug reports. Feel free to the user group (https://www.facebook.com/groups/rocksdb.dev) for such discussions.
