### ISSUE TITLE
Build for android

### ISSUE THREAD

**Issue by topilski** [facebook/rocksdb#3045]
Hi, i'am trying to build rocksdb for android, but i receive error:
```
../monitoring/perf_level.cc:15:20: error: rocksdb::__emutls_t._ZN7rocksdb10perf_levelE causes a section type conflict with rocksdb::perf_level
 __thread PerfLevel perf_level = kEnableCount;
                    ^
../monitoring/perf_level.cc:15:20: note: 'rocksdb::perf_level' was declared here
[74/421] Building CXX object CMakeFile...-shared.dir/monitoring/statistics.cc.o
ninja: build stopped: subcommand failed.
```

I'am using cmake and android toolchain file, cmake command line is:

`cmake .. -GNinja -DCMAKE_STRIP="/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip" -DCMAKE_AR="/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar" -DCMAKE_C_COMPILER="/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc" -DCMAKE_CXX_COMPILER="/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-g++" -DCMAKE_TOOLCHAIN_FILE=../cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/opt/android-ndk/platforms/android-9/arch-arm/usr/ -DPORTABLE=ON -DFAIL_ON_WARNINGS=OFF`

Can you help me how to fix this error.

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
A search for "android: in the user group will already provide some help.
