### ISSUE TITLE
RocksDB failed to build (Release/x64) on windows due to warning C4189: 'ret': local variable is initialized but not referenced 

### ISSUE THREAD

**Issue by shanshan0309** [facebook/rocksdb#3049]
RocksDB failed to build (Release/x64) on VS2017 due to warning C4189. We noticed the warning C4189 is reported after commit [ebab2e2](https://github.com/facebook/rocksdb/commits/master) "Enable MSVC W4 with a few exceptions. Fix warnings and bugs". Could you please help take a look about this issue? Thank you very much!

**Failures:**
d:\rocksdb\src\db\column_family.cc(466): warning C4189: 'deleted': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\db\compaction_iterator.cc(140): warning C4189: 'valid_key': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\db\compaction_iterator.cc(337): warning C4189: 'last_sequence': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]         d:\rocksdb\src\db\compaction_iterator.cc(541): warning C4189: 'valid_key': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\db\db_impl_compaction_flush.cc(1681): warning C4189: 'output_level': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\db\version_set.cc(1914): warning C4189: 'count': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\env\mock_env.cc(382): warning C4189: 'ret': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\monitoring\thread_status_updater.cc(255): warning C4189: 'result': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\utilities\blob_db\blob_db_impl.cc(1315): warning C4189: 'erased': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\utilities\document\json_document.cc(51): warning C4189: 'bytesWritten': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\utilities\persistent_cache\block_cache_tier_metadata.cc(66): warning C4189: 'ok': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\utilities\write_batch_with_index\write_batch_with_index.cc(483): warning C4189: 'success': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\port\win\io_win.cc(282): warning C4189: 'ret': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\port\win\io_win.cc(1023): warning C4189: 'ret': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
d:\rocksdb\src\port\win\env_win.cc(77): warning C4189: 'ret': local variable is initialized but not referenced [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]

**Repro steps:**
1.Open VS2017 x64 Native tools command tool
2.git clone https://github.com/facebook/rocksdb D:\RocksDB\src
3.cd D:\RocksDB
4.mkdir build_x64 && pushd build_x64
5.cmake -G "Visual Studio 15 Win64" -DCMAKE_SYSTEM_VERSION=10.0.15063.0  ..\src
6.msbuild build_x64\rocksdb.sln /p:Configuration=Release;Platform=x64 /t:Rebuild /m /p:BuildInParallel=true

**Comment by maysamyabandeh** [comment]
@yuslepukhin could you take a look?

**Comment by rbrasga** [comment]
I think I am seeing the same problem. It shows up as a warning then again since 'warnings as errors' is enabled. Here is what I see: 

Build FAILED.

       "C:\rocksdb\build\rocksdb.sln" (default target) (1)
        ->
       "C:\rocksdb\build\arena_test.vcxproj.metaproj" (def
       ault target) (3) ->
       "C:\rocksdb\build\rocksdb.vcxproj.metaproj" (defaul
       t target) (5) ->
       "C:\rocksdb\build\rocksdb.vcxproj" (default target)
        (163) ->
       (ClCompile target) ->
         c:\program files (x86)\microsoft visual studio\2017\community\vc\tools
       \msvc\14.11.25503\include\memory(1712): warning C4244: 'argument': conve
       rsion from 'rocksdb::cassandra::ColumnTypeMask' to 'int8_t', possible lo
       ss of data [C:\rocksdb\build\rocksdb.vcxproj]


       "C:\rocksdb\build\rocksdb.sln" (default target) (1)
        ->
       "C:\rocksdb\build\c_test.vcxproj.metaproj" (default
        target) (20) ->
       "C:\rocksdb\build\rocksdb-shared.vcxproj.metaproj"
       (default target) (21) ->
       "C:\rocksdb\build\rocksdb-shared.vcxproj" (default
       target) (164) ->
         c:\program files (x86)\microsoft visual studio\2017\community\vc\tools
       \msvc\14.11.25503\include\memory(1712): warning C4244: 'argument': conve
       rsion from 'rocksdb::cassandra::ColumnTypeMask' to 'int8_t', possible lo
       ss of data [C:\rocksdb\build\rocksdb-shared.vcxproj
       ]


       "C:\rocksdb\build\rocksdb.sln" (default target) (1)
        ->
       "C:\rocksdb\build\arena_test.vcxproj.metaproj" (def
       ault target) (3) ->
       "C:\rocksdb\build\rocksdb.vcxproj.metaproj" (defaul
       t target) (5) ->
       "C:\rocksdb\build\rocksdb.vcxproj" (default target)
        (163) ->
       (ClCompile target) ->
         c:\program files (x86)\microsoft visual studio\2017\community\vc\tools
       \msvc\14.11.25503\include\memory(1712): error C2220: warning treated as
       error - no 'object' file generated [C:\rocksdb\buil
       d\rocksdb.vcxproj]


       "C:\rocksdb\build\rocksdb.sln" (default target) (1)
        ->
       "C:\rocksdb\build\c_test.vcxproj.metaproj" (default
        target) (20) ->
       "C:\rocksdb\build\rocksdb-shared.vcxproj.metaproj"
       (default target) (21) ->
       "C:\rocksdb\build\rocksdb-shared.vcxproj" (default
       target) (164) ->
         c:\program files (x86)\microsoft visual studio\2017\community\vc\tools
       \msvc\14.11.25503\include\memory(1712): error C2220: warning treated as
       error - no 'object' file generated [C:\rocksdb\buil
       d\rocksdb-shared.vcxproj]

    2 Warning(s)
    2 Error(s)

**Comment by yuslepukhin** [comment]
This is supposed to be fixed by d2a65c59e1ae270822c4c56176a7d1dcfb8e2033

**Comment by rbrasga** [comment]
@yuslepukhin I am using 57fcdc264aa0f2bb481fdad9d4a1a7846395c6e1, which is a couple commits ahead of that one. I still get the warnings.

**Comment by shanshan0309** [comment]
@yuslepukhin, RocksDB still failed to build due to the warning C4244: 'argument': conversion from 'rocksdb::cassandra::ColumnTypeMask' to 'int8_t', possible loss of data with the latest revision 9b18cc2. Thanks.
