### ISSUE TITLE
compactation synchronization& snapshot

### ISSUE THREAD

**Issue by markk12** [facebook/rocksdb#3051]
hi 
i m using a column rocksdb for saving sequence.Sequence is a long.
for evoiding to create too many conflicts if i save the sequence value every time it is incremented
(2 different transaction conflict in the same cell also if the increment for long is atomic  ) i save sequence in async way periodically.
The problem now if there is a crash of the system ... the sequence is not updated.

How to restore the snapshot of  database to  last snapthshot aligned with the sequence(i could save the last snapshot sequence number with sequence)?
i imagined if in the while there was a compactation ... the old snapshot are destroyed right? there is a way for telling to compact until a specific snapshot sequenceNumber id?

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
