### ISSUE TITLE
RocksDB JNI Maven publication

### ISSUE THREAD

**Issue by criccomini** [facebook/rocksdb#308]
Once the ongoing RocksDB JNI work is committed (https://github.com/facebook/rocksdb/pull/235), I'm looking at publishing RocksDB's JNI libraries to Maven central so that the work can be consumed by other Java projects.

My proposal is to use [Sonatype](http://www.sonatype.org/)'s open source Maven repo as the host for RocksDB JARs. This repo gets mirrored into Maven central. The artifacts will be published under the 'org.rocksdb' group.

Does this sound OK with everyone?

**Comment by criccomini** [comment]
Hey all, when is the next version of RocksDB going to be released? Last release was 3.9.1. Thanks!

**Comment by rven1** [comment]
We are hoping to release 3.10 later this week. We are working through the last few issues.
Thanks,
-Venky

**Comment by taotaotw** [comment]
Hi, all,  when will the next version of jar be released to maven? thanks!

**Comment by fyrz** [comment]
@criccomini any plans yet ?

**Comment by naveenatceg** [comment]
Hey guys, I am working on the release, some changes in the Makefile has broken the release process. Should be out sometime next week.

**Comment by fyrz** [comment]
@naveenatceg if you encounter any problems feel free, i`ll would help to get things correct.

**Comment by naveenatceg** [comment]
Thanks @fyrz. I have released 3.10.0 jars to maven.

**Comment by taotaotw** [comment]
thanks @naveenatceg @fyrz
