### ISSUE TITLE
may be a code bug

### ISSUE THREAD

**Issue by jerousrb** [facebook/rocksdb#3112]
in the file db/column_family.cc ,the destructor of ColumnFamilySet,  deleting cfd directly after dereferencing by call  cfd->Unref();

I think we can delete cfd  only when the  cfd->Unref()== true, others we no need to delete!

ColumnFamilySet::~ColumnFamilySet() {
  while (column_family_data_.size() > 0) {
    // cfd destructor will delete itself from column_family_data_
    auto cfd = column_family_data_.begin()->second;
    cfd->Unref();
    delete cfd; // this should  do it when cfd->Unref()==true ?
  }
  dummy_cfd_->Unref();
  delete dummy_cfd_;
}

**Comment by ajkr** [comment]
Interesting question. The `ColumnFamilySet` is deleted only when the DB is destroyed, so maybe this let's us avoid memory leak in case there are CFD referrers that forget to call Unref(). Want to try fixing it as you suggested and see if valgrind/ASAN pass?

**Comment by yiwu-arbug** [comment]
I think an assert is more appropriate since cfd is not suppose to outlive the DB. I'll send a patch.
