### ISSUE TITLE
why not support DeleteFilesInRange in java ?

### ISSUE THREAD

**Issue by ltwy** [facebook/rocksdb#3132]
I want to use `DeleteFilesInRange` API  to delete a lot of SST files, but I can not find it in the Java API. Is there any other reason? If no other reason, I am going to add this interface in JNI.

**Comment by ajkr** [comment]
No reason that I know of.

**Comment by adamretter** [comment]
@Itwy please feel free to send a PR.

**Comment by itwy** [comment]
@adamretter What PR?

**Comment by adamretter** [comment]
@itwy I was suggesting that you might like to send us a PR!

**Comment by itwy** [comment]
@adamretter too busy for this shit. Do it yourself.

**Comment by adamretter** [comment]
@itwy are you not the same person as @ltwy?

**Comment by itwy** [comment]
Lol. You pinged me.
