### ISSUE TITLE
RocksDBJava: Consider using PhantomReference-based cleaner to replace finalize?

### ISSUE THREAD

**Issue by killme2008** [facebook/rocksdb#3154]
A idea came from http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-June/034425.htmlph

`finalize` in RocksDB objects is not a good practice and it will affect GC, make young GC takes more time even when you close the resource explicitly.

In our system ,we replace the finalize with  PhantomReference-based cleaner, the young GC cost time drop to almost half of the original.

Google guava lib provides [FinalizablePhantomReference](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/FinalizablePhantomReference.java), and i think it can be introduced into RocksDB Java. If you think this is valuable, i can create a patch for it.

Thanks.

**Comment by adamretter** [comment]
@killme2008 I think in the longer term I want to move towards more explicit cleanup of objects, i.e. the user should call `.close()`. In some places we can assist with this, but my experience has been that implicit cleanup, i.e. via fianlize is problematic and often leads the user to consume more memory than necessary.
