### ISSUE TITLE
Data corruption in 5.9 (possibly related to range deletion)

### ISSUE THREAD

**Issue by bdarnell** [facebook/rocksdb#3169]
When we upgraded CockroachDB from rocksdb 5.7 to 5.9, we started experiencing data corruption (cockroachdb/cockroach#19947). Bisection pointed to rocksdb commit 593d3de as the cuprit (this is not certain because our reproduction is not 100% reliable, but we've repeated it several times). 

That commit causes certain blocks (including the range deletion block) to contain no restart points (other than the one that is automatically created at 0). We know from experience that range deletions often break in rocksdb upgrades, so any change here is suspicious to us, although we don't know what the issue here might be.

**Comment by zhangjinpeng1987** [comment]
@bdarnell Do you use DeleteFilesInRange together with DeleteRange?

**Comment by bdarnell** [comment]
No. We use DeleteRange but not DeleteFilesInRange.

**Comment by zhangjinpeng1987** [comment]
After set restart interval to `kMaxInt32` for range deletion block, the `num_restarts` will always be 0, so when construct a block iterator to read this block at [here](https://github.com/facebook/rocksdb/blob/master/table/block.cc#L434), will construct a `EmptyInternalIterator` and will read nothing.
@ajkr If i am right?

**Comment by zhangjinpeng1987** [comment]
To solve this problem should improve the implementation at [here](https://github.com/facebook/rocksdb/blob/master/table/block_builder.cc#L94), the first restart position 0, we also need to record it.

**Comment by miasantreble** [comment]
@bdarnell thanks for report the regression, we've revert the commit and backported to 5.9.fb.
We will work on another fix that doesn't break CockroachDB. Closing the issue for now.
