### ISSUE TITLE
LRU Cache bug causes DLL load failure in windows in 5.8

### ISSUE THREAD

**Issue by warrenfalk** [facebook/rocksdb#3184]
### Expected behavior
v5.8 Windows DLL doesn't crash on load

### Actual behavior
v5.8 Windows DLL crashes on load in call to `_aligned_malloc` in `port_win.h` with message "invalid parameter was passed to a function that considers invalid parameters fatal"

### Steps to reproduce the behavior
Build in windows and try to load DLL

I think this may also be related to many other reports of breakage on Windows.  It looks like the error started with commit:

```
commit e367774d19501a78c0699e6458d420c57ac73567
Author: yiwu-arbug <yiwu-arbug@users.noreply.github.com>
Date:   Mon Aug 14 14:28:33 2017 -0700

    Overload new[] to properly align LRUCacheShard

    Summary:
    Also verify it fixes gcc7 compile failure #2672 (see also #2699)
    Closes https://github.com/facebook/rocksdb/pull/2732

    Differential Revision: D5620348

    Pulled By: yiwu-arbug

    fbshipit-source-id: 87db657ab734f23b1bfaaa9db9b9956d10eaef59
```

But the actual issue appears to be in port_win.h where ```cacheline_aligned_alloc``` is implemented like this:

```
inline void *cacheline_aligned_alloc(size_t size) {
  return _aligned_malloc(CACHE_LINE_SIZE, size);
}
```

The arguments to _aligned_malloc() here are backwards.

The breakage started in this commit (included in v5.8):

```
commit 16e03882054fa8c947ca84f30b87e1cd3e929597
Author: Daniel Black <daniel.black@au.ibm.com>
Date:   Mon Jul 24 10:46:21 2017 -0700

    LRUCacheShard cache line size alignment

    Summary:
    combining #2568 and #2612.
    Closes https://github.com/facebook/rocksdb/pull/2620

    Differential Revision: D5464394

    Pulled By: IslamAbdelRahman

    fbshipit-source-id: 9f71d3058dd6adaf02ce3b2de3a81a1228009778
```

And was fixed in this commit (not included in any release leaving Windows still entirely broken in 5.8)

```
commit 0ec90a7cc2077c9629bbd3ccc70823f77a94796d (HEAD)
Author: Dmitri Smirnov <dmitrism@microsoft.com>
Date:   Thu Aug 31 16:42:05 2017 -0700

    Add -DPORTABLE=1 to MSVC CI build

    Summary:
    Add -DPORTABLE=1
      port::cacheline_aligned_alloc() has arguments swapped which prevents every single test from running.
    Closes https://github.com/facebook/rocksdb/pull/2815

    Differential Revision: D5751661

    Pulled By: siying

    fbshipit-source-id: e0857d6e138ec46035b3c23d7c3c751901a0a4a0

```

Can we get an update to 5.8 released with at least this bug fixed?

**Comment by adamretter** [comment]
@warrenfalk I wonder if this is the same issue as: https://github.com/facebook/rocksdb/issues/2965

**Comment by yiwu-arbug** [comment]
Just tagged 5.8.6 which include 0ec90a7 and 682db81.

@adamretter Can you help close #2965 if you think its the same issue?

**Comment by yiwu-arbug** [comment]
Never mind. I'll close that one.

**Comment by adamretter** [comment]
@warrenfalk thanks for reporting, and thanks @yiwu-arbug for fixing.
