### ISSUE TITLE
OT:Relicensing

### ISSUE THREAD

**Issue by inoas** [facebook/rocksdb#3197]
OT: In the react repos I read you guys re-licensed rocksdb:
* How did you proceed with independent (e.g. not facebook employed) contributors who contributed based on the given license when their PRs where merged? Did you question them if the license change was okay?
* Where can I read more about this and how that was resolved?
* Was it no issue at all, and how so?

Ref: https://github.com/facebook/react/issues/10191

**Comment by sagar0** [comment]
Thanks for the inquiry. It was a Facebook legal decision, and we cannot comment on such decisions.
