### ISSUE TITLE
SyncWAL() triggers a failure on Windows

### ISSUE THREAD

**Issue by hermanlee** [facebook/rocksdb#3200]
Testing of MyRocks being ported into MariaDB of the latest SyncWAL() changes have triggered an error on Windows builds:

https://jira.mariadb.org/browse/MDEV-13852

The check !it->writer->file()->writable_file()->IsSyncThreadSafe() fails for Windows. What is the expected behavior here. Is SyncWAL() not supposed to be called on Windows builds?

**Comment by maysamyabandeh** [comment]
@yuslepukhin can you chime in? Is sync thread-safe in windows? Should we override IsSyncThreadSafe() in io_win.h?

**Comment by a-robinson** [comment]
As far as I know, `SyncWAL` can't/shouldn't be used on Windows. For example, this `SyncWAL` test is specifically skipped on Windows - https://github.com/facebook/rocksdb/blob/72502cf2270db7323d447cc7a504dbea251d432a/db/column_family_test.cc#L3132-L3133.

In CockroachDB we work around this by issuing an empty write with `WriteOptions.sync=true`, as suggested in the FAQ - https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ

**Comment by maysamyabandeh** [comment]
Thanks @a-robinson. If that is the case I wonder if we can augment SyncWAL to do a dummy write with sync=true if IsSyncThreadSafe() is false.

**Comment by yiwu-arbug** [comment]
Will letting SyncWAL() enter write thread if IsSyncThreadSafe()=false solve the problem?

**Comment by maysamyabandeh** [comment]
I am waiting for @yuslepukhin to chime in.

**Comment by yuslepukhin** [comment]
I will take a look at it but from the test it seems no-one has implemented SyncWAL() on windows and thus it is difficult make a judgement about the thread-safety.

`WARNING: c:\dev\rocksdb\gh\db\write_callback_test.cc(315): error: s
WARNING: Not implemented: SyncWAL() is not supported for this implementation of WAL file`

**Comment by yuslepukhin** [comment]
Windows makes use of FlushFileBuffers (https://msdn.microsoft.com/en-us/library/windows/desktop/aa364439(v=vs.85).aspx) which can be inefficient when called frequently and totally unnecessary when we use un-buffered mode. 

I will submit a PR where IsSyncThreadSafe() returns true but Sync() and FSync() would be a NOOP for UN-buffered mode.

**Comment by maysamyabandeh** [comment]
Thanks @yuslepukhin. So if FILE_FLAG_WRITE_THROUGH is true then IsSyncThreadSafe() should return false? If yes, does the dummy-write-with-sync solution that @a-robinson mentioned a reasonable alternative to add to SyncWAL?

**Comment by maysamyabandeh** [comment]
@yuslepukhin Any update on this?

**Comment by yuslepukhin** [comment]
@maysamyabandeh Lets find a PR that was submitted from MS but was stalled by me. I now think we can check that in.

**Comment by yuslepukhin** [comment]
@maysamyabandeh This was addressed by https://github.com/facebook/rocksdb/pull/3225, was it not?

**Comment by maysamyabandeh** [comment]
Thanks @yuslepukhin. That should take care of it.
