### ISSUE TITLE
Rocksdb version used in last updated code rocksdbjni which was 4 year back,which api of rocksdb was used in rocksdbjni

### ISSUE THREAD

**Issue by anuthekool** [facebook/rocksdb#3215]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

**Comment by adamretter** [comment]
The latest version of rocksdbjni is on Maven Central. The release numbers follow that of RocksDB.

**Comment by anuthekool** [comment]
actually i have to confirm that that the latest version of rocksdbjni uses latest RocksDB API or not?can you help me out?

**Comment by adamretter** [comment]
Yes. Check the version numbers!

**Comment by anuthekool** [comment]
can you send me the link of latest rocksdbjni and which version rocksdb it is using...i am not able to find it

**Comment by adamretter** [comment]
https://search.maven.org/#search%7Cga%7C1%7Crocksdbjni

**Comment by anuthekool** [comment]
when i download the source code i only got the rocksdb,both have same version.

i got code of rocksdbjni at path: https://github.com/facebook/rocksdb/issues/3215

this code was last updated four years ago......i have to port rocksdbjni for AARCH64 platform...i have to confirm the latest source code of rocksdbjni contain latest rocksdb API.

please help

**Comment by adamretter** [comment]
I don't know where you are taking the code from but, the code is in this GitHub repo.

**Comment by anuthekool** [comment]
you have given the path of maven central....but in git hub there is 4 years old code of Rocksdbjni.....you said latest code of Rocksdbjni is in maven central........which git hub repo you are talking for the latest code....i have to sure where is the latest code of Rocksdbjni on git hub or maven central....as per my knowledge on git hub 4 year old code is there.

**Comment by adamretter** [comment]
@anuthekool I really don't understand where the confusion is!
The code on GitHub is here - https://github.com/facebook/rocksdb you can see that it has been updated very recently.
The Maven artifacts built from that very code are here - https://search.maven.org/#search%7Cga%7C1%7Crocksdbjni

The latest release was 5.8.7, which was release 3 days ago. The Java artifacts for that were published to Maven central yesterday.

**Comment by anuthekool** [comment]
i am talking about rocksdbjni code which is at location https://github.com/fusesource/rocksdbjni   not about rocksdb which is at https://github.com/facebook/rocksdb. rocksdbjni code is last updated 4 years ago,is it latest version is there in maven central.
Actually Rocksdbjni uses rocksdb,so i have to just find  out rocksdbjni updated latest code which is using latest rocksdb API.

**Comment by adamretter** [comment]
The link https://github.com/fusesource/rocksdbjni is for a separate project which we are not involved in, and so we cannot answer questions about that. If you want to know about that, you should open an issue there, and not here.

The code in this **repo** (https://github.com/facebook/rocksdb) is current,  and the Maven artifacts I pointed you to (https://search.maven.org/#search%7Cga%7C1%7Crocksdbjni) are built from that code.

**Comment by anuthekool** [comment]
do you have any idea,which APIs of Rocksdb rocksdbjni is using....i have to identify the APi's of Rocksdb which rocksdbjni is using..can you help me out?

**Comment by adamretter** [comment]
@anuthekool I don't think I can help you further.
