### ISSUE TITLE
cross compiling error for aarch64

### ISSUE THREAD

**Issue by anuthekool** [facebook/rocksdb#3218]
i am getting following error when i am cross comiling it for aarch64

-- Found Threads: TRUE  
CMake Warning (dev) at CMakeLists.txt:603 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- JNI library is disabled
CMake Error at CMakeLists.txt:685 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "rocksdb-shared".
-- Configuring incomplete, errors occurred!

Done changes for cross compiling is cmake file is  = 

# this one is important
SET(CMAKE_SYSTEM_NAME Generic)
#this one not so much
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR aarch64)
# specify the cross compiler
SET(CMAKE_C_COMPILER   /opt/gcc-linaro-5.5.0-2017.10-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER /opt/gcc-linaro-5.5.0-2017.10-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++)

**Comment by anand1976** [comment]
I'm not sure how to reproduce this locally. Could it be a problem with the toolchain you're using?

**Comment by anand1976** [comment]
Closing due to no response. Please reopen if you're still seeing this issue.
