### ISSUE TITLE
Rocksdb can't support LZ4 compression

### ISSUE THREAD

**Issue by zengqingfu1442** [facebook/rocksdb#3221]
I have installed these on my system with yum,
[dzeng@dzeng rocksdb-master]$ rpm -qa | grep lz4
lz4-1.7.3-1.el7.x86_64
lz4-devel-1.7.3-1.el7.x86_64
[dzeng@dzeng rocksdb-master]$ rpm -qa | grep zstd
libzstd-devel-1.3.1-1.el7.x86_64
libzstd-1.3.1-1.el7.x86_64
zstd-1.3.1-1.el7.x86_64
[dzeng@dzeng rocksdb-master]$ rpm -qa | grep snappy
snappy-devel-1.1.0-3.el7.x86_64
snappy-1.1.0-3.el7.x86_64
[dzeng@dzeng rocksdb-master]$ rpm -qa | grep zlib
zlib-1.2.7-17.el7.x86_64
zlib-1.2.7-17.el7.i686
zlib-devel-1.2.7-17.el7.x86_64

Then I compile rocksdb using "make release", the tool db_sanity_test can also link to the so file,
[dzeng@dzeng rocksdb-master]$ ldd db_sanity_test
linux-vdso.so.1 => (0x00007ffe8ffe8000)
libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f8107418000)
librt.so.1 => /usr/lib64/librt.so.1 (0x00007f810720f000)
libsnappy.so.1 => /usr/lib64/libsnappy.so.1 (0x00007f8107009000)
libgflags.so.2.1 => /usr/lib64/libgflags.so.2.1 (0x00007f8106de8000)
libz.so.1 => /usr/lib64/libz.so.1 (0x00007f8106bd1000)
libcssz.so => /usr/lib64/libcssz.so (0x00007f8106929000)
libbz2.so.1 => /usr/lib64/libbz2.so.1 (0x00007f8106719000)
liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007f8106505000)
libzstd.so.1 => /usr/lib64/libzstd.so.1 (0x00007f81062a6000)
libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00007f810609a000)
libtbb.so.2 => /usr/lib64/libtbb.so.2 (0x00007f8105e64000)
libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f8105b5c000)
libm.so.6 => /usr/lib64/libm.so.6 (0x00007f810585a000)
libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f8105643000)
libc.so.6 => /usr/lib64/libc.so.6 (0x00007f8105280000)
/lib64/ld-linux-x86-64.so.2 (0x0000561a0cb8c000)
libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f810507b000)

But it can't support lz4 compression,
[dzeng@dzeng rocksdb-master]$ ./db_sanity_test /mnt/sfx-card-root/rocksdb570/ create
Creating...
Basic -- OK
SpecialComparator -- OK
ZlibCompression -- OK
ZlibCompressionVersion2 -- OK
CSSZlibCompression -- OK
CSSZlibCompressionVersion2 -- OK
LZ4Compression -- Corruption: LZ4 not supported or corrupted LZ4 compressed block contents
FAIL
LZ4HCCompression -- Corruption: LZ4HC not supported or corrupted LZ4HC compressed block contents
FAIL
ZSTDCompression -- OK
PlainTable -- OK
BloomFilter -- OK

**Comment by ajkr** [comment]
I wasn't able to repro. A similar setup works for me:

```
$ rpm -qa | grep '^lz4'
lz4-devel-1.7.3-1.el7.x86_64
lz4-1.7.3-1.el7.x86_64
$ make clean && ROCKSDB_NO_FBCODE=1 make -j64 db_sanity_test
$ ldd ./db_sanity_test | grep lz4
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007fe00469a000) 
$ ./db_sanity_test ./tmp create
Creating...
Basic -- OK
SpecialComparator -- OK
ZlibCompression -- OK
ZlibCompressionVersion2 -- OK
LZ4Compression -- OK
LZ4HCCompression -- OK
ZSTDCompression -- OK
PlainTable -- OK
BloomFilter -- OK
```

**Comment by anand1976** [comment]
@zengqingfu1442 do you still have this problem? If so, can you check the LOG file in /mnt/sfx-card-root/rocksdb570/LZ4Compression for any relevant errors?

**Comment by zengqingfu1442** [comment]
No, now I have upgraded to rocksdb-v5.8.7 and after the new compression type csszlib integrated into it , it will both support csszlib and lz4 now. Thanks.

**Comment by anand1976** [comment]
Thanks @zengqingfu1442
