### ISSUE TITLE
cross compiling error

### ISSUE THREAD

**Issue by anuthekool** [facebook/rocksdb#3224]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

CMake Warning (dev) at CMakeLists.txt:603 (add_library):
  ADD_LIBRARY called with SHARED option but the target platform does not
  support dynamic linking.  Building a STATIC library instead.  This may lead
  to problems.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- JNI library is disabled
CMake Error at CMakeLists.txt:685 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "rocksdb-shared".

**Comment by yiwu-arbug** [comment]
Any suggested fix?

**Comment by yiwu-arbug** [comment]
duplication of #3218
