### ISSUE TITLE
RocksDB failed to build (Release/x64) on windows due to warning C4244: '=': conversion from 'int' to 'unsigned short', possible loss of data

### ISSUE THREAD

**Issue by shanshan0309** [facebook/rocksdb#3239]
RocksDB failed to build (Release/x64) on VS2017 due to warning C4244: '=': conversion from 'int' to 'unsigned short', possible loss of data. We noticed the warning C4244 is reported after commit [36911f5](https://github.com/facebook/rocksdb/commit/36911f55dd4e75b05865d17e7b234454429bdee2). Could you please help take a look about this issue? Thank you very much!

Repro steps:
1.Open VS2017 x64 Native tools command tool
2.git clone https://github.com/facebook/rocksdb D:\RocksDB\src
3.cd D:\RocksDB
4.mkdir build_x64 && pushd build_x64
5.cmake -G "Visual Studio 15 Win64" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\src
6.msbuild build_x64\rocksdb.sln /p:Configuration=Release;Platform=x64 /t:Rebuild /m /p:BuildInParallel=true

Failures:
(ClCompile target) -> 
         c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): warning C4244: '=': conversion from 'int' to 'unsigned short', possible loss of data [D:\RocksDB\build_x64\rocksdb.vcxproj]

       "D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj.metaproj" (Rebuild target) (17) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj" (Rebuild target) (25) ->
         c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): warning C4244: '=': conversion from 'int' to 'unsigned short', possible loss of data [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]

       "D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\cache_bench.vcxproj.metaproj" (Rebuild target) (4) ->
       "D:\RocksDB\build_x64\rocksdb.vcxproj.metaproj" (Rebuild target) (6) ->
       "D:\RocksDB\build_x64\rocksdb.vcxproj" (Rebuild target) (26) ->
       (ClCompile target) -> 
         c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): error C2220: warning treated as error - no 'object' file generated [D:\RocksDB\build_x64\rocksdb.vcxproj]

       "D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj.metaproj" (Rebuild target) (17) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj" (Rebuild target) (25) ->
         c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): error C2220: warning treated as error - no 'object' file generated [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]

**Comment by yiwu-arbug** [comment]
Hi @shanshan0309. Thanks for reporting. We don't have VS2017 and from the error message you provide it is hard to tell which line cause the error. Are you able to help figure out? Thanks.

**Comment by shanshan0309** [comment]
Hi @yiwu-arbug. Thanks for looking into this issue. I think the error is caused by the file util/transaction_test_util.cc(127). The details are as follows. Thanks a lot.

25>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): error C2220: warning treated as error - no 'object' file generated [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
         **d:\rocksdb\src\util\transaction_test_util.cc(127)**: note: see reference to function template instantiation 'void std::iota<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,int>(_FwdIt,_FwdIt,int)' being compiled
                 with
                 [
                     _Ty=uint16_t,
                     _FwdIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<uint16_t>>>
                 ]
    25>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): warning C4244: '=': conversion from 'int' to 'unsigned short', possible loss of data [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
         xxhash.cc
         backupable_db.cc
       ClCompile:
         transaction_test_util.cc
    26>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): error C2220: warning treated as error - no 'object' file generated [D:\RocksDB\build_x64\rocksdb.vcxproj]
         d:\rocksdb\src\util\transaction_test_util.cc(127): note: see reference to function template instantiation 'void std::iota<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,int>(_FwdIt,_FwdIt,int)' being compiled
                 with
                 [
                     _Ty=uint16_t,
                     _FwdIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<uint16_t>>>
                 ]
    26>c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.10.25017\include\numeric(328): warning C4244: '=': conversion from 'int' to 'unsigned short', possible loss of data [D:\RocksDB\build_x64\rocksdb.vcxproj]

**Comment by shanshan0309** [comment]
Hi @yiwu-arbug, any update for this issue?

**Comment by yiwu-arbug** [comment]
@shanshan0309 Ouch, it fell off my radar. Do you mind try to apply #3259 and see if it fixes the issue? Thanks.

**Comment by shanshan0309** [comment]
@yiwu-arbug, thank you so much for fixing this issue. I've verified your fix works well.
