### ISSUE TITLE
Question about byteOrder

### ISSUE THREAD

**Issue by toktarev** [facebook/rocksdb#3267]
Hello RocksDB team

I have a question about byte orders after backup.

For example I have MacOs and I write all my value to column family in little endian.

After that I made export using RocksApi.

Will it possible to use such dump on the system with BigEndian ?

Thanks.

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
