### ISSUE TITLE
global const object definitions in header files

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#3278]
We should **declare** global const objects in header files, and **define** them in source files.

Examples are(master branch at 5a7e08468ad2f03b957e255aefdfa81b95a6810a(date 2017-12-15)):
[const std::vector&lt;std::pair&lt;Tickers, std::string&gt;&gt; TickersNameMap](https://github.com/facebook/rocksdb/blob/5a7e08468ad2f03b957e255aefdfa81b95a6810a/include/rocksdb/statistics.h#L301)<br/>[const std::vector&lt;std::pair&lt;Histograms, std::string&gt;&gt; HistogramsNameMap](https://github.com/facebook/rocksdb/blob/5a7e08468ad2f03b957e255aefdfa81b95a6810a/include/rocksdb/statistics.h#L517)

### Expected behavior
One definition rule: one global const object has one only one definition.

### Actual behavior
global const object definitions in header file will produce multiple objects, in each source file which included the header.

### Steps to reproduce the behavior
```c++
// common.h
#include <stdio.h>
struct AutoInit {
        int m;
        AutoInit()  { static int n = 0; m = ++n; printf("%s: %3d\n", __PRETTY_FUNCTION__, m); }
        ~AutoInit() { printf("%s: %3d\n", __PRETTY_FUNCTION__, m); }
};
const AutoInit aa;

// a.cc
#include "common.h"

// b.cc
#include "common.h"
int main() {
        return 0;
}
```

output:
```
AutoInit::AutoInit():   1
AutoInit::AutoInit():   2
AutoInit::~AutoInit():   2
AutoInit::~AutoInit():   1
```

**Comment by maysamyabandeh** [comment]
Feel free to submit a PR.

**Comment by maysamyabandeh** [comment]
@rockeet interested in submitting a patch?

**Comment by sagar0** [comment]
It think it is a great candidate for "up-for-grabs" -- may people who are interested in contributing to RocksDB and don't know where to start can take this on and contribute as their first PR.

**Comment by JoeLoser** [comment]
Have you thought about how to script a way to find all such const global objects to fix?
