### ISSUE TITLE
librocksdb.a error

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3287]
librocksdb.a(db_impl.o): relocation R_X86_64_32S against `_ZTVN7rocksdb12SnapshotImplE' can not be used when making a shared object; recompile with -fPIC
[INFO] /home/anupam/Arm_Project/project_oss/old_rocksdb/librocksdb.a: error adding symbols: Bad value

can any one help me to resolve this issue?

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
