### ISSUE TITLE
calculate scores failed

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#3291]
When i set level_compaction_dynamic_level_bytes on for an existed DB, and then turn off it again, this will cause calculating scores failed. Look at the statistics in log, the scores for L3 L4 L5 are inf.
```
** Compaction Stats [write] **
Level    Files   Size     Score 
----------------------------
  L0      3/0    6.92 MB   0.8   
  L1     65/0   510.06 MB   1.0 
  L2     98/0   509.38 MB   inf  
  L3    695/0    4.89 GB   inf      
  L4   6727/0   49.07 GB   inf    
  L5  12541/0   57.89 GB   inf    
  L6    224/0   804.98 MB   0.0     
```

**Comment by ajkr** [comment]
do you have an options file? I tried repro'ing with the below command (alternating running with `level_compaction_dynamic_level_bytes=false` and `level_compaction_dynamic_level_bytes=true`) but it worked pretty well :/.

```
TEST_TMPDIR=/dev/shm ./db_bench -benchmarks=overwrite -use_existing_db=true -write_buffer_size=131072 -num=10000000 -level_compaction_dynamic_level_bytes=false -stats_per_interval=1 -stats_interval=100000 -target_file_size_base=131072 -max_bytes_for_level_base=524288 -max_background_jobs=12
```

**Comment by miasantreble** [comment]
Also according to the [comment](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/advanced_options.h#L435-L436):

>   // Turning this feature on or off for an existing DB can cause unexpected
  // LSM tree structure so it's not recommended.

Is there a particular reason that you need to do this?
