### ISSUE TITLE
How to understand the compaction levels?

### ISSUE THREAD

**Issue by zengqingfu1442** [facebook/rocksdb#3306]
How to understand the compaction levels?https://github.com/facebook/rocksdb/wiki/Leveled-Compaction
If level_compaction_dynamic_level_bytes=false
For example, if max_bytes_for_level_base = 123456, max_bytes_for_level_multiplier = 10 and max_bytes_for_level_multiplier_additional is not set, then size of L1, L2, L3 and L4 will be 16384, 163840, 1638400, and 16384000, respectively.

But L1's target will be max_bytes_for_level_base. And then Target_Size(Ln+1) = Target_Size(Ln) * max_bytes_for_level_multiplier * max_bytes_for_level_multiplier_additional[n]. max_bytes_for_level_multiplier_additional is by default all 1.

Why is the size of L1 not 123456?

**Comment by zengqingfu1442** [comment]
How to get the data size of each compaction level? When with compresion_pre_level, how will the data size of each level be decided?

**Comment by miasantreble** [comment]
I think the original wiki entry has a typo which have been fixed by @anand1976

**Comment by zengqingfu1442** [comment]
Yes, can I use any administrative tools to get the data size of each compaction level? Thanks.

**Comment by miasantreble** [comment]
short answer is no, ldb doesn't support that yet. 
However during compaction, RocksDB will print level summary in the LOG so you may be able to find out by manually examining the LOG file.
