### ISSUE TITLE
rocksdb uses snappy internally or not

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3308]
when rocksdb uses snappy internally?

**Comment by miasantreble** [comment]
@anuscool I presume you are talking about compression used in SST files?
By default we use Snappy but you can configure it through `options.compression`
We have a [wiki page](https://github.com/facebook/rocksdb/wiki/Compression) on compression which discusses various options and compression algorithms in detail. Please take a look

**Comment by zengqingfu1442** [comment]
If we set the options.compression_per_level, will it override the options.compression on each level?Thanks.

**Comment by miasantreble** [comment]
@zengqingfu1442 yes it should override, but beware that trivial move may behave differently, see [wiki](https://github.com/facebook/rocksdb/wiki/Compression#configuration)

> Be aware that when you set different compression to different levels, compaction "trivial moves" that violate the compression styles will not be executed, and the file will be rewrite using the expected compression.

**Comment by anuscool** [comment]
if rocksdb by default uses snappy,so we include its library in our rocksdb or not?so rocksdb contain snappy code also or its library...i want to know that
?

**Comment by miasantreble** [comment]
yes you need to link RocksDB with snappy. See [INSTALL.md](https://github.com/facebook/rocksdb/blob/master/INSTALL.md)

> You can link RocksDB with following compression libraries:
> * zlib - a library for data compression.
> * bzip2 - a library for data compression.
> * lz4 - a library for extremely fast data compression.
> * snappy - a library for fast data compression.
> * zstandard - Fast real-time compression algorithm.

**Comment by siying** [comment]
@zengqingfu1442 you are right. options.compression_per_level will it overwrite options.compression. Let me clarify that in the wiki page.

**Comment by siying** [comment]
@anuscool If you use default "make" to build RocksDB library, then RocksDB will detect whether each compression library is available in your build environment. If it is available, then it is compiled, if not, the compression support is not compiled.

**Comment by anuscool** [comment]
how to link rocksdb with snappy
i am using cmake .. -DWITHSNAPPY=1
but i am getting error

CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find snappy (missing: SNAPPY_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/Findsnappy.cmake:17 (find_package_handle_standard_args)
  CMakeLists.txt:62 (find_package)
