### ISSUE TITLE
what is the work of java files  inside rocksdb

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3309]
java files inside directory rocksdb/java/src/main/java/org/rocksdb,is this java file of .cpp files inside java/rocksjni.........what this java files do?

**Comment by miasantreble** [comment]
Please check [RocksJava](https://github.com/facebook/rocksdb/wiki/RocksJava-Basics) wiki page

**Comment by anuscool** [comment]
can we use this java files for porting in hawt jni interface directly?

**Comment by adamretter** [comment]
HawtJNI is for generating JNI stubs for you to subsequently implement. A JNI implementation is already present as part of RocksJava.
