### ISSUE TITLE
LZ4 not supported or corrupted LZ4 compressed block contents

### ISSUE THREAD

**Issue by zengqingfu1442** [facebook/rocksdb#3310]
The lz4 compression can't work in my rocksbd now.
[dzeng@dzeng rocksdb-33efdde8316759f1efc6a2a228c5efcf01f09cbc]$ ./db_sanity_test /mnt/sfx-card-root/dfs/dn/disk/rocksdb573/ create
Creating...
Basic -- OK
SpecialComparator -- OK
ZlibCompression -- OK
ZlibCompressionVersion2 -- OK
LZ4Compression -- Corruption: LZ4 not supported or corrupted LZ4 compressed block contents
FAIL
LZ4HCCompression -- Corruption: LZ4HC not supported or corrupted LZ4HC compressed block contents
FAIL
ZSTDCompression -- OK
CSSZlibCompression -- mypid = 7029, dev_name = /dev/sfx0, dev_num = 0
OK
CSSZlibCompressionVersion2 -- OK
PlainTable -- OK
BloomFilter -- OK
The sst file of lz4 can't be generated under LZ4Compression dir.
From the LOG under LZ4Compression, I can see such error:
 2017/12/27-17:29:08.114337 7fa3c1ccfa00 [db/version_set.cc:2969] Recovered from manifest file:/mnt/sfx-card-root/dfs/dn/disk/rocksdb573/LZ4Compression/MANIFEST-000001 succeeded,manifest_file_number is 1, next_file_number is 3, last_sequence is 0, log_number is 0,prev_log_number is 0,max_column_family is 0
 2017/12/27-17:29:08.114344 7fa3c1ccfa00 [db/version_set.cc:2977] Column family [default] (ID 0), log number is 0
 2017/12/27-17:29:08.115443 7fa3c1ccfa00 [db/db_impl_open.cc:1111] DB pointer 0x220adb0
 2017/12/27-17:29:13.279864 7fa3c1ccfa00 [db/db_impl_write.cc:1128] [default] New memtable created with log file: #6. Immutable memtables: 0.
 2017/12/27-17:29:13.279921 7fa3b5ef5700 [db/db_impl_compaction_flush.cc:50] [JOB 2] Syncing log #3
 2017/12/27-17:29:13.304067 7fa3b5ef5700 (Original Log Time 2017/12/27-17:29:13.279910) [db/db_impl_compaction_flush.cc:1216] Calling FlushMemTableToOutputFile with column family [default], flush slots available 1, compaction slots available 1, flush slots scheduled 1, compaction slots scheduled 0
 2017/12/27-17:29:13.304075 7fa3b5ef5700 [db/flush_job.cc:264] [default] [JOB 2] Flushing memtable with next log file: 6
 2017/12/27-17:29:13.304106 7fa3b5ef5700 EVENT_LOG_v1 {"time_micros": 1514366953304093, "job": 2, "event": "flush_started", "num_memtables": 1, "num_entries": 1000000, "num_deletes": 0, "memory_usage": 42651544}
 2017/12/27-17:29:13.304113 7fa3b5ef5700 [db/flush_job.cc:293] [default] [JOB 2] Level-0 flush table #7: started
 2017/12/27-17:29:13.702675 7fa3b5ef5700 [db/flush_job.cc:324] [default] [JOB 2] Level-0 flush table #7: 13976059 bytes Corruption: LZ4 not supported or corrupted LZ4 compressed block contents
**2017/12/27-17:29:13.702897 7fa3b5ef5700 [ERROR] [db/db_impl_compaction_flush.cc:1255] Waiting after background flush error: Corruption: LZ4 not supported or corrupted LZ4 compressed block contentsAccumulated background error counts: 1**
2017/12/27-17:29:13.702903 7fa3b5ef5700 (Original Log Time 2017/12/27-17:29:13.702885) EVENT_LOG_v1 {"time_micros": 1514366953702877, "job": 2, "event": "flush_finished", "lsm_state": [0, 0, 0, 0, 0, 0, 0], "immutable_memtables": 1}
2017/12/27-17:29:13.702934 7fa3c1ccfa00 [db/db_impl.cc:222] Shutdown: canceling all background work
2017/12/27-17:29:14.705500 7fa3c1ccfa00 [db/db_impl.cc:348] Shutdown complete

But I can scan the key-values of lz4 by ldb tool.
[dzeng@dzeng rocksdb-33efdde8316759f1efc6a2a228c5efcf01f09cbc]$ ./ldb --db=/mnt/sfx-card-root/dfs/dn/disk/rocksdb573/LZ4Compression scan | less
key0 : value0
key1 : value1
key10 : value10
key100 : value100
key1000 : value1000
key10000 : value10000
key100000 : value100000
..
...

**Comment by ajkr** [comment]
is it a different issue from https://github.com/facebook/rocksdb/issues/3221?

**Comment by zengqingfu1442** [comment]
Sorry, it's the same issue.

**Comment by ajkr** [comment]
No problem, btw I'd guess the ldb command only works because it's reading entries from WAL, which are not compressed. Since the first flush failed, the DB shouldn't contain any SST file with compressed data blocks.

**Comment by zengqingfu1442** [comment]
Yes, the sst file of lz4 can't be generated. But why does it fail when flushing the memtable to disk for lz4 compression while other compression type don't ? What will lead to this?

**Comment by gfosco** [comment]
I think this might be related to #814, where there's just a problem with your build of lz4 before building rocksdb.  Can you try what I did there, cloning lz4 and building from source first?

**Comment by zengqingfu1442** [comment]
Thanks, it's when I use rocksdb-5.7.0 that I came across such error(LZ4 not supported). But now I have turned to rocksdb5.8.7 and there is no such error now.
