### ISSUE TITLE
Slowdown in read after ~ 15 million records in DB

### ISSUE THREAD

**Issue by kl3eo** [facebook/rocksdb#3314]
The manner we did the test is following: writing 1 mln. (key:value) pairs (time checked) - each key is bigint, value is ~200bytes, - then reading them back to csv format (time checked). Then adding other 1 million records, reading 2 million records, etc. The fact is until we reached 15 million records, the time necessary for reading grew proportionally with the growing of the number of records to read. After that, there was a serious non-linearity, so the time grew much more with the number of millions of records to read. I would not be much surprised if the linearity stopped at 100 mln. records, but 10-15 million seems rather low. Am I missing something important in setup, or this is normal and well-known behaviour of RocksDb?

**Comment by siying** [comment]
What's your memory size? Is it possible that before 15 million, data isn't able to all cache in OS page cache?

**Comment by kl3eo** [comment]
32G is RAM. And I haven't figured out why this happens, yet.

**Comment by siying** [comment]
First, can you share your OPTIONS-xxxx file to us? Even better, can you enable statistics and share your LOG file with us?

**Comment by siying** [comment]
@kl3eo do you still want to follow up on this? Or can I close it?

**Comment by sagar0** [comment]
Closing, as there has been no follow up with the requested information.
