### ISSUE TITLE
PPC 64 bit BigEndian ASM compilation fault

### ISSUE THREAD

**Issue by gcsideal** [facebook/rocksdb#3315]
### Expected behavior
Successful compilation on ppc64 as happened with the 5.8.8 version.

### Actual behavior
As of RocksDB 5.9.2 and with the previously used GCC 7.2 compilation fails with:
  CC       util/crc32c_ppc_asm.o
util/crc32c_ppc_asm.S: Assembler messages:
util/crc32c_ppc_asm.S:109: Error: invalid operands (*UND* and *ABS* sections) for `&'
util/crc32c_ppc_asm.S:109: Error: invalid operands (*UND* and *ABS* sections) for `&'
[...]
util/crc32c_ppc_asm.S:88: Error: unsupported relocation against v20
util/crc32c_ppc_asm.S:89: Error: unsupported relocation against v21
[...]
util/crc32c_ppc_asm.S:745: Error: unsupported relocation against v20
Makefile:1812: recipe for target 'util/crc32c_ppc_asm.o' failed

### Steps to reproduce the behavior
Try to compile on a ppc64 machine.
Full build log: https://buildd.debian.org/status/fetch.php?pkg=rocksdb&arch=ppc64&ver=5.9.2-1&stamp=1514504777&raw=0

**Comment by adamretter** [comment]
See https://github.com/facebook/rocksdb/pull/3299
