### ISSUE TITLE
rocksdbjni 5.9.2 not published to Maven Central

### ISSUE THREAD

**Issue by ktnowak** [facebook/rocksdb#3316]
The latest version published to Maven Central is 5.8.7:
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22rocksdbjni%22

whereas latest release on github is 5.9.2 cut on 18th Dec:
https://github.com/facebook/rocksdb/releases/tag/v5.9.2

**Comment by adamretter** [comment]
We has a little trouble with the PPC64le and Windows builds. That is now solved and I have release v5.9.2 to Maven Central. The artifacts will appear on Maven Central within the next two hours (their sync window)
