### ISSUE TITLE
Rocksdb all API present in include/rocksdb

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3317]
rocksdb all API is present in include/rocksdb,is it right?

i have to write hawtjni for rocksdb,so i have to port all API present in include/rocksdb folder,is it right?

**Comment by siying** [comment]
That is correct.
I have no idea bout hawtjni , and not sure about whether all APIs there will be needed though. Most of our language ports only support a subset of RocksDB core functionalities.

**Comment by sagar0** [comment]
Closing, as this has been answered.
