### ISSUE TITLE
MemoryLeak&Potential Deadlock

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#3318]
https://github.com/facebook/rocksdb/blob/b5c99cc908a7e34fa65d588b2706c33000786935/utilities/transactions/pessimistic_transaction_db.cc#L115

It should be wrapped by a unique_ptr<>
Destructor is not called, so potential row-lock ( or key-lock）may be leaked

**Comment by maysamyabandeh** [comment]
::SetName will register the transaction object in transaction_ collection. Such transactions are alive and are not supposed to be destructed before commit/rollback.

**Comment by wolfkdy** [comment]
@maysamyabandeh  
thanks for your patience.
Suppose two transactions are processed by the iteration here.
```
for (auto it = rtrxs.begin(); it != rtrxs.end(); it++) {
.........
    s = real_trx->RebuildFromWriteBatch(recovered_trx->batch_);  
}
```
the first transaction got the key-lock from RebuildFromWriteBatch, while the second one fails to hold the   
lock of the same key.
It would be possible to happen. If so, TransactionDB::Open will fail..

This situation is ok during runtime( Opposite to startup time) since a runtime lock fail will be handled by upper-level or user-level.

**Comment by softirq** [comment]
pessimistic transaction a update the key and release the lock, but the data have not flushed to disk
	pessimistic transaction b update the same key, and write the redo log, not flushed to disk also

	then the mysqld crashed

	when the mysqld restart, in the recovery mode
	first, process The TransactionDB::Open, the two transaction will lock the same lock, the transaction a lock successed, but not release until the commit / rollback in the binlog recovery, but it too late, so the transaction b lock failed, then the mysqld recovery failed with the error "Operation timed out: Timeout waiting to lock key"

	then, process The MYSQL_BIN_LOG::open, after commit or abort, it will delete trx, and relealse lock

**Comment by softirq** [comment]
pessimistic transaction a update the key and release the lock, but the data have not flushed to disk
pessimistic transaction b update the same key, and write the redo log, not flushed to disk also

then the mysqld crashed

when the mysqld restart, in the recovery mode
first, process The TransactionDB::Open, the two transaction will lock the same lock, the transaction a lock successed, but not release until the commit / rollback in the binlog recovery, but it too late, so the transaction b lock failed, then the mysqld recovery failed with the error "Operation timed out: Timeout waiting to lock key"

then, process The MYSQL_BIN_LOG::open, after commit or abort, it will delete trx, and relealse lock

**Comment by maysamyabandeh** [comment]
A unit test to reproduce the problem would help.
