### ISSUE TITLE
RocksDB stop work

### ISSUE THREAD

**Issue by lwjyqjykn** [facebook/rocksdb#3319]
We use RocksdbJava for storing data, in the writing process, RocksDB stop work. 

After that, we discover the whole OS cann't do anything. By monitoring system disks, we find there is a disk full of write, show as follower picture, this phenomenon will continue several hours, and we have to wait it to stop.

Meanwhile, we discover there is a progress named `abrt-hook-ccpp` in the mattered server, but other normal servers havn't. In the `/var/spool/abrt` directory, there is a file named `last-ccpp`, the content in it is `/usr/java/jdk1.8.0_60/bin/java`. Sometimes there are other folder named `ccpp-${time}-${serilid}`, we find:
```
Process /usr/java/jdk1.8.0_60/bin/java was killed by signal 6 (SIGABRT)
```
 from the reason file in this folder. 
Do anyone meet this problem, how do you solve it, can anyone give me some suggestions. thank you very much!

**Comment by adamretter** [comment]
You first need to find out why Java was killed with `SIGABRT`. Your system should keep some core dump or logging information to help you diagnose that.

If a disk is full, I should imagine that would be a problem though...
