### ISSUE TITLE
OS is corrput for stoping rocksdb when compaction

### ISSUE THREAD

**Issue by lwjyqjykn** [facebook/rocksdb#3320]
We do a massive of read-modify-write with rokcsdbjava, after serveral hours, invoke another thread to stop the rocksdb instance without stoping read-modify-write progress, then OS is corrput. And there is a disk full of writing, we cann't do anything in this server for serveral hours. We check rocksdb LOG, only discover "Shutdown: canceling all background work", then some compaction log infos, but we don't find "Shutdown complete" info, is it means rocksdb doesn't stop successfully, and if this will trigger brush write and OS corrupt.

**Comment by gfosco** [comment]
If you're still having issues here, please ask for support on the group:  https://www.facebook.com/groups/rocksdb.dev
