### ISSUE TITLE
rocksdbjni coredump at rocksdb::WriteThread::EnterAsBatchGroupLeader()

### ISSUE THREAD

**Issue by xiaoweizw** [facebook/rocksdb#3326]
we have used rocksdbjni, but when process batch write, generator coredump due to abort signal. 
Has anyone meet this problem and how should this problem be solved? Thank you very much.
coredump detail information:
Program terminated with signal 6, Aborted.
(gdb) bt
#0  0x00002b17cbbf8625 in raise () from /lib64/libc.so.6
#1  0x00002b17cbbf9e05 in abort () from /lib64/libc.so.6
#2  0x00002b17cc8810b5 in os::abort(bool) ()
   from /usr/java/jdk1.8.0_121/jre/lib/amd64/server/libjvm.so
#3  0x00002b17cca23443 in VMError::report_and_die() ()
   from /usr/java/jdk1.8.0_121/jre/lib/amd64/server/libjvm.so
#4  0x00002b17cc8865bf in JVM_handle_linux_signal ()
   from /usr/java/jdk1.8.0_121/jre/lib/amd64/server/libjvm.so
#5  0x00002b17cc87cb03 in signalHandler(int, siginfo*, void*) ()
   from /usr/java/jdk1.8.0_121/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x00002b1806881a95 in rocksdb::WriteThread::EnterAsBatchGroupLeader(rocksdb::WriteThread::Writer*, rocksdb::WriteThread::Writer**, rocksdb::autovector<rocksdb::WriteThread::Writer*, 8ul>*) ()
   from /tmp/librocksdbjni6424814419910142735.so
#8  0x00002b18067de00f in rocksdb::DBImpl::WriteImpl(rocksdb::WriteOptions const&, rocksdb::WriteBatch*, rocksdb::WriteCallback*, unsigned long*, unsigned long, bool) ()
   from /tmp/librocksdbjni6424814419910142735.so
#9  0x00002b18067df9eb in rocksdb::DBImpl::Write(rocksdb::WriteOptions const&, rocksdb::WriteBatch*) () from /tmp/librocksdbjni6424814419910142735.so
#10 0x00002b1806758a3f in Java_org_rocksdb_RocksDB_write0 ()
   from /tmp/librocksdbjni6424814419910142735.so

**Comment by gfosco** [comment]
Sorry nobody had a quick answer for you, there's probably not enough information here to investigate.  If you still have issues here please ask on the group, thanks.  https://www.facebook.com/groups/rocksdb.dev
