### ISSUE TITLE
feature changes in rocksdb 2.5 fb to rocksdb 5.9.2

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3327]
how i can get information of features added in comparison of rocksdb 5.9.2 and rocksdb 2.5fb......version 2.5fb was present in 4 years back.....how i can list of features changes

**Comment by ajkr** [comment]
You can look at the `HISTORY.md` file.

**Comment by anuscool** [comment]
i saw the HISTORY.md file .....there are two types of changes 
1.public API changes and second is new feature added.

This new feature is internal API of rocksdb,is it right???

If i have to write JNI of java application then i should only take care of public API,is it right?

**Comment by sagar0** [comment]
Answered a related question here: https://github.com/facebook/rocksdb/issues/3328#issuecomment-355362551 . 

git should your authoritative source and best friend for finding all the changes that went in after version 2.5. We try to add most of the changes to HISTORY.md as well.
