### ISSUE TITLE
HISTORY.md file doubt

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3328]
i saw the HISTORY.md file .....there are two types of changes
1.public API changes and second is new feature added.

This new feature is internal API of rocksdb,is it right???

If i have to write JNI of java application then i should only take care of public API,is it right?

**Comment by sagar0** [comment]
Yes, you only need to deal with the public APIs that RocksDB exposes in the "include" directory for implementing a new JNI layer. 

For general inquiries I'd suggest you to use either our public Facebook group or the mailing list. We try to use github issues mainly for bugs (and feature requests). https://github.com/facebook/rocksdb/wiki#reporting-bugs-and-asking-for-help
