### ISSUE TITLE
file under /include/rocksdb/utilities

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3329]
the files under utilities....is this file is for production support or it is feature....if i have to write jni...then i also have to write jni for files in utilities also...

**Comment by siying** [comment]
Features under utilities are those are independent components. We organize it in a way that if everything under utilities/ is removed, the core RocksDB functionality still can be used.

Yes those directories contain many features used in production, but as a language binding, providing those extra features may not be absolutely necessary for users to use RocksDB.

**Comment by siying** [comment]
By the way, we encourage these discussions happen in RocksDB's facebook group or google group. We hope github Issues are a place to report bugs or track feature developments.
