### ISSUE TITLE
Missing doc on whether compactRange() is synchronous or asynchronous

### ISSUE THREAD

**Issue by bowenli86** [facebook/rocksdb#3335]
Missing documentation on explain whether compactRange() is synchronous or asynchronous. It's hard for users to figure this out themselves. I spend a couple hours on it, and still not sure about the answer.

**Comment by sagar0** [comment]
Thanks for posting your question in the RocksDB FB discussion group as well. Feel free to update the documentation once you figure out the correct behavior.

**Comment by ajkr** [comment]
it's synchronous, for the record
