### ISSUE TITLE
how to use this ROCKSDB_DEPRECATED_FUNC variable

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3353]
if i porting with rocksdb_5.9.2 i am getting ROCKSDB_DEPRECATED_FUNC types error....my hawt JNI is on old rocksdb 3.0.fb....if i have to port it i have to change that function in my hwat JNI

**Comment by ajkr** [comment]
I'd suggest making a post on our FB group with all the details of what you're trying to do. You can update it when you hit an obstacle. It'd be easier for us to help that way. It's hard to keep track when there's separate issues for every question/obstacle you encounter.
