### ISSUE TITLE
windows 10, vs 2017: error C2220: warning treated as error - no 'object' file generated

### ISSUE THREAD

**Issue by egor-agafonov** [facebook/rocksdb#3367]
Hi, I followed installation instructions from CMakeLists.txt:
- installed GFLAGS, SNAPPY, LZ4 and ZLIB
- edited file thirdparty.inc accordingly 
cmake -G "Visual Studio 15 Win64" -DWITH_GFLAGS=1 -DWITH_SNAPPY=1 -DWITH_LZ4=1 -DWITH_ZLIB=1 ..
msbuild rocksdb.sln /p:Configuration=Release
Got problem: 
....\util\compression.h(61): error C2220: warning treated as error - no 'object' file generated [...\build\rocksdb.vcxproj]

Can anybody help me please?

**Comment by xuy98** [comment]
You need to edit compression.h to fix unreachable statements by adding #else.

**Comment by gfosco** [comment]
I'll put together a PR to address what xuy98 mentioned..

**Comment by egor-agafonov** [comment]
That is what I did (updated compression.h). Thank you guys.

**Comment by gfosco** [comment]
Should be fixed since #3389 landed.
