### ISSUE TITLE
Db open and close Api has backward compalibilty compare with rocksdb 5.9.2 and rocksdb3.0

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3368]
An java application made with rocksdb version 3.0.fb will work correctly with rocksdb 5.9.2.
Data base open and cloase is not working

**Comment by ajkr** [comment]
I'd suggest making a post on our FB group with all the details of what you're trying to do. You can update it when you hit an obstacle. It'd be easier for us to help that way. It's hard to keep track when there's separate issues for every question/obstacle you encounter.
