### ISSUE TITLE
Broken CMakeLists.txt when rocksb is used as a submodule

### ISSUE THREAD

**Issue by vogel76** [facebook/rocksdb#3370]
If your RocksDB is included in bigger project structure (as a submodule) and its CMakeLists.txt is included in parent one, few problem appears:
1.  `CMAKE_MODULE_PATH` append statement refers incorrectly to `CMAKE_SOURCE_DIR` where it should use `CMAKE_CURRENT_LIST_DIR` (project root dir is different)
1. Generate test executable target names shall be prefixed with project names to avoid conflicts against names already existing in parent tree.

**Comment by vogel76** [comment]
@yiwu-arbug Even this issue is closed and PR 3372 merged to master branch, such changes did not appear in any release published after making this change.
Can you tell me when it could be included in release ?

**Comment by miasantreble** [comment]
@vogel76 this commit will be included in release 5.12
