### ISSUE TITLE
The ordinal 43 could not be located in the dynamic link library Canibet.dll

### ISSUE THREAD

**Issue by xuy98** [facebook/rocksdb#3388]
I was able to built 64bit Windows RocksDB and tried to run test on Windows 7 Enterprise 64bit SP1 (according Windows Update it's up-to-date)

### Expected behavior
It should run on Windows 7 64bit.

### Actual behavior
Ran into error "The ordinal 43 could not be located in the dynamic link library Canibet.dll"

### Steps to reproduce the behavior
Just run any test in RocksDB.

Here is the version of Cabinet.dll on my system: 6.1.7601.17514

Ran dumpbin on Cabinet.dll:

         4    0 000057F2 DeleteExtractedFiles
         2    1 00005188 DllGetVersion
         3    2 00005741 Extract
        11    3 00008CD4 FCIAddFile
        10    4 00008E91 FCICreate
        14    5 00008E46 FCIDestroy
        13    6 00008DB8 FCIFlushCabinet
        12    7 00008E16 FCIFlushFolder
        22    8 00001849 FDICopy
        20    9 00001C3F FDICreate
        23    A 00001693 FDIDestroy
        21    B 000059BD FDIIsCabinet
        24    C 00005A60 FDITruncateCabinet
         1    D 000046D5 GetDllVersion

No 43. What's function 43?

Where can I get Cabinet.dll used by RocksDB?

**Comment by adamretter** [comment]
I am no Windows expert. Did you run and test on the same machine?

At a guess I would suspect two different versions of cabinet.dll, one that was used at compile/link time and the other at runtime

**Comment by xuy98** [comment]
I built/tested on the same machine with Windows 7. Apparently VC2015 compiler links 43 function Decompress but Windows 7's cabinet.dll does not have the function. I tried to update Windows 7 but cabinet.dll is not updated with function Decompress. Maybe it's not supported on Windows 7.

**Comment by Nashatyrev** [comment]
@xuy98, got the similar problem except 'Entry 33' 
Did you find the reason?

**Comment by Nashatyrev** [comment]
Had the same issue. 
It seems the problem happens with `-DXPRESS=1` option. As far as I understood XPRESS Win API supported starting from Win8 only, so on Win7 we got DLL linkage error.
So I just built the library with `-DXPRESS=0`
