### ISSUE TITLE
library loading error with rocksdb5.9.2

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3393]
i am using fusesource rocksdbjni which uses rocksdb library. it is working fine with rocksdb fb3.0 version but i am getting could not load library when i am using with rocksdb5.9.2.

i am compiling rocksdb with make static_lib command for both version which produces static library....is there any change of static library generation in both version.

```
TestSuite$1.warning Exception in constructor: testOpen (java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no rocksdbjni64-99-master-SNAPSHOT in java.library.path, no rocksdbjni-99-master-SNAPSHOT in java.library.path, no rocksdbjni in java.library.path, /tmp/librocksdbjni-64-99-master-SNAPSHOT-8396258567915380494.so: /tmp/librocksdbjni-64-99-master-SNAPSHOT-8396258567915380494.so: undefined symbol: _ZTIN7rocksdb6LoggerE]
	at org.fusesource.hawtjni.runtime.Library.doLoad(Library.java:187)
	at org.fusesource.hawtjni.runtime.Library.load(Library.java:143)
```

**Comment by anuscool** [comment]
This error is not coming when we compiled rocksdb static library in DEBUG_LEVEL=1 mode but in release mode i am getting error

**Comment by adamretter** [comment]
Please reopen if this is still an issue in version 6.19.3
