### ISSUE TITLE
FastoNoSQL review

### ISSUE THREAD

**Issue by topilski** [facebook/rocksdb#3394]
Hi RocksDB maintainers, can you review [RocksDB connection](https://github.com/fastogt/fastonosql/blob/master/src/core/db/rocksdb/db_connection.cpp)  in FastoNoSQL implementation, we have a lot of RocksDB users who using our solution.

**Comment by yiwu-arbug** [comment]
Hi @topilski. Unfortunately we don't have resource to do code review, but will be glad to help if you encounter any issue. And I'll close the issue since issues are not used for general discussion. Sorry!
