### ISSUE TITLE
DB::GetProperty() is not working

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3403]
String stats = db.getProperty("rocksdb.stats");
assertTrue(stats.contains("Compactions"));
what will be the output for this in stats,what should i check....it is not working in latest rocksdb5.9.2 but it is working on fb3.0

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
