### ISSUE TITLE
Clarify warning on `use_fsync`

### ISSUE THREAD

**Issue by bdarnell** [facebook/rocksdb#3410]
The `use_fsync` option has a vague warning:

https://github.com/facebook/rocksdb/blob/c7226428ddefb4679692b9d0992885a0ea92aded/include/rocksdb/options.h#L409-L416

The ext3 filesystem is old and obsolete at this point, but what filesystems are "like ext3" in this respect? Is it possible to give more clarity about when this option is appropriate?

I've been doing some research here in https://github.com/cockroachdb/cockroach/issues/16412#issuecomment-360583416, and my conclusion is that when this comment was written (2012), both ext3 and ext4 had similar bugs and could lose data if `fdatasync` were used instead of `fsync`. These bugs were fixed in kernel versions 3.6 and 3.7 respectively. 

What are the current recommendations for using this flag? I don't think it's necessary to single out ext3 since ext4 has also had bugs in `fdatasync`. However, as far as I know the bugs have been fixed for a long time so there's no real reason to use this option in any modern environment.

**Comment by siying** [comment]
Sure feel free to send a PR to remove this suggestion, or modify it to whatever you feel up-to-date.
