### ISSUE TITLE
Github autodect thinks rocksdb is licensed under GPLv2

### ISSUE THREAD

**Issue by mratsim** [facebook/rocksdb#3417]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Github License detection says Apache

### Actual behavior
Github License detection says GPLv2

### Steps to reproduce the behavior
![2018-01-26_09-38-59](https://user-images.githubusercontent.com/22738317/35431499-fcfe639c-027c-11e8-81be-ec32abfd7b04.png)

**Comment by adamretter** [comment]
@mratsim RocksDB is dual licensed under both GPLv2 and Apache 2.0 licenses.

@siying I think it might make sense to rename `COPYING` to `LICENSE.Gpl2` and add a short but explicit note to `README.md`.

**Comment by siying** [comment]
CC @gfosco I assume we need to ask legal team for this?

**Comment by gfosco** [comment]
Legal made a good point, renaming COPYING would require updating every code file header, since they reference it.  Their suggestion was to explicitly discuss the licensing in README:

```
What we can do is make a note in the README under a new ##License header or similar, and state the following (from our header): "RocksDB is dual-licensed under both the GPLv2 (found in the COPYING file in the root directory) and Apache 2.0 License (found in the LICENSE.Apache file in the root directory). You may select, at your option, one of the above-listed licenses."
```

Any issues with this approach?  I can send in a PR..

**Comment by siying** [comment]
@gfosco any idea how we can avoid github to identify the project as GPL-v2?

**Comment by gfosco** [comment]
I sent a support request to GitHub, will update when they respond.

**Comment by gfosco** [comment]
Response from GitHub:

We use the open source Licensee Ruby gem to detect licenses in a repository. Unfortunately, it's not able to elegantly handle multiple license files within a repository. In the case of your facebook/rocksdb repository I see three different licensing files, any one of which may be detected: COPYING, LICENSE.Apache and LICENSE.leveldb.

https://github.com/benbalter/licensee

Further information about what files Licensee looks at and how it detects licenses can be found in that repository here:

https://github.com/benbalter/licensee/blob/master/docs/what-we-look-at.md

In cases where your code uses multiple licenses our recommendation is to include a single LICENSE file which contains the license that covers the majority of your code, then document all of your licenses used in your README file.

I'll also forward a request that we better handle multiple licenses over to our team for consideration.

**Comment by gfosco** [comment]
The best we can do right now is update the readme, and I've submitted a PR #3541 to do so.
