### ISSUE TITLE
how to compile rocksdb statically with snappy i am getting error

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3429]
i want to link rocksdb binary with snappy.

using cmake .. -DWITH_SNAPPY=1
         make

i have already compiled snappy seprately

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
