### ISSUE TITLE
Memory usage is too high

### ISSUE THREAD

**Issue by SunguckLee** [facebook/rocksdb#3437]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
I have expected memory usage of RocksDB as (block_cache_size + a)

### Actual behavior
But actual memory usage is 95%(including mongodb + rocksdb) of total physical memory.
```
$ free -m -t
              total        used        free      shared  buff/cache   available
Mem:          64019       62238         184          57        1596        1331
Swap:         10239         110       10129
Total:        74259       62349       10313
```

### Steps to reproduce the behavior
I have not reproduce this issue with test environments.
My product evironment MongoDB+RocksDB has
```
  - Only one database and this db has 84 collections.
  - 100 ~ 300 SELECT(find)/sec, 200 INSERT/sec
  - cacheSizeGB: 30
  - No bloom filter (cache_index_and_filter_blocks=false)
```

According to the db.serverSatus().rocksdb metrics, block cache usage is looks good, but table-readers-mem usage is high.
```
        "estimate-table-readers-mem" : "31GB",
        "block-cache-usage" : "27GB",
```

[memory-usage-serverstatus.txt](https://github.com/facebook/rocksdb/files/1676150/memory-usage-serverstatus.txt)

From the source code, "rocksdb.estimate-table-readers-mem" is "estimated memory used for reading SST tables, excluding memory used in block cache (e.g., filter and index blocks)".
We are not enabled bloom filter, so this 31GB memory space is used for index block. 
1) Is that right ?
2) And index block cache is not included "block-cache-usage" ?
3) Is there any way I can strain this index block cache usage ?

Regards,
Matt.

**Comment by maysamyabandeh** [comment]
This seems more like a request for production support than a bug report. For such cases please use the user group where you can benefit from the community's help. When you do that it would be useful to also share your option file, which type of index you are using, and whether you are storing them in the block cache (cache_index_and_filter_blocks=1).

**Comment by SunguckLee** [comment]
Sorry for 
>> This seems more like a request for production support than a bug report.

I have should read RocksDB options first in detail. I have thought  cache_index_and_filter_blocks=false will prevent using bloom filter.

Anyway, this is OPTIONS file of RocksDB.
[RocksDB-OPTIONS.txt](https://github.com/facebook/rocksdb/files/1680596/RocksDB-OPTIONS.txt)

**Comment by SunguckLee** [comment]
@maysamyabandeh 

I have tried to apply "cache_index_and_filter_blocks=false" to MongoDB + RocksDB.
But looks like different way to set this Table-level option from DB or CF options.


If I set cache_index_and_filter_blocks option in mongod.conf, MongoDB abort for "Invalid argument: Can't parse option cache_index_and_filter_blocks".

-- mongod.conf ------------------
...

storage:
    dbPath: /data/mongodb

    engine: rocksdb
    rocksdb:
        cacheSizeGB: 30
        compression: lz4
        maxWriteMBPerSec : 1024
        configString: "cache_index_and_filter_blocks=1"
---------------------------------------

RocksDB option is departed three level (DB, CF, Table).
But RocksDB options parser method only take care DB and CF not Table level.
(https://github.com/facebook/rocksdb/blob/master/options/options_helper.cc#L1200)

So if I set table level option on "storage.rocksdb.configString" then RocksDB always complain "unknown option".

-- mongod.log ---------------------
...
2018-02-01T18:49:31.208+0900 I STORAGE  [main] [RocksDB] Engine custom option: cache_index_and_filter_blocks=1;max_background_jobs=12;max_background_compactions=10;target_file_size_base=134217728;write_buffer_size=134217728;level0_file_num_compaction_trigger=3;level0_slowdown_writes_trigger=10
...
2018-02-01T18:49:31.264+0900 I STORAGE  [initandlisten] Invalid rocksdbConfigString "cache_index_and_filter_blocks=1;max_background_jobs=12;max_background_compactions=10;target_file_size_base=134217728;write_buffer_size=134217728;level0_file_num_compaction_trigger=3;level0_slowdown_writes_trigger=10"
2018-02-01T18:49:31.264+0900 I -        [initandlisten] Invariant failure: s resulted in status InternalError: Invalid argument: Can't parse option cache_index_and_filter_blocks at src/mongo/db/storage/rocks/src/rocks_engine.cpp 610
...
---------------------------------------


Anyway to change table-level option of RocksDB ?

Thanks in advance.

**Comment by gfosco** [comment]
Sounds like you might have found your answer.  If not please ask on the group, thanks!  https://www.facebook.com/groups/rocksdb.dev
