### ISSUE TITLE
[Minor] Bug in Regular Expression in Makefile

### ISSUE THREAD

**Issue by rbrasga** [facebook/rocksdb#3446]
At line: https://github.com/facebook/rocksdb/blob/master/Makefile#L171
--
missing_make_config_paths := $(shell				\
	grep "\/\S*" -o $(CURDIR)/make_config.mk | 		\
	while read path;					\
		do [ -e $$path ] || echo $$path; 		\
	done | sort | uniq)
--
The grep regex is not correct. It is ignoring the "." in front of a path. Example: "./path/to/file"

### Expected behavior
No warnings (or at least display the appropriate path)

### Actual behavior
Makefile:183: Warning: /include dont exist
Makefile:183: Warning: /third-party/gtest-1.7.0/fused-src dont exist

### Steps to reproduce the behavior
On linux: `make commit_prereq`

Fix:
Instead grep for everything after, but not including "-I"

**Comment by rbrasga** [comment]
--
missing_make_config_paths := $(shell	
grep "**./\S*\|**/\S*" -o $(CURDIR)/make_config.mk | 
while read path;	
do [ -e $$path ] || echo $$path; 
done | sort | uniq)
--

This minor code change seems to have resolved the problem I was facing.

**Comment by siying** [comment]
Thank you for reporting it. If you are able to sign CLA, I encourage you to send a PR.

**Comment by rbrasga** [comment]
@siying The CLA is working its way through our legal department since last week. I'll send a PR as soon it's done.

**Comment by siying** [comment]
@rbrasga are you still working on this?

**Comment by rbrasga** [comment]
The CLA is still working its way through the legal department. Toshiba is new to open source. Sorry for the delay.

**Comment by sagar0** [comment]
@rbrasga Checking in ... Were you able to get through your legal to sign the CLA?

**Comment by rbrasga** [comment]
@sagar0 Amazingly, the CLA is still in progress. However, I will submit a pull request later today or tomorrow from my personal account. Thank you for following up!

**Comment by sagar0** [comment]
Thanks for the reminder. I'll merge #3446.

**Comment by sagar0** [comment]
Merged #4682. Thanks for the contribution.
