### ISSUE TITLE
DB threads are joined not correctly: they are terminating after db deletion in a undeterminated moment.

### ISSUE THREAD

**Issue by publicocean0** [facebook/rocksdb#3453]
when i execute 
 delete db  

i m expecting all the threads inside generated by rocksdb are joined so in the following instruction all threads are terminated.
I verified PosixEnv destructor (where are joined the threads) is called after delete db.

I searched also if there is a way eventually for setting the behaviour, but i didnt find. 

To use multiple pthread_join is undefined so to use in advance in my code pthread_join could give side effects  .

**Comment by siying** [comment]
A DB is not supposed to own any thread in the Env. The thread pool in Env will always live after DB is destroyed. When DB is destroyed, it does wait for all the jobs it has scheduled to finish. If you see any job not yet finished, it is a bug. However, those threads themselves are not terminated.

**Comment by siying** [comment]
Do you have further comment? If not I'm going to close the issue.

**Comment by publicocean0** [comment]
Sorry it is not clear. 
"The thread pool in Env will always live after DB is destroyed.". Do you mean Env and its thread pool is a object living in indipendent way? In thi case how to join the env thread pool  for waiting the thread pool termination?
 I my case i added a posix listener  in c++ when rocksdb thread is terminating. 
When execute db.delete , i would expect thread is terminated in this moment instead thread is terminating in a following moment. 
My code works so: the first time rocks db use a thread for calling a merge operator , i attach to this thread a posix thread local with a destructor (called when thread is terminated).In this way the JVM Thread Environment is set and i can skip the expensive JVM attachment /detachment process for every call execution. The benchmark tell this way is in significant way better.
It works correctly for jvm threads ( destructor is called correctly). Before VM is exiting call delete db ... so i would expect the JVM Env is detached , instead the destructor is called  after JVM is alread existed so there is a memory leak. Pratically i need a way for executing the Thread.join for rocksdb threads pool when i close the db(or with a additional routine added just after it) .

**Comment by siying** [comment]
@publicocean0 There is a way to turn off all those threads: after your DB is destroyed, you can call `Env::Default()->SetBackgroundThreads(0, LOW)` and also for `HIGH` and `BOTTON`. There are equivalent calls in Java too. However, although all the threads are notified to finish so they should terminate soon, I didn't find a way to join all those threads.

If you are interested, you can implement a function in Env to do what you want to do.

**Comment by publicocean0** [comment]
Ok I think I will add a function for joining all threads in rocksdb in c++. The priority is not hight because i have a Montaign of code to produce but I will do . I will add it in the pull request  already  shared with you
