### ISSUE TITLE
getting error in Get API of column family when using rocksdbjni

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3458]
﻿
java: db/db_impl.cc:948: rocksdb::Status rocksdb::DBImpl::GetImpl(const rocksdb::ReadOptions&, rocksdb::ColumnFamilyHandle*, const rocksdb::Slice&, rocksdb::PinnableSlice*, bool*, rocksdb::ReadCallback*, bool*): Assertion `pinnable_val != nullptr' failed. Aborted (core dumped)

**Comment by siying** [comment]
Can you find the whole call stack? (for example gdb to the core cump). The context is too limited to figure out what's going on there.

**Comment by sagar0** [comment]
Closing as there's no new information provided.
