### ISSUE TITLE
Getting UnSatisfiedLinkError on CompactionOptionsUniversal Java JNI 

### ISSUE THREAD

**Issue by bajrachar** [facebook/rocksdb#3468]
#error {
 :cause org.rocksdb.CompactionOptionsUniversal.newCompactionOptionsUniversal()J
 :via
 [{:type java.lang.UnsatisfiedLinkError
   :message org.rocksdb.CompactionOptionsUniversal.newCompactionOptionsUniversal()J
   :at [org.rocksdb.CompactionOptionsUniversal newCompactionOptionsUniversal CompactionOptionsUniversal.java -2]}]

**Comment by miasantreble** [comment]
@bajrachar which version of rocksdbjni are you using?

**Comment by bajrachar** [comment]
@miasantreble I am using 5.9.2 and I also tried this in 5.8.7. I am using this on linux x86 64 and java 1.8.
I am basically trying to implement the "in-memory prefix database" use case in the tuning guide - https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide

**Comment by miasantreble** [comment]
@sagar0 mind take a quick look?

**Comment by sagar0** [comment]
@bajrachar are you still seeing this issue with the latest versions of RocksDB?

**Comment by adamretter** [comment]
I am closing this as there has been no update from @bajrachar

@bajrachar If you still have the issue, please reopen and if you could provide the minimum code to reproduce please.
