### ISSUE TITLE
how to write hawtjni for std::shared_ptr and std::vector

### ISSUE THREAD

**Issue by anuscool** [facebook/rocksdb#3474]
how we can write hawtjni for std::shared_ptr and std::vector

**Comment by siying** [comment]
Now we only use github issues to track RocksDB bugs or feature development. We hope other discussions to happen in RocksDB google group https://groups.google.com/forum/#!forum/rocksdb or facebook group https://www.facebook.com/groups/rocksdb.dev/ . Please ask the question there.

By the way, I don't understand your question.
