### ISSUE TITLE
Writing values larger than 4GB creates memtables corruption

### ISSUE THREAD

**Issue by oranagra** [facebook/rocksdb#3480]
### Expected behavior
Be able to store and read back values of any size.

### Actual behavior
Error: Corruption: unknown WriteBatch tag

### Steps to reproduce the behavior
Put() any value larger than 4GB into RocksDB will immediately expose the problem.

## Relevant Code
```
inline void PutLengthPrefixedSlice(std::string* dst, const Slice& value) {
  PutVarint32(dst, static_cast<uint32_t>(value.size()));
  dst->append(value.data(), value.size());
}
```
Slice.size() returns size_t (64 bit on most systems today), and we serialize only 32 bit from it.
then we store the entire (full size) value, which corrupts the memtable.

I assume the fix should be to add kTypeValue64 tag in order to store any values larger than 4GB.
But i fear there are more such problems hiding inside RocksDB. Since today these are stepped at the very entrance to the database, maybe many other places that handle values down the road have this issue too.

**Comment by siying** [comment]
Supporting value larger than 4GB is more complicated than that. In SST file format, we are using fixed uint32 to represent offset inside a data block, and this can't be easily change. Unless you implement a new SST file format (or data block format), you can't get more than 4GB of data into RocksDB. Problems in write batch and memtable are fixable, but this is not easily fixable.

We have a new upcoming feature of blobDB. We can try to support it there. @yiwu-arbug does BlobDB supports blob larger than 4GB?

**Comment by oranagra** [comment]
Ok. Thanks. 
I would suggest to at least add a proper error response, rather than corruption of the memtables.

**Comment by siying** [comment]
@oranagra sure we can do that.

**Comment by siying** [comment]
@oranagra actually, I rethink about it and suspect that a value size larger than uint32_t may be OK after change from varint32 to varint64 in write batch and memtable (varint32 is technically a varint64 so we son't have compatibility issue, but the implementation of varint64 is less efficient). So this something we may fix if we invest time. Let me add the sanity check for now. If you are interested in helping us add the support, we can help you give it a try.

**Comment by oranagra** [comment]
@siying are you saying that's there are no similar issues in the SST files?
If there are, then there's no point in fixing the memtables corruption. It's better to give an error right away. 

If there aren't too many issues with values larger than 4gb, then I think for memtables we can add a new tag (kTypeValue64) and use varint64 only when the value is big.

I'll be happy to try fixing it and PR, but please try to give me some hints of the problematic areas that need to be fixed since I'm not very experienced in rocksdb internal design.

**Comment by siying** [comment]
@oranagra my point is that, we don't even need to add a new tag anywhere. Just use varint64 to encode value size, as long as we can improve the performacne of varint64 to be similar to varint32_t for small values.

**Comment by oranagra** [comment]
Ok, and you're saying that it'll fix the SST files and other problems?? 

PS, we can use the MSB to indicate there's one more byte to read. In many cases it can even encode small values more efficiently than today.

**Comment by siying** [comment]
@oranagra varint32 uses 5 bytes, and we only use 4 bits in the last byte, so we don't need to do any format change, unless I made any mistake in my calculation.

Correct: SST file format has a very similar problem: https://github.com/facebook/rocksdb/blob/v5.10.2/table/block_builder.cc#L119-L122

So if you want to try, you'll need to change in a lot of places.

I'm adding a PR for a sanity check though.

**Comment by siying** [comment]
I'm closing the PR, as I added the sanity check. Feel free to explore what it takes to make RocksDB support larger value. If you send a PR, we'll be happy to review it.
