### ISSUE TITLE
GET works incorrectly

### ISSUE THREAD

**Issue by toktarev** [facebook/rocksdb#3482]
Version of Rocks 5.6.1

I run the following code:

```
#include <chrono>
#include <cstdio>
#include <string>
#include <cstdlib>
#include <iostream>
#include <inttypes.h>
#include "rocksdb/db.h"
#include <include/rocksdb/table.h>

using namespace std;
using namespace rocksdb;
using namespace std::chrono;

std::string kDBPath = "/repos/rocksdata";

#include <include/rocksdb/filter_policy.h>
#include <include/rocksdb/slice_transform.h>
#include <table/block_based_table_factory.h>

bool isBigEndian() {
    static unsigned long x(1);
    static bool result(reinterpret_cast<unsigned char *>(&x)[0] == 0);
    return result;
}

template<typename T>
T toBigEndian(T u) {
    if (isBigEndian()) {
        return u;
    }

    static_assert(CHAR_BIT == 8, "CHAR_BIT != 8");

    union {
        T u;
        unsigned char u8[sizeof(T)];
    } source, dest;

    source.u = u;

    for (size_t k = 0; k < sizeof(T); k++)
        dest.u8[k] = source.u8[sizeof(T) - k - 1];

    return dest.u;
}

int main() {
    system("exec rm -r /repos/rocksdata/*");

    DB *db;
    Options options;
    options.num_levels = 2;
    options.create_if_missing = true;
    options.compression = CompressionType::kSnappyCompression;
    Status s = DB::Open(options, kDBPath, &db);

    if (!s.ok()) {
        cout << s.ToString();
        exit(0);
    }

    assert(s.ok());

    ColumnFamilyHandle *cf;
    ColumnFamilyOptions cfo;

    rocksdb::BlockBasedTableOptions table_options{};
    table_options.block_cache = NewLRUCache(
            1024 * 1024 * 1024,
            16,
            true,
            0.1
    );
    table_options.cache_index_and_filter_blocks = true;
    table_options.cache_index_and_filter_blocks_with_high_priority=true;
    table_options.filter_policy.reset(NewBloomFilterPolicy(64));
    cfo.table_factory.reset(new rocksdb::BlockBasedTableFactory(table_options));

    s = db->CreateColumnFamily(cfo, "new_cf", &cf);
    u_int64_t max = 1000000;
    WriteBatch batch;

    u_int64_t *buffer = new u_int64_t[4];
    char *pointer = reinterpret_cast<char *>(buffer);

    u_int64_t *aReadBuffer = new u_int64_t[4];
    char *aReadPointer = reinterpret_cast<char *>(aReadBuffer);

    for (uint64_t i = 0; i < 100000000; i++) {
        *(buffer) = toBigEndian(i);
        *(buffer + 1) = toBigEndian(i + 1);
        *(buffer + 2) = toBigEndian(i + 2);
        *(buffer + 3) = toBigEndian(i + 3);

        Slice key(pointer, 32);
        Slice value(reinterpret_cast<char *>(&max), 8);
        batch.Put(cf, key, value);

        if ((i % 1000) == 0) {
            WriteOptions w;
            s = db->Write(w, &batch);
            batch.Clear();
        }

        if ((i % 1000000) == 0) {
            uint64_t k = i / 2;
            *(aReadBuffer) = toBigEndian(k);
            *(aReadBuffer + 1) = toBigEndian(k + 1);
            *(aReadBuffer + 2) = toBigEndian(k + 2);
            *(aReadBuffer + 3) = toBigEndian(k + 3);

            std::string v{};
            ReadOptions aReadOptions{};
            Slice aReadKey(aReadPointer, 32);

            uint64_t start = (uint64_t) std::chrono::duration_cast<std::chrono::nanoseconds>(
                    system_clock::now().time_since_epoch()).count();
            Status status = db->Get(aReadOptions, cf, aReadKey, &v);
            uint64_t end = (uint64_t) std::chrono::duration_cast<std::chrono::nanoseconds>(
                    system_clock::now().time_since_epoch()).count();

            u_int64_t delta = end - start;

            printf("ToString = %s", status.ToString().c_str());
            printf("  %" PRIu64, i);
            printf("  %" PRIu64 "\n", delta);
        }
    }

    db->DestroyColumnFamilyHandle(cf);
    delete db;

    system("exec rm -r /repos/rocksdata/*");
    return 0;
}
```

### Expected behavior
All Get return OK

### Actual behavior

ToString = OK  0  1326000
ToString = OK  1000000  47000
ToString = OK  2000000  35000
ToString = OK  3000000  32000
ToString = NotFound:   4000000  1881000
ToString = NotFound:   5000000  69000
ToString = NotFound:   6000000  51000
ToString = NotFound:   7000000  50000
ToString = NotFound:   8000000  51000
ToString = NotFound:   9000000  49000
ToString = NotFound:   10000000  50000
ToString = NotFound:   11000000  844000

### Steps to reproduce the behavior

Just run C++ script I've attached.
P.S. if I remove 
`    table_options.cache_index_and_filter_blocks = true;`
All GET's return OK.

**Comment by toktarev** [comment]
Removing table_options.cache_index_and_filter_blocks = true;
everything works but I see performance degradation:

ToString = OK  0  33000
ToString = OK  1000000  28000
ToString = OK  2000000  27000
ToString = OK  3000000  87000
ToString = OK  4000000  78000
ToString = OK  5000000  73000
ToString = OK  6000000  74000
ToString = OK  7000000  88000
ToString = OK  8000000  102000
ToString = OK  9000000  193000
ToString = OK  10000000  203000

**Comment by toktarev** [comment]
If I use
```
            if (db->KeyMayExist(aReadOptions, cf, aReadKey, &v)) {
                status = db->Get(aReadOptions, cf, aReadKey, &v);
            } else {
                status = Status::NotFound();
            }
```

I see
ToString = OK  0  37000
ToString = OK  1000000  50000
ToString = OK  2000000  43000
ToString = OK  3000000  1895000
ToString = OK  4000000  87000
ToString = OK  5000000  97000
ToString = OK  6000000  93000
ToString = OK  7000000  249000
ToString = OK  8000000  234000
ToString = OK  9000000  110000
ToString = OK  10000000  102000
ToString = OK  11000000  270000

Seems that KeyMayExist doesn't help with performance degradation.

**Comment by siying** [comment]
Here is the reason you saw this failure: you used NewLRUCache() with argument `strict_capacity_limit`=true. Flush failed and froze the DB. If you print out the status returned in `s = db->Write(w, &batch);`, after a while, after inserting several keys, you'll see "Result incomplete: Insert failed due to LRU cache being full.", which indicates that the DB is freed because of error in flush.

The reason that block cache failed to be inserted is following: you specified a 1GB block cache with `num_shard_bits=16`. It means that block cache is sharded in 2^16 ways, which is about 64K. Each shard only gets 16KB. The index block of any SST file will be larger than that. When the program tries to insert the block to the block cache, block cache forbid it as it's over-sized, which causes the whole DB to be read-only state and no further key is inserted anymore.
