### ISSUE TITLE
fpm check false positive on CentOS

### ISSUE THREAD

**Issue by xkszltl** [facebook/rocksdb#3489]
### Expected behavior

`build_tools/make_package.sh`
Failed to found fpm from yum.

### Actual behavior

Found "fpm" from `fpm2` and `fpm2-debuginfo` because of grep.
Should be replaced with something like `grep $fpm^`.

### Steps to reproduce the behavior

On CentOS 7:

```
yum install epel-release
yum install fpm2
make -j$(nproc) {static,shared}_lib
make -j$(nproc) package
```

**Comment by siying** [comment]
@gfosco are you interested in taking a look at this?

**Comment by gfosco** [comment]
I checked the script and didn't see anywhere `yum` or `grep` would be used in relation to `fpm`, so I set up a Centos 7.4 box to test.  I get different output, but in the same vein:

```
[+] using rocksdb version: 5.10
Building native extensions.  This could take a while...
ERROR:  Error installing fpm:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h


Gem files will remain installed in /usr/local/share/gems/gems/ffi-1.9.21 for inspection.
Results logged to /usr/local/share/gems/gems/ffi-1.9.21/ext/ffi_c/gem_make.out
make: *** [package] Error 1
```

After `yum install ruby-devel` it fails with the following:

```
Running autoreconf for libffi
/usr/local/share/gems/gems/ffi-1.9.21/ext/ffi_c/libffi/autogen.sh: line 2: exec: autoreconf: not found
```

After `yum install autoconf automake` we fall through to:

```
configure.ac:41: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure:7636: error: possibly undefined macro: AC_PROG_LD
autoreconf: /usr/bin/autoconf failed with exit status: 1
```

After `yum install libtool` we're almost there:

```
Need executable 'rpmbuild' to convert dir to rpm {:level=>:error}
```

After `yum install rpm-build` the package completes successfully.

@xkszltl, can you try `yum install ruby-devel autoconf automake libtool rpm-build` and see if you have better luck?  We can update INSTALL.md with more recent info, I ran in to a few things in this process.

**Comment by xkszltl** [comment]
My fault.
I was searching for the line of error "fpm is already installed. skipping." and looked into package() instead of gem_install().

However, the weakly restricted grep can still be a problem in both functions, if someone has other package which name contains $1 as substring.
Highly recommend to be more specific.

**Comment by xkszltl** [comment]
And I also notice that `fpm` may not be found in certain workflow:

1. ssh to CentOS 7 machine using unprivileged user.
2. `sudo -i`
3. `echo $PATH` doesn't show `/usr/local/bin`

`/usr/local/bin` for `PATH` is hardcoded both `sshd` and `/bin/bash`.
So `ssh root@$IP` would work, but not ssh + sudo.

Maybe we should use `/usr/local/bin/fpm` instead of `fpm`

**Comment by xkszltl** [comment]
```
[root@CentOS ~]# cat /etc/ssh/sshd_config
#	$OpenBSD: sshd_config,v 1.100 2016/08/15 12:32:04 naddy Exp $

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

**# This sshd was compiled with PATH=/usr/local/bin:/usr/bin**

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

```

**Comment by gfosco** [comment]
All of the various package managers return their results differently.  `$package^` wouldn't work for `rpm`, as it returns `package-major-minor`, so you could do `package-`.  gem list returns `package (version)`, etc.. Depending on the output behavior seems also potentially problematic. Theoretically you're right, it could find a wrong package, but it doesn't sound like it has ever happened.  Any PRs will be reviewed and considered though, thanks.
