### ISSUE TITLE
win7 vs2015 x86 - rockdbs_basic_test crashes

### ISSUE THREAD

**Issue by xuy98** [facebook/rocksdb#3493]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

Built x86 RocksDB in VC2017 with Windows SDK 7.0. But the build failed on some tests, such as rockdb_basic_test, etc. All tests seem to be aborted when doing flush.

TEST_F(DBBasicTest, GetFromVersions) {
  do {
    CreateAndReopenWithCF({"pikachu"}, CurrentOptions());
    ASSERT_OK(Put(1, "foo", "v1"));
    _**ASSERT_OK(Flush(1));**_			// Crash 
    ASSERT_EQ("v1", Get(1, "foo"));
    ASSERT_EQ("NOT_FOUND", Get(0, "foo"));
  } while (ChangeOptions());
}

**Comment by gfosco** [comment]
duplicate, tracking #3494
