### ISSUE TITLE
win7 vs2015 x86 - rockdbs_basic_test crashes

### ISSUE THREAD

**Issue by xuy98** [facebook/rocksdb#3494]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

Built x86 RocksDB in VC2017 with Windows SDK 7.0. But the build failed on some tests, such as rockdb_basic_test, etc. All tests seem to be aborted when doing flush.

TEST_F(DBBasicTest, GetFromVersions) {
  do {
    CreateAndReopenWithCF({"pikachu"}, CurrentOptions());
    ASSERT_OK(Put(1, "foo", "v1"));
    _**ASSERT_OK(Flush(1));**_			// Crash 
    ASSERT_EQ("v1", Get(1, "foo"));
    ASSERT_EQ("NOT_FOUND", Get(0, "foo"));
  } while (ChangeOptions());
}

The test aborted in

        virtual bool stl_condition_variable_win7::wait_for(stl_critical_section_interface *lock, unsigned int timeout) override
        {
            return __crtSleepConditionVariableSRW(&m_condition_variable, static_cast<stl_critical_section_win7 *>(lock)->native_handle(), timeout, 0) != 0;
        }

I am not sure whether there was deadlock or not. But I noticed multiple threads in waiting. The program has exited code with code 3.

Here is the call stack:

>	msvcp140d.dll!Concurrency::details::stl_condition_variable_win7::wait_for(Concurrency::details::stl_critical_section_interface * lock, unsigned int timeout) Line 216	C++	Non-user code. Symbols loaded.
 	msvcp140d.dll!Concurrency::details::stl_condition_variable_win7::wait(Concurrency::details::stl_critical_section_interface * lock) Line 210	C++	Non-user code. Symbols loaded.
 	msvcp140d.dll!do_wait(_Cnd_internal_imp_t * cond, _Mtx_internal_imp_t * mtx, const xtime * target) Line 75	C++	Non-user code. Symbols loaded.
 	msvcp140d.dll!_Cnd_wait(_Cnd_internal_imp_t * cond, _Mtx_internal_imp_t * mtx) Line 105	C++	Non-user code. Symbols loaded.
 	db_basic_test.exe!std::_Cnd_waitX(_Cnd_internal_imp_t * _Cnd, _Mtx_internal_imp_t * _Mtx) Line 96	C++	Non-user code. Symbols loaded.
 	db_basic_test.exe!std::condition_variable::wait(std::unique_lock<std::mutex> & _Lck) Line 711	C++	Non-user code. Symbols loaded.
 	db_basic_test.exe!rocksdb::port::CondVar::Wait() Line 59	C++	Symbols loaded.
 	db_basic_test.exe!rocksdb::InstrumentedCondVar::WaitInternal() Line 61	C++	Symbols loaded.
 	db_basic_test.exe!rocksdb::InstrumentedCondVar::Wait() Line 54	C++	Symbols loaded.
 	db_basic_test.exe!rocksdb::DBImpl::WaitForFlushMemTable(rocksdb::ColumnFamilyData * cfd) Line 999	C++	Symbols loaded.
 	db_basic_test.exe!rocksdb::DBImpl::FlushMemTable(rocksdb::ColumnFamilyData * cfd, const rocksdb::FlushOptions & flush_options, bool writes_stopped) Line 979	C++	Symbols loaded.
 	db_basic_test.exe!rocksdb::DBImpl::Flush(const rocksdb::FlushOptions & flush_options, rocksdb::ColumnFamilyHandle * column_family) Line 813	C++	Symbols loaded.
 	db_basic_test.exe!rocksdb::DBTestBase::Flush(int cf) Line 624	C++	Symbols loaded.
 	db_basic_test.exe!rocksdb::DBBasicTest_GetFromVersions_Test::TestBody() Line 249	C++	Symbols loaded.
 	db_basic_test.exe!testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test,void>(testing::Test * object, void(testing::Test::*)() method, const char * location) Line 3809	C++	Symbols loaded.
 	db_basic_test.exe!testing::internal::HandleExceptionsInMethodIfSupported<testing::Test,void>(testing::Test * object, void(testing::Test::*)() method, const char * location) Line 3860	C++	Symbols loaded.
 	db_basic_test.exe!testing::Test::Run() Line 3896	C++	Symbols loaded.

**Comment by yuslepukhin** [comment]
Basic test changes are related to this: https://github.com/facebook/rocksdb/issues/3519 and this https://github.com/facebook/rocksdb/commit/d0f1b49ab600bdfb37e1226c03fed5ae4ab2da7b#diff-71a34e2e4e097b44064da7d3a2b68bd8R391

**Comment by yuslepukhin** [comment]
@xuy98 Do you still see the issue with the patch c287c098a4112d0b2577e205fd78d556885f43de?

**Comment by siying** [comment]
@yuslepukhin I assume that is a wrong copy&paste.

**Comment by yuslepukhin** [comment]
@siying You are probably correct. The issue has to do with x86.

**Comment by siying** [comment]
@yuslepukhin I meant that the patch you pasted https://github.com/facebook/rocksdb/commit/c287c098a4112d0b2577e205fd78d556885f43de was just a change in comment. I assume you pasted a wrong commit. I don't know anything about x86.

**Comment by miasantreble** [comment]
@xuy98 is this still an issue for you? 
If so can you please let us know the version of RocksDB you are using?
Otherwise this issue will be closed automatically
