### ISSUE TITLE
~DBImpl and ~Logger will potentially cause crash or data corruption

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#3519]
There is a couple of problems with the most recent Logger changes and one of them is big.

1)  With the introduction of CloseImpl() virtual method is implementing a template design pattern implying that the deriving class will supply the specifics of closing the file. Problem is this can not be called from the destructor because the derived class is destroyed first so you will be potentially calling into the destroyed portion. This will lead to a crash.

2) closed_ member is useless because no one has access to it nether the general public nor the derived classes. And because of 1) it is almost useless for the base class.

https://github.com/facebook/rocksdb/blob/ab446dc22d8c59534e56784b040afc3d91b86d04/env/env.cc#L80

@anand1976 @siying @gfosco

**Comment by yuslepukhin** [comment]
Just to follow up. If the design pattern is to be implemented properly then Close() should not be virtual.

**Comment by yuslepukhin** [comment]
The same issue is propagated to ~DBImpl() which calls Close() and that in turn calls CloseImpl() and both of them are virtual. If derived classes implement them the behavior is undefined.

https://github.com/facebook/rocksdb/blob/ab446dc22d8c59534e56784b040afc3d91b86d04/db/db_impl.cc#L407

**Comment by anand1976** [comment]
Thanks for catching this. Yeah, I think making Close() non-virtual and calling it from the derived class destructor is the way to go.

**Comment by yuslepukhin** [comment]
@anand1976 I think this requires further clarification

- Making Close() non-virtual is suggested as part of properly implementing a specific design pattern (template) so you can have only one customization point instead of two now. However, Close() should still invoke CloseImpl() to make customization possible.

- For this reason you can not call Close() from a __dtor. 

Just to make things clear, do not call anything virtual or anything that might invoke a virtual function from a __dtor.

**Comment by anand1976** [comment]
@yuslepukhin In this case, calling Close() from the dtor is for the sake of backward compatibility. We'd like to do an implicit Close() for compatibility, as well as allow an explicit Close() for those who want to get a return status. It looks like achieving both is difficult with this design pattern. Cc @siying

**Comment by yuslepukhin** [comment]
@anand1976 I agree with you. However, since the class is virtual, it dictates certain things that you can and can not do. There are elaborate ways to solve this. Those might be a little hard on readability and reviews. We do not want that. Here is what I would do for simplicity:

- Make Close non-virtual, protected CloseImpl() virtual
- Make closed_ protected and in ~Logger() assert on closed_
- Make the derived class __dtor make sure to close its handle if not already closed via a non-virtual inline helper. Implement CloseImpl() to forward to that no-virtual helper.
- Finally, go through all the derived classes and refactor them.

**Comment by yuslepukhin** [comment]
@anand1976 btw, I'd like to merge this: https://github.com/facebook/rocksdb/pull/3506

**Comment by siying** [comment]
@anand1976 My design pattern knowledge is not sufficient to follow all the discussions. I don't have any opinion on any of the change. DBImpl::~DBImpl() doesn't have to call a virtual Close(), right? We can create a non-virtual function in DBImpl so that both of DBImpl::Close() and DBImpl::~DBImpl() call it. Maybe I miss something but I don't see it break backward compatibility.

**Comment by siying** [comment]
@anand1976 another random idea: does declare DBImpl::Close() final work?

**Comment by yuslepukhin** [comment]
@siying I think we have a solution. Making Close() non-virtual requires no final.

**Comment by ajkr** [comment]
It doesn't seem that compatible though to require refactoring all derived classes. The assert in ~Logger seems to be the cause. Would it break your idea to get rid of it? After all, we know the destructor of the subclass has already run, so presumably they've done their cleanup in some form.

**Comment by yuslepukhin** [comment]
@ajkr I am fine with getting rid of assert and closed_. Refactoring is required due to the introduction of CloseImpl() pattern not due to assert() I proposed.

**Comment by ajkr** [comment]
Oh ok. We could also have CloseImpl have default implementation returning Status::NotSupported so users who haven't migrated yet will simply not be able to use Close. It should be possible to preserve compatibility this way, I think.

**Comment by anand1976** [comment]
Agree with most of the above comments. Getting rid of the assert will ensure backward compatibility for user defined extensions of Logger that have their own cleanup implementation. Its probably good to have CloseImpl() default implementation return Status::OK so callers of Close() remain agnostic of the underlying class.

**Comment by yuslepukhin** [comment]
@anand1976 Returning OK() does not seem to be a good idea for the default impl. This means after Close() returns the file is still open. On windows this will affect two things:
1) File metadata not flushed to disk. This affected log rotation in the past.
2) Neither the log file NOR the containing folder can be cleaned up.

Thus, if a person calls close, they need to implement it. It is for that reason I suggested refactoring those loggers that are present in the master branch.

**Comment by anand1976** [comment]
@ajkr @yuslepukhin I wanted to decouple callers of Close() from the implementors. But on second thoughts, I think the default CloseImpl() can return not supported and we can mandate that callers of Close() check for that and delete the Logger before assuming cleanup is done.

**Comment by yuslepukhin** [comment]
@anand1976 I am not sure I understand this thought and the purpose of CloseImpl() then. Mandating the callers the callers to check is messy and is simply not an acceptable API design. If you make CloseImpl() non-virtual you do not need it because you can never call the derived class code. Thus both Close() and CloseImpl() become useless and the best way of addressing this is simply revert the check in.

**Comment by anand1976** [comment]
@yuslepukhin Are you referring to DBImpl or Logger? The CloseImpl() in the former can be non-virtual because we don't expect (or want) any sub-class to override it. The CloseImpl() in Logger needs to be virtual since sub-classes need to provide the actual implementation. Most of the issues in this thread pertain to Logger. DBImpl is simpler and all we really need there is to override Close().

I didn't follow your first comment about the messiness of requiring callers to check the return status, which seems to contradict your original proposal of not returning OK() in the default impl. I have refactored the Loggers in the master branch. The purpose of the original check in was to provide a way for users to get the status of close/cleanup, rather than swallowing the error in the destructor. Why revert it back?

**Comment by yuslepukhin** [comment]
@anand1976 Thank you for the clarification. It makes sense now. So no need for reverting :)
With regards to the API. Checking for NotImplemented() is a little cumbersome although not unacceptable. However, we really want this check only until everyone migrates and properly overrides CloseImpl(). However , those checks will stay there for good. Since you are taking care to refactor the code there are two options available to make sure the users migrate and are not required to check of NotImplemented.

- One thought was to assert on closed_ which would make sure that the file was closed either by Close() or at the destruction time. 
- The other is to make CloseImpl() pure virtual. This would fail at compile time if someone has a custom logger (we do)

@ajkr  may disagree with me but I feel both of these contribute to the correctness tremendously at a minor expense because they detect the discrepancy either at test time or compile time. Since you are refactoring and others when refreshing from the mater will likely build and run tests I feel it is not too much to break here for a good purpose.
Said that, I am OK if you leave things as they are since for my egotistical purposes it is fine either way. I will make needed adjustments on our side.

**Comment by anand1976** [comment]
@yuslepukhin This came up during the original commit as well where making CloseImpl() pure virtual was considered but not done due to compatibility concerns. Its probably best to defer it until there's a more clear policy on rolling out API changes.

**Comment by ajkr** [comment]
We aim for API compatibility so people can upgrade their system-installed RocksDB version without losing ability to compile applications. The people compiling the applications are often not the authors so we can't block them on a migration. We may break API compatibility for major version increases. Otherwise it's considered a bug and we'll backport fixes to the affected minor versions.
