### ISSUE TITLE
cc1plus: all warnings being treated as errors

### ISSUE THREAD

**Issue by tanzeelrana** [facebook/rocksdb#3521]
CC       shared-objects/utilities/backupable/backupable_db.o
  CC       shared-objects/utilities/blob_db/blob_db.o
util/transaction_test_util.cc: In static member function 'static rocksdb::Status rocksdb::RandomTransactionInserter::DBGet(rocksdb::DB*, rocksdb::Transaction*, rocksdb::ReadOptions&, uint16_t, uint64_t, bool, uint64_t*, std::__cxx11::string*, bool*)':
util/transaction_test_util.cc:75:8: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
 Status RandomTransactionInserter::DBGet(
        ^~~~~~~~~~~~~~~~~~~~~~~~~
util/transaction_test_util.cc:83:11: note: 'snprintf' output between 5 and 6 bytes into a destination of size 5
   snprintf(prefix_buf, sizeof(prefix_buf), "%.4u", set_i + 1);
   ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
util/transaction_test_util.cc: In static member function 'static rocksdb::Status rocksdb::RandomTransactionInserter::Verify(rocksdb::DB*, uint16_t, uint64_t, bool, rocksdb::Random64*)':
util/transaction_test_util.cc:244:8: error: 'snprintf' output may be truncated before the last format character [-Werror=format-truncation=]
 Status RandomTransactionInserter::Verify(DB* db, uint16_t num_sets,
        ^~~~~~~~~~~~~~~~~~~~~~~~~
util/transaction_test_util.cc:266:13: note: 'snprintf' output between 5 and 6 bytes into a destination of size 5
     snprintf(prefix_buf, sizeof(prefix_buf), "%.4u", set_i + 1);
     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [Makefile:626: shared-objects/util/transaction_test_util.o] Error 1
make: *** Waiting for unfinished jobs....
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build rocksdb.
==> Restart building rocksdb ? [y/N]
==> --------------------------------
==> 
[archie1@08d9ea32a99f ~]$

**Comment by gfosco** [comment]
What platform are you running on, what command did you execute, and what revision was this for?

**Comment by siying** [comment]
@tanzeelrana in case you missed @gfosco 's question.

**Comment by miasantreble** [comment]
ping @tanzeelrana

**Comment by anand1976** [comment]
Closing due to no response
