### ISSUE TITLE
Branch-initial-list cannot compile with { } syntax on C++11 flag.

### ISSUE THREAD

**Issue by rchatsiri** [facebook/rocksdb#3522]
### Expected behavior
RocksDB compiles source code by use g++ version 4.9. Cmake use g++ flag for supporting C++11 syntax. It's should compiles source code pass all steps.

G++ version.
```
$g++ --version
g++ (Debian 4.9.2-10) 4.9.2
```
Linux version
```
$name -a
Linux ded6f67e9f59 4.14.19-coreos #1 SMP Wed Feb 14 04:02:14 UTC 2018 x86_64 GNU/Linux
```

### Actual behavior
After run command ../cmake .. and make. Build tools show an error as below

```
Scanning dependencies of target rocksdb_compaction_iterator_test
[ 78%] Building CXX object CMakeFiles/rocksdb_compaction_iterator_test.dir/db/compaction_iterator_test.cc.o
/home/root/workspacenetwork/rocksdb/db/compaction_iterator_test.cc:186:78: error: converting to 'const std::unordered_map<long unsigned int, long unsigned int>' from initializer list would use explicit constructor 'std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = long unsigned int; _Tp = long unsigned int; _Hash = std::hash<long unsigned int>; _Pred = std::equal_to<long unsigned int>; _Alloc = std::allocator<std::pair<const long unsigned int, long unsigned int> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<long unsigned int>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<long unsigned int>; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const long unsigned int, long unsigned int> >]'
       const std::unordered_map<SequenceNumber, SequenceNumber>& snapshots = {})
                                                                              ^
CMakeFiles/rocksdb_compaction_iterator_test.dir/build.make:54: recipe for target 'CMakeFiles/rocksdb_compaction_iterator_test.dir/db/compaction_iterator_test.cc.o' failed
make[2]: *** [CMakeFiles/rocksdb_compaction_iterator_test.dir/db/compaction_iterator_test.cc.o] Error 1
CMakeFiles/Makefile2:1314: recipe for target 'CMakeFiles/rocksdb_compaction_iterator_test.dir/all' failed
make[1]: *** [CMakeFiles/rocksdb_compaction_iterator_test.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
### Steps to reproduce the behavior
Why use branch-initial-list with std::unordered_map did not work? It possibles source code compiles on the C++11 not C++14 flags.  Unordered_map class compile with the C++11 supported use default constructor explicit, Thus error of the line number must change ```{ } ``` to  non empty of branch-initial-list ```{{}}``` [1]. For example as below current version the git commit ```ab446dc22d8c59534e56784b040afc3d91b86d04```

https://github.com/facebook/rocksdb/blob/ab446dc22d8c59534e56784b040afc3d91b86d04/db/compaction_iterator_test.cc#L186

instead of

```
 const std::unordered_map<SequenceNumber, SequenceNumber>& snapshots = {{}}) 
```

After changes initial value of class name ```std::unordered_map```. Source code compiled success.

```
...
[ 99%] Built target ldb
[ 99%] Built target rocksdb_dump
[ 99%] Built target rocksdb_undump
[ 99%] Built target sst_dump
[100%] Built target write_stress
```

[1] https://stackoverflow.com/questions/26947704/implicit-conversion-failure-from-initializer-list

**Comment by gfosco** [comment]
I might be on the wrong track here, but why CMake?  I thought we only used CMake for the Windows build.

**Comment by rchatsiri** [comment]
Project use the Cmake compile source code on Linux. Current status, Project complied success on one method ``` cmake .. && make ``` by use g++ compiler version name ``` g++ (Debian 6.3.0-18) 6.3.0 20170516 ```. Something did not work on g++ version 4.9.

**Comment by gfosco** [comment]
Ok, glad you got it to work with a newer version of g++.  We can probably increase the recommended gcc version if this becomes a problem for others.

**Comment by siying** [comment]
We do have a continuous build to make sure the release build of RocksDB works on GCC 4.8.x. We don't, however, check whether unit tests can build there any more, and rely on the community to maintain it if they have an interest. Is there any reason you want to build unit tests? Do you want to do development there? If yes we do suggest you upgrade your GCC.

I can see whether this is an easy fix though.

**Comment by siying** [comment]
@rchatsiri I'm not able to reproduce this error using gcc 4.8.1.

**Comment by rchatsiri** [comment]
After I'm switch back to virtual machine old version same error issues .  I'm resolved problems by  explained in first post. Testing show a error  from command line  ``` make check ```.

```
32/135 Test  #32: db_table_properties_test .............   Passed   20.47 sec
        Start  33: db_tailing_iter_test
 33/135 Test  #33: db_tailing_iter_test .................   Passed    6.62 sec
        Start  34: db_test
 34/135 Test  #34: db_test ..............................***Exception: Other239.30 sec
        Start  35: db_test2
 35/135 Test  #35: db_test2 .............................   Passed   20.51 sec
        Start  36: db_universal_compaction_test
 36/135 Test  #36: db_universal_compaction_test .........   Passed  298.52 sec
...
99% tests passed, 1 tests failed out of 135

Total Test time (real) = 5408.73 sec

The following tests FAILED:
         34 - db_test (OTHER_FAULT)
Errors while running CTest
```

More logging over log at console in file name ``` LastTest.log ```.   An error show as below.
```
2388 done
2389 [       OK ] DBTest.LargeBatchWithColumnFamilies (1649 ms)
2390 [ RUN      ] DBTest.FlushesInParallelWithCompactRange
2391 [       OK ] DBTest.FlushesInParallelWithCompactRange (2965 ms)
2392 [ RUN      ] DBTest.DelayedWriteRate
2393 [       OK ] DBTest.DelayedWriteRate (572 ms)
2394 [ RUN      ] DBTest.HardLimit
2395 [       OK ] DBTest.HardLimit (478 ms)
2396 [ RUN      ] DBTest.SoftLimit
2397 /home/root/workspacenetwork/rocksdb/db/db_test.cc:5456: Failure
2398 Value of: listener->CheckCondition(WriteStallCondition::kDelayed)
2399   Actual: false
2400 Expected: true
2401 pthread destroy cv: Device or resource busy
2402 <end of output>
2403 Test time = 239.30 sec
2404 ----------------------------------------------------------
2405 Test Failed.
2406 "db_test" end time: Feb 25 05:25 UTC
2407 "db_test" time elapsed: 00:03:59
2408 ----------------------------------------------------------
```
