### ISSUE TITLE
OnCompactionCompleted not working

### ISSUE THREAD

**Issue by nivdayan** [facebook/rocksdb#3538]
- I am implementing a custom merge policy using the API in listeners.h. 
 - I set options.compaction_style to kCompactionStyleNone. 
 - I am using the CompactFiles method to invoke compaction from within my client code. 
 - However, the call-back OnCompactionCompleted does not get called when compaction finishes. This contradicts expected behavior as the comment on this call-back says "A call-back function for RocksDB which will be called whenever a registered RocksDB compacts a file."
 - I noticed that when I set options.compaction_style to kCompactionStyleLevel, then the OnCompactionCompleted does work. In summary, the OnCompactionCompleted call-back does not seem to work with manual compaction triggered through the CompactFiles API. 
 - A fix would be tremendously helpful. Thanks very much, and thanks for all your work in general.

**Comment by anand1976** [comment]
The compaction performed by the CompactFiles API is done synchronously in the calling thread. The OnCompletionCallback callback is used for cases where the compaction happens in background threads. Is there anything you're looking for besides just an indication that the compaction is finished?

**Comment by nivdayan** [comment]
Thanks very much for the followup! This makes sense. Ultimately, what I am after is to be able to know at the end of a compaction the name of the files that were created as a result of the compaction. Since multiple compactions may happen concurrently, I need to be able to distinguish the resulting files from different compactions. I wanted to use the OnCompactionCompleted to achieve this, but as you suggest, perhaps there are other ways. For instance, is there a way of getting the resulting file names from the CompactFiles call? Or perhaps it would be possible to extend CompactFiles to return the resulting file names, e.g., by reference? Again, thanks a lot!

**Comment by anand1976** [comment]
I'd suggest extending CompactFiles to return the filenames. My only concern with calling OnCompactionCompleted callback in this path is that it would be a behavior change, since CompactFiles users would see an unexpected callback.
Do you want to take a stab at this and pull a PR? I'd be happy to review and import it.

**Comment by nivdayan** [comment]
I've taken a stab at doing this and made a pull request on the following URL
https://github.com/facebook/rocksdb/pull/3608
Thanks very much for being willing to review it!
