### ISSUE TITLE
Myrocks/Rocksdb cp1251 encoding support

### ISSUE THREAD

**Issue by proggga** [facebook/rocksdb#3555]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
I'm trying to create  cp1251 collation, please say where I'm wrong

Unsupported collation on string indexed column durov_live.passwords_changes_log0.old_password_hash Use binary collation (binary, latin1_bin, utf8_bin).

### Actual behavior
Idk what it should be

**Comment by siying** [comment]
Collation is completely handled in MyRocks layer and is nothing to do with RocksDB.

Can you move the discussion to MyRocks groups? The preferred the channel is Google group: https://groups.google.com/forum/#!forum/myrocks-dev . MyRocks github issues work too if you prefer this becomes a work item: https://github.com/facebook/mysql-5.6/issues
