### ISSUE TITLE
make check fails on ubuntu16.04

### ISSUE THREAD

**Issue by sandipmgiri** [facebook/rocksdb#3570]
make check command is taking too much time to execute and getting below errors on ubuntu16.04: 

....
make[1]: Entering directory '/home/test/rocksdb'
Makefile:127: Warning: Compiling in debug mode. Don't use the resulting binary in production
  GEN      util/build_version.cc
  GEN      check_0

To monitor subtest <duration,pass/fail,name>,
  run "make watch-log" in a separate window
/bin/bash: line 1:  9506 Aborted                 ./c_test &> t/log-c_test
/bin/bash: line 1:  9446 Aborted                 (core dumped) ./blob_db_test &> t/log-blob_db_test
/bin/bash: line 1:  9767 Aborted                 ./column_family_test &> t/log-column_family_test
/bin/bash: line 1:  9804 Aborted                 ./compact_files_test &> t/log-compact_files_test
/bin/bash: line 1:  9938 Aborted                 ./compaction_job_stats_test &> t/log-compaction_job_stats_test
/bin/bash: line 1: 10067 Aborted                 (core dumped) ./comparator_db_test &> t/log-comparator_db_test
/bin/bash: line 1: 10335 Aborted                 ./date_tiered_test &> t/log-date_tiered_test
/bin/bash: line 1: 10397 Aborted                 ./db_basic_test &> t/log-db_basic_test
/bin/bash: line 1: 10459 Aborted                 ./db_blob_index_test &> t/log-db_blob_index_test
/bin/bash: line 1: 10506 Aborted                 ./db_block_cache_test &> t/log-db_block_cache_test
/bin/bash: line 1: 10614 Aborted                 ./db_dynamic_level_test &> t/log-db_dynamic_level_test
/bin/bash: line 1:  9618 Aborted                 ./checkpoint_test &> t/log-checkpoint_test
/bin/bash: line 1: 10864 Aborted                 ./db_inplace_update_test &> t/log-db_inplace_update_test
/bin/bash: line 1: 11094 Aborted                 ./db_iterator_test &> t/log-db_iterator_test
/bin/bash: line 1: 11345 Aborted                 ./db_options_test &> t/log-db_options_test
/bin/bash: line 1: 11384 Aborted                 ./db_properties_test &> t/log-db_properties_test
/bin/bash: line 1: 11438 Aborted                 ./db_range_del_test &> t/log-db_range_del_test
/bin/bash: line 1: 11615 Aborted                 ./db_tailing_iter_test &> t/log-db_tailing_iter_test
/bin/bash: line 1: 11733 Aborted                 ./db_write_test &> t/log-db_write_test
/bin/bash: line 1: 11934 Aborted                 (core dumped) ./deletefile_test &> t/log-deletefile_test
/bin/bash: line 1: 10260 Aborted                 (core dumped) ./cuckoo_table_db_test &> t/log-cuckoo_table_db_test
/bin/bash: line 1: 11984 Aborted                 ./document_db_test &> t/log-document_db_test
/bin/bash: line 1: 12566 Aborted                 ./external_sst_file_basic_test &> t/log-external_sst_file_basic_test
/bin/bash: line 1: 11879 Aborted                 (core dumped) ./delete_scheduler_test &> t/log-delete_scheduler_test
/bin/bash: line 1: 10129 Aborted                 ./corruption_test &> t/log-corruption_test
/bin/bash: line 1: 13390 Aborted                 (core dumped) ./listener_test &> t/log-listener_test
/bin/bash: line 1: 13546 Aborted                 ./memory_test &> t/log-memory_test
/bin/bash: line 1: 13577 Aborted                 ./memtable_list_test &> t/log-memtable_list_test
/bin/bash: line 1: 13893 Aborted                 ./optimistic_transaction_test &> t/log-optimistic_transaction_test
/bin/bash: line 1: 13925 Aborted                 ./option_change_migration_test &> t/log-option_change_migration_test
/bin/bash: line 1: 13957 Aborted                 ./options_file_test &> t/log-options_file_test
/bin/bash: line 1:  9968 Segmentation fault      (core dumped) ./compaction_job_test &> t/log-compaction_job_test
/bin/bash: line 1: 12811 Aborted                 (core dumped) ./flush_job_test &> t/log-flush_job_test
/bin/bash: line 1: 14190 Aborted                 ./perf_context_test &> t/log-perf_context_test
/bin/bash: line 1: 10810 Aborted                 ./db_flush_test &> t/log-db_flush_test
/bin/bash: line 1: 14272 Aborted                 (core dumped) ./plain_table_db_test &> t/log-plain_table_db_test
/bin/bash: line 1: 11549 Aborted                 ./db_table_properties_test &> t/log-db_table_properties_test
/bin/bash: line 1: 14500 Aborted                 (core dumped) ./redis_test &> t/log-redis_test
/bin/bash: line 1: 14565 Aborted                 ./reduce_levels_test &> t/log-reduce_levels_test
/bin/bash: line 1: 14603 Aborted                 ./repair_test &> t/log-repair_test
/bin/bash: line 1: 14733 Aborted                 ./slice_transform_test &> t/log-slice_transform_test
/bin/bash: line 1: 14855 Aborted                 ./stringappend_test &> t/log-stringappend_test
/bin/bash: line 1: 15017 Aborted                 ./ttl_test &> t/log-ttl_test
/bin/bash: line 1: 14662 Aborted                 (core dumped) ./sim_cache_test &> t/log-sim_cache_test
/bin/bash: line 1: 15307 Aborted                 ./write_batch_with_index_test &> t/log-write_batch_with_index_test
/bin/bash: line 1: 15473 Aborted                 (core dumped) ./write_callback_test &> t/log-write_callback_test
/bin/bash: line 1: 11297 Aborted                 (core dumped) ./db_merge_operator_test &> t/log-db_merge_operator_test
/bin/bash: line 1: 10570 Aborted                 (core dumped) ./db_bloom_filter_test &> t/log-db_bloom_filter_test
/bin/bash: line 1: 13626 Aborted                 (core dumped) ./merge_test &> t/log-merge_test
/bin/bash: line 1: 11644 Aborted                 (core dumped) ./db_test2 &> t/log-db_test2
/bin/bash: line 1: 11176 Aborted                 (core dumped) ./db_log_iter_test &> t/log-db_log_iter_test
/bin/bash: line 1: 12335 Aborted                 ./env_test &> t/log-env_test
......

Any helps appreciated . Thanks!

**Comment by gfosco** [comment]
Not real clear what's going on here... Is your image out of space?  Any other details to share?

**Comment by siying** [comment]
Can you share the contents of at least one of the "t/log-*" files?

**Comment by sandipmgiri** [comment]
Now we are building rocksdb in release mode only. Hence closing this ticket.Thanks!
