### ISSUE TITLE
doc: typo in Rocksdb BlockBasedTable Format wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#3571]
In https://github.com/facebook/rocksdb/wiki/Rocksdb-BlockBasedTable-Format , there is:

> (3) A metaindex block contains one entry for every other meta block, where the key is the name of the meta block and the value is a BlockHandle pointing to that meta block.

I think that `other` should be deleted.

**Comment by riversand963** [comment]
@yaojingguo Thanks for the improvement.
