### ISSUE TITLE
doc: outdated description about SST dump tool in Administration and Data Access Tool wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#3575]
In version 5.10.4, there are the following changes compared to [SST dump tool](https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool#sst-dump-tool)

- Command `verify` and `recompress` are added. 
- `--compression_types` option is added.
- `--show_compression_sizes` option is removed.

**Comment by siying** [comment]
Thanks for reporting. Our wiki editing is open to public. Feel free to just go ahead and update them.

**Comment by yaojingguo** [comment]
How can I do it? Clone the wiki and send pull requests?

**Comment by miasantreble** [comment]
updated
