### ISSUE TITLE
New DuplicateDetector reduces insert performance on Windows

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#3579]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
No change in write perf

### Actual behavior
DuplicateDetector has a member of std::map<> which is not used for ::InsertInto but only default created. Unfortunately, on Windows default creation costs a dynamic allocation of end() node. This causes significant degradation in perf. Earlier I had to make sure that mem_post_info_map_ was only created when needed.
### Steps to reproduce the behavior
Before DuplicateDetector intro:
fillrandom   :       **2.430 micros/op 411439 ops/sec;  320.2 MB/s**
Microseconds per write:
Count: 10000000 Average: 2.4300  StdDev: 49.31
Min: 1  Median: 1.5434  Max: 24764
Percentiles: P50: 1.54 P75: 1.88 P99: 5.70 P99.9: 11.06 P99.99: 38.41

After:
fillrandom   :       **_4.118 micros/op 242813 ops/sec;  189.0 MB/s_**
Microseconds per write:
Count: 10000000 Average: 4.1181  StdDev: 40.83
Min: 2  Median: 3.3603  Max: 18085
Percentiles: P50: 3.36 P75: 3.72 P99: 8.56 P99.9: 14.34 P99.99: 70.22

![endnodeinset](https://user-images.githubusercontent.com/11303988/37114434-31e17528-21fd-11e8-9842-1ec8ba84a09c.PNG)

**Comment by siying** [comment]
@maysamyabandeh can you turn it into a unique_ptr? For now, paying an extra malloc may be OK in transaction code.

**Comment by yuslepukhin** [comment]
@maysamyabandeh @siying May I suggest sub-classing MemtableInserter and calling it MemInserterWithDupDetection so that one will have that map and we simply instantiate it when we need. In fact, since I am testing it at the moment I can propose a patch.

**Comment by yuslepukhin** [comment]
Take that back, it is no that simple. I am talking to people at MS about it so I can persuade to change ndoe based containers implementation but if successful it is gonna be awhile. Meanwhile, a good advice from a CppCon is to pursue containers such as autovec that a) has some space within themselves and then spill over to a heap b) allocate continuous heap chunks instead of per-node.

**Comment by siying** [comment]
@yuslepukhin I still believe a unique_ptr is something we can tolerant. I'll discuss with @maysamyabandeh after he is back to the office.

I'm curious how does projects inside Microsoft handle this problem. Do they always pay more allocation for this?

**Comment by yuslepukhin** [comment]
@siying Yes and no. For projects like mine the containers are usually custom. For other projects they do not care and it is often not C++.

**Comment by yuslepukhin** [comment]
@siying There is more bad news. This degradation as compared with Feb 14 master. But there is some more as compared with version 4.6

**Comment by yuslepukhin** [comment]
Btw, allow_pipelined_write is false by default but the default value in db_bench is true. Wasted some hours to see I am not profiling the same thing.

**Comment by yuslepukhin** [comment]
Wit regards to allow_concurrent_memtable_write. There is a bunch of considerations to be made before using this feature and it is only implemented for SkipList but both the options and db_bench siliently put this to true.

**Comment by yuslepukhin** [comment]
enable_write_thread_adaptive_yield also flipped to true but on Windows the stock impl is already a spin lock and provides better perf although generally, customization is a good thing. However, compatibility focus should be maintained.
