### ISSUE TITLE
Extra BlockFetcher indirections add overhead

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#3590]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Previously FileReader was invoked directly from ReadBlock and checksum verification was taking place inline. Now BlockFetcher seems to add overhead

### Actual behavior

5.6 CPU consumption only contains checksum stack

![beforeblockfetcher](https://user-images.githubusercontent.com/11303988/37235042-522fb27c-23b0-11e8-83d8-4c97fba28790.PNG)

 After that we notice the overhead of BlockFetcher with ReadBlockContents() is invoked and when the checksum is checked with a separate function.

![blockfetcheroverhead](https://user-images.githubusercontent.com/11303988/37235059-77e9c89a-23b0-11e8-8e58-faafd6cada14.PNG)

The effect is small but is noticeable nevertheless
Before:
readrandom   :      **14.265 micros/op 70101 ops/sec;   54.6 MB/s (1318999 of 1318999 found)**
Percentiles: P50: 439.78 P75: 532.01 **P99: 794.36** P99.9: 994.35 P99.99: 5432.56 

After:
readrandom   :      **14.283 micros/op 70010 ops/sec;   54.5 MB/s (1320999 of 1320999 found)**
Percentiles: P50: 453.86 P75: 542.43 **P99: 856.07** P99.9: 1243.13 P99.99: 5966.62

**Comment by yuslepukhin** [comment]
Other BlockFetcher api also adds overhead to a lesser degree but it compounds altogether.

**Comment by siying** [comment]
You can add `inline` annotation to some of the functions if you care about it. In the original PR I noticed the regression and demonstrated that I could have closed the gap by adding some "inline": https://github.com/facebook/rocksdb/pull/3244#issuecomment-350149457

I chose not too as I would in general rely on compilers to make the decision. If you feel this regression hits you, you can try to do something like that too and see whether it helps you with your use case. If you send a PR, I'll merge it.
