### ISSUE TITLE
doc: typo in Universal Compaction wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#3594]
In https://github.com/facebook/rocksdb/wiki/Universal-Compaction, there is:

> As mentioned above, data is organized as sorted runs. A sorted runs are laid out by updated time of the data in it and stored as either files in L0 or a whole "level".

`A` before `sorted runs` should be deleted.

**Comment by siying** [comment]
Feel free to go ahead and modify it.

**Comment by ajkr** [comment]
done for you
