### ISSUE TITLE
RocksDB version out of sync

### ISSUE THREAD

**Issue by topilski** [facebook/rocksdb#3596]
Hi, in code i see: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/version.h#L9
but release tag is: https://github.com/facebook/rocksdb/releases/tag/v5.10.4 why ROCKSDB_PATCH not same?

**Comment by adamretter** [comment]
Release branches are created by cherry-picking commits and then creating a tag after testing etc. Changes from master do make it into releases eventually, but the latest release is not necessarily a reflection of master at that time.
