### ISSUE TITLE
WAL corruption when using Options::manual_wal_flush

### ISSUE THREAD

**Issue by petermattis** [facebook/rocksdb#3599]
Specifying `Options::manual_wal_flush == true` without specifying `Options::concurrent_prepare` (a.k.a. `Options::two_write_queues`) can lead to corruption of the WAL due to lack of synchronization. Specifically, concurrent execution of `DBImpl::FlushWAL` and `DBImpl::WriteToWAL` can lead to concurrent calls to `WritableFileWriter::Flush` and `log::Writer::AddRecord` (which calls `WritableFileWriter::Append`), and lots of resulting badness. This was found and debugged on v5.8 (+ a few patches), but I'm not seeing anything on current head that would address this. The corruption happens so quickly that I'm guessing nobody is actually running in this configuration.

Possible fixes would be to grab `log_write_mutex` before calling `WriteToWAL` if `manual_flush && !concurrent_prepare`. Perhaps safer would be to add a mutex inside of `log::Writer` that is used of `manual_flush` is set. This is performance sensitive code, so hard for me to judge what would be appropriate.

**Comment by ajkr** [comment]
Great find, thanks for reporting. I do think `log_write_mutex` surrounding `WriteToWAL` in the case you mentioned should be sufficient. And we should probably scrub this area of the code more for bugs as we also found one recently. It was an extraneous call to `DBImpl::FlushWAL` from checkpoint/backup, even when `manual_flush` was false, which raced with `DBImpl::WriteToWAL`, causing WAL corruption.

**Comment by petermattis** [comment]
@ajkr Can I leave this in your hands to fix? I'm swamped with other work right now and won't be able to dedicate any time to this for a few weeks.

**Comment by lishuai87** [comment]
same here:  https://github.com/facebook/rocksdb/issues/2871
