### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by nichdiekuh** [facebook/rocksdb#360]
I know (Free)BSD is currently not supported and there's a FreeBSD port of version 3.2 available, but is this something your planning to add in a future release?
I'm using InfluxDB on FreeBSD and upgrading versions is always painful, because RocksDB doesn't compile natively on FreeBSD.

**Comment by igorcanadi** [comment]
Hey @nichdiekuh -- I think we fixed this in master, can you please check? We'll release with 3.10 soon so we want to make sure everything is OK

**Comment by siying** [comment]
@nichdiekuh ping

**Comment by igorcanadi** [comment]
Closing this since we now have FreeBSD support. Please open a new issue if FreeBSD compile doesn't work for you.
