### ISSUE TITLE
Manifest file and log file got deleted twice

### ISSUE THREAD

**Issue by qingping209** [facebook/rocksdb#3616]
I observed the following errors in rocksdb LOG when I restarted one of my rocksdb instance:

`
2018/03/15-23:30:54.804269 7ffff7ede9e0 [DEBUG] [db/db_impl_files.cc:325] [JOB 2] Delete tmp/rocksdb//MANIFEST-000008 type=3 #8 -- OK
2018/03/15-23:30:54.804333 7ffff7ede9e0 [DEBUG] [db/db_impl_files.cc:325] [JOB 2] Delete tmp/rocksdb/001130.log type=0 #1130 -- OK
2018/03/15-23:30:54.804362 7ffff7ede9e0 [db/db_impl_files.cc:332] [JOB 2] Tried to delete a non-existing file tmp/rocksdb///MANIFEST-000008 type=3 #8 -- IO error: while unlink() file: tmp/rocksdb///MANIFEST-000008: No such file or directory
2018/03/15-23:30:54.804376 7ffff7ede9e0 [db/db_impl_files.cc:332] [JOB 2] Tried to delete a non-existing file tmp/rocksdb//001130.log type=0 #1130 -- IO error: while unlink() file: tmp/rocksdb//001130.log: No such file or directory
`

I traced the calling stack and found _candidate_files_ in **PurgeObsoleteFiles** have the following value:

`
$8 = std::vector of length 34, capacity 35 = {{file_name = "OPTIONS-000005", path_id = 0}, {file_name = "MANIFEST-001137", path_id = 0}, {
    file_name = "MANIFEST-000008", path_id = 0}, {file_name = "LOG.old.1521126990583019", path_id = 0}, {file_name = "LOG.old.1521117072460519",
    path_id = 0}, {file_name = "LOG.old.1521117072457261", path_id = 0}, {file_name = "LOG", path_id = 0}, {file_name = "LOCK", path_id = 0}, {
    file_name = "IDENTITY", path_id = 0}, {file_name = "CURRENT", path_id = 0}, {file_name = "001138.log", path_id = 0}, {file_name = "001136.sst",
    path_id = 0}, {file_name = "001134.sst", path_id = 0}, {file_name = "001133.sst", path_id = 0}, {file_name = "001130.log", path_id = 0}, {
    file_name = "/OPTIONS-000005", path_id = 0}, {file_name = "/MANIFEST-001137", path_id = 0}, {file_name = "/MANIFEST-000008", path_id = 0}, {
    file_name = "/LOG.old.1521126990583019", path_id = 0}, {file_name = "/LOG.old.1521117072460519", path_id = 0}, {
    file_name = "/LOG.old.1521117072457261", path_id = 0}, {file_name = "/LOG", path_id = 0}, {file_name = "/LOCK", path_id = 0}, {
    file_name = "/IDENTITY", path_id = 0}, {file_name = "/CURRENT", path_id = 0}, {file_name = "/001138.log", path_id = 0}, {
    file_name = "/001136.sst", path_id = 0}, {file_name = "/001134.sst", path_id = 0}, {file_name = "/001133.sst", path_id = 0}, {
    file_name = "/001130.log", path_id = 0}, {file_name = "/..", path_id = 0}, {file_name = "/.", path_id = 0}, {file_name = "..", path_id = 0}, {
    file_name = ".", path_id = 0}}
`

The reason is that the same file appears in the vector multiple times in different forms: with or without slash prefix so that std::unique does not really remove  duplicate items. 

Maybe related to https://github.com/facebook/rocksdb/issues/3573

**Comment by qingping209** [comment]
@https://github.com/facebook/rocksdb/issues/3573

**Comment by siying** [comment]
Interesting. Thank you for reporting! We can look at a potential fix. There is no hard for double deleting though. Just ignore the warning.
