### ISSUE TITLE
External file can be modified when IngestExternalFile failed

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#3628]
### Expected behavior
When `IngestExternalFile` fails, the external file will be left unchanged.

### Actual behavior
The external file is overwritten when `IngestExternalFile` fails and RocksDB restarts.

### Steps to reproduce the behavior
``` C++
#include <rocksdb/db.h>
#include <rocksdb/sst_file_writer.h>

using namespace rocksdb;

void gen_sst_files(const Options& opts, const std::vector<std::string>& files) {
  for (auto f : files) {
    std::unique_ptr<SstFileWriter> w(new SstFileWriter(EnvOptions(), opts));
    assert(w->Open(f).ok());
    assert(w->Put(f, f).ok());
    assert(w->Finish().ok());
  }
}

int main(int argc, char** argv) {
  Options opts;
  opts.create_if_missing = true;

  std::vector<std::string> sst_files = {
    "/tmp/example.1.sst",
    "/tmp/example.2.sst",
  };
  gen_sst_files(opts, sst_files);

  DB* db = nullptr;
  assert(DB::Open(opts, "/tmp/rocksdb", &db).ok());

  assert(db->Put(WriteOptions(), "k", "v").ok());
  assert(db->Flush(FlushOptions()).ok());
  assert(db->Put(WriteOptions(), "k", "v").ok());

  IngestExternalFileOptions ingest_opts;
  ingest_opts.move_files = true;
  // I inject an `abort()` after the files have been hard linked to db.
  db->IngestExternalFile(sst_files, ingest_opts);
}
```

Consider the scenario above, if the program crashes (e.g. OOM) when the external files have been hard linked to the db, but before they have been ingested successfully. Then if we reopen the db, the file "/tmp/example.2.sst" will be overwritten, because the db reuses the same file number of the hard linked file on recover.

**Comment by huachaohuang** [comment]
@IslamAbdelRahman Would you help to check if this behavior is expected? Thanks.

**Comment by riversand963** [comment]
@huachaohuang Thanks for reporting this issue. Now that there is a separate PR #4099 addressing this issue, I'm closing this one. If you have further input, let's discuss under PR #4099 .
