### ISSUE TITLE
Documentation about the SST file format changes and versioning

### ISSUE THREAD

**Issue by leventov** [facebook/rocksdb#3643]
I went through RocksDb's release notes in the last couple of years and didn't find notes explicitly saying that the SST format has changed. Did it happen, and if yes, in what releases of RocksDb? Is it guaranteed to not be changed on patch, or minor, or major releases?

**Comment by miasantreble** [comment]
Not that I know of.
If you witnessed any problems with SST files, feel free to report it here.

**Comment by leventov** [comment]
Could somebody of the core development team confirm that SST format is "fixed" and if it is ever changed, it will be a "different" format with a different name, or "SST 2.0" very clearly announced on Release Notes?

**Comment by ajkr** [comment]
The philosophy is people should be able to upgrade/downgrade RocksDB to minor/patch versions within the same major release, without any code change or data migration. Incompatible changes are fair game only when the major version changes. They should be mentioned clearly in HISTORY.md.

You can see the history here: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/table.h#L205-L219. Note even though a new format was introduced in 3.10, it wasn't enabled by default until 4.5, so to me that doesn't violate the rule (i.e., users of version 4.x, where x >= 5, could still downgrade all the way to 4.0).

**Comment by leventov** [comment]
Thanks for answers!
