### ISSUE TITLE
export metrics for bloom filter false positive rates

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#3680]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

I want to know what the FPR is for bloom filters

### Actual behavior

RocksDB doesn't share this today

**Comment by yoshinorim** [comment]
False positive rates for prefix bloom filter is not available. How hard is it to support?

**Comment by maysamyabandeh** [comment]
The exported stats are documented here: https://github.com/facebook/rocksdb/wiki/RocksDB-Bloom-Filter#statistic
As per offline discussion at this stage we do not report false positive rate for prefix in seeks.
