### ISSUE TITLE
Non-transactional updates (put, merge, delete) are internally run under a transaction

### ISSUE THREAD

**Issue by vitalyisaev2** [facebook/rocksdb#3706]
I apologize for posting this question here instead of Facebook group. In a wiki article about [RocksDB transactions](https://github.com/facebook/rocksdb/wiki/Transactions) it is said that:

> Non-transactional updates (put, merge, delete) are internally run under a transaction. So every update is through transactions → TransactionDBImpl::Put

Could you please clarify, does it actually mean that even within a default non-transactional database (` rocksdb::DB*`) all `Put` / `Merge` / `Delete` requests will also run under a transaction?

**Comment by maysamyabandeh** [comment]
Feel free to reach user groups for questions.
