### ISSUE TITLE
Compaction doesn't work [Stopping writes because we have 36 level-0 files]

### ISSUE THREAD

**Issue by unoexperto** [facebook/rocksdb#3717]
Hey guys, sorry for posting here but noone on [Facebook](https://www.facebook.com/groups/rocksdb.dev) or [StackOverflow](https://stackoverflow.com/questions/49813603/how-do-i-force-compaction-to-eliminate-stopped-writes) responds and it's been 3 days since writes stopped working in production :(

I started seeing `Stopping writes because we have 36 level-0 files` error in the log recently. My DB is ~160GB. 

Here is full log https://hastebin.com/raw/odunajuxap

I've read your `Write stalls` wiki page and now know why writes don't work but I have two questions:

1) Why real-time compaction isn't working for me ?
2) How can I force compaction ? 

I tried to increase `max_background_compactions` to 16 and `write_buffer_size` to 512M but nothing happens.

I also tried to call compactRange(). It's blocking call but I don't see indication of activity in the log.

And I couldn't use Ldb Tool to compact because I use custom comparator.

Thanks a lot.

**Comment by unoexperto** [comment]
@ajkr I ran another instance with compaction overnight (~10 hrs uptime). Here is stack traces of live process

https://www.zerobin.net/?02035043fd722185#DEwPcAJC56PgQ2AuGUzLHfoZJng4VPDBNwIoHz1MQl0=

I'm using this build under Ubuntu MATE http://mvnrepository.com/artifact/org.rocksdb/rocksdbjni/5.11.3

**Comment by ajkr** [comment]
It looks like `rocksdb::JniCallback::getJniEnv` is waiting for something. I am not that familiar with java, though. cc @adamretter

**Comment by yiwu-arbug** [comment]
@adamretter do you mind take a look?

**Comment by unoexperto** [comment]
Guys, any progress on this ? I think it's beginning to be stuck on write for me after I recreated RocksDB from scratch. I even forcibly call compaction method after writing each chunk of documents.

**Comment by riversand963** [comment]
@unoexperto , did this happen after you trigger manual flush? How many CPU cores do you have
Can you tell the result of `std::thread::hardware_concurrency()` by any chance?

**Comment by zawlazaw** [comment]
I am absolutely no expert on this, but some time ago I ran into write stalls with rocksdb-java on a write-intense workload. After unsuccessfully trying to manually optimize, all problems went totally away simply by adding the following option before opening rocksdb:

    val` options = new Options()
    options.optimizeLevelStyleCompaction()
    val db = RocksDB.open(options, ...)

The call to `optimizeLevelStyleCompaction` sets several low-level parameters in a way that works very well for me. Probably this helps?

**Comment by adamretter** [comment]
It looks like this was resolved by setting `optimizeLevelStyleCompaction`
