### ISSUE TITLE
What's the maximum column families sizes supported?

### ISSUE THREAD

**Issue by wiley163** [facebook/rocksdb#3719]
>What's the maximum column families sizes supported?  I have created 1million column families using CreateColumnFamilies method, it seems too slow about spending one day and hasn't any result. I also try using Rocksdb::open() to open&create 1million column families, but it is much slower. how can I do this?

**Comment by yiwu-arbug** [comment]
Please use our facebook group or google group for questions. Issues are mean for real issues, not questions. Thanks.
