### ISSUE TITLE
doc: outdated description about filter_policy in the Basic Operations wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#3722]
https://github.com/facebook/rocksdb/wiki/Basic-Operations#filters says:

> rocksdb::Options options;
> options.filter_policy = NewBloomFilter(10, false /* use block based filter */);

`filter_policy` has been moved from `Options` to `BlockBasedTableOptions`.

**Comment by ajkr** [comment]
done
