### ISSUE TITLE
doc: confusing description of iterator error handling on Iterator wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#3727]
On [Iterator wiki page](https://github.com/facebook/rocksdb/wiki/Iterator), there is the following text:

> Iterator::status() returns the error of the iterating. The iterator may pass the blocks or files it had difficulties in reading (because of IO error, data corruption or other issues) and continue with the next available keys. status() may not OK after every iterator operation: Seek(), Next(), SeekToFirst(), SeekToLast(), SeekForPrev(), and Prev(), even if Valid()=true.

Does it mean that we should check `Iterator::status()` before any accessing of `Iterator::key()` or `Iterator:: value()` in a loop over an iterator?  In other words, an iteration over key and value in an iterator should be   `for (iter->SeekToFirst(); iter->Valid() && iter->status().ok(); iter->Next())` instead of `for (iter->SeekToFirst(); iter->Valid(); iter->Next()) `.

But a check of the source code  shows that the latter approach is actually used. For example, [db_iterator_test.cc](https://github.com/facebook/rocksdb/blob/master/db/db_iterator_test.cc#L1243):

```C++
// Test iterating all data forward
std::vector<Slice> all_keys;
for (iter->SeekToFirst(); iter->Valid(); iter->Next()) {
  std::string prop_value;
  ASSERT_OK(
      iter->GetProperty("rocksdb.iterator.is-key-pinned", &prop_value));
  ASSERT_EQ("1", prop_value);
  all_keys.push_back(iter->key());
}
```

**Comment by ajkr** [comment]
Closing as it seems correct, but let me know if you have any proposed clarification to the wiki
