### ISSUE TITLE
GTest does not build in VS 2017 C++17

### ISSUE THREAD

**Issue by chfast** [facebook/rocksdb#3738]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Should build.

### Actual behavior

Does not build. The copy of gtest library does not recognize what tuple implementation to use and tries `std::tr1::` which is not available in C++17.

Error:
```
ource\third-party\gtest-1.7.0\fused-src\gtest\gtest.h(10326): error C3083: 'tr1': the symbol to the left of a '::' must be a type
```

### Steps to reproduce the behavior

Configure on Windows with `cmake -DCMAKE_CXX_STANDARD=17`.

**Comment by yiwu-arbug** [comment]
@chfast Thanks for reporting. It seems that you can add macro `GTEST_HAS_TR1_TUPLE 0` to get around it. Mind give it a try? 
https://github.com/facebook/rocksdb/blob/master/third-party/gtest-1.7.0/fused-src/gtest/gtest.h#L186

**Comment by chfast** [comment]
Yes, this helps, but there are other issues with C++17, e.g. `std::random_shuffle`. I think I will skip this build config for now.

I just wander what would be the best fix for gtest issue? Upgrade sources to the latest upstream version? Restrict rocksdb builds to minimum C++11?

**Comment by chfast** [comment]
Please also check out another Windows build fix: https://github.com/facebook/rocksdb/pull/3737.

**Comment by yiwu-arbug** [comment]
@chfast I'm wondering if upgrading to gtest 1.8.0 will fix the issue but I don't have time to try. Let us know if doing it will help or for any other suggestions.

**Comment by chfast** [comment]
I can upgrade GTest, but I'd prefer to use at least CMake's ExternalProject to maintain it.
Optionally Hunter package manager.

**Comment by siying** [comment]
Is there a reason that you have to build with C++17?

**Comment by siying** [comment]
Does it build without tests? If only tests fail to build, I wouldn't bother investing time on fixing it, as it is not one of our standard development environments. If the release components fail to build too, maybe we should take a look at and see whether there is a quick fix.

**Comment by adamretter** [comment]
This combination is unsupported at this time.
