### ISSUE TITLE
Failed: Invalid argument: leveldb.BytewiseComparator: does not match existing comparator RocksKeyComparator

### ISSUE THREAD

**Issue by codesql** [facebook/rocksdb#3741]
I am trying to understand what really causing this error? And if it is by-design. There isn't a whole lot of documentation about ldb. From what I noticed, the ldb backup or scan would error when there is an sst files in the database the very first time.

### Expected behavior
Expect the ldb will back up the database in any way.

### Actual behavior
ldb errors out when sst file inside the database. 

### Steps to reproduce the behavior
We have an application that will create 4 identical rocksdb databases when it starts. When it runs, it inserts the same data to all 4 of them.

Issue starts here: backup the rocksdb. ldb scan would fail the same way.

```
~/rocksdb$ ./ldb --db=/home/ubuntu/dbtest3 backup --backup_dir=/home/ubuntu/dbtest3_bk/x3.bk

Failed: Invalid argument: leveldb.BytewiseComparator: does not match existing comparator RocksKeyComparator

~/rocksdb$ ./ldb --db=/home/ubuntu/dbtest3 scan --hex
Failed: Invalid argument: leveldb.BytewiseComparator: does not match existing comparator RocksKeyComparator

```
Step 1: Delete the database.

rm -Rf dbtest3

Step 2: start our application where it recreates the database dbtest3

```
ls --full -Gg dbtest3
total 148
-rw-r--r-- 1     0 2018-04-18 15:55:27.814654998 -0700 000003.log
-rw-r--r-- 1    16 2018-04-18 15:55:27.794654734 -0700 CURRENT
-rw-r--r-- 1    37 2018-04-18 15:55:27.798654787 -0700 IDENTITY
-rw-r--r-- 1     0 2018-04-18 15:55:27.786654629 -0700 LOCK
-rw-rw-r-- 1 13776 2018-04-18 15:55:27.822655103 -0700 LOG
-rw-r--r-- 1    13 2018-04-18 15:55:27.794654734 -0700 MANIFEST-000001
-rw-r--r-- 1  4238 2018-04-18 15:55:27.818655051 -0700 OPTIONS-000005
```

Step 3: run the application that starting to insert data. It generates log (000003.log). ldb scan works.

```
ls --full -Gg dbtest3
total 72368
-rw-r--r-- 1 19772 2018-04-18 15:58:49.585323284 -0700 000003.log
-rw-r--r-- 1    16 2018-04-18 15:55:27.794654734 -0700 CURRENT
-rw-r--r-- 1    37 2018-04-18 15:55:27.798654787 -0700 IDENTITY
-rw-r--r-- 1     0 2018-04-18 15:55:27.786654629 -0700 LOCK
-rw-rw-r-- 1  7048 2018-04-18 15:58:18.920917028 -0700 LOG
-rw-rw-r-- 1 13776 2018-04-18 15:55:27.822655103 -0700 LOG.old.1524092298923300
-rw-r--r-- 1    13 2018-04-18 15:55:27.794654734 -0700 MANIFEST-000001
-rw-r--r-- 1  4238 2018-04-18 15:55:27.818655051 -0700 OPTIONS-000005
```

Step 4: stop the application so that it releases the rocksdb LOCK and I can back it up.
So far so good. The structure remains the same, no sst.

```
ls --full -Gg dbtest3
total 72496
-rw-r--r-- 1 1447394 2018-04-18 16:00:46.590875394 -0700 000003.log
-rw-r--r-- 1      16 2018-04-18 15:55:27.794654734 -0700 CURRENT
-rw-r--r-- 1      37 2018-04-18 15:55:27.798654787 -0700 IDENTITY
-rw-r--r-- 1       0 2018-04-18 15:55:27.786654629 -0700 LOCK
-rw-rw-r-- 1    7055 2018-04-18 16:00:29.022642164 -0700 LOG
-rw-rw-r-- 1   13776 2018-04-18 15:55:27.822655103 -0700 LOG.old.1524092298923300
-rw-rw-r-- 1    7048 2018-04-18 15:58:18.920917028 -0700 LOG.old.1524092429017116
-rw-r--r-- 1      13 2018-04-18 15:55:27.794654734 -0700 MANIFEST-000001
-rw-r--r-- 1    4238 2018-04-18 15:55:27.818655051 -0700 OPTIONS-000005

```

Step 5: Back up again and it works. scan works too. dbtest1,2 and 4 not backing up.

```
~/rocksdb$ ./ldb --db=/home/ubuntu/dbtest3 backup --backup_dir=/home/ubuntu/dbtest1_bk/x3.bk
open db OK
open backup engine OK
create new backup OK
```

Step 6: start the application that causes an open to the database. It triggers sst file (000004.sst) the very first time. So, apparently, the structure changes compare to last successful backup.

```
 ls --full -Gg dbtest3
total 1204
-rw-r--r-- 1 547927 2018-04-18 16:02:10.235986620 -0700 000004.sst
-rw-r--r-- 1      0 2018-04-18 16:02:10.251986832 -0700 000006.log
-rw-r--r-- 1     16 2018-04-18 16:02:10.243986726 -0700 CURRENT
-rw-r--r-- 1     37 2018-04-18 15:55:27.798654787 -0700 IDENTITY
-rw-r--r-- 1      0 2018-04-18 15:55:27.786654629 -0700 LOCK
-rw-rw-r-- 1  13662 2018-04-18 16:03:06.896740017 -0700 LOG
-rw-rw-r-- 1  13776 2018-04-18 15:55:27.822655103 -0700 LOG.old.1524092298923300
-rw-rw-r-- 1   7048 2018-04-18 15:58:18.920917028 -0700 LOG.old.1524092429017116
-rw-rw-r-- 1   7055 2018-04-18 16:00:29.022642164 -0700 LOG.old.1524092530127649
-rw-rw-r-- 1  15692 2018-04-18 16:02:10.287987311 -0700 LOG.old.1524092586897967
-rw-r--r-- 1    132 2018-04-18 16:02:10.287987311 -0700 MANIFEST-000005
-rw-r--r-- 1   4238 2018-04-18 15:55:27.818655051 -0700 OPTIONS-000005
-rw-r--r-- 1   4333 2018-04-18 16:02:10.255986885 -0700 OPTIONS-000008

```
```
~/rocksdb$ ./ldb --db=/home/ubuntu/dbtest3 backup --backup_dir=/home/ubuntu/dbtest1_bk/x3.bk
open db OK
open backup engine OK
create new backup OK

```
dbtest3 remains fine. But others, dbtest1,2,4 all exhibit errors "Failed: Invalid argument: leveldb.BytewiseComparator: does not match existing comparator RocksKeyComparator". These are all identical databases. At this point, there is no way, the ldb or scan will work except dbtest3 (maybe something cached and enable it to continue work) but all the databases need to be deleted and start over.

```
~/rocksdb$ ./ldb --db=/home/ubuntu/dbtest4 backup --backup_dir=/home/ubuntu/dbtest1_bk/x4.bk
Failed: Invalid argument: leveldb.BytewiseComparator: does not match existing comparator RocksKeyComparator

```
With this test, I am assuming, right from the start, I need to perform a backup of ALL the databases to ensure they continue to work before stop and start my application for the second time. Can someone shed some lights if there is another workaround?

So, in order to make sure the ldb backup and scan to continue to work.

Step 1: Start application.
Step 2: Run application.
Step 3: Stop application as soon data get inserted
Step 4: ldb backup and ldb scan on ALL databases
Step 5: Start and Run application.

**Comment by yiwu-arbug** [comment]
Your application must be using a custom comparator called RocksKeyComparator. ldb only recognize the default comparator which is leveldb.BytewiseComparator. You can build your own ldb binary by including https://github.com/facebook/rocksdb/blob/master/include/rocksdb/ldb_tool.h and pass in your custom comparator through DB options.
