### ISSUE TITLE
db_bench: how to set multi column families?

### ISSUE THREAD

**Issue by liukun4515** [facebook/rocksdb#3751]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

I use the command  `./db_bench --num_column_families=2 --benchmarks="fillseq,stats"`, but the result of statistics only has the `default` column families.

**Comment by ajkr** [comment]
> For **questions**, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

The stats are for the DB which include all column families.

**Comment by liukun4515** [comment]
I'm looking forward the “cfstats” benchmark.

**Comment by brary** [comment]
@liukun4515 what's the resolution to the issue above?

I am also facing this issue and couldn't find it on the facebook page as well.

`./db_bench --db=/data/db_bench_data/event-store --benchmarks="readrandom" --use_existing_db -compression_type="snappy" -options_file=/data/db_bench_data/event-store/OPTIONS-340484 -num_column_families=3 
Initializing RocksDB Options from the specified file
open error: Invalid argument: You have to open all column families`
