### ISSUE TITLE
db_bench:unknown benchmark 'prefixscanrandom'

### ISSUE THREAD

**Issue by liukun4515** [facebook/rocksdb#3757]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

execute `./db_bench --benchmarks=prefixscanrandom`
result：
`unknown benchmark 'prefixscanrandom'`

**Comment by ajkr** [comment]
Can you use `--benchmarks=seekrandom --prefix_size=X --keys_per_prefix=Y --seek_nexts=Z`? One downside I see is it won't seek to the first key in the prefix.

**Comment by ajkr** [comment]
Also if you want to submit a PR to delete "prefixscanrandom" from the `./db_bench -help` text, it'd be helpful. I expect we won't add that benchmark back as it's redundant with "seekrandom".

**Comment by liukun4515** [comment]
The document of wiki should be updated.
[benchmart tool](https://github.com/facebook/rocksdb/wiki/Benchmarking-tools)
