### ISSUE TITLE
doc: deprecated API is used in ingestion wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#3759]
In [Creating and Ingesting SST files](https://github.com/facebook/rocksdb/wiki/Creating-and-Ingesting-SST-files), there is the following code:

```C++
for (...) {
  s = sst_file_writer.Add(key, value);
  if (!s.ok()) {
    printf("Error while adding Key: %s, Error: %s\n", key.c_str(),
           s.ToString().c_str());
    return 1;
  }
}
```

`Add` is deprecated. `Put` should be used instead.

**Comment by anand1976** [comment]
Fixed. Thanks for pointing it out.
