### ISSUE TITLE
Check for nullptr in Slice constructor

### ISSUE THREAD

**Issue by framlog** [facebook/rocksdb#3771]
https://github.com/facebook/rocksdb/blob/a4fb1f8c049ee9d61a9da8cf23b64d2c7d36a33f/include/rocksdb/slice.h#L46
Is it a problem?

**Comment by anand1976** [comment]
One way to handle this would be to throw an exception. In general, the RocksDB code doesn't throw exceptions. I'm not sure if there's any philosophy behind it. Cc: @siying

**Comment by ajkr** [comment]
@framlog Do you have an example where we create a Slice with nullptr?

**Comment by framlog** [comment]
@ajkr I don’t have an example for that. I open this issue because it causes gcc warnings. Maybe it’s designed on purpose to detect the misuse of slice

**Comment by ajkr** [comment]
Apparently it's possible (#2777) and compatibility needs to be maintained... Maybe let's take the hit and use `s == nullptr ? 0 : strlen(s)`

**Comment by jmininger** [comment]
Out of mere curiosity, if you were to change the data_ to an empty string and the size to 0 in the constructor (very much like ''' void Slice::clear() { data_ = ""; size_ = 0; } ''' does), do you have to worry about the fact that the empty string is being constructed on the stack and no longer exists after the constructor exits? Unless I am missing something, this would make data_ point to a garbage value.
Also, I can take up this issue if a pull request has not been submitted yet. I would like to take on a simple change like this and familiarize myself with the workflow.

**Comment by anand1976** [comment]
I don't think the empty string "" will be constructed on the stack. It would be treated as a string literal, so would be stored in .rodata.

And yes, no pull request has been submitted yet so you can take up this issue!
