### ISSUE TITLE
Rocksdb failing to load from Windows when saved in Linux

### ISSUE THREAD

**Issue by saifjsl** [facebook/rocksdb#3783]
### Expected behavior
Be able to load a rocksdb database from any OS regardless of where it was compiled

### Actual behavior
**When reading a Linux-saved rocksdb from Windows**
```
Caused by: org.rocksdb.RocksDBException: Snappy not supported or corrupted Snappy compressed block contents
	at org.rocksdb.RocksDB.get(Native Method)
	at org.rocksdb.RocksDB.get(RocksDB.java:788)
```
### Steps to reproduce the behavior
We are not passing any particular options, RocksDB.open() on a file and then write batches into it.
Using 5.1.4

**Comment by adamretter** [comment]
The Java release of RocksDB for Windows does not include Snappy (or any compression support), as such you will either need to build a version on Windows with Snappy support, or a version on Linux without Snappy support.
