### ISSUE TITLE
Iterator results are not stable while using iterate_upper_bound and prefix_extractor

### ISSUE THREAD

**Issue by absolute8511** [facebook/rocksdb#3789]
I am using the `prefix_extractor` with `NewFixedPrefixTransform(3)`.

read option with prefix_same_as_start=true and `iterate_upper_bound=[26 0 4 116 101 115 116 58 0 12 109 121 122 115 101 116 95 114 97 110 103 101 58 32 32 32 32 53 48 48 49 0]`  (note I am using [] to indicate byte array)

Iterator Seek at `[26 0 4 116 101 115 116 58 0 12 109 121 122 115 101 116 95 114 97 110 103 101 58]` and try `Next()` until `Valid()` return false

db insert  keys as below (total 4999 continues keys):

```
[26 0 4 116 101 115 116 58 0 12 109 121 122 115 101 116 95 114 97 110 103 101 58 32 32 32 32 32 32 32 48]
[26 0 4 116 101 115 116 58 0 12 109 121 122 115 101 116 95 114 97 110 103 101 58 32 32 32 32 32 32 32 49]
...
...
[26 0 4 116 101 115 116 58 0 12 109 121 122 115 101 116 95 114 97 110 103 101 58 32 32 32 32 52 57 57 56]
```

The iterator may return different results at sometimes (the returned key number is different and less than 4999).  If I iterating without upper_bound, I can get the right results always. I am confused by this result. Is this expected?

**Comment by absolute8511** [comment]
Seems upper_bound Slice is affected by DB put, I will check if any wrong usage in mine code.

**Comment by siddontang** [comment]
Hi @absolute8511 

Have you found anything wrong here?

**Comment by absolute8511** [comment]
@siddontang 
I solved it by copying Go bytes to C char array while setting the `iterate_upper_bound`.
