### ISSUE TITLE
DBIter::ReverseToBackward is very very slow

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#3790]
### Expected behavior
Prev is not so slow when the iterator's direction is forward.

### Actual behavior
Prev is very very slow when the iterator's direction is forward.

### Steps to reproduce the behavior
In our database, we mix the usage of Prev and Next for Iterator, and find the ReverseToBackward is damn slow. 
Here is a flame graph.
[flamegraph.tar.gz](https://github.com/facebook/rocksdb/files/1957605/flamegraph.tar.gz)

**Comment by anand1976** [comment]
Can you check the stat rocksdb.number.reseeks.iteration or use PerfContext and look at internal_recent_skipped_count and internal_key_skipped_count? I'm curious if the iterator has to skip a lot of internal keys to find the previous user key.

**Comment by anand1976** [comment]
Closing due to no response.
