### ISSUE TITLE
Parameter passing for argument of type 'X' will change in 7.1

### ISSUE THREAD

**Issue by Terry-Weymouth** [facebook/rocksdb#3791]
Under gcc version 6.3 -
Compiling code with: PORTABLE=1 make static_lib - 
There were many warnings of the form:
**note: parameter passing for argument of type '[some class-like type here]' will change in 7.1**
Looks like types are generally iterator types, table types, or tree types - things like that, 
This gist contains notes on OS type and gcc version, as well as a terminal-output capture of running the compile (showing all the warnings): https://gist.github.com/Terry-Weymouth/086b2566711308d92ac9bed53b25899c

**Comment by anand1976** [comment]
It seems like this would be an issue for code that needs ABI compatibility between 6.3 and 7.1 - https://gcc.gnu.org/ml/gcc/2017-05/msg00073.html. We guarantee only API compatibility, so if you upgrade you have to recompile RocksDB along with the application code.
Cc: @siying

**Comment by anand1976** [comment]
We don't guarantee ABI compatibility, so I think this is not an issue.
