### ISSUE TITLE
CANNOT INHERIT FROM MERGE OPERATOR

### ISSUE THREAD

**Issue by didierjeanphi** [facebook/rocksdb#3811]
I am using rocksdb compile wilt 
GCC-7.3 

the following code copied from an example in the source tree

```c++
class DpxValueMerger : public rocksdb::AssociativeMergeOperator
{
public:	

      virtual bool Merge(const rocksdb::Slice& key,
                         const rocksdb::Slice* existing_value,
                         const rocksdb::Slice& value,
                         std::string* new_value,
                         rocksdb::Logger* logger) const override	
		{

			// The key associated with the merge operation.
			if ( existing_value == nullptr)
			{
			}
			else // this is where things happens
			{
				//merge the two jason values...
			}	

		return false;
	}

	const char* Name() const override 
	{ 
		return "MY MERGE";
	}

...
//later in the code (same cpp file though...)

m_Options.merge_operator.reset( new  DpxValueMerger );

```

returns the following error :
```
 undefined reference to `typeinfo for rocksdb::AssociativeMergeOperator'
```

Is there anything I did not understand as to how to use merge operators?

Thank you

**Comment by didierjeanphi** [comment]
Please close this thread... I found the solution.
I forgot to define USE_RTTI before invoking make static_lib

**Comment by leaout** [comment]
> Please close this thread... I found the solution.
> I forgot to define USE_RTTI before invoking make static_lib

hi bro,I meet the same problem ,would you please show solution in detail?

**Comment by didierjeanphi** [comment]
> > Please close this thread... I found the solution.
> > I forgot to define USE_RTTI before invoking make static_lib
> 
> hi bro,I meet the same problem ,would you please show solution in detail?

Dude

This is how I compile 

```
make  static_lib  EXTRA_CXXFLAGS=-fPIC EXTRA_CFLAGS=-fPIC USE_RTTI=1 DEBUG_LEVEL=0
```
