### ISSUE TITLE
the rocksjni default options is very slower than c++ one

### ISSUE THREAD

**Issue by huangyoje** [facebook/rocksdb#3812]
My database has 112988527 data. When I compare the performance between Java JNI iterator and C++ iterator, the result(80s+ vs 20s+) showed that the Java JNI iterator is very slow.

After reading this [issue 1263](https://github.com/facebook/rocksdb/issues/1263),  I did some testing using ideas (no copy, group operation) from that article. However, what surprise me is that no copy can save about 20s, group operation can save about 7~10s. there is still a gap of 30s, where did it gone?

I wrote a native function that accept a pointer of `rocksdb::Iterator` ,  traverse from begin to end and return the size of db.

case 1: I open db with the rocksjni default options, get iterator with default readoptions, get the `nativeHandle_` of RocksIterator  through reflection, then pass it to above native function.

case 2: I open db with c++ default options, get iterator with default readoptions, and return the pointer of `rocksdb::Iterator` through a jni method, then pass it to above native function.

### Environment:

* java version "1.8.0_60"
* centos: 3.10.0-693.21.1.el7.x86_64
* rocksdbjni-5.11.3.jar

### Expected behavior

Both case should give me exactly same db size and basically consistent performance.

### Actual behavior
```
case1==> traverse1 size:112988527 cost time(ms):52207 
case2==> traverse2 size:112988527 cost time(ms):22433
```

### Steps to reproduce the behavior
1. download attachements
2. rename nativeImpl.txt to nativeImpl.cc, rename RocksDBIteratorTest.txt to RocksDBIteratorTest.java
3. move rocksdbjni-5.11.3.jar and librocksdb.so to the current directory.
4. execute below commands:

```
export CLASSPATH=:rocksdbjni-5.11.3.jar
export LD_LIBRARY_PATH=:.
javac RocksDBIteratorTest.java 
javah RocksDBIteratorTest
g++ -std=c++11 -fPIC -I/usr/java/jdk1.8/include -I/usr/java/jdk1.8/include/linux librocksdb.so -shared -o libNativeImpl.so nativeImpl.cc
java RocksDBIteratorTest dbpath
```

I want to improve the performance of jni iterator, but i was stuck here. Does anyone know what happened here or could give me some insights?

As I understand it，the difference here may caused by Options and ReadOptions, I have checked the source code, found that ReadOptions are exactly same in both cases. then i found below difference:
```java
public static RocksDB open(final String path) throws RocksDBException {
    // This allows to use the rocksjni default Options instead of
    // the c++ one.
    Options options = new Options();
    options.setCreateIfMissing(true);
    return open(options, path);
  }
```

So what is the special purpose of doing this?

[nativeImpl.txt](https://github.com/facebook/rocksdb/files/1977513/nativeImpl.txt)
[RocksDBIteratorTest.txt](https://github.com/facebook/rocksdb/files/1977514/RocksDBIteratorTest.txt)

**Comment by sagar0** [comment]
@adamretter Wondering if you have some time to dig deeper into this issue?

**Comment by adamretter** [comment]
> there is still a gap of 30s, where did it gone?

Even with various operations there is a performance overhead every time that the C++/Java boundary is crossed, which is once per key-value with an Iterator.

> So what is the special purpose of doing this?

The default Options object is created from Java rather than C++ code, so nothing particularly special.
