### ISSUE TITLE
Logger lines hard to read because long filenames are included

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#3820]
I am looking at LOG output for MyRocks in Percona Server and full pathnames used by the logger make this hard to read.

### Actual behavior

Options printed at the start don't have the filenames and are easier to read. The text that follows using the full filenames is hard to read because of line wrap.

```
2018/05/07-10:43:14.832627 7ff5472f8780 Options.compaction_options_fifo.allow_compaction: 0
2018/05/07-10:43:14.832630 7ff5472f8780 Options.compaction_options_fifo.ttl: 0
2018/05/07-10:43:14.832633 7ff5472f8780                   Options.table_properties_collectors: Rdb_tbl_prop_coll_factory; 
2018/05/07-10:43:14.832636 7ff5472f8780                   Options.inplace_update_support: 0
2018/05/07-10:43:14.832646 7ff5472f8780                 Options.inplace_update_num_locks: 10000
2018/05/07-10:43:14.832649 7ff5472f8780               Options.memtable_prefix_bloom_size_ratio: 0.000000
2018/05/07-10:43:14.832652 7ff5472f8780   Options.memtable_huge_page_size: 0
2018/05/07-10:43:14.832655 7ff5472f8780                           Options.bloom_locality: 0
2018/05/07-10:43:14.832658 7ff5472f8780                    Options.max_successive_merges: 0
2018/05/07-10:43:14.832661 7ff5472f8780                Options.optimize_filters_for_hits: 0
2018/05/07-10:43:14.832664 7ff5472f8780                Options.paranoid_file_checks: 0
2018/05/07-10:43:14.832667 7ff5472f8780                Options.force_consistency_checks: 0
2018/05/07-10:43:14.832669 7ff5472f8780                Options.report_bg_io_stats: 0
2018/05/07-10:43:14.832864 7ff5472f8780 [/mnt/workspace/percona-server-5.7-debian-binary-rocks/label_exp/ubuntu-xenial-64bit/percona-server-5.7-5.7.21-20/storage/rocksdb/rocksdb/db/version_set.cc:3098] Recovered from manifest file:./.rocksdb/MANIFEST-000006 succeeded,manifest_file_number is 6, next_file_number is 14, last_sequence is 2, log_number is 0,prev_log_number is 0,max_column_family is 1
2018/05/07-10:43:14.832871 7ff5472f8780 [/mnt/workspace/percona-server-5.7-debian-binary-rocks/label_exp/ubuntu-xenial-64bit/percona-server-5.7-5.7.21-20/storage/rocksdb/rocksdb/db/version_set.cc:3106] Column family [default] (ID 0), log number is 0
2018/05/07-10:43:14.832875 7ff5472f8780 [/mnt/workspace/percona-server-5.7-debian-binary-rocks/label_exp/ubuntu-xenial-64bit/percona-server-5.7-5.7.21-20/storage/rocksdb/rocksdb/db/version_set.cc:3106] Column family [__system__] (ID 1), log number is 11
2018/05/07-10:43:14.832945 7ff5472f8780 EVENT_LOG_v1 {"time_micros": 1525714994832934, "job": 1, "event": "recovery_started", "log_files": [11]}
2018/05/07-10:43:14.832951 7ff5472f8780 [/mnt/workspace/percona-server-5.7-debian-binary-rocks/label_exp/ubuntu-xenial-64bit/percona-server-5.7-5.7.21-20/storage/rocksdb/rocksdb/db/db_impl_open.cc:518] Recovering log #11 mode 1
2018/05/07-10:43:14.833033 7ff5472f8780 [/mnt/workspace/percona-server-5.7-debian-binary-rocks/label_exp/ubuntu-xenial-64bit/percona-server-5.7-5.7.21-20/storage/rocksdb/rocksdb/db/version_set.cc:2608] Creating manifest 14
```

### Steps to reproduce the behavior

Read LOG

**Comment by maysamyabandeh** [comment]
We can use the following to strip off the dir name: 
#define __FILENAME__ (__builtin_strrchr(__FILE__, '/') ? __builtin_strrchr(__FILE__, '/') + 1 : __FILE__)

**Comment by maysamyabandeh** [comment]
@mdcallag I am thinking of using the following to pass the file name to the compiler. If we do implement this, can we get Percona builds to use flag?
```
CXXFLAGS+=-D__FILENAME__='"$(notdir $<)"'
```

**Comment by georgelorchpercona** [comment]
I'm not sure we would want that as it would also change filename for all other logging, warnings, errors, and assertions, etc within the entire storage engine. If it were defined as something more relative to the root of the source tree then maybe it would pass.

**Comment by maysamyabandeh** [comment]
@georgelorchpercona Thanks for chiming in. I am not sure if I understand the argument. The problem is that the path name is too long in "all other logging, warnings, errors, and assertions, etc within the entire storage engine"; so any fix will essentially means changing them all.
As for filename vs. relative path I do not think it would make much difference. When we added this to the logging framework the intention was to provide some clue about where the log is coming from; filename is sufficiently unique within rocksdb repo, and would guide the debugger to the right line in the code.

**Comment by georgelorchpercona** [comment]
__FILENAME__ is used by many internal logging and assertions in MySQL storage engines. The MyRocks SE does not use the RocksDB CMakeLists.txt to build a RocksDB lib, it directly sources the needed code into MyRocks via the script get_rocksdb_files.sh script https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/storage/rocksdb/CMakeLists.txt#L12

Redefining __FILENAME__ for the entire engine is not likely something that will be accepted into our source tree and generally not a good idea. IMHO this is a nuisance issue and not worth altering the behavior/reporting of all things within the storage engine for one specific low level log.

**Comment by maysamyabandeh** [comment]
@georgelorchpercona the name is arbitrary. If `__FILENAME__` is already being used in percona builds we can use another var name.

**Comment by georgelorchpercona** [comment]
Grr, too early, not enough coffee, I was conflating \_\_FILENAME\_\_ with the C standard \_\_FILE\_\_. Sorry about that.

So yes, changing this will not impact storage engines as stated, but, just changing the RocksDB CMakeLists.txt will not fix this with RockDB as used within MyRocks as MyRocks does not build RocksDB via the RocksDB CMakeLists.txt. This definition would also need to be placed in the MyRocks CMakeLists.txt.

**Comment by maysamyabandeh** [comment]
Cool. So if we end up landing this change we can open an issue for myrocks to define this var in their CMakeLists.txt.

**Comment by solicomo** [comment]
> Talked to @siying offline. To avoid the overhead of maintaining this new var across builds we rather to do compile time processing to convert `__FILE__` to include only the file name and its next level directory. This would result into char* so the logging framework should also change to receive the resulting char* as a parameter to log statement instead of compile-time concatenation to the format string.
> Marking the task up-for-grab.

Hi @maysamyabandeh , do you have any idea about "compile time processing to convert `__FILE__` to include only the file name and its next level directory"?
