### ISSUE TITLE
Help~!!Makefile:66: recipe for target 'build' failed

### ISSUE THREAD

**Issue by bd506723144** [facebook/rocksdb#3833]
**make build**
cd cmd/neb; go build -ldflags "-X main.version=0.7.0 -X main.commit=e25246b8f718dd8c43355feea097882d1b17edd7 -X main.branch=testnet -X main.compileAt=`date +%s`" -o ../../neb-e25246b8f718dd8c43355feea097882d1b17edd7
go install github.com/nebulasio/go-nebulas/cmd/neb: open ../../neb-
**e25246b8f718dd8c43355feea097882d1b17edd7: permission denied
Makefile:66: recipe for target 'build' failed
make: *** [build] Error 1**

**Comment by bd506723144** [comment]
ubuntu 18 4

**Comment by riversand963** [comment]
Hi @bd506723144 , can you post this in the Facebook group: https://www.facebook.com/groups/rocksdb.dev and provide more details on how to reproduce the error you were seeing? Thanks.

**Comment by partylana** [comment]
whats the solution for this?
