### ISSUE TITLE
Add java static build target to travis

### ISSUE THREAD

**Issue by miasantreble** [facebook/rocksdb#3846]
`make rocksdbjavastatic` failed on 5.11.fb branch at some point, but luckily we caught it while doing some manual tests before making a 5.11 release. 
We should add the static target to travis as well to address this. We are only testing the dynamic target `make rocksdbjava` in travis at the moment.

**Comment by riversand963** [comment]
My understanding is that we are not adding new target to Travis. Closing. Reopen if otherwise.
