### ISSUE TITLE
Add a parameter to check SST files' checksum before ingesting it.

### ISSUE THREAD

**Issue by siying** [facebook/rocksdb#3847]
We should provide a choice for users to fail to ingest a file if the file has checksum error.

**Comment by atris** [comment]
JFYI I am working on this. Thanks

**Comment by atulagrwl** [comment]
I can see the flag being present inside IngestExternalFile function. Pull request for same - https://github.com/facebook/rocksdb/pull/4916

Hence, this issue can be closed.

**Comment by mrambacher** [comment]
Closing per above comment.
