### ISSUE TITLE
Potential problem in RocksDBSample.java according to the description on the wiki

### ISSUE THREAD

**Issue by sihuazhou** [facebook/rocksdb#3864]
### Expected behavior
According to the wiki https://github.com/facebook/rocksdb/wiki/Iterator#error-handling, people always need to call `RocksIterator#status()` after `Seek(), Next(), SeekToFirst(), SeekToLast(), SeekForPrev(), and Prev()`, even if `Valid()=true`. 

### Actual behavior
`RocksIterator#status()` is only used in a few loop, that is inconsistent with the description from the wiki.

(Additional, what is the best practice with using `RocksIterator` and the `status()`?)

**Comment by adamretter** [comment]
@sihuazhou If the Wiki is correct, then it does indeed seem like `RocksIterator#status()` should be called more frequently. @sagar0 Can you comment on whether that is the case?

**Comment by adamretter** [comment]
@StefanRRichter I think the Wiki will have to be updated again after #3810
