### ISSUE TITLE
Performance issue with get() after concatenating merge() - follow up

### ISSUE THREAD

**Issue by azagrebin** [facebook/rocksdb#3865]
The problem described originally by @StephanEwen in #1988 appeared again after switch from 5.8 to 5.9 as reported by @StefanRRichter in #2282 [here](https://github.com/facebook/rocksdb/issues/2282#issuecomment-360810599).
This issue is to explain the underlying cause of it and discuss possible solutions.

The problematic code called eventually by `Get` method:
https://github.com/facebook/rocksdb/blob/8bf555f487d1de84a4fb19cb97b9ae1a8dbebc60/db/memtable.cc#L697-L700
The similar thing happens in `get_context.cc`.

The `MergeOperator.ShouldMerge` was introduced for conditional partial merges before reaching the end of value to read out. It has currently default implementation which returns `false` (turned off) except `CassandraValueMergeOperator` and unit test.

The first call to `PushOperand` needs partial value pieces (operands) in one order and subsequent call to `GetOperands` in the reversed order. While discovering new operands, these two methods are always called and keep reversing the underlying vector back and forth. This degrades the `Get` method performance.

Possible fix could be to change `MergeOperator.ShouldMerge` interface method to accept e.g. size of operands as the current implementations basically care only about it.

**Comment by ajkr** [comment]
Without changing the API we could have `MergeContext` maintain a second vector with the reversed order operands. It could hold `Slice`s only so not much meaningful overhead (I guess). cc @sagar0.

**Comment by sagar0** [comment]
The original `MergeOperator::ShouldMerge` API was made more generic than needed, to allow users to make a decision based on the operands in the vector. Most of the users seem to only care about the number of operands though, and not much about the operands themselves. 

I can think of two ways to fix this going forward: 
1. As @azagrebin suggested, modify ShouldMerge or create an overload to take a size param. 
2. Pass the operands to `ShouldMerge` in reverse order i.e. by preserving the order of the operands from `MergeContext::PushOperand`, and document the order in the comments. This will have the benefit of users still having access to the operands to make their decisions on. The major downside is that we now depend on the user to read a comment to realize the order.

**Comment by azagrebin** [comment]
@sagar0
we could also 
- rename `MergeContext::GetOperands` to `MergeContext::GetOperandsDirectionForward` (will touch some other files)
- add `MergeContext::GetOperandsDirectionBackward`
- pass `MergeContext::GetOperandsDirectionBackward` to `ShouldMerge`

**Comment by azagrebin** [comment]
@sagar0 @ajkr 
do you have any preference about fixing this issue?

**Comment by ajkr** [comment]
@azagrebin I agree with your proposed solution. We can pass the output of `GetOperandsDirectionBackward` to `ShouldMerge` and document that the operands are in the reverse order of what would be passed to `FullMerge` or `FullMergeV2`. I'm ok with this change because we never documented before in what order the operands would be provided to `ShouldMerge`.

**Comment by ajkr** [comment]
Hi @azagrebin do you have an ETA? Our most recent two GitHub issues are both about this. We can contribute the fix if you haven't started or aren't far along. But I wanted to check with you first so we don't duplicate your work.

**Comment by azagrebin** [comment]
Hi @ajkr, thanks for asking, I have not started yet. Please, go ahead with the contribution. atm I would have time only next week to work on the fix.

**Comment by sagar0** [comment]
@azagrebin fixed this in #4266 and #4284. Thanks!
