### ISSUE TITLE
Is it possible to get common prefixes separated by delimiter like '/' in rocksdb?

### ISSUE THREAD

**Issue by winglq** [facebook/rocksdb#3880]
I have the following keys stored in rocksdb. Is it possible to add a new function in rocksdb to get the first lay of the key(folder1, folder2,... foldern) without iterate all the keys in the db? I am new to rocksdb. I am not sure whether this request is against to rocksdb's design.

Key:
```
folder1/obj1
folder1/obj2
...
folder1/objn
folder2/obj1
folder2/obj2
...
folder2/objn
...
foldern/objn
```

**Comment by ajkr** [comment]
Did you mean for a given prefix you want to return all keys with that prefix? For example, for "folder2/" do you want to iterate only over "folder2/obj1", "folder2/obj2", ..., "folder2/objn"? If that's what you're asking, then yes, you can use our prefix seek API: https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes

BTW we typically use the Facebook user's group for questions and use Github issues only for bug reports: https://www.facebook.com/groups/rocksdb.dev/

**Comment by winglq** [comment]
@ajkr I will go to the user's group link if I have new questions. Thanks.
For this question:
> Did you mean for a given prefix you want to return all keys with that prefix?
No.  I want the list ["folder1", "folder2", ...,"foldern"] without iterate over all the keys. This is a common prefix group of all the keys. If the number of keys is very big, the iteration will take a long time. So I am looking for a way to get the common prefix group quickly. Thanks.

**Comment by ajkr** [comment]
Oh sorry misunderstood. That type of query is unsupported.

Can you use Seek() to find the next folder efficiently? For example after seeing "folder1/obj1" you could call Seek("folder1\0") (i.e., giving it the first key greater than "folder1" according to your comparator) and it should position the iterator at "folder2/obj1".

**Comment by winglq** [comment]
@ajkr That's a great idea, thanks very much.
