### ISSUE TITLE
EnvPosixTest.RunImmediately test is failing intermittently on appveyor

### ISSUE THREAD

**Issue by sagar0** [facebook/rocksdb#3905]
EnvPosixTest.RunImmediately test is failing intermittently on appveyor, and seems like a re-run works in some cases. 

```
Starting env_test::EnvPosixTest.RunImmediately
...
env_test::EnvPosixTest.RunImmediately State: Completed
Note: Google Test filter = EnvPosixTest.RunImmediately
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from EnvPosixTest
[ RUN      ] EnvPosixTest.RunImmediately
c:\projects\rocksdb\env\env_test.cc(134): error: Value of: called.load()
  Actual: false
Expected: true
[  FAILED  ] EnvPosixTest.RunImmediately (136 ms)
[----------] 1 test from EnvPosixTest (137 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (141 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EnvPosixTest.RunImmediately
 1 FAILED TEST
```

### Expected behavior
The test is expected to pass. 

### Actual behavior
The test seems to be flaky, at least as seen from appveyor build history.

### Steps to reproduce the behavior
Look at these example appveyor runs:
https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.8615
https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.8595
https://ci.appveyor.com/project/Facebook/rocksdb/build/1.0.8606

**Comment by riversand963** [comment]
Test disabled in https://github.com/facebook/rocksdb/pull/4126
