### ISSUE TITLE
deadlock

### ISSUE THREAD

**Issue by bravoboy** [facebook/rocksdb#3916]
background:
1： set max_successive_merges > 0
2:   set enable_pipelined_write = true
gdb info thread:
<img width="1021" alt="r3" src="https://user-images.githubusercontent.com/9528477/40662073-e3ef45da-6387-11e8-8644-9a411a2fe14c.png">
thread 1 bt:
<img width="1267" alt="r1" src="https://user-images.githubusercontent.com/9528477/40662237-5803f66e-6388-11e8-9bdf-557f901daace.png">

thread 2 bt:
<img width="1263" alt="r2" src="https://user-images.githubusercontent.com/9528477/40662250-60318cb6-6388-11e8-8d35-1d6e3b8ebe0f.png">

thread 1  call WaitForMemTableWriters , so wait signal, here is wait thread 2 
thread 2 wait InstrumentedMutex mutex_;  this mutex owner is  thread 1.

**Comment by bravoboy** [comment]
my Solution：
1： modify InstrumentedMutex mutex_ , make it recursive
2：add trylock  where make perform_merge  true

**Comment by ajkr** [comment]
@yiwu-arbug Should we release the lock when calling `WaitForMemTableWriters`?

**Comment by bravoboy** [comment]
Should we release the lock when calling WaitForMemTableWriters?
----------------
i test it can slove deadlock

**Comment by yiwu-arbug** [comment]
Yes, we should release mutex in WaitForMemTableWriters(). Will send a fix.

**Comment by ajkr** [comment]
@yiwu-arbug how about #3923?

**Comment by yiwu-arbug** [comment]
@ajkr cool. I didn't notice the PR.
