### ISSUE TITLE
Proposal about binary compatible between patch-level release

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#3929]
### Expected behavior

Minimal binary compatible should be kept: dll of `5.9.2` should be binary compatible to `5.9.0`.

### Actual behavior

app crashed after replace `5.9.0` dll with `5.9.2`.

### Steps to reproduce the behavior

Replace `fb.5.9.0`(branch `fb.5.9.myrocks`) dll with `5.9.2`'s dll, and run app without recompilation.

### Description

We have an applicaiton using `5.9.fb.myrocks` as dynamic library, after we upgraded rocksdb to [5.9.2](), the app crashed, then we checked the header files changes, we found new field `seq_per_batch` of `DBOption` introduced an binary incompatiblility.

Binary compatible(esp. dynamic library) is hard to keep, for RocksDB, it is impossible to keep binary compatible between major version, and is impractical to keep binary compatible between minor version.

### Proposal

So at least binary compatible should be kept between patch-level versioning, we proposed the following rules:
1. If it is really needed to add a field to an user level `struct` or `class`, the field should be put in a `padding` position.
2. If we can not find a `padding` position for this new field, this code change should be rejected, or the minor version number should be bumped.

**Comment by ajkr** [comment]
Thanks, this is an interesting idea. We should bring it up in our next team meeting and get back to you. I also hope we can expand our current guarantee, which is API compatibility across minor versions and patch versions. ABI compatibility across patch versions sounds like a good next step.

**Comment by ajkr** [comment]
We discussed it today. We agreed not to make API changes within a minor version.

One thing I didn't notice earlier is you mentioned using the "5.9.fb.myrocks" branch. That branch was created for a specific internal use case, so that isn't our official 5.9. The official public releases are tags with names like "v5.9.2".

**Comment by rockeet** [comment]
@ajkr Very thanks for your discussion and agreement.

About the `5.9.fb.myrocks` branch, Maybe our understanding is different, we think all branch `major.minor.fb*` should be relatively stable, and `master` is the only unstable and active developing branch.

**Comment by ajkr** [comment]
The branches named "x.y.fb" are the branches from which we create the tagged releases: https://github.com/facebook/rocksdb/releases. If you pick up changes from "x.y.fb" before they're available in a tagged release, it's somewhat riskier as we haven't finished testing those changes internally yet.

For branches named "x.y.fb.<suffix>", like "5.9.fb.myrocks", those are forks of the corresponding "x.y.fb" branch that also include changes specific to that internal user. I wouldn't advise relying on those branches.
