### ISSUE TITLE
Make it easier for users to load options from option file and set shared block cache

### ISSUE THREAD

**Issue by siying** [facebook/rocksdb#3940]
Right now, it requires several dynamic casting for users to set the shared block cache to their option struct cast from the option file:

https://github.com/facebook/rocksdb/blob/master/include/rocksdb/utilities/options_util.h#L36-L42

If people don't do that, every CF of every DB will generate its own 8MB block cache. It's not a usable setting. So we are dragging every user who loads options from the file into such a mess.

Instead, we should allow them to pass their cache object to LoadLatestOptions() and LoadOptionsFromFile(), so that those loaded option structs will have the shared block cache.

**Comment by miasantreble** [comment]
@rashmishrm  has implemented this in https://github.com/facebook/rocksdb/pull/5063
