### ISSUE TITLE
Improving DeleteRange performance

### ISSUE THREAD

**Issue by petermattis** [facebook/rocksdb#3959]
### Background

https://github.com/facebook/rocksdb/issues/3634 discusses the performance woes caused by range tombstones. In particular, the existing `RangeDelAggregator` approach significantly slows down iterator creation when there are many tombstones in the memtable or L0 sstables. Each such tombstone is added via `RangeDelAggregator::AddTombstone` which internally adds the tombstone to a map. If the tombstones overlap they are collapsed and there is O(n) work. If the tombstones don't overlap they can't be collapsed and there is O(nlogn) work to insert the tombstones into an `stl::multimap`. The addition of tombstones to `RangeDelAggregator` at iterator creation has a dramatic impact on perf. The numbers below are using a benchmark written in Go, but the Go wrappers are trivial. The benchmark tests iterator creation when the memtable contains 0, 1, 100, 1000 and 10000 range tombstones. The "old" numbers are a variation where the tombstones overlap. The "new" numbers show the perf when the tombstones do not overlap (and thus can't be collapsed).

```
RocksDBDeleteRangeNewIterator/tombstones=0-8      1.26µs ± 4%   1.23µs ± 3%   -2.49%  (p=0.034 n=10+10)
RocksDBDeleteRangeNewIterator/tombstones=1-8      2.54µs ± 3%   2.47µs ± 2%   -2.52%  (p=0.002 n=10+10)
RocksDBDeleteRangeNewIterator/tombstones=10-8     5.49µs ± 4%   7.61µs ± 9%  +38.60%  (p=0.000 n=10+10)
RocksDBDeleteRangeNewIterator/tombstones=100-8    49.9µs ± 2%   79.7µs ± 3%  +59.68%  (p=0.000 n=10+10)
RocksDBDeleteRangeNewIterator/tombstones=1000-8    660µs ± 2%   1038µs ± 2%  +57.25%  (p=0.000 n=10+10)
RocksDBDeleteRangeNewIterator/tombstones=10000-8  8.99ms ± 2%  14.15ms ± 2%  +57.35%  (p=0.000 n=10+10)
```

This performance degradation stinks. Is it problematic? Yes. It is one of the root problems in https://github.com/cockroachdb/cockroach/issues/24029 which will likely require hacky workarounds above the RocksDB layer. The TLDR from that issue is that adding a range tombstone to one part of the key space affects the performance of another part of the key space. Ideally, this wouldn't be true at all or the impact would be minimal.

@benesch's proposal in https://github.com/facebook/rocksdb/issues/3634#issuecomment-375002993 is one approach for improving range tombstone performance. I think that approach will run into difficulties due to concurrency and I'm not quite clear on how it would handle tombstones in the memtable. I'm going to propose a more significant change to the range tombstone storage that will allow directly querying the memtable and sstable range tombstones without decoding them into the `RangeDelAggregator`.

### Range Tombstone Storage

Range tombstones are currently encoded in both memtables and sstables by storing them under `<start-key>#<seqnum>` with the value holding the tombstone's `<end-key>`. If range tombstones were guaranteed to not overlap, we could query this storage directly. For example, consider the tombstones:

```
a-c#1
d-f#3
```

If we want to determine if the key `e#2` is deleted, we'd do a lower-bound search (`Iterator::Seek`) to land on the tombstone `d-f#3` and then check the bounds of the tombstone and the sequence number to see if the tombstone is visible to the read operation and later than the key's sequence number. Note that this only works if the range tombstones do not overlap. Consider the overlapping scenario:

```
a-f#3
a-c#1
```

Now if we do a search for key `e` we find the `a-c#1` and we wrongly consider the key alive when it is deleted. To find all of the possible tombstones that overlap the key we would have to iterate backwards from that search point. How far back do we have to iterate? All the way to the beginning of the range tombstone map. No bueno.

### Alternative Range Tombstone Storage

To avoid needing to scan backwards through the entire range tombstone map, we can add an invariant: whenever two range tombstones overlap we split them at the overlap points so the overlapping portions have exactly the same start and end keys. A picture should make this clearer. Starting with the tombstones below:

```
5: a-----------m
3:      f------------s
1:          j---------------z
```

These tombstones get split at the overlap points:

```
5: a----f---j--m
3:      f---j--m-----s
1:          j--m-----s------z
```

When these split tombstones are inserted into something like the memtable they would look like:

```
a-f#5
f-j#5
f-j#3
j-m#5
j-m#3
j-m#1
m-s#3
m-s#1
s-z#1
```

A query for whether the key `p#2` is deleted would seek to find the tombstone `m-s#1`, check that this tombstone contains the key, and then walk backward as long as the start key of the tombstones is the same and we haven't reached a tombstone sequence number that is newer than read sequence number. As soon as the start key changes we know we're no longer in a containing tombstone. 

The downside to this approach is an increase in the number of range tombstones when there are overlaps. This seems acceptable to me. 

### Migration

Changing the range tombstone storage format in the memtable is trival. Changing the format in sstables would be done by storing new format range_del_blocks under a new sstable property and converting an old format block upon loading the sstable. 

### Unresolved Questions

* The above proposal outlines how to support querying the range tombstones directly in their storage format and would be suitable for `DB::Get` operations. We'd also want to support efficient integration of range tombstones into iterators and here my thinking is much less clear. Querying some sort of `RangeTombstoneIterator` at each key would be one approach, but that query would be O(logn+k) where `n` is the number of tombstones and `k` is the number of overlaps at the queried key. With iteration we should be able to avoid the `logn` component, keeping track of the active tombstones in some sort of heap. The details are fuzzy. Would this be an integration with `MergingIterator`? Or would it be easier to maintain `RangeTombstoneIterator` as a parallel structure, similar to the `RangeDelAggregator` approach? How would the `RangeTombstoneIterator` be advanced? Are there difficulties in supporting `Prev`?
* The logic to split tombstones upon insertion into the memtable is relatively straightforward. I'm not familiar enough with the memtable concurrency to know what complexities there would be in splitting existing tombstone entries while those entries are being read. It is possible we could avoid splitting existing entries, but instead add overlapping entries at the same sequence number. 
* The creation of `range_del_block` is currently done via `RangeDelAggregator::AddToBuilder`. I'm hazy on what parts (if any) of `RangeDelAggregator` would be kept. 

Ok, that's enough to digest for now. We (the CockroachDB folks) are invested in fixing the range tombstone performance problem and are planning to provide engineering resources to do so. We need guidance. Does the above sound feasible? Are there any additional complexities that I didn't mention?

**Comment by benesch** [comment]
> Changing the range tombstone storage format in the memtable is trival. Changing the format in sstables would be done by storing new format range_del_blocks under a new sstable property and converting an old format block upon loading the sstable.

It occurs to me that we could avoid the need for a migration if we performed the tombstone splitting at the the time the SST is loaded into memory and left the on-disk format the same.

**Comment by ajkr** [comment]
Hi Peter, thanks a lot for the post. This seems like a clean way to make the range tombstones binary searchable without any expensive collapsing work in the read path. Will need to think a lot more, but to  start writing my thoughts:

- For the approach of splitting the tombstones in memtable while preserving their seqnums, I think our memtable can't support it. If multiple existing tombstones overlap with the new tombstone, we'd need to split all existing ones atomically. If not done atomically, readers could see an intermediate state like the following when `a-m#5` is added:

```
5: a----f---j--m
3:      f---j--------s
1:          j--m-----s------z
```

Then if I read `n#2` and check range deletions, we find `m-s#1` and conclude the key isn't deleted.
 
Our memtable's limitation is that it atomically writes keys simply by (1) inserting keys with seqnums greater than the DB's reader-visible seqnum, then (2) updating the DB's reader-visible seqnum to make them all visible at once. So it relies on the invariant that seqnum being updated is always increasing.

So I think we may need to explore the alternative you mentioned more for adding overlapping entries at the same (new) seqnum. Then would the range tombstone's seqnum need to be stored as part of the value?

- Regarding #3634, I think it'd be ok to hold a `RangeDelAggregator` for each live `Version`, but not for `SuperVersion`s since, like you said, there'd be concurrency issues with range deletions inserted into the memtable. Using that approach, flush/compaction would build a collapsed form of range deletions in all SST files, and then those immutable collapsed forms would be readily available to readers. I didn't have any idea how to solve the problem for range deletions in memtable or in older snapshots. So your approach seems better as it seems to solve the problem generally.

**Comment by petermattis** [comment]
> Our memtable's limitation is that it atomically writes keys simply by (1) inserting keys with seqnums greater than the DB's reader-visible seqnum, then (2) updating the DB's reader-visible seqnum to make them all visible at once. So it relies on the invariant that seqnum being updated is always increasing.
>
> So I think we may need to explore the alternative you mentioned more for adding overlapping entries at the same (new) seqnum. Then would the range tombstone's seqnum need to be stored as part of the value?

Thanks for the details. I'll explore the alternative I suggested. I forgot to link to it before, but I created a little playground to verify my thinking and that the proposal wasn't completely broken. See https://github.com/cockroachdb/cockroach/pull/26323. (Go because that's what I'm most familiar with right now. Translating this to C++ should be easy.)

**Comment by petermattis** [comment]
> So I think we may need to explore the alternative you mentioned more for adding overlapping entries at the same (new) seqnum. Then would the range tombstone's seqnum need to be stored as part of the value?

The overlapping entries bit works, but the new entry created when an existing entry is "split" needs to use the existing entry's sequence number. Consider:

```
5: a-----------m
3: a------------------------z
1: a------------------------z
```

After adding the two `a-z` tombstones we'd have a structure like:

```
a-z#3
a-z#1
```

When the `a-m` tombstone is added we have to "split" the existing tombstones at `m` creating two new `m-z` tombstones. These can't exist at the same sequence number. 

Rather that using the new sequence number, I think we can create these new tombstones at the existing tombstone's sequence number and change the value to hold both the end key of the tombstone and an additional sequence number indicating when the tombstone was created. For the above example we'd have a structure like:

```
a#5 -> m,5
a#3 -> z,3
a#1 -> z,1
m#3 -> z,5
m#1 -> z,5
```

Lookups in this structure will need to consider both the sequence number in the key as well as the sequence number in the value. For example, a read of `p#2` at sequence number 4 would need to completely ignore the `m#3` and `m#1` tombstones because those tombstones are not guaranteed to providing the invariant to this data structure (`m#3` might exist before `m#1`). This doesn't seem unworkable, just unfortunate additional complexity.

**Comment by ajkr** [comment]
Sorry for the delay, thanks a lot for the idea. I was wondering whether the seqnums could be swapped, i.e., put the tombstone's seqnum in the value, and put the insertion seqnum in the key. Using your example, it'd look like:

```
a#5 -> m,5
a#3 -> z,3
a#1 -> z,1
m#5 -> z,3
m#5 -> z,1
```

One problem that came up is we can't have multiple values for `m#5`. I believe we only need to store the latest one. If a query is for a snapshot with seqnum >= 5, we do not care about the `m#5 -> z,1` because it's fully covered by `m#5 -> z,3`, so we can store only the latter:

```
a#5 -> m,5
a#3 -> z,3
a#1 -> z,1
m#5 -> z,3
```

Now when we query it, we can use a normal snapshot iterator. A snapshot with seqnum 4 would see this subset of keys:

```
a#3 -> z,3
a#1 -> z,1
```

On this snapshot, we query `SeekForPrev("p")`, which positions the iterator at `a#3 -> z,3`. Now we know `p#2` is covered.

Or let's say we have `j#4` in the database, and we want to lookup latest value for "j". We do `SeekForPrev("j")` on the memtable iterator, it gets positioned at `a#5 -> m,5`, and we determine it's deleted.

I will work through some more examples and try to verify whether it's correct. What do you think?

**Comment by petermattis** [comment]
> What do you think?

I'm not seeing anything obviously wrong with this approach, but the devil is in the details. I'll try to find time to adapt my existing testbed to this approach and see if it uncovers any problems.

**Comment by ajkr** [comment]
I started thinking about how iterator will work with this approach. Here's a first stab.

Consider we have two files each with range deletions.

```
SST_1           SST_2
a#10 -> c,10    b#30 -> e,30
c#20 -> f,20
```

Now these files are compacted together. We can iterate through each one's range deletions and create a new range deletion meta-block.

```
SST_1             SST_2
->a#10 -> c,10  ->b#30 -> e,30
c#20 -> f,20
```

We insert `a#10 -> c,10` and `b#30 -> e,30`, then advance the iterator in SST_1.

```
SST_1             SST_2
a#10 -> c,10    ->b#30 -> e,30
->c#20 -> f,20
```

We insert `c#20 -> f,20` and notice an interesting case: the starting point of `c#20 -> f,20` is below `b#30 -> e,30`. So we insert `c#30 -> e,30`. Then advance SST_2's iterator.

```
SST_1             SST_2
a#10 -> c,10      b#30 -> e,30
->c#20 -> f,20
```

Another interesting case happened when we advanced: `b#30 -> e,30` ended before a deletion underneath it. So we need to add `e#30 -> f,20`. Finally we've created:

```
a#10 -> c,10
b#30 -> e,30
c#30 -> e,30
c#20 -> f,20
e#30 -> f,20
```

The above idea feels a bit complicated, so we could also consider keeping the `RangeDelAggregator` as-is for SST files, and caching the full collapsed form in each live `Version`. That'd be a bit hacky as the memtable format will differ from the SST file format, but I believe it can work, get good perf, and avoid compatibility issues...

**Comment by ajkr** [comment]
Oh yes you are right. For snapshot we do not pin a `Version` so snapshot reads would not have a collapsed map readily available. Slow snapshot reads would probably be a problem for somebody at some point...

Anyways I thought a bit more about your splitting/format change ideas and how to integrate them with iterators, etc. It seems workable - will try to write something up this week.

**Comment by benesch** [comment]
Other ancillary related work that we discussed today:

  * Automatically triggering flushes and compactions when range tombstones pile up. Perhaps by artificially inflating the sizes of memtables/SSTs based on how much data the range tombstones cover.
  * Splitting range tombstones based on the grandparent SST boundaries during compaction.

**Comment by abhimadan** [comment]
Closing this issue since read performance with range tombstones is a lot better now. The ideas for tombstone-aware flush/compaction scheduling and smarter compaction boundaries are not implemented yet, but I'll make separate issues for those.
