### ISSUE TITLE
Flush/Compaction performance issue across combined HDD and SSD CFs 

### ISSUE THREAD

**Issue by burtonli** [facebook/rocksdb#3972]
We have a rocksdb created with leveled-compaction with multiple column families (CFs), some of CFs are using HDD to store big and less frequently accessed data and others are using SSD.
When there are continuously write traffics going on to all CFs, the compaction thread pool is mostly occupied by those slow HDD compactions, which blocks fully utilize SSD bandwidth.

### Expected behavior
Fully unitize the write throughput for both HDD and SSD. 
For HDD storage, we found it's better to give a smaller threadpool for compaction to get a better  performance, as HDD cannot handle too many concurrent reads and writes well.
But for SSD storage, it's better to have a larger threadpool (e.g. 4X of HDD thread pool size) size for maximize the compaction performance.
It seems there is no way to config different allowed compaction tasks per storage or per column family.

### Actual behavior
The problem is threadpool is shared globally, so we cannot give a best threadpool size for both HDD and SSD, so we ends up with a size in the middle, neither the best for HDD nor for SSD, and at the same time slow HDD compactions block SSD compactions.

As we can see from the snapshot, raw HDD (D: drive) throughput stuck at less than 20MB/sec by giving too many compaction tasks at the same time, and it can be reach over 30MB/sec if it uses a smaller threadpool size. At the same time, SSD (K: drive) throughput is spiky, by most of time it get queued for the threadpool, and when it got a thread, it can finish the compaction job in a short time.

![compactionissue](https://user-images.githubusercontent.com/17753898/41175521-3582384e-6b12-11e8-8e72-1670d1738d73.png)

### Steps to reproduce the behavior

Create a rocksdb with leveled compaction, adding at least two column families, one on SSD and another one HDD, and set max background jobs to 24 (or any other reasonable number). Keep writing to all column families.

Cc: @yuslepukhin

**Comment by burtonli** [comment]
Thanks for the quick response! The data we store on HDD is huge and fairly cold comparing with what's on the SSD. There are ~100 rocksdb instances on one machine, with about 3TB+ data on HDD and 1TB data on SSD in total. HDD has ~50 QPS for both read and write, and we want to achieve ~10MB/s random write throughput before compressed.
Previously, they (SSD, HDD data) used to be different db instances, and at that time, it seems HDD can handle such traffic by carefully tuning db options and thread pool size. But we merged them into one db, by configing HDD and SSD data into CFs, since we need across db transaction write support. Then this becomes an noticeable issue on some machines which received higher write traffics.
I'm currently prototyping an idea with @yuslepukhin to add a global outstanding task control per storage in SstFileManagerImpl to share among db instances, rather than creating more threadpools (because the actual CF for flush or compaction is determined after it's thrown into a pool), to see if it can fix the problem.

**Comment by yiwu-arbug** [comment]
@burtonli Instead of CFs, can you use multiple DB instance instead if you don't need atomic writes to HDD and flash simultaneously? If you cannot, you can probably implement an Env wrapper to change the thread pool behavior, but I don't if how difficult it is.

**Comment by burtonli** [comment]
@yiwu-arbug  We do need atomic write and transaction across CFs.

I have a PR to resolve the issue: https://github.com/facebook/rocksdb/pull/4332

**Comment by anand1976** [comment]
Closing  the issue since the PR #4332 has landed.
