### ISSUE TITLE
How to improve performance to get all keys in the case of very big data

### ISSUE THREAD

**Issue by vedatech** [facebook/rocksdb#3973]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

**Comment by riversand963** [comment]
@vedatech Thanks for your interest in RocksDB. We currently use Github issues to track bugs and up-for-grab tasks. Given that this is a very general, performance-optimization question, I highly recommend that you migrate this post to our RocksDB Developers Public Facebook group and include more details if you are looking for a specific answer in a timely manner. I'm closing this issue. Thanks for your understanding.
