### ISSUE TITLE
re-open db failed for prepared transactions when WAL disabled

### ISSUE THREAD

**Issue by baoxuezhao** [facebook/rocksdb#3976]
Hello,

We are using the rocksdb Two Phase Commit Transaction to build a distributed transactional storage service.
Since we also use a RAFT consensus library for multi-replica consistency, and the raft algorithm internally requires a Write Ahead Log for state recording, replay and recovery, we set disableWAL=true in WriteOptions for better write performance and only depends on the raft WAL for data recovery.
This works well when rocksdb transactions are committed without the prepare step. However, when we first prepare and then commit transactions, the rocksdb instance will be in failure when re-opened. the error message is 
"**Operation timed out: Timeout waiting to lock key**".

From the PessimisticTransaction code (utilities/transactions/pessimistic_transaction.cc# WriteCommittedTxn::PrepareInternal), we noticed the following code snippet: 

Status WriteCommittedTxn::PrepareInternal() {
  WriteOptions write_options = write_options_;
  write_options.disableWAL = false;
  WriteBatchInternal::MarkEndPrepare(GetWriteBatch()->GetWriteBatch(), name_);

That is to say, the prepare ignores user settings and forces the WAL enabled. In our case, when re-open the database, all user-committed transactions will be recovered  since the prepare is force recorded in WAL but not for the commit, and a later transaction writing a same key cannot acquire the lock, leading to the db open timed out.

I wonder what is the design consideration of forcing prepare WAL enabled but not for commit. Anyway, when they disable WAL, it is users' responsibility to rely on other recovery mechanism than rocksdb.

I can come up with two solutions for our case: 
1) prepare use user's setting for disableWAL, or
2) like prepare, force commit WAL enabled ignoring user's setting.
The first one has better write performance. 

Are the above two solutions reasonable? 
Or is there any better solutions for our case (specifically, disable WAL and use 2PC)?

Best,
Thanks 
Baoxue

**Comment by maysamyabandeh** [comment]
As you correctly noted disableWAL is not quite compatible with 2PC. The reason is that ::Prepare's promise is to remember the prepared record even after a restart and it is not possible to do that without using a WAL. We might add support for WAL-less 2PC in future by relaxing ::Prepare's guarantee.
For the moment you can skip ::Prepare to truly disable WAL, i.e., the application call NoOp when 2PC Prepare is required and calls ::Commit when Commit is required. Otherwise the norm is that after restart the application asks RocksDB for the prepared transactions, commit and rollback them based on what it finds in its application log, and then start new transactions. Checkout ::GetAllPreparedTransactions.

**Comment by baoxuezhao** [comment]
**For the moment you can skip ::Prepare to truly disable WAL, i.e., the application call NoOp when 2PC Prepare is required and calls ::Commit when Commit is required**.
We really require the the ::Prepare phase as we are doing distributed commits, but we do not require the internal recovery of prepared transactions, as we rely on RAFT's recovery.

**Otherwise the norm is that after restart the application asks RocksDB for the prepared transactions**
we can do this with ease. However, how can I make rocksdb reopen successfully w/o lock conflict, 
after two transactions operating the same key prepared and committed with WAL disabled?

Thanks!
