### ISSUE TITLE
InlineSkipList::RecomputeSpliceLevels eats lots of cpu.

### ISSUE THREAD

**Issue by corndolly** [facebook/rocksdb#3981]
Test it on 5.7.3,   write buffer size:  128M,     min_write_buffer_number_to_merge:  2

Only a few writes, no read,  i saw there were lots of cpu spend on InlineSkipList::RecomputeSpliceLevels with high latency.

I want to know is it one bug because there are only few writes.   
What's the method purpose?

**Comment by riversand963** [comment]
@corndolly 
Can you provide steps to reproduce this issue? Also, what is your OS, compiler, etc. ?

**Comment by corndolly** [comment]
reproduce is not difficult. 
1.  start one rocksdb instance (write buffer size: 128M, min_write_buffer_number_to_merge: 2 )
2.  give a few writes to it.  
3.  run "perf top" on shell,  you could see InlineSkipList::RecomputeSpliceLevels costs lots of cpu.

BTW.   os (Linux version 3.10.0)    compiler (gcc 7.2.0,  glibc 2.17)

**Comment by yiwu-arbug** [comment]
@corndolly What InlineSkipList::RecomputeSpliceLevels do is basically binary search for the insert position in the skip-list. It is normal most cpu time is spent on it. Do you mind share how large the memtable it is, how large is your key-value size, and what does latency look like for the method?

**Comment by corndolly** [comment]
Thanks @yiwu-arbug @riversand963 for your attention.

> Also, in your profiling experiment, did you issue a few writes to RocksDB and then run perf top on another shell?

Yes

> Can you try using perf record and perf report with db_stress and see if you can reproduce the problem? It will also help if you can share your testing code snippet.

Nowadays, i thinks it is normal.  Because the issue show up in our production cluster,  and it hold many rocksdb instances,   one of them costs cpu about 14%,  but others only 4%,  the latency is about 20% slower.   I check the requests and found there were one hot key for the slow instance.  Now i suspect the performance killer is the hot key.

> Do you mind share how large the memtable it is, how large is your key-value size, and what does latency look like for the method?

memtable size: 128M,   max number: 4,   min-to-merge: 2
kv payload is about 50 byte
About the latency for the method is hard to measure, but the cpu cost here is about 30% in perf top.

**Comment by yiwu-arbug** [comment]
@corndolly It could be normal for the method to take cpu if it is a write heavy workload. Please reopen if you think otherwise and have more evidence.
