### ISSUE TITLE
Manual compaction triggers write stalling - should be able to bypass

### ISSUE THREAD

**Issue by gbitzes** [facebook/rocksdb#3982]
Hi,

Let's say I have a 2TB RocksDB dataset, and want to fully recompact everything, because of changing the compression algorithm.

As it is now, once a manual compaction request is issued, pending compaction bytes will jump to some ridiculous value, causing writes to stall completely. I believe CompactRangeOptions::allow_write_stall will not help in this case, as writes will have to stall no matter what the current write load is.

Maybe a CompactRangeOptions::bypass_write_stall option would come in handy, which could prevent write stalling entirely while this compaction is running. The best would be to be able to "ignore" a particular compaction for the purposes of write stalling, but this might be more difficult to implement.

AFAIK, soft/hard_pending_compaction_bytes_limit is not changeable dynamically through SetOptions either, so I can't simply set the limit to some high value before triggering full recompaction, and restore it later..

Thanks

**Comment by ajkr** [comment]
As a workaround you could try dynamically setting "disable_auto_compactions=true" before the manual compaction and unsetting it afterwards. We don't stall writes while automatic compactions are explicitly disabled.

**Comment by gbitzes** [comment]
Thanks! I'll try out the workaround.

**Comment by yiwu-arbug** [comment]
@gbitzes please reopen if you have further question.
