### ISSUE TITLE
use marked_for_compaction to optimize read after too many delete

### ISSUE THREAD

**Issue by markrui3** [facebook/rocksdb#3987]
As we all know, when we delete similiar keys with same prefix too many times, the Seek() and Next() will be slow because we must skip too many keys with tag of kTypeDeletion. The dirty entry will only be erased after the compaction. If we want to speed up Seek(), we must compact in advance. 
### So what about compact one file after it dump from memtable to sst?
When flush memtable to level0, the parameter **marked_for_compaction** is used to mark that the file need compact. But nowhere can it turn to be true. 
After setting the parameter to be true, the file will be compacted in the **BackgroundCompaction** and code is like

```
void LevelCompactionBuilder::SetupInitialFiles() {
  // Find the compactions by size on all levels.
  bool skipped_l0_to_base = false;
  for (int i = 0; i < compaction_picker_->NumberLevels() - 1; i++) {
    start_level_score_ = vstorage_->CompactionScore(i);
    start_level_ = vstorage_->CompactionScoreLevel(i);
    assert(i == 0 || start_level_score_ <= vstorage_->CompactionScore(i - 1));
    // compute the compact score and blabla............
  }

  // if we didn't find a compaction, check if there are any files marked for compaction
  if (start_level_inputs_.empty()) {
    is_manual_ = true;
    parent_index_ = base_index_ = -1;
    PickFilesMarkedForCompaction(); // notice here!
    if (!start_level_inputs_.empty()) {
      compaction_reason_ = CompactionReason::kFilesMarkedForCompaction;
    }
  }
}
```
if no file need compact after computing scores, the files marked before will be compacted.
So if we mark some files at the begining, they will be compacted at this point. 
**And we can use that to optimize read after too many delete.**

**Comment by anand1976** [comment]
Check out the NewCompactOnDeletionCollectorFactory (https://github.com/facebook/rocksdb/blob/master/include/rocksdb/utilities/table_properties_collectors.h#L23-L27) and see if it serves your purpose. This needs to be appended to Options::table_properties_collector_factories

**Comment by markrui3** [comment]
Yes! That's exactly what I want! And user-defined collector factory is useful! Thanks!

**Comment by markrui3** [comment]
But I still have one question. 
When memtable flush to sst, duplicate keys will directly dump into sst. 
Why not just delete duplicated keys and only keep the lastest sequence number? @anand1976

**Comment by anand1976** [comment]
@markrui3 When memtable is flushed to sst, only the key with the latest sequence number is written, performing a merge as necessary. Older sequence numbers are written only if there is a snapshot where they are visible

**Comment by markrui3** [comment]
Er, ok, I read the code for one days and probobly know the logic. Thanks a lot.
