### ISSUE TITLE
Java API: Manual WAL Flush

### ISSUE THREAD

**Issue by anhldbk** [facebook/rocksdb#4008]
*I'm sorry if this is NOT a suitable way to ask a question against using RocksDb*

In the C++ version, we've got [DBOptions::manual_wal_flush](https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log#dboptionsmanual_wal_flush). How can I enable such option with our Java wrapper?

**Comment by sagar0** [comment]
`manual_wal_flush` hasn't been added to the RocksDB Java API yet. Feel free to send a pull request if you are interested in contributing. 

Also, RocksDB Developers facebook group or our google mailing list might be better suited for asking questions instead of github issues.

**Comment by anhldbk** [comment]
@sagar0 Thank you very much!

**Comment by sagar0** [comment]
Created #4034.
