### ISSUE TITLE
Add FlushWAL and manual_wal_flush to RocksJava API

### ISSUE THREAD

**Issue by sagar0** [facebook/rocksdb#4034]
manual_wal_flush option and FlushWAL API were first introduced in #2345. These should be ported to RocksJava API.

**Comment by atulagrwl** [comment]
I see both values already present in java files. https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/DBOptions.java#L1140
https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/RocksDB.java#L3686

Hence this issue can be closed now.
