### ISSUE TITLE
Improper usage of std::string results in a zero size string in Blob_log_reader

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#4059]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Actual behavior

https://github.com/facebook/rocksdb/blob/master/utilities/blob_db/blob_log_reader.cc#L30

`Reader::ReadSlice` makes use of `std::string` as output buffer. It reserves the space but does not update `std::string` for the actual amount of data it contains. It should call `resize()` after the actual amount read is known. So the `std::string` instance still thinks it has a size of 0 which may affect its operation.

Still better to call `resize()` both to reserve the space and to set the final size of the string.

### Steps to reproduce the behavior
 Code review

**Comment by riversand963** [comment]
@yiwu-arbug , could you PTAL?
