### ISSUE TITLE
RocksDB failed due to error C2338 when build with MSVC

### ISSUE THREAD

**Issue by shanshan0309** [facebook/rocksdb#4062]
Hi All,

I tried to build RocksDB with VS2017 Update 7 on Windows. It failed to build due to the C2338. This issue can be reproduced from master revision 346d106. Could you please help take a look at this? Thanks!

**Expected behavior:**
build successfully

**Actual behavior:**
The whole log file please see attachment.
[RocksDB_x64_build.log](https://github.com/facebook/rocksdb/files/2140403/RocksDB_x64_build.log)
       "D:\RocksDB\build_x64\rocksdb.sln" (Rebuild target) (1) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj.metaproj" (Rebuild target) (17) ->
       "D:\RocksDB\build_x64\rocksdb-shared.vcxproj" (Rebuild target) (26) ->
         c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.14.26428\include\type_traits(1271,1): error C2338:  You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member type would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conformant behavior. [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
       c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.14.26428\include\type_traits(1271,1): error C2338: 	static_assert(_Always_false<_Aligned>, [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]
       c:\program files (x86)\microsoft visual studio\2017\enterprise\vc\tools\msvc\14.14.26428\include\type_traits(1271,1): error C2338: ^ [D:\RocksDB\build_x64\rocksdb-shared.vcxproj]

**Steps to reproduce the behavior:**
1.Open VS2017 x64 Native tools command tool
2.git clone https://github.com/facebook/rocksdb D:\RocksDB\src
3.cd D:\RocksDB
4.mkdir build_x64 && pushd build_x64
5.cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 ..\src
6.msbuild build_x64\rocksdb.sln /p:Configuration=Release;Platform=x64 /t:Rebuild /m /p:BuildInParallel=true

Thanks,
Shanshan

**Comment by shanshan0309** [comment]
Thanks @riversand963 for looking into this issue.
I tried your fix and it works well.

**Comment by riversand963** [comment]
#4061 should already have been merged. I'm closing this issue now. Please let us know if anything comes up. Thanks.

**Comment by shanshan0309** [comment]
Thank you @riversand963.
RocksDB passed in latest master revision.
