### ISSUE TITLE
C - Column Family Options casting fails

### ISSUE THREAD

**Issue by oltdaniel** [facebook/rocksdb#4083]
### Expected behavior
The cast should pass without an error, and add the column families to the main options.

### Actual behavior
The C executable crashes with an `Segmentation fault (core dumped)` error. The `gdb` backtrace and source code can be found [here](). The error is caused [here](https://gist.github.com/oltdaniel/4abbc79aaa31aeac73aed1878958e400#file-main-c-L37) and can be traced back with [gdb](https://gist.github.com/oltdaniel/4abbc79aaa31aeac73aed1878958e400#file-gdb-md) to [`options.cc`](https://github.com/facebook/rocksdb/blob/master/options/options.cc#L103).

### Steps to reproduce the behavior
Since the error occurred before the database will be opened, just compile and run the gist file stuff.

**Comment by ajkr** [comment]
I think `family_options` should be an array of 10 pointers.

**Comment by miasantreble** [comment]
Right, you can check https://github.com/facebook/rocksdb/blob/master/db/c_test.c#L1169 as an example of setting up `column_family_options` for `rocksdb_open_column_families`
Basically the `num_column_families` you pass should match the actual number of column families in the array `column_family_options`
