### ISSUE TITLE
how to fix java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by bestans** [facebook/rocksdb#4088]
source code:
```java
public static void main(String[] args) {
        final Options options = new Options()
		        .setCreateIfMissing(true);
		try {
			OptimisticTransactionDB txnDb1 = OptimisticTransactionDB.open(options, "d:/rocksdb_test");
		} catch (RocksDBException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
	}
```

Report error:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: org.rocksdb.OptimisticTransactionDB.open(JLjava/lang/String;)J
	at org.rocksdb.OptimisticTransactionDB.open(Native Method)
	at org.rocksdb.OptimisticTransactionDB.open(OptimisticTransactionDB.java:40)
	at bestan.test.TestMain.main(TestMain.java:63)
```

Environment:
windows 7 64bit + Eclipse(Luna Service Release 2 (4.4.2)) + JDK1.7 + RocksJava 5.13.2

I have tried different JDK versions (1.7 / 1.8)，different Eclipse versions , different RocksJava  versions，but just not work. help me, please!

**Comment by adamretter** [comment]
@bestans Perhaps you have the same problem as described here: https://github.com/facebook/rocksdb/issues/3307#issuecomment-399741126

If so the next release of 5.14.x should be out in the next few days. In the mean time you could try compiling yourself with the `PORTABLE` flag as described in that issue and the Wiki.

**Comment by bestans** [comment]
@adamretter  thank you! I will try compiling myself and wait new release.

**Comment by bestans** [comment]
````aa

**Comment by bestans** [comment]
@adamretter I think it isn't the same as #3307 (comment). I have set PORTABLE  flag in CMake generation, and check  the /arch:AVX2 flag not to be set, but it still not work.

otherwise,
```java
OptimisticTransactionDB.open("d:/rocksdb_test") // can work
```
but 
```java
OptimisticTransactionDB.open(options, "d:/rocksdb_test"); //can't work
```

**Comment by adamretter** [comment]
That is very strange as it is implemented here - https://github.com/facebook/rocksdb/blob/master/java/rocksjni/optimistic_transaction_db.cc#L24

We also have a test case which uses that here: https://github.com/facebook/rocksdb/blob/master/java/src/test/java/org/rocksdb/OptimisticTransactionDBTest.java#L123

**Comment by bestans** [comment]
@adamretter I found that java cmakelist.txt doesn't contain optimistic_transaction_db.cc and some other files, so interface like Java_org_rocksdb_OptimisticTransactionDB_open__JLjava_lang_String_2 doesn't generate.
[https://github.com/facebook/rocksdb/blob/master/java/CMakeLists.txt](url)

**Comment by adamretter** [comment]
@bestans looks like this is being addressed here: https://github.com/facebook/rocksdb/pull/4015

**Comment by sagar0** [comment]
I believe this is fixed.
