### ISSUE TITLE
performance regression in merge operator in RocksDB >= 5.9 when merging many values

### ISSUE THREAD

**Issue by tcwalther** [facebook/rocksdb#4094]
When updating RocksDB to any version >= 5.9 (I tried 5.9.2, 5.11.3, 5.13.2 - 5.8.8 still works fine), the merge operator in our code base becomes extremely slow, such that a merge of ~20000 values (each around 5 bytes) takes 0.3 seconds (before that it was barely measurable). I'm not sure yet whether I can reproduce this in a simple test case - it's probably a bit complicated, as I would assume that you would've caught this yourself in your regular testing if it was easy.

I am implementing `FullMergeV2`, and `PartialMergeMulti` returns `false` since I need to merge in order (the value is a set to which items can be added and deleted).

I was wondering whether there were any changes I should be aware of that were introduced in 5.9? I couldn't find anything obvious in the changelog. Any hints would be highly appreciated.

**Comment by ajkr** [comment]
Thanks for reporting. This sounds similar to #3865. I believe @azagrebin is working on a fix.

**Comment by tcwalther** [comment]
@ajkr thank you so much for your reply. Yes, this sounds indeed like a duplicate. I'm happy for you to close this issue if you prefer, and I will track the other issue instead.
