### ISSUE TITLE
Slow Get with lots of merge records

### ISSUE THREAD

**Issue by mperham** [facebook/rocksdb#4095]
I have a uint64 counter which I'm incrementing with the Merge operator, possibly hundreds or even thousands of times per second.  As the system works, calling Get on the associated key gets slower and slower as the Merge records pile up, many seconds or even minutes.  How can I tune RocksDB to compact these Merge records more often?

I'm seeing this behavior in 5.9.2 and 5.13.2.

**Comment by yiwu-arbug** [comment]
You can try the mex_sucessive_merge option.

**Comment by mperham** [comment]
I set it to 1000 but saw no diff in performance.

**Comment by yiwu-arbug** [comment]
@mperham maybe a much lower value for it?

**Comment by mperham** [comment]
In fact, this did solve it.  I set the value on the wrong set of options, the Stats CF was using a different set of options from the other CFs because it had to enable the merge operator for that CF.  Thank you!
