### ISSUE TITLE
wiki mistake

### ISSUE THREAD

**Issue by jazy333** [facebook/rocksdb#4130]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
https://github.com/facebook/rocksdb/wiki/Simulation-Cache
### Expected behavior
NewSimCache(normal_block_cache, 
  10 * 1024 * 1024 * 1024 /* sim_capacity 10GB */);
### Actual behavior

NewSimCache(normal_block_cache, 
  1024 * 1024 * 1024 * 1024 /* sim_capacity 10GB */);

**Comment by miasantreble** [comment]
@jazy333 Thanks for reporting, feel free to update the wiki

**Comment by yiwu-arbug** [comment]
updated. thanks.
