### ISSUE TITLE
VersionSet::LogAndApply and DBImpl::IngestExternalFile running concurrently cause data loss

### ISSUE THREAD

**Issue by DorianZheng** [facebook/rocksdb#4152]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
pass

### Actual behavior
fail

### Steps to reproduce the behavior
```
./db_stress -set_options_one_in=20 -ingest_external_file_one_in=20 -nooverwritepercent=0 -ops_per_thread=10000
```

**Comment by ajkr** [comment]
Looking.

**Comment by riversand963** [comment]
@DorianZheng Thanks for looking into this. I have PR #4157 that should be able to fix it.

**Comment by DorianZheng** [comment]
#4157
