### ISSUE TITLE
Could not see statistics when opening RocksDB in read only mode

### ISSUE THREAD

**Issue by gaojieliu** [facebook/rocksdb#4168]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
I was trying to use RocksDB in read only mode to boost the read performance, but I could not see the statistics, which is working in regular read-write mode.
### Expected behavior
See statistics.
### Actual behavior
Could not see valid statistics.
### Steps to reproduce the behavior
I was using '**org.rocksdb:rocksdbjni:5.14.2**'
Code snippet:
```java
    final Cache cache = new LRUCache(8 * 1024 * 1024);
    final Statistics statistics = new Statistics();
    statistics.setStatsLevel(StatsLevel.ALL);

    Options options =
        new Options()
            .setCreateIfMissing(true)
            .setStatistics(statistics)
            .setTableFormatConfig(new BlockBasedTableConfig().setBlockCache(cache));
db = RocksDB.openReadOnly(options, dataFolder);
// Issue read request
    for (Map.Entry<String, String> entry : dataPairs.entrySet()) {
      Assert.assertEquals(db.get(entry.getKey().getBytes()), entry.getValue().getBytes());
    }

    System.out.println(statistics.toString());
```

Result:
rocksdb.block.cache.miss COUNT : 1
rocksdb.block.cache.hit COUNT : 0
rocksdb.block.cache.add COUNT : 0
rocksdb.block.cache.add.failures COUNT : 0
rocksdb.block.cache.index.miss COUNT : 0
rocksdb.block.cache.index.hit COUNT : 0
rocksdb.block.cache.index.add COUNT : 0
rocksdb.block.cache.index.bytes.insert COUNT : 0
rocksdb.block.cache.index.bytes.evict COUNT : 0
rocksdb.block.cache.filter.miss COUNT : 0
rocksdb.block.cache.filter.hit COUNT : 0
rocksdb.block.cache.filter.add COUNT : 0
rocksdb.block.cache.filter.bytes.insert COUNT : 0
rocksdb.block.cache.filter.bytes.evict COUNT : 0
... ...

**Comment by adamretter** [comment]
As far as I can see, the Java code is correctly calling the appropriate C++ methods.

Could it be that you have not performed enough operations on the db for the statistics to register yet?

**Comment by gaojieliu** [comment]
Hi @adamretter 
Thanks for your reply.

Here is my test code:
``
  private static final String DATA_BASE_DIR = "/tmp/data";
  private static final String keyPrefix = "key_";
  private static final String valuePrefix = "value_";

  private String getTempDatabaseDir(String storeName) {
    String storePath = DATA_BASE_DIR + "/" + storeName;
    File storeDir = new File(storePath);
    if (!storeDir.mkdirs()) {
      throw new RuntimeException("Failed to mkdirs for path: " + storePath);
    }
    storeDir.deleteOnExit();
    return storePath;
  }

  private void removeDir(String path) {
    File file = new File(path);
    if (file.exists() && !file.delete()) {
      throw new RuntimeException("Failed to remove path: " + path);
    }
  }

  private Map<String, String> generateInput(int recordCnt, boolean sorted) {
    Map<String, String> records;
    if (sorted) {
      BytewiseComparator comparator = new BytewiseComparator(new ComparatorOptions());
      records = new TreeMap<>((o1, o2) -> {
        Slice s1 = new Slice(o1.getBytes());
        Slice s2 = new Slice(o2.getBytes());
        return comparator.compare(s1, s2);
      });
    } else {
      records = new HashMap<>();
    }
    for (int i = 0; i < recordCnt; ++i) {
      records.put(keyPrefix + i, valuePrefix + i);
    }
    return records;
  }

  @Test
  public void testReadOnlyMetrics() throws RocksDBException {
    Map<String, String> dataPairs = generateInput(100, true);
    String dataFolder = getTempDatabaseDir("test_storesdfasfqwer");

    EnvOptions envOptions = new EnvOptions();
    envOptions.setUseDirectWrites(false);

    final Cache cache = new LRUCache(8 * 1024 * 1024);
    final Statistics statistics = new Statistics();
    statistics.setStatsLevel(StatsLevel.ALL);

    Options options =
        new Options()
            .setCreateIfMissing(true)
            .setStatistics(statistics)
            .setTableFormatConfig(new BlockBasedTableConfig().setBlockCache(cache));

    String sstFilePath = dataFolder + "/tmp_sst_file";
    SstFileWriter writer = new SstFileWriter(envOptions, options);
    writer.open(sstFilePath);
    dataPairs.forEach((k, v) -> {
      try {
        writer.put(k.getBytes(), v.getBytes());
      } catch (RocksDBException e) {
        e.printStackTrace();
      }
    });
    writer.finish();
    writer.close();

    RocksDB db = RocksDB.open(options, dataFolder);

    IngestExternalFileOptions ingestOptions = new IngestExternalFileOptions();
    ingestOptions.setMoveFiles(true);

    List<String> fileList = new ArrayList<>();
    fileList.add(sstFilePath);

    db.ingestExternalFile(fileList, ingestOptions);

    db.close();
    db = RocksDB.openReadOnly(options, dataFolder);

    // Issue read request
    for (Map.Entry<String, String> entry : dataPairs.entrySet()) {
      Assert.assertEquals(db.get(entry.getKey().getBytes()), entry.getValue().getBytes());
    }

    System.out.println(statistics.toString());

    db.close();
    RocksDB.destroyDB(dataFolder, options);
    removeDir(dataFolder);
  }
``

Here is the output snippet:
``
rocksdb.block.cache.miss COUNT : 1
rocksdb.block.cache.hit COUNT : 0
rocksdb.block.cache.add COUNT : 0
rocksdb.block.cache.add.failures COUNT : 0
rocksdb.block.cache.index.miss COUNT : 0
rocksdb.block.cache.index.hit COUNT : 0
rocksdb.block.cache.index.add COUNT : 0
rocksdb.block.cache.index.bytes.insert COUNT : 0
rocksdb.block.cache.index.bytes.evict COUNT : 0
rocksdb.block.cache.filter.miss COUNT : 0
rocksdb.block.cache.filter.hit COUNT : 0
rocksdb.block.cache.filter.add COUNT : 0
... ...
``
If I don't reopen the database in read-only mode by removing the following lines, the metrics will be emitted as expected.
``
    db.close();
    db = RocksDB.openReadOnly(options, dataFolder);
``
Output snippet:
``
rocksdb.block.cache.miss COUNT : 2
rocksdb.block.cache.hit COUNT : 99
rocksdb.block.cache.add COUNT : 1
rocksdb.block.cache.add.failures COUNT : 0
rocksdb.block.cache.index.miss COUNT : 0
rocksdb.block.cache.index.hit COUNT : 0
rocksdb.block.cache.index.add COUNT : 0
rocksdb.block.cache.index.bytes.insert COUNT : 0
rocksdb.block.cache.index.bytes.evict COUNT : 0
rocksdb.block.cache.filter.miss COUNT : 0
rocksdb.block.cache.filter.hit COUNT : 0
rocksdb.block.cache.filter.add COUNT : 0
``

Let me know if I missed anything.

**Comment by adamretter** [comment]
@gaojieliu Ah okay, I missed that you were using read-only mode.

@sagar0 Do we report stats in read-only mode?

**Comment by ajkr** [comment]
hm, it seems we're not updating many stats in read-only mode. In `DBImpl::GetImpl`, there's lots of calls to `RecordTick` like for bytes read or keys read. But those are totally missing in `DBImplReadOnly::Get`. We should fix this...

**Comment by gaojieliu** [comment]
@ajkr Who will be in charge of adding metrics for read-only user case?
Or is it intentional not to add any metrics since stats could degrade read-only performance?
