### ISSUE TITLE
RocksDB Java memory leak?

### ISSUE THREAD

**Issue by shiyanxin** [facebook/rocksdb#417]
we recently updated our rocksdb build, and noticed that there is a continuous memory grow even after setting the jvm option for max heap size. The previous version of our build does not have such problem. We are not sure this is absolutely due to the new build yet since we also have a few other application level changes (although the new build is still our current biggest suspect).

 While investigating other possibilities, I just want to bring this up  in case there is an known issue of a memory leak in some version of rocksdb java. 

Can someone let me know if you have any insights into this? Or how we can debug such memory leak in rocksdb java. (we used to yourkit to profile our application, but it does not include the c++ part)

**Comment by fyrz** [comment]
@bayesian any news here ?

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by manojlds** [comment]
No updates on this one yet?

**Comment by adamretter** [comment]
@bayesian I am closing this issue as there have been now recent updates.

**Comment by manojlds** [comment]
@adamretter it would be good to at least mention what these "recent updates" are.

**Comment by manojlds** [comment]
Or did you mean "no" instead of "now"?

**Comment by adamretter** [comment]
@manojlds Indeed I meant "no", I have corrected above...

**Comment by areyohrahul** [comment]
Hey @bayesian , were you able to solve this issue? My workload is quite similar to yours and I've been facing this issue as well
