### ISSUE TITLE
doc: outdated description of stats_dump_period_sec in RocksDB Tuning Guide wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#4175]
`This is 3600 by default, which means that stats will be dumped every 1 hour. ` should be `This is 600 by default, which means that stats will be dumped every 10 minutes.`.  Since https://github.com/facebook/rocksdb/blob/v5.14.2/include/rocksdb/options.h#L627 has the following code:

```
  // if not zero, dump rocksdb.stats to LOG every stats_dump_period_sec
  // Default: 600 (10 min)
  unsigned int stats_dump_period_sec = 600;
```

**Comment by miasantreble** [comment]
fixed, thanks for reporting
