### ISSUE TITLE
Option `max_total_wal_size` does not take effect

### ISSUE THREAD

**Issue by fuyufjh** [facebook/rocksdb#4180]
### Expected behavior

I set `max_total_wal_size` value to 1MB when opening a new RocksDB.

Expect the log in disk should be cleared (and memtable being flushed) once its size reaches 1MB.

### Actual behavior

**The WAL file didn't stop growing.** Much more than 1MB.

### Steps to reproduce the behavior

I am using `rocksdbjni`. You may reproduce it with following code on latest RocksDB version (5.14.2)

```java
import org.rocksdb.*;
import java.nio.ByteBuffer;
import java.util.UUID;

public class RocksDBTest {
    public static void main(String[] args) throws Exception {
        Options dbOptions = new Options().setMaxTotalWalSize(1024 * 1024).setCreateIfMissing(true);
        WriteOptions writeOptions = new WriteOptions().setSync(true);
        RocksDB db = RocksDB.open(dbOptions, "/tmp/RocksDBTest");
        WriteBatch writeBatch = new WriteBatch();

        int key = 0;
        while (key < 100000) {
            for (int i = 0; i < 100; i++) {
                byte[] keyBytes = ByteBuffer.allocate(4).putInt(key++).array();
                byte[] valueBytes = UUID.randomUUID().toString().getBytes();
                writeBatch.put(keyBytes, valueBytes);
            }
            db.write(writeOptions, writeBatch);
            writeBatch.clear();
        }
        writeBatch.close();
        writeOptions.close();
        db.close();
    }
}
```

**Comment by maysamyabandeh** [comment]
can you paste i) the ls result of roclsdb dir after the test, and ii) the LOG content?

**Comment by fuyufjh** [comment]
Sure @maysamyabandeh 

1) Result of RocksDB dir

```
$ ls -lah RocksDBTest
total 8512
drwxr-xr-x   9 eric  staff   288B  7 26 10:37 .
drwx------+ 14 eric  staff   448B  7 26 10:37 ..
-rw-r--r--   1 eric  staff   4.1M  7 26 10:37 000003.log
-rw-r--r--   1 eric  staff    16B  7 26 10:37 CURRENT
-rw-r--r--   1 eric  staff    33B  7 26 10:37 IDENTITY
-rw-r--r--   1 eric  staff     0B  7 26 10:37 LOCK
-rw-r--r--   1 eric  staff    15K  7 26 10:37 LOG
-rw-r--r--   1 eric  staff    13B  7 26 10:37 MANIFEST-000001
-rw-r--r--   1 eric  staff   4.5K  7 26 10:37 OPTIONS-000005
```

2) The LOG is too long so I paste them [here](https://gist.github.com/fuyufjh/e048023812e3b29d95b51dc385e081f3).

Ps. I did some modification to the Java code in issue so that you can reproduce this result exactly.

**Comment by maysamyabandeh** [comment]
this option takes effect only when we have multiple column families. we should clarify that in the inline docs. When there is only one cf, then wal is switched when memtable is flushed, so you can control the size by controlling write_buffer_size

**Comment by fuyufjh** [comment]
Thank you! @maysamyabandeh 

As you said, this fact is not doced in any inline doc or Wiki.

BTW, I just read some code and found that logic in [db_impl_write.cc#L712-L713](https://github.com/facebook/rocksdb/blob/master/db/db_impl_write.cc#L712-L713) as below:

```
if (!single_column_family_mode_ && total_log_size_ > GetMaxTotalWalSize()) {
    status = SwitchWAL(write_context);
}
```

I think we can remove this condition `!single_column_family_mode_` here and everything will work as expected (at least as I expected 😀). How about it?
