### ISSUE TITLE
doc: wrong description about max_size_amplification_percent  on RocksDB Tuning Guide wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#4181]
[RocksDB Tuning Guide](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide) has the following text:

>  Default is 200, which means that a 100 byte database could require up to 300 bytes of storage. 100 bytes of that 300 bytes are temporary and are used only during compaction.

`100 bytes of that 300 bytes` should be `200 bytes of that 300 bytes` since it conflicts with the  following comment of [max_size_amplification_percent](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/universal_compaction.h#L48):

```
  // Default: 200, which means that a 100 byte database could require upto
  // 300 bytes of storage.
  unsigned int max_size_amplification_percent;
```

**Comment by siying** [comment]
Feel free to go ahead and edit the page.

**Comment by yaojingguo** [comment]
@siying I don't have the permission to edit the page.
