### ISSUE TITLE
RocksDB "Failed to Flush State Store" Error on Startup of Streams Application

### ISSUE THREAD

**Issue by chrisjdole** [facebook/rocksdb#4184]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Within a Kafka Streams application, expected to open and access a RocksDB state store.

### Actual behavior
Get "Failed to flush state store" exception without a root cause message.

The error happens right away, just after Spring Boot app startup.

Note that I've deleted the cache multiple times in the local storage location.

I tried (through the RocksDB configuration (see attached) to up the debugging level. So far, I have not gotten a root cause to show up other than that shown in the stack trace.

### Steps to reproduce the behavior
See attached file for context.
[Streams Case Info.txt](https://github.com/facebook/rocksdb/files/2228135/Streams.Case.Info.txt)

**Comment by ajkr** [comment]
If you're still seeing this and suspect a RocksDB issue, please upload the RocksDB info log (in a file called LOG in your database directory). If you know which RocksDB API is failing and what Status object it's returning, that'd also be helpful.
