### ISSUE TITLE
[ARM64 CentOS] Rocksdb build on arm64 Centos servers

### ISSUE THREAD

**Issue by dhilipkumars** [facebook/rocksdb#4185]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
builds sucessfully

### Actual behavior
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march
cc1plus: error: unknown value ‘native’ for -march

### Steps to reproduce the behavior
git clone on an arm64 centos server and 
```
make clean shared_lib
```

Hi All,
Has it been successfully been built in arm64 servers yet? or is the port yet to happen? we were using it in X86_64 and recently moved to arm64 looks like its not supported out of the box.   Any clue on how to make this work in Arm64 servers (not on andriod or iphone ports)?

Thanks in Advance,
Dhilip

**Comment by maysamyabandeh** [comment]
You will have better luck asking such question in user group https://www.facebook.com/groups/rocksdb.dev where users who have tried rocksdb in different platforms can chime in.

**Comment by adamretter** [comment]
AFAIK it hasn't been ported yet. as @maysamyabandeh suggests, the mailing list is probably a better place to discuss this. The place to start looking is probably `port/README.md` and `port/port_posix.h`.

**Comment by dhilipkumars** [comment]
cc @gfosco @siying @yuslepukhin 
Hi all just trying to get more attention for this, this a blocking issue for us.   Are there any plans to officially port and support Rocksdb on Arm64 servers?

And facebook blocked my new account to start the discussion in the dev.list. 
![image](https://user-images.githubusercontent.com/10920260/43279053-e3abfa5c-90da-11e8-9bdd-0f945e21f859.png)

**Comment by yuslepukhin** [comment]
I am not aware of any efforts to create such a port.

**Comment by adamretter** [comment]
We now build on Arm64. See the makefile targets: `rocksdbjavastaticdockerarm64v8` and `rocksdbjavastaticdockerarm64v8musl`
