### ISSUE TITLE
Add CompactRangeOptions for Java

### ISSUE THREAD

**Issue by christian-esken** [facebook/rocksdb#4195]
The `CompactRangeOptions` are not (yet) available in the Java layer. Are there any plans to add them?

If not, is there interest in a PR from me to make it available? If yes, then I need to know whether the Java `CompactRangeOptions` can be a POJO or must be a RocksObject. I think a POJO could be enough, as `CompactRangeOptions` would not be used for a long time, as they can be created on a per-request basis.

**Comment by sagar0** [comment]
I don't know of anyone working on porting CompactRangeOptions to Java. So feel free to send out a PR if you are interested. 

If you look at other options classes, like `WriteOptions`, `FlushOptions`, `IngestExternalFileOptions`, etc, all of them extend from RocksObject. So CompactRangeOptions also should also be a RocksObject, if you decide to implement one. Also, some of the existing APIs might need to be deprecated if CompactRangeOptions is added to RocksJava.

**Comment by christian-esken** [comment]
Thanks for the info. I started to implement it. Do I need to do anything about the "up-for-grabs"?
I now also came to the conclusion that extending from RocksObject is beneficial, e.g. to inherit defaults.
About the process: Its a standard github "fork and do a PR" procedure, right? (PS: I will prepare the CLA soon).

**Comment by adamretter** [comment]
@christian-esken The important thing in RocksJava is to think about the ownership of objects.

If there is a C++ object which needs to be created on the heap for the Java object to "wrap", then the Java object must *own* the C++ object to ensure it is deleted from the heap when no-longer needed. The RocksObject hierarchy of classes in Java help with this. As @sagar0 mentioned, you should try and follow the example of one of the simpler options classes such as `CompressionOptions`.

Let me know if you want any other pointers, I am happy to assist you in this...

**Comment by christian-esken** [comment]
What is the best way to check whether my method signature in java/rocksjni/rocksjni.cc is correct? I added ``Java_org_rocksdb_RocksDB_compactRange__J_3BI_3BIJJ``, but that is more or less a best-effort name. If I understand JNI correctly then javah would generate a stub file so I could look it up - I cannot find that stub though. 

As a reference here is the commit:
https://github.com/christian-esken/rocksdb/commit/ddc0e94fe1ef589a4afdd5b0ba8e150e6e32dbd2

**Comment by adamretter** [comment]
@christian-esken Best way us to write the Java code first. Then you can have the function signatures generated for you by running `make rocksdbjava`. Look in `java/include` and you should find the C++ header file that corresponds to your native method declarations, complete with functions signatures.

**Comment by christian-esken** [comment]
That worked. Next challenge: Get the librocksdbjni lib to include the new class. Example:

The following was created in org_rocksdb_CompactRangeOptions.h :
> JNIEXPORT jlong JNICALL Java_org_rocksdb_CompactRangeOptions_newCompactRangeOptions(JNIEnv *, jclass);

Looks fine, so I implemented that, but the code does not get built into the librocksdbjni library. I see other "new options" symbols, but not my `Java_org_rocksdb_CompactRangeOptions_newCompactRangeOptions`:
```
$ nm target/librocksdbjni-osx.jnilib | grep -i compact.*new.*Options
0000000000022040 T _Java_org_rocksdb_CompactionOptionsFIFO_newCompactionOptionsFIFO
00000000000220a0 T _Java_org_rocksdb_CompactionOptionsUniversal_newCompactionOptionsUniversal
```
I guess that I need to edit CMakeLists.txt (I did that) to create a new Makefile. But when I run `cmake .` in either the main folder or the java folder I get a totally disfunctional Makefile (e.g. without "rocksdbjava" target even when enabling JNI via `ccmake .`).

**Comment by adamretter** [comment]
So there are two build systems. Make and CMake. You need to edit both CMakeLists.txt, and Makefile and java/Makefile

**Comment by christian-esken** [comment]
I think I already edited everything that is necessary:
- java/CMakeLists.txt - Edited
- java/Makefile - Edited
- Makefile - Not edited, as I only have changes below java/ . Other classes like CompressionOptions are also not in here.
- CMakeLists.txt - Not edited. Same reason

After it I did a "make clean" and "make rocksdbjava", with the same results. My `Java_org_rocksdb_CompactRangeOptions_newCompactRangeOptions` is not found in the newly created librocksdbjni . Anything else that I need to do, like a manual cmake run or such?

**Comment by adamretter** [comment]
@christian-esken Did you edit `src.mk`?

**Comment by christian-esken** [comment]
Nope. I didn't know that file. I see now it is included from Makefile. It is a bit astonishing to find JNI_NATIVE_SOURCES both within the java folder (java/CMakeLists.txt) and and also outside the Java folder (src.mk). I'll try that tomorrow.

**Comment by adamretter** [comment]
So the Make build and the CMake build are completely separate things. Sadly that means when adding files to the build you have to do it twice

**Comment by christian-esken** [comment]
Thanks for the explanation. It works now end-to-end. I have build a jar with the jni lib inside and am using the CompactRangeOptions in my application. I will complete the implementation and create a PR.

**Comment by christian-esken** [comment]
Thanks for the explanation. It works now end-to-end. I have build a jar with the jni lib inside and am using the CompactRangeOptions in my application. I will complete the implementation and create a PR.

**Comment by christian-esken** [comment]
PR is now open, and CI is done: https://github.com/facebook/rocksdb/pull/4220

**Comment by ableegoldman** [comment]
Hi @christian-esken @adamretter  --I know this was a while ago but when adding CompactRangeOptions you deprecated several of the existing RocksDB.compactRange() to leverage this new options object. However none of the new APIs allow you to specify a CompactRangeOptions without also specifying a begin, end range.

Is this a gap in the API? We would like to compact the entire range (and don't know the upper end) while taking advantage of the options. I may be able to submit a PR if so but would like to know if this was intentional or not

**Comment by ableegoldman** [comment]
Ah nvm, I was working with v5.18 but I see this is fixed in v6 by passing in null -- ignore the above
