### ISSUE TITLE
doc: some options are deprecated now in Universal Compaction wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#4197]
The following 3 options are deprecated now:

- options.source_compaction_factor
- options.max_grandparent_overlap_bytes 
- options.expanded_compaction_factor

**Comment by maysamyabandeh** [comment]
@yaojingguo feel free to update the wiki when you see a mistake.

**Comment by yaojingguo** [comment]
@maysamyabandeh I don't have the permission to edit the wiki. Could you please apply the changes to the wiki page?
