### ISSUE TITLE
doc: wrong description about Universal Compaction in RocksDB Tuning Guide wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#4198]
In https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide, there is the following text:

> For universal compaction all files are in L0. 

It is wrong since `num_levels` can have a value larger than 1.

**Comment by maysamyabandeh** [comment]
@yaojingguo if it is obvious mistake feel free to update the wiki. Otherwise that would be more like a question, which is the best to be brought up in the user group https://www.facebook.com/groups/rocksdb.dev/
