### ISSUE TITLE
Improving cache misses for FullFilterBitsReader

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#4213]
[RocksDB Bloom Filter](https://github.com/facebook/rocksdb/wiki/RocksDB-Bloom-Filter) claims that one key incurs at most one cache miss:

> Full filter limits the probe bits for a key to be all within the same CPU cache line. This ensures fast lookups by limiting the CPU cache misses to one per key.

But `data_` member of `FullFilterBitsReader` is not cache line aligned. So it is possible that one key incurs two cache misses in the case of full bloom filters.

**Comment by maysamyabandeh** [comment]
@yaojingguo if it is obvious mistake feel free to update the wiki. Otherwise that would be more like a question, which is the best to be brought up in the user group https://www.facebook.com/groups/rocksdb.dev/
