### ISSUE TITLE
doc: image link is broken in Iterator Implementation wiki page

### ISSUE THREAD

**Issue by yaojingguo** [facebook/rocksdb#4215]
[Higher quality diagram](https://s9.postimg.org/h8c9jz0zz/Screen_Shot_2016_08_09_at_5_21_47_PM.png) is broken.

**Comment by yaojingguo** [comment]
@maysamyabandeh Can you open the image link?

**Comment by KOBA789** [comment]
@yaojingguo FYI: `postimg.org` seemed to be renamed with `postimg.cc`

https://s9.postimg.cc/h8c9jz0zz/Screen_Shot_2016_08_09_at_5_21_47_PM.png
