### ISSUE TITLE
 Symbol not found: _ZDICT_isError

### ISSUE THREAD

**Issue by benoitc** [facebook/rocksdb#4241]
### Expected behavior

use latest rocksdb with zstd compression enabled.

### Actual behavior

Using latest ZSTD version (1.3.5) enabling the ZSTD compression trigger the following error in our code:  `Symbol not found: _ZDICT_isError`. 

This error has also been reproduced there : https://jira.mariadb.org/browse/MDEV-16525

### Steps to reproduce the behavior

1) Build rocksdb with ZSTD
2) Create a program enabling this compression. It will return the error.

**Comment by ajkr** [comment]
Can you provide your build/run commands? I am running with zstd 1.3.5 (with zstd compression enabled) and haven't seen a problem.

**Comment by benoitc** [comment]
@ajkr sorry for the late answer. Original ticket is there:
https://gitlab.com/barrel-db/erlang-rocksdb/issues/56

The build of rocksdb is done there: https://gitlab.com/barrel-db/erlang-rocksdb/blob/master/deps/Makefile

As you can see we are building ourself zstd then rely on the static library generated in this folder. Let me know if you need more informations or some tests :)

**Comment by ajkr** [comment]
Sorry I did not find any reference to ZSTD in the Makefile here: https://gitlab.com/barrel-db/erlang-rocksdb/blob/master/deps/Makefile. Are the ZSTD header files you're building against also v1.3.5?

**Comment by ajkr** [comment]
For the error in https://jira.mariadb.org/browse/MDEV-16525, it looks like our bug. The ZSTD dictionary APIs became available for static linking in v0.8.0, and available for dynamic linking in v1.1.3. However, we only check the version is v0.8.0+ to including dictionary generation code. I will fix that but am not certain it's the same issue as yours.

**Comment by benoitc** [comment]
@ajkr oh sorry I realised I didn't push the branch. I will update the ticket once i've pushed the branch.  I believe we are experimenting the same issue as mariadb anyway.

**Comment by ajkr** [comment]
#4295 may help.

**Comment by ajkr** [comment]
cool, you can try setting the environment variable `ROCKSDB_DISABLE_ZSTD=1` to avoid the dependency (and other optional dependencies can be avoided in a similar way; see "build_tools/build_detect_platform")

**Comment by Charles909090** [comment]
YELPNINALREADY KNOW ALL THESE ERRORS HAVE BEEN DELETED OF AS SOON AS PEOPLE SEE THEY ONLY AN CAUSE OF AN ISSUE FOR EVEN PUT IT THERE OVER ALL MINE CASH JUST SO THEY CAN THEFT.
