### ISSUE TITLE
Memory usage is incorrectly reported for all block sizes in case ROCKSDB_MALLOC_USABLE_SIZE is not defined

### ISSUE THREAD

**Issue by yuslepukhin** [facebook/rocksdb#4245]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

If jemalloc is disabled or the API is incorrectly referenced (jemalloc api on windows have a prefix je_) memory usage is incorrectly reported for all block sizes.

### Expected behavior
At least the size of the block is returned for memory usage
### Actual behavior

then this line reports always 1 for all block sizes.

https://github.com/facebook/rocksdb/blob/master/table/format.h#L215

because sizeof(char) is always 1. sizeof() is calculated at compile time and \*(char\*) is char.

**Comment by yuslepukhin** [comment]
@maysamyabandeh Will implement on Windows

**Comment by maysamyabandeh** [comment]
@yuslepukhin not sure if I understand the comment. The bug is not limited to Windows.

**Comment by yuslepukhin** [comment]
@maysamyabandeh I will make sure `malloc_usable_size` functionality is available on Windows
