### ISSUE TITLE
total_log_size not recovered when avoid flush during restart

### ISSUE THREAD

**Issue by hoganfan** [facebook/rocksdb#4253]
### Expected behavior
whenever wal log size exceed max_total_wal_size(1G), rocksdb will flush memtable to disk. 

### Actual behavior
before restart, the total wal log size is a little less than 1G.
after restart, wal log size exeed 1G, but rocksdb have not triggered the flush operation.
the options as bellow, avoid flush during restart.
it seems like that rocksdb does not recover the total_log_size_ when restart.
```
options.avoid_flush_during_shutdown = true;
options.avoid_flush_during_recovery = true;
options.max_total_wal_size = 1ul << 30;
```

**Comment by yiwu-arbug** [comment]
@hoganfan This is expected behavior. Since avoid_flush_during_recovery=true, flush could not be done during recovery, and then it is not safe the purge WAL. Then a flush is forced when WAL continue to accumulate and finally reach max_total_wal_size (1G).

**Comment by yiwu-arbug** [comment]
Please reopen if you have more questions.

**Comment by yiwu-arbug** [comment]
Sorry, I misread the issue. Reopening.
