### ISSUE TITLE
Dropping column family doesnot drop the memory associated

### ISSUE THREAD

**Issue by krithikagopalakrishnan** [facebook/rocksdb#4280]
Hi, 
Im facing an issue in rocksdb when i try to drop a columnfamily. 
Im trying to load a few hundreds of MBs into rocksdb(v5.10.4) and trying to read the memory usage while dropping it. The data was loaded in two ways, number of single PUT commands and a single WRITE_BATCH write. After loading data,  i call rocksdb_flush(), drop the CF and then Drop the handler associated with it.

case 1 : using rocksdb_put : 
inserted 200 MB data using single puts.
Flushed the memory - memory got cleared.
Droppped the column family.
Dropped the handle - SST File got removed.
[rocksdb_put_check.txt](https://github.com/facebook/rocksdb/files/2292986/rocksdb_put_check.txt)
Everything seems to be working fine here.

case 2: using rocksdb_writebatch_put:
inserted 200MB data using write batch put and rocksdb_write()
Flushed the memory - SST files are formed. but memory is around 400MB(Write batch was not destroyed and **memtable memory was still held up**)
Dropped the column family.
Dropped the handle - **SST files are not removed.** 
[rockdb_write_batch_check.txt](https://github.com/facebook/rocksdb/files/2292983/rockdb_write_batch_check.txt)

From the docs, after a CF handler is dropped, any reference relating that CF should be dropped. Why
does this happen? Am i missing anything?

[Link](https://groups.google.com/forum/#!topic/rocksdb/K8mZUUnn4uE) to related discussion on google groups

**Comment by yiwu-arbug** [comment]
@krithikagopalakrishnan I suspect it is because the write batch object itself hold all the data before its destruction, even after write. Do you measure RSS before or after destructing the write batch object?

**Comment by yiwu-arbug** [comment]
Closing for no response. Please reopen if needed.
