### ISSUE TITLE
Reading from RocksDB rapidly increases memory until OOM crasy

### ISSUE THREAD

**Issue by rjonesxmoz** [facebook/rocksdb#4285]
The database size is about 30GB compressed. Once I start reading a few hundred thousands rows it fills up the 12GB of memory and then crashes.

I'm guessing that the cache is filling up or something of that sort. Are there any configuration options to stop this? 

Thanks

**Comment by riversand963** [comment]
Can you post your LOG file and OPTIONS file?

**Comment by ajkr** [comment]
We have a function, `rocksdb::MemoryUtil::GetApproximateMemoryUsageByType`, that you can try out to see where the memory is being used.

**Comment by toktarev** [comment]
I suspect it clone of https://github.com/facebook/rocksdb/issues/4112

**Comment by vitalyisaev2** [comment]
quite similar behavior in #4313

**Comment by ajkr** [comment]
OK, closing this one due to insufficient details to investigate.
