### ISSUE TITLE
Cannot intercept the Compaction-Begin event

### ISSUE THREAD

**Issue by paolococchi** [facebook/rocksdb#4288]
In my project I use the rocksdb::EventListener::GetCompactionEventListener function as a callback for the Compaction-Begin event. I'm on RocksDB 5.8.

But, that callback has been removed from RocksDB 5.13.1 with commit https://github.com/facebook/rocksdb/commit/1209b6db5c5ea3e26d72a12e94b3d9cf6c93f6c5 .

So, from v5.13.1 we have this in rocksdb::EventListener:
- OnFlushBegin
- OnFlushCompleted
- OnCompactionCompleted

Note that my specific use case is to use some thread-local variables to track things that happen in RocksDB Background threads (Flush and Compaction). That is why the OnCompactionCompleted is not enough.

### Expected behavior
To have an OnCompactionBegin callback or any other way for intercepting that event.

### Actual behavior
We cannot intercept the Compaction-Begin event.

**Comment by ajkr** [comment]
I agree, we should have `OnCompactionBegin`. Do you want to try implementing it (in the same way `OnCompactionCompleted` is implemented, not like `CompactionEventListener`)?

**Comment by ajkr** [comment]
Or, anybody who wants to try out contributing to RocksDB can take this.

**Comment by paolococchi** [comment]
Thank you @solicomo and @ajkr for picking up and fixing this issue so quickly.
