### ISSUE TITLE
How can I get the key number from rocksdb

### ISSUE THREAD

**Issue by baotiao** [facebook/rocksdb#432]
I want know how many keys without repetition in the rocksdb.
Dose rocksdb has a simple interface to return the number, or I need the iterator the whole database..

**Comment by jcalcote** [comment]
I'm using the latest (6.22.1.1) rocksdbjni library. About 60 seconds after I start my app, I read the estimated number of keys and it's always returning zero. Is there something I have to do first to "prime" rocks so it can get a good value for the estimate?
