### ISSUE TITLE
Random characters appended to merge existing_value when implementing jni

### ISSUE THREAD

**Issue by neondude** [facebook/rocksdb#4330]
I encountered this error while i was trying to parse json which i read from `existing_value` in the merge operator interface

### Expected behavior
Expected to read the value i have inserted through put operation

### Actual behavior
Reading the value i have inserted plus some random characters have been appended when i read from `existing_value->data()`

This does not happen consistently. It happens once in around 5 times i run the java program. 

### Steps to reproduce the behavior

- Add the following code to /utilities/merge_operators/string_append/stringappend.cc line:37 (inside the else block)
 ```
 if(existing_value->size() != strlen(existing_value->data()) )
 {
       std::cout << "extra characters present" << std::endl;
       std::cout << existing_value->data() << std::endl;
  }
 ```
- run `make -j8 rocksdbjava`
- Using the resulting jar, run the following java program multiple times until you see the print statement from the merge operator
 ```

import org.rocksdb.*;

import static java.nio.charset.StandardCharsets.UTF_8;

public class MergeDemo {
    static {
        RocksDB.loadLibrary();
    }

    
    public static void main(String[] args) {
        String dbPath = "../db_store";

        RocksDB rocksDB;
        Options options;
        WriteOptions writeOptions;
        ReadOptions readOptions;

        try {
            RocksDB.destroyDB(dbPath,new Options());
            options = new Options();
            options.setCreateIfMissing(true);
            options.setMergeOperator(new StringAppendOperator());
            rocksDB = RocksDB.open(options, dbPath);
            writeOptions = new WriteOptions();
            writeOptions.setDisableWAL(false);
            readOptions = new ReadOptions();

            byte[] key = "key".getBytes();
            byte[] value = null;
            value = "hello".getBytes(UTF_8);
            rocksDB.put(writeOptions,key, value);
            rocksDB.merge(writeOptions, key, value);
            rocksDB.merge(writeOptions, key, value);

            value = rocksDB.get(readOptions,key);
            // System.out.println("key: " + new String(value));

            rocksDB.close();


        } catch (Exception e) {
            // TODO: handle exception
        }
    }
}
```
 #### Some examples of the characters that were appended 

helloicodeBlockProp��4�
hello*�
helloB
hellocation�E�3�
hello�
hellonvoke/лY�
helloiteratпj�
helloze
helloock_al
hellova/lan�m�e�
hello)Ljava�����

**Comment by guillaumepitel** [comment]
You cannot use Slice.data() to obtain a regular null-terminated string. The idea behind a Slice is that the length of the char[] is stored in Slice.size(). 

What you should do, if you want to print the value, is to create a new string s and do : s.assign(
value.data(),value.size())

**Comment by adamretter** [comment]
@guillaumepitel the reporter is using the Java API I believe,

**Comment by neondude** [comment]
@guillaumepitel yes, I am trying to implement a custom merge operator. As you pointed out the issue was because I used Slice.data() instead of creating a new string.

Instead of using Slice.data(), creating a new string using Slice.data() and Slice.size() has resolved this issue.
