### ISSUE TITLE
Add documentation for format_version 4

### ISSUE THREAD

**Issue by tcwalther** [facebook/rocksdb#4337]
The documentation for format_version 4 is currently missing:

https://github.com/facebook/rocksdb/blob/9d646a6311c4940bc69b8b95f073abf938eff70d/include/rocksdb/table.h#L241

Since I don't feel comfortable enough writing correct documentation about version 4, I'm flagging this as an issue instead of making a PR.

**Comment by miasantreble** [comment]
FYI @maysamyabandeh
