### ISSUE TITLE
RcoksDB.listColumnFamilies should return List<String> or List<ColumnFamilyDescriptor> rather than List<byte[]>

### ISSUE THREAD

**Issue by xpromache** [facebook/rocksdb#435]
In Java: if one wants to open a db without knowing all the column families, the listColumnFamilies can be used. However that returns a list of byte[] whereas for opening the database one needs a list of ColumnFamilyDescriptor which itself is built from a String.
In addition it is not clear how the options can influence the return of listColumnFamilies.

**Comment by fyrz** [comment]
@yhchiang this one can be closed.

**Comment by fyrz** [comment]
I close this as the code was aligned as proposed above. (See for reference: https://github.com/facebook/rocksdb/pull/441)

@xpromache feel free to open that one here again if the pull request didnt adress your concerns.

**Comment by xpromache** [comment]
Ok, so I have now updated to the latest rocksdb and changed my code to use byte[] instead of strings for column families, just to discover that internally are still stored somehow as null terminated strings :(

The following piece of code gives an error that the Column Family 0x0001 already exists although I only created 0x0000.



package inutil;

import org.rocksdb.ColumnFamilyDescriptor;
import org.rocksdb.ColumnFamilyHandle;
import org.rocksdb.CompressionType;
import org.rocksdb.RocksDB;
import org.rocksdb.Options;


public class RdbTest {
	public static void main(String[] args) throws Exception {
		  RocksDB.loadLibrary();
		  Runtime.getRuntime().exec("rm -r /tmp/rdb-test");
		  Options options = new Options().setCreateIfMissing(true).setCompressionType(CompressionType.SNAPPY_COMPRESSION);
		  RocksDB db = RocksDB.open(options, "/tmp/rdb-test");
		  byte[] b0 =  new byte[]{0,0};
		  byte[] b1 =  new byte[]{0,1};
		  
		  ColumnFamilyDescriptor cfd1 = new ColumnFamilyDescriptor(b0);
		  ColumnFamilyDescriptor cfd2 = new ColumnFamilyDescriptor(b1);
		  
		  ColumnFamilyHandle cfh1 =  db.createColumnFamily(cfd1);
		  ColumnFamilyHandle cfh2 =  db.createColumnFamily(cfd2);
		  
		  db.put(cfh1,"c1key1".getBytes(), "c1value1".getBytes());
		  db.put(cfh2,"c2key1".getBytes(), "c2value1".getBytes());
		  
		  db.close();
	}
}

**Comment by fyrz** [comment]
@xpromache thats correct. As internally the column family name is a string we transform the byte array to a string using a char pointer which leads to zero bytes being interpreted as termination points right now. I will provide a fix that you can store zero bytes.

**Comment by fyrz** [comment]
@xpromache is there any reason why someone would store zero bytes ? I mean in my opinion the bug is that it is allowed to pass zero bytes to a string based method.

**Comment by xpromache** [comment]
The thing is that from the java API, Column Families are identified by byte[]. Therefore you would think that any byte[] will do. Same as for the key and values, you can put an arbitrary byte[]. You don't expect (or want) that your byte[] is not ok because it's got a 0 in it...
In my application I need short numbers as Column Families so I encode them on two byte[] of length 2 0x0000, 0x0001...

(I suggested when I opened this issue to have Strings as Column Family identifier but there was a problem with encoding).

**Comment by fyrz** [comment]
@xpromache ok valid point. Let me think about it. The byte array thing is only because you want a homogenous behavior between listColumnFamilies and createColumnFamily. From listColumnFamilies we cannot determine the String encoding anymore that`s the point.

**Comment by fyrz** [comment]
@xpromache i provided a solution see pull requests.

**Comment by xpromache** [comment]
thanks a lot!
