### ISSUE TITLE
how to use jemalloc instead of tcmalloc

### ISSUE THREAD

**Issue by xinxinsh** [facebook/rocksdb#438]
wiki page says rocksdb support jemalloc , how to enable it?

**Comment by igorcanadi** [comment]
Attached diff: https://reviews.facebook.net/D36789

**Comment by igorcanadi** [comment]
Hey @xinxinsh ! You can now use jemalloc with RocksDB (check out https://github.com/facebook/rocksdb/commit/fd7a35731854528dde10deb3444a82ae4c1a9206)
!

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by vjon** [comment]
@igorcanadi, it looks like this was fixed quite a while ago and can be closed.

**Comment by toktarev** [comment]
Could you please provide an instruction: how to enable jemalloc for rocksdb and ensure that jemalloc was linked and used ?

**Comment by siying** [comment]
If you use GNU make, build will by default detect whether jemalloc has been installed in your build system and use it if it is the case. See: https://github.com/facebook/rocksdb/blob/v5.17.2/build_tools/build_detect_platform#L362-L380

If you use cmake, you need to explicitly set flag WITH_JEMALLOC=1, which is by default off: https://github.com/facebook/rocksdb/blob/v5.17.2/CMakeLists.txt#L47. See https://github.com/facebook/rocksdb/blob/v5.17.2/CMakeLists.txt#L64-L69

**Comment by toktarev** [comment]
What if I use Rocksdb as shared lib for my Java application

will it still use JEMalloc in this case ?

**Comment by toktarev** [comment]
JVM uses tmalloc

**Comment by siying** [comment]
CC @sagar0 @adamretter for RocksJava question.
