### ISSUE TITLE
RocksDB blog atom feed does not validate

### ISSUE THREAD

**Issue by theimpostor** [facebook/rocksdb#4387]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
RocksDB blog feed (http://rocksdb.org/feed.xml) is valid

### Actual behavior
The feed does not validate:

 https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frocksdb.org%2Fblog%2F

### Steps to reproduce the behavior
Try to add http://rocksdb.org/feed.xml to Mozilla Thunderbird feed reader.

Errors presented by w3c validator:

```
This feed does not validate.

line 7, column 11: link must be a full and valid URL: / [help]

    <link>/</link>
           ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

line 134, column 0: description should not contain relative URL references: /static/images/data-block-hash-index/block-format-binary-seek.png (8 occurrences) [help]

</description>
```

**Comment by ajkr** [comment]
Perhaps @gfosco would be interested in looking at this?

**Comment by gfosco** [comment]
Thanks for reporting this.  The w3 validator now reports the feed is valid.
