### ISSUE TITLE
Rocksdbjni ReadOptions :There is no lower bound on the iterator.

### ISSUE THREAD

**Issue by jing5877** [facebook/rocksdb#4401]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
ReadOptions.java has a method to set lower bound on the iterator.
### Actual behavior
There is no lower bound on the iterator.
### Steps to reproduce the behavior
When I use RocksIterator.seekForPrev(byte[] target) , I want to set lower bound in the ReadOptions. but I can not. May I ask why there is no lower bound on the iterator?  There is any way else to set lower bound ?

**Comment by sagar0** [comment]
ReadOptions.iterate_lower_bound was introduced into the C++ API about 11 months back. It hasn't been ported to the Java API as no one requested for it until now. Would you be interested in porting it? 

https://github.com/facebook/rocksdb/blob/a0ebec3804451e1aebda56b51dec82d6d900c5b1/include/rocksdb/options.h#L1008-L1018
