### ISSUE TITLE
rocksdb-java: leak/interface confusion - db.dropColumnFamily(cfh) disOwns native handle of cfh

### ISSUE THREAD

**Issue by TomasStanek** [facebook/rocksdb#4409]
Hello all,

### In RocksDB.java dropColumnFamily(cfh) calls cfh.disOwnNativeHandle()
This has the following consequences:
- Native handle of the column family is never released (disposeInternal is never called) and a user can no longer release it by cfh.close because the native handle is no longer owned.
- All resources (sst files, descriptors, etc.) are held indefinitely
- Corresponding sst files are not deleted (until the database is closed and reopened)
(If you createColumn family and then drop it in a loop, the sst files will pile up)

### Possible solution
Don't call disOwnNativeHandle in dropColumnFamily and let the user close it explicitly.

**Comment by ajkr** [comment]
I wonder if it's the cause of #4421

**Comment by ajkr** [comment]
@adamretter what do you think of the proposed solution?

**Comment by ajkr** [comment]
ping @adamretter

**Comment by adamretter** [comment]
@ajkr Okay, so it looks like I missed this one. I also noticed that the javadoc is wrong for the function. I will send a PR.
