### ISSUE TITLE
GeoDB in rocksDB is returning unexpected results for geo_fence queries

### ISSUE THREAD

**Issue by krithikagopalakrishnan** [facebook/rocksdb#4418]
Hi, 
Im doing a small testing on geodb_impl in rocksdb. And i found something strange. 
Let me summarise my testing,

I insert a Point (45,45) into geodb.
Now, i want to get all points which are at a distance of 200km from (46,46).
This is an example from geodb_test.cc. I measured the distance from the link to verify, and the distance was ~135km, and it satisfies the criteria. So yeah, All Good here.

Now, i reduce the distance to 130km. i.e. retrieve all points which are at a distance of 130km from (46,46). I expected no rows to be returned. But (45,45 ) is returned. 

Ok, let me reduce the distance further. 100km,90km, 80km,70km. For all these cases, i see the point (45,45) being returned. 

Can someone clarify how the boundary is being identified, in the function SearchQuadKeys?
Am i missing anything here?

**Comment by ajkr** [comment]
I think `GeoDB` is unknown to RocksDB team members at this point (and likely to be deprecated in next major version), so putting this up for grabs.

**Comment by atulagrwl** [comment]
geodb was removed from repository by https://github.com/facebook/rocksdb/pull/4101. Hence I think we can close the issue.
