### ISSUE TITLE
MariaDB + RocksDB Crash: "rocksdb_allow_mmap_reads" and "rocksdb_use_direct_io_for_flush_and_compaction". Both cannot be enabled at the same time.

### ISSUE THREAD

**Issue by jtelleria** [facebook/rocksdb#4422]
I attach an Issue of a Server Crash when using RocksDB + MariaDB:

https://jira.mariadb.org/browse/MDEV-16854

**Comment by mdcallag** [comment]
This reproduces in the 5.7.5 release of RocksDB but not in 5.14.3.
MariaDB 10.3 uses RocksDB 5.10

./db_bench -benchmarks=fillrandom,readrandom -use_existing_db=0 -seed=1537823408 -disable_auto_compactions=0 -sync=0 -db=./rdb -num=1000000 -num_levels=6 -key_size=32 -value_size=10 -block_size=4096 -cache_size=104857600 -cache_numshardbits=-1 -compression_type=none -compression_ratio=0.5 -level_compaction_dynamic_level_bytes=true -bytes_per_sync=0 -cache_index_and_filter_blocks=1 -write_buffer_size=33554432 -max_write_buffer_number=4 -target_file_size_base=67108864 -max_bytes_for_level_base=536870912 -statistics=0 -stats_per_interval=1 -stats_interval_seconds=5 -histogram=1 -memtablerep=skip_list -bloom_bits=10 -open_files=-1 -max_background_compactions=8 -max_background_flushes=2 -level0_file_num_compaction_trigger=4 -threads=1 -verify_checksum=0 -max_bytes_for_level_multiplier=10 --compaction_pri=3 -use_direct_io_for_flush_and_compaction=1 --mmap_read=1 --duration=10

**Comment by ajkr** [comment]
It's implicitly fixed by #3829, which makes `use_direct_io_for_flush_and_compaction` apply to writes only. Interestingly, the original implementation of flush/compaction direct I/O refused to open with mmap writes, but forgot to check mmap reads.

**Comment by ajkr** [comment]
I am not familiar with MariaDB release process. Should we backport to 5.10, or should they upgrade to 5.14?

**Comment by ajkr** [comment]
I guess it can wait for them to upgrade.

**Comment by jtelleria** [comment]
Thank you
