### ISSUE TITLE
flink taskmanager java thread crash 

### ISSUE THREAD

**Issue by wangxiaof** [facebook/rocksdb#4439]
Stack: [0x00007f1aeb1f4000,0x00007f1aeb2f5000],  sp=0x00007f1aeb2f2fb8,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x0000000000000001
C  [librocksdbjni-linux64.so+0x2df2c9]  rocksdb::DBImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*)+0x19
C  [librocksdbjni-linux64.so+0x2b0ba6]  rocksdb::DB::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, std::string*)+0x86
C  [librocksdbjni-linux64.so+0x271cb5]  rocksdb_get_helper(JNIEnv_*, rocksdb::DB*, rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, _jbyteArray*, int, int)+0x105
C  [librocksdbjni-linux64.so+0x271f7a]  Java_org_rocksdb_RocksDB_get__J_3BIIJ+0x5a
J 5804  org.rocksdb.RocksDB.get(J[BIIJ)[B (0 bytes) @ 0x00007f22de1e4f95 [0x00007f22de1e4ec0+0xd5]
J 6883 C2 org.apache.flink.contrib.streaming.state.RocksDBReducingState.get()Ljava/lang/Object; (69 bytes) @ 0x00007f22de51b9c0 [0x00007f22de51b840+0x180]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 5804  org.rocksdb.RocksDB.get(J[BIIJ)[B (0 bytes) @ 0x00007f22de1e4f13 [0x00007f22de1e4ec0+0x53]
J 6883 C2 org.apache.flink.contrib.streaming.state.RocksDBReducingState.get()Ljava/lang/Object; (69 bytes) @ 0x00007f22de51b9c0 [0x00007f22de51b840+0x180]
J 33525 C1
org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.onProcessingTime(Lorg/apache/flink/streaming/api/operators/InternalTimer;)V (214 bytes) @ 0x00007f22e02241a0 [0x00007f22e0223880+0x920]
J 32898 C2 org.apache.flink.streaming.runtime.tasks.SystemProcessingTimeService$TriggerTask.run()V (68 bytes) @ 0x00007f22e27fd644 [0x00007f22e27fcc00+0xa44]
J 21319 C2 java.util.concurrent.FutureTask.run()V (126 bytes) @ 0x00007f22e03ad6cc [0x00007f22e03ad320+0x3ac]
J 3577 C2 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V (59 bytes) @ 0x00007f22dd8f6a24 [0x00007f22dd8f5aa0+0xf84]
J 25410 C2 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V (225 bytes) @ 0x00007f22e1758390 [0x00007f22e1758240+0x150]
J 21558 C1 java.util.concurrent.ThreadPoolExecutor$Worker.run()V (9 bytes) @ 0x00007f22e05ee484 [0x00007f22e05ee380+0x104]
J 27475 C2 java.lang.Thread.run()V (17 bytes) @ 0x00007f22e056b42c [0x00007f22e056b3e0+0x4c]
v  ~StubRoutines::call_stub

**Comment by wangxiaof** [comment]
rocksdbjni 5.6.1

**Comment by Aitozi** [comment]
@wangxiaof I think It may be a flink issue. And may be it has been sloved by this PR https://github.com/apache/flink/pull/5058

**Comment by wangxiaof** [comment]
> @wangxiaof I think It may be a flink issue. And may be it has been sloved by this PR [apache/flink#5058](https://github.com/apache/flink/pull/5058)

thanks
