### ISSUE TITLE
Hard-linked snapshot SST files are changing?

### ISSUE THREAD

**Issue by gbitzes** [facebook/rocksdb#4451]
### Expected behavior
After creating a snapshot of a running db, the SST files in said snapshot should remain unchanging, and should not be affected by the running instance from which they originate.

### Actual behavior
After creating a snapshot, and attempting to tar and stream it over the network, we see this error:
```
tar: /var/lib/snapshot/state-machine/061493.sst: file changed as we read it
```

I assume these are the memtable files being changed by the running instance, which the snapshot has inherited through hard-linking. Shouldn't memtable files be copied, instead of hard-linked?

### Steps to reproduce the behavior
1. Take a snapshot of a rocksdb directory using the following code:

  ```
  rocksdb::Checkpoint *checkpoint = nullptr;
  RETURN_ON_ERROR(rocksdb::Checkpoint::Create(db.get(), &checkpoint));

  rocksdb::Status st = checkpoint->CreateCheckpoint(path);
  delete checkpoint;

  return st;
  ```

2. Immediately after, try to tar the snapshot. You can increase the probability of seeing the error if there's constant write load on the instance the snapshot originates from.

**Comment by gbitzes** [comment]
A couple more datapoints:
1. Each time we attempt this, the count number of the SST file being changed increases. For example:
```
  tar: /var/lib/snapshot/state-machine/061493.sst: file changed as we read it
  ... another attempt after an hour ...
  tar: /var/lib/snapshot/state-machine/061499.sst: file changed as we read it
  ... another attempt after an hour ...
  tar: /var/lib/snapshot/state-machine/061519.sst: file changed as we read it
  ... another attempt after an hour ...
  tar: /var/lib/snapshot/state-machine/061535.sst: file changed as we read it
```

This strongly points to the files being memtables, no?

2. We're running 5.13.4.

**Comment by anand1976** [comment]
Memtables are exclusively in-memory (heap). There are no memtable files. SST files are created by either memtable flush or compaction and are immutable, i.e don't change after they are closed and recorded in the MANIFEST file.

**Comment by gbitzes** [comment]
Thanks - if SST files are never supposed to change, this makes the error message we're getting even more strange. I'll try to make a reproducer, and update this issue once I have more info.

**Comment by gbitzes** [comment]
Ah, it looks like adding or removing a hard link to an inode will modify its ctime.. So, if the running rocksdb instance runs compaction and removes some SST file, tar will detect the modification in ctime on the checkpoint and complain, even though the contents have remained the same.

False alarm, sorry for the noise.
