### ISSUE TITLE
Missing pkg-config file

### ISSUE THREAD

**Issue by ael-code** [facebook/rocksdb#4452]
If I compile through the provided makefile, all the optional compression libraries found on my system are kicked in as dependencies. When I later try to link against the generated rocksDB shared library I need to link with all those compression libraries, otherwise I'll get:
```Compression type <CompressionLibrary> is not linked with the binary```

While compiling my software I don't have an easy way to know which compression libraries have been enabled and required by the rocksDB shared  library.
If a pkg-config file would have been provided for the shared library, it would be easy to understand which compression library I need to link with.

**Comment by yiwu-arbug** [comment]
@ael-code We are not familiar with pkg-config. Are you interested in send us a pull request for it? Thanks.

**Comment by ajkr** [comment]
The values of the options @anand1976 mentioned will tell you which compression libraries need to be linked.

**Comment by ael-code** [comment]
> The values of the options @anand1976 mentioned will tell you which compression libraries need to be linked.

That's true. But if rocksDB have been installed on my system by another person or through the package manager I don't have any clue about which configuration option have been used.

**Comment by ajkr** [comment]
Those are runtime options that the user provides to RocksDB every time a DB is opened. They are not set during RocksDB shared library installation.

**Comment by ajkr** [comment]
I agree we should have a pkg-config file, though. I just don't see that it needs to require compression libraries.
