### ISSUE TITLE
Windows C++17 support

### ISSUE THREAD

**Issue by zpalmtree** [facebook/rocksdb#4462]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
RocksDB builds on Windows C++17

### Actual behavior
Build fails due to usage of `std::random_shuffle` in
https://github.com/facebook/rocksdb/blob/master/util/transaction_test_util.cc#L138 and 
https://github.com/facebook/rocksdb/blob/master/util/transaction_test_util.cc#L262

The exact error I get is `error C2039: 'random_shuffle': is not a member of 'std'`

`std::random_shuffle` has been removed in C++17, and now it is recommended to use `std::shuffle`. I patched this locally by using `std::shuffle(set_vec.begin(), set_vec.end(), std::random_device{});` instead, which lets rocks build.

### Steps to reproduce the behavior
I experienced this when using an appveyor image, using `Visual Studio 2017` as the OS, and `Visual Studio 15 2017 Win64` as the cmake target.

**Comment by yiwu-arbug** [comment]
@zpalmtree Are you interested in sending a pull request for a fix? Thanks.

**Comment by zpalmtree** [comment]
Made a PR: https://github.com/facebook/rocksdb/pull/4482
