### ISSUE TITLE
Allow to select static or shared lib target in CMake

### ISSUE THREAD

**Issue by ael-code** [facebook/rocksdb#4484]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
It would be nice to have the possibility to select between the static and the shared lib target in CMake. In this way would be possible to build only one of them or both of them.

### Actual behavior
At the moment CMake doesn't allow you to select which target to compile. Both the static library and the shared one will be compiled. There is no way to build only one of them.

I modified the CMakeLists.txt in order to build just the shared library and the compilation time is halved from 64 seconds to 32.

### Solution Proposal
Expose a CMake option to select which target will be built.
Something like `-DSHARED_LIB:BOOL=ON -DSTATIC_LIB:BOOL=OFF`

**Comment by ajkr** [comment]
Sounds good. Do you want to open a PR for the change?

**Comment by mellery451** [comment]
I'd be happy to submit a patch for this.

The conventional way to do this is to make use of the `BUILD_SHARED_LIBS` setting (https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html) and then `add_library` without an explicit type will do the right thing. Would it be sufficient to just build one library type based on this setting, or do we need the ability to build BOTH library types with the same generated build (single configure step) ? If the latter is required, then we'll have to go with the custom options originally proposed by @ael-code .

**Comment by ael-code** [comment]
In any case you will expose the `BUILD_SHARED_LIBS` variable as CMake option as suggested in the documentation [you linked](https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html):

> The `BUILD_SHARED_LIBS` variable is often added to projects as an option() so that each user of a project can decide if they want to build the project using shared or static libraries.

**Comment by mellery451** [comment]
yes - I agree it would be exposed as an option. The main difference in functionality is that you would have to run the cmake configuration step twice if you wanted to produce both kinds of libraries whereas the dual option approach would support the existing model of building BOTH libraries at the same time (if that's what you wanted).  I prefer the standard approach, but I'm happy to do the two-option solution is that's what is preferred by most users.

**Comment by sagar0** [comment]
The standard approach of generating one library-type at a time might be good as I believe that is what most users would prefer. A user would typically need either a static lib or shared lib in their use-case, but not both simultaneously.

**Comment by ltamasi** [comment]
Fixed by #6122 .
