### ISSUE TITLE
macos build example failed

### ISSUE THREAD

**Issue by zyycj** [facebook/rocksdb#4501]
## env
macos 10.14
gcc8.2

## error
make simple_example

g++ -fno-rtti simple_example.cc -osimple_example ../librocksdb.a -I../include -O2 -std=c++11 -lsnappy -lgflags -lz -lbz2 -llz4 -lzstd -ltbb -std=c++11  -DROCKSDB_PLATFORM_POSIX -DROCKSDB_LIB_IO_POSIX  -DOS_MACOSX -DSNAPPY -DGFLAGS=1 -DZLIB -DBZIP2 -DLZ4 -DZSTD -DTBB -DROCKSDB_BACKTRACE -Wshorten-64-to-32 -march=native  -DHAVE_SSE42 -DHAVE_PCLMUL -DROCKSDB_SUPPORT_THREAD_LOCAL -DROCKSDB_JEMALLOC -DJEMALLOC_NO_DEMANGLE    -lpthread
Undefined symbols for architecture x86_64:
  "_malloc_stats_print", referenced from:
      rocksdb::DumpMallocStats(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in librocksdb.a(malloc_stats.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

And I also installed jemalloc with brew.

How to solve it?

**Comment by yiwu-arbug** [comment]
do you miss `-ljemalloc`?

**Comment by zyycj** [comment]
I add the flag `-ljemalloc` , and solve this problem.
