### ISSUE TITLE
Replication of Prepared Transactions in TransactionDB WriteCommitted

### ISSUE THREAD

**Issue by phoenixchinar** [facebook/rocksdb#4566]
Replication of Prepared Transactions in TransactionDB WriteCommitted

I am using rocksdb::TransactionDB with WRITE_COMMITTED policy for my datastore. I am using GetUpdatesSince API for replication between a master and slave. What it looks like is that transactions that are not yet committed, the information is not getting returned using GetUpdatesSince. Due to this even though a transaction has been prepared, it cannot be seen on the slave.

This creates challenges when the DB is being used in a 2 phase commit. The master acknowledges back to the transaction coordinator during the prepare phase (after ensuring that slave(s) is/are also up to date with the latest sequence so far). However, the commit cannot go ahead anymore if for any reason master crashes and a slave is promoted to master. The expectation would have been that Slave would have the same state as the Master, and the commit would then go ahead on the Slave (which would have assumed the role of the master).

* Expected results
Prepared transactions that are in the WAL are returned for replication by GetUpdatesSince API.

* Actual results (with build output window contents if applicable)
Only committed transactions in the WAL are returned for replication by GetUpdatesSince API.

``` 
    rocksdb::BlockBasedTableOptions blockBasedTableOptions;
    rocksdb::Options options;
    options.create_if_missing = true;
    options.allow_2pc = true;
    options.two_write_queues = true;
    options.WAL_ttl_seconds = 86400;
    options.table_factory.reset(rocksdb::NewBlockBasedTableFactory(blockBasedTableOptions));
    rocksdb::TransactionDBOptions tOptions;
    tOptions.write_policy = rocksdb::TxnDBWritePolicy::WRITE_COMMITTED;
    auto status = rocksdb::TransactionDB::Open(options, tOptions, path, &db);
    CHECK(status.ok());
    std::shared_ptr<rocksdb::TransactionDB> db_source(db);
    auto wo = WriteOptions();
    wo.sync = true;
    auto to = TransactionOptions();
    VLOG(1)<<"Latest sequence number "<<db_source->GetLatestSequenceNumber();
//I1020 11:36:43.389649  2104 ReplicationHandlerTest.cpp:110] Latest sequence number 0

    std::unique_ptr<Transaction> pTransaction(db_source->BeginTransaction(wo,to));
    auto status = pTransaction->SetName("TXN1");
    CHECK(status.ok());
    VLOG(1)<<"Latest sequence number "<<db_source->GetLatestSequenceNumber();
//I1020 11:36:43.389688  2104 ReplicationHandlerTest.cpp:114] Latest sequence number 0
    status = pTransaction->Put("Record 1", value);
    CHECK(status.ok());
    VLOG(1)<<"Latest sequence number "<<db_source->GetLatestSequenceNumber();
//I1020 11:36:43.389716  2104 ReplicationHandlerTest.cpp:117] Latest sequence number 0
    status = pTransaction->Put("Record 2", value);
    CHECK(status.ok());
    VLOG(1)<<"Latest sequence number "<<db_source->GetLatestSequenceNumber();
//I1020 11:36:43.389731  2104 ReplicationHandlerTest.cpp:120] Latest sequence number 0
```
This is so far all expected. However, the expectation is that prepare will also increase the sequence number by 1, so GetLatestSequenceNumber() should be returning 1, but instead returns 0. Also the record should be available to GetUpdatesSince so that it can be replicated, but it isn't.
```
    status = pTransaction->Prepare();
    VLOG(1)<<"Latest sequence number "<<db_source->GetLatestSequenceNumber();
//I1020 11:36:43.393997  2104 ReplicationHandlerTest.cpp:122] Latest sequence number 0
    CHECK(status.ok());
```
Commit, then bumps up the sequence number by **2**.

```
    status = pTransaction->Commit();
    DCHECK(status.ok());
    VLOG(1)<<"Latest sequence number "<<db_source->GetLatestSequenceNumber();
//I1020 11:36:43.395844  2104 ReplicationHandlerTest.cpp:134] Latest sequence number 2
```

Is there something I am missing? Shouldn't we be able to replicate prepared transactions across instances of RocksDB, so recovery in case of a crash can be done by the second instance.

**Comment by maysamyabandeh** [comment]
GetLatestSequenceNumber and GetUpdatesSince are function on DB (not TransactionDB) so they operate on committed data visible to normal reads.

Other applications like MyRocks use an separate external WAL (called binlog) for replication. Using RocksDB WAL for replication is an interesting approach. I do not what would be the challenges there but it does seem doable. If you could make it work perhaps you can share the results in the user group: https://www.facebook.com/groups/rocksdb.dev

About the particular issue of the fate of prepared transactions after slave promotion the common practice which is used by MyRocks is that the new master i) query the list of prepared but not committed transaction using GetAllPreparedTransactions, ii) rolls them back or commit them before starting new transactions. Perhaps studying MyRocks code would help: https://github.com/facebook/mysql-5.6
