### ISSUE TITLE
Compression type Snappy is not linked with the binary

### ISSUE THREAD

**Issue by cache123abc** [facebook/rocksdb#4578]
### ENV
Ubuntu 16.04
gcc version 5.4.0 20160609

## Problem

I want to use the simple_example.cc. So, I build a dynamic shared lib to link with the executable. But when execute the binary file, the error as follows.
```
Compression type Snappy is not linked with the binary.
Assertion `s.ok()' failed.
Aborted (core dumped)
 ```

But my CmakeLists.txt already link snappy.
```
cmake_minimum_required(VERSION 3.5)
include_directories(../include)
add_compile_options(-std=c++11)
add_executable(s_test simple_example.cc)
target_link_libraries(s_test /usr/lib/x86_64-linux-gnu/libsnappy.so ../build/librocksdb.so)
```
And  if I use the static lib and the official MakeFile in examples directory, then everything is fine. What's the problem?

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

You would have more luck in user group: https://www.facebook.com/groups/rocksdb.dev
