### ISSUE TITLE
Post upgradation to Ubuntu 18.04, getting make error

### ISSUE THREAD

**Issue by nitesh1994** [facebook/rocksdb#4586]
Previously, I could make successfully in Ubuntu 16. Then, I upgraded to Ubuntu 18.04 and made small change in examples/simple_example.cc to change the key input to DB. I'm getting following make error post that

/usr/bin/ld: db/builder.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: db/c.o: relocation R_X86_64_32S against symbol `_ZTVZ40rocksdb_filterpolicy_create_bloom_formatE7Wrapper' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: db/column_family.o: relocation R_X86_64_32 against `.bss' can not be used when making a PIE object; recompile with -fPIC
/usr/bin/ld: db/compacted_db_impl.o: relocation R_X86_64_32S against symbol `_ZTVN7rocksdb15CompactedDBImplE' can not be used when making a PIE object; recompile with -fPIC

**/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:1058: recipe for target 'db_bench' failed**

I have all the dependencies installed for Ubuntu as mentioned on install.md page.

make shared_lib works fine. But make all fails with above error.
I tried make after removing changes in example but no luck.

Am I missing some step here ?

**Comment by bluenote10** [comment]
I'm getting the same error on Ubuntu 16.04. Can you remember how you solved the problem?
