### ISSUE TITLE
I am looking for GetLiveFiles() in java-api for rocksdb. Can you expose that, didn't seem to find it 

### ISSUE THREAD

**Issue by brary** [facebook/rocksdb#4598]
There are few important functions which would be helpful if exposed in rocksjni as they are already implemented in rocksdb c++. One of them being GetLiveFiles(). Please share if it already done.

**Comment by brary** [comment]
It would be helpful if VerifyChecksum() is also exposed. Thanks.

**Comment by atulagrwl** [comment]
I can see both [GetLiveFiles](https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/RocksDB.java#L3670)  and [VerifyChecksum](https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/RocksDB.java#L3819) in the java apis. Hence, I believe this issue can be closed now.
