### ISSUE TITLE
Add additional options to Java's CompactionOptionsFIFO

### ISSUE THREAD

**Issue by eliaslevy** [facebook/rocksdb#4601]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Support for the FIFO compaction strategy's `allow_compaction` and `ttl` options.

### Actual behavior

Lack of support for the options.

**Comment by sagar0** [comment]
PR: #4609

**Comment by sagar0** [comment]
I had the java options patch sitting in my local branch for a few months now.

**Comment by adamretter** [comment]
I think that OR #4609 was merged so this can now be closed.
