### ISSUE TITLE
2PC bug 

### ISSUE THREAD

**Issue by cooljiansir** [facebook/rocksdb#4613]
In 2PC transaction, after we write a prepare entry into WAL, we call a Flush before `MarkLogAsContainingPrepSection`, the log file containing the prepare entry will be deleted.
see https://github.com/facebook/rocksdb/pull/4612

**Comment by sagar0** [comment]
@maysamyabandeh could you take a look?

**Comment by maysamyabandeh** [comment]
Thanks @cooljiansir Seems to be a valid issue. One solution could be marking the prepared logs in the write thread via PreReleaseCallback. (We can then remove logs_with_prep_mutex_ as it would be already protected by mutex_.) The drawback would be longer write time which could have negative impact in performance but I do not see any way around it.
@yiwu-arbug @lth what do you think?

**Comment by lth** [comment]
That sounds reasonable to me, since we need some way of writing WAL and marking logs atomically.

We will have to extend the callback to include log_used though, so we just have to make sure that's available when we call the callback.

**Comment by yiwu-arbug** [comment]
+1 for marking log atomically during write. I'm not familiar with the `MarkLogAsContainingPrepSection` though. Not sure if it will really have impact on write time.
