### ISSUE TITLE
Allow merge operator to return nullptr in new-value to indicate desire to remove key.

### ISSUE THREAD

**Issue by jcalcote** [facebook/rocksdb#4667]
I'd like to implement a RefCountOperator that works similarly to the UInt64AddOperator in that it allows deltas to be passed in. The RefCountOperator, however, would never allow the count to go negative, and when the addition results in zero, the key is removed. In this manner, a ref-counted key could be completely managed by the merge operator.

Here's how my merge function would work - note the else clause at the bottom where the comment says, "delete key here..."

```
    virtual bool Merge(const Slice& key,
                       const Slice* existing_value,
                       const Slice& value,
                       std::string* new_value,
                       Logger* logger) const override {
        uint64_t orig_value = 0;
        if (existing_value) {
            orig_value = DecodeInteger(*existing_value, logger);
        }
        uint64_t delta = DecodeInteger(value, logger);

        assert(new_value);
        new_value->clear();

        uint64_t result = orig_value + delta;
        if (result < 0) {
            Log(InfoLogLevel::WARN_LEVEL, logger,
                "refcount after merge would be less than zero (%"
                ROCKSDB_PRIszt "); resetting to zero (and removing key)", result);
            result = 0;
        }

        // put the new value only if the result is greater than zero -
        if (result > 0) {
            PutFixed64(new_value, result);
        } else {
            // delete key here ...
        }
        return true;  // Return true always since corruption will be treated as 0
    }
```
The problem is, I can't figure out the correct way to delete the key - is this possible? My thought was that if the Merge method were modified (MergeV3, perhaps), and the new_value argument was passed by address, then the address could return null to indicate that the key should be removed.

**Comment by ajkr** [comment]
I am not sure merge operator is able to provide this capability, even with a `MergeV3` interface like you proposed. The problem is the merging happens only on the read path, at which point it is too late to prevent refcount from going negative - that needs to be done on the write path.

Is `TransactionDB`'s `GetForUpdate` followed by `Put` or `Delete` a suitable alternative?

**Comment by jcalcote** [comment]
Hi Andrew (@ajkr) - TransactionDB would indeed be ideal if this were an isolated database. Unfortunately, it's just a secondary column family that gets updated on the same batch write as the primary column family in a regular RocksDB. Additionally, I'm accessing it though RocksJava, which (AFAIK) doesn't expose TransactionDB. (I'm ok with exposing small portions of RocksDB functionality via the Java interface, but I'm not sure I'm up to exposing the entire TransactionDB interface properly.)

I see your point about merge being on the read path, though it seems strange to me that (A) a new value can be added, or (B) an existing value can be updated atomically on the read path, but delete is not allowed (on the other hand - it's clear to me that removing an entry is a different class of functionality than adding or updating entries).

Regardless, you do present an idea to me that makes better sense. I could simply allow the reference count to go to zero. In my particular (very specific) use case, the thing being reference-counted is a sort of timestamp index entry (where the key itself holds the timestamp). Once it actually goes to zero (except in the rare case where two references are applied at once and one of them is dropped - all within the same pseudo-transaction - which is the exact scenario I'm trying to avoid screwing up), I can use a garbage-collection process to remove entries with zero references. I was hoping to make it more self-managing.

**Comment by jcalcote** [comment]
Would FB be willing to accept a submission for a RemoveZeroValueCompactionFilter class in the java interface (which exposes a new remove_zerovalue_compactionfilter C++ object)?

I've implemented one - I think this solves my problem. I'd like to submit it back upstream if anyone is interested. I believe it's useful for the purpose of keeping column families in check the use reference-counted values.

**Comment by jcalcote** [comment]
After digging into them, I can now see that compaction filters, as they're presented today, will not accomplish the thing I'm trying to do. I see that for column families whose values are designed to be set with a merge operator, a compaction filter will be called on each merge. The problem (for me) is that the filter is called before the merge and, while it does present the merge operand, it doesn't present the existing value, so you can't tell what the final result will be after the merge while in the compaction filter. In a situation like mine, where I'm trying to determine if I should remove an element based on the final value after the merge, it's useless.

I see there are discussions going on about changes that might be made in the future of compaction filters, so I'll just wait. For now, I already have a high-level garbage collection process. I'll just take a pass through my ref-counted key CF and delete zero-valued references. It's not ideal, but at least it works.

I'll leave this ticket open for a day or two more to see if anyone has any additional thoughts.

**Comment by Nashatyrev** [comment]
@jcalcote I'm also looking for ref-counting and working with Java interface.
However I'm trying to address `get+put/get+delete` performance overhead. 

> RocksJava, which (AFAIK) doesn't expose TransactionDB

I believe it does. `GetForUpdate` is also there

**Comment by adamretter** [comment]
`TransactionDB` is absolutely available in the Java API, as is `OptimisticTransactionDB`!

**Comment by unoexperto** [comment]
@adamretter @jcalcote @ajkr @Nashatyrev 
Guys, I apologize for barging into the conversation but could you please tell me 

1. What one needs to do to use existing merge operators ? I use `org.rocksdb:rocksdbjni:6.5.3` from maven and I get `java.lang.UnsatisfiedLinkError: 'long org.rocksdb.UInt64AddOperator.newSharedUInt64AddOperator()'` exception on instantiation of `UInt64AddOperator` as if native implementation is missing;
2. Can I define merge operator implementation in Java ? Currently it looks like I can only pass name of the operator;
3. If 2 is not possible how do you achieve it ? Do you implement your merger in C++ and then compile custom build of `org.rocksdb:rocksdbjni` ? It's doable but not very convenient from maintenance prospective.

Thanks!

**Comment by adamretter** [comment]
@unoexperto can you move your comment to a new issue please?

**Comment by unoexperto** [comment]
@adamretter Done! https://github.com/facebook/rocksdb/issues/6326 Sorry about that.
