### ISSUE TITLE
rocksjni: possible bug in options_util.cc - no return after setting an exception

### ISSUE THREAD

**Issue by andrewt0301** [facebook/rocksdb#4684]
Methods [Java_org_rocksdb_OptionsUtil_loadLatestOptions](https://github.com/facebook/rocksdb/blob/147697420ab60c85deb13cea4532844e3f2ae352/java/rocksjni/options_util.cc#L68) and [Java_org_rocksdb_OptionsUtil_loadOptionsFromFile](https://github.com/facebook/rocksdb/blob/147697420ab60c85deb13cea4532844e3f2ae352/java/rocksjni/options_util.cc#L91) in the  [options_util.cc](https://github.com/facebook/rocksdb/blob/master/java/rocksjni/options_util.cc) file continue execution after setting an exception (`rocksdb::RocksDBExceptionJni::ThrowNew`), which causes subsequent errors.

### Expected behavior

Methods [Java_org_rocksdb_OptionsUtil_loadLatestOptions](https://github.com/facebook/rocksdb/blob/147697420ab60c85deb13cea4532844e3f2ae352/java/rocksjni/options_util.cc#L68) and [Java_org_rocksdb_OptionsUtil_loadOptionsFromFile](https://github.com/facebook/rocksdb/blob/147697420ab60c85deb13cea4532844e3f2ae352/java/rocksjni/options_util.cc#L91) in the  [options_util.cc](https://github.com/facebook/rocksdb/blob/master/java/rocksjni/options_util.cc) file must return after setting an exception. The correct implementation should look like this:

```C++
if (!s.ok()) {
    rocksdb::RocksDBExceptionJni::ThrowNew(env, s);
} else {
    build_column_family_descriptor_list(env, jcfds, cf_descs);
}
```

### Actual behavior

Methods [Java_org_rocksdb_OptionsUtil_loadLatestOptions](https://github.com/facebook/rocksdb/blob/147697420ab60c85deb13cea4532844e3f2ae352/java/rocksjni/options_util.cc#L68) and [Java_org_rocksdb_OptionsUtil_loadOptionsFromFile](https://github.com/facebook/rocksdb/blob/147697420ab60c85deb13cea4532844e3f2ae352/java/rocksjni/options_util.cc#L91) in the  [options_util.cc](https://github.com/facebook/rocksdb/blob/master/java/rocksjni/options_util.cc) file do not return after setting an exception.

As a result, as subsequent calls for the `build_column_family_descriptor_list` method cause errors as the method is executed an invalid context (a pending exception is set). In any case, if an exceptional situation happens, it makes no sense to continue execution further.

**Comment by adamretter** [comment]
Indeed.

Alternatively just a `return;` after the `rocksdb::RocksDBExceptionJni::ThrowNew(env, s);` would also be fine.

**Comment by adamretter** [comment]
This was fixed in https://github.com/adamretter/rocksdb/commit/3197e5b6af19b84ff2a577771e0fa38dd6df2c2a
