### ISSUE TITLE
Missing features in Java version: Options::compaction_filter

### ISSUE THREAD

**Issue by RichardHightower** [facebook/rocksdb#469]
There are two features which make me consider RocksDB over LevelDB for the current project that I am working on. 
One is 
Options::compaction_filter

Described here:

https://github.com/facebook/rocksdb/wiki/Basic-Operations

"Options::compaction_filter - Allows an application to modify/delete a key-value during background compaction. The client must provide compaction_filter_factory if it requires a new compaction filter to be used for different compaction processes. Client should specify only one of filter or factory."

I would like to specify a filter to signal that older records (older than lets say 90 days assuming that I put a time stamp on the records or use a column family) should be deleted on compaction.

There does not seem to be a way to do this in Java and the Options:compaction_filter property is missing on the Java version of Options.

**Comment by igorcanadi** [comment]
You can use DBWithTTL that is available in Java. Or you can partition your data by Column Families and then drop old column families (very cheap).

RocksJava is maintained by our community, mostly @fyrz and @adamretter. So we would appreciate any patch that would expose more functionality through RocksJava.

**Comment by RichardHightower** [comment]
DBWithTTL does not exist in Java version yet.
There is TtlDB (I assume this is the same thing....), but that is not in the maven public repo yet. 
I can take a look at TtlDB.

**Comment by RichardHightower** [comment]
"Or you can partition your data by Column Families and then drop old column families (very cheap)."

Any examples of doing this?

**Comment by igorcanadi** [comment]
Check this out -- https://www.facebook.com/groups/rocksdb.dev/permalink/677018235730027/

**Comment by fyrz** [comment]
@RichardHightower DBWithTTL(C++) and TtlDB(Java) are equivalent to each other. You are right it is not in maven yet but will be in 3.10

**Comment by RichardHightower** [comment]
Thanks

On Fri, Jan 23, 2015 at 5:46 PM, Jörg Maier <notifications@github.com>
wrote:

> @RichardHightower <https://github.com/RichardHightower> DBWithTTL(C++)
> and TtlDB(Java) are equivalent to each other. You are right it is not in
> maven yet but will be in 3.10
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/rocksdb/issues/469#issuecomment-71294657>.
>



-- 
*Rick Hightower*
(415) 968-9037
Profile <http://www.google.com/profiles/RichardHightower>

**Comment by fyrz** [comment]
@RichardHightower can this issue be closed ?

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by adamretter** [comment]
Related - https://github.com/facebook/rocksdb/pull/1241
