### ISSUE TITLE
Error during benchmark testing

### ISSUE THREAD

**Issue by ssabnis** [facebook/rocksdb#4694]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Run the bulkload  bench mark
### Actual behavior
```
$> tools/benchmark.sh bulkload

./db_bench: error while loading shared libraries: libzstd.so.1: cannot open shared object file: No such file or directory
```

### Steps to reproduce the behavior
`tools/benchmark.sh bulkload`

Unable to conduct the bench mark testing, even though I have the lib installed.

OS CentOS 7.5

**Comment by ajkr** [comment]
Where is the library installed? I learned recently that CentOS doesn't search /usr/local/lib for shared libraries, which seemed surprising. If that's the issue, this answer might help: https://stackoverflow.com/a/4743249

**Comment by ssabnis** [comment]
Thanks @ajkr ,

After that doing I am getting the following error. 

```
./db_bench --benchmarks=compact --use_existing_db=1 --disable_auto_compactions=1 --sync=0 --db=/rocks/db --wal_dir=/rocks/wal --num=1073741824 --num_levels=6 --key_size=20 --value_size=400 --block_size=8192 --cache_size=1073741824 --cache_numshardbits=6 --compression_max_dict_bytes=0 --compression_ratio=0.5 --compression_type=snappy --level_compaction_dynamic_level_bytes=true --bytes_per_sync=8388608 --cache_index_and_filter_blocks=0 --pin_l0_filter_and_index_blocks_in_cache=1 --benchmark_write_rate_limit=0 --hard_rate_limit=3 --rate_limit_delay_max_milliseconds=1000000 --write_buffer_size=134217728 --target_file_size_base=134217728 --max_bytes_for_level_base=1073741824 --verify_checksum=1 --delete_obsolete_files_period_micros=62914560 --max_bytes_for_level_multiplier=8 --statistics=0 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --open_files=-1 --level0_file_num_compaction_trigger=4 --level0_slowdown_writes_trigger=12 --level0_stop_writes_trigger=20 --max_background_jobs=20 --max_write_buffer_number=8 --threads=1 2>&1 | tee -a /rocks/output/benchmark_bulkload_compact.log
./db_bench: error while loading shared libraries: libgflags.so.2: cannot open shared object file: No such file or directory
Complete bulkload in 0 seconds
```
i spent more than half a day. Can you help

Thanks

**Comment by ajkr** [comment]
Sorry for the difficulty. Do you have gflags installed? It is a requirement for running some RocksDB command-line tools like db_bench.

**Comment by ajkr** [comment]
For reference: https://github.com/facebook/rocksdb/blob/master/INSTALL.md#dependencies

**Comment by kyleyuanmh** [comment]
can someone help to solve this problem:

[root@node1 tools]# ./benchmark.sh bulkload
===== Benchmark =====
Start bulkload at 2019年 06月 06日 星期四 21:46:07 CST
Bulk loading 8000000000 random keys
./db_bench --benchmarks=fillrandom --use_existing_db=0 --disable_auto_compactions=1 --sync=0 --db=/raid/db --wal_dir=/raid/wal --num=8000000000 --num_levels=6 --key_size=20 --value_size=400 --block_size=8192 --cache_size=17179869184 --cache_numshardbits=6 --compression_max_dict_bytes=0 --compression_ratio=0.5 --compression_type=zstd --level_compaction_dynamic_level_bytes=true --bytes_per_sync=8388608 --cache_index_and_filter_blocks=0 --pin_l0_filter_and_index_blocks_in_cache=1 --benchmark_write_rate_limit=0 --hard_rate_limit=3 --rate_limit_delay_max_milliseconds=1000000 --write_buffer_size=134217728 --target_file_size_base=134217728 --max_bytes_for_level_base=1073741824 --verify_checksum=1 --delete_obsolete_files_period_micros=62914560 --max_bytes_for_level_multiplier=8 --statistics=0 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1 --memtablerep=skip_list --bloom_bits=10 --open_files=-1 --max_background_compactions=16 --max_write_buffer_number=8 --allow_concurrent_memtable_write=false --max_background_flushes=7 --level0_file_num_compaction_trigger=10485760 --level0_slowdown_writes_trigger=10485760 --level0_stop_writes_trigger=10485760 --threads=1 --memtablerep=vector --allow_concurrent_memtable_write=false --disable_wal=1 --seed=1559828767 2>&1 | tee -a /raid/output/benchmark_bulkload_fillrandom.log
Please install gflags to run rocksdb tools
(standard_in) 1: syntax error
(standard_in) 1: syntax error
Compacting...

**Comment by ljgreen** [comment]
you should install gflags.
sudo apt-get install libgflags-dev
https://github.com/gflags/gflags

**Comment by kyleyuanmh** [comment]
thats the problem: i have already installed the gflags and libgflags; it still not work..

**Comment by ljgreen** [comment]
you should add -DBUILD_SHARED_LIBS=ON when using cmake

**Comment by kyleyuanmh** [comment]
i did that, and i install gflags with ccmake with configure option:

 BUILD_PACKAGING                  ON                                                                                                      
 BUILD_SHARED_LIBS                ON                                                                                                      
 BUILD_TESTING                    ON                                                                                                      
 BUILD_gflags_LIB                 ON                                                                                                      
 BUILD_gflags_nothreads_LIB	  ON                                                                                                      
 CMAKE_BUILD_TYPE                 Release                                                                                                 
 CMAKE_INSTALL_PREFIX             /usr/local                                                                                              
 REGISTER_BUILD_DIR               ON                                                                                                      
 REGISTER_INSTALL_PREFIX          ON 

and it still not work. when i run：

         export DB_DIR=/raid/db
	export WAL_DIR=/raid/wal
	export TEMP=/raid/tmp
	export OUTPUT_DIR=/raid/output
        ./benchmark.sh bulkload

it says:

Please install gflags to run rocksdb tools
(standard_in) 1: syntax error
(standard_in) 1: syntax error

what should i do ? is there some operations i miss??

**Comment by ljgreen** [comment]
Which system do you use ? In addition, you can try to install glog after gflags installation.
Both are required by the rocksdb benchmark.

**Comment by ljgreen** [comment]
BTW, cmake verison in my computer is cmake version 3.10.2. Probably it could also affects the compiling results. Hope it could help you more or less.

**Comment by kyleyuanmh** [comment]
[root@node1 ~]# cat /proc/version 
Linux version 3.10.0-957.12.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Tue May 14 21:24:32 UTC 2019

i updated the cmake to the newer version.
# cmake --version
cmake version 3.15.0-rc1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by mrambacher** [comment]
This sounds like a potential LD_LIBRARY_PATH issue.
