### ISSUE TITLE
NO_FILE_CLOSES ticker is never incremented

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#4700]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

NO_FILE_CLOSES ticker should be incremented when a file is closed

### Actual behavior

There is no code that increments the ticker, per Sergey Petrunia

* In RocksDB, the only mentions of NO_FILE_CLOSES are:

include/rocksdb/statistics.h|144| NO_FILE_CLOSES,
include/rocksdb/statistics.h|387| {NO_FILE_CLOSES, "rocksdb.no.file.closes"},
java/rocksjni/portal.h|3204| case rocksdb::Tickers::NO_FILE_CLOSES:
java/rocksjni/portal.h|3408| return rocksdb::Tickers::NO_FILE_CLOSES;
java/src/main/java/org/rocksdb/TickerType.java|262| NO_FILE_CLOSES((byte) 0x2F),

I don't see a single place where the ticker is incremented.

Let's take some other counter, NUMBER_DB_SEEK_FOUND. The search does find calls
to increment its value:
db/db_iter.cc|1302| RecordTick(statistics_, NUMBER_DB_SEEK_FOUND);
db/db_iter.cc|1353| RecordTick(statistics_, NUMBER_DB_SEEK_FOUND);
db/db_iter.cc|1397| RecordTick(statistics_, NUMBER_DB_SEEK_FOUND);
db/db_iter.cc|1443| RecordTick(statistics_, NUMBER_DB_SEEK_FOUND);
include/rocksdb/statistics.h|138| NUMBER_DB_SEEK_FOUND,
include/rocksdb/statistics.h|383| {NUMBER_DB_SEEK_FOUND, "rocksdb.number.db.seek.found"},

### Steps to reproduce the behavior

grep the code

**Comment by ajkr** [comment]
I don't know why it was removed: https://github.com/facebook/rocksdb/commit/63f216ee0a2a6e28f9dfe24913d134d3a7fa3aca#diff-214a2fd7e8fddb41fe137f734f5b316fL23.

**Comment by ajkr** [comment]
Guess it was because it needs to be incremented in a static callback function that doesn't have access to a `Statistics` object. Now I'm feeling that author's pain...

**Comment by swikarpat** [comment]
@ajkr I am currently working on Updating RocksDB version to 9.7.3 from 7.9.2 and problems with Data type as 'NO_FILE_CLOSES' of class TickerType is removed now and we in Kafka uses this field. Can you guide me is there replacement of that field? 

java/src/main/java/org/rocksdb/TickerType.java|262| NO_FILE_CLOSES((byte) 0x2F),
