### ISSUE TITLE
when use List<ColumnFamilyHandle> to create List<RocksIterator> the value length is not right.

### ISSUE THREAD

**Issue by zhaoyanzhyn** [facebook/rocksdb#4730]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
        when i use List<ColumnFamilyHandle> to create List<RocksIterator> the length is wrong, usually larger than the actually，and the size is not right too.
### Actual behavior
       List<RocksIterator> rocksIterators = ttlDB.newIterators(handleList,readOptions);

**Comment by anand1976** [comment]
There's not enough information to troubleshoot. Can you share the exact length of the returned List? Also, what do you mean by length is not right and size is not right too? Aren't they one and the same?

**Comment by adamretter** [comment]
@zhaoyanzhyn  I am not sure which version of RocksJava you are describing, but at least with the latest version the behaviour you are describing seems impossible. See - https://github.com/facebook/rocksdb/blob/v5.17.2/java/src/main/java/org/rocksdb/RocksDB.java#L1697

**Comment by adamretter** [comment]
I am going to close this. Please re-open if it is still relevant.
