### ISSUE TITLE
CompactionPicker::ExpandToCleanCuts only needs to expand to the right

### ISSUE THREAD

**Issue by petermattis** [facebook/rocksdb#4731]
The comment on `CompactionPicker::ExpandToCleanCuts` says:

```
  // Add more files to the inputs on "level" to make sure that
  // no newer version of a key is compacted to "level+1" while leaving an older
  // version in a "level". Otherwise, any Get() will search "level" first,
  // and will likely return an old/stale value for the key, since it always
  // searches in increasing order of level to find the value. This could
  // also scramble the order of merge operands. This function should be
  // called any time a new Compaction is created, and its inputs_[0] are
  // populated.
```

Note that the requirement is that a compaction that includes `<user-key>#<seq>` also includes all older versions of the same `<user-key>` from the input level. These older versions will all occur in tables to the right of the current inputs. Tables to the left will have larger sequence numbers (or smaller user keys). 

The current behavior of `ExpandToCleanCuts` expands the inputs to both the left and right. This isn't erroneous, but it creates compactions that are larger than necessary.

**Comment by anand1976** [comment]
Thanks for the suggestion. You're right that we only need to expand to the right. We'll consider this.

**Comment by petermattis** [comment]
Turns out that this idea is incompatible with range tombstones as we only truncate range tombstone to atomic compaction unit boundaries. If we allow compaction the suffix of an atomic compaction unit without also compacting the prefix, we can end up in a scenario where a range tombstone in the prefix inadvertently starts deleting keys in the suffix when they are compacted to the bottommost level and are given seqnums of 0.
