### ISSUE TITLE
Load all the stored database into the memory

### ISSUE THREAD

**Issue by sarsanaee** [facebook/rocksdb#4737]
Hi,

I need to load all the key-values stored on the storage into the memory, however, it seems that it doesn't load like all 20GB that I have on the disk into the memory. How can I make it load everything into the memory first? Is there a flag for that?

Thanks

**Comment by anand1976** [comment]
There is no flag to do that. If you really want to pre-load everything, you could open the DB and iterate through all the keys. There is no guarantee the files will remain cached in memory though.

**Comment by sarsanaee** [comment]
Thank you for the message!

It should be it the memory when we could have an abundant amount of memory! I see no reason to send any data to the disk when have pretty sufficient memory. Just a question, so why people call this in-memory? I'm asking this because latency-sensitive applications require memory or cache latency, and storage latency is unacceptance for the microsecond latency constraints!

**Comment by zhanglistar** [comment]
Here is a tool to load all file or directory to pagecache, https://github.com/hoytech/vmtouch 
You can try this.

**Comment by anand1976** [comment]
Closing this issue as there is no further activity.
