### ISSUE TITLE
Proposal: Separate Env into Thread and FileSystem

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#4746]
### Expected behavior
`Thread` and `FileSystem` are independent components, when we implement a new `FileSystem`, we need not to implement `Thread`.

### Actual behavior
`Thread` and `FileSystem` functions are wrapped by `Env`. If we just want to implement a new `FileSystem`, we also need to implement `Thread`.

I know we can use `EnvWrapper` or `delegate to default env` to mitigate this issue, but this may causing other issues:
1. Need access to default env
2. Increase unnecessary work efforts...

### Steps to reproduce the behavior
Try to implement a new `FileSystem`.

**Comment by mrambacher** [comment]
I wholeheartedly agree with this suggestion. 

There are many classes that attempt to implement parts of the functionality of an Env and attempt to implement/override one portion or another (like HdfsEnv and MockEnv do for FileSystem and others do for overriding timers.  It would be much simpler if these interfaces would be split into separate classes.

**Comment by rockeet** [comment]
Now #5761 and #6552 have aimed on this proposal.

**Comment by mrambacher** [comment]
I think most of this work has been accomplished through the FileSystem and SystemClock classes.
