### ISSUE TITLE
How about use on a android app difference process?

### ISSUE THREAD

**Issue by crossle** [facebook/rocksdb#475]
If support difference process?

**Comment by dhruba** [comment]
I am not able to understand your question. Can you pl elaborate on your question?

**Comment by crossle** [comment]
A android application can include many process, only define on `AndroidManifest.xml` `android:process=":heloo"`, i want to know if the rocksdb support multi process. 
like https://github.com/nhachicha/SnappyDB/issues/36

**Comment by igorcanadi** [comment]
No, sorry, RocksDB doesn't support access from two different processes.
