### ISSUE TITLE
Info about docs

### ISSUE THREAD

**Issue by maframan** [facebook/rocksdb#4763]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Please, provide me the configuration properties to set compression mode for data and index individually because in the docs "https://github.com/facebook/rocksdb/wiki/Compression" is not clear how this configuration must be set .
### Actual behavior
Documentation not clear.
### Steps to reproduce the behavior
N/A

**Comment by ajkr** [comment]
Right now it's only possible to toggle whether compression is enabled for index blocks, and if it is enabled, then we use the same compression options that we use for data blocks. Is this what you wanted, or did you want to use different compression algorithms for data blocks vs index blocks?

**Comment by siying** [comment]
I updated the wiki a little bit.

**Comment by maframan** [comment]
Thanks for your answers.
We're using Java (rocksdbjni 5.7.3), compressing data with Snappy.
I looked for the option enable_index_compression in BlockBasedTableConfig class, but there is not and we noticed that compression seems to significantly worsen the reading times. 
Do you know how we can disable index compression in our classes?

**Comment by adamretter** [comment]
@maframan I am currently updating `org.rocksdb.BlockBasedTableConfig` to expose the missing options, should have something in a day or two.

**Comment by adamretter** [comment]
@maframan I have implemented `BlockBasedTableConfig#setEnableIndexCompression(boolean)` - https://github.com/adamretter/rocksdb/commit/60cfccaadfefba2e4423732d7d9e06c20f1e2bc9

I hope to send it as part of a larger PR to bring the API up to date.

**Comment by maframan** [comment]
@adamretter Thanks a lot! When will it be available?

**Comment by adamretter** [comment]
@maframan I am not certain but I hope it should be available with the next release.

**Comment by adamretter** [comment]
This is fixed.
