### ISSUE TITLE
There are no C API for backing up RocksDB

### ISSUE THREAD

**Issue by mkevac** [facebook/rocksdb#477]
There is no C API for backing up RocksDB. So one cannot backup RocksDB db from Go, for example.

**Comment by igorcanadi** [comment]
That is unfortunately correct. We usually rely on the community to maintain our C api (same as go language bindings, etc.), so we would appreciate any pull requests to that effect.

**Comment by nitingupta910** [comment]
@mkevac isn't include/rocksdb/c.h the C API you are looking for?
