### ISSUE TITLE
RocksDBException: Snappy not supported or corrupted Snappy compressed block contents

### ISSUE THREAD

**Issue by zhenyuyin** [facebook/rocksdb#4787]
I am using RocksJava version.
Some problems have been encountered. Can someone help me with this?
The required compression library is installed in the Linux environment, but the Windows environment does not know how to install these libraries.

After the database file generated in the Linux environment is copied to Windows Eclipse, the data cannot be read.

```java
org.rocksdb.RocksDBException: Snappy not supported or corrupted Snappy compressed block contents
```

Windows environment, how to install these compression libraries in order to use rocksjni? Shouldn't he integrate in librocksdbjni-win64.dll?

**Comment by adamretter** [comment]
So the RocksJava that we release for Windows does not have any compression support compiled in. 

This is because historically it has been very difficult to build the required compression dependencies on Windows and statically compile them in.

I did make some progress on getting this to work here - https://github.com/facebook/rocksdb/wiki/Building-on-Windows

@zhenyuyin If I built Windows binaries for you which include the Snappy compression support, would you be willing to test them for me? My concern has always been whether they will work on someone else's machine.

**Comment by zhenyuyin** [comment]
This is an excellent database, I am willing to help with the test.

**Comment by adamretter** [comment]
@zhenyuyin Okay, give me a few days...

**Comment by adamretter** [comment]
@zhenyuyin Okay I have built a binary for RocksJava for Windows x64 that I think includes support for compression types: Snappy, ZStd, LZ4, ZLib, and XPress.

It's available from: http://static.adamretter.org.uk/librocksdbjni-win64.dll

If you could give it a test and let me know if it works for you on Windows?

**Comment by zhenyuyin** [comment]
win10 64
Snappy, ZStd, LZ4, ZLib, XPress
It works fine !

**Comment by adamretter** [comment]
@zhenyuyin Thanks for testing. I will make sure the next release for Windows of RocksJava ships with the compression libraries.

**Comment by zhenyuyin** [comment]
java.lang.UnsatisfiedLinkError:C:\Users\Administrator\AppData\Local\Temp\librocksdbjni7322072655408916458.dll: 操作系统无法运行 %1。
win7 64  unusable

**Comment by adamretter** [comment]
@zhenyuyin Sorry I am not sure I understand your problem... You previously said that compression worked fine!

**Comment by zhenyuyin** [comment]
@adamretter  
Win10 can be used normally, but it cannot run when running on win7 64 operating system. 
Failed to load librocksdbjni-win64.dll

**Comment by adamretter** [comment]
@zhenyuyin does the released version (without compression) from Maven Central work on Windows 7?

**Comment by zhenyuyin** [comment]
@adamretter
Maven released no compressed version, can be used in win7, I said that there is a compressed version, can not be loaded on win7

**Comment by adamretter** [comment]
It's hard to know why this is. Perhaps it's the XPress compression that ships with Windows?

**Comment by zhenyuyin** [comment]
I saw that the dll file size on maven is 6734848, but the dll size with compression support is 4704256.
More compression library support, the file size has become smaller. I think it should be something you gave me this dll less

**Comment by adamretter** [comment]
@zhenyuyin Could you try this one please - http:///static.adamretter.org.uk/rocksdbjni-shared-no-xspress.dll

**Comment by zhenyuyin** [comment]
It works fine !

**Comment by adamretter** [comment]
@zhenyuyin okay great so I think the problem was that xpresss is not present in Win 7

**Comment by amandeep1991** [comment]
@adamretter : Thanks a lot Adam for this fix, I urgently required this and you made it so simple for us.

@zhenyuyin: Thanks for your efforts as well.

I was using it for for spark-nlp library:
- Environment:
1. windows 10 Enterprise 64 bit
2. scala 2.11.8
3. spark 2.3.3
4. spark-nlp 1.7.3
- Replaced 'http://static.adamretter.org.uk/librocksdbjni-win64.dll' from 'rocksdbjni-5.1.4.jar' jar which was the transitive dependency of one of the above jars
- Sample code to test it:
```
import com.johnsnowlabs.nlp.annotator._
import com.johnsnowlabs.nlp.annotators.ner.NerConverter
import com.johnsnowlabs.nlp.base._
import com.johnsnowlabs.util.Benchmark
import org.apache.spark.ml.Pipeline
import org.apache.spark.sql.SparkSession

object NerDLPipeline extends App {

  override def main(args: Array[String]): Unit = {
    val spark: SparkSession = SparkSession
      .builder()
      .appName("test")
      .master("local[*]")
      .config("spark.driver.memory", "12G")
      .config("spark.kryoserializer.buffer.max","200M")
      .config("spark.serializer","org.apache.spark.serializer.KryoSerializer")
      .getOrCreate()

    import spark.implicits._
    spark.sparkContext.setLogLevel("FATAL")

    val document = new DocumentAssembler()
      .setInputCol("text")
      .setOutputCol("document")

    val token = new Tokenizer()
      .setInputCols("document")
      .setOutputCol("token")

    val normalizer = new Normalizer()
      .setInputCols("token")
      .setOutputCol("normal")

    val ner = NerDLModel.pretrained()
      .setInputCols("normal", "document")
      .setOutputCol("ner")

    val nerConverter = new NerConverter()
      .setInputCols("document", "normal", "ner")
      .setOutputCol("ner_converter")

    val finisher = new Finisher()
      .setInputCols("ner", "ner_converter")
      .setIncludeMetadata(true)
      .setOutputAsArray(false)
      .setCleanAnnotations(false)
      .setAnnotationSplitSymbol("@")
      .setValueSplitSymbol("#")

    val pipeline = new Pipeline().setStages(Array(document, token, normalizer, ner, nerConverter, finisher))

    val testing = Seq(
      (1, "Google is a famous company"),
      (2, "Peter Parker is a super heroe")
    ).toDS.toDF( "_id", "text")

    val result = pipeline.fit(Seq.empty[String].toDS.toDF("text")).transform(testing)
    Benchmark.time("Time to convert and show") {result.select("ner", "ner_converter").show(truncate=false)}
  }
}
```

Thanks
