### ISSUE TITLE
DB::GetDbIdentity has wrong name or description

### ISSUE THREAD

**Issue by adamretter** [facebook/rocksdb#4803]
From `db.h`:

```C++
  // Sets the globally unique ID created at database creation time by invoking
  // Env::GenerateUniqueId(), in identity. Returns Status::OK if identity could
  // be set properly
  virtual Status GetDbIdentity(std::string& identity) const = 0;
```

I am not sure if the function should be renamed `SetDbIdentity` or if the description is wrong?

**Comment by riversand963** [comment]
I think the description is inaccurate. The function reads the IDENTITY file and stores the id in the variable `identity`.

**Comment by atulagrwl** [comment]
PR Created - https://github.com/facebook/rocksdb/pull/6354

**Comment by atulagrwl** [comment]
Request has been merged. The issue can be closed now.
