### ISSUE TITLE
change compression algorithm

### ISSUE THREAD

**Issue by nillith** [facebook/rocksdb#4824]
The code below gives a strange error: **Invalid argument: Compression type Snappy is not linked with the binary**

	#include<rocksdb/db.h>
	#include<iostream>

	using namespace rocksdb;
	using namespace std;
	int main() {
		Options options;
		options.IncreaseParallelism();
		options.OptimizeLevelStyleCompaction();
		options.create_if_missing = true;
		options.compression = ::rocksdb::CompressionType::kZSTD;
		DB* db;
		auto status = DB::Open(options, "db", &db);
		if (!status.ok()) {
			cerr << status.ToString() << endl;
			return EXIT_FAILURE;
		}
	}

I don't want to link it with snappy because I'll never use it.

**Comment by nillith** [comment]
Looks like I need to call `options.compression_per_level.clear()`

**Comment by ajkr** [comment]
Seems you figured it out. @miasantreble want to land #4325?
