### ISSUE TITLE
Support prepareForBulkLoad() in DBOptions in rocksjni

### ISSUE THREAD

**Issue by brary** [facebook/rocksdb#4834]
Hi, I have multiple column families and with multiple column families you can't use Options to open a database. You have to use `DBOptions`. If I want to use `prepareForBulkLoad()` in such scenerio how can I use it since there is no function `prepareForBulkLoad()` in `DBOptions`.

**Comment by sagar0** [comment]
You could try setting the options directly in the mean time in your application code. 
https://github.com/facebook/rocksdb/blob/b9d6eccac14588d03f083d22d577da0c0285143f/options/options.cc#L362-L405

**Comment by adamretter** [comment]
@brary @sagar0 So RocksDB in its C++ API does not support `PrepareForBulkLoad()` on its DBOptions class. It would need to be exposed in RocksDB C++ first, and then we could expose it in RocksJava.

**Comment by adamretter** [comment]
This isn't available in the C++ API.
