### ISSUE TITLE
Java implementation of Env.setBackgroundThreads() seems to handle argument incorrectly 

### ISSUE THREAD

**Issue by twblamer** [facebook/rocksdb#4847]
https://github.com/facebook/rocksdb/blob/v5.17.2/java/rocksjni/env.cc#L29

This code maps the second parameter from Java to C++ as follows:
- `org.rocksdb.Env.FLUSH_POOL` → `rocksdb::Env::Priority::LOW`
- `org.rocksdb.Env.COMPACTION_POOL` → `rocksdb::Env::Priority::HIGH`

AFAICT, this is doing the opposite of what it should. The `HIGH` priority thread pool is for flushes and the `LOW` priority thread pool is for compactions. This is according to the https://github.com/facebook/rocksdb/wiki/Thread-Pool page, and looking at the source code (db/db_impl_compaction_flush.cc).

Am I missing something?

```java
  switch (priority) {
    case org_rocksdb_Env_FLUSH_POOL:
      rocks_env->SetBackgroundThreads(num, rocksdb::Env::Priority::LOW);
      break;
    case org_rocksdb_Env_COMPACTION_POOL:
      rocks_env->SetBackgroundThreads(num, rocksdb::Env::Priority::HIGH);
      break;
}
```

**Comment by ajkr** [comment]
Yes you are right.. Do you want to contribute a fix?

**Comment by twblamer** [comment]
I think the fix has two parts:
1. Fix the mapping within the switch block in `java/rocksjni/env.cc`
2. Change the single-arg version of `Env.setBackgroundThreads()` in `java/src/main/java/org/rocksdb/Env.java` to pass `COMPACTION_POOL` instead of `FLUSH_POOL`. This is consistent with the `SetBackgroundThreads` API in `include/rocksdb/env.h.`.

AFAICT, there will be no change in behavior for Java clients currently using the single-arg version of `setBackgroundThreads()` because it "accidentally" does the right thing -- it passes the incorrect default `FLUSH_POOL`, which incorrectly gets mapped to `LOW` in the JNI implementation, but the net of both those things is that `LOW` is passed by default, same as the C++ API.

I can post a PR for this.

**Comment by adamretter** [comment]
@ajkr @twblamer Actually I have already fixed that - https://github.com/facebook/rocksdb/pull/4833/files#diff-aca5328bce113ce416df389234f688f7R47

**Comment by adamretter** [comment]
This was fixed in https://github.com/facebook/rocksdb/pull/4833/
