### ISSUE TITLE
Call the db->get() API, but the value returned has already been deleted

### ISSUE THREAD

**Issue by yangzhijia** [facebook/rocksdb#4854]
> Rocksdb version: 5.10.4

### Question
In our environment,
1. we put some kv into rocksdb (k1->v1) (k2->v2) ……
2. use rocksdb::WriteBatch to delete k1 k2, and call db->Write()
3. delete range()
4. compact range()
5. db->get() k1 k2

The value returned is v1 v2

I dumped all sst files with hex format , and found that the key was in 518249.sst
```
./sst_dump --file=518249.sst --command=scan --output_hex
```
![image](https://user-images.githubusercontent.com/10767033/50826546-e32da980-1376-11e9-9104-2b3db4c1122a.png)

In the above figure,  the key(016972F81A75BE746473630000000000000000, 016975F81A75BE726473630000000000000000) has been deleted.  But when we use the ldb tools to get the key, we get the old value.
![image](https://user-images.githubusercontent.com/10767033/50827823-7e744e00-137a-11e9-8a6c-706ed143f9ec.png)
![image](https://user-images.githubusercontent.com/10767033/50827869-af548300-137a-11e9-92ca-1e92cca53900.png)

@ajkr @abhimadan

**Comment by sagar0** [comment]
Delete Range improved significantly over the last few months. Are you able to reproduce this issue with the latest version of RocksDB, 5.17.2 ?

**Comment by yangzhijia** [comment]
We use rocksdb as the local storage in our production environment. The lastest version of rocksdb has not been used so far. Is there any bugs with Delete Range which causes the above problems?
