### ISSUE TITLE
is there a way to stop running CompactRange task?

### ISSUE THREAD

**Issue by xmm1989218** [facebook/rocksdb#4855]
is there a way to stop running CompactRange task?

**Comment by sagar0** [comment]
For questions, discussions, feature requests, etc. post to RocksDB dev group https://www.facebook.com/groups/rocksdb.dev. 

Did you try using `CancelAllBackgroundWork`?

**Comment by ramvadiv** [comment]
Note: Please use GitHub Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Closing out this issue.
