### ISSUE TITLE
DB shutdown takes too long and and sometimes corrupts data if process is killed

### ISSUE THREAD

**Issue by LeTurt** [facebook/rocksdb#4865]
TurtleCoinD uses RocksDB and the shutdown time of the RocksDB takes anything from 1 second to 1 hour. This leads to users often killing the process, which sometimes leads to corruption of the DB when user gets bored and kills it.

### Expected behavior
The database should exit cleanly, fast, and definitely not corrupt itself in any case.

### Actual behavior
It takes 1s-1h to shutdown and corrupts the data sometimes if exit is not "clean".

### Steps to reproduce the behavior
Install TurtleCoinD. Have it synch for a good while. Shut it down. If it takes too long, kill the process.

If there is some specific way that RocksDB should be used or could be used to avoid this type of issue, please advice.

You may find the integration code here:
https://github.com/turtlecoin/turtlecoin/blob/development/src/CryptoNoteCore/RocksDBWrapper.cpp

Thank you.

**Comment by siying** [comment]
Can you provide more detail on what it takes 2 sec to 1 hour and why killing it causes corruption? Corruption is not expected when the process is killed at any time. If you see it, it's a bug.
Can you paste the error message reporting it is corrupted?
Do you know what RocksDB does in the 1 sec to 1h? Did you disable WAL sync so it was doing memtable flush?

**Comment by LeTurt** [comment]
Thanks for your quick reply! The corruption error message is actually coming when trying to reload the blockchain after a restart when the user killed the process on exit. Unfortunately I do not have a log of a case where the shutdown takes too long at hand. But I will try to get one and get back to you. 

It is also possible that there is some related issue in the some of the TC legacy codebase that builds / loads the batches to save. The blockchain size is some 50+ GB right now. Just for reference, do you have any estimate how long writing it to disk should take for RocksDB? Assuming that in most cases not all blocks/transactions are "new" since the last start (some of that 50GB can already be there)?

**Comment by LeTurt** [comment]
Closing for now, we need to investigate this issue deeper. Sorry for the overly eager reporting, I had the impression when discussion with them peers and looking at the daemon output that there was DB corruption. After looking deeper need to investigate the overall pattern more. Thanks for the help.
