### ISSUE TITLE
Master branch build failing with jemalloc on Ubuntu 18.04

### ISSUE THREAD

**Issue by varadharajan** [facebook/rocksdb#4869]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Actual behavior
```shell
# make -j 8 shared_lib
  GEN      util/build_version.cc
  CC       shared-objects/db/malloc_stats.o
  CC       shared-objects/db/wal_manager.o
  CC       shared-objects/db/write_batch.o
  CC       shared-objects/db/write_batch_base.o
  CC       shared-objects/db/write_controller.o
  CC       shared-objects/db/write_thread.o
  CC       shared-objects/env/env.o
  CC       shared-objects/env/env_chroot.o
In file included from db/malloc_stats.cc:16:
./port/jemalloc_helper.h:33:5: error: expected initializer before ‘JEMALLOC_CXX_THROW’
     JEMALLOC_CXX_THROW __attribute__((__weak__));
     ^~~~~~~~~~~~~~~~~~
./port/jemalloc_helper.h: In function ‘bool HasJemalloc()’:
./port/jemalloc_helper.h:46:62: error: the address of ‘size_t malloc_usable_size(void*)’ will never be NULL [-Werror=address]
          malloc_stats_print != nullptr && malloc_usable_size != nullptr;
                                           ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
```

### Steps to reproduce the behavior

On a fresh Ubuntu 18.04 installation, i installed the compression related dependency libs + libjemalloc-dev and tried compiling, which resulted in the above failure. However, i was able to build the 5.17.2 release though. I think this is something to do with https://github.com/facebook/rocksdb/pull/4844 ? (cc @yiwu-arbug). Please let me know if i'm missing something.

**Comment by gnayli** [comment]
I hit the same issue when making it on ubuntu 18.04

**Comment by adamretter** [comment]
There is a fix here - https://github.com/facebook/rocksdb/pull/4943
