### ISSUE TITLE
options_helper.cc passes const std::unordered_map by value 

### ISSUE THREAD

**Issue by xunjieli** [facebook/rocksdb#4873]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
In options_helper.cc, 
GetStringFromStruct, SerializeSingleStructOption and GetStringFromStruct should pass
std::unordered_map by const reference 

### Actual behavior
GetStringFromStruct, SerializeSingleStructOption and GetStringFromStruct makes a copy of
std::unordered_map during each method invocation

### Steps to reproduce the behavior
Obtain a heap profile during DB initialization, you can see a lot of std::unordered_map being allocated.

**Comment by mrambacher** [comment]
The Configurable classes replaced these internal methods and use const references.
