### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [facebook/rocksdb#4939]
ubuntun18

orange@orange:~/work/rust/material/main/cpprust$ g++  rocksmain.cpp -o rocksmain  librocksdb.a  -lpthread 
librocksdb.a(block_based_table_reader.o): In function `rocksdb::BlockBasedTable::PutDataBlockToCache(rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::Cache*, rocksdb::Cache*, rocksdb::ReadOptions const&, rocksdb::ImmutableCFOptions const&, rocksdb::BlockBasedTable::CachableEntry<rocksdb::Block>*, rocksdb::BlockContents*, rocksdb::CompressionType, unsigned int, rocksdb::UncompressionDict const&, unsigned long, unsigned long, rocksdb::MemoryAllocator*, bool, rocksdb::Cache::Priority, rocksdb::GetContext*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(block_based_table_reader.o): In function `rocksdb::BlockBasedTable::GetDataBlockFromCache(rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::Cache*, rocksdb::Cache*, rocksdb::BlockBasedTable::Rep*, rocksdb::ReadOptions const&, rocksdb::BlockBasedTable::CachableEntry<rocksdb::Block>*, rocksdb::UncompressionDict const&, unsigned long, bool, rocksdb::GetContext*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(block_based_table_reader.o):/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: more undefined references to `ZSTD_freeDCtx' follow
librocksdb.a(compaction_job.o): In function `rocksdb::CompactionJob::ProcessKeyValueCompaction(rocksdb::CompactionJob::SubcompactionState*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1279: undefined reference to `ZDICT_trainFromBuffer'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1280: undefined reference to `ZDICT_isError'
librocksdb.a(options_helper.o): In function `rocksdb::GetSupportedCompressions()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:438: undefined reference to `ZSTD_versionNumber'
librocksdb.a(format.o): In function `rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionInfo const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableCFOptions const&, rocksdb::MemoryAllocator*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1232: undefined reference to `ZSTD_decompress_usingDict'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:530: undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:849: undefined reference to `BZ2_bzDecompressInit'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:690: undefined reference to `inflateInit2_'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:716: undefined reference to `inflate'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:748: undefined reference to `inflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1009: undefined reference to `LZ4_createStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1012: undefined reference to `LZ4_setStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1015: undefined reference to `LZ4_decompress_safe_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1018: undefined reference to `LZ4_freeStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1009: undefined reference to `LZ4_createStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1012: undefined reference to `LZ4_setStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1015: undefined reference to `LZ4_decompress_safe_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1018: undefined reference to `LZ4_freeStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:740: undefined reference to `inflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:541: undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:698: undefined reference to `inflateSetDictionary'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:864: undefined reference to `BZ2_bzDecompress'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:894: undefined reference to `BZ2_bzDecompressEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:886: undefined reference to `BZ2_bzDecompressEnd'
librocksdb.a(column_family.o): In function `rocksdb::CheckCompressionSupported(rocksdb::ColumnFamilyOptions const&)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:438: undefined reference to `ZSTD_versionNumber'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1259: undefined reference to `ZSTD_versionNumber'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:438: undefined reference to `ZSTD_versionNumber'
librocksdb.a(db_impl.o): In function `rocksdb::DBImpl::DBImpl(rocksdb::DBOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:438: undefined reference to `ZSTD_versionNumber'
librocksdb.a(block_based_table_builder.o): In function `rocksdb::CompressBlock(rocksdb::Slice const&, rocksdb::CompressionInfo const&, rocksdb::CompressionType*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:609: undefined reference to `deflateInit2_'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:618: undefined reference to `deflateSetDictionary'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:636: undefined reference to `deflate'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:622: undefined reference to `deflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1162: undefined reference to `ZSTD_compressBound'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1178: undefined reference to `ZSTD_compress_usingCDict'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1184: undefined reference to `ZSTD_compress_usingDict'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:514: undefined reference to `snappy::MaxCompressedLength(unsigned long)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:516: undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:789: undefined reference to `BZ2_bzCompressInit'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:803: undefined reference to `BZ2_bzCompress'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:812: undefined reference to `BZ2_bzCompressEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:934: undefined reference to `LZ4_compressBound'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:939: undefined reference to `LZ4_createStream'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:946: undefined reference to `LZ4_compress_fast_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:954: undefined reference to `LZ4_freeStream'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1070: undefined reference to `LZ4_compressBound'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1081: undefined reference to `LZ4_createStreamHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1082: undefined reference to `LZ4_resetStreamHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1087: undefined reference to `LZ4_loadDictHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1091: undefined reference to `LZ4_compress_HC_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1099: undefined reference to `LZ4_freeStreamHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:645: undefined reference to `deflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:812: undefined reference to `BZ2_bzCompressEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:942: undefined reference to `LZ4_loadDict'
librocksdb.a(block_based_table_builder.o): In function `rocksdb::BlockBasedTableBuilder::~BlockBasedTableBuilder()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:306: undefined reference to `ZSTD_freeCCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:190: undefined reference to `ZSTD_freeCDict'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(block_based_table_builder.o): In function `rocksdb::CompressionDict::~CompressionDict()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:190: undefined reference to `ZSTD_freeCDict'
librocksdb.a(block_based_table_builder.o): In function `rocksdb::BlockBasedTableBuilder::Rep::Rep(rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::BlockBasedTableOptions const&, rocksdb::InternalKeyComparator const&, std::vector<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> >, std::allocator<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> > > > const*, unsigned int, rocksdb::WritableFileWriter*, rocksdb::CompressionType, rocksdb::CompressionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:180: undefined reference to `ZSTD_createCDict'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:300: undefined reference to `ZSTD_createCCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:306: undefined reference to `ZSTD_freeCCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:190: undefined reference to `ZSTD_freeCDict'
librocksdb.a(compression_context_cache.o): In function `rocksdb::CompressionContextCache::~CompressionContextCache()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(compression_context_cache.o): In function `rocksdb::CompressionContextCache::GetCachedZSTDUncompressData()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:103: undefined reference to `ZSTD_createDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:103: undefined reference to `ZSTD_createDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(compression_context_cache.o): In function `rocksdb::CoreLocalArray<rocksdb::compression_cache::ZSTDCachedData>::CoreLocalArray()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:114: undefined reference to `ZSTD_freeDCtx'
collect2: error: ld returned 1 exit status
orange@orange:~/work/rust/material/main/cpprust$ g++  rocksmain.cpp -o rocksmain  librocksdb.a  -lpthread 
librocksdb.a(block_fetcher.o): In function `rocksdb::BlockFetcher::ReadBlockContents()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(compaction_job.o): In function `rocksdb::CompactionJob::ProcessKeyValueCompaction(rocksdb::CompactionJob::SubcompactionState*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1074: undefined reference to `ZDICT_trainFromBuffer'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1075: undefined reference to `ZDICT_isError'
librocksdb.a(options_helper.o): In function `rocksdb::GetSupportedCompressions()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:273: undefined reference to `ZSTD_versionNumber'
librocksdb.a(block_based_table_reader.o): In function `rocksdb::BlockBasedTable::GetDataBlockFromCache(rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::Cache*, rocksdb::Cache*, rocksdb::ImmutableCFOptions const&, rocksdb::ReadOptions const&, rocksdb::BlockBasedTable::CachableEntry<rocksdb::Block>*, unsigned int, rocksdb::Slice const&, unsigned long, bool, rocksdb::GetContext*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(block_based_table_reader.o): In function `rocksdb::BlockBasedTable::PutDataBlockToCache(rocksdb::Slice const&, rocksdb::Slice const&, rocksdb::Cache*, rocksdb::Cache*, rocksdb::ReadOptions const&, rocksdb::ImmutableCFOptions const&, rocksdb::BlockBasedTable::CachableEntry<rocksdb::Block>*, rocksdb::Block*, unsigned int, rocksdb::Slice const&, unsigned long, bool, rocksdb::Cache::Priority, rocksdb::GetContext*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(block_based_table_reader.o):/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: more undefined references to `ZSTD_freeDCtx' follow
librocksdb.a(format.o): In function `rocksdb::UncompressBlockContentsForCompressionType(rocksdb::UncompressionContext const&, char const*, unsigned long, rocksdb::BlockContents*, unsigned int, rocksdb::ImmutableCFOptions const&)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1046: undefined reference to `ZSTD_decompress_usingDict'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:366: undefined reference to `snappy::GetUncompressedLength(char const*, unsigned long, unsigned long*)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:526: undefined reference to `inflateInit2_'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:533: undefined reference to `inflateSetDictionary'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:551: undefined reference to `inflate'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:585: undefined reference to `inflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:842: undefined reference to `LZ4_createStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:847: undefined reference to `LZ4_decompress_safe_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:850: undefined reference to `LZ4_freeStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:685: undefined reference to `BZ2_bzDecompressInit'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:700: undefined reference to `BZ2_bzDecompress'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:732: undefined reference to `BZ2_bzDecompressEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:842: undefined reference to `LZ4_createStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:847: undefined reference to `LZ4_decompress_safe_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:850: undefined reference to `LZ4_freeStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:724: undefined reference to `BZ2_bzDecompressEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:377: undefined reference to `snappy::RawUncompress(char const*, unsigned long, char*)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:577: undefined reference to `inflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:844: undefined reference to `LZ4_setStreamDecode'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:844: undefined reference to `LZ4_setStreamDecode'
librocksdb.a(compression_context_cache.o): In function `rocksdb::CompressionContextCache::~CompressionContextCache()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(compression_context_cache.o): In function `rocksdb::CompressionContextCache::GetCachedZSTDUncompressData()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:84: undefined reference to `ZSTD_createDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:84: undefined reference to `ZSTD_createDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(compression_context_cache.o): In function `rocksdb::CoreLocalArray<rocksdb::compression_cache::ZSTDCachedData>::CoreLocalArray()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(column_family.o): In function `rocksdb::CheckCompressionSupported(rocksdb::ColumnFamilyOptions const&)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:273: undefined reference to `ZSTD_versionNumber'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:273: undefined reference to `ZSTD_versionNumber'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:273: undefined reference to `ZSTD_versionNumber'
librocksdb.a(db_impl.o): In function `rocksdb::DBImpl::DBImpl(rocksdb::DBOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:273: undefined reference to `ZSTD_versionNumber'
librocksdb.a(block_based_table_builder.o): In function `rocksdb::CompressBlock(rocksdb::Slice const&, rocksdb::CompressionContext const&, rocksdb::CompressionType*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:445: undefined reference to `deflateInit2_'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:453: undefined reference to `deflateSetDictionary'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:471: undefined reference to `deflate'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:457: undefined reference to `deflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:994: undefined reference to `ZSTD_compressBound'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:1008: undefined reference to `ZSTD_compress_usingDict'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:350: undefined reference to `snappy::MaxCompressedLength(unsigned long)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:352: undefined reference to `snappy::RawCompress(char const*, unsigned long, char*, unsigned long*)'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:625: undefined reference to `BZ2_bzCompressInit'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:639: undefined reference to `BZ2_bzCompress'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:648: undefined reference to `BZ2_bzCompressEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:771: undefined reference to `LZ4_compressBound'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:776: undefined reference to `LZ4_createStream'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:782: undefined reference to `LZ4_compress_fast_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:790: undefined reference to `LZ4_freeStream'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:901: undefined reference to `LZ4_compressBound'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:912: undefined reference to `LZ4_createStreamHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:913: undefined reference to `LZ4_resetStreamHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:917: undefined reference to `LZ4_loadDictHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:921: undefined reference to `LZ4_compress_HC_continue'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:929: undefined reference to `LZ4_freeStreamHC'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:648: undefined reference to `BZ2_bzCompressEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:480: undefined reference to `deflateEnd'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:778: undefined reference to `LZ4_loadDict'
librocksdb.a(block_based_table_builder.o): In function `rocksdb::BlockBasedTableBuilder::~BlockBasedTableBuilder()':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:156: undefined reference to `ZSTD_freeCCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
librocksdb.a(block_based_table_builder.o): In function `rocksdb::BlockBasedTableBuilder::Rep::Rep(rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::BlockBasedTableOptions const&, rocksdb::InternalKeyComparator const&, std::vector<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> >, std::allocator<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> > > > const*, unsigned int, rocksdb::WritableFileWriter*, rocksdb::CompressionType, rocksdb::CompressionOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned long)':
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:150: undefined reference to `ZSTD_createCCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:95: undefined reference to `ZSTD_freeDCtx'
/home/orange/work/rust/material/main/rocksdb/./util/compression.h:156: undefined reference to `ZSTD_freeCCtx'
collect2: error: ld returned 1 exit status

**Comment by Gabriel-Gardin** [comment]
What was causing the error?

**Comment by mrambacher** [comment]
> What was causing the error?

I believe this is an error in building the user application. RocksDB was built against some compression libraries that were not on the link line for the user application.
