### ISSUE TITLE
delete a not exist key and return ok 

### ISSUE THREAD

**Issue by darionyaphet** [facebook/rocksdb#4975]
When I delete a not exist key, the status is `OK` but I think it should be `IsNotFound`.

```
    rocksdb::DB *db;
    rocksdb::Options options;
    options.create_if_missing = true;
    rocksdb::Status status = rocksdb::DB::Open(options, "/tmp/test.db", &db);
    assert(status.ok());

    rocksdb::Status deleteStatus = db->Delete(rocksdb::WriteOptions(), "missed");
    if (deleteStatus.ok()) {
        std::cout << "delete OK " << std::endl;
    } else if (deleteStatus.IsNotFound()) {
        std::cout << "delete key missed " << std::endl;
    }
```

### Expected behavior

`deleteStatus IsNotFound`

### Actual behavior

`deleteStatus is OK`

**Comment by sel-fish** [comment]
Rocksdb will not try to get the key when delete, just append a record the mark the key is deleted.

**Comment by darionyaphet** [comment]
@sel-fish thanks !  RocksDB will support `exist(key)` to check whether key is exist ？
