### ISSUE TITLE
Add compression options to TableProperties

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#4992]
It looks like only compression name is given to TableProperties. Since we are planning to use dictionary compression and to use different compression level, it is quite useful to add compression options to it, even just integers. For example, in MyRocks, if the feature is available, we can query from information_schema.rocksdb_sst_props to see if all sst files are converted to ZSTD dictionary compressions.

**Comment by miasantreble** [comment]
CompressionOptions has a few fields, do we want to add all of them to TableProperties or just `level`?
