### ISSUE TITLE
CompactRange avoid double-compacting data in bottom level

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#4995]
Depending on the config, CompactRange does following compactions:
L0->L1
L1->L2
...
Ln-1 -> Ln
Ln -> Ln
The final Ln -> Ln compaction is partly unnecessary as it recompacts all the files that were just generated by the Ln-1 -> Ln. We should avoid recompacting such files. That rule should be applied to Lmax only.

**Comment by miasantreble** [comment]
@ajkr trying to understand the problem better, is the goal to skip bottom level compaction or to skip files that were newly created from level Ln-1 as part of the current compaction?

**Comment by ajkr** [comment]
The latter. The Ln->Ln compactions currently take all files in Ln as input. However, some of those files were recently created by an Ln-1->Ln compaction as part of the same manual compaction. For those files we just created in Ln, there should be no need to put them through any more compactions.

**Comment by ajkr** [comment]
I think Yoshi had some important insights into this in the internal task.
