### ISSUE TITLE
remove `max_valid_backups_to_open backup` option

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#4997]
I believe it is fundamentally flawed and should be removed. When set, it messes up reference counting and causes shared files to be deleted by surprise.

**Comment by pdillinger** [comment]
#3518 looks like you fixed the deletion by surprise, but in our current environment, not deleting by surprise is essentially as bad. I think it's ok to allow the option *only* for read-only backup engine.

**Comment by pdillinger** [comment]
Proposal: if the option is set to something other than default and opening !read_only, ignore the configured value (treat as default) and issue a warning to the log. Use the value if opening read_only. With this we should be able to delete the confusing logic around this option in the backup deletion and collection code.

Proposed addition to HISTORY.md under "unreleased" "Public API Change":
* The option BackupableDBOptions::max_valid_backups_to_open is now only used when opening BackupEngineReadOnly. When opening a read/write BackupEngine, anything but the default value logs a warning and is treated as the default. This change ensures that backup deletion has proper accounting of shared files to ensure they are deleted when no longer referenced by a backup.

**Comment by ajkr** [comment]
> not deleting by surprise is essentially as bad.

Does the problem still happen if users follow the procedure of occasionally opening a writable backup engine with `max_valid_backups_to_open = MAX_INT`? Just curious - in any case I am happy to see the option disabled for writable backup engines, as the proper procedure for using it is too surprising/error-prone.

> Proposal: if the option is set to something other than default and opening !read_only, ignore the configured value (treat as default) and issue a warning to the log. Use the value if opening read_only. With this we should be able to delete the confusing logic around this option in the backup deletion and collection code.

Sounds good to me.

**Comment by pdillinger** [comment]
> Does the problem still happen if users follow the procedure of occasionally opening a writable backup engine with `max_valid_backups_to_open = MAX_INT`?

In theory, that should be OK, but I agree it's just too hazardous. I looked at Facebook-internal uses of the option in forming my proposal. ;)

**Comment by pdillinger** [comment]
Essentially fixed by #6072
