### ISSUE TITLE
wrong level argument passed to LevelIterator

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#4998]
@abhimadan found this. https://github.com/facebook/rocksdb/blob/4db46aa2e678cdd59ae27653fbefeb438512ec8a/db/version_set.cc#L4393 passes `static_cast<int>(which)` but should be `c->level(which)`. The impact should be assessed.

**Comment by suiyuan2009** [comment]
how do you find this?

**Comment by ajkr** [comment]
IIRC, @abhimadan was reading the code and noticed that level is determined differently here compared to a few lines above: https://github.com/facebook/rocksdb/blob/a661c0d2085b6de1ff745eb83f056a87801985b4/db/version_set.cc#L4371

**Comment by ajkr** [comment]
Fixed by #6920.
