### ISSUE TITLE
Memory leak in Test

### ISSUE THREAD

**Issue by SeterKwok** [facebook/rocksdb#5008]
https://github.com/facebook/rocksdb/blob/db2445ad244fd9fefe02900fc99e47aafddbfe52/java/src/test/java/org/rocksdb/WriteBatchTest.java#L195

There is an unused WriteOptions called wOpt, which is expected to use here. Creating a new WriteOptions will lead to a memory leak.

**Comment by riversand963** [comment]
I think the original wOpt will be GCed after it goes out of scope. Have you observed increased memory consumption due to this?

**Comment by SeterKwok** [comment]
> I think the original wOpt will be GCed after it goes out of scope. Have you observed increased memory consumption due to this?

No, in fact I haven't do a memory leak test... Just a small suggestion.
wOpt is in a try-with-resource statement but `new WriteOptions()` is not. So I think the latter will not be GCed. That's why I think it's better to use wOpt here instead of creating a new one.

**Comment by riversand963** [comment]
I believe Java does not require the programmer to take care of object destruction. Every object has a scope, when it goes out of scope, JVM has a way of identifying the object's memory as garbage and reclaim it at a proper time.
That being said, you are right that there is a redundancy here. Would you be willing to submit a PR to fix it?

**Comment by SeterKwok** [comment]
> I believe Java does not require the programmer to take care of object destruction. Every object has a scope, when it goes out of scope, JVM has a way of identifying the object's memory as garbage and reclaim it at a proper time.
> That being said, you are right that there is a redundancy here. Would you be willing to submit a PR to fix it?

I admit it is not a serious problem and this object may be automatically GCed... However, referring to [the doc](https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#memory-management), I think it's better to use wOpt, which will be closed explicitly. I may fix it when I have time.

**Comment by riversand963** [comment]
Thanks.
I believe the underlying object will be managed by JVM such as [hotspot](https://en.wikipedia.org/wiki/HotSpot). If you create an object in your java code, JVM knows about it and takes care of its reclamation.
It's true that we should intentionally make the programs more GC-friendly by avoiding unnecessary object re-creations.

**Comment by siying** [comment]
@riversand963 I think it's a good idea to follow the best practice even in test code. Users may copy the code in their application which is bad.
And yes, we should call WriteOptions.close(). @SeterKwok are you interested in contributing an improvement?

**Comment by siying** [comment]
Regarding finalizer, this is what book "Effective Java" says: http://www.informit.com/articles/article.aspx?p=1216151&seqNum=7
