### ISSUE TITLE
Does the iterator guarantee unique keys?

### ISSUE THREAD

**Issue by vinniefalco** [facebook/rocksdb#501]
If I iterate a database is it guaranteed that there will be no duplicate keys?

**Comment by igorcanadi** [comment]
Yes.

**Comment by siying** [comment]
@vinniefalco RocksDB doesn't allow duplicate keys. Put() will overwrite existing value with the same key. Iterators are supposed to return what DB has, so you shouldn't see a duplicated key.

**Comment by vinniefalco** [comment]
Thanks
