### ISSUE TITLE
Problem with unresolved external symbols on windows 

### ISSUE THREAD

**Issue by suzanne-stathatos** [facebook/rocksdb#5012]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
It builds and compiles. 

### Actual behavior
I get the following linking errors
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp__RpcStringFreeA@4 referenced in function "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall rocksdb::Env::GenerateUniqueId(void)" (?GenerateUniqueId@Env@rocksdb@@UAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	C:\Users\sstat\project\rocksdb.lib(env_win.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp__UuidCreateSequential@4 referenced in function "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall rocksdb::Env::GenerateUniqueId(void)" (?GenerateUniqueId@Env@rocksdb@@UAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	C:\Users\sstat\project\rocksdb.lib(env_win.obj)	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol __imp__UuidToStringA@8 referenced in function "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall rocksdb::Env::GenerateUniqueId(void)" (?GenerateUniqueId@Env@rocksdb@@UAE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)	C:\Users\sstat\project\rocksdb.lib(env_win.obj)	1	

### Steps to reproduce the behavior
Build and link the project

**Comment by vanturman** [comment]
So, could you tell me how to solve this problem? I tried to fix this the whole day but still can not fix it. Thx @suzanne-stathatos

**Comment by suzanne-stathatos** [comment]
@vanturman I included Rpcrt4.lib in my cmake file. Alternatively, you could include it in the source code file that uses rocks, per the suggestion here https://stackoverflow.com/questions/1991941/how-to-solve-link-error-on-call-to-uuidtostring

**Comment by vanturman** [comment]
Thx. I have tried your solution but it doesn't seem work. I think this is the key point that causes this link problem below.

Only the rocksdb c interface is in the symbol file of the lib. The rocksdb.dll file in the bin directory also only has the c interface.
The C++ interface for rocksdb does not include export declspecs at all, so rocksdb would need to be built as a static library, not a shared library, in order for the C++ interfaces to be available. 

Since i installs rocksdb using vcpkg, this problem turns to be how to build rocksdb as a statis library using vcpkg? It seems that just running command `vcpkg install rocksdb:x64-windows-static` does not work.

**Comment by vanturman** [comment]
> @vanturman I included Rpcrt4.lib in my cmake file. Alternatively, you could include it in the source code file that uses rocks, per the suggestion here https://stackoverflow.com/questions/1991941/how-to-solve-link-error-on-call-to-uuidtostring

I don't mean to bother you. However, could you tell me how to include Rpcrt4.lib in the cmake file. Is  cmake file the vcpkg/ports/rocksdb/portfile.cmake file, right? Thx a lot.

**Comment by ras0219-msft** [comment]
@vanturman You'll need to include rpcrt4.lib in your consuming project

**Comment by vanturman** [comment]
@ras0219-msft Thanks a lot.
