### ISSUE TITLE
make rocksdbjava failed on ubuntu 

### ISSUE THREAD

**Issue by royforu** [facebook/rocksdb#5016]
Hello everyone,

## Expected behavior
It builds and compiles.

## Actual behavior
when i compiled with command `make static_lib`, it just be fine. And it produced `librocksdb.a` well. After that, I compiled with command `make rocksdbjava`, it showed the following messages:
```
28 warnings
javah -cp target/classes -d ./include -jni org.rocksdb.AbstractCompactionFilter org.rocksdb.AbstractCompactionFilterFactory org.rocksdb.AbstractSlice org.rocksdb.AbstractTransactionNotifier org.rocksdb.BackupEngine org.rocksdb.BackupableDBOptions org.rocksdb.BlockBasedTableConfig org.rocksdb.BloomFilter org.rocksdb.Checkpoint org.rocksdb.ClockCache org.rocksdb.CassandraCompactionFilter org.rocksdb.CassandraValueMergeOperator org.rocksdb.ColumnFamilyHandle org.rocksdb.ColumnFamilyOptions org.rocksdb.CompactionOptionsFIFO org.rocksdb.CompactionOptionsUniversal org.rocksdb.CompactRangeOptions org.rocksdb.Comparator org.rocksdb.ComparatorOptions org.rocksdb.CompressionOptions org.rocksdb.DBOptions org.rocksdb.DirectComparator org.rocksdb.DirectSlice org.rocksdb.Env org.rocksdb.EnvOptions org.rocksdb.FlushOptions org.rocksdb.Filter org.rocksdb.IngestExternalFileOptions org.rocksdb.HashLinkedListMemTableConfig org.rocksdb.HashSkipListMemTableConfig org.rocksdb.Logger org.rocksdb.LRUCache org.rocksdb.MemoryUsageType org.rocksdb.MemoryUtil org.rocksdb.MergeOperator org.rocksdb.NativeComparatorWrapper org.rocksdb.OptimisticTransactionDB org.rocksdb.OptimisticTransactionOptions org.rocksdb.Options org.rocksdb.OptionsUtil org.rocksdb.PlainTableConfig org.rocksdb.RateLimiter org.rocksdb.ReadOptions org.rocksdb.RemoveEmptyValueCompactionFilter org.rocksdb.RestoreOptions org.rocksdb.RocksCallbackObject org.rocksdb.RocksDB org.rocksdb.RocksEnv org.rocksdb.RocksIterator org.rocksdb.RocksMemEnv org.rocksdb.SkipListMemTableConfig org.rocksdb.Slice org.rocksdb.SstFileManager org.rocksdb.SstFileWriter org.rocksdb.Statistics org.rocksdb.Transaction org.rocksdb.TransactionDB org.rocksdb.TransactionDBOptions org.rocksdb.TransactionOptions org.rocksdb.TransactionLogIterator org.rocksdb.TtlDB org.rocksdb.VectorMemTableConfig org.rocksdb.Snapshot org.rocksdb.StringAppendOperator org.rocksdb.UInt64AddOperator org.rocksdb.WriteBatch org.rocksdb.WriteBatch.Handler org.rocksdb.WriteOptions org.rocksdb.WriteBatchWithIndex org.rocksdb.WriteBufferManager org.rocksdb.WBWIRocksIterator
Error: Could not find class file for 'org.rocksdb.AbstractCompactionFilter'.
Makefile:213: recipe for target 'java' failed
make[1]: *** [java] Error 1
make[1]: Leaving directory '/home/roy/test_rocksdb/rocksdb/java'
Makefile:1896: recipe for target 'rocksdbjava' failed
make: *** [rocksdbjava] Error 2
```

=====================================

what kind of problems went wrong?     
Steps to reproduce the behavior
just make rocksdbjava

environment:
OS: ubuntu version: 18.04
rocksdb version: 6.0.0
g++ version: 7.3.0
java version: 
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4, mixed mode)

   
Thanks for everyone's help~~

**Comment by adamretter** [comment]
Are you building from GitHub source?

I found on Ubuntu that I needed to apply at least this patch to build - https://github.com/facebook/rocksdb/pull/4943

**Comment by royforu** [comment]
Hi @adamretter 
Yes, i build it from github source and still the same error message after patch 4943 
Error: Could not find class file for 'org.rocksdb.AbstractCompactionFilter'.

**Comment by royforu** [comment]
Hi @adamretter
i found my java setting doesn't work well and maybe it's the cause to compile failure.
i try build it on centos and it build well.  thx for help~~

**Comment by royforu** [comment]
Hi @adamretter
i try to reinstall ubuntu again and build and find it's fine to compile well. 
So my previous problem is that my java setting isn't correct. 
So this issue should be closed. 
Thanks for your reply & help.

**Comment by marcdk** [comment]
Hi @royforu

I'm hoping you could help me out on the exact issue you were having in https://github.com/facebook/rocksdb/issues/5016#issuecomment-468998289

Did you find out what Java setting was incorrect?

The build is taking place in IBM Cloud with OpenJDK8:
```
>> uname -a
Linux df826417d65b 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:37:28 UTC 2020 s390x s390x s390x GNU/Linux
>> java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Zero VM (build 25.265-b01, interpreted mode)
```

Thanks for any help!!

**Comment by adamretter** [comment]
@marcdk Here is an example of building on s390x Ubuntu, perhaps it helps you? - https://github.com/facebook/rocksdb/pull/6168

**Comment by marcdk** [comment]
Thanks @adamretter, I've built with your fork/PR6168, but I get the same result as in https://github.com/facebook/rocksdb/issues/5487#issuecomment-711133303

**Comment by adamretter** [comment]
@marcdk Okay as the build is working, your issue is at runtime now. I will reply in #5487
