### ISSUE TITLE
Does setting num_levels = N yield levels L0 -> LN? or L0 -> LN-1?

### ISSUE THREAD

**Issue by ekg** [facebook/rocksdb#502]
If I say I want 4 levels, does this include level 0?

**Comment by igorcanadi** [comment]
L0->LN-1. So yes.

**Comment by ekg** [comment]
So level 0 is the "first level" and level 1 the second. I guess this is why
my db didn't make it to the level I thought!

**Comment by igorcanadi** [comment]
Yup :)
