### ISSUE TITLE
 Segmentation fault at rocksdb::DBWithTTLImpl::Get

### ISSUE THREAD

**Issue by 914022466** [facebook/rocksdb#5028]
when program run for n days (n > 10) ，it suddenly happens a segmentation fault.
![lark20190228113501](https://user-images.githubusercontent.com/13954644/53539543-ea8a5b80-3b4c-11e9-85ab-bf4d4ca5fc57.png)
after it,rocksdb seems to be wrong
![image](https://user-images.githubusercontent.com/13954644/53539585-1c9bbd80-3b4d-11e9-9563-768acd9d0f4b.png)
our read rocksdb code is: 
```
rocksdb::ReadOptions ropt;
ropt.ignore_range_deletions = true;
rocks_db_->Get(ropt, cfs_[Hash(key) % cfs_.size()], key, val);
```

**Comment by avisrivastava254084** [comment]
@914022466 Can you give some details about the language used? It looks like C++, isn't it?
And is it safe to presume that just the three lines pasted above if somehow made run for n days with n being greater than 10, it would result in segmentation fault?
