### ISSUE TITLE
Cannot iterate over db when useFixedLengthPrefixExtractor is set

### ISSUE THREAD

**Issue by aaudiber** [facebook/rocksdb#5036]
### Expected behavior

When using `HashLinkedListMemTableConfig` and `useFixedLengthPrefixExtractor`, it should still be possible to iterate over all values in the db.

### Actual behavior

It does not appear to be possible. Creating an iterator and seeking to the first element leaves the iterator invalid.

### Steps to reproduce the behavior

Rocks version: 5.15.10

This junit test fails on the last line. If `.useFixedLengthPrefixExtractor(2)` or `.setMemTableConfig(new HashLinkedListMemTableConfig())` are removed, the test passes.

```java
  @Rule
  public TemporaryFolder mFolder = new TemporaryFolder();

  @Test
  public void iter() throws Exception {
    List<ColumnFamilyDescriptor> descriptors = Arrays.asList(
        new ColumnFamilyDescriptor(RocksDB.DEFAULT_COLUMN_FAMILY),
        new ColumnFamilyDescriptor("test".getBytes(), new ColumnFamilyOptions()
            .setMemTableConfig(new HashLinkedListMemTableConfig())
            .useFixedLengthPrefixExtractor(2)));
    List<ColumnFamilyHandle> handles = new ArrayList<>();
    RocksDB db = RocksDB.open(new DBOptions()
            .setAllowConcurrentMemtableWrite(false)
            .setCreateIfMissing(true)
            .setCreateMissingColumnFamilies(true),
        mFolder.newFolder().getAbsolutePath(), descriptors, handles);

    ColumnFamilyHandle column = handles.get(1);
    byte[] key = "hello".getBytes();
    byte[] value = "world".getBytes();
    db.put(column, key, value);
    assertArrayEquals(value, db.get(column, key));
    RocksIterator iter = db.newIterator(column);
    iter.seekToFirst();
    assertTrue(iter.isValid());
  }
```

Is there another way to iterate over all key/value pairs in the db?

**Comment by riversand963** [comment]
Hi @aaudiber , can you try the following:
```
ReadOptions readOptions;
readOptions.setTotalOrderSeek(true);
RocksIterator iter = db.newIterator(column, readOptions);
```

**Comment by aaudiber** [comment]
@riversand963 using `setTotalOrderSeek(true)` fixes the issue, thanks!

**Comment by riversand963** [comment]
SGTM. I'm closing this issue now, feel free to reopen should anything comes up.
