### ISSUE TITLE
SetDBOptions  can't detection the wrong value 

### ISSUE THREAD

**Issue by darionyaphet** [facebook/rocksdb#5056]
When I using `SetDBOptions` to set configuration and the value is not correct, it should return a status with a error message but it's ok() . 

### Expected behavior
`it should return a status with a error message. `

### Actual behavior
`but it's ok() . `

### Steps to reproduce the behavior

```
std::unordered_map<std::string, std::string> value_failed_db_options_ = {
        {"max_background_compactions", "2_"}
};

status = client->SetDBOptions(value_failed_db_options_);
if (!status.ok()) {
    std::cout << "value miss set db option failed : " << status.ToString() << std::endl;
}
```

**Comment by anand1976** [comment]
It does return error for some types of mis-configuration. For integer and double, the standard rules of strtol/strtoll/strtoull/strtod are applied, i.e ignore whitespace, discard invalid characters etc. For those, no error is reported.
