### ISSUE TITLE
RocksDB startup fails on dual socket NUMA host  

### ISSUE THREAD

**Issue by misnomer1** [facebook/rocksdb#5060]
RocksDB fails to startup on a dual socket NUMA host with error (I tested single socket NUMA host and rocksDB startsup and works well)

rocksdb::LRUCache::LRUCache(unsigned long, int, bool, double, std::shared_ptr<rocksdb::MemoryAllocator>)+0x93

I did not find any open issues reported. Can anyone let me know if this is a bug

**Comment by anand1976** [comment]
RocksDB is used pretty widely on dual-socket hosts without any problems. Can you give more details on what the error is?

**Comment by misnomer1** [comment]
I updated RocksDB to latest 5.18 and it is not starting up after that. All the logs I have is a problematic frame (I am using Java RocksDB wrapper) 

rocksdb::LRUCache::LRUCache(unsigned long, int, bool, double, std::shared_ptrrocksdb::MemoryAllocator)+0x93

Is this thread related by any chance?
https://github.com/facebook/rocksdb/pull/3750

**Comment by misnomer1** [comment]
This is probably related to AVX2 instructions set not available on the host. I am building the binary on AVX2 supported host.
