### ISSUE TITLE
wrong result when convert between Slice and std::stringstream 

### ISSUE THREAD

**Issue by maohaihua** [facebook/rocksdb#5065]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

when I convert between std::stringstream and rocksdb::Slice, if direct using stringstream.str() it will get the wrong result, but if using middle string it will get the right result.

       std::stringstream sskey,ssvalue;
        std::string strkey,strvalue;

        sskey<<1<<"-pointId-"<<"078191cb-2514-4f66-a334-ae1e0e2089ad";
        ssvalue<<1<<"-x0797-";

        strkey = sskey.str();
        strvalue = ssvalue.str();
        printf("write %s %s\n",sskey.str().data(),ssvalue.str().data());

#if 1
        rocksdb::Slice key_slice = sskey.str();
        rocksdb::Slice value_slice = ssvalue.str();
#else
        rocksdb::Slice key_slice = strkey;
        rocksdb::Slice value_slice = strvalue;
#endif

        printf("00write %s %s\n",key_slice.ToString().data(),value_slice.ToString().data());

### Expected behavior
write 1-pointId-078191cb-2514-4f66-a334-ae1e0e2089ad 1-x0797-
00write 1-pointId-078191cb-2514-4f66-a334-ae1e0e2089ad 1-x0797-

### Actual behavior
write 1-pointId-078191cb-2514-4f66-a334-ae1e0e2089ad 1-x0797-
00write  1-x0797-

### Steps to reproduce the behavior
#if 1
        rocksdb::Slice key_slice = sskey.str();
        rocksdb::Slice value_slice = ssvalue.str();
#else
        rocksdb::Slice key_slice = strkey;
        rocksdb::Slice value_slice = strvalue;
#endif

it will get the wrong result.
#if 0
        rocksdb::Slice key_slice = sskey.str();
        rocksdb::Slice value_slice = ssvalue.str();
#else
        rocksdb::Slice key_slice = strkey;
        rocksdb::Slice value_slice = strvalue;
#endif

it will get the correct result.

**Comment by anand1976** [comment]
I couldn't reproduce this. I don't see anything wrong in the code either.

**Comment by maohaihua** [comment]
I also think it should get the same result,but actually only value slice is correct. I use Rocksdb in ROS(Robot Operating System）(http://www.ros.org/) Kinetic, are there some relations? 

correct result:
[ INFO] [1552436857.881305122]: [1552436857.881287138]: write 1-pointId-078191cb-2514-4f66-a334-ae1e0e2089ad 1-x0797-


[ INFO] [1552436857.881378524]: [1552436857.881370160]: 00write 1-pointId-078191cb-2514-4f66-a334-ae1e0e2089ad 1-x0797-

wrong result :

[ INFO] [1552436145.594674644]: [1552436145.594655791]: write 1-pointId-078191cb-2514-4f66-a334-ae1e0e2089ad 1-x0797-


[ INFO] [1552436145.594787852]: [1552436145.594780309]: 00write  1-x0797-

**Comment by rockeet** [comment]
This is not a bug, the reason is: `std::stringstream::str()` returns a temporary rvalue, the rvalue object is valid **just in the containing expression**, and `Slice` just `ref` string data, not own string data! As explained:

```c++
#if 1
rocksdb::Slice key_slice = sskey.str(); // after this stmt, data ref'ed by key_slice is invalid
rocksdb::Slice value_slice = ssvalue.str();
#else
strkey = sskey.str(); // strkey deep copy(or take ownership) of sskey.str()
strvalue = ssvalue.str();
rocksdb::Slice key_slice = strkey; // key_slice ref to strkey's internal data, which is valid before strkey die
rocksdb::Slice value_slice = strvalue;
#endif```

**Comment by maohaihua** [comment]
May it is the reason,so close the issue.
