### ISSUE TITLE
seems a bug for snapshot in blobdb

### ISSUE THREAD

**Issue by yebangyu** [facebook/rocksdb#5069]
version：master，latest
how to reproduce：
auto* db = Open(...);
for (int i  = 0;  i < 10000000; ++i) {
 db->put(i, i);
}
// stop any read or writes and try to get a snapshot
std::vector<std::string> snapshot_files;
auto status = db->GetLiveFiles(snapshot_files, &manifest_file_size);
assert(status.ok());

ok，now ,  snapshot_files contains these files:

000025.sst
000019.sst
000012.sst
CURRENT
MANIFEST-000020
OPTIONS-000023
blob_dir/000001.blob
blob_dir/000002.blob
blob_dir/000003.blob
blob_dir/000004.blob

we copy these files into a new empty folder named xx_folder , and we try to open it:
auto * replication_db = Open(xx_folder);

it sometimes may fail, and the error log is : 

E0312 20:46:55.011610 34239 db.cc:182, Open] Open db failed. path == xx_folder. status == Corruption: Can't access /000011.sst: IO error: while stat a file for size: xx_folder/000011.sst: No such file or directory

**Comment by siying** [comment]
Any chance that you forgot the truncate `MANIFEST-000020` to `manifest_file_size` after you copy the files?

**Comment by yebangyu** [comment]
Thank you siying, I will have a try. thx
