### ISSUE TITLE
Unable to execute java program for rocksdb in windows platform

### ISSUE THREAD

**Issue by venkataramkumar** [facebook/rocksdb#5092]
> I am unable to open rocksdb and put the key,value pair in it using the java code in windows

**Comment by adamretter** [comment]
Which version of RocksDB? Which version of Windows?

**Comment by venkataramkumar** [comment]
i added rocksdbjni-5.0.1.jar and Windows 7 machine

**Comment by adamretter** [comment]
You should try the latest version. It includes some portability fixes for Windows.

**Comment by venkataramkumar** [comment]
Thanks its working
