### ISSUE TITLE
make problems

### ISSUE THREAD

**Issue by nielsl** [facebook/rocksdb#510]
Jim M, that was a really quick fix, thanks. I downloaded rocksdb-master.zip, but the making didn't go well for me, these two things need attention, i think:
1. Add to instructions how to specify an install path or prefix other than /usr/local. I first tried 'make PREFIX=/file/path' as many others have it. Then I looked at the install: tartget and saw an INSTALL_PATH variable needed to be set. I did 'export INSTALL_PATH=/file/path; make' and that worked, but instructions ought to mention. 
2. The install target directories were filled only with .h files, nothing in lib or other directories, only in include/rocksdb. I am installing as regular user. The make process runs unexpectedly fast and there seems to be no .o files made at all. The command 'find . -name *.o' comes up empty in the main source directory .. 

Niels L

**Comment by igorcanadi** [comment]
Did you `make all` before `make install`?

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by vjon** [comment]
@igorcanadi, I think it's safe to say Niels has moved on, and this question can be closed.

**Comment by igorcanadi** [comment]
Haha, true :)

**Comment by ael-code** [comment]
I agree with @nielsl  that the ´INSTALL_PATH´ variable should be mentioned in the installation guide
