### ISSUE TITLE
Prefix seek APIs fail with SliceTransform::InDomain(key) returning false

### ISSUE THREAD

**Issue by CaixinGong** [facebook/rocksdb#5109]
### The following sample code will assert fail in both Put() and SeekToFirst().

```
Options options;
options.prefix_extractor.reset(NewFixedPrefixTransform(3));
options.create_if_missing = true;
options.memtable_prefix_bloom_size_ratio = 0.1;
BlockBasedTableOptions table_options;
table_options.filter_policy.reset(NewBloomFilterPolicy(10, true));
options.table_factory.reset(NewBlockBasedTableFactory(table_options));

ReadOptions read_options;
read_options.total_order_seek = false;
read_options.prefix_same_as_start = true;

TransactionDB* txn_db;
TransactionDBOptions txn_db_options;
Status s = TransactionDB::Open(options, txn_db_options, kDBPath, &txn_db);
WriteOptions write_options;

s = txn_db->Put(write_options, "fo", "def"); assert(s.ok());

std::cout << "SeekToFirst" << std::endl;
auto iter = txn_db->NewIterator(read_options);
iter->SeekToFirst();
while (iter->Valid()) {
  std::cout << "\t" << iter->key().ToString() << "," << iter->value().ToString() << std::endl;
  iter->Next();
}

```
### Expected behavior

Though SliceTransform::InDomain(Slice("fo")) returns false,  both the Put() and SeekToFirst() should be success.

### Actual behavior
But, both Put and SeekToFirst fail.
The Put() will success if options.memtable_prefix_bloom_size_ratio is not set.
The SeekToFirst() will be called and fails if options.memtable_prefix_bloom_size_ratio is not set.

### Steps to reproduce the behavior
Run the above code

**Comment by miasantreble** [comment]
you used a slicetransform that requires keys of at least length 3 but you provided a key of length 2, it is expected that slicetransform will give up and assert. Why do you think it should succeed and what do you want it to do with the key that violates the contract? As for SeekToFirst, the db is empty so there is nothing to seek to

**Comment by CaixinGong** [comment]
No, I think this is a bug.
The slice_transform.h file tells the following information about InDomain():
(https://github.com/facebook/rocksdb/blob/master/include/rocksdb/slice_transform.h)

This method is invoked for every key that is inserted into the db. If this method returns true, then Transform is called to translate the key to its prefix and that returned prefix is inserted into the bloom filter. If this method returns false, **then the call to Transform is skipped** and no prefix is inserted into the bloom filters.

The transform should skip and not assert fail.

**Comment by miasantreble** [comment]
Why is it a bug? `FixedPrefixTransform` requires the prefix to be at least some length and you broke the contract. If you don't like its requirement maybe you should consider using your own SliceTransform 

`memtable_prefix_bloom_size_ratio` being zero means bloom filter is disabled, which explains the behavior.

**Comment by CaixinGong** [comment]
The slice_transform.h file tells the following information about  [InDomain()](https://github.com/facebook/rocksdb/blob/master/include/rocksdb/slice_transform.h) :  
`If this method returns false, then the call to Transform is skipped and no prefix is inserted into the bloom filters.`
Now, the phenomena does not conform to the description.
I think the transform should skip the key and not assert fail for the key.

**Comment by CaixinGong** [comment]
I hope that I can illustrate the bug clearly this time.

A part of functions of SliceTransform and FixedPrefixTransform is defined as following:
```
class SliceTransform {
  // Extract a prefix from a specified key. This method is called when
  // a key is inserted into the db, and the returned slice is used to
  // create a bloom filter.
  virtual Slice Transform(const Slice& key) const = 0;

  // Determine whether the specified key is compatible with the logic
  // specified in the Transform method. This method is invoked for every
  // key that is inserted into the db. If this method returns true,
  // then Transform is called to translate the key to its prefix and
  // that returned prefix is inserted into the bloom filter. If this
  // method returns false, then the call to Transform is skipped and
  // no prefix is inserted into the bloom filters.
  //
  // For example, if the Transform method operates on a fixed length
  // prefix of size 4, then an invocation to InDomain("abc") returns
  // false because the specified key length(3) is shorter than the
  // prefix size of 4.
  //
  // Wiki documentation here:
  // https://github.com/facebook/rocksdb/wiki/Prefix-Seek-API-Changes
  //
  virtual bool InDomain(const Slice& key) const = 0;
}
```

```
class FixedPrefixTransform : public SliceTransform {
 Slice Transform(const Slice& src) const override {
    assert(InDomain(src));
    return Slice(src.data(), prefix_len_);
  }

  bool InDomain(const Slice& src) const override {
    return (src.size() >= prefix_len_);
  }
}
```
When I insert the key "fo",  the key "fo" will be inserted into memtable, with  _MemTable::Add_ function called. Then, the following code will be ran to add the prefix to the bloom filter.

```
    if (bloom_filter_ && prefix_extractor_) {
      bloom_filter_->Add(prefix_extractor_->Transform(key));
    }
```
Thus prefix_extractor_->Transform("fo") assert fails.
The code should be changed as following according to the description of  InDomain(),

```
    if (bloom_filter_ && prefix_extractor_ && (prefix_extractor_->InDomain(key)) ) {
      bloom_filter_->Add(prefix_extractor_->Transform(key));
    }
```
As the  BlockBasedFilterBlockBuilder::Add(const Slice& key)  function: 

```
void BlockBasedFilterBlockBuilder::Add(const Slice& key) {
  if (prefix_extractor_ && prefix_extractor_->InDomain(key)) {
    AddPrefix(key);
  }

  if (whole_key_filtering_) {
    AddKey(key);
  }
}
```

**Comment by wangxiyu191** [comment]
@CaixinGong  https://github.com/facebook/rocksdb/commit/cca141ecf8634a42b5eb548cb0ac3a6b77d783c1 This commit fix this bug. Refer to #5190.
