### ISSUE TITLE
what is the maximum size of a value in rocksdb?

### ISSUE THREAD

**Issue by ekg** [facebook/rocksdb#513]
As per the title, how big of an object can be stored in rocksdb? Is there any limit?

**Comment by igorcanadi** [comment]
I don't think there's a limit, but RocksDB is better optimized for values on the smaller side. Inserting megabyte values should work, but it will not be optimal use of RocksDB.

**Comment by siying** [comment]
We never tested it. We know for sure it works for values of megabytes and it won't work if length is close to limit of int32. I can't think of anything would fail a value in the middle but I might miss some factors.

**Comment by ekg** [comment]
Have you considered a variable-width format for storing the value length?

The int32 limit the reason that you have to use level-style compaction on
large datasets. (I haven't read the related source, but the wiki notes this
limitation.) If so, this would allow a workaround for that.

**Comment by igorcanadi** [comment]
Are you trying to store values bigger than 4GB in RocksDB?

**Comment by ekg** [comment]
No, although it would be nice to be able to not have to worry about size limits.

I was referring to the 100-200G limit to the size of a single SST. Is this not caused by the 32-bit size limit of the data index block?

**Comment by igorcanadi** [comment]
I think the issue there is that we try to compress index block as a whole, but compression library uses `int` somewhere. You should be able to create sst files bigger than 100GB, but index block will probably not be compressed in that case. Or you could increase your block_size (4KB is quite small), which should decrease size of the index.

We didn't focus on this problem much because most of our services run level compaction. It creates bigger number of files, but each file is smaller. Also, it benefits because some files can be moved through levels without extra write amp.

**Comment by ekg** [comment]
@igorcanadi What kind of *read* performance tradeoff is there between many or few files in the db? Am I misguided in aiming for a small number of files in an application that is effectively build-once read-often?

**Comment by igorcanadi** [comment]
If it's build-once read-often, you should probably use level style compaction and then Compact() after writing. That will put all the files into the same level, which means when you want to read a key, only a single file will be consulted (we prune based on key-range -- each file has non-overlapping key range)

**Comment by ekg** [comment]
@igorcanadi but the number of files in that level. Is it better to have more or less?

**Comment by igorcanadi** [comment]
Try benchmarking :) Shouldn't be a big difference though.

**Comment by zhangjinpeng1987** [comment]
@siying There are some questions I can't find the answer: If a key value is 1GB, is it will split and persistent in multiple sst files? If I read this key value with `read_options.fill_cache=true`, will the blocks can fill block cache?

**Comment by siying** [comment]
@zhangjinpeng1987 no. A key-value will never expand to even two data blocks.

**Comment by anhldbk** [comment]
@siying In case of many keys with large-sized values (and they are frequently accessed), how will Block Cache behave?

**Comment by yiwu-arbug** [comment]
@anhldbk Our block size is variable, and will fit to boundary of keys. Say if there is a gigantic key-value, we may end up with a gigantic block containing only this key-value.

**Comment by anhldbk** [comment]
@yiwu-arbug So if I have a large key, I'd be better off splitting it into multiple smaller keys, right?

**Comment by aseidlitz** [comment]
as per https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ: 
The maximum recommended sizes for key and value are 8MB and 3GB respectively.

**Comment by siying** [comment]
@ekg actually, the int32 limit is not related to compaction style. The main reasons are (1) in all current implementation of memtable, we encode key and value size as varint32; (2) in all current implementation of SST tables, we encode key and value size as varint32. No fundamental reason that they cannot be extended to varint64, but it's a pain to make a change and so far there isn't a strong reason to do it.

**Comment by ekg** [comment]
It does seem arbitrary to me to use 32 bits. You never know when you might
need a really big key and value. 32 bits is pretty small.

Are you concerned about performance costs of 64 bit values? It would seem
to matter only for small keys, and maybe not very much because you're using
a varint encoding.

To be clear, I'm not stuck because of this. It's just a curiosity to me.
I've moved a number of my applications to disk-backed sorted arrays of
fixed-size records.

**Comment by siying** [comment]
@ekg it has been the case since LevelDB and we never revisited it.
