### ISSUE TITLE
compile err when output port dir as header dir included

### ISSUE THREAD

**Issue by datonli** [facebook/rocksdb#5145]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Output port dir as include dir 
It should work.

### Actual behavior
rocksdb/tools/ldb_cmd.cc:1003:24: error: 'DIR' has not been declared

### Steps to reproduce the behavior
This caused by barking up  #include <dirent.h> while found port/dirent.h
It could simply change port/dirent.h as port/port_dirent.h to avoid this problem.

**Comment by sagar0** [comment]
@datonli Which version of RocksDB were you trying to use? And on what OS/version?

**Comment by datonli** [comment]
I've committed a pull request to fix this problem. Please review it @sagar0 
 [https://github.com/facebook/rocksdb/pull/5152](url)

**Comment by sagar0** [comment]
Fixed in #5152 . Thanks for the issue and the pull request.
