### ISSUE TITLE
Installation instruction for MacOS is not working

### ISSUE THREAD

**Issue by steven05jiang** [facebook/rocksdb#5151]
In the installation [instruction](https://github.com/facebook/rocksdb/blob/master/INSTALL.md) for OS X, the step failed at:
> brew tap homebrew/versions; brew install gcc48 --use-llvm

Error message is 
> homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.
> No available formula with the name "homebrew/core/gcc@4.8"

Do you have the latest instruction for MacOS? Thanks.

**Comment by adamretter** [comment]
Does it work if you skip the step:

```
brew tap homebrew/versions; brew install gcc48 --use-llvm
```

**Comment by steven05jiang** [comment]
@adamretter the "brew install rocksdb" works fine and rocksdb_stress passes. The concern is more on my local build env because I'm trying to compile on my laptop. Can you please provide some steps to setup/verify the env?

**Comment by adamretter** [comment]
@steven05jiang I am not sure I follow you? For compiling from source, I simply do:

```
git clone https://github.com/facebook/rocksdb.git
cd rocksdb
make clean && make static_lib
```

**Comment by steven05jiang** [comment]
@adamretter I just did as you suggested and compiling was working fine. One issue is the test is stuck at DBTest.MergeTestTime never completed. The rocksdb version 5.18.3. Do you think if it's related to the setting of MacOS?

**Comment by steven05jiang** [comment]
Digging a little bit on the test, it starts to fail at line 5071 in TEST_F(DBTest, MergeTestTime) in db_test:
this->env_->time_elapse_only_sleep_ = true;

Can anyone help on this problem?

**Comment by adamretter** [comment]
@steven05jiang Could it be related to this - https://github.com/facebook/rocksdb/issues/5276

**Comment by steven05jiang** [comment]
Thanks @adamretter. I looks like the similar issue.

**Comment by thatnerdjosh** [comment]
@adamretter is GCC 4.8 really needed to build this? Seems to work for me using macOS Catalina default and doing `brew install rocksdb`:

```
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by adamretter** [comment]
@thatnerdjosh No. If using GCC, the minimum supported version is 4.8. Otherwise, clang is fine too.
