### ISSUE TITLE
make rocksdbjava failed on mac

### ISSUE THREAD

**Issue by brary** [facebook/rocksdb#5153]
make rocksdbjava

### Expected behavior
 builds rocksdb

### Actual behavior
 fails and throws error

### Steps to reproduce the behavior
 export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/
 make rocksdbjava

Tried with 4 different branches: master, 5.17.fb, 6.0.fb, 6.1.fb and all 4 failed.

Logs:
25 warnings
javah -cp target/classes -d ./include -jni org.rocksdb.AbstractCompactionFilter org.rocksdb.AbstractCompactionFilterFactory org.rocksdb.AbstractSlice org.rocksdb.AbstractTransactionNotifier org.rocksdb.BackupEngine org.rocksdb.BackupableDBOptions org.rocksdb.BlockBasedTableConfig org.rocksdb.BloomFilter org.rocksdb.Checkpoint org.rocksdb.ClockCache org.rocksdb.CassandraCompactionFilter org.rocksdb.CassandraValueMergeOperator org.rocksdb.ColumnFamilyHandle org.rocksdb.ColumnFamilyOptions org.rocksdb.CompactionOptionsFIFO org.rocksdb.CompactionOptionsUniversal org.rocksdb.CompactRangeOptions org.rocksdb.Comparator org.rocksdb.ComparatorOptions org.rocksdb.CompressionOptions org.rocksdb.DBOptions org.rocksdb.DirectComparator org.rocksdb.DirectSlice org.rocksdb.Env org.rocksdb.EnvOptions org.rocksdb.FlushOptions org.rocksdb.Filter org.rocksdb.IngestExternalFileOptions org.rocksdb.HashLinkedListMemTableConfig org.rocksdb.HashSkipListMemTableConfig org.rocksdb.Logger org.rocksdb.LRUCache org.rocksdb.MergeOperator org.rocksdb.NativeComparatorWrapper org.rocksdb.OptimisticTransactionDB org.rocksdb.OptimisticTransactionOptions org.rocksdb.Options org.rocksdb.OptionsUtil org.rocksdb.PlainTableConfig org.rocksdb.RateLimiter org.rocksdb.ReadOptions org.rocksdb.RemoveEmptyValueCompactionFilter org.rocksdb.RestoreOptions org.rocksdb.RocksCallbackObject org.rocksdb.RocksDB org.rocksdb.RocksEnv org.rocksdb.RocksIterator org.rocksdb.RocksMemEnv org.rocksdb.SkipListMemTableConfig org.rocksdb.Slice org.rocksdb.SstFileManager org.rocksdb.SstFileWriter org.rocksdb.Statistics org.rocksdb.Transaction org.rocksdb.TransactionDB org.rocksdb.TransactionDBOptions org.rocksdb.TransactionOptions org.rocksdb.TransactionLogIterator org.rocksdb.TtlDB org.rocksdb.VectorMemTableConfig org.rocksdb.Snapshot org.rocksdb.StringAppendOperator org.rocksdb.WriteBatch org.rocksdb.WriteBatch.Handler org.rocksdb.WriteOptions org.rocksdb.WriteBatchWithIndex org.rocksdb.WBWIRocksIterator
test -d "test-libs" || mkdir -p "test-libs"
test -s "test-libs/junit-4.12.jar" || cp ~/.m2/repository/junit/junit/4.12/junit-4.12.jar test-libs || curl -k -L -o test-libs/junit-4.12.jar http://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar
test -s "test-libs/hamcrest-core-1.3.jar" || cp ~/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar test-libs || curl -k -L -o test-libs/hamcrest-core-1.3.jar http://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
test -s "test-libs/mockito-all-1.10.19.jar" || cp ~/.m2/repository/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar test-libs || curl -k -L -o "test-libs/mockito-all-1.10.19.jar" http://search.maven.org/remotecontent?filepath=org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar
test -s "test-libs/cglib-2.2.2.jar" || cp ~/.m2/repository/cglib/cglib/2.2.2/cglib-2.2.2.jar test-libs || curl -k -L -o "test-libs/cglib-2.2.2.jar" http://search.maven.org/remotecontent?filepath=cglib/cglib/2.2.2/cglib-2.2.2.jar
cp: /Users/nsb000c/.m2/repository/cglib/cglib/2.2.2/cglib-2.2.2.jar: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3389  100  3389    0     0   3389      0  0:00:01  0:00:01 --:--:--  2019
test -s "test-libs/assertj-core-1.7.1.jar" || cp ~/.m2/repository/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.jar test-libs || curl -k -L -o "test-libs/assertj-core-1.7.1.jar" http://central.maven.org/maven2/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.jar
cp: /Users/nsb000c/.m2/repository/org/assertj/assertj-core/1.7.1/assertj-core-1.7.1.jar: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3402  100  3402    0     0   3402      0  0:00:01  0:00:01 --:--:--  2164
mkdir -p target/test-classes
javac -Xlint:deprecation -Xlint:unchecked -cp target/classes:test-libs/junit-4.12.jar:test-libs/hamcrest-core-1.3.jar:test-libs/mockito-all-1.10.19.jar:test-libs/cglib-2.2.2.jar:test-libs/assertj-core-1.7.1.jar -d target/test-classes\
		src/test/java/org/rocksdb/test/*.java\
		src/test/java/org/rocksdb/util/*.java\
		src/test/java/org/rocksdb/*.java
error: error reading test-libs/mockito-all-1.10.19.jar; error in opening zip file
error: error reading test-libs/cglib-2.2.2.jar; error in opening zip file
error: error reading test-libs/assertj-core-1.7.1.jar; error in opening zip file
3 errors
make[1]: *** [java_test] Error 1
make: *** [rocksdbjava] Error 2

**Comment by adamretter** [comment]
The jar files that it is failing with errors on, are downloaded from the web! Are you perhaps behind some sort of proxy? The issue is specific to you not being able to download the necessary jar dependencies.
