### ISSUE TITLE
Wrongly documented write POSIX call on BSD causing IOErrors during compaction

### ISSUE THREAD

**Issue by rbost** [facebook/rocksdb#5169]
### Expected behavior
On Mac OS, compaction always succeeds even when having to write very large buffers when flushing.

### Actual behavior

When flushing a buffer larger to 2^31 bytes, the `write` call in `PosixWritableFile::Append` (io_posix.cc, line 757) returns `-1` and sets `errno` to `EINVAL`.
This makes the compaction fail (and subsequent call to `Merge` return an error). The error cannot be recovered after a cool down in my case, as the size of a single value is larger than the mentioned threshold.

### Steps to reproduce the behavior

I encountered this issue when writing a variant of the `string_append` test program. I used a Zipf distribution for the length of the strings, which means that a few of the strings are very long after doing a large number of insertions.

I will not provide a complete description of the code as the execution takes a few hours before encountering the issue. Instead, I created a repo to provide a very small example of where the issue comes from: [posix_write](https://github.com/rbost/posix_write). 
You can see from the [Travis execution](https://travis-ci.org/rbost/posix_write) of the program that, on Mac OS, when trying to write a buffer of 2^31 bytes or more (i.e. when a signed `int32_t` overflows), the `write` call returns `-1` and sets `errno` to `EINVAL` (invalid argument). You can also see that this behavior is not reproduced on Linux.

### Explanations

I suspect that the BSD/Mac OS implementation of `write` does not make any difference between 32-bits and 64-bits CPUs: it always supposes the worst, that we are on a 32-bits computer. As a consequence, as the return value of `write` is of `ssize_t` (signed) type, it should not return a number larger than 2^31-1.
As the return value of `write` is the number of written bytes, the call cannot accept buffers larger than 2^31-1 bytes (note that this is pure speculation, I have not had the time to dig into the BSD source).

Although I believe this is particular point is an issue with BSD, it also means that RocksDB will not support 32-bits systems with large values (larger than 2GB) in the database.
This is not a surprise, but it could be worth mentioning.

### Possible Workaround

Again, although this is definitely an issue with BSD (at least the documentation), I think it is worth developing a workaround, especially because it would be very simple.
The idea would be to write a wrapper around the `write` syscall which cuts the buffer into chunks smaller than 2^31-1, and call `write` on each of these chunks sequentially.
This would not change the complexity of the code.
Even though the change is simple, it might require some thoughts, as direct IOs need correctly-aligned inputs to be used.

**Comment by riversand963** [comment]
Make sense. Thanks @rbost for reporting and writing the test program. Would you like to contribute a PR to fix this? We probably need to fix `io_posix.cc`.

**Comment by rbost** [comment]
Sure, I will be happy to propose a PR. I already have wrappers on top of the `write` and `pwrite` calls, but I still have to integrate them to `io_posix.cc` (and do some tests). Just give me a few days :)

**Comment by rbost** [comment]
Fixed in 468ca61
