### ISSUE TITLE
How to insert int value to rocksdb using c  

### ISSUE THREAD

**Issue by kaviranga** [facebook/rocksdb#5205]
I've used following example to insert int value to rocksdb using "c"  language

       #include<stdio.h>
       #include<string.h>
       #include<stdlib.h>
       #include<assert.h>

       #include<unistd.h>

       const char DBPath[] = "/tmp/test_sample";

      #include "rocksdb/c.h"

      int main(int argc, char **argv){

	  // Intialize basic parameters
	  rocksdb_t *db;
	  rocksdb_options_t *options = rocksdb_options_create();

	 //  Create the database if it's not already present
	 rocksdb_options_set_create_if_missing(options,1);

	// Open database
	char *err = NULL;
	db = rocksdb_open(options,DBPath,&err);
	assert(!err);

	//Put key value
	//Insert value to the database
	rocksdb_writeoptions_t *writeoptions = rocksdb_writeoptions_create();
	const char key[] = "key";
	const char *value = "value";
	rocksdb_put(db,writeoptions,key,strlen(key),value,strlen(value) + 1,&err);
	assert(!err);
	
	//Cleanup 
	rocksdb_writeoptions_destroy(writeoptions);
	rocksdb_options_destroy(options);
	rocksdb_close(db);
	
	return 0;
     }

Is this correct ? 

Is there any data losses while converting int values to char values ? . I've used as this because there is no other method to direct insert int value to rocksdb.

**Comment by ananclub** [comment]
maybe strlen end of '\0'

**Comment by riversand963** [comment]
RocksDB stores key/values as bytes and there is no type. Convert the integer to byte array using encoding of your choice, and deserialize the key/values when reading them out.
