### ISSUE TITLE
Missing rocksdb_property_int_cf in C API

### ISSUE THREAD

**Issue by dvdplm** [facebook/rocksdb#5249]
Currently the C API exposes `rocksdb_property_value`, `rocksdb_property_int` and `rocksdb_property_value_cf`, however there is no `rocksdb_property_int_cf`. This seems like an oversight and an easy fix? [Code ref](https://github.com/facebook/rocksdb/blob/master/db/c.cc#L1062)

**Comment by maysamyabandeh** [comment]
Yeah it seems that `rocksdb_property_int_cf` is missing. Would you be interested in contributing a patch?

**Comment by dvdplm** [comment]
> Would you be interested in contributing a patch?

Definitely. My C is weak so will need some review, but I'll have a stab at it. :)
