### ISSUE TITLE
Block Checksum Mismatch

### ISSUE THREAD

**Issue by siuying** [facebook/rocksdb#5251]
We are running RocksDB Lite 5.13.1 on iOS. We encountered a few cases related to rocksdb throw "block checksum mismatch" when we write something to database.

This is the LOG file when this issue is first seen https://gist.github.com/siuying/6fd70cf8c83abdee79b7652028064d95

### Expected behavior

Don't cause data corruption. Or a way to recover from it automatically.

### Actual behavior

Block checksum mismatch error:
``
Corruption: block checksum mismatch: expected 3743273618, got 1401052269 in  /events_main.db/001303.sst offset 5057880 size 2023
``

### Steps to reproduce the behavior

I cannot reproduced the error, but we seen this problem happened multiple times.

---

From previous tickets, this could be ram or disk problem. We had a device in our hand having exactly this problem. We have no way to sure if it is hardware problem, or our application problem. The device otherwise seems working perfectly normal.

Due to the nature of an app, the process can be suspended or killed by OS. Is it possible the app being terminated by OS cause compaction error? Any input on how we can prevent this problem is greatly appreciated.

**Comment by maysamyabandeh** [comment]
Corruption in SST files are either caused by faulty hardware or buggy software. If it occurs too many times on different hardware, the it is more likely to be caused by software bugs. Unfortunately without a test code to reproduce the issue, there is not much followup one can do. As for the files, you can check if they are corrupted using sst_dump and ldb tools.

**Comment by siuying** [comment]
@maysamyabandeh I understand. We can only confirm one instance where user having this issue, and that happened repeated on same device. However can you elaborate on how one may introduce bug that can corrupt SST files?
