### ISSUE TITLE
use after close can SEGV

### ISSUE THREAD

**Issue by toolslive** [facebook/rocksdb#526]
using the database API after the database has been closed can result in a segmentation violation.
Below, you find an example bt end point from a corresponding core dump
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  rocksdb_get (db=<optimized out>, options=0x2480780, key=0x7f4f20d0f4fb "", keylen=6, vallen=0x3e577a0, errptr=0x246dc30) at db/c.cc:727
727	  Status s = db->rep->Get(options->rep, Slice(key, keylen), &tmp);

```
It's not a big issue, but an exception would be nicer. 
The problem occurs in a context where there are many reader threads and 1 thread closes the database, while the others only realise this has happened a bit later.

**Comment by igorcanadi** [comment]
Thanks for your report. This is by design. After close we delete all our data in memory, so as soon as you access functions that refer to deleted piece of memory, SIGSEGV happens.

**Comment by meyering** [comment]
On Fri, Mar 6, 2015 at 1:34 AM, Romain Slootmaekers <
notifications@github.com> wrote:

> using the database API after the database has been closed can result in a
> segmentation violation.
> Below, you find an example bt end point from a corresponding core dump
>
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  rocksdb_get (db=<optimized out>, options=0x2480780, key=0x7f4f20d0f4fb "", keylen=6, vallen=0x3e577a0, errptr=0x246dc30) at db/c.cc:727
> 727   Status s = db->rep->Get(options->rep, Slice(key, keylen), &tmp);
>
>
> It's not a big issue, but an exception would be nicer.
> The problem occurs in a context where there are many reader threads and 1
> thread closes the database, while the others only realise this has happened
> a bit later.
>

Thanks for the report.
To avoid that, ensure that all reader threads have been joined before you
close the DB.
