### ISSUE TITLE
compression_dict_handle is not initialized when reading RangeDelete Block

### ISSUE THREAD

**Issue by maysamyabandeh** [facebook/rocksdb#5263]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

compression_dict_handle is initialized here https://github.com/facebook/rocksdb/blob/35e6ba734e6d6443e13e24d3e7497b1ce05664e6/table/block_based_table_reader.cc#L1165 which is called at Line 859 when opening a table: https://github.com/facebook/rocksdb/blob/35e6ba734e6d6443e13e24d3e7497b1ce05664e6/table/block_based_table_reader.cc#L859

However ReadRangeDelBlock which is called at line 854 already attempts to read the handle: https://github.com/facebook/rocksdb/blob/35e6ba734e6d6443e13e24d3e7497b1ce05664e6/table/block_based_table_reader.cc#L854

### Actual behavior

```
[WARN] [table/block_based_table_reader.cc:1104] Encountered error while reading data from compression dictionary block IO error: While pread offset 18446744073709551615 len 4: /tmp/db/000309.sst: Invalid argument
```
### Steps to reproduce the behavior

Build a table with range delete block and then try to open it.

**Comment by maysamyabandeh** [comment]
CC @ajkr

**Comment by ajkr** [comment]
Sorry I didn't quite understand the third part of the expected behavior. That function is reading the range delete meta-block, not the compression dictionary meta-block. But let me try the repro steps.

**Comment by ajkr** [comment]
I did try it and it worked. Does this happen every time with your options file? This looks suspicious: "pread offset 18446744073709551615 len 4" -- that offset is 2^64-1 which looks like an error code.

My sanity check experiment:
```
// build DB with dictionary compression enabled
$ ./db_bench -benchmarks=fillrandom -target_file_size_base=1048576 -max_bytes_for_level_base=4194304 -write_buffer_size=1048576  -compression_type=zlib -compression_max_dict_bytes=4096
// verify some files have dictionary
$ ./sst_dump --command=raw --file=/tmp/rocksdbtest-1000/dbbench/000442.sst
// verify DB is readable
$ ./db_bench -benchmarks=readrandom -use_existing_db=true -target_file_size_base=1048576 -max_bytes_for_level_base=4194304 -write_buffer_size=1048576  -compression_type=zlib -compression_max_dict_bytes=4096
```

**Comment by maysamyabandeh** [comment]
Thanks @ajkr for looking into this. Does the initialization reordering in the issue description make sense to you?

**Comment by maysamyabandeh** [comment]
To clarify, the error is that the user has never used dictionary compression. But when reading the deleterange block, it tries to open the dictionary compression metablock, whose handle is not initialized null yet, ergo the weird offset size.

**Comment by ajkr** [comment]
Understood now, thanks. Doing a bisect.

**Comment by ajkr** [comment]
OK, forget the bisect, it looks like it hasn't worked for a long time with `cache_index_and_filter_blocks=true`. That's too bad, but also not surprising considering `db_stress` doesn't cover that option.
