### ISSUE TITLE
Database tests using mocked timed environments hang on MacOS

### ISSUE THREAD

**Issue by mrambacher** [facebook/rocksdb#5276]
Several tests (DBOptionsTest.DeleteObsoleteFilesPeriodChange,   DBPropertiesTest.EstimatedOldestKeyTime, DBSSTTest/RatedLimitedWALDelete, DBSSTTest.GetTotalSstFileSize) fail on MacOS in debug builds.  This is related to having a mock timed environment and using a RepeatedThread (for dump/persist stats). 

There is a comment in RepeatedThreadTest that outlines the problem on MacOS.  

One solution is to generalize the code in the RepeatedThreadTest to use for the various moc environments.  

Another solution might to have the mock time functions advance the time when they are called.  

Another solution might be to have CurrentOptions turn off the problematic threads.  I temporarily have worked around this problem by turning off the stats threads (setting the frequency to 0).

### Steps to reproduce the behavior

Run any of the aforementioned tests on MacOS in a debug build.

**Comment by riversand963** [comment]
Thanks @mrambacher for reporting. I have similar observations in #5107.

**Comment by mrambacher** [comment]
The issue is the very similar but I do not think that suggested fix solves these problems, as it looks like it is the wrong spot.  I wonder if the fix for my issue is not putting the SyncPoint code into the DBTestBase constructor.

**Comment by pdillinger** [comment]
Fixed in #7101, though further cleanup as described there would be nice
