### ISSUE TITLE
fsync directory after file ingestion

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#5287]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

@petermattis pointed me to this. We should sync the DB directory after ingesting an SST file to ensure that SST file can survive a system crash.

### Actual behavior

The directory sync is not happening (see repro below).

### Steps to reproduce the behavior

I verified with `strace` that there is indeed no sync on the directory after creating a file during ingestion: https://gist.github.com/ajkr/053b51bb97d5a8957136b2a8cf885c71

**Comment by siddontang** [comment]
> We should sync the DB directory after ingesting an SST file to ensure that SST file can survive a system crash

@ajkr 

have you met this problem already? how about the phenomenon?

**Comment by ajkr** [comment]
Hi @siddontang, we didn't meet this problem in production. Rather it was found via code inspection. I'd guess the symptom would be the DB is unable to open after machine crash/restart since a file mentioned in the manifest cannot be found on the disk (or with limited `max_open_files`, maybe it'll fail later when a read/compaction attempts to access such a file).
