### ISSUE TITLE
xxhash.h and xxhash.cpp polluting global namespace

### ISSUE THREAD

**Issue by asameet** [facebook/rocksdb#531]
The functions in xxhash.h and xxhash.cpp do not allow the rocksdb library to be used when there is already another library using the same names. We need to use a namespace for these names

**Comment by dhruba** [comment]
Your proposal makes sense. If you can contribute a patch, that would be fantastic.

**Comment by asameet** [comment]
Will do

**Comment by siying** [comment]
3ebebfccd8f33e55899905f462682a0d9d4736be
