### ISSUE TITLE
RocksDBException: While open a file for appending xxx.sst No such file or directory

### ISSUE THREAD

**Issue by klion26** [facebook/rocksdb#5318]
Run a program in Flink using RocksDB, and encountered this Exception(have set max_open_files to -1), Googled and find the issues, but didn't figure it out.

What could be the reason? any feedback is welcome.

### Expected behavior
No Exception

### Actual behavior
RocksDBException: While open a file for appending xxx.sst No such file or directory

**Comment by sagar0** [comment]
RocksDB could throw this error if it can't find the file/directory that it is trying to open for writing, from here: https://github.com/facebook/rocksdb/blob/6.1.fb/env/env_posix.cc#L291

RocksDB logs could provide more information about the life of "xxx" file. Do you see anything in there? Or did some external process affect xxx.sst?

Could you also provide more information about your setup?
- Did you encounter this issue on a newly created DB, or have you been using the DB for some time before you saw this error?
- Any changes (like upgrades, etc) that triggered this?
- Does any other process having write access to the DB directory modify it in any way?

**Comment by klion26** [comment]
Sadly, the log was deleted when the job failed.

- We use local filesystem
- Not a newly created DB, there has been some data already in it.
- No changes (but after restarting the job, the error is gone)
- There is no other process having write access to the DB directory
- I've searched the issue in flink jira, but didn't find it.

**Comment by Edward-xk** [comment]
@klion26 excuse me, how do you solve this problem finally?

**Comment by vmtuan12** [comment]
Is there solution for this?
