### ISSUE TITLE
Wnew(GB) of last level is reported in bytes rather than GB.

### ISSUE THREAD

**Issue by pshareghi** [facebook/rocksdb#535]
When running C++ benchmarks, the Wnew(GB) of last level is reported in bytes rather than GB.

```
** Compaction Stats [default] **
Level   Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) Stall(sec) Stall(cnt) Avg(ms)     RecordIn   RecordDrop
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0     2/0          4   0.5      0.0     0.0      0.0       2.0      2.0       0.0   0.0      0.0    250.3         8      1034    0.008       0.00          0    0.00            0            0
  L1     2/0          8   0.9      3.3     1.9      1.3       2.9      1.6       0.0   1.5    218.8    193.5        15       258    0.060       0.29        331    0.89      1995690            0
  L2     5/0         16   1.0      3.4     1.4      2.0       3.0      1.0       0.1   2.2    180.0    159.2        20       326    0.060       0.22        247    0.89      1629262            0
  L3     8/0         30   0.9      2.8     1.1      1.8       2.2      0.4       0.1   2.1    113.8     88.6        25       249    0.102       0.02         54    0.35      1331569            0
  L4    19/0         37   0.6      1.1     0.5      0.7       0.7 17179869184.0       0.0   1.5     84.4     50.0        14       112    0.122       0.00          0    0.00       754586            0
 Sum    36/0         94   0.0     10.7     4.9      5.8      10.8      5.0       0.3   5.5    133.4    134.5        82      1979    0.041       0.53        632    0.84      5711107            0
 Int     0/0          0   0.0      7.3     3.2      4.1       7.3      3.2       0.2   7.5    150.8    151.8        49      1165    0.042       0.40        465    0.87      3547306            0
```

**Comment by mdcallag** [comment]
It isn't reported in bytes. This is a bug in the way Wnew is computed.

On Thu, Mar 12, 2015 at 1:53 PM, Pooya Shareghi <notifications@github.com>
wrote:

> When running C++ benchmarks, the Wnew(GB) of last level is reported in
> bytes rather than GB.
>
> ** Compaction Stats [default] **
> Level   Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) Stall(sec) Stall(cnt) Avg(ms)     RecordIn   RecordDrop
> --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
>   L0     2/0          4   0.5      0.0     0.0      0.0       2.0      2.0       0.0   0.0      0.0    250.3         8      1034    0.008       0.00          0    0.00            0            0
>   L1     2/0          8   0.9      3.3     1.9      1.3       2.9      1.6       0.0   1.5    218.8    193.5        15       258    0.060       0.29        331    0.89      1995690            0
>   L2     5/0         16   1.0      3.4     1.4      2.0       3.0      1.0       0.1   2.2    180.0    159.2        20       326    0.060       0.22        247    0.89      1629262            0
>   L3     8/0         30   0.9      2.8     1.1      1.8       2.2      0.4       0.1   2.1    113.8     88.6        25       249    0.102       0.02         54    0.35      1331569            0
>   L4    19/0         37   0.6      1.1     0.5      0.7       0.7 17179869184.0       0.0   1.5     84.4     50.0        14       112    0.122       0.00          0    0.00       754586            0
>  Sum    36/0         94   0.0     10.7     4.9      5.8      10.8      5.0       0.3   5.5    133.4    134.5        82      1979    0.041       0.53        632    0.84      5711107            0
>  Int     0/0          0   0.0      7.3     3.2      4.1       7.3      3.2       0.2   7.5    150.8    151.8        49      1165    0.042       0.40        465    0.87      3547306            0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/rocksdb/issues/535>.
>



-- 
Mark Callaghan
mdcallag@gmail.com

**Comment by IslamAbdelRahman** [comment]
Thanks for reporting, this should be fixed now
