### ISSUE TITLE
[RocksJava]  Set compression per level

### ISSUE THREAD

**Issue by pshareghi** [facebook/rocksdb#542]
Is there a way to set compression algorithm per level? If not, can this feature be added please?
Thanks

**Comment by alugowski** [comment]
I'm also interested in this.

**Comment by siying** [comment]
Yes options.compression_per_level.

**Comment by fyrz** [comment]
This feature is not available at the moment. I`ll port it this week.

**Comment by pshareghi** [comment]
Thanks, @fyrz!

**Comment by fyrz** [comment]
@pshareghi @alugowski 
https://github.com/facebook/rocksdb/pull/545
