### ISSUE TITLE
Corruption error when calling GetUpdatesSince()

### ISSUE THREAD

**Issue by graetzer** [facebook/rocksdb#5455]
When using the `GetUpdatesSince(..)` method we regulary see a corruption error with the message "NO MORE DATA LEFT".

It seems to me like there is a condition in the `TransactionLogIteratorImpl::NextImpl()` method, that would always lead to this error when a new WAL file is openened (while concurrently scanning the WAL). The code in question is this piece:

```c++
is_valid_ = false;
if (current_last_seq_ == versions_->LastSequence()) {
  current_status_ = Status::OK();
} else {
  current_status_ = Status::Corruption("NO MORE DATA LEFT");
}
```
Seems like the sequence number returned by `versions_->LastSequence()` would be higher in that case ? Would it be more correct to return a "try again" type error ?

### Expected behavior

No corruption error on scanning the WAL when executing basically this code:
```c++
std::unique_ptr<rocksdb::TransactionLogIterator> it; 
rocksdb::TransactionLogIterator::ReadOptions ro(false);
rocksdb::Status s = db->GetUpdatesSince(startingFrom, &it, ro);
for (; it->Valid(); it->Next()) {
   // ..
}
if (!it->status().ok())
   std::cout << it->status().ToString();
```

### Actual behavior

We regulary see a corruption error.

### Steps to reproduce the behavior

Scan the WAL via `GetUpdatesSince` and run parallel threads writing into the database instance.

**Comment by maysamyabandeh** [comment]
Thanks @graetzer. Changing it to ::TryAgain makes sense to me. Are you interested in submitting a PR?

**Comment by graetzer** [comment]
Sure thing https://github.com/facebook/rocksdb/pull/5474
