### ISSUE TITLE
Segmentation fault in open with  rocksdb-5.16.6

### ISSUE THREAD

**Issue by wangshuaifei** [facebook/rocksdb#5462]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
open success in c++ api 

### Actual behavior
open failed

### Steps to reproduce the behavior
# db.h code is 
#ifndef MY_DB_H
  2 #define MY_DB_H
  3 
  4 #include<stdio.h>
  5 #include<string.h>
  6 #include<iostream>
  7 #include "rocksdb/db.h"
  8 #include <unistd.h>
  9 
 10 namespace wfs{
 11 
 12 static std::string DBPath= "/root/wfs";
 13 static rocksdb::DB *db;
 14 
 15 int open();
 16 
 17 int put(std::string k,std::string v);
 18 
 19 int get(std::string k,std::string *v);
 20 
 21 void close();
 22 
 23 }
 24 #endif

# db.cpp

int open(){
  7     rocksdb::Options options;
  8 
  9     // options.IncreaseParallelism();
 10     // options.OptimizeLevelStyleCompaction();
 11     std::cout<<"dbpath = "<<DBPath<<std::endl;
 12     options.create_if_missing = true;
 13     rocksdb::Status status = rocksdb::DB::Open(options,DBPath,&db);
 14     if( !status.ok() ){
 15          std::cout<<status.ToString()<<std::endl;
 16          return -1;
 17     }
 18     return 0;
 19 }

it is open failed ,

**Comment by maysamyabandeh** [comment]
This does not seem like a bug; more like how to use rocksdb. Such question are better posted in user group where many other users could help learning how to work with rocksdb: https://www.facebook.com/groups/rocksdb.dev

**Comment by wangshuaifei** [comment]
> This does not seem like a bug; more like how to use rocksdb. Such question are better posted in user group where many other users could help learning how to work with rocksdb: https://www.facebook.com/groups/rocksdb.dev

Could you help me?what is wrong when I use api ? Thanks

**Comment by YJieZhang** [comment]
兄弟，这个问题解决了吗
