### ISSUE TITLE
memory leaked?

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#5512]
https://github.com/facebook/rocksdb/blob/9dbcda9e3b9b59b76b247e24e9ebc4b9263197ff/db/db_impl/db_impl.cc#L3061

may be a stupid question, but I believe it leaks here. If not, someone would figure out how it is destroyed?

**Comment by siying** [comment]
Does alloca() allocate memory from the stack?

**Comment by wolfkdy** [comment]
shame, I did'nt recognize function alloca. It is from glibc, not somewhere from rocksdb.
This function allocates memory from stack but I never heard or used it.
