### ISSUE TITLE
RocksDB fails to delete all the compacted files after compaction

### ISSUE THREAD

**Issue by sachinteotia30** [facebook/rocksdb#5541]
We use rocksDB to handle kafka keystores in our product. The issue is that whenever the rocksDB compaction starts, it takes 2 candidate files for compaction. Then generate a new compacted file but delete only one of the candidate file.

Thus, the other candidate file remains dangling and the number of sst files keeps on increasing in the system.

### Expected behavior
After compaction, all the compacted files should be deleted

### Actual behavior
[RocksDb_issue_logs.txt](https://github.com/facebook/rocksdb/files/3362128/RocksDb_issue_logs.txt)

**Comment by riversand963** [comment]
Base on the information that is present here, I wonder whether there is an iterator on the column family. If so, did you create the iterator before the compaction started? Did you delete it?

**Comment by sachinteotia30** [comment]
Thanks, @riversand963, yes there was an open iterator and that was stoping the compaction.

Thanks once again. Your one suggestion saved my life. I will close this ticket with that.
