### ISSUE TITLE
recent releases on maven repo?

### ISSUE THREAD

**Issue by nlevitt** [facebook/rocksdb#5555]
Latest per https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni is 6.0.1 whereas https://github.com/facebook/rocksdb/releases is at 6.1.2.

(Maybe uploading to maven central could be an automated thing that happens when you publish a release?)

**Comment by adamretter** [comment]
@nlevitt Apologies, I did not see that there was a new release. I will try and publish new RocksJava releases in the next couple of days.

**Comment by nlevitt** [comment]
🥺

**Comment by linux-china** [comment]
Any news?  😄

**Comment by adamretter** [comment]
@nlevitt @linux-china I have released 6.0.2, 6.1.1 and 6.1.2.

Sorry about the delays here at my end.
