### ISSUE TITLE
fail to open db after ingesting sstfile

### ISSUE THREAD

**Issue by haiping-kernel** [facebook/rocksdb#5564]
I create sst file with SstWriter, there is no error when put() and finsh(), then I ingest them to an empty database. ALL options are default. but when I open db , there is an error:
**void rocksdb::DataBlockHashIndex::Initialize(const char*, uint16_t, uint16_t*): Assertion `size > num_buckets_ * sizeof(uint8_t)' failed.**

**Comment by riversand963** [comment]
@haiping-kernel , which version of RocksDB are you using?
By empty database, does the database already exist but has no data, or is it freshly created?
The error message is complaining that you enabled hash index for data blocks, which should be disabled by default according to https://rocksdb.org/blog/2018/08/23/data-block-hash-index.html.
Sounds your use case is pretty straightforward, can you post your code so that we can take a look? Thanks

**Comment by haiping-kernel** [comment]
@
thanks, yes , I am just making a demo case , the version is 6.0.
sorry the code can not be copyed, it is of my company.  but the key lines are :

_rocksdb::SstFileWriter(rocksdb::EnvOptions(), options);
writer->Finish();
rocksdb::IngestExternalFileOptions ingest_options;
db->IngestExternalFile(files, ingest_options);_
all options are default., and all status are ok.

I create 5 sst-files ,they may be overlapped, so I ingest them to 5 columnfamilies,
then the case occurred. the database is created just at the moment before ingesting . now , I ingest them to 5 database, and it works. so I think the sst-file is correctly created. but i had a try before, using overlapped data  with more then one columnfamilies. So I am pretty comfused.

**Comment by haiping-kernel** [comment]
@riversand963

**Comment by haiping-kernel** [comment]
the other case is , when I ingest two sst-files of these five, I can Get the value of some keys. but after ingesting 4 files,  key NotFound...  I think it is may because the overlapped data. but my test before told me it can work.  confusing , is this  undefined ingesting overlapped sstfiles to different columnfamilies., or I try it in a wrong way ??

**Comment by riversand963** [comment]
```
#include <cstdio>
#include <string>

#include "rocksdb/db.h"
#include "rocksdb/options.h"
#include "rocksdb/slice.h"
#include "rocksdb/sst_file_writer.h"

using namespace rocksdb;

// REQUIRES /tmp/rocksdb must exist.
std::string kDBPath = "/tmp/rocksdb/rocksdb_ingest_test";
std::string kSstPath = "/tmp/rocksdb/test.sst";

int main() {
  Options options;
  options.create_if_missing = true;
  DB* db = nullptr;
  Status s = DB::Open(options, kDBPath, &db);
  if (!s.ok()) {
    fprintf(stderr, "%s\n", s.ToString().c_str());
    exit(1);
  }
  SstFileWriter sst_file_writer(EnvOptions(), options);
  s = sst_file_writer.Open(kSstPath);
  if (!s.ok()) {
    fprintf(stderr, "%s\n", s.ToString().c_str());
    exit(1);
  }
  sst_file_writer.Put("key0", "value0");
  sst_file_writer.Finish();
  IngestExternalFileOptions ifo;
  s = db->IngestExternalFile({kSstPath}, ifo);
  if (!s.ok()) {
  delete db;
    fprintf(stderr, "%s\n", s.ToString().c_str());
    exit(1);
  }
  delete db;
  db = nullptr;
  s = DB::Open(options, kDBPath, &db);
  if (!s.ok()) {
    fprintf(stderr, "%s\n", s.ToString().c_str());
    exit(1);
  }
  return 0;
}
```
Unable to reproduce based on the information disclosed.

**Comment by riversand963** [comment]
Another thing to check is whether the external SSTs are corrupted when you try to ingest them.
