### ISSUE TITLE
operatelog  is support?

### ISSUE THREAD

**Issue by superwood** [facebook/rocksdb#559]
I   knew the wal is supported。 But the wal is too big to saved for longtime。 why not and when operatelog  is supported?

**Comment by siying** [comment]
Can you explain what operatelog is and what's the difference from WAL?

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by sagar0** [comment]
Closing this issue as it is more than an year old without any response.
