### ISSUE TITLE
too many threads created while opening db

### ISSUE THREAD

**Issue by clicx** [facebook/rocksdb#5631]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

Using gdb to start a app that opening rocksdb, there are two many thread creating message and continue for several minutes, whats are the doing:

[New Thread 0x7fff9ffff700 (LWP 7185)]
[New Thread 0x7fff9f7fe700 (LWP 7186)]
[New Thread 0x7fffbcff9700 (LWP 7187)]
[Thread 0x7fffbcff9700 (LWP 7187) exited]
[Thread 0x7fff9ffff700 (LWP 7185) exited]
[New Thread 0x7fffbcff9700 (LWP 7188)]
[Thread 0x7fff9f7fe700 (LWP 7186) exited]
[New Thread 0x7fff9ffff700 (LWP 7189)]
[Thread 0x7fff83ff7700 (LWP 7184) exited]
[New Thread 0x7fff9f7fe700 (LWP 7190)]
[New Thread 0x7fff83ff7700 (LWP 7191)]
[Thread 0x7fff83ff7700 (LWP 7191) exited]
[Thread 0x7fffbcff9700 (LWP 7188) exited]
[New Thread 0x7fff83ff7700 (LWP 7192)]
[Thread 0x7fff9f7fe700 (LWP 7190) exited]
[New Thread 0x7fffbcff9700 (LWP 7193)]
[Thread 0x7fff9ffff700 (LWP 7189) exited]
[New Thread 0x7fff9ffff700 (LWP 7194)]
[New Thread 0x7fff9f7fe700 (LWP 7195)]
[Thread 0x7fff9f7fe700 (LWP 7195) exited]
[Thread 0x7fffbcff9700 (LWP 7193) exited]
[Thread 0x7fff9ffff700 (LWP 7194) exited]
[New Thread 0x7fff9f7fe700 (LWP 7196)]
[Thread 0x7fff83ff7700 (LWP 7192) exited]
[New Thread 0x7fff83ff7700 (LWP 7197)]
[New Thread 0x7fff9ffff700 (LWP 7198)]
[New Thread 0x7fffbcff9700 (LWP 7199)]
[Thread 0x7fffbcff9700 (LWP 7199) exited]
[Thread 0x7fff9ffff700 (LWP 7198) exited]
[New Thread 0x7fffbcff9700 (LWP 7200)]
[Thread 0x7fff9f7fe700 (LWP 7196) exited]

**Comment by riversand963** [comment]
Can you share more information on how your code uses RocksDB, e.g. how many `DB` instances you try to create in your program?

**Comment by ramvadiv** [comment]
@clicx - not enough info... Will close this Issue. Pls open a new issue, if you still have this problem and provide more details/background

**Comment by jay-zhuang** [comment]
During DB open, to parallelize the file loading speed, rocksdb creates multiple threads (by default 16) for that:
https://github.com/facebook/rocksdb/blob/a0e4421e8133620bb2934bb36272a021a7fc2cc2/db/version_builder.cc#L980-L987

You can control the thread number for loading by `max_file_opening_threads`:
https://github.com/facebook/rocksdb/blob/d1c510baecc1aef758f91f786c4fbee3bc847a63/include/rocksdb/options.h#L461-L464
