### ISSUE TITLE
crash when opening(creating) db

### ISSUE THREAD

**Issue by clicx** [facebook/rocksdb#5650]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
should work normally
### Actual behavior
segment fault.
### Steps to reproduce the behavior
master branch of newest code.

#0  __atomic_add (__val=1, __mem=0x8000008) at /usr/include/c++/4.8.2/ext/atomicity.h:53
#1  __atomic_add_dispatch (__val=1, __mem=0x8000008) at /usr/include/c++/4.8.2/ext/atomicity.h:96
#2  _M_add_ref_copy (this=0x8000000) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:131
#3  __shared_count (__r=..., this=0x7ffe26ad7138) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:553
#4  __shared_ptr (this=0x7ffe26ad7130) at /usr/include/c++/4.8.2/bits/shared_ptr_base.h:779
#5  shared_ptr (this=0x7ffe26ad7130) at /usr/include/c++/4.8.2/bits/shared_ptr.h:103
#6  ColumnFamilyOptions (this=0x7ffe26ad6fa0) at ./include/rocksdb/options.h:82
#7  rocksdb::ColumnFamilyOptions::ColumnFamilyOptions (this=0x7ffe26ad6fa0, options=...) at options/options.cc:102

**Comment by maysamyabandeh** [comment]
Unfortunately there is not enough information in the description to reproduce the issue.
