### ISSUE TITLE
Never used variable 'tmp_slice'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/rocksdb#5654]
https://github.com/facebook/rocksdb/blob/b538e756c29eac69e5362d9dff52833200d3e242/table/plain/plain_table_reader.cc#L736

advice: delete the variable which is never used

**Comment by siying** [comment]
It's interesting that the compiler never complains about it. Are you interested in sending a pull request to delete it?

**Comment by QiAnXinCodeSafe** [comment]
yes，I make a pr，please  reviewed，thanks！

https://github.com/facebook/rocksdb/pull/5660

**Comment by QiAnXinCodeSafe** [comment]
I am  so sad，because ‘You’re not authorized to merge this pull request.’

**Comment by siying** [comment]
@QiAnXinCodeSafe in fact, we are not authorized to merge anything either. We are using a system which a bot runs unit tests and merge it. However, for your case, you probably need to sign CLA first.
