### ISSUE TITLE
possible fitting low-pri threads but not doing flush job

### ISSUE THREAD

**Issue by liangjk** [facebook/rocksdb#5656]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

as long as bg_flush_scheduled_ < bg_job_limits.max_flushes we can add a flush job

### Actual behavior

only if bg_flush_scheduled_ + bg_compaction_scheduled_ < bg_job_limits.max_flushes

### Steps to reproduce the behavior
delete "+ bg_compaction_scheduled_"
at db/db_impl/db_impl_compaction_flush.cc:1915

**Comment by maysamyabandeh** [comment]
That is the intended behavior: https://github.com/facebook/rocksdb/blob/1dfc5eaab03f998ab13a6953b53e41cdfd2c8237/include/rocksdb/options.h#L569
