### ISSUE TITLE
How does rocksdb reduce the expense of compaction

### ISSUE THREAD

**Issue by HanZijie** [facebook/rocksdb#5661]
## Questions on multiple compactions

> When we estimate write amplification, we usually simplify the problem by assuming keys are uniformly distributed inside each level. In reality, it is not the case, even if user updates are uniformly distributed across the whole key range. For instance, when we compact one file of a level to the next level, it creates a hole. Over time, incoming compaction will fill data to the hole, but the density will still be lower for a while. Picking a file with keys least densely populated is more expensive to get the file to the next level, because there will be more overlapping files in the next level so we need to rewrite more data. For example, assume a file is 100MB, if an L2 file overlaps with 8 L3 files, we need to rewrite about 800MB of data to get the file to L3. If the file overlaps with 12 L3 files, we’ll need to rewrite about 1200MB to get a file of the same size out of L2. It uses 50% more writes. (This analysis ignores the key density of the next level, because the range covers N times of files in that level so one hole only impacts write amplification by 1/N)&nbsp;&nbsp;&nbsp;From [RocksDB by Facebook](https://rocksdb.org/blog/2016/01/29/compaction_pri.html).

#### Question
If the we always pick the most densely populated SST, The density of SST in lower level will become less and less. There will be more overlapping SST because the density of SST in the lower level is very small. So how do they solve this problem?

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
