### ISSUE TITLE
RocksDb duplicates the size of database over time

### ISSUE THREAD

**Issue by jbayardo** [facebook/rocksdb#5663]
We have a very high usage RocksDb database, where the workload is _always_ Get -> Put/Delete for the same key (done in parallel by up to 64 threads). Configurations is default, except for:

- MaxBackgroundCompactions=64
- MaxBackgroundFlushes=1
- IncreaseParallelism=32
- WAL disabled
- FSync disabled
- Keep a Bloom filter with K=10 and a hash index
- Using whole key filtering
- No prefix extractor 

Under some conditions, we need to regenerate the RocksDb instance from scratch, because all of the data inside of it is considered outdated. So, we do precisely that by creating a new instance and receiving all data again from the source (i.e. the DBs may have a very small set of values that are not shared).

When looking at the size of the 2 DBs, the regenerated DB is between 2 to 3 times smaller than the original DB, and space is important in this case. Moreover, we see how the DB grows over time through several days: it takes roughly 15 days to duplicate the size of the DB. To add some more information, it seems that the number of keys has actually decreased over the same time period 

Looking at the LOG, it seems compaction is happening every 10 minutes and removing keys as expected, none of the levels report scores higher than 1 at any time, and we are currently happy with the query speed. It is just the space amplification that seems too high.

I see that `max_size_amplification_percent`  is 200 by default, which would account for this behavior. However, we are not using Universal Compaction, which discards it being a side effect of that.

### Expected behavior

RocksDb's size should not be doubled over the course of time while holding the same amount of keys

### Actual behavior

Described above.

### Steps to reproduce the behavior

Maintain a Get -> Put/Delete workload constant during 15 days?

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

Thanks for well-written post. Running a vaguely-described workload for 15 days is not exactly a constructive way to reproduce an issue. This is more suited in dev group where other users could help you with suggestions on how to inspect the db as well as the configuration to look for potential issues.
