### ISSUE TITLE
Combine multiple Rocksdb databases

### ISSUE THREAD

**Issue by skp33** [facebook/rocksdb#5666]
There is a use case for which I have to read huge Parquet file and convert into Rocksdb binary, So I decided to use spark (because everybody is familiar with it in my team).

And from Rocksdb side I know it's not distributed and you can not parallelize.

So what I have done is that I have created multiple instances of Rocksdb parallelly using Spark for each task.

![](https://i.stack.imgur.com/2HyKF.png)

Now I want to combine them together. So My question is that, is it possible to combine multiple instances of Rocksdb together to create a big Rocksdb instance using some postprocessing?

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
