### ISSUE TITLE
[Noob Question] Better way to store HashMap/Array into RocksDB

### ISSUE THREAD

**Issue by bcashier** [facebook/rocksdb#5667]
Hi,

I am willing to store HashMap / Array into RocksDB, is there a feature for this ? Or a best approach to do that please ?

I am thinking to store them in form of JSON as value, but that will not let me make modifications quickly since I have first to deserialize the JSON and then make modification, and finally serialize back.

Thanks in advance

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
