### ISSUE TITLE
[Noob Question] Use wildcard to display ordered keys

### ISSUE THREAD

**Issue by bcashier** [facebook/rocksdb#5668]
Hi,

Is there a way to use wildcard in order to display ordered keys (By ASC => Time of insertion) ?

For example, I am inserting keys in this format:

```
db.put('save:1', 'test 1');
db.put('save:2', 'test 2');
...
```

And then, iterate to display all keys containing: "`save:*`"

Thank you

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
