### ISSUE TITLE
Never used variable ‘table_properties’

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/rocksdb#5678]
https://github.com/facebook/rocksdb/blob/6e78fe3c8d35fa1c0836af4501e0f272bc363bab/table/meta_blocks.cc#L399

**Comment by miasantreble** [comment]
Thanks for reporting, would you be interested to group a fix together with your another PR https://github.com/facebook/rocksdb/pull/5660? If you see similar issues elsewhere feel free to add to your PR
