### ISSUE TITLE
JVM crashes on using RocksDB

### ISSUE THREAD

**Issue by Aravindhan1995** [facebook/rocksdb#5682]
I am using rocksdbjni-6.0.1.jar for my application,  The data is consecutively fetched from the Rocksdb using RocksDB iterator. 

**code reference** 

```
byte[] keyToSeek = getLongValue((Long) (partKey));
byte[] upperBound = getLongValue((Long) (partKey) + 1);
setUpperAndLowerBoundValues(keyToSeek, upperBound, readOptions);
RocksIterator rocksIterator = rocksDB.newIterator(columnFamilyHandle, readOptions);
for (rocksIterator.seek(keyToSeek); rocksIterator.isValid(); rocksIterator.next())
{
  dataMap.put(getMultipleLongValueFromByteArray(rocksIterator.key()), (V) 
  deSerialize(rocksIterator.value()));
}
readOptions.close();
rocksIterator.close();
```

**getting the following issue**  and the JVM crashes.

Stack: [0x00007f83ce377000,0x00007f83ce478000],  sp=0x00007f83ce4764f8,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x16efe9]  __nss_passwd_lookup+0x2a649
C  [librocksdbjni957230696721401495.so+0x3f5d02]  rocksdb::BlockBasedTableIterator<rocksdb::DataBlockIter, rocksdb::Slice>::FindKeyForward()+0x252
C  [librocksdbjni957230696721401495.so+0x41e357]  rocksdb::MergingIterator::Next()+0x37
C  [librocksdbjni957230696721401495.so+0x2a776a]  rocksdb::DBIter::FindNextUserEntryInternal(bool, bool)+0x80a
C  [librocksdbjni957230696721401495.so+0x2a92b1]  rocksdb::DBIter::Next()+0x1c1
J  org.rocksdb.RocksIterator.next0(J)V

**Comment by adamretter** [comment]
What is the signal when the JVM crashes? SIGSEGV? or other?

**Comment by Aravindhan1995** [comment]
Hi adamretter,

Current thread (0x00007fc97003f000):  JavaThread "processor-5" [_thread_in_native, id=24635, stack(0x00007fc93475b000,0x00007fc93485c000)]

siginfo:si_signo=SIGSEGV: si_errno=0, si_code=128 (), si_addr=0x0000000000000000

**Comment by adamretter** [comment]
@Aravindhan1995 does this happen on 6.2.2?

If so, can you prepare a reproducible test case?

**Comment by Aravindhan1995** [comment]
I am using 6.0.1, The JVM crashes when there is continuous/concurrent put operation on one end and continuous/ concurrent seek on the other end. The system is running fine initially but crashes suddenly. In some cases, it crashes in  10 mins and in some cases it crashes in 30 mins.

**Comment by adamretter** [comment]
@Aravindhan1995 I am afraid I would need much more detail to be able to reproduce your issue.

As requested, can you please try with 6.2.2 first. If the issue persists then I would need to be able to reproduce the problem here. So you would need to tell me exactly how to go from nothing to demonstrating the problem that you have via. the minimum required steps.

**Comment by Aravindhan1995** [comment]
@adamretter, 

Thanks for your reply, I would for sure share the test plan and even produce sample code snippet to reproduce the issue. 
I have certain doubts regarding the usage which may have cause for the crash 

1) I am getting a new **RocksIterator** instance inside a method scope and seeking data and closing it, should I need to check whether rocksIterator.isOwningHandle() is true and then close the iterator. Since its RocksIterator instance is in local scope this should always return true/
 
>                  if (**rocksIterator.isOwningHandle()**)
> 			{
> 				rocksIterator.close();
> 			}

2) should I do the same for **ReadOptions** as well. 
   

> if (readOptions.isOwningHandle())
> 			{
> 				readOptions.close();
> 			}
> 

Note: After adding the above two fixes, till now my application has not crashed.  I want to know whether I am proceeding in the correct direction.

**Comment by adamretter** [comment]
Calling `RocksIterator#close()` will only cause the object to be closed the first time it is called, so you don't need to worry. The same goes for `ReadOptions` or any class that extends `RocksObject`.

You can use Java's `try-with-resources` to simplify your code where appropriate.

**Comment by koldat** [comment]
I would recommend you to run with -ea. It will enable assertions and can help you to identify issue. But as @adamretter said, always use try-with-resources. Even your "if" is having race condition. One thread can close and second still tries to use already released object. If you do not have assertions you can easily crash, because object pointers has meaningless values in native code.

**Comment by Aravindhan1995** [comment]
Hi Team,
This is fixed after using **try with resources in Java**. Thanks for the timely help.
