### ISSUE TITLE
RocksDB java in windows requires c++ visual studio redistributable/

### ISSUE THREAD

**Issue by Aravindhan1995** [facebook/rocksdb#5689]
HI,

In my application, I am using rocksdbjni-6.0.1.jar which has windows dll bundled inside. 
I am pretty much aware that for rocksDB run time environment requires visual studio c++ redistributable. Is there any way to run the rocksDB without c++ redistributable. I have tried several ways.
One of the ways is biding the msvcr110.dll and msvcp110.dll in run time and this also has failed.

Please suggest a proper way to run rocksDB on the windows machine without c++ redistributable.

Thank you

**Comment by adamretter** [comment]
AFAIK all applications compiled with C++ on Windows, require the target Windows machine to have the C++ redistributable runtime installed.

**Comment by Aravindhan1995** [comment]
This issue is resolved.
Solution : 
The **vcruntime140.dll** and **msvcp140.dll** can be bundled independently, Rocksdb refers to these dll's in run time. Thanks for your support.
