### ISSUE TITLE
closing RocksDB in java in multithreaded environment

### ISSUE THREAD

**Issue by Aravindhan1995** [facebook/rocksdb#5690]
Hi,
I am calling the API, **rocksDB.close();** during the application shutdown, while the data is stored and fetched in RocksDB from other threads parallelly. Is there a way to safely close the RocksDB without crashing of the application.
Note: I am aware  there is API named cancelBackGroundWork in c++, but I couldn't find it on the java API, please suggest a proper way to close the DB in the concurrent environment?

**Comment by adamretter** [comment]
Calling `#close()` on any RocksObject is a thread-safe operation, and it will ensure that the underlying resources are only freed once.

Within your own application, you are responsible for making sure you have finished using the database before calling `RocksDB#close()`.

**Comment by Aravindhan1995** [comment]
Thank you @adamretter.
