### ISSUE TITLE
What's the relationship between logfile_number_, logs_ and alive_log_files

### ISSUE THREAD

**Issue by cighao** [facebook/rocksdb#5732]
Recently, I'm reading the source code about write-ahead logging. But I'm confused about the variables, `logfile_number_`, `logs_` and `alive_log_files`. I don't know the relationship between these variables and how they work for WAL? When switching WAL, a new log file is created, but the memtable is flushed background. How to avoid the old log files being deleted before memtable is flushed? Thanks.

**Comment by riversand963** [comment]
Closing issue after long period of inactivity since last response. Assuming it resolved and closing it now.
