### ISSUE TITLE
DBTestUniversalCompaction.RecalculateScoreAfterPicking (db_universal_compaction_test) sometimes fails on ARM

### ISSUE THREAD

**Issue by wangxiyuan** [facebook/rocksdb#5736]
We are now testing Rocksdb on ARM. When running `make check_some` on master branch. There a test failed:

db_universal_compaction_test

db/db_universal_compaction_test.cc:1781: Failure
Value of: 5
Expected: NumSortedRuns()
Which is: 6
terminate called after throwing an instance of 'testing::internal::GoogleTestFailureException'
  what():  db/db_universal_compaction_test.cc:1781: Failure
Value of: 5
Expected: NumSortedRuns()
Which is: 6

I'm not sure how to fix them. Could Rocksdb team take a look at this issue? Thanks.

**Comment by pdillinger** [comment]
Reproduced for me running ./db_universal_compaction_test alone. (But it passed during "make check" for me.)

<blockquote><pre>
[ RUN      ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/0
db/db_universal_compaction_test.cc:1782: Failure
Expected equality of these values:
  NumSortedRuns()
    Which is: 6
  5
[  FAILED  ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/0, where GetParam() = (1, false) 
(72 ms)
[ RUN      ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/1
db/db_universal_compaction_test.cc:1782: Failure
Expected equality of these values:
  NumSortedRuns()
    Which is: 6
  5
[  FAILED  ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/1, where GetParam() = (1, true) (
67 ms)
[ RUN      ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/2
db/db_universal_compaction_test.cc:1782: Failure
Expected equality of these values:
  NumSortedRuns()
    Which is: 6
  5
[  FAILED  ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/2, where GetParam() = (3, false) 
(66 ms)
[ RUN      ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/3
db/db_universal_compaction_test.cc:1782: Failure
Expected equality of these values:
  NumSortedRuns()
    Which is: 6
  5
[  FAILED  ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/3, where GetParam() = (3, true) (66 ms)
[ RUN      ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/4
db/db_universal_compaction_test.cc:1782: Failure
Expected equality of these values:
  NumSortedRuns()
    Which is: 6
  5
[  FAILED  ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/4, where GetParam() = (5, false) (65 ms)
[ RUN      ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/5
db/db_universal_compaction_test.cc:1782: Failure
Expected equality of these values:
  NumSortedRuns()
    Which is: 6
  5
[  FAILED  ] UniversalCompactionNumLevels/DBTestUniversalCompaction.RecalculateScoreAfterPicking/5, where GetParam() = (5, true) (65 ms)
</pre></blockquote>
