### ISSUE TITLE
VS BUILD ERROR C2131

### ISSUE THREAD

**Issue by ananclub** [facebook/rocksdb#5746]
block_cache_analyzer\block_cache_trace_analyzer.cc	1212

**Comment by ananclub** [comment]
vs 2017&2019 release has same error

not support dynamic array.

4>block_cache_trace_analyzer.cc
5>block_cache_trace_analyzer.cc
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(653,57): warning C4244:  “参数”: 从“uint64_t”转换到“unsigned int”，可能丢失数据
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1212,24): error C2131:  表达式的计算结果不是常数
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1212,24): message :  因读取超过生命周期的变量而失败
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1212,24): message :  请参见“reuse_vector_size”的用法
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1212,43): error C2131:  表达式的计算结果不是常数
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1212,43): message :  因读取超过生命周期的变量而失败
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1212,43): message :  请参见“reuse_vector_size”的用法
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1216,37): error C3863:  不可指定数组类型“uint64_t [reuse_vector_size][reuse_vector_size]”
4>F:\project\rocksdb\tools\block_cache_analyzer\block_cache_trace_analyzer.cc(1260,1): error C2036:  “uint64_t [reuse_vector_size][reuse_vector_size]”: 未知的大小

**Comment by riversand963** [comment]
Have you given it a shot to fixing these compilation errors according to the messages from the compiler? With out information about version number/commit hash, it is difficult for other people to match the warnings/errors to the exact line numbers if they cannot reproduce it.
I haven't been able to test this, but if you (or anybody else with access to VS build) can eliminate these errors, a PR will be welcome.

**Comment by solicomo** [comment]
I think this is a dup to #5730.
And it is already fixed by the following commits in master:

- [51413e0a856f377a7d62dfe4606c29ba9051c872](https://github.com/facebook/rocksdb/commit/51413e0a856f377a7d62dfe4606c29ba9051c872)
- [6d58ea901d64626745b96cc9ac072b5c1c5c8be4](https://github.com/facebook/rocksdb/commit/6d58ea901d64626745b96cc9ac072b5c1c5c8be4)
- [f32a311f0dfa0dd95ada50b1ffc9bf62cb72af94](https://github.com/facebook/rocksdb/commit/f32a311f0dfa0dd95ada50b1ffc9bf62cb72af94)

**Comment by ananclub** [comment]
it has been fixed, thanks all.
