### ISSUE TITLE
rocksdb causes the hdd disk to have a very high latency

### ISSUE THREAD

**Issue by renhwztetecs** [facebook/rocksdb#5814]
when I use the following rocksdb options, I found that when the front-end business pressure is relatively large, the HDD disk pressure is relatively large, and the application delay is high. Is there any problem with the rocksdb options configuration?
thanks

> compression=kNoCompression
max_write_buffer_number=8
min_write_buffer_number_to_merge=2
recycle_log_file_num=4
compaction_style=kCompactionStyleLevel
write_buffer_size=536870912
target_file_size_base=67108864
max_background_compactions=28
max_background_flushes=4
level0_file_num_compaction_trigger=8
level0_slowdown_writes_trigger=32
level0_stop_writes_trigger=64
num_levels=7
max_bytes_for_level_base=536870912
max_bytes_for_level_multiplier=4
compaction_readahead_size=2097152
compaction_threads=32
flusher_threads=8
rate_limiter_bytes_per_sec=10485760

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
