### ISSUE TITLE
how to subscribe rocksdb increased data ?

### ISSUE THREAD

**Issue by wenweihu86** [facebook/rocksdb#5828]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

**Comment by qingping209** [comment]
https://github.com/facebook/rocksdb/wiki/Replication-Helpers

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
