### ISSUE TITLE
fallocate test in build_detect_patform is broken on Centos 6

### ISSUE THREAD

**Issue by pshareghi** [facebook/rocksdb#583]
When building Rocksdb on Centos 6, we noticed that the ROCKSDB_FALLOCATE_PRESENT flag is never present, although our kernel support fallocate and the FALLOC_FL_PUNCH_HOLE flag.

The reason for test failure is that FALLOC_FL_PUNCH_HOLE is defined in ```linux/falloc.h``` which is missing from the test in build_detect_platform script
```
#include <fcntl.h>
int main() {
  int fd = open("/dev/null", 0);
  fallocate(fd, FALLOC_FL_KEEP_SIZE | FALLOC_FL_PUNCH_HOLE, 0, 1024);
}
```

I will add a separate pull request to merge our fix.

**Comment by igorcanadi** [comment]
Nice find!

**Comment by pshareghi** [comment]
The bug is fixed in https://github.com/facebook/rocksdb/pull/584
