### ISSUE TITLE
[RocksJava] Open Secondary instance?

### ISSUE THREAD

**Issue by jognien** [facebook/rocksdb#5852]
It's a new feature in 6.1.
but can't find OpenAsSecondary in the RocksDB_jni 6.2.2.
Is it possible to provide support in the future?

**Comment by riversand963** [comment]
I may not have bandwidth for this recently. Would you be willing to contribute this API to RocksJava?

**Comment by adamretter** [comment]
I can probably add this

**Comment by alikinir** [comment]
Hi , trying to use it in 6.8.1 java and it still not there.. Can u please update?
