### ISSUE TITLE
HISTORY.md and "releases" discrepancies

### ISSUE THREAD

**Issue by akrylysov** [facebook/rocksdb#5853]
1. `HISTORY.md` mentions a few versions that are missing from the releases page - e.g. 6.4.0 and 6.3.*.
2. The releases page has a few versions that are missing from `HISTORY.md` - e.g. 6.2.4 and 6.2.3.

**Comment by siying** [comment]
Feel free to send a pull request to respective versions to fix them. CC @gfosco
