### ISSUE TITLE
[Improvement] Better False Positive rates for large BloomFilter

### ISSUE THREAD

**Issue by cooldoger** [facebook/rocksdb#5857]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

We have a use-case that want to have lower False Positive rates with large BloomFilter size. (As we're using FIFO compaction, so there're large number of L0 sstable files, which needs to be filtered out by BF). Currently, even we set the `bits_per_key` from default 10 to 250, we only get 0.178% FP rates. We believe it could do better.

cc. @siying, @pdillinger

**Comment by pdillinger** [comment]
Background in https://github.com/facebook/rocksdb/issues/4120
