### ISSUE TITLE
https://github.com/facebook/rocksdb/blob/master/examples/c_simple_example.c is missing Copyright header

### ISSUE THREAD

**Issue by tfarina** [facebook/rocksdb#591]
https://github.com/facebook/rocksdb/blob/master/examples/c_simple_example.c has no Facebook copyright header.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by vjon** [comment]
@tfarina, this was just closed by 7004a6f7b88fdbc600e583c4d9a77c1930c20ccf

Please close this Issue when you get the chance.

**Comment by tfarina** [comment]
Thank you.
