### ISSUE TITLE
Open new Rocksdb load CPU on Windows

### ISSUE THREAD

**Issue by LordWinterstorM** [facebook/rocksdb#5917]
Hello! I use multiple instance of RocksDb, until version 6.0.2 it was ok.
I use more than 100 different RocksDB
Since 6.1.1 each new open Rocks load my CPU + 25% and not free resource
System Windows
(On Linux works well)

### Expected behavior
val options = new Options().setCreateIfMissing(true)
val db1 = RocksDB.open(options, s"c:/db/rocks1")
val db2 = RocksDB.open(options, s"c:/db/rocks2")
val db3 = RocksDB.open(options, s"c:/db/rocks3")
val db4 = RocksDB.open(options, s"c:/db/rocks4")
...
val db100 = RocksDB.open(options, s"c:/db/rocks100")

CPU not load, because db in idle condition 

### Actual behavior
val options = new Options().setCreateIfMissing(true)
val db1 = RocksDB.open(options, s"c:/db/rocks1")
val db2 = RocksDB.open(options, s"c:/db/rocks2")
val db3 = RocksDB.open(options, s"c:/db/rocks3")
val db4 = RocksDB.open(options, s"c:/db/rocks4")

after 4 Rocks open CPU 100% load and system freez

### Steps to reproduce the behavior
val options = new Options().setCreateIfMissing(true)
val db1 = RocksDB.open(options, s"c:/db/rocks1")
val db2 = RocksDB.open(options, s"c:/db/rocks2")
val db3 = RocksDB.open(options, s"c:/db/rocks3")
val db4 = RocksDB.open(options, s"c:/db/rocks4")

**Comment by koldat** [comment]
If you have Windows 7, then it is most likely this regression I was hitting as well: #5552

**Comment by LordWinterstorM** [comment]
fixed in "6.4.6"
