### ISSUE TITLE
fsync on macos should use fcntl (fd, F_FULLFSYNC)

### ISSUE THREAD

**Issue by lni** [facebook/rocksdb#5954]
### Expected behavior
According to many online resources including the macos manpage, fcntl (fd, F_FULLFSYNC) should be called to ensure that data is actually flushed onto the permanent storage. 

### Actual behavior

when searching the repo, F_FULLFSYNC is not found in the code 

### Steps to reproduce the behavior

search the repo to see whether F_FULLFSYNC is used

**Comment by yiwu-arbug** [comment]
Came across this and find a related golang issue (golang 1.12 fixed it): https://github.com/golang/go/issues/26650
