### ISSUE TITLE
[Bug Report] two_write_queue is conflict with IngestExternalFile

### ISSUE THREAD

**Issue by Little-Wallace** [facebook/rocksdb#5974]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

I'm trying to replace  `DBImpl` with `TransactionDB`  to improve our project performance, following the method described in this blog: [unordered_write](https://rocksdb.org/blog/2019/08/15/unordered-write.html).
I enable the param `unordered_write` and `two_write_queue` to improve performance of write with multiple thread. We expect TransactionDB could perform as DBImpl.

### Actual behavior

When I ingest one sstable file into TransactionDB, it was blocked.

### Steps to reproduce the behavior
Here is my code to reproduce the problem: https://github.com/Little-Wallace/rocksdb/blob/transaction_db/utilities/transactions/write_prepared_transaction_test.cc#L3522

I ingest one sstable which overlap with key range of memtable. Of course, it will trigger one FlushJob of memtable.

I have run `pstack` for the process, and I found that RocksDB waited twice to be leader in `nonmem_write_thread_`.  One leader thread would be blocked if it tries to become leader in a second time.
Here is the first time to `EnterUnbatched` : https://github.com/facebook/rocksdb/blob/master/db/db_impl/db_impl.cc#L3817

And the second time: https://github.com/facebook/rocksdb/blob/master/db/db_impl/db_impl_write.cc#L1581

**Comment by Little-Wallace** [comment]
I thank we could use one `thread_local` variable here to avoid `EnterUnbatched ` twice.

**Comment by maysamyabandeh** [comment]
@yiwu-arbug Is this the same problem you faced?

**Comment by siying** [comment]
btw @yiwu-arbug can you take a look at https://github.com/facebook/rocksdb/pull/5716 ?

**Comment by siying** [comment]
@maysamyabandeh @Little-Wallace is @yiwu-arbug 's teammate. So the answer to your question must be no.

**Comment by yiwu-arbug** [comment]
> @yiwu-arbug Is this the same problem you faced?

Yes, I was referring to this issue found by @Little-Wallace.

**Comment by yiwu-arbug** [comment]
> btw @yiwu-arbug can you take a look at #5716 ?

Sorry it fell off my radar. Will take a look.

**Comment by yiwu-arbug** [comment]
Shall we enable unordered_write in db_crashtest.py?
