### ISSUE TITLE
RocksDB write batch operation fails with error and crashes while writing a batch with sync enabled.

### ISSUE THREAD

**Issue by avijayanhwx** [facebook/rocksdb#5981]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Version
      <groupId>org.rocksdb</groupId>
      <artifactId>rocksdbjni</artifactId>
      <version>6.0.1</version>

### Steps to reproduce the behavior
We have a RocksDB Java setup where we create a DB with sync enabled in Write options. Our RocksDB client is here - 
https://github.com/apache/hadoop-ozone/blob/master/hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/RDBStore.java

When we run a multilthreaded job that repeatedly tries to write data to RocksDB through our component, it fails with the following error after writing a few million keys, and the component (JVM) crashes. 

_**Caused by: org.rocksdb.RocksDBException: WritePrepared/WriteUnprepared txn tag when write_after_commit\_ is enabled (in default WriteCommitted mode). If it is not due to corruption, the WAL must be emptied before changing the WritePolicy.
at org.rocksdb.RocksDB.write0(Native Method)
at org.rocksdb.RocksDB.write(RocksDB.java:1421)**_

The operation that fails - 
https://github.com/apache/hadoop-ozone/blob/master/hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/RDBBatchOperation.java#L46

This happens only when the sync flag is enabled.
https://github.com/apache/hadoop-ozone/blob/19f0044a67c10b19aa1befe7c5c9ccd6df2410ca/hadoop-hdds/common/src/main/java/org/apache/hadoop/hdds/utils/db/DBStoreBuilder.java#L158

**Comment by maysamyabandeh** [comment]
The error message indicate that transaction write_policy is changed between the two DB opens. If you dont change that in your code (or you dont use transactions at all), it means that WAL is corrupted. You can use "./ldb --dump_wal" tool to further investigate the WAL content.
