### ISSUE TITLE
Support cloud file system schemes in HDFS URIs

### ISSUE THREAD

**Issue by masokan** [facebook/rocksdb#5988]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
When a cloud file system scheme is specified in HDFS URI, RocksDB should use the cloud file system for its storage.
### Actual behavior
RocksDB is trying to use the default file system
### Steps to reproduce the behavior
In Hadoop configuration, define the default file system as HDFS.  Also, add configuration parameters for a cloud storage like GCS.  In a program that uses RocksDB, create a HDFS environment by calling NewHdfsEnv() with a parameter like gs://mystorage for fsname.  Set this HDFS environment in Options parameter passed to DB::Open.

**Comment by riversand963** [comment]
We have been able to run dbstress on hdfs with fsname "hdfs://<.+>". Can you try something like the following?
```
$make db_stress
$./db_stress -ops_per_thread=100 -env_uri=hdfs://<your hdfs>:port
```

Under the hood, `hdfsConnectNewInstance(host, port)` will be called. Not sure whether this works with "gs://".
The configuration you make in Hadoop configuration will not be processed by RocksDB.
It will also be better if you could provide more information about your use case. For example, are you using RocksJava, which version, etc.

**Comment by masokan** [comment]
If I specify hdfs://namenode:port for the URI, it works.  However, gs://mybucket does not work even though GS is one of the configured file systems.  I have a patch that fixes this problem.  If someone assigns this ticket to me, I can create a pull request.  Thanks.

**Comment by darionyaphet** [comment]
Is it currently supported rocksdb on `HDFS` ?

**Comment by riversand963** [comment]
@masokan Feel free to submit a PR. Are you going to use the GCS Cloud Storage Connector for Hadoop?

**Comment by riversand963** [comment]
> Is it currently supported rocksdb on `HDFS` ?

You can run RocksDB on HDFS, but there are caveats.

- Certain RocksDB operations may require random write in certain situations. For example, file ingestion may write a global sequence number to an offset within an SST if configured by user.

- There are also cases in which RocksDB may access file system metadata more often than ideal since RocksDB was originally for local, POSIX filesystem whose metadata access is not too costly.

- HDFS, as a distributed file system, can have different and more errors than local file system. Currently they are not handled in the best way, and we are already working on it. cc @anand1976 is working on #5761 to address this issue.

You are more than welcome to try RocksDB on HDFS, and report any corruption/inconsistency you observe using Github issues.

**Comment by masokan** [comment]
@riversand963 Great feedback.  Thanks!  Sure I will submit a PR soon.
Functionally, I am aware of one limitation of HDFS (and cloud file systems): there is no file locking support.  If table locking is done outside RocksDB, this limitation can be dealt with.
As far as performance is concerned, in my use case I will try to avoid the situations you mentioned.  With my patch, I did some preliminary testing on GS and it seems to work.  On HDFS, so far I have not encountered any serious problem.

**Comment by masokan** [comment]
@riversand963 I have checked in my changes to @masokan /rocksdb.  I have difficulty submitting a pull request.  Please help.

I tested the fix by running some tests to access HDFS and GCS.  I do not have access to S3 or Azure to test them.

Following are some differences in the behavior of RocksDB between the current release and after the fix for this issue:

- When a HDFS URI is specified without a port number for name node, the current release throws an exception with a message like:

Bad uri for hdfs hdfs://namenode.myorg.com

With the fix, there will not be any error since default port will be assumed.

- When a HDFS URI is specified without a name node and port number, the current release throws an exception with a message like:

Bad uri for hdfs hdfs://

With the fix, libhdfs prints the following in stderr:

URISyntaxException: Expected authority at index 7: hdfs://java.lang.IllegalArgumentException: Expected authority at index 7: hdfs://
	at java.net.URI.create(URI.java:852)
Caused by: java.net.URISyntaxException: Expected authority at index 7: hdfs://
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.failExpecting(URI.java:2854)
	at java.net.URI$Parser.parseHierarchical(URI.java:3102)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)

Also, RocksDB will throw an exception with the following message:

Error connecting to hdfs://.  Errno = 22

The errno value 22 corresponds to EINVAL or Invalid argument.

- Suppose Hadoop is configured with GCS as one of the file systems.  When a cloud file system URI like gs://mybucket is specified, the current release prints out the following in stderr:

hdfsOpenFile(/table1): FileSystem#create((Lorg/apache/hadoop/fs/Path;ZISJ)Lorg/apache/hadoop/fs/FSDataOutputStream;) error:
RemoteException: Permission denied: user=asokan, access=WRITE, inode="/":hdfs:hdfs:drwxr-xr-x
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.check(FSPermissionChecker.java:399)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:255)
	at org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer$RangerAccessControlEnforcer.checkDefaultEnforcer(RangerHdfsAuthorizer.java:555)
	at org.apache.ranger.authorization.hadoop.RangerHdfsAuthorizer$RangerAccessControlEnforcer.checkPermission(RangerHdfsAuthorizer.java:316)
	at org.apache.hadoop.hdfs.server.namenode.FSPermissionChecker.checkPermission(FSPermissionChecker.java:193)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1850)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkPermission(FSDirectory.java:1834)
	at org.apache.hadoop.hdfs.server.namenode.FSDirectory.checkAncestorAccess(FSDirectory.java:1793)
	at org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.resolvePathForStartFile(FSDirWriteFileOp.java:315)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFileInt(FSNamesystem.java:2407)
	at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.startFile(FSNamesystem.java:2351)
	at org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.create(NameNodeRpcServer.java:774)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.create(ClientNamenodeProtocolServerSideTranslatorPB.java:462)
	at org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)

...

For brevity, I omitted a lot of lines from stack trace.

In addition, RocksDB returns an error status with the message:

IO error: /table1: Permission denied

This is because RocksDB tries to use the default file system (HDFS) and create the directory /table1 for the table.  However, user does not have access rights to "/".

With the fix, RocksDB will successfully create a table in gs://mybucket/table1

**Comment by masokan** [comment]
@maysamyabandeh can you please reassign this to me?  I can create a pull request for review.  Thanks.

**Comment by maysamyabandeh** [comment]
1. You don't need the assign feature to create a PR.
2. I recommend making sure @riversand963 is onboard before working on the PR.

**Comment by masokan** [comment]
@maysamyabandeh Thanks.  @riversand963 do you have any comments before I create a PR?  Thanks,

**Comment by riversand963** [comment]
@masokan , I think it will be good if you can contribute a PR to make it work on GCS, but I very likely won't have bandwidth to review the PR in the short term.

**Comment by masokan** [comment]
@riversand963 , Thanks.  I will create the PR.

**Comment by masokan** [comment]
@riversand963 Can you spare some time to look at this patch now?

**Comment by riversand963** [comment]
We are in the process of migrating support for specific Env/FS away from main repo. Therefore, we will not continue to include support for specific file systems to main. #9159 and #9207 have more context.
