### ISSUE TITLE
Prefix Seek API In Java performance

### ISSUE THREAD

**Issue by vamossagar12** [facebook/rocksdb#6004]
I am looking to implement the Prefix seek mode implementation provided in the Java APIs. 1 of the questions that we had is that are there any performance implications which can arise due to frequent conversion of Java objects to native code via JNI. 

Something similar to this: https://github.com/facebook/rocksdb/issues/538#issuecomment-83145980

Is this something which we need to be mindful of if plan to store say million plus entries in rocksdb?

**Comment by koldat** [comment]
I agree. There is a PR from me very long time. I did not heard back from RocksDB team. We are using that in our production very long time and it helps a lot (direct buffers).

PR: #2283

Then you can simply extend it for function you are interested in.

**Comment by koldat** [comment]
@siying @adamretter  Can we agree on final "no" or "yes"? I can then rebase to master. I need to do that with every release in our builds and it looks to me that it is demanded by other people as well.

**Comment by koldat** [comment]
#2283 was just merged into master. If you are OK you can close the issue.

**Comment by adamretter** [comment]
Please reopen if there is still an issue.

**Comment by vamossagar12** [comment]
Sure thank you.
