### ISSUE TITLE
OpenAsSecondaryWALTailing in rocksdb_db_secondary_test  Failed

### ISSUE THREAD

**Issue by CAIQT** [facebook/rocksdb#6012]
### Expected behavior
Pass test. (Built with vs2017, running in Win10 x64)

### Actual behavior
Raise Exception.  Program crashed.
![Untitled](https://user-images.githubusercontent.com/3953402/68364596-666f8580-0169-11ea-9dc9-3336b8785b86.png)

### Steps to reproduce the behavior
build with vs2017 with debug configuration, and simply run **rocksdb_db_secondary_test**

**Comment by CAIQT** [comment]
I found that it may caused by the following codes in function _RemoveOldMemTables()_ in **db/memtable_list.cc**  :
`
  for (auto it = memlist.rbegin(); it != memlist.rend(); ++it) {
    MemTable* mem = *it;
    if (mem->GetNextLogNumber() > log_number) {
      break;
    }
    current_->Remove(mem, to_delete);
`

The iterator **it** turns invalid after `current_->Remove(mem, to_delete);`

**Comment by riversand963** [comment]
PR is under review. Let's migrate our discussions to PR :). I will be closing this issue to avoid duplication. Thanks @CAIQT for reporting the issue.
