### ISSUE TITLE
Proposal: BlobDB GC with merge operator

### ISSUE THREAD

**Issue by yiwu-arbug** [facebook/rocksdb#6019]
I understand BlobDB's GC is still under development, but the existing partial implementation is when GC try to update blob index in LSM, it will make use of write callback for write conflict check (https://github.com/facebook/rocksdb/blob/master/utilities/blob_db/blob_db_impl.cc#L1431). Per our experiment it will hurt user write performance during GC, since GC writer will need to drain the writer queue before the write callback can be called.

Instead of use write callback for conflict check, we can simply write a merge operand to update blob index, which delays the write conflict check to read and compaction. Despite still needing to update LSM, this approach would improve both user write and GC performance. But to do that, we will need to add a new value type kTypeMergeBlobIndex and related logic to rocksdb. We are still working on a prototype on Titan (our custom implementation for KV-separation) and will attach the experiment result once we have it.

What's your thought about the approach? Does it conflict with current plan for BlobDB GC? @siying @ltamasi

**Comment by tabokie** [comment]
While working on the prototype, I found that merge operator only provides an incomplete abstraction of "state transition".
A complete state transition should cover value-type transition, as per the doc:
```
From the state machine point of view, Merge is really a generic transition that looks at the current state (existing value, or non-existence of that), combines it with the operand (the value associated with the Merge operation) and then produces a new value (state).
Put, is a degenerate case of Merge, that pays no attention to the current state, and produces the new state solely based on its operand.
Delete goes one step further - it doesn't even have an operand and always bring the key back to its original state - non-existent.
```
For example, I can't leverage current merge operator interface to delete a key (which involves changing value_type from `kTypeValue` to `kTypeDeletion`)
I want to know what's the official saying on this problem?

**Comment by ltamasi** [comment]
@yiwu-arbug We're actually taking a different approach for garbage collection in BlobDB; I expect the pre-existing partial implementation to go away in the next couple of weeks.

**Comment by yiwu-arbug** [comment]
@ltamasi sure. It'd be great if you can share some info of the new GC approach. But we look forward to any advancement to the BlobDB project anyway.

**Comment by yiwu-arbug** [comment]
> While working on the prototype, I found that merge operator provides a partial abstraction of "state transition".
> A complete state transition should cover value-type transition, as per the doc:
> 
> ```
> From the state machine point of view, Merge is really a generic transition that looks at the current state (existing value, or non-existence of that), combines it with the operand (the value associated with the Merge operation) and then produces a new value (state).
> Put, is a degenerate case of Merge, that pays no attention to the current state, and produces the new state solely based on its operand.
> Delete goes one step further - it doesn't even have an operand and always bring the key back to its original state - non-existent.
> ```
> 
> For example, I can't leverage current merge operator interface to delete a key (which involves changing value_type from `kTypeValue` to `kTypeDeletion`)
> I want to know what's the official saying on this limitation?

Let's get a hacky working prototype and see how's the result before worrying about API.

**Comment by ufminhas** [comment]
@ltamasi : Your last reply on this thread was about ~6 months ago. Curious whether there has been any further progress on this **new GC approach** that you referenced above. Are there any design docs that you can share?
