### ISSUE TITLE
File ingest may skip necessary memtable flush if unordered_write is enabled

### ISSUE THREAD

**Issue by yiwu-arbug** [facebook/rocksdb#6026]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
File ingestion job need to flush memtable if key range of the file being ingest overlap with key wrote before the job and haven't flush.

### Actual behavior
When unordered_write is enabled, a key can have seqno assigned and wrote to WAL before an ingestion job starts, and pending writing to memtable. If the ingestion job check memtable key range before the key landing in memtable, the ingestion job may skip the necessary memtable flush, causing data corruption.

### Steps to reproduce the behavior
See test in https://github.com/yiwu-arbug/rocksdb/commit/27399777f4280b291aa3e3c5733d61a3c62624e8

**Comment by yiwu-arbug** [comment]
@maysamyabandeh I plan to fix it by having ingestion job wait on `switch_cv_` before checking memtable key range. What do you think? Thanks.

**Comment by yiwu-arbug** [comment]
@maysamyabandeh ping

**Comment by maysamyabandeh** [comment]
Sorry @yiwu-arbug for delayed response. I had not got the notification.
Your solution sounds good. Can you remind me how this behavior is broken with unordered_write? How does the normal write enforce this?

**Comment by yiwu-arbug** [comment]
Ingestion job enters writer queue so that for normal write, when ingestion job checks memtable key range, there are no ongoing memtable writes. With unordered_write we need to make sure no ongoing memtable write as well.

**Comment by maysamyabandeh** [comment]
Makes sense. Thanks for working on this. Looking forward to the patch.
