### ISSUE TITLE
Why use batched write in DBImpl::WriteImpl() when disable WAL

### ISSUE THREAD

**Issue by cighao** [facebook/rocksdb#6033]
When disabling WAL and enabling concurrent memtable writes, why do we still use batched write in DBImpl::WriteImpl() to serialize the writes. In DBImpl::WriteImpl(), 
(1) it selects a leader, then get a global sequence
(2) pick up the followers 
(3) set sequence for the followers 
(4) concurrently write data to memtable
(5) wait for all requests which are in this batch to be finished
(6) update the global sequence
In this case,  if one batching is running, other requests which are not in this batch must wait for this batch to be finished. And in a batch, the fastest write request must wait for the slowest write request to be finished. These two restrictions cause a longer latency.

Why not concurrent write all requests into memtable in DBImpl::WriteImpl() :
(1) atomically get a sequence by FetchAddLastAllocatedSequence()
(2) concurrent write the data into memtable
In this case, we do not need any synchronization between different threads.

**Comment by yiwu-arbug** [comment]
@cighao what you propose is more close to the recently introduced `unordered_write` option. The catch with that is on read, some keys with seq < last_seq may not landed in memtable yet. If your application can live with that (e.g. have external mechanism to skip keys still being written, etc), the `unordered_write` option is actually pretty neat.

**Comment by siying** [comment]
As what @yiwu-arbug  said, it's mostly unordered_write feature. If you are able to handle relaxed consistency guarantee, you can give it a try. This feature can achieve up to 3x peak write throughput.
