### ISSUE TITLE
MultiGet api support for TTLDb

### ISSUE THREAD

**Issue by ovjh** [facebook/rocksdb#604]
This I think is a feature request. Today TTLDB lacks MultiGet api support. It would be good to have for all those who want to switch from normal DB to TTLDB.

**Comment by dgrnbrg** [comment]
+1 to this!

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by igorcanadi** [comment]
Looks like this already exists: https://github.com/facebook/rocksdb/commit/ade4034a9d4d42caed8d9e635a905fdf1152b361

**Comment by igorcanadi** [comment]
@ovjh @dgrnbrg let me know if i'm missing something :)
