### ISSUE TITLE
random read test. 

### ISSUE THREAD

**Issue by leaout** [facebook/rocksdb#6044]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
I stored 300000000 key-value in 7 column families.
then testing random read.   expected  more than 10000 ops/sec
### Actual behavior
about 10 ops/sec
but, when i ran it several times , the performance increased.
### Steps to reproduce the behavior
db options:
avoid_unnecessary_blocking_io=false
  two_write_queues=false
  allow_ingest_behind=false
  writable_file_max_buffer_size=1048576
  avoid_flush_during_shutdown=false
  avoid_flush_during_recovery=false
  info_log_level=INFO_LEVEL
  access_hint_on_compaction_start=NORMAL
  allow_concurrent_memtable_write=true
  enable_pipelined_write=false
  stats_dump_period_sec=600
  stats_persist_period_sec=600
  strict_bytes_per_sync=false
  WAL_ttl_seconds=0
  WAL_size_limit_MB=0
  max_subcompactions=1
  dump_malloc_stats=false
  db_log_dir=
  wal_recovery_mode=kPointInTimeRecovery
  log_file_time_to_roll=0
  enable_write_thread_adaptive_yield=true
  recycle_log_file_num=0
  table_cache_numshardbits=6
  atomic_flush=false
  preserve_deletes=false
  stats_history_buffer_size=1048576
  max_open_files=-1
  max_file_opening_threads=16
  delete_obsolete_files_period_micros=21600000000
  max_background_flushes=-1
  write_thread_slow_yield_usec=3
  base_background_compactions=-1
  manual_wal_flush=false
  wal_dir=data/1
  max_background_compactions=-1
  bytes_per_sync=0
  max_background_jobs=4
  use_fsync=true
  unordered_write=false
  fail_if_options_file_error=false
  random_access_max_buffer_size=1048576
  compaction_readahead_size=0
  wal_bytes_per_sync=0
  new_table_reader_for_compaction_inputs=false
  skip_stats_update_on_db_open=false
  persist_stats_to_disk=false
  skip_log_error_on_recovery=false
  log_readahead_size=0
  is_fd_close_on_exec=true
  use_adaptive_mutex=false
  error_if_exists=false
  write_thread_max_yield_usec=100
  enable_thread_tracking=false
  db_write_buffer_size=67108864
  create_missing_column_families=false
  paranoid_checks=true
  create_if_missing=true
  max_manifest_file_size=1073741824
  allow_2pc=false
  max_total_wal_size=0
  use_direct_io_for_flush_and_compaction=false
  manifest_preallocation_size=4194304
  use_direct_reads=false
  delayed_write_rate=16777216
  allow_fallocate=true
  keep_log_file_num=1000
  allow_mmap_reads=false
  max_log_file_size=0
  allow_mmap_writes=false
  advise_random_on_open=true

column family options :
  pin_top_level_index_and_filter=true
  enable_index_compression=true
  read_amp_bytes_per_bit=8589934592
  format_version=2
  block_align=false
  metadata_block_size=4096
  block_size_deviation=10
  partition_filters=false
  block_size=4096
  index_block_restart_interval=1
  no_block_cache=false
  checksum=kCRC32c
  whole_key_filtering=true
  index_shortening=kShortenSeparators
  data_block_index_type=kDataBlockBinarySearch
  index_type=kBinarySearch
  verify_compression=false
  filter_policy=nullptr
  data_block_hash_table_util_ratio=0.750000
  pin_l0_filter_and_index_blocks_in_cache=false
  block_restart_interval=16
  cache_index_and_filter_blocks_with_high_priority=true
  cache_index_and_filter_blocks=false
  hash_index_allow_collision=true
  flush_block_policy_factory=FlushBlockBySizePolicyFactory

**Comment by siying** [comment]
What's your block cache size? If you never set it, it is a default 8MB block cache and it will be too small.

In general, it is a good idea to report perf_context so that we can break down the latency. Here is how to get it: https://github.com/facebook/rocksdb/wiki/Perf-Context-and-IO-Stats-Context

**Comment by leaout** [comment]
std::shared_ptr<rocksdb::Cache> cache = rocksdb::NewLRUCache(64<<20);
    rocksdb::BlockBasedTableOptions table_options;
    table_options.block_cache = cache;
    options_.table_factory.reset(rocksdb::NewBlockBasedTableFactory(table_options)); 

@siying , I setted , but it seem to   not work.

**Comment by siying** [comment]
@leaout can you post perf context profile for your query?

**Comment by leaout** [comment]
user_key_comparison_count = 2113124, block_cache_hit_count = 38471, block_read_count = 29935, block_read_byte = 26614743, block_read_time = 239801853834, block_cache_index_hit_count = 0, index_block_read_count = 0, block_cache_filter_hit_count = 0, filter_block_read_count = 0, compression_dict_block_read_count = 0, block_checksum_time = 35958815, block_decompress_time = 394606542, get_read_bytes = 556493, multiget_read_bytes = 0, iter_read_bytes = 0, internal_key_skipped_count = 0, internal_delete_skipped_count = 0, internal_recent_skipped_count = 0, internal_merge_count = 0, write_wal_time = 0, get_snapshot_time = 52222906, get_from_memtable_time = 0, get_from_memtable_count = 0, get_post_process_time = 42667366, get_from_output_files_time = 241508575628, seek_on_memtable_time = 0, seek_on_memtable_count = 0, next_on_memtable_count = 0, prev_on_memtable_count = 0, seek_child_seek_time = 0, seek_child_seek_count = 0, seek_min_heap_time = 0, seek_internal_seek_time = 0, find_next_user_entry_time = 0, write_pre_and_post_process_time = 0, write_memtable_time = 0, write_thread_wait_nanos = 0, write_scheduling_flushes_compactions_time = 0, db_mutex_lock_nanos = 0, db_condition_wait_nanos = 0, merge_operator_time_nanos = 0, write_delay_time = 0, read_index_block_nanos = 0, read_filter_block_nanos = 0, new_table_block_iter_nanos = 240755697432, new_table_iterator_nanos = 0, block_seek_nanos = 339526664, find_table_nanos = 0, bloom_memtable_hit_count = 0, bloom_memtable_miss_count = 0, bloom_sst_hit_count = 0, bloom_sst_miss_count = 0, key_lock_wait_time = 0, key_lock_wait_count = 0, env_new_sequential_file_nanos = 0, env_new_random_access_file_nanos = 0, env_new_writable_file_nanos = 0, env_reuse_writable_file_nanos = 0, env_new_random_rw_file_nanos = 0, env_new_directory_nanos = 0, env_file_exists_nanos = 0, env_get_children_nanos = 0, env_get_children_file_attributes_nanos = 0, env_delete_file_nanos = 0, env_create_dir_nanos = 0, env_create_dir_if_missing_nanos = 0, env_delete_dir_nanos = 0, env_get_file_size_nanos = 0, env_get_file_modification_time_nanos = 0, env_rename_file_nanos = 0, env_link_file_nanos = 0, env_lock_file_nanos = 0, env_unlock_file_nanos = 0, env_new_logger_nanos = 0, get_cpu_nanos = 3797313407, iter_next_cpu_nanos = 0, iter_prev_cpu_nanos = 0, iter_seek_cpu_nanos = 0

**Comment by siying** [comment]
@leaout how many queries is it for? 

```
block_read_count = 29935, block_read_byte = 26614743, block_read_time = 239801853834
```
Block reading time is really relatively long: 8 miiliseconds per block read, and each block is about 900 byte read. Are you running on hard drives? If it is hard drive, then it is expected. If it is flash, check why one I/O takes so long. But I wouldn't expect even close to10K QPS for hard drives.

Also, since you are running Get() most of the them, I suggest you enable bloom filter. This might get you improvements of several times.

**Comment by leaout** [comment]
@siying about 30000 get() ops,
running on hard drive, 
already set "options_.bloom_locality = 5" ,

another test:
when stored 30000000 key-value pairs in rokcsdb, get() runs very fast.
but if stored ten times(30000*10000)  key-value pairs, get() runs slow. have divided into 7 column families.

I want to know how to improve get() perfmance if stored large data.

**Comment by siying** [comment]
"options_.bloom_locality = 5" does not turn on bloom filter. You can find how you can turn on bloom filters here: https://github.com/facebook/rocksdb/wiki/RocksDB-Bloom-Filter

Performance for simple Get() with reasonable amount of DRAM is very straight-forward if you run on hard drives. Turn on bloom filter, and it should do approximately I/O per request. Using certain amount of threads, you would saturate the hard drive. If it is not what you are observing, it is likely bloom filter is not turned on, or not all metadata blocks are cached in memory.

Btw, this is not very important since you use cache_index_and_filter_blocks: are you sure you only want to give 64MB to block cache? It feels small for most use cases. It shouldn't impact your use case though.
