### ISSUE TITLE
memtablerep_bench cannot run

### ISSUE THREAD

**Issue by WangEP** [facebook/rocksdb#6078]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
I want to test the performance, so I compile and run the memtablerep_bench program. but I got an error:
ERROR: flag 'benchmarks' was defined more than once (in files '/rocksdb/tools/db_bench_tool.cc' and '/rocksdb/memtable/memtablerep_bench.cc').

I already install the gflags, and there are no error during compiling.

**Comment by riversand963** [comment]
Feel free to reopen, but I tried this on latest main.
```
make memtablerep_bench db_bench
./memtablerep_bench -benchmarks=fillrandom
./db_bench -benchmarks=fillrandom
```
They both work.
