### ISSUE TITLE
how to generate sst file into hdfs using mapreduce 

### ISSUE THREAD

**Issue by lnparker** [facebook/rocksdb#6109]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
generate sst file into hdfs using mapreduce
### Actual behavior
successfully create file in hdfs using org.apache.hadoop.fs.FileSystem.create func , and use org.rocksdb.SstFileWriter.open to open and write the file, but mapreduce fails : "no such file". It seems that SstFileWriter can not read the file in hdfs.

**Comment by lnparker** [comment]
is there any solution to this problem ..?

**Comment by riversand963** [comment]
Closing because we use issues to report bugs and track up-for-grab tasks.
Could you migrate this question to the Google group or public RocksDB developer group on Facebook? Thanks

**Comment by GOGOYAO** [comment]
> Closing because we use issues to report bugs and track up-for-grab tasks.
> Could you migrate this question to the Google group or public RocksDB developer group on Facebook? Thanks

Is there some discuss about this anywhere?
