### ISSUE TITLE
Mismatched free() / delete / delete []

### ISSUE THREAD

**Issue by hjiayz** [facebook/rocksdb#6112]
valgrind message:
Mismatched free() / delete / delete []

https://github.com/facebook/rocksdb/blob/e8f997ca597761087c46ad6657aebe7c73a45e38/include/rocksdb/c.h#L1532

https://github.com/facebook/rocksdb/blob/e8f997ca597761087c46ad6657aebe7c73a45e38/db/c.cc#L3890
new rocksdb_snapshot_t;

https://github.com/facebook/rocksdb/blob/e8f997ca597761087c46ad6657aebe7c73a45e38/db/c.cc#L4256
free

**Comment by anand1976** [comment]
I think there should be a ```void rocksdb_transaction_free_snapshot(rocksdb_snapshot_t* snapshot)``` that will ```delete``` the allocated structure.
