### ISSUE TITLE
rocksdbJava : java.lang.UnsatisfiedLinkError: org.rocksdb.Env.getDefaultEnvInternal()

### ISSUE THREAD

**Issue by lnparker** [facebook/rocksdb#6118]
I am trying to use MapReduce to generate SST files, but I get the error when I create a new `HdfsEnv` object, like below :
```java
HdfsEnv env = new HdfsEnv("hdfs://***.org:8000");
```
### Steps to reproduce the behavior
* I have tried maven rocksjni `6.4.6`, `6.3.6`, and `6.0.2` but all come with the error.
* I have tried  jdk1.8 and jdk1.7 both to compile the project, but  all come with the error.

**Comment by lnparker** [comment]
i find out that Class Env is the father Class of HdfsEnv, so it calls Env construct function. Finally it calls  _getDefaultEnvInternal_ in Env construct function. The corresponding error information is below:
_at org.rocksdb.Env.getDefaultEnvInternal(Native Method)
	at org.rocksdb.Env.<clinit>(Env.java:16)_

**Comment by lnparker** [comment]
i also compile and package the project with dependencies, which means that the jar package contains lib-rocksdbjni-linux64/32.so .

**Comment by lnparker** [comment]
@adamretter hello Adam, can u help me with this problem. thx

**Comment by lnparker** [comment]
hi @adamretter  adam, ps, my code is like below, is this the right way to generate sst file into hdfs  in mapreduce ? thx.

```
HdfsEnv env = new HdfsEnv("hdfs://xxx.org:8000");
DBOptions dbOps = new DBOptions();
dbOps.setEnv(env);
sstWriter = new SstFileWriter(new EnvOptions(dbOps), new Options());
sstWriter.open(filePath.toString());
sstWriter.put(key.getBytes(), value.getBytes());
sstWriter.finish();;
```

@adamretter

**Comment by adamretter** [comment]
@lnparker can you share the full error message and stack that you get please?

We have tests like: `DefaultEnvTest#backgroundThreads()` which seem to show that `Env::getDefaultEnvInternal()` work correctly without error.

**Comment by lnparker** [comment]
> @lnparker can you share the full error message and stack that you get please?
> 
> We have tests like: `DefaultEnvTest#backgroundThreads()` which seem to show that `Env::getDefaultEnvInternal()` work correctly without error.
@adamretter 
 i have sent the error stack to your email, please check it . thanks.

**Comment by adamretter** [comment]
@lnparker I have not received any email from you. Could you post it here?

**Comment by lnparker** [comment]
@adamretter here is the error information. plx help me checking it, thanks.
![image](https://user-images.githubusercontent.com/5960644/70292074-fe6b9800-1817-11ea-945a-b8837ec01eb5.png)

**Comment by lnparker** [comment]
![WechatIMG310](https://user-images.githubusercontent.com/5960644/70292169-5c987b00-1818-11ea-889e-58a3082fe94d.png)

**Comment by Myasuka** [comment]
@lnparker Have you ever tried to load library before any further usage?
~~~ java
NativeLibraryLoader.getInstance().loadLibrary(path);
RocksDB.loadLibrary();
~~~

**Comment by adamretter** [comment]
@Myasuka Good point!

Whilst `DBOptions` or `Options` will load the library for you, as we expect them to be one of the first things you instantiate, `Env` and its subclasses do not. I will send a PR so that `Env` also loads the library for you.
