### ISSUE TITLE
rocksdb_filterpolicy_create_bloom_full (C interface) uses old block-based filter

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#6129]
TIL we have a C wrapper struct rocksdb_filterpolicy_t : public FilterPolicy. A derived class of that wrapper is defined in rocksdb_filterpolicy_create_bloom_format. However, this code was not properly updated for the "full bloom filter" implemented ~4 years ago, so a filter policy from rocksdb_filterpolicy_create_bloom_full effectively uses block-based filter instead of full filter. This was not detected until I added an assertion to BloomFilterPolicy::CreateFilter, which is now failing because our C interface is only calling into the block-based part of the FilterPolicy API after creating the BloomFilterPolicy configured as a "full filter."

**Comment by yiwu-arbug** [comment]
@pdillinger Can you clarify if the issue with `rocksdb_filterpolicy_create_bloom_format` is because it doesn't implement the `GetFilterBitsBuilder` and `GetFilterBitsReader` interfaces? Thanks.

**Comment by pdillinger** [comment]
> @pdillinger Can you clarify if the issue with `rocksdb_filterpolicy_create_bloom_format` is because it doesn't implement the `GetFilterBitsBuilder` and `GetFilterBitsReader` interfaces?

That's correct, along with the new GetBuilderWithContext. To properly wrap the built-in BloomFilterPolicy you have to override GetBuilderWithContext, and you don't have to override GetFilterBitsBuilder if you override GetBuilderWithContext.
