### ISSUE TITLE
Q: rename a column family?

### ISSUE THREAD

**Issue by dvdplm** [facebook/rocksdb#6130]
We have a database that uses the "default" column family along a bunch of other columns. We would like to simplify our API and therefore move the data in the "default" column to another column family. 
Is there a way to achieve this without a full dump/restore cycle? We want all other `n` columns left intact and the data in `default` to end up in column `n+1`; i.e. a "rename" operation of sorts. Hope that makes sense!

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev
