### ISSUE TITLE
FreeDeadColumnFamilies may release dbMutex, then races with another  FreeDeadColumnFamilies 

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#6150]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
In the body of FreeDeadColumnFamilies, dbMutex shall never be released.
```
// REQUIRES: DB mutex held
void ColumnFamilySet::FreeDeadColumnFamilies() {
  autovector<ColumnFamilyData*> to_delete;
  for (auto cfd = dummy_cfd_->next_; cfd != dummy_cfd_; cfd = cfd->next_) {
    if (cfd->refs_.load(std::memory_order_relaxed) == 0) {
      to_delete.push_back(cfd);
    }
  }
  for (auto cfd : to_delete) {
    // this is very rare, so it's not a problem that we do it under a mutex
    delete cfd;
  }
}
```

however, when calling delete cfd, in the destruction function, dbMutex may be released.
```
  if (super_version_ != nullptr) {
    // Release SuperVersion reference kept in ThreadLocalPtr.
    // This must be done outside of mutex_ since unref handler can lock mutex.
    super_version_->db_mutex->Unlock();
    local_sv_.reset();
    super_version_->db_mutex->Lock();
```
So if two FreeDeadColumnFamilies races, the line below may be re-entered.
```
for (auto cfd : to_delete) 
```

**Comment by riversand963** [comment]
Thanks @wolfkdy for reporting the issue. I think this is a legit bug. I wonder whether using a db-wide data structure to make sure that different threads will not add the same dead column family can solve the issue.

**Comment by wolfkdy** [comment]
@riversand963 , cool~, this case can be reproduced several times per day in our pre-product env.
If it helps, I can post the stack by rocksdb_debug.so. 
btw, I posted another issue, in rocksdb's google-groups. I wonder if you are interested to make a comment there.

**Comment by wolfkdy** [comment]
```
// REQUIRES: DB mutex held
void ColumnFamilySet::FreeDeadColumnFamilies() {
  while (true) {
    bool found = false;
    for (auto cfd = dummy_cfd_->next_; cfd != dummy_cfd_; cfd = cfd->next_) {
      if (cfd->refs_.load(std::memory_order_relaxed) == 0) { 
        delete cfd; 
        found = true;
        break;
      }    
    }    
    if (!found) {
      break;
    }    
  }
}
```
I think the code above can solve. despite the O(n*n) time-complexity.
I will try this in our test env.

**Comment by wolfkdy** [comment]
it's proved effective after several days' long-steady test.

**Comment by riversand963** [comment]
I just checked master, and `~ColumnFamilyData()` does not release db mutex now. Could you still reproduce it on master?

**Comment by wolfkdy** [comment]
@riversand963  this issue is probably related with https://github.com/facebook/rocksdb/commit/c2029f9716b3a4d2d7da687fd9fea6bb59bc50e4

I found master has merged the fix serveral days before.
