### ISSUE TITLE
Does unordered_write provide atomic read

### ISSUE THREAD

**Issue by cighao** [facebook/rocksdb#6160]
From the wiki page: https://github.com/facebook/rocksdb/wiki/unordered_write, it shows

> atomic writes: is no longer provided since the last_visible_seq which is fed to snapshot is larger than the sequence numbers of keys in upcoming insertion of the write batch to the memtable. Therefore each prefix of the write batch that is landed on memtables is immediately visible to the readers who read from that snapshot.

Does it mean unordered_write don't provide atomic read ?

But it also says:

> If the user can tolerate the relaxed guarantee they can enjoy the higher throughput of undered_write feature. Otherwise, they would need to implement their own mechanism to advance the snapshot sequence number to a value that is guaranteed to be larger than any in-flight write. One approach is to use TransactionDB configured with WritePrpared and two_write_queues which would still offer considerably higher throughput than vanilla rocksdb.

Does it mean unordered_write can still provide atomic read if we  use TransactionDB configured with WritePrpared  and two_write_queues?

**Comment by maysamyabandeh** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

unorderd_write specifically can be studied in the wiki and the blog post: https://rocksdb.org/blog/2019/08/15/unordered-write.html
