### ISSUE TITLE
in memory without ramfs or tmpfs

### ISSUE THREAD

**Issue by ekg** [facebook/rocksdb#618]
Is there a way to load the compressed tables into memory without using a tmpfs or ramfs?

**Comment by fyrz** [comment]
@ekg did you have a look at `MemEnv` ?

**Comment by ekg** [comment]
Is there a test case showing how to use it to open a db from disk? I
haven't found one and my attempts at getting it to work have failed.

**Comment by fyrz** [comment]
@ekg it`s a hacky way and i think it was also not the devs intention. But a possible way would be to use the `BackupableDB` to backup to a `MemEnv` which incorporates a virtual directory layout. After backing things up you can use the memory environment. Theoretically this should work, but i didnt test it.

**Comment by igorcanadi** [comment]
@ekg you can use `vmtcouch` command to preload your table into OS cache. You can even make them pinned in memory.

**Comment by ekg** [comment]
@igorcanadi Thanks, vmtouch seems to do the trick. However, as non-root I'm not sure I can use `mlock` to make large files sticky.

**Comment by sagar0** [comment]
Closing this issue as it is more than an year old. Please feel free to reopen if you think this issue is still relevant and/or has been closed in error.
