### ISSUE TITLE
Android Java: keyMayExist crashes when reading non UTF8 valid character

### ISSUE THREAD

**Issue by jurmous** [facebook/rocksdb#6183]
Using a keyMayExist on a key with a value with invalid UTF8 characters it crashes on Android.

In this case I stored a value which was an encoded number which was not meant to be represented as String.

### Expected behavior

No crash using keyMayExist with a non UTF8 valid value

### Actual behavior

On Android:
```
2019-12-14 19:15:49.948 4756-4756/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.190920.001/5891938:user/release-keys'
A/DEBUG: Revision: '0'
A/DEBUG: ABI: 'x86'
A/DEBUG: Timestamp: 2019-12-14 19:15:49+0100
A/DEBUG: pid: 4693, tid: 4730, name: roidJUnitRunner  >>> org.rocksdb.test <<<
A/DEBUG: uid: 10134
A/DEBUG: signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
A/DEBUG: Abort message: 'JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0x80
        string: '�'
        input: '<0x80>'
        in call to NewStringUTF
        from boolean org.rocksdb.RocksDB.keyMayExist(long, byte[], int, int, java.lang.StringBuilder)'
```

(On the JVM it works fine)

### Steps to reproduce the behavior

put a value of 0x80 in the database. Use keyMayExist to check if key exists. Then get the exception.

Use this project to compile for Android: 
https://github.com/marykdb/rocksdb-android

The git submodule can be changed to refer to different RocksDB commits.

**Comment by adamretter** [comment]
Hmm it would seem to me that `StringBuilder` is a poor choice to use for the value parameter in `keyMayExist`, as we would have to expect a unicode value. I will work on an alternative

**Comment by adamretter** [comment]
@jurmous I think this should solve the problem - https://github.com/facebook/rocksdb/pull/6186

In particular see `KeyMayExistTest#keyMayExistNonUnicodeString()`.
