### ISSUE TITLE
sst_dump seems having some problems

### ISSUE THREAD

**Issue by changhuilin** [facebook/rocksdb#624]
Hi, all.

I am trying to dump info from an SST file.
The key-value pairs are in the form 
"key-tttt-xxxx" : "val-tttt-xxxx" (xxxx is index numbers, starting from 0)

== 1 ==
However, for some files, I got assertion failure when I do

./sst_dump --command=raw --file=/path/to/file

It complains:
"sst_dump: ./db/dbformat.h:89: rocksdb::Slice rocksdb::ExtractUserKey(const rocksdb::Slice&): Assertion `internal_key.size() >= 8' failed."

Besides, "./sst_dump --command=scan ... "  works fine.

== 2 ==
Also, I tried to use SstFileReader class to dump the table, for example

```
SstFileReader sst_reader(sst_file, false, false);
sst_reader.DumpTable(dump_file);
```

But it had segmentation fault. With gdb, the backtrace is 

---

ToString (hex=true, this=<optimized out>) at ./include/rocksdb/slice.h:82
82          snprintf(buf, 10, "%02X", (unsigned char)data_[i]);
(gdb) bt
#0  ToString (hex=true, this=<optimized out>) at ./include/rocksdb/slice.h:82
#1  rocksdb::BlockBasedTable::DumpDataBlocks (this=this@entry=0x67e5a0,

```
out_file=out_file@entry=0x67d440) at table/block_based_table_reader.cc:1621
```
#2  0x00007ffff7ab4bea in rocksdb::BlockBasedTable::DumpTable (this=0x67e5a0,

```
out_file=0x67d440) at table/block_based_table_reader.cc:1522
```
#3  0x00007ffff7b6cb4d in rocksdb::SstFileReader::DumpTable (

```
this=this@entry=0x7fffffffd4d0, out_filename=...)
at util/sst_dump_tool.cc:105
```
#4  0x0000000000401ed7 in main (argc=<optimized out>, argv=<optimized out>)

```
at sst_dump.cc:24
```

---

Any idea why? 
I guess I have to understand more about the internal key/value representation before figuring out the causes.

Thanks!

**Comment by sagar0** [comment]
I hope you were able to figure out the rootcause. 
I am closing this issue as it is more than an year old. If you still need further help, please post to our dev group: https://www.facebook.com/groups/rocksdb.dev .
