### ISSUE TITLE
global seqnum should be applied before sorting a level's files

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#6245]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://www.facebook.com/groups/rocksdb.dev

Commit hash: 2d1670948752a54c9b67797c83e9fdb563ebd0b1 (Dec 17 2019)

### Steps to reproduce the behavior

```
$ rm -rf ./tmp && for i in $(seq 3) ; do ./ldb put k a --create_if_missing --db=./tmp ; done
$ echo "k ==> b" | ./ldb write_extern_sst ./tmp.sst --db=./tmp/
external SST file written to ./tmp.sst
$ ./ldb ingest_extern_sst ./tmp.sst --db=./tmp
external SST files ingested
$ ./ldb get k --db=./tmp
a
```

### Expected behavior

The repro sequence of commands should lead to `ldb get k` returning "b", i.e., the latest value written for key "k" via ingestion.

### Actual behavior

The repro sequence led to `ldb get k` returning "a", which is incorrect. If we iterate over the internal keys we can see the key with largest seqnum comes last for some reason.

```
$ ./ldb idump ./tmp.sst --db=./tmp
'k' seq:3, type:1 => a
'k' seq:2, type:1 => a
'k' seq:1, type:1 => a
'k' seq:4, type:1 => b
Internal keys in range: 4
```

Examining the manifest shows us why. The file containing `k@4` comes last, whereas it should come first. I believe this is due to not applying the global seqnum before sorting the files within a level.

```
./ldb manifest_dump --db=./tmp | head

--------------- Column family "default"  (ID 0) --------------
log number: 16
comparator: leveldb.BytewiseComparator
--- level 0 --- version# 1 ---
--- level 1 --- version# 1 ---
 10:794[3 .. 3]['k' seq:3, type:1 .. 'k' seq:3, type:1]
 7:794[2 .. 2]['k' seq:2, type:1 .. 'k' seq:2, type:1]
 4:794[1 .. 1]['k' seq:1, type:1 .. 'k' seq:1, type:1]
 21:845[4 .. 4]['k' seq:0, type:1 .. 'k' seq:0, type:1]
--- level 2 --- version# 1 ---
```

**Comment by yiwu-arbug** [comment]
@ajkr seems a serious issue. have you root-caused this one? thanks.

**Comment by yiwu-arbug** [comment]
Anyone have progress on fixing this?

**Comment by yiwu-arbug** [comment]
The issue is  introduced in #5649 (since rocksdb 6.5.2). The PR use 0 instead of assigned seqno in smallest_internal_key and largest_internal_key in `FileMetaData`, which passed to `VersionEdit` and `VersionBuilder`. cc @jeffrey-xiao @ajkr
