### ISSUE TITLE
No release of RocksJava 6.5.2

### ISSUE THREAD

**Issue by Myasuka** [facebook/rocksdb#6246]
RocksDB community has announced release of 6.5.2 recently. However, I cannot find the built release jar under https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni can someone help to release the official jar? @adamretter

**Comment by adamretter** [comment]
@Myasuka that is now available - https://search.maven.org/artifact/org.rocksdb/rocksdbjni/6.5.2/jar

Sorry for the delay.
