### ISSUE TITLE
RockDB plugin build in MariaDB is not reproducible

### ISSUE THREAD

**Issue by ottok** [facebook/rocksdb#6276]
Reproducible builds are important for software supply chain security. See https://reproducible-builds.org/

All packages in Debian are tested for reproducibility. Currently the latest MariaDB 10.3 build in Debian fails due to the build of the Mroonga, RocksDB and TokuDB plugins. See https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/mariadb-10.3.html

Based on the diffoscope data is seems RocksDB is embedding a random build ID in every build:
![image](https://user-images.githubusercontent.com/668724/72098881-127b4b80-3328-11ea-9323-90b0593f5d2e.png)

Could you please not do that, or alternative provide a build flag to turn it off?

Greetings,
MariaDB maintainer in Debian

**Comment by anand1976** [comment]
Can you set the NO_UPDATE_BUILD_VERSION env variable and see if it helps?

**Comment by ottok** [comment]
I added this env to the build of mariadb-10.3 in Debian in: https://salsa.debian.org/mariadb-team/mariadb-10.3/commit/5eb8f505b9861f0d374663d8f2c857c8b5d1cd09

Unfortunately this did not seem to solve it, nor can I even see in the output if it helped at all:
https://user-images.githubusercontent.com/668724/73429956-89af6880-4345-11ea-9976-36cdb9727d0b.png

**Comment by ottok** [comment]
Why was this issue closed? Is RocksDB at all in any release reproducible somewhere? I suggest to keep this open until somebody manages to build it so that reproducibility is proven.

**Comment by ottok** [comment]
Did you consider the text here?
![image](https://user-images.githubusercontent.com/668724/73599403-75d15580-4543-11ea-8439-273774c9894d.png)

`​rocksdb_build_git_date:​@2020-​01-​28·​08:​12:​28@`

Can this be disabled somehow?

**Comment by ottok** [comment]
Why was this issue closed? Is RocksDB at all in any release reproducible somewhere? I suggest to keep this open until somebody manages to build it so that reproducibility is proven.

**Comment by mdcallag** [comment]
AFAIK it was closed after you didn't reply to [a question](https://github.com/facebook/rocksdb/issues/6276#issuecomment-574370196)
