### ISSUE TITLE
Clarify tailing iterator semantics

### ISSUE THREAD

**Issue by tristanz** [facebook/rocksdb#628]
Are there any more details on how exactly tailing iterators behave?  The documentation says data "is not guaranteed to be seen."

I have a logging application where I are append to a topic (`key=topic:auto_increment`).  I'd like to tail this log.  I can keep track of the tail and when things are written.  I'm trying to find the most efficient way to tail this topic.   Am I right to assume that even if I create a tailing iterator, I cannot guarantee that I'll see the appended records even if I wait until `Put` returns to `Next`?  Is there a better approach than just using `Get` and manually iterating.

Docs:

> Not all new data is guaranteed to be available to a tailing iterator. Seek() or SeekToFirst() on a tailing iterator can be thought of as creating an implicit snapshot -- anything written after it may, but is not guaranteed to be seen.

https://github.com/facebook/rocksdb/wiki/Tailing-Iterator

**Comment by fyrz** [comment]
@tristanz that means if you use seek you are working on a snapshot which prevents by definition access to changes which happened after snapshot creation. If you use just next you are fine.

**Comment by tristanz** [comment]
@fyrz perfect, thanks.

**Comment by tristanz** [comment]
Ok, I'm actually still slightly confused by the semantics.  Is no `Seek()` safe?  In other words, do tailing iterators only allow you to iterate through the entire database?  I need to `Seek` to a known position  before tailing with `Next` calls.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by asad-awadia** [comment]
@fyrz if i cant seek - then i cant seekToFirst which is required to use an iterator - so how should i use a tailing iterator?
