### ISSUE TITLE
GetUpdatesSince writeBatchPtr is null

### ISSUE THREAD

**Issue by tpet** [facebook/rocksdb#6291]
### Expected behavior
writeBatchPtr contains valid WriteBatch pointer.
### Actual behavior
The pointer is null, even for a valid iterator.
### Steps to reproduce the behavior
See https://gist.github.com/tpet/b6da41911b46b5bbab870dc7822ac0a7 for complete example.

```c++
DB::Open(opts, name, &db);

WriteOptions write_opts;
db->Put(write_opts, "key1", "value1");
db->Put(write_opts, "key2", "value2");

SequenceNumber since(0);
std::unique_ptr<TransactionLogIterator> iter;
db->GetUpdatesSince(since, &iter);
for (; iter->Valid(); iter->Next())
{
    std::cout << iter->GetBatch().sequence << ": "
            << (iter->GetBatch().writeBatchPtr == nullptr ? "null" : "not null")
            << std::endl;
}
```

**Comment by anand1976** [comment]
You can only call ```iter->GetBatch()``` once per ```Next()```, since ```BatchResult::writeBatchPtr``` is a unique_ptr and is ```std::move```'d from the iterator. The following should work -
```
for (; iter->Valid(); iter->Next())
{
    BatchResult res = iter->GetBatch();
    std::cout << res.sequence << ": "
                << (res.writeBatchPtr == nullptr ? "null" : "not null")
                << std::endl;
}
```
