### ISSUE TITLE
SetDBOptions doesn't change max_background_jobs dynamically

### ISSUE THREAD

**Issue by Connor1996** [facebook/rocksdb#6298]
See https://github.com/facebook/rocksdb/blob/master/db/db_impl/db_impl.cc#L1010
`SetDBOptions` increase background threads only when `max_background_compactions` changes which is already deprecated.  Should increase background threads too when `max_background_jobs` changes.

**Comment by ltamasi** [comment]
Thanks for reporting @Connor1996 ! I've put out a PR that should fix this issue.
