### ISSUE TITLE
Java Basic Tunings

### ISSUE THREAD

**Issue by luigi-asprino** [facebook/rocksdb#6332]
Hi,

could you please provide Basic Tunings for the Java for the Java library (like those for c++ https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning)?

Cheers,
Luigi

**Comment by adamretter** [comment]
These settings are already available in the Java API. What seems to be missing?

**Comment by luigi-asprino** [comment]
Yes I know that are available, but it seems to me that a guide (a wiki page) for setting basic tunings from Java API is actually missing.

**Comment by adamretter** [comment]
@luigi-asprino The options in the C++ and Java APIs are the same apart from the casing of the options, in C++ it is lower-case with underscore, in Java it is snake case. Are you suggesting to just copy/paste the wiki page and change the case of the options?

**Comment by luigi-asprino** [comment]
Yes  :-) 
Thanks, this would be useful for basic users (like me).

**Comment by adamretter** [comment]
@luigi-asprino I don't see the value in directly duplicating content, as the two versions will invariably become out-of-sync. Perhaps it would be better to just add a paragraph to the top of the C++ wikipage to explain the differences in naming convention?

Would you like to contribute to that page?

**Comment by adamretter** [comment]
Closed by https://github.com/facebook/rocksdb/wiki/Tuning-RocksDB-from-Java
