### ISSUE TITLE
Add event listeners in jni

### ISSUE THREAD

**Issue by brary** [facebook/rocksdb#6343]
Can't find the event listeners in java api such as EventListener::OnFlushCompleted(). Can we get them added. Thanks.

**Comment by adamretter** [comment]
@brary Sure, I have started that previously here - https://github.com/adamretter/rocksdb/commits/java-api-enhancements-2

**Comment by brary** [comment]
Thanks @adamretter . In which version will they be released?

**Comment by brary** [comment]
Hey @adamretter . Will it possible to cherry-pick this change to a 5.x version if any release for such a version is planned?

**Comment by pdillinger** [comment]
> if any release for such a version is planned?

We don't generally back-port new features, so cherry-picking is up to you in your fork.

**Comment by adamretter** [comment]
@brary Well its not finished yet, when its finished it will go into the next minor release.

**Comment by adamretter** [comment]
Implemented in #7425
