### ISSUE TITLE
Document Installation on CentOS/RedHat Linux

### ISSUE THREAD

**Issue by skynet** [facebook/rocksdb#64]
It would be beneficial if you can add additional documentation for installing RocksDB on CentOS and other flavors of Linux that do not support apt-get. Example below:

Install zlib:
`yum install zlib`
`yum install zlib-devel`

Install bzip2:
`yum install bzip2`
`yum install bzip2-devel`

Install latest C++ compiler that supports C++ 11:
`yum install gcc47-c++`

Install snappy:
`wget https://snappy.googlecode.com/files/snappy-1.1.1.tar.gz`
`tar -xzvf snappy-1.1.1.tar.gz`
`cd snappy-1.1.1`
`./configure && make && make install`

Install gflags:
`wget https://gflags.googlecode.com/files/gflags-2.0-no-svn-files.tar.gz`
`tar -xzvf gflags-2.0-no-svn-files.tar.gz`
`cd gflags-2.0`
`./configure && make && make install`

**Comment by Akhilesh53** [comment]
Hi Team,
where to find the path for rocks db that has to be mentioned in the below build command.

`CGO_CFLAGS="-I/path/to/rocksdb/include" \`

we are not doing any separate installation for rocks db.

**Comment by adamretter** [comment]
@Akhilesh53 How did you install RocksDB?
