### ISSUE TITLE
Is tailing iterator compatible with delete range?

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#6413]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Use tailing iterator with delete range.

### Actual behavior

Encounter error "Range tombstones unsupported with ForwardIterator".

### Steps to reproduce the behavior

**Comment by siying** [comment]
The error indicates that it is not supported. It's the expected behavior then.

**Comment by huachaohuang** [comment]
OK, but I think the comment and document about tailing iterator should be updated.
