### ISSUE TITLE
Data corruption with concurrent manual compactions

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#6432]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Concurrent manual compactions should not cause data corruption.

### Actual behavior

Two concurrent manual compactions put overlapped SST files in the same level.

### Steps to reproduce the behavior

Run concurrent manual compactions with options:

```
CompactRangeOptions options;
options.change_level = true;
options.exclusive_manual_compaction = false;
```

The attached file contains a MANIFEST file and a related LOG file.
[rocksdb.tar.gz](https://github.com/facebook/rocksdb/files/4225381/rocksdb.tar.gz)

Here is the interesting part:

```
{"EditNumber": 30, "PrevLogNumber": 0, "NextFileNumber": 54, "LastSeq": 4168394, "DeletedFiles": [{"Level": 6, "FileNumber": 48}], "AddedFiles": [{"Level": 5, "FileNumber": 48, "FileSize": 49488577, "SmallestIKey": "'000000000000000040000000000100010008FFFFFFFFFFFFFFFE' seq:0, type:1", "LargestIKey": "'E903000000000000407A7A7A726C36345209755935763065000006EA0BA1B245D7D63F' seq:0, type:1"}], "ColumnFamily": 0}
{"EditNumber": 31, "PrevLogNumber": 0, "NextFileNumber": 55, "LastSeq": 4169989, "DeletedFiles": [{"Level": 4, "FileNumber": 53}], "AddedFiles": [{"Level": 5, "FileNumber": 54, "FileSize": 6591272, "SmallestIKey": "'000000000000000040000000000100010008FFFFFFFFFFFFFFFE' seq:4152213, type:1", "LargestIKey": "'E903000000000000407A7A77623649683609364C716E3636504509686F5049384C78620943317769754E636509615951305359626809363477783659647709565878306400000005EA0BA195D7F54371' seq:4100281, type:1"}], "ColumnFamily": 0}
{"EditNumber": 32, "PrevLogNumber": 0, "NextFileNumber": 55, "LastSeq": 4170053, "DeletedFiles": [{"Level": 5, "FileNumber": 48}, {"Level": 5, "FileNumber": 54}], "AddedFiles": [{"Level": 6, "FileNumber": 54, "FileSize": 6591272, "SmallestIKey": "'000000000000000040000000000100010008FFFFFFFFFFFFFFFE' seq:4152213, type:1", "LargestIKey": "'E903000000000000407A7A77623649683609364C716E3636504509686F5049384C78620943317769754E636509615951305359626809363477783659647709565878306400000005EA0BA195D7F54371' seq:4100281, type:1"}, {"Level": 6, "FileNumber": 48, "FileSize": 49488577, "SmallestIKey": "'000000000000000040000000000100010008FFFFFFFFFFFFFFFE' seq:0, type:1", "LargestIKey": "'E903000000000000407A7A7A726C36345209755935763065000006EA0BA1B245D7D63F' seq:0, type:1"}], "ColumnFamily": 0}
```

In "EditNumber": 30, file 48 is moved from level 6 to level 5 (because of a manual compaction with `change_level = true`). In "EditNumber": 31, file 54 is added to level 5, but file 54 is overlapped with file 48.

**Comment by ajkr** [comment]
I guess the L6->L5 for `change_levels=true` should prevent L4->L5s from running concurrently. It tries to do this as the `change_levels` compaction calls `PauseBackgroundWork()` prior to `ReFitLevel()`, which then executes the L6->L5. But `PauseBackgroundWork()` is ineffective at preventing manual compactions from running.

**Comment by huachaohuang** [comment]
@ajkr I agree with you. As a workaround, I disable concurrent manual compactions by setting `exclusive_manual_compaction = true` (default value), do you think this is enough to prevent this problem?

**Comment by huachaohuang** [comment]
Seems setting `exclusive_manual_compaction = true` is not enough, if `change_level = true`, it is still possible that one thread is running `ReFitLevel()` and another thread is running another manual compaction.
