### ISSUE TITLE
Decryption: Do any tools support it?

### ISSUE THREAD

**Issue by MrSynAckSter-zz** [facebook/rocksdb#6438]
Hello!

I am a security engineer working with a client's RockDB database. They have used the recently added encryption features. My question: Is it possible to decrypt the RockDB database? I have been given the proper key by the client, but it does not appear any of the tools support decryption.

How do you recommend I go about this?

**Comment by anand1976** [comment]
Yes, none of the tools support it at the moment. The RocksDB team doesn't have much experience with the encryption feature. Perhaps @ewoutp or @jsteemann might be able to help.

**Comment by jsteemann** [comment]
Currently the encryption/decryption is supported via passing in a special env.
Support for this hasn't been added to any of the bundled tools by me or @ewoutp to the best of my knowledge. So it indeed is unsupported by the tools.
I haven't worked with the tools myself much, so I am not able to comment on how much effort it is to add encryption/decryption support to them. Which tools do you consider most important?
