### ISSUE TITLE
read performance issue related to use_direct_reads

### ISSUE THREAD

**Issue by sherlockwu** [facebook/rocksdb#6448]
Hi there,

I have a question on read performance when using db_bench with use_direct_reads flag.

The database is filled by:
> ./db_bench --db=/mnt/optane/db --num_levels=6 --key_size=20 --value_size=1000 --cache_size=0 --compression_type=none --compression_ratio=1 --use_existing_db=0 --num=100000000 --threads=1 --wal_dir=/mnt/optane/wal --min_level_to_compress=-1 --write_buffer_size=134217728 --benchmarks=filluniquerandom --max_background_compactions=16 --max_background_flushes=1 -use_direct_io_for_flush_and_compaction -use_direct_reads --target_file_size_base=134217728 --max_bytes_for_level_base=1073741824

The Read benchmark is as follow:
> ./db_bench --db=/mnt/optane/db --num_levels=6 --key_size=20 --value_size=1000 --cache_size=17179869184 --compression_type=none --compression_ratio=1 --min_level_to_compress=-1  --write_buffer_size=134217728 --target_file_size_base=134217728 --max_bytes_for_level_base=1073741824 --max_background_compactions=16 --max_background_flushes=1 --duration=100 --benchmarks=readrandom --use_existing_db=1 --num=100000000 --threads=32 --wal_dir=/mnt/optane/wal  -use_direct_io_for_flush_and_compaction -use_direct_reads

### Expected behavior
Should be able to saturize the SSD(an Intel Optane SSD) throughput when the #threads is large(eg. 32)

### Actual behavior
After #threads >8, the performance does not scale, while the SSD throughput is not saturized:

**#threads = 4:** 
readrandom   :    25.796 micros/op 155056 ops/sec;  150.8 MB/s (3868999 of 3868999 found)
iostat: 

> avg-cpu:  %user   %nice %system %iowait  %steal   %idle
>            5.08    0.00    1.94    4.19    0.00   88.80
> 
> Device            r/s     w/s     rMB/s     wMB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
> nvme1n1       171780.00    0.00    758.61      0.00     0.00     0.00   0.00   0.00    0.01    0.00   0.00     4.52     0.00   0.01 100.10

**#threads = 8:**
readrandom   :      30.139 micros/op 265412 ops/sec;  258.2 MB/s (3318999 of 3318999 found)
iostat:

> avg-cpu:  %user   %nice %system %iowait  %steal   %idle
>            7.68    0.00    5.34    9.71    0.00   77.27
> 
> Device            r/s     w/s     rMB/s     wMB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
> nvme1n1       283360.00    0.00   1251.26      0.00     0.00     0.00   0.00   0.00    0.01    0.00   0.00     4.52     0.00   0.00 100.00

**#threads = 16:**
readrandom   :      59.887 micros/op 267132 ops/sec;  259.9 MB/s (1665999 of 1665999 found)
iostat :

> avg-cpu:  %user   %nice %system %iowait  %steal   %idle
>           10.95    0.00    4.21   31.02    0.00   53.82
> 
> Device            r/s     w/s     rMB/s     wMB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
> nvme1n1       287663.00    0.00   1270.26      0.00     0.00     0.00   0.00   0.00    0.04    0.00   0.00     4.52     0.00   0.00 100.00

As we may see, the performance does not scale after #threads > 8, and the disk is not fully utilized. We only observe <1300MB/s throughput, while the max throughput (4KB) is 2200MB/s (and also tested through fio) for that SSD.

One interesting thing is: we observe a better performance when not using use_direct_reads:
**#threads=16 without direct IO**
readrandom   :      54.417 micros/op 293965 ops/sec;  286.0 MB/s (1842999 of 1842999 found)
iostat: 

> avg-cpu:  %user   %nice %system %iowait  %steal   %idle
>           11.86    0.00    7.92   29.42    0.00   50.80
> 
> Device            r/s     w/s     rMB/s     wMB/s   rrqm/s   wrqm/s  %rrqm  %wrqm r_await w_await aqu-sz rareq-sz wareq-sz  svctm  %util
> nvme1n1       310374.00    0.00   2253.89      0.00     0.00     0.00   0.00   0.00    0.03    0.00   0.00     7.44     0.00   0.00 100.20

Could anyone try to help figure out why is this behavior? thanks

Kan

**Comment by anand1976** [comment]
I can't think of any bottleneck in RocksDB with use_direct_reads that doesn't apply when use_direct_reads is is not set. Maybe there's some difference in how the kernel handles buffered vs direct IO that's causing it? Did you try running fio both with and w/o direct IO and was there any throughput difference?

**Comment by chawlanikhil24** [comment]
Note: If the operations are asynchronous,  most probably it is a direct IO. 
Does RocksDB do asynchronous IO ?

**Comment by sherlockwu** [comment]
> I can't think of any bottleneck in RocksDB with use_direct_reads that doesn't apply when use_direct_reads is is not set. Maybe there's some difference in how the kernel handles buffered vs direct IO that's causing it? Did you try running fio both with and w/o direct IO and was there any throughput difference?

Hi @anand1976, thanks for your reply. 
I tested with fio, usng direct IO and buffered IO:
## fio script:
>[global]
name=fio-rand-read
ioengine=psync
direct=0
thread=1
buffered=0
size=10G
randrepeat=0
time_based
ramp_time=0
norandommap
refill_buffers
log_max_value=1
group_reporting
percentile_list=25.0:50.0:75.0:99.0
filename=/mnt/optane/test_file
[file1]
bs=4k
iodepth=1
numjobs=16
rw=randread
runtime=100


## performance:
direct = 1:  READ: bw=2174MiB/s (2280MB/s)
direct = 0: READ: bw=2264MiB/s (2374MB/s)
There is no significant difference here.

**Comment by sherlockwu** [comment]
> I can't think of any bottleneck in RocksDB with use_direct_reads that doesn't apply when use_direct_reads is is not set. Maybe there's some difference in how the kernel handles buffered vs direct IO that's causing it? Did you try running fio both with and w/o direct IO and was there any throughput difference?

@anand1976  Just curious, is there any rate_limit that could limit the lookup performance?  thanks

**Comment by anand1976** [comment]
@sherlockwu The rate_limit is applicable to both direct and buffered. The only other factor I can think of is the page cache. What's the amount of free memory? Its possible some of the reads in buffered mode are page cache hits.

**Comment by sherlockwu** [comment]
@anand1976 thanks for your reply.
free memory is around 20GB. The dataset tested is ~70GB if I remember correctly.

1) for the rate_limit: one thing we found is: direct and buffered has similar IOPS(~300k) to the device; the difference is the IO request size, buffered issue 8KB reads, while direct issue 4KB as we observed. Hence we suspect it's some rate_limit influencing the direct IO performance?

2) For the page cache: agree, some of the reads in buffered mode may hit in page cache; however, I think the main issue here is the low IO bandwidth usage with direct IO, right?

Thanks
Kan

**Comment by anand1976** [comment]
@sherlockwu I don't think its related to rate_limit, as rate_limit is only enforced for compaction reads. Its interesting that direct reads are 4KB whereas buffered is 8KB. Since the default data block size is 4KB and its not aligned, I'd expect direct reads to also be 8KB. But the numbers don't add up - if the IOPS is similar and ops/sec is also similar, then I suspect buffered is reading more from the device than necessary.

What's the alignment requirement for the SSD? Is it 4KB or 512B?

**Comment by sherlockwu** [comment]
> @sherlockwu I don't think its related to rate_limit, as rate_limit is only enforced for compaction reads. Its interesting that direct reads are 4KB whereas buffered is 8KB. Since the default data block size is 4KB and its not aligned, I'd expect direct reads to also be 8KB. But the numbers don't add up - if the IOPS is similar and ops/sec is also similar, then I suspect buffered is reading more from the device than necessary.
> 
> What's the alignment requirement for the SSD? Is it 4KB or 512B?

I see what you mean for the rate_limit now. 
What specifically should I report for the alignment requirement? the SSD im using is Intel Optane SSD 905P(960GB)

Kan

**Comment by anand1976** [comment]
@sherlockwu The value of /sys/block/nvme.../queue/logical_block_size

**Comment by sherlockwu** [comment]
@anand1976 it's 512

**Comment by anand1976** [comment]
That explains it. Buffered reads are always page aligned, whereas direct reads are aligned to logical_block_size. Hence, a ~4KB data block read would read 8KB from disk in buffered mode, and ~4608B (9 sectors) in direct read mode.

**Comment by sherlockwu** [comment]
> That explains it. Buffered reads are always page aligned, whereas direct reads are aligned to logical_block_size. Hence, a ~4KB data block read would read 8KB from disk in buffered mode, and ~4608B (9 sectors) in direct read mode.

Oh, I roughly get your point! To make it clear:
1) why direct mode need to 9 sectors to get a 4KB block?
2) I also use fio confirmed that: with 9 sectors random read, the maximum read bw I can get is 1300MB/s, that explains your point! thanks! 

Finally, do you have any suggestion on how should I handle this inefficient case? should I go for a larger logical block size (if that's possible?)? or is there anything I can configure in RocksDB?

Thanks
Kan

**Comment by anand1976** [comment]
> @anand1976 Oh, I roughly get your point! To make it clear:
> 
> 1. why direct mode need to 9 sectors to get a 4KB block?

In direct mode, the reads have to be a multiple of sector size, and since a 4KB block will typically not align exactly on a sector boundary, we would need 9 sectors to get a 4KB block.

> 2. I also use fio confirmed that: with 9 sectors random read, the maximum read bw I can get is 1300MB/s, that explains your point! thanks!
> 
> Finally, do you have any suggestion on how should I handle this inefficient case? should I go for a larger logical block size (if that's possible?)? or is there anything I can configure in RocksDB?

You can try setting ```block_align``` in ```BlockBasedTableOptions```. That option aligns each data block on a 4KB boundary by padding it. You may also have to tune ```block_size_deviation``` (since your value size is 1000, maybe set it to 30 or so). Be warned that this will increase the size of your DB.
