### ISSUE TITLE
Add support for setDestroyifexists()

### ISSUE THREAD

**Issue by hecenjie** [facebook/rocksdb#6459]
Hello!

We're using RocksJava as the underlying storage engine. In our scenario, we need to clear the existing DB before startup ( e.g. ensure data consistency in distributed environment by raft ), which can be implemented indirectly by first call `RocksDB.destroyDB()` and then open it. There may be more convenient ways to simplify this process, such as adding a `setDestroyifexists()` options ( just like `setErrorIfExists()`), which would make configuration more flexible without taking much code to implement.

**Comment by adamretter** [comment]
The Rocks Java API mostly follows the C++ API. If this was added to the C++ API, then we would expose it in the Java API.

**Comment by alanpaxton** [comment]
Hi @mrambacher @jay-zhuang is the OpenOptions idea going ahead ?

**Comment by adamretter** [comment]
@siying Would you be able to let us know if this is an option you think should be added to the C++ API?
