### ISSUE TITLE
Assertion failure in multi_processes_example

### ISSUE THREAD

**Issue by knizhnik** [facebook/rocksdb#6460]
Just following scenario described in multi_processes_example.c (running 
`./multi_processes_example 0` and `./multi_processes_example 1`) causes the following assertion failure:
```
multi_processes_example: db/version_set.cc:2389: void rocksdb::VersionStorageInfo::AddFile(int, rocksdb::FileMetaData*, rocksdb::Logger*): Assertion `false' failed.
Aborted (core dumped)
```

**Comment by ltamasi** [comment]
Thanks for reporting @knizhnik ! Which version of RocksDB are you using? Also, which process (primary or secondary) is hitting the assertion?

For the record, I tried but failed to reproduce this on master; however, I did hit a *different* assertion during the verification phase in the secondary process:

```
[process 2848236] Range_scan thread finished
57000!= 53000
multi_processes_example: multi_processes_example.cc:362: void RunSecondary(): Assertion `false' failed.
Aborted (core dumped)
```

Cc @riversand963

**Comment by knizhnik** [comment]
I am using the latest version of RocksDB from the master branch.
It was configured using "cmake -DWITH_GFLAGS=1 .." and build with gcc version 5.4.0 at Linux.
I launched primary node, wait few seconds and then start  secondary node and almost immediately it got this assertion failure.

**Comment by riversand963** [comment]
> Thanks for reporting @knizhnik ! Which version of RocksDB are you using? Also, which process (primary or secondary) is hitting the assertion?
> 
> For the record, I tried but failed to reproduce this on master; however, I did hit a _different_ assertion during the verification phase in the secondary process:
> 
> ```
> [process 2848236] Range_scan thread finished
> 57000!= 53000
> multi_processes_example: multi_processes_example.cc:362: void RunSecondary(): Assertion `false' failed.
> Aborted (core dumped)
> ```
> 
> Cc @riversand963

Same as @ltamasi .

**Comment by riversand963** [comment]
I think there is a potential bug in the case of switching to a new MANIFEST. If I change `ShouldCloseDB() { return true; }` to return false always, the tests can pass verification phase.
I am not happy with the current way of handling manifest switch, and will work on a fix.

**Comment by riversand963** [comment]
I think #7998 can fix the bug here, and verified no assertion failure.
