### ISSUE TITLE
Update db_bench description for unordered_write

### ISSUE THREAD

**Issue by rbrasga** [facebook/rocksdb#6467]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
```
DEFINE_bool(enable_pipelined_write, true,
            "Allow WAL and memtable writes to be pipelined");

DEFINE_bool(unordered_write, false,
            "**The writes to the main write queue in rocskdb goes through a different path**");
```
^ I'm not really sure what belongs there, even after reading: https://github.com/facebook/rocksdb/wiki/unordered_write

### Actual behavior
```
DEFINE_bool(enable_pipelined_write, true,
            "Allow WAL and memtable writes to be pipelined");

DEFINE_bool(unordered_write, false,
            "Allow WAL and memtable writes to be pipelined");
```
^ Is the description really identical for both enable_pipelined_write and unordered_write?

### Steps to reproduce the behavior
https://github.com/facebook/rocksdb/blob/master/tools/db_bench_tool.cc#L988

**Comment by ltamasi** [comment]
Thanks for reporting @rbrasga ! I've submitted a PR to fix this.

**Comment by rbrasga** [comment]
Great wording on the help! Thanks for the quick fix.
