### ISSUE TITLE
expose `GetCompactionReasonString()` publicly

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#6471]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Users of compaction event listeners should be able to get a human-readable string indicating the reason for a compaction.

### Actual behavior

Instead they get `CompactionJobInfo::compaction_reason`, which is a `CompactionReason` enum, with no way to translate it to something human-readable.

### Steps to reproduce the behavior
N/A

**Comment by ajkr** [comment]
Thanks for taking it. Let me know if you have any questions. Coincidentally we are in the same bootcamp class.

**Comment by cbi42** [comment]
Completed in #11778.
