### ISSUE TITLE
How to quickly submit in sync mode

### ISSUE THREAD

**Issue by ansjsun** [facebook/rocksdb#6485]
hi :
I want to use rocksdb in safe mode。Don't lose data when power is off，

so i use it like this , i need write batch by every document .
````
fn write(doc){
let mut option = WriteOptions::default();
write_options.disable_wal(false);
write_options.set_sync(true);
batch.add_document(doc);
rocksdb.write(batch, option)
}
````

But it's too slow。

I found wiki has group commit feature.What can I do to improve my speed.

example config group async max_time or commit_size .

there is some option Is it useful?

````
max_write_batch_group_size_bytes
rocksdb_wal_bytes_per_sync
````

**Comment by wolfkdy** [comment]
you said it's very slow, could you plz describe 
1) how large is each of your document?
2) how many tps(writes per second) can you get by doing pressure test.
3) your hardware, especially your disk, it's a spin-disk or an ssd disk, how many iops can your disk provide?
4) does your applicaion-level write rocksdb parallelly(multi-thread/thread-pool)

**Comment by ansjsun** [comment]
Thanks you for your reply。

1. each document size 0.2K.
2,3.tps use sas disk only 500-600, when use [chubaofs ](https://github.com/chubaofs/chubaofs) distributed file system it can 5000 tps。
4. yes I used multi-thread to write rocksdb . almost 100 threads

**Comment by wolfkdy** [comment]
@ansjsun  as you can see here https://github.com/facebook/rocksdb/blob/f5bc3b99d52f266724840ed01042d637440fe299/db/write_thread.cc#L407
yes! max_write_batch_group_size_bytes can control the amount of data of each submit group. 
wal_bytes_per_sync controls how much data at most each wal's sync submits to the fs. By using sata disk, I do believe tunning wal_bytes_per_sync larger helps.
However, from the "time aspect" , AFAIK, there is no parameter to control how long a write group will wait before commit. you can control commit-interval from application-level, holding data in one writebatch before commit for 1 second, and commit at once.

**Comment by ansjsun** [comment]
@wolfkdy I know ,  very very thanks  :)
