### ISSUE TITLE
[typo or bug] potentially wrong param for LoadTableHandlers

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#6486]
https://github.com/facebook/rocksdb/blob/afb97094ae8020b1fa659de341b632678855fe95/db/version_set.cc#L3808

I do believe here it is a typo.
why pass optimize_filters_for_hits as max_threads?

**Comment by riversand963** [comment]
Thanks @wolfkdy for reporting. I believe it has been resolved in https://github.com/facebook/rocksdb/commit/921cdd37e271bf8ecb16dab53a87cc7e360b0ea0
