### ISSUE TITLE
prevent MERGE->PUT conversion when `allow_ingest_behind=true`

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#6490]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Compaction must not convert MERGEs to PUTs when `allow_ingest_behind = true`. A converted PUT can incorrectly cover a future base value or merge ingested-behind into the bottom level.

### Actual behavior

I do not see anything preventing it. For example, see how the seqnum zeroing optimization is explicitly disabled when `allow_ingest_behind = true`: https://github.com/facebook/rocksdb/blob/e171a219d592b1bda9b654db126f04d4d834a815/db/compaction/compaction_iterator.cc#L672.

We should first write a test case to verify, though.

**Comment by manhhiep92** [comment]
Hi @ajkr I would like to look at this issue if no one is looking at it. Thanks!

**Comment by ajkr** [comment]
Hi @manhhiep92 , thanks for your interest! Yes, nobody is working on it currently. Assigned to you.
