### ISSUE TITLE
Expose WriteBatchWithIndex to C API

### ISSUE THREAD

**Issue by dgrnbrg** [facebook/rocksdb#650]
Hello, I'm interested in using WBWI from Rust, which requires adding support for it to the C API.

Thanks!

**Comment by adamretter** [comment]
@dgrnbrg I previously added support for WBWI to the Java API. I guess you could look at that work and the conventions of the existing C API.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
