### ISSUE TITLE
Corruption: Snappy not supported or corrupted Snappy compressed block contents

### ISSUE THREAD

**Issue by areddy1213** [facebook/rocksdb#6504]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

**Comment by adamretter** [comment]
@areddy1213 I think you might need to provide a bit more detail! Is this a problem you have encountered and if so, how and where? Which API etc etc.

**Comment by ramvadiv** [comment]
@areddy1213 - Not enough info/details to make any progress - will close out this Issue. Pls file a new issue when you have more details.
