### ISSUE TITLE
Alignment bug in XXH3 (possible segfault)

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#6508]
See https://github.com/Cyan4973/xxHash/issues/175#issuecomment-596254843

**Comment by easyaspi314** [comment]
The current `dev` branch of xxhash fixes this.

Other than that bugfix, the only changes are aesthetic or to xxhsum.

**Comment by pdillinger** [comment]
Ah, it looks like it only affects the streaming API, XXH3_createState/freeState (XXH3p_createState in our fork). I don't think we have any uses of that currently, but we should either remove it or apply fix. Remove it might be a good option if we want to minimize our use of our "preview" version of XXH3 in favor of eventually adopting newer version (where we aren't tied to schema).

**Comment by pdillinger** [comment]
https://github.com/Cyan4973/xxHash/pull/330/files

**Comment by easyaspi314** [comment]
`master` has been updated.
