### ISSUE TITLE
Rocksdb handle EINTR incorrectly

### ISSUE THREAD

**Issue by ChinaXing** [facebook/rocksdb#6509]
from the location of following:
https://github.com/facebook/rocksdb/blob/f5bc3b99d52f266724840ed01042d637440fe299/env/io_posix.cc#L277

the test of ferror shuold call clearerr before into next loop
if not so, empty file plus interrupt by signal will cause the loop can't break

this happened when we inject EINTR to write syscall. after cancel the injection.

thread's errno isn't be cleared, so this loop can't break.

**Comment by riversand963** [comment]
Thanks @ChinaXing for reporting. Would you be interested in contributing a fix for this to RocksDB master?

**Comment by riversand963** [comment]
Given #6609 is merged, I am closing this. Thanks @ChinaXing !
