### ISSUE TITLE
block checksum mismatch onSSD

### ISSUE THREAD

**Issue by SlientKiller** [facebook/rocksdb#6510]
HI, I'm new here. 
On SSD it always emit corruption unrecover error 'block checksum mismatch onSSD'!
recently, i'm testing performance of rocksdb. my key is as long as 20 chars, while value is between 50KB ~ 22MB. I'm tending to write 40GB data to db.
hower, when i do this test in a ssd.**it always emit block checksum mismatch** , i've tried many many times. ( SSD is 'samsung SSD 860 EVO 500GB')

but in hdd, it's all ok!

**Comment by riversand963** [comment]
I searched master, and "block checksum mismatch onSSD" does not seem a RocksDB error message, and RocksDB does not require underlying storage to be specific type (eg. HDD or SSD) as long as a file system (most often POSIX).
You can check `dmesg` to see whether it contains information about what's going on. Or you can do some simple write test *without* rocksdb on the SSD.

**Comment by riversand963** [comment]
Closing after long period of inactivity. The error is very likely a hardware issue given the description here. Let me know otherwise.
