### ISSUE TITLE
db_bench with multiple column families doesn't work

### ISSUE THREAD

**Issue by brary** [facebook/rocksdb#6548]
**I have an existing db with 3 column families which I want to benchmark, but seems like there is no option to open db with these column families.**

`[root@dummy-light-521805871-1-687835889 rocksdb]# ./db_bench --db=/data/db_bench_data/event-store --benchmarks="readrandom" --use_existing_db -compression_type="snappy"  -num_column_families=3
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
open error: Invalid argument: You have to open all column families. Column families not opened: anivia, hubble`

Then I tried creating a new db with multiple column families, 
`./db_bench --db=/data/test --benchmarks="fillseq,stats" -compression_type="snappy"  -num_column_families=3 --num=100000`

but when I tried to read this new db with `./db_bench --db=/data/test --benchmarks="readrandom" --use_existing_db -compression_type="snappy"  -num_column_families=3`
It throws this error below.

`WARNING: Assertions are enabled; benchmarks unnecessarily slow
------------------------------------------------
DB path: [/data/test]
db_bench: ./include/rocksdb/slice.h:165: void rocksdb::PinnableSlice::PinSlice(const rocksdb::Slice&, rocksdb::Cleanable*): Assertion `!pinned_' failed.
Received signal 6 (Aborted)
#0   /lib64/libc.so.6(gsignal+0x37) [0x7f825f13d1d7] ??	??:0	
#1   /lib64/libc.so.6(abort+0x148) [0x7f825f13e8c8] ??	??:0	
#2   /lib64/libc.so.6(+0x2e146) [0x7f825f136146] ??	??:0	
#3   /lib64/libc.so.6(+0x2e1f2) [0x7f825f1361f2] ??	??:0	
#4   ./db_bench() [0x6a861c] rocksdb::GetContext::SaveValue(rocksdb::ParsedInternalKey const&, rocksdb::Slice const&, bool*, rocksdb::Cleanable*)	/data/rocksdb/table/get_context.cc:292 (discriminator 1)	
#5   ./db_bench() [0x677244] rocksdb::BlockBasedTable::Get(rocksdb::ReadOptions const&, rocksdb::Slice const&, rocksdb::GetContext*, rocksdb::SliceTransform const*, bool)	/data/rocksdb/table/block_based/block_based_table_reader.cc:3284	
#6   ./db_bench() [0x58813e] rocksdb::Status::operator=(rocksdb::Status&&)	/data/rocksdb/./include/rocksdb/status.h:357	
#7   ./db_bench() [0x5af001] rocksdb::Status::operator=(rocksdb::Status&&)	/data/rocksdb/./include/rocksdb/status.h:358	
#8   ./db_bench() [0x4c1048] rocksdb::DBImpl::GetImpl(rocksdb::ReadOptions const&, rocksdb::Slice const&, rocksdb::DBImpl::GetImplOptions)	/data/rocksdb/db/db_impl/db_impl.cc:1601	
#9   ./db_bench() [0x4c16c7] rocksdb::DBImpl::Get(rocksdb::ReadOptions const&, rocksdb::ColumnFamilyHandle*, rocksdb::Slice const&, rocksdb::PinnableSlice*)	/data/rocksdb/db/db_impl/db_impl.cc:1468	
#10  ./db_bench() [0x45803c] rocksdb::Status::operator=(rocksdb::Status&&)	/data/rocksdb/./include/rocksdb/status.h:360	
#11  ./db_bench() [0x448312] rocksdb::Stats::Stop()	/data/rocksdb/tools/db_bench_tool.cc:1719 (discriminator 3)	
#12  ./db_bench() [0x5edc02] rocksdb::(anonymous namespace)::StartThreadWrapper(void*)	/data/rocksdb/env/env_posix.cc:1157	
#13  /lib64/libpthread.so.0(+0x7dc5) [0x7f826074bdc5] ??	??:0	
#14  /lib64/libc.so.6(clone+0x6d) [0x7f825f1ff76d] ??	??:0	
Aborted`

**Comment by riversand963** [comment]
Sorry for getting to this with a long delay. I can reproduce it, and will work on a fix #8154
