### ISSUE TITLE
Error (converted from warning) unused field comp_ when compiling

### ISSUE THREAD

**Issue by aaronbuchwald** [facebook/rocksdb#6549]
### Expected behavior
make shared_lib compiles without throwing any errors on MacOSX

### Actual behavior
make shared_lib throws an error "private field
      'icomp_' is not used" which is converted to be an error by the compiler options in the Makefile -Werror. 

### Steps to reproduce the behavior
clone and run make shared_lib

**Comment by pdillinger** [comment]
You just checked out master while it was broken. See #6547

**Comment by pdillinger** [comment]
(Master is still broken until #6547 is merged.)
