### ISSUE TITLE
Intermittent failures in DBCompactionTestWithParam.FlushAfterIntraL0CompactionCheckConsistencyFail

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#6550]
Failed on ppc64le here: https://travis-ci.org/github/facebook/rocksdb/jobs/663322463

> [ RUN      ] DBCompactionTestWithParam/DBCompactionTestWithParam.FlushAfterIntraL0CompactionCheckConsistencyFail/3
> db/db_compaction_test.cc:5064: Failure
> Expected: (pick_intra_l0_count.load()) > (0), actual: 0 vs 0

Similar failure in a Facebook internal test run on March 11 (x86_64 with db not on shm):

> [ RUN      ] DBCompactionTestWithParam/DBCompactionTestWithParam.FlushAfterIntraL0CompactionCheckConsistencyFail/1
> db/db_compaction_test.cc:5057: Failure
> Expected equality of these values:
>   10
>   NumTableFilesAtLevel(0)
>     Which is: 5

**Comment by pdillinger** [comment]
Related to #6061

**Comment by mrambacher** [comment]
@pdillinger Is this still an issue or should it now be closed?

**Comment by pdillinger** [comment]
> @pdillinger Is this still an issue or should it now be closed?

Still an issue. See #7477

**Comment by ajkr** [comment]
#7477 landed. It was my third change to deflake this test and the adjacent test with a similar name. I am not aware of any unsolved problems at this point, but we will see.
