### ISSUE TITLE
Snappy Directory not found

### ISSUE THREAD

**Issue by shersoni610** [facebook/rocksdb#6559]
I have installed Snappy on Ubuntu 18.04 using Synaptic Manager. Thereafter, I switched
WITH_SNAPPY = ON. However, while buidling CMake, I get the error:

Could NOT find snappy (missing: snappy_LIBRARIES snappy_INCLUDE_DIRS)
 Call Stack (most recent call first):

What should I do?

Thanks

**Comment by adamretter** [comment]
Take a look in `thirdparty.inc` to set paths etc
