### ISSUE TITLE
testharness lib

### ISSUE THREAD

**Issue by shersoni610** [facebook/rocksdb#6560]
Hello,

I get the following error while compiling the source code ob Ubuntu:

[ 47%] Built target rocksdb-shared
Scanning dependencies of target table_reader_bench
[ 47%] Building CXX object CMakeFiles/table_reader_bench.dir/table/table_reader_bench.cc.o
[ 47%] Linking CXX executable table_reader_bench
/usr/bin/ld: cannot find -ltestharness

What is the issue?

Thanks

**Comment by Phantomape** [comment]
looks like you r just missing this testharness library

**Comment by Phantomape** [comment]
however this lib is built by rocksdb itself，so you may want to check the output during compilation

**Comment by khngnathan** [comment]
same here

**Comment by zwkno1** [comment]
Same error:

cmake ../  -DWITH_GFLAGS=1 -DWITH_SNAPPY=1 -DWITH_JEMALLOC=1 -DWITH_ZLIB=1 -DWITH_LZ4=1 -DWITH_ZSTD=1 -DWITH_BZ2=1 -DCMAKE_BUILD_TYPE=Release

...
[ 98%] Building CXX object db_stress_tool/CMakeFiles/db_stress.dir/no_batched_ops_stress.cc.o
[ 98%] Linking CXX executable db_repl_stress
[ 98%] Built target db_repl_stress
[ 99%] Linking CXX executable filter_bench
[ 99%] Built target filter_bench
[ 99%] Linking CXX executable range_del_aggregator_bench
[ 99%] Built target range_del_aggregator_bench
[ 99%] Linking CXX executable memtablerep_bench
[ 99%] Built target memtablerep_bench
[ 99%] Linking CXX executable table_reader_bench
/bin/ld: cannot find -ltestharness
collect2: error: ld returned 1 exit status
make[2]: *** [table_reader_bench] Error 1
make[1]: *** [CMakeFiles/table_reader_bench.dir/all] Error 2

**Comment by zwkno1** [comment]
i fix it.
https://github.com/facebook/rocksdb/pull/7040
