### ISSUE TITLE
Reading fails

### ISSUE THREAD

**Issue by shersoni610** [facebook/rocksdb#6568]
Hello,

When I use Slice (instead of std::string) for key while reading the values I get segmentation 
fault. With std::string things works:

void write_data()
{
    boost::timer::auto_cpu_timer watch;

    int offset = 0;
    Status s;
    Slice  key;
    for( int i = 0; i < N; i++) {
        key = "v:" + to_string(i);
        std::string value = to_string( i+ offset);
        s = db->Put(WriteOptions(), key, value);
        assert(s.ok());
    }
    cout << "Writing over " << endl;
}

void read_data()
{
    boost::timer::auto_cpu_timer watch;
    std::string value;
    Status s;
    int index = 0;
    Slice key;
    for( int i = 0; i < N; i++) {
        key = "v:" + to_string(i);
        cout << key.ToString() << endl;
        s = db->Get(ReadOptions(), key, &value);
        assert(s.ok());
        index++;
    }
    cout << index << endl;
    cout << "Reading over " << endl;
}

What could be the error?

**Comment by pdillinger** [comment]
A Slice doesn't own memory. It only points to memory that must be tracked elsewhere. Using a temporary string (`"v:" + to_string(i)`) to initialize a Slice will result in the Slice pointing to memory that might be reclaimed / reused / invalid.
