### ISSUE TITLE
Question: RocksDB perf impact on same key update

### ISSUE THREAD

**Issue by bharatviswa504** [facebook/rocksdb#6595]
Hi,
I have a question, we use rocksdb in our project. I want to know if updating the same key multiple times like around 100's of times per sec will it have any perf impact on the rocksdb compaction. From my understanding it has perf impact on get operations. could anyone provide info on this kind of use case, and what kind of issues it can cause as DB size increases.

To give more info, we use ColumnFamilies, in one of the column family we have this kind of use case.

Thanks in advance.

**Comment by bharatviswa504** [comment]
cc @sagar0

**Comment by Phantomape** [comment]
As I see it, the question is more of how LSM works rather than how rocksdb works. Updating the same key 100's of times per sec turns into 100's of times writes into the memtable, so I wouldn't think that would be a big problem on compaction.

**Comment by ramvadiv** [comment]
Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
