### ISSUE TITLE
`block_decompress_time` times uncompressed block reads?

### ISSUE THREAD

**Issue by jkp** [facebook/rocksdb#6618]
https://github.com/facebook/rocksdb/blob/18cf0de64085b74388ba4df029ea8d7c83ec428d/table/block_fetcher.cc#L263

Is the perf context in the wrong place? It seems to capture both cases...even if compression is disabled?

**Comment by jkp** [comment]
Do you want a PR to fix it?

**Comment by mrambacher** [comment]
This was fixed by #6658
