### ISSUE TITLE
Import data to RocksDB using Spark partition

### ISSUE THREAD

**Issue by khs123** [facebook/rocksdb#6649]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
I have a trouble when i using spark partition to import data to RocksDB. I will briefly describe my problem as follows. I have the data stored as a parquet, I use spark to read all that data, converting the data of each line into avro records in the form of column: corresponding values. At that time, I used writebatch to write all the above data to Rocksdb in the form of key: value corresponding to key is id, value is data converted into avro. 
### Actual behavior
The problem starts here, the total number of parquet records is 21 million, however when I import into RocksDB the count data is lost 500 thousand records respectively. Because the write batch in RocksDB is Async, I guess that when writing to RocksDB, there is another thread to start writing, but when Spark Partition has finished its work, the thread written to RocksDB is still not completed. After that, Spark Partition is turned off so the thread write batch into RocksDB is also deleted, so the data has been lost. How can I control the thread to write to RocksDB on the Spark partition so I don't lose data?

### Steps to reproduce the behavior
```
val convertUDF: UserDefinedFunction = udf((col: Long) => {
      val packer = MessagePack.newDefaultBufferPacker()
      packer.packLong(col)
      packer.close()
      packer.toByteArray
    })
    var parquetFileDF: DataFrame = spark.read.
      parquet("/media/khanhdv/project/exam_rocksdb/rockdb_import/file/parquet/")
    parquetFileDF = parquetFileDF.withColumn("msg_pack_id",
      convertUDF(col("profile_facebook_id")))
    parquetFileDF.createOrReplaceTempView("sample")
    parquetFileDF = parquetFileDF.withColumn("avro_record",
      to_avro(struct(parquetFileDF.columns.map(column): _*)))
    parquetFileDF.orderBy(org.apache.spark.sql.functions.col("msg_pack_id").desc)
```
Code import
```
parquetFileDF.repartition(1).rdd.foreachPartition(rows => {
      var options = new Options()
        .setCreateIfMissing(true)
        .setDbLogDir("/tmp")
        .setMaxLogFileSize(4 * SizeUnit.MB)
        .setWalDir("/tmp")
        .setInfoLogLevel(InfoLogLevel.ERROR_LEVEL)
        .setWriteBufferSize(256 * SizeUnit.MB)
        .setMaxWriteBufferNumber(4)
        .setMaxBackgroundCompactions(16)
        .setCompressionType(CompressionType.ZLIB_COMPRESSION)
        .setCompactionStyle(CompactionStyle.UNIVERSAL)
        .prepareForBulkLoad()
      var db = RocksDB.open(options, "db")
      try {
        val batch = new WriteBatch(25000000)
        val writeOptions = new WriteOptions()

        rows.foreach(row => {
          val m = row.getValuesMap(row.schema.fieldNames)
          val packer = MessagePack.newDefaultBufferPacker()
          packer.packString(Json(DefaultFormats).write(m))
          packer.close()
          batch.put(row.getAs("msg_pack_id"),
            row.getAs("avro_record"))
          if (batch.count() == 10000) {
            db.write(writeOptions, batch)
            batch.clear()
          }
        })
        if (batch.count() > 0) {
          db.write(writeOptions, batch)
        }
      }
      catch {
        case x: RocksDBException => {
          println(x)
        }
        case x: Exception => {
          println(x)
        }
      }


    })
```

**Comment by adamretter** [comment]
AFAIK `db.write` is not async... So I am not sure the problem is as you assume it to be!

**Comment by khs123** [comment]
That is my entire code, you can see the problem is my face is?

**Comment by khs123** [comment]
Using db.flush(new FlushOptions()) to solve problem. I dont know why but should flush data into the db

**Comment by adamretter** [comment]
I can't help with your problem from the information that you have provided. Spark and Paraquet are outside of RocksDB. If you can reproduce the problem with purely RocksDB I could take a look for you...
