### ISSUE TITLE
readrandom return NotFound after fillrandom in db_bench

### ISSUE THREAD

**Issue by CaixinGong** [facebook/rocksdb#6664]
### Expected behavior
The command
`./db_bench --compression_type=none --num=100 --benchmarks=fillrandom,readrandom`
should returns

_fillrandom   :      74.900 micros/op 13304 ops/sec;    1.5 MB/s
readrandom   :       2.570 micros/op 358422 ops/sec;   22.2 MB/s **(100 of 100 found)**_

that is, all read option should returns ok.

### Actual behavior

_fillrandom   :      74.900 micros/op 13304 ops/sec;    1.5 MB/s
readrandom   :       2.570 micros/op 358422 ops/sec;   22.2 MB/s **(56 of 100 found)**_

Many read options returns NotFound.

### Steps to reproduce the behavior
From version v6.2 to the update-to-date code, run the following command
`./db_bench --compression_type=none --num=100 --benchmarks=fillrandom,readrandom`

**Comment by ajkr** [comment]
I think the behavior you want is provided by `filluniquerandom`, not `fillrandom`. In `fillrandom` some keys might be written multiple times while other keys are written zero times.

**Comment by CaixinGong** [comment]
The behavior of db_bench is always 
fillrandom : 74.900 micros/op 13304 ops/sec; 1.5 MB/s
readrandom : 2.570 micros/op 358422 ops/sec; 22.2 MB/s (100 of 100 found)

From V6.2, the bug occurs.

**Comment by CaixinGong** [comment]
pull request: https://github.com/facebook/rocksdb/pull/6665

**Comment by ajkr** [comment]
Oh ok, understood now. The sequence of keys we generate for writes should be the same as the sequence we generate for reads, given the same generator seed and other parameters. Thanks for the PR.
