### ISSUE TITLE
A problem in `MakeInputIterator()`

### ISSUE THREAD

**Issue by cighao** [facebook/rocksdb#6667]
For function `MakeInputIterator()` in  `version_set.cc`

![image](https://user-images.githubusercontent.com/10767282/78791665-d86a2600-79b8-11ea-87ad-1b11e4b9daaa.png)

when call `NewIterator()`, the `level` parameters should be that which level `*flevel->files[i].file_metadata` belongs to. But the variable `which` is only the index. `which` value is 0, 1, 2,3..., it does not mean level number. The level number should be `c->level(which)`

Could you please check that? Is it my misunderstanding?

**Comment by wolfkdy** [comment]
It seems a dangerous typo, I looked deeper into the code to see how **which** (the level param) affects NewIterator, it seems currently, this param is not used in the following process.
