### ISSUE TITLE
[Refine] Such a big struct is created everytime calling GetFromBatch

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#6683]
https://github.com/facebook/rocksdb/blob/66a95f0fac3066aa6f1ac4cda3a844f49f6977a2/utilities/write_batch_with_index/write_batch_with_index.cc#L769

**Comment by wolfkdy** [comment]
perhaps related to https://github.com/facebook/rocksdb/issues/6677
If we can derive DBOptions from ImmutableDBOptions, then this cost can be eliminated.

**Comment by siying** [comment]
Good finding. Is it true that only statistics, env and logger are needed under it? If that is the case, maybe we can refine the argument passing from using ImmutableDBOptions to a smaller special struct.

**Comment by mrambacher** [comment]
This issue could be solved in a few different ways.  One way would be to make a smaller structure, but how do you decide what to put in it and where to use it?  There seems to be a lot of different places where an ImmutableDBOptions is used for just a few elements.

Another way would be to move the Mutable and Immutable structs into the public API and make DBOptions inherit from it.  Then the copy could be done away with altogether as a DBOptions would be an ImmutableDBOptions.

**Comment by mrambacher** [comment]
@wolfkdy Are you making any changes in this area currently?  I am looking at another issue in this area currently and fix this at the same time.

**Comment by wolfkdy** [comment]
@mrambacher  currently I'm not focusing on this area. Please move on.
