### ISSUE TITLE
Build fails due to unused argument for systems that don't support O_CLOEXEC

### ISSUE THREAD

**Issue by tiden0614** [facebook/rocksdb#6691]
The rocks compilation fails because my system doesn't support O_CLOEXEC:

```
env/fs_posix.cc:117:48: error: unused parameter 'options' [-Werror=unused-parameter]
int cloexec_flags(int flags, const EnvOptions* options) {
```

The reason is that the usage of that argument is defined in a macro if branch in [env/fs_posix.cc](https://github.com/facebook/rocksdb/blob/a9d168cfd7f40b8d6ed8b3ab29d155c4e5c63c13/env/fs_posix.cc#L117), and when that branch evaluates to false, the usage is gone.

```c++
int cloexec_flags(int flags, const EnvOptions* options) {
  // If the system supports opening the file with cloexec enabled,
  // do so, as this avoids a race condition if a db is opened around
  // the same time that a child process is forked
#ifdef O_CLOEXEC
  if (options == nullptr || options->set_fd_cloexec) {
    flags |= O_CLOEXEC;
  }
#endif
  return flags;
}
```

We can apply a simple fix to this function by putting the whole function definition into the macro, something like this:

```c++
#ifdef O_CLOEXEC
int cloexec_flags(int flags, const EnvOptions* options) {
  // If the system supports opening the file with cloexec enabled,
  // do so, as this avoids a race condition if a db is opened around
  // the same time that a child process is forked
  if (options == nullptr || options->set_fd_cloexec) {
    flags |= O_CLOEXEC;
  }
#else
int cloexec_flags(int flags, const EnvOptions* /*options*/) {
#endif
  return flags;
}
```

I can submit a PR to fix this bug if you guys like the proposal.

### Expected behavior
Compilation should succeed on systems that do not support O_CLOEXEC.

### Actual behavior
Compilation fails on systems that do not support O_CLOEXEC.

### Steps to reproduce the behavior
Build project on a system that doesn't support O_CLOEXEC.

**Comment by cheng-chang** [comment]
Fixed in https://github.com/facebook/rocksdb/pull/6695
