### ISSUE TITLE
make usage of gtest optional 

### ISSUE THREAD

**Issue by gocarlos** [facebook/rocksdb#6725]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

I can compile rocksdb together with my application and tests

### Actual behavior

I cannot due to the fact that rocksdb is using a vendored version of gtest which is not optional e.g. not even without tests

### Steps to reproduce the behavior

rm -rf build
mkdir build
cd build
cmake ..  -DWITH_TESTS=OFF
make
-> expected to not need `gtest/gtest.h` header

# how to possible fix this

* make gtest optional (preferred)
* make gtest mandatory but do a find_package as with gflags etc. instead of vendoring gtest

**Comment by ajkr** [comment]
It looks possible now, just need to set a bunch of options...
```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_TESTS=OFF -DWITH_BENCHMARK_TOOLS=OFF -DWITH_TOOLS=OFF
$ make VERBOSE=1 -j48
```
The above does not include anything gtest related.
