### ISSUE TITLE
Crash when using BlockBasedTableConfig()

### ISSUE THREAD

**Issue by unoexperto** [facebook/rocksdb#6729]
### Expected behavior

I'm on RocksDB JNI 6.7.3

I'm trying to use Partitioned Index Filters according to [this](https://github.com/facebook/rocksdb/wiki/Partitioned-Index-Filters) description using following options.

```java
ColumnFamilyOptions()
        .setBottommostCompressionType(CompressionType.ZSTD_COMPRESSION)
        .setCompressionType(CompressionType.ZSTD_COMPRESSION)
        .setComparator(BuiltinComparator.REVERSE_BYTEWISE_COMPARATOR)
        .setTableFormatConfig(
                BlockBasedTableConfig()
                        .setIndexType(IndexType.kTwoLevelIndexSearch)
                        .setFilterPolicy(BloomFilter(10.0, false))
                        .setPartitionFilters(true)
                        .setBlockSize(4096)
                        .setCacheIndexAndFilterBlocks(true)
                        .setPinTopLevelIndexAndFilter(true)
                        .setCacheIndexAndFilterBlocksWithHighPriority(true)
                        .setPinL0FilterAndIndexBlocksInCache(true)
        )
        .setWriteBufferSize(512 * SizeUnit.MB)
```

### Actual behavior and Steps to reproduce the behavior

Crash the moment we ingested volume defined in `setWriteBufferSize` option.
[hs_err_pid17313.log](https://github.com/facebook/rocksdb/files/4496582/hs_err_pid17313.log)

At first I thought it's related to Partitioned Index Filters but turned out it's crashing only when I use ZSTD and `BlockBasedTableConfig()`. So following options will cause crash as well (after ingesting default 64MB of data)

```java
ColumnFamilyOptions()
        .setCompressionType(CompressionType.ZSTD_COMPRESSION)
        .setTableFormatConfig(BlockBasedTableConfig())
```

**Comment by ltamasi** [comment]
@adamretter Do you have any suggestions/ideas what might be the problem here?

**Comment by adamretter** [comment]
There is another issue about zstd and bottom most compression. Could this be the same thing?

**Comment by unoexperto** [comment]
@adam-singer It crashes without `setBottommostCompressionType` option as well.

I'd like to provide more information but I'm no longer able to compile rocksdbjni. It used to work before. Could you please advise? Here is how I do it:

```
export JAVA_HOME=/usr/lib/jvm/jdk-13.0.2/
PORTABLE=1 DEBUG_LEVEL=2 make -j8 rocksdbjavastatic
```

I get following error

```
cd java;jar -cf target/rocksdbjni-6.7.3-linux64.jar HISTORY*.md
cd java/target;jar -uf rocksdbjni-6.7.3-linux64.jar librocksdbjni-linux64.so
cd java/target/classes;jar -uf ../rocksdbjni-6.7.3-linux64.jar org/rocksdb/*.class org/rocksdb/util/*.class
/usr/bin/bash: line 0: cd: java/target/classes: No such file or directory
org/rocksdb/*.class : no such file or directory
org/rocksdb/util/*.class : no such file or directory
java.io.FileNotFoundException: ../rocksdbjni-6.7.3-linux64.jar (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:155)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:360)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1680)
make: *** [Makefile:1947: rocksdbjavastatic] Error 1
```

File `./target/rocksdbjni-6.7.3-linux64.jar` is present.

**Comment by unoexperto** [comment]
@adam-singer It crashes without `setBottommostCompressionType` option as well.

I'd like to provide more information but debug version crashes for me with missing symbol. Could you please advise? Here is how I do it:

```
export JAVA_HOME=/usr/lib/jvm/jdk-13.0.2/
PORTABLE=1 DEBUG_LEVEL=2 make -j8 rocksdbjavastatic
```

but in runtime I'm getting this exception

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni11354650880302275487.so: /tmp/librocksdbjni11354650880302275487.so: undefined symbol: _ZTIN7rocksdb6LoggerE
```

What am I missing ?

**Comment by mitchelkuijpers** [comment]
Hi we are running in the same problem, as soon as i configure a `BlockBasedTableConfig` the application starts crashing, it does not matter if I actually configure it or not. Did you manage to fix this @unoexperto ?

**Comment by mitchelkuijpers** [comment]
I fixed it by changing the BottommostCompressionType to `ZLIB`

**Comment by unoexperto** [comment]
Nope, I had to postpone using `BlockBasedTableConfig`. @adam-singer Adam, could we please have some love for this issue? I suspect it might be some typo-kind of bug, but I wasn't sure to configure CLion to debug native library with Java executable.

**Comment by koldat** [comment]
I think it can be same as #6971 and #5496

Mitigation with: blockConfig.setVerifyCompression(false);

Please try and if it helps then @adamretter we should change the default (same as in C++) - see my issue for details

**Comment by mitchelkuijpers** [comment]
Awesome thank you for the suggestion @koldat, this fixes the issue for us :+1:
