### ISSUE TITLE
no member named 'NewBloomFilterPolicy' in namespace 'rocksdb'

### ISSUE THREAD

**Issue by mdesilva** [facebook/rocksdb#6738]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

NewBloomFilterPolicy function is valid

### Actual behavior

Even when using namespace rocksdb, NewBloomFilterPolicy does not exist.

**Comment by ltamasi** [comment]
`NewBloomFilterPolicy` is declared in `rocksdb/filter_policy.h`. You would need to `#include` that file in order to be able to use the method.

**Comment by mdesilva** [comment]
Thank you. How can I determine what files to import for specific functions on my own ? I am new to C++

**Comment by ltamasi** [comment]
Well, you can simply search for the file under `include/` that contains the declaration of the class, method, etc. you would like to use.
