### ISSUE TITLE
Rocksdblib cannot build completed in json_document.cc source code.

### ISSUE THREAD

**Issue by rchatsiri** [facebook/rocksdb#674]
That attach log file with error in build step. Visual Studio 2013 (Version 12) cannot find `json_document.cc` in folder of project, but  i see usually all file depend on folder such as  `E:\rocksdb\include\rocksdb\utilities\json_document.h` and `rocksdb\utilities\document\json_document.cc`. 

Why VC++ 2013 represent an error cannot read file from folder when build all project? Follow an fatal error below.

```
3>e:\workspacecpp\rocksdb\utilities\document\json_document.cc(592): fatal error C1001: An internal error has occurred in the compiler.
```

If Rocksdblib was built only step, Project throws an error as below.

```
2>  rocksdblib.dir\Debug\document_db.obj 
2>  rocksdblib.dir\Debug\json_document.obj 
2>rocksdblib.dir\Debug\json_document.obj : fatal error LNK1136: invalid or corrupt file
2>
2>Build FAILED.
2>
2>Time Elapsed 00:03:35.20
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========
```

2>Time Elapsed 00:00:00.12
3>------ Build started: Project: rocksdblib, Configuration: Debug x64 ------
3>Build started 26/7/2558 19:37:55.
3>InitializeBuildStatus:
3>  Touching "rocksdblib.dir\Debug\rocksdblib.tlog\unsuccessfulbuild".
3>CustomBuild:
3>  Building Custom Rule E:/workspacecpp/rocksdb/CMakeLists.txt
3>  CMake does not need to re-run because E:\workspacecpp\rocksdb\buildwin\CMakeFiles\generate.stamp is up-to-date.
3>  Generating ../util/build_version.cc
3>ClCompile:
3>  write_batch_with_index_internal.cc
3>  write_batch_with_index.cc
3>  db_ttl_impl.cc
3>  optimistic_transaction_db_impl.cc
3>  optimistic_transaction_impl.cc
3>  spatial_db.cc
3>  redis_lists.cc
3>  uint64add.cc
3>  put.cc
3>  stringappend2.cc
3>  stringappend.cc
3>  leveldb_options.cc
3>  geodb_impl.cc
3>  flashcache.cc
3>  json_document_builder.cc
3>  json_document.cc
3>  document_db.cc
3>  checkpoint.cc
3>  backupable_db.cc
3>  xxhash.cc
3>  Generating Code...
3>e:\workspacecpp\rocksdb\utilities\document\json_document.cc(592): fatal error C1001: An internal error has occurred in the compiler.
3>  (compiler file 'f:\dd\vctools\compiler\utc\src\p2\ehexcept.c', line 956)
3>   To work around this problem, try simplifying or changing the program near the locations listed above.
3>  Please choose the Technical Support command on the Visual C++ 
3>   Help menu, or open the Technical Support help file for more information
3>
3>Build FAILED.
3>
3>Time Elapsed 00:00:31.60
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Thank in advance, 
R.Chatsiri

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
