### ISSUE TITLE
Undefined behavior (maybe crash?) in MultiGet

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#6745]
#6483 from @hliu18 adds a 'timestamps' parameter to MultiGet. There appears to be UB in the DBImpl::MultiGet implementation taking a num_keys parameter.

https://github.com/facebook/rocksdb/blob/4cbc19d2a1da1a44775f27c2d167a0d8da0fd9f5/db/db_impl/db_impl.cc#L1999

If 'timestamps' is nullptr, as in the call up just a bit in the code, then this line is doing pointer arithmetic on nullptr, which is technically UB but if never used or compared to nullptr, then probably no crash or logic error in practice.

TBD whether this can cause a crash or logic error

**Comment by hliu18** [comment]
Good catch. I'll create a PR to fix this.

**Comment by hliu18** [comment]
created PR #6747.
