### ISSUE TITLE
Support compiling benchmarks in release mode for CMake (table_reader_bench depends on testharness)

### ISSUE THREAD

**Issue by xkszltl** [facebook/rocksdb#6769]
I'm using CMake to build RocksDB.
AFAIK RocksDB unit tests only support Debug build.

However the benchmark tool also relies on the test lib, as shown here:
https://github.com/facebook/rocksdb/blob/27e593fbe10efa5a562ca79b1939ffb69d25163f/CMakeLists.txt#L1159

Is this expected?
I thought benchmark only make sense in Release build.

**Comment by pdillinger** [comment]
Those of us using make can just use make DEBUG_LEVEL=0. table_reader_bench currently depends on test::PerThreadDBPath. Feel free to contribute if you can help to fix this. This doesn't really affect Facebook.

**Comment by mrambacher** [comment]
I no longer see this issue.  It was most likely fixed as part of #6660
