### ISSUE TITLE
Reading LevelDB files

### ISSUE THREAD

**Issue by OverlordQ** [facebook/rocksdb#677]
So judging from previous blog posts[1] and a conversation on twitter[2], I'm lead to believe that I should be able to read in a leveldb and begin working with it with rocks. However, I've noticed the first issue in doing this is that rocks is looking for sst files when leveldb is using ldb files.

`Can't access /27799377.sst: IO error: /path/goes/here/27799377.sst: No such file or directory`

The second issue, if I just go "Sure, i'll just rename them" is that it generates lots of warnings processing the files[3].

So is it generally possible to migrate/move/dump/load/whatever this existing leveldb into rocksdb without having to do the heavy processing that generated the initial database.

1 - http://rocksdb.org/blog/1811/migrating-from-leveldb-to-rocksdb-2/
2 - https://twitter.com/OverlordQ/status/626887860944248832
3 - http://pastebin.com/5quBh96f

**Comment by siying** [comment]
@OverlordQ how did you open levelDB database using RocksDB? Can you share your statement to open it?

**Comment by OverlordQ** [comment]
Not using rocksdb directly, using a python wrapper[1] around it. The leveldb code was utilizing plyvel[2]. The only options passed to either DB open was setting create_if_missing to True. If need be, I can probably try to put together a pure C++ repro case.

1 - http://github.com/stephan-hof/pyrocksdb.git
2 - https://plyvel.readthedocs.org/en/latest/

**Comment by siying** [comment]
It's probably because LevelDB renamed file names from "*.sst" to "*.ldb" and rocksDB is not yet recognize them. We should add the support. In the mean time, do you mind trying to rename all the "XXX.ldb" to "XXX.sst" and see whether you can open it?

**Comment by OverlordQ** [comment]
Running the `simple_example.cc` against the leveldb results in [this](http://sprunge.us/XNIG) LOG output.

**Comment by siying** [comment]
@OverlordQ yes, I confirmed that you are right and they cannot be opened. The only way for now to make it work is to manually rename all those xxxxx.ldb files to xxxx.sst, before opening it.

**Comment by OverlordQ** [comment]
Aside from that, it's safe to ignore the `Unable to load table properties for file --- NotFound:` and other warnings until all the leveldb files get compacted into rocks files?

**Comment by siying** [comment]
@OverlordQ "Unable to load table properties for file" is OK.

**Comment by OverlordQ** [comment]
Just of note, once the DB is loaded and operations begin on it, a slightly different but similar warning appears:

`Cannot find Properties block from file.`

**Comment by siying** [comment]
@OverlordQ that should be fine too. Did you see the data of the DB correct?

**Comment by OverlordQ** [comment]
Just to follow up, yes data reads fine, it's just when copying the DB from leveldb nodes it requires the extra manual step of renaming all the files from .ldb to .sst. It then gives the 'properties' errors reported above until those particular files get 'rocksified'

**Comment by liewegas** [comment]
Note that there is a unit test in db_test.cc (DBTest.SSTsWithLdbSuffixHandling) that pretends to verify that this works, but the test is flawed--it never causes rocksdb to read the .ldb files.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.

**Comment by folex** [comment]
> Note that there is a unit test in db_test.cc (DBTest.SSTsWithLdbSuffixHandling) that pretends to verify that this works, but the test is flawed--it never causes rocksdb to read the .ldb files.

Seems like it's still a trouble, and `.ldb` files aren't working. 

I can see [there's some logic](https://github.com/facebook/rocksdb/blob/e1c468d16ff3400508570fbbed4d4b01f3505471/db/db_impl/db_impl.cc#L3138-L3140) for handling .ldb files, and it seems like e.g., `rocksdb_ldb check_consistency` works on LevelDB database, but `rocksdb_ldb scan` – doesn't.

```shell
$ tree -L 1 blockstore.db
blockstore.db
├── 000002.ldb
├── 000010.ldb
├── 000011.ldb
├── 000013.ldb
├── 000031.sst
├── 000033.log
├── CURRENT
├── CURRENT.bak
├── IDENTITY
├── LOCK
├── LOG
...
```
```shell
rocksdb_ldb --db=$(pwd)/blockstore.db checkconsistency
OK
```
```shell
$ rocksdb_ldb --db=$(pwd)/blockstore.db scan
Failed: IO error: No such file or directoryWhile open a file for random read: .../blockstore.db/000010.sst: No such file or directory
```
```shell
$ brew info rocksdb
rocksdb: stable 6.1.2 (bottled)
```

**Comment by siying** [comment]
Yes, it's likely still to be the case. And the code might have moved on so it is harder to fix. If you are interested, you can try to add a helper function to migrate a LevelDB directory to RocksDB.

**Comment by amery** [comment]
apologies for commenting on such old ticket, but.. can rocksdb (ro) and leveldb (rw) share files in 2024?
