### ISSUE TITLE
 could not determine kind of name for C.rocksdb_backup_engine_create_new_backup_flush

### ISSUE THREAD

**Issue by Lochanahasith** [facebook/rocksdb#6779]
When I build the GoLang project, it gives this error 
# github.com/tecbot/gorocksdb
vendor/github.com/tecbot/gorocksdb/backup.go:112:2: could not determine kind of name for C.rocksdb_backup_engine_create_new_backup_flush

I'm using the Go version - 1.12.17 and rocksdb v5.11.3 
Is there a way to solve this issue ?

**Comment by ajkr** [comment]
The GoLang project's README.md says it works on RocksDB 5.16+. BTW, that project isn't maintained by the RocksDB team. Consider creating an issue in their repo if you have more questions.
