### ISSUE TITLE
Discrepancy between c.h and c.cc

### ISSUE THREAD

**Issue by domsj** [facebook/rocksdb#680]
In https://github.com/facebook/rocksdb/commit/384400128f6eb9f1111f41efd9712c6879411cfc
rocksdb_options_set_no_block_cache and rocksdb_options_set_block_size_deviation are removed from the implementation but not from the .h.

(Noticed this while working on my ocaml rocksdb binding.)

**Comment by lambdaburrito** [comment]
good spot! i just encountered this while working on a binding for node.js

**Comment by igorcanadi** [comment]
Good catch @domsj ! I created a diff: https://reviews.facebook.net/D47721
