### ISSUE TITLE
[Question] Is rocksdb capable to work on billions of keys?

### ISSUE THREAD

**Issue by beef9999** [facebook/rocksdb#6812]

**Comment by ajkr** [comment]
Yes, it is commonly done, and typically works until you run out of space. Although you may need to set some non-default config options to avoid running out of memory first; see https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide. In particular, the "spinning disk" section might be useful as it makes suggestions that are generally applicable to large DBs.
