### ISSUE TITLE
release rocksdbjni 3.13.0

### ISSUE THREAD

**Issue by anagav** [facebook/rocksdb#683]
Hi,

What is the timeline of publishing rocksdb-jni 3.13.0 to maven? I see there is a java release today.

https://github.com/facebook/rocksdb/commit/102ac118b26a8906f95f57975b6ae1f3a17c30c5

**Comment by adamretter** [comment]
@anagav I can try and take a look at this perhaps by the end of the week.

**Comment by anagav** [comment]
cool.. thanks @adamretter

**Comment by Gadreel** [comment]
+

**Comment by archiecobbs** [comment]
Yes!

Please consider including building and publishing rocksjni to maven as part of the normal release process.

Thanks.

**Comment by adamretter** [comment]
I am closing this as RocksJava has been published to Maven Central as part of the official release for some time now.
