### ISSUE TITLE
sst_dump reported a corruptted sstable  is ok

### ISSUE THREAD

**Issue by ikenchina** [facebook/rocksdb#6840]
> 
I encoutered a sstable corruption problem, it caused all write operations to fail.
Below information is `Status` was returned by rocksdb when program invoked BatchWrite operation.
```
 Corruption: block checksum mismatch: expected 2094721867, got 1946732542 in /export/xdb/db/1/1/1620539.sst offset 0 size 1600
```

but sst_dump reported it is ok when I verified it.
```
./sst_dump --file=./1620539.sst --verify_checksum --command=verify
from [] to []
Process ./1620539.sst
Sst file format: block-based
The file is ok
```

**information**   

- rocksdb : 5.14.3
- OS : CentOS Linux release 7.2.1511 (Core)

**Comment by pdillinger** [comment]
This is consistent with a random hardware bit flip between reading the data from storage and computing the checksum. If your hardware is unreliable or you operate thousands of servers, you might expect to see this once in a while. Did the DB recover after re-opening?

**Comment by ikenchina** [comment]
yep, is there a better solution to fix it other than reopen db.

**Comment by pdillinger** [comment]
We are interested in making RocksDB more robust to many (but not all) random bit flips in memory/CPU, so we would probably accept a PR that retries file read once on detection of corruption. (The retry would be more effective if it explicitly bypassed OS disk cache.)

**Comment by ikenchina** [comment]
@pdillinger 
H
