### ISSUE TITLE
java rocksdb exception "Caused by.unknown WriteBatch tag" during write.

### ISSUE THREAD

**Issue by popacai** [facebook/rocksdb#6848]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
in our service, we convert a large data set from a file to a rocksdb.

we open the rocksdb in 

```
    RocksDB.loadLibrary();
    Options options = new Options();
    options.setUnorderedWrite(true);
    options.setAllow2pc(false);
    options.setAllowConcurrentMemtableWrite(true);
    options.prepareForBulkLoad();
    options.setCreateIfMissing(true);
    return RocksDB.open(options, filePath);
```

then we perform a batch write

```
      WriteBatch batch = new WriteBatch();
      for (Map.Entry<K, V> entry : data.entrySet()) {
        // serialize the key and values into byte[]
        byte[] key = serializeKey(entry.getKey());
        byte[] value = serializeValue(entry.getValue());
        batch.put(key, value);
      }
      WriteOptions options = new WriteOptions();
      _rocksDB.write(options, batch); // <- failure point
```

after lots of writes, we close it and reopen it as a read-only DB

notice, all writes are in one single thread, we don't perform multi-thread writing.

### Actual behavior
during the ramp, we found sometimes it may fail with 
```
--- Caused by.unknown WriteBatch tag - Line ()
org.rocksdb.RocksDB.write0 - Line -2 (RocksDB.java)
org.rocksdb.RocksDB.write - Line 1421 (RocksDB.java)
my.code.base.AvroRocksDB.batchPut - Line xxx (AvroRocksDB.java)
```
we have added some retry functionality, it still failed after 4 times retry with a 1000ms delay.

### Steps to reproduce the behavior
most of the times it succeed without any exceptions. we only catch this issue twice within 1000 times runs.

rocksdb version "org.rocksdb:rocksdbjni:6.6.4"

please suggest if there is any misconfiguration.

I have checked the issue history, none of these seems to be similar.

**Comment by adamretter** [comment]
The error `unknown WriteBatch tag` only occurs in two places in the code-base:

1. `WriteBatchInternal::Iterate`
2. `WriteBatchInternal::ReadRecordFromWriteBatch`

The second is in-fact called from the first.

It implies that the first byte of the WriteBatch, its tag, is unknown. It then raises an error about the WriteBatch being corrupted.

I am wondering if you can consistently reproduce this?

**Comment by popacai** [comment]
I can't consistently reproduce this, it failed about 2 out of 1000 times. our service is waiting for rocksdb writing. so our service fails to start when the exception happens.

We have already added retry, but it still fails with 4 retries.

most of the time, it seems to be normal.

**Comment by jestan** [comment]
@popacai Exact issue happened to me when I didnt properly close the  WriteBatch or WriteOptions object after writting. Also you dont need to create WriteOptions again and again, you can define it as a constant

**Comment by popacai** [comment]
> @popacai Exact issue happened to me when I didnt properly close the WriteBatch or WriteOptions object after writting. Also you don't need to create WriteOptions again and again, you can define it as a constant

Thank you for catching this, testing now by closing them. will update the thread if it's fixed.

**Comment by popacai** [comment]
Thank you, after the close the WriteBatch, the problem is fixed. Thank you for helping!

I notice all RocksObject is "AutoClosable", Just wish to confirm, all "RocksObject"s needs to be close() correctly? Otherwise, RocksDB may crash?

**Comment by popacai** [comment]
```
      WriteBatch batch = new WriteBatch();
      for (Map.Entry<K, V> entry : data.entrySet()) {
        // serialize the key and values into byte[]
        byte[] key = serializeKey(entry.getKey());
        byte[] value = serializeValue(entry.getValue());
        batch.put(key, value);
      }
      WriteOptions options = new WriteOptions();
      _rocksDB.write(options, batch);
      batch.close();
      options.cloose();
```

**Comment by adamretter** [comment]
@popacai I would suggest adopting an ARM pattern like try-with-resources, see: https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#memory-management
