### ISSUE TITLE
Segfault at Statistics::getAndResetTickerCount on 5.18.3

### ISSUE THREAD

**Issue by ableegoldman** [facebook/rocksdb#6856]
### Expected behavior
Not to crash

### Actual behavior
Crashes with 
```
 # A fatal error has been detected by the Java Runtime Environment:
 #
 #  SIGSEGV (0xb) at pc=0x00007fa40f9e31ab, pid=23022, tid=0x00007fa4341b1700
 #
 # JRE version: OpenJDK Runtime Environment (8.0_242-b08) (build 1.8.0_242-b08)
 # Java VM: OpenJDK 64-Bit Server VM (25.242-b08 mixed mode linux-amd64 compressed oops)
 # Problematic frame:
 # C  [librocksdbjni8322403889346508613.so+0x2e21ab]  Java_org_rocksdb_Statistics_getAndResetTickerCount+0x1b
 #
 # Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
 #
 # An error report file with more information is saved as:
 # /mnt/run/hs_err_pid23022.log
 Compiled method (nm) 1697462436 5718     n 0       org.rocksdb.Statistics::getAndResetTickerCount (native)
 total in heap  [0x00007fa45d73c5d0,0x00007fa45d73c928] = 856
 relocation     [0x00007fa45d73c6f8,0x00007fa45d73c740] = 72
 main code      [0x00007fa45d73c740,0x00007fa45d73c920] = 480
 oops           [0x00007fa45d73c920,0x00007fa45d73c928] = 8
```

[hs_err_pid23022.log](https://github.com/facebook/rocksdb/files/4652018/hs_err_pid23022.log)

### Steps to reproduce the behavior
Haven't been able to reproduce this, in fact we only hit it once after running the same application for several weeks. The app uses the rocksDB Statistics to report metrics.

**Comment by adamretter** [comment]
Without a mechanism to reproduce it, it is very hard to know what the issue might be.

Can you upgrade to a newer version? 5.18.3 is quite old now

**Comment by ableegoldman** [comment]
This was in a Kafka Streams app. Unfortunately we're unable to bump the rocksdb dependency to 6.x due to some breaking changes in the user facing API.

If we do hit this again, is there anything in particular we should look out for or any useful information to collect (in addition to the error report attached in this issue)?

**Comment by adamretter** [comment]
@ableegoldman The full hs_err dump file can be helpful.

**Comment by ableegoldman** [comment]
Alright, I uploaded the hs_err log for this segfault and will do the same if we hit this again

**Comment by adamretter** [comment]
Thanks @ableegoldman. 

Looking at the stack trace I see this:

```
C  [librocksdbjni8322403889346508613.so+0x2e21ab]  Java_org_rocksdb_Statistics_getAndResetTickerCount+0x1b
J 10161 C2 org.apache.kafka.streams.state.internals.metrics.RocksDBMetricsRecorder.record()V (454 bytes) @ 0x00007fa45e217b14 [0x00007fa45e2177c0+0x354]
J 11137 C2 org.apache.kafka.streams.state.internals.metrics.RocksDBMetricsRecordingTrigger.run()V (42 bytes) @ 0x00007fa45e8cc71c [0x00007fa45e8cc500+0x21c]
J 11598 C2 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run()V (59 bytes) @ 0x00007fa45d8652f4 [0x00007fa45d8651e0+0x114]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
```

The implementation of `getAndResetTickerCount` is very simple. To know exactly where this is failing, I need you to resolve the line number within the `Java_org_rocksdb_Statistics_getAndResetTickerCount` function.
Can you follow these instructions please - https://github.com/facebook/rocksdb/wiki/JNI-Debugging#stack

**Comment by ableegoldman** [comment]
Just realized I never followed up. Unfortunately the specific instance we saw the segfault on was taken down shortly after. The good/bad news is we haven't seen it happen again, but if it does I'll make sure it stays live for debugging
