### ISSUE TITLE
[Help ] What is  the difference between backup and checkpoint ? which one will be recommended if I want  to do backup restore operation

### ISSUE THREAD

**Issue by woshidama323** [facebook/rocksdb#6863]
Hi, Newbie for rocksdb, As there is no any group for this help, I send this issue and wish someone could help to answer me this question ? if this is not a right place for asking help Please let me know, I will delete this comment. thanks

**Comment by ajkr** [comment]
Hi, checkpoint is a lightweight way to capture the DB's state in another directory. It creates hardlinks to the immutable files to prevent copy. More details: https://github.com/facebook/rocksdb/wiki/Checkpoints

Backup is a heavier weight way to capture the DB's state. It supports additional features like separating the `Env` used for backup from the DB's `Env`. That way you can write your backup to remote storage. It also has features for physical deduplication of data. So if you take backup of the same DB multiple times, it will only store one copy of the common SST files. More details: https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F

Let us know if you have any more specific questions.

**Comment by asad-awadia** [comment]
@ajkr 

> It supports additional features like separating the Env used for backup from the DB's Env. That way you can write your backup to remote storage

1. Does that mean checkpoints can't be uploaded to remote storage?

2. Are checkpoints updated after creation as writes are made to the main DB?

**Comment by jay-zhuang** [comment]
> 1. Does that mean checkpoints can't be uploaded to remote storage?
checkpoint uses the same `Env` or same `FileSystem`, so it can only use the same file system API as DB. Technically, you could still mount remote storage to a local dir and write to it. But backup is more flexible on that.
> 2. Are checkpoints updated after creation as writes are made to the main DB?
No, it's a snapshot of the DB at the time of creation.

**Comment by asad-awadia** [comment]
@jay-zhuang I am still confused - `so it can only use the same file system API as DB. ` what does this mean? A checkpoint restored can not be used on a new instance?

What is the difference between a checkpoint and backup made on a path on local disk?

**Comment by quaaanLee** [comment]
> No, it's a snapshot of the DB at the time of creation.

Hello，there is another snapshot provided by RocksDB. I have figured out that the snapshot mainly record a seqnum and will remain some data referred to snapshot during the compaction. 
If I want to keep a version and I can read the version anytime, should I use snapshot or checkpoint?

**Comment by ajkr** [comment]
> If I want to keep a version and I can read the version anytime, should I use snapshot or checkpoint?

A snapshot cannot outlive the DB session that created it, so for reading the version at any time you should use checkpoint.
