### ISSUE TITLE
[branch:master] build failed on centos7 

### ISSUE THREAD

**Issue by woshidama323** [facebook/rocksdb#6866]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
build successfully

### Actual behavior
failed 
[  0%] Built target build_version
[  0%] Building CXX object CMakeFiles/rocksdb-shared.dir/db/arena_wrapped_db_iter.cc.o
In file included from /root/rocks/file/file_prefetch_buffer.h:14:0,
                 from /root/rocks/table/format.h:13,
                 from /root/rocks/table/internal_iterator.h:14,
                 from /root/rocks/db/pinned_iterators_manager.h:12,
                 from /root/rocks/db/range_tombstone_fragmenter.h:15,
                 from /root/rocks/db/memtable.h:19,
                 from /root/rocks/db/memtable_list.h:17,
                 from /root/rocks/db/column_family.h:17,
                 from /root/rocks/db/db_impl/db_impl.h:22,
                 from /root/rocks/db/arena_wrapped_db_iter.h:13,
                 from /root/rocks/db/arena_wrapped_db_iter.cc:10:
/root/rocks/file/random_access_file_reader.h: In constructor 'rocksdb::RandomAccessFileReader::RandomAccessFileReader(std::unique_ptr<rocksdb::FSRandomAccessFile>&&, const string&, rocksdb::Env*, rocksdb::Statistics*, uint32_t, rocksdb::HistogramImpl*, rocksdb::RateLimiter*, const std::vector<std::shared_ptr<rocksdb::EventListener> >&)':
/root/rocks/file/random_access_file_reader.h:69:7: error: declaration of 'env' shadows a member of 'this' [-Werror=shadow]
       : file_(std::move(raf)),
       ^
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/rocksdb-shared.dir/db/arena_wrapped_db_iter.cc.o] Error 1
make[1]: *** [CMakeFiles/rocksdb-shared.dir/all] Error 2
make: *** [all] Error 2

### Steps to reproduce the behavior
make

**Comment by pdillinger** [comment]
Feel free to prepare a pull request with a fix.

Conflicting member:

    Env* env() const { return env_; }
