### ISSUE TITLE
Segfault at iterator close from different thread

### ISSUE THREAD

**Issue by mad** [facebook/rocksdb#6886]
### Expected behavior
exception if this operation does not supported

### Actual behavior
jvm crashed

### Steps to reproduce the behavior
```
public class RockDbCrash {
    public static void main(String[] args) throws InterruptedException, ExecutionException, RocksDBException {
        final TransactionDB db = TransactionDB.open(new Options(), new TransactionDBOptions(), "/tmp/test");
        final Transaction transaction = db.beginTransaction(new WriteOptions());
        final RocksIterator iterator = transaction.getIterator(new ReadOptions());

        final CompletableFuture<Void> done = CompletableFuture.runAsync(iterator::seekToFirst);
        iterator.close();
        done.get();
    }
}
```

```
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni11225714333648553599.so+0x1c0b46]  Java_org_rocksdb_RocksIterator_seekToFirst0+0x6
j  org.rocksdb.AbstractRocksIterator.seekToFirst()V+26
j  RockDbCrash$$Lambda$17.run()V+4
j  java.util.concurrent.CompletableFuture$AsyncRun.run()V+36 java.base@14
j  java.util.concurrent.CompletableFuture$AsyncRun.exec()Z+1 java.base@14
```

**Comment by adamretter** [comment]
It looks like you are trying to call `Iterator::SeekToFirst` on an Iterator which you have already closed. That is unsupported.

**Comment by mad** [comment]
Single thread failed with segfault too

```
public class RockDbCrash {
    public static void main(String[] args) throws RocksDBException {
        final TransactionDB db = TransactionDB.open(new Options().setCreateIfMissing(true), new TransactionDBOptions(), "/tmp/test");
        final Transaction transaction = db.beginTransaction(new WriteOptions());
        final RocksIterator iterator = transaction.getIterator(new ReadOptions());
        iterator.seekToFirst();
        iterator.close();
        iterator.isValid();
    }
}
```

**Comment by adamretter** [comment]
@mad You are calling `iterator.isValid();` after `iterator.close()`. That is also an invalid operation ;-)

**Comment by mad** [comment]
Yes, I know, but is it right behaviour when JVM totally crashed?. In java world these type of violations should generate some sort of exceptions

**Comment by mad** [comment]
Is it possible to cancel tx from different thread without additional synchronization? 

Current approach

1. One thread open and read long iterator
2. Second thread wish to cancel this long running operation and invoke rollback/close on this tx

But It lead to segfault

Or application should provide own synchronization logic for cancelling?

**Comment by adamretter** [comment]
@mad this question comes up quite a lot. The issue is that adding a fix would add some overhead to the API.

i.e. on every single method call of every Java object in the RocksJava API we would have to check an atomic variable as to whether that object has been closed or not. For systems that want the best performance such overhead is probably unacceptable.

I think it is very likely that you will find such Segfault's during development and testing. 

I agree that this is quite unusual for Java. Yet, it is very usual for C++ which is what the Java API is wrapping.

**Comment by adamretter** [comment]
> Is it possible to cancel tx from different thread without additional synchronization?

Please can you open a separate issue or ask in the mailing list or Slack channel. This issue tracker is really meant for issues on concrete problems.
