### ISSUE TITLE
Intra L0 compaction needs limits

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#6889]
### Expected behavior

More control over L0 -> L0 compaction. This is probably related to #4991

### Actual behavior

With RocksDB 6.4, L0 to L0 compaction allows for too much data in the L0. I don't see an option to disable it, nor do I see a way to ever stop it. In theory this allows an unlimited amount of data in the L0 and it already appears to circumvent write stalls that would otherwise be applied by the L0 slowdown and stall triggers.

This is from MyRocks with an IO-bound insert benchmark at the end of the load. The write buffer is 64M and then L0 -> L0 compaction leaves the L0 with GB-sized SSTs rather than ones that are ~64M.

```
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0     18/13   9.45 GB  11.8    134.7     0.0    134.7     196.6     61.9       0.0   3.0     41.6     60.7   3318.26           2804.80      2312    1.435   4193M      0
  L4    219/208 14.27 GB   0.1     39.6    14.7     24.9      39.1     14.3       0.0   2.7     29.4     29.1   1379.08            761.21         6  229.847    668M      0
  L5     85/0    5.51 GB   0.3    136.9    37.5     99.4     135.5     36.1       0.0   3.6     33.7     33.4   4157.51           2483.71        22  188.978   1809M      0
  L6    475/0   29.52 GB   0.0     39.0    30.9      8.1      37.6     29.5       0.0   1.2     25.2     24.3   1587.13            700.59       126   12.596    428M      0
 Sum    797/221 58.75 GB   0.0    350.2    83.0    267.1     408.9    141.8       0.0   6.2     34.3     40.1  10441.98           6750.31      2466    4.234   7100M      0
 Int      0/0    0.00 KB   0.0      3.0     0.0      3.0       3.5      0.5       0.0   6.0     41.6     48.7     73.59             55.64        23    3.199     94M      0
```

**Comment by mdcallag** [comment]
Another problem from this is when I configure RocksDB to pin L0 and L1 files. sizeof(L0) + sizeof(L1) should be <= 2G based on my configuration. But now they are ~20G and much more memory will be used by the pinning. This can lead to OOM.
  pin_l0_filter_and_index_blocks_in_cache: 1
  pin_top_level_index_and_filter: 1

**Comment by siying** [comment]
L0 sizing is something we can improve. In the mean time, if you are willing to sacrifice some performance, you can try to use partitioned index.

**Comment by dhruba** [comment]
we have switched off L0-L0 compaction in some of our production cluster https://www.facebook.com/groups/rocksdb.dev/permalink/2624582600973571/

**Comment by dhruba** [comment]
Based on my experiences, I have understood the disadvantages of L0->L0 compaction but I still do not understand its benefits. can somebody pl describe under what conditions L0->L0 compactions help?

**Comment by ajkr** [comment]
As Mark pointed out, #4991 describes an interaction between intra-L0 and a newer heuristic to let base level expand flexibly. Together, they cause L0 and, less noticeably, base level to expand to infinity under sustained high write rate. The short-term fix is reuse option `max_compaction_bytes` to prevent this infinite expansion (https://github.com/facebook/rocksdb/commit/3d9d77d9006c246ea54656440fb29eebfa048f8b). The longer-term fix (IMO) that no one is working on would be to restructure level compaction style so it has partitioned tiers beneath L0 but above base level; then, intra-L0 can be deprecated.

> Based on my experiences, I have understood the disadvantages of L0->L0 compaction but I still do not understand its benefits. can somebody pl describe under what conditions L0->L0 compactions help?

They're described here: https://rocksdb.org/blog/2017/06/26/17-level-based-changes.html.

**Comment by mdcallag** [comment]
@ajkr - max_compaction_bytes limits both L0 to L0 and Ln to Ln+1. I am OK with a large limit for Ln to Ln+1 but want a smaller limit for L0 to L0. I also prefer an option to turn this off.

**Comment by ajkr** [comment]
> I am also running my current round of benchmarks twice -- with L0 to L0 both enabled and disabled in RocksDB 6.4. With it on there is far too much data in L0 and L1 under stress, so much that the limits I thought that I otherwise configured get ignored.

Thanks for pointing that out. I am trying it now too and indeed compaction looks very different (not easy for me to say better or worse, but at least more variety in what level gets picked). Please let us know how the results turn out -- am interested to know about any difference in user-visible metrics like write stalls, write-amp, or throughput.

**Comment by mdcallag** [comment]
@ajkr - will have more in a few days. First result is orthogonal to this. The CPU overhead on compaction from bloom filters is larger than I expected -- between 1.3X and 1.6X more CPU
https://www.facebook.com/groups/rocksdb.dev/permalink/3109516482480178/

This is related because more CPU overhead leads to more stalls which leads to more work for intra L0 compaction.

**Comment by mdcallag** [comment]
Summary of perf after insert benchmark load using recent MyRocks (has RocksDB 6.10.1) with and without intra-L0 compaction enabled.
https://gist.github.com/mdcallag/d2011ceb6269e9a3b63cef8f96b65cea

With intra-L0 enabled:
* insert rate is 1.3X better
* sizeof(L0) ~= 8G and sizeof(L1) ~= 12G as well. They should be ~256M each
* Cumulative stall time is less, ~2/3 the value with intra-L0 disabled

**Comment by mdcallag** [comment]
@ajkr reopen if you disagree, but I think this can be closed given that [max_compaction_bytes](https://github.com/facebook/rocksdb/blob/53c8f739fd266bb9e755eccceea7adb4d5126083/include/rocksdb/advanced_options.h#L612) is a limit
