### ISSUE TITLE
[BUG] option 'OptimizeForPointLookup' before 6.2.2 could lead to iterator seek invalid

### ISSUE THREAD

**Issue by Myasuka** [facebook/rocksdb#6893]
### Expected behavior
Insert a key-value with key as a byte array like: `{0, 0, 0, 1}`.
And then seek the iterator with beginning: `{0}`, we could get a valid iterator.

### Actual behavior
This behavior is expected with default options. However, if I just enable `optimizeForPointLookup` before rocksDB-6.2.2, the iterator would be invalid.

### Steps to reproduce the behavior
A simple java program to reproduce this:
~~~java
NativeLibraryLoader.getInstance().loadLibrary("/tmp/rocksdb-lib");

Options options = new Options()
		// if we do not enable `optimizeForPointLookup`, the result is expected 
		.optimizeForPointLookup(2048)
		.setCreateIfMissing(true);
try(RocksDB rocksDB = RocksDB.open(options, "/tmp/rocksdb")) {
	byte[] array = ByteBuffer.allocate(4).putInt(1).array();
	rocksDB.put(array, new byte[]{});
	RocksIterator iterator = rocksDB.newIterator();
	iterator.seek(new byte[]{array[0]});
	System.out.println("seek is valid: " + iterator.isValid());
	iterator.close();
}
~~~

I noticed that @siying has changed the default implementation of `OptimizeForPointLookup` in https://github.com/facebook/rocksdb/pull/5165 by removing `NewNoopTransform` and `kHashSearch` index type. And also said that "move away from prefix extractor as well as hash-based indexing, as they are prone to misuse." Is my case the scenario that misused this option?

Moreover, why this bug could happen?

**Comment by Myasuka** [comment]
@siying would you please take a look at this problem?

**Comment by pdillinger** [comment]
With prefix_extractor set, iterators use prefix seek by default. If the prefix_extractor is NoopTransform (should be called IdentityTransform) then prefix seek means an iterator might only access that one user key that you seek to, {0}.

It was probably intended that users of OptimizeForPointLookup would not be using Iterator::Seek. Although the behavior is weird, it seems to be as expected and documented if you dig into the actual meaning of OptimizeForPointLookup.

Details: https://github.com/facebook/rocksdb/wiki/Prefix-Seek

**Comment by adamretter** [comment]
@pdillinger Perhaps we should raise an error with that combination?

**Comment by pdillinger** [comment]
As OP points out, OptimizeForPointLookup no longer sets a prefix extractor, so this is not really a current issue. And although setting a prefix extractor has documented caveats, prefix seek is very important for MyRocks.
