### ISSUE TITLE
fix env/env_hdfs.cc

### ISSUE THREAD

**Issue by hfrt456** [facebook/rocksdb#6910]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
In  file(env/env_hdfs.cc)
  --- *is_dir = (pFileInfo->mKind == tObjectKindDirectory);---
it should be  --- *is_dir = (pFileInfo->mKind == kObjectKindDirectory);---

**Comment by ajkr** [comment]
Are you interested in contributing a fix?

**Comment by riversand963** [comment]
Note we are going to migrate HDFS from repo https://github.com/facebook/rocksdb/issues/9159.
ALso, it seems the issue has been resolved by #6917
