### ISSUE TITLE
[BUG] incorrect level information of hit file in Version::Get()

### ISSUE THREAD

**Issue by cighao** [facebook/rocksdb#6912]
In `Version::Get()`, once hit a file, calls
```
table_cache_->Get(
        read_options, *internal_comparator(), *f->file_metadata, ikey,
        &get_context, mutable_cf_options_.prefix_extractor.get(),
        cfd_->internal_stats()->GetFileReadHist(fp.GetHitFileLevel()),
        IsFilterSkipped(static_cast<int>(fp.GetHitFileLevel()),
       fp.IsHitFileLastInLevel()),
       fp.GetCurrentLevel());
```
to get this file. 

`fp.GetCurrentLevel()` should refer to which level this file belongs to. But actually `fp.GetCurrentLevel()` does not represent the level that the file belongs to. 

In `fp.GetNextFile()`,  
```
...
returned_file_level_ = curr_level_;
if (curr_level_ > 0 && cmp_largest < 0) {
     // No more files to search in this level.
     search_ended_ = !PrepareNextLevel();  // increase curr_level_ in PrepareNextLevel()
 } else {
      ++curr_index_in_curr_level_;
}
return f;
...
```
if hit a file, it firstly calls `PrepareNextLevel()`, which will increase `curr_level_`, then return `f`. After returning `f`, the `curr_level_` does not refer to which level `f` belongs to, and it points to the next level.

I think it should change ` fp.GetCurrentLevel()` to ` fp.GetHitFileLevel()`  in

```
table_cache_->Get(
        read_options, *internal_comparator(), *f->file_metadata, ikey,
        &get_context, mutable_cf_options_.prefix_extractor.get(),
        cfd_->internal_stats()->GetFileReadHist(fp.GetHitFileLevel()),
        IsFilterSkipped(static_cast<int>(fp.GetHitFileLevel()),
       fp.IsHitFileLastInLevel()),
       fp.GetCurrentLevel());
```

**Comment by ajkr** [comment]
These `static_cast<int>(which)`es are also wrong: https://github.com/facebook/rocksdb/blob/14eca6bf04f0077e109a7251e4df6c54ebe9dc51/db/version_set.cc#L5675-L5689. The implication of these and the one you mentioned looks like prefetching/pinning can apply to the "wrong" files. It's more an optimization problem than correctness. If you're interested in a fix that'd be really useful -- the `level` parameter may be used for other things one day, so hopefully we can trust it is correct..
