### ISSUE TITLE
Segmentation fault when using the ldb tool

### ISSUE THREAD

**Issue by gg814** [facebook/rocksdb#6914]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
If the command (see below) is not legitimate, should print an error message.

### Actual behavior
`Segmentation fault (core dumped)`

### Steps to reproduce the behavior
`./ldb --db=<db_path> create_column_family <new_column_family_name>`

When <db_path> does not exist in the file system, executing the above command results in segmentation fault.

**Comment by ajkr** [comment]
cc @siying (I ran into this too - https://github.com/facebook/rocksdb/commit/4a4b8a13444e67fa51127568c63d6f0a225c4549#r39538424).
