### ISSUE TITLE
rate_limiter problem (Illegal instruction in CalculateRefillBytesPerPeriod)

### ISSUE THREAD

**Issue by flozano** [facebook/rocksdb#692]
I'm trying to use Mongo-rocks CentOS 7 RPMs and I think I'm hitting an issue with the rate limiter in rocksdb:
```
# gdb --args mongod -f /etc/mongod.conf
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-64.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/mongod...done.
(gdb) run
Starting program: /bin/mongod -f /etc/mongod.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
2015-08-17T12:51:16.931+0000 I STORAGE  Compression: snappy
2015-08-17T12:51:16.931+0000 I STORAGE  MaxWriteMBPerSec: 1024
2015-08-17T12:51:16.931+0000 I STORAGE  Crash safe counters: 0
[New Thread 0x7ffff0286700 (LWP 27044)]

Program received signal SIGILL, Illegal instruction.
0x000000000150b881 in CalculateRefillBytesPerPeriod (this=0x2496000, rate_bytes_per_sec=1073741824) at ./util/rate_limiter.h:63
warning: Source file is more recent than executable.
63	    return rate_bytes_per_sec * refill_period_us_ / 1000000.0;
Missing separate debuginfos, use: debuginfo-install mongodb-org-server-3.0.4-1.el7.x86_64
(gdb)
```

**Comment by igorcanadi** [comment]
Hmmm. This looks like the rocksdb was compiled with PORTABLE flag set turned off (which is the default). When PORTABLE flag is turned off, we compile RocksDB to optimize for native architecture. This makes the binary work only on that specific architecture.

**Comment by flozano** [comment]
Thanks a lot for the quick answer. I'll try to recompile myself under the same machine (vagrant instance) to see what happens.

Open candid question: Is it worth it to disable the PORTABLE? does it really squeeze more performance in a significant way?

**Comment by igorcanadi** [comment]
The biggest gain from using PORTABLE=0 is with CRC32: https://github.com/facebook/rocksdb/blob/master/util/crc32c.cc#L318. When we compile on SSE4.2 architecture we use a crc32 machine instruction, which makes checksumming much much faster.

**Comment by flozano** [comment]
Out of curiosity, I've tried running the thing in two different computers and enabled virtualbox support for SSE4.1/4.2 (checked in /proc/cpuinfo) but got the same result. I guess some other option only available on high-end xeon's is being used.

I will wait for my ongoing mongo-rocks build to finish and try again.

**Comment by igorcanadi** [comment]
Yeah -march=native enables all kinds of things. You can try `-march=sse4.2` to only enable sse4.2 support.

**Comment by flozano** [comment]
It seems the original issue could be solved, as it proceeds further down in the startup, but it still fails:
```
Starting program: /usr/src/mongo/./mongod -f /etc/mongod.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
2015-08-17T19:09:00.444+0000 I STORAGE  Compression: snappy
2015-08-17T19:09:00.444+0000 I STORAGE  MaxWriteMBPerSec: 256
2015-08-17T19:09:00.444+0000 I STORAGE  Engine custom option: max_background_compactions=8;block_based_table_factory={checksum=kxxHash};level_compaction_dynamic_level_bytes=true
2015-08-17T19:09:00.444+0000 I STORAGE  Crash safe counters: 0
warning: bind_ip of 0.0.0.0 is unnecessary; listens on all ips by default
[New Thread 0x7ffff0286700 (LWP 3816)]

Program received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff77a900b in raise () from /lib64/libpthread.so.0
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-12.el7.x86_64 glibc-2.17-55.el7.x86_64 libgcc-4.8.3-9.el7.x86_64 libstdc++-4.8.3-9.el7.x86_64 zlib-1.2.7-13.el7.x86_64
(gdb) quit
A debugging session is active.

	Inferior 1 [process 3812] will be killed.
```

**Comment by flozano** [comment]
Of course, at this stage I have no idea if this is from mongodb or from rocksdb...

**Comment by flozano** [comment]
OK, the issue now is related to compression, so I'm closing this one and keep investigating myself... @igorcanadi thanks a lot for the hint! I guess I should have checked #690 before.

**Comment by igorcanadi** [comment]
No worries. Let me know if you see any other issues!

**Comment by igorcanadi** [comment]
@flozano what makes you think this is related to compression? Can you copy/paste the error message? It is likely because RocksDB was compiled without support for snappy. Try `sudo apt-get install libsnappy-dev` before you compile RocksDB. Or you can try running MongoRocks with `--rocksdbCompression=none`

**Comment by flozano** [comment]
That was the reason, RocksDB was compiled without support for snappy or zlib. I should have been more specific in the comment above :+1:

**Comment by flozano** [comment]
The remaining issue now is that mongorocks RPMs don't work very well, but that's already reported in https://github.com/mongodb-partners/mongo-rocks/issues/9
