### ISSUE TITLE
[Java] Java support for Transactions

### ISSUE THREAD

**Issue by agiardullo** [facebook/rocksdb#697]
Received a request for Java support for RocksDB Transactions.  Filing this issue to track.  Anyone interested in working on this?

By transactions, I am referring to the `transaction.h`, `transaction_db.h`, `optimistic_transaction_db.h` APIs in `include/rocksdb/utilities/`.

**Comment by adamretter** [comment]
@agiardullo I would be interested to pick this up, but I cannot say when at the moment as I am pretty busy.

**Comment by adamretter** [comment]
@agiardullo This is being implemented and in fact is almost complete, see https://github.com/facebook/rocksdb/issues/1151.

I am closing this issue as there is a larger audience in the other duplicate issue.
