### ISSUE TITLE
[Bug]Rocksdbjni 6.6.4 crashed and could not be started again

### ISSUE THREAD

**Issue by fenghaoming** [facebook/rocksdb#6971]
Rocksdbjni 6.6.4 crashed and could not be started again. Could you help me to see what the problem is. Thank you!

```
# uname -a
Linux VM_126_160_centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
# java -version
openjdk version "1.8.0_71"
OpenJDK Runtime Environment (build 1.8.0_71-b15)
OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
```

JVM fatal error log as follow:

[hs_err_pid27111.log](https://github.com/facebook/rocksdb/files/4769203/hs_err_pid27111.log)

**Comment by koldat** [comment]
You have most likely met #5496 

To mitigate just set: blockConfig.setVerifyCompression(false);
