### ISSUE TITLE
options_helper.cc fails to compile with clang10

### ISSUE THREAD

**Issue by kryton** [facebook/rocksdb#6995]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Actual behavior
```
[ 13%] Building CXX object CMakeFiles/rocksdb-shared.dir/options/options_helper.cc.o
/home/iholsman/src/rocksdb/options/options_helper.cc:936:19: error: loop variable 'iter' of type 'const std::pair<const std::__cxx11::basic_string<char>, rocksdb::OptionTypeInfo>' creates a copy from type 'const std::pair<const std::__cxx11::basic_string<char>, rocksdb::OptionTypeInfo>' [-Werror,-Wrange-loop-construct]
  for (const auto iter : type_info) {
                  ^
/home/iholsman/src/rocksdb/options/options_helper.cc:936:8: note: use reference type 'const std::pair<const std::__cxx11::basic_string<char>, rocksdb::OptionTypeInfo> &' to prevent copying
  for (const auto iter : type_info) {
       ^~~~~~~~~~~~~~~~~
                  &
1 error generated.
make[2]: *** [CMakeFiles/rocksdb-shared.dir/build.make:1532: CMakeFiles/rocksdb-shared.dir/options/options_helper.cc.o] Error 1
```
### Steps to reproduce the behavior
on Ubuntu 20.04.
using
/usr/bin/clang++-10
$ cmake --version
cmake version 3.16.3

**Comment by feliwir** [comment]
I can't compile either with latest clang on Ubuntu. Can the PR please be merged or looked at?

**Comment by mrambacher** [comment]
In what version of RocksDB are you seeing this issue?  I am attempting to reproduce it in master, but do not see the failure.

**Comment by adamretter** [comment]
This not the same issue, but I had problems also with Clang 11 on Ubuntu - https://github.com/facebook/rocksdb/issues/7736

**Comment by mrambacher** [comment]
I installed clang via "sudo apt install clang" on my ubuntu box, which installed clang v10:
clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

I did not see the same build issue, but saw an issue with atomic functions:

[ 66%] Building CXX object CMakeFiles/rocksdb_reduce_levels_test.dir/tools/reduce_levels_test.cc.o
/usr/bin/ld: CMakeFiles/db_stress.dir/db_stress_driver.cc.o: in function `std::__atomic_base<unsigned int>::is_lock_free() const':
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/atomic_base.h:377: undefined reference to `__atomic_is_lock_free'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [db_stress_tool/CMakeFiles/db_stress.dir/build.make:221: db_stress_tool/db_stress] Error 1
make[1]: *** [CMakeFiles/Makefile2:6566: db_stress_tool/CMakeFiles/db_stress.dir/all] Error 2

**Comment by adamretter** [comment]
@mrambacher I see that there are some Clang 10 jobs on CircleCI, but none using CMake. Perhaps the first step would be to add jobs there for Clang 10 and 11 (for https://github.com/facebook/rocksdb/issues/7736). Would you like me to try?

**Comment by mrambacher** [comment]
@adamretter Thanks for the offer.  Please do!

**Comment by mrambacher** [comment]
I tried to build the latest master on Ubuntu 20.x with clang-11 and do not see the options_helper error, only the undefined reference to atomic_is_lock_free.

**Comment by mrambacher** [comment]
I believe this is fixed now.
