### ISSUE TITLE
RocksDB benchmarking

### ISSUE THREAD

**Issue by darshan-ghumare** [facebook/rocksdb#700]
Hi,

I have modified example/c_simple_example.c os that it will only do put,

// Put key-value
rocksdb_writeoptions_t *writeoptions = rocksdb_writeoptions_create();
const char key[] = "key";
char *value = NULL;
unsigned long i = 0, n = atol(argv[1]), size = atol(argv[2]);
value = (char *) malloc(size);
assert(value);
for (i = 0; i < n; i++) {
    rocksdb_put(db, writeoptions, key, strlen(key), value, strlen(value) + 1,
            &err);
    assert(!err);
}
free(value);

Following is my observations,
1.
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 10000 4096

real	0m0.276s
user	0m0.026s
sys	0m0.034s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 100000 4096

real	0m4.782s
user	0m0.281s
sys	0m0.297s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 1000000 4096

real	1m1.820s
user	0m2.916s
sys	0m2.521s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 1000000 8192

real	0m58.633s
user	0m2.801s
sys	0m2.599s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 1000000 65536

real	0m50.593s
user	0m2.996s
sys	0m2.575s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 1000 65536

real	0m0.419s
user	0m0.014s
sys	0m0.007s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 1000 8192

real	0m0.253s
user	0m0.011s
sys	0m0.004s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 1000 4096

real	0m0.237s
user	0m0.009s
sys	0m0.006s

2. iostat showed
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00   120.50    0.00   72.50     0.00   772.00    21.30     1.48   20.19    0.00   20.19  13.79 100.00

WkB/s never crosses 800 and disk utilization  always 99-100%.

This server is a Ubuntu 14.04 with 32GB RAM and Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz Quad-core processor.
All test ran on hard disk, it does not have SSD.

Are my observations correct?
Moreover, when I used LedisDB with RocksDB I got 5.2K IOPS for block size of 4096.

Please help.

Thanks,
Darshan

**Comment by 4tXJ7f** [comment]
I don't think that `strlen(value) + 1` does what you want: strlen will counts the number of chars until it encounters a \0, which is a random amount in your case because you never initialize the memory (your malloc implementation/OS might always zero it out).

**Comment by darshan-ghumare** [comment]
Thanks :)

// Put key-value
rocksdb_writeoptions_t *writeoptions = rocksdb_writeoptions_create();
const char key[] = "key";
char *value = NULL;
unsigned long i = 0, n = atol(argv[1]), size = atol(argv[2]);
value = (char *) malloc(size);
assert(value);
value[size - 1] = '\0';
for (i = 0; i < n; i++) {
    rocksdb_put(db, writeoptions, key, strlen(key), value, size,
            &err);
    assert(!err);
}
free(value);


Following are my observations with above changes,
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 10000 4096 

real	0m49.127s
user	0m0.464s
sys	0m0.501s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 100000 4096

real	9m10.426s
user	0m3.508s
sys	0m4.113s
root@Machine3:~/prototypes/rocksdb/examples# time ./c_simple_example 10000 8192

real	1m24.411s
user	0m0.507s
sys	0m0.760s

**Comment by igorcanadi** [comment]
Default RocksDB settings are not very performant. Unfortunately we can't change them because that would break existing use cases. To tune RocksDB and make it more performant, please refer to RocksDB Tuning Guide: https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide

**Comment by dhruba** [comment]
Closing this hoping that you were able to tune rocksdb appropriately.
