### ISSUE TITLE
(May a bug?)org.rocksdb.NativeLibraryLoader.loadLibrary.loadLibraryFromJarToTemp  needs to check its parameter tmpdir.

### ISSUE THREAD

**Issue by zyj183247166** [facebook/rocksdb#7053]
Dear, I may find a bug.

1.  First, the issue code is in the file 
[NativeLibraryLoader.java](https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/NativeLibraryLoader.java) and the method `loadLibraryFromJarToTemp`.
Although it checks if the new file is already existing, but it does't checks if the dir exists.
The code is as
```java
if (tmpDir == null || tmpDir.isEmpty()) {
      temp = File.createTempFile(tempFilePrefix, tempFileSuffix);
    } else {
      temp = new File(tmpDir, jniLibraryFileName);
      if (temp.exists() && !temp.delete()) {
        throw new RuntimeException("File: " + temp.getAbsolutePath()
            + " already exists and cannot be removed.");
      }
      if (!temp.createNewFile()) {
        throw new RuntimeException("File: " + temp.getAbsolutePath()
            + " could not be created.");
      }
    }
```

2. When the directory of `tmpDir` is not exist, the above code `tmp.createNewFile`  will not return and thus will not go into the if block to throw new `RuntimeException`. It will directly throw IOException `java.io.IOException: No such file or directory`

3. In fact, it is seen as a bug and repaired in one SVN project, please see the url http://svn.apache.org/viewvc/lucene/java/trunk/src/java/org/apache/lucene/store/FSDirectory.java?r1=150347&r2=150346&pathrev=150347&diff_format=h

4. One bug report about the issue i am talking is described in https://knowledge.broadcom.com/external/article/139684/cannot-start-em-after-applying-hf49-una.html and it has the following error description: `Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared libraryjava.io.IOException: No such file or directory`

5. At first see, i wonder why two Exceptions are thrown together. When i debug, i find the reason.
The code of the above bug report call `org.rocksdb.RocksDB.loadLibrary`. And its code is as below:
```java
      final String tmpDir = System.getenv("ROCKSDB_SHAREDLIB_DIR");
      // loading possibly necessary libraries.
      ....
    {
        NativeLibraryLoader.getInstance().loadLibrary(tmpDir);
    } catch (IOException e) {
        libraryLoaded.set(LibraryState.NOT_LOADED);
        throw new RuntimeException("Unable to load the RocksDB shared library",
            e);
    }
```

And when the directory of `tmpDir` which are got by `System.getenv("ROCKSDB_SHAREDLIB_DIR")` is not existing, the code `NativeLibraryLoader.getInstance().loadLibrary(tmpDir);` will calls `loadLibraryFromJarToTemp` (which don't check the `tmpdir` and in which the called `tmp.createNewFile` will not return and will not  goes into the if's then block, and will directly throws the the `IOException` )

Then, in `org.rocksdb.RocksDB.loadLibrary`, the above code, it will catch it. and throw `new RuntimeException("Unable to load the RocksDB shared library", e);`. Doing this, will throw two exceptions together, and don't  even have a blank or space. And that is why the bug report in "https://knowledge.broadcom.com/external/article/139684/cannot-start-em-after-applying-hf49-una.html" gives result `Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared libraryjava.io.IOException: No such file or directory` in which, `Unable to load the RocksDB shared library"and"java.io.IOException: No such file or directory` are connected very closely without just one blank. But sadly, the publishers of the bug report don't find the bug I am talking. They solve their problem in another way.

6. So in the above bug report, the really reason is the `org/rocksdb/NativeLibraryLoader.java`s method `loadLibraryFromJarToTemp` don't check `tmpdir` and which is already seen as a bug in the SVN patch http://svn.apache.org/viewvc/lucene/java/trunk/src/java/org/apache/lucene/store/FSDirectory.java?r1=150347&r2=150346&pathrev=150347&diff_format=h

7. Maybe you don't think it really matters. But i can tell you. If someone send some installation programs of some very good softwares which don't need money and are cracked on the Internet, and if they put a Trojan in the installation programs which modify the env variable `ROCKSDB_SHAREDLIB_DIR` to a directory which are not exist, then every user who uses rocksdb and modified env variable, when they open their application which start rocksdb. then they will find that, the rocksdb's staring procedure calls `RocksDB.loadLibrary`, and in it calls `String tmpDir = System.getenv("ROCKSDB_SHAREDLIB_DIR")`,  and `tmpDir` is not a valid path, and in it continually calls `NativeLibraryLoader.getInstance().loadLibrary(tmpDir)` and because it don't check `tmpDir`. and `tmp.createNewFile` will directly throw, and then every user who uses rocksdb and modified env variable  will find just the same result as https://knowledge.broadcom.com/external/article/139684/cannot-start-em-after-applying-hf49-una.html.
But what is really scaring is that, they don't know why and just get one exception information `Unable to load the RocksDB shared library` and `java.io.IOException: No such file or directory`.
What a sad thing!

8. My english is too so so and maybe not very easy to understand. I am now doing some work checking API Misuse. I am a reading doctor of Computer Science in China. I find the bug in your code is during my experiment about finding API Misuses.

9. Maybe you don't think it is a bug. But I, just as the publisher of the patch in http://svn.apache.org/viewvc/lucene/java/trunk/src/java/org/apache/lucene/store/FSDirectory.java?r1=150347&r2=150346&pathrev=150347&diff_format=h, thinks it is truly a bug.

**Comment by zyj183247166** [comment]
it needs to check if the tmpDir is exist. For example, check if the folder "wordcrash" is exist in the directory path stored in tmpDir variable ("D:\wordcrash\"). Note, check the folder. or the path.  Not just to check the tmpDir variable is null or is empty.

**Comment by zyj183247166** [comment]
check the Folder of the variable.  Not check the variable itself.

**Comment by adamretter** [comment]
Thanks for reporting I will take a look tomorrow at this

**Comment by adamretter** [comment]
@zyj183247166 Thanks for your report.
I constructed a small test where I set the environment variable `ROCKSDB_SHAREDLIB_DIR` to `/no-such-path` and the result was this:

```
Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared library
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:70)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
	... 9 more
Caused by: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1006)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJarToTemp(NativeLibraryLoader.java:95)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:67)
	... 10 more
```

Apart from the fact that the error messages could be friendlier... I am not sure I agree/understand your assessment.

In response to your points:

Regards (3), the behaviour that you cited in Lucene is different. They attempt to create the supplied tmpDir if it does not exist, we don't want to do that. Instead we allow the IO error to be reported to the user.

Regards (4), the issue is clearly with the Broadcom software failing to setup RocksDB correctly. Broadcom's described resolution tells you how to resolve this.

Regards (5), I don't see any such issue with the two error messages concatenated together. See my output that I included above. I suspect a problem with the text in the broadcom report, or in 3rd-party software. If you can reproduce this otherwise, please let me know how?

Regards (7)...
> Maybe you don't think it really matters. But i can tell you. If someone send some installation programs of some very good softwares which don't need money and are cracked on the Internet, and if they put a Trojan in the installation programs which modify the env variable ROCKSDB_SHAREDLIB_DIR

If someone is shipping bad software there is very little we can do. At that point the malicious party has complete control of the software and this IOException is probably the least of your concerns.

> and in it continually calls NativeLibraryLoader.getInstance().loadLibrary(tmpDir) and because it don't check tmpDir

If a 3rd-party piece of software that uses RocksDB (or any other library) continually calls a method after it has thrown an exception without trying to resolve the issue first, then that software is at fault.

I think the concerns between RocksDB and the Lucene issue that you sight are subtly different. I also think the Broadcom issue you sight is a problem in their application, for which they have already provided a solution.

At the moment I don't think there is anything to fix here. However, just to make sure we are not misunderstanding each other. If you were to address this problem that you perceive, keeping in mind that we don't want to create the tmpDir if it does not exist, what would you prescribe as a fix?

**Comment by zyj183247166** [comment]
Ok. Very thank you for replying me.  But i have many things to  refute you.
(1) The bug report in https://knowledge.broadcom.com/external/article/139684/cannot-start-em-after-applying-hf49-una.html. It is truly because of wrongly setting up RocksDB just as it said, but the exception reported in it is also truly that i am talking about all the way. And the really reason is the org/rocksdb/NativeLibraryLoader.java method loadLibraryFromJarToTemp don't check if the tmpdir directory already exists.

First, your small test is just suitable for a single platform, maybe Linux or Unix. And the bug report in https://knowledge.broadcom.com/external/article/139684/cannot-start-em-after-applying-hf49-una.html is not your platform. And the bug report's exception message thrown in the broadcam as below is quite possible.
"
Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared libraryjava.io.IOException: No such file or directory
    at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:51)
    at org.rocksdb.RocksDB.<clinit>(RocksDB.java:23)
"
Second, your small test just wants to say that the bug report in the above url is not because of calling RocksDB.loadLibrary. But the bug report clearly records the call trace is "calling RocksDB.<clinit> and then calling RocksDB.loadLibrary",just the same as the code in RocksDB.java
"
static {  
    RocksDB.loadLibrary(); // now at line 38
  }
....
....
NativeLibraryLoader.getInstance().loadLibrary(tmpDir); // now at line 67
"
More, the bug report records as RocksDB.java:23 and then RocksDB.java:51.  51-23=28
And in the now RocksDb.java, it is 67-38=29.  Because RocksDB.java is through many modifications. 
So, what lead to the above bug report. You may say it is caused by wrong set up. But as to the  exception itself, why it is thrown? it is caused by the wrong use of File.createNewFile  in NativeLibraryLoader.loadLibraryFromJarToTemp  without check if the dir already exists.
For example, you want to use File.createNewFIle at C:/a/b/c/xiaojie.txt. You should check if the dir C:/a/b/c already exists.

（2）Maybe every user correctly set up rocksdb, the above exception will not occur again because the dir path  in the env variable ROCKSDB_SHAREDLIB_DIR can not be a invalid path. And because of this, you think it is not a bug. But i want to talk the code itself and talk the use of API File.createNewFile. And i extract all the relative code in the 
NativeLibraryLoader.loadLibraryFromJarToTemp as below.
"
    if (tmpDir == null || tmpDir.isEmpty()) {
      temp = File.createTempFile(tempFilePrefix, tempFileSuffix);
    } else {
      temp = new File(tmpDir, jniLibraryFileName);
      if (temp.exists() && !temp.delete()) {
        throw new RuntimeException("File: " + temp.getAbsolutePath()
            + " already exists and cannot be removed.");
      }
      if (!temp.createNewFile()) {
        throw new RuntimeException("File: " + temp.getAbsolutePath()
            + " could not be created.");
      }
    }
"
Just as above, the correct coding style using Java is that you should discuss all the possible exception that maybe thrown.
Just as above, you discuss the tmpdir variabe itself maybe a null; you discuss the created File maybe already exists; you also throw a Exception Message "File xxx could not be created." if !temp.createNewFile().
But, can you go into the then block of  "if (!temp.createNewFile()) {}" when the tmpdir is not exist? If the passed tmpdir is not a null but contains a directory that is not exist, it will directly throws a "Not such file or directory" exception. And as to this exception, did the coding people consider it? And will you acknowledge that ignoring the potential exception is a right thing? Of course, you can say that the function itself throws IOException "File loadLibraryFromJarToTemp(final String tmpDir)
 throws IOException " But i think, you should know where correctly thrown it because only by doing this, you can debug quickly to solve it. But the function throws IOException to outer, to outer, to outer, until to RocksDB.java's loadLibrary. And when it throws, the called trace will just  recorded RocksDB.java's loadLibrary throws a exception and everyone will not immediately think of it is really thrown in NativeLibraryLoader.loadLibraryFromJarToTemp.
So, i think the code is not adequate.

(3) File.createNewFile needs check the file not exists and check the directory is exists. Its' misuse just as i am talking about, has already be recorded in the open database of MuBench. It is already one of the 89 API misuse recorded by MuBench.
And MuBench has been a standard benchmark for testing API-Misuse Detectors.
S. Amann, S. Nadi, H. A. Nguyen, T. N. Nguyen and M. Mezini, "MUBench: A Benchmark for API-Misuse Detectors," 2016 IEEE/ACM 13th Working Conference on Mining Software Repositories (MSR), Austin, TX, 2016, pp. 464-467.

(4)you say " the behaviour that you cited in Lucene is different. They attempt to create the supplied tmpDir if it does not 
exist. we don't want to do that. Instead we allow the IO error to be reported to the user." 
Yeah, you may think it is not a bug because you do't need to consider the tmpDir because the tmpDir in rocksDB can not be a invalid path because it is stored in the system env "ROCKSDB_SHAREDLIB_DIR" and modifying the env is a very difficult thing.
But, as i know, rocksDB is very quality project in Github with above 20000 stars. And many programmers will copy your code to learn the good programming style of rocksDB. For example, in https://www.jianshu.com/p/13c461c2ec09, a Chinese programmer thinks rocksDB is very quality and learn the good source code. 
If you think the "bug" i am talking will not cause anything to the users that installing rocksDB, you can think it is not a bug.
But if you think more, or in a more  wider perspective, and consider the correct use of API File.createNewFile and consider the right programming style should be advocated, you should think it is a bug and a Java API misuse.

Of course, very thank you for talking to me. And i hope more people can join in the talk.

**Comment by zyj183247166** [comment]
Maybe there exists some difference between scientific research and engineering.
In the ASE paper 
"
Wang S, Chollak D, Movshovitz-Attias D, et al. Bugram: bug detection with n-gram language models[C]//Proceedings of the 31st IEEE/ACM International Conference on Automated Software Engineering. 2016: 708-719.
"
It give some bug examples. I screenshot some information of this paper as below:
"
Figure 8(b) also shows a true bug. The
method waitForCompletion might throw several exceptions,
e.g., ClassNotFoundException and IOException, while in
this case, developers used this function without handling these
potential exceptions. 
"
and the code in Figure 8(b) is
"
try {
 currentJob.waitForCompletion(true);
 } finally { ...
}}...}
"
Even a potential exception is ignored, it will be seen as a bug.
I'm just throwing out one point for discussion.

**Comment by adamretter** [comment]
> First, your small test is just suitable for a single platform, maybe Linux or Unix. And the bug report in https://knowledge.broadcom.com/external/article/139684/cannot-start-em-after-applying-hf49-una.html is not your platform. And the bug report's exception message thrown in the broadcom as below is quite possible.
```
Caused by: java.lang.RuntimeException: Unable to load the RocksDB shared libraryjava.io.IOException: No such file or directory
    at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:51)
    at org.rocksdb.RocksDB.<clinit>(RocksDB.java:23)
```

I don't think that is the case. I did test on more than one platform. So that we can be certain, I have pushed the test code to GitHub - https://github.com/adamretter/rocksdb-tmpdir-test. I also setup Travis-CI to run the tests on Linux, macOS, and Windows, you can see the output of the tests on all 3 platforms here - @zyj183247166 https://travis-ci.com/github/adamretter/rocksdb-tmpdir-test

As you will see in the output of the tests, the concatenated error message which you described from the Broadcom issue is never created by any of the platforms.

> Second, your small test just wants to say that the bug report in the above url is not because of calling RocksDB.loadLibrary.

That is not what I was trying to say!

> But i think, you should know where correctly thrown it because only by doing this, you can debug quickly to solve it. But the function throws IOException to outer, to outer, to outer, until to RocksDB.java's loadLibrary. And when it throws, the called trace will just recorded RocksDB.java's loadLibrary throws a exception and everyone will not immediately think of it is really thrown in NativeLibraryLoader.loadLibraryFromJarToTemp.

From the Java StackTrace it is very clear to any Java developer that the exception is raised at line 95 of NativeLibraryLoader. I do not agree that this is difficult or confusing in any way.


> Yeah, you may think it is not a bug because you do't need to consider the tmpDir because the tmpDir in rocksDB can not be an invalid path because it is stored in the system env ROCKSDB_SHAREDLIB_DIR and modifying the env is a very difficult thing.

That is not what I think. Modifying an evironment variable is relatively easy, and they should generally be avoided for anything sensitive. 

Rather my point is, I *could* explicitly check that the `tmpDir` exists, but the end result will be the same. If it does not exist I would just throw an IOException, so ultimately the user gets the same exception and basically the same stack trace. Perhaps the error message is a little nicer, but the end result in the application would be the same!

**Comment by adamretter** [comment]
@zyj183247166 I put together an experimental change. Do you feel that this https://github.com/adamretter/rocksdb/commit/fe6b2365550616bed94386a63861b7a8d83e4298 improves the situation?

**Comment by zyj183247166** [comment]
Thank you very much. This issue can be closed. Everything will be fine and nothing will be changed. You have your viewpoint, but i will also insist my viewpoint. 
Anyway, thank you very much.

**Comment by adamretter** [comment]
@zyj183247166 Your approach does not seem very constructive now. I am trying to work though the issue with you, so that we can come to the best conclusion. I would appreciate your feedback on my test project and CI output and also of my suggested change? I have also put time and effort in to try and understand what you are communicating and to try and address any issue that you are reporting. I would welcome continuation until we have a sure resolution.

**Comment by zyj183247166** [comment]
Thank you. But i have no more words. Everything that i want to convey has already been said.
Thank you all the same.

**Comment by zyj183247166** [comment]
More,it  is unintentional that i give comment as below
"
Thank you very much. This issue can be closed. Everything will be fine and nothing will be changed. You have your viewpoint, but i will also insist my viewpoint.
Anyway, thank you very much.
"
Why i comment as this? it is because of my so so English. I wrongly understand your words "I put together an experimental change. Do you feel that this adamretter@fe6b236 improves the situation?"
Your real meaning is that you give a commit advice.
But because of my so so English, i wrongly understand your words as that you have experiments on three platforms and your meaning is  that nothing will be changed.
Just because of this misunderstand, i wrongly think that you think little of my effort and my advoice.
So i give a comment as above.
Really sorry. It is my English problem.
Pray for forgiveness.

**Comment by zyj183247166** [comment]
The added codes,
      "
      final File parentDir = new File(tmpDir);
      if (!parentDir.exists()) {
        throw new RuntimeException("Directory: " + parentDir.getAbsolutePath()
            + " does not exist!");
      }
      temp = new File(parentDir, jniLibraryFileName);
      "
should modify the last line " temp = new File(parentDir, jniLibraryFileName);" as "temp = new File(tmpDir, jniLibraryFileName);"
Because a File class can not be a parameter of File constructor. The first parameter should be a String.

**Comment by zyj183247166** [comment]
@adamretter

**Comment by adamretter** [comment]
@zyj183247166 We are using Java language level 7. It does allow a File object to be the first argument to constructing another File object -
https://docs.oracle.com/javase/7/docs/api/java/io/File.html#File(java.io.File,%20java.lang.String)

**Comment by zyj183247166** [comment]
@adamretter Ok. I get it.
