### ISSUE TITLE
CircleCI test passes even there's failed test

### ISSUE THREAD

**Issue by jay-zhuang** [facebook/rocksdb#7146]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
For example #7140 introduces a few test failure, but CircleCI test still passes:
https://app.circleci.com/pipelines/github/facebook/rocksdb/2447/workflows/39de8b0b-48f2-4c4f-82e7-5f3cda94a0ce/jobs/9322/steps

### Actual behavior
CircleCI build should fail.

**Comment by siying** [comment]
I observed the same issue once but didn't figure out the reason. It does print out
```
Seq	Host	Starttime	JobRuntime	Send	Receive	Exitval	Signal	Command
91	:	1594869192.315	     0.310	0	0	0	6	./compaction_job_test
197	:	1594869206.591	     0.174	0	0	0	6	./timer_test
```
But it didn't terminate. I suspect that these lines have a bug somewhere: https://github.com/facebook/rocksdb/blob/master/Makefile#L853-L856

But I didn't find out after some debugging.

**Comment by jay-zhuang** [comment]
Thanks @siying for the quick fix.
