### ISSUE TITLE
Mention 'compaction_readahead_size' in 'Whats new in rocksdb 4.0.0'

### ISSUE THREAD

**Issue by stephan-hof** [facebook/rocksdb#715]
Hi I have seen that you release rocksdb 4.0

would be nice if you can mention the new 'compaction_readahead_size' option in the "HISTORY.md" file.
If found it accidentally by calling diff on the include directory between 3.13 and 4.0

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
