### ISSUE TITLE
Bug in MultiRead() coalescing (introduced 4fc216649d #6446) (pull request in #6979)

### ISSUE THREAD

**Issue by jevolk** [facebook/rocksdb#7155]
I opened a pull request at #6979 describing and fixing a bug which makes the much anticipated and fabulous `MultiRead()` feature unusable in the 6.10 release. Since then this bug has also been cut into every 6.11.x release and that's not good folks! In case a PR without an associated issue gets lost down the cracks between github and phabricator I'm opening this here.

Please follow up on this, thanks.

**Comment by cheng-chang** [comment]
@jevolk thanks for catching this. The bug won't cause correctness bug. The problem is it may merge all the requests into one big request even if the requests are not overlapped.
