### ISSUE TITLE
Tailing iterator is not working in Java

### ISSUE THREAD

**Issue by gowthamgutha** [facebook/rocksdb#7169]
### Expected behavior
All the elements, whatever are put in the other thread should get printed (similar to `tail -f` on a file), blocking if necessary, when there are no elements.
### Actual behavior
Only the elements that are put within the sleep interval of `1 sec` are getting printed.
### Steps to reproduce the behavior
```java
        Thread t = new Thread(() -> {
            for (int i = 0; i < 1000; i++) {
                try {
                    System.out.println("Putting " + i);
                    rocksDB.put(("key " + i).getBytes(), ("value " + i).getBytes());
                    Thread.sleep(100);
                } catch (InterruptedException | RocksDBException e) {
                    e.printStackTrace();
                }
            }
        }, "Putting thread");
        t.start();

       Thread.sleep(1000); // wait for sometime

       ReadOptions readOptions = new ReadOptions();
       readOptions.setTailing(true);
       try (RocksIterator rocksIterator = rocksDB.newIterator(readOptions)) {
            for (rocksIterator.seekToFirst(); rocksIterator.isValid(); rocksIterator.next()) {
                System.out.println(new String(rocksIterator.key()) + " = " + new String(rocksIterator.value()));
            }
        }

        t.join();

```

If the problem is calling the `seekToFirst()` that creates a snapshot, how is it possible to read from beginning of iterator? 
Moreover, calling `next()` without `seek()` or `seekToFirst()` produces error that crashes the JVM.
Is not `next()` supposed to block, if there are no elements?
What difference does it make setting `tailing` to `true` or `false`?

**Comment by asad-awadia** [comment]
>If the problem is calling the seekToFirst() that creates a snapshot, how is it possible to read from beginning of iterator?

yes exactly - i have the same question - the whole point of tailing iterator is to not have seqnum snapshot - but seekToFirst is required to use an iterator and it creates a seqnum snapshot

@ajkr @pdillinger

**Comment by asad-awadia** [comment]
@ajkr @pdillinger friendly ping for help here

**Comment by ajkr** [comment]
> If the problem is calling the seekToFirst() that creates a snapshot, how is it possible to read from beginning of iterator?
> ...
> Is not next() supposed to block, if there are no elements?

The expectation appears incorrect. `Next()` is supposed to advance according to the state of the DB at the time it is called. Once it reached the end of all keys (`Valid() == false`), `Next()` cannot be called.

> What difference does it make setting tailing to true or false?

If it were false, `Next()` would advance according to a particular sequence number of the DB. Since it's true, `Next()` should advance according to the DB's latest state.

**Comment by asad-awadia** [comment]
@ajkr in what situations will next miss data values?

**Comment by ajkr** [comment]
> @ajkr in what situations will next miss data values?

An expected situation where it misses a newly inserted key-value is when the new key comes before the iterator's current key, according to the comparator. The expected behavior in the description (behave like `tail -f`) is also incorrect on this point: a tailing iterator uses comparator-based ordering, not insertion time based ordering.

**Comment by asad-awadia** [comment]
@ajkr any distinction for what data is in the memtable/sstable etc? or all data will be visible?

**Comment by ajkr** [comment]
All data ahead of the iterator will be visible by calling `Next()`

**Comment by asad-awadia** [comment]
@ajkr thanks for all your help

```
val emptyByte = byteArrayOf()
    RocksDB.loadLibrary()
    val options = Options().setCreateIfMissing(true)
    val rdb = OptimisticTransactionDB.open(options, dbPath)
    val readOptions = ReadOptions()
    readOptions.setTailing(true)
    val newIterator = rdb.newIterator(readOptions)
    newIterator.seekToFirst()
    rdb.put("foo".encodeToByteArray(), emptyByte)
    rdb.put("bar".encodeToByteArray(), emptyByte)

    while (newIterator.isValid) {
        println(newIterator.key().decodeToString())
        newIterator.next()
    }
    newIterator.close()
    rdb.close()
```

this doesn't print anything - I am assuming because the seekToFirst happened before - but i would have thought that foo and bar would still be seen because it is tailing

How can i make those visible here?

**Comment by ajkr** [comment]
I think the issue here is the iterator is already invalid before any keys are added. Then, by my definition, the newly added keys are *behind* the iterator's position, not ahead of it. Can you try:

```
    ...
    rdb.put(emptyByte, emptyByte)  // A sentinel key to prevent the `seekToFirst()` from going past all keys
    newIterator.seekToFirst()
    rdb.put("foo".encodeToByteArray(), emptyByte)
    rdb.put("bar".encodeToByteArray(), emptyByte)
    ...
```

**Comment by asad-awadia** [comment]
@ajkr that worked! Thank you so much - you are the best!
