### ISSUE TITLE
Sudden memory growth during RocksDB compaction 

### ISSUE THREAD

**Issue by JeevithaK** [facebook/rocksdb#719]
Hi,

I have a rocksdb with ~280GB data and our process is running with memory limit set to 16G. Every few days, our process is getting killed by oom-killer. 
According to the heap profiles collected just before crash: ~75% of memory is used by TableIndexReader & Filter data created as a result of BackgroundCompaction.

Increasing the memory limit to 24G didn't help either. It eventually hits the limit and crashes.
Is there a way to limit the memory usage by rocksdb compaction?

Here is the list of DB options we use:
table_options.filter_policy.reset(NewBloomFilterPolicy(8, false /* use_block_based_builder */));

table_options.block_size = 8 * 1024;
table_options.block_cache = NewLRUCache(128 * 1024 * 1024);

options->min_write_buffer_number_to_merge = 3;
options->max_write_buffer_number = 5;

options->env->SetBackgroundThreads(3, Env::Priority::HIGH);
options->max_background_flushes = 3;

options->env->SetBackgroundThreads(4, Env::Priority::LOW);
options->max_background_compactions = 4;

options->level0_file_num_compaction_trigger = 8;
options->level0_slowdown_writes_trigger = 17;
options->level0_stop_writes_trigger = 24;
options->target_file_size_base = 64 * 1024 * 1024;
options->max_bytes_for_level_base = 8 * options->target_file_size_base;
options->max_bytes_for_level_multiplier = 8;
options->target_file_size_multiplier = 3;

Thanks!

**Comment by JeevithaK** [comment]
When the memory usage was climbing up, I inspected the db compaction stats. It looked like:

**Comment by igorcanadi** [comment]
I'm just about to write a wiki page on how RocksDB uses memory. Here's the short story:
1. block cache -- just a normal LRU cache that keeps the block. the size is configurable, default is 8MB
2. indexes -- you can estimate the size we need for indexes like this: (database_size / block_size) * average_key_size. Default block size is 4KB (uncompressed, so this can go down to 2KB if you have 0.5 compression ratio). I would recommend increasing this to 32KB for example. This will decrease your memory usage for indexes 8x.
3. bloom filters -- you can estimate the size of bloom filters like this: number_of_keys * bloom_bits_per_key (this will give you size in bits).

By default, max_open_files is 5000. I would recommend configuring your system such that all files are always open (which can be setup by setting max_open_files == -1) because that gives the best performance, especially on in-memory databases.

**Comment by igorcanadi** [comment]
Also, from your options I see that you set L1 size to 512MB.

    options->target_file_size_base = 64 * 1024 * 1024;
    options->max_bytes_for_level_base = 8 * options->target_file_size_base;

 We usually recommend setting L0 size to be equal to L1 size. L0 size is `write_buffer_size * level0_file_num_compaction_trigger`. So in your case, I would set write_buffer_size to 64MB. Default is 4MB.

**Comment by JeevithaK** [comment]
Hi Igor,

Really appreciate your quick response!

Few months ago, we had similar memory growth problems and we tried changing the block size to 32K. Since that resulted in performance degradation we ended up increasing the process memory limit and went back to 8K. I will change the block size to 16K and check if the performance is acceptable.

Some questions for our understanding: 
1. Since we are leaving cache_index_and_filter_blocks=false, is it fair to assume that the index and filter data brought into memory stays in memory as long as the corresponding SSTable is open?
2. In steady state, (i.e., when there are no compactions and light load of reads & writes), the memory usage of our process stays around 8 - 9GB. It is only when compaction starts (especially at L4), we see the memory spiking up. Our current hypotheses is: it is because the indexes and filters of new SSTs being created as part of the compaction and the old SSTs are both in memory. Does it sound correct?
3. Do you have any suggestions on estimating the peak memory usage which accounts for any extra memory consumption by compaction?

Thank you!

**Comment by igorcanadi** [comment]
> 1. Since we are leaving cache_index_and_filter_blocks=false, is it fair to assume that the index and filter data brought into memory stays in memory as long as the corresponding SSTable is open?

That is correct.

> 2. In steady state, (i.e., when there are no compactions and light load of reads & writes), the memory usage of our process stays around 8 - 9GB. It is only when compaction starts (especially at L4), we see the memory spiking up. Our current hypotheses is: it is because the indexes and filters of new SSTs being created as part of the compaction and the old SSTs are both in memory. Does it sound correct?

What you could do is decrease target_file_size_base. That way, each compaction should be smaller, which means the memory spikes will also be smaller. The temporary doubling of space will also have less of an effect.

> 3. Do you have any suggestions on estimating the peak memory usage which accounts for any extra memory consumption by compaction?

You could try to estimate how much percent of DB is going through the compaction. If the percent is too big, it would be better to decrease compaction size by decreasing file size.

**Comment by JeevithaK** [comment]
I will play with target_file_size_base and target_file_size_multiplier options and check if that reduces memory pressure during compaction.

Thank you!

**Comment by igorcanadi** [comment]
Hey @JeevithaK, did the additional tuning help?

**Comment by JeevithaK** [comment]
Hi Igor, I haven't gotten a chance to verify performance with the changed options. For now, we increased the memory limit of the process to get around the issue. I will update the thread after my experiments.

**Comment by abhideodhar** [comment]
@igorcanadi -

I am seeing a similar OOM issue during background compaction from L0->L1 with my rocksdb environment. I looked at your responses above and also looked at your memory usage in rocksdb wiki page - thanks for writing that :-).
https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB

But I am still unable to justify the huge memory usage by rocksdb during compaction. 
As per my calculation,

block_cache_size = 128MB.
cache_index_and_filter_blocks: 1 for my database - so there should be no extra memory used for these, it should all be within the 128MB block_cache_size limit - right?
memtable write buffers = 4 * 12MB each = 48MB 
Blocks pinned by iterators - I am not using any iterators, so I guess this will not come into picture for my scenario.

Can you please help us identify any tunable which has not been set right that could cause spike in memory usage. I would really appreciate your help.

My database size is around 150GB and my rocksdb options are:

  cache_index_and_filter_blocks: 1
  index_type: 0
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x10141578
  block_cache_size: 134217728
  block_cache_compressed: (nil)
  block_size: 16384
  block_size_deviation: 10
  block_restart_interval: 8
  filter_policy: nullptr
Options.write_buffer_size: 12582912
Options.max_write_buffer_number: 4
Options.target_file_size_base: 12582912
Options.target_file_size_multiplier: 1
Options.max_bytes_for_level_base: 100663296
Options.level_compaction_dynamic_level_bytes: 0
Options.max_bytes_for_level_multiplier: 12

Thanks!

**Comment by abhideodhar** [comment]
@igorcanadi - Igor, can you please let us know what may be wrong with our configuration above which is causing high memory usage during compaction?

**Comment by igorcanadi** [comment]
> So memory usage of index = (128Gb/16Kb)* 4Kb = 32GB.
> But does that mean that compaction will try to load this much data in memory??

It's usually advisable to keep your entire index in memory. Compaction will not load all of it, but it will load some parts + you'll have a issues with performance if your index doesn't fit in memory.

32GB is way too big for an index with 150GB database. Do your keys have to be 4KB? That's rather big.

**Comment by JeevithaK** [comment]
We changed the rocksdb block size from 8K to 32K. This did not affect the performance and our memory usage was under control.

Thanks for all the help!

**Comment by abinashkaran** [comment]
@igorcanadi is compaction scoped to a mysql table partition?
that will curb the memory need?

**Comment by igorcanadi** [comment]
I'm not sure what you mean by 'scoped'? For MyRocks questions, I would recommend posting to https://github.com/facebook/mysql-5.6/issues
