### ISSUE TITLE
double-lock in WriteImplWALOnly

### ISSUE THREAD

**Issue by byteink** [facebook/rocksdb#7197]
In WriteImplWALOnly, mutex_ is locked twice, cause deadlock.

First time:
https://github.com/facebook/rocksdb/blob/d9d190742c0a8a3d5ff0b0867383bd38c1d0f5f0/db/db_impl/db_impl_write.cc#L689

Then the second one in the call of WriteStatusCheck:
https://github.com/facebook/rocksdb/blob/d9d190742c0a8a3d5ff0b0867383bd38c1d0f5f0/db/db_impl/db_impl_write.cc#L838

**Comment by zhichao-cao** [comment]
Hi @byteink , you are right, will create a PR to fix it. Thanks for pointing out it!
