### ISSUE TITLE
L6 level files has deletion entries

### ISSUE THREAD

**Issue by koldat** [facebook/rocksdb#7204]
When using manual compactFile deleted entries are sometimes kept even on L6. There cannot be a file that overlays this (there is no L7) so why this happens?

### Expected behavior

No deletion entries on L6.

### Actual behavior

See that I already got to situation that I have deletions on L6. If I compact it manually (compactFile) it produces again SST with deletions. What is the reason?

2020/07/30-06:36:30.791116 7f3c2b5fc700 [mpaction/compaction_job.cc:1671] [ooo] [JOB 0] Compacting 1@6 files to L6, score -1.00
2020/07/30-06:36:30.791129 7f3c2b5fc700 [mpaction/compaction_job.cc:1675] [ooo] Compaction start summary: Base version 90 Base level 6, inputs: [44737(113MB)]
2020/07/30-06:36:30.791163 7f3c2b5fc700 EVENT_LOG_v1 {"time_micros": 1596090990791147, "job": 0, "event": "compaction_started", "compaction_reason": "ManualCompaction", "files_L6": [44737], "score": -1, "input_data_size": 118593177}
2020/07/30-06:37:02.708099 7f3c2b5fc700 [mpaction/compaction_job.cc:1350] [ooo] [JOB 0] Generated table #44758: 34735886 keys, 118593177 bytes
2020/07/30-06:37:02.708201 7f3c2b5fc700 EVENT_LOG_v1 {"time_micros": 1596091022708156, "cf_name": "ooo", "job": 0, "event": "table_file_creation", "file_number": 44758, "file_size": 118593177, "table_properties": {"data_size": 117769918, "index_size": 2538750, "index_partitions": 616, "top_level_index_size": 32308, "index_key_is_user_key": 0, "index_value_is_delta_encoded": 0, "filter_size": 0, "raw_key_size": 1389435440, "raw_average_key_size": 40, "raw_value_size": 1067435819, "raw_average_value_size": 30, "num_data_blocks": 47822, "num_entries": 34735886, **"num_deletions": 17367943**, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "", "column_family_name": "ooo", "column_family_id": 6, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "ZSTD", "compression_options": "window_bits=-14; level=3; strategy=0; max_dict_bytes=16384; zstd_max_train_bytes=262144; enabled=0; ", "creation_time": 1583199056, "oldest_key_time": 0, "file_creation_time": 1596090990}}
2020/07/30-06:37:02.786553 7f3c2b5fc700 [mpaction/compaction_job.cc:1416] [ooo] [JOB 0] Compacted 1@6 files to L6 => 118593177 bytes
2020/07/30-06:37:02.793785 7f3c2b5fc700 (Original Log Time 2020/07/30-06:37:02.793079) [mpaction/compaction_job.cc:765] [ooo] compacted to: files[1 3 24 121 0 0 156] max score 1.00, MB/sec: 3.7 rd, 3.7 wr, level 6, files in(0, 1) out(1) MB in(0.0, 113.1) out(113.1), read-write-amplify(0.0) write-amplify(0.0) OK, records in: 34735886, **records dropped: 0** output_compression: ZSTD
2020/07/30-06:37:02.793802 7f3c2b5fc700 (Original Log Time 2020/07/30-06:37:02.793124) EVENT_LOG_v1 {"time_micros": 1596091022793107, "job": 0, "event": "compaction_finished", "compaction_time_micros": 31918061, "compaction_time_cpu_micros": 22437551, "output_level": 6, "num_output_files": 1, "total_output_size": 118593177, "num_input_records": 34735886, "num_output_records": 34735886, "num_subcompactions": 1, "output_compression": "ZSTD", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [1, 3, 24, 121, 0, 0, 156]}

**Comment by siying** [comment]
Either this file is trivial moved from L0 all the way to L6, or some snapshot prevents those delete records from removed in compactions. Think about whether you have very old snapshots that didn't get released.

**Comment by koldat** [comment]
Yes it is most likely snapshot. I still do not understand why snapshot would be an issue. Compaction is creating new files with sequence greater then snapshot and current files are held because of snapshot. So why it should be keeping delete records when merging into L6? Maybe I missed something around sequences, that is not obvious to me.

Flow is that I do a lot of deletes of existing records and want to compact these ingested delete files asap. So I call compact to L6. It cannot be trivial move as I am deleting existing records. Compaction happens but L6 file has deleted records (maybe bc of snapshot that existed during compaction). After some time file is compacted again by some process finding this type of files.

It is just not necessary I think. It would be great if you can give me some hint why snapshot matters. 

Thanks

**Comment by siying** [comment]
> Yes it is most likely snapshot. I still do not understand why snapshot would be an issue. Compaction is creating new files with sequence greater then snapshot and current files are held because of snapshot. So why it should be keeping delete records when merging into L6? Maybe I missed something around sequences, that is not obvious to me.
> 
> Flow is that I do a lot of deletes of existing records and want to compact these ingested delete files asap. So I call compact to L6. It cannot be trivial move as I am deleting existing records. Compaction happens but L6 file has deleted records (maybe bc of snapshot that existed during compaction). After some time file is compacted again by some process finding this type of files.
> 
> It is just not necessary I think. It would be great if you can give me some hint why snapshot matters.
> 
> Thanks

Snapshot doesn't hold any file. Instead, older version of a key is kept so that the snapshot can read it. If an older key is kept, then a later delete would need to be kept too.

**Comment by koldat** [comment]
Ok. I thought it works similar way as iterators.  Then behavior makes sense. Thanks for making it clear for me.
