### ISSUE TITLE
Eviction Statistics for Index and Filter Blocks are broken

### ISSUE THREAD

**Issue by sahibpandori** [facebook/rocksdb#7206]
Due to side effects of the following pull requests, the block cache eviction metrics for both index and filter blocks are broken. 
- https://github.com/facebook/rocksdb/pull/5298
- https://github.com/facebook/rocksdb/pull/5504

I'm wondering if these will be fixed anytime soon or if there's an alternative metric/methodology I could use to estimate memory usage of block cache? Thanks!

**Comment by zhichao-cao** [comment]
Hi @ltamasi , you may have more context on this issue.

**Comment by ltamasi** [comment]
We don't have a specific ETA for the eviction stats at the moment but if you're just curious about the amount of memory used by the block cache, you can call `GetUsage` on the `Cache` object as described here: https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB#block-cache . This is also available as the `rocksdb.block-cache-usage` DB property.

**Comment by riversand963** [comment]
Looks like the eviction counters in stats are not available yet.

**Comment by ltamasi** [comment]
These stats are no longer supported as of RocksDB 8.0 but we do have a DB property `rocksdb.block-cache-entry-stats` that provides a per-block type breakdown of cache usage.
