### ISSUE TITLE
rocksdb 6.11.4 building failed

### ISSUE THREAD

**Issue by darionyaphet** [facebook/rocksdb#7217]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

When I building rocksdb in gcc version 4.8.5 and Red Hat 4.8.5. It's report :

```
/usr/local/lib/libgflags_nothreads.a(gflags.cc.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
```

**Comment by siying** [comment]
No idea why it happens. How did you build gflags? Download from github and build?
Also, unless you run tests or benchmark, gflags should not be needed to build RocksDB. Set ROCKSDB_DISABLE_GFLAGS=1 for GNU make and -DWITH_GFLAGS=0 for cmake.

**Comment by YanB25** [comment]
Same error, but a slightly different message.
```
/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value

```

**Comment by adamretter** [comment]
@YanB25 Do you see the same issue with newer RocksDB versions?

**Comment by YanB25** [comment]
@adamretter Hi, I tried both master branch and `v6.15.2` and they both failed with the same error. Thanks!

**Comment by adamretter** [comment]
@YanB25 Okay thanks. Given a clean Ubuntu 18.04 install, can you tell me what commands you run to setup the system and build RocksDB. I can then try and reproduce your issue.

**Comment by YanB25** [comment]
@adam-singer Thank you very much! Firstly I'm not sure whether a conflict version of `gflag` has been installed in the server. I was wondering if I could give priority to the `gflag` installed by `apt` in the building process.

Here's my command to build RocksDB

``` bash
git clone <this repo>
sudo apt install libgflags-dev
cd build; cmake ..; make -j
```

I also tried running `make -j` in the project root.

**Comment by adamretter** [comment]
@YanB25 So I started with a clean Ubuntu 18.04.5 Server Install and from there did the following setup:

```
sudo apt-get update && sudo apt-get -y dist-upgrade
sudo apt-get -y install clang make cmake
sudo update-alternatives --config c++
sudo update-alternatives --config cc
sudo update-alternatives --config c89
sudo update-alternatives --config c99
```

Which yielded the following installed versions:
```
$ cc --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

$ c++ --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

$ make --version
GNU Make 4.1

$ cmake --version
cmake version 3.10.2
```

I then installed all the optional library dependencies for building RocksDB:
```
sudo apt-get -y install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev
```

I then attempted to build the RocksDB source code using Clang:
```
mkdir code && cd code
git clone --single-branch --branch=master https://github.com/facebook/rocksdb.git
cd rocksdb
mkdir build && cd build
cmake ..
make
```

This eventually yielded an error during one of the linking processes. However the error is different to yours:

```
...

[ 99%] Building CXX object db_stress_tool/CMakeFiles/db_stress.dir/db_stress_test_base.cc.o
[100%] Building CXX object db_stress_tool/CMakeFiles/db_stress.dir/db_stress_shared_state.cc.o
[100%] Building CXX object db_stress_tool/CMakeFiles/db_stress.dir/db_stress_gflags.cc.o
[100%] Building CXX object db_stress_tool/CMakeFiles/db_stress.dir/no_batched_ops_stress.cc.o
[100%] Linking CXX executable db_stress
CMakeFiles/db_stress.dir/db_stress_driver.cc.o: In function `std::__atomic_base<unsigned int>::is_lock_free() const':
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/atomic_base.h:354: undefined reference to `__atomic_is_lock_free'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
db_stress_tool/CMakeFiles/db_stress.dir/build.make:330: recipe for target 'db_stress_tool/db_stress' failed
make[2]: *** [db_stress_tool/db_stress] Error 1
CMakeFiles/Makefile2:8218: recipe for target 'db_stress_tool/CMakeFiles/db_stress.dir/all' failed
make[1]: *** [db_stress_tool/CMakeFiles/db_stress.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I will investigate a little further and see what I can find...

**Comment by siying** [comment]
> @adamretter Thank you very much! Firstly I'm not sure whether a conflict version of `gflag` has been installed in the server. I was wondering if I could give priority to the `gflag` installed by `apt` in the building process.
> 
> Here's my command to build RocksDB
> 
> ```shell
> git clone <this repo>
> sudo apt install libgflags-dev
> cd build; cmake ..; make -j
> ```

For a long time, I wasn't able to build RocksDB with libgflags fetched from apt. Not sure why. What I usually do is to download source code of libgflags, build and install. It's usually from a different error though. But I'm curious if you do the same, whether it would work.

**Comment by adamretter** [comment]
So the issue I am seeing, i.e.:
```
[100%] Linking CXX executable db_stress
CMakeFiles/db_stress.dir/db_stress_driver.cc.o: In function `std::__atomic_base<unsigned int>::is_lock_free() const':
/usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/bits/atomic_base.h:354: undefined reference to `__atomic_is_lock_free'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Seems to be some sort of issue with Clang vs GCC, most of the advice I have found seems to suggest to link against `libc++` instead of `libstdc++` when compiling with clang.

I have attempted this by installing further LLVM/Clang dependencies:

```
sudo apt-get -y install "libc++-dev" "libc++1" "libc++abi1" "libc++abi-dev"
```

And then re-attempting to build by running:
```
rmdir code/rocksdb/build
mkdir code/rocksdb/build && cd code/rocksdb/build
CXXFLAGS="-stdlib=libc++" cmake ..
make
```

This now leaves me with what appears to be a gflags related error:
```
[ 29%] Linking CXX executable hash_table_bench
CMakeFiles/hash_table_bench.dir/utilities/persistent_cache/hash_table_bench.cc.o: In function `main':
/home/aretter/code/rocksdb/utilities/persistent_cache/hash_table_bench.cc:278: undefined reference to `google::SetUsageMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)'
librocksdb.so.6.16.0: undefined reference to `google::FlagRegisterer::FlagRegisterer<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >(char const*, char const*, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/hash_table_bench.dir/build.make:96: recipe for target 'hash_table_bench' failed
make[2]: *** [hash_table_bench] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/hash_table_bench.dir/all' failed
make[1]: *** [CMakeFiles/hash_table_bench.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

@siying I will try uninstalling the apt version of gflags and building one from source...

**Comment by adamretter** [comment]
After uninstalling the apt version of gflags (2.2.1-1 https://packages.ubuntu.com/bionic/libgflags-dev), I have then built and installed version 2.2.2 of gflags from source and see the same error as reported by @YanB25.

My process for installing gflags was:
```
cd ~/code
wget -O gflags-2.2.2.tar.gz https://github.com/gflags/gflags/archive/v2.2.2.tar.gz
tar zxvf gflags-2.2.2.tar.gz
mkdir gflags-2.2.2/build && cd gflags-2.2.2/build
CXXFLAGS="-stdlib=libc++" cmake ..
make
sudo make install
```

The error I now see is:
```
...

[ 29%] Building CXX object CMakeFiles/rocksdb-shared.dir/third-party/folly/folly/synchronization/WaitOptions.cpp.o
[ 29%] Linking CXX shared library librocksdb.so
/usr/bin/ld: /usr/local/lib/libgflags_nothreads.a(gflags.cc.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgflags_nothreads.a(gflags_reporting.cc.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib/libgflags_nothreads.a(gflags_completions.cc.o): relocation R_X86_64_32S against symbol `_ZN3fLS25FLAGS_tab_completion_wordE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
clang: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/rocksdb-shared.dir/build.make:7559: recipe for target 'librocksdb.so.6.16.0' failed
make[2]: *** [librocksdb.so.6.16.0] Error 1
CMakeFiles/Makefile2:2996: recipe for target 'CMakeFiles/rocksdb-shared.dir/all' failed
make[1]: *** [CMakeFiles/rocksdb-shared.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

My initial guess is that RocksDB CMake is trying to build a shared library, but that I have static gflags library installed... I will attempt to build a shared gflags library and try building RocksDB again.

**Comment by adamretter** [comment]
So I also installed also the gflags shared library from source code by doing the following:

```
rm -rf ~/code/gflags-2.2.2/build
mkdir ~/code/gflags-2.2.2/build && cd ~/code/gflags-2.2.2/build
CXXFLAGS="-stdlib=libc++" cmake -DBUILD_SHARED_LIBS=ON ..
make
sudo make install
```

I now see both static and shared libgflags libraries in `/usr/local/lib/`:
```
ls -la /usr/local/lib/libgflags*
-rw-r--r-- 1 root root 519538 Jan  9 19:59 /usr/local/lib/libgflags.a
lrwxrwxrwx 1 root root     16 Jan  9 21:17 /usr/local/lib/libgflags.so -> libgflags.so.2.2
lrwxrwxrwx 1 root root     18 Jan  9 21:17 /usr/local/lib/libgflags.so.2.2 -> libgflags.so.2.2.2
-rw-r--r-- 1 root root 404184 Jan  9 21:17 /usr/local/lib/libgflags.so.2.2.2
-rw-r--r-- 1 root root 518944 Jan  9 19:59 /usr/local/lib/libgflags_nothreads.a
lrwxrwxrwx 1 root root     26 Jan  9 21:17 /usr/local/lib/libgflags_nothreads.so -> libgflags_nothreads.so.2.2
lrwxrwxrwx 1 root root     28 Jan  9 21:17 /usr/local/lib/libgflags_nothreads.so.2.2 -> libgflags_nothreads.so.2.2.2
-rw-r--r-- 1 root root 403784 Jan  9 21:17 /usr/local/lib/libgflags_nothreads.so.2.2.2
```

After that, rebuilding RocksDB using CMake worked perfectly. I think the default RocksDB CMake approach is to build all the things which include both shared and static libraries, and therefore you need both shared and static libgflags installed. My RocksDB rebuild process was as simple as:

```
rm -rf ~/code/rocksdb/build
mkdir ~/code/rocksdb/build && cd ~/code/rocksdb/build
CXXFLAGS="-stdlib=libc++" cmake ..
make
```

Which resulted in:
```
...

[100%] Building CXX object db_stress_tool/CMakeFiles/db_stress.dir/db_stress_gflags.cc.o
[100%] Building CXX object db_stress_tool/CMakeFiles/db_stress.dir/no_batched_ops_stress.cc.o
[100%] Linking CXX executable db_stress
[100%] Built target db_stress
aretter@ubuntu18:~/code/rocksdb/build$
```

@YanB25 I hope that helps?

@siying There seem to be two things at play here, each of which need special attention:
1. Building with CMake
2. Building with Clang (with CMake)

Where is best to start documenting this stuff? Should I just add it to the `INSTALL.md` or a Wiki page?

**Comment by mrambacher** [comment]
@adamretter The problem with Ubuntu "is_lock_free"  build error via CMAKE is an open PR/issue (#7060, #7828, #6995).  On Ubuntu, we need to link against -latomic.

As for the GFLAGS issue, there are potentially a few different things going on, and I am not sure which is in play.    One possibility is that we (or the linker) is grabbing the wrong library (linking against libgflags.a instead of libgflags.so).  Another is that there we are building a shared library that includes GFLAGS, which is resulting in the wrong library.

Building or using the GFLAGS shared library, or using -fPIC in the static library should both solve this issue.

**Comment by YanB25** [comment]
@adamretter Your instructions solve the problem perfectly! Thank you very much. They are very helpful.
