### ISSUE TITLE
Using TtlDB and deleteRange together

### ISSUE THREAD

**Issue by pgrivachev** [facebook/rocksdb#7218]
I tried to use `deleteRange` for rocksdb that opened with `TtlDB.open`, but it does not work for me. Is there any limitation for using them together?

### Expected behavior
`deleteRange` should delete data

### Actual behavior
`deleteRange` does not delete data when using `TtlDB.open` for opening rocksdb.

### Steps to reproduce the behavior
Run the following code:

```
public void test() throws RocksDBException {
    Options dbOptions = new Options();
    dbOptions.setCreateIfMissing(true);
    try (RocksDB db = TtlDB.open(dbOptions, "rocksdb")) {
        db.put("1".getBytes(), "value1".getBytes());
        db.put("2".getBytes(), "value2".getBytes());
        db.put("3".getBytes(), "value3".getBytes());
        db.put("4".getBytes(), "value4".getBytes());

        print(db.get("1".getBytes()));
        print(db.get("2".getBytes()));
        print(db.get("3".getBytes()));
        print(db.get("4".getBytes()));

        db.deleteRange("2".getBytes(), "4".getBytes());

        print(db.get("1".getBytes()));
        print(db.get("2".getBytes()));
        print(db.get("3".getBytes()));
        print(db.get("4".getBytes()));
    }
}

private static void print(byte[] bytes) {
    System.out.println(bytes == null ? "null" : new String(bytes));
}
```
Expected output:
```
value1
value2
value3
value4
value1
null
null
value4
```
Actual output:
```
value1
value2
value3
value4
value1
value2
value3
value4
```

**Comment by pgrivachev** [comment]
Looks like currently it is not supported for TtlDB 
https://github.com/facebook/rocksdb/blob/fdf882ded218344c136c97daf76dfb59e4bc155f/utilities/ttl/db_ttl_impl.cc#L271

**Comment by KNOEEE** [comment]
I met the same problem.
DeleteRange doesn't work for DBWithTTL.
Is it not supported yet?

**Comment by ajkr** [comment]
> Is it not supported yet?

Correct. We should make sure it returns an error.

**Comment by KNOEEE** [comment]
> Correct. We should make sure it returns an error.

Hi, I implement `DeleteRange` for `DBWithTTL` by adding a `DeleteRangeCF` method in the handler.
Can I open a pull request for it?
