### ISSUE TITLE
Slack logo is not available in login or sign up page

### ISSUE THREAD

**Issue by rahmanharoon** [facebook/rocksdb#7241]
In login or signup page the slack logo on the top is not available on your website. Hope you guys will fix..

**Comment by siying** [comment]
Which login or signup page do you mean? I don't think https://rocksdb.org/ supports user account at all.

**Comment by riversand963** [comment]
Checked on multiple browsers on different machines. I can see the logo.
Also, due to long silence, closing the issue now.
