### ISSUE TITLE
Invalid column family specified in write batch

### ISSUE THREAD

**Issue by javeme** [facebook/rocksdb#7268]
When writing to the database after dropping and re-creating the CF, the following error will be encountered:
```
Caused by: org.rocksdb.RocksDBException: Invalid column family specified in write batch
	at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-6.10.2.jar:?]
	at org.rocksdb.RocksDB.write(RocksDB.java:1586) ~[rocksdbjni-6.10.2.jar:?]
```

Reproduced code:
```java
    public static void testInsertCfAfterDropCF() throws Exception {
        String path = "rocksdb-data";
        FileUtils.deleteDirectory(new File(path));

        DBOptions options = new DBOptions();
        options.setWalDir(path);
        options.setCreateIfMissing(true);

        List<ColumnFamilyDescriptor> cfds = new ArrayList<>();
        cfds.add(new ColumnFamilyDescriptor(encode("default")));
        List<ColumnFamilyHandle> cfhs = new ArrayList<>();
        RocksDB rocksdb = RocksDB.open(options, path, cfds, cfhs);

        for (int i = 0; i < 10; i++) {
            println("==============> time " + i);

            String cf = "cf-" + i;
            ColumnFamilyDescriptor cfd = new ColumnFamilyDescriptor(encode(cf));
            println("create CF: " + cf);
            ColumnFamilyHandle cfHandle = rocksdb.createColumnFamily(cfd);

            println("write CF: " + cf);
            WriteBatch batch = new WriteBatch();
            batch.put(cfHandle, encode("key"), encode("value"));
            rocksdb.write(new WriteOptions(), batch);

            println("drop CF: " + cf);
            rocksdb.dropColumnFamily(cfHandle);
            println("close CF: " + cf);
            cfHandle.close();

            println("write CF after drop");
            try {
                rocksdb.write(new WriteOptions(), batch);
            } catch (Exception e) {
                println("error when writing CF after drop: " + e.toString());
            }

            // it's ok if reopen it
//            rocksdb.close();
//            rocksdb = RocksDB.open(options, path, cfds, cfhs);
        }
    }
```

**Comment by adamretter** [comment]
@javeme This is expected behaviour... The WriteBatch has a reference to a Column Family that you have subsequently dropped. You then try and write the WriteBatch to the database, obviously that is impossible (and therefore raises an exception) because the Column Family is no longer available.

**Comment by javeme** [comment]
@adamretter Sorry for lack of detailed description, I mean when the CF is created for the second time (when i = 1, not i=0), the new CF can't work.

**Comment by javeme** [comment]
@adamretter Is it possible to prevent it from causing the rocksdb instance to be no longer available after WriteBatch is written by mistake?

**Comment by adamretter** [comment]
@javeme Why would the WriteBatch be written by mistake? I am not sure I understand your question... Is this a different question than before?

**Comment by javeme** [comment]
@adamretter They are the same question.
Because there are multiple threads, when a thread deletes a table (a very low-frequency operation), it may be writing this table at the same time (a very high-frequency operation). At present, we use locks to solve this problem.
We get the CF handle according to the CF name for each write operation, if only the write operation is wrong but the rocksdb instance can continue to work normally, then there is no need to lock for low frequency table deletion.

**Comment by adamretter** [comment]
@javeme you need to use locks or some other synchronisation primitive in your application as you describe. Your issue is an application issue not a RocksDB issue

**Comment by javeme** [comment]
@adamretter I found this issue is the same as [Using a closed column family handle leads to persistent error](https://github.com/facebook/rocksdb/issues/592). Is there any way to solve it, I am happy to contribute code.

**Comment by adamretter** [comment]
@javeme So your problem is using a Column Family which you have closed? If so, then to me that sounds like a synchronisation isssue in your app

**Comment by javeme** [comment]
@adamretter my problem is using a CF which is dropped, and then cause persistent error of whole rocksdb instance. I agree https://github.com/facebook/rocksdb/issues/592#issuecomment-120924003 that we need to check all writes in the batch to see if they're pointing to the dropped-cf.
