### ISSUE TITLE
db_bench throws an exception when passed an invalid benchmark

### ISSUE THREAD

**Issue by mrambacher** [facebook/rocksdb#7284]
### Expected behavior

I expected an error "no such benchmark"

### Actual behavior

Got a stack trace out.

### Steps to reproduce the behavior

./db_bench --db=/tmp --use_existing_db=false --benchmarks=fred --compression_type=none

Note that I think this is a regression introduced by a recent change in 6.11 (I do not recall seeing it previously).

**Comment by akankshamahajan15** [comment]
thanks @mrambacher for raising it. @jay-zhuang Could you take a look? I think it shows data race in Timer called through StatsDumpScheduler.

**Comment by akankshamahajan15** [comment]
Update: With the latest changes, it shows error in the deletion of unique_ptr Timer.
