### ISSUE TITLE
Iterator.seek(prefix) returning different response pre/post restart.

### ISSUE THREAD

**Issue by uditsharma** [facebook/rocksdb#7318]
> I am using **rocksdbjni-6.11.4**.  Seek results in returning different result pre/post restart.

Code i am using to replicate.
           
`package rocksdb;

import org.rocksdb.*;

public class RocksExperiment {

    public static void main(String[] args) throws RocksDBException {
        RocksDB.loadLibrary();
        String path = "/home/learning/rocks";
        RocksDB db = getDB(path);
        createDataIfMissing(db);
        validate(db);
        db.close();
    }

    private static void validate(RocksDB db) throws RocksDBException {

        System.out.println("*********** Try seek(jris) & iterate ***************");
        try (RocksIterator it = db.newIterator(new ReadOptions());) {
            for (it.seek("jris".getBytes()); it.isValid(); it.next()) {
                System.out.println(new String(it.key()) + " : " + new String(it.value()));
            }
        }

    }

    private static void createDataIfMissing(RocksDB db) throws RocksDBException {
        if (db.get("krish".getBytes()) == null) {
            db.put("krish".getBytes(), "sharma".getBytes()); // < 8
            db.put("krish_x".getBytes(), "sharma".getBytes()); // < 8
            db.put("krish_xs".getBytes(), "sharma".getBytes()); // < 8
            db.put("krish_xssz2".getBytes(), "sharma".getBytes()); // < 8
        }
    }

    static RocksDB getDB(String path) throws RocksDBException {
        Options options = new Options();
        options.setCreateIfMissing(true);
        options.setCreateMissingColumnFamilies(true);
        options.setComparator(BuiltinComparator.BYTEWISE_COMPARATOR);
        //compaction
        options.setCompactionStyle(CompactionStyle.LEVEL);
        options.setCompactionPriority(CompactionPriority.MinOverlappingRatio);
        options.setLevelCompactionDynamicLevelBytes(true);

        BlockBasedTableConfig blockBasedTableConfig = new BlockBasedTableConfig();

        final BloomFilter bloomFilter = new BloomFilter(10, false);
        blockBasedTableConfig.setFilterPolicy(bloomFilter);

        options.setTableFormatConfig(blockBasedTableConfig);
        options.useFixedLengthPrefixExtractor(4);

        return RocksDB.open(options, path);
    }
}
`

### Expected behavior
Pre and Post restart i was expecting iterator.seek(prefix) to return the same result.

*********** Try seek(jris) & iterate ***************
krish : sharma
krish_x : sharma
krish_xs : sharma
krish_xssz2 : sharma

### Actual behavior
**Pre Restart: Fresh Run**

*********** Try seek(jris) & iterate ***************
krish : sharma
krish_x : sharma
krish_xs : sharma
krish_xssz2 : sharma

**Post Restart : Second Run**
*********** Try seek(jris) & iterate ***************
EMPTY

### Steps to reproduce the behavior:
I am attaching the main program which we can use to run it multiple time to replicate the issue.
https://gist.github.com/uditsharma/8f8188c2ce52918045bc934562074a3a

**Comment by pdillinger** [comment]
Iterating outside the prefix (with default options) is undefined behavior. https://github.com/facebook/rocksdb/wiki/Prefix-Seek#manual-prefix-iterating  You probably want auto_prefix_mode.
