### ISSUE TITLE
[Java] initializing the native library on Android fails

### ISSUE THREAD

**Issue by fourlastor** [facebook/rocksdb#734]
Hello,

I'm not sure if you're already supporting Android as a platform (I'm guessing yes because a quick search shows there are precompiler directives to check `OS_ANDROID`).

Basically trying to initialize the native library via `RocksDB.loadLibrary()` fails at https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/NativeLibraryLoader.java#L101 due to missing `Files`, `File#toPath` and `StandardCopyOption`.

I'm using the [jar in Maven](http://search.maven.org/#artifactdetails%7Corg.rocksdb%7Crocksdbjni%7C3.13.1%7Cjar).

**Comment by adamretter** [comment]
Okay so those classes came in NIO.2 which means you will need at least Java 7. I am not familiar with Android development, so do you have Java 7 SDK classes available?

**Comment by fourlastor** [comment]
Android doesn't have those classes in nio https://developer.android.com/reference/java/nio/package-summary.html

**Comment by adamretter** [comment]
Hmm so it seems like Android is based on and has stayed with JDK 6. Unfortunately the Rocks Java API requires at least Java 7.

**Comment by fourlastor** [comment]
Would it be feasible to switch to something like [Okio](https://github.com/square/okio)? Or would it be too much of a dependency?

**Comment by adamretter** [comment]
@fourlastor For reference, can I ask which is the minimum Android API level that you are targeting?

**Comment by fourlastor** [comment]
It was a test project just to try out rocksdb and it was some months ago, but I usually just leave the last SDK for those so 20+ must likely. If you want I can put up a quick repository tomorrow and check?

**Comment by adamretter** [comment]
@fourlastor I am trying to establish if we want to support Android with RocksDB, and is so which API level we should target. Do you have any instructions for building Rocks with Android NDK?

**Comment by fourlastor** [comment]
No I don't, but it literally fails while copying a file while instantiating the library because it uses nio which is a Java 7 library. It would be necessary only to use Java 6 API to copy the file to support it I suppose

**Comment by chakrit** [comment]
@adamretter have you come to any conclusion?

**Comment by adamretter** [comment]
I don't think this is straight forward. We would first need to compile RocksDB C++ code for Android using the NDK. After that, we could make some small changes to ] the Java part to support Android. However, before all of that I wan't to make sure the other Rocks developers want to actually support Android. Let me get back to you...

**Comment by adamretter** [comment]
@chakrit @fourlastor Okay so there is an appetite to support Android. I will see if I can't get something working in the near future...

**Comment by chakrit** [comment]
@adamretter nice, thanks!

Simple and FAST key-value DB like this are very very good as the final persistence layer for mobile because of the speed limitation. Apps shouldn't need to parse 100 SQL statements to display its first views with cached data when user taps the app icon. Also this just helps with any UI interactivity in general.

Also applications may crash or be killed anytime so we need something that can do small incremental persistence (many PUTs + flush) instead of the traditional dump-entire-model-layer-to-JSON approach. RocksDB fits the use case perfectly and  is also especially well-suited to this task due to the widespread use of solid state drives on mobile devices.

Hope this helps explains my use case a bit. Don't want to use any random fork floating around the interwebs if I can help it. And LevelDB just isn't fast enough (you still need to be consciously careful about it, for it to be fast.)

I can help test as soon as there is something released officially.

**Comment by fourlastor** [comment]
@adamretter thanks for following up!

**Comment by adamretter** [comment]
@chakrit if there is something already in existence, can you please point me at "the random fork floating around the interwebs"?

**Comment by chakrit** [comment]
@adamretter I remember a blog post detailing how to port to android but I can't find it anymore. However there is this https://github.com/fusesource/rocksdbjni/blob/master/rocksdb.patch going on which maybe of interest.

**Comment by adamretter** [comment]
Huh! That's really interesting, that is an entirely different implementation separate from this one. I also see that it hasn't been updated since 2013. Do you know that that code compiles on Android?

**Comment by chakrit** [comment]
@adamretter Yep, 2013. I havn't try to compile it from source but the artifact of the same thing on maven is non-working. Complains about `librocksdb.so` or something.

**Comment by mvayngrib** [comment]
+1

**Comment by MoNTE48** [comment]
+1

**Comment by fourlastor** [comment]
@adamretter maybe it's possible to use https://github.com/facebook/SoLoader to load the .so file on android and that should be enough? never used it but I just noticed it seems like a possible quick solution

**Comment by adamretter** [comment]
@fourlastor I don't think the problem is with loading the SO file. Rather the issue is that the SO file is compiled for Linux and not Android.

**Comment by fourlastor** [comment]
@adamretter partially, the problem is that you can't load it right now so you can't really tell (at least with the current version), not that I'm saying it will work if you remove the nio usages, but I'd give it a try once that's done :) 

Don't have a lot of experience working on rocksdb and I tried a bit today (failing), any tips on how to set it up? Would be up to do some tries and possibly a PR if that goes well!

**Comment by adamretter** [comment]
@fourlastor The problem is not really the Java part of RocksDB, that is easily addressed. The hard part is that the Java code is just a lightweight wrapper around RocksDB proper which is written in C++ and would need to be ported correctly to Android using the Android NDK.

**Comment by fourlastor** [comment]
Oh, I see what you mean now.

**Comment by tomharper** [comment]
anyone working on this?

**Comment by adamretter** [comment]
@tomharper not that I know of

**Comment by 502904420** [comment]
You can load it using "System.oadLibrary("rocksdbjni")",it works well in Android;But first, you should copy "librocksdbjni.so" to library path of app

**Comment by 502904420** [comment]
You can load it using "System.loadLibrary("rocksdbjni")",it works well in Android;But first, you should copy "librocksdbjni.so" to library path of app

**Comment by adamretter** [comment]
See - https://github.com/facebook/rocksdb/issues/1193
