### ISSUE TITLE
[BUG] core dumped on vmull_p64 in crc32c_arm64.cc

### ISSUE THREAD

**Issue by meilihao** [facebook/rocksdb#7363]
### Expected behavior
no error
### Actual behavior
core dumped
### Steps to reproduce the behavior
env:
os: ubuntu 16.04.6
cpu: Phytium ft2000plus
rocksdb: 6.11.4

mystep:
```bash
# g++ c_simple_example.cc -o test -std=c++11 -lpthread -lrocksdb -ldl -lrt -lsnappy -lgflags -lz -lbz2 -lzstd
# ./test
# Illegal instruction (core dumped)
```

gdb log:
![2020-09-09_15-18-21](https://user-images.githubusercontent.com/4382586/92567139-d3830880-f2af-11ea-9479-c4fa5e57e068.png)

**Comment by meilihao** [comment]
`put a big value` will get the same error:
```c++
int main() {
  DB* db;
  Options options;
  // Optimize RocksDB. This is the easiest way to get RocksDB to perform well
  options.IncreaseParallelism();
  options.OptimizeLevelStyleCompaction();
  // create the DB if it's not already present
  options.create_if_missing = true;

  // open DB
  Status s = DB::Open(options, kDBPath, &db);
  assert(s.ok());

  // Put key-value
  s = db->Put(WriteOptions(), "key1", std::string(1023,'c')); // core dump here
  assert(s.ok());

  delete db;

  return 0;
}
```

gdb:
![截图_2020-09-09_18-44-57](https://user-images.githubusercontent.com/4382586/92589070-96793f00-f2cc-11ea-9201-457dd1814212.png)

**Comment by siying** [comment]
If you store the result of std::string(1023,'c') into a variable and pass in the variable, would you see the same problem?

**Comment by meilihao** [comment]
@siying I tried, core dumped too.

**Comment by meilihao** [comment]
@guyuqi can you fix this?

**Comment by guyuqi** [comment]
The PR #7233 is to fix this issue.

It needs to add PMULL/VPULL runtime-check to detect whether vmall instruction is supported or not.

**Comment by siying** [comment]
@meilihao can you confirm that https://github.com/facebook/rocksdb/pull/7233 would fix your issue?

**Comment by meilihao** [comment]
@siying It works. At least the program has not crashed so far, I want to test more.

**Comment by meilihao** [comment]
@siying My program is still running. LGTM.

**Comment by siying** [comment]
#7233 is merged.

**Comment by halberdholder** [comment]
i came cross the same issue, thanks @meilihao @siying
