### ISSUE TITLE
Java UX: using an iterator from WriteBatchWithIndex can segfault

### ISSUE THREAD

**Issue by adammitchelldev** [facebook/rocksdb#7370]
Just a UX issue with the JNI and `WriteBatchWithIndex` that caused us a headache; RocksDB causing avoidable segfaults is annoying to debug in Java.

In this case, creating an iterator with base for a WBWI is not supported in the default configuration (`overwriteKey = false`). The C++ behaviour appears to be to return a `nullptr` when this happens, so an acceptable Java fix may be to return `null` and avoid adding a checked exception to the signature.

Another issue is that the Javadoc does not mention this limitation (where the C++ comments do), so the user is left to figure out why this segfault happens themselves.

### Expected behavior

`WriteBatchWithIndex#newIteratorWithBase(RocksIterator)` either succeeds or throws an exception (or returns null).

### Actual behavior

The method appears to succeed, but the returned object has a 0 nativeHandle, so any successive calls segfault.

### Steps to reproduce the behavior

```java
try (Options options = new Options().setCreateIfMissing(true);
     RocksDB db = RocksDB.open(options, "test");
     WriteBatchWithIndex wbwi = new WriteBatchWithIndex();
     RocksIterator base = db.newIterator();
     RocksIterator iterator = wbwi.newIteratorWithBase(base)) {
    iterator.status();
}
```

The user fix is to use `new WriteBatchWithIndex(true)`.

**Comment by riversand963** [comment]
Thanks for reporting @adammitchelldev . The behavior is indeed different, and we should fix it. Would you like to contribute a PR for this?

**Comment by adammitchelldev** [comment]
@riversand963 No problem, looks like @adamretter is already working on this area and should fix this on the way?

**Comment by riversand963** [comment]
Looks like it since @adamretter has self-assigned this issue.
