### ISSUE TITLE
[BUG/OPTIMIZE] misuse of wfe instruction on ARM

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#7376]
https://github.com/facebook/rocksdb/blob/c7432cc3c0848ad4d2a34a3eb40ad94d37477856/port/port_posix.h#L170
I don't know why using wfe instruction here to yield cpu. But refering to some literals, this instruction is possible to turn cpu off for a while. We've observed significant performance downgrade due to this op. By using `yield` instruction, 
```
asm volatile("yield"); 
```
performance could be 2x better.

I strongly encourage people who run rocksdb on arm platform to test and leave a comment.

**Comment by siying** [comment]
@guyuqi @HouBingjian @Zhiwei-Dai  any comment on this?

**Comment by Zhiwei-Dai** [comment]
I believe that's a nice choice. Folly has accepted the pr 4 years ago.
https://github.com/facebook/folly/blob/master/folly/portability/Asm.h
https://github.com/facebook/folly/commit/add5a7aeacacb050c4b0bad84aac1475fa2658c9

**Comment by siying** [comment]
@wolfkdy feel free to send a Pull Request to get it fixed.

**Comment by wolfkdy** [comment]
@siying I‘ve discussed with @HouBingjian and @Zhiwei-Dai offline as we happen to be colleagues. 
FB Folly uses `yield` to schedule cpu out, this is a way that certainly can not be wrong.
Apart from this, the op sequences on ARM which perfectly matches X86's `pause` is `"sevl; wfe"`.
The difference is `yield` schedules current thread out of the core while `sevl;wfe` will not.
**Zhiwei-Dai** made a perf of running `wfe`, `sevl;wfe`, `yield` and intel's `pause`
```
loop: 20000000
kunpeng 920
yield: 0.056s
sevl+wfe: 0.509s
wfe: >9min30s

Intel 6148
pause: 1.217s
```

It's hard to tell which one is better, `yield` or `sevl+wfe`, leave this comment for others who may also be interested.
Here let's just choose `yield`.

**Comment by Zhiwei-Dai** [comment]
In LinaroConnectVirtual2020, Martin Weidmann introduces the 2020 extensions to the A profile architecture. WFE/WFI with timeout appears in ARMv8.7. He said:
_A lot of potential usage of WFE/WFI is blocked by the unlimited time that the WFx might be asleep.
Armv8.7 introduces variants of WFE/WFI with a software specified timeout. (Specified in terms of time, not cycles)
WFET Xd / WFIT Xd
 Xd holds a 64-bit value to compare with CNTCVT_EL0
  --Generates a local event to wake the WFxT when CNTCVT_EL0 >= Xd value
  --If WFxT is woken for any reason, the count will be discarded
  --Event only applies to the PE that executes the instruction_
Reference: 
https://static.sched.com/hosted_files/lvc20/ec/Arm%20Architecture%202020%20Extensions%20-%20LVC20-214.pdf

**Comment by siying** [comment]
> @siying I‘ve discussed with @HouBingjian and @Zhiwei-Dai offline as we happen to be colleagues.
> FB Folly uses `yield` to schedule cpu out, this is a way that certainly can not be wrong.
> Apart from this, the op sequences on ARM which perfectly matches X86's `pause` is `"sevl; wfe"`.
> The difference is `yield` schedules current thread out of the core while `sevl;wfe` will not.
> **Zhiwei-Dai** made a perf of running `wfe`, `sevl;wfe`, `yield` and intel's `pause`
> 
> ```
> loop: 20000000
> kunpeng 920
> yield: 0.056s
> sevl+wfe: 0.509s
> wfe: >9min30s
> 
> Intel 6148
> pause: 1.217s
> ```
> 
> It's hard to tell which one is better, `yield` or `sevl+wfe`, leave this comment for others who may also be interested.
> Here let's just choose `yield`.

Sure. Feel free to send a PR to change to `yield`. The code was copied from folly, so it's safe to stick to what they use.

**Comment by riversand963** [comment]
#7438 is merged. Closing.
