### ISSUE TITLE
ZSTD Not included in JNI build

### ISSUE THREAD

**Issue by Downchuck** [facebook/rocksdb#738]
In Makefile there are lib.a builds for four compression libraries (libz, libbz2, libsnappy, liblz4), but the new experimental zstd is missing.

**Comment by Downchuck** [comment]
In ./build_tools/rocksdb-lego-determinator run_no_compression, ztsd is not explicitly excluded as the other compression libraries are.

**Comment by adamretter** [comment]
@downchuck you will now find that ZSTD is included in the build.
