### ISSUE TITLE
Support `CompactionFilter` function called only during flush

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#7396]
We offer a feature, `ReadOptions::read_tier = ReadTier::kMemtableTier`, for reads that access memtable only. This is naturally useful for things like application-level transaction conflict checking, where I/O is undesirable and only recent keys need to have conflict checking metadata attached in their values.

For such use cases, it makes sense to strip the conflict checking info during flush, as it won't ever be accessed on-disk due to the above read option. Furthermore, this enables easy migration to introduce conflict checking info, since it is never persisted so we don't have to worry about having a mix of SST files with/without conflict checking info in them.

A way to achieve this stripping is calling a special `CompactionFilter` function during flush. Then, the use case mentioned can be achieved by extending such a function to strip conflict checking info from the value.

There is a compatibility issue the first time this feature is used. WAL data written prior to adopting the feature would naturally not have conflict checking info. But opening the DB with this feature enabled would lead us to attempt to strip the (non-existent) conflict checking info for entries in such WALs. One idea: the function could take an argument like the flush reason, so the implementor can make the function a no-op for recovery-triggered flushes the first time they open a DB post-upgrade.

**Comment by briantkim93** [comment]
@ajkr I'm happy to get this assigned to me

**Comment by ajkr** [comment]
Actually this one was done in #8243. Sorry I forgot there was an issue associated with it.
