### ISSUE TITLE
crash : Illegal instructions  ---  in CMakeList.txt with -march=native

### ISSUE THREAD

**Issue by zgaoq123** [facebook/rocksdb#7398]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### describe
The preconditions are: The CPU instruction set of server a is different from that of server B

### Expected behavior
server B start-up successfully

### Actual behavior
Failed to start-up

### Steps to reproduce the behavior
On Linux platform，compile and generate the executable file on server A.

But the executable file starts up on server B. When B start-up, it will directly report an error of illegal instructions and core dumped.

answer:
The root cause is in rocksdb's own CMakeList.txt, is caused by the use of a compilation parameter -march = native.By default, the CPU instruction set of server A is used, but the CPU instruction set of server B is different from that of server A, resulting in a direct crash when starting on server B

**Comment by pdillinger** [comment]
You have to set the PORTABLE flag to create a binary usable on machines with different instruction subsets under the same architecture.
