### ISSUE TITLE
Corruption: Unable to read from file .log: read attempt would read beyond file bounds, with encryption enabled

### ISSUE THREAD

**Issue by areddy1213** [facebook/rocksdb#7410]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

**Comment by areddy1213** [comment]
Hi Rocksb team,
  We have with encryption enabled and on Db::Open if a .log(wal) file is partially written or unwritten, is leading to this issue.
Which is due to the fact that when we do a DB::Open() in a encryption env if the file size is zero or less than the prefix length < 2*blockSize.  it leads to this issue.

But after some time(around 1-2 hrs) the log file is gone (deleted or merged.) and it recovers from the issue.
Please explain this behaviour.

**Comment by jay-zhuang** [comment]
Thanks @areddy1213 for reporting the issue. Seems like WAL file is corrupted, can you share the WAL file? It would be great if you could provide more information on how to reproduce the issue.

**Comment by areddy1213** [comment]
Hi Jay,
   Actually the file size is empty and has no data(size zero), but when we do DB::Open(...)  in a encrypted environment, rocksdb tries to read the file and if the prefix.length() (in this case 0.) is less than 2*encryption block size. It results in this error.

**Comment by areddy1213** [comment]
When I manually try to delete this file, It results in a I/O error.

**Comment by jay-zhuang** [comment]
> When I manually try to delete this file, It results in a I/O error.

Sounds like a file system issue.
Is rocksdb running when you try to delete the WAL file?

**Comment by areddy1213** [comment]
But the actual issue is this.... The file size is empty and has no data(size zero), but when we do DB::Open(...) in a encrypted environment, rocksdb tries to read the file and if the prefix.length() (in this case 0.) is less than 2*encryption block size. It results in this error.

**Comment by areddy1213** [comment]
Also I ran db_wal_test (kSkipAnyCorruptedRecords) it is failing.

**Comment by jay-zhuang** [comment]
> But the actual issue is this.... The file size is empty and has no data(size zero), but when we do DB::Open(...) in a encrypted environment, rocksdb tries to read the file and if the prefix.length() (in this case 0.) is less than 2*encryption block size. It results in this error.

Yeah, that's one of the issue. Also it's unable to read CURRENT file: `Corruption: CURRENT file does not end with newline`. Patches are welcomed. Or you could implement your own ENV to do the encryption.

**Comment by deepakojha123** [comment]
@jay-zhuang  I have created a PR for the fix for error with zero byte WAL files with encryption. Please take a look.

**Comment by ajkr** [comment]
Fixed by #7924.
