### ISSUE TITLE
Read Performance for various workloads 

### ISSUE THREAD

**Issue by KiranCS-17** [facebook/rocksdb#7422]
Is it possible to provide the read performance benchmarks for various workloads

**Comment by mrambacher** [comment]
What workloads are you suggesting?  There are some performance results on the Wiki: https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks

**Comment by KiranCS-17** [comment]
> What workloads are you suggesting? There are some performance results on the Wiki: https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks

Read performance benchmark with complex deep nested structures with depth = 10

**Comment by ramvadiv** [comment]
Pls use forums for these kind of extended help. Pls use Github issues only for reporting suspected issues/bugs/enhancements to RocksDB.

Closing out this issue.
