### ISSUE TITLE
Missing GitHub releases

### ISSUE THREAD

**Issue by akrylysov** [facebook/rocksdb#7465]
Some of the recent versions mentioned in HISTORY.md are not tagged on GitHub, hence the releases are missing.

Can anyone tag the latest release 6.13 please?

**Comment by SixPlusZero** [comment]
Same here! I'd like the official support of secondary instance for RocksDB java use case, which should be included since 6.12 if the git commit history is correct.

**Comment by adamretter** [comment]
Not all releases listed in History.md become public releases. Some of those are point or internal releases. Only major stable milestones become public releases.

**Comment by akrylysov** [comment]
Thanks for a new release!
