### ISSUE TITLE
flaky test: db_compaction_test

### ISSUE THREAD

**Issue by jay-zhuang** [facebook/rocksdb#7471]
https://app.circleci.com/pipelines/github/facebook/rocksdb/3706/workflows/9bba0d7d-e6db-4354-a3a9-59f38d40e1f5/jobs/35800

```
[ RUN      ] DBCompactionTestWithParam/DBCompactionTestWithParam.FlushAfterIntraL0CompactionCheckConsistencyFail/0
db/db_compaction_test.cc:5349: Failure
Expected equality of these values:
  i + 1
    Which is: 10
  NumTableFilesAtLevel(0)
    Which is: 3
[  FAILED  ] DBCompactionTestWithParam/DBCompactionTestWithParam.FlushAfterIntraL0CompactionCheckConsistencyFail/0, where GetParam() = (1, true) (177 ms)
```

**Comment by jay-zhuang** [comment]
Another failure for master: https://app.circleci.com/pipelines/github/facebook/rocksdb/3671/workflows/0b18720b-58ee-4829-baa1-ea93d7ce87af/jobs/34955

**Comment by jay-zhuang** [comment]
I tried to re-run `db_compaction_test` 100 times (#7474), failed on a different test:
```
Note: Google Test filter = DBCompactionTest.DeleteFileRange
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DBCompactionTest
[ RUN      ] DBCompactionTest.DeleteFileRange
db/db_compaction_test.cc:1762: Failure
Expected: (deleted_count) > (0), actual: 0 vs 0
[  FAILED  ] DBCompactionTest.DeleteFileRange (359023 ms)
[----------] 1 test from DBCompactionTest (359023 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (359023 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DBCompactionTest.DeleteFileRange

 1 FAILED TEST
[1425/16500] DBCompactionTest.DeleteFileRange returned/aborted with exit code 1 (359036 ms)
```

https://app.circleci.com/pipelines/github/facebook/rocksdb/3757/workflows/a5fdca9d-d94a-4852-9088-03926a8c1855/jobs/36987/steps

**Comment by ajkr** [comment]
I plan to look at `DBCompactionTestWithParam/DBCompactionTestWithParam.FlushAfterIntraL0CompactionCheckConsistencyFail/*` and `DBCompactionTestWithParam/DBCompactionTestWithParam.IntraL0CompactionAfterFlushCheckConsistencyFail/*`. The `DBCompactionTest.DeleteFileRange` is still available.

**Comment by ajkr** [comment]
#7477 removed the assertions causing the `DBCompactionTestWithParam/DBCompactionTestWithParam.FlushAfterIntraL0CompactionCheckConsistencyFail/*` and `DBCompactionTestWithParam/DBCompactionTestWithParam.IntraL0CompactionAfterFlushCheckConsistencyFail/*` failures.

**Comment by jay-zhuang** [comment]
I'm unable to reproduce `DeleteFileRange()` issue again. As we haven't seen that for master branch yet. I'm going to close this issue for now.
