### ISSUE TITLE
SST File doesn't clean up

### ISSUE THREAD

**Issue by philipktlin** [facebook/rocksdb#7512]
Scenario: I ran some batch process to insert records to RocksDB.  By observation, max SST file size is ~64M.  I expected that db will continue to write to SST file until it reaches/closes to max file size, why there are some SST files with smaller file size?  After processing records, my program will remove them from RocksDB and I expect SST files will be removed or size of SST files will reduce to a very small size (<10K).  But after processing and no more inputs (compaction configured to 2 hours), I can see the total size of SST files remain over 100M in >3 hours.  Why it behaves like this? do I miss any configuration parameter to shrink SST files?

**Comment by ramvadiv** [comment]
From the issue report, most probably the compaction never ran (or deletes didn't happen). Can you use ldb/sst_dump to inspect the key/values in the SST files? 

Ref: https://github.com/facebook/rocksdb/wiki/Administration-and-Data-Access-Tool

If you can prove this is a bug in the RocksDB code, pls provide more information and open a new Issue.
