### ISSUE TITLE
use java api to report an error:org.rocksdb.RocksDBException: While open a file for random read: /eventData/20201012/db/000828.sst:  Insufficient permissions

### ISSUE THREAD

**Issue by zhousPole** [facebook/rocksdb#7537]
version：6.11.4

Problem description：
1. Our java application is started with the root account, and then the current program runner is switched to a normal user through seteuid and setegid.
2. During the program execution, when root privileges are required, the current program runner is switched to root, switch to normal user after execution.
3. Then after the program runs for a period of time, the rocksdb write fails: `org.rocksdb.RocksDBException: While open a file for random read: /eventData/20201012/db/000828.sst: Insufficient permissions` .But the owner of the view db directory belongs to an ordinary user, and the program is also run by an ordinary user, why does it prompt that the permissions are not enough?**（The code of status in `RocksDBException` is `IOError`）**
4. If our java application does not switch users to run, there is no problem if we use the root account from beginning to end
From the existing logs, we can’t tell what went wrong, because everything looks normal. How can I get more error information, or who can tell me what is causing the problem now, thank you very much！

**Comment by adamretter** [comment]
@zhousPole I think you would need to use various operating system level tools to find out where and why your permissions error is occurring. I don't think this is really related to RocksDB.

**Comment by zhousPole** [comment]
> @zhousPole I think you would need to use various operating system level tools to find out where and why your permissions error is occurring. I don't think this is really related to RocksDB.

Ok thanks, we have solved this problem。But now there is a new problem，When our JAVA application was running for about 20 hours, rockssb failed to write again, indicating that there are too many open files，
Is there a file descriptor leak in rocksdb?

**Comment by adamretter** [comment]
@zhousPole you can use the `lsof` tool to find out where the open file handles are being used...

**Comment by zhousPole** [comment]
> @zhousPole you can use the `lsof` tool to find out where the open file handles are being used...


Ok thanks, I checked the code and found that the ColumnFamilyHandle was not closed. Is it due to this reason? I have closed it now, and then observe whether the problem will occur

**Comment by adamretter** [comment]
@zhousPole I would think so, as the ColumnFamilyHandle will hold the references to the SST files that it uses.
