### ISSUE TITLE
add method to clear all data from DB (while having it opened)

### ISSUE THREAD

**Issue by alekibango** [facebook/rocksdb#755]
It might be nice to have a method to delete all db contents,
which can be runned while db is opened.   For example for unittesting.

I do not like the idea of closing DB and running rm -rf from shell, 
deleting every key from list of all keys is not very nice too.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
