### ISSUE TITLE
C:\Users\admin\AppData\Local\Temp\librocksdbjni5734698881557363843.dll cannot be deleted

### ISSUE THREAD

**Issue by xiezhaokun** [facebook/rocksdb#7557]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
C:\Users\admin\AppData\Local\Temp\librocksdbjni5734698881557363843.dll can be deleted when application shutdown

### Actual behavior
C:\Users\admin\AppData\Local\Temp\librocksdbjni5734698881557363843.dll cannot be deleted when application shutdown

**Comment by adamretter** [comment]
Typically this is a Windows issuer because the .dll is in use by some process. It could be your application, or it could be a virus scanner etc.

You can use the OpenedFilesView utility from http://www.nirsoft.net to monitor the DLL and find out which process is holding it open.
