### ISSUE TITLE
Make/build_detect_platform fails to detect installed components; needs to use FLAGS

### ISSUE THREAD

**Issue by mrambacher** [facebook/rocksdb#7565]
I found this issue with Snappy on my Mac, but it is a more general problem.

On my Mac, I have snappy installed in the normal place.  The check for build_detect_platform fails to detect it; snappy will not compile without the -std=c++11 on my machine.  Because this flag is not passed in, I cannot use snappy.  FWIW, I have snappy 1.1.8 on my machine.

A more general problem is that the check for installed components does not use the EXTRA_CXXFLAGS (and related flags).  Because these flags are not used by the build_detect_platform, anything not installed in a system/standard location cannot be detected by this script.

The EXTRA_FLAGS should be passed into the build_detect_platform script and used as a potential location for the installed components.  The installation checks compilation needs to use these flags (as well as the PLATFORM ones) when performing their compilation/check.

**Comment by jay-zhuang** [comment]
+1
(a workaround for me is using cmake, with flag `-WITHSNAPPY=1`).

**Comment by mrambacher** [comment]
Fixed by #8111
