### ISSUE TITLE
Mutex::lock in port_win is leading to serious crashes

### ISSUE THREAD

**Issue by DoktorSeltsam** [facebook/rocksdb#758]
The Member `Mutex::lock` in the windows port is implemented by a `std::unique_lock`. It is called from different threads but it is not thread safe. This may leading to crashes (when the compactions is called for example).

As a workaround i put the `std::unique_lock` in a map with thread id as key. So `Mutex` can provide a single  `std::unique_lock` for every thread its needed.

**Comment by yuslepukhin** [comment]
@DoktorSeltsam This is an oversight. getLock() method must return by value a new instance of unique_lock not a member. Unique_lock is not a subject to multi-threded access.

**Comment by yuslepukhin** [comment]
@DoktorSeltsam Thanks for reporting this. This is a serious oversight. I will re-work this. Map is probably not a good solution here.

**Comment by edouarda** [comment]
You need to use CRITICAL_SECTION and CONDITION_VARIABLE. The current code is broken. I am working on a patch as well.

**Comment by edouarda** [comment]
Have to run more tests but this work better:

```cpp
class Mutex {
 public:
  /* implicit */ Mutex(bool adaptive = false) { ::InitializeCriticalSection(&section_); }
  ~Mutex() { ::DeleteCriticalSection(&section_); }

  void Lock()
  {
    ::EnterCriticalSection(&section_);
  #ifndef NDEBUG
    locked_ = true;
  #endif
  }

  void Unlock()
  {
  #ifndef NDEBUG
    locked_ = false;
  #endif
    ::LeaveCriticalSection(&section_);
  }


  // this will assert if the mutex is not locked
  // it does NOT verify that mutex is held by a calling thread
  void AssertHeld()
  {
  #ifndef NDEBUG
    assert(locked_);
  #endif
  }

 private:
  friend class CondVar;

  CRITICAL_SECTION section_;

#ifndef NDEBUG
  bool locked_;
#endif

  // No copying
  Mutex(const Mutex&);
  void operator=(const Mutex&);
};

class CondVar {
 public:
  explicit CondVar(Mutex* mu): mu_(mu) { ::InitializeConditionVariable(&cv_); }
  ~CondVar() {} 
  void Wait()
  {
    #ifndef NDEBUG
      mu_->locked_ = false;
    #endif
      ::SleepConditionVariableCS(&cv_, &(mu_->section_), INFINITE);
    #ifndef NDEBUG
      mu_->locked_ = true;
    #endif
  }

  bool TimedWait(uint64_t expiration_time)
  {
    #ifndef NDEBUG
      mu_->locked_ = false;
    #endif

      using namespace std::chrono;

      microseconds usAbsTime(abs_time_us);
      microseconds usNow(
          duration_cast<microseconds>(system_clock::now().time_since_epoch()));
      microseconds relTimeUs =
          (usAbsTime > usNow) ? (usAbsTime - usNow) : microseconds::zero();

      const BOOL great_success = ::SleepConditionVariableCS(&cv_, &(mu_->section_), duration_cast<milliseconds>(relTimeUs).count());
      
    #ifndef NDEBUG
      mu_->locked_ = true;
    #endif

      if ((!great_success) && (GetLastError() == ERROR_TIMEOUT))
      {
    	  return true;
      }

      return false;
  }
  
  void Signal()  { ::WakeConditionVariable(&cv_); }
  void SignalAll()  { WakeAllConditionVariable(&cv_); }

 private:
  CONDITION_VARIABLE cv_;
  Mutex* mu_;
};
```

**Comment by yuslepukhin** [comment]
@edouarda The api requires microseconds sleep. std implementation at least promised that. There is a simple path under internal review that makes use std.

**Comment by edouarda** [comment]
Understood, you can indeed use _Mtx_t instead of CONDITION_VARIABLE then.

**Comment by DoktorSeltsam** [comment]
@yuslepukhin Indeed, map is not a desirable solution. It was only used to make the project work with minor local changes of the code. A better solution would be for example to expand `InstrumentedMutexLock` with `Lock` and `Unlock` functionality like `std::unique_lock`. But this has a huge impact on the existing code as `InstrumentedMutexLock` is mixed with the direct call of the `InstrumentedMutex` functions.

A litle additional question.. Are there important reasons not to use `assert(lock.owns_lock());` in `Mutex::AssertHeld` ? That could eleminate some #ifdef and the `friend class CondVar` in `Mutex` ...

**Comment by PraveenSinghRao** [comment]
Fix in https://github.com/facebook/rocksdb/pull/763

**Comment by PraveenSinghRao** [comment]
Fix has been merged by Igor. Please get the latest and try.

**Comment by PraveenSinghRao** [comment]
@DoktorSeltsam the usage of unique_lock was incorrect, hence owns_lock can't be used.

**Comment by DoktorSeltsam** [comment]
The constructor of Mutex needs a little change for release mode yet...

`   /* implicit */ Mutex(bool adaptive = false)`
`#ifndef NDEBUG`
`   : locked_(false)`
`#endif`
`   {}`

**Comment by DoktorSeltsam** [comment]
I took a more detailed look on the current implementation of the class `Mutex`. Unfortunately the method `AssertHeld` is useless because `locked_`is not thread save. It may be set or unset by another thread and the assertation leads to wrong assumptions. It's the same reason why `std::mutex`doesn't provide a test as "`is_locked()`". `AssertHeld` takes only effect when it's coupledwith `Lock` and `Unlock` in the same thread. Relating to that, the initial idea to use `std::unique_lock` is not a bad idea.

**Comment by yuslepukhin** [comment]
I was arguing on removing AssertHeld and all related things as useless everywhere. A better solution would be to get rid of Mutex and CondVar class all together and use std directly since RocksDB requires a C++11 compiler anyway. Things like instrumented Mutex may be used for other purposes.

**Comment by edouarda** [comment]
I agree with you that C++ 11 provides a satisfactory cross-platform abstraction for mutexes. This platform specific code around mutexes and condition variables is inherited from LevelDB. 

Additionally the assertions are useless as there is already such assertion inside the implementation of mutexes will throw if you are doing something obviously wrong (such as double acquisition or releasing and unowned mutex):

```cpp
	void _Validate() const
		{	// check if the mutex can be locked
		if (!_Pmtx)
			_THROW_NCEE(system_error,
				_STD make_error_code(errc::operation_not_permitted));

		if (_Owns)
			_THROW_NCEE(system_error,
				_STD make_error_code(errc::resource_deadlock_would_occur));
		}
```

One might argue that the abstraction enables an easier migration toward lightweight locks, but I disagree as such migration would probably be partial in the first place.

**Comment by yuslepukhin** [comment]
@DoktorSeltsam @edouarda Do we want to close this with the last issue addressed?

**Comment by DoktorSeltsam** [comment]
There is nothing to be said against it.

I can't await an overhaul of the mutex system towards std :) ...

**Comment by edouarda** [comment]
Yes it's fine!

**Comment by dhruba** [comment]
Is there any plans of moving the windows code  to std::mutex?

**Comment by yuslepukhin** [comment]
@dhruba Ready whenever you are. port::Mutex impl use std::mutex

**Comment by yuslepukhin** [comment]
This particular issue was fixed here https://github.com/facebook/rocksdb/commit/a1d37602a0b9a31c0fc5a9869e57bd55884f6af9#diff-e438cc784cd0656061844d09ff9372ce
