### ISSUE TITLE
Cross-building ERROR

### ISSUE THREAD

**Issue by z-Dapor** [facebook/rocksdb#7582]
**version**:    ## **rocksdb-6.13.3** from release :https://github.com/facebook/rocksdb/releases/tag/v6.13.3

**FLOW**: https://github.com/facebook/rocksdb/blob/master/java/RELEASE.md

**RUN**: make jclean clean rocksdbjavastaticreleasedocker

ERROR:
![image](https://user-images.githubusercontent.com/21967676/96819143-828d3500-1455-11eb-8330-9a9e0d75fb33.png)

There is no specific error message.
can u hellp me?

**Comment by z-Dapor** [comment]
found librocksdbjni-osx.jnilib and librocksdbjni-linux32.so version compile success,but linux-64 compile failed.

**Comment by z-Dapor** [comment]
fix: increment memory

**Comment by adamretter** [comment]
@z-Dapor Indeed, the `killed` part indicates that you likely ran out of memory
