### ISSUE TITLE
A failed `SstFileWriter::Add()` should not apply any internal state changes

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#7600]
#7448 accidentally changed the API contract of `SstFileWriter::Add()` and dependent functions (`SstFileWriter::Put()`, etc.). Now there is a case where the KV may be added to the table builder _and_ the returned `Status` is non-OK, i.e., when the `InvalidatePageCache()` fails. If there are clients that retry, they may now attempt to add an already existing key to a table builder. Ideally, clients shouldn't have been retrying since the pre-existing non-OK `Status`es were all `InvalidArgument`, on which retry would never succeed. However, in practice we have found some clients had implemented retry logic anyways, and after this change, the following sequence is possible:

1. `Add()` successfully adds a kv to the table builder.
2. `Add()` fails on `InvalidatePageCache()` and returns non-OK `Status`.
3. The retrying client calls `Add()` again with the same kv
4. `Add()` fails on validation of arguments (user key not strictly ascending)

Prior to this change, a failure in `InvalidatePageCache()` could not fail `Add()`, so the client would just move on to the next key.

**Comment by sunby** [comment]
If this issue is not assigned, I want to have a try.

**Comment by ajkr** [comment]
Great, let me know if you have any questions.

**Comment by ajkr** [comment]
By the way, my current thinking on this is we can permit `InvalidatePageCache()` failures without failing the `SstFileWriter::Add()`.  We just need to call `PermitUncheckedError()` on any intentionally ignored status.

**Comment by sunby** [comment]
@ajkr Thanks for your help! I still have a question:
Should we do the same thing to `InvalidatePageCache()`s called by `Rep::DeleteRange` and `SstFileWriter::Finish` ?

**Comment by ajkr** [comment]
Sorry missed the question. Yes, I think that is fine. LMK if you still plan to work on it; otherwise, putting up-for-grabs again.

**Comment by sunby** [comment]
> Sorry missed the question. Yes, I think that is fine. LMK if you still plan to work on it; otherwise, putting up-for-grabs again.

Sorry I just saw the notification. Yes, I would like to work on it and I create a pr about this issue https://github.com/facebook/rocksdb/pull/8156. PTAL.
