### ISSUE TITLE
Error: Compression type Snappy is not linked with the binary

### ISSUE THREAD

**Issue by VELVETDETH** [facebook/rocksdb#761]
Hi I'm facing an error which is: Compression type Snappy is not linked with the binary.

I got this error while running the `simple_example` in the `examples/` directory. I simply built this by using `make simple_example`. However, this program failed at the `s.ok()` assertion. So I followed the instruction in the wiki to find out what had happened. With `s.ToString()`, I've got the error message listed previously.

It seems that I haven't got this library, so I've built it again with this option:
```
options.compression = kNoCompression;
```

But still, that error message showed up again..

Thanks for your help!

**Comment by igorcanadi** [comment]
Can you please install snappy library before compiling RocksDB? This should be pretty simple. For example, if you're running Ubuntu, you just have to call: `sudo apt-get install libsnappy-dev`

**Comment by VELVETDETH** [comment]
Hi @igorcanadi Your idea works, thanks a lot. :+1:

**Comment by guileen** [comment]
I make a rocksdb shared library for golang use, I want to use `LZ4` compression. But it said `Invalid argument: Compression type LZ4 is not linked with the binary.`

I execute `make liblz4.a`, It still show this message.

**Comment by ruiaylin** [comment]
lz4  lz4-devel needed by   rocksdb  . But the document do not mention it

**Comment by yinyi26** [comment]
The issue is resolved after i update the version of libsnappy

**Comment by nullne** [comment]
@yinyi26 which version do you update to ?

**Comment by ljgreen** [comment]
Why the same issue occurs? 

When I test with ./db_bench --benchmarks="fillsync"

open error: Invalid argument: Compression type Snappy is not linked with the binary.

I have already installed the snappy, but it does not work.

Some one could help me figure out ? 

Thanks

**Comment by ljgreen** [comment]
Finally, I address the issue by upgrading the snappy verison. If you have the same problem, you can also solve that.
libsnappy-dev_1.1.7 is required.

**Comment by sqrtpineapple** [comment]
```
root@fvm:/home/femu/rocksdb# sudo ./db_bench --fs_uri=zenfs://dev:nvme0n1 --benchmarks=fillrandom --use_direct_io_for_flush_and_compaction
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
open error: Invalid argument: Compression type Snappy is not linked with the binary.
```
Update doesn't work...The error occurs again.
libsnappy-dev is already the newest version (1.1.8-1build1).
Anyone knows how to fix it?

**Comment by mrambacher** [comment]
Did you build the binary yourself?  Did you use make or cmake to generate it?  Which platform?  Is snappy installed on your machine?

Most likely the build system did not detect that snappy was installed (if it was).

db_bench defaults to using snappy compression (even if not installed) .  You can use --compression_type=none to disable compression in db_bench.

**Comment by sqrtpineapple** [comment]
@mrambacher Thanks!

**Comment by fanweneddie** [comment]
In `ubuntu`, you can simply enter the directory of `rocksdb` and directly run
```
make -jNCPU db_bench DEBUG_LEVEL=0
```
Maybe that is because `CMakeLists.txt` in `rocksdb` is only for win64(A comment in `CMakeLists.txt` is shown below).
```
# Prerequisites for Windows:
#     This cmake build is for Windows 64-bit only.
```

**Comment by hgdesai** [comment]
@igorcanadi when I type command yum install libsnappy-dev
Last metadata expiration check: 0:50:59 ago on Thu 20 Jan 2022 05:21:21 PM CST.
No match for argument: libsnappy-dev
Error: Unable to find a match. This is for Centos 8 Operating System.

**Comment by hdesai78** [comment]
i have installed snappy using yum install snappy command before compiling rocksdb. Also, I ran following link command "“ln -sfT /usr/local/rocksdb-6.xx.x /usr/local/rocksdb" but snappy is not linked binary issue is still persist. I am using Centos 8.0

**Comment by adamretter** [comment]
@hgdesai After installing Snappy you have to rebuild RocksDB. You also need tom make sure you installed `snappy-devel` in CentOS.
