### ISSUE TITLE
Cannot build rocksJava linux32-musl binary

### ISSUE THREAD

**Issue by Myasuka** [facebook/rocksdb#7610]
### Expected behavior
Running `make rocksdbjavastaticrelease` on mac could build all unix jars including `librocksdbjni-linux32-musl.so`.

### Actual behavior
Only `librocksdbjni-linux32.so` is built and cannot find the binary `librocksdbjni-linux32-musl.so`.

I noticed that we have `linux32-musl` definition in `Vagrantfile`,  but current [`Makefile`](https://github.com/facebook/rocksdb/blob/394210f280c6e7bc0e1210409fe326250a163d53/Makefile#L2208) did not include `vagrant up linux32-musl`.

### Steps to reproduce the behavior
Run `make rocksdbjavastaticrelease` would not generate `librocksdbjni-linux32-musl.so`.

I tried `vagrant up linux32-musl`, however, I meet error below:
~~~
==> linux32-musl: Rsyncing folder: /Users/myasuka/Documents/GitHub/frocksdb/ => /rocksdb
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.

Host path: /Users/myasuka/Documents/GitHub/frocksdb/
Guest path: /rocksdb
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 2222 -o LogLevel=FATAL   -o ControlMaster=auto -o ControlPath=/var/folders/g0/z20t923d7m37nwcygn196b640000gn/T/vagrant-rsync-20201029-9432-1a391vv -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/Users/myasuka/Documents/GitHub/frocksdb/java/crossbuild/.vagrant/machines/linux32-musl/virtualbox/private_key'" "--exclude" ".vagrant/" "/Users/myasuka/Documents/GitHub/frocksdb/" "vagrant@127.0.0.1:/rocksdb"
Error: Error relocating /lib/libacl.so.1: __lstat_time64: symbol not found
Error relocating /lib/libacl.so.1: __fstat_time64: symbol not found
Error relocating /lib/libacl.so.1: __stat_time64: symbol not found
Error relocating /lib/libpopt.so.0: secure_getenv: symbol not found
Error relocating /lib/libpopt.so.0: __stat_time64: symbol not found
Error relocating /usr/bin/rsync: __mktime64: symbol not found
Error relocating /usr/bin/rsync: __select_time64: symbol not found
Error relocating /usr/bin/rsync: __fstat_time64: symbol not found
Error relocating /usr/bin/rsync: __utimes_time64: symbol not found
Error relocating /usr/bin/rsync: __utimensat_time64: symbol not found
Error relocating /usr/bin/rsync: __lutimes_time64: symbol not found
Error relocating /usr/bin/rsync: __stat_time64: symbol not found
Error relocating /usr/bin/rsync: __time64: symbol not found
Error relocating /usr/bin/rsync: __nanosleep_time64: symbol not found
Error relocating /usr/bin/rsync: __gettimeofday_time64: symbol not found
Error relocating /usr/bin/rsync: __localtime64: symbol not found
Error relocating /usr/bin/rsync: __lstat_time64: symbol not found
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
~~~

Then I run `vagrant ssh linux32-musl` to login the virtual machine and found `rsync` command is broken. It seems a bug for `alpine/alpine32` image?

**Comment by Myasuka** [comment]
@adamretter how did you build such linux32-musl binary to include in the release jar?

**Comment by adamretter** [comment]
@Myasuka I use Docker to build the release, e.g. `PORTABLE=1 ROCKSDB_DISABLE_JEMALLOC=true make clean rocksdbjavastaticreleasedocker`

**Comment by Myasuka** [comment]
@adamretter Thanks for your reply. I have several questions:

1. I remember RocksDB community used `make clean rocksdbjavastaticreleas` to release previously, why we change the command now?
1. Why we need to disable `jemalloc` to build? In my point of view, `jemalloc` should be a powerful memory allocator.

**Comment by adamretter** [comment]
@Myasuka 

1. When I started doing release for RocksJava (~4 years ago) I had problems with the VirtualBox builds. I then added the Docker builds, as I found that was faster and worked better across all platforms. We have been using the Docker builds for at least 3 years (I think) for all of the RocksJava releases.

2. jemalloc support on Mac in RocksDB is broken and has been for some time I think. I believe the non-mac builds done in Docker are still built with jemalloc.

**Comment by Myasuka** [comment]
@adamretter sorry to bother you again, I have another questions, how do you publish ppc64le binary files?
Did you also run `PORTABLE=1 make clean rocksdbjavastaticdockerppc64le` and `PORTABLE=1 make clean rocksdbjavastaticdockerppc64lemusl` on mac laptop?

**Comment by adamretter** [comment]
@Myasuka The ppc64le binaries can only be build on a PPC64le machine. The same goes for the aarch64 binaries needing an ARM machine. You might be able to set something up with cross-compilation, but I that's not something I needed.
