### ISSUE TITLE
Failed to compile rocksdbjava on mac

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#7616]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

I want to get rocksdbjni with hdfs. But on the official maven repo, the rocksdbjni does not support hdfs. So I have to try to compile it by myself.

### Expected behavior
Succeed to compile.
### Actual behavior
![image](https://user-images.githubusercontent.com/18675094/97672772-94aa4b80-1ac5-11eb-8c3b-c21a92f06911.png)

### Steps to reproduce the behavior
rocksdb version v6.6.4
gcc version 4.9.4(I use alias for gcc in my `~/.bash_profile` file)
![image](https://user-images.githubusercontent.com/18675094/97672920-daffaa80-1ac5-11eb-8bfc-c21cf051fec9.png)
![image](https://user-images.githubusercontent.com/18675094/97673001-fbc80000-1ac5-11eb-9d6b-a7a455d36e2b.png)
java version 1.8.0_202
mac os version 10.15.7

run command: make -j8 rocksdbjava

Maybe, this is caused by `-Wrange-loop-analysis`. So is it better to use reference(`auto &newf`) here instead of copy(`auto newf`)?

Anybody help or anybody can offer me a rocksdb jni with hdfs?

**Comment by adamretter** [comment]
@GOGOYAO I am on macOS Catalina 10.15.6 with Apple clang version 11.0.3 (clang-1103.0.32.62), and OpenJDK 1.8.0_252.

Running `ROCKSDB_DISABLE_JEMALLOC=true make -j8 rocksdbjava` works perfectly here on the `HEAD` of the master branch.

I note you are using GCC, could you try with the build-in clang instead?
...or I wonder if your problem specifically with RocksJava version 6.6.4? Can you try with the latest?

**Comment by GOGOYAO** [comment]
I use built-in clang and try your command. It works.
