### ISSUE TITLE
No Space Left on device

### ISSUE THREAD

**Issue by saurabh1007** [facebook/rocksdb#7646]
Hi,
We keep getting these errors 
org.rocksdb.RocksDBException: IO error: /rocksdata/EVENT_STORE/164054106.sst: No space left on device
        at org.rocksdb.RocksDB.write0(Native Method) ~[rocksdbjni-4.0.jar:?]
        at org.rocksdb.RocksDB.write(RocksDB.java:546) ~[rocksdbjni-4.0.jar:?]

This is happening when we still have a lot of space left on the disk. We do see a spike in IOPS just before this exception. Using 3 disks (16TB each) in raid0. 
 
Appreciate any help/leads.

**Comment by saurabh1007** [comment]
If this helps:
`Filesystem volume name:   rocks_vol
Last mounted on:          /rocksdata
Filesystem UUID:          UUID
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr dir_index filetype needs_recovery extent 64bit flex_bg sparse_super large_file huge_file uninit_bg dir_nlink extra_isize
Filesystem flags:         signed_directory_hash 
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              1048567808
Block count:              16777083904
Reserved block count:     838854195
Free blocks:              16578540532
Free inodes:              1048325026
First block:              0
Block size:               4096
Fragment size:            4096
Group descriptor size:    64
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         2048
Inode blocks per group:   128
RAID stride:              128
RAID stripe width:        512
Flex block group size:    16
Filesystem created:       Thu Jul  9 20:38:21 2020
Last mount time:          Fri Jul 10 07:56:55 2020
Last write time:          Fri Jul 10 07:56:55 2020
Mount count:              4
Maximum mount count:      -1
Last checked:             Thu Jul  9 20:38:21 2020
Check interval:           0 (<none>)
Lifetime writes:          11 TB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:	          256
Required extra isize:     28
Desired extra isize:      28
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      UUID
Journal backup:           inode blocks`

**Comment by ajkr** [comment]
What filesystem is it? We've seen transient ENOSPC on btrfs. Also what version of RocksDB are you using? If it's 4.0 as the jar name suggests, there's been a couple (or more) improvements made since then that may help with this situation:

- Since 5.16, RocksDB automatically resumes accepting writes after the disk no longer reports it's full.
- We fixed a bug in a certain configuration that led to an impossibly large attempt to `fallocate()` - https://github.com/facebook/rocksdb/pull/2252
