### ISSUE TITLE
undefined reference to Gflags

### ISSUE THREAD

**Issue by rainays** [facebook/rocksdb#7652]
I encountered an error about gflags when compiling. I modified the namespace and environment variables in accordance with several similar issues, and tried to link to the gflags library, but they were all unsuccessful.
Here are the error messages I get：

```
table/table_reader_bench.o: In function `main':
/home/ayj/rocksdb/table/table_reader_bench.cc:283: undefined reference to `google::SetUsageMessage(std::string const&)'
/home/ayj/rocksdb/table/table_reader_bench.cc:284: undefined reference to `google::ParseCommandLineFlags(int*, char***, bool)'
table/table_reader_bench.o: In function `__static_initialization_and_destruction_0':
/home/ayj/rocksdb/table/table_reader_bench.cc:263: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/home/ayj/rocksdb/table/table_reader_bench.cc:265: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/home/ayj/rocksdb/table/table_reader_bench.cc:266: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/home/ayj/rocksdb/table/table_reader_bench.cc:267: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/home/ayj/rocksdb/table/table_reader_bench.cc:268: undefined reference to `google::FlagRegisterer::FlagRegisterer<int>(char const*, char const*, char const*, int*, int*)'
/home/ayj/rocksdb/table/table_reader_bench.cc:269: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/home/ayj/rocksdb/table/table_reader_bench.cc:270: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
/home/ayj/rocksdb/table/table_reader_bench.cc:273: undefined reference to `google::FlagRegisterer::FlagRegisterer<bool>(char const*, char const*, char const*, bool*, bool*)'
```

**Comment by ajkr** [comment]
Can you show the gflags install directory, the gflags version, and the command being used to link? (Run `make V=1 ...` to show commands run by our Makefile.)

**Comment by pdillinger** [comment]
Also, you would see this if forgetting to "make clean" between config changes. (Mentioning that in case you forgot it this time.)

**Comment by Phantomape** [comment]
Came across the same error above along with ```DSO missing from command line``` error using ubuntu 16.04 (which use libgflags-dev 2.1.2-3). However I succeed in compiling in ubuntu 18.04 (which use libgflags-dev 2.2.1-1). I use docker to run these containers, which should be fairly easy to reproduce

**Comment by ajkr** [comment]
Thanks. Yes with gflags 2.1 there's a known problem (#6628). I'm not sure when that'll be fixed, but it should be able to be worked around by explicitly setting `-DGFLAGS_NAMESPACE=gflags`.

**Comment by Phantomape** [comment]
Hmm, I'm not sure that's the case, cause in ubuntu 16.04 container mentioned above,I saw this in my gflags header file ```gflags_declare.h```
![image](https://user-images.githubusercontent.com/8809221/99614026-9c6d6800-2a53-11eb-920d-152d463031bd.png)
And the command ```nm -D libgflags.so```, I can see ```google``` is actually the namespace for these undefined functions
![image](https://user-images.githubusercontent.com/8809221/99614156-e7877b00-2a53-11eb-8174-9183fde2de17.png)
Looks kinda weird to me ...

**Comment by rainays** [comment]
> Can you show the gflags install directory, the gflags version, and the command being used to link? (Run `make V=1 ...` to show commands run by our Makefile.)

thanks for reply, package version is 2.2.2 and install directory /usr/lib64

**Comment by rainays** [comment]
> Hmm, I'm not sure that's the case, cause in ubuntu 16.04 container mentioned above,I saw this in my gflags header file `gflags_declare.h`
> ![image](https://user-images.githubusercontent.com/8809221/99614026-9c6d6800-2a53-11eb-920d-152d463031bd.png)
> And the command `nm -D libgflags.so`, I can see `google` is actually the namespace for these undefined functions
> ![image](https://user-images.githubusercontent.com/8809221/99614156-e7877b00-2a53-11eb-8174-9183fde2de17.png)
> 
> ## Update
> Took a closer look at the gflags repo (tag v2.1.2), it seems that this namespace is actually controlled by cmake logic
> ![image](https://user-images.githubusercontent.com/8809221/99614704-fb7fac80-2a54-11eb-8281-ca434cdcea4f.png)

thanks,  I've tried this, but not work

**Comment by rainays** [comment]
> Also, you would see this if forgetting to "make clean" between config changes. (Mentioning that in case you forgot it this time.)

thank you, it works!
