### ISSUE TITLE
Compaction Stats missing

### ISSUE THREAD

**Issue by yinsudahuizhuan** [facebook/rocksdb#7664]
I used to check the compaction stats when using db_bench, but it does not work with the newest work.

### Expected behavior
illrandom   :      50.704 micros/op 19722 ops/sec;   38.5 MB/s

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0     16/0   541.10 MB   4.0      0.0     0.0      0.0      19.0     19.0       0.0   1.0      0.0    191.3    101.59             90.13       575    0.177       0      0
  L1     38/1    2.05 GB   8.0     51.5    18.4     33.0      51.4     18.4       0.0   2.8    128.2    128.0    411.32            351.04        31   13.269     48M    79K
  L2    240/4   14.49 GB   5.7     62.7    15.1     47.6      62.4     14.8       1.2   4.1    129.8    129.0    494.95            418.70       248    1.996     59M   294K
  L3     24/0    1.47 GB   0.0      0.0     0.0      0.0       0.0      0.0       1.5   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0
 Sum    318/5   18.54 GB   0.0    114.2    33.6     80.7     132.8     52.1       2.7   7.0    116.1    134.9   1007.86            859.86       854    1.180    108M   374K
 Int      0/0    0.00 KB   0.0     40.4     9.9     30.5      45.2     14.7       1.5   9.0    119.2    133.5    346.70            295.82       237    1.463     38M   175K

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Low      0/0    0.00 KB   0.0    114.2    33.6     80.7     113.8     33.1       0.0   0.0    129.1    128.6    906.28            769.74       279    3.248    108M   374K
High      0/0    0.00 KB   0.0      0.0     0.0      0.0      19.0     19.0       0.0   0.0      0.0    191.3    101.59             90.13       575    0.177       0      0
Uptime(secs): 912.7 total, 310.7 interval
Flush(GB): cumulative 18.978, interval 5.050
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 132.76 GB write, 148.96 MB/s write, 114.23 GB read, 128.16 MB/s read, 1007.9 seconds
Interval compaction: 45.20 GB write, 149.00 MB/s write, 40.35 GB read, 133.00 MB/s read, 346.7 seconds
Stalls(count): 370 level0_slowdown, 79 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 143 total count

** File Read Latency Histogram By Level [default] **
** Level 0 read latency histogram (micros):
Count: 10082 Average: 1542.1700  StdDev: 607.19
Min: 60  Median: 1606.2377  Max: 9274
Percentiles: P50: 1606.24 P75: 1835.76 P99: 3908.81 P99.9: 6508.45 P99.99: 9274.00
------------------------------------------------------
(      51,      76 ]        3   0.030%   0.030% 
(     110,     170 ]        1   0.010%   0.040% 
(     170,     250 ]        4   0.040%   0.079% 
......
......
### Actual behavior
fillrandom   :      52.620 micros/op 19004 ops/sec;   37.1 MB/s

** File Read Latency Histogram By Level [default] **
** Level 0 read latency histogram (micros):
Count: 10097 Average: 1594.1490  StdDev: 613.17
Min: 99  Median: 1623.9299  Max: 10185
Percentiles: P50: 1623.93 P75: 1845.19 P99: 4056.97 P99.9: 6481.71 P99.99: 9895.43
------------------------------------------------------
(      76,     110 ]        2   0.020%   0.020% 
(     250,     380 ]      316   3.130%   3.149% #
(     380,     580 ]      240   2.377%   5.526% 
(     580,     870 ]       12   0.119%   5.645% 
......
......

**Comment by yinsudahuizhuan** [comment]
db/internal_stats.cc

void InternalStats::DumpCFFileHistogram(std::string* value) {
  assert(value);
  assert(cfd_);

  std::ostringstream oss;
  oss << *value;
  oss << "\n** File Read Latency Histogram By Level [" << cfd_->GetName()
      << "] **\n";

  for (int level = 0; level < number_levels_; level++) {
    if (!file_read_latency_[level].Empty()) {
      oss << "** Level " << level << " read latency histogram (micros):\n"
          << file_read_latency_[level].ToString() << '\n';
    }
  }

  if (!blob_file_read_latency_.Empty()) {
    oss << "** Blob file read latency histogram (micros):\n"
        << blob_file_read_latency_.ToString() << '\n';
  }

  *value = oss.str();
}

In this function, value is overwritten. And it will discard the compaction stats.

**Comment by mrambacher** [comment]
I believe this issue was introduced in #7461 

The issue can probably be resolved by changing the line " *value = oss.str(); " to "value->append(oss.str());"

**Comment by ltamasi** [comment]
Thanks for reporting @yinsudahuizhuan ! I'll put out a patch to fix this.
