### ISSUE TITLE
Makefile:265: make_config.mk: No such file or directory

### ISSUE THREAD

**Issue by Wwwwwxh** [facebook/rocksdb#7677]
in  centos 8.2  make  shared_lib success
in  centos 7.2.1511 make  shared_lib failed

**Comment by Wwwwwxh** [comment]
[root@fe578a8f1d66 rocksdb-6.13.3]# make shared_lib
make: which: Command not found
make: which: Command not found
make: -c: Command not found
$DEBUG_LEVEL is 0
make: -c: Command not found
make: -c: Command not found
make: -c: Command not found
make: -c: Command not found
make: -c: Command not found
make: -c: Command not found
Makefile:265: make_config.mk: No such file or directory
make: -c: Command not found
make: -c: Command not found

**Comment by adamretter** [comment]
@Wwwwwxh Looks like you are missing some tools on your CentOS 7 system, including `which`.

Can you tell me what version of RocksDB you are trying to build?

**Comment by Wwwwwxh** [comment]
RocksDB  version  5.18.3

**Comment by adamretter** [comment]
@Wwwwwxh Did you try installing the missing commands?

**Comment by Wwwwwxh** [comment]
try installing the missing commands 
find out why 
missing commands      which
thank you
