### ISSUE TITLE
db_test_util.cc  build error on windows

### ISSUE THREAD

**Issue by maximecaron** [facebook/rocksdb#769]
d:\new folder\rocksdb\db\db_test_util.cc(782): error C2039: 'TEST_CompactRange'
 : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\rocksdblib
.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(784): error C2039: 'TEST_CompactRange'
 : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\rocksdblib
.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(792): error C2039: 'TEST_MaxNextLevelO
verlappingBytes' : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\
build\rocksdblib.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(833): error C2039: 'TEST_WaitForFlushM
emTable' : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\ro
cksdblib.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(834): error C2039: 'TEST_WaitForCompac
t' : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\rocksdbl
ib.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(845): error C2039: 'TEST_WaitForFlushM
emTable' : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\ro
cksdblib.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(846): error C2039: 'TEST_WaitForCompac
t' : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\rocksdbl
ib.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(856): error C2039: 'TEST_WaitForFlushM
emTable' : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\ro
cksdblib.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:
  :DBImpl'
d:\new folder\rocksdb\db\db_test_util.cc(857): error C2039: 'TEST_WaitForCompac
t' : is not a member of 'rocksdb::DBImpl' [D:\New folder\rocksdb\build\rocksdbl
ib.vcxproj]
          d:\new folder\rocksdb\db\db_impl.h(59) : see declaration of 'rocksdb:

**Comment by IslamAbdelRahman** [comment]
Hi @maximecaron , Are you compiling the tests in Release mode ?

**Comment by maximecaron** [comment]
yes for debug mode I dont get those error.

**Comment by maximecaron** [comment]
for json_documet.cc error it seem changing code to below is fixing it:

  return std::pair<std::string,rocksdb::JSONDocument>(std::string(it_->getKeyStr(), it_->klen()),
    JSONDocument(it_->value(), false));

**Comment by IslamAbdelRahman** [comment]
Can you please try to do a clean build ? I have tried a windows build without changing any code and did not encounter any errors.

**Comment by maximecaron** [comment]
After clean build I now only get JSONDocument error for release build. I sent a pull request for the fix. Feel free to close this issue.

**Comment by Vaisman** [comment]
from CMakeLists.txt:
```
 # Prerequisites:
 #     You must have Visual Studio 2013 Update 4 installed.
```
when I build project on Visual Studio without Update 4, I got this build error, after Update 4 installed build successfully.

**Comment by yuslepukhin** [comment]
@Vaisman You will not have a working RocksDB w/o Update 4 installed for Studio 13.

**Comment by maximecaron** [comment]
The code without my fix to JSONDocument is valid C++11 code and simply trigger a bug in VC++.
If C++11 is already required to compile RocksDB please ignore this pull request.
