### ISSUE TITLE
Crash when DBImpl::Open

### ISSUE THREAD

**Issue by runzhiwang** [facebook/rocksdb#7704]
rocksdbjni with version 6.8.1
![image](https://user-images.githubusercontent.com/51938049/99754353-30f2cb80-2b23-11eb-840c-df25a065facd.png)

**Comment by adamretter** [comment]
There is nothing that immediately jumps out here. Could you install the debuginfos as it suggest and see whether that provides a more detailed Stacktrace?

**Comment by runzhiwang** [comment]
![image](https://user-images.githubusercontent.com/51938049/100312904-6fd6c480-2fee-11eb-8e7c-fc8fe893c6ae.png)
@adamretter Thanks the suggestion, I install the debuginfos, but no more detaild stacktrace.

**Comment by adamretter** [comment]
@runzhiwang Perhaps if you resolve the line number from `rocksdb::DBImpl::Open` it could give us some clue. See - https://github.com/facebook/rocksdb/wiki/JNI-Debugging

**Comment by runzhiwang** [comment]
![image](https://user-images.githubusercontent.com/51938049/100349133-eb526900-3022-11eb-9525-0022a7eff443.png)
![image](https://user-images.githubusercontent.com/51938049/100349214-16d55380-3023-11eb-93c2-e513421b206e.png)

@adamretter  I have use addr2line, but no clue.

**Comment by adamretter** [comment]
@runzhiwang  You need to build `DEBUG_LEVEL=2` versions of the RocksDB binaries to be able to get the line numbers

**Comment by runzhiwang** [comment]
@adamretter Thanks the suggestions. Could you give the command used to build` DEBUG_LEVEL=2`, with `-g` option, versions of the RocksDB, and deploy it to maven repository ?

**Comment by runzhiwang** [comment]
@adamretter  Hi, I build rocksdb with command: ROCKSDB_DISABLE_JEMALLOC=true make -j8 rocksdbjava, then use the jar, but throw exception.
![image](https://user-images.githubusercontent.com/51938049/102299646-3c081280-3f8e-11eb-836a-15f2fb6215ab.png)

**Comment by adamretter** [comment]
@runzhiwang It looks like you dynamically linked it on a platform that happy Snappy installed, and then tried to run it on a platform which didn't have Snappy
