### ISSUE TITLE
Is there a race in code?

### ISSUE THREAD

**Issue by nikitamikhaylov** [facebook/rocksdb#7711]
Could you please explain this piece of code? https://github.com/facebook/rocksdb/blob/0355d14dd9c9e41d37bb3a462c5a1ddbc8962392/util/timer.h#L78-L105 

I think there is a race on `thread_` variable, because we can call Start(), then call Start() and Shutdown() in parallel. So, there will be a situation when `running_=false`, but `thread_` is not nullptr, so if `reset` will be called a bit earlier than `join` it will lead to `std::terminate` according to C++ standart. 

It reproduces in stress tests in ClickHouse with this trace https://gist.github.com/alesapin/3749e00d962a0843d61866e4565c5aee

**Comment by jay-zhuang** [comment]
Thanks @nikitamikhaylov for reporting the issue. Yes, there's race condition for timer `start` and `shutdown`. I'm working on a fix for that.
