### ISSUE TITLE
Is there any way to determine the exact last write/sequence number in the rocksdb's backup 

### ISSUE THREAD

**Issue by ufo2243** [facebook/rocksdb#7712]
After I called rocksdb::BackupEngine::CreateBackupWithMetadata() , the information I can get from Backup is only a id and a timestamp.  
What I what to do here is that if I can have the last operation in the backup I can log all the operations after backing up rocksdb somewhere else.

**Comment by pdillinger** [comment]
Not currently, but this is a feature request that has been on my mind.

**Comment by pdillinger** [comment]
Added the ability to open backups as read-only DBs, which should enable all the inspection you need. #8142
