### ISSUE TITLE
Strange disk usage on backup

### ISSUE THREAD

**Issue by theolivenbaum** [facebook/rocksdb#7727]
Hi,

We saw a strange issue in a production system this week - appreciate any guidance in investigating it.

The system is a >2TB RocksDB store, configured for incremental backup that is triggered every night. As part of the backup task, we also purge older backups so that we keep only the N latest ones. All following the [Wiki Backup Page](https://github.com/facebook/rocksdb/wiki/How-to-backup-RocksDB%3F) procedure.

Two days ago, after the backup process started, we saw a continuous increase of 200GB/hr in storage usage for both the backup disk and in the live disk, which went till the live disk had no more space left. 

After a restart, RocksDB seems to have cleaned up whatever it was doing, so that the disk usage went back to normal (in both backup and live disks). Last night, when the backup triggered again, we observed the same behavior and just stopped the process ourselves before it run out of disk space.

Any ideas of what could be happening here?

**Comment by pdillinger** [comment]
In general, if you change any of your share_table_files, share_files_with_checksum, or share_files_with_checksum_naming options, you will disrupt incremental backup and get all new files saved. For version 6.12, we changed the naming but hacked in a way of using old naming for pre-6.12 SST files, thus avoiding a forced disruption to incremental backups.

If you run a full compaction, obviously you will have nothing shared on incremental backup.

Re-open if you have more details about the issue, such as file x_1 and x_2 are the same but aren't being shared.
