### ISSUE TITLE
Rocksdb can be opened with Time to Live(TTL) support - Java support missing

### ISSUE THREAD

**Issue by b00lean** [facebook/rocksdb#774]
https://github.com/facebook/rocksdb/wiki/Time-to-Live is not accessible from Java.
Any plan to add the binding?

**Comment by adamretter** [comment]
We would like the Java API to be feature complete with the C++ API, but at the moment it is a matter or resources. If this is something you would like to contribute feel free to sign the CLA and send a PR.

**Comment by feng-tao** [comment]
I thought TTL is already supported in rocksJava?https://github.com/facebook/rocksdb/blob/master/java/src/main/java/org/rocksdb/TtlDB.java

**Comment by adamretter** [comment]
@b00lean I am closing this because as @feng-tao point's out the Java API has TTLDB.
