### ISSUE TITLE
DBTest2.PartitionedIndexUserToInternalKey failing on ppc64le

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#7746]
DBTest2.PartitionedIndexUserToInternalKey failing (always or very often?) on ppc64le, as seen in Travis at least since version 6.13

**Comment by akankshamahajan15** [comment]
Working on the issue and fix.

**Comment by pdillinger** [comment]
https://travis-ci.org/github/facebook/rocksdb/jobs/750937923

I believe the issue is that an automatic flush can be triggered before sufficient entries have been added. I don't know why, except maybe you're dangerously close to exceeding the write buffer size and/or dangerously close to not splitting a partition.

**Comment by akankshamahajan15** [comment]
Oh! I will check it again. Since its not reproducible so difficult to understand the issue but keeping your suggestions in mind, I will try to change the test.
