### ISSUE TITLE
Question: How does rocksDB deal with stale data on the last level?

### ISSUE THREAD

**Issue by jarifibrahim** [facebook/rocksdb#7773]
Hi guys, I work on Badger DB and I had a question about compaction. 
How does rocksdb deal with stale data on the last level of the LSM Tree?
We have a situation where our last level has most of the stale data (which will be dropped can be dropped by the next compaction).

I am wondering how does rocksDB deal with this situation? Does it have same level compactions (apart from the L0 to L0 ones)?

**Comment by siying** [comment]
A "TTL" feature is used to make sure all updates reach the last level in certain amount of time: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/advanced_options.h#L678-L694

The option name is a little bit confusing, but reading the comment you can get the purpose. We have some optimizations on progress to improve the feature to reduce the spiking behavior of the option.

**Comment by jay-zhuang** [comment]
Hi @jarifibrahim, I'm hoping @siying answered your question. Closing it for now and please use https://groups.google.com/g/rocksdb?pli=1 for any questions. Thanks.
