### ISSUE TITLE
Rocksdb failed to recover after disk full error

### ISSUE THREAD

**Issue by deepakojha123** [facebook/rocksdb#7784]
Hi,

We saw an issue with rocksdb v6.4.6 where after disk full error rocksdb failed to recover and went into crashloop during WAL recovery. The error was as follows:
"Corruption: SST file is ahead of WALs"

Our use case: We open a single DB instance with multiple column-families and we do only sync writes. We use kPointInTimeRecovery mode. The rocksdb logs indicate a corrupted WAL file which was safely dropped.
2020/12/16-23:39:46.326488 52f0700 [WARN] [_impl/db_impl_open.cc:629] /home/cohesity/data/disks/nvme0n1p2_ce37060b-5269-4177-9a70-f61b46b8791d/scribe/newscribe/tablet_repo/tablet_1/db/253737849.log: dropping 266 bytes; Corruption: checksum mismatch
2020/12/16-23:39:46.326524 52f0700 [_impl/db_impl_open.cc:923] Point in time recovered to log #253737849 seq #653422636747

Listing the WAL files indicate another empty WAL file next to this corrupted file:
rw-rr-. 1 cohesity cohesity 175902 Dec 16 23:39 253737847.log
rw-rr-. 1 cohesity cohesity 0 Dec 16 23:39 253737851.log             <-----  Empty WAL file.
rw-rr-. 1 cohesity cohesity 340221 Dec 16 23:39 253737849.log

### Expected behavior

Once the disk space was cleared rocksdb should have safely dropped the truncated WAL file and recovered.

### Actual behavior

Rocksdb went into a crashloop with "Corruption: SST file is ahead of WALs"

### Steps to reproduce the behavior

I think below steps lead to the crashloop:
1. Crash rocksdb while writing the WAL file (the WAL file will be truncated). Please note another empty WAL file should have been created.
2. Upon restart during WAL recovery while doing a flush hit another crash. Please note before this point some of the column families(with no data to be recovered, would start pointing to the empty WAL file).
3. All subsequent WAL recovery would hit the error "Corruption: SST file is ahead of WALs".

I will go through the rocksdb unit test framework to create a test with above steps. Meanwhile I have attached the relevant LOG files.

[LOG.old.1608190304754106.txt](https://github.com/facebook/rocksdb/files/5720558/LOG.old.1608190304754106.txt)
[LOG.old.1608190774690063.txt](https://github.com/facebook/rocksdb/files/5720559/LOG.old.1608190774690063.txt)
[LOG.old.1608190795336528.txt](https://github.com/facebook/rocksdb/files/5720560/LOG.old.1608190795336528.txt)
[LOG.old.1608191111379541.txt](https://github.com/facebook/rocksdb/files/5720561/LOG.old.1608191111379541.txt)

**Comment by ajkr** [comment]
I stressed version 6.4 with `ENOSPC` and also saw the DB fail with the newest WAL having zero bytes most times. @anand1976 do you happen to have a guess why? Unfortunately the only time it doesn't happen is when run under a debugger.

We shouldn't need to fail when there's a zero-byte WAL, anyways. Maybe when calculating `corrupted_wal_number`, we can increase it as long as the next newer WAL contains zero bytes.

**Comment by deepakojha123** [comment]
@ajkr I have created a patch with your suggested fix. Please take a look.

**Comment by deepakojha123** [comment]
It turns out that 6.4.6 has a bug which was fixed in PR #5856. The condition is precisely what we are hitting: a point-in-time recovery with a corrupted wal file and a crash during recovery after flushing some CFs. Now the flushed CFs moved past the corrupted wal while remaining CFs still behind. Next Open will hit the corruption error. The fix is to update the Manifest atomically for all CFs after the flush.
