### ISSUE TITLE
is WriteUnprepared ready?

### ISSUE THREAD

**Issue by Layamon** [facebook/rocksdb#7856]
>  from this wiki : https://github.com/facebook/rocksdb/wiki/WriteUnprepared-Transactions, there is "WriteUnprepared are to be announced as production-ready soon." ;
Is it ready now? thx

**Comment by ajkr** [comment]
It is not used internally or developed actively so there'll unlikely be an announcement anytime soon. It is tested continuously/extensively in correctness tests. So I guess it should be used with extra caution, considering that it isn't widely deployed in FB. I'll remove that note from the Wiki.
