### ISSUE TITLE
Zeros for bloom filter stats

### ISSUE THREAD

**Issue by Phantomape** [facebook/rocksdb#7868]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

I'm trying to see how bloom filter affects the point lookup(theoretically it should reduce the number of sst files opened). Here is my source code(mainly copied from the simple_example.cc with slight modifications)
```
// Copyright (c) 2011-present, Facebook, Inc.  All rights reserved.
//  This source code is licensed under both the GPLv2 (found in the
//  COPYING file in the root directory) and Apache 2.0 License
//  (found in the LICENSE.Apache file in the root directory).

#include <cstdio>
#include <string>

#include "rocksdb/db.h"
#include "rocksdb/slice.h"
#include "rocksdb/options.h"

using namespace ROCKSDB_NAMESPACE;

#if defined(OS_WIN)
std::string kDBPath = "C:\\Windows\\TEMP\\rocksdb_simple_example";
#else
std::string kDBPath = "/tmp/rocksdb_simple_example";
#endif

int main() {
  DB* db;
  Options options;
  // Optimize RocksDB. This is the easiest way to get RocksDB to perform well
  options.IncreaseParallelism();
  options.OptimizeForPointLookup(4);
  options.OptimizeLevelStyleCompaction();
  // create the DB if it's not already present
  options.create_if_missing = true;
  options.statistics = CreateDBStatistics();

  // open DB
  Status s = DB::Open(options, kDBPath, &db);
  assert(s.ok());

  // Put key-value
  for (size_t i = 0; i < 1000000; i ++) {
    s = db->Put(WriteOptions(), "key" + std::to_string(i), std::to_string(i));
    assert(s.ok());
  }
  std::string value;
  // get value
  s = db->Get(ReadOptions(), "key1", &value);
  assert(s.ok());
  printf("%s\n", options.statistics->ToString().c_str());

  delete db;

  return 0;
}

```

### Expected behavior

stats should show something related to the bloom filter

### Actual behavior

![image](https://user-images.githubusercontent.com/8809221/104756488-d7132880-5796-11eb-8267-e0de8910c720.png)
Related stats numbers are all zero.

### Steps to reproduce the behavior

Replace simple_example.cc with the source code pasted above and ```make all && ./simple_example```

**Comment by pdillinger** [comment]
You might need to flush before Gets for them to come from SST files rather than memtable. These stats are only for SST file bloom filters

**Comment by Phantomape** [comment]
Thanks, it works now
