### ISSUE TITLE
Compilation Fails on OSX

### ISSUE THREAD

**Issue by abramsm** [facebook/rocksdb#789]
After checking out master I attempted to run `make all` but run into a compilation issue.

```
In file included from util/io_posix.cc:12:
./include/posix/io_posix.h:172:35: error: use of undeclared identifier 'errno'
      return IOError("directory", errno);
```

My gcc version is:

```
iMac:rocksdb abramsm$ gcc --version
gcc (Homebrew gcc49 4.9.3) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Adding `#include <errno.h>` to include/posix/io_posix.h resolves the issue for me.  It has been a very long time since I've worked with gcc so this could be something stupid on my part.

**Comment by siying** [comment]
I'm fixing it: https://reviews.facebook.net/D49551

**Comment by siying** [comment]
I committed it. Can you sync and retry?

**Comment by abramsm** [comment]
That fixed it.  thanks for the quick turn around.
