### ISSUE TITLE
TransactionDB now explicitly rejects range deletes in 6.15.

### ISSUE THREAD

**Issue by sfackler** [facebook/rocksdb#7913]
#7572 added missing error checks to various places. However, one in particular (https://github.com/facebook/rocksdb/pull/7572/files#diff-8d4f52efb53431efba2194e523696a9e147c6b24421f12d81b7aae9678495994R513-R516) caused TransactionDBs to start explicitly rejecting range deletes. The old behavior, where the delete would commit but fail to take locks on the affected keys, seems pretty clearly wrong, but it is a change that didn't end up in the release notes and took me a while to track down.

We were relying on the old behavior in an application I'm working on, but luckily we only perform the deletes on key ranges we know aren't visible to any transactions (it's happening in a background GC job). Am I right in thinking that we should be able to just perform the deletes on the base DB (i.e. `db->GetBaseDB()->DeleteRange(...)` rather than `db->DeleteRange(...)` as long as we are confident that we won't have any concurrent use of those keys?

It may also be worth updating the release notes to include this change for future people that come across it.

**Comment by ajkr** [comment]
Thanks for pointing this out - I didn't realize it was allowed by previous versions. Working on a fix now.

> Am I right in thinking that we should be able to just perform the deletes on the base DB ...

That might work depending on which kind of transaction DB you're using. With `TxnDBWritePolicy::WRITE_COMMITTED` it should work. With others (write-prepared or write-unprepared), calling `Write()` APIs on the underlying `DB` should fail. In `OptimisticTransactionDB` it should work.

But, I suggest using the transaction DB APIs to explicitly promise to RocksDB that there is no conflict. Here is the way I am proposing now which we should support into the future:

```
+  // Transactional `DeleteRange()` is not yet supported.
+  // However, users who know their deleted range does not conflict with
+  // anything can still use it via the `Write()` API. When using one of the
+  // `PessimisticTransactionDB`s, the `Write()` overload specifying
+  // `TransactionDBWriteOptimizations` must be used and
+  // `skip_concurrency_control` must be set. When using one of the
+  // `WritePreparedTxnDB`s, `skip_duplicate_key_check` must additionally be set.
```

Unless you are using `OptimisticTransactionDB`, I think the above API usage could work for your use case. Let me know..

**Comment by sfackler** [comment]
We're using a `TransactionDB` with `WRITE_COMMITTED`, yeah.

That proposal seems good to me!
