### ISSUE TITLE
How to run a manual compaction as fast as possible?

### ISSUE THREAD

**Issue by qqnidaye** [facebook/rocksdb#7915]
Is there a way to run a manual compaction by multi threads?

I have  with 8T data on a big machine with 256-core and 1T ram, I want to run a manual compation as fast as possible.

I know sub compactions, I also know a manual compaction is divided into many `CompactionJob`, and these `CompactionJob` are run sequentially.

The question is: How to run these `CompactionJob`  concurrently?

**Comment by riversand963** [comment]
> sub compactions

Have you tried it?

**Comment by ramvadiv** [comment]
@qqnidaye - can you pls try sub compactions and respond?
