### ISSUE TITLE
The repo‘s Wiki all page can be edited

### ISSUE THREAD

**Issue by kana112233** [facebook/rocksdb#7922]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
https://github.com/facebook/rocksdb/wiki/How-to-persist-in-memory-RocksDB-database%3F
The wiki page can be edited by anyone who already logged in.
### Actual behavior
https://github.com/facebook/rocksdb/wiki/How-to-persist-in-memory-RocksDB-database%3F
### Steps to reproduce the behavior
1. goto https://github.com/facebook/rocksdb/wiki/How-to-persist-in-memory-RocksDB-database%3F
2.  click edit button

**Comment by ajkr** [comment]
> The wiki page can be edited by anyone who already logged in.

Despite that, I can't really think of any time we saw a bad edit. Have you seen any? If not I'd rather leave it open to editing.

**Comment by kana112233** [comment]
I clicked the the [link,](https://github.com/facebook/rocksdb/wiki/How-to-persist-in-memory-RocksDB-database%3F) then I only jumped to the edited page. I guess the page‘s content is missing.

**Comment by jay-zhuang** [comment]
Thanks @kana112233 for reporting the issue. Seems sidebar link address is not updated. I just fixed that link. Thanks.
