### ISSUE TITLE
Incorrect timestamps returns by MultiGet when hit row cache

### ISSUE THREAD

**Issue by burtonli** [facebook/rocksdb#7930]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Timestamps returned by MultiGet should be matched with timestamps of WriteOptions when records were written .

### Actual behavior
When hit record cache, the returned timestamps are matched with the timestamp of ReadOptions.

### Steps to reproduce the behavior

Initial DB with enough capacity for row_cache.

1. Write record A with V1+ timestamp "1000"
2. Write record A with V2 + timestamp "2000"
3. Read record A with timestamp "1500", it returns V1 + timestamp with "1000" correctly.
4. Read record A with timestamp "1500" again (hit row cache), it returns V1 + timestamp "1500" ("1000" is expected)

**Root cause:**
In the implementation of TableCache::Get(), when the user query key hit row cache, it call replayGetContextLog() by directly passing user query key, where it will extract query timestamp (1500) instead of timestamp for the record (1000).
@riversand963

Internal ref: T86715827

**Comment by jay-zhuang** [comment]
Yes, currently timestamp + row_cache is not supported yet.

**Comment by riversand963** [comment]
Hi @burtonli , would you like to contribute this feature?

**Comment by burtonli** [comment]
I don't have plan in short future.

**Comment by thejchap** [comment]
i am happy to take a look at this one

**Comment by burtonli** [comment]
Thank you @thejchap , do we have any finding on this?

**Comment by thejchap** [comment]
@burtonli thanks for following up. got derailed with team selection and onboarding. fully onboarded now and easing back in to normal day to day life. i plan to revisit this next week.

**Comment by sherriiiliu** [comment]
Hi @thejchap , is there any update on this bug fix?

**Comment by sherriiiliu** [comment]
> Hi @thejchap , is there any update on this bug fix?

Kindly ping again @thejchap , is the bug fixed?

**Comment by cz2h** [comment]
Hi @thejchap , any updates on this issue? If this issue is still up for grad, can I work on this?

**Comment by thejchap** [comment]
@cz2h all yours
