### ISSUE TITLE
Generate rocksdb.pc (pkg-config) file in CMake

### ISSUE THREAD

**Issue by Warchant** [facebook/rocksdb#7934]
Target `gen-pc` in Makefile generates `rocksdb.pc`.
https://github.com/facebook/rocksdb/blob/21218316dabca5ffd02e5d10793fb1894e3870ae/Makefile#L2097-L2108

Please, add this target in CMakeLists.txt and also add `install` step for this file.

**Comment by alexreg** [comment]
Any chance of getting this implemented soon?
