### ISSUE TITLE
db_bench is not compatibility with -DROCKSDB_ASSERT_STATUS_CHECKED

### ISSUE THREAD

**Issue by vrqq** [facebook/rocksdb#7954]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
In **db_bench_tools.cc**
There are too much code like ```FLAGS_env->GetChildren(FLAGS_db, &files)``` or ```FLAGS_env->GetTestDirectory(&default_db_path)``` that not to check the status returned.
Does it necessary to support run bench test with that additional check? (like in DEBUG mode)

I have found that some hint in code below, so maybe it's need to be fixed.
```
WARNING: Optimization is disabled: benchmarks unnecessarily slow
WARNING: Assertions are enabled; benchmarks unnecessarily slow
```

### Steps to reproduce the behavior
just build db_bench with -DROCKSDB_ASSERT_STATUS_CHECKED

### Idea
fix it in db_bench_tools.cc or just modify the definition in **status.h** , such as
```cpp
#ifdef ROCKSDB_ASSERT_STATUS_CHECKED
  mutable bool checked_ = false;
#else
  constexpr static bool checked_ = true;  // at least c++ 11?
#endif  // ROCKSDB_ASSERT_STATUS_CHECKED
```
But it doesn't make compatibility between with and without ROCKSDB_ASSERT_STATUS_CHECKED

**Comment by vrqq** [comment]
And also on: 
https://github.com/facebook/rocksdb/blob/master/port/win/win_logger.cc#L59

BTW: Add auto test case with ROCKSDB_ASSERT_STATUS_CHECKED

**Comment by vrqq** [comment]
**Bug 2**: Since the definition ROCKSDB_ASSERT_STATUS_CHECKED change the structure of ```rocksdb::Status```, we have to build the user code also with this definition.
And there's ```#include "port/stack_trace.h"``` in include/rocksdb/status.h, it should be in folder 'include'

**Comment by riversand963** [comment]
I believe it is always useful to check the result of a function that may fail and return an error. It will be nice if db_bench does the same.

**Comment by riversand963** [comment]
Since this is expected instead of a bug, closing.
