### ISSUE TITLE
rocksdb shared lib link error

### ISSUE THREAD

**Issue by leon-db** [facebook/rocksdb#7975]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
   rocksdb build success
### Actual behavior
![image](https://user-images.githubusercontent.com/7334994/108351303-4a89d900-7220-11eb-99db-a0d8e7f487d6.png)

### Steps to reproduce the behavior
1.   /usr/bin/cmake3 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/usr/bin/make -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -DPORTABLE=1 -DWITH_GFLAGS=1 -G "CodeBlocks - Unix Makefiles" /tmp/tmp.eREQymHrEg
2. make rocksdb   // success 
3. but when i run `make db_bench`. it hit the link error.   and can't see the librt in the output of `ldd rocksdb.so `

**Comment by mrambacher** [comment]
I attempted this on my machine and do not see the issue.  Can you do "VERBOSE=1 make db_bench" so we can see what libraries db_bench is linking against?  

On my machine, the GFLAGS library is a static (libgflags.a) library and not dynamic.  I do not know if that would necessarily cause your problem however.

**Comment by leon-db** [comment]
![image](https://user-images.githubusercontent.com/7334994/108451455-d0019d80-72a1-11eb-8a0d-dcd0e57be4e7.png)

the output shows it not link the necessary libs.

**Comment by mrambacher** [comment]
In your gflags header file, what is GFLAGS_NAMESPACE defined as?  If you look in the libflags.so file, what is the namespace of one of those missing methods?

**Comment by leon-db** [comment]
gflags_declare.h:43:#define GFLAGS_NAMESPACE google.
![image](https://user-images.githubusercontent.com/7334994/108589128-dbcf8b80-7397-11eb-8a67-32c63142540a.png)

with time is tight, when i change the env from centos6 to centos7. and install devtoolset-4,   
mkdir build && cd build; 
cmake ..  
make -j 8 
then all is ok.
