### ISSUE TITLE
[BUG] CompactRange does not apply to all the records in range.

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#7983]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
CompactRange, as is described in the comments, in db.h, quoted below, is intended to apply to a superset of the input range.
```
  // Compact the underlying storage for the key range [*begin,*end].
  // The actual compaction interval might be superset of [*begin, *end].
```
### Actual behavior
In fact, in several situations, it does not behave so.
A subset of records in the range may be missed when auto compaction or flush run parallely with manual compaction.

### Steps to reproduce the behavior
A brief summery of `DBImpl::CompactRangeInternal` (specially for LevelCompaction) is list below:
```
1)  Flush MemTable if memtable is overlapped with the range
2)  Find first_overlapped_level  and  max_overlapped_level which overlaps with the range
3)  Foreach level in [first_overlapped_level, max_overlapped_level], schedules a `ManualCompaction` and wait for it to complete
```
The problem happens in step 3), that Manual Compaction is run one by one, the procedure is not atomic, during which, a file may have been moved by `AutoCompaction` from some input level into a level which is not in [first_overlapped_level, max_overlapped_level], so that, some records in the range may be missed in the execution of CompactRange.

**Comment by anand1976** [comment]
A ```CompactRange``` will compact all files in the given range from L0 to bottommost level. If ```exclusive_manual_compaction``` is set (default), then auto and manual compaction should not happen at the same time. They could get interleaved, but why is that a problem? Can you give a specific example?

**Comment by wolfkdy** [comment]
1) Because sst files may have been moved outside of `max_overlapped_level` after `max_overlapped_level` is calculated 
https://github.com/facebook/rocksdb/blob/469164dc3c25bbf1128b9f2ddcd301a304634e0e/db/db_impl/db_impl_compaction_flush.cc#L961 
2) `manual compaction` is exclusive, but CompactRangeInternal calls `manual compaction` several times, from first_overlapped_level  to max_overlapped_level, after each time a `manual compaction` ends while the next `manual compaction` is not started, an `auto compaction` may silently `trivial move`  a file to level `max_overlapped_level` + 1.

If it's hard to imagine, I may provide an unittest to reproduce

**Comment by anand1976** [comment]
> 2. `manual compaction` is exclusive, but CompactRangeInternal calls `manual compaction` several times, from first_overlapped_level  to max_overlapped_level, after each time a `manual compaction` ends while the next `manual compaction` is not started, an `auto compaction` may silently `trivial move`  a file to level `max_overlapped_level` + 1.

This indeed does sound like a bug. If the auto compaction compacts a overlapping file from ```max_overlapped_level``` to ```max_overlapped_level + 1```, then it would get missed. It seems like this could happen due to a trivial move or a regular compaction.  One way to fix it could be to calculate overlap with the next level after every manual compaction. @ajkr What do you think?

**Comment by ajkr** [comment]
> > 1. `manual compaction` is exclusive, but CompactRangeInternal calls `manual compaction` several times, from first_overlapped_level  to max_overlapped_level, after each time a `manual compaction` ends while the next `manual compaction` is not started, an `auto compaction` may silently `trivial move`  a file to level `max_overlapped_level` + 1.
> 
> This indeed does sound like a bug. If the auto compaction compacts a overlapping file from `max_overlapped_level` to `max_overlapped_level + 1`, then it would get missed. It seems like this could happen due to a trivial move or a regular compaction. One way to fix it could be to calculate overlap with the next level after every manual compaction. @ajkr What do you think?

Yeah, I think we can get rid of the loop that pre-computes the level range, and just loop from 0 to num_levels(), breaking early when there's no possibility of anymore overlap.

If we do end up changing the loop structure, it'd be nice if we can unify the `kForceBottommost*` cases. In case of L0->L1 and L0->Lbase we handle it by disabling trivial move, whereas in other cases we handle it by making an extra call to `RunManualCompaction()` with `max_overlapped_level` as the input level. A user found the former approach problematic due to simultaneous readahead on all L0 compaction inputs causing OOM.

**Comment by cz2h** [comment]
Hi, can I grab this one if it was not been taken/resolved?

**Comment by ajkr** [comment]
Sorry I missed updating this. #11468 got rid of pre-computing `max_overlapped_level`.
