### ISSUE TITLE
so many deleted sstfile fd not release

### ISSUE THREAD

**Issue by CCPig** [facebook/rocksdb#7986]
![image](https://user-images.githubusercontent.com/39623381/108646328-64613f80-74f0-11eb-8afa-b8503bb9f823.png)
detail:I write the data into rocksdb by date index including inserting and replacing .Just start working, there is no deleted sst like this, but on the next day appearing many sst deleted fd.Can  someone of big gods resolve this problem?

**Comment by riversand963** [comment]
Are you using Java API or C++? Also RocksDB version, etc....

**Comment by dinardov** [comment]
I'm seeing the same issue in C#, see #8211.
