### ISSUE TITLE
L0 compaction score is boosted to help subcompactions even when subcompactions are disabled

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#7996]
### Expected behavior

I expect the L0 compaction score to be based on the number of SSTs in the L0 and the L0 compaction trigger.

### Actual behavior

The L0 compaction score can be boosted to help with subcompactions even when subcompactions are disabled (max_subcompactions=0).

### Steps to reproduce the behavior

1) Setup RocksDB with level0_file_num_compaction_trigger=8, max_subcompactions=1, target_file_size_base=64M and write_buffer_size large enough to get ~8M L0 SSTs.
2) Insert enough values so there are 6 SSTs in L0
3) Look at the compaction IO statistics and see that the compaction score for L0 is 1 when I expect it to be 0.75

This change is from [this diff](https://github.com/facebook/rocksdb/commit/d659faad54741933df5339f7f5be1cc420dcd9ed).

And is on [line 2626](https://github.com/facebook/rocksdb/blob/master/db/version_set.cc#L2626) in version_set today.

Look for this code in ComputeCompactionScore
```
          score =
              std::max(score, static_cast<double>(total_size) / l0_target_size);
```

**Comment by ajkr** [comment]
The motivation for that change was not related to subcompactions. The motivation was to prioritize L0->Lbase when size(L0) is large, even though the L0 file count may be low due to intra-L0 compactions.

Is there a different way to phrase the expected behavior in terms of what is the deficiency in write-amp or other metrics?

**Comment by ajkr** [comment]
The title is inaccurate. Please provide more details and reopen if needed.
