### ISSUE TITLE
creation time can not be read

### ISSUE THREAD

**Issue by zhougit86** [facebook/rocksdb#8014]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

i am using JNI the FIFO compaction and snapshot sst files to hdfs and recover it from previous run, looks like the SST file lost the creation time table property, can any body suggest how can i fix this?

2021/03/01-18:51:01.202049 7f59042fc700 (Original Log Time 2021/03/01-18:51:01.200883) [/compaction/compaction_picker_fifo.cc:107] [_timer_state/processing_user-timers] FIFO compaction: picking file 1710 with creation time 0 for deletion

 

the configuration is like 

currentOptions.setCompactionStyle(getCompactionStyle());
currentOptions.setLevel0FileNumCompactionTrigger(8);
CompactionOptionsFIFO compactionOptionsFIFO = new CompactionOptionsFIFO();
compactionOptionsFIFO.setMaxTableFilesSize(MemorySize.parse("8gb").getBytes());
compactionOptionsFIFO.setAllowCompaction(true);

 

the rocksdb version is 

<dependency>
<groupId>io.github.myasuka</groupId>
<artifactId>frocksdbjni</artifactId>
<version>6.10.2-ververica-3.0</version>
</dependency>

**Comment by adamretter** [comment]
@ajkr do you know of any existing issues with `creation time` appearing as `0`?

**Comment by ajkr** [comment]
I can repro on RocksDB 6.19.1 by setting `max_open_files > 0`. We say it has to be -1 (unlimited) but it's not enforced:
https://github.com/facebook/rocksdb/blob/96205baa63f2b38774fccd5586d086c7cd24e71e/include/rocksdb/advanced_options.h#L706
 @zhougit86 can you check the setting for `max_open_files` in your LOG or OPTIONS file? If it's a positive number, then we know creation time is zero for the unopened files (always the compaction results in my experiments). If it's -1 that should not be the problem, in which case do you know of any other config that might prevent RocksDB from opening all the files?

**Comment by ajkr** [comment]
Unassigned under assumption you got it originally for the mention of Java - please feel free to reclaim.

**Comment by thejchap** [comment]
@ajkr While looking into this I found [this test](https://github.com/facebook/rocksdb/blob/master/db/db_test.cc#L3509-L3523). [this assertion](https://github.com/facebook/rocksdb/blob/master/db/db_test.cc#L3516-L3519) seems to disagree with what I've read in the [wiki](https://github.com/facebook/rocksdb/wiki/FIFO-compaction-style#fifo-compaction-with-ttl) and [comments](https://github.com/facebook/rocksdb/blob/96205baa63f2b38774fccd5586d086c7cd24e71e/include/rocksdb/advanced_options.h#L706). It seems like we want to disallow that combo of options with a `Status::NotSupported` and update that test? Or did I misread something somewhere 🧐

**Comment by ajkr** [comment]
Yeah, that assertion and the comment just above it ("... is now supported ...") appear wrong. I think it should say "... is not supported ..." and we would assert `Status::NotSupported` is returned, as you said.
