### ISSUE TITLE
db_bench failed

### ISSUE THREAD

**Issue by leon-db** [facebook/rocksdb#8018]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
db_bench --gtest_filter=* --gtest_color=no   test ok
### Actual behavior
ERROR: unknown command line flag 'gtest_filter'
ERROR: unknown command line flag 'gtest_color'

### Steps to reproduce the behavior
rocksdb version 5.7
1. compile
2. run  db_bench --gtest_filter=* --gtest_color=no

**Comment by mrambacher** [comment]
Isn't gtest_filter for tests not tools?  db_bench would use flags not the tests.

What were you trying to run?
