### ISSUE TITLE
RocksDB crashes on DB::Open() when following getting started guide

### ISSUE THREAD

**Issue by kitattyor** [facebook/rocksdb#8019]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Should not crash

### Actual behavior

Seems like it's crashing on [this line](https://github.com/facebook/rocksdb/blob/72d1e258cdbdeba4fbd0de116b277959f5bad8bb/options/configurable.cc#L75) if I create connector object outside the main scope (see code below). 

### Steps to reproduce the behavior

```
#include "rocksdb/db.h"

class RocksDBConnector {
private:
  /* data */
public:
  RocksDBConnector();
  ~RocksDBConnector();

private:
  rocksdb::DB *db;
};

RocksDBConnector::RocksDBConnector() {
  const std::string db_path = "D:\\DebugDB\\test";
  rocksdb::Options options;
  options.create_if_missing = true;

  rocksdb::Status status = rocksdb::DB::Open(options, db_path, &db);

  assert(status.ok());
}

RocksDBConnector::~RocksDBConnector() { delete db; }

static RocksDBConnector rocks_;
int main(int, char **) {
    return 0;
}
```

This works fine:
```
int main(int, char **) {
    static RocksDBConnector rocks_;
    return 0;
}
```

**Comment by riversand963** [comment]
The `Configurable` is a newly added type which I am not very familiar with. Maybe @mrambacher can chime in.

Generally, global static objects are dangerous because such objects in different translation units can be initialized in undeterministic order. It will be dangerous if there are dependencies among them.
If you do want something similar, you can do
```
RocksDBConnector& GetRocksDBConnector() {
  static RocksDBConnector rocks_;
  return rocks_;
}
int main(int, char**) {
  return 0;
}
```

**Comment by anand1976** [comment]
@kitattyor As @riversand963 mentioned, global static object initialization order is undefined, and the ```type_map``` is  typically a static ```unordered_map```, so its probably not initialized when ```DB::Open``` is called. Let us know if the alternative mentioned in the previous comment doesn't work.
