### ISSUE TITLE
The meaning of db_bench test results

### ISSUE THREAD

**Issue by springeee** [facebook/rocksdb#8023]
Hi all:
     Using db_bench can easily test the performance of rocksdb in different read-write modes . but I don't know the different parameters' meaning in test results.
     This link https://github.com/facebook/rocksdb/wiki/Performance-Benchmarks , we can see the db_bench test results. But don't know the results' meaning . for example W-Amp .
" ops/sec	mb/sec	Size-GB	L0_GB	Sum_GB	W-Amp	W-MB/s	usec/op	p50	p75	p99	p99.9	p99.99	Uptime	Stall-time	Stall%	Test "
     Where can I find the documentation of test results ?

Thanks,
Regards 
Spring
  

Significance of different parameters in test results

**Comment by akankshamahajan15** [comment]
@springeee, W-Amp means write amplification. 
You can refer these docs for db_bench: https://github.com/facebook/rocksdb/wiki/Benchmarking-tools, https://github.com/facebook/rocksdb/wiki/RocksDB-In-Memory-Workload-Performance-Benchmarks

db_bench uses script tool/benchmark.sh that prints the output. https://github.com/facebook/rocksdb/blob/1600aac46f64f906631f64d036b2ea5359c7ef5f/tools/benchmark.sh#L155

> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Closing this for now.
