### ISSUE TITLE
When I set flush_options.wait = 1, FlushMemTable return ok but memtable does not synchronize flush 

### ISSUE THREAD

**Issue by zhuchong0329** [facebook/rocksdb#8046]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
FlushMemTable return failed 
### Actual behavior
FlushMemTable return ok
### Steps to reproduce the behavior
1、In my environment ：db_options_.paranoid_checks = ture and auto_recovery_ = true
2、One compaction thread encountered a problem of insufficient disk space, so it set SetBGError. The bg_error_ will be set kSoftError.
3、Another compaction thread also encountered a problem of insufficient disk space, so it set SetBGError . The recovery_error will be set.
4、My code set flush_options.wait = 1  then call  DBImpl::Flush .
5、FlushMemTable  return ok but flush memtable thread failed with an insufficient disk space error.

### Where is the bug I guess
![image](https://user-images.githubusercontent.com/9687347/110574879-e4e29a00-8198-11eb-9ea8-6a2ef6bdcb64.png)

**Comment by riversand963** [comment]
Sounds reasonable, thanks for reporting @zhuchong0329 .
Are you willing to submit a fix?

**Comment by zhuchong0329** [comment]
It is easy to fix it. I will submit a merge request this weekend.
