### ISSUE TITLE
ldb tool load doesn’t write all values back into the database.

### ISSUE THREAD

**Issue by ytrezq** [facebook/rocksdb#8052]
The issue appears when dumping a full archive EthereumDatabase from latest OpenEthereum and using the latest code from this repository concerning the `ldb` tool.

    ulimit -n 131072
    ./ldb --db=/mnt/OpenEthereum/ethereum/db/906a34e69aec8c0d/archive/db dump --hex --column_family=col4 > /mnt/col4
    cat /mnt/col4 | ./ldb --db=/mnt/EthereumNew/ethereum/db/906a34e69aec8c0d/archive/db load --hex --compression_type=no --try_load_options --block_size=16384 --column_family=col4 --bulk_load --disable_wal
    # Keys in range: 11931536
    cat /mnt/col4 | ./ldb --db=/mnt/EthereumNew/ethereum/db/906a34e69aec8c0d/archive/db load --hex --compression_type=no --try_load_options --block_size=16384 --column_family=col4 --bulk_load --disable_wal
    # Keys in range: 2362

where `/mnt/EthereumNew/ethereum/db/906a34e69aec8c0d/archive/db`is a fresh empty started database with the exact same  configuration as `/mnt/OpenEthereum/ethereum/db/906a34e69aec8c0d/archive/db`
So only 100Mib is restored out of 1 Tib.
More exactly, it seems the ldb load command stops to write after a random specific row so that the restored data never exceed 64Gib.

**Comment by riversand963** [comment]
Maybe I am missing something. Two consecutive execution of
```
cat /mnt/col4 | ./ldb --db=/mnt/EthereumNew/ethereum/db/906a34e69aec8c0d/archive/db load --hex --compression_type=no --try_load_options --block_size=16384 --column_family=col4 --bulk_load --disable_wal
```
give different results? Can you sanity check /mnt/col4?

It also looks like the result of `Put()` during the execution of load is not checked: https://github.com/facebook/rocksdb/blob/6.18.fb/tools/ldb_cmd.cc#L1015. (I do not know the RocksDB version you are using, so just assume 6.18). Should anything happen and cause the Put() to fail, we do not know unfortunately. This should be fixed.

**Comment by ytrezq** [comment]
@riversand963 ok. it was the ulimit on the number of open files which was too low. And the real issue is `ldb` doesn t detect the resulting error and instead peform gargbage.

**Comment by riversand963** [comment]
Yeah, we should fix this for ldb. Thanks for reporting.

**Comment by riversand963** [comment]
@ytrezq is this resolved?

**Comment by ytrezq** [comment]
I don't know. Trying to backup the database damaged both the source disk and the destination.

**Comment by ytrezq** [comment]
I don't know. Trying to backup the database damaged both the source disk and the destination.

**Comment by riversand963** [comment]
> I don't know. Trying to backup the database damaged both the source disk and the destination.

Is /mnt/OpenEthereum/ethereum/db/906a34e69aec8c0d/archive/db damaged?

**Comment by riversand963** [comment]
the dump command does not write data to the database. Did you try to write any data to the source?

**Comment by ytrezq** [comment]
> the dump command does not write data to the database. Did you try to write any data to the source?

I said source disk and destination disk. The hardware is damaged not the database directly.

**Comment by riversand963** [comment]
> > the dump command does not write data to the database. Did you try to write any data to the source?
> 
> I said source disk and destination disk. The hardware is damaged not the database directly.

This sounds a different issue from the one reported here.

> it was the ulimit on the number of open files which was too low. And the real issue is ldb doesn t detect the resulting error and instead peform gargbage.
Closing this one for now, since the error seen should be reported by latest ldb.

**Comment by ytrezq** [comment]
@riversand963 then please reopen as even the version of February 2021 doesn t produce any errors.

**Comment by riversand963** [comment]
My prior comment (posted in March) proposes that the issue should be detected/fixed by https://github.com/facebook/rocksdb/commit/063a68b9cd9e66727bde1e59f17aba53c0ae03db merged in March 2021. Have you tried a version since 6.19? If not, can you try it? If it still fails, we can reopen. Posting the commands you used and the resulting LOGs will be appreciated.

> Closing this one for now, since the error seen should be reported by latest ldb.
