### ISSUE TITLE
CircleCI build-linux-clang10-mini-tsan sometimes reporting data race in DBTest.GetLiveBlobFiles

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#8056]
See e.g. https://app.circleci.com/pipelines/github/facebook/rocksdb/6125/workflows/7c916e2a-0fb8-4d16-b724-e58d15d91944/jobs/104560 and https://app.circleci.com/pipelines/github/facebook/rocksdb/6128/workflows/34f237ac-fdfa-435e-a4e6-34101fc01763/jobs/104669

**Comment by ltamasi** [comment]
Should be fixed now (b708b166dc7093e08dcd432edcff0b39c581ec21).
