### ISSUE TITLE
Flaky test DBWALTestWithParam/DBWALTestWithParam.WALTrashCleanupOnOpen

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#8057]
Example failure https://app.circleci.com/pipelines/github/facebook/rocksdb/6144/workflows/6800febc-2adb-442d-b821-dae4149b6a4a/jobs/105052:

[139/1952] DBWALTestWithParam/DBWALTestWithParam.WALTrashCleanupOnOpen/0 (33351 ms)
Note: Google Test filter = DBWALTestWithParam/DBWALTestWithParam.WALTrashCleanupOnOpen/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DBWALTestWithParam/DBWALTestWithParam
[ RUN      ] DBWALTestWithParam/DBWALTestWithParam.WALTrashCleanupOnOpen/0
db/db_sst_test.cc:588: Failure
Expected: (trash_log_count) >= (1), actual: 0 vs 1
[  FAILED  ] DBWALTestWithParam/DBWALTestWithParam.WALTrashCleanupOnOpen/0, where GetParam() = ("", true) (33347 ms)
[----------] 1 test from DBWALTestWithParam/DBWALTestWithParam (33347 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (33347 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DBWALTestWithParam/DBWALTestWithParam.WALTrashCleanupOnOpen/0, where GetParam() = ("", true)

 1 FAILED TEST

**Comment by akankshamahajan15** [comment]
Issue raised in https://github.com/facebook/rocksdb/issues/7546
Closing this one.
