### ISSUE TITLE
Snappy is used even if Options::compression is set to ZSTD

### ISSUE THREAD

**Issue by AlexNk** [facebook/rocksdb#8060]
### Steps to reproduce the behavior
RocksDB 6.15.4

1. Compile with Snappy to be able to read Snappy-based DBs.
2. Create a new ZSTD-based DB: Options::compression = kZSTD
3. Options::compression_per_level.clear()
4. Write some data into DB
5. Try to open this DB with a binary, created without Snappy

### Actual behavior
DB fails to open with the exception "Unsupported compression method or corrupted compressed block contents: Snappy" 

### Expected behavior
DB must open and read with no problems

**Comment by riversand963** [comment]
Can you double check the db is a freshly-created? Maybe the file was created before using Snappy.
I tried to reproduce with the following code snippet, but sst_dump shows the file created is compressed with zstd.
```
diff --git a/db/db_basic_test.cc b/db/db_basic_test.cc
index 63a225252..52c5739e0 100644
--- a/db/db_basic_test.cc
+++ b/db/db_basic_test.cc
@@ -34,6 +34,18 @@ class DBBasicTest : public DBTestBase {
   DBBasicTest() : DBTestBase("/db_basic_test", /*env_do_fsync=*/false) {}
 };

+TEST_F(DBBasicTest, Test1) {
+  Options options = GetDefaultOptions();
+  options.env = env_;
+  options.create_if_missing = true;
+  options.compression = CompressionType::kZSTD;
+  DestroyAndReopen(options);
+  for (int i = 0; i < 5000; ++i) {
+    ASSERT_OK(Put("key" + std::to_string(i), std::string(1024, '\xff')));
+  }
+  ASSERT_OK(Flush());
+}
+
 TEST_F(DBBasicTest, OpenWhenOpen) {
   Options options = CurrentOptions();
   options.env = env_;
```

```
$./sst_dump --file=/tmp/rocksdbtest-148062/db_basic_test_8608830700614650517/ --command=check --show_properties

```

**Comment by AlexNk** [comment]
The DB is always freshly-created. I made more tests and it seems that the problem only happens with larger DBs. In my case, it's 1GiB and more.

**Comment by riversand963** [comment]
@AlexNk  Can you share a .cc file that reproduces the bug? I have tried the steps you posted, but cannot reproduce it myself.

**Comment by mrambacher** [comment]
@AlexNk Some other questions.  
- Are you using one of the tools (ldb, db_bench, etc) to create the DB or your own code?
- Are you performing any manual compactions? 
- When this error happens, can you determine what SST file is compressed incorrectly and at what level it exists?
- Does the OPTIONS file refer to snappy at all and does it match the settings you were expecting?

**Comment by AlexNk** [comment]
> Can you share a .cc file that reproduces the bug

The whole CC would be too large. This is the code to create a DB:

    rocksdb::Options options;
    options.compression = rocksdb::kZSTD;
    options.create_if_missing = true;
    options.compression_per_level.clear();
    options.target_file_size_base = 100_MiB;
    options.target_file_size_multiplier = 3;
    options.max_bytes_for_level_base = 100_MiB;
    rocksdb::DB *pdb;
    auto status = rocksdb::DB::Open( options, db_path, &pdb );


And then it's just storing a lot of values by using Put or batch->Put. 

> Are you using one of the tools (ldb, db_bench, etc) to create the DB or your own code?

My code. See above.

> Are you performing any manual compactions?

No

> When this error happens, can you determine what SST file is compressed incorrectly and at what level it exists?
> Does the OPTIONS file refer to snappy at all and does it match the settings you were expecting?

Next time it will happen, I will check and share the results. 

I found several places like this in RocksDB code:

    if (sampled_output_fast && (LZ4_Supported() || Snappy_Supported())) 
    {
        CompressionType c = LZ4_Supported() ? kLZ4Compression : kSnappyCompression;

And Snappy_Supported() returns true if it was linked with Snappy. So basically, in some cases, it will be used as a default compression. Though, I don't know if it really the reason and if it affects something.

**Comment by riversand963** [comment]
> And Snappy_Supported() returns true if it was linked with Snappy. So basically, in some cases, it will be used as a default compression. Though, I don't know if it really the reason and if it affects something.

Not really. RocksDB has an option `sample_for_compression` (https://github.com/facebook/rocksdb/blob/master/include/rocksdb/advanced_options.h#L759) to try compressiong a block using other compression algorithms. This is just to sample for the effectiveness of different compression algorithms, and will not violate user-specified compression because sampled_output_fast/sampled_output_slow are **not** actually written to disk. Sometimes, if no size reduction results from compression, then no compression will be used. You can see the details in `CompressBlock()`.
