### ISSUE TITLE
`CompactFiles` does not properly expand inputs when moving data up in the LSM

### ISSUE THREAD

**Issue by ajkr** [facebook/rocksdb#8063]
From code inspection while reviewing #8024, I noticed we only expand inputs while traversing downwards through the levels. But we do not require users set output_level  at or below the lowest level of a file included in the compaction. The screenshots show an example LSM setup and `CompactFiles()` call (the target level is 1 but files are included from level 2) where this approach does not include all necessary files in the compaction, leading to a compaction failing on `Status::Corruption` that requires restarting the DB.

<img width="449" alt="Screen Shot 2021-03-15 at 1 35 53 PM" src="https://user-images.githubusercontent.com/4780362/111219092-d6c7bb80-8594-11eb-8e17-8c3de65fd30a.png">
<img width="836" alt="Screen Shot 2021-03-15 at 1 37 15 PM" src="https://user-images.githubusercontent.com/4780362/111219113-daf3d900-8594-11eb-8300-0c99d59eb450.png">

**Comment by ajkr** [comment]
A bigger problem is we don't check overlap in the levels that data passes over when being moved up by `CompactFiles()`. Perhaps we should disallow moving data up in the LSM via this API.

**Comment by jay-zhuang** [comment]
@ajkr is there any usecase that compaction needs to move up the data? In #8116, I just added the vilification for all compactions, what do you think?

**Comment by ajkr** [comment]
> @ajkr is there any usecase that compaction needs to move up the data? In #8116, I just added the vilification for all compactions, what do you think?

I think that's good. The usual use case for moving data up is to migrate compaction styles, but that's better done with `CompactRange()`'s `change_level` / `target_level` options.
