### ISSUE TITLE
db_with_timestamp_basic_test takes ~7 minutes single-thread (~15 minutes on Travis PPC)

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#8073]
For comparison (local runs):
db_basic_test: 0.5 min
db_test: 16 min (includes multithreaded mini-stress test)
db_test2: 4 min

Recent timeout on Travis:
https://travis-ci.org/github/facebook/rocksdb/jobs/763352334

What stood out in the Travis run was all the expensive tests in db_with_timestamp_basic_test, which is in TESTS_PLATFORM_DEPENDENT perhaps only because it used to be fast and short.

It seems like this test is testing way too many configurations. Can we do something to reduce exponential blow-up (DBBasicTestWithTimestampFilterPrefixSettings especially)? Can we at least take this test out of platform-dependent?

**Comment by riversand963** [comment]
I think this is the direction to proceed. Since db_with_timestamp_basic_test covers a variety of RocksDB features, it makes sense to separate them into dedicated tests, e.g. db_with_timestamp_iterator_test.cc, db_with_timestamp_point_lookup.cc, etc.

**Comment by pdillinger** [comment]
That could help people working on timestamp who want to run a subset of tests. We should be able to parallelize the tests for full testsuite runs simply by adding to PARALLEL_TEST. I'm mostly concerned about (a) the overall CPU cost of running the tests relative to the feature set covered, and (b) (likely unnecessary) inclusion in the "platform dependent" set.

**Comment by riversand963** [comment]
Seems we do not have a standard for which tests go into "platform dependent" set (https://github.com/facebook/rocksdb/blob/master/Makefile#L760), and I think we can remove `db_with_timestamp_basic_test` from the list.
