### ISSUE TITLE
use java api operate ,if application happen error  transaction not  commit close, memory or disk if exist transaction not commit data?

### ISSUE THREAD

**Issue by dev-zl** [facebook/rocksdb#8089]
### Expected behavior
if exist  please tell my,How to deal with such data.

thanks

**Comment by ajkr** [comment]
Transactions only become visible to readers after they are committed. Before that, the transaction writes are buffered in memory, so their state would be lost after a crash. (Assuming you are not using WRITE_PREPARED or WRITE_UNPREPARED.)

**Comment by ajkr** [comment]
See the wiki (https://github.com/facebook/rocksdb/wiki/Transactions) and also let us know if you need further help.

**Comment by dev-zl** [comment]
@ajkr One more question，my in (https://github.com/facebook/rocksdb/wiki/Transactions)  not find,
if one transaction long time not  commit or close , will it auto end?

**Comment by ajkr** [comment]
A transaction can be held open forever. There is no automatic commit or timeout.

**Comment by dev-zl** [comment]
> A transaction can be held open forever. There is no automatic commit or timeout.

@ajkr thanks .
