### ISSUE TITLE
rocksdbjni-6.14.6 SstFileReader open hdfs sst  happens Corruption "offset 10516580470, expected 97627493 bytes, got 86620042"

### ISSUE THREAD

**Issue by huangmiumang** [facebook/rocksdb#8096]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

when use rocksdb java hdfs api:
```
private final Options options = new Options();
final Env env = new HdfsEnv("hdfs://xxx");
sstFileReader = new SstFileReader(options);
sstFileReader.open("hdfs://xxx.sst"); // the sst file size is 10G
```
it happens:
```
org.rocksdb.RocksDBException: truncated block read from...  offset 10516580470, expected 97627493 bytes, got 86620042
```
but if download the sst in local, use local SstFileReader, it works.

**Comment by adamretter** [comment]
@shamomanba If I want to reproduce your problem... Is it enough for me to create a 10GB SST file, store it into HDFS and then run your code above? Also which version of RocksDB are you using please?

**Comment by shamomanba** [comment]
create 10G sst file: through SstFileWriter
version of RocksDB: 6.14.6
