### ISSUE TITLE
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’

### ISSUE THREAD

**Issue by nwcs** [facebook/rocksdb#810]
OS:Raspberry Pi 2
uname -a
4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux

g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.9/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libitm --disable-libquadmath --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-armhf --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-armhf --with-arch-directory=arm --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.9.2 (Raspbian 4.9.2-10)

apt-get install libsnappy-dev zlib1g-dev libbz2-dev  libgflags-dev
cd rocksdb-4.0 
rocksdb-4.0# make shared_lib
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’
g++: error: unrecognized command line option ‘-momit-leaf-frame-pointer’

**Comment by igorcanadi** [comment]
I would be surprised if this is the only compile error for Raspberry Pi :)

But it should be easy to fix. We already have a option to not include -momit-leaf-frame-pointer when compiling for ppc64: https://github.com/facebook/rocksdb/blob/master/Makefile#L79

We just need to add Raspberry Pi to the list of machines.

**Comment by nwcs** [comment]
Thank you!

vi /root/.bashrc
export LD_PRELOAD=/lib/arm-linux-gnueabihf/librt-2.19.so
source /root/.bashrc 

cd rocksdb-4.0
vi Makefile 
......
# compile with -O2 if debug level is not 2
ifneq ($(DEBUG_LEVEL), 2)
### add -lrt
OPT += -O2 -lrt
ifneq ($(MACHINE),ppc64) # ppc64 doesn't support -momit-leaf-frame-pointer
OPT += 
endif
endif
.........



rocksdb-4.0# ll
total 111536
-rw-rw-r--  1 root root       225 Oct 16 06:05 appveyor.yml
drwxrwxr-x  6 root root      4096 Oct 16 06:05 arcanist_util
-rw-rw-r--  1 root root       247 Oct 16 06:05 AUTHORS
drwxrwxr-x  2 root root      4096 Oct 16 06:05 build_tools
-rw-rw-r--  1 root root     13200 Oct 16 06:05 CMakeLists.txt
-rw-rw-r--  1 root root       733 Oct 16 06:05 CONTRIBUTING.md
drwxrwxr-x  2 root root      4096 Oct 16 06:05 coverage
drwxrwxr-x  2 root root     12288 Nov  2 13:35 db
drwxrwxr-x  2 root root      4096 Oct 16 06:05 doc
-rw-rw-r--  1 root root       763 Oct 16 06:05 DUMP_FORMAT.md
drwxrwxr-x  2 root root      4096 Oct 16 06:05 examples
drwxrwxr-x  2 root root      4096 Oct 16 06:05 hdfs
-rw-rw-r--  1 root root     26408 Oct 16 06:05 HISTORY.md
drwxrwxr-x  4 root root      4096 Nov  3 09:12 include
-rw-rw-r--  1 root root      3503 Oct 16 06:05 INSTALL.md
drwxrwxr-x  7 root root      4096 Oct 16 06:05 java
-rw-r--r--  1 root root 113944526 Nov  3 09:05 librocksdb.a
-rw-rw-r--  1 root root      1646 Oct 16 06:05 LICENSE
-rw-r--r--  1 root root       888 Nov  3 09:21 make_config.mk
-rw-rw-r--  1 root root     38274 Nov  2 11:00 Makefile
-rw-rw-r--  1 root root      1978 Oct 16 06:05 PATENTS
drwxrwxr-x  3 root root      4096 Nov  2 13:34 port
-rw-rw-r--  1 root root      1268 Oct 16 06:05 README.md
-rw-rw-r--  1 root root      1038 Oct 16 06:05 ROCKSDB_LITE.md
-rw-rw-r--  1 root root     20313 Oct 16 06:05 src.mk
drwxrwxr-x  2 root root      4096 Nov  2 13:37 table
drwxrwxr-x  5 root root      4096 Oct 16 06:05 third-party
-rw-rw-r--  1 root root      5609 Oct 16 06:05 thirdparty.inc
drwxr-xr-x  2 root root      4096 Nov  2 12:14 tmp
drwxrwxr-x  4 root root      4096 Nov  2 13:26 tools
-rw-rw-r--  1 root root      2114 Oct 16 06:05 USERS.md
drwxrwxr-x  2 root root     12288 Nov  3 09:21 util
drwxrwxr-x 17 root root      4096 Oct 16 06:05 utilities
-rw-rw-r--  1 root root       862 Oct 16 06:05 Vagrantfile
-rw-rw-r--  1 root root     12835 Oct 16 06:05 WINDOWS_PORT.md

Compile success!!!

**Comment by benoitc** [comment]
checking for `armv7l`  on raspberry 2 does the tricks (and the tests from our CI pass) . What would be the proper patch to add its support? Btw why enabling this function? Why not simply using `-02` and no `-fno-omit-frame-pointer` or `-momit-leaf-frame-pointer` ?

**Comment by igorcanadi** [comment]
@benoitc https://github.com/facebook/rocksdb/pull/964 is a good fix :)

We just need to make sure that we're not breaking the compile, by setting a proper CI

**Comment by igorcanadi** [comment]
Even better fix would be to detect if a compiler supports `-momit-leaf-frame-pointer` in https://github.com/facebook/rocksdb/blob/master/build_tools/build_detect_platform and pass that information to the Makefile.
