### ISSUE TITLE
Suspected memory leak in UncompressBlockContentsForCompressionType

### ISSUE THREAD

**Issue by lokeshj1703** [facebook/rocksdb#8128]
We have a use case with rocksDB where a process has 200K rocksdb instances. Every instance holds 1000+ key value pairs. When the process starts it opens every instance to read some metadata and then closes the db. Even after closing all the instances the process shows high memory usage in UncompressBlockContentsForCompressionType according to jeprof results(Attachment - app-profiling.122753.331.pdf). 

We are using rocksdb java api (rocksdbjni:6.8.1).

ColumnFamilyOptions and DBOptions are cached and reused for all the rocksdb instances.

ColumnFamilyOptions: 
  cache_index_and_filter_blocks: 1
  cache_index_and_filter_blocks_with_high_priority: 0
  pin_l0_filter_and_index_blocks_in_cache: 1
  pin_top_level_index_and_filter: 1
  index_type: 0
  data_block_index_type: 0
  index_shortening: 1
  data_block_hash_table_util_ratio: 0.750000
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x7f5cf2c11330
  block_cache_name: LRUCache
  block_cache_options:
    capacity : 268435456
    num_shard_bits : 6
    strict_capacity_limit : 0
    memory_allocator : None
    high_pri_pool_ratio: 0.000
  block_cache_compressed: (nil)
  persistent_cache: (nil)
  block_size: 16384
  block_size_deviation: 10
  block_restart_interval: 16
  index_block_restart_interval: 1
  metadata_block_size: 4096
  partition_filters: 0
  use_delta_encoding: 1
  filter_policy: rocksdb.BuiltinBloomFilter
  whole_key_filtering: 1
  verify_compression: 1
  read_amp_bytes_per_bit: 0
  format_version: 2
  enable_index_compression: 1
  block_align: 0

### Expected behavior
Initially all the rocksdb instances are opened in read only mode to load some data. After this step all the instances are closed. Since all the dbs are closed the memory used by rocksdb should be negligible.

### Actual behavior
The process shows that ~12-13GB is still being used by UncompressBlockContentsForCompressionType according to jeprof results.
[app-profiling.122753.331.pdf](https://github.com/facebook/rocksdb/files/6221234/app-profiling.122753.331.pdf)

**Comment by pdillinger** [comment]
If your block cache (LRUCache, referenced by shared ColumnFamilyOptions) is still around, it will still have cached data in it. This is by design because a block cache can survive longer than a DB and cache data across DB close and re-open. Re-open if my assessment is wrong.

**Comment by lokeshj1703** [comment]
@pdillinger I do not have the option to reopen the issue. Can you please reopen it if you think the problem exists given the above information?

**Comment by lokeshj1703** [comment]
@pdillinger I investigated the issue further and it turns out the problem is at our end. Due to a bug we are not sharing the block cache. Thanks for all the help!
