### ISSUE TITLE
EstimatedNumKeys Counter Inaccurate

### ISSUE THREAD

**Issue by SherlockNoMad** [facebook/rocksdb#813]
When a new SSTable is generated during compaction, the # entry in the file is accumulated in the counter: VersionStorageInfo::accumulated_num_non_deletions_. 
However, when the stale files are deleted after compaction finished, the deleted entries are not decrease from counter.

**Comment by SherlockNoMad** [comment]
This is FYI. I will fix this.

**Comment by siying** [comment]
CC @yhchiang

**Comment by yhchiang** [comment]
Hey @SherlockNoMad.  Sorry for my late reply.  The stats collected there is to compute the historical average value size overtime and thus not deleting those counter when removing files is on purposed.

Or, are you building any logic based on this numbers where you need the counters reflect the current status instead of historical status?

**Comment by SherlockNoMad** [comment]
Hi @yhchiang.
DBImpl::GetProperty("rocksdb.estimate-num-keys", value) should return the estimated number of keys in a column family. 
In its actually implementation, it returns accumulated_num_non_deletions_ - accumulated_num_deletions_ as the estimated number of key. (see version_set.cc @GetEstimatedActiveKeys() )
This estimation is inaccurate as it's actually historical accumulated number of key written to the DB. 

We do need a counter to reflect the current number of keys in DB. 
Do you have any suggestion for this?

**Comment by yhchiang** [comment]
Hey @SherlockNoMad: I think that makes sense.  Are you interested in submitting a patch for this?  Or we can provide a patch for this.

**Comment by SherlockNoMad** [comment]
Hi @yhchiang, I already submitted the PR https://github.com/facebook/rocksdb/pull/815

**Comment by yhchiang** [comment]
LGTM.  Thanks for the fix!  I have merged the patch into master.

**Comment by SherlockNoMad** [comment]
@yhchiang @siying Thank you for reviewing this. :)
