### ISSUE TITLE
Parse blob file name error

### ISSUE THREAD

**Issue by caipengbo** [facebook/rocksdb#8157]
I saw in 
https://github.com/facebook/rocksdb/blob/b2c48a570f36a91715deca3a62a7def310d651c8/file/filename.cc#L91
we can create blob using the prefix of  `dbname + "/" + blob_dir`.

but in

https://github.com/facebook/rocksdb/blob/b2c48a570f36a91715deca3a62a7def310d651c8/file/filename.cc#L254

we parse the blob file lose sight of `blob_dir` 

https://github.com/facebook/rocksdb/blob/b2c48a570f36a91715deca3a62a7def310d651c8/file/filename.cc#L364

I think we need to consider the prefix of `blob_dir` like `ARCHIVAL_DIR `:

https://github.com/facebook/rocksdb/blob/b2c48a570f36a91715deca3a62a7def310d651c8/file/filename.cc#L334

**Comment by riversand963** [comment]
Thanks @caipengbo for reporting.
I think the code comment may be misleading. I checked a few call sites of `ParseFileNumber()`. It looks like the `fname` passed as argument are just file names not paths. The file names are obtained via `Env::GetChildren()` which (implicitly) returns names. The handling of archived logs is different, but I do not know why. The other part of the function does assume that only the name is passed with a possible leading '/'.

**Comment by caipengbo** [comment]
Thank you, I was really misled by that code comment. 
I review the call context of `ParseFileNumber `, it is a fact that the file names are always obtained via `Env::GetChildren()`.
