### ISSUE TITLE
Why do we set background threads twice in DBOptions::IncreaseParallelism

### ISSUE THREAD

**Issue by PiyushDatta** [facebook/rocksdb#8202]
Just a question, why do we call `SetBackgroundThreads` twice in `DBOptions::IncreaseParallelism`?

Code in `options/options.cc`:
```
DBOptions* DBOptions::IncreaseParallelism(int total_threads) {
  max_background_jobs = total_threads;
  env->SetBackgroundThreads(total_threads, Env::LOW);
  env->SetBackgroundThreads(1, Env::HIGH);
  return this;
}
```
My guess is that, if the scheduled job has a low priority, the thread pool will use `total_threads`, and if the job is high priority only use 1 thread? If so, why do we need 1 thread for high priority jobs?

Please label this as question

**Comment by akankshamahajan15** [comment]
You can refer https://github.com/facebook/rocksdb/wiki/Thread-Pool about why there are two sets of pool for threads  and https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide#tuning-flushes-and-compactions how to tune them for better performance.

**Comment by akankshamahajan15** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Closing this for now.

**Comment by PiyushDatta** [comment]
Thank you!
