### ISSUE TITLE
GC approach of BlobDB

### ISSUE THREAD

**Issue by leon-db** [facebook/rocksdb#8214]
i just want to know the exactly gc approach of blobdb. is there have any document? thanks

**Comment by leon-db** [comment]
when complete compaction, the OnCompactionCompleted will be called. the input link between blob will be remove, and add to the new output.  my question is when and what the blob db file will be shrinked.

**Comment by anand1976** [comment]
Cc @ltamasi

**Comment by ltamasi** [comment]
With the new BlobDB, blob files are immutable, so individual files never shrink. What happens is that the garbage collection logic relocates blobs and updates the pointers (blob indexes) to them; blob files are then deleted in one shot once no table file references them.

P.S. Please use other forums for questions; issues are meant to be used for bug reports/small improvements.
