### ISSUE TITLE
Add Java bindings for the new integrated BlobDB implementation

### ISSUE THREAD

**Issue by ltamasi** [facebook/rocksdb#8221]
It would be nice to expose the column family options of the new integrated BlobDB implementation (defined here: https://github.com/facebook/rocksdb/blob/master/include/rocksdb/advanced_options.h#L761-L823) through the Java API.

**Comment by ltamasi** [comment]
@adamretter  Do you think you could help with this one?

**Comment by adamretter** [comment]
Yes. I didn't think it should be too difficult. Can you addign the issue to me please?

**Comment by ltamasi** [comment]
Hi @adamretter ! Did you get a chance to work on this?
