### ISSUE TITLE
build fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [facebook/rocksdb#8224]
[jw@cn06 rocksdb]$ make VERBOSE=1 -j1 shared_lib
$DEBUG_LEVEL is 0
  CCLD     librocksdb.so.6.20.0
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZZNSt19_Sp_make_shared_tag5_S_tiEvE5__tag' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `std::_Sp_counted_ptr_inplace<rocksdb::(anonymous namespace)::ClockCache, std::allocator<rocksdb::(anonymous namespace)::ClockCache>, (__gnu_cxx::_Lock_policy)2>::_M_get_deleter(std::type_info const&)':
/usr/include/c++/10/bits/shared_ptr_base.h:586:(.text+0x78): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb12ShardedCacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::ShardedCache::~ShardedCache()':
/data/jw/rocksdb/./cache/sharded_cache.h:59:(.text+0x618): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb5CacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::Cache::~Cache()':
/data/jw/rocksdb/./include/rocksdb/cache.h:165:(.text+0x630): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb12ShardedCacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::ShardedCache::~ShardedCache()':
/data/jw/rocksdb/./cache/sharded_cache.h:59:(.text+0x744): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb5CacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::Cache::~Cache()':
/data/jw/rocksdb/./include/rocksdb/cache.h:165:(.text+0x758): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb12ShardedCacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::ShardedCache::~ShardedCache()':
/data/jw/rocksdb/./cache/sharded_cache.h:59:(.text+0x864): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb5CacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::Cache::~Cache()':
/data/jw/rocksdb/./include/rocksdb/cache.h:165:(.text+0x878): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN7rocksdb23kDefaultToAdaptiveMutexE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::NewClockCache(unsigned long, int, bool, rocksdb::CacheMetadataChargePolicy)':
/data/jw/rocksdb/cache/clock_cache.cc:717:(.text+0x1408): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb12ShardedCacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::ShardedCache::~ShardedCache()':
/data/jw/rocksdb/./cache/sharded_cache.h:59:(.text._ZN7rocksdb12ShardedCacheD2Ev[_ZN7rocksdb12ShardedCacheD5Ev]+0x4): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb5CacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::Cache::~Cache()':
/data/jw/rocksdb/./include/rocksdb/cache.h:165:(.text._ZN7rocksdb12ShardedCacheD2Ev[_ZN7rocksdb12ShardedCacheD5Ev]+0x24): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb12ShardedCacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::ShardedCache::~ShardedCache()':
/data/jw/rocksdb/./cache/sharded_cache.h:59:(.text._ZN7rocksdb12ShardedCacheD0Ev[_ZN7rocksdb12ShardedCacheD5Ev]+0x4): dangerous relocation: unsupported relocation
/usr/bin/ld: ./cache/clock_cache.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb5CacheE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./cache/clock_cache.o: in function `rocksdb::Cache::~Cache()':
/data/jw/rocksdb/./include/rocksdb/cache.h:165:(.text._ZN7rocksdb12ShardedCacheD0Ev[_ZN7rocksdb12ShardedCacheD5Ev]+0x24): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb28CompactionRangeDelAggregatorE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::CompactionRangeDelAggregator::CompactionRangeDelAggregator(rocksdb::InternalKeyComparator const*, std::vector<unsigned long, std::allocator<unsigned long> > const&)':
/data/jw/rocksdb/./db/range_del_aggregator.h:398:(.text+0x10ec): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN7rocksdb28CompactionRangeDelAggregator13AddTombstonesESt10unique_ptrINS_32FragmentedRangeTombstoneIteratorESt14default_deleteIS2_EEPKNS_11InternalKeyES8_' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::BuildTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::VersionSet*, rocksdb::ImmutableDBOptions const&, rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::FileOptions const&, rocksdb::TableCache*, rocksdb::InternalIteratorBase<rocksdb::Slice>*, std::vector<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> >, std::allocator<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> > > >, rocksdb::FileMetaData*, std::vector<rocksdb::BlobFileAddition, std::allocator<rocksdb::BlobFileAddition> >*, rocksdb::InternalKeyComparator const&, std::vector<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> >, std::allocator<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> > > > const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> >, unsigned long, rocksdb::SnapshotChecker*, rocksdb::CompressionType, rocksdb::CompressionOptions const&, bool, rocksdb::InternalStats*, rocksdb::TableFileCreationReason, rocksdb::IOStatus*, std::shared_ptr<rocksdb::IOTracer> const&, rocksdb::EventLogger*, int, rocksdb::Env::IOPriority, rocksdb::TableProperties*, int, unsigned long, unsigned long, rocksdb::Env::WriteLifeTimeHint, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, rocksdb::BlobFileCompletionCallback*)':
/data/jw/rocksdb/db/builder.cc:112:(.text+0x1150): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN7rocksdb31TablePropertiesCollectorFactory7Context20kUnknownColumnFamilyE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::TableProperties::TableProperties()':
/data/jw/rocksdb/./include/rocksdb/table_properties.h:153:(.text+0x1234): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZNK7rocksdb28CompactionRangeDelAggregator7IsEmptyEv' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `std::__uniq_ptr_impl<rocksdb::CompactionRangeDelAggregator, std::default_delete<rocksdb::CompactionRangeDelAggregator> >::_M_ptr() const':
/usr/include/c++/10/bits/unique_ptr.h:173:(.text+0x13a0): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN7rocksdb14FSWritableFile13SetIOPriorityENS_3Env10IOPriorityE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::BuildTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::VersionSet*, rocksdb::ImmutableDBOptions const&, rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::FileOptions const&, rocksdb::TableCache*, rocksdb::InternalIteratorBase<rocksdb::Slice>*, std::vector<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> >, std::allocator<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> > > >, rocksdb::FileMetaData*, std::vector<rocksdb::BlobFileAddition, std::allocator<rocksdb::BlobFileAddition> >*, rocksdb::InternalKeyComparator const&, std::vector<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> >, std::allocator<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> > > > const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> >, unsigned long, rocksdb::SnapshotChecker*, rocksdb::CompressionType, rocksdb::CompressionOptions const&, bool, rocksdb::InternalStats*, rocksdb::TableFileCreationReason, rocksdb::IOStatus*, std::shared_ptr<rocksdb::IOTracer> const&, rocksdb::EventLogger*, int, rocksdb::Env::IOPriority, rocksdb::TableProperties*, int, unsigned long, unsigned long, rocksdb::Env::WriteLifeTimeHint, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, rocksdb::BlobFileCompletionCallback*)':
/data/jw/rocksdb/db/builder.cc:153:(.text+0x1444): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN7rocksdb28FSWritableFileTracingWrapperD0Ev' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `std::default_delete<rocksdb::FSWritableFileTracingWrapper>::operator()(rocksdb::FSWritableFileTracingWrapper*) const':
/usr/include/c++/10/bits/unique_ptr.h:85:(.text+0x17d8): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb28FSWritableFileTracingWrapperE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::FSWritableFileTracingWrapper::~FSWritableFileTracingWrapper()':
/data/jw/rocksdb/./env/file_system_tracer.h:291:(.text+0x17f0): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN7rocksdb28CompactionRangeDelAggregatorD0Ev' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `std::default_delete<rocksdb::CompactionRangeDelAggregator>::operator()(rocksdb::CompactionRangeDelAggregator*) const':
/usr/include/c++/10/bits/unique_ptr.h:85:(.text+0x1bd8): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb18RangeDelAggregatorE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::RangeDelAggregator::~RangeDelAggregator()':
/data/jw/rocksdb/./db/range_del_aggregator.h:277:(.text+0x1c78): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZNK7rocksdb12TableBuilder7IsEmptyEv' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::BuildTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rocksdb::VersionSet*, rocksdb::ImmutableDBOptions const&, rocksdb::ImmutableCFOptions const&, rocksdb::MutableCFOptions const&, rocksdb::FileOptions const&, rocksdb::TableCache*, rocksdb::InternalIteratorBase<rocksdb::Slice>*, std::vector<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> >, std::allocator<std::unique_ptr<rocksdb::FragmentedRangeTombstoneIterator, std::default_delete<rocksdb::FragmentedRangeTombstoneIterator> > > >, rocksdb::FileMetaData*, std::vector<rocksdb::BlobFileAddition, std::allocator<rocksdb::BlobFileAddition> >*, rocksdb::InternalKeyComparator const&, std::vector<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> >, std::allocator<std::unique_ptr<rocksdb::IntTblPropCollectorFactory, std::default_delete<rocksdb::IntTblPropCollectorFactory> > > > const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<unsigned long, std::allocator<unsigned long> >, unsigned long, rocksdb::SnapshotChecker*, rocksdb::CompressionType, rocksdb::CompressionOptions const&, bool, rocksdb::InternalStats*, rocksdb::TableFileCreationReason, rocksdb::IOStatus*, std::shared_ptr<rocksdb::IOTracer> const&, rocksdb::EventLogger*, int, rocksdb::Env::IOPriority, rocksdb::TableProperties*, int, unsigned long, unsigned long, rocksdb::Env::WriteLifeTimeHint, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, rocksdb::BlobFileCompletionCallback*)':
/data/jw/rocksdb/db/builder.cc:235:(.text+0x1dc0): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZNK7rocksdb12TableBuilder11NeedCompactEv' which may bind externally can not be used when making a shared object; recompile with -fPIC
/data/jw/rocksdb/db/builder.cc:248:(.text+0x1fc8): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZN7rocksdb18SystemClockWrapper9NowMicrosEv' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::StopWatch::StopWatch(rocksdb::SystemClock*, rocksdb::Statistics*, unsigned int, unsigned long*, bool, bool)':
/data/jw/rocksdb/./util/stop_watch.h:33:(.text+0x28cc): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb28CompactionRangeDelAggregatorE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::CompactionRangeDelAggregator::~CompactionRangeDelAggregator()':
/data/jw/rocksdb/./db/range_del_aggregator.h:399:(.text._ZN7rocksdb28CompactionRangeDelAggregatorD0Ev[_ZN7rocksdb28CompactionRangeDelAggregatorD5Ev]+0x4): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN7rocksdb18RangeDelAggregatorE' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `rocksdb::RangeDelAggregator::~RangeDelAggregator()':
/data/jw/rocksdb/./db/range_del_aggregator.h:277:(.text._ZN7rocksdb28CompactionRangeDelAggregatorD0Ev[_ZN7rocksdb28CompactionRangeDelAggregatorD5Ev]+0xa0): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZNSt6vectorIN7rocksdb5SliceESaIS1_EED1Ev' which may bind externally can not be used when making a shared object; recompile with -fPIC
./db/builder.o: in function `_GLOBAL__sub_I__ZN7rocksdb15NewTableBuilderERKNS_18ImmutableCFOptionsERKNS_16MutableCFOptionsERKNS_21InternalKeyComparatorEPKSt6vectorISt10unique_ptrINS_26IntTblPropCollectorFactoryESt14default_deleteISB_EESaISE_EEjRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_18WritableFileWriterENS_15CompressionTypeERKNS_18CompressionOptionsEibmmmmSQ_SQ_':
/data/jw/rocksdb/./db/merge_context.h:15:(.text.startup+0xb8): dangerous relocation: unsupported relocation
/usr/bin/ld: ./db/builder.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev@@GLIBCXX_3.4.21' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: ./db/builder.o(.text.startup+0xf4): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev@@GLIBCXX_3.4.21'
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:702: librocksdb.so.6.20.0] Error 1
[jw@cn06 rocksdb]$

**Comment by mrambacher** [comment]
At first glance, this appears that some objects were compiled statically
and others for dynamic.  Can you do a make clean and re-run the command?
If it still fails, can you please also post some of the compilation steps
-- using VERBOSE=1 -- what is shown is just the linker errors.

/ Mark

**Comment by LutzWeischerFujitsu** [comment]
Solved.
