### ISSUE TITLE
only read queries but creates new sstables...

### ISSUE THREAD

**Issue by jonggyup** [facebook/rocksdb#8252]
Is it normal that Rocksdb perform sth like compaction when only read requests occurs?
While running YCSB workloadc (read 100%) with rocksdb, new sst files are generated even when there is no write request. 
Using blktrace, I checked bulk writes were issued by low level threads of rocksdb.
Do Read queries also contribute to a reconstruction of SSTables?
If then, is there a way to prevent this?

P.S.
I set O_DIRECT for both read and writes, and the record size is 128kb.

**Comment by ajkr** [comment]
> Is it normal that Rocksdb perform sth like compaction when only read requests occurs?

Yes, if the initial state of the DB when it is opened already requires compaction.

A few common ways to avoid this are:

- Wait for pending compactions to finish when populating the DB
- Issue a full compaction after populating the DB
- Open the DB in read-only mode for the read-only workload

> Do Read queries also contribute to a reconstruction of SSTables?

No.
