### ISSUE TITLE
garbage_blob_count_ always 0

### ISSUE THREAD

**Issue by caipengbo** [facebook/rocksdb#8294]
The new implementation of Integrated BlobDB use two variables `garbage_blob_count_` and `garbage_blob_bytes_` in the `BlobFileMetadata` to record the garbage infos about BLOB files. 

I traced the path of `BlobFileMetadata`, found that `garbage_blob_count_` and `garbage_blob_bytes_` are only set in the `BlobFileMetadata::Create()`. I continue tracing and found that the garbage infos is only derived from `BlobFileMetaDatadelta`, and the garbage infos of BlobFileMetaDatadelta is derived from `VersionEdit`. So I traced the path of `VersionEdit::AddBlobFileGarbage()` and found that VersionEdit adds garbage infos in two places:
1. `VersionSet::WriteCurrentStateToManifest`: Call `VersionStorageInfo::GetBlobFiles()` to obtain BlobFileMetaData then read  garbage infos from `BlobFileMetaData`. The path of garbage infos: BlobFileMetaData -> VersionEdit -> BlobFileMetaData caused a loop call. **There is no increase in garbage anywhere**.
2. `VersionEdit::DecodeFrom`: Reads the record from the MANIFEST file

Based on the above analysis, I think there is a lack of statistics about garbage in the process of BLOB GC.

**Also, isn't the Blob Garbage of RocksDB useless at the moment? Will garbage information be used to optimize the GC policy in the future?**

**Comment by ltamasi** [comment]
Correct, the garbage count/bytes related logic you mentioned is dormant as of now, and yes, it will be used to improve the GC logic.
