### ISSUE TITLE
Lost blob files when Version changed in new Integrated BlobDB

### ISSUE THREAD

**Issue by caipengbo** [facebook/rocksdb#8304]
`VersionBuilder::Rep::AddBlobFileIfNeeded()` will add the blob file specified by meta to *vstorage if it is determined to contain valid data (blobs). It use `linked_ssts_` in `BlobFileMetaData` determine whether the blob is associated with an SST. I tracked the path of `linked_ssts_` in `BlobFileMetaData`, found that `VersionBuilder::Rep::Apply()` call `ApplyFileAddition` and `ApplyFileDeletion`:  When delete or add an SST file , the `linked_ssts_` information will be recorded in the `BlobFileMetaDataDelta`. 
But only the oldest blob file this SST file refers to will record `linked_ssts_` information, See: https://github.com/facebook/rocksdb/blob/feb06e83b2fbe5fe0bb63e18f1d3bbdbdb1a73e0/db/version_builder.cc#L643

If a SST file refers to multiple blob files, and those blob files are referenced only by that SST file. **Only the smallest blob file will have `linked_ssts_`  information and other blob files will not**. In `VersionBuilder::Rep::AddBlobFileIfNeeded()` will skip those blob files, and don't add it into `*vstorage`.

**Comment by ltamasi** [comment]
This is by design. Linked SSTs for a given blob file are _defined_ as the set of SSTs for which the blob file in question is the oldest referenced blob file.

P.S. Did you encounter any actual bug or is this just a question about the logic? If the former, please provide details. If the latter, please use other channels; issues are for bug reports/minor enhancements and we're trying to keep the issues list clean. Thanks!

**Comment by caipengbo** [comment]
I think there are potential bug with this design. 

If a given blob file is not the oldest referenced blob file of any SST, this blob file will not have `linked_ssts`. So this blob file will not been added into `*vstorage`.

**Comment by ltamasi** [comment]
I don't think there is an issue here; just because a blob file doesn't have any linked SSTs doesn't mean it will be ignored/not added to the new `Version`. In particular, the logic related to the `found_first_non_empty` flag would prevent what you describe from happening.
