### ISSUE TITLE
RocksDB not work with network filesystem paths on Windows (like \\hostname\folder\...)

### ISSUE THREAD

**Issue by prigluchenie** [facebook/rocksdb#8345]
Problem occurs near
https://github.com/facebook/rocksdb/blob/1c88f66ff89c8746e9451e58c8806ef9868c054f/file/filename.cc#L467
during normalizing front double slash.

RocksDB worked with network filesystem paths in the version 6.6.4 (for example).

**Comment by riversand963** [comment]
Thanks for reporting. Would you like to contribute a fix?

**Comment by igorrogov** [comment]
Yes, we might. One of our developers will be looking into it soon. I'll ask him to send a patch/PR.

**Comment by bbkot** [comment]
created pull request , with solution proposed solution
here you are the link

https://github.com/facebook/rocksdb/pull/9384
