### ISSUE TITLE
You have to open all column families

### ISSUE THREAD

**Issue by hiqsociety** [facebook/rocksdb#8359]
Why do you need to open all column families when all i need to do / work on is the only 1 i want to use?

Any ways to work around?

**Comment by hiqsociety** [comment]
how do i achieve OpenDBColumnFamily without inserting all CFs?

**Comment by akankshamahajan15** [comment]
Since ColumnFamilies share WAL so thats why we need to open DB with all ColumnFamilies to maintain the state. https://github.com/facebook/rocksdb/wiki/Column-Families#implementation.  In case of OpenForReadOnly you can provide subset of ColumnFamilies.

Closing this for now. 

> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
