### ISSUE TITLE
Options::disable_seek_compaction is true or false now?

### ISSUE THREAD

**Issue by followheart** [facebook/rocksdb#836]
i learned disable_seek_compaction from wiki，but it is deprecated now，i want to know how can i turn this feature on ? or if max_open_files is large, default value is true?

content in wiki:
Options::disable_seek_compaction - Disable compaction triggered by seek

**Comment by siying** [comment]
The "seek compaction" feature is deprecated for impacting performance of reads. So there is no such feature now.
