### ISSUE TITLE
USERS.md addition

### ISSUE THREAD

**Issue by cfferry** [facebook/rocksdb#8372]
Dear Friends,

I have been working on a small database (Beryl) that utilizes RocksDB. I have been having a great time using RocksDB and pretend to maintain this project in the foreseeable future. Here's a basic [documentation](http://docs.beryl.dev/) and [here is the official repo](https://github.com/beryldb/beryldb). There is also a [client.](https://github.com/beryldb/beryldb-cli), which can be used for testing purposes. 

At this time, I'm currently working on a Python and PHP client, and these should be released in the upcoming weeks. It'd be great to have this project added to USERS.md as RocksDB is intensively used in all [commands](https://docs.beryl.dev/using/commands/) that have been implemented.

Would certainly love to get some feedbacks.

Have a great week.

**Comment by jay-zhuang** [comment]
Would you please send a PR for that, thanks.
