### ISSUE TITLE
gen core dump when run test case in parallels 

### ISSUE THREAD

**Issue by leon-db** [facebook/rocksdb#8381]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
all test case successfully
### Actual behavior
core dump
### Steps to reproduce the behavior
 make J=8 check -j32 DEBUG_LEVEL=2 DISABLE_WARNING_AS_ERROR=1

**Comment by akankshamahajan15** [comment]
@leon-db  Can you share the core dump and the unit test which is failing.

**Comment by leon-db** [comment]
I try the test in many docker  and all coredump.   I can't share the env, sorry
Q：the unit test which is failing
A:   All the test case core dump.   I trace some of this unit case with gdb
![image](https://user-images.githubusercontent.com/7334994/121624549-5259db80-caa4-11eb-8a94-fb8e8ffa8f35.png)
the reason cause coredump just because of the fwrite action unexpected.

**Comment by leon-db** [comment]
I found the root reason is when run test case it will check if the /dev/shm set the sticky bit and if the /dev/shm set sticky bit all test case tmpdir will create in these dirs. and in my env the /dev/shm is limit to 64MB,  so the cause the coredump
