### ISSUE TITLE
RocksJava - Opening database fails on Windows with non-english characters/locale

### ISSUE THREAD

**Issue by DaMatrix** [facebook/rocksdb#8466]
### Expected behavior

`DB#open` will work properly, regardless of what characters the path name contains and/or the system locale.

### Actual behavior

In some cases, it fails with an exception. See https://github.com/PorkStudios/FarPlaneTwo/issues/32 for an example of a case where it failed with a garbled error message when given an entirely ASCII path, as well as a few people who are reporting that it works properly as long as the path is entirely ASCII.

I'm reasonably certain this issue is specific to Windows (as I was unable to reproduce it locally when using path names consisting of totally random UTF-8 characters), but I don't have enough experience with character encodings/locales/whatever to know whether or not these are all different problems caused by the same underlying issue, or two separate things. I can't confirm this, though, because I don't have access to any Windows machines to test it out on.

The errors in the linked issue all occurred on `rocksdbjni 6.13.3`.

Possibly related to #3408?

**Comment by adamretter** [comment]
@DaMatrix We have been releasing the Windows builds with UTF-8 support enabled by default for several iterations. Can you try updating to a more recent version of RocksDB please?

**Comment by DaMatrix** [comment]
Yep, sure! Sorry, I hadn't realized just how old 6.13.3 is. I'll let you know as soon as I have more information.

**Comment by jay-zhuang** [comment]
Closing it now. @DaMatrix please feel free to re-open if it still fails.

**Comment by DaMatrix** [comment]
Fine by me, none of the people who originally encountered the issue got back to me and nobody else has reported it since I upgraded to a more recent rocksdb version, so I'd assume it's been fixed. Will come back here if anyone else reports it.
