### ISSUE TITLE
java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni4577185059083269782.so

### ISSUE THREAD

**Issue by Cicizz** [facebook/rocksdb#8484]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
env:
  Rocksdb java 6.20.3 + spring boot
  linux centos 7
how to solve this problem

**Comment by adamretter** [comment]
How are you initialising RocksDB? Also is it possible that the .so file was later removed from /tmp by a reboot or automated process
