### ISSUE TITLE
db_iter.cc:316 assert fail

### ISSUE THREAD

**Issue by rockeet** [facebook/rocksdb#8488]
### Expected behavior
kill -9 should not make db broken.

### Actual behavior
db/db_iter.cc:316: bool rocksdb::DBIter::FindNextUserEntryInternal(bool, const rocksdb::Slice*): Assertion `!skipping_saved_key || CompareKeyForSkip(ikey_.user_key, saved_key_.GetUserKey()) > 0' failed.

### Steps to reproduce the behavior
repeat **kill -9 while writing db, then restart process**, after serveral times, the assert fail will be hit.

We tried to delete this assert, the db started successfully.

**Comment by siying** [comment]
Sounds like bug somewhere. Which optins.wal_recovery_mode value do you use? Do you set options. Do you set options.avoid_flush_during_recovery? 

To debug, can you try to preserve historic WAL files (e.g. by setting options.WAL_ttl_seconds and WAL_size_limit_MB) and when it reproduces, examine whether we've ever got two WAL entries with the same sequence number?

**Comment by rockeet** [comment]
we did not set `avoid_flush_during_recovery` nor set `WAL_ttl_seconds` and `WAL_size_limit_MB`

**Comment by ehds** [comment]
Is there any updates to this issue？

**Comment by ajkr** [comment]
> Is there any updates to this issue？

Did you hit this issue? If so can you provide details about the workload and the RocksDB version so we can try to repro it?

**Comment by rockeet** [comment]
We have not investigate this issue in recent 1 year.
