### ISSUE TITLE
rocksdb suppot multi-stream 

### ISSUE THREAD

**Issue by springeee** [facebook/rocksdb#8496]
Hi,  all:

If rocksdb support multi-stream ？ if yes, how to set it ?

Thanks,
Regards
Spring

**Comment by jay-zhuang** [comment]
Sorry, what do you multi-stream?

**Comment by springeee** [comment]
> Sorry, what do you multi-stream?

Multi-stream is a technology that allows the SSD to receive host hints where “data streams” emerge to make better placement of data.

**Comment by ajkr** [comment]
We provide such hints here. https://github.com/facebook/rocksdb/blob/60e5af83c14f48e302a29591deab6d06bf59d30f/env/io_posix.cc#L1331. I think it's enabled by default to give different hints for WAL vs. L0 file vs. others. We have not used it much so would be interested in your experience on if it's working as expected.

**Comment by siying** [comment]
> We provide such hints here.
> 
> https://github.com/facebook/rocksdb/blob/60e5af83c14f48e302a29591deab6d06bf59d30f/env/io_posix.cc#L1331
> 
> . I think it's enabled by default to give different hints for WAL vs. L0 file vs. others. We have not looked into it recently (I guess that code is a no-op for most hardware?) so would be interested in your experience on if it's working as expected.

Ah, interesting. Sorry for providing the wrong answer previously.

**Comment by ajkr** [comment]
No problem, you were on parental leave during that project so shouldn't have known :).

**Comment by springeee** [comment]
> We provide such hints here.
> 
> https://github.com/facebook/rocksdb/blob/60e5af83c14f48e302a29591deab6d06bf59d30f/env/io_posix.cc#L1331
> 
> . I think it's enabled by default to give different hints for WAL vs. L0 file vs. others. We have not looked into it recently (I guess that code is a no-op for most hardware?) so would be interested in your experience on if it's working as expected.

I have one samsung PM9A3 nvme ssd which support multi-stream, so I want to do some test use PM9A3 whith rocksdb， but use the default parameters,  use PM9A3 have the same performance with  other nvme ssd(which is not support multi-stream) . so I want to know how to the multi-stream feature?
Thanks.

**Comment by ajkr** [comment]
Do you have a way to debug whether it is already enabled? I thought it is enabled by default but please let us know if you find it is not. Perhaps your workload/config has a different bottleneck, or the better endurance from multi-stream is not easily visible.

If there's a way to measure HW write-amp, you can try on your multi-stream NVMe SSD with and without that `fcntl()` commented. I recall an experiment like that proved to us there is an improvement.

**Comment by springeee** [comment]
> Do you have a way to debug whether it is already enabled? I thought it is enabled by default but please let us know if you find it is not. Perhaps your workload/config has a different bottleneck, or the better endurance from multi-stream is not easily visible.
> 
> If there's a way to measure HW write-amp, you can try on your multi-stream NVMe SSD with and without that `fcntl()` commented. I recall an experiment like that proved to us there is an improvement.
“Do you have a way to debug whether it is already enabled? ” 
I don't know if already enabled.

"Perhaps your workload/config has a different bottleneck"
I have used db_bench and YCSB test rocksdb, db_bench parameters "NUM_KEYS=900000000 NUM_THREADS=32 CACHE_SIZE=6442450944 DURATION=5400" , db, wal, tmp and output on the same disk.
about db_bench or YCSB test, do you have any advices?
Thanks.
