### ISSUE TITLE
some questions about write_thread in dbimpl

### ISSUE THREAD

**Issue by followheart** [facebook/rocksdb#851]
hi, when i read rocksdb's sourcecode, i have a question about write_thread,
code segment in writeimpl,

  if (w.done) {
    // write was done by someone else, no need to grab mutex
    RecordTick(stats_, WRITE_DONE_BY_OTHER);
    return w.status;
  }

writethread class keep all writecontext in dequeue by link_older and link_newer, 
i think this situation can only happen in multi write threads , so my question is if there is only one write thread, this code will not executed any more (such as one write thread and N read threads)? is this right?

one write thread or several write threads, which is better ? can you give some suggestions~~

**Comment by siying** [comment]
You are right. If you only have at most one thread writing to DB at one time, this code path will not be executed.
