### ISSUE TITLE
Is TablePropertiesCollector::NeedCompact still experimental?

### ISSUE THREAD

**Issue by hicqu** [facebook/rocksdb#8512]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Hi, I have noticed this feature is introduced in the commit `6df589b446b3bd4b468a36a07b959d4d98a75fc7`, but marked as *experimental*.

Thanks to you we can benifit from the feature but we worry about whether there are any unresolved significant problems. I have searched it in issues but nothing is found.

So if I lose sight of some issues, could you help me to point out them? Thanks!

**Comment by ajkr** [comment]
It's used in production now so not experimental. I saw mention of experimental in that commit but not in the current code base. Please let us know if there are still mentions of experimental so we can clean them up.
