### ISSUE TITLE
Does rocksdb support wide column scenario?

### ISSUE THREAD

**Issue by mdianjun** [facebook/rocksdb#8521]
We want to integrate rocksdb with our database, to provide the wide table ability. Although hbase is an alternative, but it's necessary to transfer data between our database and hbase.
Does rocksdb support wide column store scenario like hbase，for example 1 billion columns?

**Comment by jay-zhuang** [comment]
RocksDB currently doesn't natively support columns, but you can schematize and build columns based on RocksDB key-value store. For example, DB like MyRocks, Rocksandra based on rocksdb, but do support columns.
