### ISSUE TITLE
Crash on Windows calling rocksdb_open on version 6.20.3 and newer

### ISSUE THREAD

**Issue by theolivenbaum** [facebook/rocksdb#8522]
### Expected behavior

RocksDB should not crash on Windows. 

### Actual behavior

RocksDB crashes with System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception. 

### Steps to reproduce the behavior

This code reproduces the issue on some machines: https://github.com/theolivenbaum/rdb-test

### Notes

We're observing some crashes when using RocksDB on Windows. It only happens for some users (i.e. not on my dev machine). I've boiled it down to the call to DB.Open on our code calling the native code.

`````
.Unhandled exception. System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at RocksDbSharp.Native.rocksdb_open(IntPtr options, String name)
   at RocksDbSharp.RocksDb.Open(OptionsHandle options, String path)
   at rdb_test.RocksDbStorage..ctor(String path, String journalPath) in RocksDbStorage.cs:line 16
   at rdb_test.Program.Main(String[] args) in Program.cs:line 21
`````

I did a bit of [testing](https://github.com/curiosity-ai/rocksdb-sharp/issues/5#issuecomment-879109356) with older versions of our [NuGet package](https://www.nuget.org/packages/RocksDb), and it seems like this issue was introduced between version 6.17.3 and 6.20.3:

[6.11.4.12240](https://www.nuget.org/packages/RocksDB/6.11.4.12240) works
[6.14.5.13874](https://www.nuget.org/packages/RocksDB/6.14.5.13874) works
[6.15.5.15759](https://www.nuget.org/packages/RocksDB/6.15.5.15759) works
[6.17.3.16253](https://www.nuget.org/packages/RocksDB/6.17.3.16253) works
[6.20.3.19177](https://www.nuget.org/packages/RocksDB/6.20.3.19177) doesn't work

Any suggestions how I can get started debugging the issue?

**Comment by adamretter** [comment]
@theolivenbaum your stack trace is for the `RocksDbSharp` code. So unfortunately that doesn't tell us anything about RocksDB. We would need to know the stack for RocksDB

**Comment by theolivenbaum** [comment]
Will try to get one asap!

**Comment by sondreb** [comment]
Using your "rdb-test" repo, I can verify that it runs fine without crashes (at least for a while, I have not run it very long), but there is an obvious resource leak that increases the time it takes.

Library: [RocksDB](https://www.nuget.org/packages/RocksDB/) Version 6.22.1.19445

![image](https://user-images.githubusercontent.com/309938/125518106-304ff12e-c087-40ba-bb43-4de6e508cd95.png)

I changed the referenced library to a fork I made a while back:

Library: [Blockcore.RocksDB](https://www.nuget.org/packages/Blockcore.RocksDB/) Version 6.20.3.9

![image](https://user-images.githubusercontent.com/309938/125518193-8090eb29-7908-46f8-94a2-5828b98a50c8.png)

I noticed that you had unlisted the 6.22 and 6.20 packages, so I tried with the latest published:

Library: RocksDB Version 6.19.3.19494

![image](https://user-images.githubusercontent.com/309938/125518501-58755e58-a5d7-491a-b1ed-7cd3c49b9c59.png)

I have a very good M.2 SSD disk, and if the issue is related to open and close of DB, it might not easily be reproduced on my drive since it's so fast. With slower maybe the issue is locks on the file system?

In my fork, I have taken a few PRs from warrenfalk/rocksdb-sharp and your curiosity-ai/rocksdb-sharp repo. I think some of those changes might be a fix for the issue seen above with increased times taken to run the tests.

**Comment by theolivenbaum** [comment]
Hi, actually the while (true) loop is unnecessary for the crash, when it
happens, it happens on the first call to DB.Open... I'll try to get a
proper dump tomorrow. And yes, this is one of those bugs that doesn't
happen on my machine either 😓
Interesting with the leak. I was also wondering as I was reviewing the
changes in the API if I should add a way to call the StopBackgroundTasks
method (forgot the exact name now) from RocksDb.

**Comment by theolivenbaum** [comment]
Also regarding the packages. I unlisted them but they should still be
available if you set them on the project. NuGet never forgets

**Comment by theolivenbaum** [comment]
Not sure if this helps: `Unhandled exception at 0x00007FFEE272A4A7 (coreclr.dll) in RocksDBExample.exe_210823_230219.dmp: 0xC000001D: Illegal Instruction.` (you can find the full dump [here](https://curiosityai-my.sharepoint.com/:u:/g/personal/rafael_curiosity_ai/EREbqIb0ok5Hnt7414TVIEUB1wTNzqItcOMkDw7qfIhu6g?e=4ecmuR))

Seems like it could be related to #2585.

We already build with the PORTABLE flag (see [here](https://github.com/curiosity-ai/rocksdb-sharp/blob/4134ea5afa2f2535f858ed5d8fdc902335e53819/build-native/build-rocksdb.sh#L95)), could it be that something is ignoring the PORTABLE flag? 

Dumping the instructions used by the DLL does show AVX opcodes - but not sure if this is normal or not...

The strange thing is that the error happens on a machine that has AVX2.

**Comment by theolivenbaum** [comment]
Seems like this also happens without the csharp bindings (see https://github.com/curiosity-ai/rocksdb-sharp/issues/5#issuecomment-999586255). Any ideas how we can investigate this further?

**Comment by AllegraMcdonnell123** [comment]
anything new with this bug?

**Comment by adamretter** [comment]
Is it possible to re-test this with a newer version of RocksDB?

**Comment by theolivenbaum** [comment]
Still seeing the same issue, it seems like the rocksdb portable build is not really portable on Windows. Happens on machines that don't have AVX2

**Comment by adamretter** [comment]
@theolivenbaum Can you send a PR to the CMakeLists.txt to adjust it?

**Comment by theolivenbaum** [comment]
Hi @adamretter I would love to - but I'm not familiar enough with the rocksdb source code to be able to identify what's causing this dependency on AVX2. If there is no bandwidth on your side, I could try to figure this out. but would appreciate any tips!

**Comment by pdillinger** [comment]
> We already build with the PORTABLE flag (see [here](https://github.com/curiosity-ai/rocksdb-sharp/blob/4134ea5afa2f2535f858ed5d8fdc902335e53819/build-native/build-rocksdb.sh#L95)), could it be that something new is missing the check for the PORTABLE flag?

I'm not a cmake expert but I believe that `-DHAVE_AVX2=OFF` is going to enable the `#ifdef HAVE_AVX2` in the source code

**Comment by mrambacher** [comment]
> > We already build with the PORTABLE flag (see [here](https://github.com/curiosity-ai/rocksdb-sharp/blob/4134ea5afa2f2535f858ed5d8fdc902335e53819/build-native/build-rocksdb.sh#L95)), could it be that something new is missing the check for the PORTABLE flag?
> 
> I'm not a cmake expert but I believe that `-DHAVE_AVX2=OFF` is going to enable the `#ifdef HAVE_AVX2` in the source code

I agree with Peter.  I think the "HAVE_AVX=OFF and HAVE_AVX2=OFF are wrong.  The are not commands to the cmake system and, if they actually managed to set something in the C++ code, it would be enabled.

If you are attempting to make sure the AVX is OFF even with PORTABLE=ON, you need to use -DFORCE_AVX(2)=OFF

**Comment by theolivenbaum** [comment]
@ajkr this is unfortunately not closed yet.
I've tested the change proposed but still crashing on CPUs without AVX2.

I've ordered now an older laptop to see how to test this directly from the rocksdb source code, but any guidance would be appreciated!

**Comment by theolivenbaum** [comment]
I'm wondering if we're missing setting flags for one of the imports is causing this issue. @fmarkor reported that [disabling compression](https://github.com/curiosity-ai/rocksdb-sharp/issues/5#issuecomment-1087785763) fixes the problem on his case - obviously not the ideal solution, but interesting finding... I'm still investigating on our case if this also fixes the crash.

From a quick check on [snappy](https://github.com/google/snappy/blob/main/snappy.cc), it seems like they auto-detect CPU capabilities based on [certain flags](https://grep.app/search?q=SNAPPY_HAVE_) - @ajkr any ideas if this is being set by rocksdb on portable builds?

**Comment by theolivenbaum** [comment]
@ajkr we can finally close the issue. The problem was with the vcpkg imports on the windows build script, that didn't disable avx2.
