### ISSUE TITLE
Clang compilation failure in customizable_test

### ISSUE THREAD

**Issue by isaac-io** [facebook/rocksdb#8525]
Compilation of `customizable_test` fails under clang due to the use of `offsetof()` on a non-standard-layout type.

```
options/customizable_test.cc:230:7: error: offset of on non-standard-layout type 'struct SimpleOptions' [-Werror,-Winvalid-offsetof]
     {offsetof(struct SimpleOptions, b), OptionType::kBoolean,
      ^                              ~
/usr/lib/clang/12.0.1/include/stddef.h:104:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~
options/customizable_test.cc:233:20: error: offset of on non-standard-layout type 'struct SimpleOptions' [-Werror,-Winvalid-offsetof]
                   offsetof(struct SimpleOptions, cu),
                   ^                              ~~
/usr/lib/clang/12.0.1/include/stddef.h:104:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~
options/customizable_test.cc:236:20: error: offset of on non-standard-layout type 'struct SimpleOptions' [-Werror,-Winvalid-offsetof]
                   offsetof(struct SimpleOptions, cs),
                   ^                              ~~
/usr/lib/clang/12.0.1/include/stddef.h:104:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~
options/customizable_test.cc:239:21: error: offset of on non-standard-layout type 'struct SimpleOptions' [-Werror,-Winvalid-offsetof]
                    offsetof(struct SimpleOptions, cp),
                    ^                              ~~
/usr/lib/clang/12.0.1/include/stddef.h:104:24: note: expanded from macro 'offsetof'
#define offsetof(t, d) __builtin_offsetof(t, d)
                       ^                     ~
4 errors generated.
```

### Expected behavior

Compilation should succeed.

### Actual behavior

Compilation fails.

### Steps to reproduce the behavior

Compile with `CC=clang CXX=clang++ make customizable_test`.

**Comment by mrambacher** [comment]
Which version of clang are you using?  Which platform?  I built using clang-10 without an issue:

CC=clang CXX=clang++ make customizable_test
$DEBUG_LEVEL is 1
Makefile:176: Warning: Compiling in debug mode. Don't use the resulting binary in production
microbench/ribbon_bench.cc:8:10: fatal error: 'benchmark/benchmark.h' file not found
#include <benchmark/benchmark.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
  CC       options/customizable_test.o
  CCLD     customizable_test
mark@ip-172-31-15-121:~/rocksdb$ clang++ --version
clang version 10.0.0-4ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

**Comment by helius-isaac** [comment]
Sorry for not providing this information upfront. I'm using Clang 12 on arch:

```
$ uname -srv
Linux 5.12.15-arch1-1 #1 SMP PREEMPT Wed, 07 Jul 2021 23:35:29 +0000
$ clang --version
clang version 12.0.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by isaac-io** [comment]
Just a quick update:

This is also broken with Clang 13, but not with Clang 14, so likely just a compiler bug that was fixed. Closing this issue for now.
