### ISSUE TITLE
Prefix Seek doesn't always work with PlainTable format after flushing DB

### ISSUE THREAD

**Issue by angeladietz** [facebook/rocksdb#8529]
Hello RocksDB team,

I've encountered some strange behaviour when using prefix seeking with PlainTable format. 

### Steps to reproduce:
1. Open a RocksDB instance with PlainTable format and specify a capped prefix extractor
2. Put a key/value pair into the db
3. Flush the db
4. Try to do a prefix seek with a prefix of the key which is _shorter than the specified capped prefix extractor_

### Expected behaviour:
The iterator should find the key/value pair.

### Actual behaviour:
The iterator doesn't find the key/value pair and is immediately invalid.

I have found that I get the expected behaviour when I either:
1. Don't flush the db, OR
2. Use a prefix at least as long as the capped prefix extractor

### Sample code to reproduce
```
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;
import org.rocksdb.FlushOptions;
import org.rocksdb.Options;
import org.rocksdb.PlainTableConfig;
import org.rocksdb.ReadOptions;
import org.rocksdb.RocksDB;
import org.rocksdb.RocksDBException;
import org.rocksdb.RocksIterator;
import org.testng.Assert;
import org.testng.annotations.Test;


public class RocksDBTest {
  private static final String dbPath = "./" + getDbPath("rocksdb-data") + "/";

  @Test
  public void testRocksDBIterator() {
    try (final Options options = getStoreOptions()) {
      byte[] prefix = {1, 2, 3, 4, 5};
      byte[] key = {1, 2, 3, 4, 5, 6, 7, 8, 9, 0};
      byte[] value = {0, 0, 0, 0, 0, 0, 0, 0};
      try (final RocksDB rocksDB = RocksDB.open(options, dbPath)) {
        rocksDB.put(key, value);

        rocksDB.flush(new FlushOptions().setWaitForFlush(true)); // comment out this line, test passes

        List<byte[]> found = new ArrayList<>();
        try (RocksIterator iter = rocksDB.newIterator(new ReadOptions())){
          for (iter.seek(prefix); iter.isValid(); iter.next()) {
            found.add(iter.key());
          }
        }
        // Should find the key which starts with the prefix
        Assert.assertEquals(found.size(), 1);
      }
    } catch (RocksDBException e) {
      Assert.fail(e.getMessage());
    } finally {
      removeDirWithTwoLayers(dbPath);
    }
  }

  private static String getDbPath(String name){
    Random rand = new Random();
    return name + "-" + System.nanoTime() + "-" + rand.nextInt(Integer.MAX_VALUE) ;
  }

  private Options getStoreOptions() {
    Options options = new Options();

    options.setCreateIfMissing(true);

    PlainTableConfig tableConfig = new PlainTableConfig();
    tableConfig.setStoreIndexInFile(true);
    tableConfig.setHugePageTlbSize(0);
    tableConfig.setBloomBitsPerKey(10);
    options.setTableFormatConfig(tableConfig);
    options.setAllowMmapReads(true);
    options.useCappedPrefixExtractor(6); // Or, reduce the length to 5, test passes

    return options;
  }

  private void removeDirWithTwoLayers(String fullPath) {
    File dir = new File(fullPath);
    if (dir.exists()) {
      // Remove the files inside first
      Arrays.stream(dir.list()).forEach(file -> {
        if (!(new File(fullPath, file).delete())) {
          System.out.println("Failed to remove file: " + file + " in dir: " + fullPath);
        }
      });
      // Remove file directory
      if (!dir.delete()) {
        System.out.println("Failed to remove dir: " + fullPath);
      }
    }
  }
}
```

I would like to use prefix seeking with PlainTable format and any prefix length regardless of whether the db has been flushed.
The rocksdbjni version being used is `6.20.3`. Thanks!

**Comment by angeladietz** [comment]
@adamretter @jay-zhuang @ajkr Is there any update on this? Thanks in advance.

**Comment by siying** [comment]
In prefix iterating, we don't support iterating outside the keys with the prefix. In capped iterator, if the seek key is shorter than the prefix length, only the key itself has the prefix of the seek key. If you don't have an exact key in DB, the behavior is undefined and might return null. Is it the case you are seeing?

**Comment by angeladietz** [comment]
If I understand you correctly, you're saying that if the prefix used in the `iterator.seek(prefix)` has a length less than the length of the capped prefix extractor, the only key which could possibly be found from the seek is a key which is equal to the prefix. Is this correct? And if so, is this still true even if the db has both a key which is equal to the prefix, and other keys which have that prefix but are longer?

I tried rerunning the above test except right after the line `rocksDB.put(key, value);`, I added the line `rocksDB.put(prefix,value);`. This time however, the iterator seek was able to find both key-value pairs which contradicts my understanding of your response.

As well, why does this behaviour only happen when using PlainTable format and not Block-based format?

**Comment by authsl** [comment]
@siying Do you know why this behavior only happens to PlainTable? Under BlockBasedTable, iterator could find the k/v pair even though the seek key is shorter than prefix extractor length. Is it because PlainTable uses hash + binary search, while BlockBasedTable uses binary search?

**Comment by siying** [comment]
It applies to both of block based table and plain table. Maybe specific implementation makes wrong result more visible, but we don't guarantee correctness for any table format the way it is used. One difference is that with Block Based Table, users can use this new interface https://github.com/facebook/rocksdb/wiki/Prefix-Seek#adaptive-prefix-mode which would be less prone to mistakes.

**Comment by pdillinger** [comment]
A prefix extractor puts keys into equivalence classes for keys that are "in domain," and the prefix must not be ordered after any keys in the equivalence class. The default prefix seek mode does not allow you to select a "subtree" of keys with any given leading substring. It only allows you to select an equivalence class of keys by the prefix determined by the prefix extractor. And the "undefined" part Siying refers to is that this mode might return results outside of the equivalence class once you iterate past any keys in the equivalence class.

As Siying said, "In capped iterator, if the seek key is shorter than the prefix length, only the key itself has the prefix of the seek key." So with capped extractor(6), the equivalence class for prefix {1,2,3,4,5} only includes that exact key, {1,2,3,4,5}. With capped extractor(5), the equivalence class for prefix {1,2,3,4,5} includes all keys starting with that.
