### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION in JVM when calling put/find/delete (on ClassLoader.findNative return statement)

### ISSUE THREAD

**Issue by DavidSandh** [facebook/rocksdb#8532]
When calling rocksDB.put/find/delete methods to use the database, the JVM crashes with below error message. It looks to occur just as ClassLoader.findNative returns the RocksDB library entry.
### Expected behavior
Data is written to the DB file

### Actual behavior
"# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe89e76c9f, pid=12872, tid=0x0000000000001604
#
# JRE version: Java(TM) SE Runtime Environment (8.0_201-b09) (build 1.8.0_201-b09)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.201-b09 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni5039116752717259225.dll+0xd6c9f]"

Full log file:
[hs_err_pid12872.log](https://github.com/facebook/rocksdb/files/6821696/hs_err_pid12872.log)

### Steps to reproduce the behavior
Code for initializing the database:
```
public static void initialize() throws RocksDBException {
		RocksDB.loadLibrary();
		String path = "D:\\temp";
		dbDir = new File(path, NAME);
		ColumnFamilyOptions cfOptions = new ColumnFamilyOptions();
		final List<ColumnFamilyHandle> columnFamilyHandles = new ArrayList<>();

		try (final ColumnFamilyOptions cfOpts = new ColumnFamilyOptions().optimizeUniversalStyleCompaction()) {

			// list of column family descriptors, first entry must always be default column
			// family
			final List<ColumnFamilyDescriptor> cfDescriptors = Arrays.asList(
					new ColumnFamilyDescriptor(RocksDB.DEFAULT_COLUMN_FAMILY, cfOptions),
					new ColumnFamilyDescriptor("obfuscate".getBytes(), cfOptions),
					new ColumnFamilyDescriptor("obfuscate".getBytes(), cfOptions),
					new ColumnFamilyDescriptor("obfuscate".getBytes(), cfOptions),
					new ColumnFamilyDescriptor("obfuscate".getBytes(), cfOptions));

			// a list which will hold the handles for the column families once the db is
			// opened
			final List<ColumnFamilyHandle> columnFamilyHandleList = new ArrayList<>();

			try (final DBOptions options = new DBOptions().setCreateIfMissing(true)
					.setCreateMissingColumnFamilies(true).setEnv(Env.getDefault());
					final RocksDB db = RocksDB.open(options, dbDir.getAbsolutePath(), cfDescriptors,
							columnFamilyHandleList)) {

				try {
					System.out.print("Opening DB");
				} finally {
					// NOTE frees the column family handles before freeing the db
					for (final ColumnFamilyHandle columnFamilyHandle : columnFamilyHandleList) {
						columnFamilyHandle.close();
					}
				}

				initialized = true;
				System.out.print("DB initialized");
				// frees the db and the db options
				db.close();
			}
		}
	}
```
Save method:
```
public static void save(UUID key, byte[] value, String cache) {
		try {
			db.put(key.toString().getBytes(), value);
		} catch (RocksDBException e) {
			// TODO Auto-generated catch block
			System.out.print("Error saving entry in RocksDB, cause: " + e.getMessage());
		}
	}
```
In the initialize() method I close the database stream, to later reopen it and return the RocksDB instance with a near-identical method. I encounter the same behavior no matter whether I close the DB or not.
I also get the same error whether i assign the DB instance to a static variable. and re-use it, or re-open the db locally in the method.

The crash occurs when ClassLoader.findNative tries to return an entry.
Specifically for calling put, the second argument provided to findNative is "Java_org_rocksdb_RocksDB_put__J_3BII_3BII".

JVM versions tried:
AdoptOpenJDK jdk-8.0.265.01-hotspot
Oracle jdk1.8.0_152
Oracle jdk1.8.0_201

**Comment by ajkr** [comment]
> later reopen it and return the RocksDB instance with a near-identical method

Can you show it? Does it also open the DB in a try-with-resources, which would accidentally close it?

Also I am not sure we support multiple CFs with the same name.

**Comment by DavidSandh** [comment]
Sure, the getDB() method looks like this:
```
public static RocksDB getDB() throws RocksDBException {
		RocksDB.loadLibrary();
		String path = "D:\\temp";
		dbDir = new File(path, NAME);
		ColumnFamilyOptions cfOptions = new ColumnFamilyOptions();
		final List<ColumnFamilyHandle> columnFamilyHandles = new ArrayList<>();

		try (final ColumnFamilyOptions cfOpts = new ColumnFamilyOptions().optimizeUniversalStyleCompaction()) {

			// list of column family descriptors, first entry must always be default column
			// family
			final List<ColumnFamilyDescriptor> cfDescriptors = Arrays.asList(
					new ColumnFamilyDescriptor(RocksDB.DEFAULT_COLUMN_FAMILY, cfOptions),
					new ColumnFamilyDescriptor("ParentIdToSubObjectIdsCache".getBytes(), cfOptions),
					new ColumnFamilyDescriptor("RecordIdToKeyCache".getBytes(), cfOptions),
					new ColumnFamilyDescriptor("RecordIdToObjectCache".getBytes(), cfOptions),
					new ColumnFamilyDescriptor("OwnerUUIDToSubObjectsCache".getBytes(), cfOptions));

			// a list which will hold the handles for the column families once the db is
			// opened
			final List<ColumnFamilyHandle> columnFamilyHandleList = new ArrayList<>();

			try (final DBOptions options = new DBOptions().setCreateIfMissing(true)
					.setCreateMissingColumnFamilies(true).setEnv(Env.getDefault());
					final RocksDB db = RocksDB.open(options, dbDir.getAbsolutePath(), cfDescriptors,
							columnFamilyHandleList)) {
				return db;
			}
		}
```

I want to note though, that this also occurred when just assigning the RocksDB to a static variable. Is this wrongful usage?

The "obfuscate" is just to hide company info, they're all different CFs in reality :)

**Comment by ajkr** [comment]
> Sure, the getDB() method looks like this:
> 
> ```
> public static RocksDB getDB() throws RocksDBException {
> 		RocksDB.loadLibrary();
> 		String path = "D:\\temp";
> 		dbDir = new File(path, NAME);
> 		ColumnFamilyOptions cfOptions = new ColumnFamilyOptions();
> 		final List<ColumnFamilyHandle> columnFamilyHandles = new ArrayList<>();
> 
> 		try (final ColumnFamilyOptions cfOpts = new ColumnFamilyOptions().optimizeUniversalStyleCompaction()) {
> 
> 			// list of column family descriptors, first entry must always be default column
> 			// family
> 			final List<ColumnFamilyDescriptor> cfDescriptors = Arrays.asList(
> 					new ColumnFamilyDescriptor(RocksDB.DEFAULT_COLUMN_FAMILY, cfOptions),
> 					new ColumnFamilyDescriptor("obfuscate1".getBytes(), cfOptions),
> 					new ColumnFamilyDescriptor("obfuscate2".getBytes(), cfOptions),
> 					new ColumnFamilyDescriptor("obfuscate3".getBytes(), cfOptions),
> 					new ColumnFamilyDescriptor("obfuscate4".getBytes(), cfOptions));
> 
> 			// a list which will hold the handles for the column families once the db is
> 			// opened
> 			final List<ColumnFamilyHandle> columnFamilyHandleList = new ArrayList<>();
> 
> 			try (final DBOptions options = new DBOptions().setCreateIfMissing(true)
> 					.setCreateMissingColumnFamilies(true).setEnv(Env.getDefault());
> 					final RocksDB db = RocksDB.open(options, dbDir.getAbsolutePath(), cfDescriptors,
> 							columnFamilyHandleList)) {
> 				return db;
> 			}
> 		}
> ```

This code appears to have a bug. The `db` is a resource in a try-with-resources statement, and `close()` will be automatically invoked on it at the end of that statement. So the client of this function can only get a closed DB.

> I want to note though, that this also occurred when just assigning the RocksDB to a static variable. Is this wrongful usage?

Not sure, again we'd need to see how the DB object is managed from open() to put() in case there's a bug in the client code. How about just change the getDB() to not use a try-with-resources and let us know how it goes?

> The "obfuscate" is just to hide company info, they're all different CFs in reality :)

Oh right, I should have noticed based on the name :).

**Comment by DavidSandh** [comment]
Sometimes the answer is so obvious you can only miss it. 

Thank you!!
It looks to work just fine without the try-with-resource statement.
