### ISSUE TITLE
While Running using benchmark.sh, the result does not display some fields using RocksDB v6.22.1

### ISSUE THREAD

**Issue by hdesai78** [facebook/rocksdb#8540]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
Do I need to enable any parameters within the benchmark.sh file in order to populate the results of the missing parameters? 

### Expected behavior

ops/sec | mb/sec | usec/op | p50 | p75 | p99 | p99.9 | p99.99 | Stall-time | Stall% | du -s -k
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1062310 | 425.5 | 0.9 | 0.5 | 0.8 | 1 | 3 | 1013 | 00:02:24.652 | 17.2 | 101402936
1045195 | 418.6 | 1.0 | 0.5 | 0.8 | 1 | 3 | 980 | 00:02:08.223 | 15.3 | 101401808
1017259 | 407.5 | 0.9 | 0.5 | 0.8 | 2 | 3 | 556 | 00:01:32.279 | 11.0 | 101406320
1013002 | 405.8 | 1.0 | 0.5 | 0.8 | 2 | 3 | 224 | 00:01:26.032 | 10.2 | 101405804
1031703 | 413.2 | 1.0 | 0.5 | 0.8 | 2 | 3 | 125 | 00:01:23.019 | 9.9 | 101403424

### Actual behavior

OPS/sec | mb/sec | Size-GB | L0_GB | Sum_GB | W-Amp | W-MB/s | usec/op | P50 | P75 | P99 | P99.9 | Uptime | Stall-Time | Stall% | Test
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
  |   | 0.1 | 53.2 | 53.2 | 1 | 56.7 |   |   |   |   |   | 960 | 09:40.2 | 60.4 | bulkload

### Steps to reproduce the behavior
By running following command
 NUM_KEYS=900000000 CACHE_SIZE=6442450944 DURATION=5400 ./benchmark.sh bulkload

**Comment by jay-zhuang** [comment]
Did you set environment variable  `DB_DIR` and `WAL_DIR`? the command should be like:
```
DB_DIR=/tmp/dbbench WAL_DIR=/tmp/dbbench NUM_KEYS=900000000 CACHE_SIZE=6442450944 tools/benchmark.sh bulkload
```

**Comment by mrambacher** [comment]
Did the database get populated and created and the problem is a reporting one or is something else amiss?

Did you set OUTPUT_DIR?  What are the contents of the benchmark log in that directory?
