### ISSUE TITLE
librocksdbjni-win64.dll from rocksdbjni-6.22.1.jar says "RocksDB version: 6.21.0"

### ISSUE THREAD

**Issue by stefan-zobel** [facebook/rocksdb#8586]
### Expected behavior
2021/07/24-18:36:50.521995 40d4 RocksDB version: 6.**22.1**

### Actual behavior
2021/07/24-18:36:50.521995 40d4 RocksDB version: 6.**21.0**
2021/07/24-18:36:50.522280 40d4 Git sha c7f8ae9f17743774ac48e2ffc6e150eafcfae416
2021/07/24-18:36:50.522321 40d4 Compile date 2021-07-23 11:30:29

### Steps to reproduce the behavior
I've used the librocksdbjni-win64.dll from the Maven Central rocksdbjni-6.22.1.jar which was uploaded on 2021-07-23.

From the LOG file:

2021/07/24-18:36:50.521995 40d4 RocksDB version: 6.21.0
2021/07/24-18:36:50.522280 40d4 Git sha c7f8ae9f17743774ac48e2ffc6e150eafcfae416
2021/07/24-18:36:50.522321 40d4 Compile date 2021-07-23 11:30:29

Why does ist say that it is version 6.21.0?
Is that correct?

@adamretter could you please have a look?

**Comment by adamretter** [comment]
@stefan-zobel Apologies for the confusion. It looks like for just the Windows binaries they were somehow built from a stale branch. So indeed the Windows dll is `6.21.0` and not `6.22.1`.

Maven Central does not enable you to remove artifacts, so instead I will upload an updated build tomorrow with the correct Windows binaries within it. As RocksDB is not following Semantic versioning exactly, I think the best way will likely be to number this new RocksJava release as `6.22.1.1`. Does that sound reasonable to you?

**Comment by stefan-zobel** [comment]
@adamretter
Hi Adam,

thanks for the confirmation. Yes, I think a `6.22.1.1` build is a reasonable plan.

**Comment by adamretter** [comment]
@stefan-zobel 6.22.1.1 has now been released to Maven Central and should show up within their next sync window ~2 hours.

RocksDB should report version `6.22.1` the additional `.1` postfix is just to indicate the newer build and packaging.

I will close this ticket now, please let me know if you have any issues.
