### ISSUE TITLE
Wiki has broken links

### ISSUE THREAD

**Issue by utdrmac** [facebook/rocksdb#8601]
### Expected behavior
For wiki links to work

### Actual behavior
Wiki links don't work ;)

### Steps to reproduce the behavior
Go here: https://github.com/facebook/rocksdb/wiki/Basic-Operations
Scroll to bottom. Click 'RocksDB Overview and Architecture'. Asks you to create new page.

Scroll to top. Expand 'Pages (146)'. Search for 'arch'. Click on only result, 'Rocksdb Architecture Guide'. Takes you to page that says content relocated. Click that link. Same as above.

**Comment by ltamasi** [comment]
Thanks for reporting @utdrmac ! Based on [the latest revision of that page before the content got moved](https://github.com/facebook/rocksdb/wiki/Rocksdb-Architecture-Guide/a1e4f83e8165ea3d3c8995b2b8e5f49cbf44f7b3), this got turned into the "Overview" page.

**Comment by ltamasi** [comment]
Fixed the links on both https://github.com/facebook/rocksdb/wiki/Basic-Operations and https://github.com/facebook/rocksdb/wiki/RocksDB-Overview.

**Comment by ltamasi** [comment]
There were a couple of mentions each on https://github.com/facebook/rocksdb/wiki/Terminology and https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ as well; also fixed.
