### ISSUE TITLE
The FSxxxFileWrapper classes have potential inner ownership issues

### ISSUE THREAD

**Issue by mrambacher** [facebook/rocksdb#8606]
I think this applies to all of the FSxxxFileWrapper classes.

For example, the FSRandomRWFileWrapper class is constructed as such:
  explicit FSRandomRWFileWrapper(FSRandomRWFile* t) : target_(t) {}
The "target_" is not deleted when this instance is destroyed, meaning that the class may be relying on some other class for the destruction of target_ (there is no documentation).
- If another class destroys target before this class is destroyed, there is a potential that target_ points to invalid memory
- Alternatively, it is possible another class never destroys target_, since the ownership of the inner value is unclear.

This has the potential to get worse as more layers are added.  For example, a CountedFileSystem or EncryptedFileSystem could return these wrapped Files.  The ownership of the different layers gets complicated.

The FSxxxFileWrapper classes should take a std::unique_ptr<>&&  as a constructor argument and assume ownership of the inner/wrapped value.  This change will prevent leaks and use after deletion.

**Comment by siying** [comment]
I agree that the current interface is not a nice one and is confusing. However, users might have already been using it in many places. Does it worth it breaking users' existing uses?

**Comment by mrambacher** [comment]
If it is required for backwards compatibility to support both the old and new one, we could do that by two constructors and storing both a unique_ptr and its contents.  If passed a unique_ptr, the wrapper takes ownership.  If passed a raw one, it does not.

Is that desirable and/or a requirement?
