### ISSUE TITLE
Documentation incorrect for bloom filter setting

### ISSUE THREAD

**Issue by utdrmac** [facebook/rocksdb#8612]
Regarding this paragraph: https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide#bloom-filters

> Bloom filters are always kept in memory for open files, unless BlockBasedTableOptions::cache_index_and_filter_blocks is set to true.

This contradicts the logic implied by the name of the variable (where 'true' would cache the index and filter blocks), and also the comments within the code (https://github.com/facebook/rocksdb/blob/5ba1b6e5495ed7c4023dc7983b1268c943fb4d84/include/rocksdb/table.h#L125)

Can someone please confirm and correct the documentation?

**Comment by ltamasi** [comment]
This might sound counterintuitive and the wording could be clearer but it's actually correct. There are two cases: 1) `cache_index_and_filter_blocks` is `false`: metablocks are kept in memory as long as the file is open but they are not *in the cache* (and thus don't count towards the block cache memory limit), and 2) `cache_index_and_filter_blocks` is `true`: metablocks are stored in the cache, which means they count towards the limit but might get evicted.

[This](https://github.com/facebook/rocksdb/wiki/Block-Cache#caching-index-filter-and-compression-dictionary-blocks) page has more details about the relevant options and their effects.
