### ISSUE TITLE
[JAVA] RocksDB Java test failure

### ISSUE THREAD

**Issue by bjlemaire** [facebook/rocksdb#8630]
### Expected behavior

org.rocksdb.util.BytewiseComparatorTest test passes when running RocksDBJava tests.

### Actual behavior

Test fails: 

```
Running: org.rocksdb.util.BytewiseComparatorTest
Assertion failed: (jclazz != nullptr), function getJClass, file ./java/./rocksjni/portal.h, line 69.
make[1]: *** [run_test] Abort trap: 6
make[1]: *** Waiting for unfinished jobs....
```

### Steps to reproduce the behavior

See full test [here](https://app.circleci.com/pipelines/github/facebook/rocksdb/8263/workflows/41bbc547-90fa-4c45-b01b-930061a7e215/jobs/176644).

**Comment by adamretter** [comment]
**NOTE** This is shown as part of the CI for this PR - https://github.com/facebook/rocksdb/pull/8628

I haven't seen this being flaky before, let me try restarting the CI...

**Comment by bjlemaire** [comment]
I'm not sure if this is coming from the PR (#8628) or not, so I decided to report it just in case. But if it doesn't show up again feel free to close it, else I'll do it.

**Comment by adamretter** [comment]
@bjlemaire I don't immediately see anything in your PR that would make me think that it would affect that test... so let's see what happens...

**Comment by ajkr** [comment]
Put up-for-grabs I guess. Anyone who wants can make a judgement that it's closable, for example, based on not seeing it for a while, or based on stressing the test and not being able to repro any failure.
