### ISSUE TITLE
Support in rocksdb 5.18.4

### ISSUE THREAD

**Issue by srajmane** [facebook/rocksdb#8642]
We would like to volunteer to add s390x support for rocksdb 5.18.4, as this is dependency for another package.
Will you be willing to accept PRs to 5.18.x branch to add s390x support?
Can we get jar file from https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni for rocksdb 5.18.4?

**Comment by jay-zhuang** [comment]
RocksDB's APIs are typically backward compatible, is there any specific reason you cannot upgrade to the latest version? We would highly recommend you to do so, the new version has more bug fixes, performance improvement and features.
Please feel free to re-open if needed, thanks.

**Comment by srajmane** [comment]
The package that we are building needs this specific rocksdb (5.18.4) only, we tried using the latest however it doesn't seem to be compatible

**Comment by cwsolee** [comment]
@jay-zhuang We're porting the latest code base and will PR any fixes required, once we complete all that, we might try to ask Apache Kafka to move up to latest but not sure whether they'll agree to. Partly why we would like to see whether we could back port the needed change to 5.18.x also.

**Comment by jay-zhuang** [comment]
For general guideline, patch release cannot have new features, API change etc. (plus the old branch is not maintained and may not be built for all platforms, which is a requirement for official release).
On the other hand, even we created new patch release, you will still need to upgrade the RocksDB dependency from 5.18.4 -> 5.18.5 for your build. In that case, why cannot you just upgrade to 6.22.1?
If an old release is really needed by a special need, you can always backport and build the JAR by yourself.

**Comment by cwsolee** [comment]
Thanks and I hear u, we're going to work with packages that depends on rocksdb to move up to newer release. For now, we did provide instruction https://github.com/linux-on-ibm-z/docs/wiki/Building-Apache-Kafka to help user to build Kafka which required rocksdb 5.18.4 with z patch. Thanks for your consideration, we'll focus on making sure latest rocksdb is working on z.

**Comment by adamretter** [comment]
@cwsolee I started on getting things passing on s390x some time ago, but I never had time to complete it - maybe it's helpful for you - https://github.com/facebook/rocksdb/pull/6168/files

**Comment by cwsolee** [comment]
Thanks @adamretter We'll certainly take a look, we just started to work on latest too.
