### ISSUE TITLE
Getting a deadlock while write in database

### ISSUE THREAD

**Issue by TimurMamedov-zz** [facebook/rocksdb#8643]
### Expected behavior
No deadlock
### Actual behavior
Getting a deadlock while write in database
### Steps to reproduce the behavior
1. Open a database in which for each ColumnFamily `disable_auto_compactions=false` and which have 
`write_stall_condition == WriteStallCondition::kStopped &&
               write_stall_cause == WriteStallCause::kL0FileCountLimit`
https://github.com/facebook/rocksdb/blob/82b81dc8b5e5370d1c77c860da9b518b5a7681ad/db/column_family.cc#L903
2. SetOptions where for each ColumnFamily `disable_auto_compactions=true`
3. Write into Database and get deadlock in https://github.com/facebook/rocksdb/blob/82b81dc8b5e5370d1c77c860da9b518b5a7681ad/db/db_impl/db_impl_write.cc#L1532 where `bg_cv_` will wait forever

**Comment by ajkr** [comment]
What is the RocksDB version, and do you have a LOG file we can look at? I thought about it a bit but couldn't yet think of a way that code path gets stuck waiting on CV and/or WriteController gets stuck in stall mode despite setting `disable_auto_compactions=true`.

**Comment by TimurMamedov-zz** [comment]
Hi. Sorry for not answering for a long time. I used RocksDB 6.19.3. I don't have LOG file, but when I tried to reproduce this BUG with LOG file, I could not do this even on the version of the application where it was reproduced constantly. If I can reproduce it again I will attach a log file.
