### ISSUE TITLE
Can Java rocksdb define a subclass that inherits MergeOperator, such as modifying a key of JSON

### ISSUE THREAD

**Issue by xiaoyangxu** [facebook/rocksdb#8665]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

**Comment by ajkr** [comment]
Yes, you can subclass MergeOperator for this purpose. Your subclass should implement `FullMergeV2()`. `MergeOperationInput::existing_value` gives you the base JSON value if one exists. `MergeOperationInput::operand_list` gives you the list of changes (merges) that are newer than the JSON value. Your `FullMergeV2()` can apply the changes and write the result to `MergeOperationOutput::new_value`.
