### ISSUE TITLE
Support for s390x platform

### ISSUE THREAD

**Issue by vishwabmc** [facebook/rocksdb#8698]
We are compiling Solana in s390x platform and that uses rocksdb. It needed a support to be added in toku_time.h and I have pushed that code in 

https://github.com/vishwabmc/rocksdb/commit/3013350e2ddc35715ab353bf9f129f241233410c

Please help review and let me know if there is any feedback. If everything is acceptable. would you consider merging it ?.. 
Thanks.

**Comment by mrambacher** [comment]
You should create a PR for your changes so they can be reviewed and merged.  You will need to sign the Contributors License Agreement as well.

Once those happen, we can work on reviewing and merging your changes.  Thank you for the contribution!

**Comment by hegjon** [comment]
Related to #8610

**Comment by ajkr** [comment]
Let's use #8610 to track this.
