### ISSUE TITLE
Key not found unexpectedly due to 'Blob Not Found as blob file missing'

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#8705]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

I use blobdb in rocksdb 5.11.3. And I create 2 threads. One is write thread and another is read thread. 
In write thread, I write key of `key_{1~1000000}` with value of 1k in one loop. At the end of loop, I will call compact manually. This loop will run again and again. 
In read thread, I read key as those written in write thread. 

After several hours later, I found Key not found unexpectedly due to 'Blob Not Found as blob file missing'.

### Expected behavior
No key is not found. 
### Actual behavior
Key not found unexpectedly due to 'Blob Not Found as blob file missing'.

**Comment by GOGOYAO** [comment]
> > Yes, those races were fixed in RocksDB 6.5 (see #5698).
> 
> thank you. I will add the patch and test again. close this issue ahead

I merge the commit to my code. But I encountered the not found error again. Any more bug has been fixed?

**Comment by ltamasi** [comment]
> I merge the commit to my code. But I encountered the not found error again. Any more bug has been fixed?

Like I said, the version you're using is a *very early development version* of the *old* BlobDB. This predates me but looking at the history, there were many fixes and major changes over 2018 and early 2019. I think your best bet would be to try a recent version; cherry-picking fixes might not be realistic with the amount of changes involved.

**Comment by ltamasi** [comment]
Also, regarding your options:

> Options is as follow.
> 
> ```
>   blob_ops.enable_garbage_collection = true;
>   blob_ops.part_expire_percent = 30;
> ```

I don't see any option named `part_expire_percent` in 5.11: https://github.com/facebook/rocksdb/blob/5.11.fb/utilities/blob_db/blob_db.h#L31-L85

And in fact, a brief search hasn't turned up any mentions of it either. Are you using a custom fork of RocksDB/BlobDB?

**Comment by GOGOYAO** [comment]
> > I merge the commit to my code. But I encountered the not found error again. Any more bug has been fixed?
> 
> Like I said, the version you're using is a _very early development version_ of the _old_ BlobDB. This predates me but looking at the history, there were many fixes and major changes over 2018 and early 2019. I think your best bet would be to try a recent version; cherry-picking fixes might not be realistic with the amount of changes involved.

ok. thank you

**Comment by GOGOYAO** [comment]
> Also, regarding your options:
> 
> > Options is as follow.
> > ```
> >   blob_ops.enable_garbage_collection = true;
> >   blob_ops.part_expire_percent = 30;
> > ```
> 
> I don't see any option named `part_expire_percent` in 5.11: https://github.com/facebook/rocksdb/blob/5.11.fb/utilities/blob_db/blob_db.h#L31-L85
> 
> And in fact, a brief search hasn't turned up any mentions of it either. Are you using a custom fork of RocksDB/BlobDB?

Yes. We add some code to support our custom feature
