### ISSUE TITLE
If it is necessary cache value read from blob files

### ISSUE THREAD

**Issue by leon-db** [facebook/rocksdb#8713]
Generally speaking, the RocksDB instance's size have a limit size in designing because we need to take account of the failover.   So  block_cache size compared with not use the BlobDB, is big enough and all the block cache not used will be wasted.  Also we can make the block_cache size much more smaller,  but resource on a single machine are mutually limited.
In out case, We don't want to change the count of deployment RocksDB on a single machine. So is there have a plan to use the memory to cache the value read from blob file(*.blob).  Technically, there is no challenge to correctness.  The only challenge it may be the cache storage efficiency, because the value smaller than min_blob_size will be storage inline, but compared with 
wasting the memory resource, i thank use the memory to storage blob value read from blob file is worthy, and we can introduce a max_blob_size，all the value between min_blob_size and max_blob_size will storage in that "blob cache"(not the blob cache for blob file handle).  While another solution is just give the memory back to OS (page cache). In some case, just 
give the memory to the OS should be simple and better. But it should be better to cache in RocksDB in some other case.

Now my question is if we have a plan to impl this feature,  any suggestion would be greatly appreciated.  And if it is ok I will 
have time to implement this feature.

**Comment by ltamasi** [comment]
@leon-db Sorry about the long delay. Would you still be interested in working on this feature?

**Comment by ltamasi** [comment]
Implemented in RocksDB 7.5, with improvements up to 7.7
