### ISSUE TITLE
RocksJava UnsupportedOperationException in internal ByteBuffer during seek

### ISSUE THREAD

**Issue by nvaishampayan517** [facebook/rocksdb#8715]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
No exception being thrown on seek.

### Actual behavior
Error stack trace:
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.nio.ByteBuffer.array(ByteBuffer.java:1002)
	at org.rocksdb.RocksIterator.seek0(Native Method)
	at org.rocksdb.AbstractRocksIterator.seek(AbstractRocksIterator.java:60)
```

### Steps to reproduce the behavior
See `DatabaseHandlerTest::testContainsValueFunctionalityAdvanced` from https://github.com/CorfuDB/CorfuDB/pull/3005

Pseudocode:
1. Open database with default options, and comparator defined in `ReversedVersionedKeyComparator`
2. Call `DatabaseHandler::containsValue` which performs multiple iterations of `DatabaseHandler::scan`
3. Each scan call creates a new iterator in the DB with `totalOrderSeek`, and uses `seekToFirst()` and `seek()` to scan the DB

**Comment by adamretter** [comment]
@nvaishampayan517 At the moment it doesn't appear to me that `org.rocksdb.RocksIterator.seek0(Native Method)` even calls `ByteBuffer.array`.

Can you please provided a minimum reproducible test case? It's not reasonable to expect us to download and debug an external project.

**Comment by nvaishampayan517** [comment]
Here's a test class that produces the error:

        import com.google.common.primitives.Bytes;
        import com.google.common.primitives.Longs;
        import org.corfudb.infrastructure.remotecorfutable.ReversedVersionedKeyComparator;
        import org.rocksdb.ColumnFamilyDescriptor;
        import org.rocksdb.ColumnFamilyHandle;
        import org.rocksdb.ColumnFamilyOptions;
        import org.rocksdb.ComparatorOptions;
        import org.rocksdb.Options;
        import org.rocksdb.ReadOptions;
        import org.rocksdb.RocksDB;
        import org.rocksdb.RocksDBException;
        import org.rocksdb.RocksIterator;
        import org.rocksdb.WriteBatch;
        import org.rocksdb.WriteOptions;
        
        import java.util.ArrayList;
        import java.util.Arrays;
        import java.util.LinkedList;
        import java.util.List;
        import java.util.Map;
        import java.util.UUID;
        import java.util.concurrent.ConcurrentHashMap;
        import java.util.stream.Collectors;
        import java.util.stream.IntStream;
        
        public class MinReproducibleTestCase {
            static {
                RocksDB.loadLibrary();
            }
        
            public static class Handler {
        
                private final RocksDB database;
                private final Map<UUID, ColumnFamilyHandle> columnFamilies;
        
                public Handler(String path, Options options) throws RocksDBException {
                    RocksDB.destroyDB(path, options);
                    this.database = RocksDB.open(options, path);
                    this.columnFamilies = new ConcurrentHashMap<>();
                }
        
                public void addTable(UUID streamID) throws RocksDBException {
                    ColumnFamilyOptions tableOptions = new ColumnFamilyOptions();
                    tableOptions.optimizeUniversalStyleCompaction();
                    ComparatorOptions comparatorOptions = new ComparatorOptions();
                    ReversedVersionedKeyComparator comparator = new ReversedVersionedKeyComparator(comparatorOptions);
                    tableOptions.setComparator(comparator);
                    ColumnFamilyDescriptor tableDescriptor = new ColumnFamilyDescriptor(getBytes(streamID), tableOptions);
                    ColumnFamilyHandle tableHandle = database.createColumnFamily(tableDescriptor);
                    columnFamilies.put(streamID, tableHandle);
                }
                
                private byte[] getBytes(UUID id) {
                    return Bytes.concat(Longs.toByteArray(id.getMostSignificantBits()),
                            Longs.toByteArray(id.getLeastSignificantBits()));
                }
        
                public void updateAll(List<byte[][]> keyValuePairs, UUID streamID)
                        throws RocksDBException {
                    ColumnFamilyHandle currTable = columnFamilies.get(streamID);
                    try (WriteBatch batchedWrite = new WriteBatch();
                         WriteOptions writeOptions = new WriteOptions()) {
                        for (byte[][] pair : keyValuePairs) {
                            byte[] keyBytes = pair[0];
                            byte[] valueBytes = pair[1];
                            batchedWrite.put(currTable,keyBytes,valueBytes);
                        }
                        database.write(writeOptions,batchedWrite);
                    }
                }
        
                private List<byte[][]> scan(byte[] startKey, int numEntries, UUID streamID)
                        throws RocksDBException {
                    List<byte[][]> results = new LinkedList<>();
                    int elements = 0;
                    try (ReadOptions iterOptions = new ReadOptions()){
                        iterOptions.setTotalOrderSeek(true);
                        try (RocksIterator iter = database.newIterator(columnFamilies.get(streamID),
                                iterOptions)) {
                            if (startKey == null) {
                                iter.seekToFirst();
                            } else {
                                iter.seek(startKey);
                                if (!iter.isValid()) {
                                    return results;
                                }
                                iter.next();
                            }
                            while (iter.isValid()) {
                                results.add(new byte[][]{iter.key(), iter.value()});
                                elements++;
                                if (elements > numEntries) {
                                    break;
                                }
                                iter.next();
                            }
                            if (!iter.isValid()) {
                                iter.status();
                            }
                        }
                    }
                    return results;
                }
        
                public boolean containsValue(byte[] encodedValue, UUID streamID, int scanSize)
                        throws RocksDBException {
                    boolean first = true;
                    byte[] lastKey = null;
                    List<byte[][]> scannedEntries;
                    do {
                        scannedEntries = scan(lastKey,scanSize, streamID);
                        for (byte[][] scannedEntry : scannedEntries) {
                            if (Arrays.equals(scannedEntry[1], encodedValue)) {
                                return true;
                            }
                        }
                        if (!scannedEntries.isEmpty()) {
                            lastKey = scannedEntries.get(scannedEntries.size() - 1)[0];
                        }
                    } while (scannedEntries.size() >= scanSize);
                    return false;
                }
        
                
        
                public void close() {
                    for (ColumnFamilyHandle handle : columnFamilies.values()) {
                        handle.close();
                    }
                    database.close();
                }
            }
        
            public static void main(String[] args) throws RocksDBException {
                Options opts = new Options();
                opts.setCreateIfMissing(true);
                Handler handler = new Handler("testDB", opts);
                UUID stream1 = UUID.randomUUID();
        
                List<byte[][]> entries = new ArrayList<>(1000);
                List<byte[]> vals = IntStream.range(0,1000)
                        .mapToObj(j -> ("val" + j).getBytes()).collect(Collectors.toList());
                byte[] key;
                byte[] value;
                for (int i = 0; i < 1000; i++) {
                    value = vals.get(i);
                    key = Bytes.concat(
                            ("key" + i).getBytes(), Longs.toByteArray(0L));
                    entries.add(new byte[][]{key, value});
                }
                handler.addTable(stream1);
                handler.updateAll(entries, stream1);
        
                for (byte[] val : vals) {
                    handler.containsValue(val, stream1, 3);
                }
        
                handler.close();
            }
        }

Sorry for the length of the example, it's the smallest approximation of the conditions in which the error is logged. I am not sure how to consistently trigger the exception, since some runs of the class pass with no exceptions logged.

Additionally, the exception seems to be handled somehow by the native code, since the iter.seek() and iter.next() calls do not throw an error that can be caught by my Java program.

**Comment by dfa1** [comment]
@nvaishampayan517 @adamretter stumbled upon this error as well. Please find a minimal reproducer (i.e. kicked out guava dependency):

```
import org.rocksdb.ColumnFamilyDescriptor;
import org.rocksdb.ColumnFamilyHandle;
import org.rocksdb.ColumnFamilyOptions;
import org.rocksdb.ComparatorOptions;
import org.rocksdb.Options;
import org.rocksdb.RocksDB;
import org.rocksdb.RocksDBException;
import org.rocksdb.RocksIterator;
import org.rocksdb.WriteBatch;
import org.rocksdb.WriteOptions;
import org.rocksdb.util.ReverseBytewiseComparator;

import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;

public class MinimalBugRepro {
	static {
		RocksDB.loadLibrary();
	}

	public static class Handler {

		private final RocksDB database;
		private final Map<UUID, ColumnFamilyHandle> columnFamilies;

		public Handler(String path, Options options) throws RocksDBException {
			RocksDB.destroyDB(path, options);
			this.database = RocksDB.open(options, path);
			this.columnFamilies = new ConcurrentHashMap<>();
		}

		public void addTable(UUID streamID) throws RocksDBException {
			ColumnFamilyOptions tableOptions = new ColumnFamilyOptions();
			tableOptions.optimizeUniversalStyleCompaction();
			ComparatorOptions comparatorOptions = new ComparatorOptions();
			//comparatorOptions.setReusedSynchronisationType(ReusedSynchronisationType.ADAPTIVE_MUTEX);
			tableOptions.setComparator(new ReverseBytewiseComparator(comparatorOptions));
			ColumnFamilyDescriptor tableDescriptor = new ColumnFamilyDescriptor(streamID.toString().getBytes(StandardCharsets.UTF_8), tableOptions);
			ColumnFamilyHandle tableHandle = database.createColumnFamily(tableDescriptor);
			columnFamilies.put(streamID, tableHandle);
		}

		public void updateAll(List<byte[][]> keyValuePairs, UUID streamID)
			throws RocksDBException {
			ColumnFamilyHandle currTable = columnFamilies.get(streamID);
			try (WriteBatch batchedWrite = new WriteBatch();
			     WriteOptions writeOptions = new WriteOptions()) {
				for (byte[][] pair : keyValuePairs) {
					byte[] keyBytes = pair[0];
					byte[] valueBytes = pair[1];
					batchedWrite.put(currTable, keyBytes, valueBytes);
				}
				database.write(writeOptions, batchedWrite);
			}
		}

		// a silly loop trying to locale value
		public boolean containsValue(byte[] encodedValue, UUID streamID) {
			try (RocksIterator iter = database.newIterator(columnFamilies.get(streamID))) {
				iter.seekToFirst();
				while (iter.isValid()) {
					byte[] val = iter.value();
					if (Arrays.equals(val, encodedValue)) {
						return true;
					}
					iter.next();
				}
			}
			return false;
		}


		public void close() {
			for (ColumnFamilyHandle handle : columnFamilies.values()) {
				handle.close();
			}
			database.close();
		}
	}

	private static void test(int n) throws RocksDBException {
		Options opts = new Options();
		opts.setCreateIfMissing(true);
		Handler handler = new Handler("testDB", opts);
		UUID stream1 = UUID.randomUUID();

		List<byte[][]> entries = new ArrayList<>();
		for (int i = 0; i < n; i++) {
			byte[] value = value(i);
			byte[] key = key(i);
			entries.add(new byte[][]{key, value});
		}
		handler.addTable(stream1);
		handler.updateAll(entries, stream1);

		for (int i = 0; i < n; i++) {
			byte[] val = value(i);
			boolean hasValue = handler.containsValue(val, stream1);
			if (!hasValue) {
				throw new IllegalStateException("not has value " + i);
			}
		}

		handler.close();
	}

	private static byte[] key(int i) {
		return ("key" + i).getBytes(StandardCharsets.UTF_8);
	}

	private static byte[] value(int i) {
		return ("value" + i).getBytes(StandardCharsets.UTF_8);
	}

	public static void main(String[] args) throws RocksDBException {
		int n = 1_000;
		int repeatTest = 100;

		// the error is not always reproducible... let's try to increase the odds by repeating the main test body
		for (int i = 0; i < repeatTest; i++) {
			test(n);
			System.out.println("done " + i);
		}
	}

}
```

Some facts:
- the bug is still reproducible on 6.25.3 with OpenJDK11/MacOSX
- I'm using a Java comparator shipped with the library (i.e. `ReverseBytewiseComparator`, so need to need to have `org.corfudb.infrastructure.remotecorfutable.ReversedVersionedKeyComparator`)
- the bug is not always triggered: it never happens with n=10 and a very high number of repetitions but happens a lot with n=1000
- when the bug is triggered I can see only stacktraces in `RocksIterator.next0` or `RocksIterator.seek0`  printed on stderr (perhaps it is one of those `env->ExceptionDescribe(); // print out exception to stderr
` in `comparatorjnicallback.cc`?). 

For reference I see these two stacktraces:
```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.nio.ByteBuffer.array(ByteBuffer.java:1049)
	at org.rocksdb.RocksIterator.next0(Native Method)
	at org.rocksdb.AbstractRocksIterator.next(AbstractRocksIterator.java:86)
	at MinimalBugRepro$Handler.containsValue(MinimalBugRepro.java:71)
	at MinimalBugRepro.test(MinimalBugRepro.java:103)
	at MinimalBugRepro.main(MinimalBugRepro.java:126)
```

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at java.base/java.nio.ByteBuffer.array(ByteBuffer.java:1049)
	at org.rocksdb.RocksIterator.next0(Native Method)
	at org.rocksdb.AbstractRocksIterator.next(AbstractRocksIterator.java:86)
	at MinimalBugRepro$Handler.containsValue(MinimalBugRepro.java:71)
	at MinimalBugRepro.test(MinimalBugRepro.java:103)
	at MinimalBugRepro.main(MinimalBugRepro.java:126) 
```

**Comment by dfa1** [comment]
@adamretter found also two other problems:

1) by enabling 
```java
comparatorOptions.setReusedSynchronisationType(ReusedSynchronisationType.THREAD_LOCAL);
comparatorOptions.setMaxReusedBufferSize(1 << 20);
```
JVM  is crashing:

```
Stack: [0x000070000f3fa000,0x000070000f4fa000],  sp=0x000070000f4f9700,  free space=1021k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libsystem_pthread.dylib+0x1d86]  pthread_mutex_lock+0x4
C  [librocksdbjni10525004276510915101.jnilib+0x2d5489]  rocksdb::port::Mutex::Lock()+0x9
C  [librocksdbjni10525004276510915101.jnilib+0x9ccf]  rocksdb::ComparatorJniCallback::Compare(rocksdb::Slice const&, rocksdb::Slice const&) const+0x6f
C  [librocksdbjni10525004276510915101.jnilib+0x150eb0]  rocksdb::DBIter::FindNextUserEntryInternal(bool, rocksdb::Slice const*)+0x7c0
C  [librocksdbjni10525004276510915101.jnilib+0x1502d7]  rocksdb::DBIter::FindNextUserEntry(bool, rocksdb::Slice const*)+0x67
C  [librocksdbjni10525004276510915101.jnilib+0x14fd5d]  rocksdb::DBIter::Next()+0x18d
J 553  org.rocksdb.RocksIterator.next0(J)V (0 bytes) @ 0x000000012c4ddc7b [0x000000012c4ddbc0+0x00000000000000bb]
J 569 c2 MinimalBugRepro$Handler.containsValue([BLjava/util/UUID;)Z (106 bytes) @ 0x000000012c4e2418 [0x000000012c4e2240+0x00000000000001d8]
```
Details here: [hs_err_pid48035.log](https://github.com/facebook/rocksdb/files/7577027/hs_err_pid48035.log)

2) when I try to disable buffer reuse as mentioned by javadoc: 

```java
comparatorOptions.setMaxReusedBufferSize(0);
```

I get a lot of exceptions like:

```
Exception in thread "main" java.lang.IllegalArgumentException: newLimit > capacity: (6 > 0)
	at java.base/java.nio.Buffer.createLimitException(Buffer.java:372)
	at java.base/java.nio.Buffer.limit(Buffer.java:346)
	at java.base/java.nio.ByteBuffer.limit(ByteBuffer.java:1107)
	at java.base/java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:235)
	at java.base/java.nio.MappedByteBuffer.limit(MappedByteBuffer.java:67)
	at org.rocksdb.AbstractComparatorJniBridge.compareInternal(AbstractComparatorJniBridge.java:47)
	at org.rocksdb.RocksIterator.next0(Native Method)
	at org.rocksdb.AbstractRocksIterator.next(AbstractRocksIterator.java:86)
	at MinimalBugRepro$Handler.containsValue(MinimalBugRepro.java:72)
	at MinimalBugRepro.test(MinimalBugRepro.java:104)
	at MinimalBugRepro.main(MinimalBugRepro.java:127)
```

but the program completes normally. Setting this to a negative value for `setMaxReusedBufferSize`, crashes the JVM with 
[hs_err_pid48158.log](https://github.com/facebook/rocksdb/files/7577056/hs_err_pid48158.log).

(Not sure if I should open separate issues for these to not pollute the original issue by @nvaishampayan517... ideas?)
