### ISSUE TITLE
Can compaction happen across different column families from RocksDB-5.17?

### ISSUE THREAD

**Issue by Myasuka** [facebook/rocksdb#8718]
### Expected behavior
As we all know, comlumn family actually separets data physiscally, and compaction actually happened within each column family. We have different key value formats to write for different column familes: cf-A has key-format-A with always empty value, and cf-B has key-format-B with value-format-B.

### Actual behavior
After long running, cf-A exsistd data with key-format-B and value-format-B in a level-1 SST file, as we would check the format when we are writiing, it's really weird to scan out such unexpected data out. 
My guess is that the unexpected data occurs during compaction which includes input files belonging to other column family. 
Although this idea is really creazy, I cannot figure out other reasonable explanation yet. Could you tell me that is there any known simliar bug existed before? (I checked the history but nothing found.)

**Comment by anand1976** [comment]
@Myasuka I have not heard of anything like this before. The only storage that column families share are WAL files. There is no way, by design or code, that data can move across column families. Maybe you can check the manifest file for which CF the level-1 SST file actually belongs to?

**Comment by Myasuka** [comment]
@anand1976 Thanks for your response. I checked before and the level-1 sst files actually belongs to the CF-A which should have key-format-A with always empty value.
Since we already disabled WAL of RocksDB in our use case, it's really weird that why data could be mixed.

**Comment by ajkr** [comment]
Do you use any advanced features like RepairDB(), best effort recovery, etc?

Upon restarting the process, do you see the problem still? It sounds like you checked the SST files actually have contents corresponding to the correct CF. So I would expect the problem went away after restart.

Do you know what was the nature of the KVs unexpectedly returned from CF B? Such as, how many consecutive CF B keys were returned? After scanning further did CF A keys resume showing up? Were the CF B keys out of order relative to the CF A keys? I guess it might be impossible to answer these questions now if it only happened once. But if you know the answer it could help us evaluate whether you ran into this tricky bug -- https://github.com/facebook/rocksdb/issues/7405#issuecomment-694595587.

Another question I have, based on this and another surprising issue you ran into (empty CURRENT file), is what filesystem are you using?

**Comment by Myasuka** [comment]
Thanks for @ajkr kind response! Some of the answers for your questions:

> Do you use any advanced features like RepairDB(), best effort recovery, etc?

No, we just use RocksDB of multi column families with WAL disabled.

> Upon restarting the process, do you see the problem still

Yes, I use `sst_dump` to checked the files, one of the SST file is corrupted.

> what filesystem are you using

Ext4 file system and running within a docker container.

**Comment by ajkr** [comment]
> Thanks for @ajkr kind response! Some of the answers for your questions:
> 
> > Do you use any advanced features like RepairDB(), best effort recovery, etc?
> 
> No, we just use RocksDB of multi column families with WAL disabled.
> 
> > Upon restarting the process, do you see the problem still
> 
> Yes, I use `sst_dump` to checked the files, one of the SST file is corrupted.
> 
> > what filesystem are you using
> 
> Ext4 file system and running within a docker container.

Thanks for the extra info. When you look at the keys in `sst_dump` where the entries switch from CF A -> B or CF B -> A, is there any key mis-ordering as well?

**Comment by Myasuka** [comment]
@ajkr Sorry for no reply to your extra question as I am busy with internal development works. I'll check another column family in next days.
