### ISSUE TITLE
how many skiplists can be there at most in a memtable?

### ISSUE THREAD

**Issue by dzwinning** [facebook/rocksdb#8735]
as the title.  thanks。

**Comment by ramvadiv** [comment]
@dzwinning - GitHub Issues are meant for only reporting suspected issues and not for asking questions. Pls see the guidance provided during New Issues creation - "Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev"

Pls review the following Wiki - https://github.com/facebook/rocksdb/wiki/MemTable . This wiki contains pointers to your question. Pls use the forums listed above for any follow-up questions.
