### ISSUE TITLE
ar: creating archive librocksdb.a /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(xfunc.o) has no symbols

### ISSUE THREAD

**Issue by jonnywang** [facebook/rocksdb#875]
rocksdb 4.1
os mac 10.11.1

ar: creating archive librocksdb.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: librocksdb.a(xfunc.o) has no symbols

**Comment by PaladinTyrion** [comment]
Finally, there is no solution??

**Comment by thinkerou** [comment]
And then?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
