### ISSUE TITLE
Using rocksdb_compactionfilter_destroy leads to a Segfault

### ISSUE THREAD

**Issue by pydima** [facebook/rocksdb#8752]
When `rocksdb_compactionfilter_destroy` is called it deletes compaction filter object, but `ColumnFamilyData->ioptions()->compaction_filter` still has a pointer to deleted compaction filter, so when compaction kicks in it leads to a Segfault. Is it expected behaviour? I'd expect that filter would be deleted completely (together with all pointers to it), so it won't lead to a Segfault.

**Comment by ajkr** [comment]
The DB is configured with a raw pointer to `CompactionFilter`. That object must not be destroyed while the DB is using it.

`CompactionFilterFactory` is configured in the more modern `shared_ptr` way so, using that API, a client could destroy its copy of the `shared_ptr` at any time.
