### ISSUE TITLE
compile problems,cmake have no way to open AVX2 for bloomfilter

### ISSUE THREAD

**Issue by dongdongwcpp** [facebook/rocksdb#8886]
rocksdb version 6.24.0,building by cmake.
`cmake ../ -DCMAKE_BUILD_TYPE=Release  -DWITH_SNAPPY=1 -DWITH_JEMALLOC=1 -DWITH_ZLIB=1 -DCMAKE_INSTALL_PREFIX=/root/tmp/rocksdb/output -DJeMalloc_LIBRARIES=/root/tmp/rocksdb/third-party/jemalloc/output/lib/libjemalloc.a -DJeMalloc_INCLUDE_DIRS=/root/tmp/rocksdb/third-party/jemalloc/output/include -DWITH_TBB=0 -DWITH_TESTS=0 -DWITH_BENCH=1 -DWITH_BENCHMARK_TOOLS=1 -DWITH_TOOLS=0 -DWITH_CORE_TOOLS=1 -DWITH_EXAMPLES=0 -DUSE_RTTI=1 -DFORCE_AVX2=1` ,but I have a few questions:
- I notified the Makefile in the root dir is useless. 
- there were no way to build `block_cache_trace_analyzer ` mentioned [here](https://github.com/facebook/rocksdb/wiki/Block-cache-analysis-and-simulation-tools)
- cmake have no way to open AVX2 for bloomfilter @[here](https://github.com/facebook/rocksdb/blob/2e09a54c4fb82e88bcaa3e7cfa8ccbbbbf3635d5/util/bloom_impl.h#L230)
- how to use `build_tools/build_detect_platform` ？

**Comment by mrambacher** [comment]
@dongdongwcpp  I will attempt to answer your questions.  
- The Makefile in the root directory is used to build via make itself and is not used by cmake at all.  Is that what you mean by "worthless"
- The build_tools/build_detect_platform is used by the Makefile in the root directory.  Its purpose is accomplished by many of the features that cmake has built into it.  Therefore, it is not needed if you are building via cmake.
- Looking at the cmake file, it appears that there is a compile check missing for AVX2.  Would you care to submit a PR to fix this issue?
- Looking at the cmake file, there are a few executables/tests that are not built by cmake.  I entered issue #8892 to track that issue.  I will attempt to look into that shortly.

**Comment by dongdongwcpp** [comment]
thanks for the reply, my mistake, my makefile in the root directory didn't work cause the encoding issue, fixed,I will try to submit a PR.

**Comment by ramvadiv** [comment]
@dongdongwcpp - closing out this issue.
