### ISSUE TITLE
GetUpdatesSince() is slow.

### ISSUE THREAD

**Issue by huachaohuang** [facebook/rocksdb#889]
Hi, I have some problem about `GetUpdatesSince()`.

The size of my Write Ahead Log file is about 512M, with a lot of small integer values.

I run a server based on rocksdb, and I have a slave server using `GetUpdatesSince()` to do incremental backups.
The slave server will keep trying to sync the latest changes from the master, so the master need to call `GetUpdatesSince()` very often.
The problem is, the implementation of `GetUpdatesSince()` will collect all Write Ahead Logs (archived and alive), read the first record of each WAL to get the start sequence, then use binary search to find the target WAL, and scan it from the beginning. With a large WAL (512M) with very small values, it will be very slow.

Actually, I just want to get the latest changes from the tail of the lastest WAL at most time, no reason to scan the WAL from the beginning every time.

That's it, forgive my broken english, any solution to this problem ?

**Comment by huachaohuang** [comment]
Finally, I solve this by reusing the `TransactionLogIterator` instead of creating a new one every time.

**Comment by wubbalubbaaa** [comment]
hi, I met the same problem.
can you explain more about how to reusing the TransactionLogIterator ? I think it's hard to reuse as the iterator makes a consitent view of db when created

**Comment by 1522140840** [comment]
> hi, I met the same problem. can you explain more about how to reusing the TransactionLogIterator ? I think it's hard to reuse as the iterator makes a consitent view of db when created

You can refer to this。

https://github.com/facebook/rocksdb/issues/12516

**Comment by wubbalubbaaa** [comment]
thx a lot , I've solved this problem by caching the former seq-to-file_offset in the TransactionLogIterator

**Comment by wubbalubbaaa** [comment]
> > hi, I met the same problem. can you explain more about how to reusing the TransactionLogIterator ? I think it's hard to reuse as the iterator makes a consitent view of db when created↳
> 
> You can refer to this。↳
> 
> #12516
thx a lot , I've solved this problem by caching the former seq-to-file_offset in the TransactionLogIterator
