### ISSUE TITLE
Questions about rocksdb tracing tool

### ISSUE THREAD

**Issue by wenhaocs** [facebook/rocksdb#8908]
Dear RocksDB developer,

I was searching for tracing tools of RocksDB, and found the following, is my understanding of the usage of each tracing tool correct?

tracing at query level(get, put, prefix, etc.) https://github.com/facebook/rocksdb/wiki/RocksDB-Trace,-Replay,-Analyzer,-and-Workload-Generation
tracing at block I/O level: https://github.com/facebook/rocksdb/wiki/IO-Tracer-and-Parser
tracing at rocksdb block cache level: https://github.com/facebook/rocksdb/wiki/Block-cache-analysis-and-simulation-tools

Apart from these, is there any other tracing tool or one stop tracing tool available?

Thanks!

**Comment by zhichao-cao** [comment]
@wenhaocs yes, those are the three tracing tools available at RocksDB now and you can follow the Wiki instructions to enable them. Note that, enabling the tracing function can bring in unexpected slowdown or even corruption risks. Please be aware of it when using them in production.
