### ISSUE TITLE
keep working on PrepareForBulkLoad mode in insert only workload

### ISSUE THREAD

**Issue by dongdongwcpp** [facebook/rocksdb#8909]
Dear developers:
        I have some questions and need some advises for the optimizes, many thanks for the help.
        The workload is insert only, the value is away 4k, this is for a backup system which 90% of the workload was writing, and there were no delete,no duplicate key, By using `Intel S4510 SSD`, I hope the speed can up to 200MB/s, here were some important options were set:
```
Options.table_cache_numshardbits: 6
Options.max_subcompactions: 1
Options.max_background_flushes: 10
Options.WAL_ttl_seconds: 0
Options.allow_concurrent_memtable_write: 1
Options.max_background_jobs: 2
Options.max_background_compactions: 8
Options.compression_opts.window_bits: -14
Options.compression_opts.level: -1
Options.compression_opts.strategy: 0
Options.compression_opts.max_dict_bytes: 0
Options.level0_file_num_compaction_trigger: 4
Options.level0_slowdown_writes_trigger: 20
Options.level0_stop_writes_trigger: 36
Options.target_file_size_base: 20971520
Options.target_file_size_multiplier: 1
Options.max_bytes_for_level_base: 268435456
Options.level_compaction_dynamic_level_bytes: 1
Options.max_bytes_for_level_multiplier: 10.000000
Options.rate_limiter: (nil)

  block_cache_options:
    capacity : 8388608
    num_shard_bits : 4
    strict_capacity_limit : 0
    high_pri_pool_ratio: 0.000
  block_cache_compressed: (nil)
  persistent_cache: (nil)
  block_size: 4096

```
I got some questions:
- the PrepareForBulkLoad mode works fine for the inserting, can I use [Options::PrepareForBulkLoad](https://github.com/facebook/rocksdb/blob/2e09a54c4fb82e88bcaa3e7cfa8ccbbbbf3635d5/options/options.cc#L418) mode for ever?
- by setting max_background_flushes thread to 10, but still got write stalling as show follow , how can I keep improving the speed？
```
2021/09/13-17:05:43.750853 7f3e91586700 [WARN] [/root/pika/third/rocksdb/db/column_family.cc:704] [default] Stalling writes because we have 21 level-0 files rate 10737417
2021/09/13-17:05:56.102181 7f3e99a92700 [WARN] [/root/pika/third/rocksdb/db/column_family.cc:704] [default] Stalling writes because we have 20 level-0 files rate 15032383
2021/09/13-17:06:01.001993 7f3e9bba7700 [WARN] [/root/pika/third/rocksdb/db/column_family.cc:704] [default] Stalling writes because we have 21 level-0 files rate 12025906
```
![image](https://user-images.githubusercontent.com/85050932/133055740-67f54e5b-7db3-4ae6-9843-a9ab4a9ac606.png)

**Comment by dongdongwcpp** [comment]
can we keep rocksdb work on PrepareForBulkLoad where workload was no delete nor duplicate key ? @ajkr

**Comment by jay-zhuang** [comment]
`Options::PrepareForBulkLoad` mode disables the auto-compaction and the user supposes to trigger manual compaction after all data is written. I won't recommend you using that forever (unless there's no read, or read only after manual compaction), but you can try increase for example:
`level0_slowdown_writes_trigger`, `level0_stop_writes_trigger`. Increase `write_buffer_size` may also help to buffer more write before flush.
As the write stall is because L0 file number, flush is not the bottleneck. Increase `max_background_flushes` won't help.

**Comment by dongdongwcpp** [comment]
thank you for replying , why read become so slow after using `PrepareForBulkLoad` even i have no duplicate key in L0? @jay-zhuang

**Comment by ajkr** [comment]
Do you enable Bloom filter? Without it, reads need to check all L0 files whose boundaries contain the lookup key.
