### ISSUE TITLE
Additional default merge operator 'byteappend'.

### ISSUE THREAD

**Issue by j-pb** [facebook/rocksdb#891]
It would be nice if RocksDB came with a default merge operator for appending bytes,
analogous to `stringappend`.

A common use case for a merge operation is simply storing additional values under that key.
At the same time many binary serialisation formats can read object collections when their byte-strings are simply concatenated (to support streaming applications).

`stringappend` almost handles this case, but always inserts a separating character ("," by default).
So introducing this would merely require a copy of `stringappend` with the line introducing the delimiter removed and the names updated.

I know that it seems trivial to implement this on an application level, however when using RocksJava, one has to jump through quite a few hoops to do this.

I'd be willing to create a patch for this.

Thanks :), JP

**Comment by dumbird** [comment]
+1

**Comment by adamretter** [comment]
@j-pb So you would propose something that stores the size of the bytes and then the bytes?

**Comment by yiwu-arbug** [comment]
You are welcome to send a PR..

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
