### ISSUE TITLE
Track per-SST user-defined timestamp information in MANIFEST

### ISSUE THREAD

**Issue by riversand963** [facebook/rocksdb#8957]
Internal ref: T86717089
We have been working on adding support for user-defined timestamp feature. Application can specify a timestamp when writing each key-value pair. Conceptually,
```
db->Put(key, value, timestamp);
```
Data written will first be buffered in memory in a data structure called MemTable, after a certain amount of time when certain conditions trigger, RocksDB flushes data from MemTable to files called SST files.
After writing SST files, RocksDB commits the file creation activity to the MANIFEST by calling `LogAndApply()`. We should also track timestamp information in the MANIFEST for each file.

Places to explore:
- `NewFileCustomTag`, defined in version_edit.h. Note that we require these new tags to be format-compatible.
- `VersionEdit::AddFile()`, `VersionEdit::DecodeFrom()`, `ToString()`, etc.
- `FileMetaData`.
- Unit tests in version_edit_test.cc, version_set_test.cc, etc.
- Verification of timestamp info during recovery (maybe) and other operations.

We follow Google C++ style guide (https://google.github.io/styleguide/cppguide.html).

**Comment by riversand963** [comment]
@wolfkdy @eharry

**Comment by wolfkdy** [comment]
@riversand963  ok, we'll try to privide a mr recently base on your advises, and discuss with the code.

**Comment by sunlike-Lipo** [comment]
@riversand963 I repost a new pull request for this issue.
Because the older pull request somehow closed automically after I re-push code.

**Comment by riversand963** [comment]
Turns out our internal linter is unhappy about putting `kDisableUserTimestamp` definition in dbformat.h. Can we declare it in dbformat.h and define it in dbformat.cc?

**Comment by riversand963** [comment]
PR merged.
