### ISSUE TITLE
Track each SST's timestamp information as user properties

### ISSUE THREAD

**Issue by riversand963** [facebook/rocksdb#8959]
(Internal ref: T86717137)
We have been working on adding support for user-defined timestamp feature. Application can specify a timestamp when writing each key-value pair.
Each SST files consist of multiple (potentially many) data blocks and several metadata blocks. Among the metadata blocks, there is one called Properties block that tracks some pre-defined properties of this SST file.
We should track timestamp-related information in each SST file's properties block, e.g. min and max timestamps of all keys in the file. Otherwise, the SST file is hardly self-contained: without timestamp info, it's hard to tell whether the keys in the SST have timestamps or not. (In fact, the timestamp info can also be inferred from Comparator, but Comparator info stored in the properties block is a string, thus it is more convenient just to store the timestamp info as well.)

A few places to consider
- When opening database, RocksDB allow application to pass a list of TablePropertiesCollector objects (a member of advanced column family options). Each of these collectors' methods will be invoked at certain points while building an SST file.
- utilities/table_properties_collectors contain a few example properties collectors. They collect information about the keys in the SST files while processing the keys.
- Maybe we should mandate such a user properties collector if application enables timestamp for a column family.

We can track these information in the properties blocks to enable additional validation.

We follow Google C++ style guide (https://google.github.io/styleguide/cppguide.html).

**Comment by riversand963** [comment]
@wolfkdy @eharry

**Comment by riversand963** [comment]
@wolfkdy @eharry  just want to clarify, would you be interested in this one? If you have not started, can I take this back and re-assign? If I understand correctly, #8957 can achieve the same purpose for you.

**Comment by eharry** [comment]
@riversand963 We are very willing to do this work. The development work has already begun. We will submit a patch for review this weekend.

**Comment by sunlike-Lipo** [comment]
@riversand963 I repost a  new pull request for this issue.
