### ISSUE TITLE
Continually-increasing memory usage

### ISSUE THREAD

**Issue by cpp77** [facebook/rocksdb#8969]
I'm using RocksDB to write data, not read (that's done by another process later).

I have 124x RocksDB databases and my total memory usage is increasing beyond 50GB. The total disk space of the underlying RocksDB directories is only 50GB. It seems like RocksDB is caching too much memory.

I am creating my database using the following options:

```
rocksdb::Options options;
options.compression = rocksdb::CompressionType::kZSTD;
options.create_if_missing = true;
options.create_missing_column_families = true;
```

Are there additional parameters I can set, for write-only, which take advantage I'm not doing any reads and therefore reduce memory usage? I still need decent write performance.

**Comment by mrambacher** [comment]
What version of RocksDB are you using?  I presume you are using the C++ interface?

How many column families are you using?  What are the cache settings?  Are the databases sharing a cache or is each database/column family using its own block cache?  

Does the memory continue to grow over time or is it a steady state?  If it grows, is it continual or growing in steps -- like when a compaction job happens?

It seems like disabling the block_cache might be good for a write-only database, but I am not sure if it will help or not.

**Comment by cpp77** [comment]
Thanks for responding:

- Version 6.17.3
- Yes, C++ interface
- I'm not creating any explicit columns. Just using `Put()` with a string key and a string value.
- I create 124x RocksDB databases. The data in each is independent/different data. It is not 124x instances of the same data.
- The memory continues to grow as more data arrives. If I graphed it, it would be a linear straight line.
- It grows continually. I was monitoring in htop and it would increment 0.1GB every 10-20 seconds.

I looked at `BlockBasedTableOptions` to set `block_size` to something large. I haven't tried this yet because I had no idea what to set for NewLRUCache.

I think I read somewhere about setting `cache_index_and_filter_blocks = true;` ?

Would you be able to give a sample options to use? I literally do no reads, I just write write write.

**Comment by akankshamahajan15** [comment]
You can refer this guide to tune the options https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ#configuration-and-tuning. As Mark mentioned disabling the block_cache  might help. Also what is the size of key-value pair. And how may sst files are generated and of what size. You can use https://github.com/facebook/rocksdb/wiki/Memory-usage-in-RocksDB to understand what is taking the memory.

**Comment by akankshamahajan15** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev
