### ISSUE TITLE
Please install gflags to run rocksdb tools

### ISSUE THREAD

**Issue by lcoon815** [facebook/rocksdb#8978]
Hi, 
I am new to RocksDB. I was trying to run ./benchmark.sh bulkload but encountered (standard_in) 1: synctax error. I saw the statement "Please install gflags to run rocksdb tools". 
I was following the steps here https://github.com/facebook/rocksdb/blob/main/INSTALL.md . I guess i was missing doing the step to include the path. I am sorry that I do not understand the instruction. Can someone here guide me how to do that?

Notice: Once installed, please add the include path for gflags to your CPATH environment variable and the lib path to LIBRARY_PATH. If installed with default settings, the include path will be /usr/local/include and the lib path will be /usr/local/lib.

**Comment by akankshamahajan15** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

**Comment by lcoon815** [comment]
The step to install the gflags.

Install gflags:

    git clone https://github.com/gflags/gflags.git
    cd gflags
    git checkout v2.0
    ./configure && make && sudo make install
Notice: Once installed, please add the include path for gflags to your CPATH environment variable and the lib path to LIBRARY_PATH. If installed with default settings, the include path will be /usr/local/include and the lib path will be /usr/local/lib.

How to add the include path and the lib path? Can you please guide me?

**Comment by akankshamahajan15** [comment]
These are the environment variables. https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html

**Comment by akankshamahajan15** [comment]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Closing this for now. Please post to https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev for more information
