### ISSUE TITLE
Make `DB::Close()` retry-able

### ISSUE THREAD

**Issue by jay-zhuang** [facebook/rocksdb#9029]
### Expected behavior
If `db->Close()` return non-ok status, calling `db->Close()` again should try to release the resource and Close again. If it fails to close again, a non-ok status should be returned.

### Actual behavior
`db->Close()` may throw seg fault exception.

It's because `DB::versions_` is released regardless of the return status in the first `Close()`:
https://github.com/facebook/rocksdb/blob/ae4ade5c8a25c730f03a2a750e50a7bef341121f/db/db_impl/db_impl.cc#L677
So the second second `Close()` is unable to do the cleanup.

### Steps to reproduce the behavior
```
  fault_injection_env->SetFilesystemActive(false);
  Status s = dbfull()->Close();
  ASSERT_NE(s, Status::OK());
  s = dbfull()->Close();
  ASSERT_NE(s, Status::OK()); // 
```

**Comment by ajkr** [comment]
@jay-zhuang Do you mind updating the issue now that #8970 landed?
