### ISSUE TITLE
rocksdbjni Not compiled with HDFS support is reported when HdfsEnv is used

### ISSUE THREAD

**Issue by collabH** [facebook/rocksdb#9067]
> Hi,guys,There is Not compiled with HDFS support when I use ROCKsdbjni HdfsEnv. How can I fix it? Thank you

### Expected behavior
* pom.xm
```xml
  <dependencies>
        <!-- https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni -->
        <!-- https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni -->
        <dependency>
            <groupId>org.rocksdb</groupId>
            <artifactId>rocksdbjni</artifactId>
            <version>6.22.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.hadoop</groupId>
            <artifactId>hadoop-client</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>
```
* code
```java
 public static final String HDFS_SST_PATH = "hdfs://hadoop:8082/rocksdb";
    public static final String HDFS_DATA_PATH = "/rocksdb/data";
    public static final String HDFS_LOG_PATH = "/rocksdb/log";
    public static final String HDFS_WAL_PATH = "/rocksdb/wal";

    public static void main(String[] args) throws RocksDBException {
        DBOptions dbOptions = new DBOptions();
        dbOptions.setWalDir(HDFS_WAL_PATH);
        dbOptions.setDbLogDir(HDFS_LOG_PATH);
        dbOptions.setCreateMissingColumnFamilies(true);
        dbOptions.setCreateIfMissing(true);
        dbOptions.setAllowConcurrentMemtableWrite(true);
        dbOptions.setSstFileManager(new SstFileManager(new HdfsEnv(HDFS_SST_PATH)));
        dbOptions.setEnv(new HdfsEnv("hdfs://hadoop:8082/"));
        List<ColumnFamilyDescriptor> columnFamilyDescriptors = Lists.newArrayList();
        columnFamilyDescriptors.add(new ColumnFamilyDescriptor(RocksDB.DEFAULT_COLUMN_FAMILY));
        ColumnFamilyOptions columnFamilyOptions = new ColumnFamilyOptions();
        columnFamilyOptions.setLevelCompactionDynamicLevelBytes(true);
        BlockBasedTableConfig blockBasedTableConfig = new BlockBasedTableConfig();
        blockBasedTableConfig.setFilterPolicy(new BloomFilter());
        blockBasedTableConfig.setBlockCache(new LRUCache(2000));
        blockBasedTableConfig.setEnableIndexCompression(true);
        columnFamilyOptions.setTableFormatConfig(blockBasedTableConfig);
        columnFamilyOptions.setCompactionThreadLimiter(new ConcurrentTaskLimiterImpl("compaction-thread", 4));
        columnFamilyDescriptors.add(new ColumnFamilyDescriptor("user".getBytes(), columnFamilyOptions));
        List<ColumnFamilyHandle> columnFamilyHandles = Lists.newArrayList();
        RocksDB db = RocksDB.open(dbOptions, HDFS_DATA_PATH, columnFamilyDescriptors, columnFamilyHandles);
        ColumnFamilyHandle userCf = columnFamilyHandles.get(1);
        /**
         * create
         */

        // put
        db.put(userCf, "name".getBytes(), "huangsm".getBytes());

        for (ColumnFamilyHandle columnFamilyHandle : columnFamilyHandles) {
            columnFamilyHandle.getDescriptor().getOptions().close();
        }
        dbOptions.close();
        db.close();
    }
```
* error log
```txt
Exception in thread "main" org.rocksdb.RocksDBException: Not compiled with hdfs support
	at org.rocksdb.HdfsEnv.createHdfsEnv(Native Method)
	at org.rocksdb.HdfsEnv.<init>(HdfsEnv.java:22)
	at org.rocksdb.baseoperator.curd.RocksDBBestPractice.main(RocksDBBestPractice.java:43)
```
### Actual behavior
> I think open DB should be a success

**Comment by manishrawat1992** [comment]
Hi collabH, 
Please compile rocksDB from source code 
1. export USE_HDFS=1
2. export DEBUG_LEVEL=0
3.  make -j8 rocksdbjava

**Comment by adamretter** [comment]
@collabH The public binary releases of RocksJava do not include HDFS support. We could potentially look at including it into the public releases, however we would first have to make sure that it is supported and possible on all CPU architectures and OS that we support.
In the mean-time you can build RocksJava from source code for your platform with HDFS support as indicated by @manishrawat1992 

@riversand963 Do you have a feeling whether this should be in the standard public release? To me HDFS seems more like an optional extension?

**Comment by collabH** [comment]
> Hi collabH, Please compile rocksDB from source code
> 
> 1. export USE_HDFS=1
> 2. export DEBUG_LEVEL=0
> 3. make -j8 rocksdbjava

**Comment by riversand963** [comment]
@adamretter I share the same feeling with you, but the addition of the HDFS stuff in RocksDB main repo predates me. Furthermore, I do not have a sense of how thoroughly RocksDB is tested on HDFS either. According to Git history, there has been no contribution to hdfs support for quite some time. Given that HDFS may have already evolved a lot, I wonder whether we should keep it. This is just my personal feeling, and will need to discuss with the team.

**Comment by adamretter** [comment]
> I do not have a sense of how thoroughly RocksDB is tested on HDFS either

It isn't anything that I have every tested yet as part of our RocksJava work and issues.

**Comment by riversand963** [comment]
@adamretter, as a follow-up, I have created #9159. Let me know if you would like to help.

**Comment by mrambacher** [comment]
@riversand963 I am interested in making HDFS a plugin, but think it needs some work (for Customizable) before it will easily work.  You can assign the task to me if you want.  One issue is that I am not sure how to test that I did not break anything...

**Comment by manishrawat1992** [comment]
@mrambacher Is it possible to include HDFS support inside rocksdb-cloud using storage_provider interface.

**Comment by mrambacher** [comment]
@manishrawat1992 Inside of RocksDB Cloud is a different issue requiring more coordination between the two forks/branches.  However, making an "HDFSFileSystem" and have it loaded as a plugin is fairly straightforward work.

**Comment by riversand963** [comment]
Thanks @mrambacher for volunteering.
I hope we can start the migration now with as little dependency as possible, so that when we officially remove hdfs-related code from main repo in the near future, we will have it ready for use in another plug-in repo. If this depends on some new feature not checked in yet, then it will add another blocking item for the new release (next, or the one after next, maybe). Furthermore, we should add some code comments or logging to warn people of the upcoming change, as what we do in #9091.
Does this make sense?

**Comment by mrambacher** [comment]
@riversand963 Has anyone attempted the current approach for Java?  I believe you will need to use the Customizable infrastructure to get what you want, which has not been added to Java at this time.  Alternatively, the plugin code will have to have Java/JNI classes to access the functionality (e.g. how would one go about creating a HDFSEnv in Java?)

**Comment by riversand963** [comment]
@mrambacher I think there may have been some confusion on my part.

> You can assign the task to me if you want

When I saw this, I had just finished creating #9159, thus I was under the impression (by mistake) that you would like to claim #9159. My entire argument about preventing dependency and not blocking new release was based on #9159, which is an item we want to finish for RocksDB 7.0
