### ISSUE TITLE
Concurrency bug in ClockCache

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#9075]
From https://github.com/facebook/rocksdb/pull/8261#issuecomment-832247624:

Unfortunately, there is at least one more bug in ClockCache that shows up in the crash test:

    ***db_stress: cache/clock_cache.cc:486: bool rocksdb::{anonymous}::ClockCacheShard::Unref(rocksdb::{anonymous}::CacheHandle*, bool, rocksdb::{anonymous}::CleanupContext*): Assertion `CountRefs(flags) > 0' failed.***

I tried a few possible fixes, but none worked.

**Comment by mpoeter** [comment]
I don't think the race described in https://github.com/facebook/rocksdb/pull/8261#issuecomment-832262226 is possible
```
[thread 1] Lookup starts, up to Ref()
[thread 2] Erase/evict the entry just looked up
[thread 1] Ref() the handle, even though it's in the recycle bin
[thread 2] Insert with recycling that handle, handle->flags.store obliterates the other thread's Ref
```
`Ref()` only attempts the CAS if the `kInCacheBit` is set, but erase/evict clear that flag. So either the `Ref()` must fail, or the erase/evict cannot recycle the entry. I added additional assertions in insert that fore the recycled entry `InCache(flags) == false && CountRef(flags)`. But so far I was not able to trigger any of those assertions.

**Comment by jiguanglizipao** [comment]
Is there any update about this bug?

**Comment by pdillinger** [comment]
Old implementation with this bug has been deleted. HyperClockCache is now available as a much faster alternative (see API comments for caveats). I still need to update wiki and write blog post.
