### ISSUE TITLE
Feature Request: schedule concurrent compaction jobs for manual compaction

### ISSUE THREAD

**Issue by qqnidaye** [facebook/rocksdb#9082]
I have with 8T data on a big machine with 256-core and 1T ram, I want to run a manual compation as fast as possible.

I know sub compactions, I also know a manual compaction is divided into many CompactionJob, and these CompactionJob are run sequentially.

I have tried sub compact(=100), but it is less helpful as expected, and it generates small sst files.

I have also submitted an related issue #7915(closed).

**Comment by ajkr** [comment]
Let us know if it doesn't work. Right now subcompaction is the parallelization mechanism for manual compactions.

**Comment by rockeet** [comment]
I found this feature is very valuable to us also, because we use shared distributed file system and offload compactions to dedicated cluster, so file system bandwidth and computation resources are not bottle necks, we can submit compaction jobs concurrently as many as possible.

**Comment by guoxiangCN** [comment]
Maybe Concurrent Manual compaction can be controlled by a config ? It's useful in some biz testcases.
