### ISSUE TITLE
Snappy used in database with binary that did not support Snappy and never had Snappy support enabled

### ISSUE THREAD

**Issue by awused** [facebook/rocksdb#9127]
When using rust-rocksdb compiled without Snappy with no compression level set, but eventually the database failed to open with the same binary that created it because Snappy wasn't supported. This was the only binary to ever interact with the database in primary mode, and while I did open it in secondary mode with another binary that binary was also built without Snappy and with only LZ4 enabled. I have never built or installed RocksDB with Snappy enabled, and this database was only from a few hours ago so I can't have missed anything.

### Expected behavior

Snappy shouldn't be used when support isn't enabled and it hasn't been specified.

### Actual behavior

I compiled rust-rocksdb with `default-features = false and features = [ "LZ4" ]`. This is how I'd specified it even before the first build, so there was no opportunity for a binary supporting Snappy to have ever been created. I initialized a database with no compression level set (because I forgot to set LZ4). The database functioned as normal for some time but eventually, when I restarted the process (using the exact same binary used to create the database in the first place), the database failed to open with the error:
```
2021/11/04-03:24:20.895084 7fbbaffff640 [ERROR] [table/block_based/block_based_table_reader.cc:1154] Encountered error while reading data from properties block Corruption: Unsupported compression method or corrupted compressed block contents: Snappy
```

### Steps to reproduce the behavior

It just seems to take some time, but I don't have exact numbers since I haven't looked into it in depth. I've yet to reproduce it now that I'm explicitly setting compression to LZ4, but I don't know if enough time has passed.

I've attached the LOG from a newly created database with the known-bad binary. [LOG-new-from-same-binary.txt](https://github.com/facebook/rocksdb/files/7474183/LOG-new-from-same-binary.txt)

Notably I see that Snappy compression is, correctly, not supported, and NoCompression was chosen, but index compression is somehow enabled even though I failed to specify any compression level. I don't know if that's significant or a red herring.
```
2021/11/04-03:40:47.217976 7fac2aacec00 	kSnappyCompression supported: 0

  enable_index_compression: 1

2021/11/04-03:40:47.237941 7fac2aacec00          Options.compression: NoCompression
```

**Comment by mrambacher** [comment]
I do not see that error in the log file.  When it occurs, can you do an sst_dump on the SST file that appears to be corrupted and report its settings (e.g. does it say that it is using Snappy Compression)?

Narrowing down to see if the file itself is somehow corrupted (by sst_dump) will help to isolate if the problem is in the RocksDB layer or in the Rust bindings (I am suspecting the latter).

**Comment by awused** [comment]
The logs were from a new database from the affected binary. But now I don't think it was a RocksDB bug at all, though I cannot explain what happened.

I was using the same directory path for a leveldb database up until a few hours ago when I removed it, killed the process that was using it, removed the old database, and started the new RocksDB application which created a fresh database. This functioned fine for a few hours until something mysteriously overwrote the RocksDB database with a new, empty, leveldb database. I can see it in my file system snapshots and I honestly cannot explain it, even stepping through my shell history. But whatever it is it doesn't appear to be a RocksDB bug.

Thanks for the fast response, but I guess this was user error. Sorry about wasting your time, I thought I'd checked everything twice before sending the bug report but I guess I failed.

**Comment by awused** [comment]
The logs in earlier file system snapshots make it seem like RocksDB was able to make use of the leveldb database for several hours, apparently without errors, until I happened to restart the process and it tried to read Snappy blocks that were possibly not even really compressed with Snappy. I'd share the database itself at least as a curiosity but some of the information is private.
