### ISSUE TITLE
rocksdb.number.keys.read always 0 in statistics

### ISSUE THREAD

**Issue by caipengbo** [facebook/rocksdb#9137]
When I call Get interface in Rocksdb(v6.25.3), I found the `rocksdb.number.keys.read` statistic always 0.

My usage is: `statistics.getTickerCount(rocksdb::Tickers::NUMBER_KEYS_READ));`

**Comment by jay-zhuang** [comment]
can you provide a testcase for that?
I just wrote a simple test, which works fine:
https://github.com/jay-zhuang/rocksdb/blob/12095f30d450c838e4e711b4fcba53910332f272/db/db_basic_test.cc#L2088-L2092

Closing the issue for now, please feel free to re-open.
