### ISSUE TITLE
[Question] What different between ExternalSstFileIngestionJob and ImportColumnFamilyJob

### ISSUE THREAD

**Issue by darionyaphet** [facebook/rocksdb#9161]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

Hi here is a question, What different between ExternalSstFileIngestionJob and ImportColumnFamilyJob? They look a little alike.

**Comment by pdillinger** [comment]
Someone committed a grievous case of the sin of copy-paste. They serve deeply related but distinct APIs, one creating a new column family and one adding to existing column families.
