### ISSUE TITLE
IO error: IO error: While mmap read offset 211319992 larger than file length 42612255 when I user mmap and blob

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#9167]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Succeeded to read data
### Actual behavior
IO error: IO error: While mmap read offset 211319992 larger than file length 42612255 when I user mmap and blob

### Steps to reproduce the behavior
I use rocksdb 5.11.3. I open mmap read and use blob, then I get error 'IO error: IO error: While mmap read offset 211319992 larger than file length 42612255'

**Comment by ltamasi** [comment]
RocksDB 5.11.3 is almost 4 years old and contains an early non-production ready version of the old/`StackableDB` based BlobDB implementation. Could you please check if this is still an issue on mainline?

**Comment by ltamasi** [comment]
Closing for now, please feel free to reopen if this is still an issue with the latest version.

**Comment by GOGOYAO** [comment]
> RocksDB 5.11.3 is almost 4 years old and contains an early non-production ready version of the old/`StackableDB` based BlobDB implementation. Could you please check if this is still an issue on mainline?

we will try it
