### ISSUE TITLE
[Question] Db Snapshot on checkpoint

### ISSUE THREAD

**Issue by itsmeakashgoyal** [facebook/rocksdb#9182]
Hello folks!

I have a question regarding the creation of db snapshot on specific checkpoint using hard-link http://rocksdb.org/blog/2015/11/10/use-checkpoints-for-efficient-snapshots.html#:~:text=The%20Checkpoint%20feature%20enables%20RocksDB,CURRENT%20files%20will%20be%20copied.

When I am creating a db snapshot of rocksdb sst files on specific checkpoint, a directory is created in the same directory and hard-link created to each files.
But when I am creating a backup on different directory say outside to the original directory where sst files are present, then no hard-link were created.

Application running container and rocksdbdata mounted on host machine directory. Can we create checkpoint on different mount point with hard-links?

Can anyone help me if this is the exact behaviour of creating a snapshot. That we can only get hard-links inside the same directory not any other directory which is not inside the backup directory?

**Comment by ajkr** [comment]
> Application running container and rocksdbdata mounted on host machine directory. Can we create checkpoint on different mount point with hard-links?
>
> Can anyone help me if this is the exact behaviour of creating a snapshot. That we can only get hard-links inside the same directory not any other directory which is not inside the backup directory?

Different directories on the same mount point, yes. Different directories on different mount points, no, because Linux doesn't allow it:

```
$ man 2 link
...
EXDEV  oldpath and newpath are not on the same mounted filesystem.  (Linux permits a filesystem to be mounted at multiple points, but link() does not work across different mount points, even if the same filesystem is mounted on both.)
```
