### ISSUE TITLE
The LRUCache::DisownData() drops data in case code is compiled with ASAN

### ISSUE THREAD

**Issue by oleksandr-kachan** [facebook/rocksdb#9183]
It looks like MUST_FREE_HEAP_ALLOCATIONS is not properly defined in scope of `cache/lru_cache.cc`. As a result ASAN leak warnings suppression doesn't work as expected. The issue seem to be caused by changes in https://github.com/facebook/rocksdb/commit/311a544c2aa513a1f9b33823996f6b3e7843b6c5.

The `ClockCache::DisownData()` should be affected as well.

**Comment by siying** [comment]
I assume you mean running ASAN with your program, rather than RocksDB unit tests? We don't observe it in RocksDB unit tests' ASAN run. If you have a proper fix, feel free to submit it.

**Comment by pdillinger** [comment]
We don't call DisownData in unit tests, only db_bench
