### ISSUE TITLE
Some problems while compiling rocksdbjava with USE_HDFS=1

### ISSUE THREAD

**Issue by Sakura1007** [facebook/rocksdb#9197]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
expect rocksdbjni-***.jar will be in /java/target

### Actual behavior
JAVA_CGLIB_SHA256_ACTUAL=`openssl sha256 -r test-libs/cglib-3.3.0.jar | cut -d ' ' -f 1`; \
if [ "9fe0c26d7464140ccdfe019ac687be1fb906122b508ab54beb810db0f09a9212" != "$JAVA_CGLIB_SHA256_ACTUAL" ]; then \
	echo test-libs/cglib-3.3.0.jar checksum mismatch, expected=\"9fe0c26d7464140ccdfe019ac687be1fb906122b508ab54beb810db0f09a9212\" actual=\"$JAVA_CGLIB_SHA256_ACTUAL\"; \
	exit 1; \
fi
  9  9 5 52 8 3 7 1362k20 25 kk   9  9    5 023  7  2 6k 2  9 0k      06  9  30 3  7    0       04  1 5 007 7 0 01 :3 05100  373k  100  373k    0     0  41626      0  0:00:09  0:00:09 --:--:-- 565169:00:0050::0086  7766916680
JAVA_JUNIT_SHA256_ACTUAL=`openssl sha256 -r test-libs/junit-4.13.1.jar | cut -d ' ' -f 1`; \
if [ "c30719db974d6452793fe191b3638a5777005485bae145924044530ffa5f6122" != "$JAVA_JUNIT_SHA256_ACTUAL" ]; then \
	echo test-libs/junit-4.13.1.jar checksum mismatch, expected=\"c30719db974d6452793fe191b3638a5777005485bae145924044530ffa5f6122\" actual=\"$JAVA_JUNIT_SHA256_ACTUAL\"; \
	exit 1; \
fi
  6692  11027005kk      696 2  7 417k4 9 k    0    0      0    07 4 174409 5 5        0    00:00:14  0 :00 :01:00 0 :01: 72 1205k  8 0  721 07 08k6 8 k  8 0    0860k    0        0    0 7 87087831 3          0  0  0 :00:00:01:41 5  0 :000:11100 1070k  100 1070k    0     0  86157      0  0:00:12  0:00:12 --:--:--  113k    0  0:00:14  0:00:12  0:00:02  102k
JAVA_ASSERTJ_SHA256_ACTUAL=`openssl sha256 -r test-libs/assertj-core-2.9.0.jar | cut -d ' ' -f 1`; \
if [ "5e88ea3ecbe3c48aa1346fec76c84979fa9c8d22499f11479011691230e8babf" != "$JAVA_ASSERTJ_SHA256_ACTUAL" ]; then \
	echo test-libs/assertj-core-2.9.0.jar checksum mismatch, expected=\"5e88ea3ecbe3c48aa1346fec76c84979fa9c8d22499f11479011691230e8babf\" actual=\"$JAVA_ASSERTJ_SHA256_ACTUAL\"; \
	exit 1; \
fi
100 1205k  100 1205k    0     0  87564      0  0:00:14  0:00:14 --:--:--  117k
JAVA_MOCKITO_SHA256_ACTUAL=`openssl sha256 -r test-libs/mockito-all-1.10.19.jar | cut -d ' ' -f 1`; \
if [ "d1a7a7ef14b3db5c0fc3e0a63a81b374b510afe85add9f7984b97911f4c70605" != "$JAVA_MOCKITO_SHA256_ACTUAL" ]; then \
	echo test-libs/mockito-all-1.10.19.jar checksum mismatch, expected=\"d1a7a7ef14b3db5c0fc3e0a63a81b374b510afe85add9f7984b97911f4c70605\" actual=\"$JAVA_MOCKITO_SHA256_ACTUAL\"; \
	exit 1; \
fi
mkdir -p target/test-classes
javac -source 7 -cp target/classes:test-libs/junit-4.13.1.jar:test-libs/hamcrest-2.2.jar:test-libs/mockito-all-1.10.19.jar:test-libs/cglib-3.3.0.jar:test-libs/assertj-core-2.9.0.jar -h ./include -d target/test-classes\
	src/test/java/org/rocksdb/test/*.java\
	src/test/java/org/rocksdb/util/*.java\
	src/test/java/org/rocksdb/*.java
警告: [options] 未与 -source 1.7 一起设置引导类路径
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
1 个警告
gmake[1]: Leaving directory '/Users/junjiehu/Desktop/rocksdb/java'
ld: warning: directory not found for option '-L/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/jre/lib/amd64'
ld: warning: directory not found for option '-L/Library/Java/JavaVirtualMachines/jdk1.8.0_221.jdk/Contents/Home/jre/lib/amd64/server'
ld: warning: directory not found for option '-L/lib'
ld: library not found for -lverify
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:2230: rocksdbjava] Error 1

### Steps to reproduce the behavior
1. get rocksdb-master from github
2. cd to dir
3. export USE_HDFS=1
4. export DEBUG_LEVEL=0
5. make -j8 rocksdbjava
6. BTW:
java -version: 1.8.0_221
make --version: 4.3
cmake --version: 3.21.3
gcc --version: 5.5.0
OS: macOS Monterey 12.0.1
And, if not set USE_HDFS=1, it can be compiled successfully.

**Comment by riversand963** [comment]
I am not aware of anybody testing this on Mac, and I myself have tested only on CentOS. In fact, we are planning to migrate HDFS support to a separate repo starting from RocksDB 7.0 (see #9159 and ongoing effort #9170). Will post about this in user group and mail list.
