### ISSUE TITLE
Tuning rocksdb parameters in large memory scenarios

### ISSUE THREAD

**Issue by carryxyh** [facebook/rocksdb#9218]
Currently I can allocate 12G memory usage for rocksdb. In this case, my current parameters are:

```
max_background_compactions/max_background_flushes or setIncreaseParallelism: 8
block_cache_size: 6144M
writebuffer.size: 256M
max_write_buffer_number: 20
block.blocksize: 32K
min_write_buffer_number_to_merge: 1
```

In this mode, serious write blocking will still occur. A lot of cpu is spent on compaction and put. Any suggestions?

**Comment by carryxyh** [comment]
Anyone here?

**Comment by flyingsilverfin** [comment]
You should read the performance tuning guides at https://github.com/facebook/rocksdb/wiki/Setup-Options-and-Basic-Tuning and https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide

In general you should be able to find a configuration that has good throughput. You could for instance allow more write buffers to accumulate if you're not doing read/write mix loads too much (unsorted data = more expensive reads). You should also match the L1 size to L0, which you're affecting by changing the write buffer size. Hopefully that helps you get started.

**Comment by carryxyh** [comment]
`You should also match the L1 size to L0`

Thank you for your reminder, I found similar information in the document. I will try it. If there are still problems, I will reopen it. :)
