### ISSUE TITLE
[Timestamp|Discussion] Weird behavior when Timestamped Del combined with CompactionFilter

### ISSUE THREAD

**Issue by wolfkdy** [facebook/rocksdb#9223]
@riversand963 
### Expected behavior
full_history_ts_low: 3
data history: (put k1, v1, ts=2), (put k1, v2, ts=4), (del k1, ts=5), (put k1, v3, ts=6)
compactionFilter behavior: remove every kv with timestamp >= full_history_ts_low

After compaction with the specified filter, the data history should left (put k1, v1, ts=2) and a timestamped read with readTs = 7 should see (put k1, v1, ts=2) tuple

### Actual behavior
A timestamped read with readTs = 7 cannot see (put k1, v1, ts=2) tuple
That's because the (del k1, ts=5) timestamped delete won't be passed into the filter to get a kRemove Decision, as we've already discuss in https://github.com/facebook/rocksdb/issues/8770

As timestamp is provided by users, it's better for users have all privilege to determine the existence of a kv with ts >= full_history_ts_low, so should we pass all kinds of keys with ts >= full_history_ts_low to filters?

### Steps to reproduce the behavior
see the below unittest
```
namespace {
class NotKeepFilter: public CompactionFilter {
 public:
  Decision FilterV2(int /*level*/, const Slice& /*key*/, ValueType /*value_type*/,
                    const Slice& existing_value, std::string* /*new_value*/,
                    std::string* /*skip_until*/) const override {
    std::cout << "here called " << existing_value.ToString() << "\n";
    if (existing_value.ToString() == "v1") {
      return Decision::kKeep;
    }
    return Decision::kRemove;
  }

  bool IgnoreSnapshots() const override { return true; }

  const char* Name() const override { return "NotKeepFilter"; }
};

class NotKeepFilterFactory: public CompactionFilterFactory {
 public:
  std::unique_ptr<CompactionFilter> CreateCompactionFilter(
      const CompactionFilter::Context& /*context*/) override {
    return std::unique_ptr<CompactionFilter>(new NotKeepFilter());
  }
  const char* Name() const override { return "NotKeepFilterFactory"; }
};
}
TEST_F(DBBasicTestWithTimestamp, GcPreserveLatestVersionBelowFullHistoryLowWithFilter) {
  Options options = CurrentOptions();
  options.env = env_;
  options.compaction_filter_factory = std::make_shared<NotKeepFilterFactory>();
  options.create_if_missing = true;
  const size_t kTimestampSize = Timestamp(0, 0).size();
  TestComparator test_cmp(kTimestampSize);
  options.comparator = &test_cmp;
  DestroyAndReopen(options);

  std::string ts_str = Timestamp(2, 0);
  WriteOptions wopts;
  Slice ts = ts_str;
  wopts.timestamp = &ts; 
  ASSERT_OK(db_->Put(wopts, "k1", "v1"));
  ts_str = Timestamp(4, 0);
  ts = ts_str;
  wopts.timestamp = &ts; 
  ASSERT_OK(db_->Put(wopts, "k1", "v2"));
  ts_str = Timestamp(5, 0);
  ts = ts_str;
  wopts.timestamp = &ts; 
  ASSERT_OK(db_->Delete(wopts, "k1"));
  ts_str = Timestamp(6, 0);
  ts = ts_str;
  wopts.timestamp = &ts; 
  ASSERT_OK(db_->Put(wopts, "k1", "v3"));

  ts_str = Timestamp(3, 0);
  ts = ts_str;
  CompactRangeOptions cro; 
  cro.full_history_ts_low = &ts; 
  ASSERT_OK(Flush());
  ASSERT_OK(db_->CompactRange(cro, nullptr, nullptr));

  ReadOptions ropts;
  ts_str = Timestamp(2, 0);
  ts = ts_str;
  ropts.timestamp = &ts;
  std::string value;
  Status s = db_->Get(ropts, "k1", &value);
  ASSERT_OK(s);
  ASSERT_EQ("v1", value);

  ts_str = Timestamp(7, 0);
  ts = ts_str;
  ropts.timestamp = &ts;
  s = db_->Get(ropts, "k1", &value); 
  ASSERT_OK(s); // here asserts, read with ts=7 won't see (k1, v1)
  ASSERT_EQ("v1", value);

  Close();
}
```

**Comment by riversand963** [comment]
Right, compaction filter currently does not process tombstones.
Will think about it more. I will be on leave from later this week to mid December.

Is this a follow-up regarding trimming most recent history?

**Comment by wolfkdy** [comment]
Yes, I think compaction filter is the most close approach torwards trimming most recent history.

**Comment by riversand963** [comment]
How about a new `InternalIterator` which can be the "root" of the iterator tree when generating compaction output?
This does not unnecessarily complicate `CompactionIterator` code which is already very complex, nor does it have to change the assumption of `CompactionFilter`.

**Comment by wolfkdy** [comment]
If so, the new `InternalIterator` may have quite a lot of duplicated code pieces as the `CompactionIterator`, and because the task generates new sst files and remove old ones, the new mechanism should rely on the `CompactionJob` subsystem, so a new kind of CompactionJob should be defined.

I found that the `BlobDB` has already broken the two rules CompactionFilter ever followed as the below code piece
1. `CompactionFilter only processes Put`, 
2. `CompactionFilter provides Userkey as Filter's parameter`
```
bool CompactionIterator::InvokeFilterIfNeeded() {
  if (!compaction_filter_ ||
      (ikey_.type != kTypeValue && ikey_.type != kTypeBlobIndex)) {
    return true;
  }
  Slice& filter_key =
      (ikey_.type == kTypeValue ||
       !compaction_filter_->IsStackedBlobDbInternalCompactionFilter())
          ? ikey_.user_key
          : key_;
}
```
With the existing mechanism, I think we can fulfill this by just adding less than five lines of code to `bool CompactionIterator::InvokeFilterIfNeeded`

```
bool CompactionIterator::InvokeFilterIfNeeded(bool* need_skip,
                                              Slice* skip_until) {
  if (!compaction_filter_ ||
      (ikey_.type != kTypeValue && ikey_.type != kTypeBlobIndex && ikey_.type != kTimestampedDelete)) {
    return true;
  }
  Slice& filter_key = (timestamp_size_ > 0 ? key_ : ikey_.user_key);

```

**Comment by riversand963** [comment]
Sorry for the delay. Will resume the discussion later this week or early next.

**Comment by riversand963** [comment]
> I found that the BlobDB has already broken the two rules CompactionFilter ever followed as the below code piece

I think BlobDB is kind of special here. BlobIndex is semantically more similar to a Put than tombstones: it's just an indirection to Put. That's why changing the behavior of compaction filter invoking for blob index is less of a concern. For tombstones, if we change the restriction, we need to think really hard about possible unexpected behaviors.

We should re-use the `CompactionJob` vehicle for history trimming and GC. `CompactionIterator` has a `InternalIterator*`. What I proposed is implementing a new iterator, e.g. `HistoryTrimmingIterator : public InternalIterator`. When building the compaction iterator, we create the iterator tree as before, except we put a `HistroyTrimingIterator` as the root and pass it to `CompactionIterator`. 
In `HistoryTrimmingIterator` methods, it will be a wrapper around the underlying `InternalITerator` such that keys whose timestamps newer than a certain threshold should not be returned to the compaction iterator.

I admit this approach is more complex.

**Comment by wolfkdy** [comment]
@riversand963  thanks for your suggestion, I've got your point, recently we'll try to provide a demo as what you described above.

**Comment by riversand963** [comment]
@wolfkdy please correct me if I am wrong: the trim history functionality will only be needed when you recover a crashed leader and demote it to follower?

**Comment by wolfkdy** [comment]
@riversand963 yes, you are right, this functionality  is only needed when a leader crashes(or been killed, or been manually demoted) and becomes a follower.

**Comment by sunlike-Lipo** [comment]
@riversand963 
I wrote a demo (https://github.com/eharry/rocksdb/commit/7b17266e25409f9c3507f16ef0375b044208a5a7) about  the HistoryTrimmingIterator. 
Could you take a look when you're not busy? Please let me know if it did not go to the wrong way than you expected.

**Comment by riversand963** [comment]
Thanks @sunlike-Lipo, will take a look and get back to you.

**Comment by sunlike-Lipo** [comment]
> Thanks @sunlike-Lipo, will take a look and get back to you.
Very sorry to bother you, but have you reviewed the demo recently?
If it is implemented in the way that you expected, I will open a pull request for a formal review.

**Comment by riversand963** [comment]
@sunlike-Lipo Sorry for the delay.
After reviewing at high level, I think the idea of creating a new InternalIterator is what I have suggested. Feel free to create a PR and we can continue from there.
According to our prior discussion, it would be nice to make sure history trimming happens at db instance recovery. Otherwise, it would be more complex to reason about possibly concurrent compactions/flushes.

**Comment by sunlike-Lipo** [comment]
@riversand963 
I create a PR https://github.com/facebook/rocksdb/pull/9410. Please take a review when you are not busy.
Thanks a lot.

**Comment by riversand963** [comment]
Closing after #9410 is merged.
