### ISSUE TITLE
Typo/not-easy-to-understand wiki of kBinarySearchWithFirstKey

### ISSUE THREAD

**Issue by XinyuZeng** [facebook/rocksdb#9261]
In wiki page: https://github.com/facebook/rocksdb/wiki/Index-Block-Format#:~:text=For%20example%2C%20when%20data%20block%20usually%20occupy%20the%20whole%20data%20block

The example given is not clear when saying data block occupy itself. Probably a more concrete example like the one in the initial PR of this feature:#5289 can be included in the wiki to help readers better understand the scenario.

**Comment by ltamasi** [comment]
Thanks for reporting @XinyuZeng ! I've updated the wiki.
