### ISSUE TITLE
SIGSEV during iterator seek from Java

### ISSUE THREAD

**Issue by flyingsilverfin** [facebook/rocksdb#9262]
### Expected behavior
`seek()`  on an iterator in an Optimistic Transaction DB with snapshotting consistently works. We are using Snapshotting with the optimistic transaction DB.

### Actual behavior
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f630fbc8dcc, pid=11068, tid=13236
#
# JRE version: OpenJDK Runtime Environment (11.0.11+9) (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [librocksdbjni3729440934318541011.so+0x775dcc]  rocksdb::WBWIIteratorImpl::Entry() const+0x5c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /home/joshua/typedb-all-linux-partitioned/core.11068)
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Host: Intel(R) Xeon(R) CPU @ 2.20GHz, 32 cores, 62G, Ubuntu 18.04.5 LTS
Time: Tue Dec  7 16:43:48 2021 UTC elapsed time: 8365.451956 seconds (0d 2h 19m 25s)

---------------  T H R E A D  ---------------

Current thread (0x00007f602804b000):  JavaThread "async-2::0" [_thread_in_native, id=13236, stack(0x00007f6194149000,0x00007f619424a000)]

Stack: [0x00007f6194149000,0x00007f619424a000],  sp=0x00007f61942482d0,  free space=1020k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni3729440934318541011.so+0x775dcc]  rocksdb::WBWIIteratorImpl::Entry() const+0x5c
C  [librocksdbjni3729440934318541011.so+0x776b6d]  rocksdb::BaseDeltaIterator::UpdateCurrent()+0x17d
C  [librocksdbjni3729440934318541011.so+0x776f2d]  rocksdb::BaseDeltaIterator::Seek(rocksdb::Slice const&)+0x7d
C  [librocksdbjni3729440934318541011.so+0x258348]  Java_org_rocksdb_RocksIterator_seek0+0x48
J 2843  org.rocksdb.RocksIterator.seek0(J[BI)V (0 bytes) @ 0x00007f63805a2b15 [0x00007f63805a2a40+0x00000000000000d5]
...
```

### Steps to reproduce the behavior

Unfortunately this does not happen determinstically and is really quite rare. I'm hoping that someone can look at this stack trace
and get an idea of what _might_ be going wrong? Maybe we're doing something wrong from our side.

**Comment by hx235** [comment]
Hi @flyingsilverfin, there could be many things leading to a segmentation fault exists in `rocksdb::WBWIIteratorImpl::Entry()`. Can you expand a bit into "seek() on an iterator in an Optimistic Transaction DB with snapshotting consistently works.", preferably with some code snippet to illustrate the context of of this stack trace leading to the SIGSEV if it's okay to do so?

Also, what's the version of RocksJava you are using?

Thanks!

**Comment by hx235** [comment]
Hi @flyingsilverfin, could you translate the `0x775dcc` in `Problematic frame:
# C  [librocksdbjni3729440934318541011.so+0x775dcc]  rocksdb::WBWIIteratorImpl::Entry() const+0x5c` following https://github.com/facebook/rocksdb/wiki/JNI-Debugging#stack instruction here and let us know the number? This is the line-number in the function `rocksdb::WBWIIteratorImpl::Entry()` where the SIGSEV happens.

By the way, what is the version of your RocksdbJava? Thanks!

**Comment by flyingsilverfin** [comment]
@hx235 I attempted to follow the instructions, however, I keep getting a `??:?` from `addr2line`.

I was unable to locate the example rocksdbJNI from the error, however, in the meanwhile I saw the exception again and used the stack from that instance:
```
Stack: [0x00007fd0d31ca000,0x00007fd0d32cb000],  sp=0x00007fd0d32c92b0,  free space=1020k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [librocksdbjni2520647259709175976.so+0x775dcc]  rocksdb::WBWIIteratorImpl::Entry() const+0x5c
C  [librocksdbjni2520647259709175976.so+0x776b6d]  rocksdb::BaseDeltaIterator::UpdateCurrent()+0x17d
C  [librocksdbjni2520647259709175976.so+0x776f2d]  rocksdb::BaseDeltaIterator::Seek(rocksdb::Slice const&)+0x7d
C  [librocksdbjni2520647259709175976.so+0x258348]  Java_org_rocksdb_RocksIterator_seek0+0x48
J 3057  org.rocksdb.RocksIterator.seek0(J[BI)V (0 bytes) @ 0x00007fd18c49e715 [0x00007fd18c49e640+0x00000000000000d5]
```

found `librocksdbjni2520647259709175976.so` in `/tmp`, appears RocksDB is unzipping its JAR into a temp directory.

however, running:
```
addr2line -e /tmp/librocksdbjni2520647259709175976.so 0x775dcc
```
yields:
```
??:?
```

**Comment by adamretter** [comment]
> we're using is 6.21.1, from Maven central.

@flyingsilverfin The versions on Maven Central are for production use and do not including debugging information. You will need to build a library which includes debugging information, to do so, from the 6.21.1 tag of the source code you can run:
```
DEBUG_LEVEL=2 make rocksdbjavastatic
```

**Comment by ajkr** [comment]
> The RocksDB version we're using is 6.21.1, from Maven central.

Is there a typo? I can't find 6.21.1 -- https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni

**Comment by adamretter** [comment]
@ajkr don't trust mvnrepository! See Maven Central - https://search.maven.org/artifact/org.rocksdb/rocksdbjni/6.26.1/jar

**Comment by flyingsilverfin** [comment]
Unfortunately, it might be a a while until I can get the linux dev build integrated into our system, and then run our tests often enough to reproduce it.

I did build the rocks binary with debug symbols, however the offset doesn't appear to be valid there.
_However_ would it be valid to take the function offset, and add it to the new function location? 
eg.
```
C  [librocksdbjni2520647259709175976.so+0x775dcc]  rocksdb::WBWIIteratorImpl::Entry() const+0x5c
```

`gdb` tells me that the new line number for `_ZNK7rocksdb16WBWIIteratorImpl5EntryEv` is at `0x000000000151dc3c`.  If I add the offset 0x5c, I can get a valid line number from `addr2line` (thanks to https://stackoverflow.com/questions/7556045/how-to-map-function-address-to-function-in-so-files/23910453#23910453).

I get this:
```
>  addr2line -f -C -e librocksdbjni-linux64.so 0x151dc98 
rocksdb::WBWIIteratorImpl::Entry() const
/home/joshua/rocksdb/utilities/write_batch_with_index/write_batch_with_index_internal.cc:586
```

The question is, does the function offset remain valid across the debugging and production binary?

**Comment by hx235** [comment]
> Unfortunately, it might be a a while until I can get the linux dev build integrated into our system

@adamretter I wonder if you can translate the line number `0x775dcc` in your corresponding library which includes debugging information of 6.21.1 (I had some trouble to get my java build set up to do so)

@flyingsilverfin Thanks for your investigation!! For me, the line number 586 points to an [assertion](https://github.com/facebook/rocksdb/blob/6.21.fb/utilities/write_batch_with_index/write_batch_with_index_internal.cc#L586-L587) which won't matter in production build (and cause your sigsev during production build) so that should be irrelevant. Fortunately, the Entry() is not a terribly long function so I think we can susepct line [584](https://github.com/facebook/rocksdb/blob/6.21.fb/utilities/write_batch_with_index/write_batch_with_index_internal.cc#L584), [588](https://github.com/facebook/rocksdb/blob/6.21.fb/utilities/write_batch_with_index/write_batch_with_index_internal.cc#L588).

While we are doing that, have you tried looking into your [information logs](https://github.com/facebook/rocksdb/wiki/RocksDB-Troubleshooting-Guide#information-logs) to see whether there has a line number already translated?

**Comment by hx235** [comment]
> https://search.maven.org/artifact/org.rocksdb/rocksdbjni/6.26.1/jar

@adamretter  for some reason - this directs me to a 6.26.1 jar instead fo 6.21.1 - I can't find 6.21.1 on maven central too. https://search.maven.org/search?q=g:org.rocksdb%20AND%20a:rocksdbjni%20AND%20v:6.21.1

**Comment by flyingsilverfin** [comment]
Ah Im very sorry, I mistyped the version -- we're on 6.26.1, not 6.21.1 (I also failed to look up 6.21.1 which confused me!!)

**Comment by adamretter** [comment]
> Unfortunately, it might be a a while until I can get the linux dev build integrated into our system, and then run our tests often enough to reproduce it.

@flyingsilverfin To speed this up, you can use the build environments we provide as Docker Images, if you are on intel x64 you can use: `evolvedbinary/rocksjava:centos6_x64-be`.
