### ISSUE TITLE
org.rocksdb.KeyMayExist fields and enum are private

### ISSUE THREAD

**Issue by cavallium** [facebook/rocksdb#9284]
### Expected behavior
Being able to access the fields exists and valueLength inside KeyMayExist class

### Actual behavior
Everything is package-private and it can be used only inside the package org.rocksdb

### Steps to reproduce the behavior
```java
var result = db.keyMayExist(columnFamilyHandle, keyBuffer, valueBuffer);
```

`result.valueLength` and `result.exists` can't be accessed.

**Comment by hx235** [comment]
Not a RocksJava expert but seem like the whole `KeyMayExist` class was originally introduced in this [PR](https://github.com/facebook/rocksdb/pull/9013) reviewed by @adamretter.

@adamretter, I'm just curious - why there is a Java class `KeyMayExist` while there doesn't seem to be a c++ equivalent to that? Is this class part of the RocksJava implementation details? 

I also found it interesting that the [`db.keyMayExist` Java api](https://github.com/facebook/rocksdb/blob/6.27.fb/java/src/test/java/org/rocksdb/KeyMayExistTest.java#L309) is different from [the C++ api](https://github.com/facebook/rocksdb/blob/6.27.fb/include/rocksdb/db.h#L706-L709)  in its return type. Is there any historical reason for this discrepancy? 

Thanks!

**Comment by cavallium** [comment]
> Not a RocksJava expert but seem like the whole `KeyMayExist` class was originally introduced in this [PR](https://github.com/facebook/rocksdb/pull/9013) reviewed by @adamretter.
> 
> @adamretter, I'm just curious - why there is a Java class `KeyMayExist` while there doesn't seem to be a c++ equivalent to that? Is this class part of the RocksJava implementation details?
> 
> I also found it interesting that the [`db.keyMayExist` Java api](https://github.com/facebook/rocksdb/blob/6.27.fb/java/src/test/java/org/rocksdb/KeyMayExistTest.java#L309) is different from [the C++ api](https://github.com/facebook/rocksdb/blob/6.27.fb/include/rocksdb/db.h#L706-L709) in its return type. Is there any historical reason for this discrepancy?
> 
> Thanks!


The keyMayExist Java api doesn't have the pointer in the arguments but it returns an object with all the informations.

**Comment by adamretter** [comment]
@cavallium Yes it seems to have been an oversight that it was package-private, sorry, it should have been public. I have approved your PR to fix that.

> I'm just curious - why there is a Java class KeyMayExist while there doesn't seem to be a c++ equivalent to that? Is this class part of the RocksJava implementation details?

@hx235 The C++ API uses pointers as function parameters to effectively enable more than one distinct value to be returned from the function. This isn't possible in Java in the same way, we could pass an Object as a parameter and mutate it, or the more normal approach is too return an object which contains the multiple values.

**Comment by hx235** [comment]
@cavallium  @adamretter  Thanks!
