### ISSUE TITLE
WriteStallCondition isn't notified in order

### ISSUE THREAD

**Issue by lhsoft** [facebook/rocksdb#9288]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
WriteStallCondition is notified by OnStallConditionsChanged should be in order(kDelayed -> kNormal)
### Actual behavior
WriteStallCondition isn't notified in order(kNormal->kDelayed)

**Comment by hx235** [comment]
Could you clarify a bit into what you meant by "should be in order (kDelayed -> kNormal)" and attached the code repro? Were you in a situation where `WriteStallCondition` is supposed to change from `kDelayed` to `kNormal` but ended up changing in the opposite direction? 

Thanks!

**Comment by ajkr** [comment]
In case the DB is already in stall mode when opened, the first notification you see may be when stall mode ends (`WriteStallInfo::condition.cur == kNormal`). We don't notify what the initial stall mode is, but maybe we should.

I don't know if that is the case you're hitting, though. We would need some clarification to pursue this further.
