### ISSUE TITLE
zstd set compression_max_dict_bytes doesn't save space but eats 30% more CPU when running fillseq&fillrandom benchmark

### ISSUE THREAD

**Issue by zhangjinpeng1987** [facebook/rocksdb#9308]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Setting compression_max_dict_bytes will save some space for zstd compression type.

### Actual behavior
There is no space-saving.

### Steps to reproduce the behavior

time ./db_bench \
  --write_buffer_size=$((64 * 1024*1024))  \
  --threads=1                      \
  --bloom_bits=10                         \
  --cache_size=$((128*1024*1024))         \
  --benchmarks=fillseq                 \
  --compression_type=zstd               \
  --compression_max_dict_bytes=$((16*1024)) \
  --memtablerep=skip_list                 \
  --compression_ratio=0.5                 \
  --key_size=30                           \
  --value_size=256                        \
  --num=10000000                          \
  --batch_size=100               \
  --db=$db_path                           \
  --use_existing_db=0

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

Fillseq 10m rows | Total CPU time(sys + user) | Database size
-- | -- | --
Zstd, dict bytes = 16KB, compression level = 3(default) | 83s | 1319MB
Zstd, dict bytes = 0, compression level = 3(default) | 55s | 1306MB

</div>

<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

Fillrandom 10m rows | Total CPU time(sys + user) | Database size
-- | -- | --
Zstd, dict bytes = 16KB, compression level = 3(default) | 218s | 1242MB
Zstd, dict bytes = 0, compression level = 3(default) | 161s | 1249MB

</div>

**Comment by zhangjinpeng1987** [comment]
Is it expected? The conclusion is different from https://rocksdb.org/blog/2021/05/31/dictionary-compression.html?utm_source=dbplatz

Is it has anything to do with `compression_ratio`?  @ajkr

**Comment by ajkr** [comment]
> Is it expected? The conclusion is different from https://rocksdb.org/blog/2021/05/31/dictionary-compression.html?utm_source=dbplatz

I guess the conclusion you're referring to is "In production, we have deployed dictionary presetting to save space in multiple RocksDB use cases with data block size 8KB or smaller. We have measured meaningful benefit to compression ratio in use cases with data block size up to 16KB. We have also measured a use case that can save both CPU and space by reducing data block size and turning on dictionary presetting at the same time."

That conclusion is drawn from production data, not synthetic data. `db_bench` uses synthetic data. I forgot how the synthetic data is generated but do remember it does not benefit from dictionary compression.

**Comment by mdcallag** [comment]
WRT to how the random data is generated, [see CompressibleString](https://github.com/facebook/rocksdb/blob/653c392e4796af3febdbdef9405e6e1c7b165878/test_util/testutil.cc#L75).

With compression_ratio=0.5 and value_size=256
1) compression_ratio X value_size bytes from the random buffer (128 bytes in this case)
2) copy the (128 byte) random string (1 / compression_ratio) times into the value buffer

Now the value buffer can compress by half, in theory. Perhaps more if the random buffer isn't large enough, but it almost always is. But yes, this looks very synthetic and very random. I don't know enough about zstd to have an opinion.

**Comment by ajkr** [comment]
IIRC if you decrease this 1048576 to the block size, you can get great results by enabling dictionary compression in `db_bench`. https://github.com/facebook/rocksdb/blob/2e51b33de9979673e3d0e8f632ee9e73dbe04bd6/tools/db_bench_tool.cc#L1890

Let me know that doesn't work or if there's some meaning to compression on synthetic data that I'm not getting (as of right now I think it has little practical use), if so we can reopen this.
