### ISSUE TITLE
Unexpected 'gtest/gtest.h' dependency in release build

### ISSUE THREAD

**Issue by strrchr** [facebook/rocksdb#934]
I tried to build master branch of rocksdb on Windows 7.
I found that `tools/ldb_cmd.cc` depends on `tools/sst_dump_tool_imp.h`, 
and `tools/sst_dump_tool_imp.h` depends on `util/testharness.h`, 
and `util/testharness.h` depends on `gtest/gtest.h`.

I just tried to build a release version.
I think it should not depend on `gtest/gtest.h`.
I just comment out `#include "util/testharness.h"` in `tools/sst_dump_tool_imp.h`, and found the compilation is OK.

Am I do it right?

**Comment by siying** [comment]
CC @yuslepukhin

**Comment by yuslepukhin** [comment]
@siying I don't think it is a WIndows problem. For some reason tools that are rightly build in release include test related headers.

**Comment by siying** [comment]
@yuslepukhin ahh, sorry I misunderstood that. If that is the case, we should fix it.

**Comment by siying** [comment]
https://reviews.facebook.net/D52791

**Comment by yuslepukhin** [comment]
Looks good to me. Perhaps, after this is checked in, I can address another issue by @strrchr

**Comment by siying** [comment]
@yuslepukhin I checked it in.
