### ISSUE TITLE
Is it safe to re-use ColumnFamilyHandle pointer while creating CFs

### ISSUE THREAD

**Issue by pcpLiu** [facebook/rocksdb#9341]
Hi experts,

I wanna create a several CFs for a DB in a initial function which will be called once.

```c++
void init_db() {
  // Open db
  ...

  std::vector<string> cfs = {.......};
  
  // create column family
  ColumnFamilyHandle* cf;
  for (auto& cf_name: cfs) {
    s = db->CreateColumnFamily(ColumnFamilyOptions(), cf_name, &cf);
  }

  // Close DB
  s = _db->DestroyColumnFamilyHandle(cf);
  assert(s.ok());
  delete _db;
}
```

My understanding from the doc is that we should have a `ColumnFamilyHandle` for each CF. But here I just want to create those CFs and don't have plan to use them RN in this function. So, I just reuse the pointer. Is the logic safe? especially the `DestroyColumnFamilyHandle` part?

Thanks.

**Comment by riversand963** [comment]
One column family handle for each cf which application must track and explicitly `delete` before closing the db.

ps.
I recommend re-using RocksDB unit test / examples framework to try out and see if there is any issue. One problem with the usage of `examples` is that it compiles RocksDB static lib with DEBUG_LEVEL=0 losing some debug symbols and I believe assertions are opt-away. You can tweak the Makefile in both `rocksdb` directory and `rocksdb/examples` directory a bit to get debug/assertion enabled.

As the issue template says, issues are mainly for bug reports. Closing this. If you have further doubt about this question, please use Google group / FB group.

**Comment by pcpLiu** [comment]
@riversand963  thanks. I will post related questions to Google group
