### ISSUE TITLE
Unexpected mock and test support files in Windows release build

### ISSUE THREAD

**Issue by strrchr** [facebook/rocksdb#935]
I tried to build master branch of rocksdb on Windows 7.
I think these files should not be included in release build:

```
table/mock_table.cc
util/mock_env.cc
util/testharness.cc
util/testutil.cc
```

**Comment by yuslepukhin** [comment]
@strrchr testharness.cc and testutil.cc are currently required by the code. I tried to move them to a test only library but failed.

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If you'd like this to be re-opened, please just comment here and we'll open it back up.
