### ISSUE TITLE
Regression in memory usage for db open after #8692

### ISSUE THREAD

**Issue by niklasf** [facebook/rocksdb#9375]
A test instance of one column family produced by https://github.com/niklasf/lila-openingexplorer:
* has 50 million random keys
* of fixed length
* with a fixed-size prefix extractor
* custom merge operator
* 2 bit per key bloom filter with new format
* 500 MB LRU cache

### Expected behavior

A process that just opens the database using RocksDB `9a116ab~1` needs about 50 MB RAM (RSS).

`rocksdb.estimate-table-readers-mem` for the column family is 20,998,116 and remains so after opening.

### Actual behavior

After 9a116ab4b4af980132c2deb4d6a68a9687030b14 (#8692), opening the database requires 2.7 GB RAM.

The additional memory usage appears to be at least proportional to database size, so that a larger production database can no longer be opened.

`rocksdb.estimate-table-readers-mem` for the column family is 406,459,504 and remains so after opening.

### Steps to reproduce the behavior

I will try to narrow this down to a smaller test case.

**Comment by pdillinger** [comment]
IIRC, this change fixed a bug where the hash index would not be used. Very large indexes might just be the effect of the bug fix. It looks like you are generating hash indexes. Using the default kBinarySearch index (only) should give you the old behavior.

https://github.com/niklasf/lila-openingexplorer/blob/44335964d5062abc5d2c8b33ed52ebed93357ac5/src/db.rs#L37

**Comment by niklasf** [comment]
Thank you, that clears it up!

In can confirm that the memory usage is back to the previous level.

There also doesn't appear to be any performance regression from not using kBinarySearch. As expected, if it wasn't really used in the first place.
