### ISSUE TITLE
Removing some deprecated APIs in 7.0

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#9389]
In the upcoming 7.0 major release we plan to remove some APIs marked "deprecated." We have have not committed to which will or will not be removed, but let us know in comments if you have particular concerns (such as deprecated API with no workable alternative).

Deprecated options to remove:
- max_mem_compaction_level
- soft_rate_limit
- hard_rate_limit
- rate_limit_delay_max_milliseconds
- purge_redundant_kvs_while_flush
- base_background_compactions
- skip_log_error_on_recovery
- preserve_deletes
- iter_start_seqnum
- table_cache_remove_scan_count_limit

Deprecated APIs to remove:
- ROCKSDB_DEPRECATED_FUNC DB::AddFile() overloads
- ROCKSDB_DEPRECATED_FUNC DB::CompactRange() overloads
- ROCKSDB_DEPRECATED_FUNC DB::GetApproximateSizes() overloads

**Comment by riversand963** [comment]
Repeating here to boost this post:

This is the current list we plan to remove.

Deprecated options to remove:

max_mem_compaction_level
soft_rate_limit
hard_rate_limit
rate_limit_delay_max_milliseconds
purge_redundant_kvs_while_flush
base_background_compactions
skip_log_error_on_recovery
preserve_deletes
iter_start_seqnum
table_cache_remove_scan_count_limit
Deprecated APIs to remove:

ROCKSDB_DEPRECATED_FUNC DB::AddFile() overloads
ROCKSDB_DEPRECATED_FUNC DB::CompactRange() overloads
ROCKSDB_DEPRECATED_FUNC DB::GetApproximateSizes() overloads

**Comment by pdillinger** [comment]
(Will also update the description with these)

Deprecated override implementations to remove (derived classes must now implement):

Env::Name
EnvWrapper::Name
FileSystemWrapper::Name
Statistics::Name
FilterBitsBuilder::ApproximateNumEntries

Deprecated APIs to remove:

ObjectLibrary::Register (uses regexes)
FilterBitsBuilder::CalculateNumEntry
FilterPolicy::CreateFilter (for slow, deprecated block-based filter only)
FilterPolicy::KeyMayMatch (for slow, deprecated block-based filter only)
FilterPolicy::GetFilterBitsBuilder
NewExperimentalRibbonFilterPolicy

Deprecated headers to remove:

utilities/backupable_db.h (obsolete with backup_engine.h)
utilities/regex.h (obsolete with ObjectLibrary::Register removal)
utilities/utility_db.h (only contains obsolete)
