### ISSUE TITLE
Total threads in the DB doing concurrent compaction exceed Max Background Compactions value

### ISSUE THREAD

**Issue by lookforsandy** [facebook/rocksdb#939]
2015/11/24-23:00:48.341789 ffecc40080 [WARN] ------- DUMPING STATS -------
2015/11/24-23:00:48.341930 ffecc40080 [WARN]
*\* Compaction Stats [default] **
## Level    Files   Size(MB) Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) Stall(cnt)  KeyIn KeyDrop

  L0     59/32        29   6.8      0.0     0.0      0.0     102.6    102.6       0.0   0.0      0.0      4.4     23990     99566    0.241      19946       0      0
  L1     33/24       307   0.3   1646.0   102.6   1543.4    1642.7     99.2       0.0  16.0      6.5      6.5    260502     19141   13.610          0    132M  3438K
  L2    220/0       1147   1.0     48.8    17.1     31.7      48.1     16.4      81.8   2.8      6.6      6.5      7545      1460    5.168          0     18M   959K
  L3   1289/0      13813   1.0     71.9    34.5     37.5      71.2     33.8      62.6   2.1      6.7      6.6     11042      1864    5.924          0     44M   915K
  L4   5870/0      82686   0.0    122.9    63.0     59.9     120.7     60.9      19.9   1.9      6.6      6.5     18999      2611    7.276          0     81M  2790K
Sum   7471/56     97981   0.0   1889.6   217.2   1672.5    1985.3    312.9     164.3  19.3      6.0      6.3    322078    124642    2.584      19946    278M  8103K
Int      0/0          0   0.0     16.9     1.7     15.2      17.0      1.9       0.6  39.6      3.5      3.5      4960      1029    4.820        654   2016K   315K
Flush(GB): cumulative 102.611, interval 0.430
Stalls(count): 19437 level0_slowdown, 509 level0_numfiles, 0 memtable_compaction, 0 leveln_slowdown_soft, 0 leveln_slowdown_hard

Based on the above stats, we are seeing a total of 56 threads currently doing compaction across all the levels.
We have set max_background_compactions = 4.
Can you clarify how is max_background_compactions taken into account ? 
Thanks!

**Comment by lookforsandy** [comment]
Bump

**Comment by igorcanadi** [comment]
The stats say that 56 files are getting compacted, not that there are 56 thread. One compaction can affect many files.

**Comment by lookforsandy** [comment]
Thanks for the clarification.
I think tuning guide needs a fix under compaction stats section.
"Files - this has two values as (a/b). The first is the number of files in the level. The second is the number of threads currently doing compaction for that level."

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
