### ISSUE TITLE
NOTICE: Changes planned for RocksDB 7.0 release

### ISSUE THREAD

**Issue by pdillinger** [facebook/rocksdb#9390]
The next major release of RocksDB, 7.0, is planned for cut in February 2022 and release in March 2022.

Here are some relevant linked issues with various planned changes:

Removing some compiler support in 7.0 #9388, including requiring gcc >= 7 and C++17
Removing some deprecated APIs in 7.0 #9389
Move RADOS support to a separate plugin repo #9207
Move HDFS support from RocksDB main repo to plugin #9159
Move rdb support from RocksDB main repo to separate repo #9382

**Comment by adamretter** [comment]
@pdillinger Can you tell me where to contribute to this effort - is there a canonical list of TODO - there are changes and cleanup we would like to make in RocksJava as well as moving to Java 8.

**Comment by pdillinger** [comment]
> @pdillinger Can you tell me where to contribute to planning this effort? Is there a canonical list of TODO - there are changes and cleanup we would like to make in RocksJava as well as moving to Java 8.

All the listed items (specifics in tasks) are already "claimed" by Meta employees.

For Java updates, we grant you pretty broad discretion to make updates you think are appropriate for a major release.

For changes affecting C++, you're welcome to propose additional items, though we might veto if they seem like they would have unacceptable internal impact for us.

Our planned branch cut date is Feb 18 (two weeks), so not much time left.

**Comment by pdillinger** [comment]
If you want to create a tracking issue for Java updates for 7.0, I can link to it from here. Prefer linked issues for discussing specifics, but some discussion here is also OK.
