### ISSUE TITLE
Can I use multiple RocksDB instance in one process safely ? 

### ISSUE THREAD

**Issue by ppLorins** [facebook/rocksdb#942]
![image](https://cloud.githubusercontent.com/assets/5534049/12257018/790d3dcc-b93d-11e5-99e5-9eb28f059230.png)

I learned the same rocksDB instance cannot be shared among threads.   

But if each thread has its own instance , will the extra(user level) synchronous mechanism still needed ?

**Comment by igorcanadi** [comment]
The same RocksDB instance can definitely be shared among multiple threads.

**Comment by ppLorins** [comment]
Yes ,sorry ,  I didn't made it clear.  What I mean is , when I wanna use the same instance among threads, 
I can't do write operation simultaneously , according the document.   But If I can do that when every single thread has its own instance.

**Comment by igorcanadi** [comment]
You can definitely call Write() function simultaneously. What you can't do is define WriteBatch in one thread and then use it in another. But two threads having their own WriteBatch and calling Write() is legal.

**Comment by jerousrb** [comment]
@igorcanadi   
hi  igorcanadi, Do you know the max num of  rocksdb instances supported?   there any problems if create 2K  rocksdb instance in the same process? thinks

**Comment by HMAshiqulIslam** [comment]
@jerousrb did you manage to find any answer ?

**Comment by riversand963** [comment]
@HMAshiqulIslam @jerousrb 
afaik, there is no hard-coded, artificial limit on the number of RocksDB instances that can be created by a process. The number of instances is likely bounded by the amount of resources available, and performance/efficiency is the main consideration here.
