### ISSUE TITLE
SNAPPY LINK ISSUE TO BINARY

### ISSUE THREAD

**Issue by hdesai78** [facebook/rocksdb#9422]
###> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
rocksdb shoul_bench command it shows error "[root@RocksDBNew rocksdb-6.27.3]# ./db_bench
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
open error: Invalid argument: Compression type Snappy is not linked with the binary."
### Steps to reproduce the behavior
Installed all the dependencies library for rocksdb including snappy. ( I am not able to install snappy-dev due to command not recognized in Centos 8, "yum install snappy-dev."
Installed rocksdb-6.27.3
Initiate ./deb_bench command to run benchmarks.

Looking ASAP to resolve issue.

**Comment by adamretter** [comment]
@hdesai78 I think as you also posted here https://github.com/facebook/rocksdb/issues/761#issuecomment-1019589468 I answered your question there.
