### ISSUE TITLE
Disk usage is too large，need some help

### ISSUE THREAD

**Issue by wuguanyu** [facebook/rocksdb#9440]
> 

** DB Stats **
Uptime(secs): 0.9 total, 0.9 interval
Cumulative writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 GB, 0.00 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 MB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop
----------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      4/0    2.28 MB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     57.0         0         1    0.007       0      0
  L1    664/0   488.74 MB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
  L2   1820/0    4.99 GB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
  L3   2731/0   50.00 GB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
  L4  18840/0   499.94 GB   1.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
  L5  26132/0    1.25 TB   0.3      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0         0         0    0.000       0      0
 Sum  50191/0    1.80 TB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     57.0         0         1    0.007       0      0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   1.0      0.0     57.0         0         1    0.007       0      0

**Comment by wuguanyu** [comment]
I hope what can i do? It can reduce disk usage, I have already delete range key, But it doesn't work

**Comment by wuguanyu** [comment]
2022/01/25-19:36:15.041933 7f2ffb430ae8 RocksDB version: 5.17.2
2022/01/25-19:36:15.042004 7f2ffb430ae8 Git sha rocksdb_build_git_sha:
2022/01/25-19:36:15.042013 7f2ffb430ae8 Compile date Nov 26 2018
2022/01/25-19:36:15.042020 7f2ffb430ae8 DB SUMMARY
2022/01/25-19:36:15.090924 7f2ffb430ae8 CURRENT file:  CURRENT
2022/01/25-19:36:15.090944 7f2ffb430ae8 IDENTITY file:  IDENTITY
2022/01/25-19:36:15.090958 7f2ffb430ae8 MANIFEST file:  MANIFEST-820128 size: 3723165 Bytes
2022/01/25-19:36:15.090969 7f2ffb430ae8 SST files in /root/neptune/store/rocksdb dir, Total Num: 50190, files: 023268.sst 023426.sst 023442.sst 023443.sst 023456.sst 023457.sst 023469.sst 023470.sst 023482.sst 
2022/01/25-19:36:15.090976 7f2ffb430ae8 Write Ahead Log file in /root/neptune/store/rocksdb: 820129.log size: 833801 ; 
2022/01/25-19:36:15.099994 7f2ffb430ae8                         Options.error_if_exists: 0

**Comment by ajkr** [comment]
> I hope know what can i do? It can reduce disk usage, I have already delete range key, But it doesn't work

`Delete()` or `DeleteRange()` only logically delete the keys so they won't be visible to reads. For physical removal you need to run compaction after `Delete()` or `DeleteRange()`, such as by calling `CompactRange()`.

**Comment by wuguanyu** [comment]
> > I hope know what can i do? It can reduce disk usage, I have already delete range key, But it doesn't work
> 
> `Delete()` or `DeleteRange()` only logically delete the keys so they won't be visible to reads. For physical removal you need to run compaction after `Delete()` or `DeleteRange()`, such as by calling `CompactRange()`.

I need invoke CompactRange by myself. It doesn't compact auto when i invoke DeleteRange method

**Comment by wuguanyu** [comment]
> > I hope know what can i do? It can reduce disk usage, I have already delete range key, But it doesn't work
> 
> `Delete()` or `DeleteRange()` only logically delete the keys so they won't be visible to reads. For physical removal you need to run compaction after `Delete()` or `DeleteRange()`, such as by calling `CompactRange()`.

thanks for your support

**Comment by wuguanyu** [comment]
https://github.com/facebook/rocksdb/wiki/Delete-Stale-Files
 
 I will take a look at above wiki
