### ISSUE TITLE
benchmark readrandom  show 0.00 MB/s data read

### ISSUE THREAD

**Issue by hgdesai** [facebook/rocksdb#9445]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Should see some MB read when issuing ./db_bench --benchmarks=readrandom
### Actual behavior
Not seeing any data being read from DB_DIR
### Steps to reproduce the behavior
1) Ran fillseq benchmarks to create some *.sst files into DB_DIR and WAL_DIR by using following command.
./db_bench --benchmarks=fillseq --use_existing_db=0 --db=$DB_DIR --wal_dir=$WAL_DIR --key_size=12 --value_size=1024 --num=1200000000 --threads=4 --max_background_jobs=12 --block_size=2048 --write_buffer_size=1073741824 --arena_block_size=16777216 --max_write_buffer_number=50 --memtablerep=vector --allow_concurrent_memtable_write=false --cache_size=0 --batch_size=4 --bloom_bits=10 --compression_type=snappy --benchmark_write_rate_limit=0 --rate_limit_delay_max_milliseconds=1000000 --target_file_size_base=1073741824  --max_bytes_for_level_base=1073741824 --max_bytes_for_level_multiplier=10 --level0_slowdown_writes_trigger=1048576000 --level0_stop_writes_trigger=1048576000 --level0_stop_writes_trigger=1048576000 --soft_pending_compaction_bytes_limit=274877906944 --hard_pending_compaction_bytes_limit=549755813888 --use_direct_reads=0 --use_direct_io_for_flush_and_compaction=0 --disable_wal=1 --verify_checksum=1 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1

** DB Stats **
Uptime(secs): 2566.5 total, 62.8 interval
Cumulative writes: 0 writes, 222M keys, 0 commit groups, 0.0 writes per commit group, ingest: 215.79 GB, 86.10 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 450K keys, 0 commit groups, 0.0 writes per commit group, ingest: 447.46 MB, 7.12 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

2022/01/25-16:51:16  ... thread 2: (127000,56399000) ops and (2101.0,21492.1) ops/second in (60.447267,2624.172245) seconds
2022/01/25-16:51:16  ... thread 3: (128000,55442000) ops and (2116.9,21127.4) ops/second in (60.465309,2624.172414) seconds
2022/01/25-16:51:16  ... thread 1: (125000,55315000) ops and (2065.7,21078.6) ops/second in (60.510785,2624.229741) seconds
2022/01/25-16:51:16  ... thread 0: (125000,55508000) ops and (2065.5,21152.0) ops/second in (60.518676,2624.243583) seconds

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0     22/22  28.33 GB   0.0     65.6     0.0     65.6     130.3     64.7       0.0   1.5     16.4     32.5   4106.66           1532.15       208   19.744    115M    40M       0.0       0.0
  L1      2/2    1.32 GB   0.0     33.4    31.1      2.4      17.9     15.5       0.0   0.6     70.9     37.9    482.75            300.95         4  120.687     58M    27M       0.0       0.0
  L2      9/0    9.11 GB   0.9      0.0     0.0      0.0       0.0      0.0      14.2   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
  L3      5/0    5.06 GB   0.1      0.0     0.0      0.0       0.0      0.0       5.1   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum     38/24  43.82 GB   0.0     99.0    31.1     67.9     148.2     80.2      19.2   1.7     22.1     33.1   4589.41           1833.11       212   21.648    173M    68M       0.0       0.0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Low      0/0    0.00 KB   0.0     99.0    31.1     67.9      60.2     -7.7       0.0   0.0     54.3     33.0   1866.16            947.57        37   50.437    173M    68M       0.0       0.0
High      0/0    0.00 KB   0.0      0.0     0.0      0.0      88.0     88.0       0.0   0.0      0.0     33.1   2723.25            885.53       175   15.561       0      0       0.0       0.0

Blob file count: 0, total size: 0.0 GB

Uptime(secs): 2626.4 total, 59.9 interval
Flush(GB): cumulative 87.962, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 148.18 GB write, 57.78 MB/s write, 99.03 GB read, 38.61 MB/s read, 4589.4 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
2) When initiating benchmarks=readrandom getting following with 0.0 MB/s read with following command
db_bench --benchmarks=readrandom --disable_auto_compactions=1 --use_existing_db=1 --db=$DB_DIR --wal_dir=$WAL_DIR --key_size=12 --value_size=1024 --num=1200000000 --threads=1  --block_size=2048 --cache_size=17179869184  --cache_numshardbits=10 --compression_type=snappy  --arena_block_size=16777216 --memtablerep=skip_list --bloom_bits=10  --use_direct_reads=0 --use_direct_io_for_flush_and_compaction=0 --verify_checksum=1 --seed=1576170874 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1

** DB Stats **
Uptime(secs): 301.0 total, 60.0 interval
Cumulative writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 GB, 0.00 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

2022/01/26-12:08:40  ... thread 0: (6057000,35188000) ops and (100937.5,97738.1) ops/second in (60.007423,360.023472) seconds

** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0     68/0   83.93 GB 335.7      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
  L1      1/0   766.87 MB   3.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
  L2      9/0    9.11 GB   3.6      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
  L3      9/0    9.11 GB   0.4      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum     87/0   102.89 GB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Blob file count: 0, total size: 0.0 GB

Uptime(secs): 361.1 total, 60.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
Block cache LRUCache@0x246f8e0#21339 capacity: 16.00 GB collections: 1 last_copies: 0 last_secs: 0.000734 secs_since: 360
Block cache entry stats(count,size,portion): Misc(1,0.00 KB,0%)

[root@RocksDBNew ~]# ll /mnt/nvme0n/db
total 57912112
-rw-r--r--. 1 root root 1038964949 Jan 26 10:50 000035.sst
-rw-r--r--. 1 root root 1086585352 Jan 26 10:50 000037.sst
-rw-r--r--. 1 root root 1086557341 Jan 26 10:50 000039.sst
-rw-r--r--. 1 root root 1086585542 Jan 26 10:50 000040.sst
-rw-r--r--. 1 root root 1203011879 Jan 26 10:51 000043.sst
-rw-r--r--. 1 root root 1086557231 Jan 26 10:51 000046.sst
-rw-r--r--. 1 root root 1124315386 Jan 26 10:51 000049.sst
-rw-r--r--. 1 root root  516310635 Jan 26 10:51 000054.sst
-rw-r--r--. 1 root root 1260956792 Jan 26 10:51 000056.sst
-rw-r--r--. 1 root root 1335481934 Jan 26 10:52 000062.sst
-rw-r--r--. 1 root root 1383473698 Jan 26 10:52 000068.sst
-rw-r--r--. 1 root root  537938414 Jan 26 10:51 000070.sst
-rw-r--r--. 1 root root  515067139 Jan 26 10:51 000071.sst
-rw-r--r--. 1 root root  556635172 Jan 26 10:51 000072.sst
-rw-r--r--. 1 root root 1430635155 Jan 26 10:52 000073.sst
-rw-r--r--. 1 root root 1468577099 Jan 26 10:52 000074.sst
-rw-r--r--. 1 root root 1691443277 Jan 26 10:52 000079.sst
-rw-r--r--. 1 root root  520790488 Jan 26 10:52 000080.sst
-rw-r--r--. 1 root root 1269534640 Jan 26 10:53 000081.sst
-rw-r--r--. 1 root root 1814430209 Jan 26 10:53 000082.sst
-rw-r--r--. 1 root root 1472039630 Jan 26 10:53 000083.sst
-rw-r--r--. 1 root root 1086585483 Jan 26 10:55 000087.sst
-rw-r--r--. 1 root root 1267311287 Jan 26 10:55 000089.sst
-rw-r--r--. 1 root root  562826763 Jan 26 10:53 000090.sst
-rw-r--r--. 1 root root  547556923 Jan 26 10:53 000091.sst
-rw-r--r--. 1 root root 1461673919 Jan 26 10:55 000092.sst
-rw-r--r--. 1 root root 1483245306 Jan 26 10:55 000093.sst
-rw-r--r--. 1 root root  958326242 Jan 26 10:56 000094.sst
-rw-r--r--. 1 root root 1086557794 Jan 26 10:56 000096.sst
-rw-r--r--. 1 root root 1086585290 Jan 26 10:56 000098.sst
-rw-r--r--. 1 root root 1086558092 Jan 26 10:58 000099.sst
-rw-r--r--. 1 root root 1086585399 Jan 26 10:59 000100.sst
-rw-r--r--. 1 root root  502804264 Jan 26 10:59 000104.sst
-rw-r--r--. 1 root root  517328123 Jan 26 10:59 000105.sst
-rw-r--r--. 1 root root 1294205786 Jan 26 10:59 000106.sst
-rw-r--r--. 1 root root 1323335941 Jan 26 10:59 000107.sst
-rw-r--r--. 1 root root  411908418 Jan 26 10:59 000108.sst
-rw-r--r--. 1 root root  386447617 Jan 26 10:59 000109.sst
-rw-r--r--. 1 root root 1086550895 Jan 26 11:03 000114.sst
-rw-r--r--. 1 root root  947359381 Jan 26 11:06 000115.sst
-rw-r--r--. 1 root root  506201565 Jan 26 11:01 000116.sst
-rw-r--r--. 1 root root  897237510 Jan 26 11:04 000117.sst
-rw-r--r--. 1 root root 1483021141 Jan 26 11:03 000118.sst
-rw-r--r--. 1 root root  559913122 Jan 26 11:03 000119.sst
-rw-r--r--. 1 root root 3695924599 Jan 26 11:04 000120.sst
-rw-r--r--. 1 root root 1086574890 Jan 26 11:03 000121.sst
-rw-r--r--. 1 root root  665318286 Jan 26 11:03 000122.sst
-rw-r--r--. 1 root root  575273371 Jan 26 11:04 000123.sst
-rw-r--r--. 1 root root 1086574890 Jan 26 11:04 000124.sst
-rw-r--r--. 1 root root 1086547363 Jan 26 11:05 000125.sst
-rw-r--r--. 1 root root 1086574218 Jan 26 11:05 000126.sst
-rw-r--r--. 1 root root  593032311 Jan 26 11:05 000127.sst
-rw-r--r--. 1 root root 1086547120 Jan 26 11:05 000128.sst
-rw-r--r--. 1 root root 1086574416 Jan 26 11:06 000129.sst
-rw-r--r--. 1 root root 1086547427 Jan 26 11:06 000130.sst
-rw-r--r--. 1 root root  916315690 Jan 26 11:06 000131.sst
-rw-r--r--. 1 root root         16 Jan 26 10:48 CURRENT
drwxr-xr-x. 2 root root        241 Jan 26 10:28 dbbench
-rw-r--r--. 1 root root         36 Jan 26 10:48 IDENTITY
-rw-r--r--. 1 root root          0 Jan 26 10:48 LOCK
-rw-r--r--. 1 root root     533482 Jan 26 11:06 LOG
-rw-r--r--. 1 root root      14171 Jan 26 11:06 MANIFEST-000004
-rw-r--r--. 1 root root       6653 Jan 26 10:48 OPTIONS-000007

**Comment by ajkr** [comment]
It's a lot of output but the only read throughput line I saw was `2022/01/26-12:08:40 ... thread 0: (6057000,35188000) ops and (100937.5,97738.1) ops/second in (60.007423,360.023472) seconds`. Can you include the line of output that says 0.0 MB/s -- I believe it includes other info too like how many keys were queried vs. found, which could be useful.

**Comment by hgdesai** [comment]
@ajkr As you can see below every data is zero(start line with ** and end line with **(bold)). 
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds

[root@RocksDBNew rocksdb-6.27.3]# ./db_bench --benchmarks=readrandom --disable_auto_compactions=1 --use_existing_db=1 --db=$DB_DIR --wal_dir=$WAL_DIR --key_size=12 --value_size=1024 --num=1200000000 --threads=1  --block_size=2048 --cache_size=17179869184  --cache_numshardbits=10 --compression_type=snappy  --arena_block_size=16777216 --memtablerep=skip_list --bloom_bits=10  --use_direct_reads=0 --use_direct_io_for_flush_and_compaction=0 --verify_checksum=1 --seed=1576170874 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
RocksDB:    version 6.27
Date:       Wed Jan 26 13:54:49 2022
CPU:        4 * Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz
CPUCache:   10240 KB
Keys:       12 bytes each (+ 0 bytes user-defined timestamp)
Values:     1024 bytes each (512 bytes after compression)
Entries:    1200000000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    1185607.9 MB (estimated)
FileSize:   599670.4 MB (estimated)
Write rate: 0 bytes/second
Read rate: 0 ops/second
Compression: Snappy
Compression sampling rate: 0
Memtablerep: SkipListFactory
Perf Level: 1
------------------------------------------------
DB path: [/mnt/nvme0n/db]
** Compaction Stats [default] **
Level    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  L0      3/0   568.31 MB   2.2      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Sum      3/0   568.31 MB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0
 Int      0/0    0.00 KB   0.0      0.0     0.0      0.0       0.0      0.0       0.0   0.0      0.0      0.0      0.00              0.00         0    0.000       0      0       0.0       0.0

** Compaction Stats [default] **
Priority    Files   Size     Score Read(GB)  Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Blob file count: 0, total size: 0.0 GB

Uptime(secs): 61.7 total, 60.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
**Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds**
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
Block cache LRUCache@0x2a4a8e0#27951 capacity: 16.00 GB collections: 1 last_copies: 0 last_secs: 0.000745 secs_since: 60
Block cache entry stats(count,size,portion): Misc(1,0.00 KB,0%)

** File Read Latency Histogram By Level [default] **

** DB Stats **
Uptime(secs): 61.7 total, 60.0 interval
Cumulative writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 GB, 0.00 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent

**Comment by hgdesai** [comment]
> It's a lot of output but the only read throughput line I saw was `2022/01/26-12:08:40 ... thread 0: (6057000,35188000) ops and (100937.5,97738.1) ops/second in (60.007423,360.023472) seconds`. Can you include the line of output that says 0.0 MB/s -- I believe it includes other info too like how many keys were queried vs. found, which could be useful.

@ajkr As you can see below every data is zero(start line with ** and end line with **(bold)).
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
[root@RocksDBNew rocksdb-6.27.3]# ./db_bench --benchmarks=readrandom --disable_auto_compactions=1 --use_existing_db=1 --db=$DB_DIR --wal_dir=$WAL_DIR --key_size=12 --value_size=1024 --num=1200000000 --threads=1 --block_size=2048 --cache_size=17179869184 --cache_numshardbits=10 --compression_type=snappy --arena_block_size=16777216 --memtablerep=skip_list --bloom_bits=10 --use_direct_reads=0 --use_direct_io_for_flush_and_compaction=0 --verify_checksum=1 --seed=1576170874 --stats_per_interval=1 --stats_interval_seconds=60 --histogram=1
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
RocksDB: version 6.27
Date: Wed Jan 26 13:54:49 2022
CPU: 4 * Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz
CPUCache: 10240 KB
Keys: 12 bytes each (+ 0 bytes user-defined timestamp)
Values: 1024 bytes each (512 bytes after compression)
Entries: 1200000000
Prefix: 0 bytes
Keys per prefix: 0
RawSize: 1185607.9 MB (estimated)
FileSize: 599670.4 MB (estimated)
Write rate: 0 bytes/second
Read rate: 0 ops/second
Compression: Snappy
Compression sampling rate: 0
Memtablerep: SkipListFactory
Perf Level: 1
DB path: [/mnt/nvme0n/db]
** Compaction Stats [default] **
Level Files Size Score Read(GB) Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)

L0 3/0 568.31 MB 2.2 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.00 0.00 0 0.000 0 0 0.0 0.0
Sum 3/0 568.31 MB 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.00 0.00 0 0.000 0 0 0.0 0.0
Int 0/0 0.00 KB 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.00 0.00 0 0.000 0 0 0.0 0.0
** Compaction Stats [default] **
Priority Files Size Score Read(GB) Rn(GB) Rnp1(GB) Write(GB) Wnew(GB) Moved(GB) W-Amp Rd(MB/s) Wr(MB/s) Comp(sec) CompMergeCPU(sec) Comp(cnt) Avg(sec) KeyIn KeyDrop Rblob(GB) Wblob(GB)

Blob file count: 0, total size: 0.0 GB

Uptime(secs): 61.7 total, 60.0 interval
Flush(GB): cumulative 0.000, interval 0.000
AddFile(GB): cumulative 0.000, interval 0.000
AddFile(Total Files): cumulative 0, interval 0
AddFile(L0 Files): cumulative 0, interval 0
AddFile(Keys): cumulative 0, interval 0
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Interval compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
Stalls(count): 0 level0_slowdown, 0 level0_slowdown_with_compaction, 0 level0_numfiles, 0 level0_numfiles_with_compaction, 0 stop for pending_compaction_bytes, 0 slowdown for pending_compaction_bytes, 0 memtable_compaction, 0 memtable_slowdown, interval 0 total count
Block cache LRUCache@0x2a4a8e0#27951 capacity: 16.00 GB collections: 1 last_copies: 0 last_secs: 0.000745 secs_since: 60
Block cache entry stats(count,size,portion): Misc(1,0.00 KB,0%)

** File Read Latency Histogram By Level [default] **

** DB Stats **
Uptime(secs): 61.7 total, 60.0 interval
Cumulative writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 GB, 0.00 MB/s
Cumulative WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Cumulative stall: 00:00:0.000 H:M:S, 0.0 percent
Interval writes: 0 writes, 0 keys, 0 commit groups, 0.0 writes per commit group, ingest: 0.00 MB, 0.00 MB/s
Interval WAL: 0 writes, 0 syncs, 0.00 writes per sync, written: 0.00 GB, 0.00 MB/s
Interval stall: 00:00:0.000 H:M:S, 0.0 percent
@hgdesai

**Comment by riversand963** [comment]
In the above, you disabled compaction and the benchmark is only readrandom, so compaction and write related counters are of course 0. Note the following
```
Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds
```
The "0.00MB/s read" refers to compaction read.

**Comment by hgdesai** [comment]
@riversand963 thanks for the response. It works now.

**Comment by ajkr** [comment]
> @ajkr As you can see below every data is zero(start line with ** and end line with **(bold)). Cumulative compaction: 0.00 GB write, 0.00 MB/s write, 0.00 GB read, 0.00 MB/s read, 0.0 seconds

Just want to re-emphasize this is compaction read, not readrandom benchmark read throughput.

**Comment by hgdesai** [comment]
@ajkr how would I read throughput of readrandom benchmark?

**Comment by ajkr** [comment]
> how would I read throughput of readrandom benchmark? 

At the end of the benchmark run it should print a line like this:

```
readrandom   :       1.957 micros/op 510910 ops/sec;   56.5 MB/s (100000 of 100000 found)
```

> Also please guide me through document where I can understand results output.

Sorry I did not find one...

**Comment by hgdesai** [comment]
Anyone else guide me to it please?

**Comment by ajkr** [comment]
For both this and #9536, your db_bench command is using all kinds of options to print advanced info, and you're interpreting it as a zero result. I am not sure what line exactly suggests to you the result is zero, but anyways I'd suggest starting with db_bench readrandom with default options and add advanced options only as needed.

**Comment by hgdesai** [comment]
@ajkr The commands were used by benchmark.sh in both the cases.  As you see I am only initiating the command as follows "NUM_KEYS=900000000 CACHE_SIZE=6442450944 DURATION=5400 /root/rocksdb-6.28.2/tools/./benchmark.sh readrandom --stats_per_interval=1" the rest of the output is done by the db_bench automatically.  My question is why it is only showing zeros for readradom benchmark but it shows some read data for "bulkload , fillseq and readwhilewriting" benchmarks.

**Comment by hgdesai** [comment]
@riversand963  I did ran following command and the result is really low compare to Facebook benchmark results. The hardware information is as below listed and I am running the benchmark using Samsung 512 P918 NVMe drive.  The default sequential read for this drive is 3500 MB. 


[root@RocksDBNew rocksdb-6.28.2]# ./db_bench -use_existing_db=1 --benchmarks=readrandom  --stats_per_interval=1 --db=$DB_DIR --wal_dir=$WAL_DIR --duration=5400
Initializing RocksDB Options from the specified file
Initializing RocksDB Options from command-line flags
RocksDB:    version 6.28
Date:       Fri Feb 11 12:39:44 2022
CPU:        4 * Intel(R) Xeon(R) CPU E5-2407 v2 @ 2.40GHz
CPUCache:   10240 KB
Keys:       16 bytes each (+ 0 bytes user-defined timestamp)
Values:     100 bytes each (50 bytes after compression)
Entries:    1000000
Prefix:    0 bytes
Keys per prefix:    0
RawSize:    110.6 MB (estimated)
FileSize:   62.9 MB (estimated)
Write rate: 0 bytes/second
Read rate: 0 ops/second
Compression: Snappy
Compression sampling rate: 0
Memtablerep: SkipListFactory
Perf Level: 1
------------------------------------------------
DB path: [/mnt/nvme0n/db]
readrandom   :      11.940 micros/op 83750 ops/sec;    9.3 MB/s (452253999 of 452253999 found)
