### ISSUE TITLE
Rocksdb diff tool

### ISSUE THREAD

**Issue by asad-awadia** [facebook/rocksdb#9447]
Is there any support for checking consistency between two rocksdb instances? Something like a diff tool that shows data difference, if any?

**Comment by ajkr** [comment]
Not specifically. You can compare the output of `ldb scan --hex` for an offline comparison. Or for online comparison, create iterators at the same point in time and compare their results.

**Comment by asad-awadia** [comment]
@ajkr how can i create an iterator at the same point in time if the DBs are on different machines?

**Comment by riversand963** [comment]
sequence numbers in different RocksDB instances are irrelevant, thus not comparable. Without additional application input, there is no such concept as "same point in time across two DBs".
To establish the connection, application can
- use user-defined timestamp, or
- assign the same timestamp to two snapshots taken from the two DBs respectively. The application needs to ensure that the timestamp <-> snapshot correlation on each DB is valid. See https://github.com/facebook/rocksdb/wiki/Snapshot for more information on "timestamped snapshots". This set of APIs is currently available at Transaction/TransactionDB layer.

**Comment by asad-awadia** [comment]
@riversand963 yeah we are on a really old version of rocksdb and can't do most of that

Need a simple way to compare if two rocksdb DBs are the same - they are being written to via raft so in theory should be at the same state

**Comment by riversand963** [comment]
> should be at the same state

True only if you are comparing the end state. Otherwise, RocksDB does not support creating snapshot of the past because the history is not necessarily preserved, as explained in https://github.com/facebook/rocksdb/issues/10439#issuecomment-1199845223
