### ISSUE TITLE
Please Provide Document or Guidance to Read benchmarks results Output

### ISSUE THREAD

**Issue by hgdesai** [facebook/rocksdb#9449]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
Looking for guidance how to read results output for rocksdb benchmark
### Actual behavior
Looking for guidance how to read results output for rocksdb benchmark
### Steps to reproduce the behavior
Looking for guidance or documentation which explain result output of benchmarks from attached file.
[fillseq.txt](https://github.com/facebook/rocksdb/files/7945975/fillseq.txt)

**Comment by riversand963** [comment]
Could you refer to https://github.com/facebook/rocksdb/blob/6.29.fb/db/internal_stats.cc and take a look at the various `DumpXXStats()` functions? For the metrics that interest you, you can find how they are computed. It may be nice to have some code comments for some of the types defined in internal_stats.h to explain in more detail what they exactly stand for, but there are actually some comments for `struct CompactionStats`'s members. Hope they can help you.

Note that we use Github issues for bug reports/feature requests. For questions, we use the following:

> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

The original question asked here is also very broad, and I think specific questions can be answered more easily :)
