### ISSUE TITLE
Typo on variable name

### ISSUE THREAD

**Issue by theolivenbaum** [facebook/rocksdb#9488]
Minor minor issue, but I just noticed a typo on the C header (colummn instead of column) , which was breaking our [header to C# code gen](https://github.com/curiosity-ai/rocksdb-sharp/commit/de6b157ebf8d3cda2cf62f8159e6c6dc26ad28d5#diff-a6067276a613ed8b5ff021589a35966d840ebd2e3bd69e49087fc93725023004R348)

https://github.com/facebook/rocksdb/blob/42cca28ebb379177e6248b664eeab8475c3bebcb/include/rocksdb/c.h#L343

**Comment by riversand963** [comment]
Thanks @theolivenbaum for reporting. Would you like to contribute a PR to fix this?

**Comment by theolivenbaum** [comment]
@riversand963 done!
