### ISSUE TITLE
threadpool_imp.cc:146: rocksdb::ThreadPoolImpl::Impl::~Impl(): Assertion `bgthreads_.size() == 0U' failed.

### ISSUE THREAD

**Issue by lhsoft** [facebook/rocksdb#9509]
in func ThreadPoolImpl::Impl::JoinThreads
the exit_all_threads_ is set back to false when exiting
`void ThreadPoolImpl::Impl::JoinThreads(bool wait_for_jobs_to_complete) {

  std::unique_lock<std::mutex> lock(mu_);
  assert(!exit_all_threads_);

  wait_for_jobs_to_complete_ = wait_for_jobs_to_complete;
  exit_all_threads_ = true;
  // prevent threads from being recreated right after they're joined, in case
  // the user is concurrently submitting jobs.
  total_threads_limit_ = 0;

  lock.unlock();

  bgsignal_.notify_all();

  for (auto& th : bgthreads_) {
    th.join();
  }

  bgthreads_.clear();

  exit_all_threads_ = false;
  wait_for_jobs_to_complete_ = false;`

and the func ThreadPoolImpl::Impl::SetBackgroundThreadsInternal only renturn when exit_all_threads_  is true.

void ThreadPoolImpl::Impl::SetBackgroundThreadsInternal(int num,
  bool allow_reduce) {
  std::unique_lock<std::mutex> lock(mu_);
  if (exit_all_threads_) {
    lock.unlock();
    return;
  }
  if (num > total_threads_limit_ ||
      (num < total_threads_limit_ && allow_reduce)) {
    total_threads_limit_ = std::max(0, num);
    WakeUpAllThreads();
    StartBGThreads();
  }
}

it may cause the assert fail

**Comment by akankshamahajan15** [comment]
@lhsoft I didn't look deep into the APIs  I am not sure if you will get the  assertion because exit_all_threads_ is set false at the end of the function. Can you share the unit test/scenario where you are seeing this assertion? From the title it seems you are getting different assertion.

**Comment by lhsoft** [comment]
@akankshamahajan15 I meet the assertion error when I'm closing the db. Firstly I called the JoinThreads and then close db instance.
If we exit_all_threads_ is set false in JoinThreads, it may create new thread by calling SetBackgroundThreads after JoinThreads and will cause the assertion error when closing db instance。

**Comment by ajkr** [comment]
It does not appear supported to join all threads while the DB is still using the thread pool.

Why is such support needed? Also, are you using a custom `Env`? I did not see a public interface exposing our `Env`s' underlying `ThreadPool`s.

**Comment by lhsoft** [comment]
Yes, we are using custom Env which cause this problem and I have fixed it in out env Impl. 
Thanks for your replay, this issue can be closed.
