### ISSUE TITLE
Difficulty in understanding db_bench output for RocksDB/Programming beginners

### ISSUE THREAD

**Issue by hx235** [facebook/rocksdb#9530]
Posting for a user in RocksDB Developers Public facebook group.

For users with limited experience in programming/RocksDB, it could be challenging to understand db bench output (e.g, what each column means, what data is important). It might be a good doc enhancement if we have that.

TODO
- Dig into the code and find out what each keyword means
- Put them into a readable Github doc
- Invite some expert to write 1 or 2 examples of how they read and use db bench.

**Comment by hx235** [comment]
Hey dbbench experts! Please free to grab this task from me.

**Comment by ajkr** [comment]
See also #9445 #9449

**Comment by riversand963** [comment]
Discussed with @hx235 offline, and decided to close.

**Comment by bpan2020** [comment]
Sorry. Are there any examples to help understand the details of db_bench outputs?  Such as, 
1.  For a readrandom benchmark, why the result shows different performance in 'micros/op' and 'ops/sec'? Why isn't 'xxx micros/op' equal to '1000 000  ➗ xxx ops/sec'？

readrandom   :    1206.874 micros/op 26510 ops/sec;   18.0 MB/s (1291899 of 1490999 found)

2.  For a readwhilewrite benchmark, where can we find the separated read and write performance?
3.  A more detailed explanation to avoid misunderstand the output message.
