### ISSUE TITLE
Error building on SmartOS

### ISSUE THREAD

**Issue by benoitc** [facebook/rocksdb#956]
Hi,

Working on the erlang binding of rocksdb I tried to compile it on SmartOS but got the error reported here in leo-project/erocksdb#12 . Is there a recommended version of gcc/clang to build rocksdb?

 Any idea on how to compile rocksdb on old versions?

**Comment by igorcanadi** [comment]
RocksDB needs C++11 support, so any compiler with C++11 support should be OK. In gcc land this is 4.7 version.

**Comment by Licenser** [comment]
It seems not to be enough the bug mentioned uses gcc 4.9

**Comment by benoitc** [comment]
@igorcanadi yes the issue here is that some os shipped GCC with custom templates that allow the overloading. The comment here is more descriptive:

https://github.com/leo-project/erocksdb/issues/12#issuecomment-173125008

a reasonnable solution would be patching the rocksdb utility to be more strict with its c++ usage imo. Thoughts?

**Comment by dhruba** [comment]
@benoitc : just curious to know if any patches need to be done to rocksdb to make it compile on SmartOS. If you have such a patch, please consider contributing it back here..

**Comment by Licenser** [comment]
The following patch is what was missing to compile it on SmartOS: https://github.com/project-fifo/erocksdb/blob/r3/c_src/smartos.patch

**Comment by dhruba** [comment]
Is  std::emplace_hint not available in the C++ compiler on SmartOS?

**Comment by Licenser** [comment]
nope it was not :(

**Comment by Licenser** [comment]
That said I have no idea about c libraires so it's just pulling togehter work of @benoitc and google to get it to work

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
