### ISSUE TITLE
rocksdb jni fails on invalid instruction when popcnt instruction is missing

### ISSUE THREAD

**Issue by romanblachman** [facebook/rocksdb#9560]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

rocksdb fails to execute on some windows machine, and crashes with invalid instruction.
it appears that popcnt (popcount) instruction is missing on specific CPUs that causes this crash.

`Current thread (0x000000f6a9db0000): JavaThread "main" [_thread_in_native, id=16228, stack(0x000000f6a9420000,0x000000f6a9520000)]

Stack: [0x000000f6a9420000,0x000000f6a9520000], sp=0x000000f6a9519fa0, free space=999k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C [rocksdbjni-win64.dll+0x31985c]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j org.rocksdb.RocksDB.open(JLjava/lang/String;)J+0
j org.rocksdb.RocksDB.open(Lorg/rocksdb/Options;Ljava/lang/String;)Lorg/rocksdb/RocksDB;+9
j com.preempt.common.rocks.BaseRocksDaoImpl.init()V+257
...

siginfo: EXCEPTION_ILLEGAL_INSTRUCTION (0xc000001d)
`

**Comment by jxy-s** [comment]
After investigating the source of this. `BitSetToOne` makes the assumption that `popcnt` is supported on all cpus. `BitSetToOne` shouldn't make this assumption and check the feature bits of the cpu for the existence of `popcnt` support (`ECX` bit 23) and opt to use the fallback `BitsSetToOneFallback` when the feature isn't present. Or alternatively use a portable solution like `std::bitset::count` - however I suspect the reason for the implementation of `BitSetToOne` was a critical path that wished to avoid a possibly inefficient implementation of `std::bitset::count`.

**Comment by romanblachman** [comment]
@ajkr @akankshamahajan15 any updates here? I'm not sure why bug was removed, since rocksdb just crashes on virtual machines with CPUs that don't support the popcnt/popcount instruction.

**Comment by ajkr** [comment]
Anyways, do you mind sharing more details of your build? For example, are you using the Maven builds? Or if building with our Makefile, what flags do you set, like PORTABLE=1?

I prefer somebody on our team confirms it first before applying "bug" label as the description of that label is "Confirmed RocksDB bugs".

**Comment by jxy-s** [comment]
[`math.h`](https://github.com/facebook/rocksdb/blob/main/util/math.h#L142) makes a pretty clear assumption that `popcnt` is supported by the CPU.

From [MSDN](https://docs.microsoft.com/en-us/cpp/intrinsics/popcnt16-popcnt-popcnt64?view=msvc-170):
> If you run code that uses these intrinsics on hardware that doesn't support the popcnt instruction, the results are unpredictable.

**Comment by romanblachman** [comment]
Thank you @ajkr for pushing the fix! Do you know if this is expected to make the 7.0 major release? or 6.29.x release?

**Comment by ajkr** [comment]
No problem. Do you mind letting us know once you've validated the fix works for you? As @pdillinger mentioned in the PR review, we don't have the hardware to validate it, so we aren't completely certain.

I will include it in both 6.29 and 7.0. There should be new tags for both release series this week.

**Comment by romanblachman** [comment]
Is there a way for me to get a JNI JAR with the fix included that I can test with for the 6.29 release series? I'm happy to validate this as soon as possible.

**Comment by ajkr** [comment]
Oh, we only have them published to Maven after the tagging happens, unless you coordinate with @adamretter to get an early build. It's still helpful if you can verify after the Maven publishing, though that could take a few more days.

**Comment by adamretter** [comment]
@romanblachman You can easily build a snapshot yourself, `make rocksdbjavastatic` should do the trick.

**Comment by romanblachman** [comment]
@adamretter I am worried that my build won't originate the same output as the build system does, but I can try that.

**Comment by ajkr** [comment]
#9689 for tracking Maven release.

**Comment by romanblachman** [comment]
@ajkr Hi Andrew, any updates? It appears that none of the 6.29.x releases appear in maven central.
https://mvnrepository.com/artifact/org.rocksdb/rocksdbjni

**Comment by romanblachman** [comment]
I can confirm that the solution works with 6.29.4
