### ISSUE TITLE
Some Azure Container Instances for Linux fail due to lack of SMB hard link support

### ISSUE THREAD

**Issue by matthewvon** [facebook/rocksdb#9627]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

Checkpoints execute flawlessly in Linux when executed on Azure Container Instances.

### Actual behavior

Checkpoints fail with "operation not supported" due to missing hard link feature.  Going to assume same would happen with BackupEngine since documentation says backups based upon checkpoint.

Sample error line from our application:
 Unable to checkpoint column family __TXN__. Error: IO error: while link file to /var/opt/stardog/data/checkpoints/system_2022-01-20_12.00/__TXN__.tmp/000109.sst: /var/opt/stardog/data/000109.sst: Operation not supported

Azure container instance documentation that says only SMB mounts supported:
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-overview#persistent-storage

Azure documentation that says the SMB mounts do not support hard links (see Limitations section):
https://docs.microsoft.com/en-us/azure/storage/files/files-smb-protocol?tabs=azure-portal

### Steps to reproduce the behavior
Waste money on Azure Linux container.

Currently use of hard links is mandatory if destination is on the same mount.  Bad.  There needs to be a way to manually force use of copy.

So, there needs to be an options structure for checkpoints that says "bool move_files".  This would match similar option found in ImportColumnFamilyOptions (options.h).  And implies same bool needs to be in BackupEngineOptions ... so BackupEngine can set flag in its checkpoint calls.

**Comment by anand1976** [comment]
The checkpoint implementation automatically falls back to copying if hard linking fails. However, the Env/FileSystem needs to return Status::NotSupported() from the LinkFile() method. In this case, its returning Status::IOError. Cc @burtonli the maintainer of the Windows port.

**Comment by mrambacher** [comment]
> The checkpoint implementation automatically falls back to copying if hard linking fails. However, the Env/FileSystem needs to return Status::NotSupported() from the LinkFile() method. In this case, its returning Status::IOError. I'm not familiar with the Azure environment. Which Env is used?

I think the original post said this was an "Azure Linux" container, not Windows.  And that specific error message is printed by fs_posix.cc.  

@matthewvon Can you determine the exact error number that is translated to "Operation not supported" for Azure Linux?

**Comment by pdillinger** [comment]
Is it ENOTSUP?

**Comment by anand1976** [comment]
Yeah, you're right. That last part of the IOStatus error message comes from strerror, so it corresponds to ENOTSUP. I guess we can just check for it in LinkFile().

**Comment by pdillinger** [comment]
Assuming fixed with #9657
