### ISSUE TITLE
Rocksdb dll error

### ISSUE THREAD

**Issue by bbkot** [facebook/rocksdb#9641]
### Expected behavior
Closing rocksdb database without errors 

### Actual behavior
error raised from rocksdb Collumn_family destructor 

### Steps to reproduce the behavior
version latest 
executed from java using rockdsdbjni.
assertions failed in destructor. Skipping them cause jvm crash , or some weird errors. Guess it might be source of some weird crashes of jvm we observed , but couldn't identify the reason.

 

![image](https://user-images.githubusercontent.com/97723937/156108016-2e5ca924-468f-437f-9da7-5de71802cfb2.png)

**Comment by adamretter** [comment]
@bbkot Which version of RocksDB? Have you checked this - https://github.com/facebook/rocksdb/wiki/RocksJava-Basics#memory-management

**Comment by EvanSonnemans** [comment]
Guess it's not only a windows issue:
`
digita@ubuntu:~/ail-framework/ardb/deps/rocksdb-6.8.1$ make static_lib
$DEBUG_LEVEL is 0
  GEN      util/build_version.cc
  CC       db/column_family.o
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [Makefile:2117: db/column_family.o] Error 1
`

**Comment by adamretter** [comment]
@EvanSonnemans The problem described by @bbkot is a runtime issue.

However, the problem you have shown is a compile issue. I most usually see this when you don't have enough memory to compile the source code.

**Comment by EvanSonnemans** [comment]
> @EvanSonnemans The problem described by @bbkot is a runtime issue.
> 
> However, the problem you have shown is a compile issue. I most usually see this when you don't have enough memory to compile the source code.

Thank you for your information!

**Comment by rhubner** [comment]
@bbkot Thanks for reporting this issue, unfortunately I'm not able to reproduce it in any way. Do you think it will be possible to share your code?
