### ISSUE TITLE
Unsatisfied link error when creating statistics from Java api

### ISSUE THREAD

**Issue by pedrohjordao** [facebook/rocksdb#9667]
### Expected behavior

Statistics should be able to be created from Java

### Actual behavior

The following exception:

```
[2022/03/07 10:41:14] java.lang.UnsatisfiedLinkError: org.rocksdb.Statistics.newStatistics()J
[2022/03/07 10:41:14] at org.rocksdb.Statistics.newStatistics(Native Method)
[2022/03/07 10:41:14] at org.rocksdb.Statistics.<init>(Statistics.java:17)
[2022/03/07 10:41:14] at com.stackstate.servicemanager.RocksDBService.$anonfun$doStart$1(RocksDBService.scala:131)
[2022/03/07 10:41:14] at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
```

### Steps to reproduce the behavior

I have the following code (in scala):

```scala
 RocksDB.loadLibrary()
 val stats = new Statistics()
 stats.setStatsLevel(StatsLevel.EXCEPT_DETAILED_TIMERS)
 val opt = new Options().setCreateIfMissing(true).setStatistics(stats)
 RocksDB.open(opt, rocksDbInstance.toJava.getPath)
```

If i remove the statistics everything works as expected.

I'm using rocksdbjni version 6.28.2

**Comment by pedrohjordao** [comment]
Weirdly enough, if I change it to

```scala
      val opt = new Options().setCreateIfMissing(true)
      val stats = new Statistics()
      stats.setStatsLevel(StatsLevel.EXCEPT_DETAILED_TIMERS)
      opt.setStatistics(stats)
```

it works as expected

**Comment by nickrw** [comment]
I've encountered the same issue, with rocksjni 6.27.3, also from scala.

@pedrohjordao's suggested workaround also works for me (initialising Options before creating a new Statistics() instance)

**Comment by rhubner** [comment]
@pedrohjordao thank you for reporting this issue, unfortunately I'm not able to replicate it with your code.

I can replicate it only when I don't load the library.

Maybe if you can describe your environment where you are using RocksDB. If you are using IO monad or Apache Spark, or any other tool to run your code asynchronously or in a distributed environment, this can cause some out-of-order execution and native libraries may not be loaded in JVM yet.

**Comment by pedrohjordao** [comment]
I don't have access to that codebase anymore, but thank you for looking
into this
