### ISSUE TITLE
rocksdbjni 6.29.4 and 7.0.3 are missing from maven central

### ISSUE THREAD

**Issue by tianleios** [facebook/rocksdb#9689]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

**Comment by tianleios** [comment]
6.29.0 support m1 but i cannot find this in maven central

**Comment by tianleios** [comment]
quick！quick！

**Comment by cavallium** [comment]
Also 7.0.1

**Comment by ajkr** [comment]
I changed the title. There is currently no 6.29.4, but there will be once https://github.com/facebook/rocksdb/pull/9662#issuecomment-1062018209 is answered or we get tired of waiting. In any case it should be tagged before release to Maven.

**Comment by LuciferYang** [comment]
Is there an expected release time?

**Comment by ramvadiv** [comment]
@LuciferYang  - we don't have a firm ETA yet. Waiting for update/status from @adamretter  on this. Will try to provide an firm ETA soon.

**Comment by ajkr** [comment]
Changed 7.0.2 -> 7.0.3 in the title. We don't want to distribute [7.0.0, 7.0.2] further due to a severe bug that'll be fixed by #9736 and included in 7.0.3.

**Comment by ajkr** [comment]
Tagged v6.29.4 with latest fixes so there is something concrete to release  when this resumes. I know there was a claim that 6.29.fb contains the wrong commits, but we don't know what those are and only intend to make bug fix changes on that branch at this point.

**Comment by adamretter** [comment]
I have posted a status update here - https://github.com/facebook/rocksdb/pull/9662#issuecomment-1076243221

**Comment by adamretter** [comment]
@ajkr Should I release RocksJava 7.0.1 and 7.0.2 or should I wait for 7.0.3?

**Comment by jay-zhuang** [comment]
I think v7.0.3 is tagged: https://github.com/facebook/rocksdb/tree/v7.0.3

**Comment by stefan-zobel** [comment]
> I have now managed to get 6.29.4 released to Maven Central. It should appear there within the next 2 hours. I will now try and get version 7.0.1 out...

6.29.4 is on Maven Central. I just noticed that librocksdbjni-win64.dll is missing in rocksdbjni-6.29.4.jar.
Don't know if that is on purpose. It is in rocksdbjni-6.29.4-win64.jar, so personally, I'm fine with that.

**Comment by adamretter** [comment]
> Don't know if that is on purpose. 

Afraid not. It should have also been in `rocksdbjni-6.29.4.jar`

**Comment by adamretter** [comment]
@stefan-zobel I just released a 6.29.4.1 to Maven Central (should appear in their next sync window <2 hours).

**Comment by stefan-zobel** [comment]
> I just released a 6.29.4.1 to Maven Central

Thanks, it's there and it contains `librocksdbjni-win64.dll`

**Comment by adamretter** [comment]
I have now just release 7.0.3 as well to Maven Central. It should appear in their next sync window <2 hours.
