### ISSUE TITLE
Missing cache `strict_capacity_limit` from C API

### ISSUE THREAD

**Issue by guerinoni** [facebook/rocksdb#9707]
### Expected behavior
I'm working with C API (from rust) and my expectation was to create a `Cache` with `strict_capacity_limit` `true`.

### Actual behavior
The only `ctor` that C API offers is with default option (strict_capacity_limit=false)

Here my patch for add this new feature

[new_c_api.txt](https://github.com/facebook/rocksdb/files/8288373/new_c_api.txt)

**Comment by hx235** [comment]
@guerinoni Considering you have the patch already, would you be interested in opening a new PR or link one if you already did so? Thanks!

**Comment by guerinoni** [comment]
@hx235 thank you for reviewing this :)
Opened a PR
