### ISSUE TITLE
mac  m1  rocksdb create Object of  ‘org.rocksdb.Options’ to make error 

### ISSUE THREAD

**Issue by zhangxiatlq** [facebook/rocksdb#9721]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/v6/m7pdv5jx32j4x4chgx9g84lm0000gn/T/librocksdbjni1427334806259122995.jnilib: dlopen(/private/var/folders/v6/m7pdv5jx32j4x4chgx9g84lm0000gn/T/librocksdbjni1427334806259122995.jnilib, 0x0001): tried: '/private/var/folders/v6/m7pdv5jx32j4x4chgx9g84lm0000gn/T/librocksdbjni1427334806259122995.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni1427334806259122995.jnilib' (no such file)

**Comment by zhangxiatlq** [comment]
the program is true  when running in environment of windows

**Comment by vibbix** [comment]
Latest version of RocksJaba (6.28.2 as of now) isn't a universal binary, this is fixed in the upcoming 6.29.x release.

**Comment by ajkr** [comment]
Tracking issue for upcoming release - #9689

**Comment by jurmous** [comment]
RocksDB 6.29.4.1 has been released to maven.

**Comment by zhangxiatlq** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/26112021/160234073-f1f71d70-bd2c-465f-903e-bd362470042c.png">

**Comment by jurmous** [comment]
@zhangxiatlq I checked it on Maven Central directly and it works inside my project. It seems mvnrepository did not reindex Maven Central yet at the moment you checked it. It is now there.

<img width="736" alt="Screenshot 2022-03-26 at 12 25 23" src="https://user-images.githubusercontent.com/6823511/160237260-83d58cf7-4cad-45b0-ab45-c74b2ecb2704.png">

<img width="734" alt="Screenshot 2022-03-26 at 12 28 02" src="https://user-images.githubusercontent.com/6823511/160237326-40f7e138-ad4f-498e-a304-4e42f41b97c7.png">

**Comment by adamretter** [comment]
@zhangxiatlq I would not trust mvnrepository!

**Comment by zhangxiatlq** [comment]
I have found version 6.29.4.1 of rocksdb in mvn repository

**Comment by zhangxiatlq** [comment]
> @zhangxiatlq I would not trust mvnrepository!
why？？I think it very nice, but  Network instability

**Comment by adamretter** [comment]
> why？？I think it very nice, but Network instability

Because it is just an aggregation index. I think it is better to go to the source, so you can be certain where your artifacts are coming from and what they are. Also mvnrepository can be out of date at times.

**Comment by adamretter** [comment]
Also to note that RocksDB 7.0.3 is now available from Maven Central too.
