### ISSUE TITLE
Use a good seed when --seed is not set or set to 0

### ISSUE THREAD

**Issue by mdcallag** [facebook/rocksdb#9737]
I have wasted more than a few hours running db_bench benchmarks where --seed was not set and getting better than expected results because cache hit rates are great because multiple invocations of db_bench used the same value for --seed or did not set it, and then all used 0. The result is that all see the same sequence of keys.

A good way to avoid this is to set it to the equivalent of gettimeofday() when either --seed is not set or it is set to 0 (the default).

**Comment by ajkr** [comment]
Is it fixed so can be closed?

**Comment by mdcallag** [comment]
Fixed by https://github.com/facebook/rocksdb/pull/9740

**Comment by mdcallag** [comment]
> Is it fixed so can be closed?

yes
