### ISSUE TITLE
Assert constantly hit when using iter_start_ts

### ISSUE THREAD

**Issue by Coder666** [facebook/rocksdb#9761]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior

When enumerating keys with an iterator that has the lower bound timestamp set the keys should be able to be enumerated without hitting any asserts within ```saved_key_.GetInternalKey()```

In a Relase build this works fine and the expected keys are returned.  In a Debug build this assert is triggered which leads me to believe that there is some possible logic error with the assert in GetInternalKey .

GetInternalKey  is called from the following iterator function in rocksdb-6.29.4\db\db_iter.h:

```
Slice key() const override {
    assert(valid_);
    if (start_seqnum_ > 0 || timestamp_lb_) {
      return saved_key_.GetInternalKey();
    } else {
      const Slice ukey_and_ts = saved_key_.GetUserKey();
      return Slice(ukey_and_ts.data(), ukey_and_ts.size() - timestamp_size_);
    }
}
```

```
Slice GetInternalKey() const {
    assert(!IsUserKey());
    return Slice(key_, key_size_);
}
```

### Actual behavior

The following assert is hit, even though the data in key_ appears to be one of the keys previously inserted, i.e. it is a user key.

```
Slice GetInternalKey() const {
    assert(!IsUserKey());
    return Slice(key_, key_size_);
}
```

### Steps to reproduce the behavior

Add a UINT64 unix epoch timestamp in big endian byte order 

Create an iterator with read options:

timestamp => containing a > 0 timestamp
iter_start_ts=> containing a > 0 timestamp

where:

timestamp >= iter_start_ts

use a comparator that simply does a memcmp for all required overrides.

seek to arbitrary key

iterate over items

NOTE: we are using version 6.29.4

**Comment by riversand963** [comment]
Thanks @Coder666 for reporting.
I wonder whether there is any subtle difference between your code and our unit test https://github.com/facebook/rocksdb/blob/6.29.fb/db/db_with_timestamp_basic_test.cc#L1061:L1075, except comparators.

**Comment by Coder666** [comment]
ok so I uncommented the assert and ran our unit tests again.  The issue is actually ocurring only when iterating backwards

so:

pIter->Seek( ... );

```
if( pIter->Valid() )
{
    for( ;pIter->Valid(); pIter->Prev() )
    {
        pIter->key();   //assert
    }
}
```

**Comment by riversand963** [comment]
I see. I don't think iter_start_ts is supported in backward mode, and unfortunately, there is no comment to make this explicit. We should update the API comment.

**Comment by Coder666** [comment]
seems to work fine with the assert just commented out :)

**Comment by Coder666** [comment]
We have been using it for almost a month now like that.

**Comment by Coder666** [comment]
@riversand963 thanks for the update, much appreciated.
