### ISSUE TITLE
Implement ByteBuffer methods for Transaction in Java API

### ISSUE THREAD

**Issue by cavallium** [facebook/rocksdb#9776]
Transaction.getForUpdate, and other methods of Transaction, do not allow to use buffers, but only arrays.

**Comment by siying** [comment]
@cavallium are you interested in helping with it, assuming @adamretter would review the change?

**Comment by cavallium** [comment]
Sorry, I can't, I am currently very busy.

> @cavallium are you interested in helping with it, assuming @adamretter would review the change?

**Comment by aivinog1** [comment]
Hello! 
I think I can try to implement it. But I have a question: is it okay if I implement it just for one method and create a draft PR to review? Just to make sure, that I got the idea :)

**Comment by alanpaxton** [comment]
Just a note that https://github.com/facebook/rocksdb/pull/11019 addresses this. and is currently awaiting review.
