### ISSUE TITLE
CacheAlignedInstrumentedMutex padding array can be zero on 32bit

### ISSUE THREAD

**Issue by jxy-s** [facebook/rocksdb#9779]
### Expected behavior
The source should build.

### Actual behavior
The source does not build.

### Steps to reproduce the behavior
Building for Win32 produces a zero sized array in `CacheAlignedInstrumentedMutex` due to the a zero sized "padding" array.
 
 ```
\repos\rocksdb\monitoring\instrumented_mutex.h(57,8): warning C4200: nonstandard extension used: zero-sized array in struct/union
\repos\rocksdb\db\db_impl\db_impl.h(1195,27): error C2229: class 'rocksdb::DBImpl' has an illegal zero-sized array
 ```
 
I do not believe the explicit array padding is necessary, at least not for MSVC, as you defined the class to be aligned already with `ALIGN_AS(CACHE_LINE_SIZE)`.

For example, removing that padding array should be fine:
```
class ALIGN_AS(CACHE_LINE_SIZE) CacheAlignedInstrumentedMutex
    : public InstrumentedMutex {
  using InstrumentedMutex::InstrumentedMutex;
  //char padding[(CACHE_LINE_SIZE - sizeof(InstrumentedMutex) % CACHE_LINE_SIZE) %
  //             CACHE_LINE_SIZE] ROCKSDB_FIELD_UNUSED;
};
static_assert(sizeof(CacheAlignedInstrumentedMutex) % CACHE_LINE_SIZE == 0);
```

https://github.com/facebook/rocksdb/blame/9983eecdfbaf8e16f6ac2e22d1a16a5b37d8ac4d/monitoring/instrumented_mutex.h#L57

**Comment by siying** [comment]
> I do not believe the explicit array padding is necessary, at least not for MSVC, as you defined the class to be aligned already with `ALIGN_AS(CACHE_LINE_SIZE)`.

If my understanding is correct, this is not to align the beginning of the object, but to make sure the variable after the object won't sit in the same cacheline as the current mutex.

If it breaks the build if "char padding[0]" is used, it might indeed be a problem. @ajkr do you have any suggestion how we should fix it?

**Comment by ajkr** [comment]
> If my understanding is correct, this is not to align the beginning of the object, but to make sure the variable after the object won't sit in the same cacheline as the current mutex.

Right.

> If it breaks the build if "char padding[0]" is used, it might indeed be a problem. @ajkr do you have any suggestion how we should fix it?

I think we could heap allocate the CacheAlignedInstrumentedMutex (to solve C2229) and disable the warning (to solve C4200).

**Comment by ajkr** [comment]
> > If my understanding is correct, this is not to align the beginning of the object, but to make sure the variable after the object won't sit in the same cacheline as the current mutex.

> Right.

Actually, it is an artifact of an earlier approach and is no longer needed. Now that we have a struct we can rely on sizeof to include padding at the end (implied in the sizeof spec: [When applied to a class, the result is the number of bytes in an object of that class including any padding required for placing objects of that type in an array.](https://eel.is/c++draft/expr.sizeof#2.sentence-2))

Let me remove it.

**Comment by jxy-s** [comment]
kudos for taking care of this @ajkr - thank you!

**Comment by jxy-s** [comment]
kudos for taking care of this @ajkr - thank you!
