### ISSUE TITLE
facebook-rocksdb-v6.6.4.tar.gz wrong hash

### ISSUE THREAD

**Issue by davidtavarez** [facebook/rocksdb#9808]
### Expected behavior

Hash of file https://github.com/facebook/rocksdb/archive/v6.6.4.tar.gz should be: 22f5105244c55ca7030cc8d7ee06cb87f4afdfc85b3f44f7512a9c9c41c037c3b70fd291ec1b0df2553a93b770e11abc4ae2d7f984b2a0f1addd26d424c09539 
### Actual behavior

Hash of https://github.com/facebook/rocksdb/archive/v6.6.4.tar.gz vary.

### Steps to reproduce the behavior

Install rocksdb using vcpkg.

**Comment by jay-zhuang** [comment]
sounds like a problem of vcpkg. Other than java package, rocksdb team doesn't distribute other binaries.
and here is the link to 6.6.4 release: https://github.com/facebook/rocksdb/releases/tag/v6.6.4 with asset links.
