### ISSUE TITLE
Error reported when build rocksjava portable target

### ISSUE THREAD

**Issue by guoxiangCN** [facebook/rocksdb#9813]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
build success

### Actual behavior
1. failed since zlib's download url was invalid. (i fixed this) 
2. build java target when use docker, error like:
mkdir -p java/target
docker run --rm --name rocksdb_linux_x86-be --platform linux/386 --attach stdin --attach stdout --attach stderr --volume /Users/kuiper/.m2:/root/.m2:ro --volume `pwd`:/rocksdb-host:ro --volume /rocksdb-local-build --volume `pwd`/java/target:/rocksdb-java-target --env DEBUG_LEVEL=0 evolvedbinary/rocksjava:centos6_x86-be /rocksdb-host/java/crossbuild/docker-build-linux-centos.sh
Could not find devtoolset
make: *** [rocksdbjavastaticdockerx86] Error 1

### Steps to reproduce the behavior
make rocksdbjavastaticreleasedocker DISABLE_JEMALLOC=1

**Comment by adamretter** [comment]
Which version are you building?

**Comment by asad-awadia** [comment]
@adamretter happens on 6.22.1

**Comment by asad-awadia** [comment]
@ajkr

**Comment by asad-awadia** [comment]
@guoxiangCN how did you fix this?

**Comment by adamretter** [comment]
@asad-awadia As 6.22.1 is now quite old - It is likely the paths that the dependencies are downloaded from has changed. You may need to patch these in the Makefile for 6.22.1
