### ISSUE TITLE
`cache_index_and_filter_blocks=true` make `Get` slowdown on RAM

### ISSUE THREAD

**Issue by GOGOYAO** [facebook/rocksdb#9816]
> Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

I use rocksdb on ram with`cache_index_and_filter_blocks=true`. But it will slow down `get` performance.
The cpu is used heavily and cpu hotspot is on `crc`
![image](https://user-images.githubusercontent.com/18675094/162135751-e18fcdca-241b-4905-b855-d6aeaedd1eca.png)

If I set `cache_index_and_filter_blocks=true`, I will get a steady performance.

### Expected behavior
performance should be steady.
### Actual behavior
performance slow down.

**Comment by GOGOYAO** [comment]
This issue is mentioned at https://github.com/facebook/rocksdb/issues/3961 before.

My rocksdb version is 5.11.3. I wonder whether this issue is fixed after version 5.11.3

**Comment by ajkr** [comment]
@GOGOYAO What is the capacity of your block cache? It can be found in the LOG file or in your code where you create a block cache. LOG file example (capacity is 8MB):

```
  block_cache_options:
    capacity : 8388608
    num_shard_bits : 6
    strict_capacity_limit : 0
    memory_allocator : None
    high_pri_pool_ratio: 0.000
```

Also, what is the size of your filter data? You could get it exactly by calling `GetPropertiesOfAllTables()` and summing the TableProperties::filter_size, or provide an estimate.

My guess based on the profile is that your filter data is larger than your block cache. If that's not the case you might need to upgrade for us to investigate further.

**Comment by GOGOYAO** [comment]
> @GOGOYAO What is the capacity of your block cache? It can be found in the LOG file or in your code where you create a block cache. LOG file example (capacity is 8MB):
> 
> ```
>   block_cache_options:
>     capacity : 8388608
>     num_shard_bits : 6
>     strict_capacity_limit : 0
>     memory_allocator : None
>     high_pri_pool_ratio: 0.000
> ```
> 
> Also, what is the size of your filter data? You could get it exactly by calling `GetPropertiesOfAllTables()` and summing the TableProperties::filter_size, or provide an estimate.
> 
> My guess based on the profile is that your filter data is larger than your block cache. If that's not the case you might need to upgrade for us to investigate further.
```
2022/04/07-09:25:19.632478 7fa8bed77b40         Options.memtable_factory: SkipListFactory
2022/04/07-09:25:19.632479 7fa8bed77b40            Options.table_factory: BlockBasedTable
2022/04/07-09:25:19.632501 7fa8bed77b40            table_factory options:   flush_block_policy_factory: FlushBlockBySizePolicyFactory (0x3eec880)
  cache_index_and_filter_blocks: 1
  cache_index_and_filter_blocks_with_high_priority: 1
  pin_l0_filter_and_index_blocks_in_cache: 1
  index_type: 0
  hash_index_allow_collision: 1
  checksum: 1
  no_block_cache: 0
  block_cache: 0x51ab970
  block_cache_name: LRUCache
  block_cache_options:
    capacity : 1073741824
    num_shard_bits : 6
    strict_capacity_limit : 0
    high_pri_pool_ratio: 0.000
  block_cache_compressed: (nil)
  persistent_cache: (nil)
  block_size: 16384
  block_size_deviation: 10
  block_restart_interval: 16
  index_block_restart_interval: 1
  metadata_block_size: 4096
  partition_filters: 0
  use_delta_encoding: 1
  filter_policy: nullptr
  whole_key_filtering: 1
  verify_compression: 0
  read_amp_bytes_per_bit: 0
  format_version: 2
2022/04/07-09:25:19.632507 7fa8bed77b40        Options.write_buffer_size: 268435456
2022/04/07-09:25:19.632508 7fa8bed77b40  Options.max_write_buffer_number: 16
2022/04/07-09:25:19.632510 7fa8bed77b40          Options.compression: LZ4
2022/04/07-09:25:19.632511 7fa8bed77b40                  Options.bottommost_compression: Disabled
2022/04/07-09:25:19.632512 7fa8bed77b40       Options.prefix_extractor: nullptr
2022/04/07-09:25:19.632513 7fa8bed77b40   Options.memtable_insert_with_hint_prefix_extractor: nullptr
2022/04/07-09:25:19.632515 7fa8bed77b40             Options.num_levels: 7
2022/04/07-09:25:19.632516 7fa8bed77b40        Options.min_write_buffer_number_to_merge: 2
2022/04/07-09:25:19.632517 7fa8bed77b40     Options.max_write_buffer_number_to_maintain: 0
2022/04/07-09:25:19.632518 7fa8bed77b40            Options.compression_opts.window_bits: -14
2022/04/07-09:25:19.632520 7fa8bed77b40                  Options.compression_opts.level: -1
2022/04/07-09:25:19.632521 7fa8bed77b40               Options.compression_opts.strategy: 0
```
My cache capacity is 1 GB. The setting details is as stated above.

My value is small, about 200 bytes.  The compaction log is as below. 
```
2022/04/07-14:37:51.464179 7f2f8b1a2700 [xlib/deps/rocksdb_5_11_3/db/compaction_job.cc:1172] [data_cf] [JOB 42] Generated table #669827: 780383 keys, 268957297 bytes
2022/04/07-14:37:51.464208 7f2f8b1a2700 EVENT_LOG_v1 {"time_micros": 1649313471464196, "cf_name": "data_cf", "job": 42, "event": "table_file_creation", "file_number": 669827, "file_size": 268957297, "table_propertie
s": {"data_size": 268448557, "index_size": 984999, "filter_size": 0, "raw_key_size": 33891192, "raw_average_key_size": 43, "raw_value_size": 272134272, "raw_average_value_size": 348, "num_data_blocks": 17903, "num_e
ntries": 780383, "filter_policy_name": "rocksdb.BuiltinBloomFilter", "kDeletedKeys": "0", "kMergeOperands": "0"}}
```

**Comment by GOGOYAO** [comment]
Besides, I wonder what is the caveat of cache_index_and_filter_blocks. I did not see advise in wiki.

**Comment by ajkr** [comment]
Yeah the index+filter is not huge according to the logs.. But it still appears quite possible the total exceeds 1GB (particularly considering the logs showed files with average value size 800+ bytes, while you mentioned average value size is 200 bytes, which would mean the filters in other files are on average > 4x larger than shown here). If the total index+filter exceeds your block cache size, and you set cache_index_and_filter_blocks == true, there is expected to be thrashing (unless you have a workload with cold files almost never accessed).

**Comment by ajkr** [comment]
Here is one related wiki: [cache_index_and_filter_blocks](https://github.com/facebook/rocksdb/wiki/Block-Cache#caching-index-filter-and-compression-dictionary-blocks)

Also note newer RocksDB versions offer pinning options to prevent thrashing in more scenarios; see https://github.com/facebook/rocksdb/blob/49623f9c8e3c2803b6e1d992fc1687628a17491e/include/rocksdb/table.h#L58-L105

**Comment by GOGOYAO** [comment]
> 

thank you. I will test it.

**Comment by hx235** [comment]
@GOGOYAO Any other things you might need for this issue? I am closing this one but feel free to reopen if you do need more help.
