### ISSUE TITLE
Error running c_simple_example OSX

### ISSUE THREAD

**Issue by hackintoshrao** [facebook/rocksdb#982]
I'm new to rocksdb and I compiled the examples and tried running the the c_simple_example from the example folder, but it fails with the following error 
`Assertion failed: (!err), function main, file c_simple_example.c, line 28.
Abort trap: 6` 
What might be going wrong ? How to fix it ?

**Comment by igorcanadi** [comment]
Have you try printing out the error message you get (which is stored in `err`)?

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
