### ISSUE TITLE
mongorocks with rocksdb 5.7.3 lose data

### ISSUE THREAD

**Issue by q96456** [facebook/rocksdb#9822]
[[](>]([url](url)) Note: Please use Issues only for bug reports. For questions, discussions, feature requests, etc. post to dev group: https://groups.google.com/forum/#!forum/rocksdb or https://www.facebook.com/groups/rocksdb.dev

### Expected behavior
data integrity

### Actual behavior
data lost or invisible

I use mongorocks with rocksdb 5.7.3. Theoretically, primary and secondary data are approximately consistent. But I use "ldb" to scan primary's db has 4885827 entries, secondary has 10494720 entries.  Use "sst_dump" dump all sst files, primary get 10503389 entries ,secondary get 10494962 entries,approximately equal.I don't know what triggers this bug.

I can provide the primary and secondary data directory.
### Steps to reproduce the behavior
)

**Comment by hx235** [comment]
Hi @q96456, does the suggestion above work for you? I am closing this for now but feel free to re-open it if any more help is needed.

**Comment by q96456** [comment]
> Hi @q96456, does the suggestion above work for you? I am closing this for now but feel free to re-open it if any more help is needed.

It's maybe ok.,but I don't think I have to call DeleteRange or DeleteFilesInRange. I find the issue https://github.com/facebook/rocksdb/issues/5317 It looks similar to my problem. I can provide complete data catalog and logs, from creation to current. How do i submit it to you.

**Comment by ajkr** [comment]
I didn't check your version, but one safeguard against #5317 that we enable by default today is force_consistency_checks=true. In recent versions, at least, it checks that files do not overlap before installing them to the LSM (more details: http://rocksdb.org/blog/2021/05/26/online-validation.html).
