### ISSUE TITLE
Multiple crashes with rocksdbjni 7.0.4

### ISSUE THREAD

**Issue by cavallium** [facebook/rocksdb#9826]
Recently I found out that my server crashed multiple times on a rocksdb internal function during the last days, here are the crash logs:

[hs_err_pid711251.log](https://github.com/facebook/rocksdb/files/8457113/hs_err_pid711251.log)
[hs_err_pid712825.log](https://github.com/facebook/rocksdb/files/8457114/hs_err_pid712825.log)
[hs_err_pid3360734.log](https://github.com/facebook/rocksdb/files/8457115/hs_err_pid3360734.log)
[hs_err_pid3364158.log](https://github.com/facebook/rocksdb/files/8457116/hs_err_pid3364158.log)
[hs_err_pid3365424.log](https://github.com/facebook/rocksdb/files/8457117/hs_err_pid3365424.log)
[hs_err_pid3366682.log](https://github.com/facebook/rocksdb/files/8457118/hs_err_pid3366682.log)

**Comment by adamretter** [comment]
These all appear to be caused by Background Compaction - @jay-zhuang have you seen anything like this?

**Comment by jay-zhuang** [comment]
@cavallium is there any information could help to reproduce the issue?

**Comment by cavallium** [comment]
Unfortunately no, It seems to happen randomly.

**Comment by cavallium** [comment]
In the tests I just opened the databases and started writing a large quantity of key-value pairs for some minutes

**Comment by jay-zhuang** [comment]
> In the tests I just opened new databases and started writing a large quantity of key-value pairs for some minutes

Can you share the tests?

And run with a debug version should give us more information about the exception, can you try that: https://github.com/facebook/rocksdb/wiki/JNI-Debugging

**Comment by cavallium** [comment]
Unfortunately the test is based on a lot of private code that I can't share.
I'll try to write a test based only on rocksdbjni, thanks for the suggestion about the debug version

**Comment by adamretter** [comment]
@jay-zhuang I might be wrong, but the existing traces seem to indicate a problem in Rocks background compaction as opposed to a jni misuse issue. What are your thoughts?

**Comment by pdillinger** [comment]
The crash is likely in code from https://github.com/facebook/rocksdb/pull/9736. Any chance the process is shutting down when you see this crash (static destruction order)?

**Comment by cavallium** [comment]
I figured out the problem, there was a bug in my code that bypassed the close method (I was marking the database as closed before checking if it needed to be closed).

So this happened because my code didn't call db.close()
