### ISSUE TITLE
custom comparator incompatible with iterate_upper_bound?

### ISSUE THREAD

**Issue by petermattis** [facebook/rocksdb#983]
While trying to using `ReadOptions::iterate_upper_bound` in combination with a DB that uses a custom comparator (i.e. `ColumnFamilyOptions::comparator`) I discovered https://github.com/facebook/rocksdb/blob/master/db/db_iter.cc#L278:

```
      if (iterate_upper_bound_ != nullptr &&
          ikey.user_key.compare(*iterate_upper_bound_) >= 0) {
        break;
      }
```

`DBIter::FindNextUserEntryInternal` is using `rocksdb::Slice::compare` to compare the user key against the iteration upper bound. That doesn't seem to mesh with the presence of a custom comparator. Is there a reason for this or is it just a bug?

**Comment by igorcanadi** [comment]
Oh wow. Definitely a bug.

**Comment by petermattis** [comment]
I can send a PR to fix. Sending a PR with a new test might take a bit longer.

**Comment by igorcanadi** [comment]
Don't worry about a test.

**Comment by siying** [comment]
Thank you for discovering it!
