### ISSUE TITLE
confuse about memory usage of block cache

### ISSUE THREAD

**Issue by AndyShen105** [facebook/rocksdb#9847]
RocksDB:6.20.3

Background: There is a  task which I read data by multi-get and write some data meanwhile. And first, I set the option as follow:
bbt_opts.cache_index_and_filter_blocks = true;
bbt_opts.cache_index_and_filter_blocks_with_high_priority = true; 
max_open_files = -1
when the task finished, the memory usage of block cache is about 11GB;
Then I set cache_index_and_filter_blocks to false and restart this task, the memory usage of this process is about 5.1GB ; 
Why is the memory usage not 11GB when cache_index_and_filter_blocks=false?

**Comment by ajkr** [comment]
What's the configured capacity of your block cache? We do not proactively evict an index/filter block from block cache when its associated file is deleted. Whereas, with `cache_index_and_filter_blocks == false`, an index or filter will only occupy memory while its associated file is alive.
