### ISSUE TITLE
EXCEPTION_UNCAUGHT_CXX_EXCEPTION

### ISSUE THREAD

**Issue by nguyenm100** [facebook/rocksdb#9883]
using java rocksdb/java 7.1.1 on windows 10, java 17.  trying to build a triplestore atop rocksdb and loading a very large ttl file (88G) but have seen this write issue before on ttls a few gigs large.

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363) at pc=0x00007ffda0974f69, pid=29012, tid=7532
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [KERNELBASE.dll+0x34f69]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Xmx8G org.eclipse.rdf4j.console.Console $@

Host: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 8 cores, 15G,  Windows 10 , 64 bit Build 19041 (10.0.19041.1645)
Time: Wed Apr 20 23:16:46 2022 Eastern Daylight Time elapsed time: 6797.234403 seconds (0d 1h 53m 17s)

---------------  T H R E A D  ---------------

Current thread (0x00000196f460ead0):  JavaThread "main" [_thread_in_native, id=7532, stack(0x00000074a3b00000,0x00000074a3c00000)]

Stack: [0x00000074a3b00000,0x00000074a3c00000],  sp=0x00000074a3bfda50,  free space=1014k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [KERNELBASE.dll+0x34f69]
C  [VCRUNTIME140.dll+0x6220]
C  [librocksdbjni13512701107477641984.dll+0x502513]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 2506  org.rocksdb.RocksDB.write0(JJJ)V (0 bytes) @ 0x0000019687c13968 [0x0000019687c13920+0x0000000000000048]
J 2596 c2 com.msd.gin.halyard.sail.rocksdb.RocksDbSailConnection.addStatementInternal(Lorg/eclipse/rdf4j/model/Resource;Lorg/eclipse/rdf4j/model/IRI;Lorg/eclipse/rdf4j/model/Value;[Lorg/eclipse/rdf4j/model/Resource;J)V (162 bytes) @ 0x0000019687c90368 [0x0000019687c8fec0+0x00000000000004a8]
J 2608 c2 org.eclipse.rdf4j.repository.sail.SailRepositoryConnection.addWithoutCommit(Lorg/eclipse/rdf4j/model/Resource;Lorg/eclipse/rdf4j/model/IRI;Lorg/eclipse/rdf4j/model/Value;[Lorg/eclipse/rdf4j/model/Resource;)V (47 bytes) @ 0x0000019687ca3c24 [0x0000019687ca3ba0+0x0000000000000084]
J 2606 c2 org.eclipse.rdf4j.repository.util.RDFInserter.addStatement(Lorg/eclipse/rdf4j/model/Resource;Lorg/eclipse/rdf4j/model/IRI;Lorg/eclipse/rdf4j/model/Value;Lorg/eclipse/rdf4j/model/Resource;)V (48 bytes) @ 0x0000019687ca0f34 [0x0000019687ca0dc0+0x0000000000000174]
J 2572 c2 org.eclipse.rdf4j.rio.turtle.TurtleParser.parseStatement()V (138 bytes) @ 0x0000019687c4d6e4 [0x0000019687c4bd80+0x0000000000001964]
J 2632% c2 org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(Ljava/io/Reader;Ljava/lang/String;)V (121 bytes) @ 0x0000019687cb9564 [0x0000019687cb9460+0x0000000000000104]
j  org.eclipse.rdf4j.rio.turtle.TurtleParser.parse(Ljava/io/InputStream;Ljava/lang/String;)V+35
j  org.eclipse.rdf4j.repository.util.RDFLoader.loadInputStreamOrReader(Ljava/lang/Object;Ljava/lang/String;Lorg/eclipse/rdf4j/rio/RDFFormat;Lorg/eclipse/rdf4j/rio/RDFHandler;)V+61
j  org.eclipse.rdf4j.repository.util.RDFLoader.load(Ljava/io/InputStream;Ljava/lang/String;Lorg/eclipse/rdf4j/rio/RDFFormat;Lorg/eclipse/rdf4j/rio/RDFHandler;)V+70
j  org.eclipse.rdf4j.repository.util.RDFLoader.load(Ljava/io/File;Ljava/lang/String;Lorg/eclipse/rdf4j/rio/RDFFormat;Lorg/eclipse/rdf4j/rio/RDFHandler;)V+56
j  org.eclipse.rdf4j.repository.base.AbstractRepositoryConnection.add(Ljava/io/File;Ljava/lang/String;Lorg/eclipse/rdf4j/rio/RDFFormat;[Lorg/eclipse/rdf4j/model/Resource;)V+52
j  org.eclipse.rdf4j.console.command.Load.addData(Lorg/eclipse/rdf4j/repository/Repository;Ljava/lang/String;Ljava/lang/String;Ljava/net/URL;Ljava/io/File;)V+43
j  org.eclipse.rdf4j.console.command.Load.load(Lorg/eclipse/rdf4j/repository/Repository;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V+63
j  org.eclipse.rdf4j.console.command.Load.execute([Ljava/lang/String;)V+133
j  org.eclipse.rdf4j.console.Console.executeCommand(Ljava/lang/String;)Z+109
j  org.eclipse.rdf4j.console.Console.start()V+97
j  org.eclipse.rdf4j.console.Console.main([Ljava/lang/String;)V+82
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_UNCAUGHT_CXX_EXCEPTION (0xe06d7363), ExceptionInformation=0x0000000019930520 0x00000074a3bfdbb0 0x00007ffd588eaa80 0x00007ffd582b0000 

Register to memory mapping:

RIP=0x00007ffda0974f69 KERNELBASE.dll
RAX=0x4c73692367726562 is an unknown value
RBX=0x00007ffd588eaa80 librocksdbjni13512701107477641984.dll
RCX=0x616622203e657669 is an unknown value
RDX=0x683c5e5e2265736c is an unknown value
RSP=0x00000074a3bfda50 is pointing into the stack for thread: 0x00000196f460ead0
RBP=0x00000000000000be is an unknown value
RSI=0x00000074a3bfdbb0 is pointing into the stack for thread: 0x00000196f460ead0
RDI=0x0000000019930520 is an unknown value
R8 =0x707474683c0a2e20 is an unknown value
R9 =0x6d6f6f6c622f2f3a is an unknown value
R10=0x6172742367726562 is an unknown value
R11=0x615f6b72616d6564 is an unknown value
R12=0x00000074a3bfdd00 is pointing into the stack for thread: 0x00000196f460ead0
R13=0x000001978a75e710 points into unknown readable memory: 0x000001975c3265a0 | a0 65 32 5c 97 01 00 00
R14=0x000001978a75ddf0 points into unknown readable memory: 0x00007ffd58844ca0 | a0 4c 84 58 fd 7f 00 00
R15=0x00000000000000c8 is an unknown value


Registers:
RAX=0x4c73692367726562, RBX=0x00007ffd588eaa80, RCX=0x616622203e657669, RDX=0x683c5e5e2265736c
RSP=0x00000074a3bfda50, RBP=0x00000000000000be, RSI=0x00000074a3bfdbb0, RDI=0x0000000019930520
R8 =0x707474683c0a2e20, R9 =0x6d6f6f6c622f2f3a, R10=0x6172742367726562, R11=0x615f6b72616d6564
R12=0x00000074a3bfdd00, R13=0x000001978a75e710, R14=0x000001978a75ddf0, R15=0x00000000000000c8
RIP=0x00007ffda0974f69, EFLAGS=0x0000000000000206

Top of Stack: (sp=0x00000074a3bfda50)
0x00000074a3bfda50:   707474683c5e5e22 00007ffd588eaa80
0x00000074a3bfda60:   00000074a3bfdbb0 0000000000000000
0x00000074a3bfda70:   00000001e06d7363 0000000000000000
0x00000074a3bfda80:   00007ffda0974f69 0000019600000004
0x00000074a3bfda90:   0000000019930520 00000074a3bfdbb0
0x00000074a3bfdaa0:   00007ffd588eaa80 00007ffd582b0000
0x00000074a3bfdab0:   000001978a75e710 00000074a3bfdd00
0x00000074a3bfdac0:   00000074a3bfdbb0 00000000000000be
0x00000074a3bfdad0:   00000074a3bfdb50 00007ffda2dc4a5f
0x00000074a3bfdae0:   0000000019930520 23616d6500000000
0x00000074a3bfdaf0:   203e676e69727473 00007ffda2de07b0
0x00000074a3bfdb00:   00007ffd5891e000 00007ffd582b0000
0x00000074a3bfdb10:   00000fb0375601d0 00007ffda098986b
0x00000074a3bfdb20:   00007ffd588eaa80 00007ffd89796220
0x00000074a3bfdb30:   00004cf0f436bedd 6974617274736967
0x00000074a3bfdb40:   0000000000000008 00007ffda07639ce 

Instructions: (pc=0x00007ffda0974f69)
0x00007ffda0974e69:   d8 21 00 00 41 0f 44 c0 89 43 24 8b 41 18 89 43
0x00007ffda0974e79:   28 65 48 8b 04 25 60 00 00 00 48 8b 48 20 39 79
0x00007ffda0974e89:   08 7c 36 41 b9 40 00 00 00 48 89 7c 24 20 4c 8d
0x00007ffda0974e99:   44 24 30 48 83 c9 ff 41 8d 51 e5 48 ff 15 fd 9e
0x00007ffda0974ea9:   18 00 0f 1f 44 00 00 85 c0 0f 88 5f f1 06 00 81
0x00007ffda0974eb9:   7c 24 54 33 00 03 00 72 0f 48 8b 9c 24 80 00 00
0x00007ffda0974ec9:   00 48 83 c4 70 5f c3 cc 89 7b 2c eb ec cc cc cc
0x00007ffda0974ed9:   cc cc cc cc cc cc cc 65 48 8b 04 25 30 00 00 00
0x00007ffda0974ee9:   8b 40 68 c3 cc cc cc cc cc cc cc cc cc cc cc cc
0x00007ffda0974ef9:   cc cc cc cc cc cc cc 48 81 ec d8 00 00 00 48 8b
0x00007ffda0974f09:   05 62 5f 25 00 48 33 c4 48 89 84 24 c0 00 00 00
0x00007ffda0974f19:   48 83 64 24 28 00 48 8d 05 da ff ff ff 83 e2 01
0x00007ffda0974f29:   89 4c 24 20 89 54 24 24 48 89 44 24 30 4d 85 c9
0x00007ffda0974f39:   74 4c b8 0f 00 00 00 48 8d 4c 24 40 44 3b c0 49
0x00007ffda0974f49:   8b d1 44 0f 47 c0 44 89 44 24 38 49 c1 e0 03 e8
0x00007ffda0974f59:   fa d6 05 00 48 8d 4c 24 20 48 ff 15 1f 9f 18 00
0x00007ffda0974f69:   0f 1f 44 00 00 48 8b 8c 24 c0 00 00 00 48 33 cc
0x00007ffda0974f79:   e8 22 98 05 00 48 81 c4 d8 00 00 00 c3 cc 83 64
0x00007ffda0974f89:   24 38 00 eb cf cc cc cc cc cc cc cc cc cc cc cc
0x00007ffda0974f99:   cc cc cc cc cc cc cc 40 53 48 83 ec 30 48 8b d1
0x00007ffda0974fa9:   48 8d 4c 24 20 e8 e5 cc ff ff 85 c0 74 26 48 8b
0x00007ffda0974fb9:   4c 24 28 e8 8f 6f ff ff 48 8d 4c 24 20 8b d8 48
0x00007ffda0974fc9:   ff 15 11 97 18 00 0f 1f 44 00 00 8b c3 48 83 c4
0x00007ffda0974fd9:   30 5b c3 cc 83 c8 ff eb f4 cc cc cc cc cc cc cc
0x00007ffda0974fe9:   cc cc cc cc cc cc cc 48 8b c4 48 89 58 10 48 89
0x00007ffda0974ff9:   70 18 57 48 83 ec 60 0f 57 c0 0f 11 40 b8 48 8d
0x00007ffda0975009:   35 32 f7 18 00 33 db 48 85 c9 48 0f 45 f1 48 8b
0x00007ffda0975019:   d6 48 8d 48 c8 48 ff 15 43 9d 18 00 0f 1f 44 00
0x00007ffda0975029:   00 8b f8 89 44 24 70 85 c0 78 1f 41 b0 01 48 8d
0x00007ffda0975039:   54 24 30 48 8d 4c 24 20 48 ff 15 c0 96 18 00 0f
0x00007ffda0975049:   1f 44 00 00 8b f8 89 44 24 70 85 ff 0f 88 c9 ef
0x00007ffda0975059:   06 00 48 83 c8 ff 48 8b c8 48 ff c1 66 39 1c 4e 


Stack slot to memory mapping:
stack at sp + 0 slots: 0x707474683c5e5e22 is an unknown value
stack at sp + 1 slots: 0x00007ffd588eaa80 librocksdbjni13512701107477641984.dll
stack at sp + 2 slots: 0x00000074a3bfdbb0 is pointing into the stack for thread: 0x00000196f460ead0
stack at sp + 3 slots: 0x0 is NULL
stack at sp + 4 slots: 0x00000001e06d7363 is an unknown value
stack at sp + 5 slots: 0x0 is NULL
stack at sp + 6 slots: 0x00007ffda0974f69 KERNELBASE.dll
stack at sp + 7 slots: 0x0000019600000004 is an unknown value
```

**Comment by nguyenm100** [comment]
May have been around the time of a compaction.  Per above, crash around: 23:16:46

From LOG

2022/04/20-23:16:02.518062 345c [db\compaction\compaction_job.cc:2040] [default] [JOB 78] enerated table #660: 31249505 keys, 2299557453 bytes
2022/04/20-23:16:02.518878 345c EVENT_LOG_v1 {"time_micros": 1650510962518233, "cf_name": "default", "job": 78, "event": "table_file_creation", "file_number": 660, "file_size": 2299557453, "file_checksum": "", "file_checksum_func_name": "Unknown", "table_properties": {"data_size": 2242606959, "index_size": 29395243, "index_partitions": 0, "top_level_index_size": 0, "index_key_is_user_key": 1, "index_value_is_delta_encoded": 1, "filter_size": 39061893, "raw_key_size": 2156216145, "raw_average_key_size": 69, "raw_value_size": 2822180589, "raw_average_value_size": 90, "num_data_blocks": 1183392, "num_entries": 31249505, "num_filter_entries": 31249505, "num_deletions": 0, "num_merge_operands": 0, "num_range_deletions": 0, "format_version": 0, "fixed_key_len": 0, "filter_policy": "bloomfilter", "column_family_name": "default", "column_family_id": 0, "comparator": "leveldb.BytewiseComparator", "merge_operator": "nullptr", "prefix_extractor_name": "nullptr", "property_collectors": "[]", "compression": "Snappy", "compression_options": "window_bits=-14; level=32767; strategy=0; max_dict_bytes=0; zstd_max_train_bytes=0; enabled=0; max_dict_buffer_bytes=0; ", "creation_time": 1650468340, "oldest_key_time": 0, "file_creation_time": 1650510733, "slow_compression_estimated_data_size": 0, "fast_compression_estimated_data_size": 0, "db_id": "16e9bc64-c0be-11ec-90de-94e6f7929e0a", "db_session_id": "NT8UM0KABOQ7WPK28136", "orig_file_number": 660}}
2022/04/20-23:16:02.689346 345c [db\compaction\compaction_job.cc:2104] [default] [JOB 78] Compacted 1@1 + 2@2 files to L2 => 2299557453 bytes
2022/04/20-23:16:02.690374 345c [db\column_family.cc:1013] [default] Increasing compaction threads because of estimated pending compaction bytes 65807518750
2022/04/20-23:16:02.690446 345c (Original Log Time 2022/04/20-23:16:02.690315) [db\compaction\compaction_job.cc:969] [default] compacted to: files[5 15 5 2 0 0 0] max score 7.53, MB/sec: 11.5 rd, 10.0 wr, level 2, files in(1, 2) out(1 +0 blob) MB in(341.6, 2176.5 +0.0 blob) out(2193.0 +0.0 blob), read-write-amplify(13.8) write-amplify(6.4) OK, records in: 36653589, records dropped: 5404084 output_compression: Snappy
2022/04/20-23:16:02.690989 345c (Original Log Time 2022/04/20-23:16:02.690367) EVENT_LOG_v1 {"time_micros": 1650510962690333, "job": 78, "event": "compaction_finished", "compaction_time_micros": 229361383, "compaction_time_cpu_micros": 0, "output_level": 2, "num_output_files": 1, "total_output_size": 2299557453, "num_input_records": 36653589, "num_output_records": 31249505, "num_subcompactions": 1, "output_compression": "Snappy", "num_single_delete_mismatches": 0, "num_single_delete_fallthrough": 0, "lsm_state": [5, 15, 5, 2, 0, 0, 0]}
2022/04/20-23:16:02.694180 345c [file\delete_scheduler.cc:77] Deleted file /bb/data/cyclops/bbkg/000659.sst immediately, rate_bytes_per_sec 0, total_trash_size 0 max_trash_db_ratio 0.250000
2022/04/20-23:16:02.694235 345c EVENT_LOG_v1 {"time_micros": 1650510962694220, "job": 78, "event": "table_file_deletion", "file_number": 659}
2022/04/20-23:16:02.700366 345c [file\delete_scheduler.cc:77] Deleted file /bb/data/cyclops/bbkg/000605.sst immediately, rate_bytes_per_sec 0, total_trash_size 0 max_trash_db_ratio 0.250000
2022/04/20-23:16:02.700411 345c EVENT_LOG_v1 {"time_micros": 1650510962700399, "job": 78, "event": "table_file_deletion", "file_number": 605}
2022/04/20-23:16:02.710203 345c [file\delete_scheduler.cc:77] Deleted file /bb/data/cyclops/bbkg/000526.sst immediately, rate_bytes_per_sec 0, total_trash_size 0 max_trash_db_ratio 0.250000
2022/04/20-23:16:02.710256 345c EVENT_LOG_v1 {"time_micros": 1650510962710242, "job": 78, "event": "table_file_deletion", "file_number": 526}
2022/04/20-23:16:02.710372 345c [db\compaction\compaction_job.cc:2435] [default] [JOB 83] Compacting 1@1 + 1@2 files to L2, score 7.53
2022/04/20-23:16:02.710388 345c [db\compaction\compaction_job.cc:2439] [default] Compaction start summary: Base version 83 Base level 1, inputs: [651(528MB)], [608(5120MB)]
2022/04/20-23:16:02.710411 345c EVENT_LOG_v1 {"time_micros": 1650510962710397, "job": 83, "event": "compaction_started", "compaction_reason": "LevelMaxLevelSize", "files_L1": [651], "files_L2": [608], "score": 7.53153, "input_data_size": 5923103841}

**Comment by adamretter** [comment]
Is this exception coming from `KERNELBASE.dll` ? We need some idea of what the exception is to progress I think

**Comment by nguyenm100** [comment]
sorry am new to rocksdb wrt internals. this is the dump i get after kicking off the process and having it run for a few hours. could you advise on how to obtain better debugging info? tx

**Comment by adamretter** [comment]
@nguyenm100 I am afraid I am not sure. Maybe building a Debug version of RocksDB would help (but I am not certain), see:

https://github.com/facebook/rocksdb/wiki/Building-on-Windows

Specifically, changing `-DCMAKE_BUILD_TYPE=Release` and `/p:Configuration=Release` to `-DCMAKE_BUILD_TYPE=Debug` and `/p:Configuration=Debug`

**Comment by nguyenm100** [comment]
Ok thanks.  Revisiting my code, I noticed I'm not closing out my WriteBatch and WriteOptions objects which may be causing the problem.  Will dig around a little more on my side.

**Comment by nguyenm100** [comment]
problem does appear to be not releasing various rocksdb jni objects.

**Comment by HellsingAshen** [comment]
how to sovle it ?
