### ISSUE TITLE
Slice is missing virtual destructor

### ISSUE THREAD

**Issue by ronag** [facebook/rocksdb#9884]
The following will not work as expected without a virtual destructor:

```cpp
Slice* slice = new PinnableSlice();
delete slice;
```

**Comment by ajkr** [comment]
I tried it and it worked. You may want to specify what is expected to happen and what actually happened.

**Comment by ronag** [comment]
I don't think this should have question label?

**Comment by ajkr** [comment]
I think it should have the question label. The question is whether to add a virtual function to Slice thereby increasing an extremely frequently used class's size. My feeling is we should not, but I'll leave it as an open question in case there are differing opinions/alternative ideas.

**Comment by pdillinger** [comment]
My understanding of the consensus in C++ coding standards and analyzers is this:

* A class with virtual functions should have a virtual destructor
* Don't delete a derived class object through pointer to base class without virtual destructor

Or subsuming both of those:
* [Do not delete a polymorphic object without a virtual destructor](https://wiki.sei.cmu.edu/confluence/display/cplusplus/OOP52-CPP.+Do+not+delete+a+polymorphic+object+without+a+virtual+destructor)

Given these rules, the problem with your code example is your code example, not with the Slice API.
