### ISSUE TITLE
Question: How to get exclusive/inclusive bounds?

### ISSUE THREAD

**Issue by ronag** [facebook/rocksdb#9900]
The `iterate_upper_bound` and `iterate_lower_bound` are exclusive and inclusive respectively. Is there a smart way to also get the opposite somehow (i.e. inclusive and exclusive)?

**Comment by ronag** [comment]
I'm trying to simplify the following code https://github.com/nxtedition/rocks-level/blob/951441f9722bf87288945a7d15618f829fcf4ae6/binding.cc#L451-L633

**Comment by ajkr** [comment]
I don't think there is a way. If your key's immediate successor can be determined by appending a '\0', you could do that to the lower bound to make it exclusive, or do that to the upper bound to make it inclusive.
