### ISSUE TITLE
Iterator Seek & SeekForPrev does not consider bounds

### ISSUE THREAD

**Issue by ronag** [facebook/rocksdb#9904]
When seeking it's possible to seek out of bounds. Seems like the bounds are only applied for Next/Prev?

**Comment by ajkr** [comment]
I'd assume `Seek*()` should target a key within the bounds specified by `iterate_{lower,upper}_bound`. The bounds should apply to the internal iterations that happen during `Seek*()`, though. For example, if your `iterate_upper_bound` is "b", you `Seek("a")`, and the only key in the DB is "c", the iterator should not iterate to "c".

**Comment by ronag** [comment]
>  For example, if your iterate_upper_bound is "b", you Seek("a"), and the only key in the DB is "c", the iterator should not iterate to "c".

In this case I would assume the iterator is no longer valid. However, that is not what I am seeing.

**Comment by ronag** [comment]
```cpp
  void Seek(const std::string& target) {
    didSeek_ = true;

    if (
      (lower_bound_ && target.compare(*lower_bound_) >= 0) ||
      (upper_bound_ && target.compare(*upper_bound_) < 0)
    ) {
      // TODO (fix): Why is this required? Seek should handle it?
      iterator_->SeekToLast();
      if (iterator_->Valid()) {
        iterator_->Next();
      }
    } else if (reverse_) {
      iterator_->SeekForPrev(target);
    } else {
      iterator_->Seek(target);
    }
  }
```

**Comment by ronag** [comment]
Only SeekToFirst, SeekToLast and Next seem to consider the bounds :/

**Comment by adamretter** [comment]
@ronag If this is an Iterator on a WBWI, there are issues that I tried to solve here - https://github.com/facebook/rocksdb/pull/7214

That PR stalled, but I can try and get it restarted if it is the issue you are seeing?

**Comment by ronag** [comment]
> That PR stalled, but I can try and get it restarted if it is the issue you are seeing?

That would be great!

**Comment by ajkr** [comment]
> > For example, if your iterate_upper_bound is "b", you Seek("a"), and the only key in the DB is "c", the iterator should not iterate to "c".
> 
> In this case I would assume the iterator is no longer valid. However, that is not what I am seeing.

Is the code example intended to support this argument? If so, I don't understand. It appears to be handling the other case I mentioned: "I'd assume `Seek*()` should target a key within the bounds specified by `iterate_{lower,upper}_bound`." It does not appear to be preventing `Seek("a")` when `iterate_upper_bound` is "c".
