### ISSUE TITLE
env_ in java of Options might be messed

### ISSUE THREAD

**Issue by chris-yupeng** [facebook/rocksdb#9909]
In Options.java
```java
 public Options(final DBOptions dbOptions,
      final ColumnFamilyOptions columnFamilyOptions) {
    super(newOptions(dbOptions.nativeHandle_,
        columnFamilyOptions.nativeHandle_));
    env_ = Env.getDefault();
  }
```

The DBOptions here already has an env_ which could be implemented with some other os interfaces and very different from the Env.getDefault().  
When using this function to generate a new Options from DBOptions and ColumnFamilyOptions, shouldn't we use the env from the DBOptions to the Options java env_ here?

So I think the code should be like this:
```java
 public Options(final DBOptions dbOptions,
      final ColumnFamilyOptions columnFamilyOptions) {
    super(newOptions(dbOptions.nativeHandle_,
        columnFamilyOptions.nativeHandle_));
    env_ = dbOptions.getEnv();
  }
```

**Comment by adamretter** [comment]
Should it perhaps be:

```
env_ = dbOptions.getEnv() != null ? dbOptions.getEnv() : Env.getDefault();
```

We should check also when DbOptions can have a null `env_`, and also ask the question if it should ever have a null `env_` or if that is a bug?
