### ISSUE TITLE
IO error :rocksdb IO error : Resource temporarily unavailable

### ISSUE THREAD

**Issue by cnbscience** [facebook/rocksdb#991]
I hit this thing while trying run benchmark tests to read 3 billion hashes from my already existing database on ssd. The error was indicating the existence of LOCK file.  Could anyone please provide any insight on this and how to overcome this ?

Regards

**Comment by igorcanadi** [comment]
This means that you ran two benchmarks at the same time on the same rocksdb directory. Only one RocksDB process can access a single database.
