### ISSUE TITLE
drop ColumnFamily and delete it's files

### ISSUE THREAD

**Issue by superwood** [facebook/rocksdb#994]
Can i delete the   files of  ColumnFamily ? 

step1. 
  virtual Status DropColumnFamily(ColumnFamilyHandle\* column_family);

step2. 
   virtual void GetColumnFamilyMetaData(ColumnFamilyHandle\* column_family,ColumnFamilyMetaData\* metadata)

step3.
   DeleteFile(std::string name)

**Comment by gfosco** [comment]
Closing this via automation due to lack of activity.  If discussion is still needed here, please re-open or create a new/updated issue.
