### ISSUE TITLE
Calling function ReadOneLine does not return correctly

### ISSUE THREAD

**Issue by walterzhaoJR** [facebook/rocksdb#9959]
### version
* RocksDB version: 5.18.3

### Expected behavior
* After calling the function ReadOneLine, it can return correctly.

### Actual behavior
* When I use the function ReadOneLine in a loop, it does not return correctly on the last call to ReadOneLine

### Steps to reproduce the behavior
* I call ReadOneLine in a loop to call the file on disk
<img width="1059" alt="image" src="https://user-images.githubusercontent.com/22393698/167189753-4585681a-7227-452c-b731-4303180cc701.png">

* the file consists of 224 lines.

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/22393698/167190051-0d52f6ab-4ac7-4c7b-8b6e-d296ee50dd0b.png">

* when ReadOneLine was last called, there was no return.
<img width="1663" alt="image" src="https://user-images.githubusercontent.com/22393698/167191924-03df654c-d7c3-4501-bf03-5a5b5b44ec60.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/22393698/167192500-5e2e9d81-e629-4b85-9676-5232412f4991.png">

<img width="953" alt="image" src="https://user-images.githubusercontent.com/22393698/167192043-2a390e9a-a46b-45dd-9168-dbb95f4b86e5.png">

* some information
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/22393698/167192950-130f3a89-141e-4bd1-a15d-0fef4d075080.png">

<img width="1650" alt="image" src="https://user-images.githubusercontent.com/22393698/167193123-9f49e54f-72b3-48f3-b1f8-64faed4d824f.png">

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/22393698/167193245-da907ced-7e20-4f92-98f9-14d262887977.png">

<img width="1690" alt="image" src="https://user-images.githubusercontent.com/22393698/167193754-ea3395f0-a556-4bb1-9736-bb7cfed25caa.png">

<img width="1754" alt="image" src="https://user-images.githubusercontent.com/22393698/167193800-21d0ce06-1c14-47d6-a789-9115d368ad04.png">

the file is open
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/22393698/167195235-4bfd127b-e26e-4eec-846b-c2debeb2d42f.png">

**Comment by riversand963** [comment]
It looks like `rocksdb::ReadOneLine()` has been removed for sometime. Is it possible for you to try a newer RocksDB version?

**Comment by walterzhaoJR** [comment]
> It looks like `rocksdb::ReadOneLine()` has been removed for sometime. Is it possible for you to try a newer RocksDB version?

We may not be able to upgrade the new version for the time being.

**Comment by pdillinger** [comment]
Sorry, we can't help you with your own usage of a "confusing, awkward, and undocumented internal API" that has been long removed. https://github.com/facebook/rocksdb/pull/8026

**Comment by walterzhaoJR** [comment]
I see.Currently I temporarily circumvent it by adjusting the size of kBufferSize.
