### ISSUE TITLE
Best practices for implementing DB splitting

### ISSUE THREAD

**Issue by LucienXian** [facebook/rocksdb#9985]
## Problem Description

I'm trying to use rocksdb on hdfs or some object storage, like S3, etc(Like SST files and WAL will be placed on this), but I'm having some issues with how to implement DB instance splitting.

Suppose the current DB key range is `[0, 100]`. To split the DB into 2 small DBs according to certain rules, the 2 new DBs may be `[0, 50]` and `[51, 100]`. How should I do it in a better way?

In this process, it is necessary to split as quickly as possible to reduce the time of stop writing. All I can think of is to **share the sst files when splitting, the other files are quickly independent. When the new DB is opened, the WAL of the old DB is replayed, and the replay calls a DeleteRange to delete it.**

But here is a question, can we control sst files to be shared in two new DBs until both DBs no longer need to use shared sst files because of subsequent compaction

**Or is there a better solution?**

**Comment by riversand963** [comment]
Thanks @LucienXian 

Before discussion starts to diverge, I am closing this one. Please see #9828
