### ISSUE TITLE
Plugin header support missing in CMakeLists.txt

### ISSUE THREAD

**Issue by twblamer** [facebook/rocksdb#9987]
The Makefile processing for plugins allows you to set a ${PLUGIN}_HEADERS variable to add your plugin's headers to the RocksDB install. For example, see [rados.mk](https://github.com/riversand963/rocksdb-rados-env/blob/main/rados.mk) in the rocksdb-rados-env repo.

This functionality seems to be missing from CMakeLists.txt. The following patch seems to do the trick, but I could be missing something.

```patch
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -941,6 +941,9 @@ if ( ROCKSDB_PLUGINS )
         plugin/${plugin}/${src}
         PROPERTIES COMPILE_FLAGS "${${plugin}_COMPILE_FLAGS}")
     endforeach()
+    foreach (header ${${plugin}_HEADERS})
+      install(FILES plugin/${plugin}/${header} DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/plugin/${plugin}/")
+    endforeach()
     foreach (path ${${plugin}_INCLUDE_PATHS})
       include_directories(${path})
     endforeach()
```
Issue #6589 is a great explanation of why this is currently necessary when extending certain interfaces.

**Comment by mrambacher** [comment]
@twblamer Could you submit this as a PR?
